### PR TITLE
Cleanup keyword tests

### PR DESCRIPTION
**Pull request by DoctorKrolic**
- Abstracted tests of special type keywords (`bool`, `byte`, `char` etc.) into an inheritance hierarchy. This allows to save _multiple tons of code duplication_
- For whatever reason some special type keywords had their own tests, that could be applied to all of them, e.g. `string` had tests for absence in generic declarations (`class C<$$> { }` and so on). Extracted them to base type as well, so now all keywords run this test. This is not the only one, there were several of those
- There were 1 or 2 duplicate tests with different names. Removed them

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
We would not take this. These tests were explicitly written this way intentionally.  The point is to not share across the keywords, but have unique tests per keyword.

**Comment by DoctorKrolic** [comment]
This is only about keywords, that repsesent a type. Is is _very_ unlikely, that the language will change so that type keywords are used too differently. + I didn't take an opportunity to make a test for an individual keyword. + The savings are 10k lines, and it is _a lot_. Are you _sure_, that this is still not acceptable?

**Comment by CyrusNajmabadi** [comment]
Yes. The design of these tests is 100% intentional. And precisely because the previous impl (and tests) went the way you mention and were very costly because of that. 

Note: I have no problem flashing out the tests. If there are missing ones, feel free to add. But do not merge across the different keywords. Thanks!

**Comment by CyrusNajmabadi** [comment]
> The savings are 10k lines, and it is a lot. Are you sure, that this is still 

This is not shipping code though. So that's not a prime concern here.

**Comment by DoctorKrolic** [comment]
> were very costly because of that

I can hardly imagine how merged logic of similar handler tests can be more costly than ton of duplication, but that's up to you and the team, so closing

**Comment by CyrusNajmabadi** [comment]
There are times when the language does change. And needing to then break things apart, or parameterize, etc. becomes a tax.  

These tests are written. They basically incur no cost to keep in their current form. In a very real sense "if it ain't broken" applies here. Thanks!

**Pull request closed without merging**
