### PR TITLE
Address a number of IOperation issues for VB

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #22548 and #22229.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review IOperation fix.

**Review by mavasani — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
:shipit:

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review IOperation fix.

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review IOperation fix, need a second sign-off.

**Review by jcouv — APPROVED** [review]
LGTM

**Pull request merged**
