### PR TITLE
Add NewLine option support to formatter

### LINKED ISSUE #202: Formatter ignores NewLine option
Run the code below and notice that neither \r\n is removed, nor that \n is being used.

```c#
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.MSBuild;

namespace Formatting
{
    class Program
    {
        static void Main(string[] args)
        {

            var unformattedCode = @"using System\r\n; namespace HelloWorld{class Program{static void Main(string[]args){Console.WriteLine(""Hello,World!"");}}}";

            var cu = CSharpSyntaxTree.ParseText(unformattedCode);

            var normalizedNode = cu.GetRoot().NormalizeWhitespace("    ");
            var value = normalizedNode.GetText().ToString();
            if (value.IndexOf("\r\n") >= 0)
            {
                Console.WriteLine("normalized? nope");
            }

            var cw = MSBuildWorkspace.Create();
            var options = cw.Options
                .WithChangedOption(FormattingOptions.NewLine, LanguageNames.CSharp, "\n")
                .WithChangedOption(FormattingOptions.UseTabs, LanguageNames.CSharp, false)
                .WithChangedOption(FormattingOptions.TabSize, LanguageNames.CSharp, 8);

            var formattedNode = Formatter.Format(cu.GetRoot(), cw, options);
            value = formattedNode.GetText().ToString();
            if (value.IndexOf("\r\n") >= 0)
            {
                Console.WriteLine("formatted? nope");
            }

            Console.ReadLine();

        }
    }
}
```

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #202 

@basoundr @pilchie @heejaechang please review

### CODE REVIEW

**Comment by basoundr** [comment]
The change as such looks good. There are some complex cases. For eg, in [CurlyBraceCompletionSession](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.EditorFeatures/AutomaticCompletion/Sessions/CurlyBraceCompletionSession.cs,71), which returns [`NewLine`](http://referencesource.microsoft.com/#mscorlib/system/environment.cs,1169).

We might also have to replace those instances with what the user desires. This is just one example. There will be more cases.

**Comment by mattwar** [comment]
My change does not add any new formatter behavior.  It just changes the kinds of new lines it adds, when it adds them.

**Comment by mattwar** [comment]
@basoundr .. The caller is not expected to do trivia replacement. That's just the test forcing the new lines to be added.  Normally only specific conditions, like alignment, cause the formatter to add new lines.  For VB, it never does unless there is elastic trivia.

**Comment by heejaechang** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1: from me too, once the test failures are figured out.

**Pull request merged**
