### PR TITLE
Move to SHA2 code signing.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tag @dotnet/roslyn-infrastructure

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by jmarolf** [comment]
:+1:

**Comment by davkean** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/vsi/p3 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/322/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
@davkean Can i merge this in?  Any special rules about thsi sort of thing?

**Pull request merged**
