### PR TITLE
made CS0067 another build only error

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani  can you take a look?

**Comment by mavasani** [comment]
:+1:

**Comment by heejaechang** [comment]
@dotnet-bot retest linux please

**Comment by heejaechang** [comment]
@dotnet-bot retest win dbg unit please

**Comment by heejaechang** [comment]
@dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
#dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot test win unit32 please

**Comment by sharwell** [comment]
This is very frustrating, because it's extra difficult to use the suppression code fix to suppress build-only errors. Is there a reason why these warnings cannot be reported with IntelliSense?

**Comment by heejaechang** [comment]
@sharwell that is unfortunate limitation on our live compiler diagnostic analyzer. @mavasani to support those live, we need a bit of change on how our compiler diagnostic analyzer work.

**Comment by heejaechang** [comment]
added related issue #5957

**Comment by heejaechang** [comment]
@dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
test win unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Pull request merged**
