### PR TITLE
Skip a flaky test

### PR DESCRIPTION
**Pull request by gafter**

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Please let me know if you have any objection.

**Comment by davkean** [comment]
If the test is useful, then we should add a bug to reenable it and refer to that in the skip description. 
Otherwise, the test should be just deleted.

**Comment by gafter** [comment]
The test can be useful, mainly when run by hand, but I don't believe it is feasible to enable it for automated testing.

**Comment by AlekseyTs** [comment]
@TyOverby is working on fixing the flakiness. I believe there is an issue for that.

**Comment by TyOverby** [comment]
@gafter @AlekseyTs 

The fix (in its most recent form) is here: https://github.com/dotnet/roslyn/pull/7409

It operates by streaming pseudo-random characters rather than allocating a huge chunk of memory and filling it.  This means that there are no excess allocations.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by VSadov** [comment]
if it is flakey because of rare OOM. Could it just catch OOM?

**Comment by gafter** [comment]
@VSadov OOM was the symptom of the original problem it is testing for (producing millions of errors).

**Pull request merged**
