### PR TITLE
Do not try to convert interpolated string format specifiers into virtual chars

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/30378

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Yup yup.  Sorry this was missed.

**Comment by jinujoseph** [comment]
Approved to merge once green.

**Comment by dpoeschl** [comment]
For the `ubuntu_16_mono_debug_prtest` failure at https://ci.dot.net/job/dotnet_roslyn/job/dev16.0.x/job/ubuntu_16_mono_debug_prtest/128/consoleFull, several C# `CustomModifiersTests` are failing. Tagging @jaredpar @jcouv to look at these.

(Also Jenkins is taking forever on the rest.)

**Comment by jcouv** [comment]
I'll let @jaredpar respond, as those seem related to mono.

**Comment by jaredpar** [comment]
Mono failures look like this issue 

https://github.com/mono/mono/issues/10945

This was a regression that should only be occurring in Mono nightly while this branch is still on stable. @kg did stable just have a new release? If so the diff there may help you track down this bug.

**Comment by jaredpar** [comment]
@dpoeschl @CyrusNajmabadi can you copy these three lines into this PR? That will "fix" the failure on Mono. 

https://github.com/dotnet/roslyn/blob/master/build/scripts/tests.sh#L68

**Comment by dpoeschl** [comment]
@jaredpar I'd like to not reset the test runs if possible ([see my comment about Jenkins taking forever today](https://github.com/dotnet/roslyn/pull/30379#issuecomment-427999279)). Would you be okay with me doing this separately so the `dev16.0.x` branch gets updated but we don't slow this one down?

**Comment by jaredpar** [comment]
That’s fine. Note I’m pretty sure all Mono runs are going to start failing this way. Given the slowdown consider just pushing those three lines directly to get things moving. Sorry I’m not at my computer or I would take care of it.

**Comment by CyrusNajmabadi** [comment]
Thanks all!

**Pull request merged**
