### PR TITLE
Test revert of two recent WinForm perf PRs for RPS validation

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Please dont' revert #46391.  These are independent changes.

**Comment by JoeRobich** [comment]
> Please dont' revert #46391. These are independent changes.

@CyrusNajmabadi That PR has been identified as causing RPS regressions. 

Build with commits prior - https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/265000
Build with #46391 - https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/265017

**Comment by JoeRobich** [comment]
In order to restore code flow, we will merge this PR and revert these changes.

**Comment by JoeRobich** [comment]
Merging to get restore code flow. Prior to marking as ready for review CI was passing other than a flaky test.

**Pull request merged**
