### PR TITLE
Add IVT to Orchestrator UnitTests

### PR DESCRIPTION
**Pull request by drognanar**

### CODE REVIEW

**Comment by drognanar** [comment]
FYI @dotnet/roslyn-interactive

**Comment by shyamnamboodiripad** [comment]
Could you please describe why this is needed? i.e. What internal functionality do you wish to access?

**Comment by drognanar** [comment]
This change allows to access `IIncrementalAnalzyer`, `IIncrementalAnalyzerProvider`, `InvocationReasons` by the tests.

**Comment by shyamnamboodiripad** [comment]
:+1:

**Pull request merged**
