### PR TITLE
Simplify expression.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by balajikris** [comment]
do we have a regression test for the bug mentioned in comments that are now removed by your change?

**Comment by CyrusNajmabadi** [comment]
I don't think there's any change in behavior or problem here.  We just had some strangely parenthesized code that i was able to clean up.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Please take a look.  Thanks!

**Comment by dpoeschl** [comment]
:+1:

Balaji - This was just a long-standing "incorrect" parenthesization that Nikov noticed, but that could not cause any problems (explained in detail in the now-deleted comment). We allowed this conversation to grow in the comments way before we open-sourced, so @CyrusNajmabadi used his related bugfix as a chance to fix the parenthesization (with no behavioral change) and remove the commentversation(TM).

**Comment by balajikris** [comment]
Ah, alright.. thanks for explaining.. :+1:

**Pull request merged**
