### PR TITLE
Enabled automatic validation and fixing of braces in Roslyn solution

### PR DESCRIPTION
**Pull request by sharwell**
As noted by several contributors recently, we are manually enforcing a bracing style during code reviews that isn't automatically handled during the editing experience. This pull request enables automatic validation of brace placement during the coding cycle so this burden is no longer part of the pull request review effort.

/cc @jnm2

### CODE REVIEW

**Comment by sharwell** [comment]
:memo: As a demonstration of the overall quality of the code fix provided with these rules, keep the following in mind:

* 3810d91 is a single "Fix All in Solution" operation applied to the whole of Roslyn.sln. No changes were made to the result of the code fix operation (spacing / indentation / etc.).
* f5918eb is a single "Fix All in Solution" operation applied to the whole of Roslyn.sln, similar to the previous.
* The output was manually reviewed for bugs resulting from the application of the code fix. b5db1a4 is a correction to the one formatting bug found.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can we please have a second review of this style-fix-only change?

**Comment by jcouv** [comment]
Tagging @jaredpar, since he previously had concerns about pulling in stylecop.

**Comment by kuhlenh** [comment]
@sharwell -- Isn't this part of our desire to write a "formatting analyzer" that lets you know your formatting doesn't adhere to team style via .editorconfig? And then you can use Format Document (or our future code cleanup) to remedy?

**Pull request closed without merging**
