### PR TITLE
update Optimization data to 2.11.0-beta1-63312-03

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
tagging @dotnet/roslyn-infrastructure @jmarolf @ManishJayaswal 
can I sign off for the PR?

and @ManishJayaswal do I need ask mode template for this PR?

**Comment by heejaechang** [comment]
@ManishJayaswal can I check this in? we need this for tomorrow insertion so that we get VAL build with new Optimization data.

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by heejaechang** [comment]
@ManishJayaswal can I check this in? I dont think integration test failure has anything to do with this PR. it is failing in many PRs.

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by jasonmalinowski** [comment]
@heejaechang The optimization data package isn't really consumed on integration runs so that'd be safe to discard.

**Comment by heejaechang** [comment]
do we know why WIP never finish? @jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
Probably that bot being flaky. If we agree we want to merge this, we'll just merge and bypass it.

**Comment by ManishJayaswal** [comment]
@heejaechang - approved.

**Comment by heejaechang** [comment]
@jasonmalinowski I dont think I have permission to bypass it?

**Comment by heejaechang** [comment]
@jasonmalinowski thank you!

**Pull request merged**
