### PR TITLE
Enable Emit unit-tests for C# and VB compilers in CIBuild.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #2375.

### CODE REVIEW

**Comment by amcasey** [comment]
:+1:

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Pull request merged**
