### PR TITLE
Fix argument for async indentation services.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Tagging @dotnet/roslyn-ide @jramsay

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by jramsay** [comment]
👍

**Comment by Pilchie** [comment]
Gee - it sure would have been nice if there was a test that caught this break...

**Comment by jasonmalinowski** [comment]
image

But :+1: otherwise. :-)

**Pull request merged**
