### PR TITLE
Change code blocks to inline code to make the paragraph read nicer

### PR DESCRIPTION
**Pull request by mikkelbu**
Relates to dotnet/roslyn-api-docs#43

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
How does this look in the IDE before/after this change?

**Comment by Neme12** [comment]
>  jcouv (Julien Couvreur) added Area-IDE  Community  

@jcouv It looks like this is in compiler code.

**Comment by jcouv** [comment]
Corrected the label. Thanks

**Comment by CyrusNajmabadi** [comment]
Note: i think this should get some IDE eyes.  I'm curious about this new code-blcok style, and how it will appear to customers in the IDE.

**Comment by mikkelbu** [comment]
Actually, I'm not sure I thought it through. I was so focus on dotnet/roslyn-api-docs that I did not think about how it would look in the editor. Perhaps a better approach would be to translate `<code>` into `` ` `` when extracting the documentation for the web. /cc @BillWagner

**Comment by sharwell** [comment]
@mikkelbu If you would like to be able to use backticks in the future, please consider commenting and/or adding :+1: in dotnet/csharplang#891 as a small show of additional support.

**Comment by sharwell** [comment]
:memo: I filed #26676 to fix the rest of these after we get this merged

**Comment by sharwell** [comment]
Thanks @mikkelbu !

**Pull request merged**
