### PR TITLE
Support SetType/AddParameter for DeclareStatement in VB

### LINKED ISSUE #1873: Some VisualBasicCodeModelService APIs not handling Declare Function and Sub
`VisualBasicCodeModelService` does not handle Declare Function and Sub in the following APIs
1. `SetType`
2. `InsertParameterIntoContainer`
3. `GetFunctionExtender`

@DustinCampbell @carlos-j-quintero Are these scenarios that we should handle?

### PR DESCRIPTION
**Pull request by basoundr**
Fix #1873 Add support for SetType & AddParameter in Declare Sub and
Function

### CODE REVIEW

**Comment by basoundr** [comment]
Reviewers: @Pilchie @DustinCampbell @jasonmalinowski @dpoeschl @balajikris @rchande @brettfo @jmarolf

**Comment by basoundr** [comment]
AddParameter was working as expected so I have added some testcases. I fixed SetType and added tests to prevent regression.

**Comment by Pilchie** [comment]
:+1:

**Comment by dpoeschl** [comment]
LGTM

**Pull request merged**
