### PR TITLE
Fix code analysis messages in command-line parser

### PR DESCRIPTION
**Pull request by davkean**
Some quick cleanup in command-line parser.

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet/roslyn-compiler Going to merge thsi in tomorrow; please tell if you have any concerns.

**Comment by RikkiGibson** [comment]
Is this just cleanup or are there observable behavior changes from this PR?

**Comment by davkean** [comment]
@RikkiGibson There is/should be no obserable behavior changes.

**Comment by AlekseyTs** [comment]
@davkean 

>  Going to merge thsi in tomorrow; please tell if you have any concerns.

For changes under Compilers, a PR has to have two sign-off from the compiler team before it can be merged. Please follow the policy.

**Pull request merged**
