### PR TITLE
Update paths in `.vscode/launch.json` due to TFM changes

### PR DESCRIPTION
**Pull request by Youssef1313**
e.g:

https://github.com/dotnet/roslyn/blob/3b32fc36ec4c2a81457d90f965c89c5b6fc37082/src/Tools/BuildValidator/BuildValidator.csproj#L7

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
@333fred Since you use VS Code for working on Roslyn, can you check if those changes are correct? Thanks!

**Review by 333fred — APPROVED** [review]
You can tell how often I use these tasks.

**Comment by 333fred** [comment]
@RikkiGibson for a second review

**Review by RikkiGibson — APPROVED** [review]

**Comment by Youssef1313** [comment]
@333fred @RikkiGibson GitHub is stuck auto-merging this.

image

Can you manually merge? Thanks!

**Pull request merged**
