### PR TITLE
Merge microupdate into dev15-preview-4

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from microupdate into dev15-preview-4.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-microupdate-into-dev15-preview-420160727-150134
git reset --hard upstream/dev15-preview-4
git merge upstream/microupdate
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-microupdate-into-dev15-preview-420160727-150134 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by Pilchie** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/dev15-preview-4/job/windows_debug_unit64_prtest/44/
// Retest reason: Hit a build race in VisualStudioInteractiveComponents.csproj

**Comment by Pilchie** [comment]
:+1:

**Comment by jcouv** [comment]
@MattGertz Please approve merging microupdate fix into preview 4 branch here as well.

**Pull request merged**
