### PR TITLE
Require .NET 4.6 min runtime in app.config

### LINKED ISSUE #17908: Faulting csc.exe (2.0.0.61501) on Windows Server 2012 without latest .Net Framework 4.6.2
Hi,
  I recently upgraded our ASP.Net MVC 4.5.2 project with the latest 2.0.1 roslyn compiler version but, after publishing on our production servers, the app crashes with the error:
```
Faulting application name: csc.exe, version: 2.0.0.61501, time stamp: 0xa16928ca
Faulting module name: KERNELBASE.dll, version: 6.3.9600.18340, time stamp: 0x57366075
Exception code: 0xe0434352
Fault offset: 0x0000000000008a5c
Faulting process id: 0x1550
Faulting application start time: 0x01d29e2fc5c1f876
Faulting application path: C:\www\****\bin\roslyn\csc.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 037cd29d-0a23-11e7-80d6-bc764e093275
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Application: csc.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.MissingMethodException
Stack:
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(System.String[])
```
Our servers had already installed the 4.5.2 framework but I needed to upgrade it to the latest one.

Thanks
Marco

### PR DESCRIPTION
**Pull request by agocke**
Fixes #17908

### CODE REVIEW

**Comment by agocke** [comment]
cc @jaredpar @jcouv @dotnet/roslyn-compiler For review

**Comment by jaredpar** [comment]
CC @tmat do we need to make a similar change for csi, vbi?

**Comment by tmat** [comment]
Yup, csi and vbi should be the same.

**Comment by agocke** [comment]
@tmat Added.

**Pull request merged**
