### PR TITLE
Add CoreCLR xunit support

### PR DESCRIPTION
**Pull request by agocke**
This adds a new convention for tests: if you name your test DLL *.Core.UnitTests.dll that means it is a CoreCLR-compatible unit test and could be run under XUnit running on CoreCLR.

The scripting tests assemblies have already been switched to use this naming convention. Right now actual running is disabled to unit test failures, but once the failures are fixed running can be switched on by removing the commented out section in BuildAndTest.proj.

### CODE REVIEW

**Comment by agocke** [comment]
@dotnet/roslyn-compiler @tmat Please review

**Comment by jaredpar** [comment]
Please hold off on submitting this until I can merge my xunit changes.  It looks like we'regoing to conflict and I'm a bit time boxed on getting the 2.1 upgrade done.

**Comment by agocke** [comment]
@jaredpar Go for it

**Comment by davkean** [comment]
We ready to revive this?

**Comment by agocke** [comment]
@davkean needs to be merged, has lots of conflicts with Jareds pr.

**Pull request closed without merging**
