### PR TITLE
Adding 'await' to ERR_IllegalStatement message

### LINKED ISSUE #27180: CS0201 (Only assignment, call....) doesn't mention await
The old compiler used to report:
Only assignment, call, increment, decrement, **await**, and new object expressions can be used as a statement

Roslyn:
Only assignment, call, increment, decrement, and new object expressions can be used as a statement

reported here: https://stackoverflow.com/questions/50514829/why-a-declaration-doesnt-give-a-cs0201-compiler-error/50515400#answer-50515400

### PR DESCRIPTION
**Pull request by Neme12**
fixes #27180

### CODE REVIEW

**Comment by Neme12** [comment]
@jcouv can you tag this as Area-Compilers please?

**Comment by jcouv** [comment]
@jaredpar for ask-mode approval for 15.8. Thanks

**Comment by jaredpar** [comment]
approved

**Comment by Neme12** [comment]
@jcouv good to merge?

**Pull request merged**
