### PR TITLE
Update azure-pipelines-richnav.yml

### PR DESCRIPTION
**Pull request by RikkiGibson**
@jepetty @xuachen for review.

### CODE REVIEW

**Review by jepetty — APPROVED** [review]
LGTM!

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-infrastructure for review

**Comment by dibarbet** [comment]
I see the richnav-CI running in the checks.  Will failures in that leg potentially block automerges (and is that what we want)?

**Comment by RikkiGibson** [comment]
> Will failures in that leg potentially block automerges (and is that what we want)?

The failures will block automerges currently but
1. we already need a long term solution for auto-merging in the face of optional check failures
2. the [pass rate on the richnav-CI](https://dev.azure.com/dnceng/public/_build?definitionId=851&view=ms.vss-pipelineanalytics-web.new-build-definition-pipeline-analytics-view-cardmetrics) seems pretty high--95% in past 14 days, and most of the remaining 5% likely due to the AzDO outage this morning. Definitely compares favorably to the ~70% [pass rate for roslyn-ci](https://dev.azure.com/dnceng/public/_build?definitionId=15&view=ms.vss-pipelineanalytics-web.new-build-definition-pipeline-analytics-view-cardmetrics).

As a small optimization, it could be reasonable to prevent the job from running when the PR branch matches the pattern `merges/*`.

**Review by dibarbet — APPROVED** [review]
Fair enough.  :shipit:

**Comment by RikkiGibson** [comment]
Test failures are due to an issue in the base branch.

**Comment by RikkiGibson** [comment]
The CI run affected by this change is passing, so will merge.

**Pull request merged**
