### PR TITLE
Move to segmented collections to avoid LOH allocations

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Addresses about 10MB of allocs we're placing in the LOH:

image

### CODE REVIEW

**Review by genlu — APPROVED** [review]
:shipit:

**Comment by ToddGrun** [comment]
Doesn't the Entry item in your image above come from _set in AddClassification?

**Comment by ToddGrun** [comment]
> Doesn't the Entry item in your image above come from _set in AddClassification?

Could you use SegmentedHashSet for it?

**Comment by CyrusNajmabadi** [comment]
@ToddGrun yup. Good catch. This fix only gets half of the above

**Review by ToddGrun — APPROVED** [review]
:shipit:

**Pull request merged**
