### PR TITLE
deal with cases where item in table control is not associated with any project or document

### PR DESCRIPTION
**Pull request by heejaechang**
also unit tests are added.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @basoundr can you take a look?

**Comment by mavasani** [comment]
:+1:

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Comment by heejaechang** [comment]
@dotnet-bot retest win please

**Comment by heejaechang** [comment]
@dotnet-bot retest win_dbg_eta please

**Comment by heejaechang** [comment]
@dotnet-bot retest dotnet_roslyn_prtest_win_dbg_eta please

**Comment by heejaechang** [comment]
@dotnet-bot retest test please

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Pull request merged**
