### PR TITLE
Remove unnecessary partial keyword

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
in general, i would prefer to not take one-off tweaks like this.  If you want to go through and clean up a particular project so that it doesn't have unnecessary 'partial', i would be more amenable.  that way we could take care of a large swath at once, instead of just having a slow trickle of PRs to do these changes.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi, does having an analyzer for that and dogfooding it in Roslyn makes more sense?
Should the analyzer go here or in roslyn-analyzers repo?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi, does having an analyzer for that and dogfooding it in Roslyn makes more sense?
Should the analyzer go here or in roslyn-analyzers repo?

Honestly, given the zero issues here in the past, i would say this isn't really a style we are trying to enforce.  So my preference would be to not do anything.  However, as mentioned above, i am amenable to a bulk change here just so it is done once and not through a series of PRs.

**Comment by jinujoseph** [comment]
Based on @CyrusNajmabadi comments here, Closing this out @Youssef1313 
Feel free to ping if you think otherwise

**Pull request closed without merging**
