### PR TITLE
Update VirtualTreePoint.cs

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Fix for ##11574
Escape the braces withing the built `String Format` text.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Could we switch this over to using an interpolated string, to prevent this bug from accidentally being reintroduced?

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski 
I've changed it over, but you still require to escape the braces.

**Comment by jasonmalinowski** [comment]
Indeed, but at least we have the compiler verifying it instead of nothing verifying it. This looks good to me, anybody else from @dotnet/roslyn-ide want to take a look? This is really tiny.

**Comment by Pilchie** [comment]
:+1:

Thanks @AdamSpeight2008!

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
:+1:

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski 
The compiler checks this?

**Comment by jasonmalinowski** [comment]
@AdamSpeight2008: of course. If you had a { you forgot to convert to a {{, the parser will complain.

**Comment by jasonmalinowski** [comment]
Thanks @AdamSpeight2008 for the fix!

**Pull request merged**
