### PR TITLE
Merge Extension GetEnumerator into master

### PR DESCRIPTION
**Pull request by 333fred**
This implements the extension GetEnumerator feature, done by @YairHalberstadt. All commits in this PR have been individually reviewed. @jaredpar for approval.

Smoke Test results:
Signed Build (only MS accessible): https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3950241&view=results
Passing Test Insertion (only MS accessible): https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/265683

🦔

### CODE REVIEW

**Comment by RikkiGibson** [comment]
This is ready to go in once CI passes.

**Comment by 333fred** [comment]
Thanks @YairHalberstadt! And congrats on contributing a language feature!

**Comment by jcouv** [comment]
Thanks much @YairHalberstadt. Glad the feature is making it into C# 9 🎉

**Comment by YairHalberstadt** [comment]
Thanks for all your help and time! Glad this made it to C# 9

**Pull request merged**
