### PR TITLE
Update corefx dependencies

### PR DESCRIPTION
**Pull request by AArnott**
- System.Runtime.CompilerServices.Unsafe to 4.7.1
- System.Threading.Tasks.Extensions to 4.5.4
- System.Threading.Tasks.Dataflow to 4.11.1
- Microsoft.Bcl.AsyncInterfaces to 1.1.1

This brings them up to the latest stable version on nuget.org so we can keep updating other dependencies in VS without fear that they need a dependency that's newer than what VS ships.

🦔

### CODE REVIEW

**Comment by jaredpar** [comment]
@RikkiGibson FYI on this PR. Feel free to dismiss my block once we get the insertion issues fixed and are ready to ingest.

**Comment by AArnott** [comment]
Thanks, @jaredpar. This change is _not_ urgent, so please proceed as you suggest.

**Comment by AArnott** [comment]
@jaredpar Would you prefer I hold off on [this PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/265216) as well till Roslyn gets inserted properly?

**Comment by jaredpar** [comment]
@AArnott 

> Would you prefer I hold off on this PR as well till Roslyn gets inserted properly?

Will let @RikkiGibson comment definitively here since he's helping track all this down. But likely yes we would really appreciate that. :smile:

**Comment by AArnott** [comment]
@RikkiGibson  Can we proceed with this PR now that Roslyn's insertions into VS are apparently rolling again?

**Comment by RikkiGibson** [comment]
I'm happy to take this change in the near future, however 2 things are blocking:

1. We are snapping for preview2 tomorrow (Tuesday) at EOD. It will be much easier for us to ingest a risky change after that time.
2. There is a failing test across all the desktop runs of this PR. https://dev.azure.com/dnceng/public/_build/results?buildId=756560&view=ms.vss-test-web.build-test-results-tab&runId=23486458&resultId=186079&paneView=debug It's hard to tell what the issue is in the failure, so I will rerun the tests as a first resort.

**Comment by RikkiGibson** [comment]
I also queued a validation PR for this change https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/266491

**Comment by AArnott** [comment]
Given the failures here, and the new [optprof bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1171579) that started once I merged [this PR](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/265216) to VS, I pushed more to *this* PR to bring more corefx assemblies in dotnet/roslyn up to match the assemblies I've upgraded in VS.

**Comment by RikkiGibson** [comment]
@jaredpar the failure in TestReferenceDirective is not due to flakiness. Does anything come to mind as to what we should do to fix the test?

```
Expected:
Microsoft (R) Visual Basic Interactive Compiler version 3.8.0-ci ()
Copyright (C) Microsoft Corporation. All rights reserved.
Type ""#help"" for more information.
> #r ""F:\workspace\_work\1\sartifacts	mp\Debug\RoslynTests\1.dllc29d247a-15d0-4e7f-b8d1-42106eddcb35.tmp""
> ? New C1().Goo()
""Bar""
>
Actual:
Microsoft (R) Visual Basic Interactive Compiler version 3.8.0-ci ()
Copyright (C) Microsoft Corporation. All rights reserved.
Type ""#help"" for more information.
> #r ""F:\workspace\_work\1\sartifacts	mp\Debug\RoslynTests\1.dllc29d247a-15d0-4e7f-b8d1-42106eddcb35.tmp""
> ? New C1().Goo()
«Red»
(1) : error BC30652: Reference required to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' containing the type '[Object]'. Add one to your project.
«Gray»
> 
Differences:
    Microsoft (R) Visual Basic Interactive Compiler version 3.8.0-ci ()
    Copyright (C) Microsoft Corporation. All rights reserved.
    Type ""#help"" for more information.
    > #r ""F:\workspace\_work\1\sartifacts	mp\Debug\RoslynTests\1.dllc29d247a-15d0-4e7f-b8d1-42106eddcb35.tmp""
    > ? New C1().Goo()
++> «Red»
++> (1) : error BC30652: Reference required to assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' containing the type '[Object]'. Add one to your project.
++> «Gray»
++> > 
--> ""Bar""
--> >

Expected: True
Actual:   False

 at Roslyn.Test.Utilities.AssertEx.AssertEqualToleratingWhitespaceDifferences(String expected, String actual, Boolean escapeQuotes, String expectedValueSourcePath, Int32 expectedValueSourceLine) in /_/src/Test/Utilities/Portable/Assert/AssertEx.cs:line 533
   at Microsoft.CodeAnalysis.VisualBasic.Scripting.UnitTests.CommandLineRunnerTests.TestReferenceDirective() in /_/src/Scripting/VisualBasicTest/CommandLineRunnerTests.vb:line 93
```

**Comment by RikkiGibson** [comment]
Ping @jaredpar. I think we are unblocked here even though it is not ideal to have to disable a test whose failure we can't reproduce locally.

**Comment by RikkiGibson** [comment]
Queueing a new validation run out of an abundance of caution. Will provide the link when the build completes.

**Comment by RikkiGibson** [comment]
The only RPS regressions in the validation run are expected, and the conflict in Versions.props is just git being git, so I will merge once the checks complete.

**Comment by RikkiGibson** [comment]
Thanks @AArnott!

**Pull request merged**
