### PR TITLE
Enable 64bit RemoteHost

### PR DESCRIPTION
**Pull request by heejaechang**
Enable 64bit OOP.

before 15.5, this will be changed to A/B testing.

### CODE REVIEW

**Comment by heejaechang** [comment]
enable 64bit by default to catch any unexpected issues. this will be changed to a/b testing before release.

**Comment by heejaechang** [comment]
this PR won't be checked in until VS integration tests are fixed.

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @dotnet/roslyn-ide @sharwell can you take a look?

**Comment by Pilchie** [comment]
Why not do the A/B test now?

**Comment by heejaechang** [comment]
working with them to make it a/b testing. but didn't decide what we are measuring for a/b testing yet.

**Comment by Pilchie** [comment]
You can write the code to check RemoteControl service before building the dashboard and metrics for A/B testing, and potentially force it on for people signed in with @microsoft.com addresses.

**Comment by heejaechang** [comment]
@Pilchie 
ah, didn't know about this "and potentially force it on for people signed in with @microsoft.com addresses."

anyway, code is already there. (http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,166)

**Comment by heejaechang** [comment]
anyway, I want it to run in 64bit for a while at least before release to make sure I get all issues though.

**Comment by Pilchie** [comment]
Okay - seems reasonable to me.  Want to make sure that @MattGertz sees explicitly that we're planning this though.

Finally - I will email offline with details of the internal only checks.

**Comment by MattGertz** [comment]
I see this is for master -- that's fine.  It goes without saying that this shouldn't go into d15prerel until we are really and truly ready for an A/B debut (I don't want machines keeling over, radioactive spiders charging through the streets, or whatever).  

Please tag me specifically when that happens (i.e. when it would actually go into a prerel build, I mean -- not the spiders).

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure windows_determinism_prtest is having a file lock issue - 
 https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_determinism_prtest/9557/

**Comment by heejaechang** [comment]
retest windows_determinism_prtest please

**Comment by sharwell** [comment]
@heejaechang Can you hold this while I check with @dotnet/roslyn-infrastructure about the safeguards we have to prevent this from making it to a release?

**Comment by sharwell** [comment]
@heejaechang If this is merged in its current form to the **master** branch, our current workflow will automatically push it to the 15.5 release. Barring an RPS failure (which would be fun on its own), we can't merge this unless its acceptable for it to ship.

/cc @MattGertz

**Comment by MattGertz** [comment]
We're having an offline conversation on this.  If it's off by default, then I'm OK.

**Comment by heejaechang** [comment]
all code for a/b testing is already there. only thing I need to enable 64bit OOP through a/b testing is enabling a/b testing.

I will leave it open so that I can at least get jenkins run with 64bits for testing.

**Comment by heejaechang** [comment]
so, what is a way to run RPS with this change? if I have it enabled for all internal users, will it be on for lab and RPS as well so that we can get RPS results with this on?

**Comment by MattGertz** [comment]
You could create a VAL build with this change to get RPS.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure can I get some help or pointer to doc where I can create VAL build with PR? without insertion PR? or create temporary insertion PR with github PR?

**Comment by heejaechang** [comment]
@brettfo can you help me on creating VAL build?

**Comment by heejaechang** [comment]
@KevinH-MS can you help me on running VAL build?

**Comment by KevinH-MS** [comment]
Yup, I'll be over in a min.

**Comment by heejaechang** [comment]
just talked with Duy. he will enable this A/B testing for 90%+ internal users today. it is for me to get stability issues rather than generating score cards. once we see it as stable enough, we will start real A/B testing that generates valid score cards.

**Comment by heejaechang** [comment]
@KevinH-MS thank you. kevin helped me how to do VAL run.

**Pull request closed without merging**
