### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160420-150019
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160420-150019 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by AlekseyTs** [comment]
Test prtest/lin/dbg/unit32 please

**Comment by AlekseyTs** [comment]
Test vsi please

**Comment by AlekseyTs** [comment]
Test prtest/lin/dbg/unit32 please

**Comment by AlekseyTs** [comment]
@dotnet-bot retest this please.

**Comment by AlekseyTs** [comment]
Test vsi please

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit64 please

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6346/

**Comment by AlekseyTs** [comment]
It has been determined that the failures are not caused by the changes in the PR.

**Pull request merged**
