### PR TITLE
Ensure that we don't break if we recurse into methods during symbol-key reader

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/16585

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
The existing SymbolKey-writing/reading code presumes that as it is recursing through symbols it will never hit a method-symbol reference inside a method-symbol reference.  So, when writing, it will keep track of the method it is in, and reset that method to 'null' when it is done writing.  It uses this information to determine how it should treat method-type-parameters when it encounters them.  If it is 'inside' a method, it writes out that type-parameter as an ordinal and moves on.

During reading, when then track when when we're inside a method, and we use that to resolve these type-arameter ordinals.  We then restore the mtehod to 'null' when we are done with the method.

--

Unfortunately, in teh wild, we are running into situations where we are trying to resolve a type-parameter ordinal and our current-method is 'null'.  This shouldn't be possible *if* our assumption that we can only be in a single-method at a time is true.

However, if it was possible to be in multiple methods at a time, then that assumption would no longer hold.  When we were done with the inner method, we'd set our 'current method' to null, and then move on.  When we hit an ordinal later on, we'd then crash due to the 'current method' not being there.

--

To try to mitigate this, i'm moving us away from this assumption entirely and i'm making the code firmly support the idea that there could be nested methods during writing and reading.  I'm also moving away from debug-only asserts, to runtime contracts.  This way, if there are issues with our assumptions, we can discover them immediately, instead of crashing later on down the line.

**Comment by CyrusNajmabadi** [comment]
My theory here is that there is some sort of code situation (possibly in error situations) where we end up with some sort of nested method reference).  This is just making the code resilient to that.

**Comment by Pilchie** [comment]
Is this crash the `SymbolKey` equivalent of the fix I made to `SymbolId` [here](https://github.com/dotnet/roslyn/pull/12311)?

**Comment by CyrusNajmabadi** [comment]
It's similar @Pilchie .  I just try to be more resilient to hte idea that there might be more than one Method that we're walking through when serializing out/in.

**Comment by CyrusNajmabadi** [comment]
**Customer scenario**

Customer is editing.  They get the yellow-bar stating that the "Add import fixer has been disabled"

**Bugs this fixes:** 

Fixes #16585

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

Low.  

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

For our Out-of-process work, we developed a system to serialize/deserialize symbols using 'string keys' so we could talk about symbols in a unified way across the client and server.  This system has turned out to be quite complex as uniquely describing a symbol is non-trivial.  In other words, we can't actually serialize out the symbol (because it would be *enormous* given everything in touches).  INstead, we essentially serialize out a path/description that allows us to recover/recreate the symbol on the other end.

As users are typing, some of these symbol descriptions can get quite complex.  We made an assumption in our description building/restoring code that looks to be incorrect and this change makes us resilient to it.


**How was the bug found?**

Several hits by the team while doing normal development.

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 

I'm not sure if this meets the bar.  We've def gotten a few reports about this.  But the end impact isn't terrible (but it's definitely still bad).  User sees a feature they really like get disabled and they either have to live without it until they restart VS, or they have to go manually restart the feature.

**Comment by MattGertz** [comment]
This is on the borderline; I'd like to take it so as to get a Shiproom read; this would be a good bar-setter for JoC.  The interesting thing here is that it's OOP related, and your fix is a catch-all for a broad class of scenarios.  Before taking it, we should heavily validate it; get our vendors to stress-test this scenario with your fix -- have them attack it for 30 minutes or so.  We could then target tomorrow to take it to Shiproom.

**Comment by MattGertz** [comment]
@Pilchie @CyrusNajmabadi  Forgot to tag you...

**Comment by CyrusNajmabadi** [comment]
Sounds good.  @Pilchie How would we go aobut doing what Matt is asking for?

**Comment by natidea** [comment]
VSO Bug: [Bug 370303](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/370303)

**Comment by natidea** [comment]
Approved to merge via [Bug 370303](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/370303)

**Pull request merged**
