### PR TITLE
Preselect "True" and "False" keywords in VB

### PR DESCRIPTION
**Pull request by rchande**
This is a redo of https://github.com/dotnet/roslyn/pull/6318.

* VB completion item matching now prefers preselected matches over case sensitive matches

### CODE REVIEW

**Comment by rchande** [comment]
Retagging @dotnet/roslyn-ide for review

@Pilchie: I was able to remove "fa" from that test; it's not just "f"
@jasonmalinowski: awkwardly enough, I'm getting the Document in order to get language services; I'm already using the SemanticModel off the SyntaxContext (which already gave you access to it).

**Comment by ManishJayaswal** [comment]
@rchande will it get preselected if I type "Dim d = t"?

:+1:

**Comment by rchande** [comment]
@ManishJayaswal It doesn't. I didn't realize Dev12 did that.

**Comment by DustinCampbell** [comment]
:+1:

**Comment by Pilchie** [comment]
Adding the approved tag, since @ManishJayaswal forgot.

**Pull request merged**
