### PR TITLE
Support expression bodied properties in "use auto property" analyzer.

### PR DESCRIPTION
**Pull request by MaStr11**
### Customer scenario

This PR adds support for expression bodied properties to the "Use auto property" code fixer.

Code this fixes:

```C#
class Class
{
    int i;
    int P
    {
        get => i;
    }
}
```

After:

```C#
class Class
{
    int P { get; }
}
```
### Bugs this fixes

None. No related issue found.

### Workarounds, if any

None.

### Risk

Low. Code fixer might fail to produce valid code or raise an unhandled exception (golden bar).

### Performance impact

Low. The analyzer does more syntax analysis now, but these changes should be allocation free. The fixer stayed almost the same.

### Is this a regression from a previous update?

Feature improvement.

### Root cause analysis

--

### How was the bug found?

Discovered during working on #23835

### Test documentation updated?

--

### CODE REVIEW

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by MaStr11** [comment]
Could I get feedback please. @CyrusNajmabadi probably?

**Comment by sharwell** [comment]
@MaStr11 Do you mind if I go ahead and fix the merge conflict?

@Pilchie This is already based on **dev15.7.x** so it would not be difficult to merge it there. Do you have a preference?

**Comment by MaStr11** [comment]
> Do you mind if I go ahead and fix the merge conflict?

No. Go ahead.

**Comment by Pilchie** [comment]
I'm open to taking this in 15.7.

**Comment by sharwell** [comment]
@Pilchie for 15.7 approval 😄

**Comment by Pilchie** [comment]
Requires another reviewer and a passing CI run.

**Comment by CyrusNajmabadi** [comment]
What, one single signoff from me isn't good enough? :P

**Comment by Pilchie** [comment]
You know I've never trusted you @CyrusNajmabadi  😉 .  Miss you!

**Comment by sharwell** [comment]
@Pilchie again

**Comment by Pilchie** [comment]
Approved - thanks @MaStr11 !

**Pull request merged**
