### PR TITLE
Don't run naming rules on symbols with no name

### LINKED ISSUE #19106: Naming Styles fantastic failure in broken code.
```c#
namespace Microsoft.CodeAnalysis.Host
{
    /// <summary>
    /// This service allows you to persist information relative to solution, projects and documents.
    /// </summary>
    public interface IPersistentStorageService : IWorkspaceService
    {
        IPersistentStorage GetStorage(Solution solution);
    }

    internal interface 
}
```

Note hte unterminated interface.  First, observe the following suggestion tag span:

image

Next, observe the totally broken suggestion:

image

Note: that "IHost" is being picked because the *namespace* we're contained in ends with "Host".

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #19106

Ask Mode
=======

**Customer scenario**: The customer has broken code such that there's a declared symbol with no name ("interface" with no name), and the naming style analyzer throws exceptions into the error list.

**Bugs this fixes:** #19106

**Workarounds, if any** No reasonable ones.

**Risk**: Very low. It's a very simple empty string check, and no other features depend on this.

**Risk**: Very low. It's a very simple empty string check.

**Performance impact**: Very low. It's a very simple empty string check.

**Is this a regression from a previous update?** No

**Root cause analysis:** A missed scenario. Unit tests are added.

**How was the bug found?** Dogfooding

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide for review

**Comment by CyrusNajmabadi** [comment]
How did we get a symbol with no name anyways?

**Comment by CyrusNajmabadi** [comment]
I've been through the IDE with a symbol with no name.

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
Tagging @MattGertz for Ask Mode consideration

**Pull request merged**
