### PR TITLE
Remove dead class diagram

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Is there anyone actually mentioning it? It hasn't changed for 4 years.
Visual editor in IDE always picks alphabetically first file for the partial classes.
Or we should get the outdated diagram removed instead?

### CODE REVIEW

**Comment by RikkiGibson** [comment]
It looks like this file hasn't been touched since 2014. It was added in commit `Roslyn.Says("Hello World");` and over time moved to different folders. I think we should just delete the file. @dotnet/roslyn-compiler

**Comment by 333fred** [comment]
Agreed, we should just delete.

**Comment by huoyaoyuan** [comment]
PR updated to remove instead.

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a senior review.

**Pull request merged**
