### PR TITLE
Correct comment about parameterized property

### LINKED ISSUE #21262: Incorrect comment in src/Features/VisualBasic/Portable/ReplacePropertyWithMethods/VisualBasicReplacePropertyWithMethods.vb#L23?
**Version Used**: 
master branch

**Steps to Reproduce**:

I am looking at the code to see what VB properties are not supported by the ReplacePropertyWithMethods feature

https://github.com/dotnet/roslyn/blob/24d55702cb26ab11e22eae8db4cf7ccc5fe3eef5/src/Features/VisualBasic/Portable/ReplacePropertyWithMethods/VisualBasicReplacePropertyWithMethods.vb#L23

**Expected Behavior**:
`' a parameterized property can be trivially converted to a method.`

Seems like it should  be `cannot`?

### PR DESCRIPTION
**Pull request by jeremymeng**
**Customer scenario**

N/A

Documentation issue: comment is incorrect.

**Bugs this fixes:**

https://github.com/dotnet/roslyn/issues/21262

**Workarounds, if any**

N/A Documentation issue

**Risk**

Low

**Performance impact**

Low

**Is this a regression from a previous update?**

N/A

**Root cause analysis:**

N/A

**How was the bug found?**

ad hoc testing

Fixes #21262.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi  in particular

**Comment by jeremymeng** [comment]
The test failure looks new. Should I log a issue for that then re-test?

**Comment by Pilchie** [comment]
Yes, please!  FYI @dotnet/roslyn-infrastructure

**Comment by jeremymeng** [comment]
Logged #21388

**Comment by jeremymeng** [comment]
retest windows_release_unit32_prtest please

**Pull request merged**
