### PR TITLE
Set insert_final_newline to true for C# and VB source files

### PR DESCRIPTION
**Pull request by sharwell**
I've noticed some inconsistency in editor settings across different pull requests, so I updated our **.editorconfig** in the repository to treat it uniformly from here forward.

Fixes #18384

### CODE REVIEW

**Comment by jmarolf** [comment]
to my knowledge `insert_final_newline` is not supported by the editor, has this changed?

**Comment by sharwell** [comment]
@jmarolf I'm not sure if the editor supports it directly, but it would be supported by other extensions that are known to be used by developers. Some discrepancies remain but this should reduce a small amount of churn that is currently occurring for cases where two developers use an editorconfig-aware editor with different configured default.s

**Comment by CyrusNajmabadi** [comment]
Why do we want an extra newline on all files?  It seems unnecessarily superfluous.  Can we set this to false, and have these tools opt for generating less code?

**Comment by CyrusNajmabadi** [comment]
Also, if we do this, can we also just do the work at the same time to make the codebase consistent.

Otherwise i don't want to be fighting between editors as some tools add this newline, while devs on this team remove things.

--

Finally, all coding guidelines for the team have to be approved by all teams affected by it.  i.e. if this hits compiler, then compiler needs to sign off as well.

**Comment by jmarolf** [comment]
@sharwell I ask because people look at our .editorconfig file as an example of what visual studio supports.

**Comment by sharwell** [comment]
> Why do we want an extra newline on all files?

:memo: This setting is already used by both [dotnet/coreclr](https://github.com/dotnet/coreclr/blob/master/.editorconfig#L12) and [dotnet/corefx](https://github.com/dotnet/corefx/blob/master/.editorconfig#L10), so I would expect it to make sense here.

Git calls attention to the missing newline in diffs, both in client-side tools and on places like GitHub. While neither C# nor VB require it, these notices are a red flag for some users because there are many tools which will not accept an input in this form, which makes them distracting.

> Also, if we do this, can we also just do the work at the same time to make the codebase consistent.

I can do this if uniformly preferred by the affected teams. Unlike reconfiguration some style settings, this one is relatively unintrusive to just let happen when it happens.

> Finally, all coding guidelines for the team have to be approved by all teams affected by it. i.e. if this hits compiler, then compiler needs to sign off as well.

I'd be disappointed if this wasn't the case. :smile:

> I ask because people look at our .editorconfig file as an example of what visual studio supports.

It looks like partial support was added in #17331. We could look into expanding support for this in more places.

**Comment by CyrusNajmabadi** [comment]
> these notices are a red flag for some users because there are many tools which will not accept an input in this form

Which tools?  Clearly tons of Roslyn files are of this form.  I can't recall a single issue about a tool that doesn't properly handle it.  So why change to this form if it isn't actually a problem in practice?

>  Unlike reconfiguration some style settings, this one is relatively unintrusive to just let happen when it happens.

I'm not a fan of an actual style setting that we aren't enforcing.  After all, if you make this change, and then people start editing the files *without* the newline, and their editor adds the newline, then we'll have the same problem as now, except in reverse.  You'll have git reviews where you see the newline added.  

> I'd be disappointed if this wasn't the case.

I'm just saying, you need to tag all the teams affected by this, so they can see and weigh in on this.  At the very least @jaredpar needs to be ok with this :)

**Comment by jaredpar** [comment]
> I'm just saying, you need to tag all the teams affected by this, so they can see and weigh in on this. At the very least @jaredpar needs to be ok with this :)

When it comes to coding styles my thoughts are generally:

1. Consistency wins out over basically anything else. 
1. Avoid debating coding styles in a PR where you also adopt the change.

The last one is because I've found it counterproductive to conflate what you should do with the actual impact to the code base.  Any style change is going to have a non-trivial change on the code base this large and it leads to endless debate.  Better to decide what is best, then tool the change and check in with a cursory review.

**Comment by sharwell** [comment]
@jaredpar Filed #18934 for discussion.

**Comment by sharwell** [comment]
@jaredpar The IDE now enforces this rule without extensions installed. Also updated all affected files for consistency.

**Comment by jaredpar** [comment]
> The IDE now enforces this rule without extensions installed. Also updated all affected files for consistency.

Imagine I edit a csproj file with vim which strips newline. Presumably this will pass PR and merge cleanly. What is the experience when other developers open the merged change in VS?

**Comment by sharwell** [comment]
> Imagine I edit a csproj file with vim which strips newline.

This change only applies to four file extensions: .cs, .csx, .vb, and .vbx. There is nothing preventing a user from using a non-standard editor to manually remove the end of the line from a file, but this will not happen on the officially-supported developer workflows.

> Presumably this will pass PR and merge cleanly. 

Correct, none of our code style rules are enforced by the build. This now one is no different.

> What is the experience when other developers open the merged change in VS?

VS will add the newline back when saving a changed file. If the file is opened but no changes are made to it, the deviation is ignored.

**Comment by tannergooding** [comment]
`insert_final_newline` is supported by the editor as of 15.3 (as should the other core options, such as charset).

**Comment by Pilchie** [comment]
> Imagine I edit a csproj file with vim which strips newline. 

@jaredpar: https://github.com/editorconfig/editorconfig-vim#readme

**Comment by jaredpar** [comment]
@Pilchie 

Understood. Mostly i'm trying to understand if there is the potential for me to cause the IDE pain by carelessly removing a new line 😄  @sharwell assured me offline this isn't the case.

**Pull request merged**
