### PR TITLE
Corrected references to language-specific syntax nodes in documentation

### PR DESCRIPTION
**Pull request by svick**

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Have you checked other CA1200 suppressions?

**Comment by Youssef1313** [comment]
Found a similar problem while reviewing other suppressions:

https://github.com/dotnet/roslyn/blob/32d55e216a8f0877b093eb27cd6ce085fdb49a3e/src/Compilers/Core/Portable/Syntax/SyntaxTrivia.cs#L20

**Comment by Youssef1313** [comment]
This one seems to be invalid too:

https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Compilers/CSharp/Portable/SymbolDisplay/ObjectDisplay.cs#L23

Here is the definition of ObjectDisplay.

https://github.com/dotnet/roslyn/blob/e704ca635bd6de70a0250e34c4567c7a28fa9f6d/src/Compilers/VisualBasic/Portable/SymbolDisplay/ObjectDisplay.vb#L9-L17

**Comment by svick** [comment]
@Youssef1313 No, I did not, thanks for looking into that.

I have fixed the issues you found this way:

* Remove references to the nonexistent `SyntaxTrivia` types.
* Fix references to the `ObjectDisplay` types (and also remove one nearby unnecessary cref prefix).

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
@svick thanks for the contribution!

**Pull request merged**
