### PR TITLE
Switch to 1ES servicing pools on release/dev16.7-vs-deps

### PR DESCRIPTION
**Pull request by jonfortescue**
Per https://github.com/dotnet/core-eng/issues/14276.

### CODE REVIEW

**Comment by 333fred** [comment]
@JoeRobich why do we even still have this branch? Shouldn't the -vs-deps branches all be removed at this point?

**Comment by JoeRobich** [comment]
> @JoeRobich why do we even still have this branch? Shouldn't the -vs-deps branches all be removed at this point?

We opted to keep the -vs-deps branches as our servicing branches. Helps keep things consistent when releases all come from -vs-deps branches.

**Comment by JoeRobich** [comment]
All that being said. This branch is not buildable because it still references myget feeds that are no longer available. We should add the dotnet-public and myget-legacy feeds to the nuget.config. Even then there may be packages we have to hunt down and get published.

**Comment by jonfortescue** [comment]
@JoeRobich would you be okay merging this even though the builds are failing in the meantime so we can migrate this off the BuildPools?

**Comment by JoeRobich** [comment]
> @JoeRobich would you be okay merging this even though the builds are failing in the meantime so we can migrate this off the BuildPools?

Let me try updating the nuget.config to see if this is an easy fix.

**Comment by lpatalas** [comment]
@JoeRobich Do you have any update on this PR? This is one of the last issues that's blocking us from completing 1ES migration.

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
> Do you have any update on this PR? 

Well, since the branch isn't buildable, there is no reason not to take the change. We would have to do a fair bit of work either way to service this release. Let us merge it and may April come soon.

**Comment by lpatalas** [comment]
Thanks!

**Pull request merged**
