### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by daking2014**
Fixes a typo in the summary of SyntaxGenerator.ThrowStatement

@tmeschter don't know if I need to tag anyone else?

### CODE REVIEW

**Comment by tmeschter** [comment]
:+1:

**Comment by tmeschter** [comment]
@daking2014 No, you don't need to add anyone else.

**Comment by tmeschter** [comment]
@daking2014 In general, you would add a few people who had context on the area of code you are changing. For fixing a small typo, most anyone on the Roslyn team will do. :-)

**Comment by daking2014** [comment]
@ManishJayaswal first merge to roslyn!

**Pull request merged**
