### PR TITLE
Compiler.SyntaxTest.IncrementalParser Refactored

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Refactored the UnitTest code of `CompilerSyntax\IncrementalParser\` 
* Made `IncParserNode` immutable.
* Added a Shared ReadOnly Instance of TextSpan to represent a "NullSpan" eg `New TextSpan(0,0)`
* Removed the helper method `ToText`.
** Which converted `XCData` to `String` correcting the different line feeds used in XML Literals to those used in strings.
* Convert the XML Literals over to Multiline Strings.
* Simplify some of the string.

### CODE REVIEW

**Comment by Neme12** [comment]
Why was this closed without a response?

**Comment by jaredpar** [comment]
@Neme12 the style changes to IncrementalParser.vb. There is a long history of this developer sending unwanted style changes in PR form. They've been asked ad nauseam to cease doing this and been warned that future PRs of the sort will be closed without comment.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot test this please

**Comment by AdamSpeight2008** [comment]
@jaredpar  Reconsider reopening this as it about potential perf improvements of the test code.
Running just the 99 Unit Test in `IncrementalParser` and reading the reported run time from the testrunners.
```
	       CodeRush	TestRunner (Parallel)
Using Strings: 5.52	07.9465125 08.087527  sec
Using XML    : 6.02	13.3898614 08.806287  sec
```

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 Can you resubmit without the style changes.  For example, the style changes here degraded readability:

image

now, instead of being able to read the code on github, i have to scroll to the right because you made the lines so long.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi It isn't a style change but a functional change `IncParseNode` is now immutable struct, rather than mutable. Hence the change.

**Comment by Neme12** [comment]
@AdamSpeight2008 Putting the whole expression on one line is a style change.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi It isn't a style change but a functional change IncParseNode is now immutable struct, rather than mutable. Hence the change.

You stylistically changed things to move them to a single line, makign it less readable (esp. on github).  I get that you had the touch the  line, however the compiler team has made it *very* clear over many PRs that you should really avoid unnecessary stylistic changes, even when you do need to touch a line.

**Comment by AdamSpeight2008** [comment]
@Neme12  Does it better when I the pr is predominantly focused potential perf improvements. 
Function over Form first. If the perf improvement are present, then focus on stylistic changes.

**Comment by Neme12** [comment]
> Function over Form first. If the perf improvement are present, then focus on stylistic changes

You *did* make stylistic changes first.

**Comment by CyrusNajmabadi** [comment]
@AdamSpeight2008 This is a repo that has rules around what sort of PRs are acceptable.  The compiler team has explained those rules to you many times.  If you want your PRs to be accepted you need to follow those rules.  If you don't this will continue happening.

**Comment by AdamSpeight2008** [comment]
@Neme12 The first commit are functional changes.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi I'm willing to make stylist change, after functionally tested.

**Comment by AdamSpeight2008** [comment]
Which why a "pr bot" to check style, would be useful. The pull-request indicates failures in style but still permit functionality testing.

**Comment by AdamSpeight2008** [comment]
@Neme12 Also this pull-request isn't show the full set of commits, since its closed.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I'm willing to make stylist change, after functionally tested.

@AdamSpeight2008 you can do wahtever you want.  However, until you follow the rules of this repo/team, you're going to continually see the same behavior and attitude toward your PRs.  Your own personal preferences do not, and never will, override the rules that have been set out and stated to you, clearly, many times over.

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi Open the pull-request so the latest diffs can be pulled in as you see that I self-corrected the style issue myself sometime ago.

**Comment by Neme12** [comment]
@AdamSpeight2008 @CyrusNajmabadi is not a member and can't open the pull-request. If you want the team to ever have patience with you again and to receive some reviews, I would strongly suggest that you stop commenting and forget about this. You're not making things better right now.

**Pull request closed without merging**
