### PR TITLE
Simplify .Kind() checks in the IDE layers.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @davidwengier in case it's a weekday over htere :D

**Comment by CyrusNajmabadi** [comment]
@genlu @Cosifne @akhera99 ptal :)

**Review by dibarbet — APPROVED** [review]

**Review by Youssef1313 — COMMENTED** [review]
If this change is okay, should [RS1034](https://github.com/dotnet/roslyn-analyzers/blob/0e1e7d5ceac134b93ec31ab6179dcd1f5bcea726/src/Microsoft.CodeAnalysis.Analyzers/Microsoft.CodeAnalysis.Analyzers.sarif#L442-L459) be retired?

**Comment by CyrusNajmabadi** [comment]
I have no idea what that rule is about.  I've never been able to measure a difference here.

**Pull request merged**
