### PR TITLE
Followup work to move over to using ITextImage.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
**Customer scenario**

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

**Bugs this fixes:**

(either VSO or GitHub links)

**Workarounds, if any**

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

**Risk**

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

**Performance impact**

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

**Is this a regression from a previous update?**

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

(E.g. customer reported it vs. ad hoc testing)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
git push --set-upstream origin smalledIndices

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by Pilchie** [comment]
@cyrusnajmabadi - is this something important to get merged for 15.3?

**Comment by CyrusNajmabadi** [comment]
I don't think so, no.  This was just something jason and i were considering taking to clean up some code now that we were on ITextImage.

**Comment by MattGertz** [comment]
Mondo escrow triage:  moving out.

**Comment by sharwell** [comment]
@CyrusNajmabadi Can you edit the original post to replace the template with an overview of this change?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski This was work we talked about doing to simplify and decouple our textimage wrappers.  If you want, feel free to pick this up and get it merged in.

**Pull request closed without merging**
