### PR TITLE
Add ubuntu.16.04-x64 RID to remaining projects

### LINKED ISSUE #17385: Build fails on Ubuntu 16.04
**Version Used**: master

**Steps to Reproduce**:

1. build from source using Ubuntu 16.04

**Expected Behavior**:
Build succeeds

**Actual Behavior**:
```
/home/vtsv/dotnet-arm/roslyn/Binaries/toolset/Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'ubuntu.16.04-x64' as a targeted runtime. You should add '"ubuntu.16.04-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [/home/vtsv/dotnet-arm/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/BoundTreeGenerator/CompilersBoundTreeGenerator.csproj]
/home/vtsv/dotnet-arm/roslyn/Binaries/toolset/Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'ubuntu.16.04-x64' as a targeted runtime. You should add '"ubuntu.16.04-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [/home/vtsv/dotnet-arm/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpErrorFactsGenerator/CSharpErrorFactsGenerator.csproj]
/home/vtsv/dotnet-arm/roslyn/Binaries/toolset/Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'ubuntu.16.04-x64' as a targeted runtime. You should add '"ubuntu.16.04-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [/home/vtsv/dotnet-arm/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/CSharpSyntaxGenerator/CSharpSyntaxGenerator.csproj]
/home/vtsv/dotnet-arm/roslyn/Binaries/toolset/Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'ubuntu.16.04-x64' as a targeted runtime. You should add '"ubuntu.16.04-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [/home/vtsv/dotnet-arm/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicErrorFactsGenerator/VisualBasicErrorFactsGenerator.vbproj]
/home/vtsv/dotnet-arm/roslyn/Binaries/toolset/Microsoft.NuGet.targets(140,5): error : Your project.json doesn't list 'ubuntu.16.04-x64' as a targeted runtime. You should add '"ubuntu.16.04-x64": { }' inside your "runtimes" section in your project.json, and then re-run NuGet restore. [/home/vtsv/dotnet-arm/roslyn/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj]
```

Incoming PR to fix this.

### PR DESCRIPTION
**Pull request by stevedesmond-ca**
Some projects already had it, but most didn't -- fixes #17385

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Tagging @dotnet/roslyn-compiler since these are all compiler projects.

**Comment by jasonmalinowski** [comment]
@jaredpar @agocke Can you find somebody to review this?

**Comment by TyOverby** [comment]
We should also likely add ubuntu.16 to our CI infrastructure

**Comment by TyOverby** [comment]
LGTM.  I've also added an Ubuntu16 leg in CI so we don't regress this.

You can find the PR changing CI over in https://github.com/dotnet/roslyn/pull/17535

**Comment by TyOverby** [comment]
ping @jaredpar

**Comment by TyOverby** [comment]
This change was added over in https://github.com/dotnet/roslyn/pull/17535

**Pull request closed without merging**
