### PR TITLE
More use of nameof() operator in ArgumentException and derived classes

### PR DESCRIPTION
**Pull request by bkoelman**
Switched from quoted argument names to nameof() operator, correcting a dozen or so in this manual process. RoslynLight.sln builds in VS2015 CTP6 and BuildAndTest.proj runs all tests without errors.

Note I did not update cases like: ```new ArgumentException("symbol")``` because according to the signature, the first parameter holds message and second holds parameter name. Not sure how the team would like to change this. Mostly affects code generated from Syntax.xml.

### CODE REVIEW

**Comment by pharring** [comment]
LGTM :+1: 
Of course, now we need an analyzer+fixer to prevent other uses creeping back in.

**Comment by bartkoelman** [comment]
@pharring Great suggestion to create an analyzer+fixer for that. I have created #2235 to track this.

In the mean time, would you be so kind to merge in the first pull request of my life? :)

**Comment by pharring** [comment]
@jaredpar @pilchie for additional review.
@bartkoelman it looks like there's a merge conflict ("We can't automatically merge this pull request"). Can you fix that?

**Comment by Pilchie** [comment]
LGTM too.

**Comment by bartkoelman** [comment]
@pharring Sorry to say this, I'm new to git. Spent the last 2h on trying to update the full request, think I broke my fork in the process. Unfortunately I have other obligations for the rest of this weekend. The merge itself is easy. Is this something you can maybe do or give me some guidance how to start over?

**Comment by pharring** [comment]
@bartkoelman I'm no git expert but I think you need to do this:

    git fetch upstream
    git merge upstream/master

At this point you will get one or some merge conflicts (because one of the files you changed has already been changed in the main branch). I find it easiest to deal with merge conflicts in Visual Studio's GUI.

If you're still stuck, someone like @jaredpar can probably help.

**Comment by bkoelman** [comment]
@pharring @Pilchie Updated pull request, see #2296
Please review and merge asap, as large change sets like this become outdated quickly.

**Comment by bkoelman** [comment]
Replaced by #2296

**Comment by jaredpar** [comment]
Why are we opening a new PR here?  No reason to do that.  We should iterate in this PR as this is the same issue.

**Comment by bkoelman** [comment]
@jaredpar Sorry for opening a new PR, I'm still getting used to git. I will try that next time.

**Comment by jaredpar** [comment]
@bkoelman 

No problem.  In the future though just keep pushing to the same branch.  The PR will auto update.

**Pull request closed without merging**
