### PR TITLE
Fix crash in nuget code when nuget.config file is broken.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20IDE/_workitems?_a=edit&id=468626&triage=true

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide .  I also audited the rest of the use of this interface.  We properly check for exceptions for all other calls.

**Comment by Pilchie** [comment]
Tagging @emgarten - are there other exceptions we should be watching for here?  (i.e., should we go for pokemon exception handling, or specific types)?

**Comment by Pilchie** [comment]
@CyrusNajmabadi - can you re-target this to `dev15.3.x`?

**Comment by dpoeschl** [comment]
Lots of these failures are known and will be fixed by https://github.com/dotnet/roslyn/pull/21069

**Comment by dpoeschl** [comment]
Lots of these failures are known and will be fixed by https://github.com/dotnet/roslyn/pull/21069

**Comment by Pilchie** [comment]
```
Finished:    Roslyn.VisualStudio.IntegrationTests
System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.
```

**Comment by Pilchie** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by emgarten** [comment]
This change looks good to me. You might also want to catch `InvalidOperationException` which is what NuGet throws for all expected failures from IVs interfaces.

`ArgumentException` or `ArgumentNullException` could happen on bad inputs.

For reference the NuGet code behind the sources call is here: https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.VisualStudio.Implementation/Extensibility/VsPackageInstallerServices.cs

All pokemon should be caught too of course 😄

**Comment by Pilchie** [comment]
Let's at least catch `InvalidOperationException` then.

**Comment by natidea** [comment]
Approved to merge via [468626](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/468626)

**Pull request merged**
