### PR TITLE
Crash on dispose

### PR DESCRIPTION
**Pull request by heejaechang**
explicitly crash VS if JsonRpc closed unexpectedly to get better dump.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @dotnet/roslyn-ide @CyrusNajmabadi can I get some code review?

**Comment by sharwell** [comment]
I'm always opposed to forced termination of the IDE without a separate guarantee that an effort has been made to avoid the loss of unsaved work. Can you be specific regarding the incremental benefit of this destructive process over the information already made available by a non-fatal Watson (NFW)?

**Comment by heejaechang** [comment]
@sharwell VS already crash in higher callstack. roslyn is already set up to crash on unknown exception. I just made the crash to happen earlier where the exception is first happened so that we can get better dump + callstack.

**Comment by heejaechang** [comment]
ping? can I get some code review? current dump from several report doesn't contain enough info for me to figure out how connection from VS to OOP got removed.

**Comment by heejaechang** [comment]
ping? @jinujoseph @mavasani can you take a look? I just added some watson early on rather than throw which lead to crash much later on.

**Comment by CyrusNajmabadi** [comment]
have you manually tried this out to see if it works.

**Comment by heejaechang** [comment]
@CyrusNajmabadi yes. I just re-checked it. working as expected.

**Pull request merged**
