### PR TITLE
Update absolute links to relative

### PR DESCRIPTION
**Pull request by Saisang**

### CODE REVIEW

**Review by 333fred — CHANGES_REQUESTED** [review]
These links are not relative to this repository, so by doing this we'd make them not resolve in our markdown. What is the reason you're trying to change them?

**Comment by Saisang** [comment]
> These links are not relative to this repository, so by doing this we'd make them not resolve in our markdown. What is the reason you're trying to change them?

This is a kind of [build suggestion in OPS](https://buildapi.docs.microsoft.com/Output/Commit/a3bda507-3390-de91-8f7f-26f90f4e5fc8/202402031616023749-main/BuildReport?accessString=86ad653daba836a80d61062830ce20667e9b108c0c5069ceb1786939f5c446de). "Absolute link '{URL}' will be broken in isolated environments. Replace with a relative link." I'm trying to update all absolute links to relative ones.

**Comment by 333fred** [comment]
Well, it's wrong. These links are not relative to this repository and updating them to be relative is incorrect, as it will break the markdown in this repo.

**Comment by sharwell** [comment]
@Saisang All links to learn.microsoft.com should be excluded from that analysis. The links will be broken _by design_ in isolated environments.

**Pull request closed without merging**
