### PR TITLE
Move DocumentHighlights data types down to the 'Features' layer.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This is just resending: https://github.com/dotnet/roslyn/pull/18972  out again.

We rolled that back because of some infrastructure problems we were ahving around insertions.  

Note: this is the change that changes our API layering and will affect TypeScript and F# as welll.   Tagging @paulvanbrenk @minestarks @brettfo 

I'm going to try to get this in today and i will let you know when it makes it through and is published so you can pull the latest Roslyn version and update your bits according. 

If i'm not mistaken these bits will flow into vsuml.  But @Pilchie and @jasonmalinowski can confirm this.

**Comment by Pilchie** [comment]
Starting today, we'll be targeting insertions to `d15prerel` as well as `vsuml`

**Comment by CyrusNajmabadi** [comment]
Ok.  @tmeschter Is very smart. I changed the API to leave hte old API in and to add the new API.  The roslny impl will look for either export and will support both until the point that F# and TypeScript are able to move over. 

Once this is checked in, i will mildly poke TypeScript and F# until they are able to move over.  

Note: @minestarks  As you noticed, we have changed Roslyn a bit (especially some enum values).  So no matter what, you should move to a more recent version and recompile to fix things up.

**Comment by CyrusNajmabadi** [comment]
This is now no longer a breaking change to Roslyn, and so can go in much more gently.

**Comment by CyrusNajmabadi** [comment]
Telling @MattGertz  aobut this.  This is just a resend of https://github.com/dotnet/roslyn/pull/18972 which was already approved.  The original was rolled because because we didn't want to take the breaking change in it at a time when we were trying to lock down the insertion.

Tom proposed a way to do it again without any breaks, and so that's what we're taking now.  This means that we don't need to coordinate any insertion, and Roslyn can unblock itself wrt OOP work here without impacting F# or TypeScript.

**Comment by MattGertz** [comment]
Approved pending tests.

**Pull request merged**
