### PR TITLE
Log commit information before we start a CI build

### PR DESCRIPTION
**Pull request by jasonmalinowski**
By passing --pretty=raw we get the full SHA1s of all parent commits,
as well as the tree SHA1 so we can confirm content as well.

*Review:* @dotnet/roslyn-infrastructure, @jaredpar

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1:

**Comment by davkean** [comment]
Can we add this the non-Windows script to keep it in sync?

**Comment by davkean** [comment]
Oh you did, didn't see it in the logs, let me look again

**Comment by davkean** [comment]
Sorry, accidently closed it - really struggling this morning...

**Comment by jaredpar** [comment]
:smile:

**Comment by davkean** [comment]
:+1:

**Comment by davkean** [comment]
11 minutes to run a build with zero changes, @jaredpar this is really damn awesome.

**Comment by jaredpar** [comment]
Nice.  Glad to see it working.  Now to get my distributed caching version out for PR :smile:

**Comment by davkean** [comment]
@jaredpar Where are you going to store it?

**Comment by jaredpar** [comment]
@davkean the cloud :smile:

**Comment by jaredpar** [comment]
@davkean if you're curious:

https://github.com/jaredpar/roslyn/tree/cache

That branch is already functional.  Been running it locally today and it's working as expected.  I need to do a bit more work before it's ready though.  In particular making sure it's not the default for arbitrary clones of the repo (can be opted into).  Don't want to surprise people by defaulting to sending their results to our caching layer.

**Comment by davkean** [comment]
That's awesome.

**Pull request merged**
