### PR TITLE
Don't use SymbolId when creating completion items (MU edition)

### PR DESCRIPTION
**Pull request by rchande**
This is a redo of https://github.com/dotnet/roslyn/pull/15688 against the microupdate branch. The completion code has diverged significantly in master so I'm keeping the original PR to use there.

### CODE REVIEW

**Comment by rchande** [comment]
Tag @dotnet/roslyn-ide @jasonmalinowski @DustinCampbell for review

**Comment by rchande** [comment]
Confirmed that 0 time is spent computing SymbolId in completion.

**Comment by rchande** [comment]
retest windows_release_unit32_prtest please

**Comment by rchande** [comment]
retest windows_release_unit64_prtest

**Comment by rchande** [comment]
retest windows_release_unit32_prtest please

**Comment by rchande** [comment]
retest windows_release_unit64_prtest

**Comment by jasonmalinowski** [comment]
@rchande and @Pilchie: to confirm, we think we're ready to merge this in today?

**Comment by rchande** [comment]
@jasonmalinowski Yep!

**Comment by Pilchie** [comment]
@CyrusNajmabadi @mattwar can you take a quick look at this port of #15688 to the `microupdate` branch?

**Comment by jasonmalinowski** [comment]
I had "require commits to be serial" enabled for this branch since I figured we wouldn't have much volume. Unfortunately that means we don't have VMs handy either to run stuff. I'll merge this once we get some greenness from it.

**Pull request merged**
