### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160311-160019
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160311-160019 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5098/
// Retest reason:

**Comment by heejaechang** [comment]
test vsi please

**Comment by davkean** [comment]
test eta please

**Comment by heejaechang** [comment]
github timed out

**Comment by heejaechang** [comment]
retest prtest/win/vsi/p0 please

**Comment by heejaechang** [comment]
retest prtest/win/vsi/p3  please

**Pull request merged**
