### PR TITLE
Port 3 fixes from master to rc2

### PR DESCRIPTION
**Pull request by heejaechang**
**Customer scenario**

it fixes 2 customer issues.

1. random crash when user builds solution using special "devenv /build" command line argument (#15490)
2. various issues reported from new OOP features released in RC (#14978, #15110).

**Bugs this fixes:** 
#15490, #14978, #15110

**Workarounds, if any**
there is no workaround. these fixes are better to be in early so that we can catch more issues before RTM.

**Risk**

Fix for the first issue is very low risk. simple and very specific fix. no broad impact.
Fix for the second issue will not make OOP any less stable than before. it either makes it more stable or let us have better dump if it happens again. 

**Performance impact**

these fixes are not related to any major perf releated code.

**Is this a regression from a previous update?**
No. both of them are issues we first found out. especially second fix is for feature which released in RC.

**Root cause analysis:**
issue for the first fix is due to a race. 
OOP related issues has multiple root causes. one is due to some failure in service hub, another is due to us not setting option correctly in some code path or not catching exception we should have and etc.

How did we miss it?  What tests are we adding to guard against it in the future?
race is hard to test and catch. OOP is new feature so there were missing test holes and pattern we didn't thought of.

unit tests are added for found issues.

**How was the bug found?**
customer reports and watsons.

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani @panopticoncentral can you take a look? these are straight port from master which already got signed off

**Comment by heejaechang** [comment]
@MattGertz can I get approval for rc2?

**Comment by heejaechang** [comment]
adding @natidea for FYI

**Comment by MattGertz** [comment]
Approved to take to Escrow Shiproom on 11/30.

**Comment by natidea** [comment]
@heejaechang this PR is against master. Should be dev15-rc2

**Comment by srivatsn** [comment]
I retargeted the PR to dev15-rc2.

**Comment by heejaechang** [comment]
@srivatsn oops. thank you.

**Pull request merged**
