### PR TITLE
Permit a throw expression as the body of an expression-bodied lambda

### LINKED ISSUE #15555: Throw in expression bodied lambdas is a syntax error
**Version Used**: 
2017 RC
**Steps to Reproduce**:
@gafter in #13389, it says that a throw expression is permitted as the body of an expression-bodied lambda or method. I receive the error
> error CS8115: A throw expression is not allowed in this context.
With the following code
```C#
Action a = () => throw new Exception();
```
I'm not sure if this was an intentional change but I don't see it documented. Thanks!
**Expected Behavior**:
Throw expressions may be used in an expression bodied lambda expression.
**Actual Behavior**:
Throw expressions are not legal as the bodies of expression bodied lambda expressions.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #15555

@dotnet/roslyn-compiler Please review. This will be proposed for ask mode after review.

### CODE REVIEW

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet/roslyn-compiler One more review, please.

**Comment by AlekseyTs** [comment]
>             switch (node.Parent.Kind())

Consider replacing ```node.Parent``` with ```parent```.

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Expressions.cs:680 in 785b456. [](commit_id = 785b456f3fe395300dfcd711ffcdf41b97f38358, deletion_comment = False)

**Comment by gafter** [comment]
@jared @jcouv Could you please shepherd this now-approved PR into the correct branch? I am out for the week. If not urgent I can do it next week.

**Comment by jcouv** [comment]
@gafter Yes, I will.

**Comment by jcouv** [comment]
@MattGertz please approve for RC.3.

Customer scenario:
`Action a = () => throw new Exception();`
Throw exceptions should be allowed in such lambdas, but were blocked.

Bugs this fixes:
Fixes #15555

Workarounds, if any:
The user can add a block, then the throw is no longer an throw-expression, it is a good old statement.
`Action a = () => { throw new Exception(); };`

Risk:
Low

Performance impact:
Low, the method that decides which contexts allow throw-exceptions is just getting an additional case branch.

Is this a regression from a previous update?
No

Root cause analysis:
I'm shepherding Neal's PR, so I don't know the whole context, but seems like a test gap for new feature (throw expressions).

How was the bug found?
Reported by a customer.

**Pull request merged**
