### PR TITLE
Revert "Make APIs related to scripting and interactive internal for RTM"

### LINKED ISSUE #3786: Symbols from previous submissions are squiggled in the Interactive Window
interactivewindow

They bind, but they're not available via Completion and they're squiggled.  They're probably not available through the SemanticModel.

### PR DESCRIPTION
**Pull request by amcasey**
This reverts commit 15443a233a4cfb400e349f40f9d265ec341998a2.

Conflicts:
* src/Compilers/CSharp/Portable/CommandLine/CommandLineParser.cs
* src/Compilers/CSharp/Portable/PublicAPI.txt
* src/Compilers/Core/Portable/PublicAPI.txt
* src/Compilers/VisualBasic/Portable/CommandLine/CommandLineParser.vb

Fixes #3786 and #2888.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @cston @KevinH-MS @ManishJayaswal

**Comment by cston** [comment]
LGTM

**Comment by KevinH-MS** [comment]
LGTM

**Comment by cston** [comment]
Fixes #3214

**Pull request merged**
