### PR TITLE
Clear dead links to feature branches in `Language Feature Status.md`

### PR DESCRIPTION
**Pull request by DoctorKrolic**

### CODE REVIEW

**Comment by DoctorKrolic** [comment]
Can I have a review here? This is just a simple cleanup without any code changes

**Comment by jcouv** [comment]
Would it be possible to instead blank that column when it's no longer meaningful?

**Comment by DoctorKrolic** [comment]
I followed pattern used in other feature descriptions, where the branch is set to `main` if there is no actual feature branch left. Introducing blank spaces for only those cells, changed in this PR would create inconsistency, therefore I assume you request this change for all features with no feature branch, not only already changed ones, right?

**Comment by jcouv** [comment]
I see. Leaving as "main" seems fine then. Thanks

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Comment by jcouv** [comment]
Thanks @DoctorKrolic !

**Pull request merged**
