### PR TITLE
Infer types from constraints

### PR DESCRIPTION
**Pull request by HellBrick**
This is a prototype of #5023 rebased on top of the future branch. See https://github.com/dotnet/roslyn/issues/5023#issuecomment-154728796 for the description of the implementation mechanics and #6644 for the original PR against master.

/cc @gafter

### CODE REVIEW

**Comment by davkean** [comment]
Closing and reopening, so that merge branch gets updated.

**Comment by davkean** [comment]
@dotnet-bot retest this please

test eta please

**Comment by davkean** [comment]
What's the plans with this PR? You mention this is a prototype, are you looking for feedback? Or is this just to get some coverage for tests?

**Comment by amcasey** [comment]
The test failures appear to due to some issues that have already been resolved in master.  They should clear up as soon as we've merged.

**Comment by davkean** [comment]
Ignore these failures for the moment, looks like future is broken.

**Comment by HellBrick** [comment]
To be honest, I have no clue about what comes next for this PR. This is my shot at an up-for-grabs issue that I care about: I just came up with an idea on how to do it and implemented it. The tests have been taken care of in the previous incarnation of this PR (against the master branch), the feature seems to be working fine and it's designed in the most non-invasive way I could think of to minimize the chance of screwing other things up.

However, there wasn't a proper discussion of the implementation neither before nor after the PR, so I have no idea if it's good or bad or anything in between. There was [this comment](https://github.com/dotnet/roslyn/pull/6644#issuecomment-169801937), but I'm not sure what LDM is, whether it covered the details of this PR and what to do next. So yes, some clarity and/or feedback would be nice =)

**Comment by gafter** [comment]
"LDM" is the (members of the) language design meeting.

We just looked at the proposal. It appears to be a breaking language change (i.e. will change the behavior of existing code), and there doesn't appear to be any nice way to fix that.

Here is an example of how the break arises. Given the two methods

```cs
void M(object) {}
void M<T, U>(T t) where T : IEnumerable<U> {}
```

and existing invocation

```cs
M("foo");
```

the previous version of the language (without this change) would call the former method. With the new rules in place, it would call the latter method.

Our customers tar and feather us when we take breaking changes, so this, unfortunately, might kill the idea of this feature.

Having said that, don't lose all hope. We (the LDM) are sad that we cannot take *any* breaking changes, even one such as this that seems like an improvement. We're wondering if it will be possible for us to make breaking changes *if we also ship a tool that updates your code so that it has the same meaning as before*. Having a mechanism for such a tool to exist would have made it easier for us to do many things in the past, and would have enabled us to avoid language-design contortions, for example due to new keywords (such as `var`, `nameof` and `async`) being identifiers in the previous version.

/cc @MadsTorgersen

**Comment by amcasey** [comment]
The pull request that should fix Future is https://github.com/dotnet/roslyn/pull/7853.

**Comment by HellBrick** [comment]
Ah, now I see it's way trickier than I expected =) Thanks for the explanation.

I do hope that some story for mitigating breaking changes will be worked out eventually. Is there a public issue that tracks this idea? It would be a very interesting thing to follow.

**Comment by BreyerW** [comment]
As for breaking change - i wonder couldn't it be reduced by adding small constraint like that you have to say that you want to infer generic version. I think better to show example:

Instead of calling `M("foo");` you have to write smth like `M<,>("foo");`. Just that you have to add `<,>` to tell compiler that you want to infer version with two generics. If there is more overloads with two generics then i think standard overload resolution should come in.

The problem is - will this constraint kill usefulness of feature or not?

**Comment by SergeyZhurikhin** [comment]
@gafter I accept, the call  M("foo")  as  M<string, char>("foo").

**Comment by davkean** [comment]
(Closing/opening to sync update the merge branch to pick up the build break we just fixed)

**Comment by davkean** [comment]
@dotnet-bot retest this please

**Comment by gafter** [comment]
There is no way for us to accept this change until we have a way of handling breaking changes, which will not be soon. So I'm going to close this PR. However, we are leaving it around for reference in case we can take it in the future.

@HellBrick Thanks for your contribution!

**Comment by Ultrahead** [comment]
@gafter: maybe M("Foo"); should throw a compiler error that could be solved with something like:

M<!>("Foo"); // calls the non-generic operation

M<>("Foo"); // call the generic operation

**Comment by YairHalberstadt** [comment]
@Ultrahead
That would also be a breaking change.

**Comment by bahusoid** [comment]
Is this issue forgotten? Why it's not considered for .NET Core 3.0?

I don't quite understand the argument about breaking changes. Can't it instead of silent behavior change throw some **compilation** "ambiguous extension method" exception. So end user when target framework is updated have to explicitly call proper generic/non-generic method and instead of `foo.Method()` have to  call `MyNonGenericExtensionsClass.Method()` for **rare**  ambiguous cases. That's IMHO really little price for such a great improvement in  framework.

**Comment by gafter** [comment]
@bahusoid This PR is a breaking change to the language, and has therefore been rejected by the LDM.  If you have a different proposal we would consider it, but no alternate specification has been offered for us to consider.  A specification that makes these cases ambiguous, as you suggest, would be a plausible approach if it doesn't make overload resolution much more complex.

In any case, language changes for .NET Core 3.0 were completed several months ago.  It is too late to add to C# 8.0.

**Comment by symbiogenesis** [comment]
This would be a nice addition to C# 12 or 13

**Comment by thomhurst** [comment]
Could it not be opt-in functionality based on a project property or something? If people explicitly opt-in them that's on them to be aware about breaking changes .

Like how we have 
`<Nullable>enabled</Nullable>` Or `<ImplicitUsings>enabled</ImplicitUsings>`

We could have something like:

`<EnhancedTypeInferance>enabled</EnhancedTypeInferance>`

**Comment by phoyd** [comment]
Couldn't this simply be solved by specifying that U should be inferred from the where clause if not given explicitly? For example using a reserved word: 
```
void M(object) {}
void M<T, U>(T t) where T : IEnumerable<U> where U : implicit {} // U is inferred from where clause
// alternatively: 
void M<T, implicit U>(T t) where T : IEnumerable<U> // U is inferred from where clause
```
This wouldn't break anything, would it? Just enable new functionality on new code.

**Comment by thomhurst** [comment]
> Couldn't this simply be solved by specifying that U should be inferred from the where clause if not given explicitly? For example using a reserved word:
> 
> ```
> void M(object) {}
> void M<T, U>(T t) where T : IEnumerable<U> where U : implicit {} // U is inferred from where clause
> // alternatively: 
> void M<T, implicit U>(T t) where T : IEnumerable<U> // U is inferred from where clause
> ```
> 
> This wouldn't break anything, would it? Just enable new functionality on new code.

The issue isn't defining the method, it's calling it. Other bits of unchanged code will switch from calling an `object` overload to a `T` overload, meaning a simple upgrade to .NET (if this was implemented) would change your code and what it's calling.

**Comment by thomhurst** [comment]
> Couldn't this simply be solved by specifying that U should be inferred from the where clause if not given explicitly? For example using a reserved word:
> 
> ```
> void M(object) {}
> void M<T, U>(T t) where T : IEnumerable<U> where U : implicit {} // U is inferred from where clause
> // alternatively: 
> void M<T, implicit U>(T t) where T : IEnumerable<U> // U is inferred from where clause
> ```
> 
> This wouldn't break anything, would it? Just enable new functionality on new code.

I like this. By utilising that where clause you're opting into the behaviour.

**Comment by symbiogenesis** [comment]
Like the opt-in syntax as a compatibility solution.

**Pull request closed without merging**
