### PR TITLE
Revert "Merge pull request #6636 from CyrusNajmabadi/asyncLazy"

### PR DESCRIPTION
**Pull request by KevinH-MS**
This reverts commit 492dc66f66123c04231a9c8eadba5c5370d0e087, reversing
changes made to 788eed075204058dc8356dac763d0ee1174a4f8e.

(pending investigation into why this results in excess allocations)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @CyrusNajmabadi 

This the first of two remaining issues that seem to be at the root of the managed allocations/VM regressions that showed up in RPS about a month ago.  I can't actually tell ***why*** this is causing more allocations, but I was able to test with change reverted and see (part) of the regression go away.  Since this may take some time to understand, I'd like to revert for now (so we can get new Roslyn into the VS update branch before the build lab shuts down for the holidays).

**Comment by KevinH-MS** [comment]
Let me know if you want an issue tracking this (there didn't appear to be specific one associated with the original commit).

**Comment by Pilchie** [comment]
:cry: It was so nice to not hit that exception all the time.  

Also tagging @jasonmalinowski

**Comment by jasonmalinowski** [comment]
File a new bug to track this. I look forward to the analysis on how this affected performance. I would have thought throwing fewer exceptions would be good... :smile:

**Comment by KevinH-MS** [comment]
Filed #7505

**Comment by CyrusNajmabadi** [comment]
I really would like ot understand why this is causing excess allocations.  So far there have been three PRs undone because of that reason.  I've been unable to repro the issue locally, and nothing about these changes seems like it would cause any excess allocations at all...

Do we have a diff of the allocations before/after the change to at least see what kind of objects we're seeing being allocated and how they differ?

**Pull request merged**
