### PR TITLE
Fix ctrl click crash

### PR DESCRIPTION
**Pull request by rchande**
**Customer scenario**

Customer holds CTRL key in a JS/TS file and Visual Studio crashes.

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/_workitems?id=479492

**Workarounds, if any**

Disable Ctrl-Click Go To Definition for all languages (the editor doesn't provide a per-language option for this). This is not a good workaround because it also disables the feature in languages where it does work.

**Risk**
Low--adds a null check.

**Performance impact**
Low--adds a null check.

**Is this a regression from a previous update?**
Yes--our implementation of the Editor's "Ctrl-Click Go To Definition" feature allows all languages using Roslyn to opt into the feature at the Roslyn layer. However, we crash in languages that don't implement it.

**Root cause analysis:**

Didn't test languages other than C#/VB to validate that the feature was simply disabled without crashing. When adding extension points like this in the future, we should test them in other languages to verify that not implementing the feature doesn't cause any issues.

**How was the bug found?**

Dogfooding.

### CODE REVIEW

**Comment by rchande** [comment]
Tag @dotnet/roslyn-ide @Pilchie @MattGertz 
Note that this PR also reverts some changes that were merged into dev15.4.x for Preview 2. After this change is inserted into Preview 1, we can merge a followup change that un-reverts the changes intended for Preview 2.

**Comment by Pilchie** [comment]
@heejaechang can you please comment on the revert of #21274?  Was that intended for 15.4 P1?

**Comment by heejaechang** [comment]
@Pilchie @rchande that changes were for perf regression on d15prerel. if you revert the change, d15prerel can get the regression back.

**Comment by rchande** [comment]
@heejaechang Was the change actually inserted? There's no indication of that on the VSO bug linked in the PR.

**Comment by rchande** [comment]
@amcasey is testing this out.

**Comment by amcasey** [comment]
I've specifically verified that the original issue no longer repros.  I assume that the usual TS integration tests will be run before this is inserted?

**Comment by rchande** [comment]
retest windows_debug_vs-integration_prtest

**Comment by amcasey** [comment]
I kicked the tires in a TS Node project and nothing awful happened.

**Comment by amcasey** [comment]
@paulvanbrenk was recently broken and might wish to perform additional validation for NTVS (though I can't see how this would break NTVS specfically).

**Comment by heejaechang** [comment]
@brettfo is dev15.4.xx inserted to vso?

**Pull request merged**
