### PR TITLE
[Ask Mode] Fix crash in `EventAssignmentExpression.EventInstance` in VB

### LINKED ISSUE #9012: NRE in `EventAssignmentExpression.EventInstance` property
It crash with a NRE when trying to access `EventAssignmentExpression.EventInstance` property in test `Microsoft.CodeAnalysis.VisualBasic.UnitTests.Binder_Statements_Tests.AddHandlerMissingStuff`
```
Test 'Microsoft.CodeAnalysis.VisualBasic.UnitTests.Binder_Statements_Tests.AddHandlerMissingStuff' failed: System.NullReferenceException : Object reference not set to an instance of an object.
	BoundTree\Statement.vb(1548,0): at Microsoft.CodeAnalysis.VisualBasic.BoundAddRemoveHandlerStatement.EventAssignmentExpression.get_EventInstance()
	Compilation\OperationWalker.cs(254,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitEventAssignmentExpression(IEventAssignmentExpression operation)
	BoundTree\Statement.vb(1516,0): at Microsoft.CodeAnalysis.VisualBasic.BoundAddRemoveHandlerStatement.EventAssignmentExpression.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	Compilation\OperationWalker.cs(178,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.VisitExpressionStatement(IExpressionStatement operation)
	BoundTree\Statement.vb(1497,0): at Microsoft.CodeAnalysis.VisualBasic.BoundAddRemoveHandlerStatement.Accept(OperationVisitor visitor)
	Compilation\OperationWalker.cs(34,0): at Microsoft.CodeAnalysis.Semantics.OperationWalker.Visit(IOperation operation)
	CompilationTestUtils.vb(247,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.WalkOperationTrees(VisualBasicCompilation compilation)
	CompilationTestUtils.vb(228,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(IEnumerable`1 sourceTrees, IEnumerable`1 references, VisualBasicCompilationOptions options, String assemblyName)
	CompilationTestUtils.vb(199,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithReferences(XElement sources, IEnumerable`1 references, VisualBasicCompilationOptions options, IEnumerable`1& spans, VisualBasicParseOptions parseOptions)
	CompilationTestUtils.vb(120,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.CompilationUtils.CreateCompilationWithMscorlibAndVBRuntime(XElement sources, MetadataReference[] additionalRefs, VisualBasicCompilationOptions options, VisualBasicParseOptions parseOptions)
	Binding\Binder_Statements_Tests.vb(2959,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.Binder_Statements_Tests.AddHandlerMissingStuff()
```

Here's some other code snippet to repro this.

```vb
	Module Program
		Sub Main(args As String())
			AddHandler Function(ByVal x) x
		End Sub
	End Module
```
```vb
	Class TestClass

		Event TestEvent As Action

		Shared Sub Test(receiver As TestClass)
			AddHandler receiver?.TestEvent, AddressOf Main
		End Sub

		Shared Sub Main()
		End Sub
	End Class
```
```vb
Imports System
Imports System.Collections.Generic

Module Module1
    Sub Main()
        Dim x = {Iterator sub() yield, new object}
        Dim y = {Iterator sub() yield 1, Iterator sub() yield, new object}
        Dim z = {Sub() AddHandler, New Object}
        g0(Iterator sub() Yield)
        g1(Iterator Sub() Yield, 5)
    End Sub

    Sub g0(ByVal x As Func(Of IEnumerator))
    End Sub
    Sub g1(ByVal x As Func(Of IEnumerator), ByVal y As Integer)
    End Sub

    Iterator Function f() As IEnumerator
        Yield
    End Function

End Module
```

### PR DESCRIPTION
**Pull request by genlu**
This fixes #9012.

@JohnHamby @dotnet/roslyn-interactive @MattGertz

### CODE REVIEW

**Comment by genlu** [comment]
retest vsi please

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/vsi/p1 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/328/
// Retest reason: System.Runtime.InteropServices.COMException (0x800706BA): The RPC server is unavailable.

**Comment by JohnHamby** [comment]
I sign off.

This is, of course, another instance of the bound tree being unreliable in the presence of errors.

**Comment by MattGertz** [comment]
Approved.

**Pull request merged**
