### PR TITLE
Disable code action prior to C# 6

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/13226

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by balajikris** [comment]
Does VB has this code fix? If so, it probably requires the same change as well.

**Comment by balajikris** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
VB doesn't have this codefix because 'Invoke' is already a feature of their language since the first VB.net.

**Pull request merged**
