### PR TITLE
Revert "Add semantic classification for records"

### PR DESCRIPTION
**Pull request by RikkiGibson**
Reverts dotnet/roslyn#47960

We believe this PR has caused an RPS regression in a XAML scenario. https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/283694?view=discussion

Please note that this revert is not a rejection of the change being reverted. It just means that this change is blocking insertion into VS right now. We are happy to take this change back into a release branch once necessary modification and validation has been done to fix or seek exception for the RPS regression.

FYI @allisonchou

### CODE REVIEW

**Review by allisonchou — APPROVED** [review]
Thanks Rikki for setting up the revert PR.

**Comment by CyrusNajmabadi** [comment]
> We believe this PR has caused an RPS regression in a XAML scenario. https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/283694?view=discussion

i would like to understand this better.  Why do we think this caused the RPS regression? And can we clarify what the RPS regressoin is here?

**Comment by sharwell** [comment]
@CyrusNajmabadi It looks like `GetShortName` forced a bunch of metadata to load

image

**Comment by sharwell** [comment]
The interesting thing here is `ToDisplayString` doesn't even care about `SymbolDisplayKind`, but there is no way with the current API to skip its computation.

**Comment by 333fred** [comment]
https://github.com/dotnet/roslyn/pull/48935 will hopefully fix this.

**Comment by RikkiGibson** [comment]
I'm gonna keep an eye on this insertion linked from #48935 https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/283946

If the RPS results resolve the issue then we can abandon this PR.

**Comment by 333fred** [comment]
Closing in favor of https://github.com/dotnet/roslyn/pull/48935.

**Pull request closed without merging**
