### PR TITLE
Update link to `up-for-grabs` issues

### PR DESCRIPTION
**Pull request by aochagavia**
It points now to the issues on the GitHub repository

### CODE REVIEW

**Comment by khellang** [comment]
Isn't "https://github.com/dotnet/roslyn/labels/Up%20for%20Grabs" more correct? Just sent [a PR](https://github.com/dahlbyk/up-for-grabs.net/pull/150) to up-for-grabs.net as well :smile:

**Comment by aochagavia** [comment]
I think that one would also show closed issues. Wouldn't it?

**Comment by adamralph** [comment]
IIRC, last time I checked, 'up-for-grabs' was more common.

**Comment by khellang** [comment]
> I think that one would also show closed issues. Wouldn't it?

Nope, if you check the link, it'll search for `is:open label:"Up for Grabs" ` :smile:

**Comment by khellang** [comment]
> IIRC, last time I checked, 'up-for-grabs' was more common.

Not sure that'll work, since the label itself is "Up for Grabs".

**Comment by adamralph** [comment]
Yep, my comment was out of context. I should probably have a look at the PR
rather than blindly replying by email :smiley:. It was a comment about the
name of the label itself.

**Comment by aochagavia** [comment]
@khellang I have updated the commit with your link :wink:

**Pull request closed without merging**
