### PR TITLE
Updating Microsoft.DiaSymReader to v1.0.6 and System.Collections.Immutable to v1.1.37

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @tmat, @jasonmalinowski

**Comment by tannergooding** [comment]
FYI. @jmarolf, @heejaechang

**Comment by tannergooding** [comment]
test Linux please

**Comment by tannergooding** [comment]
Merging preliminarily. I have tested locally and we need to get a signed build completed so this cannot wait until the build queues empty out.

**Comment by jasonmalinowski** [comment]
:+1:. It looks like there's some redundancy we can clean up in our project.json files and other things, but I don't think you made anything worse.

**Pull request merged**
