### PR TITLE
Support structure guides for #if directives

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/10426

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@akhera99 ptal.  thanks!

**Comment by ryzngard** [comment]
Screenshot please :)

**Comment by CyrusNajmabadi** [comment]
@ryzngard 

image

image

**Comment by CyrusNajmabadi** [comment]
@ryzngard plz.

**Review by akhera99 — APPROVED** [review]

**Pull request merged**
