### PR TITLE
Pass NoBuild=true to Publish step

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar

**Comment by tmat** [comment]
@nguerrera FYI: Setting NoBuild is needed after all...

**Comment by nguerrera** [comment]
Please explain why. Does this always run after build or sometimes it is invoked on its own?

**Comment by tmat** [comment]
`_PublishILAsm` has `BeforeTargets="AfterBuild"`, which means it will be triggered whenever `Build` target is executed. When `Publish` target executes `Build` target leading to circular target dependency and the build fails.

**Comment by nguerrera** [comment]
ah, circular dependency. How did this get passed CI the first time?

**Comment by tmat** [comment]
Two different PRs got merged, both CIs started building without knowing of the other change.

**Comment by CyrusNajmabadi** [comment]
i think this impacting several of my PRs.  Would it be possible to merge this in tonight?

**Comment by CyrusNajmabadi** [comment]
@nguerrera @jaredpar can you merge this in?  thanks!

**Comment by jaredpar** [comment]
@CyrusNajmabadi done

**Pull request merged**
