### PR TITLE
[ask mode]Remove unwanted public APIs and enable public API analyzers for Interactive (Editor) Features

### PR DESCRIPTION
**Pull request by tmat**
We had a few public types in InteractiveFeatures and InteractiveEditorFeatures. This change makes all of them internal.

### CODE REVIEW

**Comment by tmat** [comment]
[ask mode] @ManishJayaswal @MattGertz

**Comment by ManishJayaswal** [comment]
:+1: as long as the CI checks are passing :-)

**Comment by tmat** [comment]
@ManishJayaswal Sure. Seems like git merge went wrong.

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
test mac please

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
test vsi please

**Pull request merged**
