### PR TITLE
Fix issue where we could not goto-def on a generic instantiation.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/17360

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Preemptively merging in.  Let me know if there are any issues you want me to address.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Tests? And I'm surprised that code is even involved in F12 at all...?

**Comment by danielcrabtree** [comment]
I just upgraded VS2017, but am still experiencing issue #17360. Just wondering if #17360 is supposed to be fixed in VS2017 version 15.1 (26403.00) or if this fix isn't merged that far yet?

**Comment by Pilchie** [comment]
I would expect this fix to show up in version 15.3.

**Comment by Spongman** [comment]
ugh. can you ship this yesterday?

**Comment by Joelasaur** [comment]
I'm with Spongman. When is this getting shipped? Visual Studio is useless to me without F12

**Comment by tcsmith** [comment]
Any updates on this?

All of my google-fu'ing has led me to this thread. I've tried many proposed solutions to no avail. most recently this post: https://stackoverflow.com/questions/33029127/go-to-definition-cannot-navigate-to-the-symbol-under-the-caret (which led me here). 

i've gone through every step in that post. removed all extensions, removed other version of Visual Studio (2015 is left), signed out of my MSDEV account in VS. created a brand new C# console application and F12/Go To Definition/Implementation is brokedid. 

I have a newly imaged machine that is fine. two other machines that have seen "heavy VS" use are exhibiting the bugged behavior.

haaaaaaaaaaaaaaaaaaaaaaaaaaaaaallllllllllllp!

**Comment by danielcrabtree** [comment]
This issue was fixed for me in version 15.3 of Visual Studio 2017.

**Comment by Joelasaur** [comment]
Yeah i believe i fixed mine by reinstalling a new version and re compiling
my project.

**Comment by tcsmith** [comment]
Thanks for the responses.

The tech stack we are working with is currently tied to VS 2015 so I cannot upgrade.
Tried a full uninstall/reinstall and still have the bug.

I'll live with it till we can upgrade
:'(

**Pull request merged**
