### PR TITLE
Parse a pointer to an array correctly.

### PR DESCRIPTION
**Pull request by YairHalberstadt**
See #33482

### CODE REVIEW

**Comment by YairHalberstadt** [comment]
@gafter

**Comment by CyrusNajmabadi** [comment]
I feel like this would need a *ton* more tests.  ScanType is used is *numerous* codepaths (including speculative ones).  So to ensure it doesn't regress anything, i'd really like examples for pretty all those paths taht shows this is ok.

**Comment by YairHalberstadt** [comment]
Specifically cases where the actual intent is to parse Asterisk as a multiplier?

**Comment by YairHalberstadt** [comment]
@CyrusNajmabadi
Looking at the code more closely, I confused ScanType and ParseTypeCore.
I only changed ParseTypeCore, and that seems to have been sufficient for my test case - I will look to see if there are any cases where I will also need to modify ScanType.
Is changing ParseTypeCore less risky than ScanType?

**Comment by YairHalberstadt** [comment]
I will close for now then, till I have a chance to more thoroughly test the change.

**Pull request closed without merging**
