### PR TITLE
17.5 port: WithFrozenPartialSemantics freezing linked documents (#66904)

### PR DESCRIPTION
**Pull request by arkalyanms**
Port #66904 into 17.5

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Approved, as long as this was a pure port without any manual changes after that.  if there were manual changes, please point them out to get extra attention on that.  Thanks! :)

**Comment by arkalyanms** [comment]
> Approved, as long as this was a pure port without any manual changes after that. if there were manual changes, please point them out to get extra attention on that. Thanks! :)

Just a cherry pick. Thanks for the approval!

**Review by akhera99 — APPROVED** [review]

**Comment by genlu** [comment]
this seems to be a bug in GitHub?

image

**Pull request merged**
