### PR TITLE
Make OSX 10.11 usage explicit (#17483)

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by Pilchie** [comment]
@mmitche what is up with this change?  It looks like it has unexpected changes?

**Comment by mmitche** [comment]
@Pilchie I think someone force pushed to that branch....let me update.

**Comment by mmitche** [comment]
@Pilchie Actually looks like it got rebased against master and has the correct stuff in it now.

**Pull request closed without merging**
