### PR TITLE
added abstraction in remote host and diagnostic service to prevent VS…

### PR DESCRIPTION
**Pull request by heejaechang**
….Next dll from loading if remote host option is off.

the abstraction I added here is specific to diagnostic service feature. that abstract solely exist to prevent VS.Next dll from loading if remote host option is off.

this is different than IHostSpecificService abstraction I used to have that is generalized form of this abstraction which automatically figure out what to load based on option and layering/MEF composition of roslyn.

in this model, each feature need to take care of this kind of issue.

### CODE REVIEW

**Comment by heejaechang** [comment]
@Pilchie this is port of the change you reviewed for preview 4.

@mavasani @srivatsn @panopticoncentral can you take a look?

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p2_open_prtest/365/
// Retest reason:

**Comment by srivatsn** [comment]
:shipit:

**Comment by srivatsn** [comment]
Tagging @panopticoncentral since we'll need to do this for CodeLens as well.

**Comment by Pilchie** [comment]
Thanks @heejaechang!

**Pull request merged**
