### PR TITLE
Be consistent with placement of attributes in tests.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
We have about 30k tests in this style, and 2000 not.  So i'm just bringing up the 2k that are different in line with the rest.

### CODE REVIEW

**Comment by tmat** [comment]
I don't think there is much value in enforcing/maintaining a single style for this.

What happens if you need multiple work items?

**Comment by tmat** [comment]
I'd be for moving Trait attributes from methods to their containing classes. Most of the time all tests within a class have the same traits.

**Comment by CyrusNajmabadi** [comment]
> I'd be for moving Trait attributes from methods to their containing classes. Most of the time all tests within a class have the same traits.

WFM.

**Comment by CyrusNajmabadi** [comment]
> This style doesn't work for all cases and it's not worth unifying on.

This is the style we do use for the vast majority of cases.  And this is only making consistent for the ones that don't fall into outlier buckets (i.e. skipped facts).

This is how we often do style. simple non-outliers are don't consistently. The corner cases aren't controlled by style and can deviate as necessary for readability.

**Comment by CyrusNajmabadi** [comment]
> What happens if you need to list multiple work items?

I don't touch that case.  So nothing happens.  You can list mulitple work items however you want.  General pattern is to give each its own line.

> What do you do for Theory with multiple InlineData?

I haven't touched theories.  So nothing happens.  I can investigate if there are common patterns we use with theories to align those.

> What if the fact is skipped, so the fact attribute gets longer and now WorkItem gets pushed even further to the right?

I don't touch skipped facts.  So nothing happens.  

Effectively the pattern is about being consistent with our simple tests (i.e. those that are a `fact + workitem` or `fact + trait`).  The vast majority of these are written one way, and this just brings the outliers in line with them.  More complex cases can remain complex.

**Comment by tmat** [comment]
My issue with this is that when I need to skip a test, add another workitem, make a theory, etc. I now need to change the style from `[A,B]` to `[A]\n[B]\n[new attr]`. If we kept `[A]\b[B]` there is no change in style necessary.

**Comment by CyrusNajmabadi** [comment]
Closing out.  No Consensus on what we want here.

**Pull request closed without merging**
