### PR TITLE
Verify lock files are correct

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @agocke, @tannergooding, @TyOverby

**Comment by jaredpar** [comment]
retest all please

**Comment by DustinCampbell** [comment]
cute :smile:

:+1:

**Comment by TyOverby** [comment]
LGTM

**Comment by jaredpar** [comment]
retest all please

**Comment by agocke** [comment]
@jaredpar Maybe it's worth passing -nocache to nuget restore when we do this? There have been some instances where packages are deleted but we don't notice because every machine has the packages cached.

**Comment by tannergooding** [comment]
+1, modulo @agocke comment.

@jaredpar, this is currently failing because it is catching some project.lock.json changes which were not checked in at some point (which means your PR is doing exactly what it should :))

**Comment by jaredpar** [comment]
@agocke which restore should we be passing -nocache to?

**Comment by jaredpar** [comment]
test unit32 please

**Comment by jaredpar** [comment]
test unit64 please

**Comment by jaredpar** [comment]
@tannergooding what do I need to type to retest these failed ones?

**Comment by tannergooding** [comment]
test unit64 please

**Comment by tannergooding** [comment]
@jaredpar, Could you try the test unit32 phrase again. I believe you hit a window when I was regenerating the jobs (the jobs weren't automatically kicking off for external PRs).

**Comment by jaredpar** [comment]
test unit32 please

**Comment by jaredpar** [comment]
@tannergooding whatever you did fixed it ;)

**Comment by jaredpar** [comment]
test unit32 please

**Comment by jaredpar** [comment]
test mac please

**Pull request merged**
