### PR TITLE
[17.6] Only send workspace/configuration request when client supports that

### PR DESCRIPTION
**Pull request by Cosifne**
Fix https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1778595
Need to validate before merged.

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]
I think this will need QB approval?  cc @phil-allen-msft

**Comment by Cosifne** [comment]
> I think this will need QB approval? cc @phil-allen-msft

Yes, I will ping phil later offline

**Comment by Cosifne** [comment]
Verified https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/464384

**Pull request merged**
