### PR TITLE
Use command line args to describe options

### PR DESCRIPTION
**Pull request by mattwar**
Changes the MSBuildWorkspace internal project file abstraction to communicate project options via compiler command line args instead of the existing data structure with fixed layout. Ideally, this will be more flexible in the future for other project types beyond msbuild, so that this service can be used with other kinds of workspaces.  Also, it forces us to use the command line parsers to resolve all files, etc, so we don't get diverging logic between workspaces and compilers.

@Pilchie @jasonmalinowski please review.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Possible Reviewers: @balajikris, @basoundr, @brettfo, @DustinCampbell, @dpoeschl

**Comment by balajikris** [comment]
looks like `ICommandLineParserService` is not defined. Missed a file?

**Comment by mattwar** [comment]
anybody want to offer any feedback?  I've got cookies.

**Comment by mattwar** [comment]
@jaredpar  you may review at your leisure

**Comment by jaredpar** [comment]
LGTM

**Pull request merged**
