### PR TITLE
Adds NewLinesForBracesInProperties option.

### PR DESCRIPTION
**Pull request by mkrueger**
Fixes Issue #84.

Just a possible way of handling the formatting. (Howver unit tests are missing and should be added)

### CODE REVIEW

**Comment by pharring** [comment]
@dotnet-bot retest this, please.
@DustinCampbell @Pilchie, @dpoeschl does this look like something we'd accept?
If so, @mkrueger, it needs unit tests.

**Comment by mkrueger** [comment]
The problem is that I can't run roslyn from inside md :/.

Treat that as proposal.

**Comment by sharwell** [comment]
I would think it also needs to include a corresponding change to [NewLinesViewModel.cs](https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/CSharp/Impl/Options/Formatting/NewLinesViewModel.cs) and a few other places?

**Comment by DustinCampbell** [comment]
@pharring This is probably something we'd accept. We've chatted with @mkrueger about this particular option already.

@sharwell You're right. I'm comfortable with having some formatting options in the workspace layer that aren't threaded through to IDE, but this one probably should be.

**Comment by Pilchie** [comment]
@mkrueger - what do you think - can you add some tests for this?

**Comment by mkrueger** [comment]
If you can make monodevelop loading the project + the ms tests :/.

ATM I have no way running it.

**Comment by Pilchie** [comment]
We don't have any mstest based tests, we use xunit.  You should be able to install the xunit.runners package (done as part of `MSBuild BuildAndTest.proj`) and then use packages\xunit.runners.2.0.0-alpha-build2576\tools\xunit.console.x86.exe to run the tests.

(Also spoke to @jaredpar - we just just restore the runners package directly instead of waiting for you to run MSBuild BuildAndTest.pro)

**Comment by mkrueger** [comment]
I'll look at it.

**Comment by gafter** [comment]
Note that there is no contributor agreement for this PR. It is also quite stale.

**Comment by mkrueger** [comment]
We still have problems with the roslyn project on monodevelop :/ - as said regard that as proposal.

**Pull request closed without merging**
