### PR TITLE
Do not show "Convert to raw string" refactoring for C# version lower than 11

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Fixes: https://github.com/dotnet/roslyn/issues/63592

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
@davidwengier Please help me with integration tests here. They all currently setup test project with `<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>`, so they expectedly fail after my change. I tried to fix them myself, but I didn't find any "easy" switch for language version ot target framework. @CyrusNajmabadi suggested you to ask help from.

**Comment by davidwengier** [comment]
If you want to change the project that the integration tests create, you can pass the project template name into the base constructor call [here](https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpCodeActions.cs#L26). I'm getting you want [`WellKnownProjectTemplates.CSharpNetCoreClassLibrary`](https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/IntegrationTest/TestUtilities/WellKnownProjectTemplates.cs#L15)

The project template is the same for all tests in the class, so you might need to separate out the failing test to its own class, if the change inroduces a problem with a different test. See if it passes after changing the project template I guess :)

**Comment by DoctorKrolic** [comment]
Well, on my machine `WellKnownProjectTemplates.CSharpNetCoreClassLibrary` creates `net6.0` project, which is still not enough. Will see how it shows itself in CI, but I genuinely think the result won't change there

**Comment by DoctorKrolic** [comment]
Well, my hypothesis seems to be tue, because both raw-string-related integration tests failed. Now I need to bump language version to `11` in the generated test project. @davidwengier Are there any "legal" ways of doing it? Because I have an idea to just open `.csproj` in the editor during the test and paste whatever I need, but it seems like a VERY dirty hack to me

**Comment by davidwengier** [comment]
Sorry, last night when I read your comment I was thinking only of target frameworks, and forgot entirely about language versions, which yes, you also need. There is no API for changing LangVersion I'm aware, or certainly not one that is exposed in our existing integration test services. Your best bet is either to do as you say, and open the file and update its contents, or if it were up to me, you could also just skip the tests because presumably in November when .NET 7 is released, they'll start passing.

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
Just realized this is a refactoring.  We always want to offer this to the user. Users who have heard about raw strings can then use this refactoring to try the feature out. When they do, they'll then get the message about upgrading. Current code is working as intended. 

Note: this does not apply to analyzers/fixers. They should respect the lang version.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Should the following check be removed then?

https://github.com/dotnet/roslyn/blob/9768ab693a6efeb6dda75fad1f1cb50c129cf1d0/src/Features/CSharp/Portable/ConvertProgram/ConvertToTopLevelStatementsCodeRefactoringProvider.cs#L37-L38

**Pull request closed without merging**
