### PR TITLE
Prevent NaN from slipping into .Measure calls.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/8514

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Code was signed off on in: https://github.com/dotnet/roslyn/pull/8471

I'm just extracting it out so we can get the fix in independent of the NuGet work.

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/vsi/p2 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/vsi/p2 please

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/241/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/241/
// Retest reason:

**Comment by davkean** [comment]
Looks like one of the tests timed out for vsi p2.

**Pull request merged**
