### PR TITLE
Move VSTelemetryLoggerTests to a closed source test project

### PR DESCRIPTION
**Pull request by rchande**
This tests closed-source components, so it's easiest to move it out of the open.

### CODE REVIEW

**Comment by rchande** [comment]
There's a corresponding review in CodeFlow for the new test project.

**Comment by rchande** [comment]
@Pilchie and @dpoeschl  reviewed meat of this which is closed source

cc @jasonmalinowski @basoundr @balajikris @brettfo

**Comment by dpoeschl** [comment]
retest this please

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by dpoeschl** [comment]
LGTM

**Pull request merged**
