### PR TITLE
Merging master into features/embeddedRegex

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv .  Just keeping this branch up to date.  Finally got through the unicorn.  Thanks!

**Comment by CyrusNajmabadi** [comment]
@jcouv can you merge this quickly before anything else goes into master :)  It's really just a merge commit, so reviewwise, there's nothing much to so.

**Comment by jcouv** [comment]
Merged, but it looks like there was a legitimate break in the correctness leg:
https://ci.dot.net/job/dotnet_roslyn/job/features_embeddedJson/job/perf_correctness_prtest/78/console

Try a dummy PR on top of this branch to confirm.

**Comment by CyrusNajmabadi** [comment]
Will do.  Not sure what's up with perf_correctness.  I can't imagine how a merge would impact that.  @agocke and @jaredpar for some insight here.

**Pull request merged**
