### PR TITLE
Ignore completion item span

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/34952

This is currently mutable, which makes sharing completion items hard.  Now, instead, we just track the completion span we are told on the completion context and pass that along at the end when making changes. That helps ensure completion items can be safely shared across invocations.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@genlu @jasonmalinowski @ivanbasov @dpoeschl Need eyes on https://github.com/dotnet/roslyn/pull/34974/commits/430865b87cf71303bfd9821d45bbe1e94c0d0d7e

**Comment by CyrusNajmabadi** [comment]
Note: this should have a followup PR where we:

1. Obsolete the existing methods i'm adding overloads for.
2. Obsolete CompletionItem.Span 
3. Make the new methods public.

Most users will be fine.  This is mostly so that if anyone ends up using the new 'add import' completion items that things will be ok.

**Comment by ivanbasov** [comment]
>             CancellationToken cancellationToken = default)

maybe we should mark this overload as obsolete

---
Refers to: src/Features/Core/Portable/Completion/CompletionService.cs:122 in 9205c57. [](commit_id = 9205c57334f558ecb52aa9f97c182e02818d0eaf, deletion_comment = False)

**Comment by genlu** [comment]
We can close this now, all changed merged in #34808

**Comment by genlu** [comment]
> 
    Obsolete the existing methods i'm adding overloads for.
    Obsolete CompletionItem.Span
    Make the new methods public.

@jasonmalinowski @ivanbasov DO we want to do this in master now?

**Comment by jasonmalinowski** [comment]
Are the existing APIs we're doing that to public?

**Comment by genlu** [comment]
Yes. `CompletionItem`, `CompletionProvider` and `CompletionService` are all public

**Pull request merged**
