### PR TITLE
Add indent guides for C# and VB blocks - With simplified block types.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide Please review this PR instead. it subsumes #14227

**Comment by CyrusNajmabadi** [comment]
test windows_debug_unit32_prtest

**Comment by CyrusNajmabadi** [comment]
test windows_release_unit64_prtest

**Comment by paulvanbrenk** [comment]
tagging @aozgaa

**Comment by jmarolf** [comment]
:shipit:

**Pull request merged**
