### PR TITLE
Make CodeLens APIs public

### PR DESCRIPTION
**Pull request by panopticoncentral**
The consumer of the CodeLens API will be in VS, so it will need to be a public API. I'm not sure how much XML documentation I need to add, particularly with making Glyph public. Plus, if there are issues with making APIs public, let me know.

@heejaechang @CyrusNajmabadi

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @mattwar 

I'm not comfortable making these public.  Once public, we can't change them.  Can we instead just grant permission to use these APIs to the requisite VS services using InternalsVisibleTo?

**Comment by panopticoncentral** [comment]
@dotnet/roslyn-ide @mattwar  @CyrusNajmabadi Sure, I have no issue with that, I didn't know that we can do that. So it's just a matter of putting the correct IDE assembly in the IVT list?

**Comment by AdamSpeight2008** [comment]
@panopticoncentral @CyrusNajmabadi  Even if they are `internal` better documentation on VS APIs is still beneficial for those learning from the repo.

**Comment by mattwar** [comment]
There is a process for getting API's to be public, and that usually is offering me treats and waiting a long time.

**Pull request closed without merging**
