### PR TITLE
VB init-only: add tests for ReDim, Erase and dictionary access.

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by jaredpar** [comment]
@AlekseyTs we should retarget this to `release/dev16.9` as the snap has occurred. Would like to have the additional testing there in case we need any last minute bug fixes in the feature.

**Comment by AlekseyTs** [comment]
> we should retarget this to release/dev16.9

Done

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Review by jaredpar — APPROVED** [review]

**Comment by jcouv** [comment]
@jaredpar I assume we need to wait for the yellow approval label before merging into release branch?

**Comment by jcouv** [comment]
Never mind. This is a test-only change. We don't usually need approval.

**Pull request merged**
