### PR TITLE
Ensure rename works for property pattern members

### LINKED ISSUE #9079: Rename does not update usages in complex patterns.
```c#
    public class Expression { }
    public class Constant : Expression
    {
        public readonly int Value;
        public Constant(int Value)
        {
            this.Value = Value;
        }
    }
    public class Plus : Expression
    {
        public readonly Expression Left, Right;     // rename Left here.
        public Plus(Expression Left, Expression Right)
        {
            this.Left = Left;
            this.Right = Right;
        }
    }
    public class X
    {
        public static void Main()
        {
            Expression expr = new Plus(new Plus(new Constant(1), new Plus(new Constant(2), new Constant(3))), new Constant(6));

            if (expr is Plus { Left is Plus p,Right is Constant c })
            {
            }
```

Renaming Plus.Left does not update reference in the complex pattern.

### PR DESCRIPTION
**Pull request by gafter**
Closes #9079 #9080

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-ide @CyrusNajmabadi Please review.

**Comment by CyrusNajmabadi** [comment]
I'd also like specific tests that renaming the type itself happens to rename the usage of the type in the pattern.

**Comment by CyrusNajmabadi** [comment]
:+1: Once that test is added.

**Comment by gafter** [comment]
@CyrusNajmabadi How about now?

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by DustinCampbell** [comment]
:+1:

**Pull request merged**
