### PR TITLE
Exclude VS-related packages on non-Windows

### PR DESCRIPTION
**Pull request by mmitche**
If Roslyn.sln is built on Unix with --ci and --configuration Release, the build will fail in this target, as some files aren't avaialable. These files aren't available because some dependent project functionality doesn't run if VS SDK tooling isn't available. Conditionalize to windows.

### CODE REVIEW

**Comment by mmitche** [comment]
@jaredpar I don't love this fix, but it should work. It's generally trying to get to the heart of "is vs tooling avaialble and associated targets are running", There is another property for this VSToolsPath, but it's defined internally in the VS SDK packages so I didn't like using it here.

**Comment by jaredpar** [comment]
Could we instead just exclude those projects when building in Linux? I'm happy to disable a bit of the repo in that case because the build just doesn't make sense.

**Comment by mmitche** [comment]
> Could we instead just exclude those projects when building in Linux? I'm happy to disable a bit of the repo in that case because the build just doesn't make sense.

Yeah, let's do that. Do you have a preference on how that's done? Solution filter for roslyn.sln (Roslyn-Unix.slnf?) or a few projects with ExcludeFromBuild conditioned on OS?

**Review by jaredpar — APPROVED** [review]

**Comment by mmitche** [comment]
I had to turn static graph on for non-Windows to get this to work properly. Because of (it appears) some manual imports of arcade Sdk props files, the target _IsProjectrestoreSupported doesn't get created as an empty target when a build is excluded. This is fine for static graph restore, but bad for non-static restores.

**Comment by mmitche** [comment]
Oh good gracious. Prebuilts?

**Comment by mmitche** [comment]
Timeouts are unrelated to the non-windows infra changes and showing up in other jobs.

**Pull request merged**
