### PR TITLE
Fix flaky ForegroundNotificationServiceTests.Test_Delay

### PR DESCRIPTION
**Pull request by davkean**
Fixes: #7512

This test has been changed twice, first time was using DateTime, second was using Stopwatch. From my testing, both have a slightly different opinion than to Environment.TickCount as to how long has passed by 1 - 3 milliseconds. Environment.TickCount on my box has a resolution of 15/16 milliseconds accuracy, but Stopwatch and DateTime both found that these same 15/16 milliseconds took between 14 -> 16 milliseconds.

Instead of accounting for this, I just changed this test to use the same clock as the underlying service.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-ide @srivatsn

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by jmarolf** [comment]
:+1:

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5314/
// Retest reason: https://github.com/dotnet/roslyn/issues/8975

**Pull request merged**
