### PR TITLE
Spelling fixes, mostly in VB compiler

### PR DESCRIPTION
**Pull request by bkoelman**
@Pilchie can you tag some people from the VB team for review?

### CODE REVIEW

**Comment by jaredpar** [comment]
test mac please

**Comment by jaredpar** [comment]
:+1: 

CC @dotnet/roslyn-compiler

**Comment by gafter** [comment]
:+1:

**Comment by bkoelman** [comment]
I just rebased on latest version from master, because this PR did not automerge anymore. Now the windows test is failing. It fails with:

`Commit changed dependencies without updating project.lock.json`

I'm not sure what is causing this or how to resolve. Can anyone help out here?

**Comment by jaredpar** [comment]
test windows 32 please

**Comment by jaredpar** [comment]
test win32 please

**Comment by jaredpar** [comment]
test unit32 please

**Comment by jaredpar** [comment]
@bkoelman we've had some issues recently with our lock files changing unexpectedly.  I kicked off another run of your job to see if this is just another instance of that showing up.

**Comment by bkoelman** [comment]
@jaredpar :+1:

**Pull request merged**
