### PR TITLE
Remove NuGetPackageResolver implementation

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@tmat, @ManishJayaswal, @amcasey, @kevinh-ms, @genlu, @kuhlenh

**Comment by KevinH-MS** [comment]
:cry: farewell, sweet impl...

:+1:

**Comment by tmat** [comment]
@cston I have merged the change, need to rebase against it.

**Comment by filipw** [comment]
why is this gone? no nuget package support in Update 1?

**Comment by tmat** [comment]
@filipw That is correct. Update 1 (v1 of scripting) is not going to ship with NuGet support. Due to various technical difficulties we haven't had enough time to deliver a high-quality implementation and end-to-end experience, so we decided to postpone NuGet support to the next release.

**Comment by filipw** [comment]
:+1:

**Comment by malekpour** [comment]
Any plan to add NuGet support again?

**Comment by tmat** [comment]
We will look into it again.

**Pull request merged**
