### PR TITLE
Use Document.GetOptionsAsync instead of Document.Project.Solution.Options

### LINKED ISSUE #17042: .editorconfig settings being ignored in some refactorings
The following places look like they're touching solution options when they should be using document options:

- src/Features/CSharp/Portable/ExtractMethod/CSharpMethodExtractor.CSharpCodeGenerator.cs
- src/Features/CSharp/Portable/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider
- src/Features/CSharp/Portable/UseExpressionBody/AbstractUseExpressionBodyCodeFixProvider.cs

FYI to @kuhlenh and @Pilchie

Also reported in https://developercommunity.visualstudio.com/content/problem/24588/useexpressionbodyformethodscodefixprovider-faillin.html

### PR DESCRIPTION
**Pull request by Pilchie**
Fixes #17042.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski and @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
@jasonmalinowski I can't tell why your commit is showing up in this PR :-/

**Comment by Pilchie** [comment]
Wait, I understand now.  Give me a second.

**Comment by Pilchie** [comment]
Fixed

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by Pilchie** [comment]
Note - windows_debug_unit64_prtest passed at https://ci.dot.net/job/dotnet_roslyn/job/post-dev15/job/windows_debug_unit64_prtest/672/, but failed to update status on GitHub.

**Pull request merged**
