### PR TITLE
adding telemetry for completion commit

### PR DESCRIPTION
**Pull request by heejaechang**
this will help us track some ratio such as completion commit/dismiss

### Customer scenario

There is no user experience impact by this

### Bugs this fixes

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/640207

### Workarounds, if any

N/A

### Risk

Low. it is not even per keystroke. it will be 1 per each completion committed

### Performance impact

Low. same as risk.

### Is this a regression from a previous update?

No

### Root cause analysis

we didn't send one before. we just tracked whether we showed completion or not. but now we want to see whether users once saw completion, whether they dismiss or commit completion. 

this telemetry doesn't include what user committed just whether he committed or not.

### How was the bug found?

feature usage analysis

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph @dpoeschl can you take a look? confirmed with shengyu that this works for him

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4 (Once Green)

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is jenkins test down?

**Comment by jasonmalinowski** [comment]
@heejaechang There was a delay with the Preview 4 branch, but it's catching up.

**Pull request merged**
