### PR TITLE
[Workspaces] DocumentInfo never set IsGenerated value

### PR DESCRIPTION
**Pull request by DavidKarlas**
Looks like bug to me...

More baby steps :)

### CODE REVIEW

**Comment by pharring** [comment]
Interesting. This change looks correct, but it brings up a few issues:
1. I couldn't find anywhere else where IsGenerated was set, so that implies that no code is exercising this path. Which means that, as it stands today, the IsGenerated property is always false and might as well be deleted. It's referenced in [exactly one place](http://index/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/DocumentInfo.cs,13a31ffc22701d7a,references).
2. There's no unit test exercising this property.
3. The .With method [line 93] (http://index/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/DocumentInfo.cs,93) probably needs updating to test for and propagate the isGenerated property.

@DavidKarlas Are you able to address any of those issues?

**Comment by tmeschter** [comment]
Determining whether or not a file is generated is problematic, which is probably why this field is never set. We should remove this property entirely until we actually have a design for identifying and handling generated files.

**Comment by mattwar** [comment]
I'm surprised that this value is not getting set on DocumentInfo.  It was there for a purpose.  It actually solved a problem in the past.  MSBuild was changing time stamps (or regenerating) a few files it would add to the project each time the build was run (which equated to each time the project was opened) and that would throw off the version stamp calculation.  So either that behavior changed, or the features that relied on the version stamp changed.  Either way, the information was critical at some point.

**Comment by DavidKarlas** [comment]
Maybe check also references to IsGenerated property from VisualStudio source code (http://source.roslyn.codeplex.com/ covers only Roslyn)

About 1,2,3 points...
1. It's up to you guys, I just noticed it's never set, because I was trying to figure out what is used for :)
2. Since I'm not sure what is used for... What unit tests can I write? To see if it's set properly?
3. I can add that. No problem if you guys decide to keep it...

**Comment by mattwar** [comment]
Well, it's clearly wrong in its current state and the pull request fixes it. Any further issue with whether the property should exist or not is a separate issue.

**Pull request merged**
