### PR TITLE
Ensure that SemanticModel binds with an IncrementalBinder if result of the binding is added to the cache.

### LINKED ISSUE #1504: Assertion failed in MemberSemanticModel.NodeMapBuilder.AddToMap
Repro:
Run test ```RudeEditStatementTests.Lambdas_Insert_CatchFilter1```.

Call stack:

```
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.NodeMapBuilder.AddToMap(Microsoft.CodeAnalysis.CSharp.BoundNode root, System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CSharp.BoundNode>> map, Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node) Line 105	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GuardedAddBoundTreeAndGetBoundNodeFromMap(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode syntax, Microsoft.CodeAnalysis.CSharp.BoundNode bound) Line 1043	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetEnclosingBinderInternal(int position) Line 1187	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingBinder(int position) Line 1000	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetEnclosingBinderInternal(int position) Line 150	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingBinder(int position) Line 1000	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbol(int position, System.Threading.CancellationToken cancellationToken) Line 4181	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingSymbolCore(int position, System.Threading.CancellationToken cancellationToken) Line 4650	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetEnclosingSymbol(int position, System.Threading.CancellationToken cancellationToken) Line 739	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.ReportLambdaSignatureRudeEdits(Microsoft.CodeAnalysis.SemanticModel oldModel, Microsoft.CodeAnalysis.SyntaxNode oldLambdaBody, Microsoft.CodeAnalysis.SemanticModel newModel, Microsoft.CodeAnalysis.SyntaxNode newLambdaBody, System.Collections.Generic.List<Microsoft.CodeAnalysis.EditAndContinue.RudeEditDiagnostic> diagnostics, out bool hasErrors) Line 3178	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.ReportLambdaAndClosureRudeEdits(Microsoft.CodeAnalysis.SemanticModel oldModel, Microsoft.CodeAnalysis.SyntaxNode oldMemberBody, Microsoft.CodeAnalysis.ISymbol oldMember, Microsoft.CodeAnalysis.SemanticModel newModel, Microsoft.CodeAnalysis.SyntaxNode newMemberBody, Microsoft.CodeAnalysis.ISymbol newMember, System.Collections.Generic.IReadOnlyDictionary<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.LambdaInfo> matchedLambdasOpt, Microsoft.CodeAnalysis.EditAndContinue.BidirectionalMap<Microsoft.CodeAnalysis.SyntaxNode> map, System.Collections.Generic.List<Microsoft.CodeAnalysis.EditAndContinue.RudeEditDiagnostic> diagnostics, out bool newBodyHasLambdas, System.Threading.CancellationToken cancellationToken) Line 2582	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.AnalyzeSemantics(Microsoft.CodeAnalysis.Differencing.EditScript<Microsoft.CodeAnalysis.SyntaxNode> editScript, System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.Differencing.EditKind> editMap, Microsoft.CodeAnalysis.Text.SourceText oldText, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.EditAndContinue.ActiveStatementSpan> oldActiveStatements, System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<Microsoft.CodeAnalysis.SyntaxNode, Microsoft.CodeAnalysis.SyntaxNode>> triviaEdits, System.Collections.Generic.List<Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.UpdatedMethodInfo> updatedMethods, Microsoft.CodeAnalysis.SemanticModel oldModel, Microsoft.CodeAnalysis.SemanticModel newModel, System.Collections.Generic.List<Microsoft.CodeAnalysis.Emit.SemanticEdit> semanticEdits, System.Collections.Generic.List<Microsoft.CodeAnalysis.EditAndContinue.RudeEditDiagnostic> diagnostics, System.Threading.CancellationToken cancellationToken) Line 2170	C#
 	Roslyn.Services.Editor.UnitTests.dll!Microsoft.CodeAnalysis.EditAndContinue.UnitTests.EditAndContinueTestHelpers.VerifySemantics(Microsoft.CodeAnalysis.Differencing.EditScript<Microsoft.CodeAnalysis.SyntaxNode> editScript, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.ActiveStatementsDescription activeStatements, System.Collections.Generic.IEnumerable<string> additionalOldSources, System.Collections.Generic.IEnumerable<string> additionalNewSources, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.SemanticEditDescription[] expectedSemanticEdits, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.RudeEditDiagnosticDescription[] expectedDiagnostics) Line 288	C#
 	Roslyn.Services.Editor.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemantics(Microsoft.CodeAnalysis.Differencing.EditScript<Microsoft.CodeAnalysis.SyntaxNode> editScript, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.ActiveStatementsDescription activeStatements, System.Collections.Generic.IEnumerable<string> additionalOldSources, System.Collections.Generic.IEnumerable<string> additionalNewSources, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.SemanticEditDescription[] expectedSemanticEdits, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.RudeEditDiagnosticDescription[] expectedDiagnostics) Line 83	C#
 	Roslyn.Services.Editor.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemantics(Microsoft.CodeAnalysis.Differencing.EditScript<Microsoft.CodeAnalysis.SyntaxNode> editScript, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.ActiveStatementsDescription activeStatements, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.SemanticEditDescription[] expectedSemanticEdits, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.RudeEditDiagnosticDescription[] expectedDiagnostics) Line 72	C#
 	Roslyn.Services.Editor.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.Extensions.VerifySemanticDiagnostics(Microsoft.CodeAnalysis.Differencing.EditScript<Microsoft.CodeAnalysis.SyntaxNode> editScript, Microsoft.CodeAnalysis.EditAndContinue.UnitTests.RudeEditDiagnosticDescription[] expectedDiagnostics) Line 63	C#
 	Roslyn.Services.Editor.CSharp.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.EditAndContinue.UnitTests.RudeEditStatementTests.Lambdas_Insert_CatchFilter1() Line 3053	C#
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #1504.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@VSadov, @gafter, @agocke, @jaredpar Please review.

**Comment by jaredpar** [comment]
LGTM

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Comment by gafter** [comment]
I suggest adding a compiler test, for example one from #1986. Other than that LGTM.

**Comment by AlekseyTs** [comment]
Incorporated tests from #1986.

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
It looks like merge build is failing due to 73b17e39a18ef99876f33f27ebd98daaa213ddc5

**Comment by VSadov** [comment]
LGTM. Nice!

**Pull request merged**
