### PR TITLE
share GetEffectiveSeverity between AnalyzerNode and service

### PR DESCRIPTION
**Pull request by heejaechang**
we use this to filter out running analyzer that only has hidden diagnostics in closed file. this will prevent us from running all simplifier analyzers in closed file which is useless since there is no visual indications for those diagnostics.

but those will show up once changed to other than hidden effective severity.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @tmeschter @srivatsn @shyamnamboodiripad can you take a look?

**Comment by sharwell** [comment]
I'm assuming this is intended to resolve the issue I reported?

**Comment by heejaechang** [comment]
@sharwell yes. I should have linked to the bug #2512

**Comment by heejaechang** [comment]
opened related issue #2598

**Comment by mavasani** [comment]
:+1: Thanks for opening the API bug.

@sharwell Issue #2598 should also make your current workaround for linked diagnostic descriptors a bit more cleaner. Once we add a public API to allow querying for effective severity of a descriptor, you can invoke that upfront in your analyzer for primary descriptor and suppress the entire analyzer if primary descriptor has effective severity None.

**Comment by heejaechang** [comment]
@dotnet-bot please re-run tests

**Comment by heejaechang** [comment]
@dotnet-bot test this please.

**Pull request merged**
