### PR TITLE
Fix a couple small errors in the microbuild scripts

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @tannergooding

**Comment by tannergooding** [comment]
These changes LGTM.

However, there is an additional failure:

```
D:\A\_work\193\s\src\Tools\MicroBuild\publish-assets.ps1 : Cannot process 
2016-07-08T16:05:38.7654184Z          argument transformation on parameter 'UploadNuGets'. Cannot convert value 
2016-07-08T16:05:38.7810434Z          "System.String" to type "System.Boolean". Boolean parameters accept only 
2016-07-08T16:05:38.7810434Z          Boolean values and numbers, such as $True, $False, 1 or 0.
2016-07-08T16:05:38.7810434Z              + CategoryInfo          : InvalidData: (:) [publish-assets.ps1], ParentCon 
2016-07-08T16:05:38.7810434Z             tainsErrorRecordException
2016-07-08T16:05:38.7810434Z              + FullyQualifiedErrorId : ParameterArgumentTransformationError,publish-ass 
2016-07-08T16:05:38.7810434Z             ets.ps1
```

It looks like, based on the arguments being passed (`-UploadNugets 1 -UploadVsixes 1 -UploadCoreXTPackages 1`) that the numeric value is being interpreted as a string 😄

**Comment by jaredpar** [comment]
@tannergooding hmm, all the more reason to add the `-test` parameter so we execute this script at validation time.  Would catch this.  Going to do this now.

**Comment by jaredpar** [comment]
@tannergooding  updated

**Pull request merged**
