### PR TITLE
Enable some `await` scenarios involving inline arrays

### PR DESCRIPTION
**Pull request by AlekseyTs**
Relates to test plan https://github.com/dotnet/roslyn/issues/67826

### CODE REVIEW

**Comment by cston** [comment]
>     static async Task<int> M1(C x) => x.F[await Task.FromResult(^10)];

Should this be `^await Task.FromResult(10)` instead?

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/InlineArrayTests.cs:1698 in b159d40. [](commit_id = b159d405a838a958cba6abb479f0e7176fc44f18, deletion_comment = False)

**Comment by cston** [comment]
>     static async Task<int> M1(C x) => GetC(x).F[GetRange()][await Task.FromResult(Get01(x))];

It looks like all the examples use `Task.FromResult()`. Does that mean these will execute synchronously? If so, consider testing one or more cases that execute asynchronously (perhaps with `Task.Yield;` for instance).

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/InlineArrayTests.cs:4262 in b159d40. [](commit_id = b159d405a838a958cba6abb479f0e7176fc44f18, deletion_comment = False)

**Review by jjonescz — APPROVED** [review]

**Comment by AlekseyTs** [comment]
>     static async Task<int> M1(C x) => x.F[await Task.FromResult(^10)];

Quite possibly

---
In reply to: [1539174134](https://github.com/dotnet/roslyn/pull/68129#issuecomment-1539174134) [](http://example.com/codeflow?ancestors=1539174134,1539174134)

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/InlineArrayTests.cs:1698 in b159d40. [](commit_id = b159d405a838a958cba6abb479f0e7176fc44f18, deletion_comment = False)

**Comment by AlekseyTs** [comment]
@cston I think I addressed your feedback

**Review by cston — APPROVED** [review]

**Pull request merged**
