### PR TITLE
Reduce unnecessary task allocations.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixing https://github.com/dotnet/roslyn/issues/15363

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide   This shaves off 600MB of allocations from the OOP process.

**Comment by asecchia** [comment]
750MB -> 170MB 

this is what's left after the change
Name                                                                                                                                                                                	Exc %	        Exc
Type System.Threading.Tasks.Task`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[Microsoft.CodeAnalysis.INamedTypeSymbol]]] 	  1.1	 73,806,144
Type System.Threading.Tasks.Task`1[Microsoft.CodeAnalysis.FindSymbols.SyntaxTreeDeclarationInfo]                                                                                    	  1.0	 72,839,848
Type System.Threading.Tasks.Task`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.FindSymbols.SymbolAndProjectId`1[Microsoft.CodeAnalysis.INamedTypeSymbol]]][] 	  0.4	 30,335,564

**Comment by Pilchie** [comment]
Worth taking to `master` @MattGertz?

**Comment by MattGertz** [comment]
Yeah, I've been following along with the e-mails.  Let's make sure to have a good write-up for the next perf epic.

**Pull request merged**
