### PR TITLE
Update Roslyn LKG toolset to RTM build 20150616.2

### PR DESCRIPTION
**Pull request by agocke**
As it sounds

@jaredpar

### CODE REVIEW

**Comment by agocke** [comment]
FYI I'm still grabbing a blank machine with only VS2013 to test this on, not that that will necessarily block this from going in.

**Comment by MattGertz** [comment]
Talk to @jaredpar and @ManishJayaswal on the timing for this.  This is approved but we will take a particular build.

**Comment by agocke** [comment]
The bad news is that this doesn't work for a machine with only VS2013 installed since the build task depends on assemblies in MSBuild 14. The other bad news is that the current package doesn't work either since building the build task requires MSBuild 14 being installed.

I'll look into whether or not we actually need MSBuild 14 to build the build task or if we can use a version-independent reference.

**Comment by agocke** [comment]
This has been updated to the new toolset. As soon as the build succeeds this will be merged.

**Comment by agocke** [comment]
The Linux and Mac builds have finished. Since the Windows build is essentially duplicated, I'm going to merge this now.

**Pull request merged**
