### PR TITLE
added an internal option to control whether we include custom symbol in bing search query or not

### LINKED ISSUE #4297: Data Leak in Bing-Powered Compiler Help
Hello!

The Bing-Powered Compiler help (see links below) will generate URLs to http://bingdev.cloudapp.net which include the original error text. This poses a major data leak, since it 
a) uses HTTP instead of HTTPS, sending the data for the wholer Internet to see, and 
b) includes member names from the code base where the error occurred. 

Since the code base can contain priviledged information, this is a significant roadblock for information sensitive companies, resulting in firewall lockdowns for the bingdev.cloudapp.net or, possibly, the policy of not being allowed to use VS2015 at all.

Please change the generated url to not include information about the local code base. I.e. the information filtering for Bing done by the BingUrl.svc will have to be incorporated into Roslyn.

Best regards, Michael

http://blogs.msdn.com/b/bingdevcenter/archive/2015/07/16/need-compiler-help-bing-in-visual-studio-brings-what-you-need-in-just-one-click.aspx

https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/Utilities/BrowserHelper.cs

### PR DESCRIPTION
**Pull request by heejaechang**
by default, we include custom type information in bing query but some customers are required not to leak any of those kinds of information out side of their own organization.

for them, we added internal option they can use to turn it off explicitly. there is no customer facing option for this, people who need this need to use registry.

fixes #4297

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @basoundr can you take a look? thank you

**Comment by heejaechang** [comment]
ping?

**Comment by heejaechang** [comment]
I talked with mark and bing team and this is what we decide to do (adding an option)

**Comment by MichaelKetting** [comment]
@heejaechang Thanks for fixing this! Since I didn't find any documentation: How do I enable the PutCustomTypeInBingSearch option? I'm guessing the Registry but where exactly does it go and is it a DWord or a String?

**Comment by heejaechang** [comment]
@MichaelKetting in HKCU\Microsoft\VisualStudio\<Hive>\Roslyn\Internal\Diagnostics
create DWORD Value - PutCustomTypeInBingSearch with value 0

**Comment by MichaelKetting** [comment]
Great, thanks, that did the trick :)

**Comment by MichaelKetting** [comment]
@heejaechang I've just installed Visual Studio 2017 and set the registry key again:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\15.0\Roslyn\Internal\Diagnostics
DWORD: PutCustomTypeInBingSearch = 0

The key no longer works. 

I've noticed that the registry entires for VS2017 are almost empty. Did the locations get moved? / Is Visual Studio longer using the regsitry?

**Comment by MichaelKetting** [comment]
Okay, I've figured it out (partialy):
The config is stored in a separate registry hive:
http://stackoverflow.com/questions/41119996/where-does-visual-studio-2017-rc-store-its-config

Adding the setting there will solve the immediate issue, but there is no longer a way to do this via administrative rollout. Do you guys have a story for that?

**Comment by heejaechang** [comment]
@MichaelKetting Hi. adding registry key still work as well, just it is not 15.0 anymore but 15.0_xxxx (where xxxx is per instance value)

about administrative rollout. let me get back to you.

**Comment by MichaelKetting** [comment]
@heejaechang Thanks, that one works! I could have sworn that I tried that one, too, but apparently, not.

**Pull request merged**
