### PR TITLE
Handle missing property

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@jmarolf, @amcasey see #6594

**Comment by jmarolf** [comment]
:+1:

**Comment by amcasey** [comment]
Is that the only thing that was being caught?  I thought it might also be guarding against failures during property eval.  I only suggested the change to eliminate the cost of the throw in an apparently common case.

**Comment by cston** [comment]
@amcasey If there are cases where property evaluation fails, we should probably handle those cases explicitly.

**Pull request merged**
