### PR TITLE
Port PR #7217 to stabilization

### PR DESCRIPTION
**Pull request by DustinCampbell**
This is the same as PR #7217 except that unit tests are updated to be synchronous since the unit test infrastructure has diverged in master. The same tests are there. They just aren't async.

Tagging @dotnet/roslyn-ide

### CODE REVIEW

**Comment by DustinCampbell** [comment]
retest prtest/win/dbg/unit32 please

**Comment by davkean** [comment]
This was the unit32 failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/1775/consoleFull#-126064114a82fefab-f698-416f-8fca-58544c94cd4e

**Comment by DustinCampbell** [comment]
retest prtest/mac/dbg/unit32 please

**Comment by DustinCampbell** [comment]
retest prtest/win/dbg/unit32 please

**Pull request merged**
