### PR TITLE
Fix dynamic parameter PR

### PR DESCRIPTION
**Pull request by jaredpar**
Responding to some feedback that occurred after pr #5447 was
merged.

### CODE REVIEW

**Comment by jaredpar** [comment]
This is really PR #5597.  I had to create a new one to work around Jenkins issues.

**Comment by davkean** [comment]
Looks like the tests timed out on win32, can't tell if was a deadlock or not as we only started caching build artifacts

retest prtest/win/dbg/unit32 please

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
Lost track of this.  PR #7725 ended up fixing this.

**Pull request closed without merging**
