### PR TITLE
Fixed a bug where errors from previous analyzer leaking to next analyzer for Workspace Analyzers

### PR DESCRIPTION
**Pull request by heejaechang**
### Customer scenario

User is editing a typescript file and same error shows up twice in error list some times.

### Bugs this fixes

typescript team reported the issue. will add bug number once I get the number.

### Workarounds, if any

No workaround

### Risk

No risk

### Performance impact

No impact

### Is this a regression from a previous update?

No

### Root cause analysis

when we build error map for Document/ProjectDiagnosticAnalyzer, we didn't clear errors from previous analyzer which caused the errors to be merged to next analyzer. 

we didn't notice this issue since most of people uses just 1 Document/ProjectDiagnosticAnalyzer.

### How was the bug found?

Dogfooding

### CODE REVIEW

**Comment by heejaechang** [comment]
@amcasey @dotnet/roslyn-ide  can you take a look?

**Comment by heejaechang** [comment]
first bug to fix using this (https://github.com/dotnet/project-system-tools/pull/44) in project-system-tool

**Comment by jinujoseph** [comment]
@Pilchie for ask mode approval for 15.7.P2

**Comment by Pilchie** [comment]
Approved.

**Pull request merged**
