### PR TITLE
Add feature to add missing File-Banner to a file.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by sharwell** [comment]
Based on experiences building a similar feature in StyleCop Analyzers, I would prefer several aspects of this get an intentional design prior to proceeding. Since a pull request probably isn't the best place for this, a new issue would likely be the way to start.

**Comment by CyrusNajmabadi** [comment]
I think this feature is simple enough and provides enough value that it can go in as it.  All it is is a speedup over having ot manually go to another file, find the bannner, and copy it into the current file.  The design suffices for a primary use case.  If more cases come forth we can invest as appropriate.

**Comment by sharwell** [comment]
It's simple, but to me it feels haphazard ("thrown together").

* It uses the first "banner" it finds on a non-generated source file in the same directory.
* It doesn't provide validation.
* It isn't configurable.
* It doesn't support Fix All.

I don't believe the incremental value of the feature in its current form would meet the quality expectations of Visual Studio users.

**Comment by CyrusNajmabadi** [comment]
> It's simple, but to me it feels haphazard ("thrown together").

I don't see a problem with that.  

> It uses the first "banner" it finds on a non-generated source file in the same directory.

Yes.  that seems like a perfectly reasonable heuristic.  It will be right the vast majority of times and will save the user the pain of having to go do something manually.

> It doesn't provide validation.

That can be provided by something else *if* it was even necessary.  

> It isn't configurable.

I don't think it needs to be.  For the vast majority of customers and use cases, they will just want their file to match the banner of some other file in their project.  THere's no need to overcomplicate here.  If more interesting cases come about, we could consider supporting them. But, in the meantime, this feature will still be able to make things more pleasant for most consumers who currently have no mechanism to support them.

> It doesn't support Fix All.

Again, not something that bothers me.  Make a new file: add the banner.  We coudl consider a fix-all, but again this is still better than hte current system where you have to go and do this manually anyways.
 
> I don't believe the incremental value of the feature in its current form would meet the quality expectations of Visual Studio users. 

I think you're conflating two things.  Something can provide marginal value and still be high quality.  We have features to do incredibly marginal things (and, indeed, i expect the majority of refactorings we'll eventually have will be all sorts of marginal).  But we can still provide them to give users a general toolbox of available functionality to help speed them up.

> The best place for an initial implementation like this would be a standalone analyzer package, and it would certainly be a great candidate for that.

Right now we can get something in the product at nearly no cost to us that can still be helpful to other users (and ourselves).  Needing to be in a separate package doesn't seem worthwhile, and just delays the benefit from reaching people.

**Comment by jasonmalinowski** [comment]
It'd also be really cool if we ran this during creation of new files directly. We already have a hook where we apply formatting...can we add this too?

**Comment by CyrusNajmabadi** [comment]
> It'd also be really cool if we ran this during creation of new files directly. We already have a hook where we apply formatting...can we add this too?

That's an interesting idea.  I'm going to open a bug to track it.  I'm concerned about being overly aggressive here.  For example, the user has a single file that has some sort of required banner (maybe they included a file from another project).  Now, every time they make a file they'd get that banner getting sucked in, evenif they didn't want it.

The nice thing about the approach here is that it has no user impact unless the user goes and says "let me bring up quick fixes at the top of the file.

**Comment by CyrusNajmabadi** [comment]
> Could we also provide this as an analyzer, so you get some indication that you forgot the banner?

I think we can design such a thing where the user opts into stating that the banner is required, and thus the absence need to be called out.  Right now i like that this is completely just a mechanism to help speed up things for the user without otherwise bothering them.

**Comment by sharwell** [comment]
> The nice thing about the approach here is that it has no user impact unless the user goes and says "let me bring up quick fixes at the top of the file."

I believe it also executes if you are positioned on the first line of the file (in order to prompt with the light bulb)? If that's the case, then it could be problematic for cases where a user with a large number of files in a directory, all without file headers, opens a file (which by default places the caret at the top).

**Comment by CyrusNajmabadi** [comment]
>  it could be problematic for cases where a user with a large number of files in a directory, all without file headers, opens a file (which by default places the caret at the top).

It would only be problematic in that case if the user immediately tried to bring up the lightbulb.   The actual analysis will normally only be happening in the background in a cancellable manner.

**Pull request merged**
