### PR TITLE
Make HostAnalyzerManager a bit lazier

### PR DESCRIPTION
**Pull request by jasonmalinowski**
We take the analyzer references provided from VSIX extensions and create
a map of AnalyzerReference.Id -> AnalyzerReference, which is done by
cracking the metadata and getting the .NET assembly identity for them.
We were doing this on the UI during package load, which really isn't
necessary.

<details><summary>Ask Mode template</summary>

### Customer scenario

When you open any project, the Roslyn load path triggers disk hits to read metadata for all the VSIX-provided analyzers on the UI thread during package load. This just moves it until first actual use.

### Bugs this fixes

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/491081

### Workarounds, if any

None.

### Risk

Very low. Lazy used to keep the code simple, and the code is already thread-safe.

### Performance impact

Better: we can defer a few disk hits until necessary.

### Is this a regression from a previous update?

No.

### Root cause analysis

This has always been like this.

### How was the bug found?

Internal testing.

</details>

### CODE REVIEW

**Comment by heejaechang** [comment]
just FYI.

I have this change
https://github.com/dotnet/roslyn/pull/25982

that I have been working with extension manager team to make everything that depends on UI thread.

**Comment by jasonmalinowski** [comment]
@heejaechang Should I just close this one then? Didn't realize you had a duplicate here.

**Comment by jasonmalinowski** [comment]
@heejaechang OK, makes sense. I'll make the small improvement now, you make the big improvement later.

**Comment by jasonmalinowski** [comment]
@jinujoseph @Pilchie We're good to take this for escrow? What's the process given people who are on vacation next week?

**Comment by Pilchie** [comment]
Yes, I would take this for escrow.  At the moment, I would get a VSTS bug in front of @MattGertz ASAP to start the process.

**Comment by jinujoseph** [comment]
I will submit the bug right away (cc @tmat ) as a info for escrow process

**Pull request merged**
