### PR TITLE
Create solution on the main thread in integration tests

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Comment by sharwell** [comment]
@JoeRobich is this still needed?

**Comment by JoeRobich** [comment]
It does not appear to be needed. closing

**Comment by JoeRobich** [comment]
Integration VM image has updated to 17.2 Preview 2 and this PR appears to be needed.

**Review by allisonchou — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by JoeRobich** [comment]
This PR is superseded by https://github.com/dotnet/roslyn/pull/60366

**Pull request merged**
