### PR TITLE
Convert To Record Refactoring/Code Fix initial offering

### PR DESCRIPTION
**Pull request by Soreloser2**
Completes #47598, #49682
merge feature branch into main.
Initial implementation of #62623

Convert To Record is a refactoring that allows a user to turn a class or struct into a record or record struct. In this initial offering we are supporting the "positional parameter" or "primary constructor" style of records, where all the notable properties are used as parameters in a constructor. Converting to a record will also automatically detect and refactor other constructors to meet the requirements of the record type. In addition, the conversion will analyze and potentially delete methods which have automatic implementation on record types, such as GetHashCode, Equals, and the equality operators. Finally, the conversion will refactor object creation expressions (using initializer blocks) in other areas of the code and convert them to use the primary constructor instead.

This is also offered as a code fix for diagnostic CS8865 ("classes cannot inherit from records"), so that the user can potentially go down an inheritance hierarchy of classes and sequentially convert each of them to a record.

Later improvements will offer support for the "Normal Property" style of records, where there is no primary constructor and properties are declared normally, and for "Fix All" scenarios so the user can refactor a number of classes at once.

[Demo](https://user-images.githubusercontent.com/43689321/188733221-aa62b03d-5e06-4c94-a5e2-c1f0be46e9e4.webm)

### CODE REVIEW

**Review by jasonmalinowski — APPROVED** [review]

**Comment by Youssef1313** [comment]
@jasonmalinowski Merging and deleting the branch caused a close for https://github.com/dotnet/roslyn/pull/63964 and https://github.com/dotnet/roslyn/pull/63848

I think the closing of these PRs is an unintended side effect.

**Comment by jasonmalinowski** [comment]
@Youssef1313 Ah thanks; I swore that was supposed to retarget the PRs to main but apparently not. 😦

**Comment by ChairmanMawh** [comment]
Can we also have the inverse please (record to class)?

**Comment by sharwell** [comment]
@ChairmanMawh This issue is closed. Please file a new issue for that request.

**Pull request merged**
