### PR TITLE
Suggestion scroll bar

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Update our code so that Suggestions show up in the scroll bar on the right.  By default, they will look like this:

image image

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Color for this is controlled through this FontsAndColors guy:

image

image


Foreground affects the dots.  Background affects the scroll margin (so you can update them independently!).

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide @kuhlenh

**Comment by Pilchie** [comment]
Can we do highlight references too?

**Comment by Pilchie** [comment]
Can we do highlight references too?!?

**Comment by CyrusNajmabadi** [comment]
@Pilchie Sure.  Can that happen in another PR?

**Comment by Pilchie** [comment]
Of course.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Can this go in then?

**Comment by CyrusNajmabadi** [comment]
@Pilchie Please review/signoff.  Thanks!

**Comment by CyrusNajmabadi** [comment]
ping @Pilchie

**Comment by CyrusNajmabadi** [comment]
Preemptively merging in.  Let me know if there's anything you want me to change.

**Pull request merged**
