### PR TITLE
Add public sign to help for csc & vbc

### LINKED ISSUE #7700: The publicsign argument does not have a help entry
The `/publicsign` command line argument lacks an entry when running `csc -h` or `vbc -h`.  There are entries for related arguments like `/delaysign` and should be one for `/publicsign`

### PR DESCRIPTION
**Pull request by agocke**
Fixes #7700

@dotnet/roslyn-compiler Super simple one, please review :)

### CODE REVIEW

**Comment by AlekseyTs** [comment]
It is probably too late to change resources in stabilization branch. CC @jinujoseph

**Comment by jaredpar** [comment]
@AlekseyTs the localization window has passed.  Agree this won't get localized in update 2.  But will having the English version hurt the existing loc'd ones?  If not I'm inclined to take this and let the loc catch up in update 3.

**Comment by AlekseyTs** [comment]
I don't know exact impact of this change on the current localization process. I'll let @jinujoseph to comment on that. I believe that, at the very least, the entire compiler help (not just the part specific to /publicsign) might not be localized after the change.

**Comment by agocke** [comment]
If there's an agreement that this could hurt existing localization I'll rebase this PR against master and fix it there.

**Comment by TyOverby** [comment]
:+1:

**Comment by jaredpar** [comment]
@jinujoseph can you please give us guidance here?  See @AlekseyTs comment.

**Comment by jinujoseph** [comment]
Localization is string by string , this is a new string so should not have any effect on the current localization process. If the new string has no loced string it will fallback to english one.

**Comment by AlekseyTs** [comment]
This is not a new string, this is a change to an existing and huge string.

**Comment by jaredpar** [comment]
@jinujoseph this is an update of an existing string, not a new one.  What will happen when this is viewed on say a JPN OS?  Will they see:

a. The localized version of the string before this change.
b. The unlocalized English string that is being added here.

**Comment by jinujoseph** [comment]
Ah sorry, from the commit changes looked like a new string.
Incase of a existing string change, Loc will detect the string change and trigger reloc on updated string and incase of not finding the localized version will fall back to English version.

So @jaredpar , it will fall back to B ( The unlocalized English string that is being added here )

**Comment by jaredpar** [comment]
Just verified wit @ManishJayaswal that loc freeze is 3/6 so this new string should be fine.

**Comment by jinujoseph** [comment]
yes , as long as you make it to del14rel branch before 6pm March 6'th.

locfreeze

**Pull request merged**
