### PR TITLE
Construct submissions with empty file path in VS

### LINKED ISSUE #7645: Intellisense does not work for assemblies referenced with paths relative to root
Repro:
Make a reference relative to root: `#r "\Users\Me\RosBin\Microsoft.CodeAnalysis.CSharp.dll"`. Type `Microsoft.|`. `CodeAnalysis` completion is not shown.

Cause:
ReferenceManager when running under IDE does not resolve paths relative to root.

### PR DESCRIPTION
**Pull request by drognanar**
Sets file paths for parsed syntax tree to "" in VS document state.
This is the same path name as set by the scripting API.

Fixes #7645.

### CODE REVIEW

**Comment by drognanar** [comment]
FYI @dotnet/roslyn-interactive @KevinH-MS

**Comment by drognanar** [comment]
test prtest/mac/dbg/unit32 please

**Comment by drognanar** [comment]
test prtest/win/dbg/unit32 please

**Comment by amcasey** [comment]
Can you please add a unit test asserting that the path is empty?

**Comment by amcasey** [comment]
Thanks!

:+1:

**Comment by drognanar** [comment]
retest prtest/mac/dbg/unit32 please

**Pull request merged**
