### PR TITLE
Select better auto-property backing field type to support devirtualization

### LINKED ISSUE #30797: Select better auto-prop backing field type to help with devirtualization
Given code like:
```C#
public class C
{
    public static A Shared { get; } = new B();
}
public abstract class A {  public virtual void Foo(); }
public sealed class B : A { public override void Foo(); }
```
the compiler currently produces an equivalent for the `Shared` property like:
```C#
    private static readonly A <Shared>k__BackingField = new B();
    public static A Shared => <Shared>k__BackingField;
```
If the backing field were instead created as type `B` instead of as `A`, it would be easier for the JIT to devirtualize calls to `C.Shared.Foo();`  It seems like the C# compiler could do this fairly easily, using the type of the RHS expression rather than the type of the property, as long as there isn't a conversion/boxing/etc. involved.

### PR DESCRIPTION
**Pull request by AustinWise**
Fixes #30797

### CODE REVIEW

**Comment by jaredpar** [comment]
Thanks for the contribution here. Couple of things:

1. We still need to clarify whether or not we want to take this change with the language design team. I'm optimistic this will be supported but I need to ensure that's the case.
1. Tests: with this change I would expect to see a number of tests here, both positive and negative. There don't seem to be any tests so far.

**Comment by AustinWise** [comment]
I got this working in the editor experience and the compiler. There is still some work to do before merging, but I'd like some feedback to make sure this approach is not totally wrong.

Things I think I need to do before merging:
* Add unit tests
* Perhaps refactor the binder code so that `BindVariableOrAutoPropInitializerValue` and this new code share the same logic for determining field conversions.

**Comment by AustinWise** [comment]
Rebased and updated with some unit tests. These mostly focus on the positive cases (implicit reference conversions from the initializer expression to the property type).

**Comment by jaredpar** [comment]
In the process of checking with LDM about this particular change we ended up discovering some problems with the proposal. I added a lot of detail to the original issue + CC'd you. 

https://github.com/dotnet/roslyn/issues/30797

**Comment by AustinWise** [comment]
As mentioned in #30797, the fact that constructors can reassign readonly auto properties make this approach intractable.

Interesting, there is no test currently that excises this feature in a way that was broken by my changes. Perhaps it would be worth adding a little unit test to exercise this case:
```csharp
class A { }
class B1 : A { }
class B2 : A { }
class C
{
    public C()
    {
        P = new B2();
    }
    A P { get; } = new B1();
}
```

**Comment by jaredpar** [comment]
I agree. I was surprised as well. I got lulled into a false sense of completeness when your PR passed the first round of testing. 

Again thanks for trying to get this optimization in! Dissapointing that it's harder than we thought but also good to have a firm resolution on it.

**Pull request closed without merging**
