### PR TITLE
Revert "Remove portions of solution crawler"

### PR DESCRIPTION
**Pull request by RikkiGibson**
#72147 is suspected of introducing RPS regressions.

Last known good: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/535650
First known bad: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/535699
Revert validation: TODO

Please advise whether the failures are plausibly connected with this PR, and if so, whether we should revert, or take a follow-up PR to fix, or seek an exception. @genlu, @CyrusNajmabadi @mavasani.

<details>
  <summary>Regressed counters:</summary>

BuildInfoVS64.Test
0001.BuildInfo
Build_Ngen_InvalidAssemblyCount
Regressed: 1 Count (12.5%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInRazorView
9990.Totals
CLR_AdjustedExceptions_Count_Total_devenv
Regressed: 376 Count (1315.38%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WinformsVS64.Designer
9990.Totals
CLR_AdjustedExceptions_Count_Total_devenv
Regressed: 9 Count (26.19%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.SolutionManagement
9990.Totals
CLR_AdjustedExceptions_Count_Total_devenv
Regressed: 7 Count (29.66%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.SolutionManagement
9990.Totals
CLR_AdjustedExceptions_Count_Total_devenv
Regressed: 7 Count (8.15%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Typing
9990.Totals
CLR_AdjustedExceptions_Count_Total_NonDevenv
Regressed: 51 Count (119.81%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInRazorView
9990.Totals
CLR_AdjustedExceptions_Count_Total_NonDevenv
Regressed: 60 Count (104.88%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.Debugging
9990.Totals
CLR_AdjustedExceptions_Count_Total_NonDevenv
Regressed: 228 Count (235.95%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Debugging
9990.Totals
CLR_AdjustedExceptions_Count_Total_NonDevenv
Regressed: 109 Count (83.18%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.AddNewProject
9990.Totals
CLR_AdjustedExceptions_Count_Total_NonDevenv
Regressed: 36 Count (80.18%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInWebforms
9990.Totals
CLR_AdjustedExceptions_Count_Total_NonDevenv
Regressed: 56 Count (170.91%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Debugging
0600.Stop Debugging
CLR_AdjustedMethodsJitted_Total_NonDevenv
Regressed: 4,772 Count (12.1%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Debugging
0500.Fast Stepping
CLR_BytesAllocated_devenv
Regressed: 29,704,600 Bytes (92.66%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Debugging
9990.Totals
CLR_BytesAllocated_devenv
Regressed: 207,341,773 Bytes (14.32%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Typing
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 1,117 Count (16.63%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInRazorView
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 2,303 Count (28.04%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.Debugging
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 2,221 Count (23.76%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
UWP64.BuildAndDebug
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 1,089 Count (10.2%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.Debugging
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 983 Count (12.54%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
ManagedLangsVS64.AddNewProject
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 1,098 Count (19.37%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInWebforms
9990.Totals
CLR_MethodsJitted_Total_devenv
Regressed: 1,102 Count (19.05%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInWebforms
9990.Totals
Threads_AdjustedBackgroundRPCCount_devenv
Regressed: 4 Count (0%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView 
WebToolsVS64.TypingInWebforms
0200.Typing CSharp in Webforms
VM_AdjustedImagesInMemory_Total_devenv
Regressed: 1 Count (0.24%)	🕳 View it in PIT 
📂 Open test outputs 
📈 Compare in PerfView a
</details>

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson https://github.com/dotnet/roslyn/pull/72524 will fix this.

**Comment by RikkiGibson** [comment]
We have an insertion now which includes #72524 and it doesn't appear to have resolved the regressions. https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/536210

**Comment by CyrusNajmabadi** [comment]
looking.

**Comment by CyrusNajmabadi** [comment]
Have looked, and i don't see anything in this PR that would affect any of the failures we're seeing.  The failures appear to be in streamjsonrpc as well as build failures building in TS due to the change made here: https://github.com/dotnet/roslyn/pull/72449

I don't think this change should be taken.

**Pull request closed without merging**
