### PR TITLE
Start running C# syntax tests on CoreCLR

### PR DESCRIPTION
**Pull request by agocke**
This PR ports the C# syntax tests to Portable and starts running them on CoreCLR on Windows, in addition to running them on Desktop.

On Linux+Mac, running on CoreCLR replaces our current Mono tests, so only C# syntax tests on CoreCLR are now enabled xplat.

/cc @jaredpar @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by jaredpar** [comment]
Is this just merging all of the work we've been already reviewing in the coreclr branch?

**Comment by agocke** [comment]
@jaredpar Yes

**Comment by agocke** [comment]
Note: Apparently this will require a Closed-side change for the ETA tests.

**Comment by jaredpar** [comment]
:+1: 

Note: I didn't review this change but have reviewed all of the intermediate changes.

**Comment by jaredpar** [comment]
CC @davkean since this will require a closed change once committed.

**Comment by agocke** [comment]
/cc @dotnet/roslyn-infrastructure 

Could I get one more person to look at this?

**Comment by tannergooding** [comment]
LGTM

**Comment by davkean** [comment]
@agocke @jaredpar Does this change need to make Update 1? Given the destabilization of the internal builds right now, we're looking at rolling this back.

**Comment by jaredpar** [comment]
@davkean this was merged after the cut off.  Didn't think it would be a factor in update 2.

**Comment by davkean** [comment]
We figured out its not. The failures in stabilization looked very similar to the ones in master, but investigating they look due to a different cause.

**Pull request merged**
