### PR TITLE
Replace PdbOutputInfo with EmitStreamProvider

### PR DESCRIPTION
**Pull request by tmat**
We need to abstract away the peculiarities of native PDB writer in order to support Portable PDB writer, which is in nature the same writer as PE writer. Specifically, it doesn't auto-create the target file unlike the native PDB writer.

### CODE REVIEW

**Comment by tmat** [comment]
retest this please

**Comment by jaredpar** [comment]
:+1:

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by tmat** [comment]
jenkins retest this please

**Pull request merged**
