### PR TITLE
Expose C# formatting service to Razor via external access

### PR DESCRIPTION
**Pull request by allisonchou**
Razor wants to use Roslyn's formatting service directly instead of going through the C# language server for on-type formatting (see https://github.com/dotnet/aspnetcore/issues/33951 for additional details).

<s>I only included methods that I thought might be useful in the future. For example, I left out `GetFormattingChangesOnReturnAsync` (despite it being part of the default `IFormattingInteractionService` interface) since the C# on-type formatter does not support format on return.</s>

Link to Razor side PR: https://github.com/dotnet/aspnetcore-tooling/pull/4203

### CODE REVIEW

**Review by dibarbet — COMMENTED** [review]
Would you be able to write out the performance issues with the LSP based formatting?  At some point C# formatting will have to be done through LSP (for VSCode for example).  It would be good to have the perf issues noted somewhere so that when we start that investigation we know what problems we need to fix.

**Review by dibarbet — APPROVED** [review]

**Comment by davidwengier** [comment]
> Would you be able to write out the performance issues with the LSP based formatting? 

I don't have numbers and haven't done a proper investigation here, but on type formatting on Razor is noticeably slow, and I suspect/assume/hope its because VS is calling Razor to do on type formatting via LSP, then Razor calls Roslyn to do on type formatting via LSP, so we incur the LSP delay twice.

> At some point C# formatting will have to be done through LSP (for VSCode for example)

Do you mean for Razor, or just in general for C#?

**Comment by davidwengier** [comment]
> For example, I left out `GetFormattingChangesOnReturnAsync` (despite it being part of the default `IFormattingInteractionService` interface) since the C# on-type formatter does not support format on return.

https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs#L62 ? Am I missing something?

I would have thought Format on Paste could be left out, since I would guess that an LSP client would just call range formatting for that.

**Comment by allisonchou** [comment]
>https://github.com/dotnet/roslyn/blob/main/src/Features/LanguageServer/Protocol/Handler/Formatting/FormatDocumentOnTypeHandler.cs#L62 ? Am I missing something?

I think that line doesn't do anything today, at least in C#, because the C# formatting service doesn't support [format on return](https://github.com/dotnet/roslyn/blob/04cef9860ed6b6a6d97c35e0053149f4117f3a10/src/Features/CSharp/Portable/Formatting/CSharpFormattingInteractionService.cs#L45). I'm guessing the line is just kept there in case any other language server supports it (like TS perhaps)? Or maybe we can remove it? cc @dibarbet 

>I would have thought Format on Paste could be left out, since I would guess that an LSP client would just call range formatting for that.

I think it could be removed, the only method we technically need today is `GetFormattingChangesAsync`. I was thinking it might be useful for the future despite not being used today, but if the scenario is covered already I can remove it.

**Comment by davidwengier** [comment]
> I was thinking it might be useful for the future despite not being used today, but if the scenario is covered already I can remove it.

I'm okay with either way, but at the moment it seems inconsistent. Either expose all of the methods, for future use, or none and update later. Having Paste for future by not Return is odd.

**Review by davidwengier — APPROVED** [review]

**Comment by allisonchou** [comment]
> I'm okay with either way, but at the moment it seems inconsistent. Either expose all of the methods, for future use, or none and update later. Having Paste for future by not Return is odd.

Totally fair! I added Return back.

**Pull request merged**
