### PR TITLE
Fix InvalidCastException when exception filter contains a switch expression

### LINKED ISSUE #48259: Switch expression in exception filter of async method crash compiler
**Version Used**: 
VS 16.7.4 / VS 16.8.0 Preview 3.1

**Steps to Reproduce**:
Compile next source:
```c#
        static async Task Test()
        {
            try
            {
                Console.WriteLine("Hello World!");
            }
            catch (Exception e) when (e switch { _ => true})
            {
                return;
            }
        }
```

**Expected Behavior**:
Compilation without problems

**Actual Behavior**:
Compiler crashed: "csc.exe" exited with code -2146232797.

### PR DESCRIPTION
**Pull request by Youssef1313**
Hopefully fixes #48259

This is a very quick fix by looking into the exception and stacktrace in [SharpLab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOyQExAagB8ABAJgEYBYAKGIAYACY8gVgG4aayBmGgbxoMhTcgDYmADibiAshACWmABQBKQcIHVh2hjAQBPdToabjx5gE4lAIgAScADYOA9gwDqzhA5wBCayo4tMwBfIx0AYwgYcIALBiUAUQAPcLgABxh5Z0wGOBUGAHcYuBylOAYoAvlouL4GAH0GAF4APl0MOGC1IONTM21iAHZA/tCehjHgoA=):

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.BoundStatementList' to type 'Microsoft.CodeAnalysis.CSharp.BoundBlock'.

   at Microsoft.CodeAnalysis.CSharp.Symbols.MethodToClassRewriter.VisitCatchBlock(BoundCatchBlock node) in /_/src/Compilers/CSharp/Portable/Lowering/MethodToClassRewriter.cs:line 130
```

I found a similar cast in:

https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs#L91

Can you please review if this have a similar bug?

### CODE REVIEW

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 3)

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@333fred @jaredpar can you confirm if this is something we want to take in 16.8?

**Comment by RikkiGibson** [comment]
> I found a similar cast in:
> 
> https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_TryStatement.cs#L91
> 
> Can you please review if this have a similar bug?

Currently I don't think it's possible to cause the compiler to crash due to this, because the exception filter prologue is only introduced by subsequent lowering passes (specifically SpillSequenceSpiller which calls `BoundCatchBlock.Update()`.) Thus it is always null when we cast it in `LocalRewriter_TryStatement.cs`.

However, I think we should just do the same fix here.

**Comment by RikkiGibson** [comment]
Thanks @Youssef1313!

**Pull request merged**
