### PR TITLE
Add Margin to GroupBoxes in AdvancedOptionPageCSharp

### LINKED ISSUE #14979: C# advanced options appearance issue
image

With the options dialog at its default size, note how the gray borders are touching the scrollbar.

### PR DESCRIPTION
**Pull request by reaction1989**
**Customer scenario** Go to Tools\Options without resizing, and the group box is touching the border.
**Bugs this fixes:** #14979
**Workarounds:** Can resize Tools\Options.
**Risk:** Very low, just adding a Margin to the UI.
**Performance impact:** None
**Is this a regression from a previous update?** No
**Root cause analysis:** Rarely on a clean machine where Tools\Options hasn't been resized.
**How was the bug found?** Bug bash

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
can you put a screenshot of the before/after?  Thanks!

**Comment by Pilchie** [comment]
Thanks for the PR. Tagging @dotnet/roslyn-ide for code review.

**Comment by reaction1989** [comment]
Before:

image


After:

image

**Comment by Pilchie** [comment]
Would love confirmation from @dpoeschl that this is the *right* way to solve the issue taking DPI scaling into account.

**Comment by reaction1989** [comment]
@jasonmalinowski sure i can add a comment. Do you want a reference to the issue in that comment?

**Comment by dpoeschl** [comment]
@reaction1989 I'll get back to you on the DPI thing, but an unrelated question: The left-hand option tree structure is localized but the option page itself isn't? If that page isn't localized, that's really bad. Are other options pages localized for you? /cc: @nguerrera in case there's a known problem here.

**Comment by nguerrera** [comment]
@dpoeschl Not known. Also, not reproducible with 15.0.0-RC.2+26030.1.d15prerel (FR):

image

**Comment by reaction1989** [comment]
@dpoeschl that was a screenshot from vs2015 (i think) it looks good in vs2017

**Comment by dpoeschl** [comment]
@Pilchie Adjusting the Margin like this is the appropriate way to handle High DPI.

**Comment by Pilchie** [comment]
Awesome. Tagging @MattGertz for approval - do you want to take this, or push to `post-dev15`?

**Comment by MattGertz** [comment]
@Pilchie ASK template?

**Comment by Pilchie** [comment]
@MattGertz Sorry - updated original PR description to include the template.

**Comment by MattGertz** [comment]
Post-dev15, please -- thanks!

**Comment by reaction1989** [comment]
@MattGertz it is pushed to post-dev15

**Comment by Pilchie** [comment]
Thanks for the contribution!

**Pull request merged**
