### PR TITLE
Avoid directory enumerations in DeleteLeftoverDirectories

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Review by jaredpar — APPROVED** [review]

**Review by genlu — APPROVED** [review]

**Comment by genlu** [comment]
@sharwell I think this should target release/dev17.6

**Review by arkalyanms — APPROVED** [review]

**Comment by sharwell** [comment]
@genlu since there's no specific regression getting fixed here, I think main would be fine

**Comment by sharwell** [comment]
@jaredpar can you get a second compiler review here?

**Comment by jaredpar** [comment]
@jjonescz, @RikkiGibson  PTAL

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
