### PR TITLE
Adjust `IsAttributeTargetSpecifier` helper

### PR DESCRIPTION
**Pull request by jcouv**
Fixes https://github.com/dotnet/roslyn/issues/67485

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Consider adding an assertion in https://github.com/dotnet/roslyn/blob/9f323e7fa41ebe0c0bb2222265a59071d2d0e602/src/Compilers/CSharp/Portable/Symbols/Source/AttributeLocation.cs#L102-L116

something like this

```csharp
Debug.Assert(ToAttributeLocation(token.ValueText) == AttributeLocation.None ^ SyntaxFacts.IsAttributeTargetSpecifier(token.Kind()));
```

**Comment by jcouv** [comment]
> Consider adding an assertion ...

@Youssef1313 Thanks for the suggestion, but I don't think that would work (such an assertion would cause test breaks). See the comment in that `ToAttributeLocation` method. It is meant to recognize tokens by `ValueText` not by `SyntaxKind`. So it works with tokens that are not keywords. It's a weird mismatch, but it should stay as-is.

**Comment by Youssef1313** [comment]
@jcouv Would it work similar to this?

```csharp
#if DEBUG
var kind = SyntaxFacts.GetKeywordKind(token.ValueText);
if (kind == SyntaxKind.None)
{
    kind = SyntaxFacts.GetContextualKeywordKind(token.ValueText);
}

Debug.Assert(ToAttributeLocation(token.ValueText) == AttributeLocation.None ^ SyntaxFacts.IsAttributeTargetSpecifier(kind));
#endif
```

It's a bit longer though :'(

**Review by jjonescz — APPROVED** [review]

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for another review please.

**Review by cston — APPROVED** [review]

**Pull request merged**
