### PR TITLE
Update required dotnet to 3.1.100

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar @agocke Any objections?

**Comment by agocke** [comment]
VS probably needs to be bumped to 16.4 for that.

**Comment by tmat** [comment]
@agocke Bumped VS as well.

**Comment by agocke** [comment]
@rainersigwald @nguerrera For input on SDK. What MSBuild should we match up with 3.1.100?

**Comment by nguerrera** [comment]
16.4

**Comment by nguerrera** [comment]
We don’t block you from using 16.3 but 16.4 is the tested golden path. Earlier than 16.3 is straight out.

**Comment by agocke** [comment]
@tmat you'll have to make a 16.4 MSBuild package. @jaredpar has a guide somewhere but I've forgotten where it is.

**Comment by agocke** [comment]
Ah, I think it's here https://github.com/jaredpar/xcopy-msbuild

**Comment by genlu** [comment]
I'm seeing this ibcmerge error in signed build, could it be related to this change?

```
2020-01-23T21:48:17.5964086Z ##[error]EXEC(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Build) the following exception was thrown while processing profile data
2020-01-23T21:48:17.6143460Z   System.BadImageFormatException: Invalid compressed integer.
2020-01-23T21:48:17.6144204Z      at System.Reflection.Throw.InvalidCompressedInteger()
2020-01-23T21:48:17.6151921Z      at System.Reflection.Metadata.BlobReader.ReadCompressedInteger()
2020-01-23T21:48:17.6152581Z      at MDReader.GetMethodName(ModuleId moduleId, UInt32 methodToken, BlobReader& genSig, Boolean encodesMethodInstantiation, String& returnType) in /_/src/IbcMerge/ibcmerge.cs:line 2301
2020-01-23T21:48:17.6153129Z      at MDReader.GetSigMethodInstantiation(BlobReader sig, String& typeInstantiation, String& returnType) in /_/src/IbcMerge/ibcmerge.cs:line 2145
2020-01-23T21:48:17.6153541Z      at IBCData.ParamSpecLookupName(MDReader mdr, UInt32 token) in /_/src/IbcMerge/ibcmerge.cs:line 1565
2020-01-23T21:48:17.6153909Z      at IBCRead.DumpAsXml(String outFileName) in /_/src/IbcMerge/ibcmerge.cs:line 9852
2020-01-23T21:48:17.6154235Z      at IBCMerge.Merge(String[] args) in /_/src/IbcMerge/ibcmerge.cs:line 11155
2020-01-23T21:48:17.6154589Z      at IBCMerge.Main(String[] args) in /_/src/IbcMerge/ibcmerge.cs:line 10616
2020-01-23T21:48:17.6269629Z E:\A\_work\2835\s\.packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20071.3\tools\OptimizationData.targets(176,5): error MSB3073: The command ""E:\A\_work\2835\s\.dotnet\dotnet.exe" exec "E:\A\_work\2835\s\.packages\microsoft.dotnet.ibcmerge\5.0.6-beta.19203.1\tools\netcoreapp2.0\ibcmerge.dll" -q -f -partialNGEN -minify -delete -mo "E:\A\_work\2835\s\artifacts\obj\Microsoft.CodeAnalysis.CSharp.EditorFeatures\Release\net472\Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll" -incremental "E:\A\_work\2835\s\artifacts\tmp\Release\OptimizedAssemblies\a4dc6411-e58d-417d-8700-c7d0ce4ad707" -dxml "E:\A\_work\2835\s\artifacts\tmp\Release\ibcxml\Microsoft.CodeAnalysis.CSharp.EditorFeatures.dll.f94b7090-51d9-43c5-9cfe-40e58925e86e.temp.ibc.xml"" exited with code -1. [E:\A\_work\2835\s\src\EditorFeatures\CSharp\Microsoft.CodeAnalysis.CSharp.EditorFeatures.csproj]
```

**Comment by genlu** [comment]
The revert linked above is from a branch I'm testing (dev/gel/revert41113 ), not in the official branch

**Comment by genlu** [comment]
Reverting the dotnet version seems to fix the error.

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=3410964

**Pull request merged**
