### PR TITLE
User-defined operator checks should ignore differences in tuple member names

### LINKED ISSUE #30659: It feels like Microsoft.CodeAnalysis.CSharp.Symbols.SourceUserDefinedOperatorSymbolBase.CheckUserDefinedConversionSignature Should ignore tuple names when type symbols are compared
```
            // SPEC: * S0 and T0 are different types:

            if ((ContainingType.SpecialType == SpecialType.System_Nullable_T) ? source == target : source0 == target0)
```

```
            if (source0 == this.ContainingType)
            {
                same = source;
                different = target;
            }
            else
            {
                same = target;
                different = source;
            }

```

### LINKED ISSUE #30668: It feels like Microsoft.CodeAnalysis.CSharp.Symbols.SourceUserDefinedOperatorSymbolBase.CheckIncrementDecrementSignature should ignore tuple names when type symbols are compared
```
            else if (!this.ReturnType.TypeSymbol.EffectiveTypeNoUseSiteDiagnostics.IsEqualToOrDerivedFrom(parameterType, TypeCompareKind.ConsiderEverything, useSiteDiagnostics: ref useSiteDiagnostics))
            {
                // CS0448: The return type for ++ or -- operator must match the parameter type
                //         or be derived from the parameter type
                diagnostics.Add(ErrorCode.ERR_BadIncDecRetType, this.Locations[0]);
            }
```

### PR DESCRIPTION
**Pull request by RikkiGibson**
- [x] Resolves #30668 
- [x] Resolves #30659

### CODE REVIEW

**Comment by gafter** [comment]
> Any reason to prefer one or the other of these:
> 
> `typeSymbol1.TupleUnderlyingTypeOrSelf() == typeSymbol2.TupleUnderlyingTypeOrSelf()`
> `typeSymbol1.Equals(typeSymbol2, TypeCompareKind.IgnoreTupleNames)`

The latter directly expresses the intent of the code and therefore should be preferred.

**Comment by RikkiGibson** [comment]
Tests pass locally but fail in CI:

```
++>                 Diagnostic(ErrorCode.WRN_SameFullNameThisAggAgg, "ValueTuple<T1, T2>").WithArguments("", "System.ValueTuple<T1, T2>", "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51", "System.ValueTuple<T1, T2>").WithLocation(6, 51)
-->                 Diagnostic(ErrorCode.WRN_SameFullNameThisAggAgg, "ValueTuple<T1, T2>").WithArguments("", "System.ValueTuple<T1, T2>", "System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51", "System.ValueTuple<T1, T2>").WithLocation(6, 51)
```

Seems like the environment the compiler is run in affects the exact warning message. Should I change the verification here to skip checking the `WRN_SameFullNameThisAggAgg` diagnostic?

**Comment by RikkiGibson** [comment]
CI failures related to the build agent getting into a bad state (compiler server is persisting and preventing clearing out/cloning sources at the start of build)

**Comment by jaredpar** [comment]
@RikkiGibson 

> Seems like the environment the compiler is run in affects the exact warning message.

This can be the case when error messages mention DLL names. Types can be located in differetn assemblies in desktop and CoreClr.

Which test is failing here? None of the new tests seem to have this message and CI is broken so I couldn't see the failed run you were looking at.

**Comment by RikkiGibson** [comment]
It was `TestTupleOperatorConvertToBaseType` and `TestTupleBinaryOperator`. I resolved it in 9f808de by just filtering out the warning diagnostics before verifying.

**Pull request merged**
