### PR TITLE
VB: Ensure array access indexes undergo conversion to integer even when there is a mismatch with array rank.

### LINKED ISSUE #49904: Unreachable code exception is thrown for incomplete With statement
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Structures-and-Multidimensional-Array/726880)._

---
[regression] [worked-in:Community Preview 16.2.0 (untested)]
What steps will reproduce the problem?
1.Create a structure
    Structure MyStruct
        Dim A As Integer
        Dim B As Integer
        Dim C As Integer
    End Structure
and create an array
Private MyArr(9, 3, 11) As MyStruct
2.
Trying to assign values
        Dim n, p, r As Integer
        For n = 0 To 9
            For p = 0 To 3
                For r = 0 To 11
                    With MyArr(n, error)
                        . A = n
                        . B = p
                        . C = r
                    End With
                Next
            Next
        Next
3.
As soon as I try to write , p  (after (n)) VS crashes
4.
The same problem apears in VS Community 16.2.4
Apparently this happens after upgrading both versions
Forcing the introdution (commenting the line, for example) and writing (n, p, r) and uncommenting the line, no error apears and the project is created

---
#### Feedback Bot on 9/9/2019, 03:51 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 10/14/2019, 00:59 AM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 10/31/2019, 07:13 PM: 

I have detected that for the last 35 days, this issue didn't have any product team activity and a very small amount of new votes or comments.&nbsp;Based on this, its severity, and affected area, it’s my experience that this issue is very unlikely to be fixed.
#### Wenwen Fan [MSFT] on 12/1/2020, 00:57 AM: 

<p>Thank you for taking the time to log this issue! Verified on VS2019 build 16.8.2, we create a VB winform project with the code:</p>
<p>Public Class Form1<br>
Structure MyStruct<br>
Dim A As Integer</p>
<pre><code>    Dim B As Integer

    Dim C As Integer
End Structure

Private MyArr(9, 3, 11) As MyStruct

Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
    Dim n, p, r As Integer
    For n = 0 To 9
        For p = 0 To 3
            For r = 0 To 11
                With MyArr(n, p, r)
                    .A = n
                    .B = p
                    .C = r
                End With
            Next
        Next
    Next
End Sub
</code></pre>
<p>End Class</p>
<p>When We write p after n, VS not crashed, and popup two errors bellow the menu bar:<br>
“IntroduceVariableCodeRefactoringProvider” encountered an error has been disabled.<br>
“VisualBasicAddAwaitCodeRefactoringProvider” encountered an error and has been disabled.<br>
Could you please have a try with the latest build, thank you.</p>

#### Feedback Bot on 12/8/2020, 07:33 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #49904.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off

**Comment by 333fred** [comment]
Looking

**Review by 333fred — APPROVED** [review]
LGTM (commit 1)

**Pull request merged**
