### PR TITLE
fix crash.

### PR DESCRIPTION
**Pull request by heejaechang**
I don't have heap so can't figure out why the situation happened. but this should at least prevent crash.

when this happens, after this fix, we might have wrong span for diagnostic, but that is not critical issue to crash VS.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure same IO issue on prtest/determinism

**Comment by davkean** [comment]
@heejaechang Yep, I've made @jaredpar aware. Ignore it.

**Comment by heejaechang** [comment]
@mavasani @srivatsn can you take a look?

**Comment by mavasani** [comment]
There is a hep dump now in the bug.

**Comment by heejaechang** [comment]
@mavasani I looked the heap dump. info needed is all optimized away. so not much more data. but position before this

var startPos = textLines.GetPosition(originalSpan.Start);
var endPos = textLines.GetPosition(originalSpan.End);

are all in right order. 

so, above call seems returned locations in reversed order, but I can't get text info so can't figure out why.

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
