### PR TITLE
Fix incorrectly serialized OOP parameters. Also, reenabled all OOP tests.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 

**Customer scenario**

If you turn on the experimental OOP option, NavigateTo will crash.  This was due to incorrectly serialized parameters.  This was not caught because of a previous change that went through that accidently disabled all OOP feature tests :(   (i.e. we thought the feature tests were testing for OOP, but they actually weren't :( ).

**Bugs this fixes:**

(either VSO or GitHub links)

**Workarounds, if any**

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

**Risk**

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

**Performance impact**

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

**Is this a regression from a previous update?**

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

(E.g. customer reported it vs. ad hoc testing)

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide @heejaechang @Pilchie

**Comment by CyrusNajmabadi** [comment]
@heejaechang I'm going to need some help with this.  With OOP on, no diagnostics are getting reported in tests, so all the code action tests fail.

**Comment by CyrusNajmabadi** [comment]
I'm trying to debug through it with @mavasani .  So far, we've seen that the compiler is properly reporting semantic diagnostics.  But they're not making it all the way back to the code-action test harness.

**Comment by CyrusNajmabadi** [comment]
Ok, so we're getting to:

C:\GitHub\roslyn-internal\Open\src\Features\Core\Portable\Diagnostics\EngineV2\DiagnosticAnalyzerExecutor.cs line 75:

```
               // due to OpenFileOnly analyzer, we need to run inproc as well for such analyzers
                var inProcResultTask = AnalyzeInProcAsync(CreateAnalyzerDriver(analyzerDriver, a => a.IsOpenFileOnly(project.Solution.Workspace)), project, cancellationToken);
                var outOfProcResultTask = AnalyzeOutOfProcAsync(remoteHostClient, analyzerDriver, project, cancellationToken);
```

However, both inproc and out of proc are reporting no results for diagnostics.

**Comment by CyrusNajmabadi** [comment]
We are getting to ehre on the OOP side:

```
                    var analyzers = RoslynServices.AssetService.GetGlobalAssetsOfType<AnalyzerReference>(CancellationToken);

                    var result = await (new DiagnosticComputer(solution.GetProject(projectId))).GetDiagnosticsAsync(
                        analyzers, optionSet, arguments.AnalyzerIds, arguments.ReportSuppressedDiagnostics, arguments.LogAnalyzerExecutionTime, CancellationToken).ConfigureAwait(false);
```

But 'analyzers' is empty, so GetDiagnosticsAsync immediately returns.

**Comment by CyrusNajmabadi** [comment]
Note: teh arguments we're passing to OOP include:

image

So i don't know why we're getting no analyzers back.

**Comment by heejaechang** [comment]
@CyrusNajmabadi @mavasani in the test, how the analyzer get added to project? through host (vsix) or through project's analyzer reference (nuget) ?

for host (vsix), one need to explicitly do this.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,177

if it is added as project's analyzer reference, then it should just work.

**Comment by heejaechang** [comment]
test is quite complex so I can't figure out by just looking thorough test how diagnostic analyzer is actually added. but I don't see any place where the diagnostic analyzer is added as analyzer reference to project, so my guess is it is getting it from Host, in that case, one need to explicitly tell OOP that the analyzer is Host (vsix) analyzer that is not part of solution snapshot.

...

another way to solve this is explicitly adding the analyzer as analyzer reference to the project in the test so that things just work.

**Comment by CyrusNajmabadi** [comment]
> another way to solve this is explicitly adding the analyzer as analyzer reference to the project in the test so that things just work.

how would i do that?

**Comment by CyrusNajmabadi** [comment]
>  in that case, one need to explicitly tell OOP that the analyzer is Host (vsix) analyzer that is not part of solution snapshot.

How would i do that?

**Comment by CyrusNajmabadi** [comment]
@heejaechang That could only gets hit if EnableAsync gets called.  And EnableAsync only gets called if Enable gets called.  But no one seems to call Enable except for AbstractPackage...  so i'm not sure how this stuff is supposed to work in tests.

**Comment by heejaechang** [comment]
http://source.roslyn.io/#Roslyn.Services.Test.Utilities/Diagnostics/TestDiagnosticAnalyzerDriver.cs,26

ya. it is added as host analyzer. you can in that constructor or caller of the constructor, do what this test does.

http://source.roslyn.io/#Roslyn.VisualStudio.Next.UnitTests/Services/VisualStudioDiagnosticAnalyzerExecutorTests.cs,178

or you can do what this does
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,177

**Comment by heejaechang** [comment]
http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,177

you can't use the code there as it is. but you need to call this to let OOP knows there are data that are out side of given solution snapshot.

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostClientServiceFactory.RemoteHostClientService.cs,180

**Comment by CyrusNajmabadi** [comment]
This is massively complex and confusing.

**Comment by heejaechang** [comment]
are you talking about test? ya, I agree. so much stuff

**Comment by CyrusNajmabadi** [comment]
> you can't use the code there as it is. but you need to call this to let OOP knows there are data that are out side of given solution snapshot.

Where would i call this?

**Comment by CyrusNajmabadi** [comment]
> ya. it is added as host analyzer. you can in that constructor or caller of the constructor, do what this test does.

Can you be more specific.  That test does a lot.  Which parts of that would i need to do?

**Comment by CyrusNajmabadi** [comment]
Sorry @heejaechang It's really unclear what you're asking me to do.  A lot of the code you've linked me to exists in the VS layers.  It's unclear to me how i would use it from the Features-Test layer where i am currently.

It seems like a bug to me that the code in DiagnosticAnalyzerExecutor.cs is behaving differently depending on if OOP is on or not.  If OOP is off, we run:

```C#
return await AnalyzeInProcAsync(analyzerDriver, project, cancellationToken).ConfigureAwait(false);
```

And it works properly.  But if OOP is on, it does hte following:

```c#
var inProcResultTask = AnalyzeInProcAsync(CreateAnalyzerDriver(analyzerDriver, a => a.IsOpenFileOnly(project.Solution.Workspace)), project, cancellationToken);
var outOfProcResultTask = AnalyzeOutOfProcAsync(remoteHostClient, analyzerDriver, project, cancellationToken);
```

And we get disparate results.  That means that that code is not equivalent.  it assumes that running some analyzers in-proc and some OOP will results in teh same values as running everything in proc.  But that clearly depends on unstated and unenforced assumptions.

**Comment by CyrusNajmabadi** [comment]
It feels like the code i linked to should either:

1. Not run the analyzer OOP if it won't result in anything being produced.
2. Setup the OOP side so that the analyzer will be safe to run there.
3. Ensure that it is only run after someone has properly set things up so that the split it makes is safe.

Right now it's depending on the environment being in a state that is never specified and is not actually provided by the tests infrastructure.  All this implicitness leads to hard to diagnose deviations in behavior between tests and real code.  And, ideally, that should not happen.  As much code should be in the product, so that tests just need to call in, and we exercise the same codepaths from tests and the real product.

**Comment by heejaechang** [comment]
so there are 2 ways analyzer can be added to a project. one is added by MEF/vsix (we call that Host analyzer) and the other is added by project's analyzer reference (we call it nuget analyzers).

the first one is not part of solution, only host knows about the existence of such analyzers. the second one is part of solution. and one know existence of such analyzer by just having solution.

Host such as VS has 2 mechanism to add such analyzers to system. one is called IWorkspaceDiagnosticAnalyzerProviderService and the other is project system.

since there is no host for the unit test, it looks like the tests do its own thing for both. it looks like the test doesn't even use the second way. but just use the first way to add analyzer to the test. (not 100% sure, but code looks like it acts that way)

and the test doesn't actually go through all pipe line, but just create fake test diagnostic service and give in those analyzer as if that are host analyzers. it works in proc since they are visible to everyone in same process.

but for OOP, that won't work. first, the test doesn't go through the part that tell OOP that there are host analyzers so OOP has no idea on those analyzers. second one can't exchange diagnostic analyzer code in memory between 2 isolated process (even if we fake it in unit test). it needs to use file to do so. but the test seems just assume diagnostic analyzer can be run without any restriction.

much simpler way might just running diagnostic in proc all the time since the test wasn't built in a way that can let things run in OOP

**Comment by CyrusNajmabadi** [comment]
> much simpler way might just running diagnostic in proc all the time since the test wasn't built in a way that can let things run in OOP

How would i do that?

Note: i can't set the OOP option to 'false' before calling diagnostics.  Because then the OOP layer caches that there is a null client, and later OOP calls fail out immediately.

**Comment by heejaechang** [comment]
I don't think right now, there is a way. basically, sounds like we want yet another option?

**Comment by MattGertz** [comment]
Proactively setting the label as I'm assuming this will be resolved by noon.  However, I would like to have our tests updated so that they make it clear which path they are testing in the output.

**Comment by CyrusNajmabadi** [comment]
Ok.  I'll go that route.  Note: as far as i can tell, we need to massively revamp and cleanup how we test things that involve diagnostics.  There ar ea bunch of a places we do it in code, and so many of them just seem to be a mishmash of random calls into certain APIs, with no clarity if they're doing the right thing :(

**Comment by heejaechang** [comment]
about test giving different result based on whether things run in OOP or not. 

sure, test doesn't do everything that must be done in host to run things in OOP. so not all analyzer seems registered or possible to run in OOP. so some analyzers don't run in OOP and results from those analyzers are missing.

I think that is wrong assumption that  by just flipping a flag, everything automatically possible to run in OOP. one need to explicitly make one to be able to run in OOP. for example, OOP only support AnalyzerFileReference but not AnalyzerImageReference and others.

it is only an issue if same analyzers are given to both in proc and out of proc and 2 returns different results. I believe that is not the case here.

**Comment by CyrusNajmabadi** [comment]
We can take this offline.  But the reason we use Workspaces in tests is so that tests simulate the actual real host experience as closely as possible.  Tests do not want to have to know how to specially configure subsystems to try to make it close to the host.  Instead, they want to be able to say "give me an environment that is practically teh same as the host and allow me to run in it".

Right now, with diagnostic tests it does not work that way.  Tests have to know the ins and outs of drivers, analyzers, many different services, options, etc. etc.  It's extremely error prone and hard to have any sense if the test is setting things up properly.  That is not what we want in tests.

We might want some high level knobs for the test environment (like "Do i want OOP, etc.") but the test environemnt (i.e. TestWorkspace) should then just do all teh right configuration to ensure it emulates the host as closely as possible in that regard.

**Comment by heejaechang** [comment]
sure. you are the first one that enabled Diagnostic OOP in other layer than VS layer. so sure none of diagnostic tests are adjusted for OOP. but like I said, just flipping a flag and hoping things to just work won't happen.

**Pull request merged**
