### PR TITLE
Disable apphost build of 'csi', 'vbi' for source-build

### PR DESCRIPTION
**Pull request by dagood**
* For #57233 (more details here)
* https://github.com/dotnet/source-build/issues/2528

### CODE REVIEW

**Comment by kasperk81** [comment]
is this ready to merge (after resolving conflicts)? this often cause patch conflict in installer repo and holds back the update

**Comment by tmat** [comment]
Yes

**Comment by MichaelSimons** [comment]
This should be closed in preference of https://github.com/dotnet/roslyn/pull/58727.

**Pull request closed without merging**
