### PR TITLE
found a race where we might double start progress bar for solution cr…

### PR DESCRIPTION
**Pull request by heejaechang**
…awler (error list)

### Customer scenario

User sees "ErrorList" title contains "..." and it never goes away. and it can confuse users that error list is still updating while it is already done.

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/23764

### Workarounds, if any

there is no workaround.

### Risk

low risk. not something that can cause crash.

### Performance impact

Low

### Is this a regression from a previous update?

Yes.

### Root cause analysis

this fix introduced this race - https://github.com/dotnet/roslyn/pull/23623

basically, previously, we didn't account work that are still running (ex, last work that is running). we start and stop progress bar as first work is enqueued to the work queue and as last work is dequeued. which can be misleading since last work might still running even if progress bar said work is done. so the PR above changed progress bar to consider work still running, but failed to change logic on when we start progress bar since now even if queue is empty, progress bar might still not done yet. restarting progress bar while it is still running will mess up its state tracking. this fix that issue.

### How was the bug found?

dogfooding.

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph @dotnet/roslyn-analysis @dotnet/roslyn-ide @Pilchie can you take a look?

**Comment by Pilchie** [comment]
Approved pending tests passing.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure test failure
https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_14_debug_prtest/8105/
Microsoft.CodeAnalysis.CSharp.UnitTests.PatternParsingTexts.ThrowExpression_Good

**Comment by heejaechang** [comment]
retest ubuntu_14_debug_prtest please

**Pull request merged**
