### PR TITLE
Fix bad refactoring which could potentially cause a crash.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide two-character PR.

**Comment by DustinCampbell** [comment]
LOL

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Was this not caught by tests? Is that a test hole or is this just defensive code?

**Pull request merged**
