### PR TITLE
support retries in integration tests

### LINKED ISSUE #36058: Auto-retry failed integration tests
Some flakiness in individual integration tests is outside the current control of this repository. We should implement an auto-retry strategy consisting of the following:

1. Run integration tests
1. If the previous step fails, run integration tests again but exclude all tests that passed in the previous step
1. Report failures from the second step to the build job

This change means the build will only fail if one or more tests fails twice in consecutive launches of the IDE for testing.

### PR DESCRIPTION
**Pull request by ivanbasov**
Resolves #36058

### CODE REVIEW

**Comment by ivanbasov** [comment]
Hi @sharwell ,
Let us start with this.
1. I haven't actually executed this locally. Please let me know tips and tricks about local runs.
2. I suppose this should be implemented some other way for WpfTheories or we should exclude them.
3. I do not know if returning the time from the first attempt is enough or if we should send more to the message bus. See point 1.

**Comment by JoeRobich** [comment]
Just a thought, but I suggested once that we create a separate leg for integration tests that we considered flaky. That way they still ran and we could monitor progress on moving them to the "stable" leg. I think I would prefer a solution more in that vain than simply rerunning failed tests.

**Comment by sharwell** [comment]
@JoeRobich we're going to run some experiments in this branch and come back with clear data before attempting to make a decision.

**Comment by sharwell** [comment]
This LGTM, just waiting on @jaredpar to approve expanding the experiment by merging this.

**Pull request merged**
