### PR TITLE
Watson: Fix crash when accessing CodeProperty.OverrideKind property for property not contained by a type

### PR DESCRIPTION
**Pull request by DustinCampbell**
The root cause is based on analysis of a Watson crash dump with ~300 hits. The call stack looks like this:

```
microsoft_visualstudio_languageservices_csharp_ni!Microsoft.VisualStudio.LanguageServices.CSharp.CodeModel.CSharpCodeModelService.GetOverrideKind
microsoft_visualstudio_languageservices_implementation_ni!Microsoft.VisualStudio.LanguageServices.Implementation.CodeModel.InternalElements.AbstractCodeMember.get_OverrideKind
envdte80!EnvDTE80.CodeProperty2.get_OverrideKind
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeController+AllLanguages+AttributeIsNew.GetAttribute
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeController.GetAttribute
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeController.GetProperties
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler+CodeModelCache.FireAddEvent
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler+CodeModelCache.AddElement
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler.WalkCodeElement
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler+CodeModelCache.AddElementWithChildren
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler+CodeModelCache.RebindChildren
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler+CodeModelCache.ChangeElementUnknown
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler+CodeModelCache.ChangeElement
microsoft_visualstudio_modeling_artifactmapper_vshost!Microsoft.VisualStudio.Modeling.ArtifactMapper.VSHost.CodeHandler.codeModelEvents_Changed
```

After analysis of the dump, I was able to reproduce the call stack using the following steps:

1. Create new Class Library
2. In the Solution Explorer, right-click on Class1.cs and choose View->View Class Diagram from the context menu.
3. Add a new property inside Class1.
4. Copy and paste that property *twice* inside the enclosing namespace of Class1.

This causes an "Unknown" code model event to fire which the Class Designer responds to by digging through its elements and accessing various properties. One of those properties (`OverrideKind`) retrieves the containing type of the element, but that's null for the properties contained in a namespace and the call throws. So, I've added simple null checks to harden against that situation. However, there is a mode serious problem in that Code Model really shouldn't be firing events for members that it doesn't really support (and didn't support in Dev12). So, I've made a deeper change that attempts to faithfully replicate the behavior of Dev12 with regard to what nodes are supported by Code Model.

Tagging @dotnet/roslyn-ide, @Pilchie

### CODE REVIEW

**Comment by Pilchie** [comment]
Did VS2013 also fire the unknown code event?  Could it cause other badness in the class designer even if it doesn't crash?

Otherwise :+1:

**Comment by DustinCampbell** [comment]
I didn't checked VS 2013 because it's awkward to do so. I believe it did, but I'll take a look to be sure.

**Comment by Pilchie** [comment]
Thanks!

**Comment by DustinCampbell** [comment]
AFAICT, we didn't fire an event at all for this situation.

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by DustinCampbell** [comment]
Experimenting with VS 2013 a bit more, it appears that members at the namespace level weren't included in the `CodeNamespace.Members` collection either. I'll take a look at a more comprehensive fix to better match VS 2013.

**Comment by Pilchie** [comment]
Ugh.  Darn that fault tolerance we added to help support interactive.  My guess is that the old parser completely choked on these and codemodel never had to think about it.

**Comment by Pilchie** [comment]
:+1:

**Comment by davkean** [comment]
Closed and reopened to resync with Jenkins.

**Comment by davkean** [comment]
test this please

**Pull request merged**
