### PR TITLE
Disable add usings on paste by default

### PR DESCRIPTION
**Pull request by ryzngard**

### CODE REVIEW

**Comment by Cosifne** [comment]
Why disable it?

**Comment by ryzngard** [comment]
> Why disable it?

There are lots of feedback on this behavior being undesirable in current state for most users. It will still be available as an option to turn on for those who want it. We are looking into other designs to enable this in the future.

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by Cosifne — APPROVED** [review]

**Comment by MartyIX** [comment]
@ryzngard Could you say why they find it undesirable? In a sentence or two.

**Comment by ryzngard** [comment]
> @ryzngard Could you say why they find it undesirable? In a sentence or two.

Absolutely. The current behavior will block the UI thread to do expensive work for getting fixable diagnostics and then determining what usings can be added. While this is fast most of the time, in cases where it's not it becomes increasingly frustrating for the user to see a dialog on every paste event. We're evaluating a new design where we can improve performance here and possibly make the work async. The feature is still available and I encourage you to turn it on :)

**Comment by MartyIX** [comment]
> The feature is still available and I encourage you to turn it on :)

The feature works for me great. I like it very much. I have a middle-sized project so I'm not affected by those longer delays. :)

**Pull request merged**
