### PR TITLE
Fix project file for EE

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Reviewers: @tmat @KevinH-MS @amcasey

**Comment by amcasey** [comment]
Do the C# and VB projects need that too?

**Comment by KevinH-MS** [comment]
If CSharpResultProvider.NetFX20 and VisualBasicResultProvider.NetFX20 fail to build in a similar manner, they will need the same property to be applied (and I'm guessing they will need it).

We should also probably fix up all 3 project.jsons to say "net40" instead of "net20".

**Comment by CyrusNajmabadi** [comment]
I will leave that to you guys :)

**Comment by KevinH-MS** [comment]
Fair enough--if it builds, I don't have a problem with it.

**Pull request merged**
