### PR TITLE
moved to newer optimization package

### PR DESCRIPTION
**Pull request by heejaechang**
removed extra pgo files that weren't in the previous version of the package.

### CODE REVIEW

**Comment by heejaechang** [comment]
test signed bit passed. once it passes tests, I will check this in to create official signed bit.

**Comment by heejaechang** [comment]
private test passed - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2068942&view=results

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure 

it looks like failure has nothing to do with PR?

15:09:23    6 running,  8 queued, 40 completed
15:13:52 FATAL: command execution failed
15:13:52 java.nio.channels.ClosedChannelException
15:13:52 	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
15:13:52 	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:179)
15:13:52 	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
15:13:52 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
15:13:52 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:13:52 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:13:52 	at java.lang.Thread.run(Thread.java:748)
15:13:52 Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from 104.42.145.203/104.42.145.203:1984' is disconnected.
15:13:52 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:212)
15:13:52 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
15:13:52 	at com.sun.proxy.$Proxy183.isAlive(Unknown Source)
15:13:52 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1138)
15:13:52 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1130)
15:13:52 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
15:13:52 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
15:13:52 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
15:13:52 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
15:13:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
15:13:52 	at hudson.model.Build$BuildExecution.build(Build.java:206)
15:13:52 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
15:13:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
15:13:52 	at hudson.model.Run.execute(Run.java:1724)
15:13:52 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
15:13:52 	at hudson.model.ResourceController.execute(ResourceController.java:97)
15:13:52 	at hudson.model.Executor.run(Executor.java:429)

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_debug_unit64_prtes please

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is jenkins down?

**Comment by MattGal** [comment]
@heejaechang unfortunately about every month or so we hit issues with Windows update causing machines to reboot.  @alexperovich is looking at the same issue on a different queue here: https://github.com/dotnet/core-eng/issues/4228 .  While it's still possible that the connections drop for other reasons (Jenkins being one) the specific types of jobs  (long running Windows-based Jenkins jobs) are the most susceptible to the problem.  

We continue to investigate this issue (it did seem to be less prominent recently but that could be coincidence) and seek a way to prevent WU-related reboots.  Please monitor that issue for updates.

**Comment by heejaechang** [comment]
retest windows_release_unit32_prtest  please

**Comment by heejaechang** [comment]
retest windows_debug_unit64_prtest  please

**Comment by jasonmalinowski** [comment]
The internal signed build confirms this is good, so going to override Jenkins' failures.

**Comment by MattGal** [comment]
My apologies, and please keep trying as it should eventually work.  Jenkins is doing OK, we're actually having a Service bus problem as detailed in the linked issue. Whenever Service Bus errors out and drops work items, we drop Jenkins jobs. I'll send a summary to partners as heads up shortly.

**Pull request merged**
