### PR TITLE
Fix three .editorconfig bugs

### PR DESCRIPTION
**Pull request by jasonmalinowski**
These make the full end-to-end experience work.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Any way to test this?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Yeah, I'll add a test, at least for the first one. I just wanted this off my machine before I close it for the night. :-)

**Comment by CyrusNajmabadi** [comment]
Thanks! :)

**Comment by jasonmalinowski** [comment]
Thank you for asking; good to always keep people honest!

**Pull request merged**
