### PR TITLE
Making add static more deterministic

### PR DESCRIPTION
**Pull request by jmarolf**
Don't just look at static types.

fixes https://github.com/dotnet/roslyn/issues/5359

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide

**Comment by jmarolf** [comment]
test eta please

**Comment by jmarolf** [comment]
retest prtest/win/dbg/unit32 please

**Comment by davkean** [comment]
@dotnet/roslyn-ide Can someone look over this? This PR is ~2 weeks old and hasn't had any eyes on it.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by jmarolf** [comment]
retest all please

**Comment by jmarolf** [comment]
retest prtest/lin/dbg/unit32 please
retest prtest/mac/dbg/unit32 please
retest prtest/win/dbg/eta please
retest prtest/win/dbg/unit32 please
retest prtest/win/dbg/unit64 please

**Pull request merged**
