### PR TITLE
Merge dev15.1.x to master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15.1.x into master.

``` bash
git fetch --all
git checkout merges/dev15.1.x-to-master-20170310-080005
git reset --hard upstream/master
git merge upstream/dev15.1.x
# Fix merge conflicts
git commit
git push merges/dev15.1.x-to-master-20170310-080005 --force
```

Once all conflicts are resolved and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
@tmat Please take a look.  The following test is failing: Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.CompilationChain_NestedTypesClass

**Comment by CyrusNajmabadi** [comment]
Merging as all required tests are passing.

**Pull request merged**
