### PR TITLE
DryDock Effort: Removing the skipped unit tests from SimplifyTypeNamesTests

### PR DESCRIPTION
**Pull request by jinujoseph**
Associated work item http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems?_a=edit&id=1033012
has been marked as won't fix

@srivatsn @mavasani 
@dotnet/roslyn-ide

### CODE REVIEW

**Comment by jinujoseph** [comment]
test eta please

**Comment by davkean** [comment]
test eta please

**Comment by CyrusNajmabadi** [comment]
I don't understand why we would not fix this issue.

**Comment by DustinCampbell** [comment]
Agreed. At least the first unit test removes looks like a product bug.

**Comment by jinujoseph** [comment]
Had a conversation with @CyrusNajmabadi , created a new issue #9877 and mapped the skipped test to the same.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by DustinCampbell** [comment]
Hey @jinujoseph -- is #9877 the correct issue? It doesn't look at all related to this.

**Pull request merged**
