### PR TITLE
made internal data structure to care about dll versions

### PR DESCRIPTION
**Pull request by heejaechang**
we have changed AnalyzerFileReference.Id to include versions, public keys and etc as its identity.

some internal data structure that generates string from it didn't changed accordingly.

this should fix the issue.

### CODE REVIEW

**Comment by heejaechang** [comment]
fixes #3030

@mavasani @srivatsn @tmeschter can you take a look? very simple change.

**Comment by heejaechang** [comment]
@srivatsn this is RTM bug, so I guess we need to bring this to ask mode?

**Comment by heejaechang** [comment]
not meeting ask mode bar. checking in to main only.

**Comment by mavasani** [comment]
:+1:

**Pull request merged**
