### PR TITLE
make telemetry to only log when there are multiple files re-analyzed

### PR DESCRIPTION
**Pull request by heejaechang**
**Customer scenario**

typing html code is several milliseconds better than before.

**Bugs this fixes:** 

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/368117

**Workarounds, if any**

No workaround

**Risk**

No functional change, I don't see any risk on this change

**Performance impact**

typing html code is now several milliseconds faster. but it also reduce amount of data we send to App Insight. 

Verified it fixes RPS regression by running private RPS run.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

fixing a bug caused VS telemetry to be called on every keystroke.
(https://github.com/dotnet/roslyn/pull/16289)

**How was the bug found?**

RPS testing

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @dotnet/roslyn-perf @srivatsn can you take a look?

**Comment by heejaechang** [comment]
@mavasani @tmeschter so I guess I need to get RPS number before asking for approval. what should I do?

**Comment by heejaechang** [comment]
@mavasani ping?

**Comment by heejaechang** [comment]
sorry @mavasani I also meant how I can run private RPS run to confirm the fix.

**Comment by mavasani** [comment]
@tmeschter is helping @CyrusNajmabadi with similar validation - they were facing some infrastructure issues. Can you follow up with them offline?

**Comment by heejaechang** [comment]
@dotnet/roslyn-perf can I get other sign off? really simple change. @rchande ?

**Comment by heejaechang** [comment]
@MattGertz can I bring this to RTW shiproom? this fix RPS regression. @natidea

**Comment by natidea** [comment]
Approved to merge via [368117](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/368117)

**Pull request merged**
