### PR TITLE
[WIP][Personal] TypeOfMany

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Prototyping `TypeOf obj Is {T0,T1,T2}` for vb

### CODE REVIEW

**Comment by gafter** [comment]
This does not correspond to any planned language change, so I am not interested in spending time reviewing it.

**Comment by AdamSpeight2008** [comment]
@gafter You don't have to review as is `PR For Personal Review Only` but I cant add tags, hence the title tags.

**Comment by gafter** [comment]
You did request a review

**Comment by AdamSpeight2008** [comment]
@gafter I didn't explicitly ask for one on this PR yet,  think the review was automatic as the PR touch area of code owned by `roslyn ide`

**Comment by jaredpar** [comment]
As stated several times before and listed in the contribution guidelines: please do not send PRs for language features that we have not been previously in touch about. There is no way for us to be any clearer about this.

**Pull request closed without merging**
