### PR TITLE
Properly highlight written references differently in FindRefs

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Looks like this: 

image

(of course, with whatever color you've actually chosen for written references).

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Pull request merged**
