### PR TITLE
ISymUnmanagedWriter cleanup

### PR DESCRIPTION
**Pull request by tmat**
Remove workaround that is no longer needed, tidy up COM interface definitions.

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by tmat** [comment]
@AlekseyTs @TyOverby @VSadov @gafter @agocke  Ping

**Comment by agocke** [comment]
:+1:

**Comment by AlekseyTs** [comment]
LGTM

**Comment by tmat** [comment]
Thanks!

**Pull request merged**
