### PR TITLE
Revert "Implement equality semantics for async tagger tags."

### PR DESCRIPTION
**Pull request by genlu**
Reverts dotnet/roslyn#64802 to fix errors in [insertion](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/430655), which breaks TypeScript tagger 
1. https://github.com/dotnet/roslyn/pull/64802#discussion_r1000985298
2. https://github.com/dotnet/roslyn/pull/64802/files#r1000998300

FYI @CyrusNajmabadi a dual insertion with TS is required to reinstate the change

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
what is the error in insertion?

**Comment by CyrusNajmabadi** [comment]
if there is a third party that is extending this type, we can solve this by making the member non-abstract, and giving it a default impl of `object.Equals(tag1, tag2);`

**Comment by CyrusNajmabadi** [comment]
I can make such a change fyi.

**Comment by CyrusNajmabadi** [comment]
Non-breaking fix here: https://github.com/dotnet/roslyn/pull/64869

**Comment by RikkiGibson** [comment]
In general, it's encouraged to link the associated insertion when opening a revert.

**Comment by genlu** [comment]
@RikkiGibson Thanks for the reminder, link to insertion added

**Review by arkalyanms — APPROVED** [review]

**Review by JoeRobich — APPROVED** [review]

**Comment by Cosifne** [comment]
BTW the original change also breaks the Integration test.
See my PR here for the fix https://github.com/dotnet/roslyn/pull/64852

**Pull request merged**
