### PR TITLE
Add RHEL 7 runtime IDs

### PR DESCRIPTION
**Pull request by omajid**
Roslyn won't build on RHEL 7 just yet. There's a few issues that I am working through, including https://github.com/dotnet/roslyn/issues/17421

I will open separate PRs for those.

### CODE REVIEW

**Comment by omajid** [comment]
Ping?

/cc @ellismg

**Comment by jcouv** [comment]
I'm not sure we should add this runtime until it is supported.
Ping @jaredpar @agocke for review.

**Comment by omajid** [comment]
@jcouv hey, can you explain a little about what "supported" in this context means? Is roslyin going to endorse a few distributions as "supported" for building and others can't be used?

**Comment by jcouv** [comment]
Sorry I wasn't clear. I was not implying any kind of support policy.
I was referring to your comment "Roslyn won't build on RHEL 7 just yet." If this runtime isn't supported in build, why add it? Maybe fold this into your subsequent PR to enable an observable scenario.

**Comment by omajid** [comment]
Fair enough. Thank you for clarifying.

**Comment by omajid** [comment]
Closing in favour of https://github.com/dotnet/roslyn/pull/19472

**Pull request closed without merging**
