### PR TITLE
Migrate Codelens provider to .NET

### PR DESCRIPTION
**Pull request by genlu**
val build: ~~https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=10026486&view=results~~
~~https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=10035404&view=results~~
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/586489

### CODE REVIEW

**Comment by genlu** [comment]
@dotnet/roslyn-ide This is now ready for review. @allisonchou has confirmed the change works with the .NET codelens host from editor. I'm keeping this PR as draft because it's blocked until the change on editor side landed in VS.

**Comment by CyrusNajmabadi** [comment]
> @dotnet/roslyn-ide This is now ready for review

want to take out of draft?

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by genlu** [comment]
@CyrusNajmabadi Keeping it a draft so we don't accidentally merge it before editor insert their change

**Comment by CyrusNajmabadi** [comment]
Ah ok!

**Pull request merged**
