### PR TITLE
Classify pattern variables

### PR DESCRIPTION
**Pull request by alrz**
Fixes https://github.com/dotnet/roslyn/issues/59484

### CODE REVIEW

**Review by Youssef1313 — APPROVED** [review]

**Review by Youssef1313 — COMMENTED** [review]
@alrz Can you merge the latest main and run this test locally:

https://github.com/dotnet/roslyn/blob/220b3ebfd25a839b3abc1b0096eaca0b9de0a3c2/src/EditorFeatures/CSharpTest/Classification/SyntacticClassifierTests.cs#L5109-L5125

I think it will fail (`Identifier("x")` should be `Local("x")`), then you need to update it.

This test didn't exist when you first opened the PR.

**Review by sharwell — APPROVED** [review]
I don't see an issue here but @CyrusNajmabadi should double check

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by alrz** [comment]
> @alrz Can you merge the latest main and run this test locally

Thanks for the pointer. I'll take a look.

**Comment by alrz** [comment]
Failures seem to be unrelated. @CyrusNajmabadi

**Comment by alrz** [comment]
ping @CyrusNajmabadi (looks like one check is still blocking)

**Comment by CyrusNajmabadi** [comment]
We're having issues with ci. Likely won't be able to merge until Monday unless someone can fix that.

**Review by sharwell — APPROVED** [review]

**Comment by alrz** [comment]
@CyrusNajmabadi Should I sync this with main?

**Comment by alrz** [comment]
I can't anyways, sounds like git is entirely blocked on GH right now.

**Comment by alrz** [comment]
> We're having issues with ci. Likely won't be able to merge until Monday unless someone can fix that.

It's been quite a few Mondays since the last time, still not green. :(

**Comment by Youssef1313** [comment]
@alrz The current failure is `roslyn-integration-corehost` which isn't required for merge. It should be okay to merge as is now.

@CyrusNajmabadi Can you merge please?

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
