### PR TITLE
Remove some unnecessary <SubType>Code</SubType>

### PR DESCRIPTION
**Pull request by jasonmalinowski**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
FYI: my vs keeps adding these back in.

**Comment by sharwell** [comment]
> FYI: my vs keeps adding these back in.

This is a known bug. The changes should not be committed to source control.

**Comment by CyrusNajmabadi** [comment]
Super frustrating as it means having to manually review/fixup every commit you make

**Comment by CyrusNajmabadi** [comment]
Is tehre a downside to checkin these in, then taking them out once the bug is fixed?

**Comment by sharwell** [comment]
> Is tehre a downside to checkin these in, then taking them out once the bug is fixed?

Some builds have the opposite behavior right now.

**Comment by jasonmalinowski** [comment]
Yeah, internal builds fixed the bug of adding things they shouldn't; the side effect is now they remove things too. Since this PR is putting the repo into the "final state the repository should be in...eventually", let's just go with this since unfortunately there's now no state that can please everybody.

**Pull request merged**
