### PR TITLE
Add some unit-tests.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #9021, #12078, #12266, #12267.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by agocke** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
As you know, this PR contains a unit test that contradicts current LDM position on #9021.

**Comment by jcouv** [comment]
LGTM
Thanks!

**Comment by AlekseyTs** [comment]
> As you know, this PR contains a unit test that contradicts current LDM position on #9021.

@gafter As usual, you are confusing **your** opinion with LDM position.

**Comment by gafter** [comment]
> @gafter As usual, you are confusing your opinion with LDM position.

As the LDM-assigned language designer for this feature, my expressed opinion is the LDM position until there is a decision otherwise. This question was opened for discussion to the LDM and no member argued to change the status quo. There has been no confusion: this is both my opinion and the LDM decision.

**Comment by AlekseyTs** [comment]
windows_eta_open_prtest reports some strange merge conflict:

GitHub pull request #12268 of commit 67ac07712b0f7123ff824c96de0148da3d30bc46, has merge conflicts.

Ignoring, this change only affects compiler tests

**Pull request merged**
