### PR TITLE
Fix parsing of langVersion 14.0

### LINKED ISSUE #3393: vbc doesn't parse langversion 14 properly
From CommandLineParser.vb

``` vb
Case "14", "14.0"
  languageVersion = LanguageVersion.VisualBasic12
```

This is a breaker to anyone who uses the `/langversion` switch to control the language as does the ASP.Net team.

### PR DESCRIPTION
**Pull request by jaredpar**
Fix the parsing of langVersion 14.0 to be 14 instead of 12.

closes #3393

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @AlekseyTs, @gafter, @agocke, @khyperia

**Comment by jaredpar** [comment]
Bug Data

- Bug number: Fixes #3393
- Customer scenario: Passing 14 to the `/langversion` switch will silently change the language to version 12.  
- Fix description: Use the correct value for the user specified version 14.
- Testing done: unit-tests.

**Comment by MattGertz** [comment]
Approved 6/9 by ML Shiproom.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
LGTM

**Pull request merged**
