### PR TITLE
Upgrade NuGet to 3.4.0.247 and increase restore timeout

### PR DESCRIPTION
**Pull request by davkean**
NuGet's timeout for restoring us is too short, causing a
timeout on our internal build machines when the CPU is
under high load. We need to upgrade to 3.4 to control
this.

Increase this to 20 minutes from the default 5 minutes.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @jaredpar @agocke

**Comment by davkean** [comment]
Internal changes to opt into this coming in later change.

**Comment by davkean** [comment]
Closed and reopened to resync with Jenkins.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by davkean** [comment]
ETA failure: https://github.com/dotnet/roslyn/issues/7379.

@dotnet-bot retest eta please

**Comment by agocke** [comment]
:+1:

**Comment by davkean** [comment]
Merging this in - this is the number one cause of failures outside of VSI failures. We've passed NuGet restore in the eta step.

**Pull request merged**
