### PR TITLE
Don't show a count for FAR definitions with zero references to them.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Improvement, but not total fix, for https://github.com/dotnet/roslyn/issues/20259

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
There is no way to display (0) for these nodes.  We could consider a DCR for that.  But showing nothing is still better than showing (1) which is clearly wrong.

**Comment by sharwell** [comment]
@CyrusNajmabadi Can we not just append `" (0)"` to the message at the same time we disable the count?

**Comment by CyrusNajmabadi** [comment]
Unfortunately, we don't own most of the 'buckets'.  So we could change some of the buckets, but we'll still end up with others that say things like (1) or (2) depending on what is underneath them.  I think my idea would be to bake this into the core API, and have the system that produces the counts aware of these special 'non-counting' rows.

**Comment by CyrusNajmabadi** [comment]
Closing this out.  We'll improve this through work on the editor tracked here: https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=457565&triage=true

**Pull request closed without merging**
