### PR TITLE
Add missing dependecies for Core Host

### PR DESCRIPTION
**Pull request by genlu**
@sharwell @tmat

### CODE REVIEW

**Comment by tmat** [comment]
Odd, why are these needed for Core and not for net472?

**Comment by genlu** [comment]
@tmat those binaries can be resolved on desktop framework, since they located in the same folder.

**Comment by tmat** [comment]
I guess we have hidden MEF dependencies? :(

**Comment by genlu** [comment]
@tmat I'm not sure if we need both C# and VB EditroFeature for remote (maybe only Feature is enough? Any idea?), but we are definitely missing all VB stuff.

**Comment by genlu** [comment]
@tmat @sharwell Included up to Features layer as discussed offline. Removing EF reference is tracked by https://github.com/dotnet/roslyn/issues/55142

**Review by tmat — APPROVED** [review]

**Pull request merged**
