### PR TITLE
[AskMode] Change parsing of #! from Comment -> Directive...

### PR DESCRIPTION
**Pull request by KevinH-MS**
This change adds a ShebangDirectiveTriviaSyntax type to the public API.

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @jaredpar @DustinCampbell 
/cc @brettfo @dotnet/roslyn-compiler

**Comment by VSadov** [comment]
LGTM

**Comment by brettfo** [comment]
:shipit:

**Comment by MattGertz** [comment]
Approved pending successful test completion.

**Comment by KevinH-MS** [comment]
test unit32 please

**Comment by KevinH-MS** [comment]
test win unit32 please

**Comment by KevinH-MS** [comment]
test lin please

**Comment by KevinH-MS** [comment]
test Linux please

**Comment by KevinH-MS** [comment]
Can one more person from @dotnet/roslyn-compiler please review?  Thanks!

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
