### PR TITLE
enable initial D15 unit tests

### PR DESCRIPTION
**Pull request by heejaechang**
re-enable initial d15 unit tests.

working on more unit tests. will send next PR.

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani @panopticoncentral can you take a look?

**Comment by heejaechang** [comment]
ping?

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest  please

**Comment by heejaechang** [comment]
@mavasani can I get sign off?

**Comment by heejaechang** [comment]
@MattGertz can I get approval for rc3? sorry I checked in I didn't know master was in lock down.

**Comment by heejaechang** [comment]
@MattGertz changes are mostly on adding unit tests for OOP

**Comment by MattGertz** [comment]
Approved for rc3.

**Pull request merged**
