### PR TITLE
Avoid duplicate syntax node callbacks for CompilationUnitSyntax nodes…

### LINKED ISSUE #58561: Duplicate syntax node callbacks for top-level statements
> Here is a _seemingly_ suspicious assert:
> 
> https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5111-L5122
> 
> Specifically, both `FireCount3` and `FireCount5` are 1
> 
> Here is where those counters are incremented:
> 
> https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5156
> 
> https://github.com/dotnet/roslyn/blob/80d7e32b44a83246eb26ecac9bca3c2283b8d938/src/Compilers/CSharp/Test/Semantic/Semantics/SimpleProgramsTests.cs#L5189-L5199
> 
> So it looks like `Handle2` was called for the same syntax node but different `ContainingSymbol`.

Thanks @Youssef1313. That confirms similar issue exists with top-level statements. I am going to create a separate tracking issue and PR to address that one.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/58482#issuecomment-1004101585_

### PR DESCRIPTION
**Pull request by mavasani**
… for files with top level statements

Fixes #58561
Follow-up change to #58482

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313

**Review by Youssef1313 — COMMENTED** [review]
It might be worth adding tests for the nodes checked in:

https://github.com/dotnet/roslyn/blob/755ec14dac0b42ad7de8c234aee0eb137002e80d/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L2515

https://github.com/dotnet/roslyn/blob/755ec14dac0b42ad7de8c234aee0eb137002e80d/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L2524

If they have issues, we can add a comment in:

https://github.com/dotnet/roslyn/blob/755ec14dac0b42ad7de8c234aee0eb137002e80d/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L2424

to prevent future bugs when new syntax nodes are checked in `GetSyntaxNodesToAnalyzeFilter`

**Comment by mavasani** [comment]
@Youssef1313 Thanks for the suggestions. That would be outside the scope of this PR as it unrelated to top level statements. We can file a separate test issue to increase coverage for those cases.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

**Review by 333fred — APPROVED** [review]

**Pull request merged**
