### PR TITLE
Make tests strongly typed.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by jmarolf** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:  Why was this ever object?

**Comment by balajikris** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
I have no idea why this was ever object.  It seems to have happened when the Analyzer refactoring came in.  My guess is that maybe at one point you could return a CodeRefactoringProvider or a CodeFixProvider.

**Pull request merged**
