### PR TITLE
Resolve merge issue that caused duplicate VB error IDs

### LINKED ISSUE #13134: Two VB error codes have same numeric value
https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Errors/Errors.vb#L1689

``` VB
ERR_SourceLinkRequiresPortablePdb = 37258
ERR_TupleExplicitNamesOnAllMembersOrNone = 37258
```

@VSadov @tmat Merge issue?

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #13134

### CODE REVIEW

**Comment by nguerrera** [comment]
@jaredpar @tmat @VSadov Please review

**Comment by tmat** [comment]
:+1:

**Comment by nguerrera** [comment]
@dotnet/roslyn-compiler Ping.

**Comment by nguerrera** [comment]
@dotnet-bot retest microbuild_prtest please

Retest reason: Looks like infrastructure issue. I'll file a bug.

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/microbuild_prtest/1577/

**Comment by jcouv** [comment]
:shipit:

**Comment by cston** [comment]
LGTM

**Pull request merged**
