### PR TITLE
Fix a null ref in symbol tree info.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
See below

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
**Customer scenario**

VS crashes when referencing metadata that Roslyn can't load.

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/_workitems?id=445161&_a=edit

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

Low.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

A previous change to our metadata index made us resilient to bad metadata.  However, it did so by producing an empty-index that wasn't completely initialized.  This empty index then caused a crash later on down the line if somone called a specific search API.  

This change fixes things so that the index is properly initialized so that these later searches don't fail.

**How was the bug found?**

Customer reported.  Large number of watson hits.

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz @natidea     
Ask mode template here: https://devdiv.visualstudio.com/DevDiv/_workitems?id=445161

**Comment by CyrusNajmabadi** [comment]
@Pilchie I've made those changes in master: https://github.com/dotnet/roslyn/pull/20702 
For 15.3. i've gone with the simplest and safest change.

**Comment by MattGertz** [comment]
Thanks, I will submit to JoC & Shiproom on Monday.

**Comment by CyrusNajmabadi** [comment]
@MattGertz Any status update here?

**Comment by MattGertz** [comment]
No.  I couldn't access bugs yesterday, so I'll be bringing bugs today at noon.

**Comment by natidea** [comment]
Approved to merge via [445161](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/445161)

**Pull request merged**
