### PR TITLE
Don't group symbols by definition when we show them for Goto-Impl/Goto-Def

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
"Grouping By Definition" is just not a helpful mode for features like Go-To-Implementation  That's because you end up just seeing something like this:

image

There's no need to show both the definition symbol and the location it is out.  Now we just show the locations of the actual implementations, making the display much cleaner.

image

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by saul** [comment]
You've lost the class name now, though. In the first screenshot you see Derived1 and Derived2 and Program.

**Comment by CyrusNajmabadi** [comment]
@saul Good point.  Checking with the editor team to see if i can keep the grouping, but hide the actual item.

@tmat The item in the list isn't a SymbolDisplay result.  It's the actual source code where the entity is located.

**Comment by CyrusNajmabadi** [comment]
Ideal: 

image

**Comment by CyrusNajmabadi** [comment]
Closing in favor of: https://github.com/dotnet/roslyn/pull/16866

**Pull request closed without merging**
