### PR TITLE
Remove obsolete ToTestDisplayString method

### LINKED ISSUE #11915: Remove duplicate copies of test helper ToTestDisplayString extension method
Currently, there are multiple copies of extension method [ToTestDisplayString](http://source.roslyn.io/#q=ToTestDisplayString) in C# and VB compiler test layers. We should move this extension method to the core test utilities project and remove the duplicate copies and fix all the callsites by adding the necessary using.

### PR DESCRIPTION
**Pull request by nbalakin**
Fixes #11915

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Spanish run failed due to the xunit runner crashing when unloading an appdomain (?) I can't discern any other information from the crash dump. Rerunning.

**Comment by sharwell** [comment]
@RikkiGibson The failure was caused by https://github.com/xunit/xunit/issues/2097

**Comment by nbalakin** [comment]
I've accidentally removed `dotnet/roslyn-compiler` from reviewers list. Not sure how to add it back.

**Comment by jcouv** [comment]
No worries, the `Area-Compilers` label is enough that we'll notice this PR.

**Comment by jcouv** [comment]
Merged/squashed. Thanks @nbalakin for the contribution!

**Pull request merged**
