### PR TITLE
Fix AnalyzerRunner failure to load Microsoft.Build.Framework

### PR DESCRIPTION
**Pull request by sharwell**
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at AnalyzerRunner.Program.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at AnalyzerRunner.Program.Main(String[] args)
   at AnalyzerRunner.Program.<Main>(String[] args)
```

### CODE REVIEW

**Comment by sharwell** [comment]
@jasonmalinowski I do not know how/why this fixes the problem. After getting loader exceptions, I copied the approach from dotnet/format, and when it worked I sent this pull request.

https://github.com/dotnet/format/blob/d6a90a3013f5ace4efd42525b0b0400c7ced610e/src/dotnet-format.csproj#L29-L30

**Comment by JoeRobich** [comment]
The changes to support producing a binary log from MSBuildWorkspace use the ILogger interface =/
https://github.com/dotnet/roslyn/blob/d4fb1db122dbdac048c1def403fa4d4fd5ac5456/src/Workspaces/Core/MSBuild/MSBuild/MSBuildWorkspace.cs#L180-L209

**Comment by sharwell** [comment]
> Do we understand why this fixes it though?

Not currently. The MSBuildLocator is still magic to me.

**Comment by sharwell** [comment]
Merging to 16.6 as non-production code only.

**Pull request merged**
