### PR TITLE
Port Tuple SymbolDisplay tests to VB

### LINKED ISSUE #10861: Need to settle/confirm on final state of tuple visualization
There are some flags like "MinimallyQualify" that may or may not need to have effect on tuple visualization recursively.

Ensure that we have agreement on the right behavior here. And tests.

### PR DESCRIPTION
**Pull request by cston**
Fixes #10861.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @jcouv please review.

**Comment by cston** [comment]
cc @dotnet/roslyn-ide

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
