### PR TITLE
Merge dev15-rc into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15-rc into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-dev15-rc-into-master20161017-225723
git reset --hard upstream/master
git merge upstream/dev15-rc
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-dev15-rc-into-master20161017-225723 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by VSadov** [comment]
@dotnet-bot test windows_vsi_p0_open_prtest  please

**Comment by VSadov** [comment]
@dotnet-bot test windows_eta_open_prtest please

**Comment by VSadov** [comment]
@dotnet-bot test windows_vsi_p1_open_prtest please

**Comment by VSadov** [comment]
test windows_vsi_p1_open_prtest please

**Comment by VSadov** [comment]
test windows_vsi_p0_open_prtest please

**Comment by VSadov** [comment]
test windows_vsi_p0_open_prtest please

**Pull request merged**
