### PR TITLE
Add LockStatement to SyntaxGenerator

### PR DESCRIPTION
**Pull request by bpierson**
There is currently no way to use the abstract `SyntaxGenerator` class to generate a locked section of code. This means that to create a lock block, one must use the static methods defined in the `SyntaxFactory` class, which are specific to a target language (currently C# or VB).

This PR will add a `LockStatement` method to the `SyntaxGenerator` abstract class, and implementations of this method in `CSharpSyntaxGenerator` and `VBSyntaxGenerator`.

This new method will forward the bulk of its work to the `LockStatement` method defined in `Microsoft.CodeAnalysis.CSharp.SyntaxFactory`, and the `SyncLockBlock` method defined in `Microsoft.CodeAnalysis.VisualBasic.SyntaxFactory`.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
You've done some veyr strange branching/merging.  You should only be branching off post-dev15 and only doing your own work off of that branch.  The fact that your branch is called "bpierson:master" makes me think you did this work off of your fork of our master branch.  Instead of your fork of our post-dev15 branch.

**Comment by bpierson** [comment]
You're right - I misunderstood. I forked the master and then did the PR on
the postdev branch. I haven't done anything yet except describe the PR, so
I'll delete the bpierson/roslyn and re-fork from postdev15. Thanks for your
help - I'm a little green at this. 15 years of C# but new to git. :)

**Comment by CyrusNajmabadi** [comment]
Totally understood.  Trust me, i did all the same stuff as i started building up my git-fu! :)

**Comment by bpierson** [comment]
@CyrusNajmabadi , I'm not sure how to delete this PR - I don't want to mess anything up. Is there a way you could remove it? Sorry for the bother.

**Comment by CyrusNajmabadi** [comment]
I've closed it :)

**Comment by bpierson** [comment]
Thanks Cyrus, I'll delete my fork and try again when I have some time and
studied up a bit. :)

**Pull request closed without merging**
