### PR TITLE
Correct spacing on nullable tuple type

### PR DESCRIPTION
**Pull request by jcouv**
The formatter current prefers `(int, string) ? t;` over `(int, string)? t;`.
This is because the rule for formatting parenthesis comes before the rule for handling nullable type. I'm switching the order around to give priority to the rule for nullable type, which is more specific.

Fixes https://github.com/dotnet/roslyn/issues/11988
@CyrusNajmabadi @dotnet/roslyn-ide for review.
FYI for @gafter @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by gafter** [comment]
:shipit:

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by jcouv** [comment]
Thanks! Merged

**Pull request merged**
