### PR TITLE
Disable package search until we have some better memory information.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @davkean @dotnet/roslyn-ide

**Comment by davkean** [comment]
tag @MattGertz @heejaechang @dotnet/roslyn-infrastructure 

This is the change to turn off NuGet package search.

**Comment by heejaechang** [comment]
if everything goes well (all test passes, here and in sign build), I will babysit to make sure it goes into vsuml.

**Comment by MattGertz** [comment]
Approved pending testing.

**Comment by Pilchie** [comment]
Not saying to change this tonight, but we should consider making this enablable via a reg key to enable internal testing, or using remote control to do a/b testing.

**Comment by davkean** [comment]
We're abandoning this change Kevin, and disabling via remote control.

**Pull request closed without merging**
