### PR TITLE
Moving CA1018 and CA1019 to System.Runtime.Analyzers

### PR DESCRIPTION
**Pull request by srivatsn**
Moving the analyzers is straightforward. For CA1019, I've added a fixer that will generate the property accessors for an attribute constructor's parameters.

### CODE REVIEW

**Comment by srivatsn** [comment]
Moved CA1036 as well. Working on fixer for it.

**Comment by tmeschter** [comment]
:+1:

**Comment by srivatsn** [comment]
Added another commit for a codefix for CA1036

**Comment by tmeschter** [comment]
:+1: modulo my other comments.

**Pull request merged**
