### PR TITLE
Move suggestion options down to EditorFeatures lib.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Review by ryzngard — APPROVED** [review]
AFAIK if this change compiles then :shipit:

**Comment by RikkiGibson** [comment]
@CyrusNajmabadi Please target release/dev17.0-vs-deps with this change.

**Review by davidwengier — APPROVED** [review]

**Review by RikkiGibson — CHANGES_REQUESTED** [review]
blocking until the base branch is fixed.

**Comment by RikkiGibson** [comment]
Superseded by #54549

**Pull request closed without merging**
