### PR TITLE
Don't crash in QuickInfo if the search for linked tokens goes out of bounds

### PR DESCRIPTION
**Pull request by natidea**
Port #17884 and #21567 to dev15.0.x

15.0.x Tracking Bug: [484304](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/484304)

### CODE REVIEW

**Comment by natidea** [comment]
test vsi please

**Comment by Pilchie** [comment]
@natidea - can this be closed now?

**Comment by natidea** [comment]
yes, closing

**Pull request closed without merging**
