### PR TITLE
made default namespace Solution/Project APIs public

### PR DESCRIPTION
**Pull request by filipw**
Fixes https://github.com/dotnet/roslyn/issues/35173

This will allow OmniSharp (and by proxy, C# extension in VS Code) to offer SyncNamespace refactoring.

Just putting this out there 😇

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
I don't mind this.  But i'm not sure i understand this bit

> This will allow OmniSharp (and by proxy, C# extension in VS Code) to offer SyncNamespace refactoring.

Doesn't sync-namespace already have internal access here?  If it works in VS, why would it need to be public to work in these other hosts?  Thanks!

**Comment by filipw** [comment]
> Doesn't sync-namespace already have internal access here?

When OmniSharp builds up `ProjectInfo`s to populate the workspace, there is currently no way to construct those with the default namespace configured for the sync refactoring to work in the first place (unless I am missing something).

**Comment by jasonmalinowski** [comment]
These were internal largely because we were just stabilizing the feature and didn't want to lock an API we were still actively building. But at this point I feel good about it.

**Comment by sharwell** [comment]
Blocked to verify the public API is approved

**Comment by genlu** [comment]
@jasonmalinowski Should we make `Project.DefaultNamespace` public too?

**Comment by genlu** [comment]
@filipw does OmniSharp use MSBuildWorkspace? Or you have your own project system that handles project creation, etc.?

**Comment by filipw** [comment]
> @filipw does OmniSharp use MSBuildWorkspace? Or you have your own project system that handles project creation, etc.?

it uses it's own `OmniSharpWorkspace` and manages projects on its own (by consuming msbuild nuget packages)

**Comment by filipw** [comment]
> @jasonmalinowski We probably should make `Project.DefaultNamespace` public too.

that's a good point - rebased and added it

**Comment by genlu** [comment]
@vatsalyaagrawal @jinujoe for approval.

**Comment by jinujoseph** [comment]
@genlu this is needed in 16.2 ? or 16.3 sounds good ?

**Comment by filipw** [comment]
we consume prerelease Roslyn builds in OmniSharp so it doesn't really matter - thanks

**Comment by genlu** [comment]
@filipw Then let's retarget this to dev16.3-preview1 branch

**Comment by filipw** [comment]
done

**Comment by genlu** [comment]
@filipw Merged. Thanks!

**Pull request merged**
