### PR TITLE
Discard a reference to project being emitted when debugging session terminates

### PR DESCRIPTION
**Pull request by tmat**
Internal bug 254128.

### CODE REVIEW

**Comment by tmat** [comment]
@MattGertz For approval
/cc @ManishJayaswal @natidea @jasonmalinowski

**Comment by MattGertz** [comment]
Approved to bring to shiproom.

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
:+1:

**Pull request merged**
