### PR TITLE
track session across remote host

### PR DESCRIPTION
**Pull request by heejaechang**
now OOP tracks session id across 2 processes. VS and remote host.

this should let us use exact connection for the session communication and use exact pinned snapshot for the session.

this should improve cancellation tracking (since we use connection for cancellation) and perf of finding pinned asset for the session.

this should also fix the issue where named pipe connectAsync spin wait for server which already got cancelled.

### CODE REVIEW

**Comment by heejaechang** [comment]
in next PR, I will remove magic solution checksum from service API.

**Comment by heejaechang** [comment]
@panopticoncentral @CyrusNajmabadi @KevinH-MS @mavasani @srivatsn can you take a look?

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest  please

**Comment by heejaechang** [comment]
@panopticoncentral paul, this should fix one of issue I found around code lens, can you take a look?

**Comment by panopticoncentral** [comment]
:shipit:

**Pull request merged**
