### PR TITLE
Ensure that we call out to third parties in FAR in the same context that we were called on.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @Pilchie

**Comment by MattGertz** [comment]
I don't think this meets the Escrow bar but I'm willing to listen @CyrusNajmabadi @Pilchie.

**Comment by CyrusNajmabadi** [comment]
Sorry, i should have been more clear.  The *trigger* is highlight-references.  The effect is that VS crashes.  Highlight-references is super common because it happens all the time as your cursor moves around.

**Comment by MattGertz** [comment]
@CyrusNajmabadi Well that does put a different spin on things :-) -- that would definitely meet the bar IMO. @natidea Nat let's track this one on the list please.  Approved to take pending CRs and testing.

**Comment by Pilchie** [comment]
:+1:  Hit this twice already this morning while working on DPL.

**Comment by Pilchie** [comment]
test vsi please

**Comment by natidea** [comment]
We'll take to shiproom tomorrow. Please hold off merging until it is approved in shiproom.

**Comment by CyrusNajmabadi** [comment]
retest windows_eta_open_prtest  please

**Pull request merged**
