### PR TITLE
Re-add property that internal CodeLens implementation depends on

### LINKED ISSUE #13607: MissingMethodException: VisualStudioProjectTracker.get_Projects() not found
**Version Used**: master (4d6eb4f)

**Steps to Reproduce**:

1. Clone the Roslyn repo.
2. `Restore.cmd`, `msbuild /v:m /m Roslyn.sln`.
3. Open Roslyn.sln in VS 2015 U3, set Roslyn as the startup project, <kbd>F5</kbd>.
4. Create new .Net Framework C# Console application project.

**Expected Behavior**: No fatal exception.

**Actual Behavior**:

VS breaks in `FatalError.Report` with the following exception:

```
System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.AbstractProject> Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectTracker.get_Projects()'.
   at Microsoft.VisualStudio.Alm.Roslyn.Client.VisualStudioIntegrationService.TryGetProjectInformation(Guid projectGuid, IVisualStudioProjectInformation& projectInformation)
   at Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTagger.RefreshProjectInformation()
   at Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTagger.SetHierarchy(IVsHierarchy hierarchy)
   at Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTagger..ctor(ITextView textView, ICodeElementCache cache, IVsHierarchy hierarchy, String documentName, UInt32 documentCookie, RunningDocumentTable runningDocumentTable, IVisualStudioIntegrationService visualStudioIntegrationService)
   at Microsoft.VisualStudio.CodeSense.Editor.Roslyn.CodeElementTaggerProvider.CreateTagger(ITextView textView)
   at Microsoft.VisualStudio.CodeSense.Editor.TaggerProvider`1.CreateTagger[T](ITextView textView, ITextBuffer buffer)
   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)
```

Call stack at the break:

```
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C#
 	Roslyn.VisualStudio.Test.Setup.dll!Roslyn.VisualStudio.Test.Setup.TestExtensionErrorHandler.HandleError(object sender, System.Exception exception) Line 17	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.HandleException(object errorSource, System.Exception e)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Language.Intellisense.ICodeLensTag>.GatherTaggers(Microsoft.VisualStudio.Text.ITextBuffer textBuffer)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Language.Intellisense.ICodeLensTag>.Initialize.AnonymousMethod__13_0(Microsoft.VisualStudio.Text.ITextBuffer buffer)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Projection.Implementation.BufferGraph.GetTextBuffers(System.Predicate<Microsoft.VisualStudio.Text.ITextBuffer> match)	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Language.Intellisense.ICodeLensTag>.Initialize()	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<Microsoft.VisualStudio.Language.Intellisense.ICodeLensTag>.EnsureInitialized()	Unknown
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator<System.__Canon>..ctor.AnonymousMethod__12_0()	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs)	Unknown
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler)	Unknown
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs)	Unknown
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)	Unknown
```

### PR DESCRIPTION
**Pull request by Pilchie**
Fixes #13607.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide @mavasani and @panopticoncentral.

Do people think this is the approach to follow, or should we just live with a short term break in CodeLens to avoid the hassle.

@panopticoncentral is the internal code referencing this property likely to go away soon with your changes?

**Comment by Pilchie** [comment]
Also tagging @svick.

**Comment by CyrusNajmabadi** [comment]
How short is the break?

**Comment by panopticoncentral** [comment]
The problem is that I'm only changing the code in Dev15, not Dev14. So removing this property will permanently break Dev14 CodeLens with current Roslyn. I forget what the plan is vis-a-vis Dev14 and current Roslyn, so not sure how much this matters, but if we want to keep Dev14 working then we 'll need to keep the property until it's no longer supported...

**Comment by CyrusNajmabadi** [comment]
Seems trivial to keep this code around to keep Dev14 working.  Once Dev15 is totally public we can remove it.

**Comment by Pilchie** [comment]
Suggestions on names for the new property then.  I don't much like `ImmutableProjects`.

Also, I *will* fix up references to it to not use the obsolete one :)

**Comment by AdamSpeight2008** [comment]
Keep the old implementation, when Dev15 is ready add the `[Obselete()]` to the old implementation.

**Comment by mavasani** [comment]
Does CodeLens still need IVT access to MS.VS.LanguageServices in Dev15 after Paul's changes? If so, it might be good to add doc comments to those APIs to prevent such breaks in future.

**Comment by Pilchie** [comment]
retest vsi please

**Comment by panopticoncentral** [comment]
It shouldn't need that IVT access, no.

**Comment by mavasani** [comment]
Thanks @panopticoncentral - I have filed https://github.com/dotnet/roslyn/issues/13627 to ensure we remove the IVT once we stop supporting Roslyn.sln on Dev14.

**Comment by Pilchie** [comment]
retest windows_eta_open_prtest please

**Comment by Pilchie** [comment]
Going to merge in 1 hour if people don't have a better name for `ImmutableProjects`.

**Pull request merged**
