### PR TITLE
Add an assert message to help diagnose intermittent test failure

### PR DESCRIPTION
**Pull request by mavasani**
Intermittent test failure log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-roslyn-refs-heads-main-d5b992606e8b4c2098/Microsoft.CodeAnalysis.CSharp.Semantic.UnitTests.dll.2/console.d0298752.log?sv=2019-07-07&se=2021-04-27T19%3A07%3A22Z&sr=c&sp=rl&sig=vqAAmnezm0Aa3hecfxKwr6AdqYMrwTOwxXEjNLdTKco%3D

Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=1076538&view=logs&j=85444f1b-759e-5cca-5123-eed49cf93063&t=17125aaf-307c-5a57-0474-fb68c5b5fee2

### CODE REVIEW

**Comment by mavasani** [comment]
@sharwell Do you know if we have seen this assert fire in test failure again? Wondering if it is worth adding this or not..

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Comment by mavasani** [comment]
Thanks @dotnet/roslyn-compiler for an additional review - trivial assert-only change.

**Comment by jcouv** [comment]
@mavasani I'm marking this PR as draft for now to make some room in our review queue. Please ping when ready for another look.

**Comment by mavasani** [comment]
Closing this stale PR - the assert hasn't fired since.

**Pull request closed without merging**
