### PR TITLE
Make fields internal.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide and @DustinCampbell .   This is for Update3.  I'm making these fields internal as we intend to remove them in Master and we don't want anyone taking a dependency on them now.

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz this is to prevent either making a breaking change in Dev15, or keeping around API remnants that don't serve any purpose.

**Comment by DustinCampbell** [comment]
LGTM

**Comment by jasonmalinowski** [comment]
:+1: to the change, but why didn't this trigger a PublicAPI change as well?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski It needs that change.  Just pushing from home is super slow for some strange reason :)

**Pull request merged**
