### PR TITLE
Update 'use block body' to be better understand async methods.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/25202

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Ready for merging.  Thanks!

**Comment by CyrusNajmabadi** [comment]
test windows_build_correctness_prtest

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Ready for merging. Thanks!

**Comment by jinujoseph** [comment]
test windows_debug_vs-integration_prtest

**Comment by mavasani** [comment]
Integration test failure is unrelated.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by roryap** [comment]
If this is fixed, why does it still exist in VS as of 15.9.13?

**Comment by mavasani** [comment]
@roryap The issue was fixed in VS2019 (16.0).

**Comment by roryap** [comment]
Are fixes no longer being applied to VS 2017?

**Comment by mavasani** [comment]
> Are fixes no longer being applied to VS 2017?

Unless the underlying issue is a critical reliability/security/performance issue, it will likely not be backported to previous VS releases.

**Comment by roryap** [comment]
Okay, thank you.

**Pull request merged**
