### PR TITLE
Remove unused IPointerIndirectionReferenceOperation code

### PR DESCRIPTION
**Pull request by chborl**
BoundPointerIndirectionOperator is not handled by the C# factory. We have a method for it, but it is not called anywhere. This operator was punted because we currently don’t fully support C# unsafe code in IOperation.

Also added 2 tests for flow scenarios involving pointers, to verify this area is not broken.

### CODE REVIEW

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 1)

**Comment by AlekseyTs** [comment]
@333fred, @mavasani, @cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review

**Review by 333fred — APPROVED** [review]
LGTM (iteration 1)

**Review by mavasani — APPROVED** [review]

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Pull request merged**
