### PR TITLE
Fixed VB.NET implicitly typed array type

### PR DESCRIPTION
**Pull request by michalhosala**
Fix should address bug number #11933. Problem was with implicitly typed arrays such as `{ 1, 2 }` for which `SemanticModel.GetTypeInfo(arrExpression).Type` was returning just `null`. I believe correct solution is to remove the redundant handling for implicitly typed arrays within `SemanticModel`.

### CODE REVIEW

**Comment by crummel** [comment]
Build triggered. sha1 is merged.

**Comment by michalhosala** [comment]
The remaining failing unit test is `TestDontInsertUnnecessaryCast9` which I am unable to fix after hours of trying. I ended up in `Conversions.ClassifyArrayInitialization` method which, to my surprise, either returns either `ConversionKind.Widening` or `ConversionKind.Narrowing` but never `ConversionKind.Identity`. However, adjusting the logic in this method to also return Identity when I thought it is desired causes many tests to fail...

**Comment by gafter** [comment]
@michalhosala I think we'd need that problem solved to consider this PR. In the meantime we could use it as a reference when attempting our own fix.

**Comment by gafter** [comment]
@jcouv This PR is mainly kept around for reference for whoever works on #11933. Since we're not going to pull this, I'll close it, but we hope the author keeps the change around for us to refer to.

**Pull request closed without merging**
