### PR TITLE
Regression test for issue 7030

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @roslyn-compiler

**Comment by jaredpar** [comment]
Related to #7030 

Had to create a new PR because the old one can't be re-opened.

**Comment by jaredpar** [comment]
Can I get a quick sign off on this? Very small review.

**Comment by TyOverby** [comment]
LGTM.  

Do you have a bug opened on the CLR?

**Comment by jaredpar** [comment]
@TyOverby we have a thread going with them.  Once they open a bug we're going to link to it.

**Comment by agocke** [comment]
:+1:

**Comment by jcouv** [comment]
LGTM

**Pull request merged**
