### PR TITLE
Add Compilers filter for Roslyn

### PR DESCRIPTION
**Pull request by agocke**
Dev16 has a new feature that allows you to filter solutions down to a subset of the projects. I did this for the compiler layer and saved the result to this file.

### CODE REVIEW

**Comment by jaredpar** [comment]
What is this? Probably need to add a description to the PR.

**Comment by jaredpar** [comment]
@agocke ping

**Comment by jaredpar** [comment]
How do we use this file though? Basically if we merge what do I need to do in order to use this?

**Comment by agocke** [comment]
Just double click on it with Dev16 P1 installed. Just like a sln file.

**Comment by jaredpar** [comment]
This looks to just be Roslyn.sln slimmed down to Compilers.sln? Why would I use this over Compilers.sln? 

I don't really object to this change. I'm just trying to understand what benifit it gives.

**Comment by agocke** [comment]
Ah, two things really.

1. We can dogfood the filters functionality, providing benefit to the broader team.
2. In theory filters would allow us to more easily change the compilers and Roslyn solutions simultaneously, preventing them from going out of sync.

**Comment by jaredpar** [comment]
> We can dogfood the filters functionality, providing benefit to the broader team.

Always a winner. 

> In theory filters would allow us to more easily change the compilers and Roslyn solutions simultaneously, preventing them from going out of sync.

Don't think it does this. Unless I'm missing something this just changes the Visual Studio view, this isn't an item that we can target with msbuild. That would be necessary as we use Compilers.sln to filter the solution to projects that can be built with `dotnet build`.  Or can msbuild target this too?

**Comment by agocke** [comment]
On the dotnet build part -- no idea. Not even sure who to ask, tbh.

**Pull request merged**
