### PR TITLE
Use the right tree in SequencePointList.FindFirstRealSequencePoint

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/roslyn/issues/12923.

Also fix incorrect comment.

<s>I don't like that the test setup is so complicated, but I couldn't figure out an easy way to test this.</s>

### CODE REVIEW

**Comment by svick** [comment]
cc: @jcouv

**Comment by jcouv** [comment]
cc @tmat

**Comment by jcouv** [comment]
LGTM Thanks!

**Comment by jcouv** [comment]
CC @tmat @dotnet/roslyn-compiler for another review.

**Comment by tmat** [comment]
:-1:

**Pull request merged**
