### PR TITLE
Prefer list-pattern for length-only counterexamples

### PR DESCRIPTION
**Pull request by alrz**

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @alrz!

**Comment by alrz** [comment]
Would like to note that the the reason we didn't do this before was that (1) the fact that it will be suggested even if source contains only recursive patterns like `{ Length: 1 }` and (2) the length can be arbitrary large e.g. `{Length : < N }` generates a list pattern with N elements.  I don't expect these to be common but just wanted to check if there is any concerns here.

**Comment by cston** [comment]
> and (2) the length can be arbitrary large e.g. `{ Length : < N }` generates a list pattern with N elements.

That seems like a potential issue, thanks for pointing it out. Given that, we should consider keeping the previous behavior where the example used `{ Length: N }`.

We should include a test to catch this case in the future.

```csharp
[Fact]
public void NotExhaustive_LongList()
{
    string source = """
    var a = new[] { 1, 2, 3 };
    _ = a switch { { Length: < 1000 } => 0 };
    """;

    var comp = CreateCompilationWithIndexAndRangeAndSpan(source);
    comp.VerifyEmitDiagnostics(
        // (2,7): warning CS8509: The switch expression does not handle all possible values of its input type (it is not exhaustive). For example, the pattern '{ Length: 1000 }' is not covered.
        // _ = a switch { { Length: < 1000 } => 0 };
        Diagnostic(ErrorCode.WRN_SwitchExpressionNotExhaustive, "switch").WithArguments("{ Length: 1000 }").WithLocation(2, 7));
}
```

**Comment by cston** [comment]
Reverting the change to avoid generating arbitrarily long examples: https://github.com/dotnet/roslyn/pull/66576.

**Comment by alrz** [comment]
Opened a follow-up PR: #66585

**Pull request merged**
