### PR TITLE
Add IVT to build manager

### PR DESCRIPTION
**Pull request by drognanar**
Allows to access `WorkspaceVersion`

### CODE REVIEW

**Comment by drognanar** [comment]
@dotnet/roslyn-interactive

**Comment by Pilchie** [comment]
:-1: If there is really only one type you need, can we just figure out a way to make something public?

Tagging @mattwar.

**Comment by KevinH-MS** [comment]
@Pilchie I'm going to need to add this IVT in order to allow the BuildManager to access the Solution SnapshotService, so it's now or later... :smile:

**Comment by drognanar** [comment]
ping

**Comment by KevinH-MS** [comment]
LGTM

**Comment by Pilchie** [comment]
Again - why can we not actually do the right thing instead of adding more IVTs?

**Comment by tannergooding** [comment]
@Pilchie, I think its more a question of can we get the dependencies required made into public APIs within the timeframe required and without hindering other work in the meantime.

If we can make the required APIs public and do it within a reasonable timeframe (so we can ship on time and so we aren't blocked from doing developement/testing in the meantime), then I think that would be more desirable (and I believe @KevinH-MS and @drognanar would agree).

However, if that is not possible (or not immediately possible) than we need to add IVTs (and should log a bug tracking this API, for the longer term solution of making it public).

tagging @ManishJayaswal

**Comment by KevinH-MS** [comment]
@Pilchie @mattwar can you clarify/provide guidance on what the ***right*** behavior is here?

If we just want to make ```WorkspaceVersion``` public, that's certainly fine by me (and we can do that instead of merging this PR), but it doesn't feel like that design provides the "safety" of say, a ```VersionStamp```.

To clarify our scenario, there are several places in our code where want a cheap way to identify a particular Solution snapshot (without actually hanging on to the Solution snapshot).

Also, at a higher level, please note, we are writing an ```IIncrementalAnalyzer```.  That requires IVT today, not just for this one property, but because ***none*** of the interfaces related to that are public.  It just happens that our analyzer implementation is complex and split accross multiple dlls.  We already have IVT to one of our dlls, we just need it in the other now, because we want to move some code around.  The other option is for us to wrap those values in our own proxy type to pass from the component that has IVT to the one that doesn't, but that seems a bit convoluted and doesn't really provide much additional safety.

**Comment by Pilchie** [comment]
Mostly I just want to make sure that we *think* about whether we can make the API public.  Despite good intentions, and bugs to follow up on it, in 6 years, I've *never* seen us remove an IVT from the codebase.

If you need a version for a solution object, what's wrong with [`Solution.Version`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/Workspace/Solution/Solution.cs,68)?

**Comment by KevinH-MS** [comment]
> Despite good intentions, and bugs to follow up on it, in 6 years, I've never seen us remove an IVT from the codebase.

Sadly, I cannot refute that... 😞 

Re:  "Why not ```Solution.Version```?" I believe that's just the solution file itself.  What I meant by "snapshot" is the identity of the snapshot (i.e. snapshots are different if any Project or Document in the Solution is different)

**Comment by KevinH-MS** [comment]
@mattwar any thoughts on this?

**Comment by ManishJayaswal** [comment]
@mattwar Specifically we need to decide if we want to do the work now to make IIncrementalAnalyzer not need IVTs by designing the right public APIs. A tactical alternative for now is to just add the APIs we need right now and not do the complete work but that may limit us in future. So adding another IVT for now, if we decide to not do the public API design work now, seems like the right call.

@Pilchie has a fair point though that we never seem to remove IVTs once we add them. Only if we had more time...

**Comment by ManishJayaswal** [comment]
Talked to @Pilchie offline. We are ok with adding this IVT.
@KevinH-MS @drognanar please merge if everything else looks fine.

**Comment by KevinH-MS** [comment]
Current Roslyn builds (20160824.0X) have this change, as it was necessary for the Solution Snapshot (out-of-proc) work.  I am working on moving TestImpact over to those builds.  I'm just going to close this PR, but if there are suggestions for how to make this a public API, we can still do that.

**Pull request closed without merging**
