### PR TITLE
Use ExprContext.None for fake stack slots used to disable stack scheduler optimizations.

### LINKED ISSUE #7148: VBC crash in Double to Decimal conversion
(MattGe posting from BHarry blog.  Please verify in C# code as well.)

Hi Brian - I found a potential serious regression in VS2015 Update 1 when it comes to VB.  It took me 2 hours of commenting out huge pieces of our codebase until I narrowed it down to one line of code that trips up vbc.exe.  If I paste the rotation code directly into Sub Main, it works.  If I make rotation local to CalculateDimensions, it works.  But if I craft the code as follows, it causes a compiler error.  All you have to do is make a VB 'Console Application'.  Doesn't matter which version of .NET you target (4, 4.5, 4.5.1, 4.6, 4.6.1).  I suspect others will run into something similar.  It's like a needle in the haystack finding the culprit.  Not sure who I should notify about this.

``` vb
Module Module1
   Sub Main()
   End Sub
End Module

Public Class TestClass
   Private _rotation As Decimal
   Private Sub CalculateDimensions()
       _rotation *= 180 / Math.PI 'This line causes '"vbc.exe" exited with code -2146232797'
   End Sub
End Class
```

(MattGe:  Workaround is to change 180 to 180.0 in the example above, indicating a problem with integer conversion in the compiler.)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #7148.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by agocke** [comment]
Shouldn't this change go into/onto `stabilization`?

**Comment by AlekseyTs** [comment]
Not according to @jaredpar.

**Comment by agocke** [comment]
:+1: to the actual fix, and I prefer it to just doing a null check -- I think it's just as safe and more robust.

**Comment by agocke** [comment]
But we should wait on @jaredpar before merging this -- I think it should go into stabilization.

**Comment by jaredpar** [comment]
My main concern with master vs. stabilization was whether we were still producing NuGet packages for stabilization.  If we are and it makes the update / QFE easier to author then I agree it should go to stabilization.

**Comment by jaredpar** [comment]
Do we understand why this bug happened for only this type of conversion and not others?  I worry there is a lower consistency issue here in how we process the tree that is surfacing with this bug.  I want to make sure that we cover that as well in case it causes other issues.

I agree this fixes the bug.

**Comment by agocke** [comment]
I talked with Aleksey about this fix and can provide some more information on the problem. 

The central problem here is that the stack optimizer will sometimes notice when constructing a value type that rather than requesting a new type and assigning to an existing location, it can simply leave the value type on the stack as the receiver.

However, to do this the optimizer has to indicate to further visitors that nothing else should be pushed on to the stack. To signal this, it pushes a `null` value as a sentinel. The bug is that in VB the sentinel also had the `None` `ExprContext` -- except in one case. Here, it had the `Address` `ExprContext`. This caused a problem when a further pass saw the `ExprContext.Address` and took that as a green light to further inspect the stack item -- this caused an NRE.

By changing the `ExprContext` to `None`, all the passes should not view the value as inspectable.

**Comment by agocke** [comment]
@AlekseyTs Based on the conversation earlier, could you rebase this onto stabilization? That should make things easier.

**Comment by agocke** [comment]
Also, the key pieces here are a `ref` local for the struct that also gets referenced in the expression passed to the constructor.

A conversion is necessary, because otherwise calling the constructor shouldn't be necessary, and since a ref local needs to be created, it would have to be in a case where we generate locals. The cases where this happen should only be in a compound assignment to a decimal stored in a field or array. There may be other cases, but they would be very complicated.

However, when ref locals are added, this would be easy to hit.

**Comment by jaredpar** [comment]
@agocke yep.  @AlekseyTs and I chatted about this for a bit and I understand the root cause here now. 

> Also, the key pieces here are a ref local for the struct that also gets referenced in the expression passed to the constructor.

To clarify for any others, a `ref` parameter does not qualify in this context.  It must be an actual `ref` local.  Today this cannot be created by user code, instead it only created as temporaries by the compiler.  Compound assignment is one of the cases where this will occur.

**Comment by AlekseyTs** [comment]
Closing in favor of https://github.com/dotnet/roslyn/pull/7172.

**Pull request closed without merging**
