### PR TITLE
Ensure that IOperations nodes within an IsPatternExpression are part …

### LINKED ISSUE #19790: IOperation tree does not contain nodes with an IsPatternExpression
```
namespace ClassLibrary
{
    public class Class1
    {
        public void Method1(object x)
        {
            if (x is int y) { }
        }
    }
}
```

```
IOperation tree for "x is int y"

IOperation:  (OperationKind.None) (Syntax: 'x is int y')
```

### PR DESCRIPTION
**Pull request by mavasani**
…of the Operation tree

**Customer scenario**

Analysis of any code within an IsPatternExpression (for e.g. `if (x is int y)`) with IOperation analyzers will produce false or missing diagnostics, as the operation tree doesn't contain any operation nodes within the BoundIsPatternExpression. This can be a dogfood blocker for IOperation analyzers on real world code - we had multiple false reports due this on Analyzers repo and Roslyn repo as we widely use this new language feature, and corresponding rules had to be disabled in the repo.

**Bugs this fixes:**

Fixes #19790

**Workarounds, if any**

Disable or uninstall IOperation based analyzers

**Risk**

Low risk. We are following the common pattern for not yet implemented IOperation feature API for 15.3 - we don't yet provide rich IOperation API for the new language feature, but ensure that any descendant operation nodes are still included in the Operation tree.

**Performance impact**

None

**Is this a regression from a previous update?**

No, this never worked before.

**Root cause analysis:**

We missed this while adding unit tests, but caught this as soon as we tried to move the Analyzers and Roslyn repo forward to dogfood the new FXCop analyzers.

**How was the bug found?**

Dogfooding.

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/analyzer-ioperation @dotnet/roslyn-compiler for review.

**Comment by heejaechang** [comment]
👍

**Comment by heejaechang** [comment]
by the way, is it hard for all BoundNode which doesn't implement IOperation properly to all have Children?

**Comment by mavasani** [comment]
@heejaechang - we have bunch of bound nodes that don't implement IOperation by design as they are part of lowering. Then we have bunch of them that have no child IOperation nodes, so don't need to override Children. I did look at every node to identify cases where we do need to override Children, but missed on this node. I don't see any automated way to figure this out.

**Comment by mavasani** [comment]
@dotnet-bot retest this please

**Comment by mavasani** [comment]
@dotnet-bot retest this please

**Comment by mavasani** [comment]
Can someone from the compiler team take a look as well?

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler

**Comment by AlekseyTs** [comment]
I am surprised none of the existing tests required modifications.

**Comment by mavasani** [comment]
@AlekseyTs I didn't have Jenkins results to verify the failures, but just see now that some tests are indeed failing due to this. I will fix them and update the PR.

**Comment by mavasani** [comment]
@AlekseyTs fixed the unit tests

**Comment by mavasani** [comment]
@MattGertz for ask mode approval

**Comment by mavasani** [comment]
@dotnet-bot retest perf_correctness_prtest please

// Failed job: https://ci.dot.net/job/dotnet_roslyn/job/master/job/perf_correctness_prtest/6729/
// Failure reason: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: D:\j\workspace\perf_correctn---991e8cc1 at hudson.remoting.Channel@1de25c8e:win2016-f12380: hudson.remoting.ChannelClosedException: channel is already closed

**Comment by mavasani** [comment]
@dotnet-bot retest perf_correctness_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_eta_open_prtest please

**Comment by mavasani** [comment]
ETA test failed due a test runner issue: System.IO.FileNotFoundException: Could not find file 'D:\j\workspace\windows_eta_o---d880a2eb\Open\Binaries\Debug\Exes\EditorTestApp\Tao.log'.

https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/6820/console

Integration test failed due to another test infrastructure issue:
```
17:24:48 [xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern '**/xUnitResults/*.xml' relative to 'D:\j\workspace\windows_relea---8a39a417' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
17:24:48 
[xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/xUnitResults/*.xml'. Configuration error?.
```

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4706/console

**Comment by mavasani** [comment]
@dotnet-bot retest windows_eta_open_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by mavasani** [comment]
ETA failure is unrelated.

**Pull request merged**
