### PR TITLE
🧹 Move Regex embedded language to the Features layer

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Could you help me understand the goal here?  I did try to layer this in a proper fashion (from my perspective) when originally doing this.  i.e. things like classification was at the workspace layer, since that's where we have classification today.  But completion was at a higher layer.  etc. etc.  

Was that done incorrectly?

**Comment by CyrusNajmabadi** [comment]
I have no problem with this.  just trying to grok what hte preferred layering/extensbility model is desired to be for this sort of hting.  Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi Regex is an option feature not needed by the majority of workspaces work in command line tools. It's a large implementation and moving it up to features helps us keep the base case lightweight.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Regex is an optional feature not needed by the majority of workspaces work in command line tools. It's a large implementation and moving it up to features helps us keep the base case lightweight.

I see... but wouldn't the same hold for lots of other things (like normal classification?) 

Note: i'm not against this per-se.  I'm just a little surprised since we have a ton of stuff in Workspaces that likely aren't valuable for nearly all command line tools.

> The layering issues are resolved as part of #34801, 

When you say "layering issue", do you mean that there's actually a problem with how things were layered?  Or more that we'd prefer to move things up to Features, and that's teh work to do so.

I'm trying to distinguish betweent eh cases of:
1. this would have been bad no matter what.  versus
2. we would prefer a slightly different split due to the desire to keep Workspaces lean for command-line-app purposes.

**Comment by sharwell** [comment]
> When you say "layering issue", do you mean that there's actually a problem with how things were layered?

Yes, the part addressed in the first pull request was problematic.

> I see... but wouldn't the same hold for lots of other things (like normal classification?)

Maybe. This one seemed like a good win mostly because of the size of implementation. **Microsoft.CodeAnalysis.Workspaces** drops from 2815KiB to 2729KiB.

**Comment by sharwell** [comment]
@dotnet/roslyn-ide for reviews

**Comment by CyrusNajmabadi** [comment]
Note: i'm currently making a change to regex over in: https://github.com/dotnet/roslyn/pull/41294.  Can we try to avoid merge conflict here?  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
OVerall this looks fine to me.  As long as loc's tools will just auto patch things up on their end.

**Comment by sharwell** [comment]
> i'm currently making a change to regex over in: #41294. Can we try to avoid merge conflict here?

Git should not have trouble with this merge.

**Pull request merged**
