### PR TITLE
Change to the VS release queue for integration tests

### PR DESCRIPTION
**Pull request by JoeRobich**
Contains same commit as https://github.com/dotnet/roslyn/pull/41473 but targeted at master branch

### CODE REVIEW

**Comment by jaredpar** [comment]
This does a lot more than change the queues, it also changes a lot of code under `eng/common` which is effectively changing the arcade version we use. Is that intentional here?

**Comment by sharwell** [comment]
I think this is not a necessary change anymore. The original queue has been reverted to an image we expect to work.

**Comment by JoeRobich** [comment]
> Is that intentional here?

Those changes are in release/dev16.5 not sure why the versions went from V5 to V1.

**Comment by JoeRobich** [comment]
See the dev16.5 to master merge https://github.com/dotnet/roslyn/pull/41435

**Comment by JoeRobich** [comment]
Merging since this is basically the dev16.5-master master

**Pull request merged**
