### PR TITLE
Make *Core projects IL-only and use win7 runtime identifier globally

### PR DESCRIPTION
**Pull request by agocke**
We're in the weird situation where we want the runtime implementations for x64 on all platforms, but NuGet by default uses the PlatformTarget property to decide which runtime implementations to copy and PlatformTarget of x64 forces PE32+ emit on the compiler. To resolve this we set MSBuild to emit AnyCPU but override the NuGet defaults to our own runtime identifier.

@tmat @jaredpar @TyOverby Please review

### CODE REVIEW

**Comment by agocke** [comment]
test eta please

**Comment by agocke** [comment]
ping

**Comment by agocke** [comment]
+ @jasonmalinowski

**Comment by agocke** [comment]
ping, please review

**Comment by agocke** [comment]
@dotnet/roslyn-compiler review please.

**Comment by jaredpar** [comment]
:+1: 

Do we have a bug tracking the NuGet behavior so we don't have to do this work around?

**Comment by agocke** [comment]
@jaredpar Actually, I don't necessarily think this is a bug. The fact that we want our runtime target to be different when we compile as opposed to when we restore packages is just weird.

The only bug is that RuntimeIndentifier is misspelled and should probably be called NuGetRuntimeIdentifier. I'll file a bug for that.

**Comment by jasonmalinowski** [comment]
@agocke: we've already got a bug on the typo. Sorry about that.
@jaredpar: this might be something we need to support in a more general case, but I otherwise have no problem with this.

**Pull request merged**
