### PR TITLE
using static and alias can access private types

### LINKED ISSUE #42567: using static does not work with private type
**Version Used**: master as of 10th march

**Steps to Reproduce**:

```csharp
using static Outer.Inner;

public class Outer
{
    
    public void M() {
        var x = Prop;
    }
    private static class Inner
    {
        public static int Prop => 42;
    }
}
```

**Expected Behavior**: No Errors

**Actual Behavior**: 
error CS0122: 'Outer.Inner' is inaccessible due to its protection level
error CS0103: The name 'Prop' does not exist in the current context

I think this is a bug because the [Spec](https://github.com/dotnet/csharplang/blob/master/spec/namespaces.md#using-static-directives) makes no mention of such restrictions.

### PR DESCRIPTION
**Pull request by YairHalberstadt**
Fixes #42567, #42568

### CODE REVIEW

**Comment by jcouv** [comment]
The PR have build breaks. I suspect that those result from doing `build.cmd -bootstrap` (which compiles roslyn with the compiler including your change) and this reveals the breaking change in the proposed fix.

**Comment by YairHalberstadt** [comment]
This would allow you to use using static on internal types.
I presume that's no desirable?

**Comment by jcouv** [comment]
The revised approach still doesn't seem desirable (the special-casing of static vs. non-static would still not correspond to any language rule). Also, I'm concerned that we could hit a similar compat issue with static.
So I'd recommend keeping the current behavior :-(

**Comment by YairHalberstadt** [comment]
I do not think this can lead to a breaking change, since the following cases are already errors:

*case 1*
```csharp
comp1:
public class A
{
    public class B {}
}

comp2:
class A
{
    class B {}
}

comp3:
using static A; //error: the type A exists in both comp1 and comp2
using static A.Inner; //error: the type A exists in both comp1 and comp2
```
*case 2*
```csharp
using static System.Console; // error CS0122: 'System.Console' is inaccessible due to its protection level

public class System
{
     private class Console ()
}

...

WriteLine("Hello World");
```

**Comment by YairHalberstadt** [comment]
@jcouv 

Do you think the spec should be amended to mention accessibility?

**Comment by YairHalberstadt** [comment]
> the special-casing of static vs. non-static would still not correspond to any language rule

A better solution would be to have non-static using completely ignore any types, so this would become legal:

```csharp
using System;

public class System
{
}
```

However that would be a true spec change I think, and is probably not worth it.

**Comment by jcouv** [comment]
> Do you think the spec should be amended to mention accessibility?

Yes, I'd lean that way. @gafter what do you think?

**Comment by YairHalberstadt** [comment]
@gafter 
For background, changing imports to ignore accessibility leads to the following breaking change:

```csharp
comp1:
internal class A {}

comp2 references comp1:
using A; // error CS0435: The namespace A conflicts with imported type A.
using System;
namespace A
{
    public class PrintUtils
    {
        public static void Print(string str) => Console.Write(str);
    }
}
```

I fixed that by making `using static` ignore accessibility but not `using` which is understandably an inelegant solution

**Comment by YairHalberstadt** [comment]
We still have a problem with 436, namely when two types have the same name, one is accessible, and an alias references it.

I think that this is best closed and the spec amended.

**Comment by YairHalberstadt** [comment]
Opened https://github.com/dotnet/csharplang/pull/3299

**Comment by AlekseyTs** [comment]
Don't regular name lookup rules outlined in section **3.8 Namespace and type names** involve type accessibility? I am not sure why sections about using directives are expected to reiterate them.

**Pull request closed without merging**
