### PR TITLE
Fixes 7 failing pattern matching tests due to an incorrect assumption about standard cultural settings

### PR DESCRIPTION
**Pull request by axel-habermaier**
This fixes an issue related to #10362:

7 of the C# pattern matching tests in master fail due to the use of ``Roslyn.Test.Utilities.EnsureEnglishCulture``: The tests print out some numbers, expecting them to be formatted using English formatting rules. To ensure this, the ``EnsureEnglishCulture`` class is used.
This class basically checks if the current culture's names starts with ``en`` (which it does in my case) and then does nothing -- otherwise, it sets the invariant culture. However, as shown in #10362, I use non-standard cultural settings for the ``en`` culture, in particular changing the decimal symbol. Thus, the ``GeneralizedSwitchStatement`` test, for instance, fails as it prints out ``double 1,2`` instead of ``double 1.2``.

This issue can be fixed by always setting the invariant culture, in which case all 7 tests succeed. In that case, however, the entire class should probably be renamed to ``EnsureInvariantCulture``. As the class is only used by the pattern matching tests, this change seems to be safe. 

This pull requests thus makes the necessary changes to fix the tests.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_release_unit32_prtest please and test windows_release_unit64_prtest please. (These are new jobs that are now also required.)

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler 

LGTM

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
