### PR TITLE
Ensure PeNamedTypeSymbol.GetFieldsToEmit returns backing fields for events.

### PR DESCRIPTION
**Pull request by AlekseyTs**
This fixes some Edit and Continue failures (DevDiv 1175704).

@VSadov, @tmat, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please.

**Comment by AlekseyTs** [comment]
- Bug number - DevDiv 1175704
- Customer scenario - Edit and Continue in a method, which is using field-like event, causes an unexpected TypeLoadException once execution is resumed.  
- Fix description - Ensure PENamedTypeSymbol.GetFieldsToEmit returns backing fields for events. The fields are not part of the public surface of the PENamedTypeSymbol, however GetFieldsToEmit is an internal API, which is supposed to reflect metadata view of the type and, therefore, should return symbols for the backing fields. The fact that the symbols we not returned was causing incorrect behavior of EnC.
- Testing done - unit-tests.

@jaredpar, @VSadov FYI

**Comment by VSadov** [comment]
Does VB have this bug too?

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
No VB doesn't have this bug. I have a test ready.

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please.

**Comment by MattGertz** [comment]
Approved 5/29 by ML Shiproom, pending @pharring check on perf in EnC.

**Comment by pharring** [comment]
:+1:

**Pull request merged**
