### PR TITLE
Add filters for keywords and snippets.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/14528

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Taggging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide  

Looks like this:

image

**Comment by CyrusNajmabadi** [comment]
test this please

**Comment by Pilchie** [comment]
I'm a bit confused by your screenshot.  It looks like the keyword filter is checked, but you're still seeing snippets and locals.  Also, what is that empty entry at the top of the list?

**Comment by CyrusNajmabadi** [comment]
> I'm a bit confused by your screenshot. It looks like the keyword filter is checked

It wasn't checked.  I was just hovering.  Good call on the empty entry.  I will go find out what's happening htere!

**Pull request merged**
