### PR TITLE
Update comment

### PR DESCRIPTION
**Pull request by Youssef1313**
Addresses https://github.com/dotnet/roslyn/pull/53614#discussion_r637948788

cc @jcouv @333fred @AlekseyTs

### CODE REVIEW

**Comment by 333fred** [comment]
@AlekseyTs the compat council said not rename things _after_ Data, but said nothing about reserving the Kind number itself.

**Comment by AlekseyTs** [comment]
> the compat council said not rename things after Data, but said nothing about reserving the Kind number itself.

My interpretation of the quote: "remove the kind, but don’t change the numeric value of kinds declared after it." Is that we shouldn't reuse the value. The fact that the kind happened to be the last one doesn't change anything in my opinion. Any new kind added later shouldn't reuse the value.

**Comment by 333fred** [comment]
Confirmed with compat council, and the conclusion is that we should not reuse this kind in the future.

**Review by 333fred — APPROVED** [review]

**Review by jcouv — APPROVED** [review]

**Comment by 333fred** [comment]
@AlekseyTs can you give this a second review?

**Comment by 333fred** [comment]
Or julien and I commented at the same time, going to call this good.

**Pull request merged**
