### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160217-160029
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160217-160029 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by genlu** [comment]
retest vsi please

**Comment by davkean** [comment]
retest vsi please

**Comment by genlu** [comment]
@davkean vsi will fail again I believe. This is blocked on @heejaechang's fix.

**Comment by davkean** [comment]
Yep, understood, just want current results.

**Comment by genlu** [comment]
retest vsi please

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/329/
// Retest reason: Caused by a known flay test #8725

**Comment by drognanar** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/332/
// Retest reason:

**Pull request merged**
