### PR TITLE
DryDock Effort: Removing the skipped Unit Tests from OrganizeUsingsTests

### PR DESCRIPTION
**Pull request by jinujoseph**
Associated work item has been marked as Won't Fix.
http://vstfdevdiv:8080/DevDiv2/DevDiv/_workItems?id=752024&_a=edit

### CODE REVIEW

**Comment by jinujoseph** [comment]
@dotnet/roslyn-ide

**Comment by brettfo** [comment]
Nit: there appear to be extra newlines that aren't needed, but otherwise :shipit:.  I'm all for deleting stuff that was never useful anyways.

**Comment by jasonmalinowski** [comment]
What _does_ the product do if you're missing semicolons?

Please elide the commits that are adding and removing the .rc file.

**Comment by jinujoseph** [comment]
@jasonmalinowski, It adds extra line after those using statements.

**Comment by jasonmalinowski** [comment]
OK, just wanted to make sure it wasn't some horrible behavior that we still needed a test (of some kind) for. :+1:

**Pull request merged**
