### PR TITLE
Add OneLocBuild to the dev16.10-vs-deps branch

### PR DESCRIPTION
**Pull request by jonfortescue**
Same as https://github.com/dotnet/roslyn/pull/52962 but this one is for the release/dev16.10-vs-deps branch that needs loc for release.

### CODE REVIEW

**Comment by jaredpar** [comment]
@tmat the ENC tests failed on this PR in a catastrophic way. Essentially a large swath of tests across all our different architectures. This is an infra only PR so it doesn't seem to be a code change. A bit concerning to see that level of failure because the explanations I can think of suggest a decently severe product issue. 

https://dev.azure.com/dnceng/public/_build/results?buildId=1110117&view=results

Are you aware of this?

**Comment by jaredpar** [comment]
@dotnet/roslyn-infrastructure PTAL

**Comment by tmat** [comment]
@davidwengier PTAL at the EnC failures.

**Review by JoeRobich — APPROVED** [review]

**Comment by dibarbet** [comment]
@jonfortescue would you be able to merge in the latest from release/dev16.10-vs-deps?  That should fix the failures

**Comment by jonfortescue** [comment]
@dibarbet done! crossing my fingers

**Comment by dibarbet** [comment]
roslyn-integration-lsp-CI is optional and known failure - this PR can be merged without it passing

**Pull request merged**
