### PR TITLE
Simplify how we deal with langauges in remote scenarios.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
I've observed some very wonky stuff in remote scenarios where the options we have and this remoteSupportedLangs field can be in disagreement.  This is because these values are computed independently but have codepaths where they affect each other.  Trying to simplify to remove the need for these disparate sets of values to stay in sync.

**Comment by sharwell** [comment]
Frightening number of 🐉 in this. Please don't merge without a ✔ from @mavasani. 😄

**Comment by CyrusNajmabadi** [comment]
Closing out.  this was used for learning how this part of the system work.

**Comment by CyrusNajmabadi** [comment]
Don't worry. This was to help me understand some surrounding system behavior.

**Pull request closed without merging**
