### PR TITLE
Test GetAttribute for CodeFunction

### PR DESCRIPTION
**Pull request by basoundr**
Add testcase for internal issue 876614 to prevent regression in the
future

### CODE REVIEW

**Comment by basoundr** [comment]
Reviewers: @Pilchie @DustinCampbell @jasonmalinowski

**Comment by Pilchie** [comment]
I don't think this is what the bug is talking about.  I think the issue is if you have something like:

```C#
class C1
{
    [Obsolete]
    public void F() {}
}

class C2 : C1 {}
```
and you first get the type for C2, then get it's base type, the get it's members, and *then* ask for the attributes it doesn't return anything.  Oh, and C1 could be in metadata.

**Comment by basoundr** [comment]
@Pilchie You are right, If the repro steps are followed then we hit the issue. The issue seems that Attribute property is overriden to produce the correct value. 

This issue still repros

**Comment by basoundr** [comment]
Closing this PR since the issue is still present

**Pull request closed without merging**
