### PR TITLE
WIP: Dont warn about the deprecated lincseUrl property

### PR DESCRIPTION
**Pull request by ryzngard**
Command line builds can fail with a warning like below. This removes that warning for all projects. Based on the fix provided in [project-system](https://github.com/dotnet/project-system/pull/4320)

To repro, run `build/scripts/cibuild.cmd -configuration Debug -testDesktop -Test32 `

```
C:\Program Files\dotnet\sdk\2.1.500\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): error NU51
25: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [C:\Users\ryzng\Source\R
epos\roslyn\src\NuGet\Microsoft.Net.Compilers\Microsoft.Net.Compilers.Package.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\2.1.500\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(202,5): error NU51
25: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead. [C:\Users\ryzng\Source\R
epos\roslyn\src\NuGet\Microsoft.Net.Compilers\Microsoft.Net.Compilers.Package.csproj]
    0 Warning(s)
    1 Error(s)
```

### CODE REVIEW

**Comment by tmat** [comment]
Maybe we should rather fix the actual issue than hide it?

**Comment by ryzngard** [comment]
I think for that we'd have to change to packaging our nuget with a copy of the file? At least from my understanding reading https://docs.microsoft.com/en-us/nuget/reference/nuspec 

Alternatively, if we use a standard license from https://spdx.org/licenses/ we can just reference directly; i.e, MIT. If that's the case, I can make that change

**Comment by ryzngard** [comment]
At least one package uses (NetFX20 I think) https://www.microsoft.com/web/webpi/eula/dotnetcompilerplatform_redistributables_preview.htm 

There's also a reference to https://visualstudio.microsoft.com/license-terms/mt171586/ in base.nuspec, which probably gets applied to most packages.

**Comment by tmat** [comment]
I believe the right fix is to set `PackageLicenseFile` property to a license file in the repo. If we don't have one yet, we need to add it.

**Comment by ryzngard** [comment]
@tmat  I don't see `PackageLicenseFile` in the csproj additions or nuget docs, do you mean `PackageLicenseUrl`? I think that will likely be deprecated as well given the discussion at https://github.com/NuGet/Home/issues/4628 which lead to the deprecation of the property to begin with.

**Comment by tmat** [comment]
> I don't see PackageLicenseFile in the csproj additions or nuget docs, do you mean PackageLicenseUrl?

I mean `PackageLicenseFile` needs to be set in Settings.props instead of [PackageLicenseUrl](https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L11)

**Pull request closed without merging**
