### PR TITLE
LOC CHECKIN | dotnet/roslyn dev15.8.x-vs-deps | 20180712

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by tmeschter** [comment]
test loc

**Comment by tmeschter** [comment]
test windows_release_vs-integration_prtest

**Comment by dpoeschl** [comment]
FYI @tmeschter @v-zbsail for the merge conflicts.

**Comment by dpoeschl** [comment]
@jinujoseph Can we take this for approval now? 
@jinujoseph @tmeschter @v-zbsail @Shyam-Gupta Shouldn't these be targeting `dev15.8.x` instead of the `-vs-deps` version, at least in theory? Perhaps we've just always been putting them in `-vs-deps` and now it'd be annoying to switch back to `dev15.8.x`, but it seems weird we let `dev15.8.x` resources slip out of date until we _finally_ do the `dev15.8.x-vs-deps`-->`dev15.8.x` merge someday. Also weird because devs are checking new strings into `dev15.8.x` so these are merge conflicts waiting to happen.

**Comment by tmeschter** [comment]
@dpoeschl Our efforts are focused on dev15.8.x-vs-deps because that is the actual release branch. Translating dev15.8.x as well would involve a fair bit of busy work for the Loc team without much benefit since the set of localizable resources in each of these branches will always be identical or nearly identical.

Merge conflicts should be rare as no one is supposed to be committing loc changes to either branch, anyway.

**Comment by tmeschter** [comment]
I've fixed the merge conflicts.

**Pull request merged**
