### PR TITLE
Fix tests to be only conditionally skipped

### PR DESCRIPTION
**Pull request by jaredpar**
When conditionally skipping tests for CoreClr I mistakenly
unconditionally skipped them in my attempt to document the reason for
the skip. The use of the Skip property causes the test to be
unconditionally skipped, not documenting the reason.

In addition to fixing this I prevented this from happening in the
future. It's very rare for a `[ConditionalFact]` to actually want to use
Skip as it means unconditionally skip. This is generally only for short
term bug work arounds. Hence I changed `ConditionalFactAttribute` as
follows:

- Added a new Skip property that is obsolete and has no setter.
Completely prevents the code `[ConditionalFact(..., Skip = )`
- Added a Reason property documentation in the case the test is skipped.
- Added an AlwaysSkip property in the case you always want to skip.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler for review

**Comment by agocke** [comment]
Those test failures look real, but I'm not sure what's going on. The syntax test one doesn't even look modified.

**Comment by sharwell** [comment]
> A possible explanation: xunit is using my new Skip property vs. the on on FactAttribute. That would be a bit disturbing but explains the behavior.

xunit doesn't use the property at all. It uses the metadata in [CustomAttributeData.NamedArguments](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.customattributedata.namedarguments?view=netframework-4.7.1) (and it uses `MemberName` not `MemberInfo`).

**Comment by jaredpar** [comment]
> xunit doesn't use the property at all.

It definitely does. Look at the code in `ConditionalFactAttribute` before my changes (go back a couple moths). The Skip property is the only value modified in those cases and it's done so in the ctor, not in a named argument. This has been the basis of our conditional test execution since I joined the team.

**Comment by sharwell** [comment]
:memo: @jaredpar and I looked at this a bit more, and it turns out we were both correct:

* If `Skip` is set in the attribute usage, it's read without instantiating the attribute type and applied to the test during test discovery. This is a fast path for improved design-time UI and avoiding unnecessary use of the test execution path. Unconditional skips typically rely on this path.
* If `Skip` is set in the argument, it's ignored during test discovery but applied later during the test execution phase. `ConditionalFactAttribute` relies on this path.

**Pull request merged**
