### PR TITLE
Disable the IDE oop features by default.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
We're going to do some quality/perf testing (and possibly full on dogfooding) first to get
more confidence about this before having them be on by default.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @heejaechang @srivatsn @Pilchie

**Comment by CyrusNajmabadi** [comment]
test windows_release_unit32_prtest

**Comment by heejaechang** [comment]
if you put your options here 

http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Options/InternalFeatureOnOffOptions.cs,7

or like this

http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Remote/RemoteHostOptions.cs,8

this will show up in options->Roslyn->Features so that user can easily turn on and off for dogfooding.

**Comment by CyrusNajmabadi** [comment]
Some of these options exist at the Workspace layer.

**Comment by heejaechang** [comment]
👍

**Comment by heejaechang** [comment]
featurename and registry location are all just string. you can duplicate those string there.

**Comment by CyrusNajmabadi** [comment]
> you can duplicate those string there.

Ewww. :)  But i see your point.  Def something i can try to do in a followup PR.

**Comment by heejaechang** [comment]
@CyrusNajmabadi if you don't mind not showing those options something visible to users for easier dogfooding, then don't need to. I was just saying if you do, you can tell people to go to the option page and enable those for dogfooding.

**Pull request merged**
