### PR TITLE
Implement #! comment syntax...

### LINKED ISSUE #4498: Support C# (.csx) shell scripts on *nix OSes
The following should work on *nix without additional pre-processing on the part of the execution host (ala https://github.com/mbaker-dev/scriptcs/commit/4fab22f49839df7f94fbb0f44916e5241c589c8f):
```
#!/usr/bin/env scriptcs
System.Console.WriteLine("Hello World!");
```

### PR DESCRIPTION
**Pull request by KevinH-MS**
This just amounts to structured trivia that (optionally) can be further processed by the script host...

Fixes #4498

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @jaredpar @agocke I was doing this for scripting, but I understand you may have thoughts/plans as well.

**Comment by KevinH-MS** [comment]
At the suggestion of a couple folks, I'll add a new ```SyntaxKind.ShebangCommentTrivia``` for this (so it can be distinguished from other single line comment trivia).

**Comment by KevinH-MS** [comment]
I've now introduced ```SyntaxKind.ShebangCommentTrivia```.

@jaredpar @agocke @tmat please review...

**Comment by agocke** [comment]
:+1:

**Pull request merged**
