### PR TITLE
Create a specific error ID for using a throw expression in an unsupported language version

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv

**Comment by CyrusNajmabadi** [comment]
Closing out.  Not sure i like this approach.

**Comment by jcouv** [comment]
LGTM :-P 
What's wrong with the approach?

**Comment by CyrusNajmabadi** [comment]
@jcouv I think i have a better way that doesn't involve specific error IDs.  trying it out now.

**Pull request closed without merging**
