### PR TITLE
Tuples: removing more PROTOTYPE markers

### PR DESCRIPTION
**Pull request by jcouv**
Removing the last PROTOTYPE stragglers. 

Opened #10918
Updated #10803
Vlad will open an issue for the IDE team on completion.

### CODE REVIEW

**Comment by jcouv** [comment]
@VSadov @dotnet/roslyn-compiler for review.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jcouv** [comment]
@VSadov Can you give the second approval?

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
