### PR TITLE
Improve interval tree construction performance.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
I recommend looking at this PR one commit at a time.

---

Currently we adding items to a tree one at a time.  This means that we end up incurring a ton of balancing operations, and we end up having to introspect nodes over and over again.

Now, we sort the nodes up front, and then build the interval tree in a bottom up fashion, never needing to balance anything.

### CODE REVIEW

**Comment by Pilchie** [comment]
@heejaechang are you interested in taking a look at this?

**Comment by jasonwilliams200OK** [comment]
@CyrusNajmabadi, a note on commits in the PR which are failing CI build: sometimes the maintainer ask the contributors to squash the commits. Mostly it is to keep the git history clean and consistent, but generally it is not requirement to keep the commit count 1 per PR, as a PR can have multiple commits.

However, it turned out there is a grave side effect if the PR is merged with some commits failing the CI (regardless of final green). Which pops up in situations when you want to go back in time and figure out which commit caused some particular behavior or bug using `git bisect` command.

For instance, in this PR, commits ab150e3 and 6c83339 have ditto commit log: "Remove unused constructors." and the latter one is failing the CI build. Now that there are more commits on top of them, which remedied/hide the problem. It would probably be a good idea to squash down the commits and fix the issue before the merge, so when this batch of commits will finally land in the source control, individually none are failing the build. This is to keep the reverse-engineering path unbroken.

So IMHO, the general best practice to follow should be; "squash as much as possible && make sure none of the commits fail the CI build".

**Comment by davkean** [comment]
@CyrusNajmabadi This has been around for a while, are there plans to revive this or can we close it out?

**Comment by CyrusNajmabadi** [comment]
@davkean I'd like to get it in.  I haven't had a lot of time to focus on it though..

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit64 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/eta please

**Comment by CyrusNajmabadi** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by davkean** [comment]
@CyrusNajmabadi This PR is now the oldest PR, has now been around for 6 months, with zero progress in 3. 

In ~1 week I'll assume it's been abandoned and will close out. You'll still have the original branch if you want to reopen it at a later date.

**Pull request closed without merging**
