### PR TITLE
67328 - Update the casing of remove unecessary usings in lightbulb menu

### PR DESCRIPTION
**Pull request by sshiells-scottlogic**
Change to address [Issue 67328](https://github.com/dotnet/roslyn/issues/67328) - Inconsistent capitalisation of "Remove Unnecessary Usings" in lightbulb menu.

### CODE REVIEW

**Comment by sshiells-scottlogic** [comment]
@dotnet-policy-service agree company="Scott Logic"

**Review by drewnoakes — APPROVED** [review]

**Comment by mavasani** [comment]
@sshiells-scottlogic Let me know if you prefer to create a separate PR for the VB change or push another commit to this PR. Thanks!

**Comment by sshiells-scottlogic** [comment]
@mavasani I can push another commit to this PR. I will try to get to that today.

**Comment by sshiells-scottlogic** [comment]
@mavasani I have pushed up a commit with the changes. I couldn't see any tests on the VB side to update like there were on the C# side?

**Review by mavasani — APPROVED** [review]

**Pull request merged**
