### PR TITLE
Merge dev15.1.x to master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15.1.x into master.

``` bash
git fetch --all
git checkout merges/dev15.1.x-to-master-20170309-080003
git reset --hard upstream/master
git merge upstream/dev15.1.x
# Fix merge conflicts
git commit
git push merges/dev15.1.x-to-master-20170309-080003 --force
```

Once all conflicts are resolved and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@TyOverby Is going to investigate the Ubuntu16 issue.

**Comment by TyOverby** [comment]
@CyrusNajmabadi Fixed somehow

**Comment by CyrusNajmabadi** [comment]
windows_debug_vs-integration_prtest  is failing with: error MSB4018: The "EnableExtension" task failed unexpectedly.

The enable-extension issue is being tracked with https://github.com/dotnet/roslyn/issues/17456

**Comment by CyrusNajmabadi** [comment]
@dpoeschl release_vs is failing with "Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicGenerateTypeDialog.CheckFoldersPopulateComboBox [FAIL]
Indication 1 

"

**Comment by CyrusNajmabadi** [comment]
Merging since the only failures are integration tests.

**Pull request merged**
