### PR TITLE
21898 - Fixed typo in help message

### PR DESCRIPTION
**Pull request by EddTheGeek**
- Fixed variable typo in all places

### CODE REVIEW

**Comment by Pilchie** [comment]
Thanks for the contribution!

**Comment by Pilchie** [comment]
@dotnet-bot retest this please

**Comment by Pilchie** [comment]
@dotnet/roslyn-infrastructure: Failures in PDC unit tests, are these known?
```
Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests.ForEachStatement_Array
Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests.ForStatement1
Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests.SwitchStatement1
Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests.ClosuresInCtor
Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBLocalFunctionTests.UsingStatement1
Microsoft.CodeAnalysis.CSharp.UnitTests.PDB.PDBTests.SwitchWithPatternAndLocalFunctions
```

**Comment by AlekseyTs** [comment]
The failures a known, we have a PR (https://github.com/dotnet/roslyn/pull/21969) to fix them, but issues with infrastructure prevented us from merging it in.

**Comment by Pilchie** [comment]
Thanks - I'll wait and re-test after that PR is merged.

**Comment by Pilchie** [comment]
@dotnet-bot retest this please

**Comment by Pilchie** [comment]
Filed https://github.com/dotnet/roslyn/issues/21999 for the integration test failure

**Comment by Pilchie** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Pilchie** [comment]
Thanks @EddTheGeek!

**Pull request merged**
