### PR TITLE
Clarify assert assumptions in BetterFunctionMember<TMember> with a comment.

### LINKED ISSUE #2641: Clarify assert assumptions in BetterFunctionMember<TMember> with a comment.
See discussion in https://github.com/dotnet/roslyn/pull/2573

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2641.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by VSadov** [comment]
LGTM

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Pull request merged**
