### PR TITLE
add entry point related errors as build only errors

### PR DESCRIPTION
**Pull request by heejaechang**
fix https://github.com/dotnet/roslyn/issues/12858

### CODE REVIEW

**Comment by heejaechang** [comment]
@Pilchie can you take a look?

**Comment by Pilchie** [comment]
:+1:  Also tagging @gafter to confirm this is the set

**Comment by heejaechang** [comment]
retest   windows_eta_open_prtest  please

**Comment by heejaechang** [comment]
@gafter ping?

**Comment by heejaechang** [comment]
@gafter can I check this in?

**Comment by heejaechang** [comment]
@Pilchie @MattGal do I need approval for ask mode?

**Comment by gafter** [comment]
Looks good to me; all of these are build-only errors. I can't promise this list is exhaustive, but it is better than it was before. Here are some others:

ErrorCode.ERR_BadDelegateConstructor
ErrorCode.ERR_InsufficientStack
ErrorCode.ERR_ModuleEmitFailure
ErrorCode.ERR_TooManyLocals
ErrorCode.ERR_BindToBogus
ErrorCode.ERR_ExportedTypeConflictsWithDeclaration
ErrorCode.ERR_ForwardedTypeConflictsWithDeclaration
ErrorCode.ERR_ExportedTypesConflict
ErrorCode.ERR_ForwardedTypeConflictsWithExportedType
ErrorCode.ERR_ByRefTypeAndAwait
ErrorCode.ERR_RefReturningCallAndAwait
ErrorCode.ERR_SpecialByRefInLambda
ErrorCode.ERR_DynamicRequiredTypesMissing


---
In reply to: [245457262](https://github.com/dotnet/roslyn/pull/13621#issuecomment-245457262) [](ancestors = 245457262,245452879)

**Comment by heejaechang** [comment]
So these are ones GetDiagnostics on compilation can’t produce?


-          heejae

**Comment by gafter** [comment]
Yes, these are ones `GetDiagnostics` does not produce.

**Comment by MattGal** [comment]
@heejaechang  you don't need my approval AFAIK!

**Comment by Pilchie** [comment]
That was meant to be @mattge.  If we want this for preview-5, then it needs approval, and needs to be changed to target the `dev15-preview-5` branch (which can now be done without creating a new PR).

**Comment by gafter** [comment]
In case it wasn't clear, LGTM

**Comment by heejaechang** [comment]
@MattGertz can I get approval for preview 5?

**Comment by gafter** [comment]
:shipit:

**Pull request merged**
