### PR TITLE
Delete the Microsoft.CodeAnalysis.Analyzers package

### PR DESCRIPTION
**Pull request by tmeschter**
Future work on this package has moved to the dotnet/roslyn-analyzers
repo.

### CODE REVIEW

**Comment by tmeschter** [comment]
@srivatsn @mavasani Can you review, please?

**Comment by jaredpar** [comment]
@tmeschter so this delete is basically a move to roslyn-internal?

**Comment by tmeschter** [comment]
@jaredpar It's a move to dotnet/roslyn-analyzers.

**Comment by jaredpar** [comment]
:+1:

**Comment by davkean** [comment]
@tmeschter What's going on with this PR?

**Comment by tmeschter** [comment]
@davkean This pull request is redundant. Closing.

**Pull request closed without merging**
