### PR TITLE
Remove old IDocumentHIghlightsService.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @minestarks @brettfo.  This will be able to go in once your changes go in to use the new service at the lower level in Roslyn.  I'll wait on your stuff going in and flowing to our branch first.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski This should also be safe to merge in at this point.  Easy way to test is just verify that you can make an edit a TS and F# document without a problem.    Would you be willing to shepherd this in?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Can this be merged in?

**Comment by brettfo** [comment]
This looks good from the F# side; I can't find any references in our code to `IDocumentHighlightService`.

**Comment by minestarks** [comment]
we're all good too.

**Comment by jasonmalinowski** [comment]
We'll get this in in the next few weeks (I hope). Lots of moving pieces right now which is making not this PR specifically difficult but just a lot going on.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @dotnet/roslyn-ide can this be merged in now?

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Pull request merged**
