### PR TITLE
Avoid directly calling AddError.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler 

The goal here i to limit the places where we call AddError directly.  Ideally, we can get AddError down to only being called in a few core routines (like EatToken).  That way the onus is not on all the parsing routines to remember to add errors, but instead happens automatically through the low level primitives.

**Comment by cston** [comment]
LGTM

**Comment by jcouv** [comment]
(You got two reviews)

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
