### PR TITLE
Portable scripting tests

### PR DESCRIPTION
**Pull request by tmat**
1) Split scripting tests into Desktop and Portable
2) List all FX and xUnit nuget packages in .nuget\packages.config
3) List all FX references in ```build\Targets\PortableReferences.targets```
4) List all xUnit references in ```build\Targets\PortableTestReferences.targets```
5) Portable projects that have dependencies on FX libraries beyond Profile7 now import ```build\Targets\PortableReferences.targets``` and ```build\Targets\PortableTestReferences.targets``` for product projects and test projects, respectively.
6) Add Nuget.exe V3 since some FX packages are V3. List them separately in ```.nuget\V3\packages.config```

### CODE REVIEW

**Comment by tmat** [comment]
@ManishJayaswal @agocke @KevinH-MS @cston @amcasey

**Comment by tmat** [comment]
Note that although tests are now portable most of them won't run on Core CLR due to missing Assembly.Location property.

**Comment by tmat** [comment]
@jaredpar Could you review changes in build.sh?

**Comment by jaredpar** [comment]
@tmat the cibuild.sh changes look good.  

Is the NuGet binary checked in there good enough that we can use it instead of dnu now?

**Comment by tmat** [comment]
@jaredpar Maybe. @agocke mentioned some problems, but for the couple of V3 nuget packages we need it seems to work fine. We can try to use this approach for corecsc and corevbc instead of using dnu.

**Comment by tmat** [comment]
retest this please

**Comment by tmat** [comment]
retest this please

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by tmat** [comment]
retest this please

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Pull request merged**
