### PR TITLE
Move to BYOC pools

### PR DESCRIPTION
**Pull request by jaredpar**
This changes our pipelines to use the BYOC (Bring Your Own Cloud) pools
hosed by the core engineering team. This is a dynamic queue which should
scale better for our uses than the static pools we are using today.

### CODE REVIEW

**Comment by jaredpar** [comment]
@JoeRobich FYI I had to make one change to fix a warning in the IDE build. May want to review that.

**Comment by jaredpar** [comment]
@dotnet/roslyn-ide can someone review the change to the Xamarin project?

**Comment by jasonmalinowski** [comment]
@jaredpar: why was it needed? The project in question literally has no code...

**Comment by jaredpar** [comment]
@jasonmalinowski 

>  why was it needed? The project in question literally has no code...

Code is not necessary to generate an MSB3277 warning. I'm not sure which change caused it to start occuring but suddenly its blocking builds.

**Comment by jasonmalinowski** [comment]
@jaredpar Is the change related to your previous change to the queue? Asking differently, can these be two separate PRs?

**Comment by jaredpar** [comment]
>  Is the change related to your previous change to the queue?

No. I can reproduce the MSB3277 locally.
 
> Asking differently, can these be two separate PRs?

Currently there is about a four hour delay in getting machines. If I do these separately then pretty much not merging any PRs until tomorrow.

**Comment by jaredpar** [comment]
@jasonmalinowski here is a PR build from @sharwell hitting the same MSB3277 warning. 

https://dnceng.visualstudio.com/public/_build/results?buildId=139740

**Comment by jaredpar** [comment]
@dotnet/roslyn-ide, @jasonmalinowski  this PR is ready to go. All other PRs are blocked. If you truly want me to separate these two commits out into separate PRs then I can but it seems like a large waste of time. Trying to get features merged today. This is blocking.

**Comment by jaredpar** [comment]
Heading out for the day. Feel free to merge or not.

**Comment by jasonmalinowski** [comment]
> If you truly want me to separate these two commits out into separate PRs then I can but it seems like a large waste of time. Trying to get features merged today. This is blocking.

Sorry, I was entirely unaware there was a blocking problem here (or that the build was busted.)

**Comment by jaredpar** [comment]
@jasonmalinowski 

No problem. The initial change was not fixing a blocking issue, just an incredibly slow issue. Turns out the build was broken though and we hadn't found out yet because the queues were so backed up. The initial commit sped ahead, found the blocking issue and I updated it to fix that as well. I noted it was blocking [here](https://github.com/dotnet/roslyn/pull/34656#issuecomment-478792153) and in slack. But end of day, easy to miss. Probably should have bolded it.

**Pull request merged**
