### PR TITLE
Reduce TypeSymbolExtensions.VisitType's promiscuity

### PR DESCRIPTION
**Pull request by benaadams**
`TypeSymbolExtensions.VisitType` uses backtracking; iteration and recursion - and ends up over visiting types.

Ideally the algorithm would be revisted; however this takes the other approach; and uses a little duct tape.

**Customer scenario**

Writes this code
```csharp
class Class<A, B, C, D, E, F>
{
    class Inner : Class<Inner, Inner, Inner, Inner, Inner, Inner>
    {
        Inner.Inner.Inner.Inner.Inner.Inner.Inner.Inner.Inner inner;
    }
}
```

**Performance impact**
Before top call counts (using `WriteCompressedMarker` as watermark - for comparison)

After top call counts (using `WriteCompressedMarker` as watermark - for comparison)

Also `TypeParameterSymbol.get_TypeKind` (non-inlinable virtual call) is top of list at 786M calls in before and at bottom of selection in after, at 60M calls

### CODE REVIEW

**Comment by jcouv** [comment]
Looks like there are legitimate test failures.

**Comment by benaadams** [comment]
> I think they are cases where we want to visit all the types, even if that involves the same type more than once.

It currently does a explosion of visitation though; e.g. in one path for 26 types it visits then 84,652,646 times; and that has 5 repeats for different predicates - so I assume some of them are overvisits:

**Comment by benaadams** [comment]
Is currently nested type to parent, checking all children, to parent, checking all children, to parent, checking all children - so is a lot of overlap. Not sure if it just wants to check its children and direct parent chain - or just go to top type and check all children and their children; rather than checking going up and then checking coming back...

**Comment by benaadams** [comment]
Though I am a little handicapped by not knowing what it supposed to be doing :)

**Comment by benaadams** [comment]
I don't think what its doing it correct; however am also handicapped by not knowing what it supposed to be doing :)

**Comment by CyrusNajmabadi** [comment]
>  however am also a little disadvantaged by not knowing what it supposed to be doing :)

@benaadams It's unclear to me why work needs to be done here.  I read OtherMattWarrens post on this topic and was amused by the pathological nature of the situation :) .  However, it's an extremely contrived issue that doesn't seem to have practical limitations for customers.  As such, doing work to try to make this scale better doesn't seem valuable.  (Unless you're doing htis as an experiment to help you understand the compiler better, in which case there is def value from an educational perspective).

I would be very careful here though. The lookup rules for the language, and the way expansions happen are subtle and complex.  I would not want an unnecessary optimization here breaking something in ways that people didn't realize.

**Comment by benaadams** [comment]
> However, it's an extremely contrived issue that doesn't seem to have practical limitations for customers.

Valid point. 

It still outputs a 169MB dll so it doesn't improve the output.

> Unless you're doing htis as an experiment to help you understand the compiler better, in which case there is def value from an educational perspective

I found it interesting; though there is likely more value to be gained in more common code paths; though I don't currently have a problematic example or alas the luxury of spare time to investigate if I did 😢 

Along the way I learnt how to profile roslyn though, so I may come back for seconds when I have more time 😉

**Pull request closed without merging**
