### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160129-160012
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160129-160012 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet-bot Test this please

**Comment by TyOverby** [comment]
test vsi please

**Comment by TyOverby** [comment]
@dotnet-bot test this please

**Comment by TyOverby** [comment]
@jaredpar @gafter 

I merged this, but needed to fill out an implementation in https://github.com/vslsnap/roslyn/commit/8c8e0b8c50a37e8379761a453079d07b35fafbe4 for local functions.  It was pretty straight forward, but could you review for correctness?

**Comment by jaredpar** [comment]
CC @genlu to review that `IOperation` implementation.

**Comment by genlu** [comment]
`IOperation` related code looks fine. But I just noticed `OperationKind.LocalFunctionStatement` is in master branch as well, should it be removed for 1.2? @JohnHamby @jaredpar

**Pull request merged**
