### PR TITLE
Remove value that is not used in fix all.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
I'm generally trying to clean up the last remaining use of specialized fix-all (which is in simplify type names).  I expect to make several refactorings in this area.  But i will try my best to keep commits clean and independent when possible.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @mavasani @heejaechang @jcouv  @sharwell

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Were you planning on adding to this or can we call it complete there?

This PR is complete as is.  I have a couple of followup changes, but they will be in new PRs as they change actual behavior.  thanks!

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv  Very simple PR, thanks :)

**Comment by CyrusNajmabadi** [comment]
@mavasani do you want to merge in?  Thanks!

**Comment by mavasani** [comment]
Tagging @jinujoseph for approval

**Comment by jinujoseph** [comment]
Approved to merge to 15.8.Preview3

**Pull request merged**
