### PR TITLE
Respect the iteration parameter in IterationData

### PR DESCRIPTION
**Pull request by jasonmalinowski**

### CODE REVIEW

**Comment by sharwell** [comment]
This is already part of other pull requests

**Comment by sharwell** [comment]
Correction. This is already fixed in **master** 😆

**Comment by sharwell** [comment]
Duplicate of #33791

**Comment by jasonmalinowski** [comment]
Going to reopen against dev16.0 (it's actually where I made the PR); not having this merged in is currently making it hard for me to test stuf.

**Comment by jasonmalinowski** [comment]
My intent is to merge this if/when we take another fix into dev16.0. I don't want to merge this and cause a build to spin for just this change.

**Pull request merged**
