### PR TITLE
Rename Microsoft.Net.Interactive.netcore to Microsoft.Net.Interactive.CSharp.netcore

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@agocke, @dotnet/roslyn-interactive

**Comment by jaredpar** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
:+1:

**Comment by tannergooding** [comment]
@cston, @ManishJayaswal, @jaredpar. Shouldn't this be Microsoft.Net.CSharp.Interactive? We just went through all the trouble of renaming the assemblies (and all the nuget packages follow the naming convention as well).

**Comment by cston** [comment]
@tannergooding Good catch. Renamed to Microsoft.Net.CSharp.Interactive.

**Comment by cston** [comment]
@dotnet-bot retest this please

**Comment by cston** [comment]
@dotnet-bot retest this please

**Pull request merged**
