### PR TITLE
ReplaceSyntaxTree should throw on duplicate

### PR DESCRIPTION
**Pull request by amcasey**
...as AddSyntaxTrees does.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @jaredpar @VSadov @AlekseyTs @agocke @gafter 
FYI @AnthonyDGreen

**Comment by VSadov** [comment]
LGTM

**Comment by jaredpar** [comment]
LGTM

**Comment by AnthonyDGreen** [comment]
Is this just an inconsistency or is it driven by discovering it caused some bug? As this is a breaking change maybe we should relax AddSyntaxTree instead. If it's a meaningless operation then perhaps we should just ignore it?

**Comment by amcasey** [comment]
@AnthonyDGreen Should we also ignore it in cases that already throw?

**Comment by amcasey** [comment]
As we discussed offline, anyone seeing this exception should re-examine their code.

**Pull request merged**
