### PR TITLE
Revert "fix for CLR_EXCEPTION_System.NullReferenceException_80004003_…

### PR DESCRIPTION
**Pull request by agocke**
…Microsoft.VisualStudio.InteractiveWindow.dll (#26770)"

This reverts commit db46bcf53c2c662c799acf4be317f82fd7f4c94a.

### CODE REVIEW

**Comment by agocke** [comment]
test this please

**Comment by tmat** [comment]
Why revert?

**Comment by agocke** [comment]
@tmat No longer meets the servicing bar for 15.7.x, but there's another fix in this branch that we need to insert.

**Comment by tmat** [comment]
@jinujoseph @ivanbasov FYI

**Comment by jinujoseph** [comment]
test windows_release_vs-integration_prtest

**Pull request merged**
