### PR TITLE
Change order of C# completion providers to get better completions for type parameter T

### LINKED ISSUE #24960: Type parameters named T should have "T in classname<T>" tooltip in Intellisense completion list
**Version Used**: 2.6.0.62329 (VS 15.5.6), 2.7.0.62608 (VS 15.6 Preview 5)

**Steps to Reproduce**:

1. Copy the class definition below into a C# source file.
2. Invoke Intellisense completion at the two marked locations.

```c#
class TestClass<T, T2>
{
    T$$ a;
    T2$$ b;
}
```

**Expected Behavior**:
About one second after invoking Intellisense, a tooltip reading "T in TestClass<T, T2>" (or "T2 in TestClass<T, T2>", respectively) should appear next to the list entry.

**Actual Behavior**:
A tooltip will appear next to the entry for T, but it won't have any text, while the tooltip for T2 (or any other type parameter not named "T") will appear as expected.

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #24960.

When [`CompletionServiceWithProviders.AddToDisplayMap`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,368) detects a duplicate completion item, it hands the old and new items to [`GetBetterItem`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,405), which will always pick the item that came later. Because the `SpeculativeTCompletionProvider` currently comes after the `SymbolCompletionProvider`, the meaningful T item will always get overridden by the speculative T item.

With this patch the `SpeculativeTCompletionProvider` moves up the list of default completion providers a bit, in front of the `SymbolCompletionProvider`. Now, when the user brings up the completion list, the meaningful T item (with the "T in Class&lt;T&gt;" tooltip) will override the speculative T item.

Side note: I don't know how to add a unit test for this, because the test [`SymbolCompletionProviderTests.DescriptionGenericTypeParameter`](http://source.roslyn.io/#Roslyn.Services.Editor.CSharp.UnitTests/Completion/CompletionProviders/SymbolCompletionProviderTests.cs,3295) already covers this case, but it didn't fail before, because the completion service has different behaviours: during test execution, the local var [`providers` in `CompletionServiceWithProvidera.GetCompletionAsync`](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/Completion/CompletionServiceWithProviders.cs,224) has only one provider, a `SymbolCompletionProvider` (which returns the correct result); when run as part of *VisualStudioSetup*, `providers` contains 22 providers.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
You should be able to use CSharpCompletionCommandHandlerTests to write a test here.

**Comment by jhinder** [comment]
Yes, that worked. I've added two unit tests now. Thank you!

**Comment by jasonmalinowski** [comment]
FYI to @dpoeschl who might already have fixed this in the new implementation. (Or might not have!)

**Comment by dpoeschl** [comment]
We still use this service in old & new completion, so this would be a nice fix to take for both!

**Comment by dpoeschl** [comment]
(close/reopen to rekick tests)

**Comment by jinujoseph** [comment]
@ivanbasov  can you review and buddy this thru.

**Comment by jasonmalinowski** [comment]
@ivanbasov Per your comments on January 2nd, do we still need this change? This:

> There are changes already published in master-vs-deps for a new completion approach. master-vs-deps is what we currently use for shipping Dev16 previews.

Makes me think we already have the fix in master now?

**Comment by ivanbasov** [comment]
Yes, currently all those changes are already in master. The right approach for now is to resolve conflicts with master and be sure unit tests correspond to existing tests in master.

**Comment by jasonmalinowski** [comment]
@ivanbasov Can you take over as buddy for this PR? I'm not sure how this landed on me, given this is your area of expertise.

**Comment by ivanbasov** [comment]
@jhinder, would you like to resolve conflicts with tie master branch and merge the PR? Or do you need any help from us?

**Comment by jhinder** [comment]
I've rebased the changes onto master (I figured it'd be fine now that 16.0 has shipped -- if not, tell me and I'll rebase) and fixed the conflicts/required changes (or rather, I did that back in January and totally forgot about it -- sorry about that).

But now the tests are broken, both for legacy and modern completion.

The behaviour of `CompletionServiceWithProviders` is still correct: the proper T completion item wins over the speculative one, and ultimately ends up in the list of completion items.
However, the item has no `DisplayText` (expected: `T in C<T>`).
In the legacy variant of `AssertSelectedCompletionItem`, this understandably fails on [line 206](https://github.com/dotnet/roslyn/blob/43368ee4df7f26b693c68d339500f3f1e15427bf/src/EditorFeatures/TestUtilities2/Intellisense/LegacyTestState.vb#L206).
I have a question about the modern completion though: why does the assertion on [line 244](https://github.com/dotnet/roslyn/blob/43368ee4df7f26b693c68d339500f3f1e15427bf/src/EditorFeatures/TestUtilities2/Intellisense/ModernCompletionTestState.vb#L245) concatenate `displayText` and `displayTextSuffix`, and then compare that to the item's `DisplayText`? That would fail even if `DisplayText` had a value.

The method [`AddDescriptionForTypeParameter`](https://github.com/dotnet/roslyn/blob/fd501c70615a687560b22b0ade32a34f4721068a/src/Features/Core/Portable/LanguageServices/SymbolDisplayService/AbstractSymbolDisplayService.AbstractSymbolDescriptionBuilder.cs#L611) in `AbstractSymbolDescriptionBuilder` (which is the only call site of `FeatureResources.in_` FAR found outside of tests) is never called during execution of those tests, and neither is any of its callers up the call chain. Could that be why there's no display text?

**Comment by ivanbasov** [comment]
@jhinder could you please rebase to upstream/master and push?

**Comment by jhinder** [comment]
@ivanbasov Done. The tests in question are still failing, mind.

**Comment by ivanbasov** [comment]
> @ivanbasov Done. The tests in question are still failing, mind.

Thank you, @jhinder ! Now only tests just added failed: `TypeParameterTOnType` and `TypeParameterTOnMethod`. You may want to take a look. If you need help with this, it seems reasonable if you'd allow us to contribute by checking 'Allow edits from maintainers' on the PR.

**Comment by jhinder** [comment]
@ivanbasov I already dug into the issue about two months ago (see my comment from 4 April). Do you have any idea why that behaviour might occur (the tests succeeded back when I wrote the fix a year ago)?

**Comment by ivanbasov** [comment]
Thank you, @jhinder !

1. Regarding the question about modern completion, `Suffix` in `VSCompletionItem` displayed in UI different way comparing to one we used to have in the legacy completion. Therefore, we decided to send the concatenation of prefix-displaytext-suffix to the Editor API. This decision should not affect any tests. 

2. I do not know what changed since the last year that broke tests. To investigate this, I had to enlist into your PR and debug it. If you want me to do so, please set 'Allow edits from maintainers' that will allow me to commit my suggestions.

**Comment by ivanbasov** [comment]
Thank you for your help, @jhinder !

**Pull request merged**
