### PR TITLE
Remove redundant MethodKind parameter

### PR DESCRIPTION
**Pull request by Youssef1313**
Related to #58475.

### CODE REVIEW

**Comment by davidwengier** [comment]
Looks like you were right 👍

**Comment by Youssef1313** [comment]
@davidwengier Do you think it's worth getting this merged? I opened it only for curiosity.

**Comment by davidwengier** [comment]
May as well, keeps the code cleaner.

**Review by davidwengier — APPROVED** [review]

**Comment by davidwengier** [comment]
Thanks as always @Youssef1313 😄

**Pull request merged**
