### PR TITLE
Ensure that we throw the CLR's InsufficientExecutionStackException in…

### LINKED ISSUE #22193: Revisit use of BoundTreeRewriterWithStackGuard in VisualBasicOperationFactory_QueryLambdaRewriter.vb
See https://github.com/dotnet/roslyn/pull/21356#discussion_r139535884

### PR DESCRIPTION
**Pull request by mavasani**
…stead of CancelledByStackGuardException

As the rewriter is being invoked from the OperationFactory, which is accessible from the public API `SemanticModel.GetOperation`, we prefer to throw the CLR InsufficientExecutionStackException instead of compiler's internal CancelledByStackGuardException.

Fixes #22193

### CODE REVIEW

**Review by heejaechang — APPROVED** [review]

**Comment by heejaechang** [comment]
I found the test that checks long expression case asked in last design meeting. (https://github.com/dotnet/roslyn/pull/20964/files#r129447310)

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by mavasani** [comment]
Ping for reviews.

**Review by AlekseyTs — APPROVED** [review]
LGTM

**Comment by mavasani** [comment]
Can I get one more review and ask mode approval @jaredpar @jcouv?

**Comment by jaredpar** [comment]
Will let @jinujoseph provide ask mode guidance here.

**Comment by jinujoseph** [comment]
wait for one more sign off from compiler

**Review by cston — APPROVED** [review]

**Pull request merged**
