### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by alrz**

### CODE REVIEW

**Comment by Pilchie** [comment]
@dotnet/roslyn-ide @CyrusNajmabadi Please review.

@MattGertz for approval for approval on a comment update.

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by MattGertz** [comment]
This doesn't meet an ASK mode bar.

**Comment by MattGertz** [comment]
Changed my mind.  No code impact, so I don't mind a bit of hygiene,

**Pull request merged**
