### PR TITLE
Adjust XmlDocumentationCommentTextReader.Reader to be finite.

### LINKED ISSUE #4699: Connect: Intellisense for a method which contains a unclosed HTML comment crashes VS
Having an issue with a particular class and when IntelliSense was being displayed for this existing method, VS would crash. Looking at the method's code, it contained the beginning of a HTML comment in the form <!-- (The < is not in an encoded form) and there was no closing tag. Adding a closing tag or encoding the < fixes the issue. 

Attached is a repo project [not in github] and when in class1 if you type test.TestMethod and wait for IntelliSense to appear VS will crash with an out of memory error. I would have expected VS to not crash an just display blank IntelliSense with the methods signature. 

Note: This applies to Visual Studio 2015 Full.

[Migrated from TFS/DevDiv 1210421]

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #4699.

@gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.
CC @amcasey, @tmat

### CODE REVIEW

**Comment by amcasey** [comment]
As we discussed offline, I think it would also be nice to skip this work entirely when in Parse mode.

**Comment by AlekseyTs** [comment]
This would make behavior inconsistent between Parse and Diagnose mode for C#. There is a value in going through the XmlReader for the purpose of the GetDocumentationCommentXml API even in Parse mode.

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by amcasey** [comment]
Oh, I see - ```haveParseError``` is set regardless of whether a diagnostic is reported.  I agree that it makes sense to retain that behavior.

**Comment by TyOverby** [comment]
Should all occurrences of "mulformed" be "malformed"?

**Comment by AlekseyTs** [comment]
@TyOverby Thanks, I'll fix the spelling.

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @gafter, @jaredpar, @agocke, @TyOverby Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet-bot Test win 32 please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test windows 32 please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test windows

**Comment by AlekseyTs** [comment]
Test win 32 please

**Comment by AlekseyTs** [comment]
Test win please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by jaredpar** [comment]
:+1:

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
