### PR TITLE
Make more of the IDE layer async.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2185/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by davkean** [comment]
test ccc please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Pull request merged**
