### PR TITLE
Add "Test" project type GUID to all test projects

### PR DESCRIPTION
**Pull request by sharwell**
This change affects the way these projects are displayed in Solution Explorer. When test projects are clearly indicated, it allows them to be manually unloaded. I use this approach to unload all but one test project at a time when I need to debug tests, since this dramatically improves the performance of Test Explorer.

### Before

image

### After

image

## Ask Mode

**Customer scenario**

This change only changes the unit test projects. It does not change code distributed to customers.

**Bugs this fixes:**

N/A

**Workarounds, if any**

Assume that the projects with a name ending with **Test** are test projects.

**Risk**

Low. The new project type GUID should not negatively affect project loads for any contributors.

**Performance impact**

None (no changes are made to production code).

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

N/A

**How was the bug found?**

It was a personal annoyance.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @jaredpar @tannergooding and @OmarTawfik.  Can't this be done in a targets file based on our project type stuff?

**Comment by jaredpar** [comment]
There is definitely enough metadata present to add this in Imports.targets automatically.  Will VS pick that up though or does it need to be in the actual project file to light up the experience?

**Comment by OmarTawfik** [comment]
I saw a similar issue in #17370 where VS keeps adding test explorer service GUIDs.
@tannergooding would know better.

**Comment by tannergooding** [comment]
Not sure if project type GUIDs need to be declared in the csproj file or not, although it would be simple enough to check.

In either case, aren't these going away with the conversion to the new project system anyways?

**Comment by sharwell** [comment]
@jaredpar @Pilchie I tested and this does not work unless it's in the project file itself.

**Comment by sharwell** [comment]
Rebased to address merge conflict

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by tannergooding** [comment]
@sharwell, for the projects that have been migrated to the new SDK, we should be using ProjectCapabilities, rather than ProjectTypeGuid (@srivatsn might be able to point to docs or give the appropriate capability to add).

**Comment by sharwell** [comment]
@tannergooding Sounds good. I'll rebase and update after I hear from @srivatsn.

**Comment by srivatsn** [comment]
There's a capability you can add to the project called `UnitTestContainer` (see [here](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/project_capabilities.md)). However, the reason you are doing this is so you can see the test icon. I don't know if the test flavor recognizes this capability. @codito @sbaid would know.

**Comment by sharwell** [comment]
@srivatsn Currently the icon is not updated when you add the following to the project:

```xml
<ItemGroup>
  <ProjectCapability Include="UnitTestContainer" />
</ItemGroup>
```

However, it's possible that this would change in a future release. With that said, the important part I need to know is whether this line needs to be in the project file itself (the .csproj/.vbproj), or if it will work equally well to place it in an included .props file.

**Comment by srivatsn** [comment]
Depends on how it's implemented when they implement it in a future release - they should use the msbuild evaluation model to read the capability item so that you can put these in the props.

**Comment by sharwell** [comment]
@srivatsn This has now been updated to use ProjectTypeGuids for legacy projects, and capabilities for new projects. Everything look good to you?

**Comment by sharwell** [comment]
@codito @sbaid Please let me know if/where I should file a bug to have the project icon in solution explorer reflect projects with the UnitTestContainer capability.

**Comment by srivatsn** [comment]
@codito @sbaid - to get the icon for CPS you need to MEF export a component like this - https://github.com/dotnet/project-system/blob/master/src/Microsoft.VisualStudio.ProjectSystem.CSharp.VS/ProjectSystem/VS/Imaging/CSharpProjectImageProvider.cs Work with us when you get to this.

**Pull request merged**
