### PR TITLE
Do not use the shallow checkout job during integration CI

### PR DESCRIPTION
**Pull request by JoeRobich**
https://github.com/dotnet/roslyn/issues/52444

Disables the shallow checkout task.

### CODE REVIEW

**Comment by JoeRobich** [comment]
CC: @RikkiGibson

**Comment by JoeRobich** [comment]
azp /run

**Review by sharwell — CHANGES_REQUESTED** [review]
The checkout issue _only_ impacts builds triggered with `/azp run`, so we should first try to get that bot fixed.

**Comment by JoeRobich** [comment]
I tried /azp run on this PR and the CI run was against the merge commit, so it isn't even consistent.

**Pull request closed without merging**
