### PR TITLE
update unit tests to use localized resources

### LINKED ISSUE #818: Roslyn.VisualStudio.Services.UnitTests.dll - 138 tests fail with Russian language set as primary with localized resources present
Ported from TFS WorkItem: **1101390**

------------------------------

**Repro Steps:**

**Steps to reproduce (likely to&nbsp;repro with other languages):**<BR>

1. Follow three steps described at [http://windows.microsoft.com/en-us/windows-8/using-multiple-languages](http://windows.microsoft.com/en-us/windows-8/using-multiple-languages)&nbsp;to install Russian language pack and make Russian the primary language.

&nbsp;

2. Queue Main-PerCheckin-Debug build with pseudo localization for Russian language (go to the Parameters tab in the Queue Build dialog and change Localization Languages value to RUS)

&nbsp;

3. Wait for the drop. Copy binaries to the machine prepared on step 1. Copy localize\RUS folder from the drop location next to the binaries and rename it to 'ru'. Verify that output of command line compilers is localized.

&nbsp;

4. Run tests. I simply copy bits over to Binaries\Debug folder on the previous step and run 'test' script.

&nbsp;

The test log is attached.

------------------------------

**Revisions:**

1) Created By Aleksey Tsingauz (1/2/2015 10:30:31 AM)

------------------------------

2) Edited By Jason Malinowski (1/5/2015 3:11:13 PM)

Brett, can you look at Microsoft.VisualStudio.LanguageServices.UnitTests.ProjectSystemShim.VisualStudioAnalyzerTests.AnalyzerErrorsAreUpdated : Assert.Contains() failure: Not found: !hOPPn!Unable to load Analyzer assembly C:\Users\alekseyt\AppData\Local\Temp\tmp4910.tmp: ЁЧЫюр! In value: !hOPPn!Unable to load Analyzer assembly C:\Users\alekseyt\AppData\Local\Temp\tmp4910.tmp: Image is too small. ЁЧЫюр! to see if there's a problem there?

------------------------------

3) Edited By Brett Forsgren (1/14/2015 2:15:12 PM)

I've checked the failures and they're all due to tests using hard-coded English strings.&nbsp; The specific case mentioned below (AnalyzerErrorsAreUpdated) is due to the fact that loc strings get a prefix and a suffix so the string &quot;!abcd!Unable to load Analyzer assembly !suffix!&quot; understandable cannot be found in &quot;!abcd!Unable to load Analyzer assembly &lt;some assembly&gt;!suffix!&quot;.&nbsp; The proper fix for that test would be for the String.Format() call to not pass 'Nothing' into the loc string, but rather pass the appropriate assembly path.

&nbsp;

Moving bug to RTM since it's only tests that need to properly use the loc strings and not a product bug.

------------------------------

### PR DESCRIPTION
**Pull request by brettfo**
Fixes #818.

### CODE REVIEW

**Comment by VladimirReshetnikov** [comment]
:+1:

**Comment by balajikris** [comment]
LGTM.

**Comment by Pilchie** [comment]
:+1:

**Comment by brettfo** [comment]
test this please

**Pull request merged**
