### PR TITLE
Remove legacy 'todo list' support

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
TypeScript moved off of the legacy API here: https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS/pullrequest/424103?_a=files

So it can be removed safely.

### CODE REVIEW

**Comment by Cosifne** [comment]
Do you want to this to be in 17.4?

**Review by genlu — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
> Do you want to this to be in 17.4? (If so, then target release/dev17.4)

I don't see any need for this to be in 17.4

> Also, does this mean we need to wait TS to merge & insert first, and then we insert the change?

Isn't that what this PR from TS is: https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS/pullrequest/424103?_a=files ?

Do they have a separate insertion process on top of that?

**Comment by Cosifne** [comment]
> > Do you want to this to be in 17.4? (If so, then target release/dev17.4)
> 
> I don't see any need for this to be in 17.4
> 
> > Also, does this mean we need to wait TS to merge & insert first, and then we insert the change?
> 
> Isn't that what this PR from TS is: https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS/pullrequest/424103?_a=files ?
> 
> Do they have a separate insertion process on top of that?

I think the link you posts is the VS extension for TS right? So I guess they also need to insert their payload to VS in some way.
If we inserted this first, and they do it next. There might be some broken builds.

But since it doesn't need to be in 17.4 this won't be a problem yet. Since there is no 17.5 branch in VS, by the time when 17.5 opens we should be fine.

**Review by Cosifne — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
> I think the link you posts is the VS extension for TS right? So I guess they also need to insert their payload to VS in some way.
If we inserted this first, and they do it next. There might be some broken builds.

Ah, i didn't realize that.  Thanks! :)

**Comment by MariaSolOs** [comment]
I agree with everything that @Cosifne said :) https://devdiv.visualstudio.com/DevDiv/_git/TypeScript-VS/pullrequest/424103 only added TaskList support to our main branch but our insertion into VS happens later.

**Pull request merged**
