### PR TITLE
Add simplifier annotation to cast expressions generated using syntax gen...

### LINKED ISSUE #472: Implement Interface through member adds extra casts
Ported from TFS WorkItem: **1105750** and [http://roslyn.codeplex.com/workitem/482](http://roslyn.codeplex.com/workitem/482)

SSL reported:

Source:
```
sealed class X : IComparer{
X x;
}
```
Quick fix:
```
public int Compare(object x, object y) {
return ((IComparer)this.x).Compare(x, y);
}
```

Why do you add the cast, even when there is no explicit implementation?
The cast is highlighted as unnecessary (only when the class is sealed)

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
...erator.

This ensures that code fixes such as Implement Interface Through Member never generate casts that user has to simplify in a subsequent manual step.

Fixes #472

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@srivatsn @heejaechang @mavasani @jmarolf, could you please take a look?

**Comment by mavasani** [comment]
:+1:

**Comment by srivatsn** [comment]
Normally the SyntaxGenerator doesn't add Simplify annotations but maybe it's reasonable to do so for cast expressions... /cc @mattwar

**Comment by mattwar** [comment]
It does add simplifier annotations for type expressions.  This change does fit with the intended use cases for SyntaxGenerator.

:+1:

**Pull request merged**
