### PR TITLE
made syntaxtree and symbol tree info cache builder to run on OOP thro…

### PR DESCRIPTION
**Pull request by heejaechang**
…ugh solution crawler.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @panopticoncentral @Pilchie @CyrusNajmabadi can you take a look?

**Comment by heejaechang** [comment]
do we want to disable these (the cache builder) from running in proc if those IDE features run on OOP? or those cache might be used for some other features than FAR, GOTO, SymbolSearcher?

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by heejaechang** [comment]
@Pilchie HR will run on OOP as well since SymbolFinder API itself is the one that gets replaced to run on OOP not find all reference command.

I am working on moving all solution crawler analyzer such as Todo, designer scanner and etc to OOP so, I will turn it off as I go with that work.

**Comment by Pilchie** [comment]
I'm very much looking forward to getting all solution crawlers OOP!  Nice work.

**Pull request merged**
