### PR TITLE
Pascal and camel case should not allow underscores -- unless "_" is set as word_separator

### PR DESCRIPTION
**Pull request by HaraldNordgren**
Fixes: https://github.com/dotnet/roslyn/issues/22745
Fixes: https://github.com/dotnet/roslyn/issues/23706

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
@CyrusNajmabadi I am having trouble getting the tests to work locally on my machine (I am on macOS) and on CI the build appears to be generally broken.

**Comment by HaraldNordgren** [comment]
Running

```
./build.sh --test
```

it runs the tests suite, but it doesn't seem like that e.g. this test runs at all:

```
TestCamelCaseLocalsUpperCaseConstants_ConstLocal
```

the the file in question is

```
src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs
```

Can someone help me out regarding that?

**Comment by sharwell** [comment]
I worry this is going to cause a very large number of new warnings to show up in existing code, and there is no Fix All support for naming styles.

**Review by sharwell — CHANGES_REQUESTED** [review]
Can you rebase this to remove the two unrelated commits from @jjonescz ? These issues are being handled separately and may not take this final form.

**Comment by HaraldNordgren** [comment]
> Can you rebase this to remove the two unrelated commits from @jjonescz ? These issues are being handled separately and may not take this final form.

Done.

**Comment by HaraldNordgren** [comment]
> I worry this is going to cause a very large number of new warnings to show up in existing code, and there is no Fix All support for naming styles.

That's a good point maybe this should be merged in this form.

But do you agree with me that PascalCase and camelCase should not have underscores? I feel like this should be fixed in some way.

Would it be feasible to introduce new constants for `pascal_case_no_underscore`, or `pascal_case_new` or something similar to avoid breaking existing usage? I'm not totally sold on those names myself, but it's an example of something that would be backwards compatible.

**Comment by CyrusNajmabadi** [comment]
> But do you agree with me that PascalCase and camelCase should not have underscores?

I'm not sure i agree with that.  Sometimes we def do thigns like FooBarBaz_SpecialCaseWithUnderscoreToGroupThings

**Comment by HaraldNordgren** [comment]
I am not meaning to be argumentative at all, but wouldn't that be the case then to specify like this:

```editorconfig
dotnet_naming_style.some_style.capitalization = pascal_case
dotnet_naming_style.some_style.word_separator = "_"
```

Or use `required_prefix = "_"` and/or `required_prefix = _`.

And otherwise Pascal case and Camel case would not allow underscores.

**Comment by HaraldNordgren** [comment]
I have realized as I worked on this PR that a strict definition of pascal case is quite unenforceable even without the underscore issue.

I would assume (maybe it's a personal opinion) that most people will expect casing to be used semantically, so that `ThisIsValidPascalCase` but `ThiSIsnOtValid`. However, without a dictionary at hand it's not possible I think. And even with a dictionary, there is the issue that a lot of programming concepts are not actual dictionary words. Oftentimes because they are domain or company specific.

So this explains why we currently do FirstWordUpper and call that PascalCase.

That's a side note. But my point is that although these issues seem trivial, I realize that they hold more complexity.

**Pull request closed without merging**
