### PR TITLE
Don't add accessors for a property with an arrow-body

### LINKED ISSUE #6034: Convert to property doesn't work with expression bodied members
``` C#
class C
{
    int GetNumber() => 42;
}
```

Invoke convert to property and you end up with:

```C#
class C
{
    int Number { get; } => 42;
}
```

We should remove the `{get;}` in this case.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is the port to update1 of the code action fix.

Fixes #6034

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1L

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit32  please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit32  please

**Pull request merged**
