### PR TITLE
Allow 'const' implicitly typed local variables.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Implements one take on ~~#4423~~ dotnet/csharplang#106 (inferred type for `const` declarations)

### CODE REVIEW

**Comment by apskim** [comment]
There was a more concise proposal #4423, which allows simply `const x = 4` instead of `const var x = 4` (which looks quite self-contradictory to me, by the way). #4423 got an "Up for Grabs" label. Why not upgrade this PR to that syntax instead?

**Comment by CyrusNajmabadi** [comment]
@apskim I can bring that suggestion to the language design meeting today.

Note: i don't see how it's contradictory at all.  "var" simply means "you don't need to specify the type because we can figure it out from the initializer."   So "const var" means the exact same thing, except now it's 'const'.

Right now you can say:

```c#
const string s = ...
```

Being able to say "var" instead of "string" seems natural and parallel to the existing language constructs we have today.

**Comment by apskim** [comment]
@CyrusNajmabadi I understand the logic and how it is parallel to the existing constructs. However, in most languages (Scala, TypeScript, Swift) `var`, `var`, `const`, `let` and friends are keywords for _introducing an entity_, not for _replacing its type_. Thus, a sentence `const var` for a person coming from that background looks quite confusing (is it a constant or a variable?) If `var` had a different name (e.g. `auto` from C++), that would not be a problem, but it's too late now.

I guess the team picked the word `var` for C# 3.0 exactly because it makes an impression of "introducing a new variable" (the type is inferred; the language construct emphasizes that the act of introducing a variable is the most important one, and communicating its type is secondary).

**Comment by CyrusNajmabadi** [comment]
@apskim All those languages came after C# :)

```var``` in C# is used for a very specific reason.  To allow someone to avoid writing the type.  As such, it fits in other locations where we could sensibly allow you to elide the type as well (like ```const int I```).  

That said, as mentioned earlier, I will discuss with the Language Design group if we think the shorthand form ```const I``` would also be acceptable.  As it is syntactically unambiguous, I think it would be fine.  That said, I don't think having multiple forms that differ in such a minor fashion is valuable.  So i'll be personally be going just for the ```const var I = ``` form.

**Comment by CyrusNajmabadi** [comment]
> const var  for a person coming from that background looks quite confusing (is it a constant or a variable?)

It's a constant variable, just like it says :)

Why would having two keywords be an "or" situation?  Ok... we screwed up with "protected internal", but in all other cases in the language, keywords "and" together.  So "public static" is something that is both public and static.  "const var" is something that is both a constant and a var.

**Comment by apskim** [comment]
> It's a constant variable, just like it says :)

> Why would having two keywords be an "or" situation?

@CyrusNajmabadi I was unclear, sorry. I wasn't assuming that the semantics of `const var` is disjunctive, like in `protected internal`. I was saying that for a group of readers like me, it is self-contradictory as in "I don't understand which of the two possibilities are specified".

To clarify: for me the words "constant" and "variable" are _antonyms_. I guess that philosophically there exist two points of view:
1. There exist two kinds of _entities_: mutable and immutable. A mutable entity is called a _variable_. An immutable entity is called a _constant_.
2. _Variable_ is a synonym for _entity_. A variable can have various properties (adjectives). One possible property of a variable is "being a constant".

I personally think in terms of POV №1, but that's just me. The question is, how many people think in terms of №1, and how many think in terms of №2. If the split turns out to be 50:50, then including both syntaxes seems useful.

**Comment by mikedn** [comment]
> It's a constant variable, just like it says :)

Nope, the current C# specification disagrees. Both local and field constants are treated differently from variables. For example check 8.5 where there are 2 different subsections for local variables and local constants.

C++ does have constant variables but C# constants and C++ constants are quite different, C++ constants are more like C# readonly fields.

**Comment by CyrusNajmabadi** [comment]
> Nope, the current C# specification disagrees.

Well... yes.  Because this feature isn't supported yet.  In my proposal it becomes the conjunction. Which seems sensible to me.  In C# when you have multiple keywords you create a thing with all the aspects of all those keywords (except for 'protected internal' :( ).

**Comment by CyrusNajmabadi** [comment]
> I was saying that for a group of readers like me, it is self-contradictory as in "I don't understand which of the two possibilities are specified".

But you're asking me to design the language such that it is not consistent with itself, but so that it is consistent with other languages which have different meanings for these terms.  I'd rather the language stay consistent with itself here.  "var" is not a synonym for "entity" in C#.  It's a mechanism to avoid having to state the type from a variable declaration and instead have the compiler infer it from the initializer.  

> If  var  had a different name (e.g.  auto  from C++), that would not be a problem, but it's too late now.

C++ ```auto``` also came after C#'s ```var``` :)   

I can't imagine a single language feature that is consistent among all languages.  Even the humble ```=``` has a myriad of different meanings depending on which language you go to.  

Now, if we were adopting some feature that existed elsewhere, wasn't in the language at all, and had a fairly consistent form elsewhere, I can imagine us taking that into account when bringing it to C#.  However, that's not the case here.  Here's where we're just taking what's already in the language today and just relaxing things to allow it in more situations. :)

**Comment by mikedn** [comment]
> Well... yes. Because this feature isn't supported yet. In my proposal it becomes the conjunction.

But the main goal here is to get type inference to work for constant definitions and not to turn constants into variables. Note that my reply was specific to your comment that a constant is a variable. It is not and it would be impossible to change the spec to make it so.

>  In C# when you have multiple keywords you create a thing with all the aspects of all those keywords (except for 'protected internal' :( ).

Not necessarily. To quote the C# spec:

> 10.4 Constants ...  Even though constants are considered static members, a constant-declaration neither requires nor allows a static modifier.

If `static` isn't required why would `var` be?

I think the real issue is the `var` name which is obviously a shorthand for variable. If we had `auto` instead of `var` then `const auto` would have been fine. If C# constants worked like C++ constants then `const var` would have been fine. But neither is true and we get `const var` for something that doesn't really have a variable aspect. The next thing that will happen is that people will write blog posts complaining that they have to define a variable to get a constant much like the had to click the Windows's "Start" button to shutdown the machine :)

**Comment by CyrusNajmabadi** [comment]
> If  static  isn't required why would  var  be?

Because 'var' is the word in C# to say "infer the type from the initializer". :)
And, as such, fits very nicely into the feature where we want constants, but we want their type to be inferred.

> If  static  isn't required why would  var  be?

I didn't say you had to use all keywords to define a thing.  I said that, in general, in the language, providing multiple keywords provides you with the conjunction of their meanings.   There can certainly be cases where shorthands are provided.

> I think the real issue is the  var  name which is obviously a shorthand for variable

But it isn't.  If it was, then this would be legal:

```c#
foreach (var v in collection) {
    v = something; // can't do this.
}

using (var v = GetSomething()) {
    v = something; // can't do this.
}
```

 'var' already does not mean 'variable' in C#.  It means 'this is an inferentially typed declaration'.  i.e. we determine the type of variable from the context it is used in, rather than making you specify it directly.  

In every location in the language where 'var' is supported, it is used solely to allow you to elide a type when it can be inferred from the surrounding context.  That is its purpose. Whether or not a symbol is readonly or not, or constant or not, is a separate from its type and if it was provided explicitly or implicitly.
--

And, to repeat: 

> That said, as mentioned earlier, I will discuss with the Language Design group if we think the shorthand form  const I  would also be acceptable. As it is syntactically unambiguous, I think it would be fine. 

I hear your feedback.  I am ok with your proposal.  I agree that it is a reasonable, unambiguous, shorthand form for the feature.  I am bringing both options to the LDM.   And if either is approved, i'll be implanting it.

**Comment by mikedn** [comment]
> But it isn't. If it was, then this would be legal: ...

That doesn't mean that `v` isn't a variable. It's not assignable because it is `readonly`, not because it is `const` or a non-variable:

> 8.8.4 ...  The iteration variable corresponds to a read-only local variable with a scope that extends over the embedded statement.

**Comment by CyrusNajmabadi** [comment]
At this point I have no idea what "variable" actually means to you :)

**Comment by CyrusNajmabadi** [comment]
Also, it seems like you're extremely hung up on the piece of syntax here.  That "auto" vs "var" have such an affect on your reading (despite how C# has treated 'var' up to now) indicates strong influence of your own internal view of 'var'.  I recommend stepping back and not necessarily viewing all languages through the lenses of choices made elsewhere.  C# is not Swift or Scala or any of these other languages.  While there may be syntax that is similar to what you've seen elsewhere, that does not mean that that syntax is used in precisely the same way across all these languages.

I've got lots of experience with many different languages, and it does not bug me when this happens.  For example, Classes/Structs mean very different things in C# vs C++.  Destructors/Finalizers are very different (despite being syntactically close).   Enum's are hugely different across many languages.  'const' itself has a wide variety of meanings.  etc. etc. etc.  It's fine to know and be influenced by how other languages have done things.  But that does not mean you have to be beholden to them. 

'var' may mean something in other languages.  And if we were just adding 'var' to C# today we could consider being closer to those languages.  But, that isn't what happened.  'var' was added to C# long ago, and had an entirely different meaning.  We could consider changing that.  But i don't see the need, nor do i personally have the desire given that the current meaning has served us well.

But, as i mentioned several times over at this point.  I will leave it to the LDM to make a determination here.  Syntactically, both approaches work fine.  And semantically they're identical in terms of what your final program will be.  So it will come down to which approach (possibly neither!) the design group feels best fits the language.

**Comment by mikedn** [comment]
> At this point I have no idea what "variable" actually means to you :)

Well, it's actually very simple:

> 5. Variables 
> Variables represent storage locations.

Constants do not have any associated storage. Referencing a constant in an expression results in that constant's value being used directly instead of being read from storage like it happens for variables. This leads to well know behavior differences between constants and readonly variables.

> 'var' may mean something in other languages.

The only other language I brought into this discussion is C++ and I only mentioned it for contrast. Besides, it doesn't even have `var` and I don't really care what `var` means in other languages. Usually I take the view that if the language specification says that x means y then that's what it means and the meaning assigned to x by other (both programming and natural) languages is irrelevant. But still, language keywords tend to be chosen for their natural language meaning, we have `if`, `for`, `while` and not `pi`, `foo` and `theta`.

Oh well. In retrospect, the `var` name was a bad choice but I suppose we'll have to live with it.

**Comment by paul1956** [comment]
@mikedn  I am not sure what you mean by the statements below
```
Constants do not have any associated storage
```
Well then where do they live, unless they are very small the CPU registers can't hold them, therefore they are in storage (memory).
```
Referencing a constant in an expression results in that constant's value being used directly instead of being read from storage like it happens for variables
```
From a hardware prospective, both constants and read-only variables are identical and live in memory until they are read into the CPU. The only time constants are really constant is when they are stored in code segments stored in Flash, like can be done in "C". I was not aware C# could do that. If it can then I agree with you there is a real difference that matters. 
```
.This leads to well know behavior differences between constants and read-only variables.
```
Please enlighten us because I don't see any real difference that is visible to either the hardware or the programmer.

**Comment by mikedn** [comment]
@paul1956
> Well then where do they live, unless they are very small the CPU registers can't hold them, therefore they are in storage (memory).

* Local constants - nowhere, they exist only at compile time. At runtime they're indistinguishable from literals.
* Member constants - they're stored in metadata so they can be referenced by other assemblies but they don't have any associated storage in the same way variables do. And just like local constants they are indistinguishable from literals at runtime.

> From a hardware prospective, both constants and read-only variables are identical and live in memory until they are read into the CPU. ...

We're discussing a high level language feature based on the way it is specified and not the way it is implemented. For example constants of decimal type actually have storage because the CLR doesn't support decimal constants so the C# compiler has no choice but to simulate such constants by using static readonly fields and a custom attribute. But as far as the language specification is concerned constants do not have storage. Or, if you want to be more precise, you could say: "It is unspecified if constants have storage but under no circumstances the constant value will be read from storage at runtime".

> Please enlighten us because I don't see any real difference that is visible to either the hardware or the programmer.

The most obvious difference is that if you define a constant in an assembly and then use that constant in another assembly that other assembly will need to be recompiled if the constant value changes and you want to use the new value. This doesn't happen with static readonly fields where the "current" value is always used.

**Comment by CyrusNajmabadi** [comment]
Under that interpretation, i can see your confusion.  It's best to try not to get too hung up on how some languages use keywords.  If you do, you'll just end up always confused by how languages differ in so many of these areas.  Cheers!

**Comment by paul1956** [comment]
@CyrusNajmabadi  that is why I always try to translate foreign languages to one I understand well.

@mikedn Just so I understand, if Assembly A defines a Constant X = 5 and a Module in Assembly B assigns a variable Q the value of X the compiler assigns 5 to Q with no connection back to Module A. In fact there is no dependence at runtime to Module A. Where if X a read-only variable there would be a dependence between the module and a newer version of Module A could change the value of X. Correct?

**Comment by mikedn** [comment]
@paul1956 Yes, that's correct.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by khellang** [comment]
I think `const x = 4` reads much better than `const var x = 4` or `const int x = 4`, so :+1: to that.

@paul1956 You should read http://www.stum.de/2009/01/14/const-strings-a-very-convenient-way-to-shoot-yourself-in-the-foot/.

> As you see, **A const string is not a reference to something**. While a static readonly string is still a reference to a field in a class which will be resolved only at runtime, a const string is actually “copy/pasted” by the compiler.

> Say you have multiple assemblies, one that provides the const and one that consumes it. What happens if you change the two string in the “provider.dll” without touching the consumer.dll? The MyStringTestClass.StaticReadonly will point to the new reference, **but the const string will not change**, because it had been literally inserted. You will need to recompile the consumer.dll to have the string replaced with the new one.

**Comment by diryboy** [comment]
I think the syntax `const x = 1` will confuse the intellisense autocomplete between aggressive and suggestion mode after you type `const` and hit space.

I understand in C# `var` is just a syntactic placeholder for a type symbol, so `const var x = 0` looks fine for me.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski please retest this

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest prtest/mac/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/eta please

**Comment by CyrusNajmabadi** [comment]
retest prtest/lin/dbg/unit32  please

**Comment by CyrusNajmabadi** [comment]
retest prtest/mac/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/eta please

**Comment by CyrusNajmabadi** [comment]
retest prtest/mac/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by alrz** [comment]
@diryboy A little late, but, what about `from`? or `join`? or `let`? also this one #6400?

**Comment by diryboy** [comment]
@alrz I'm not aware of something like `from var`, `join var` constructs, if so, that might also cause ambiguous completion behavior, depending on the context.

`let x = ...` is used within Linq while `let var x = ...` is not(?), so it's possible for IDE to disambiguate, but I'm not sure.

**Comment by alrz** [comment]
@diryboy There is even `CS1949` if you try to use `var` in `from`. I'm saying that it'll be more consistent without `var`. see [#4423 comment](https://github.com/dotnet/roslyn/issues/4423#issuecomment-164507469).

**Pull request closed without merging**
