### PR TITLE
Removes Bing search link from diagnostic data

### PR DESCRIPTION
**Pull request by tmat**
Removes Bing search link. All our first party analyzers and almost all the well-known and maintained third party analyzers specify help links (see https://github.com/dotnet/roslyn-analyzers/issues/2991).
We now require analyzers to set HelpLink on their diagnostics if they want F1 to work in Error List.

Currently `DiagnosticDescriptor` does not validate that the string passed to HelpLink is valid HTTP/HTTPS URI, but we only want to display the link if it is. Filed https://github.com/dotnet/roslyn/issues/59205 to consider changing that so that we don't need to validate the URI each time we read HelpLink from diagnostic or its descriptor.

Validated that F1 still works for compiler and analyzer produced diagnostics.

Fixes https://github.com/dotnet/roslyn/issues/39415

### CODE REVIEW

**Comment by 333fred** [comment]
Please consider updating the title and description so I know what I'm reviewing :)

**Review by sandyarmstrong — APPROVED** [review]
Cocoa changes look good.

**Review by 333fred — APPROVED** [review]
Compiler change LGTM

**Review by Youssef1313 — COMMENTED** [review]
I think not all analyzers in roslyn-analyzers repo have help links associated (specifically some RSxxxx analyzers)

**Review by jmarolf — APPROVED** [review]

**Comment by tmat** [comment]
@Youssef1313 Could you please file an issue in roslyn-analyzers repo pointing out the specific analyzers that need to be fixed? Thanks!

**Comment by Youssef1313** [comment]
@tmat There is already an issue https://github.com/dotnet/roslyn-analyzers/issues/4425#issuecomment-725538184.

**Comment by tmat** [comment]
@Youssef1313 Perfect. Thanks!

**Pull request merged**
