### PR TITLE
removed semantic version tracking code which recently caused some iss…

### PR DESCRIPTION
**Pull request by heejaechang**
…ue on RPS test. **this code is already removed from master (15.5)**

**Customer scenario**

VS uses more memory while closing solution.

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/_workitems?id=472556&_a=edit

**Workarounds, if any**

no workaround

**Risk**

this service has been disabled for long time, so basically dead code. we should have removed it earlier.

**Performance impact**

it should fix the RPS regression.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

the tracking service tries to save data to persistent storage which we didn't used to do and shouldn't.

**How was the bug found?**

RPS test.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @dotnet/roslyn-ide can you take a look? @MattGertz already approved this for 15.4

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure for 15.4, which branch I should use? dev15.4.x or dev15.4 ?

**Comment by heejaechang** [comment]
get I can code review?

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure when will this change binary insert to d15prerel for dev15.4? @jinujoseph do you know?

**Comment by jinujoseph** [comment]
not sure @jasonmalinowski  ?

**Comment by heejaechang** [comment]
signed bit - https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=903557&_a=summary

**Comment by heejaechang** [comment]
signed bit published to Roslyn\Roslyn-Signed\dev15.4.x\Release\20170803.5

**Pull request merged**
