### PR TITLE
Revert "Make solution options global"

### PR DESCRIPTION
**Pull request by RikkiGibson**
#59168 is suspected of introducing RPS regressions.

Last known good: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379782
First known bad: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379787
Revert validation: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379865

Regressed counters:

- BuildInfoVS64.Test - RegressedBeyondThreshold / 0001.BuildInfo / Build_Ngen_InvalidAssemblyCount / Regressed: 3.00 Count (50.00%)
- WebToolsVS64.Debugging - RegressedBeyondThreshold / 0300.Stop Debugging / VM_AdjustedImagesInMemory_Total_devenv / Regressed: 3.80 Count (0.75%)
- WebToolsVS64.SolutionManagement - RegressedBeyondThreshold / 0100.Open Solution / IO_AdjustedFileReads_devenv / Regressed: 35.40 Count (9.41%)
- WebToolsVS64.SolutionManagement - RegressedBeyondThreshold / 0100.Open Solution / RefSet_Image_Delta_devenv / Regressed: 5296128.00 Bytes (3.81%)
- WebToolsVS64.SolutionManagement - RegressedBeyondThreshold / 0300.Close Solution / VM_AdjustedImagesInMemory_Total_devenv / Regressed: 4.00 Count (1.01%)
- WebToolsVS64.TypingInRazorView - RegressedBeyondThreshold / 0100.Typing in Razor View / VM_AdjustedImagesInMemory_Total_devenv / Regressed: 4.60 Count (1.09%)

Please advise whether the failures are plausibly connected with this PR, and if so, whether we should revert, or take a follow-up PR to fix, or seek an exception. @genlu @tmat @dibarbet.

### CODE REVIEW

**Comment by genlu** [comment]
> BuildInfoVS64.Test - RegressedBeyondThreshold / 0001.BuildInfo / Build_Ngen_InvalidAssemblyCount / Regressed: 3.00 Count (50.00%)

The ngen error is definitely caused by this change:

> 02/14/2022 10:44:44.177 [4060]: 1>Warning: System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.ExternalAccess.Razor.IRazorDocumentExcerptService' from assembly 'Microsoft.CodeAnalysis.ExternalAccess.Razor, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. while resolving 0x200000d - Microsoft.CodeAnalysis.Razor.DocumentExcerptServiceBase.

**Comment by genlu** [comment]
Those assembly load regression seem to be caused by ProjectSystem reporting erros. For example:

```
Name
 Image Load wer.dll (C:\Windows\System32\)
+ ntoskrnl!?
 + ntdll!NtMapViewOfSection
  + ntdll!LdrpMinimalMapModule
   + ntdll!LdrpMapDllWithSectionHandle
    + ntdll!LdrpMapDllNtFileName
     + ntdll!LdrpMapDllSearchPath
      + ntdll!LdrpProcessWork
       + ntdll!LdrpLoadDllInternal
        + ntdll!LdrpLoadDll
         + ntdll!LdrLoadDll
          + kernelbase!LoadLibraryExW
           + clr!CLRLoadLibraryExWorker
            + clr!CLRLoadLibraryEx
             + clr!LocalLoadLibraryHelper
              + clr!??NDirect::LoadLibraryModule
               + clr!NDirect::NDirectLink
                + clr!NDirect::GetStubForILStub
                 + clr!GetStubForInteropMethod
                  + clr!??MethodDesc::DoPrestub
                   + clr!PreStubWorker
                    + clr!ThePreStub
                     + microsoft.visualstudio.projectsystem.implementation.ni!HResult.Verify
                      + microsoft.visualstudio.projectsystem.implementation.ni!WatsonErrorReport.Prepare
                       + microsoft.visualstudio.projectsystem.implementation.ni!WatsonErrorReport.CreatePreparedNonFatalReport
                        + microsoft.visualstudio.projectsystem.implementation.ni!ProjectErrorReporting.SubmitErrorReport
                         + microsoft.visualstudio.projectsystem.implementation.ni!Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting+<>c__DisplayClass10_0.<SubmitErrorReport>b__1(System.Exception)
                          + guardmethodassembly!GuardMethodClass.GuardMethod(class System.Func`1,class System.Func`2,class System.Func`2)
                           + clr!ExceptionTracker::CallHandler
                            + clr!ExceptionTracker::CallFilterFunclet
                             + clr!ExceptionTracker::ProcessManagedCallFrame
                              + clr!ExceptionTracker::ProcessOSExceptionNotification
                               + clr!ProcessCLRException
                                + ntdll!RtlpExecuteHandlerForException
                                 + ntdll!RtlDispatchException
                                  + ntdll!RtlRaiseException
                                   + kernelbase!RaiseException
                                    + clr!RaiseTheExceptionInternalOnly
                                     + clr!IL_Throw
                                      + mscorlib.ni!ExceptionDispatchInfo.Throw
                                       + microsoft.visualstudio.projectsystem.ni!CommonProjectSystemTools.Rethrow
                                        + microsoft.visualstudio.projectsystem.implementation.ni!Microsoft.VisualStudio.ProjectSystem.ExceptionFilter+<>c__DisplayClass2_0.<Guard>g__Action|0()
                                         + guardmethodassembly!GuardMethodClass.GuardMethod(class System.Func`1,class System.Func`2,class System.Func`2)
                                          + microsoft.visualstudio.projectsystem.implementation.ni!Microsoft.VisualStudio.ProjectSystem.Designers.ProjectFaultHandlerService+<HandleErrorAsync>d__45.MoveNext()
                                           + microsoft.visualstudio.projectsystem.implementation.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[Microsoft.VisualStudio.ProjectSystem.Designers.ProjectFaultHandlerService+<HandleErrorAsync>d__45](<HandleErrorAsync>d__45 ByRef)
                                            + microsoft.visualstudio.projectsystem.implementation.ni!ProjectFaultHandlerService.HandleErrorAsync
                                             + microsoft.visualstudio.projectsystem.managed.ni!FaultExtensions.ReportFaultAsync
                                              + microsoft.visualstudio.projectsystem.managed.ni!Microsoft.VisualStudio.ProjectSystem.FaultExtensions+<>c__DisplayClass6_0.<RegisterFaultHandlerAsync>b__0(System.Threading.Tasks.Task)
```

And by checking the exceptions thrown in the trace around the time of the call stack above, it's also caused by the razor ExternalAccess change:

image

**Comment by tmat** [comment]
We should instead insert new Razor build. I thought it's already inserted but apparently not.

**Review by tmat — CHANGES_REQUESTED** [review]
Let's make sure Razor is inserted instead of reverting this.

**Comment by tmat** [comment]
Razor insertion is now in progress.

**Comment by RikkiGibson** [comment]
Could you please include a link to it?

**Comment by dibarbet** [comment]
> Could you please include a link to it?

@RikkiGibson this is the release that is generating the insertion, unfortunately it doesn't have your improvements and it has to clone VS so it may take a few :)
https://dev.azure.com/dnceng/internal/_releaseProgress?releaseId=40624&_a=release-environment-logs&environmentId=121442

**Comment by dibarbet** [comment]
PR link - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/379899?_a=overview

**Comment by RikkiGibson** [comment]
We're now dual inserting in https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379897

**Comment by RikkiGibson** [comment]
> We're now dual inserting in https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379897

RPS results are in for this. Unfortunately, we're still regressing a counter:

- BuildInfoVS64.Test - RegressedBeyondThreshold / 0001.BuildInfo / Build_Ngen_InvalidAssemblyCount / Regressed: 1.00 Count (16.67%)

cc @genlu @tmat

**Review by tmat — APPROVED** [review]

**Comment by tmat** [comment]
@NTaylorMullen There seems to be version mismatch with Razor assemblies. Missing binding redirect?

```
02/14/2022 23:51:57.434 [5464]: Failed to load dependency Microsoft.AspNetCore.Razor.Language of assembly Microsoft.WebTools.Languages.Razor.Core, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a because of the following error : The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
02/14/2022 23:51:57.637 [5464]: 1>    Compiling assembly C:\VisualStudio\Common7\IDE\Extensions\Microsoft\Web Tools\Languages\Razor\v4.0\Microsoft.WebTools.Languages.Razor.Core.dll (CLR v4.0.30319) ...
02/14/2022 23:51:57.934 [5464]: 3>    Compiling assembly C:\VisualStudio\Common7\IDE\Extensions\ukdqr4lk.ss4\MSTestv2IntelliTestExtension.dll (CLR v4.0.30319) ...
02/14/2022 23:51:58.028 [5464]: 1>Warning: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=6.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.Language, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---02/14/2022 23:51:58.028 [5464]: 1> while resolving 0x1000031 - Microsoft.AspNetCore.Razor.Language.RazorCodeDocument.

```

**Comment by tmat** [comment]
We should insert Razor separately and make sure it's good.

**Pull request merged**
