### PR TITLE
Semantic snippets - `enum` snippet

### PR DESCRIPTION
**Pull request by DoctorKrolic**

### CODE REVIEW

**Comment by DoctorKrolic** [comment]
@akhera99 Can you please take a look at this PR? It is relatively simple given that all abstractions were basically already there. Just added a new type snippet provider and changed `TypeDeclarationSyntax` to `BaseTypeDeclarationSyntax` in several places

**Review by akhera99 — APPROVED** [review]
Looks great, thanks for the contribution! 
Can you add me as a reviewer in the future for all snippet related PRs?

**Comment by DoctorKrolic** [comment]
@akhera99 Can you please restart failed CI again. Don't restart the whole thing, only pipelines that failed. The likelihood of success in such case is a lot higher

**Pull request merged**
