### PR TITLE
Update to NuGet3

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by agocke** [comment]
@jaredpar @jasonmalinowski

**Comment by agocke** [comment]
retest this please

**Comment by tannergooding** [comment]
@agocke, don't forget about the nuget exe in src\Samples\.nuget.

**Comment by jasonmalinowski** [comment]
I assume when @tannergooding says "don't forget about that nuget.exe" he means "don't forget to delete it."

**Comment by tannergooding** [comment]
@jasonmalinowski, delete it and make sure all references to it are updated it :)

**Pull request closed without merging**
