### PR TITLE
Avoid leaking documents if an exception is thrown in AddDocument

### LINKED ISSUE #22723: ContainedDocument can leak if exceptions are thrown
Underlying issue:

During the call to `CreateContainedLanguage`, a call is made to `AbstractProject.AddDocument`. This call adds the `ContainedDocument` to two sets. If the key already exists in the second set, an exception is thrown and the caller will lose the ability to dispose of the `IVsContainedLanguage` instance, leaving a strong reference to the `ContainedDocument` permanently in the first set.

Heap dumps where this bug manifests show large numbers of `ContainedDocument` instances leaking. One case has 343,931 instances.

The offending code block is the following:

https://github.com/dotnet/roslyn/blob/a4239cbcadcf8a1f1e8485e430a7ac190b78fc85/src/VisualStudio/Core/Def/Implementation/ProjectSystem/AbstractProject.cs#L1028-L1032

💭 It should be possible to fix this by simply reversing the two calls to `Add`. Since `ContainedDocument` always uses a new GUID for each instance, the addition using that GUID should never fail. However, a safer fix would ensure that the pair of additions is atomic, regardless of input.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #22723

**Customer scenario**

It's unknown exactly how a customer enters this scenario. The stack trace was found via an exception instance in a heap dump during investigation of a known `ContainedDocument` leak. This change mitigates a memory leak resulting from improper use of a Roslyn API. The offending call sequence has not yet been identified, and will continue observing an `ArgumentException` at the same location it was previously.

**Bugs this fixes:**

#22723
vso : https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20IDE/_queries/edit/512706 

**Workarounds, if any**

None.

**Risk**

Low. This code does not change the exception which was getting thrown, or the location where it was getting thrown previously. Its only change is preventing the accidental GC rooting of a `ContainedDocument` instance during the error handling process.

**Performance impact**

Improves performance for impacted users by avoiding running out of memory.

**Is this a regression from a previous update?**

Unknown; the analysis tool which identified this bug only runs on heap dumps from 15.3.

**Root cause analysis:**

See "how was the bug found".

**How was the bug found?**

Found via automated analysis of heap dumps using tools developed for the identification of #22650.

**Test documentation updated?**

N/A

### CODE REVIEW

**Comment by sharwell** [comment]
@jasonmalinowski It's unknown whether this change prevents the creation of `EventHandler<SnapshotSpanEventArgs>` which showed up so prominently in the heap dump analysis. Its target is the known GC root for `ContainedDocument`.

**Comment by jasonmalinowski** [comment]
We have a little unit test harness that should let you test this I think.

**Comment by jasonmalinowski** [comment]
I must admit the overall policy here worries me: we have never really made guarantees in this part of Roslyn that we're safe to resume from exceptions. This might not leak here but do we know if all callers except the exception either and will resume safely?

**Comment by sharwell** [comment]
This change makes me uncomfortable too. Did Todd ever find out why this is happening in the first place (repro case)?

**Comment by jasonmalinowski** [comment]
@sharwell As best I know, no. We've already that retrying this was bad because of this leak...I'd prefer they didn't retry and fixed their problem. I'll of course concede that figuring out the root cause might be difficult too and this might be the best approach we've got, but I'm not sure we've done that due diligence yet.

**Comment by natidea** [comment]
Approved to merge via [512706](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/512706)

**Pull request merged**
