### PR TITLE
Infer delegate types with -langversion:preview only

### PR DESCRIPTION
**Pull request by cston**
See https://github.com/dotnet/roslyn/pull/52448.
Test plan: https://github.com/dotnet/roslyn/issues/52192

### CODE REVIEW

**Comment by jcouv** [comment]
>             if (delegateOrFuncPtrType.SpecialType != SpecialType.System_Delegate)

Do we need to adjust this one too?

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1189 in 366686a. [](commit_id = 366686a592b0ec4c32bbdc20cd5c95e5d4795918, deletion_comment = False)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3) with one question

**Comment by cston** [comment]
>             if (delegateOrFuncPtrType.SpecialType != SpecialType.System_Delegate)

> Do we need to adjust this one too?

I don't believe so, since this method should only be called in cases where `Conversions.GetMethodGroupDelegateConversion()` classified the conversion as a method group conversion, and that method checks if the feature is enabled.

---
In reply to: [834049365](https://github.com/dotnet/roslyn/pull/53241#issuecomment-834049365) [](http://example.com/codeflow?ancestors=834049365,834049365)

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_Conversions.cs:1189 in 366686a. [](commit_id = 366686a592b0ec4c32bbdc20cd5c95e5d4795918, deletion_comment = False)

**Comment by AlekseyTs** [comment]
> Infer delegate types with -langversion:preview only

Is this a permanent or a temporary change? It feels like it violates the general principle that language version doesn't affect result of semantic analysis, apart from diagnostics.

**Comment by cston** [comment]
> Is this a permanent or a temporary change? It feels like it violates the general principle that language version doesn't affect result of semantic analysis, apart from diagnostics.

This change is temporary and intended for the initial preview only.

**Comment by jcouv** [comment]
> This change is temporary and intended for early previews only.

Btw, I added a note to test plan as a reminder to revert this change (assuming it gets merged).

**Comment by cston** [comment]
@dotnet/roslyn-compiler for a second review of a temporary change for early previews only.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 3)

**Pull request merged**
