### PR TITLE
Throw BadImageFormatException decoding TypeRef with resolution scope with nil ModuleRef or TypeRef

### LINKED ISSUE #11795: Throw BadImageFormatException decoding TypeRef with resolution scope with nil ModuleRef or TypeRef
See comment in #11772.

### PR DESCRIPTION
**Pull request by cston**
See comment in #11772. Fixes #11795.

### CODE REVIEW

**Comment by cston** [comment]
@tmat, @AlekseyTs, @dotnet/roslyn-compiler please review.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by cston** [comment]
@dotnet-bot test windows_debug_unit32_prtest please

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
