### PR TITLE
Clean up the MSBuild code

### PR DESCRIPTION
**Pull request by jaredpar**
Fix a couple of issues:

- Use nameof where appropriate
- Accessibility should come before override

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @VSadov, @agocke, @khyperia

**Comment by jaredpar** [comment]
The transform for anyone who is interested 

https://gist.github.com/jaredpar/4b2467622cd37fc1f654

**Comment by khyperia** [comment]
LGTM.

The license comments being in the diff with no visible changes is a bit curious. Is it a UTF-BOM change or something weird like that?

**Comment by jaredpar** [comment]
@khyperia yeah it's likely a BOM issue.

**Comment by agocke** [comment]
:+1: Nice

**Pull request merged**
