### PR TITLE
Port compiler generator tools to run on CoreCLR 

### LINKED ISSUE #7136: Make build tools run on CoreCLR
There are a number of managed tools used during our build that need to be transitioned to CoreCLR.   That includes both:

- Targeting a portable profile 
- Change build on all OS to use CoreCLR

These tools include:

- BoundTreeGenerator
- CSharpErrorFactsGenerator
- CSharpSyntaxGenerator
- VBErrorFactsGenerator
- VBSyntaxGenerator

### PR DESCRIPTION
**Pull request by agocke**
Ports the compiler generator tools (syntax generator, bound tree
generator, et al.) to .NET core and runs the exes on CoreCLR instead of
the desktop framework.

Fixes #7136

### CODE REVIEW

**Comment by agocke** [comment]
This should port everything in our build to CoreCLR (resolving #7139)

**Comment by agocke** [comment]
@davkean I thought we got rid of the NuGet zip for ETA?

**Comment by jaredpar** [comment]
@agocke ETA is doing real restore.  It uses solutions checked into Closed though.  You've only made changes to Open here hence the restore is incomplete.  We should change ETA to restore the Open solution as well to avoid this problem.

**Comment by davkean** [comment]
Closed solution is supposed to be superset of Open.

**Comment by jaredpar** [comment]
@davkean true but it's only a superset after we've updated it.  This change can't update Closed until it's merged.

**Comment by davkean** [comment]
Hmm, actually not sure how this is possible.

We build only the Closed solution, if the project isn't in that - how do we get build errors?

**Comment by agocke** [comment]
@davkean It looks like it's building my new project -- so it must be building one of the Open solutions

**Comment by davkean** [comment]
MSBuild is probably building dependent projects regardless of whether they are included in the Solution.

**Comment by jaredpar** [comment]
The change does two actions relevant here:

1. Adds a new project to the open solution
2. Adds references to that project to existing projects

The existing projects are compiled as a part of the old solution hence the new project is in turn built.  Because restore doesn't follow that reference though restore doesn't happen.  Hence we are building the project but not restoring it.

**Comment by davkean** [comment]
Long term, we should split the solutions into Open and Closed; then restore both.

**Comment by agocke** [comment]
I see. @davkean What do you want me to do here? Do my branch trick to validate ETA on CI, or just run it locally and trust me that it passes?

**Comment by jaredpar** [comment]
For the moment we should change ETA to restore the Open solution as well.  It minimizes the friction for cross cutting changes.

**Comment by agocke** [comment]
Right, I forgot it will resync. I'll make the change in closed.

**Comment by agocke** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5127/
// Retest reason: Fixed issue on Closed side.

**Comment by jaredpar** [comment]
:+1:

**Comment by alrz** [comment]
@agock CoreRun.exe and other executables are 64bit, is there any way to build Roslyn using a 32bit machine?

**Comment by alrz** [comment]
@agocke CoreRun.exe and other executables are 64bit, is there any way to build Roslyn using a 32bit machine?

**Pull request merged**
