### PR TITLE
Renamed roslyn servicehub service names

### PR DESCRIPTION
**Pull request by heejaechang**
it is asked from service hub team so that they can more easily identify which team owns which service.

### Customer scenario

this is not user visible change

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/22970

### Workarounds, if any

no workaround

### Risk

no risk

### Performance impact

no performance impact

### Is this a regression from a previous update?

N/A

### Root cause analysis

our service hub service used too general term such as remote host service, snapshot service and etc which made it hard for others to find out which team owns the service.

### How was the bug found?

dogfooding

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph can you take a look?

**Comment by sharwell** [comment]
> no risk

This is not correct. Missing a reference somewhere could result in a failure to create and/or communicate with the OOP host.

Is the full matrix covered by automated testing (e.g. do tests cover execution using both 32- and 64-bit OOP hosts)?

**Comment by sharwell** [comment]
@heejaechang Can you give an overview of how these changes can be observed? For example:

* Where do the renamed files go in a Visual Studio installation?
* Do the names of any child processes change?
* Can this cause a problem for an <kbd>F5</kbd> experience for Roslyn developers?
* Any other observable differences?

**Comment by heejaechang** [comment]
retest microbuild_prtest please

**Comment by heejaechang** [comment]
DEVDIV insertion tool failed.

**Comment by heejaechang** [comment]
@sharwell 

* Where do the renamed files go in a Visual Studio installation?
> this is servicehub service definition file. it will go where our VS.Setup.vsix puts Roslyn bits.

* Do the names of any child processes change?
> No

* Can this cause a problem for an F5 experience for Roslyn developers?
> No

* Any other observable differences?
> No

like I said, there is no user visible changes. except the first, those are user visible changes.

**Comment by heejaechang** [comment]
@jinujoseph @AArnott do you want it to be 15.6? or it is fine to be 15.7?

**Comment by heejaechang** [comment]
turns out microbuild_prtest failure was valid one. the devdiv insertion tool had whitelist of files and that had old file names. updated devdiv insertion tool to new names.

**Comment by jinujoseph** [comment]
We are technically in escrow for 15.6 , so i am ok to take this for 15.7 , unless @AArnott  has a strong reason to take for 15.6

**Comment by AArnott** [comment]
15.7 is fine. It's a long-term concern that your service names were not sufficiently unique as to both be identified as roslyn and avoid collisions with someone else's similarly simply named service.

**Comment by heejaechang** [comment]
moving it to 15.7.x

**Comment by jinujoseph** [comment]
@MattGertz  for 15.7 approval

**Comment by MattGertz** [comment]
Approved.  Note that @Pilchie can approve these too.

**Pull request merged**
