### PR TITLE
Don't recommend type keywords in cref type args

### LINKED ISSUE #1468: <see> IntelliSense offers keyword types for generic parameters, producing warnings
Source:

```
/// <see cref="Func{bo"/>
```

IntelliSense will show `bool`, which will produce the following two warnings when selected:

 1. CS1658	Type parameter declaration must be an identifier not a type. See also error CS0081.	
 2. CS1584	XML comment has syntactically incorrect cref attribute 'Action{bool}'	

On a related note, why does this syntax produce an error when referencing types, but work fine in types in method arguments?

### PR DESCRIPTION
**Pull request by rchande**
Fixes #1468.

Could you review? @basoundr @balajikris @davkean @dpoeschl @jmarolf @jasonmalinowski @Pilchie

### CODE REVIEW

**Comment by balajikris** [comment]
:+1:  for the change, is this C# only?

**Comment by Pilchie** [comment]
Ditto @balajikris :smile:

**Comment by rchande** [comment]
@Pilchie @balajikris see #2383

**Comment by Pilchie** [comment]
Ah, right. I didn't make the connection that that handled keyword as well as symbols.

LGTM

**Pull request merged**
