### PR TITLE
Do not qualify member accesses that appear inside attributes.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/26893

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv @dotnet/roslyn-ide @sharwell .  This fixes a high visibility annoyance with "qualify with ```this.```".  This problem is exacerbated because of "code cleanup on format document."

**Comment by CyrusNajmabadi** [comment]
@jcouv I'm not understanding the error i'm getting.  It's:

> error CS0618: 'ConditionalFactAttribute.Skip' is obsolete: 'ConditionalFact should use Reason or AlwaysSkip' [D:\j\workspace\windows_debug---09a07fba\src\Compilers\CSharp\Test\Emit\Microsoft.CodeAnalysis.CSharp.Emit.UnitTests.csproj]

Bu i didn't change anything at the CodeAnalysis level... :-/

**Comment by sharwell** [comment]
:memo: Without having reviewed either pull request yet, I prefer to take #27459 over this one since it was submitted first.

> I'm not understanding the error i'm getting.

Separate issue fixed in #28683.

**Comment by davidwengier** [comment]
This one fixes more scenarios, albeit more specific since it's attributes only. #27459 doesn't work for attributes on parameters for example.

**Comment by sharwell** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
test this please

**Comment by CyrusNajmabadi** [comment]
> 📝 Without having reviewed either pull request yet, I prefer to take #27459 over this one since it was submitted first.

@sharwell this is the more complete fix.  :) We should probably close #27459.  Can you let review this and also let me know what the right branch is for this to go in?

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Wht branch shoudl this PR be targetting? Thanks!

**Comment by jinujoseph** [comment]
master is right

**Comment by CyrusNajmabadi** [comment]
@jinujoseph great.  thanks!

**Comment by CyrusNajmabadi** [comment]
@sharwell can you take a look?  It's a fairly simple PR.  It would be nice to get this in today.

**Comment by CyrusNajmabadi** [comment]
test windows_debug_spanish_unit32_prtest

**Comment by CyrusNajmabadi** [comment]
test windows_release_vs-integration_prtest

**Comment by sharwell** [comment]
> This one fixes more scenarios, albeit more specific since it's attributes only. #27459 doesn't work for attributes on parameters for example.

Thanks for the clarification! I do tend to prefer this pull request since it's easier to understand *why* it works. There are a few more bugs filed for IDE0009; even though we aren't using your fix for this one perhaps you would be interested in helping with those since it's in the same files?

**Comment by CyrusNajmabadi** [comment]
> There are a few more bugs filed for IDE0009; even though we aren't using your fix for this one perhaps you would be interested in helping with those since it's in the same files?

Link me to the relevant issues.  If i have time i'll see what i can do.  Can't make any promises though :)

**Comment by CyrusNajmabadi** [comment]
Merge plz? :)

**Comment by paulomorgado** [comment]
This is still a problem in 15.9.0 Preview 2.0

**Comment by sharwell** [comment]
@paulomorgado Looks like a 16.0 fix

**Comment by paulomorgado** [comment]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers to the resque!

**Pull request merged**
