### PR TITLE
Target net46 in all desktop projects

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
Change in open: https://github.com/dotnet/roslyn-internal/pull/838

**Comment by tmat** [comment]
@dotnet/roslyn

**Comment by tmat** [comment]
ETA test failures expected, the corresponding closed change is required to pass.

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5983/
// Retest reason:

**Comment by tmat** [comment]
retest vsi please

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/roslyn/pull/10638

**Pull request closed without merging**
