### PR TITLE
Show the dependencies node in Solution Explorer

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by jaredpar** [comment]
Should probably let @davkean / @srivatsn sign off on when a good time to merge this is.

**Comment by sharwell** [comment]
Here is the current GC-only impact of this change:

## Current code (commit 05ef4df21d3954fa6d205a4f4eb09fedd66c0187, no dependencies node)

image

## New code (previous commit plus this change)

image

**Comment by sharwell** [comment]
The wall-clock solution load in 15.5 Preview 2 for Roslyn.sln appears to increase by 5.4% as a result of this change. I believe this is low enough to allow the feature to be re-enabled for dogfooding.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Pull request merged**
