### PR TITLE
Set up roslyn to use dynamic windows images

### PR DESCRIPTION
**Pull request by mmitche**
/cc @agocke @jaredpar

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @davkean 

Can you explain a bit how this works?  For example how does this grab the windows image that Roslyn needs.  Curious because wonder how this will expand out when we begin setting up jobs for Dev15 which will require a different image.  

Also how can we expand this out for Linux?

**Comment by mmitche** [comment]
Today you have all your jobs marked for 'windows-roslyn'.  Every 'windows' machine today is marked as both 'windows' and 'windows-roslyn', so they are effectively the same.  The dynamic base image is exactly the same as the 'windows' image.  It was not created from scratch, just a version of the 'windows' image with the startup task added.  The Utilities.setMachineAffinity call sets the label expression on the job passed to it.;  There are two parameters, which are used to look up a label expression in the map in the linked code below.  The OS and the version.  The OS is straightforward: 'Windows_NT'.  'latest-or-auto' is a version label, which corresponds today to the label expression:

'windows || auto-win2012-20160311.1'

https://github.com/dotnet/dotnet-ci/blob/master/jobs/generation/Utilities.groovy#L93

windows corresponds to any machines labeled windows (which is just the normal machines today).  auto-win2012-20160311.1 is the captured base image used for the dynamic pooling.  This basically means that if no windows machines are available, the cloud plugin will start spinning up that azure image.

The process for modifying and upgrading the dynamic images is detailed here:  https://github.com/dotnet/dotnet-ci-internal/blob/master/docs/NODE-AUTO-IMAGE-LIFECYCLE.md.  This process makes it straightforward and non-invasive to change images.  We will be moving away from static VMs except where we can use dynamic VMs, and this process should be used going forward.

**Comment by jaredpar** [comment]
This PR is basically a push and pray commit: there is no way to test this before hand and we just have to push and pray that it doesn't bring our CI down.

Is there a way we can test this before we commit to it (haha)?  Perhaps add a parallel job to validate it works and then switch over when it's verified.

**Comment by davkean** [comment]
Agreed. I'd like us to stage this with parallel jobs. We're currently in the middle of shutting down 1.2 and 2.0, a break in the CI system would be extremely detrimental to our ability to ship.

@jaredpar We should take @mmitche's change and setup parallel jobs - do you have anyone who can work on this in your feature crew.

**Comment by mmitche** [comment]
@davkean @jaredpar I am 99.99% sure this will be fine.  I moved each and every project on the system over to dynamic in a single move on Friday (after testing on another CI project) without issue.  We can also immediately revert if we see issues.

However, we could also check this out by generating the GenPRTest jobs, enabling one or two and verifying.

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by jaredpar** [comment]
@mmitche pretty sure your last comment "t e s t  c i p l e a s e" just broke our Jenkins job entirely.  For whatever reason that command is not safe to use with Roslyn.  Last time we ran it it killed all PR hookup afterwards.  @tannergooding has the understading here.

**Comment by tannergooding** [comment]
Yup. All jobs disabled. Working on fixing it and then will provide context.

**Comment by tannergooding** [comment]
Context: Roslyn puts all of its jobs into the root, rather than a subfolder (blah, blah, legacy reasons, blah, blah, we can update to the new branch model now which doesn't have this issue).

Due to a bug in the generator script, this causes the generator_prtest job to overwrite the actual jobs, rather than creating a separate folder to contain them.

**Comment by tannergooding** [comment]
We should be fixed now.

**Comment by davkean** [comment]
I want parallel jobs for this change - we're literally shutting down right now with some [important bugs](https://github.com/dotnet/roslyn/pulls?q=is%3Aopen+is%3Apr+label%3AStabilization%2FFuture-Stabilization) that we're trying to get through, I don't want any risk to the jobs.

**Pull request merged**
