### PR TITLE
Remove unnecessary projects from Toolset.sln

### PR DESCRIPTION
**Pull request by agocke**
@jaredpar @tmat @jasonmalinowski

### CODE REVIEW

**Comment by agocke** [comment]
@tmat This should heavily reduce the probability that any of your changes will require changing Toolset.sln.

**Comment by jasonmalinowski** [comment]
Really dumb question: what is Toolset.sln supposed to contain?

**Comment by jaredpar** [comment]
@jasonmalinowski just the compilers (aka the Roslyn toolset).

**Comment by jasonmalinowski** [comment]
OK, some removals totally make sense (like Workspace and Features!). You don't want tests though?

**Comment by agocke** [comment]
@jasonmalinowski Toolset builds the compilers that we then build and run tests on.

**Comment by jaredpar** [comment]
@jasonmalinowski the PR is the test.  This is the solution we build in order to create the csc, vbc and VBCSCompiler binaries.  After we build these we save them off to the side, delete all the build artifacts and do the full CI run using these as the compiler.  So if the PR succeeds then by definition it was correct :smile;

**Comment by jasonmalinowski** [comment]
Ah, makes sense. :+1:

**Comment by agocke** [comment]
@jaredpar Is that a :+1: ?

**Comment by jaredpar** [comment]
Yep :shipit:

**Pull request merged**
