### PR TITLE
Remove CheckServerState

### PR DESCRIPTION
**Pull request by ryanbrandenburg**
- We wanted to "do the right thing" by verifying the LSP specification requirements WRT the initialized method, but our implementation was flawed. For now we're going to disable the check and come back to do the proper fix later. The check should be a no-op for well-behaved client anyway (and we've already confirmed that VS and VSCode are well-behaved.

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]
> For now we're going to disable the check and come back to do the proper fix later. 

Can you create a tracking bug as well?  It is important that we add back the invariant checking because while the client appears to be working correctly now, there have definitely been bugs here in the past.

**Comment by ryanbrandenburg** [comment]
https://github.com/dotnet/razor/issues/8311

**Review by davidwengier — APPROVED** [review]

**Comment by ryanbrandenburg** [comment]
@dibarbet do you recognize the test failures there? They look unrelated to me.

**Comment by ryanbrandenburg** [comment]
It seems like (unrelated to this PR) SDK URLs were broken for a time, but they seem to be back online now.

**Pull request merged**
