### PR TITLE
Revert "Disable flakey integration tests"

### LINKED ISSUE #62280: Disabling Quick Info integration tests due to CI flakeyness.
The following tests are commonly failing: https://dev.azure.com/dnceng/public/_build/results?buildId=1854838&view=logs&j=cd35c29e-b8fa-564f-16e0-bece8461e2f7&t=63994ce8-351b-522b-bb58-0316934d7b0d

  Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpQuickInfo.SectionOrdering: Fail
  Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpQuickInfo.QuickInfo_Documentation: Fail
  Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpQuickInfo.International: Fail
  Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicQuickInfo.International: Fail

### PR DESCRIPTION
**Pull request by sharwell**
These tests need to be ported to the new integration test framework, but are not showing up as significantly flaky currently.

Closes #62280
Reverts dotnet/roslyn#62282

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
I don't understand. What changed?  These years caused many failures for me and others for several days.

**Comment by sharwell** [comment]
Nothing changed. The failure was just a misinterpretation of the test output. We could fix the output messaging to avoid this confusion, but the new test harness already fixed that so the problem is going away as the tests are migrated.

**Comment by davidwengier** [comment]
Could you give examples of what the logs were, and how they were misinterpreted? I would have thought if the leg was green, and not blocking the PR, then nobody would look at the logs to misinterpret them, and if the leg was red and blocking the PR, then the tests should be disabled.

**Comment by CyrusNajmabadi** [comment]
i agree with david.  Also, as i mentioned, i was genuinely blocked *numerous* times by the flakeyness.  Moving these tests to be disabled meant my PRs starting going in.  

> but the new test harness already fixed that so the problem is going away as the tests are migrated.

I'm ok with a PR that migrates these and *then* reenables them.  I'm not ok with them being reenabled but not migrated, as i'm going to end up back in the situation where i was running each PR of mine at least 2-3 times to get them to go through.

**Comment by arkalyanms** [comment]
Can this PR be revived now?

**Comment by sharwell** [comment]
Superseded by #65725

**Pull request closed without merging**
