### PR TITLE
Add missing editor configuration properties

### PR DESCRIPTION
**Pull request by sharwell**
I noticed some differences between my local settings and the code in the repository, only to find that the **.editorconfig** file we're using was incomplete. I added the missing code style properties for uniform behavior in cases where users have customized settings in Tools &rarr; Options...

### CODE REVIEW

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@dotnet/roslyn-infrastructure This doesn't actually change the settings we're using, it merely sets them in .editorconfig instead of relying on individual settings on the contributors' machines.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@kuhlenh Can you review this against the PR you've been working on?

**Comment by kuhlenh** [comment]
@sharwell will get to this soon. FYI we're axing some of those formatting rules because they aren't changed from default values

**Comment by CyrusNajmabadi** [comment]
Oooh, tell me more.  Which ones are getting the ax? :)

**Comment by sharwell** [comment]
@dotnet/roslyn-infrastructure This needs to be merged. Reviewers are commenting on deviations in code style for formatting options that are not defined by the project settings, which by definition means that the style choice is at the discretion of individual developers.

**Pull request merged**
