### PR TITLE
Add `Conversion.IsSpan` public API

### PR DESCRIPTION
**Pull request by jjonescz**
Test plan: https://github.com/dotnet/roslyn/issues/73445
Resolves https://github.com/dotnet/roslyn/issues/74738.

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Comment by cston** [comment]
Has the public API change been approved?

**Comment by jjonescz** [comment]
> Has the public API change been approved?

Not yet, I'm hoping this PR can serve as the ticket for the approval process.

**Comment by 333fred** [comment]
> > Has the public API change been approved?
> 
> Not yet, I'm hoping this PR can serve as the ticket for the approval process.

Sorry, but please follow the process outlined in https://github.com/dotnet/roslyn/blob/main/docs/contributing/API%20Review%20Process.md.

**Comment by jjonescz** [comment]
@dotnet/roslyn-compiler for a second review, thanks

**Review by 333fred — APPROVED** [review]

**Pull request merged**
