### PR TITLE
Use the right public key for the InternalsVisibleTo to Monodevelop

### PR DESCRIPTION
**Pull request by Pilchie**
A while back, we added internals visible to for Monodevelop.  Unfortunately, using our infrastructure, that just did the MS public key, which isn't what Monodevelop uses.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @mhutch @mkrueger @dotnet/roslyn-ide for review, and @MattGertz for approval.

@mkrueger or @mhutch can we get some verification that this work for you guys?

**Comment by mhutch** [comment]
What key are you using here? We don't currently sign any of our assemblies - will need to discuss doing so with the team.

**Comment by Pilchie** [comment]
The one that @mkrueger asked me to in email this morning 😉

**Comment by Pilchie** [comment]
Updated to target master and use a new key.  @mhutch and @mkrueger - can you take a look and verify it works for you?

**Comment by mhutch** [comment]
It looks good to me.

It's going to get us a little bit of time to get PublicSign working and enable signing on all the MD assemblies so I can't test just yet.

**Comment by Pilchie** [comment]
Pinging @MattGertz for approval for RC.3.  Can we merge this so that we have myget packages with this for the VS for Mac folks to try out?

**Comment by MattGertz** [comment]
Approved for RC.3.

**Pull request merged**
