### PR TITLE
Add support for custom modifiers referencing generic types.

### LINKED ISSUE #5725: Compilers are unable to consume signatures with custom modifiers referencing constructed types.
Here is an example of a method signature like this 
```
.method public hidebysig specialname instance class [mscorlib]System.ValueType modopt(valuetype [mscorlib]System.Nullable`1<bool>) modopt([mscorlib]System.Runtime.CompilerServices.IsBoxed) 
        get_OffScreenTransparentBackground() cil managed
```

The modifier that is causing the problem is ```modopt(valuetype [mscorlib]System.Nullable`1<bool>)```. Strictly speaking, it violates ECMA-335 specification. In particular, Section II.23.2.7 says:
```
The CMOD_OPT or CMOD_REQD is followed by a metadata token that indexes a row in the TypeDef table or
the TypeRef table.
```
However, in order to refer to a ```System.Nullable`1<bool>``` type, a row in the TypeSpec table should be used.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #5725.

@gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Ping. @gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

**Comment by AlekseyTs** [comment]
Ping. @gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @gafter, @jaredpar, @agocke, @TyOverby Please review, need a second sign-off.

**Comment by gafter** [comment]
LGTM

**Pull request merged**
