### PR TITLE
Fix usernames in area-owners.md [features/dont-build-docs-changes]

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
@RikkiGibson @jaredpar

**Review by RikkiGibson — DISMISSED** [review]

**Comment by RikkiGibson** [comment]
I see the following

image

Basically, it seems the proper status is now reported to GitHub and we get a green merge button without having to run the CI jobs 😊 This should mean that we can merge the config change from this feature branch over to main and actually skip running CI on doc changes from now on. cc @jmarolf

**Comment by RikkiGibson** [comment]
@Youssef1313 feel free to reopen #58712 targeting main and we'll consider the "feature" completed 😉

**Comment by RikkiGibson** [comment]
Sorry, one more thing @Youssef1313. Could you please try pushing a non-doc change to this PR and let's verify that the CI gets run as expected.

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
(signing off but don't treat my signoff as meaning anything to the fight we're having with CI)

**Comment by RikkiGibson** [comment]
We opened this PR to verify behavior of #58723. Now that we've merged that, we don't need this PR any more.

**Pull request closed without merging**
