### PR TITLE
Add ISymUnmanagedBinder interfaces to Microsoft.DiaSymReader

### PR DESCRIPTION
**Pull request by tmat**
/cc @KevinH-MS @amcasey

### CODE REVIEW

**Comment by tmat** [comment]
@pnelsonmsft

**Comment by tmat** [comment]
FYI @gregg-miskelly

**Comment by amcasey** [comment]
:+1:

**Comment by pnelsonmsft** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
LGTM

**Pull request merged**
