### PR TITLE
added internal visible to to ETA.

### PR DESCRIPTION
**Pull request by heejaechang**
preparing remote host test options for ETA testing.

### CODE REVIEW

**Comment by heejaechang** [comment]
code review? @mavasani @jinujoseph @srivatsn @333fred @tmat

**Comment by CyrusNajmabadi** [comment]
I believe ETA will be going away.  We're moving all our integration tests out of it and making VS integration tests instead.  So do we need this?

**Comment by heejaechang** [comment]
@CyrusNajmabadi ah, didn't know about it.

**Comment by heejaechang** [comment]
@jasonmalinowski @KirillOsenkov any reason decided to move away with ETA? ETA let us to maintain layering right I believe... do we go instead MSBuildWorkspace path?

**Comment by tannergooding** [comment]
@heejaechang, because we can't open source it and the community can't run or write integration tests using it.

**Comment by CyrusNajmabadi** [comment]
We can't open source ETA, and customers can't use it.  It also means all Roslyn devs need an open/closed enlistment which is a royal PITA.

**Comment by heejaechang** [comment]
I see. that's unfortunate. so I guess that means VSI is already open sourced?

**Comment by CyrusNajmabadi** [comment]
Yes.  All the VS integration tests are happening in Open.  Several IDE devs are working on porting all the ETA/Tao integration tests over to being the new system (which Dustin wrote).

**Pull request closed without merging**
