### PR TITLE
disable CSharpIsAndCastCheckWithoutNameDiagnosticAnalyzer for preview 1

### PR DESCRIPTION
**Pull request by heejaechang**
**Customer scenario**

VS is unresponsive and hard to use

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/504602 (one of issue from this feedback 
https://devdiv.visualstudio.com/DevDiv/_workitems?id=504089&_a=edit&triage=true)

**Workarounds, if any**

no workaround

**Risk**

none

**Performance impact**

we are disabling an analyzer which we identified as costly one. this should improve perf.

**Is this a regression from a previous update?**

No

**Root cause analysis:**

the analyzer is calling one of expensive check repeatedly multiple times.

**How was the bug found?**

User feedback and dogfooding.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @dotnet/roslyn-ide can I get some code review?

**Comment by heejaechang** [comment]
@jinujoseph @natidea added ask mode template.

**Comment by jinujoseph** [comment]
@Pilchie / @MattGertz

**Comment by natidea** [comment]
Approved to merge via [504602](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/504602)

**Pull request merged**
