### PR TITLE
Add restore.cmd to Update 1

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Does what it says. This is just a cherry-pick of the commits in master.

### CODE REVIEW

**Comment by davkean** [comment]
eta failure is expected for update-1

**Comment by jasonmalinowski** [comment]
I guess I technically lied: the first change also updated cibuild.cmd, but I didn't bring that along since the versions have heavily diverged....but if people expect to use cibuild.sh locally then they'll want that to work. Trying again.

**Comment by davkean** [comment]
Are the diasym changes required? Do we support those in VS Update 1?

**Comment by jaredpar** [comment]
:+1: 

@davkean the diasym changes are supported for update 1 and are necessary for determinism.  They should be in any branch that is update 1 targetted.

**Comment by leppie** [comment]
You guys should really get more disk space on the mac box, been choking the entire weekend.

**Comment by jaredpar** [comment]
@leppie in the middle of a lab switch this weekend so down to a single mac while we transition.  Looks like we got a bit overloaded.

**Comment by jasonmalinowski** [comment]
@davkean: that file isn't actually consumed anywhere, but if I don't make the change then Restore.cmd in Update 1 will always create that as a dirty modification. Once I merge this I'll merge it to Update 1 and then do a commit there to .gitignore the file entirely. Nothing actually consumes that (unlike project.lock.jsons alongside csproj files).

**Comment by davkean** [comment]
retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/1754/
// Retest reason: https://github.com/dotnet/roslyn/issues/7272

**Comment by paul1956** [comment]
After running Restore.cmd (as Admin) and running MSBUILD without errors I still get 148,435K errors when I open Roslyn.sln in Visual Studio and waiting a long time. Many seem to be due to missing libraries, If I manually add some of the missing VSIX's to one project some of the issue in that project go away. The lines below are grayed out,
```
Imports Microsoft.CodeAnalysis.ExpressionEvaluator
Imports Microsoft.CodeAnalysis.Test.Utilities
Imports Microsoft.VisualStudio.Debugger.Evaluation
Imports Microsoft.VisualStudio.Debugger.Evaluation.ClrCompilation
Imports Roslyn.Test.Utilities
```
image

**Comment by leppie** [comment]
@paul1956 You probably dont want to build from command line and then in VS from different accounts. I have had problems with that before on the master branch.

**Comment by paul1956** [comment]
Thanks @leppie I deleted everything, downloaded the zip again, and on a clean system following the instructions and your advice everything worked. As far as I am concerned this issue is closed. Thanks everyone.

**Pull request merged**
