### PR TITLE
Reworked Compiler packages

### PR DESCRIPTION
**Pull request by Nirmal4G**
This PR uses `Microsoft.NET.Compilers` ID for both frameworks and `Microsoft.NETFramework.Compilers` ID for `.NET Framework` only package.

Thus we'll have

- `Microsoft.NET.Compilers` (both)
- `Microsoft.NETCore.Compilers` (coreclr-only)
- `Microsoft.NETFramework.Compilers` (netclr-only)

The naming is easy, predictable and understandable.

Also, since `Microsoft.NET.Compilers` is becoming all-in-one package, it's compatible with existing users since they only relied on it being the NETCLR only package and now it contains both.

### CODE REVIEW

**Comment by jaredpar** [comment]
Closing this PR as this is not how we wish our NuPkg files to move forward. There is simply no plan or motivation for us to change these packages at this point in the direction described here.

If you want to discuss the possibility of these we should do so via an issue. But at this point there would need to be an **extremely** compelling reason to make this change that we're not aware of.

**Comment by Nirmal4G** [comment]
It's okay. After all, it's your project. I just made a suggestion. That's all.

Thanks for responding quickly though.

**Comment by Nirmal4G** [comment]
Could these could be compelling reasons, then?

- https://github.com/dotnet/msbuild/issues/7832 
- https://github.com/dotnet/msbuild/pull/7947

It is stated that the plan is to re-structure the packages. Does that mean to introduce new packages with fixes or fix existing ones (_huge breaking change as per above comment_).

**Comment by jaredpar** [comment]
> It is stated that the plan is to re-structure the packages. 

The plan is to restructure the .NET SDK setup. That may or may not necessitate changing the packages. I do not think it will be necessary though. 

> Could these could be compelling reasons, then?

No. There are still no plans to do this.

**Comment by Nirmal4G** [comment]
If it's possible, shipping the compilers as an SDK package like `Microsoft.NET.Sdk` would solve those issues. It enables us to reference explicitly versioned packages through NuGet (_or `NuGetFallbackFolder`_) and in-built compilers via `<MSBuild>\Sdks\...` path which could guarantee the versions.

**Comment by jaredpar** [comment]
> If it's possible, shipping the compilers as an SDK package (like Microsoft.NET.Sdk) via .NET SDK and NuGet, would solve those issues.

That's not a goal for the .NET SDK that Im' aware of. If they want to make that a goal then we can discuss how we support our NuPkg files. 

To restate though: We do not desire a world where people can patch the compiler in the .NET SDK with a NuPkg. We **strongly** prefer developers to use the compiler that come with the .NET SDK. The fact that this NuPkg can do this is meant for very short term patching only.

**Pull request closed without merging**
