### PR TITLE
added Telemetry dumper to roslyn diagnostic tool window

### PR DESCRIPTION
**Pull request by heejaechang**
people are asking how to get telemetry ID we record on code fix.

so added a tool to dump that info on roslyn diagnostic tool window

you can get it from View -> Other Windows -> Roslyn Diagnostics
image

which will give you this
image

click dump to get all telemetry guid

### CODE REVIEW

**Comment by heejaechang** [comment]
cleanup and pushing telemetry id thing I did for intellicode people in case they want it again for newly added fixes

@kendrahavens @jinujoseph

**Comment by heejaechang** [comment]
it contains no functional changes. some refactoring to share code though.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure integration test failure seems some test infra issue? all looks like failed with this kind of screenshot

image

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure @jaredpar actually looks like real issue on compiler? this is from one of the log from integration test.

vent Time (UTC): 12/4/2018 7:33:28 AM
Event ID: 1025
Data: Application: devenv.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: System.NullReferenceException: Object reference not set to an instance of an object.

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxTokenWithValue`1..ctor(SyntaxKind kind, String text, T value)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken.SyntaxTokenWithValueAndTrivia`1..ctor(SyntaxKind kind, String text, T value, GreenNode leading, GreenNode trailing)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.Create(TokenInfo& info, SyntaxListBuilder leading, SyntaxListBuilder trailing, SyntaxDiagnosticInfo[] errors)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexXmlCDataSectionTextToken()

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.Lex(LexerMode mode)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Blender.Reader.LexNewToken(LexerMode mode)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Blender.Reader.ReadNewToken(LexerMode mode)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Blender.Reader.ReadNodeOrToken(LexerMode mode, Boolean asToken)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Blender.ReadNodeOrToken(LexerMode mode, Boolean asToken)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.AddNewToken()

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxParser.FetchCurrentToken()

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.DocumentationCommentParser.ParseRemainder(SyntaxListBuilder`1 nodes)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.DocumentationCommentParser.ParseDocumentationComment(Boolean& isTerminated)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexXmlDocComment(XmlDocCommentStyle style)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexSyntaxTrivia(Boolean afterFirstToken, Boolean isTrailing, SyntaxListBuilder& triviaList)

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.LexSyntaxToken()

   at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer.Lex(LexerMode mode)

   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.<ParseTokens>d__680.MoveNext()

**Comment by genlu** [comment]
Is this deployed to the actual product (e.g. as part of roslyn sdk)?

**Comment by heejaechang** [comment]
@genlu no, this tool is not part of the product. this tool window is a place where we used to put roslyn diagnostic tools in it. it was created before we had "diagnostic analyzer" so it has a word "diagnostic" in it, but don't be confused by the word. it has nothing to do with "diagnostic analyzer"

it will be installed into RoslynDev hive when you build "Roslyn". it will put Roslyn option page in Tools->Options that let you control bunch of internal roslyn behaviors or enable/disable some ETW events for performance investigations.

and install the tool window that let you see some internal workings and install Razor projection buffer viewer as editor extension to make razor/venus investigation easier.

**Comment by heejaechang** [comment]
tagging @jinujoseph can I check this in?

**Pull request merged**
