### PR TITLE
Remove unused service IWorkCoordinatorPriorityService

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by mavasani** [comment]
Is this no longer used by TypeScript? I tried the same change a while ago in https://github.com/dotnet/roslyn/pull/41439

**Comment by mavasani** [comment]
Seems to be still used [here](https://dev.azure.com/devdiv/DevDiv/_search?action=contents&text=TypeScriptWorkCoordinatorPriorityService&type=code&lp=code-Project&filters=ProjectFilters%7BDevDiv%7DRepositoryFilters%7BTypeScript-VS%7D&pageSize=25&result=DefaultCollection%2FDevDiv%2FTypeScript-VS%2FGBmaster%2F%2FVS%2FLanguageService%2FTypeScriptLanguageService%2FFeatures%2FSolutionCrawler%2FTypeScriptWorkCoordinatorPriorityService.cs) by TypeScript.

@tmat Move to TS ExternalAccess instead?

**Comment by tmat** [comment]
Damn, TypeScript strikes again! OK... will follow up with them.

**Comment by tmat** [comment]
Checked with TypeScript and they say they need this at this point. Once we move to LSP diagnostics we can remove.

**Pull request closed without merging**
