### PR TITLE
Modify DataFlowAnalysis implementations to only report referenceable symbols (fixes #5891)

### LINKED ISSUE #5891: Region analysis API returning symbols not declared in source
This issue was reported in #5845 but not fixed before it was integrated.

See `TestOmittedLambdaPointerTypeParameter` in `RegionAnalysisTests.cs`. It demonstrates that the region analysis APIs will return symbols not declared in source. Those APIs should never report synthetic symbols.

### PR DESCRIPTION
**Pull request by tuespetre**
Fixes #5891

👽 I saw this one was up-for-grabs.

### CODE REVIEW

**Comment by agocke** [comment]
@tuespetre Sorry for the delay, I somehow missed the notification for a review for this.

**Comment by agocke** [comment]
test windows_release_vs-integration_prtest please

**Comment by tuespetre** [comment]
@agocke NP (meaning no problem, and *nice puppy! 🐶*)

**Comment by agocke** [comment]
🐶 💯

**Comment by gafter** [comment]
This looks slightly out-of-date, but I like the change.

**Comment by gafter** [comment]
@tuespetre Can you please merge this branch from master?

**Comment by tuespetre** [comment]
@jaredpar @gafter sure thing

**Comment by tuespetre** [comment]
OK, cherry-picked onto a fresh master and made sure the `capturedInside`/`capturedOutside` lists were included in the new tests.

**Comment by gafter** [comment]
@tuespetre Thank you for your contribution. You are awesome!

**Pull request merged**
