### PR TITLE
Add ConfigureAwait.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @natidea @AlekseyTs @jaredpar 

Jared, do you know why the ConfigureAwait analyzer isn't running Master, but is running in features/ioperation?

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Pilchie** [comment]
Is it one of the slow ones that @sharwell disabled in master?

**Comment by jasonmalinowski** [comment]
I threw together a quick test: ugh, it's not running in CI right now:

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9428/console

Investigating further.

**Pull request merged**
