### PR TITLE
Fix #308 and #306 - issues with dynamic expressions in string interpolation

### LINKED ISSUE #306: String interpolation: new difference in dynamic/static overload resolution
```c#
using System;

class Foo {
    void M(object[] xs) {
        IFormattable s1 = $"{null}"; // Create("{0}", new object[1])
        IFormattable s2 = $"{xs}";   // Create("{0}", new object[] { xs })
        
        dynamic nil = null, ys = xs;
        IFormattable d1 = $"{nil}";  // Create("{0}", (object[]) null)
        IFormattable d2 = $"{ys}";   // Create("{0}", (object[]) xs)
    }
}

namespace System.Runtime.CompilerServices {
    public static class FormattableStringFactory {
        public static IFormattable Create(string format, params object[] xs) => null;
    }
}
```
Can this be solved with current `dynamic` codegen? Maybe with some flags...

### LINKED ISSUE #308: Internal compiler error: string interpolation + dynamic + expression trees
Continue of #306 story:

```c#
using System;
using System.Linq.Expressions;

class Foo {
    Expression<Func<string>> M(dynamic d) {
        return () => $"Dynamic: {d}";
    }
}
```

> Unexpected value 'Sequence' of type 'Microsoft.CodeAnalysis.CSharp.BoundKind'
> 
>    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitInternal(BoundExpression node)
>    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.Visit(BoundExpression node)
>    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.TranslateLambdaBody(BoundBlock block)
>    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.VisitLambdaInternal(BoundLambda node)
>    at Microsoft.CodeAnalysis.CSharp.ExpressionLambdaRewriter.RewriteLambda(BoundLambda node, TypeCompilationState compilationState, TypeMap typeMap, DiagnosticBag diagnostics)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.RewriteLambdaConversion(BoundLambda node)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.VisitConversion(BoundConversion conversion)
>    at Microsoft.CodeAnalysis.CSharp.BoundConversion.Accept(BoundTreeVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
>    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitReturnStatement(BoundReturnStatement node)
>    at Microsoft.CodeAnalysis.CSharp.BoundReturnStatement.Accept(BoundTreeVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
>    at Microsoft.CodeAnalysis.CSharp.BoundTreeRewriter.VisitSequencePoint(BoundSequencePoint node)
>    at Microsoft.CodeAnalysis.CSharp.BoundSequencePoint.Accept(BoundTreeVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.RewriteBlock(BoundBlock node, ArrayBuilder`1 prologue, ArrayBuilder`1 newLocals)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.<>c__DisplayClass45_0.<VisitBlock>b__0(ArrayBuilder`1 prologue, ArrayBuilder`1 newLocals)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.IntroduceFrame[T](BoundNode node, LambdaFrame frame, Func`3 F)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.VisitBlock(BoundBlock node)
>    at Microsoft.CodeAnalysis.CSharp.BoundBlock.Accept(BoundTreeVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.BoundTreeVisitor.Visit(BoundNode node)
>    at Microsoft.CodeAnalysis.CSharp.LambdaRewriter.Rewrite(BoundStatement loweredBody, NamedTypeSymbol thisType, ParameterSymbol thisParameter, MethodSymbol method, Int32 methodOrdinal, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, VariableSlotAllocator slotAllocatorOpt, TypeCompilationState compilationState, DiagnosticBag diagnostics, Boolean assignLocals)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.LowerBodyOrInitializer(MethodSymbol method, Int32 methodOrdinal, BoundStatement body, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState, DiagnosticBag diagnostics, VariableSlotAllocator& lazyVariableSlotAllocator, ArrayBuilder`1 lambdaDebugInfoBuilder, ArrayBuilder`1 closureDebugInfoBuilder, StateMachineTypeSymbol& stateMachineTypeOpt)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol)
>    at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
>    at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()

### PR DESCRIPTION
**Pull request by gafter**
Fixes #306 and #308.

### CODE REVIEW

**Comment by gafter** [comment]
Hey, can a couple of you please look at this @jaredpar @AlekseyTs @VladimirReshetnikov @VSadov @agocke

**Comment by jaredpar** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by agocke** [comment]
:+1:

**Pull request merged**
