### PR TITLE
Add NamingPreferences to the SimplificationOptionProvider

### PR DESCRIPTION
**Pull request by dpoeschl**
This allows the VSI option resetter to reset the option (so that stale
default values aren't used).

### CODE REVIEW

**Comment by dpoeschl** [comment]
@dotnet/roslyn-ide

**Comment by dpoeschl** [comment]
Tagging @MattGertz for ask mode approval - this improves VSI test consistency.

**Comment by MattGertz** [comment]
@dpoeschl So to be clear -- this is a product change specifically to improve a test hook, but which otherwise has no impact on (and thus no risk to) current functionality?

**Comment by dpoeschl** [comment]
@MattGertz Correct, that is my understanding. But I want to verify with @jasonmalinowski that this doesn't mean anything new in the .editorconfig world.

**Comment by MattGertz** [comment]
@dpoeschl OK, tag me again once you find out.

**Comment by jasonmalinowski** [comment]
Nope, no impact. (I told @dpoeschl to make this exact change. :-))

**Comment by dpoeschl** [comment]
@MattGertz No .editorconfig implications.

**Pull request merged**
