### PR TITLE
Cherry-pick the ExplicitInterfaceImplemetation fix

### PR DESCRIPTION
**Pull request by Cosifne**
Port this fix to 16.11
https://github.com/dotnet/roslyn/pull/53984

### CODE REVIEW

**Comment by Cosifne** [comment]
@jinujoseph  @vatsalyaagrawal 
This is just a one line fix for the inheritance margin. Without this fix inheritance margin won't be created for explict interface implementation.
So I feel it will be great to check this change to 16.11

**Comment by Cosifne** [comment]
OMG this is forgotten for a long time.
@davidwengier Could you give this a quick approval. it's the same as https://github.com/dotnet/roslyn/pull/53984

**Comment by CyrusNajmabadi** [comment]
Why do we need to backport this to 16.11?  seems like a minor issue?

**Comment by Cosifne** [comment]
> Why do we need to backport this to 16.11? seems like a minor issue?

@CyrusNajmabadi 
I believe explicit implementation is used widely, and the fix is pretty easy and low-risk. 
Do we only checked in big reliability fix to 16.11 now?

**Comment by CyrusNajmabadi** [comment]
> Do we only checked in big reliability fix to 16.11 now?

I'm not sure what the 16.11 bar is at currently.  Are we in any sort of QB mode now?

**Comment by Cosifne** [comment]
> > Do we only checked in big reliability fix to 16.11 now?
> 
> I'm not sure what the 16.11 bar is at currently. Are we in any sort of QB mode now?

@CyrusNajmabadi 
I think 16.11 is in M1 mode. (required approval from Jinu or Vatsalya) and I have already explained this to Jinu

**Review by davidwengier — APPROVED** [review]

**Pull request merged**
