### PR TITLE
Only offer 'Use coalesce expression' in C#8 and above.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/44793

### CODE REVIEW

**Comment by sharwell** [comment]
@CyrusNajmabadi Can you set the milestone for this (version and preview)? Milestones must be set manually for all pull requests where the **auto-merge** feature is used.

**Comment by CyrusNajmabadi** [comment]
I odn't know what milestone this went into.  How can I find out?  Is there some sort of reverse mapping service?  Can we make the `auto-merge` bot set this?  Who would we contact about that?  Thanks!

**Comment by RikkiGibson** [comment]
It seems like this somehow slipped through the cracks, we're supposed to have an automation that adds everything to the Next milestone and things get moved to the correct milestone from there.

**Comment by sharwell** [comment]
@RikkiGibson There was a long period of time where auto-merge PRs did not also get milestones. The PR author needs to manually set the milestones for these PRs.

**Pull request merged**
