### PR TITLE
Using correct case in-sensitive comparer

### LINKED ISSUE #4782: Add Import uses incorrect string comparison for identifiers
https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/CodeFixes/AddImport/CSharpAddImportCodeFixProvider.cs#L704-L706

Should use Microsoft.CodeAnalysis.CaseInsenitiveComparison.

### PR DESCRIPTION
**Pull request by jmarolf**
Fixes #4782

### CODE REVIEW

**Comment by jmarolf** [comment]
@Pilchie @balajikris @dpoeschl @rchande @brettfo @DustinCampbell @basoundr @CyrusNajmabadi

**Comment by jmarolf** [comment]
@dotnet-bot retest this please

**Comment by Pilchie** [comment]
Can we craft a test that relies on this?

**Comment by jmarolf** [comment]
@Pilchie  This pull request now removes the check.  There was never any test that could rely on this behavior.

**Comment by Pilchie** [comment]
:+1:

**Comment by Pilchie** [comment]
We could still have a test where we have 2 names that vary in case, and verify that only the right case namespace is suggested.

**Comment by jmarolf** [comment]
@Pilchie good point.  I'll add the test

**Pull request merged**
