### PR TITLE
Move SymbolSearch down to EditorFeatures

### PR DESCRIPTION
**Pull request by tmat**
... from EditorFeatures.Wpf.

### CODE REVIEW

**Comment by tmat** [comment]
@CyrusNajmabadi PTAL

**Comment by CyrusNajmabadi** [comment]
I'm totally fine with this.  However, i'm curious what's the overall motivation here.  Could you expand on that a bit?  Thanks!

**Comment by tmat** [comment]
The motivation is to remove dependency on WPF layer from ServiceHub project:
https://github.com/dotnet/roslyn/pull/45505/files#diff-526e287dd825598a68895e89a4d13489L19

Features that do not depend on WPF shouldn't be in WPF layer.

**Comment by CyrusNajmabadi** [comment]
WFM!  Thanks!

**Comment by jasonmalinowski** [comment]
So this is ironcially the identical change that @sharwell was making in https://github.com/dotnet/roslyn/pull/45115, which we were not going to take because this was potentially going to cause other issues. RemoteControl isn't a library that is cross-plat -- it depends on things like "the Internet Explorer cache" and the registry, and so it won't run on VS for Mac. In @sharwell's PR we were looking at alternative solutions.

@tmat is this fixing an urgent issue? Otherwise we may need to roll this back.

**Comment by tmat** [comment]
@jasonmalinowski Let's roll back.

**Pull request merged**
