### PR TITLE
More VSTS experiments (2)

### PR DESCRIPTION
**Pull request by jaredpar**
<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by sharwell** [comment]
Notes:

* I attempted to retry the build (hoping for equivalent to Jenkins' Retry button) by clicking Queue Build &rarr; Queue. A new build started, but the status here still points to the original build (I expected it to update saying in progress).
* When restarting a build, the "Associated changes" for the build are lost (it only shows the merge commit that GitHub creates at refs/pull/27990/merge)
* We need to [Publish Test Results](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results?view=vsts) for the tests to show on the Tests tab.
* The following error is not detected as an error by the log parsing features (I expect we will need to keep track of each time this happens to incrementally improve the ability of VSTS to report the true cause of a build failure):

    > The archive file E:\\A\\_work\\692\\s\\Binaries\\Debug\\Installer\\Roslyn_Preview.zip already exists. Use the -Update parameter to update the existing archive file or use the -Force parameter to overwrite the existing archive file.

* The name **public-CI** is very confusing given the scoping of VSTS builds
* Given the ability of VSTS to separate build tasks and report the time of each, it would be nice to split the current Cmdline take into at least Compile and Test phases, and possibly a publish phase or anything else that takes significant time but doesn't fit into one of these two.

**Comment by whoisj** [comment]
> I attempted to retry the build (hoping for equivalent to Jenkins' Retry button) by clicking Queue Build → Queue. A new build started, but the status here still points to the original build (I expected it to update saying in progress).

As best I know, VSTS doesn't yet have a re-build PR concept. The only way to achieve this, that I am aware of, is to pull the branch locally use `git commit --amend --no-edit` to "touch" the tip commit, then `git push --force-with-lease` back to the PR branch. Of course, this is very manual and causes all CI to rebuild.

If you find a better way to do this, please let me know! 😄

**Comment by jaredpar** [comment]
@sharwell 

> We need to Publish Test Results for the tests to show on the Tests tab.

Yep. It's very much on the list. For context though this is the **first** time I got to the point of tests actually executing. Still very early here. 

@whoisj 

> As best I know, VSTS doesn't yet have a re-build PR concep

Going to need that before we move over I suspect. I hate "retest this" more than pretty much anyone but it's essentially for getting some of or tests to complete at this point (VS integration).

**Comment by sharwell** [comment]
> Going to need that before we move over I suspect

Agreed. @whoisj this is going to be a blocker for us so we'll want to let the appropriate people know early that it's historically a very important feature for us.

**Comment by jaredpar** [comment]
This is a known issue. We have a couple threads going about our conversion. Right now we are working through more fundamental on boarding issues though.

**Pull request merged**
