### PR TITLE
[Automated] Merge origin/stabilization into origin/master

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by davkean** [comment]
Thanks for the PR for this! Appreciate it. @agocke We're failing to find the portable targets on Mono/Linux, what's going here?

**Comment by agocke** [comment]
@davkean @tannergooding This line was merged wrong: https://github.com/dotnet/roslyn/pull/6426/files#diff-eeecaff74834007a6aaf4dbb7158a161L207

Always choose the highest version.

**Comment by davkean** [comment]
Was this accidentally merged, I didn't see the jobs finish?

**Comment by tannergooding** [comment]
Yes. Meant to comment saying I pulled in the rest of the changes and clicked merge instead.

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure, please watch for failures coming out of this.

**Pull request merged**
