### PR TITLE
Remove duplicate validation logic

### LINKED ISSUE #42465: Project.AssemblyName does not accurately report assembly name.
_This issue has a corresponding [ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/943329/projectassemblyname-does-not-accurately-report-ass.html). Please vote and comment there to make sure your voice is heard._

---
The following code suddently started appending ".csproj" onto assembly names which seems wrong.

```c#
private IReadOnlyList<string> GetTargetAssemblies()
{
    List<string> result = new List<string>();

    foreach (Microsoft.CodeAnalysis.Project project in this.workspace.CurrentSolution.Projects)
    {
        // .Net Core projects can have ".csproj" attached sometimes.
        result.Add(project.AssemblyName.Replace(".csproj", string.Empty));
    }

    return result.AsReadOnly();
}
```

It is important to keep apis reporting data in a consistent format. if it doesn't it requires  rolling out extension updates for no useful reason.

Here is the csproj that causes the assembly name to be wrong:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Microsoft.Exchange.Diagnostics</AssemblyName>
  </PropertyGroup>
</Project>
```

Note: I must have `<AssemblyName>` in this new format project because there is no other way (known? supported?) to find the target assembly programmatically between old and new format csproj files.

### PR DESCRIPTION
**Pull request by jaredpar**
The MSBuild task for csc / vbc compilers contained validation to detect
that no duplicate source files or resources were provided. This
validation is duplicated with logic in the compiler hence it's
unnecessary.

Further this use came during `ValidateParameters` which means that when
it fails the underlying task doesn't actually execute. This means that
design time builds don't process the project in the face of that type of
error which blocks a number of Visual Studio based scenarios.

closes #42465

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler @jasonmalinowski  PTAL

**Comment by jaredpar** [comment]
> I'm OK with this if you're OK with this!

@rainersigwald is okay with this so who am I to dispute?

**Comment by agocke** [comment]
@jaredpar Is there a Csc/Vbc task test? And a command line test that demonstrates our resilience?

**Comment by jaredpar** [comment]
@agocke 

There are existing compiler tests:
- https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/Emit/ResourceTests.cs#L286
- https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/CommandLine/CommandLineTests.cs#L8917

Similar tests exist for VB. The C# tests actually demonstrate another reason for removing this check. The compiler is actually tolerant of duplicate source files, it just emits a warning. 

There were no Task tests.

**Comment by agocke** [comment]
@jaredpar do you want to add one to http://sourceroslyn.io/#Microsoft.Build.Tasks.CodeAnalysis.UnitTests/CscTests.cs,691dd5a92870fd19? :)

**Comment by jaredpar** [comment]
@agocke 

Tests to just verify the files are passed multiple times?

**Comment by jasonmalinowski** [comment]
> The compiler is actually tolerant of duplicate source files, it just emits a warning.

Which case comparison was it using in that case? I was surprised this was doing case-insensitive, because you were just in trouble if you had two differently cased files on Linux. At least if it's a warning in the compiler you have some hope.

(I of course pray nobody is relying on this, but alas....)

**Comment by agocke** [comment]
Ah, I see, so the task unit test wouldnt' exercise the code path that was previously causing the problem. OK, in that case we can proceed, but it would be good to see how we can add a regression test for the scenario.

**Comment by jaredpar** [comment]
@jasonmalinowski 

> Which case comparison was it using in that case?

The compiler is rather inconsistent in how it applies case to paths. Back when I re-joined Roslyn I tried to rationalize it but eventually gave up. I think the only rationalization we could ever really add 
 without breaking compat was that the compiler always compares file paths case insensitive. I'd prefer the other but I fear that would definitely break compat.

**Comment by rainersigwald** [comment]
That story is very familiar to me; it's basically where we've landed in MSBuild. Don't distinguish files based only on case for .NET code: that way lies pain.

**Pull request merged**
