### PR TITLE
made error list to be loaded quite upfront so that error from early stat...

### PR DESCRIPTION
**Pull request by heejaechang**
...e can show up. otherwise, some errors (ex, package loading stage) could be lost.

### CODE REVIEW

**Comment by heejaechang** [comment]
@shyamnamboodiripad @srivatsn @mavasani can you take a look?

**Comment by heejaechang** [comment]
#1521

**Comment by mavasani** [comment]
:+1: Thanks for fixing!

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
