### PR TITLE
Fix assertion for WellKnownTypes

### PR DESCRIPTION
**Pull request by drognanar**
Updates the expected name of the last well known type.

### CODE REVIEW

**Comment by drognanar** [comment]
FYI @dotnet/roslyn-compiler @dotnet/testimpact

**Comment by jcouv** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by genlu** [comment]
:+1:

**Comment by JohnHamby** [comment]
Sorry if I messed this up. The fix looks good to me.

**Comment by jcouv** [comment]
You didn't mess up. This would necessarily have happened in the merge.

In the future branch, I re-ordered the list so that IFormatProvider is not the last item (and the assertion didn't apply to it, or the second last item, because they are generic types).
In the test-impact branch, you added a non-generic type just before the last.
The combination of both changes means the assert will be hit, even though both of our changes are legit ;-)

**Pull request merged**
