### PR TITLE
Disable IPerformanceTrackerService in production scenarios

### PR DESCRIPTION
**Pull request by sharwell**
See #48926

### CODE REVIEW

**Comment by jinujoseph** [comment]
Synced with @DamianEdwards on going forward here.

**Comment by mavasani** [comment]
@jinujoseph This is not used by partner team- this is used to log analyzer telemetry for expensive analyzers in IDE. We should get sign off from our PM team on this.

**Review by mavasani — CHANGES_REQUESTED** [review]
We should just disable `PerformanceTrackerService.GenerateReport` that showed up in performance traces, not the entire analyzer telemetry. Basically, just remove the below call: https://github.com/dotnet/roslyn/blob/cf55f3a58e47298426fa971d3bd9d8857c746c65/src/Workspaces/Remote/ServiceHub/Services/Host/RemoteHostService.PerformanceReporter.cs#L73

**Comment by sharwell** [comment]
@mavasani `GenerateReport` is the only action taken by `PerformanceReporter`. It doesn't serve any purpose to keep the background processor enabled knowing it takes no action.

**Review by mavasani — APPROVED** [review]
LGTM. Probably we should consider deleting the code completely? Do you see anyone using this in debug bits?

**Comment by sharwell** [comment]
> Probably we should consider deleting the code completely? Do you see anyone using this in debug bits?

There are two things that can lead to us using this again in the future:  

1. It looks like we're going to need to implement strict throttles to avoid customer performance overhead for API usage telemetry (#48932), which could be reused for this feature.
2. My evaluation was limited to telemetry costs alone, with no determination at all related to the usefulness of telemetry. If the telemetry does turn out to be useful, the goal here would be fixing the performance issues instead of removing it completely.

**Pull request merged**
