### PR TITLE
Switch to Microsoft.DiaSymReader.PortablePdb 1.3.0 release

### PR DESCRIPTION
**Pull request by tmat**
Use the release package. No code changes were made since the last version (1.3.0-beta1-61619-01).

### CODE REVIEW

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
@jaredpar @jasonmalinowski

**Comment by tmat** [comment]
test windows_debug_unit64_prtest please
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_debug_unit64_prtest please

**Comment by jaredpar** [comment]
> Is there a myget feed we can remove while doing this?

Every time you delete a myget feed, two more get added.

**Comment by tmat** [comment]
@jasonmalinowski I have not pushed to nuget.org yet. Will do that when we officially ship. Why would we want to remove nuget feed anyways? We'll need it for the next version.

**Comment by jasonmalinowski** [comment]
@tmat: each fewer feed means one less chance for a screwed up package upload to myget or accidental package deletion to break us. @jaredpar has long wanted to see us be in a place where we don't depend upon myget for shipping branches...at least keeping the config file reflecting the current set of feeds we depend on is one small step in that direction.

**Comment by tmat** [comment]
@MattGertz For ask mode approval

**Comment by tmat** [comment]
@jasonmalinowski I guess we can do that once we snap a release branch.

**Comment by tmat** [comment]
test perf_correctness_prtest please

**Comment by tmat** [comment]
NuGet cache corruption with null files

**Comment by tmat** [comment]
test perf_correctness_prtest please

**Pull request merged**
