### PR TITLE
Remove unnecessary references

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
logged win failure: https://github.com/dotnet/roslyn/issues/7618

test win please

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
test win please

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_ccc/6/
// Retest reason: Look like it timed out during a git operation.

**Pull request merged**
