### PR TITLE
Unskip test for fixed IOperation issue

### PR DESCRIPTION
**Pull request by mavasani**
Original issue: ~~https://github.com/dotnet/roslyn/issues/23821~~ https://github.com/dotnet/roslyn/issues/22980

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Comment by mavasani** [comment]
@jinujoseph for approval of this test-only change.

**Comment by jinujoseph** [comment]
@mavasani test only changes don't need approval.
feel free to approval

**Review by jinujoseph — APPROVED** [review]

**Comment by mavasani** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 1)

**Pull request merged**
