### PR TITLE
Make code more resilient to potential bad situations.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is the same change as: https://github.com/dotnet/roslyn/pull/6679

However, if that change is not approved, i would still like this to go in.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
:+1:

**Comment by Pilchie** [comment]
Actually, on second thought, maybe we want to add an exception filter instead, so we can get an actionable crash that tells us *what* is null?

**Comment by jasonmalinowski** [comment]
I agree with @Pilchie: let's crash rather than silently march on.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski We now use a non-fatal watson.  Let me know if this is what you were looking for.  Thanks!

**Comment by jasonmalinowski** [comment]
Seems reasonable to me. :+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
retest mac please

**Pull request merged**
