### PR TITLE
Bump unix toolset version to VS 2017 RTW compiler version

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by agocke** [comment]
cc @VSadov @jcouv

**Comment by agocke** [comment]
@jcouv You said you had a failing branch -- could you try rebasing on this one and see if it fixes your problem?

**Comment by jcouv** [comment]
@agocke Yes, I'll try that.

**Comment by jcouv** [comment]
Re-opened PR and added this fix to it to confirm it fixes the problem: https://github.com/dotnet/roslyn/pull/18381

**Comment by agocke** [comment]
@jcouv Looks like the ubuntu build passed. I'll merge this, then.

**Pull request merged**
