### PR TITLE
Handle pattern-matching against Nullable<T>.

### PR DESCRIPTION
**Pull request by gafter**
Even though disallowed in source, it can arise through generic substitution.

@AlekseyTs Please review
@dotnet/roslyn-compiler A second review, please

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5618/
// Retest reason: inexplicable

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@agocke Second review, please?

**Comment by agocke** [comment]
:+1:

**Pull request merged**
