### PR TITLE
Sync namespace and folder refactoring

### PR DESCRIPTION
**Pull request by genlu**
This is retargeting https://github.com/dotnet/roslyn/pull/30156 to master. As mentioned in https://github.com/dotnet/vblang/issues/351, this will not be provided for VB.

Remaining issues/work that will be addressed in separate PRs
- [ ] Fix "undo" for "move file to folder" refactoring
- [ ] Enable this refactoring for CPS based project (this requires a crosscutting change between roslyn and project system)
- [ ] refactor the language service to support "Move type to new namespace" and "change namespace (selected declaration only)" refactoring. (we might implement those for VB as well, still under discussion)

@dotnet/roslyn-ide

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> nable this refactoring for CPS based project (this requires a crosscutting change between roslyn and project system)

Is this about fixing the issue where CPS is changed, but then doesn't reflect the change at some point in the future?  If so, will you be able to fixup the CanRenameFilesDuringCodeActions as part of that work?

**Comment by CyrusNajmabadi** [comment]
I'm a little confused.  Did you open a new PR here?  Aren't all our comments lost now?

**Comment by CyrusNajmabadi** [comment]
>As mentioned in dotnet/vblang#351, this will not be provided for VB.

Sounds good.  I appreciate that vb was consulted on this and some community members weighed in.  I'm hesitant about if enough data was collected.  But i think there's enough info now to say this doesn't have to eb shipped at launch, and this can be provided later if there is community desire for it.

**Comment by genlu** [comment]
@CyrusNajmabadi No, this is a different issue. Basically we need a non-blocking way to get default namespace for CPS projects ([here's the proposed fix](https://github.com/dotnet/roslyn/pull/30771)). The problem you mentioned is tracked by https://github.com/dotnet/project-system/issues/3425, I will work with @davkean to drive that too.

**Comment by genlu** [comment]
@CyrusNajmabadi I have to retarget against master, hence the new PR. Should I just force push to the original branch instead?

**Comment by CyrusNajmabadi** [comment]
Yes please.  Just do a normal rebase in your branch against upstream/master.  Push that up, then tell github what your new base-branch is.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi No, this is a different issue.

Ah ok.  Thanks! :)

**Comment by genlu** [comment]
Closed, switch back to the [original PR.](https://github.com/dotnet/roslyn/pull/30156)

**Comment by CyrusNajmabadi** [comment]
> Closed, switch back to the original PR.

Thanks.  I think the way we should handle this is to just do the other PR until it gets sign off, then just rebase and merge when passing :)

**Pull request closed without merging**
