### PR TITLE
Adjust “reachable” walker according to design meeting decision.

### PR DESCRIPTION
**Pull request by AlekseyTs**
- Assume an exception can be thrown from any try block, even an empty one.
- Do not treat any catch clause as definitely catching all exceptions.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]
:shipit:

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review

**Review by mavasani — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review, need second sign-off.

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review, need second sign-off.

**Review by jcouv — APPROVED** [review]
LGTM

**Pull request merged**
