### PR TITLE
Updated WorkItemAttribute documentation

### PR DESCRIPTION
**Pull request by sharwell**
The construction arguments were misleading with respect to our practices. I
updated the names and documentation so new contributors can follow along more
easily.

### CODE REVIEW

**Comment by sharwell** [comment]
😆 I had no idea that this change would result in the build system *enforcing* that the location is a URI.

**Comment by Pilchie** [comment]
Apparently https://msdn.microsoft.com/en-us/library/bb264490.aspx...

**Comment by MaximRouiller** [comment]
😛 Sorry about that. :canada:

**Comment by sharwell** [comment]
@MaximRouiller It's not a bad thing. :smile: It's not too often we get someone who provides as complete a picture of their onboarding experience as you did (between the work in the issue/PR and the blog posts).

I'm planning to fix up all the prior deviations during the week of 4/17 and merge this afterwards.

**Comment by MaximRouiller** [comment]
@sharwell One thing for sure... traffic on my post has been exploding. If there is anything more I can document in this way, please let me know. It's literally a win-win-win scenario (user/me/Microsoft).

**Pull request merged**
