### PR TITLE
Unskip test

### PR DESCRIPTION
**Pull request by rchande**

### CODE REVIEW

**Comment by rchande** [comment]
@dotnet/roslyn-ide Anyone want to sign off on this? CI builds are green with this test unskipped.

**Comment by jasonmalinowski** [comment]
Did we understand why this failed on @gafter's machine, or were we unable to reproduce it there too?

**Comment by rchande** [comment]
I was never able to get it to fail on my machine. @gafter Does it still fail on yours?

**Comment by Pilchie** [comment]
:+1: if @gafter can't repro.  Should the commit description include the bug number so that it will close?

**Comment by gafter** [comment]
It still fails for me:

```none
------ Test started: Assembly: Roslyn.Services.Editor.UnitTests2.dll ------
Unknown .NET Framework Version: v4.6
Test 'Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.SelectKeywordFirst' failed:
	Assert.Equal() Failure
          ↓ (pos 0)
Expected: GetType function\r\nReturns a System.Type o···
Actual:   Sub C.GetType()
          ↑ (pos 0)
	IntelliSense\TestState.vb(270,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.TestState.VB$StateMachine_36_AssertSelectedCompletionItem.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	IntelliSense\VisualBasicCompletionCommandHandlerTests.vb(1843,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_88_SelectKeywordFirst.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

0 passed, 1 failed, 0 skipped, took 6.27 seconds (xUnit.net 2.1.0 build 3179).
```

**Pull request closed without merging**
