### PR TITLE
Update Debugger nuspecs

### PR DESCRIPTION
**Pull request by tmat**
Fix the layout of debugger packages to be netstandard compatible.

Corresponding [VSO PR](https://mseng.visualstudio.com/VS%20IDE%20-%20Connected%20Experience/_git/VsixTemplates/pullrequest/239199)

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar

**Comment by tmat** [comment]
@jaredpar  Since we need to publish packages from ```vsucorediag``` branch for upcoming EnC work I'm thinking we should use version ```#####-vscordiag``` instead of ```####-alpha``` to differentiate packages publishing binaries from d15rel. Sounds reasonable?

**Comment by jaredpar** [comment]
That's fine by me.

**Comment by jaredpar** [comment]
Can you update the README.md in the same file to list the suffix which should be used for the various branhces being consumed?

**Pull request merged**
