### PR TITLE
Merge dev15.6.x into dev15.6.x-vs-deps

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Merging last changes prior to final insertion.

### CODE REVIEW

**Comment by heejaechang** [comment]
retest windows_debug_unit64_prtest please

**Comment by heejaechang** [comment]
looking into integration test failure.

**Comment by heejaechang** [comment]
dump has nothing useful. building locally to run test

**Comment by heejaechang** [comment]
passed locally. machine issue?

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please

**Comment by heejaechang** [comment]
okay, found reason. integration test fails for d15.5 drop. it only works for d15.6stg drop. due to this

----- Catalog construction errors -----
Error #1
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "Microsoft.VisualStudio.ConnectedServices.MobileApps.Handlers.CordovaMobileAppHandler". ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.ApacheCordovaTools.Definitions.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeFieldInfo fieldHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.get_FieldType()
   at Microsoft.VisualStudio.Composition.ReflectionHelpers.GetMemberType(MemberInfo fieldOrPropertyOrType)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscoveryV1.AddImportsFromMembers(PropertyInfo[] declaredProperties, FieldInfo[] declaredFields, TypeRef partTypeRef, IList`1 imports)
   at Microsoft.VisualStudio.Composition.AttributedPartDiscoveryV1.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.CombinedPartDiscovery.CreatePart(Type partType, Boolean typeExplicitlyRequested)
   at Microsoft.VisualStudio.Composition.PartDiscovery.<>c__DisplayClass27_0.<CreateDiscoveryBlockChain>b__0(Type type)
   --- End of inner exception stack trace ---
----- CompositionError level 1 ------
Microsoft.VisualStudio.ProjectServices.DesignTimeBuildService.DesignTimeBuildHost: expected exactly 1 export of Microsoft.VisualStudio.ProjectServices.IVsDesignTimeBuildHost but found 0.
   part definition Microsoft.VisualStudio.ProjectServices.DesignTimeBuildService

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
hmmm.. still can't enqueue new integration test.

**Comment by jasonmalinowski** [comment]
@heejaechang Integration tests can't run in -vs-deps since we don't have a new image yet for the latest command handler changes. We need to fix that.

Why they are running here I don't know...those were supposed to have been disabled.

**Comment by heejaechang** [comment]
thank you

**Pull request merged**
