### PR TITLE
Extend Linux CI Support

### PR DESCRIPTION
**Pull request by jaredpar**
Now that Mac and Linux are using the same version of Mono, we can extend
the Linux support to match that of Mac.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dpoeschl, @agocke, @VSadov, @jasonmalinowski

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
@jaredpar, slightly related. Some parts of linux build instructions seems outdated: https://github.com/dotnet/roslyn/wiki/Linux-Instructions. It indicates that the instructions will be updated frequently, but it's been a while. Also, will it make sense to move instructions in `docs/` directory like what @richlander did in coreclr repo?

**Comment by jaredpar** [comment]
@jasonwilliams200OK thanks for pointing that out.  

The instructions got a bit out of date because I had to switch off cross platform work for a few weeks.  A couple of shipping bugs and role changes took priority.  The recent updates were driven by some infrastructure needs and I had forgotten to update the docs as a part of the work.  I just updated them so they should be current (please let me know if they aren't).  

Note: the cross platform work will probably be picking up again here in a few weeks.  Still have some other work that has priority but hopefully it will be winding down here in a bit.  

As for moving to `/docs`.  That is something we are looking into doing.  I really like the idea of `/docs` because then I can version the docs with the code repo.  Additionally it would allow for customers to send us PRs to fix our docs.

**Comment by jasonwilliams200OK** [comment]
@jaredpar, thanks for quickly updating the instructions. The Azure Drops idea in updated docs is pretty awesome! It would probably be a good idea to have similar drops for CoreCLR where user need to build the framework for FBSD, Linux or OSX and require Windows ([CoreCLR FreeBSD instructions | section: building the framework](https://github.com/dotnet/coreclr/blob/2ec6b94f7e90353f8cda32ddee9adf5e7206529c/Documentation/freebsd-instructions.md#build-the-framework-)). Folks using bare metal install of other operating systems, often don't have access to Windows dev machine. (@saper, @josteink) :)

:+1: for refactoring the manuals to `/docs` (or `/Documentation`; to keep the folder on top of source tree => ASCII order). @ajensenwaud has added initial FreeBSD support https://github.com/dotnet/roslyn/pull/2634. There still appear to be some caveats (https://github.com/dotnet/roslyn/issues/2844), but hopefully at some point soon, they will have complete instructions to build
Roslyn on FreeBSD. :crossed_flags:

**Pull request merged**
