### PR TITLE
Test VS SDK fixes against Roslyn 

### PR DESCRIPTION
**Pull request by tannergooding**
…t dependencies."

This reverts commit 4231a466c1317186f5ae67dd6694c0e6fdf16f0a.

### CODE REVIEW

**Comment by jaredpar** [comment]
Can we add the VS SDK change to this PR?  Basically want to run it in a loop so that we can see the Jenkins failures.

**Comment by tannergooding** [comment]
I'll get to it when I have some time; Otherwise, feel free to update my branch. Maintainers have edit privileges.

**Comment by jaredpar** [comment]
retest windows_debug_vs-integration_prtest please
retest windows_release_vs-integration_prtest please

**Comment by jaredpar** [comment]
retest this please

**Comment by jaredpar** [comment]
test this please

**Comment by tannergooding** [comment]
@jaredpar, is this still needed or am I good to close?

**Comment by jaredpar** [comment]
Go ahead and close.  Don't delete the branch yet though please.  I'm going to grab this code soon for a different test.

**Pull request closed without merging**
