### PR TITLE
added column filter to suppression column so that it doesnt count in …

### PR DESCRIPTION
**Pull request by heejaechang**
…error/warning count.

this fixes devdiv bug #150906

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani @basoundr can you take a look?

**Comment by mavasani** [comment]
This requires a follow up change for error list team to remove special casing this column as entry filter definition. You may want to ask David to do so once your change goes in. Thanks for fixing this Heejae.

**Comment by mavasani** [comment]
LGTM, but you may want DavidPu to sign off.

**Comment by heejaechang** [comment]
@mavasani will do.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure this is another check in blocked by update 1.

the test failure is due to missing type only exist in Update 1

**Comment by heejaechang** [comment]
retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/3392/
// Retest reason: jenkins moved to update 1

**Pull request merged**
