### PR TITLE
Draft

### PR DESCRIPTION
**Pull request by Youssef1313**
I think anything used from this project outside the Compilers layer makes more sense to be in a shared project.
Going to see how many things are going to break, and depending on that I'll either try to proceed or close if too much is broken.

This is not the only project reference I think it should be refactored, but picked it as a start to see how things can go.

### CODE REVIEW

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Before trying to proceed, can you confirm whether this is something you want?

Also tagging @jaredpar since it will require factoring out few types from `Compilers\Test\Core` into a shared project.

The end goal is to have more lightweight project references over the whole codebase, which I'm aware is very hard and is unlikely to *completely* get to. I started with test projects since they will be easier than product code.

**Comment by Youssef1313** [comment]
> > The end goal is to have more lightweight project references
> 
> Can you give an example of what yo mean by 'lightweight project references'? Also, tagging @sharwell .

Some projects have heavy dependencies unnecessarily. If this is fixed, building single projects can become noticably faster.

This is not significant for CI time, but significant for working locally.

**Comment by sharwell** [comment]
> I think anything used from this project outside the Compilers layer makes more sense to be in a shared project.

I don't agree with this premise. I see no value in test layering.

**Comment by Youssef1313** [comment]
> > I think anything used from this project outside the Compilers layer makes more sense to be in a shared project.
> 
> I don't agree with this premise. I see no value in test layering (I'm somewhat unique on this front, but I've just never seen it pay dividends).

I'm okay with closing if others think the same.

**Comment by jaredpar** [comment]
> I don't agree with this premise. I see no value in test layering (I'm somewhat unique on this front, but I've just never seen it pay dividends).

I tend to agree with this. Some amount of layering is sensible and beneficial. In general though I think we've overlayered in Roslyn. There are several libraries I wish I had more time to merge into existing ones.

**Comment by Youssef1313** [comment]
Thanks. I'm going to close.

> There are several libraries I wish I had more time to merge into existing ones.

@jaredpar I may try to work on that if it's something you think is beneficial. Let me know which libraries/projects you meant and I will try to give a look. Thanks.

**Pull request closed without merging**
