### PR TITLE
Allow languages to specify if they want completion to block or not.  

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/Microsoft/visualfsharp/issues/1825

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by rchande** [comment]
👍

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest windows_eta_open_prtest  please

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz This change exist to help out F# completion.  F# completion can take quite a long time due to a nifty feature they have where arbitrary code (including async-network code) can run during completion.

Roslyn's impl was designed around the idea that completion computation would always be fast, and so blocking would not be a problem.  We relax this design here so that languages like F# can say that they are slower and should not block.

**Comment by MattGertz** [comment]
Approved for RC.3.

**Comment by CyrusNajmabadi** [comment]
@dsyme @OmarTawfik You will be able to control this by setting "CompletionOptions.BlockForCompletionItems" to 'false' for the TypeScript language.

**Comment by OmarTawfik** [comment]
cc @brettfo

**Pull request merged**
