### PR TITLE
Revert "Load analyzers and generators in isolated ALCs in our OOP process"

### PR DESCRIPTION
**Pull request by 333fred**
Reverts dotnet/roslyn#74780. Running into exceptions in speedometer and blocking VS insertions.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
What exceptions are you running into?

**Comment by CyrusNajmabadi** [comment]
@dibarbet as well.  We sent this pr through speedometer, and it passed. So it's unclear why we'd hit an issue now.

**Comment by 333fred** [comment]
> @dibarbet as well. We sent this pr through speedometer, and it passed. So it's unclear why we'd hit an issue now.

Unfortunately, your validation PR didn't pass speedometer. There was an infra issue, and it didn't run:

image


There are lots of filenotfound and unauthorizedaccess exceptions when attempting to load various generators in speedometer, we're reverting for expediency.

**Comment by CyrusNajmabadi** [comment]
I'm super confused.  I got a pass notification. I even copied it...  Ugh.

**Comment by jjonescz** [comment]
> I'm super confused. I got a pass notification. I even copied it... Ugh.

That was just the DDRIT test run passing, not the Speedometer, unfortunately.

**Pull request merged**
