### PR TITLE
Remove locale-dependence in RealParserTests

### PR DESCRIPTION
**Pull request by gafter**
This addresses part of #7883 

@dotnet/roslyn-compiler Please review; test-only changes

### CODE REVIEW

**Comment by cston** [comment]
LGTM

**Comment by davkean** [comment]
:+1:

**Comment by AlekseyTs** [comment]
LGTM

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2686/
// Retest reason: Github timed out.

**Comment by TyOverby** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet-bot test this please

**Comment by bkoelman** [comment]
LGTM, this fixes all failing tests on my machine (culture nl-NL).

**Pull request merged**
