### PR TITLE
Add documentation on rule set files

### LINKED ISSUE #1073: Ruleset file format should be specified
The syntax and semantics of the ruleset file should be added to our docs.

### PR DESCRIPTION
**Pull request by tmeschter**
Add documentation describing the relevant portions of the .ruleset file
format.

Fixes #1073.

### CODE REVIEW

**Comment by tmeschter** [comment]
@gafter Is this what you had in mind in the way of documentation?

@ManishJayaswal @srivatsn @mavasani @shyamnamboodiripad @heejaechang @jmarolf Could you review as well, please?

@billchi-ms @zoepetard @jepetty @daking2014 You may be interested as well.

**Comment by srivatsn** [comment]
LGTM

**Comment by jmarolf** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
LGTM

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by gafter** [comment]
Awesome! Please also mention the command-line flag that relates this file format to the behavior of the compilers.

LGTM.

**Comment by tmeschter** [comment]
@gafter Good catch. I've added that information.

**Pull request merged**
