### PR TITLE
Improve `CSharpSyntaxFacts.IsValidIdentifier` performance

### PR DESCRIPTION
**Pull request by Youssef1313**
The simplified implementation is much faster since it's a very simple for loop.

<details> 
  <summary>Outdated benchmark results - see comment below</summary>

```csharp
using Bench;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

BenchmarkSwitcher.FromAssembly(typeof(Benchmarks).Assembly).Run(args);

namespace Bench
{
    public class Benchmarks
    {
        [Benchmark]
        public void Fast()
        {
            _ = SyntaxFacts.IsValidIdentifier("MyIdentifierName");
        }

        [Benchmark]
        public void Slow()
        {
            var token = SyntaxFactory.ParseToken("MyIdentifierName");
            _ = this.IsIdentifier(token) && !token.ContainsDiagnostics && token.ToString().Length == "MyIdentifierName".Length;
        }

        private bool IsIdentifier(SyntaxToken token)
            => token.RawKind == 8508 ;

    }
}

```

```
| Method |      Mean |    Error |   StdDev |
|------- |----------:|---------:|---------:|
|   Fast |  34.13 ns | 0.124 ns | 0.103 ns |
|   Slow | 430.47 ns | 2.279 ns | 2.131 ns |
```

~~But I'm worried if there are any behavioral differences.~~ (There was, but fixed now)

</details>

### CODE REVIEW

**Comment by Youssef1313** [comment]
There is a behavioral difference for keywords. I fixed that and benchmarked again:

```csharp
using Bench;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

BenchmarkSwitcher.FromAssembly(typeof(Benchmarks).Assembly).Run(args);

namespace Bench
{
    public class Benchmarks
    {
        [Benchmark]
        public void Fast()
        {
            _ = SyntaxFacts.IsValidIdentifier("MyIdentifierName") && SyntaxFacts.GetKeywordKind("MyIdentifierName") == SyntaxKind.None;
        }

        [Benchmark]
        public void Slow()
        {
            var token = SyntaxFactory.ParseToken("MyIdentifierName");
            _ = this.IsIdentifier(token) && !token.ContainsDiagnostics && token.ToString().Length == "MyIdentifierName".Length;
        }

        private bool IsIdentifier(SyntaxToken token)
            => token.RawKind == 8508 ;

    }
}
```

```
| Method |      Mean |    Error |   StdDev |
|------- |----------:|---------:|---------:|
|   Fast |  49.94 ns | 0.440 ns | 0.390 ns |
|   Slow | 420.78 ns | 7.955 ns | 7.051 ns |
```

**Comment by Youssef1313** [comment]
Failures seems unrelated. Closing and reopening for new build

**Comment by Youssef1313** [comment]
Updated benchmark results:

// * Summary *

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19042.1466 (20H2/October2020Update)
AMD Ryzen 5 PRO 4650G with Radeon Graphics, 1 CPU, 12 logical and 6 physical cores
.NET SDK=6.0.100
  [Host]     : .NET 5.0.13 (5.0.1321.56516), X64 RyuJIT
  DefaultJob : .NET 5.0.13 (5.0.1321.56516), X64 RyuJIT


| Method | IdentifierName |        Mean |     Error |     StdDev |
|------- |--------------- |------------:|----------:|-----------:|
|   Fast |                |   0.2360 ns | 0.0152 ns |  0.0127 ns |
|   Slow |                | 268.4553 ns | 5.2864 ns |  6.2931 ns |
|   Fast |          `12345` |   4.0776 ns | 0.0536 ns |  0.0447 ns |
|   Slow |          `12345` | 493.5482 ns | 7.2858 ns |  6.8152 ns |
|   Fast |          `@ABCD` |  22.8332 ns | 0.3939 ns |  0.3492 ns |
|   Slow |          `@ABCD` | 391.0935 ns | 7.7010 ns | 11.7603 ns |
|   Fast |         `@class` |  23.6367 ns | 0.2791 ns |  0.2330 ns |
|   Slow |         `@class` | 388.2642 ns | 4.0699 ns |  3.8070 ns |
|   Fast |           `ABCD` |  16.8198 ns | 0.1633 ns |  0.1448 ns |
|   Slow |           `ABCD` | 365.6708 ns | 1.5656 ns |  1.4645 ns |
|   Fast |          `class` |  27.3430 ns | 0.1829 ns |  0.1711 ns |
|   Slow |          `class` | 356.6230 ns | 3.4552 ns |  3.0629 ns |

```
// * Hints *
Outliers
  Benchmarks.Fast: Default -> 2 outliers were removed (1.78 ns, 1.78 ns)
  Benchmarks.Slow: Default -> 1 outlier  was  removed (297.51 ns)
  Benchmarks.Fast: Default -> 2 outliers were removed (5.77 ns, 5.92 ns)
  Benchmarks.Fast: Default -> 1 outlier  was  removed (25.76 ns)
  Benchmarks.Fast: Default -> 2 outliers were removed (26.26 ns, 26.67 ns)
  Benchmarks.Fast: Default -> 1 outlier  was  removed (19.18 ns)
  Benchmarks.Fast: Default -> 1 outlier  was  detected (28.28 ns)
  Benchmarks.Slow: Default -> 1 outlier  was  removed (368.61 ns)

// * Legends *
  IdentifierName : Value of the 'IdentifierName' parameter
  Mean           : Arithmetic mean of all measurements
  Error          : Half of 99.9% confidence interval
  StdDev         : Standard deviation of all measurements
  1 ns           : 1 Nanosecond (0.000000001 sec)
```

Benchmark code:

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

public class Program
{
    public static void Main(string[] args)
    {
        var summary = BenchmarkRunner.Run(typeof(Program).Assembly);
    }
}


namespace Bench
{
    public class Benchmarks
    {
        [Params("", "ABCD", "@ABCD", "class", "@class", "12345")]
        public string IdentifierName { get; set; }

        [Benchmark]
        public void Fast()
        {
            var identifier = IdentifierName;
            if (identifier.Length == 0)
            {
                return;
            }

            if (identifier[0] == '@')
            {
                _ = SyntaxFacts.IsValidIdentifier(identifier.Substring(1));
                return;
            }
            else
            {
                _ = SyntaxFacts.IsValidIdentifier(identifier) && SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None;
                return;
            }
        }

        [Benchmark]
        public void Slow()
        {
            var identifier = IdentifierName;
            var token = SyntaxFactory.ParseToken(identifier);
            _ = this.IsIdentifier(token) && !token.ContainsDiagnostics && token.ToString().Length == identifier.Length;
        }

        private bool IsIdentifier(SyntaxToken token)
            => token.RawKind == 8508;

    }
}
```

**Comment by Youssef1313** [comment]
@sharwell Can you take a look please? Thanks!

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Woudl love to see the memory benchmark as well :)

**Comment by CyrusNajmabadi** [comment]
test failures look legitimate.

**Comment by Youssef1313** [comment]
Ahh, never knew the following is valid:

```csharp
using System;

var \u0061 = "ABC";
Console.WriteLine(a.ToString());
```

Will look into fixing this and re-benchmark with memory diagnoser

**Comment by Youssef1313** [comment]
@CyrusNajmabadi It's probably not trivial to do.

Here is the logic around it in the compiler:

https://github.com/dotnet/roslyn/blob/7b6b57276d7a27198956beb3a86d7d0db34a0829/src/Compilers/CSharp/Portable/Parser/Lexer.cs#L1697-L1705

A possible solution is to do the following:

```csharp
            // Fast path
            if (identifier.Length == 0)
            {
                return false;
            }

            if (identifier[0] == '@')
            {
                if (SyntaxFacts.IsValidIdentifier(identifier.Substring(1)))
                        return true;
            }
            else
            {
                if (SyntaxFacts.IsValidIdentifier(identifier) && SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None)
                        return true;
            }

            // Slow path. This path handles everything, but the above code is a common path and is much faster.
            var token = SyntaxFactory.ParseToken(identifier);
            return this.IsIdentifier(token) && !token.ContainsDiagnostics && token.ToString().Length == identifier.Length;
```

But I'm not sure it's worth complicating it. And I don't recall if there was specific reason I optimized this for, or if it was random :smile:

What do you think?

**Comment by Youssef1313** [comment]
image

@CyrusNajmabadi

**Comment by Youssef1313** [comment]
image

**Comment by CyrusNajmabadi** [comment]
So, do we actually need to make any changes here? Was this motivated by a real world issue?

**Comment by Youssef1313** [comment]
I don't really recall why I tried to optimize this.

I looked at the callers now, and I don't think any is a hot path (would like you to take a quick look too). But still the percentage of improvement is too high for the common case (valid identifier).

I'm hesitant and fine either with merging or closing.

**Comment by Youssef1313** [comment]
I'm going to close as I'm not seeing a real affected scenario. If this method has proven any performance hits in future, this can be reconsidered.

**Pull request closed without merging**
