### PR TITLE
Instance extensions - flesh out code gen for iterator/async methods.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Relates to test plan https://github.com/dotnet/roslyn/issues/66722

### CODE REVIEW

**Review by jjonescz — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review

**Comment by AlekseyTs** [comment]
@jcouv, @dotnet/roslyn-compiler For the second review

**Review by chsienki — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@jcouv Please review

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Pull request merged**
