### PR TITLE
[AskMode] Add a command handler for pasting from interactive window

### PR DESCRIPTION
**Pull request by genlu**
- The expected behavior is, when pasting text copied from interactive window into CS/VB code editor, the prompt should be dropped. See #5212.
- `InteractivePasteCommandHandler` is created under `EditorFeatures`. While the actual paste depends on `InteractiveWindow`, special care is taken to avoid loading that assembly in VS unless necessary.
- Changes are validated by both unit tests and manual tests.

Ported from PR against master https://github.com/dotnet/roslyn/pull/6289

@dotnet/interactive @dotnet/roslyn-ide

### CODE REVIEW

**Comment by dpoeschl** [comment]
Please add review comments to #6289, not this one (right, Gen?).

**Comment by genlu** [comment]
Yes, for any comments, please add to https://github.com/dotnet/roslyn/pull/6289

**Comment by genlu** [comment]
The test failure in InteractiveSessionTests is a known issue https://github.com/dotnet/roslyn/issues/6291

**Comment by ManishJayaswal** [comment]
:+1: pending the following:
passing of tests ( which should now be fixed)
Validating that interactive assemblies are not getting loaded till paste operation is done in vsuml build.

**Comment by davkean** [comment]
Closing and reopening to see if you pick up the latest changes, you might be hitting: #6356

**Comment by MattGertz** [comment]
Approved pending successful test completion.

**Pull request merged**
