### PR TITLE
Removing WpfFact from Analyzer and Codefix tests

### PR DESCRIPTION
**Pull request by jmarolf**
Removing WpfFact from Analyzer and Codefix tests as they don't use any editor apis.

1281 WpfFact tests removed, 21152 to go.

### CODE REVIEW

**Comment by jmarolf** [comment]
test unit please

**Comment by jmarolf** [comment]
test win please

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
can you branch off of my change in "waitAndGetResult"?  Otherwise this will be a merge conflict from hell.

**Comment by jmarolf** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by jmarolf** [comment]
@CyrusNajmabadi There shouldn't be conflicts between our branches, you aren't changing the same lines.  git **should** be able to auto merge those.

**Comment by jasonmalinowski** [comment]
Why the modification of NuGet in this change?

**Comment by jasonmalinowski** [comment]
And doing some fun with git show + grep, I can confirm that this only consists of Fact -> WpfFact other than:

- The change to NuGet.exe
- A casing change within SpellcheckTests.vb
- Blank lines being adjusted in SuppressionTests.vb

**Comment by jmarolf** [comment]
retest win please

**Comment by jmarolf** [comment]
retest prtest/win/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
this is a merge conflict from hell.  :(

**Pull request merged**
