### PR TITLE
Fix for #5760

### PR DESCRIPTION
**Pull request by bkoelman**
I scanned for other occurences of "?.Kind()", but found none.

### CODE REVIEW

**Comment by bkoelman** [comment]
@CyrusNajmabadi I've updated this PR, thanks for review.

**Comment by CyrusNajmabadi** [comment]
Lgtm!

    -- Cyrus
________________________________

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit32 please

**Comment by CyrusNajmabadi** [comment]
@bkoelman Once all tests pass, feel free to merge!

**Comment by bkoelman** [comment]
I'd love to, but I am not allowed to merge:

`Only those with write access to this repository can merge pull requests.`

**Comment by CyrusNajmabadi** [comment]
I'll merge it for you then!

**Comment by tannergooding** [comment]
ok to test

**Comment by bkoelman** [comment]
retest prtest/win/dbg/unit32 please

**Pull request merged**
