### PR TITLE
Fix roundtripping of generic error types.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/39936

Fixes OOP crash when rountripping user code in error.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Would likely want to take this for 16.7

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Do you want to just target 16.7 with this now?

**Comment by jinujoseph** [comment]
@CyrusNajmabadi lets retarget to 16.8.P1 branch ..I will get the approval

**Comment by CyrusNajmabadi** [comment]
This is against 16.8p1 now.  @jasonmalinowski  Does that automatically merge back into master?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Yep, we auto-merge for you.

**Pull request merged**
