### PR TITLE
Update xunit to 2.4.1-pre.build.4059

### PR DESCRIPTION
**Pull request by tmat**
Version 2.4.0 has Portable PDBs enabled on .NET Framework:

```xml
<runtime>
    <AppContextSwitchOverrides value="Switch.System.Diagnostics.IgnorePortablePDBsInStackTraces=false" />
  </runtime>
```

Version 2.4.1-pre.build.4059 has some additional bug fixes.

### CODE REVIEW

**Comment by sharwell** [comment]
I'm with @jasonmalinowski - why do we need a pre-release?

**Comment by tmat** [comment]
Standardizing on the same version across .NET Core repos.

**Comment by tmat** [comment]
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/DefaultVersions.props#L58

**Comment by jasonmalinowski** [comment]
@tmat What happens then if we need to upgrade to something higher?

**Comment by tmat** [comment]
@jasonmalinowski We can override the default version.

**Comment by tmat** [comment]
@jcouv FYI

**Pull request merged**
