### PR TITLE
fixed live diagnostic argId leak

### PR DESCRIPTION
**Pull request by heejaechang**
it looks like my previous update 2 leak fix for Task introduced argId leaks. since this was much smaller leak than before I didn't notice it being leaked.

this is port of #10715

### CODE REVIEW

**Comment by heejaechang** [comment]
@MattGertz @natidea can I get approval for microupdate for this bug?

**Comment by MattGertz** [comment]
Approved pending CRs/tests.

**Comment by srivatsn** [comment]
👍 Is there a PR out against master for this? Make sure to check this in to master as well.

**Comment by heejaechang** [comment]
it is already in for master

**Comment by jasonmalinowski** [comment]
@srivatsn, @heejaechang, just as an FYI: although I highly encourage microupdate fixes to get checked into somewhere that will get extra coverage, we will ensure that these flow back to master (eventually).

**Pull request merged**
