### PR TITLE
Guarding rename to check if a node is a type that can be expanded.

### PR DESCRIPTION
**Pull request by jmarolf**
Fixes https://github.com/dotnet/roslyn/issues/5035
Fixes https://github.com/dotnet/roslyn/issues/2445

Tagging @dotnet/mlangideTeam members are private

### CODE REVIEW

**Comment by jmarolf** [comment]
test linux please

**Comment by jmarolf** [comment]
test unit64 please

**Comment by balajikris** [comment]
LGTM.

**Comment by Pilchie** [comment]
LGTM too

**Pull request merged**
