### PR TITLE
fixing up stack trace logic as per Cyrus' suggestions

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by jmarolf** [comment]
@CyrusNajmabadi @dotnet/roslyn-ide

**Comment by tmat** [comment]
We have similar code in scripting BTW.

**Comment by jmarolf** [comment]
@tmat could you point me at it? no reason to have this duplicated.

**Comment by tmat** [comment]
http://source.roslyn.io/#Microsoft.CodeAnalysis.Scripting/Hosting/ObjectFormatter/CommonObjectFormatter.cs,57

We might want to factor the implementation out somehow, so it can be shared. Perhaps into a shared source project.

**Comment by tmat** [comment]
It might also be sufficiently specific to scripting that sharing it won't make much sense.

**Comment by tmat** [comment]
p[erhaps the best would be to share a few static helpers via a linked file.

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
I'll see what I can combine with CommonObjectFormatter in a future PR.

**Pull request merged**
