### PR TITLE
Disable VS Integration tests for investigations.

### PR DESCRIPTION
**Pull request by brettfo**
Tests can still be manually triggered with "test vsintegration please"

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet-bot test {test_name} please

**Comment by TyOverby** [comment]
@dotnet-bot test windows_release_vs-integration_prtest  please

**Comment by brettfo** [comment]
PR tests are going to fail, hence this PR to disable them.

**Comment by brettfo** [comment]
@jaredpar

**Pull request closed without merging**
