### PR TITLE
changed sign method from vsix to vsixSHA2

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@tmeschter @ManishJayaswal @tannergooding can you take a look please.

**Comment by tmeschter** [comment]
@heejaechang I expect we need to port this to the stabilization branch, too.

**Comment by tmeschter** [comment]
LGTM

**Comment by ManishJayaswal** [comment]
LGTM. @tmeschter @heejaechang  yes we will need to port this to stabilization branch. HeeJae can we have a PR for stabilization that we can review at shiproom today?

**Pull request merged**
