### PR TITLE
Add various fail fasts for flakiness [master]

### PR DESCRIPTION
**Pull request by jasonmalinowski**
*DO NOT MERGE THIS.* (I think.)

This is adding various hard failures to see if we can hit stuff in Jenkins.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest this please. (I am intentionally spamming the queue so we can have more runs to look for flakiness.)

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest this please. (I am intentionally spamming the queue so we can have more runs to look for flakiness.)

**Comment by davkean** [comment]
test this please

All machines went offline due to network outtage.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please. (Retrying to trigger the flakiness.)

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by jmarolf** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by jmarolf** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by jasonmalinowski** [comment]
Closing in favor of #9492 which is something we'll actually want to merge.

**Pull request closed without merging**
