### PR TITLE
Skip an IDE test that fails in master.

### PR DESCRIPTION
**Pull request by gafter**
Related to #11980 

@dotnet/roslyn-ide Please have a look. Blocking some compiler work.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@cston, @CyrusNajmabadi, @rchande, how was this failing in master?

**Comment by rchande** [comment]
My recent PR (https://github.com/dotnet/roslyn/pull/11874) was green. @CyrusNajmabadi ?

**Comment by gafter** [comment]
I'll post the failure mode here in the morning.

**Comment by gafter** [comment]
This test

```vb
        <WorkItem(546208, "http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/546208")>
        <WpfFact, Trait(Traits.Feature, Traits.Features.Completion)>
        Public Async Function SelectKeywordFirst() As Task
            Using state = TestState.CreateVisualBasicTestState(
                              <Document>
Class C
    Sub M()
        $$
    End Sub

    Sub GetType()
    End Sub
End Class
                              </Document>)

                state.SendTypeChars("GetType")
                Await state.WaitForAsynchronousOperationsAsync()
                Await state.AssertSelectedCompletionItem("GetType", VBFeaturesResources.GettypeFunction + vbCrLf +
                    ReturnsSystemTypeObject + vbCrLf +
                    $"GetType({Typename}) As Type")
            End Using
        End Function
```

consistently fails this way on my machine

```none
------ Test started: Assembly: Roslyn.Services.Editor.UnitTests2.dll ------

Unknown .NET Framework Version: v4.6
Test 'Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.SelectKeywordFirst' failed:
	Assert.Equal() Failure
          ↓ (pos 0)
Expected: GetType function\r\nReturns a System.Type o···
Actual:   Sub C.GetType()
          ↑ (pos 0)
	IntelliSense\TestState.vb(270,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.TestState.VB$StateMachine_36_AssertSelectedCompletionItem.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
	IntelliSense\VisualBasicCompletionCommandHandlerTests.vb(1843,0): at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_88_SelectKeywordFirst.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

0 passed, 1 failed, 0 skipped, took 9.37 seconds (xUnit.net 2.1.0 build 3179).
```

**Pull request merged**
