### PR TITLE
Avoid depencency on the exact order of AssemblyRefs in tests

### LINKED ISSUE #6291: InteractiveSessionTests Are Failing
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.HostObjectAssemblyReference3
Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.HostObjectAssemblyReference2

are failing, see http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/130/

introduced with https://github.com/dotnet/roslyn/commit/d2bfd11ddada278f3343d23746b9c3c2f18e3312

### PR DESCRIPTION
**Pull request by tmat**
Fixes #6291

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/interactive

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure

**Comment by brettfo** [comment]
:shipit: pending passing tests

**Comment by genlu** [comment]
:+1:

**Comment by cston** [comment]
LGTM

**Comment by davkean** [comment]
We were seeing this in master, too, right?

**Comment by brettfo** [comment]
I did the cheap update in `master` last week in PR #6283 so it's currently passing, but once this PR is merged, the changes should follow the normal flow from `stabilization` -> `master`.

**Comment by tmat** [comment]
Failed due to PEVerify issue. Merging anyways to unblock CI.

**Pull request merged**
