### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160227-160016
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160227-160016 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by drognanar** [comment]
retest vsi please

**Comment by drognanar** [comment]
retest prtest/win/vsi/p2 please

**Comment by drognanar** [comment]
retest prtest/win/vsi/p2 please
retest prtest/win/vsi/p3 please
// Previous failures:
// http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/357/
// http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/376/

**Comment by davkean** [comment]
@drognanar It looks like these failures are real failures.

**Comment by drognanar** [comment]
retest prtest/win/vsi/p2 please
retest prtest/win/vsi/p3 please

**Comment by drognanar** [comment]
retest prtest/win/vsi/p3 please

**Pull request merged**
