### PR TITLE
Move more features over to Solution.Services from Workspace.Services (1)

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
We intend to add `solutionInstance.Workspace` to the banned api list for roslyn itself.  It's highly problematic for OOP, as we have to try to replicate that concept, which isn't something sensical in that world.  First, OOP cannot mutation things, so exposing the mutable workspace doesn't make much sense.  Second, in VS you can have many workspaces, but in OOP we map that all back to one, which means we don't have a proper representation of VS state (for example, where you might have the VSWorkspace and the Metadata-as-source workspace).  This means those features either cannot use OOP, or they try to use OOP and can end up with non-sensical results.

This is a series of PRs to get us off of that API so we can move to a much cleaner and simpler OOP model for the solution and services.

### CODE REVIEW

**Comment by genlu** [comment]
There seems to overlap with a few other PRs, I will wait for them to be merged so the diff can be reviewed more easily.

**Comment by CyrusNajmabadi** [comment]
@genlu  you can start with https://github.com/dotnet/roslyn/pull/62911

**Comment by CyrusNajmabadi** [comment]
This is ready for review.

**Review by tmat — APPROVED** [review]
:shipit:

**Pull request merged**
