### PR TITLE
Removing redundancies in conditionals and useless string.format

### PR DESCRIPTION
**Pull request by tvsonar**

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet-bot retest roslyn_ignore_this_test_eta2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_ignore_this_test_eta2/49/
// Retest reason:

**Comment by gafter** [comment]
@dotnet-bot retest roslyn_ignore_this_test_eta2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_ignore_this_test_eta2/49/
// Retest reason:

**Comment by gafter** [comment]
@tvsonar Can you please bring this PR up to date with the master branch?

**Comment by tvsonar** [comment]
Done. @gafter

**Comment by gafter** [comment]
LGTM

@dotnet/roslyn-ide @dotnet/roslyn-interactive Can I please have a review from the IDE and interactive teams? This is a tiny community-contributed cleanup.

**Comment by jmarolf** [comment]
👍 From IDE

**Comment by genlu** [comment]
👍

**Pull request merged**
