### PR TITLE
Force compiler apps to ref netstadard2.0 version of SCI and SRM

### PR DESCRIPTION
**Pull request by genlu**
Address the mvid mismatch error in ibcmerge https://github.com/dotnet/roslyn/issues/53197

### CODE REVIEW

**Review by tmat — APPROVED** [review]

**Review by JoeRobich — APPROVED** [review]

**Comment by genlu** [comment]
@RikkiGibson Any idea where I can find more details about this error? It doesn't mention which nupkg/vsix

> Processing NuPkg and VSIX files ... FAILED
Asset System.Collections.Immutable.dll exists at two different versions
	Hash 1: 5B-9F-4E-04-5B-D0-94-1F-35-66-5D-E2-3F-2B-94-03
	Hash 2: C5-98-08-0F-A7-77-D6-E6-3D-FD-03-70-E9-7E-C8-F3
Asset System.Reflection.Metadata.dll exists at two different versions
	Hash 1: 45-5C-33-F3-1D-71-82-E0-BA-1E-59-BA-5A-4B-20-5D
	Hash 2: C4-EA-65-BD-80-2F-1C-CD-3E-A2-AD-18-41-FD-85-C2

**Comment by RikkiGibson** [comment]
I can see that the error message is produced here: https://github.com/dotnet/roslyn/blob/315c2e149ba7889b0937d872274c33fcbfe9af5f/src/Tools/BuildBoss/CompilerNuGetCheckerUtil.cs#L330

It's not completely obvious to me how to fix it, though. Is it possible that csi is now referencing both the net461 and netstandard2.0 versions of the packages simultaneously? Digging into the binlog could help here.

**Comment by genlu** [comment]
@jaredpar Could you please take a look at this? Trying to address some ibcmerge issue caused by shipping both net461 and netstadard2.0 version of SCI and SRM in PrivateAssemblies and MSBuild folder in VS

**Comment by jaredpar** [comment]
This change is essentially patching over a bug in how we insert / profile by creating a non-standard deployment application. Basically we're breaking all the rules of how binaries are deployed by doing this. 

I don't think this is the right answer here. My instinct would be to first turn off opt-prof for these assemblies than making our build even harder and more complex.

**Comment by genlu** [comment]
@jaredpar OK, that's fair. Alternatively we can fix Arcade to apply ibc data only to matching binary. But in this specific case, given that we have data for both net461 and netstandard2.0 binaries, I think simply ignoring mismatched ibc files when calling ibcmerge wouldn't even cause any loss of coverage. 

@JoeRobich Let's just use the new -ignoremismatchmvid switch w/o making anything here.

**Comment by JoeRobich** [comment]
> Let's just use the new -ignoremismatchmvid switch w/o making any change to what we ship.

@genlu Is this a change that you've already made?

**Pull request closed without merging**
