### PR TITLE
Make passing of CompletionItemRules more explicit.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
@rchande Can you take a look?  Also @dotnet/roslyn-ide please look.

This just tries doing a bit of tidying up around completion.  There's still work i'd like to do.  But it will likely have to be in time i can fit in while being tiger.

**Comment by DustinCampbell** [comment]
@Pilchie: FYI that @CyrusNajmabadi chatted with me about a small behavior change caused by this PR. Essentially, we'll no longer display EnumMember glyphs a list that we've built using the `completionlist` XML doc tag in VB. Instead, we use the actual glyphs of the members. I'm personally fine with this change. Are you OK with it?

**Comment by CyrusNajmabadi** [comment]
Main changes:

1) no need to pass a glyph along.  This does change the behavior in one small case.  but @DustinCampbell and i think the new behavior is totally fine.
2) Remove complex forwarding methods that did nothing more than change a single value.
3) Removed matchPriority and formatOnCommit parameters as those are already part of the 'rules' that we pass along.
4) Removed unused parameters.
5) Remove unnecessary overrides.
6) Made passing of 'rules' non-optional.
7) Made passing of 'contextPosition' non-optional

**Comment by CyrusNajmabadi** [comment]
>  I'm personally fine with this change. Are you OK with it?

I personally think this is appropriate.  These are not enum-members.  They are actual fields/properties of some type.  So i think we should show them as they actually are.

**Comment by Pilchie** [comment]
Yes, I'm okay with that change.

**Pull request merged**
