### PR TITLE
Fix build definition

### PR DESCRIPTION
**Pull request by tmat**
A couple of fixes to official build definition missed in the previous PR.

### CODE REVIEW

**Comment by tmat** [comment]
test ci please

**Comment by tmat** [comment]
@jaredpar @jasonmalinowski PTAL. Yes, the squirrel has a new home.

**Comment by tmat** [comment]
@jaredpar microbuild_prtest seems to be still hanging around, even though i merge the PR that removed it from groovy file.

**Comment by jaredpar** [comment]
It's gone now.

**Pull request merged**
