### PR TITLE
Set IDE0008 severity

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
What is teh value of this change?

**Comment by Youssef1313** [comment]
> What is teh value of this change?

Having a consistent behavior between IDE and command-line. Currently it's already enabled using the `option = value:severity` option. Until compiler support for this syntax comes out, setting the severity using diagnostic id is needed for command-line builds to match IDE behavior.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Can you take a look please? Thanks.

**Comment by CyrusNajmabadi** [comment]
@sharwell  this is safe to take right?

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by sharwell** [comment]
🤷 We don't use this diagnostic (and don't plan to)

**Pull request closed without merging**
