### PR TITLE
Work around IL bug

### PR DESCRIPTION
**Pull request by pharring**
This could be a re-emergence of #4828 or perhaps a more complicated case.

@VSadov FYI, since you fixed the original bug and suggested this workaround.
@basoundr @rchande FYI, since this is affecting rolling perf machines.

### CODE REVIEW

**Comment by pharring** [comment]
The "bad" IL looks like this:

```
  IL_0111:  call       instance int32 [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Text.TextSpan::get_Start()
  IL_0116:  ldloc.3
  IL_0117:  add
  IL_0118:  ldc.i4.0
  IL_0119:  call       int32 [System.Runtime.Extensions]System.Math::Max(int32,
                                                                         int32)
  IL_011e:  ldloc.s    length
  IL_0120:  call       int32 [System.Runtime.Extensions]System.Math::Min(int32,
                                                                         int32)
  IL_0125:  ldloca.s   newSpan
  IL_0127:  dup
  IL_0128:  ldloc.s    length
  IL_012a:  bge.s      IL_0135
  IL_012c:  ldloca.s   span
  IL_012e:  call       instance int32 [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Text.TextSpan::get_Length()
  IL_0133:  br.s       IL_0136
  IL_0135:  ldc.i4.0
  IL_0136:  call       instance void [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Text.TextSpan::.ctor(int32,
                                                                                                         int32)
```

After this change, the fixed IL looks like this:
```
  IL_0111:  call       instance int32 [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Text.TextSpan::get_Start()
  IL_0116:  ldloc.3
  IL_0117:  add
  IL_0118:  ldc.i4.0
  IL_0119:  call       int32 [System.Runtime.Extensions]System.Math::Max(int32,
                                                                         int32)
  IL_011e:  ldloc.s    length
  IL_0120:  call       int32 [System.Runtime.Extensions]System.Math::Min(int32,
                                                                         int32)
  IL_0125:  stloc.s    newStart
  IL_0127:  ldloc.s    list
  IL_0129:  ldloc.s    i
  IL_012b:  ldloc.s    newStart
  IL_012d:  dup
  IL_012e:  ldloc.s    length
  IL_0130:  bge.s      IL_013b
  IL_0132:  ldloca.s   span
  IL_0134:  call       instance int32 [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Text.TextSpan::get_Length()
  IL_0139:  br.s       IL_013c
  IL_013b:  ldc.i4.0
  IL_013c:  newobj     instance void [Microsoft.CodeAnalysis]Microsoft.CodeAnalysis.Text.TextSpan::.ctor(int32,
                                                                                                         int32)
```

**Comment by VSadov** [comment]
it seems like this is now affected by https://github.com/dotnet/roslyn/issues/5530 , which is also fixed, but the fix might not be on the build that was used to produce binaries.

**Comment by pharring** [comment]
@dotnet-bot test win

**Comment by pharring** [comment]
@dotnet-bot test

**Comment by pharring** [comment]
@VSadov the rolling perf machines build with the toolset compiler. i.e, they build the compilers, then they build the rest of the product with those compilers.
The "bad" assembly in this case is Microsoft.CodeAnalysis.Features.dll.

**Comment by pharring** [comment]
@jaredpar @tannergooding How do I get Jenkins to re-test this? It looks like the [first one](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/371/console) was an unrelated failure in interactive tests. The [2nd one was a timeout](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/359/console).

**Comment by jaredpar** [comment]
retest windows please

**Comment by VSadov** [comment]
test this please

**Comment by pharring** [comment]
I found out that the rolling perf builds use the beta1 toolset from nuget, rather than the just-built compiler. So that explains why I thought the code-gen bug wasn't fixed.
So, we need this workaround until the nuget compiler is updated to a build that includes the referenced fix.

**Comment by jaredpar** [comment]
Do we have a bug tracking updating the rolling perf machines?  Seems pretty critical that we're not testing the latest compiler on the perf jobs.

**Comment by pharring** [comment]
@tannergooding The Linux tests failed with Build Timed Out again. Is this expected? May I merge?

**Comment by pharring** [comment]
Got permission from @jaredpar to merge this. Linux builds occasionally hang in Mono's GC.

**Comment by pharring** [comment]
To loop back on the "beta1" toolset issue, it's "Update 1 Beta 1" which is expected for our VSO builds.

**Pull request merged**
