### PR TITLE
Only build Release packages if we have no dependency on pre-release packages

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by tmat** [comment]
Merging to fix setup build.

**Comment by jasonmalinowski** [comment]
Do we have to remember to undo this change later? I worry that we're going to make what we think is the final build, forget about this, and then have to do it again. Can we be smarter here?

**Comment by tmat** [comment]
@jasonmalinowski The change can only be undone in a Release branch. Do we have a flag that says "this is a release branch"? 

BTW, we need to have a validation step that verifies all Release nugets are properly formed and can be used via project.json and packages.config. Such validation would discover that we have not generated any Release packages.

**Comment by jasonmalinowski** [comment]
No, we don't. Branches are a figment of your imagination instead. How about we condition it based upon our dependencies being pre-release? i.e. as long as we don't have any, we also build a release package.

**Pull request merged**
