### PR TITLE
Update versions in post-dev15 branch to 2.1.0-beta1

### PR DESCRIPTION
**Pull request by DustinCampbell**
cc @jaredpar, @jasonmalinowski, @natidea 

This is for the post-dev15 branch. Look OK?

### CODE REVIEW

**Comment by Pilchie** [comment]
Hmm - this never got merged?  Does that mean we have two branches pushing packages with the same version, or are we not uploading packages to myget from post-dev15 yet?

**Comment by DustinCampbell** [comment]
Sorry about that. I got test errors and forgot to look. Let me retrigger tests and get this in.

As for whether we're uploading packages to myget from post-dev15, the answer is that I have no idea. That's outside of my knowledge space.

**Comment by DustinCampbell** [comment]
Does anyone have any insight into the test failures? Clearly, I can't merge with those. Re-pinging @jasonmalinowski, @natidea and @jaredpar.

**Comment by DustinCampbell** [comment]
Chatted with @PIlchie. His thought is that the binding redirects need updating, but I don't know where those are. Any pointers?

**Comment by jasonmalinowski** [comment]
That would be the compiler's binding redirects...maybe we have a bad package or something. @jaredpar or @tmat can help here as they've both touched the area.

**Comment by jaredpar** [comment]
@DustinCampbell the binding redirects are located under build/bootstrap.  I think every config file in that list will need to be updated.

@jasonmalinowski does your auto-generate binding redirect code need to be updated too?  Or does it derive the values from the other changes in this PR?

**Comment by jaredpar** [comment]
For the curious: 

https://github.com/dotnet/roslyn/issues/15229

That tracks updating our bootstrap to always use @jasonmalinowski solution so it should be automatic.  Will help us out next time 😦

**Comment by jasonmalinowski** [comment]
My automatic stuff picks up the version. Once you fix your bug then you'd be good.

**Comment by DustinCampbell** [comment]
@jaredpar: windows_eta_open_prtests failed with `Error! RepoUtil verification failed.`?

**Comment by jaredpar** [comment]
@DustinCampbell other PRs are seeing the same.  I believe @tannergooding is being asked to look at it due to an earlier change.

**Comment by DustinCampbell** [comment]
OK. I merged master into post-dev15 earlier today, so i'm probably seeing the same thing.

**Comment by tannergooding** [comment]
I have a fix for the issue up against roslyn-internal

**Comment by Pilchie** [comment]
This needs to get backed out of master now, right?

**Comment by Pilchie** [comment]
Nevermind this wouldn't have flowed into master.

**Comment by DustinCampbell** [comment]
right. This is only in post-dev15.

**Comment by Pilchie** [comment]
Yep, got my directions wrong for moment.

**Comment by davkean** [comment]
Looks like this did get into master. @jmarolf's backing it out.

**Comment by DustinCampbell** [comment]
Man. I looked at this PR a thousand times and never noticed it was based incorrectly.

**Comment by davkean** [comment]
As well as the other 10 people in this thread. :)

**Pull request merged**
