### PR TITLE
Fix path to HellWorld.cs if not tun from the Perf directory

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @pharring, @heejaechang

**Comment by pharring** [comment]
:+1:

**Comment by heejaechang** [comment]
can I ask what this perf test does?

**Comment by pharring** [comment]
It compiles "HelloWorld.cs" using the just-built C# compiler while capturing ETW events. It's the first perf test we're putting into our continuous integration system. For now, it's experimental.

**Pull request merged**
