### PR TITLE
Upgrade NuGet to 3.3.0.212.

### LINKED ISSUE #6981: NuGet is failing to restore on internal jobs
PR: [#6978](https://github.com/dotnet/roslyn/pull/6978) *Set Experimental flag for our VSIXes* by @jasonmalinowski
Failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/60/

**Issue 1: MSBuild Error**
error MSB4057: The target "_NuGet_GetProjectsReferencingProjectJsonInternal" does not exist in the project.

**Issue 2: Compile Error**
error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?) [d:\j\workspace\dotnet_roslyn_prtest_win_vsi_p2\Open\src\Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj]

### PR DESCRIPTION
**Pull request by davkean**
NuGet has now resolved #6981 which caused
us to roll-back to 3.2 last time we upgraded
to 3.3.

### CODE REVIEW

**Comment by davkean** [comment]
test vsi please

tag @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
vsi/p3 filed #7126.

retest prtest/win/vsi/p3 please

**Comment by davkean** [comment]
tag @agocke @jaredpar @jasonmalinowski Can one of you sign off please?

**Comment by jaredpar** [comment]
:+1:

**Comment by agocke** [comment]
:+1:

**Comment by davkean** [comment]
Hit #7126 again. I'm going to merge this in, as it's got passed Restore. We'll look at disabling this test when tomorrow.

**Pull request merged**
