### PR TITLE
Switch occurrences of master to main

### PR DESCRIPTION
**Pull request by allisonchou**
Switches master -> main throughout the repo.

Some URLs to other repositories are broken, but I think this should be OK because those specific repos are scheduled to also switch from master to main this sprint.

### CODE REVIEW

**Review by jmarolf — APPROVED** [review]

**Comment by dibarbet** [comment]
I see a bunch of changes to scripts in eng/common which is managed by arcade.  Should we be changing anything there?  Seems like we might end up breaking a bunch of stuff.

**Comment by allisonchou** [comment]
@dibarbet Thanks for the catch! I removed all changes to files in eng/common.

**Review by dibarbet — APPROVED** [review]

**Comment by Youssef1313** [comment]
@allisonchou Can you take a look at:

https://github.com/dotnet/arcade-services/blob/737108990a317c591d6beb46197a1b094e5979a6/src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/DependencyFlowGraph/IncludeBuildTimes/output.json#L489-L490

**Comment by allisonchou** [comment]
@Youssef1313 Thanks for the heads up. I opened an issue on the arcade side: https://github.com/dotnet/arcade/issues/7052

**Pull request merged**
