### PR TITLE
Proposed change allow customization of InternalsVisibleTo attributes (issue #3668)

### PR DESCRIPTION
**Pull request by jakesays**
This PR contains a proposed change that would allow easy local customization of generated `InternalsVisibleTo` attributes.

Applies to issue #3668.

### CODE REVIEW

**Comment by davkean** [comment]
@tannergooding @jasonmalinowski @jaredpar Can one of your have a look at this and decide if we're happy with this approach?

**Comment by jasonmalinowski** [comment]
@jakesays: what type of customization are you needing to do? I would have expected the "git way" here is just to modify what you need to modify and maintain your own fork. Is that not usable here?

**Comment by jakesays** [comment]
@jasonmalinowski Maintaining my own fork is easily doable, but the reason for asking for an upstream change is because I have created a little application scripting environment (simple, embeddable IDE with debugger) for Roslyn scripting, and I'm going to opensource it. I would prefer people not have to deal with modifying Roslyn to make it work. However I need access to internal classes to make code completion function. I was searching for a solution that would cause the least impact on Roslyn as a whole, and I was able to limit it to a single build file.

Its not a huge deal, but I have come across others that have similar issues with needing access to Roslyn internals. I believe this would help them as well.

However I do understand the desire to not want to do a million customization's for every project that comes along.

**Comment by jasonmalinowski** [comment]
@jakesays: I guess from my perspective, having to copy in a magic file is still "modifying" it no different than just maintaining your own fork. You still have to post instructions on how to do such a modification. You could just as well make those instructions be "download this git patch" and run "git apply", and then we don't have to maintain this.

I also hesitate to accept changes that support just your build scenario versus a more general scenario that's applicable. I can assure you we'll break this and other people down the road won't know why this is here or how to not break it. (Consider: in three years when somebody sees this, will they know what they should do with it?) This is what forks in git is for, arguably.

Also, which APIs are you missing? @DustinCampbell has been thinking hard about the completion APIs to make them public. Rather than working around the problem you might want to just work with him directly (if you're not already) to get what you need.

**Comment by jakesays** [comment]
@jasonmalinowski no problem. I didnt even think of doing a patch. Easy enough!

Thanks for the feedback, and I'll contact @DustinCampbell about the features I'm using.

**Pull request closed without merging**
