### PR TITLE
moved todo analyzer to use temporary storage instead of persistent storage.

### PR DESCRIPTION
**Pull request by heejaechang**
we can't use persistent storage as state storage anymore since 2 vs with same solution can overwrite each other. it now only can be used as cache storage.

since state is more important, it now uses temporary storage as its backing store.

this means todo information will not be kept between vs sessions.

diagnostics and designer attribute change will follow.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Why do we need to make this change?  Is this fixing an actual issue?  If someone were to open two VS's all that should happen is that one will find that it cannot use the cached data from the other because checksums won't match.

**Comment by heejaechang** [comment]
todo comment and diagnostics used persistent storage not only for cache but to save state. since now it can't be used for state since other vs can overwrite its state, it had to move to other storage which can be used to save state.

for example, if user scroll error list, as user scroll, we read data from storage to show information, now that is not possible, since information in error list might erased due to other vs overwriting information there.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure test failed
Microsoft.CodeAnalysis.Editor.UnitTests.CodeGeneration.CodeGenerationTests+Shared.TestSorting [FAIL]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/8767/

**Comment by heejaechang** [comment]
Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicLineCommit.CommitOnSave [FAIL]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_vs-integration_prtest/7007/

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
> todo comment and diagnostics used persistent storage not only for cache but to save state. since now it can't be used for state since other vs can overwrite its state

Doesn't the todo system have to deal with the persisted state possibly being not valid?  i.e. if it saved from some version of the file, but the file has actually changed (i.e. when VS is not open and not tracking edits).  If it can know to not use the data because it doesn't match the file, wouldn't htat still work even for the case if another process is changng the data?

--

Also, this seems like quite a bit of an issue with IPersistenceService.  It looks like the API is designed to save data corresponding to file/project, without any other constraints.  It seems unfortunate if features are using the data (that has never been confirmed to be accurate) without checking somethign like a checksum.

**Comment by CyrusNajmabadi** [comment]
Again, this seems really really really bad:

> this means todo information will not be kept between vs sessions.
> diagnostics and designer attribute change will follow.

This seems like this means that every time you launch VS and load a solution that it will recompute all this data.  That seems horrible for perf.

**Comment by heejaechang** [comment]
todo used persisted storage for 2 purposes. 
(1) caching data between sessions, and
(2) save state so that it doesn't need to hold onto all state in memory.

for (1), todo scanner checks the data, (version or checksum or something else, what it is doesn't matter, point is it has something to verify data integrity saved in the storage), and if data is valid, it accepts the data or if data is invalid, it re-calculate the data and save it, after that, it send out message to other components that todo data for item A (a file) is ready. and remove the data from memory.

now, when other component such as task list needs todo comments for file A, it ask todo scanner to give the data, then todo comment read the data from the storage and give that back to task list. this is where it is used for (2). since the data only change when todo scanner changes it, data saved in the storage is always valid once todo scanner verified its integrity.

and that is no longer true since the data can be altered without todo scanner knows about it. and can give wrong information back to other components when asked.

we don't want to re-calculate it every single time since that is too expensive.

for ones that uses persistent service only for caching, it works fine. but not for ones that uses it for state.

**Comment by heejaechang** [comment]
we can create IPersistentService2 which can't be used by 2 process at the same time, but until then, currently feature is broken, so we can't leave it as it is.

**Comment by heejaechang** [comment]
> Doesn't the todo system have to deal with the persisted state possibly being not valid? i.e. if it saved from some version of the file, but the file has actually changed (i.e. when VS is not open and not tracking edits). If it can know to not use the data because it doesn't match the file, wouldn't htat still work even for the case if another process is changng the data?

sure, but that is only once when solution is first opened, after that, data was always valid since only the todo scanner was allowed to change data in persistent storage.

**Comment by heejaechang** [comment]
> Also, this seems like quite a bit of an issue with IPersistenceService. It looks like the API is designed to save data corresponding to file/project, without any other constraints. It seems unfortunate if features are using the data (that has never been confirmed to be accurate) without checking somethign like a checksum.

previous persistent service guaranteed 2 things

1) persisted data between VS session
2) data is owned by only 1 VS session

existing code used some logic to check integrity of data for (1) between VS session. and it relied on (2) characteristic as state storage.

new persistent storage kept (1) but not (2)

we have some features who want only (1) and not (2) so that data can be shared between multiple processes, but we also have features that want both.

right now, features that want both are broken, I meant functionality is broken. so we need to fix those. and sure we can add new API where one can ask persistent service what kind of guarantee caller wants

**Comment by CyrusNajmabadi** [comment]
> sure, but that is only once when solution is first opened (which it does valid the data), after that, data was always valid since only the todo scanner was allowed to change data in persistent storage.

That seems like a guarantee that was not stated.  But, if we want that guarantee, it sounds like we should just provide that.  i.e. if there's an active session then the persistence service automatically does something like prepends an integral key to make sure that anything read/written from another session does not interfere.

In this way the common case of a single VS caches all data properly.  If you routinely use two VSs, then the data for the second session will be stored as well under different keys.  

--

We need to ensure we do not degrade things for the 99% case (single-VS) for the much rarer case of multiple VSs.

--

Heck, i'd rather have it that the second VS case simply doesn't use the persistence service at all if this is a problem.

**Comment by heejaechang** [comment]
sure, if you prefer, we can go that route, can we make that change then? right now, todo and diagnostics and designer attribute is all broken.

**Comment by heejaechang** [comment]
> that seems like a guarantee that was not stated.

I told you when you were doing the work.

**Comment by heejaechang** [comment]
anyway, so should I close this and open a bug to provide an persistent service API that is locked to 1 VS?

**Comment by heejaechang** [comment]
opened an issue asking new persistent API.

**Comment by CyrusNajmabadi** [comment]
> we can create IPersistentService2 which can't be used by 2 process at the same time

I would rather IPersistentService just be safe to use across two processes.  There's nothing about the IPersistentStorage that indicates (either by signatures or with documentation) that what you read back will necessarily be what you wrote.  All it appears to provide is a mechanism to get back data keyed by project
+name or document+name, nothing more.  

I would prefer this API behave effectively like a safe file system store, keyed with workspace concepts.  As with any FS API, data might be written outside of your control, and you would need to validate the data upon reading (which many/most? consumers of this API already do).  

As IPersistentStorageService and IPersistentStorage are public, i think it would be best to just have this one single API, document clearly to consumers how they need to behave, and update our code to be resilient to the rare case of a double-VS-sessions, while still gaining the majority of perf for the common case of a single-VS sessions.

--

Or, as mentioned before, we could just change things under the covers so that this problem is transparent to the clients using the service.  i.e. we could guarantee that anything you wrote in a session would be returned within the same session.  Then all our existing clients would not have to be rewritten at all, and we would still be fast for the common case of one session, while correct for the rarer case of multiple sessions.

**Pull request closed without merging**
