### PR TITLE
Add support for NotInheritable and NotOverridable

### LINKED ISSUE #7348: SyntaxGenerator generates incorrect syntax for VB with DeclarationModifier.Sealed
Sealed (taken from C#) has two translations in VB, NotInheritable for classes and NotOverridable for members.  Currently, it only generates "NotInheritable" for everything.

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #7348 

This change fixes the VB SyntaxGenerator so it generates the correct modifier keyword when DeclarationModifier.Sealed is used.  

@Pilchie @jasonmalinowski @DustinCampbell

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Hmmm... this does change the VB SyntaxFactory at all. Now, *SyntaxGenerator* I'd believe. :smile:

**Comment by DustinCampbell** [comment]
LGTM :+1:

**Comment by Pilchie** [comment]
retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/1867/
// Retest reason: timeout due to overloaded machines

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
