### PR TITLE
Don't add automatic argument to invoke

### PR DESCRIPTION
**Pull request by panopticoncentral**
ServiceHub appears to be broken because @CyrusNajmabadi checked in code that does an Invoke but didn't realize that Invoke silently adds an extra parameter to all calls. So the invoke fails because the receiving end doesn't take enough arguments. Rather than have people run into this, we should just not add the extra argument and have people pass it in if they need it. @heejaechang

### CODE REVIEW

**Comment by heejaechang** [comment]
@panopticoncentral that's what I originally did but @CyrusNajmabadi preferred the current way. I am fine with either way.

unless we create our own abstraction above StreamJson or something like StreamJson, we can't make this simpler. we need to choose one of 2 ways and stick to it.

**Comment by panopticoncentral** [comment]
I'm fine with it either way, @CyrusNajmabadi if you would prefer the parameter be added, then I'll fix this by adding the parameter to methods that need them, just let me know.

**Comment by panopticoncentral** [comment]
@heejaechang Given the short timeframe, I switched the fix to the minimal thing of just adding the missing parameters. Can you take a look?

**Comment by panopticoncentral** [comment]
I'm going to go ahead and push this because it's a very simple fix, it's clearly and unambiguously broken, the code isn't on at this point in master (and it doesn't exist in preview5), and it's blocking some other stuff. If we don't like the fix I did here, I'll be happy to adjust it.

**Comment by heejaechang** [comment]
:+1: 

but I think this is not in preview

**Comment by CyrusNajmabadi** [comment]
I'm a bit confused.  

> @panopticoncentral that's what I originally did but @CyrusNajmabadi preferred the current way. 

The way i prefer it is that neither the caller or the callee should see this.  The caller shouldn't have to provde this, and the callee shouldn't have to accept it.  It should be completely transparent to both sides.

**Comment by heejaechang** [comment]
@CyrusNajmabadi I told you about the issue of magic parameter. and I don't think there is any way to hide this both side unless we create our own Rpc like StreamJsonRpc.

**Comment by CyrusNajmabadi** [comment]
> I told you about the issue of magic parameter. 

Sorry, i don't remember that discussion.  My feedback has always been intended to be taken as: 

Neither hte caller nor callee should have to worry about implicit parameters.  At the time, when i was talking about the caller not having to pass it along (because it was redundant in their 'using' block), the implication for me was that that meant the callee wouldn't need it either.

(it's not actually clear why the callee needs this parameter...).

**Comment by heejaechang** [comment]
@CyrusNajmabadi how the callee know the information without no-one giving it?

**Comment by CyrusNajmabadi** [comment]
I was under the impression that we would instantiate an instance of the remote type, set the data on it, and then call the right method.  so, for something like the 'solution' you would just have your 'solution' instance available to you the moment the method started running.  Just as the solution was the 'pinned' context on the caller side, the solution would be available context on the callee side.

**Comment by heejaechang** [comment]
there is no type in the other side. the method is your entry to the other side.

**Comment by CyrusNajmabadi** [comment]
I see.  this is not as i would expect, and does make things unfortunately more complex.  It's more like we're calling static methods in this fashion.  and we have to package up everything we need.

It would be more ideal if the framework would instantiate the object and give it hte Solution snapshot and the Cancellation token that the functions should run under.  The RPC framework would be responsible then for doing all the cancellation hookup and whatnot and the code could be written simply to work on normal Workspace abstractions without having to worry about doing anything but marshalling it's own data to/from either side.

**Comment by CyrusNajmabadi** [comment]
Something to think about as we work on simplifying the system in the future.

**Comment by heejaechang** [comment]
I actually prefer the way it is doing. giving all input rather than having some magic behind it. might be more boiler plate code when call, but everything is explicit and no magic so way easier to understand.

all input one need is right there when calling.

...

but that being said. I think I might be able to do what you are asking.

**Comment by heejaechang** [comment]
one more thing is they added custom json converter support in StreamJsonRpc as well so after preivew 5+, we should be able to use documentId/projectid and etc as they are without needed to convert them to primitive types.

**Comment by CyrusNajmabadi** [comment]
> might be more boiler plate code when calling, but everything is explicit and no magic so way easier to understand.

The problem with more boilerplate is that it's more opportunity for things to go wrong.  And it's more code that needs to be updated if anything changes.  For people writing features, the desirable state is to keep things as simple as possible. 

> Andrew just added support for cancellation token natively in stream json rpc, so now all call can give cancellationtoken to method call and it will flow into remote side.

That's great :)

That's exactly what i want.  Now i just want that for the solution side as well :D

> one more thing is they added custom json converter support in StreamJsonRpc as well so after preivew 5+, we should be able to use documentId/projectid and etc as they are without needed to convert them to primitive types.

Great!  Do you know if the Json converters support aync conversion?  If so, then we could provide a converter that could handle things like transmitting Symbols over as well.

**Comment by heejaechang** [comment]
there is no async converter as long as I know. converter is supposed to do very simple stuff so not sure whether they will add such one.

**Comment by heejaechang** [comment]
I feel like you want a helper method that will hide all these. sure we can do that.

**Comment by CyrusNajmabadi** [comment]
Yes.  My ideal for feature work is that host side says: ```using (... make the session ) { Invoke(nameof(IMyOperation.MethodName), arguments) }```.  The remote then has ```class MyClass : AbstractRemoteService, IMyOperation { Task MethodName(args, CancellationToken) { this.Solution... } }```

**Comment by heejaechang** [comment]
you can do that, but you will need to add myoperation.servicehub.service.json for each class since you need to register each one to service hub.

otherwise, we need to create our own Rpc mechanism either directly on top of stream or StreamJsonRpc.

I think both of them is too much work for little benefit.

**Comment by CyrusNajmabadi** [comment]
> add myoperation.servicehub.service.json

I don't see how that will do the right stuff like making sure the Solution is appropriately synced.

> otherwise, we need to create our own Rpc mechanism either directly on top of stream or StreamJsonRpc.

Yes.  This seems like a valuable thing to do.  The current stream is very low level and is just about raw data transportation.  For our features it would be nice to abstract out all the common functionality into a system that they can use and then easily call into.

> I think both of them is too much work for little benefit.

We did htis in TS and it made things pretty nice.  It meant that features themselves never needed to know how the OOP stuff worked.  It  meant that all marshalling/unmarshalling was contained in a common piece of code that everyone could use (right now, every feature may have to rewrite the same logic even if they share data types).  

Anything common was taken care of by the infrastructure.  Features only needed to write code specific to their feature.

**Comment by panopticoncentral** [comment]
Having experience with several RPC mechanisms, I've also been thinking a more high-level mechanism would be nice. It's something to look at as we move past the initial implementation, I was going to think some about it as well...

**Comment by heejaechang** [comment]
raw stream is already hidden by StreamJsonRpc.

converting checksum to actual object for me feels like same thing as we convert ITextSnapshot to document.

as long as there is easy to get convert one to the other, other abstraction on top seems just more code to manage.

also, once we have OOP running, it doesnt require solution to always needed. OOP can be delegate to do any work.

**Comment by heejaechang** [comment]
actually PersistentStorageService_XXXX methods are best example. it doesnt need solution checksum at all since it doesnt need it.

the last parameter was needed just because the magic parameter. if we make it magic differently, it still doesnt change the fact the caller side need to create checksum before calling the method just because it is blindly required by the abstraction.

**Comment by heejaechang** [comment]
this seems just problem of having different helper method. I also see using (.. session .. Invoke happens repeatedly. we can create one helper method that makes it just one line. using (session ... is for anyone who want to call multiple Invoke with same session.

**Pull request merged**
