### PR TITLE
Bump Razor to 7.0.0-preview.23405.1

### PR DESCRIPTION
**Pull request by davidwengier**
Dustin changed the serialization format that Razor uses, so need to update Roslyn to newer bits for VS Code. Needed to do a dual insertion (or at least, close together insertions) so that Razor can insert changes from https://github.com/dotnet/razor/pull/9061

### CODE REVIEW

**Review by dibarbet — CHANGES_REQUESTED** [review]
Not opposed to the change - but blocking for now because we have some RPS issues with the existing changes so we won't be able to do a quick / dual insertion for this yet.

**Comment by davidwengier** [comment]
Totally fair, with a note that this is only used in VS Code, so I don't think it affects RPS. But I get wanting less churn :)

**Review by dibarbet — APPROVED** [review]
Resetting my vote - since this is only used in vscode we can merge this whenever the razor side is ready.

**Comment by davidwengier** [comment]
Updated because Dustin changed the serialization format again... if this is the last planned change for a while, i'll get a Razor insertion going and merge this.

**Pull request merged**
