### PR TITLE
Add toolbar buttons for history navigation

### PR DESCRIPTION
**Pull request by amcasey**
...to improve discoverability.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @cston @ManishJayaswal @KevinH-MS @kuhlenh 
FYI @zooba @DinoV

**Comment by amcasey** [comment]
historybuttons

**Comment by KevinH-MS** [comment]
Screenshot?  (I don't really understand the vsct change)

**Comment by KevinH-MS** [comment]
Comment withdrawn... :)

**Comment by KevinH-MS** [comment]
:+1: certainly helps with discoverability!

**Comment by tmat** [comment]
:+1:

**Comment by amcasey** [comment]
Test this please

**Comment by amcasey** [comment]
@ManishJayaswal I've dropped the history buttons from the context menu.  Good catch!

**Comment by amcasey** [comment]
@dotnet-bot test this please.

**Pull request merged**
