### PR TITLE
Persist the low-memory-mode option to the registry

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This persists the checkbox. Before I merge this, I'll restore the ability to change the default 500MB size.

*Review:* @dotnet/roslyn-infrastructure, @mattwar

### CODE REVIEW

**Comment by tannergooding** [comment]
@jasonmalinowski, does this also solve the issue where updating the size requires you to uncheck/recheck for it to take affect?

**Comment by jasonmalinowski** [comment]
It will once I add the textbox back. :smile:

**Comment by jasonmalinowski** [comment]
OK, and I've also updated the code to persist the size again. This required fixing some core serialization infrastructure, but it's code only used for internal options. @Pilchie/@MattGertz, I targeted this against stabilization so that way people can test Update 3 bits with this being persisted, but that would require an ask mode approval. If that fails I can just put it into master, no big deal.

**Comment by jasonmalinowski** [comment]
Also @heejaechang for additional review. And @dotnet-bot, test vsi please.

**Comment by heejaechang** [comment]
:+1:

**Comment by balajikris** [comment]
Curious: is the setting and persistence hive specific? Can I potentially do this: create a hive for forced low memory mode, turn this setting on, use that profile/hive on fridays? 
That way I do not have to remember turning on or off this specific option for a day?

**Comment by jasonmalinowski** [comment]
@balajikris, yes, this is hive specific. You could that if you'd like. @tannergooding did request a checkbox which is "do this on Friday" where we'd turn it on and off automatically, but not sure if that will just confuse everyone.

**Comment by balajikris** [comment]
@jasonmalinowski thanks, I am good with this, as is, as i could isolate such testing to a hive than introduce confusions due to the setting staying on beyond its intended time period.

**Comment by jasonmalinowski** [comment]
My optimism I'd have time to get this in during ask mode was unfounded. I'll retarget this to master.

**Pull request closed without merging**
