### PR TITLE
Update corefx assemblies to .NET 5.0 generation

### PR DESCRIPTION
**Pull request by AArnott**
See also VS PR: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/291258

### CODE REVIEW

**Review by tmat — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]
I can't speak to the wisdom of upgrading these packages, but the PR itself seems fine. :smile:

**Comment by RikkiGibson** [comment]
I'm going to try and test insert this to VS (probably on top of the changes in [Andrew's PR to VS](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/291258)) and verify the best I can that everything works together before merging here.

**Review by jmarolf — APPROVED** [review]
I am ok with this change as long as a test insertion passes

**Comment by AArnott** [comment]
@RikkiGibson can you share a link to your test PR so I can watch as well?

**Comment by RikkiGibson** [comment]
I will post the link here as soon as it's created. Signed builds have been finicky this afternoon (seems like [network](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4284138&view=results) [issues](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4284161&view=results)?) so I haven't been able to create a test insertion for this yet.

**Comment by RikkiGibson** [comment]
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/292063

We still may want to merge your dev branch into this to fully validate things. Feel free to do so if you have some time.

**Comment by AArnott** [comment]
As expected, that insertion PR failed to build. I've merged my branch into it and expect better things soon. :)

**Comment by AArnott** [comment]
The test insertion passed.

**Comment by AArnott** [comment]
@RikkiGibson did you want to validate anything beyond the PR checks?

**Comment by RikkiGibson** [comment]
Nope, I think we are ready to merge here. Would it be acceptable for me to squash merge this PR?

My plan for this is: 
- we will merge this and produce an official build for it.
- We will produce an auto-insertion for it that we will not merge.
- We will give you the commit SHA for the content of the auto insertion, which you will cherry pick into [your VS PR](https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/291258) and you can merge when ready.

Does that work for you?

**Comment by RikkiGibson** [comment]
BTW, we seem to be experiencing a publishing issue with our official builds today, so the official build for this may be delayed. /cc @dibarbet

**Comment by AArnott** [comment]
@RikkiGibson squash merge of this PR is fine. I definitely want to *merge* the PR going into VS though as those commits are carefully curated. 

I'd rather merge my PR into VS right away and have your insertion follow-up and succeed on its own. Since your insertion will appear to 'downgrade' the nuget packages that you optimize, the bot that resolves conflicts will pick the wrong one and I have to manually fix it. But if my PR goes in first (or your insertion PR targets my PR's source branch instead of main) I believe the right thing will happen.
My PR by itself doesn't trigger any RPS regressions, so loss of IBC data from the Unsafe assembly evidently isn't too significant. And since that IBC data will be back with your next insertion, it doesn't seem like they _have_ to go in together.

**Comment by RikkiGibson** [comment]
I don't think I see a problem with merging your PR to VS standalone, but would like to double check with @tmat as he expressed interest in ensuring that we insert Roslyn at the same time as your change.

**Comment by AArnott** [comment]
In the meantime, shall we complete this PR?

**Comment by RikkiGibson** [comment]
Sounds good to me.

Note @dibarbet that if we need to try and insert a version from before this was merged for some reason, we can just look through the [master-vs-deps PR history](https://github.com/dotnet/roslyn/pulls?q=is%3Amerged+is%3Apr+base%3Amaster-vs-deps+) to find the suitable commit we want to build.

**Pull request merged**
