### PR TITLE
Don't directly reenter back into the workpsace when initializing listeners.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1656376

Internal VS tests found another reentrancy hang here.  So i'm just changing the component in question to not re-enter into the workspace (to mutate it) when it hears about workspace events.  That seems like the safest thing we can do.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski ptal :)

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Do we need to port this for 17.5 Preview 1?

**Comment by CyrusNajmabadi** [comment]
>@CyrusNajmabadi Do we need to port this for 17.5 Preview 1?

Maybe?  Is that not 'main'?

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I guess I'm still not really understanding why the original deadlock happened here -- my worry too is whether the code starting later here might cause other problems. Do you still have the deadlock stack handy here?

**Comment by jasonmalinowski** [comment]
> Maybe? Is that not 'main'?

We snapped yesterday, this would need to target release/dev17.5 now.

**Comment by CyrusNajmabadi** [comment]
great, will retarget.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi We can close this now?

**Pull request closed without merging**
