### PR TITLE
this is port of 7 different changes from master. and enabled remote host by default

### PR DESCRIPTION
**Pull request by heejaechang**
6 changes ported from master as they are.

#13694
#13721 
#13703
#13743 
#13756
#13779
#13787

all these changes are signed off from master.

...

only change in preview 5 branch is making remotehost to be on by default.

public static readonly Option<bool> RemoteHost = new Option<bool>(OptionName, nameof(RemoteHost), defaultValue: true);

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@Pilchie can I get approval for preview 5

**Comment by heejaechang** [comment]
cc @srivatsn @panopticoncentral @dpoeschl 

@panopticoncentral @dpoeschl I think you guys should either wait this change to be in before checkin yours or want to include your changes in master to be part of this PR.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure does "test vsi please" work? it seems it doesnt respond /cc @ManishJayaswal

**Comment by heejaechang** [comment]
test vsi please

**Comment by panopticoncentral** [comment]
@heejaechang @srivatsn @Pilchie Have we already snapped for preview 5? I thought I had until noon to get into master to get into preview 5 snap. If not, I need to port my changes over to the branch as well.

**Comment by natidea** [comment]
@panopticoncentral yes we snapped last Wednesday. Today's insertion would be the last for Preview 5 before escrow.

**Comment by natidea** [comment]
Note that we have not inserted master for about a week, so some of these changes have not yet run through DDRIT or RPS gauntlets

**Comment by heejaechang** [comment]
@MattGertz can I get approval for preview 5?

**Comment by srivatsn** [comment]
👍

**Comment by heejaechang** [comment]
I included all 7 PRs in this PR.

**Comment by heejaechang** [comment]
@srivatsn only thing left is decision on whether we will make remote host on by default or not in this PR.

**Pull request merged**
