### PR TITLE
Move shipped public APIs to PublicAPI.Shipped.txt

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
@jasonmalinowski Does this any ask mode approval?

**Comment by jasonmalinowski** [comment]
@mavasani No ask mode approval, but good to get a signoff or two that the APIs moving do look right. And @agocke knows now so he can anticipate merge issues.

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-infrastructure for one more signoff

**Comment by mavasani** [comment]
I am going to merge this in as it just involves public API txt file changes.

**Pull request merged**
