### PR TITLE
update training branch

### PR DESCRIPTION
**Pull request by jmarolf**
This change ensures that we are training against the same branch that we are inserting into.

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/roslyn-infrastructure ping. this is blocking new optprof data generation.

**Comment by jasonmalinowski** [comment]
@jmarolf Should we be configuring this somewhere else? Since this flows to other branches that insert other places, it's not clear to me how this works.

**Comment by jmarolf** [comment]
> Should we be configuring this somewhere else? 

Where?

**Comment by jasonmalinowski** [comment]
Dunno, https://github.com/dotnet/roslyn/blob/master/build/config/PublishData.json maybe?

**Pull request merged**
