### PR TITLE
Fix operation kind for tuple equality

### PR DESCRIPTION
**Pull request by jcouv**

### CODE REVIEW

**Comment by jcouv** [comment]
FYI @AlekseyTs @jaredpar It looks like there is another failure (`Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenDeconstructTests.ShortDiscardDisallowedInForeach`).

**Comment by AlekseyTs** [comment]
> It looks like there is another failure (Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenDeconstructTests.ShortDiscardDisallowedInForeach).

```
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(string message, string detailMessage) Line 24	C#
 	System.dll!System.Diagnostics.TraceListener.Fail(string message)	Unknown
 	System.dll!System.Diagnostics.TraceInternal.Fail(string message)	Unknown
 	System.dll!System.Diagnostics.Debug.Assert(bool condition)	Unknown
>	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.BoundDiscardExpression.ExpressionSymbol.get() Line 29	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateDiscardExpressionOperation(Microsoft.CodeAnalysis.CSharp.BoundDiscardExpression boundNode) Line 1938	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateInternal(Microsoft.CodeAnalysis.CSharp.BoundNode boundNode) Line 249	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create.AnonymousMethod__3_0(Microsoft.CodeAnalysis.CSharp.BoundNode n) Line 43	C#
 	mscorlib.dll!System.Collections.Concurrent.ConcurrentDictionary<Microsoft.CodeAnalysis.CSharp.BoundNode, Microsoft.CodeAnalysis.IOperation>.GetOrAdd(Microsoft.CodeAnalysis.CSharp.BoundNode key, System.Func<Microsoft.CodeAnalysis.CSharp.BoundNode, Microsoft.CodeAnalysis.IOperation> valueFactory)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.Create(Microsoft.CodeAnalysis.CSharp.BoundNode boundNode) Line 43	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.Operations.CSharpOperationFactory.CreateBoundForEachStatementOperation.AnonymousMethod__1() Line 1474	C#
 	mscorlib.dll!System.Lazy<Microsoft.CodeAnalysis.IOperation>.CreateValue()	Unknown
 	mscorlib.dll!System.Lazy<Microsoft.CodeAnalysis.IOperation>.LazyInitValue()	Unknown
 	mscorlib.dll!System.Lazy<Microsoft.CodeAnalysis.IOperation>.Value.get()	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.LazyForEachLoopStatement.LoopControlVariable.get() Line 2229	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.BaseForEachLoopStatement.Children.get() Line 2142	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Operations.OperationExtensions.Descendants(Microsoft.CodeAnalysis.IOperation operation, bool includeSelf) Line 77	C#
 	System.Core.dll!System.Linq.Enumerable.FirstOrDefault<Microsoft.CodeAnalysis.IOperation>(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.IOperation> source, System.Func<Microsoft.CodeAnalysis.IOperation, bool> predicate)	Unknown
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetOperationWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 1010	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetOperationWorker(Microsoft.CodeAnalysis.CSharp.CSharpSyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 186	C#
 	Microsoft.CodeAnalysis.CSharp.dll!Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetOperationCore(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 469	C#
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SemanticModel.GetOperation(Microsoft.CodeAnalysis.SyntaxNode node, System.Threading.CancellationToken cancellationToken) Line 77	C#
 	Roslyn.Test.Utilities.dll!Microsoft.CodeAnalysis.Test.Utilities.CompilationExtensions.ValidateIOperations(System.Func<Microsoft.CodeAnalysis.Compilation> createCompilation) Line 282	C#
 	Roslyn.Compilers.CSharp.Test.Utilities.dll!Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateEmptyCompilation(Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestSource source, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.MetadataReference> references, Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions options, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions parseOptions, string assemblyName, string sourceFileName) Line 426	C#
 	Roslyn.Compilers.CSharp.Test.Utilities.dll!Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CreateCompilation(Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestSource source, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.MetadataReference> references, Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions options, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions parseOptions, Roslyn.Test.Utilities.TargetFramework targetFramework, string assemblyName, string sourceFileName) Line 400	C#
 	Roslyn.Compilers.CSharp.Emit.UnitTests.dll!Microsoft.CodeAnalysis.CSharp.UnitTests.CodeGen.CodeGenDeconstructTests.ShortDiscardDisallowedInForeach() Line 6596	C#
```

```
        public override Symbol ExpressionSymbol
        {
            get
            {
                Debug.Assert((object)this.Type != null);
                return new DiscardSymbol(this.Type);
            }
        }
```

**Comment by jcouv** [comment]
@jaredpar I just pushed a fix for the remaining failure.

**Comment by jaredpar** [comment]
@jcouv awesome thanks!

**Comment by jcouv** [comment]
@AlekseyTs @jaredpar Merged the two test fixes (`windows_debug_ioperation_unit32_prtest` was green).
What's next?

**Pull request merged**
