### PR TITLE
Keep accessor with attributes on a single line.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/4720

### CODE REVIEW

**Comment by Pilchie** [comment]
Can you also take a look at the same line spacing issue @oatkins mentions in #4720 and ensure there is a test for it?

**Comment by CyrusNajmabadi** [comment]
Sure.  I'll take a look.

**Comment by CyrusNajmabadi** [comment]
@Pilchie I've addressed that other issue as well.

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
