### PR TITLE
Disabled more flakey tests which fail on a trivial PR.

### PR DESCRIPTION
**Pull request by VSadov**
Make Position/Green/Parent all implemented in the same style.
Added comments.

=== Disabled tests:
NavigateTo because of https://github.com/dotnet/roslyn/issues/18870
EncapsulateThroughCommand  because of https://github.com/dotnet/roslyn/issues/18879
VerifyNoCrashOnEnter  because of https://github.com/dotnet/roslyn/issues/18877
ResetInteractiveFromProjectAndVerify  because of https://github.com/dotnet/roslyn/issues/18880

### CODE REVIEW

**Comment by VSadov** [comment]
test this please

To see if any tests are flakey

**Comment by VSadov** [comment]
Now a failure in   CSharpReplIntellisense.VerifyNoCrashOnEnter

**Comment by VSadov** [comment]
test this please

To see if any other tests are flakey

**Comment by VSadov** [comment]
Now a failure in CSharpEncapsulateField.EncapsulateThroughCommand

**Comment by VSadov** [comment]
And in CSharpSendToInteractive.ResetInteractiveFromProjectAndVerify

**Comment by VSadov** [comment]
test this please

To see if any other tests are flakey

**Comment by VSadov** [comment]
test perf_correctness_prtest please

no idea what happened
https://ci.dot.net/job/dotnet_roslyn/job/master/job/perf_correctness_prtest/5171/

**Comment by VSadov** [comment]
test perf_correctness_prtest please

**Comment by VSadov** [comment]
test this please

To see if any other tests are flakey

**Comment by VSadov** [comment]
all passed twice now

**Comment by VSadov** [comment]
test this please

To see if any other tests are flakey

**Comment by VSadov** [comment]
passed three times

**Comment by jasonmalinowski** [comment]
@VSadov Should we get this merged? Better to merge and disable some tests than wait for all of them to be perfect.

**Comment by VSadov** [comment]
Now a failure in
Microsoft.CodeAnalysis.CSharp.UnitTests.Declarations.SourcePlusMetadataTests.InterfaceName

That is disturbing, since it is blocking the merge. Could not be caused by this change though.
Will look at that failure in a different PR.

**Comment by VSadov** [comment]
test windows_debug_unit32_prtest  please

**Comment by sharwell** [comment]
@VSadov Is it possible some failures could be occurring due to #18887?

**Comment by VSadov** [comment]
@sharwell - I do not know for sure. 
There seems to be a fairly limited set of tests that are failing. I'd guess #18887 would have a wider effect.

**Pull request merged**
