### PR TITLE
Changes to project.lock.json file that automatically happened to me

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Tagging @davkean  and @jasonmalinowski 

This is on a completely frsh machine.  I opened roslyn.sln and built and had this file get changed on me.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Pinging @tmat as well. 

According to @davkean it looks like a bunch of versions are wrong in this .json file.

**Comment by CyrusNajmabadi** [comment]
Ping.  Should i check this in?

**Comment by dpoeschl** [comment]
Looks similar to what's happening to @jaredpar in https://github.com/dotnet/roslyn/pull/8182/files#r50915454

**Comment by CyrusNajmabadi** [comment]
ping @tmat  What should i do here?  Thanks!

**Comment by jasonmalinowski** [comment]
So I had a little chat with `git bisect` to figure out what happened here. The problem @CyrusNajmabadi that you're seeing was introduced in TBD. Since then the problem has been made worse in @amcasey's change 705514c12c2241eabf1871f9f55d24bf604ea97a, since that touched project references and thus should have had the lock files updated. I'd recommend you either retry this PR with the current changes and then we'll merge that (assuming everything passes), or abandon this if you'd like somebody else to do the work.

**Comment by jasonmalinowski** [comment]
So I had a little chat with `git bisect` to figure out what happened here. The problem @CyrusNajmabadi that you're seeing was introduced in 57517f955986b22bc5b7c3205df74111ca8a4480/75be716bc0ba51e2f00155353c0ea3528ef2d67e. Since then the problem has been made worse in @amcasey's change 705514c12c2241eabf1871f9f55d24bf604ea97a, since that touched project references and thus should have had the lock files updated.

I'd recommend you either retry this PR with the current changes and then we'll merge that (assuming everything passes), or abandon this if you'd like somebody else to do the work.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/tst/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_tst_unit64/124/
// Retest reason: timeous

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi: you should hard reset this and re-run restore from scratch; there are other errors that have crept in since your original work.

**Pull request closed without merging**
