### PR TITLE
Increase maximum suggestions to 5, fixes #31002

### LINKED ISSUE #31002: 'Add Imports' feature fails to show the expected namespace
Currently the Add Imports feature trims the list to 3 elements.

https://github.com/dotnet/roslyn/blob/1abe9656700bc7b8021d13154545354b30b2dde2/src/Features/Core/Portable/AddImport/AbstractAddImportCodeFixProvider.cs#L16

When the desired namespace is not one of the first three found, the feature becomes useless.

### PR DESCRIPTION
**Pull request by ffMathy**
See #31002 for more context.

### CODE REVIEW

**Review by mavasani — CHANGES_REQUESTED** [review]
Marking as blocked as #31002 is marked for design review.

**Comment by ffMathy** [comment]
@mavasani that makes sense, but since the current feature is rather useless until it is fixed, is there a way we can speed up the process priority-wise?

**Comment by ffMathy** [comment]
And can we accept "5" as a temporary solution until we have a proper design?

**Comment by mavasani** [comment]
> And can we accept "5" as a temporary solution until we have a proper design?

@ffMathy Kindly add the same comment on the issue, and I have no pushback on the change if you get the approval on that issue.

**Comment by ffMathy** [comment]
@mavasani gotcha - thank you very much!

**Review by CyrusNajmabadi — APPROVED** [review]
This is fine with me.

**Comment by ffMathy** [comment]
@CyrusNajmabadi thank you so much!

Is there anything I can do to make the build pass? Is it a transient issue?

**Comment by CyrusNajmabadi** [comment]
Thank you!

**Pull request merged**
