### PR TITLE
Add basic implementation of new rename UI

### PR DESCRIPTION
**Pull request by ryzngard**
This adds the most basic implementation of the new rename UI. This PR is mostly to move code around and start a very ugly but workable demo. None of the behavior in the new UI is final, but it should make subsequent code reviews easier to parse in chunks as we modify the behavior. 

image

image

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
Cool stuff, is there a spec or planning issue for this?

**Comment by JoeRobich** [comment]
UI Proposal: If we used the "Find in document" UI as a starting point, the replace UI could look something like this. Optional replacements become toggle buttons with icons and the preview changes become part of the apply changes dropdown.

image

image

Also, I second Sandy's request for a tracking issue for this work.

**Comment by ryzngard** [comment]
> Cool stuff, is there a spec or planning issue for this?

We're working on producing a final design. I expect a meeting within the next week to produce something formal we can share. Since this is going into a feature branch I'm not worried about presenting at least the skeleton of the design which is that we want the inline experience to be: 

1. An editable box instead of editing the editor
2. Appears next to the invocation location 
3. Supports all options that were previously supported 

Beyond that design is tbd.

**Comment by sandyarmstrong** [comment]
So this would not live-update-as-you-type anymore? I think that's for the best.

**Comment by ryzngard** [comment]
#57715

**Review by JoeRobich — APPROVED** [review]

**Pull request merged**
