### PR TITLE
Trigger C# suggestion mode except for snippets

### PR DESCRIPTION
**Pull request by rchande**
Tag @dotnet/roslyn-ide  for review

### CODE REVIEW

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
@jcouv This change updates the C# SuggestionModeCompletionProvider to always trigger. The following tests now fail because a builder appears where the tests expected a hard selection. Is that a desired change?

```
Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.TestParenthesizedDeconstructionDeclarationWithVarAfterComma
Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CSharpCompletionCommandHandlerTests.TestParenthesizedDeconstructionDeclarationWithVar
```

**Comment by jcouv** [comment]
@rchande It is ok to update those tests. 
It looks like your fix will also address https://github.com/dotnet/roslyn/issues/15448. Basically, what I had noticed is that in some scenarios, sending a backspace will trigger suggestion mode, and in others it won't. Now that won't be an issue anymore.

**Comment by rchande** [comment]
Actually @jcouv those tests fail for me even without my change. I'm unable to manually reproduce their expected behavior on Dev15 + lastest master.
Any ideas?

**Comment by rchande** [comment]
Fixes https://github.com/dotnet/roslyn/issues/15302

**Pull request merged**
