### PR TITLE
Fix function naming.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by genlu** [comment]
@CyrusNajmabadi Is this related to your change?
```
    Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestGetSyntaxRootAsyncDoesNotKeepRootAlive
      Reference should have been released but was not.
      Expected: False
      Actual:   True
      Stack Trace:
        q:\roslyn\src\Test\Utilities\Desktop\ObjectReference.cs(60,0): at Roslyn.Test.Utilities.ObjectReference`1.AssertReleased()
        q:\roslyn\src\Workspaces\CoreTest\SolutionTests\SolutionTests.cs(951,0): at Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestGetSyntaxRootAsyncDoesNotKeepRootAlive()
```

**Comment by CyrusNajmabadi** [comment]
@genlu No.  This is a flakey test.  I thought that @jaredpar disabled this test.  @mattwar and @jasonmalinowski as i think they've looked into this code to figure out what's wrong with it.

**Comment by CyrusNajmabadi** [comment]
test this please

**Comment by genlu** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please

**Comment by genlu** [comment]
@dotnet-bot retest windows_eta_open_prtest please

**Pull request merged**
