### PR TITLE
Put the 'Add Nuget Reference' feature behind a disabled regkey option.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
To enable the feature set the following DWORD regkey to 1:
Key: ```HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\<your hive>\Roslyn\Internal\OnOff\Components```
Name: PackageSearch

To disable, set it to 0.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @KevinH-MS @Pilchie @davkean @MattGertz

**Comment by MattGertz** [comment]
Tentative approval pending exception discussion -- this might not be needed immediately (or at all).

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by KevinH-MS** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
ETA errors are the same as reported here: https://github.com/dotnet/roslyn/issues/9551
Which are also seen here: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4947/

These do not appear to be related to my changes.

**Comment by Pilchie** [comment]
:+1:, though I'd like confirmation that we've verified that the option is deserialized from somewhere and can be enabled.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Yup, i've verified this works when the indicaed registry entry is set/unset.  See the top of hte PR for more info about this.

**Comment by Pilchie** [comment]
@MattGertz Can you add an approval tag to this for bookkeeping?

**Pull request merged**
