### PR TITLE
Add support for await expressions to SyntaxGenerator

### LINKED ISSUE #1496: SyntaxGenerator lacks methods for creating "await" expressions
Other binary and unary expression types are supported, just not "await".

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #1496 

@tmeschter, @srivatsn please review

### CODE REVIEW

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by srivatsn** [comment]
:+1:

**Comment by tmeschter** [comment]
:+1:

**Comment by mattwar** [comment]
@dotnet-bot test this please

**Pull request merged**
