### PR TITLE
[EnC] Store entire spans instead of line deltas

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes https://github.com/dotnet/roslyn/issues/58179

Bit noisy with the renames, but pretty straightforward over all. Commit by commit might help, but probably won't make a huge difference.

### CODE REVIEW

**Review by ryzngard — APPROVED** [review]
I _think_ this looks correct, in as much as I understand EnC code.

**Comment by davidwengier** [comment]
> I _think_ this looks correct, in as much as I understand EnC code. 

You and me both. The only EnC understanding here is knowing what the fix is, and that was provided by @tmat 😛

**Comment by davidwengier** [comment]
Ping @tmat

**Comment by tmat** [comment]
Looks good, though I think the new test is a bit hard to read. BaseActiveStatementsAndExceptionRegions_WithInitialNonRemappableRegions is similar but using some markers to make it easier to express the edit.

**Review by tmat — APPROVED** [review]

**Pull request merged**
