### PR TITLE
WIP: SRM and SCI update

### PR DESCRIPTION
**Pull request by tmat**
<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/24677
https://github.com/dotnet/roslyn/issues/23762
https://github.com/dotnet/roslyn/issues/24712
https://github.com/dotnet/roslyn/issues/25185

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by sharwell** [comment]
Can you include a full technical description of the net46 limitation with this change?

**Comment by jaredpar** [comment]
Agree it would be nice to have in one of the commits. I can summarize it here though. 

> Even though Roslyn can only every be deployed where at least net461 or netcoreapp2.0 is available Roslyn cannot depend on netstandard2.0 assemblies. This is due to the setup of Visual Studio which has a minimum target of net46 and hence only deploys netstandard1.3 facades. In order to prevent netstandard2.0 versions of NuGet references to deploy, at build or test, we must limit the desktop target framework used in our projects to net46.

**Comment by tmat** [comment]
test windows_debug_unit32_prtest  please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_release_unit32_prtest  please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Pull request closed without merging**
