### PR TITLE
Avoid using GetEntireImage for detecting empty images as it maps the entire PE into memory in case of memory mapped PE image

### PR DESCRIPTION
**Pull request by tmat**
Fixes internal bug 1178264 (VM regression).

**Scenario**
VM footprint of debugging start regressed.

@ManishJayaswal

### CODE REVIEW

**Comment by KevinH-MS** [comment]
LGTM :shipit:

**Comment by tmat** [comment]
@pharring @VSadov @nguerrera

**Comment by nguerrera** [comment]
:+1:

**Comment by pharring** [comment]
:+1:
Thanks for the quick turnaround. @heejaechang Can you think of a way to get an early RPS read on this fix?

**Comment by VSadov** [comment]
LGTM

**Comment by heejaechang** [comment]
Once the issue where we can’t mix master to stabilization bits are fixed. I believe I can run private runs. Once we have release bits from master, I can try run them.


-          heejae

**Comment by pharring** [comment]
@KevinH-MS I was unable to test this manually. Could you take a stab at it?
@tmat Please check into master and we'll try and verify private bits.

**Comment by pharring** [comment]
**Scenario**
An RPS-detected regression in VM when you start debugging could lead to an out-of-address-space crash.
 
**Description of issue:** In order to address GitHub issue 1815, we added a check in PEModule.MetadataReader to check for zero-length PE files. To do that, we used the GetEntireImage API. This has the effect of mapping the entire image into memory. This is a regression in mapped bytes because we were previously mapping only a smaller portion of the images necessary for debugging. If the image contains a lot of native resources, for example, this will result in a large VM regression.
 
**Description of fix:** The fix is to avoid the GetEntireImage API and, instead, to deal with the exceptional case of a zero-length file by catching any exceptions from the ".HasMetadata" call.
 
**Testing:** Using VMMap, and manually loading the Picasso solution and debugging it:
_Before:_ 94,392 KB
_After:_ 72,084 KB
_Improvement:_ 22,308 KB

**Comment by MattGertz** [comment]
Approved 5/28 by ML Shiproom.

**Comment by pharring** [comment]
@tmat @ManishJayaswal Someone owes Shiproom cookies. This is a fix for a previously approved fix: #2995 

>Cookie rule applies:  If you bring the same bug twice because your team didn’t fix it properly the first time, you owe the shiproom cookies. 

**Pull request merged**
