### PR TITLE
Merge features/compiler

### PR DESCRIPTION
**Pull request by 333fred**
Updates features/dataflow with the new test changes from @jaredpar. @jaredpar, I'd like a review on the merge commit (722464c) to make sure that I ported the new stuff correctly.

### CODE REVIEW

**Comment by 333fred** [comment]
The important file to review is CSharpTestBase, IOperationTests_IBlock.cs, IOperationTests_ICoalesceOperation.cs, and IOperationTests_TryCatch.cs.

**Comment by AlekseyTs** [comment]
> The important files to review are CSharpTestBase, IOperationTests_IBlock.cs, IOperationTests_ICoalesceOperation.cs, and IOperationTests_TryCatch.cs.

We generally do not review integrations PRs. Did you make any non-trivial feature related changes?

**Comment by 333fred** [comment]
Test failure for unit32_prtest is https://github.com/dotnet/roslyn/issues/18637.

**Comment by 333fred** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

**Comment by 333fred** [comment]
Integration test failure was https://github.com/dotnet/roslyn/issues/20991.

**Comment by 333fred** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Pull request merged**
