### PR TITLE
Moving the Glyph enum back to the 'Features' dll.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This type is used by TypeScript and so it can't move to the Workspaces layer (as there is no IVT there to typescript).

This fixes the break until we can provide a far better, supported, way of doing glyphs/images across the workspace.

### CODE REVIEW

**Comment by davkean** [comment]
:+1:

**Comment by paulvanbrenk** [comment]
:+1: I agree we shouldn't be adding more IVT for TypeScript.

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by Pilchie** [comment]
:+1:

**Comment by genlu** [comment]
This looks like a regression:
 http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/245/

**Comment by dpoeschl** [comment]
:+1:

**Comment by dpoeschl** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/245/
// Retest reason: EnC failures that seem very unrelated. @genlu do you know anything about those failing tests?

**Comment by genlu** [comment]
No, tagging @dotnet/roslyn-interactive for the failed EnC tests.

**Pull request merged**
