### PR TITLE
Merge from branch 'master' to 'stabilization'

### PR DESCRIPTION
**Pull request by genlu**
This is simply done by 
```
... sync up everything
git checkout stabilization
git merge upstream/master
... resolve conflicts
git commit --all
```
Here's a list of files I have to resolve conflicts manually :
```
src/VisualStudio/Core/Test/CodeModel/CSharp/ExternalCodeFunctionTests.vb
src/VisualStudio/Core/Test/CodeModel/CSharp/ExternalCodeParameterTests.vb
src/VisualStudio/Core/Test/CodeModel/VisualBasic/ExternalCodeFunctionTests.vb
src/VisualStudio/Core/Test/CodeModel/VisualBasic/ExternalCodeParameterTests.vb
src/VisualStudio/Core/Test/CodeModel/CSharp/CodeClassTests.vb
src/VisualStudio/Core/Test/CodeModel/CSharp/CodeParameterTests.vb
src/VisualStudio/Core/Test/CodeModel/VisualBasic/CodeClassTests.vb
```

This is just a warm up to make sure everything will go smoothly, the official merge will be on Tuesday.
@dotnet/roslyn-infrastructure @DustinCampbell @jasonmalinowski

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Why only one commit listed? Did you accidentally squash the merge?

**Comment by genlu** [comment]
No I didn't. That's weird, I will fix it. Thanks for noticing.

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/dbg/eta please

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/3871/
// Retest reason: Seems like a build server issue. Will investigate if persist.

**Pull request merged**
