### PR TITLE
Allow extension methods in script code

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@tmat, @gafter, @ManishJayaswal, @pilchie

**Comment by gafter** [comment]
The implementation does what it claims to do, so LGTM in that sense.

It isn't clear to me that's what we should want.

**Comment by gafter** [comment]
:+1:

**Comment by hez2010** [comment]
I believe this also need to be done for the new extension members introduced in C# 14?

**Pull request merged**
