### PR TITLE
Consume VS SDK tasks and targets via NuGet

### PR DESCRIPTION
**Pull request by jasonmalinowski**
The NuGet packages for the SDK don't currently support cross-targeting,
so we must pick the right version to consume based on the version of
Visual Studio you are targeting. I implement this by simply restoring
both versions, and conditioning our MSBuild includes to the right one.
The annoying bit is since we need to restore two different versions
of the same package name via NuGet, we have to put the dependencies
in separate project.json files.

*Review:* @dotnet/roslyn-infrastructure, @dotnet/roslyn-ide, @Pilchie

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Comment by Pilchie** [comment]
This at least built for me on my VS "15" branch.

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest prtest/win/dbg/unit32 please. The underlying failure is fixed in #10958.

**Pull request merged**
