### PR TITLE
Make Empty.Set<T> conform to ISet<T> norms

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@jaredpar @agocke @gafter This was bugging me after it was suggested that I use specialized collections and noticed that the empty set implementation didn't implement `ISet<T>` with full fidelity.

**Comment by nguerrera** [comment]
@dotnet/roslyn-compiler Ping.

**Comment by jcouv** [comment]
I'm a little uneasy about adding code which doesn't presently support any compiler functionality. I don't know what other people on the team think.
That said the change LGTM

**Comment by cston** [comment]
LGTM. The change seems reasonable to me since `EmptySet<T>` was already implementing the `ISet<T>` interface and the implementation is now tested.

**Pull request merged**
