### PR TITLE
Remove now redundant code.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
It uses the enum from typekind.cx

### CODE REVIEW

**Comment by gafter** [comment]
Why wouldn't you remove the entire source file? The only remaining function in it doesn't do anything.

**Comment by AdamSpeight2008** [comment]
@gafter I didn't remove it as the extension method has call to it. [TypeSymbol.vb line: 519](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Symbols/TypeSymbol.vb#L519)

**Comment by gafter** [comment]
@AdamSpeight2008 Did you consider removing the call, since it is a no-op?

**Comment by AdamSpeight2008** [comment]
I didn't consider removing the call, so I'll retest without it.

**Comment by AdamSpeight2008** [comment]
When I remove the call. The following unit test fails. `Microsoft.CodeAnalysis.UnitTests.SolutionTests.TestRecoverableSyntaxTreeVisualBasic`
via `msbuild /nodereuse:false /v:m /m BuildAndTest.proj`
yet seems to pass when the test invoked independently.

**Comment by gafter** [comment]
LGTM

@dotnet/roslyn-compiler Can we please have a second review?

**Comment by AlekseyTs** [comment]
LGTM

**Comment by AdamSpeight2008** [comment]
@dotnot retest windows_eta_open_prtest please

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
