### PR TITLE
change default to only re-analyze direct dependencies rather than all…

### PR DESCRIPTION
**Pull request by heejaechang**
… transitive dependencies due to perf concern.

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@mavasani @srivatsn can  you take a look?

**Comment by mavasani** [comment]
:+1:

**Comment by heejaechang** [comment]
test vsi please

**Comment by srivatsn** [comment]
👍

**Comment by heejaechang** [comment]
test prtest/win/vsi/p1 please

**Comment by heejaechang** [comment]
retest roslyn_test_eta2  please

**Comment by heejaechang** [comment]
test  prtest/win/vsi/p3 please

**Comment by heejaechang** [comment]
test roslyn_test_eta2 please

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure how can I rerun eta2 test?

**Comment by mavasani** [comment]
@heejaechang you should ignore the eta2 result for now, its currently in trial phase.

**Pull request merged**
