### PR TITLE
Rename SyntaxPartKind.RecordName to RecordClassName

### PR DESCRIPTION
**Pull request by 333fred**
Addresses part of https://github.com/dotnet/roslyn/issues/50297, followup from API review. @dotnet/roslyn-compiler for review.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by JoeRobich — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for review.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2). Do we need to record the breaking change?

**Comment by 333fred** [comment]
> Do we need to record the breaking change?

We're specifically doing this now because the API hasn't shipped and it isn't a breaking change.

**Pull request merged**
