### PR TITLE
Restore RoslynTools.Microsoft.VSIXExpInstaller

### PR DESCRIPTION
**Pull request by tmeschter**
We're going to need this soon, so may as well start restoring it now to make it easier to test.

### CODE REVIEW

**Comment by tmeschter** [comment]
@tannergooding Please review.

**Comment by tannergooding** [comment]
Do we want to add MSBuild properties (in a similar manner to what we do for the compiler toolset here  https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L14) so that everything that consumes the package can be updated simultaneously?

**Comment by tmeschter** [comment]
@tannergooding It gets consumed by various scripts; not so much by targets/settings/projects. However, it wouldn't hurt to do that so it is available.

**Comment by tannergooding** [comment]
👍 for the new commit

**Pull request merged**
