### PR TITLE
Revert "Remove InteractiveWindow from Willow authoring (#13588)"

### PR DESCRIPTION
**Pull request by tmat**
This reverts commit b9dcaa13cba7344a8cc49f56256005eae5c77edd.

### CODE REVIEW

**Comment by tmat** [comment]
@KevinH-MS @ManishJayaswal OK, this time against Preview5 branch.

**Comment by KevinH-MS** [comment]
:shipit:

**Comment by tmat** [comment]
@MattGertz Ask mode change. I haven't been able to make Interactive Window built from dotnet/interactive-window work with Willow, so we need to revert this change for Preview 5.

**Comment by MattGertz** [comment]
@tmat  I need clarification; what is the user experience after this change with respect to installation and usage?

**Comment by tmat** [comment]
@MattGertz Currently in the latest ml build Interactive Window is broken - the Willow setup reports an error, skips installing it and continues. This change reverts to the previous state where Interactive Window built from Roslyn repo is installed instead and it works. So the difference is between not having Interactive Window at all and having one installed with Roslyn automatically.

**Comment by MattGertz** [comment]
@tmat Thanks.  I will approve; does there need to be a separate issue tracking future Willow work on IW? 

Approved pending successful test completion.

**Comment by tmat** [comment]
@MattGertz  Added an issue: https://github.com/dotnet/roslyn/issues/13684 for tracking.

**Comment by tmat** [comment]
failed due to https://github.com/dotnet/roslyn/issues/13433
test windows_debug_unit64_prtest  please

**Comment by tmat** [comment]
test windows_debug_unit64_prtest please

**Comment by tmat** [comment]
test windows_debug_unit64_prtest please

**Comment by tmat** [comment]
retest windows_debug_unit64_prtest please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
retest this please

**Pull request merged**
