### PR TITLE
Add a workaround for EventListener bugs

### PR DESCRIPTION
**Pull request by davkean**
To workaround: https://github.com/dotnet/roslyn/issues/6358

### CODE REVIEW

**Comment by davkean** [comment]
tag @tannergooding @dotnet/roslyn-infrastructure @dotnet/roslyn-interactive 

We're hitting this still both on open runs: https://github.com/dotnet/roslyn/pull/7327, and 2 out of 5 signed builds internally. Checking in a workaround to make it less likely to hit it.

**Comment by davkean** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2210/
// Retest reason: Mac machines are down again...:(

**Comment by genlu** [comment]
:+1: assuming it works :)

**Comment by amcasey** [comment]
Consider tagging these tests with the bug number so that they can be removed.

**Pull request merged**
