### PR TITLE
Fork diag/code-action tests to ones without editor dep. 3/N

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/71557

Move additional tests downwards.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@genlu ptal

**Review by tmat — CHANGES_REQUESTED** [review]
Blocking until https://github.com/dotnet/roslyn/pull/71525 is merged

**Review by tmat — CHANGES_REQUESTED** [review]
Blocking until https://github.com/dotnet/roslyn/pull/71525 is merged

**Review by tmat — APPROVED** [review]
Unblocking. Features test projects are now clean.

**Pull request merged**
