### PR TITLE
EnC test refactoring

### PR DESCRIPTION
**Pull request by tmat**
Test only change.

Move tests around, rename some files, group tests better.

### CODE REVIEW

**Comment by tmat** [comment]
@ivanbasov

**Comment by ivanbasov** [comment]
:shipit:

**Comment by tmat** [comment]
test hang windows_release_vs-integration_prtest: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5203/

**Comment by tmat** [comment]
test  windows_release_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest please

**Pull request merged**
