### PR TITLE
Install dotnet sdk explicitly for RichNav CI

### PR DESCRIPTION
**Pull request by xuachen**

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Overrode checks since right now it's only running checks that aren't in the file being touched.

**Comment by jaredpar** [comment]
@jasonmalinowski @xuachen why does this need to be done?

**Comment by jasonmalinowski** [comment]
@jaredpar What is "this"? The installing of the SDK or the job as a whole?

**Comment by jaredpar** [comment]
Why do we need a custom .NET SDK here that differs from the other SDK versions we use elsewhere in the repository.

**Comment by xuachen** [comment]
The previous builds ([here](https://dev.azure.com/dnceng/public/_build/results?buildId=661546&view=logs&j=c9b5975f-9534-57a6-63b4-9ff88d3ad797&t=9bd201d1-e2ba-5767-1cb9-95346b719bcf)) failed even though it was run after the build step which should have acquired a dotnet SDK on the machine, so I am not sure if it was due to the version or not able to find the SDK. I could try to switch to the SDK version used by the repo

**Comment by jaredpar** [comment]
@xuachen the `Build` step there did acquire a .NET SDK but it did not install it globally. Instead it was installed locally under the roslyn enlistment. Guessing by the error though that the `RichCodeNavIndexer` task requires that `dotnet` be installed globally on the machine. This new task though will install it globally and ensure it's on `%PATH%` so that should satisfy the rich nav task. 

Thanks, understand why we're doing this now.

**Comment by jaredpar** [comment]
Can't decide if this a good or bad approach by the `RichCodeNavIndexer` though. How do the communicate for instance when their application moves to be `netcoreapp3.1` instead of `netcoreapp2.1`? Given they depend on global installation if they silently move forward they would break all of their consumers. Maybe they just release a new version of the task, say `RichCodeNavIndex@3`, every time they move to a new TFM?

**Comment by xuachen** [comment]
Thanks @jaredpar for the explanation that makes sense. Our team owns the `RichCodeNavIndexer` task so I think the dependency on global .NET tool is because internally the RichNav task calls `dotnet tool install` which has [dependency on .NET > 2.1](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install), so we included that in our onboarding wiki. I don't think it is likely to move to the next .NET version though but will definitely make sure not to break existing users if that happens!

Do you think I should change to explicitly install 3.1.200 or use global.json? #44611

**Comment by jasonmalinowski** [comment]
@xuachen Any reason the task itself can't install (locally) the version it needs, if there isn't already a global one installed?

**Comment by xuachen** [comment]
I am not aware of any blockers so we probably just haven't done that, and I think it is a great idea. @jepetty are you aware of any previous problems for installing .NET SDK in our build task?

**Comment by jepetty** [comment]
I believe this is an item on our backlog that just hasn't been addressed yet. To be safe, @AArnott do you know of any reason not to install the proper .NET SDK in our Rich Nav build tasks?

**Comment by jaredpar** [comment]
@xuachen 

> Do you think I should change to explicitly install 3.1.200 or use global.json? 

My worry was more about how your task would evolve. Basically looking at our YML today we're supporting your task by installing 2.1 SDK in our YML. If at some point in the future your task moves to require 3.1 SDK, cause say you moved to `netcoreapp3.1`, then how would that happen without introducing a break into existing builds?

I was speculating that say moving to `RichCodeNavIndex@3` would be a solution. That would mean everyone has to opt into the move vs. it being forced on them. This is speculation on my part though (this isn't an area I have a lot of experience with). 

Overall though I was mostly curious if this has been thought through. This is the first time i've seen a build task that was .NET SDK dependent and hence I was curious if anyone had thought though all this and had a plan for how this would work. If so wanted to understand so we could apply to tasks we authored in the future.

**Comment by AArnott** [comment]
I don't see any reason our task couldn't install the SDK version that it requires. You can see a script that I already use to install the SDK (without using the `UseDotNet` task) here: 

https://github.com/AArnott/Library.Template/blob/master/tools/Install-DotNetSdk.ps1

**Comment by xuachen** [comment]
Thanks Andrew sounds like we could remove that dependency from user and make sure we have .NET SDK installed within our build task, so we could probably include that in our next sprint. Once that's done I could remove this extra step but it won't introduce breaking changes. 

@jaredpar Yes I think that's exactly what we should do. I think whenever we bump up the major version, it will require user to opt-in to use the new version (we are at preview 0.1.1504 so it was `RichCodeNavIndexer@0`) so we could make use of that if we release version with breaking changes.

**Pull request merged**
