### PR TITLE
fix crash due to control following through next statement

### PR DESCRIPTION
**Pull request by heejaechang**
I forgot to put "continue" in some places and it made null to pass into next statement.

it looks like I missed this case since I was concentrated on project document case not project case so this call path never exercised.

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @balajikris @shyamnamboodiripad @tmeschter @mavasani can you take a look?

**Comment by mavasani** [comment]
:+1:

**Comment by srivatsn** [comment]
:+1:

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by ilmax** [comment]
Is there any way to apply this fix to VS2015 CTP 6?

**Comment by heejaechang** [comment]
This is not in CTP6


-          Heejae

**Comment by ilmax** [comment]
Thank you, I was thinking this was somewhat related to #914.

**Pull request merged**
