### PR TITLE
Add GetDeclaredSymbol API for DeclarationPatternSyntax to C# SemanticModel.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Also add tests for scoping of variables declared within expression statements by using DeclarationPatternSyntax.

Related to #8817.

@gafter, @jaredpar, @dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-infrastructure It looks like mac and lin a failing due to some infrastructure issue:
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/4114/

MSBuild Error

error MSB6003: The specified task executable "vbc" could not be run. ApplicationName='/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/Binaries/Bootstrap/vbc', CommandLine=' -noconfig @"/tmp/tmpea495231a89a4b6faffe8dfcd733d323.rsp"', CurrentDirectory='', Native error= Access denied [/mnt/j/workspace/roslyn_prtest_lin_dbg_unit32/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj]
Indication 1 


http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/4051/

MSBuild Error

error MSB6003: The specified task executable "vbc" could not be run. ApplicationName='/Users/dotnet-bot/j/workspace/roslyn_prtest_mac_dbg_unit32/Binaries/Bootstrap/vbc', CommandLine=' -noconfig @"/tmp/tmp19cfbed064594a9fb9ecdf295cdfc828.rsp"', CurrentDirectory='', Native error= Access denied [/Users/dotnet-bot/j/workspace/roslyn_prtest_mac_dbg_unit32/src/Tools/Source/CompilerGeneratorTools/Source/VisualBasicSyntaxGenerator/VisualBasicSyntaxGenerator.vbproj]
Indication 1

**Comment by natidea** [comment]
@dotnet/roslyn-infrastructure 
Failures in `prtest/win/dbg/unit32` and `prtest/win/dbg/unit64` are related to #8807 have be resolved in stabilization by #8899 and #8979. Those changes need to make it into this feature branch to unblock these builds

**Comment by natidea** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/4114/@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/4051/
// Retest reason: Don't see these failures in other builds. Opened #9030

**Comment by natidea** [comment]
@AlekseyTs @gafter to resolve the failing windows unit tests your feature team will need to sync the feature branch to master.

**Comment by gafter** [comment]
Thank you for adding this API!

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
