### PR TITLE
Emit My.InternalXmlHelper under the root namespace

### PR DESCRIPTION
**Pull request by amcasey**
...as in Dev12.

NOTE: the new test won't actually pass until https://github.com/dotnet/roslyn/pull/2931 is merged.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @cston 
FYI @gafter @jaredpar @VSadov

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by amcasey** [comment]
Cool, I'll merge as soon as I rebase on top of my other change.

**Comment by amcasey** [comment]
This change will probably be merged as part of https://github.com/dotnet/roslyn/pull/3011 instead.

**Comment by amcasey** [comment]
Yes, this change will be merged into the stabilization branch and then integrated to master.

**Pull request closed without merging**
