### PR TITLE
Remove unnecessary type parameter from SymbolDisplay base type.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler @dotnet/roslyn-ide

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@CyrusNajmabadi Compiler changes require **two**  sign-offs from the Compiler team.

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
