### PR TITLE
Remove unwanted public APIs and enable public API analyzers for Interactive (Editor) Features

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/roslyn/issues/5986

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/interactive

**Comment by gafter** [comment]
#5988 says it fixes #5986, and #5986 says it fixes #5988. But neither has any description of what it is supposed to accomplish.

**Comment by tmat** [comment]
@gafter The description is in the title: "Interactive Editor Features should expose no public APIs"

**Comment by gafter** [comment]
I don't get it. How can an issue fix a PR?

**Comment by tmat** [comment]
Moving to stabilization branch: https://github.com/dotnet/roslyn/pull/6033

**Pull request closed without merging**
