### PR TITLE
Add support for suppressing diagnostics without source location from the error list

### PR DESCRIPTION
**Pull request by mavasani**
This change builds on the prior suppression related changes to allow applying add/remove suppression fix for diagnostics without a source location (project level diagnostics) from the error list.
Additionally, when the diagnostics being suppressed or unsuppressed are across different languages, instead of showing a preview changes dialog per-language, now we show a single preview changes dialog for the entire changed solution.

### CODE REVIEW

**Comment by mavasani** [comment]
ping?

**Comment by heejaechang** [comment]
Let me take a look once I am in office.


-          heejae

**Comment by heejaechang** [comment]
:+1:

**Pull request merged**
