### PR TITLE
Support records in CSharpGenerateDefaultConstructorsService

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
The added test failed with:

> System.Exception : No action was offered when one was expected. Diagnostics from the compilation:

**Comment by Youssef1313** [comment]
```diff
Actual and expected values differ. Expected shown in baseline of diff:
 record C : B
 {
-    public C(int x) : base(x)
+    protected C(B original) : base(original)
     {
     }
 }
 
 record B
 {
     public B(int x)
     {
     }
 }
```

Needs to make sure there is a nested code action that suggests generating different constructors.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
@Youssef1313 test failures?

**Comment by Youssef1313** [comment]
@CyrusNajmabadi There should be multiple code actions offered. I'm not sure how to write the test for a specific code action given that it's not using the new test library.

**Comment by CyrusNajmabadi** [comment]
@Youssef1313  you can pass `index: 0` or `index: 1` and so forth to select a particular action to invoke.

**Comment by Youssef1313** [comment]
> @Youssef1313 you can pass `index: 0` or `index: 1` and so forth to select a particular action to invoke.

Thanks. Wasn't aware of this overload. Fixed the test now.

Sorry for missing this for some time.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
