### PR TITLE
made roslyn to use new GetContentLocation API from extension manager

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
fix https://github.com/dotnet/roslyn/issues/6286

**Comment by heejaechang** [comment]
@srivatsn @mavasani @basoundr can you take a look? quite simple change.

**Comment by heejaechang** [comment]
it looks like build machine is not moved to update 1 yet.

**Comment by davkean** [comment]
(Closing/opening to sync update the merge branch to pick up the build break we just fixed)

**Comment by heejaechang** [comment]
@davkean is Jenkins moved to update1 now?

**Comment by davkean** [comment]
No not yet - we've still finding things that need to be fixed.

**Comment by davkean** [comment]
@dpoeschl is in the same situation. As a workaround, he's using dynamic to avoid the static reference to the new API, which he'll fix later.

**Comment by heejaechang** [comment]
@davkean is machine now moved to update 1?

**Comment by davkean** [comment]
We're moving next week, we're still blocked on something at the moment.

**Comment by heejaechang** [comment]
retest this please.

**Comment by heejaechang** [comment]
Jenkins moved to update 1

**Comment by mavasani** [comment]
:+1:

**Pull request merged**
