### PR TITLE
Remove usages of ConfigureAwait in tests

### LINKED ISSUE #6980: Remove all usages of ConfigureAwait in tests
As per this thread, let's remove all usages of ConfigureAwait in test code so that we're consistent across the board: https://github.com/dotnet/roslyn/pull/6975.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #6980

(Afraid if any of them is needed?)

### CODE REVIEW

**Comment by 333fred** [comment]
@jaredpar can you look at this, particularly the compiler server tests?

**Comment by jaredpar** [comment]
What's the motivation for the change here? True we don't require code to be explicit about `ConfigureAwait` in the tests but it's not wrong either.

**Comment by Youssef1313** [comment]
> What's the motivation for the change here? True we don't require code to be explicit about `ConfigureAwait` in the tests but it's not wrong either.

https://github.com/dotnet/roslyn/pull/6975#issuecomment-159030984 (Not sure if this still holds?)

**Review by jaredpar — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @Youssef1313!

**Pull request merged**
