### PR TITLE
made us to re-analyze some part of solution when assembly name have c…

### LINKED ISSUE #3410: Solution crawler not triggering project analysis on project rename (after the 1st rename)
1. Create an Analyzer + Fix project (say Analyzer2) and replace the analyzer code with the below code:

    ```C#
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Analyzer2
{
    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    public class Analyzer2Analyzer : DiagnosticAnalyzer
    {
        public const string DiagnosticId = "Analyzer2";

        // You can change these strings in the Resources.resx file. If you do not want your analyzer to be localize-able, you can use regular strings for Title and MessageFormat.
        internal static readonly LocalizableString Title = "MyProjectDiagnostic";
        internal static readonly LocalizableString MessageFormat = "MyProjectName: '{0}'";
        internal const string Category = "Naming";

        internal static DiagnosticDescriptor Rule = new DiagnosticDescriptor(DiagnosticId, Title, MessageFormat, Category, DiagnosticSeverity.Warning, isEnabledByDefault: true);

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics { get { return ImmutableArray.Create(Rule); } }

        public override void Initialize(AnalysisContext context)
        {
            context.RegisterCompilationAction(OnCompilationAction);
        }

        private void OnCompilationAction(CompilationAnalysisContext context)
        {
            context.ReportDiagnostic(Diagnostic.Create(Rule, Location.None, context.Compilation.AssemblyName));
        }
    }
}
    ```

2. Build solution and install the generated analyzer VSIX.

3. Start a new VS instance and create a new C# class lib application, `ClassLibrary1`.

4. Wait for some time, you should see a diagnostic `MyProjectName: 'ClassLibrary1'` in the error list.

5. Open project property pages and rename the project assembly name to a new name, say `ClassLibrary2` and hit save.

6. Wait for few seconds and see that the error list diagnostic is updated to `MyProjectName: 'ClassLibrary2'`, as expected.

7. Now again go back to project property pages and rename the project assembly name to a new name, say `ClassLibrary3` and hit save..

**Got:** Error list diagnostic does not change even after waiting for a few minutes.
Try 7 again with older names or any new names, and the diagnostic never changes.

The root cause seems to be that Solution crawler is invoking [AnalyzerProjectAsync](http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/f828748c0ec79d64.html) for steps 2-6 but not from step 7 onwards, causing us to never re-trigger project analysis after the first rename.

### PR DESCRIPTION
**Pull request by heejaechang**
…hanged.

this is PR for master for #3414.

see #3414 for more detail.

Fixes #3410

### CODE REVIEW

**Comment by srivatsn** [comment]
LGTM

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Pull request merged**
