### PR TITLE
Infer types from generic constraints

### PR DESCRIPTION
**Pull request by HellBrick**
This is a prototype of #5023. See https://github.com/dotnet/roslyn/issues/5023#issuecomment-154728796 for the description of the implementation mechanics.

### CODE REVIEW

**Comment by bbarry** [comment]
It looks like these tests are failing exactly for the reason the code was changed. The expected refactorings no longer need the type parameters on these method calls with the change here:

in EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs

* [line 8148](https://github.com/dotnet/roslyn/blob/db9c4edd46ebd93c862c2479c1bac5d85818ec89/src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs#L8148)
* [line 8840](https://github.com/dotnet/roslyn/blob/db9c4edd46ebd93c862c2479c1bac5d85818ec89/src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs#L8840)
* [line 8885](https://github.com/dotnet/roslyn/blob/db9c4edd46ebd93c862c2479c1bac5d85818ec89/src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs#L8885)
* [line 8933](https://github.com/dotnet/roslyn/blob/db9c4edd46ebd93c862c2479c1bac5d85818ec89/src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs#L8933)
* [line 9004](https://github.com/dotnet/roslyn/blob/db9c4edd46ebd93c862c2479c1bac5d85818ec89/src/EditorFeatures/CSharpTest/ExtractMethod/ExtractMethodTests.cs#L9004)

**Comment by HellBrick** [comment]
Thanks, I've fixed the tests.

**Comment by HellBrick** [comment]
>Edit: also the comments in the MethodTypeInference.cs file should be updated to match spec changes.
That's a bit tricky, since there is no updated spec at this point =)

**Comment by SolalPirelli** [comment]
I see that your tests use methods with one argument; would this also work with parameterless methods, e.g. `M<T, X>() where T : IEnumerable<X>` called as `M<List<int>>()`? (sorry, my computer is in a bit of a messy state right now, can't check for myself)

**Comment by bbarry** [comment]
No. This change is about getting rid of some (all?) cases where the generic parameters are already fixed but the compiler fails to tell so the developer must supply them.

**Comment by khellang** [comment]
So will this solve [this problem](http://stackoverflow.com/questions/8511066/why-doesnt-c-sharp-infer-my-generic-types) (inferred return type) as well?

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler

**Comment by HellBrick** [comment]
@SolalPirelli It doesn't work like that. This PR improves the type inference, but in your case it's never actually invoked. Waaaaaay earlier down the stack the compiler detects that method is called with less type arguments than required and produces an error. If this behavior is altered to try inferring the missing types before failing, then the mechanism from the current PR would kick in and save the day. But I believe it's a separate issue (#6207 looks related).

**Comment by davkean** [comment]
test eta please

tag @dotnet/roslyn-compiler

**Comment by gafter** [comment]
@HellBrick Nice work! We're still discussing it (but mostly we have vacations that prevent us from meeting much until January).

**Comment by davkean** [comment]
@gafter @dotnet/roslyn-compiler It's been nearly ~3 weeks, can we take a look?

**Comment by HellBrick** [comment]
>mostly we have vacations that prevent us from meeting much until January

It's January now =) Any plans for further action here?

**Comment by gafter** [comment]
Our plans are to meet around the third week of January and start prioritizing our language design work.

**Comment by gafter** [comment]
@HellBrick OK, the LDM looked at this very briefly, and we decided that we don't want to make language changes to overload resolution in 1.2 (except to fix compat bugs). We can consider it for a later language version (i.e. version 2.0, tentatively called C# 7). And I am still interested in pushing it through the process.

Can you please retarget this to the [future branch](https://github.com/dotnet/roslyn/tree/future) (i.e. close this PR and open a new PR against the future branch]?

Tag me on the new PR and I'll continue working it with the language team.

/cc @MadsTorgersen

**Comment by HellBrick** [comment]
Sure, I'll open a new PR tomorrow. It's a pity though that such a small nice improvement has to wait until the next major language version. If you don't mind me asking, what's the reason behind postponing it? I'm just trying to get a better understanding of your process and to see if there's anything else that can be done here to simplify acceptance of this feature.

P.S. Out of curiosity: what are the minor milestones (1.2, 1.3) mapped to, timeline- or release-wise? Do they correspond to the upcoming VS 2015 updates?

**Pull request closed without merging**
