### PR TITLE
Updating VSL.Version.targets to properly specify build number.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jasonmalinowski, @jmarolf

### CODE REVIEW

**Comment by jmarolf** [comment]
retest vsi please

**Comment by jmarolf** [comment]
retest windows_debug_unit32_prtest please
retest windows_debug_unit64_prtest please

**Comment by tmat** [comment]
:+1:

**Comment by tannergooding** [comment]
test vsi please

**Comment by tannergooding** [comment]
@jmarolf, there was a case (specifically the bootstrap build) where we still needed to respect what the user specified for BuildVersion.

**Comment by tannergooding** [comment]
Also FYI. @dotnet/roslyn-infrastructure

**Comment by tannergooding** [comment]
*Ping* Could I get a second sign-off on this.

**Comment by jmarolf** [comment]
:+1:

**Pull request merged**
