### PR TITLE
reverting Syntax Vizualizer dependencies to use MSBuild so we can specify that nuget dependencies are build-time only

### PR DESCRIPTION
**Pull request by jmarolf**
https://github.com/dotnet/roslyn/pull/7259 introduces a problem: project.json has no way to specify that dependencies should not be copied to the output folder (buildtime vs. runtime dependencies), therefore it will happily copy Microsoft.CodeAnalysis.dll Version 1.0 over the top of  Microsoft.CodeAnalysis.dll 1.2 since all of our binaries are dropped into a single directory.

To solve this, we revert back to packages.config which gives us the ability to test that certain sets of dependencies should not be copied to the output folder.

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
Why didn't we just turn off copying to the output directory? There's an option for that.

**Comment by jmarolf** [comment]
@jasonmalinowski is there an option to not copy the references but still copy the binaries being built?  I was unaware of such an option

**Comment by jasonmalinowski** [comment]
It looks like you can set UseCommonOutputDirectory to true?

```xml
    ============================================================
                                        _CopyFilesMarkedCopyLocal

    Copy references that are marked as "CopyLocal" and their dependencies, including .pdbs, .xmls and satellites.
    ============================================================
    -->
  <Target
      Name="_CopyFilesMarkedCopyLocal"
      Condition="'@(ReferenceCopyLocalPaths)' != ''"
        >

    <PropertyGroup>
      <!-- By default we're not using Hard Links to copy to the output directory, and never when building in VS -->
      <CreateHardLinksForCopyLocalIfPossible Condition="'$(BuildingInsideVisualStudio)' == 'true' or '$(CreateHardLinksForCopyLocalIfPossible)' == ''">false</CreateHardLinksForCopyLocalIfPossible>
    </PropertyGroup>

    <Copy
        SourceFiles="@(ReferenceCopyLocalPaths)"
        DestinationFiles="@(ReferenceCopyLocalPaths->'$(OutDir)%(DestinationSubDirectory)%(Filename)%(Extension)')"
        SkipUnchangedFiles="$(SkipCopyUnchangedFiles)"
        OverwriteReadOnlyFiles="$(OverwriteReadOnlyFiles)"
        Retries="$(CopyRetryCount)"
        RetryDelayMilliseconds="$(CopyRetryDelayMilliseconds)"
        UseHardlinksIfPossible="$(CreateHardLinksForCopyLocalIfPossible)"
        Condition="'$(UseCommonOutputDirectory)' != 'true'"
            >

      <Output TaskParameter="DestinationFiles" ItemName="FileWritesShareable"/>

    </Copy>

  </Target>
```

**Comment by jasonmalinowski** [comment]
Also, in your case, isn't the only binary being shipped in the VSIX the Visualizers DLL itself, since everything else is being picked up from the ambient shell? If that's the case, you could also just set CopyNuGetImplementations = false.

**Pull request merged**
