### PR TITLE
Use SyntaxEditorBasedCodeFixProvider for 'qualify member access'

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
As per https://github.com/dotnet/roslyn/pull/26558#discussion_r185895035 there are substantive benefits to using this over the default BatchFixAllProvider.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jcouv @heejaechang @mavasani

**Comment by jinujoseph** [comment]
cc @heejaechang to review as well

**Comment by mavasani** [comment]
@jinujoseph for approval

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview2 
Thanks every one!!

**Comment by CyrusNajmabadi** [comment]
@jcouv can you merge in?  Thanks!

**Comment by jcouv** [comment]
Jinu merged it already. :-)

**Comment by CyrusNajmabadi** [comment]
Weird!  It shows unmerged for me...  that is super strange!

**Pull request merged**
