### PR TITLE
Update UnitTesting Hot Reload API to consider syntax errors  

### PR DESCRIPTION
**Pull request by vritant24**
Updates made:
1. Returns detected syntax error.
2. Returns UpdatedTypes and UpdatedMethods in wrapper type.

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

**Comment by vritant24** [comment]
@davidwengier I don't have write access so will you be the one to merge this in?

**Comment by davidwengier** [comment]
@vritant24 Are the test failures real?

**Comment by vritant24** [comment]
@davidwengier yup looks like I didn't catch one of the tests. Pushed a fix 👍

**Comment by vritant24** [comment]
The current failing test seems to be unrelated and about async lightbulbs

**Pull request merged**
