### PR TITLE
Emit anonymous types in deterministic order

### LINKED ISSUE #223: EditAndContinueTests.AnonymousTypes changes emit order in 64-bit runner
Failure:

```
Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTests.AnonymousTypes [FAIL]
        Actual:
        <Module>,
        VB$AnonymousType_1`2,
        VB$AnonymousType_2`1,
        VB$AnonymousType_0`2,
        A,
        B
        Differences:
            <Module>,
            VB$AnonymousType_1`2,
        ++> VB$AnonymousType_2`1,
            VB$AnonymousType_0`2,
        Stack Trace:
           src\Test\Utilities\AssertEx.cs(208,0): at Roslyn.Test.Utilities.AssertEx.Equal[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector)
           src\Compilers\VisualBasic\Test\Emit\Emit\EditAndContinueTestBase.vb(212,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTestBase.CheckNames(MetadataReader[] readers, StringHandle[] handles, String[] expectedNames)
           src\Compilers\VisualBasic\Test\Emit\Emit\EditAndContinueTestBase.vb(207,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTestBase.CheckNames(MetadataReader reader, StringHandle[] handles, String[] expectedNames)
           src\Compilers\VisualBasic\Test\Emit\Emit\EditAndContinueTests.vb(3328,0): at Microsoft.CodeAnalysis.VisualBasic.UnitTests.EditAndContinueTests.AnonymousTypes()
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #223

### CODE REVIEW

**Comment by gafter** [comment]
@jaredpar @VSadov @AlekseyTs @agocke @VladimirReshetnikov Could a couple of you review this please?

**Comment by agocke** [comment]
jenkins retest this please

**Comment by jaredpar** [comment]
:+1: 

This change is deceptively simple.

**Comment by agocke** [comment]
Ship it

**Pull request merged**
