### PR TITLE
Add support for generating 'nameof' expressions from the SyntaxGenerator

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @kuhlenh

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
Venus issue is: https://github.com/dotnet/roslyn/issues/9671

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/vsi/p1 please

**Comment by CyrusNajmabadi** [comment]
Ping @dotnet/roslyn-ide

**Comment by jmarolf** [comment]
:+1:

**Comment by balajikris** [comment]
:+1:

**Comment by DustinCampbell** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
