### PR TITLE
Clean up and refactor outlining unit tests

### PR DESCRIPTION
**Pull request by DustinCampbell**
The outlining unit tests are some of the last IDE tests in an ancient style that we stopped using about 5 years ago. This change migrates them to more of a "fit" style -- at least, that's what @CyrusNajmabadi calls them -- which more closely matches other IDE tests.

Tagging @dotnet/roslyn-ide

### CODE REVIEW

**Comment by DustinCampbell** [comment]
retest this please

**Comment by DustinCampbell** [comment]
Oops. Looks like a build failure

**Comment by davkean** [comment]
Yep, these looks like real failures:

```
d:\j\workspace\roslyn_prtest_win_dbg_unit64\src\EditorFeatures\VisualBasicTest\Outlining\MetadataAsSource\OperatorDeclarationOutlinerTests.vb(31,13): error BC42358: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the Await operator to the result of the call. [d:\j\workspace\roslyn_prtest_win_dbg_unit64\src\EditorFeatures\VisualBasicTest\BasicEditorServicesTest.vbproj]
```

Trying to figure out why the failure cause didn't pull this out of the build log.

**Comment by DustinCampbell** [comment]
Tagging @CyrusNajmabadi -- you don't need to spot check every test, but it'd be great if you could look at the infrastructure.

**Comment by DustinCampbell** [comment]
Retest this please

**Comment by DustinCampbell** [comment]
retest prtest/win/dbg/eta please

**Comment by DustinCampbell** [comment]
retest prtest/win/dbg/eta please

**Pull request merged**
