### PR TITLE
Use a separate flag for inequality patterns as C# does not support it

### PR DESCRIPTION
**Pull request by alrz**
Summary:

- Use a separate flag for inequality patterns as C# does not support it - `case != 0` is invalid
- Remove ranges from C# analysis. This does not affect the result since we already support `and`
(there's no actual range patterns in C#)

Note: this PR does not add support for `not` patterns. I think that could be done after https://github.com/dotnet/roslyn/pull/43596 when we can share some parts between the two features.

### CODE REVIEW

**Comment by alrz** [comment]
tagging @CyrusNajmabadi for review this bugfix for a recently updated feature. Thanks.

**Comment by alrz** [comment]
nevermind the branch name. 🤦

**Comment by alrz** [comment]
nevermind the branch name. 🤦

**Comment by alrz** [comment]
ping @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
LGTM.  Thanks!

**Pull request merged**
