### PR TITLE
Cleanup `SyntaxNormalizerTests`

### PR DESCRIPTION
**Pull request by DoctorKrolic**
- Converted multiline strings to raw form
- Removed unnecessary `NormalizeLineEndings` calls
- Made `WorkItem` attribute placement consistent: `[Fact, WorkItem...]`
- Converted `Theory`s to `Fact`s when inline data contains string with line breaks
- Made usage of variables consistent (inlined them)
- Made offered methods `static`

### CODE REVIEW

**Comment by DoctorKrolic** [comment]
I've resolved all test fails on unix systems and ready for review now

**Comment by 333fred** [comment]
@DoctorKrolic is this fixing any bugs? Or is this a style refactoring?

**Comment by DoctorKrolic** [comment]
I would call it a style refactoring, but the main motivation here is readability. As per discussion in https://github.com/dotnet/roslyn/pull/65249#discussion_r1025852346 I was actually allowed to do this)

**Comment by RikkiGibson** [comment]
> * Converted `Theory`s to `Fact`s when inline data contains string with line breaks

I didn't understand the motivation for this part.

**Comment by DoctorKrolic** [comment]
> I didn't understand the motivation for this part.

As for me, long multiline strings as attribute parameters look really odd. Usually attributes contain some short easy-to-sequentially-read things. When they had single-line string it was kinda halfway right. When I converted them to raw strings, however, I decided, that it look better, when these values are somewhere in method body. + many tests already used this pattern with several test cases in single test method (even before my previous PR with initializers), so it also makes thing more consistent. I can totally revert this if you don't share this point of view.

**Comment by DoctorKrolic** [comment]
@RikkiGibson ?

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@jcouv @CyrusNajmabadi for review

**Comment by DoctorKrolic** [comment]
@jcouv @CyrusNajmabadi Still waiting for a review here...

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by jcouv** [comment]
We typically don't accept PRs that focus on code style. That said, given that this is a test-only PR (which therefore only needs one compiler review) and we have the required review, we'll go ahead and merge.
Thanks

**Comment by CyrusNajmabadi** [comment]
Note: i don't personally feel this is code-style.  These single-line tests are actually quite painful to work with, requiring lots of manual minging of \r\n in the comments, and basically often obfuscating what's actually going on (like what the test is testing against and what it is validating).  A prime use case for raw-strings was exactly 'tests', with a bunch of enthusiasm from compiler side about being able to move these forward to this more maintainable form :)

**Comment by RikkiGibson** [comment]
I'm very late on this, but thanks for the contribution @DoctorKrolic!

**Pull request merged**
