### PR TITLE
Fix a NullReferenceException in the DeclarePublicAPI analyzer

### LINKED ISSUE #672: Exception in 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer'
1.Build Roslyn.sln and start a new VS instance in RoslynDev hive
2.Create a C#/VB class library project 

Got:
Message	AD0001	The User Diagnostic Analyzer 'Roslyn.Diagnostics.Analyzers.ApiDesign.DeclarePublicAPIAnalyzer' threw an exception with message 'Object reference not set to an instance of an object.'.			1

### PR DESCRIPTION
**Pull request by tmeschter**
Fixes #672.

Move the existing null check to the right location.

### CODE REVIEW

**Comment by srivatsn** [comment]
:+1:

**Comment by tmeschter** [comment]
@jmarolf @mavasani @shyamnamboodiripad @heejaechang @JohnHamby Could one of you take a quick look?

**Comment by mavasani** [comment]
:+1:

**Comment by heejaechang** [comment]
:+1:

**Comment by JohnHamby** [comment]
Looks good.

**Comment by shyamnamboodiripad** [comment]
:+1:

**Pull request merged**
