### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by genlu** [comment]
test vsi please

**Comment by AlekseyTs** [comment]
test prtest/win/vsi/p2 please
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/636/

**Comment by AlekseyTs** [comment]
test prtest/win/vsi/p2 please
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/637/

**Pull request merged**
