### PR TITLE
Lfa skiplocalsinit 2

### PR DESCRIPTION
**Pull request by RikkiGibson**

### CODE REVIEW

**Comment by RikkiGibson** [comment]
So over here I'm trying to triage the regression in our ability to parse deeply nested if statements (f5db21c). My guess is that adding an `attributes` parameter to many statement parsing methods in #38937 is blowing the stack. I actually can't repro the debug_64 failure out of the box when running tests in VS. (I set "Test->Processor Architecture for AnyCPU Projects" to x64.) I have to edit the test and increase the expected nesting level for that configuration from 200 to over 520.

When I do that, I find that the stack has this representative cycle in it:
```cs
LanguageParser.ParseEmbeddedStatement() Line 7196
LanguageParser.ParseIfStatement(SyntaxList<AttributeListSyntax> attributes) Line 7740
LanguageParser.TryParseStatementNoDeclaration(SyntaxList<AttributeListSyntax> attributes, bool allowAnyExpression) Line 6452
LanguageParser.TryParseStatementCore() Line 6301
LanguageParser.ParseStatements(ref CSharpSyntaxNode previousNode, SyntaxListBuilder<StatementSyntax> statements, bool stopOnSwitchSections) Line 7069
LanguageParser.ParseBlock(SyntaxList<AttributeListSyntax> attributes, bool isMethodBody, bool isAccessorBody) Line 7007
LanguageParser.TryParseStatementNoDeclaration(SyntaxList<AttributeListSyntax> attributes, bool allowAnyExpression) Line 6475
LanguageParser.TryParseStatementCore() Line 6301
LanguageParser.ParseEmbeddedStatement() Line 7196
```

This seems to align with my guess that the 'attributes' parameters are what's sinking us. I am wondering if there is some way to avoid passing so many attribute lists up the stack. For instance in situations where attributes are only found in error scenarios, could we maybe change the code to something like this (pseudo to get the idea across):

```cs
var attributes = ParseAttributes();
var statement = ParseStatement();
if (attributes != default)
{
    statement = statement.WithAttributeLists(attributes);
    // diagnostics here, maybe?
    // maybe a helper method called for many kinds of statements?
}
```

This involves allocating another syntax node for the new statement but since it's only really for error recovery it should be infrequent. Maybe there's another way to mitigate the problem that I don't see. Tagging @jaredpar @cston @CyrusNajmabadi to see if you have any ideas.

**Comment by CyrusNajmabadi** [comment]
> to see if you have any ideas.

One unfortunate thing i see is the number of 'layers' of calls just to parse a statement.  For example, we have to go through `ParseEmbeddedStatement->TryParseStatementCore->TryParseStatementNoDeclaration`.  

This feels pretty wasteful for recursive scenarios, esp. as ParseEmbeddedStatement seems to exist just to handle a corner script case that feels lke it could be handled by some other means.

**Comment by CyrusNajmabadi** [comment]
> So over here I'm trying to triage the regression in our ability to parse deeply nested if statements 

I thought we were doing work to make us resilient to deep nesting through the use of pushing the work to a different thread. 

Is this something we really need to care about?  Even a depth of 200 seems pretty crazy to me (esp. if we have a workaround by pushing the work to a different thread).  99.9999% of all code will be fine.  And the few crazy cases will take a tiny perf hit but keep working.

**Comment by RikkiGibson** [comment]
Re: stack chaining. See the latest discussion on #40367.

It's possible we will end up doing some combination of chaining execution stacks (with a modest limit on the number of times we can spin up in a new thread), as well as maybe adopting some measures to balance out increased stack frame sizes as we implement new features.

I agree with the sense that we shouldn't necessarily have to support the most absolutely complex code that can fit on a stack in Roslyn version X-1 ongoing into Roslyn version X. Some kind of balance is needed.

**Comment by jaredpar** [comment]
@CyrusNajmabadi 

> Is this something we really need to care about? Even a depth of 200 seems pretty crazy to me 

All the tests we've added here are customer driven scenarios. In pretty much every case it was an adoption blocker. 

> I thought we were doing work to make us resilient to deep nesting through the use of pushing the work to a different thread.

That idea was rejected after discussion of all the trade offs involved. Instead we're focusing on keeping the existing known stress scenarios working using existing stack limits. We will re-evaluate if we get more data on the issue.

**Comment by cston** [comment]
@RikkiGibson, it looks like we're just passing `attributes` the parsed in `ParseStatementCore()` down several methods so those attributes can be included when we generate the containing `SyntaxNode`. Since attributes are not the common case, would it make sense (and would it help to reduce the stack size) to have a `WithAttributes()` method that could be called in `ParseStatementCore()` instead?

**Comment by RikkiGibson** [comment]
This PR is just for triage, will open a more organized PR under a different branch.

**Pull request closed without merging**
