### PR TITLE
Add .NET 2.0 ResultProvider DLLs to NetFX20 root directory in ExternalAPIs nupkg

### LINKED ISSUE #15058: .NET 2.0 ResultProvider DLLs should be in NetFX20 root directory in ExternalAPIs nupkg
ResultProvider DLLs were previously in a NetFX20 root directory in the ExternalAPIs nupkg. As of a recent change, the DLLs are in Dlls/*ResultProvider.NetFX20.

### PR DESCRIPTION
**Pull request by cston**
Fixes #15058.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-infrastructure please review.

**Comment by cston** [comment]
@jaredpar please review.

**Comment by mavasani** [comment]
@cston I presume this will mean that we will need to revert the VSO PRs in ML branch done over the weekend, otherwise ML branch will break again with subsequent insertion. Please co-ordinate with @OmarTawfik so that whenever you merge this in, the next Roslyn insertion PR should also revert the above mentioned VSO changes.

Also, can we hold off this change for another day? We are hoping to RI tonight's ML branch drop and don't want to risk a build break. Tagging @jasonmalinowski

**Comment by cston** [comment]
Original issue #15058 has been closed.

**Pull request closed without merging**
