### PR TITLE
Make VisualBasicAdditionalFormattingRuleLanguageService a singleton.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Make VisualBasicAdditionalFormattingRuleLanguageService a singleton.

### CODE REVIEW

**Comment by sharwell** [comment]
@jinujoseph for approval. I verified that all types involved have no mutable state.

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview3

**Comment by AdamSpeight2008** [comment]
@sharwell  Would you mind sharing, how you did the verification.  *Curious*

**Comment by sharwell** [comment]
@AdamSpeight2008 visual review of the types via source.roslyn.io 😄

**Comment by AdamSpeight2008** [comment]
@sharwell  Though you had some clever code to validate them. 😄

**Pull request merged**
