### PR TITLE
Do not treat enum base list as type context for completions

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Part of https://github.com/dotnet/roslyn/pull/62013 (the original PR was closed due to its enormous size and other difficulties)

This implementatio is _a lot_ cleaner than the previous one in https://github.com/dotnet/roslyn/pull/62013 as it doesn't require any additional flags and is basically 1-line-of-code fix.

As a result _a lot of_ junk completions are not shown in the enum's base list ([spec paragraph](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/enums#182-enum-declarations))

**Before:**
devenv_IF3CCrDY5i

**After:**
devenv_Jbi8zgyUPz

Originally 2 problematic areas were symbol completions and incorrect `delegate` keyword recommendation. Not treating enum base list as a type context automatically fixes both of them. Added tests to verify the behaviour.

Also applied diagnostic recommendation and removed "Opt" suffix from 2 places. This should not interfere the review much.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Does this change interfere with someone wants to type `enum E : System.Int32`?

**Comment by Youssef1313** [comment]
> Having Int32 in the code immediately triggers an IDE rule to simplify it to int.

This is not correct. There is a code-style option for the user to specify whether he prefers framework types. There are definitely users who prefers framework types.

**Comment by Youssef1313** [comment]
> Also note: this behaviour was already implemented in VB

I'd consider the VB case to be a bug actually :)

**Comment by Youssef1313** [comment]
Real-world example:

https://github.com/xamarin/xamarin-macios/blob/491c5c979cdf5f1d0751f16fd260b21d06e63e2b/src/PrintCore/Defs.cs#L147-L165

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic could you return the symbol completion just for System and the primitive enums types?  Thanks!

**Comment by CyrusNajmabadi** [comment]
And 'global' plz

**Pull request merged**
