### PR TITLE
Update toolset compilers and analyzers

### PR DESCRIPTION
**Pull request by tmeschter**
Update to version 1.0.0-rc3-20150510-01.

### CODE REVIEW

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by dpoeschl** [comment]
retest this please

**Comment by tmeschter** [comment]
Retest this, please.

**Comment by tmeschter** [comment]
Retest this, please.

**Comment by tmeschter** [comment]
Retest this, please.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by tmeschter** [comment]
Retest this, please.

**Comment by jaredpar** [comment]
@dotnet-not test this please

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Pull request merged**
