### PR TITLE
Avoid emitting redundant locals in deconstruction assignment

### PR DESCRIPTION
**Pull request by alrz**
Fixes https://github.com/dotnet/roslyn/issues/38702

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@alrz Does the title of the PR, "Deconstructing pairwise assignments won't be used", accurately reflect the nature of the change?

**Comment by alrz** [comment]
Probably not. I'm out of ideas for this one actually

**Comment by AlekseyTs** [comment]
Consider adding a test for scenario from #38702.

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/roslyn/issues/50784 also reported this issue.

**Comment by alrz** [comment]
@RikkiGibson This doesn't repro with fields.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 5)

**Comment by 333fred** [comment]
Thanks @alrz!

**Pull request merged**
