### PR TITLE
Make the FAR test harness run all tests in proc and out of proc.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide   Note that this PR depends on both https://github.com/dotnet/roslyn/pull/14298 and https://github.com/dotnet/roslyn/pull/14307.  When they go in, it will make reviewing this a lot easier.

**Comment by CyrusNajmabadi** [comment]
test this please

**Comment by CyrusNajmabadi** [comment]
@jaredpar Still having problems, even after i added that redirect you specified.  Now i have tests failing with:

```
MESSAGE:
System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=8.0.3.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)\r\n---- System.IO.FileLoadException : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
+++++++++++++++++++
STACK TRACE:
at Roslyn.Test.Utilities.Remote.InProcRemoteHostClient.<CreateAsync>d__2.MoveNext() at 
```

**Comment by CyrusNajmabadi** [comment]
Also, when i debug the NavigateTo tests i get:

```
Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.NavigateTo.NavigateToTests.FindClass FAILED:
	Exception type: 'System.TypeInitializationException', number: '0', parent: '-1'
	Exception message:
The type initializer for 'Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.NavigateTo.NavigateToTests' threw an exception.
	Exception stacktrace
   at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.NavigateTo.NavigateToTests..ctor()
	Exception type: 'System.IO.FileLoadException', number: '1', parent: '0'
	Exception message:
Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	Exception stacktrace
   at Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.NavigateTo.NavigateToTests..cctor()
```

So there is still some issue with loading particular versions of VS assemblies.

**Comment by jaredpar** [comment]
@CyrusNajmabadi for the JSON tests change the binding redirect to

``` xml
<bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0"/>
```

Even though the package reference is for 8.0.3 the actual assembly version is 8.0.0.0.  Allowing these to be different is a *feature* of NuGet.  It has caused me and others no end of headaches and shipping problems.  

> Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=14.0.0.0, 

Is this happening in the Next projects?  If so it's likely we need a different config file for those projects.  They need a different class of binding redirects.

**Comment by CyrusNajmabadi** [comment]
Ok.  I'll try this later today

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide  This enables testing of OOP FAR and OOP NavigateTo.   Note: i have merged one of @jaredpar 's changes in.  Hence all the changes to OOP.

@jaredpar @heejaechang can you take a look as well?  I won't merge this in until your work goes in (at which point, this PR should get much smaller).

**Comment by heejaechang** [comment]
test parts seems fine. I think if you sync to latest a lot of changes will be gone and making PR changes smaller.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Does this still need reviews?

**Pull request closed without merging**
