### PR TITLE
Modifying cibuild.sh to run the test binaries in parallel.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jaredpar, @agocke

### CODE REVIEW

**Comment by jaredpar** [comment]
I'm nervous about this change.  I agree that long term this is the right thing to do.  But right now we hit mono crashes on xunit about 2-3% of the time.  This feels like a much more complex usage of mono.  Have we verified, by running in a loop, that this doesn't increase our failure rate?

**Comment by tannergooding** [comment]
@jaredpar, I don't have a machine setup to run this in a loop right now. Can we retarget these unit test assemblies to CoreCLR and run them on there instead?

**Comment by jaredpar** [comment]
@tannergooding we can and that's the plan.  It's just work we haven't done yet and it's non-trivial.  Probably take us a week to get them ported over.  The biggest blocker was moving to xunit 2.1 which we've done now.  So we can begin this work.

**Comment by agocke** [comment]
@jaredpar Yeah, the first step is me rebasing my PR. Haven't gotten around to it but hope to do it today.

**Pull request closed without merging**
