### PR TITLE
Use processes to parallelize our big unit test assemblies

### PR DESCRIPTION
**Pull request by jaredpar**
This started out by a suggestion from @jcouv on our unit tests.  Rather than spending the time to divide up the big unit test assemblies or make them able to run in parallel (particularly difficult for our WPF assemblies), why not use traits to divide up the assembly and use multiple instances of xunit to run the suites in parallel?  Traits ended up not working out for a few reasons:

1. Still too much code to annotate no matter how we sliced it. 
2. Concerns about maintaining the pattern going forward.
3. Didn't allow for dynamic scheduling down the road.  

Instead after some discussion with other team members I settled on a different route: crack open the big assemblies with System.Reflection.MetadataReader. That gives us the list of classes and hence we can partition the assembly with `-class` arguments to xunit.  

This approach allowed me to shrink the end to end running time of our big assemblies pretty dramatically:  For instance running Roslyn.Services.CSharp.Editor.UnitTests took 12:50 on my box before this change and 3:30 after (~75% improvement) because I could fully utilize my processor.  

This change doesn't dramatically improve a full test run as our existing scheduling code is already pretty good at maximizing the processor.  It's still an improvement but a relatively small one (around 1-2 minutes).  

The good news though is that our test caching infrastructure means that we're not always doing full test runs anymore.  Right now only ~50% of our runs have to execute the full battery of unit tests.  The rest are caching at least some amount of the assemblies and hence the assembly chunking logic will deliver even faster runs.  

At the moment the scheduling decision is very boring and static.  Over time hoping to improve this to be more dynamic and deliver more savings.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @davkean, @jasonmalinowski, @CyrusNajmabadi, @jcouv, @agocke

**Comment by jcouv** [comment]
LGTM with some questions to consider.

**Comment by jaredpar** [comment]
@tmat addressed your feedback concerning nested types and verified the fix works with xunit.

**Comment by jaredpar** [comment]
Note: i wrote a program to verify that the assembly chunking code will test the exact same set of tests as non-chunking code as a sanity check.  At this point my plan is to merge when this latest round of Jenkins passes.

**Pull request merged**
