### PR TITLE
Ensure we do string-copy-paste before format-on-paste

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Otherwise we have to contend with both the edits made by the user, and what format-on-paste changed them to be.  That makes fixing things up much more difficult.  

Will add tests for this soon.

### CODE REVIEW

**Review by davidwengier — COMMENTED** [review]
Am I misunderstanding or does the code change not match the PR title?

**Comment by CyrusNajmabadi** [comment]
> Am I misunderstanding or does the code change not match the PR title?

Bleagh.  English hard.  There is a chain of command handler.s  We want to do "String copy paste" *closer* to the text buffer than format-document.  e.g. string copy-paste shoudl run first, then format on paste.  So it happens "Before" in that sense.

However, in the actual *chain* of command handlers, that means that we need to have:

FormatDocument->StringCopyPaste->ActualPasteToBuffer

So in that sense StringCopyPaste is *after* in the chain (so that it runs 'before it' in terms of making changes).

Bleagh.

**Review by davidwengier — APPROVED** [review]
Tests definitely would be good here, to prove that the confusing way this has to be done is correct.

**Comment by ryzngard** [comment]
> Ooohhhh, so all of the handlers call `nextHandler()` first? Seems flaky, but I get it.

This confuses me every time I write them :/ but yea... that's how it is. It means order is backwards from the way the attributes are.

**Review by ryzngard — APPROVED** [review]

**Pull request merged**
