### PR TITLE
merge stabilization into master

### PR DESCRIPTION
**Pull request by brettfo**

### CODE REVIEW

**Comment by brettfo** [comment]
FYI: @dotnet/roslyn-infrastructure

**Comment by brettfo** [comment]
test prtest/win/dbg/unit64 please

**Comment by davkean** [comment]
What was the unit64 failure? Can you link to it? (It helps us track what's going on, and serves as a hit count for the issue).

**Comment by brettfo** [comment]
I should have mentioned it in the retest comment.

It was msbuild node reuse issue where it can't find the "Deterministic" parameter on CscTask.

**Comment by brettfo** [comment]
retest prtest/lin/dbg/unit32 please due to a build timeout

**Comment by davkean** [comment]
#6211 for unit64 failure.

What was the linux failure? The last timeout on Linux was a bug in the product.

**Comment by brettfo** [comment]
Filed #6484 for the Linux issue (I couldn't find an existing issue that matched.)

**Comment by brettfo** [comment]
restarting win32 tests due to a hung process on a machine; investigating offline
test prtest/win/dbg/unit32 please

**Comment by brettfo** [comment]
same hung process issue, but the machine has now been fixed
test prtest/win/dbg/unit32 please

**Pull request merged**
