### PR TITLE
Remove unneeded `isPartial` check

### LINKED ISSUE #55825: isPartial check in SourceOrdinaryMethodSymbolBase.MakeModifiers is not verified by tests
#55087

It appears that when the `isPartial` check is removed from `SourceOrdinaryMethodSymbolBase.MakeModifiers`, no tests fail. We should probably determine a scenario that depends on the check, or if no scenario is affected by the check, remove the check from the implementation.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #55825

Commit by commit review will demonstrate why the check is unneeded.

### Commit 1:

- Corrects the value of `isPartial`. For background see #45424, specifically:
    - In #45424, see `SourceOrdinaryMethodSymbol.cs` which had:

        ```csharp
        var defaultAccess = isInterface && modifiers.IndexOf(SyntaxKind.PartialKeyword) < 0 && !isExplicitInterfaceImplementation ? DeclarationModifiers.Public : DeclarationModifiers.Private;
        ```

    - This code was moved to `SourceOrdinaryMethodSymbolBase.cs` as:

        ```csharp
        var defaultAccess = isInterface && isPartial && !isExplicitInterfaceImplementation ? DeclarationModifiers.Public : DeclarationModifiers.Private;
        ```

    - Ooops? The original check was `!isPartial` and the new one is `isPartial`?
    - Nope, `isPartial` passed to `SourceOrdinarySymbolBase` from `SourceOrdinaryMethodSymbol.cs` through base constructor is `isPartial: syntax.Modifiers.IndexOf(SyntaxKind.PartialKeyword) < 0`
    - **NOTE:** The value fixed in commit 1 isn't too important as it will be removed in the second commit. I just wanted to restore the original intent, nothing more.
    - The important part in this commit is following all the possible combinations of `isInterface`, `isPartial`, and `isExplicitInterfaceImplementation` to simplify the code.

### Commit 2:

Look at the truth table I added in commit 1 for all possible combinations, then figure out `isPartial` is unnecessary, and `DeclarationModifiers.Public` is unused.

### CODE REVIEW

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler for second review

**Comment by Youssef1313** [comment]
@AlekseyTs Can you take a look please?

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by AlekseyTs** [comment]
@Youssef1313 Thanks for the contribution!

**Pull request merged**
