### PR TITLE
Remove an unused test resource.

### PR DESCRIPTION
**Pull request by gafter**
Not sure why this resource is here, but it does not appear to be used.

@jaredpar @AlekseyTs Please review

### CODE REVIEW

**Comment by tmat** [comment]
Probably used before we moved metadata tests over to CoreFx

**Comment by gafter** [comment]
I wonder how many other resources we can delete.

**Comment by KevinH-MS** [comment]
LGTM

FWIW, @dsplaisted recently (re)discovered another binary we had checked in somewhat unnecessarily (see #2228).  I don't know how to do it efficiently, but it'd be great to audit all of our binary resources.

**Comment by ManishJayaswal** [comment]
Approved 5/21 by ML Shiproom.

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
