### PR TITLE
Add feature to convert concatenated strings to interpolated strings.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide   Will write tests tomorrow.

**Comment by genlu** [comment]
@dotnet/roslyn-infrastructure There's no test result xml being generated for the failure in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/1703/
Seems like an issue in Xunit itself? 
```
xUnit.net Console Runner (64-bit .NET 4.0.30319.42000)
  Discovering: Roslyn.Services.Editor.UnitTests2
  Discovered:  Roslyn.Services.Editor.UnitTests2
  Starting:    Roslyn.Services.Editor.UnitTests2
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionRulesTests.TestMatchEnglishUpperI
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionRulesTests.TestMatchNonDottedLowerTurkishI
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionRulesTests.TestMatchLowerCaseEnglishI
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.CompletionRulesTests.TestMatchDottedUpperTurkishI
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionWhenExtensionMethodFromMetadata
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionFromVisualBasicMetadataAsSource
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionOnLinqVariable
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestWorksAcrossLanguages
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionWhenInvokedOnLiteral
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestInvokeInEmptyFile
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekDefinitionOnParamNameXmlDocComment
    Microsoft.CodeAnalysis.Editor.UnitTests.Peek.PeekTests.TestPeekAcrossProjectsInvolvingPortableReferences
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.SessionTests.SessionStopsWhenPresenterIsDismissed
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.SessionTests.PresenterIsDismissedWhenSessionIsStopped
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestVisualBasic_SimpleIdentifierAliasExpansion_AliasDoesNotBind
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestVisualBasic_SimpleIdentifierAliasExpansion_AliasDoesNotBind [SKIP]
      https://github.com/dotnet/roslyn/issues/2805
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestCSharp_SimpleIdentifierAliasExpansion_AliasDoesNotBind
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestNoExpansionForPropertyNamesOfObjectInitializers
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestVisualBasic_SimpleIdentifierAliasExpansion_AliasBinds
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestCSharp_GenericNameExpansion_DontExpandAnonymousTypes
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestCSharp_LambdaParameter_DontExpandAnonymousTypes2_variation
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestCSharp_SimpleIdentifierAliasExpansion_AliasBinds
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestCSharp_LambdaParameter_DontExpandAnonymousTypes2
    Microsoft.CodeAnalysis.Editor.UnitTests.Expansion.NameExpansionTests.TestCSharp_LambdaParameter_DontExpandAnonymousTypes1
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestSigHelpNotDismissedAfterQuote
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestGenericNameSigHelpInTypeParameterListMuchAfterConditionalAccess
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestGenericNameSigHelpInTypeParameterListAfterMultipleConditionalAccess
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestSigHelpNotDismissedAfterSpace
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestFilterOnNamedParameters1
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestSigHelpShowsOnBackspace
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.DontShowSignatureHelpIfOptionIsTurnedOffUnlessExplicitlyInvoked
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestSigHelpInLinkedFiles
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestFilterOnNamedParameters2
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestGenericNameSigHelpInTypeParameterListAfterConditionalAccess
    Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicSignatureHelpCommandHandlerTests.TestSigHelpDismissedAfterComment
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictBetweenPropertyAndFieldDeclaration
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictForDelegate
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_OverridingImplicitlyUsedMethod_2
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ResolveConflictWhenAnonymousTypeIsUsedAsGenericArgument
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_ConflictBetweenTypeParameterAndMember_2
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictForIsolatedScopes
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictForIsolatedScopes [SKIP]
      917043
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_ConflictBetweenTypeParametersInMethodDeclaration
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictInsideAttributeArgument
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_ConflictBetweenTypeParametersInTypeDeclaration
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ResolveConflictInAnonymousTypeProperty
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_ConflictBetweenTypeParametersInMethodDeclaration_2
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictBetweenMemberDeclarationsWithOutOrRefDifferenceOnly
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_OverridingImplicitlyUsedMethod
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_OverridingImplicitlyUsedMethod_1
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictBetweenFieldAndMethodDeclaration
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictBetweenMethodsDifferingByArity
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_ConflictInFieldInitializerOfFieldAndModuleNameResolvedThroughFullQualification
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictWithNamespaceDefinedInMetadata
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictBetweenMethodDeclarations
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictWithEquallyNamedNamespaces
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictBetweenParameterDeclarations
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_ConflictBetweenTypeParameterAndMember_1
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.CS_NoConflictBetweenLambdaParameterAndField
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.ConflictBetweenFields
    Microsoft.CodeAnalysis.Editor.UnitTests.Rename.CSharp.DeclarationConflictTests.NoConflictBetweenMethodsOfDifferentSignature
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateEvent.GenerateEventCrossLanguageTests.TestGenerateEventInCSharpFileFromImplementsWithType
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateEvent.GenerateEventCrossLanguageTests.PreferNormalFileOverAutoGeneratedFile_Basic
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateEvent.GenerateEventCrossLanguageTests.TestGenerateEventInCSharpFileFromHandles
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateEvent.GenerateEventCrossLanguageTests.TestGenerateEventInCSharpFileFromImplementsWithParameterList
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.GenerateMethodUsingTypeConstraint_SingleNamedType
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.TestDelegate_CSharpToVisualBasic
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.TestIntoNestedType_VisualBasicToCSharp
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.GenerateMethodUsingTypeConstraint_3BaseTypeConstraints_CommonDerivedInstantiatedTypes
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.GenerateMethodUsingTypeConstraint_2BaseTypeConstraints_Interfaces
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.PreferNormalFileOverAutoGeneratedFile_Basic
    Microsoft.CodeAnalysis.Editor.UnitTests.Diagnostics.GenerateMethod.GenerateMethodCrossLanguageTests.TestIntoNestedGenericType_CSharpToVisualBasic
  Finished:    Roslyn.Services.Editor.UnitTests2
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestRunner.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 136
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 205
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestAssemblyRunner`1.<RunTestCollectionsAsync>d__42.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestAssemblyRunner.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.XunitTestAssemblyRunner.<RunTestCollectionsAsync>d__14.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.TestAssemblyRunner`1.<RunAsync>d__41.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestAssemblyRunner.cs:line 198
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.XunitTestFrameworkExecutor.<RunTestCases>d__6.MoveNext() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by genlu** [comment]
@dotnet-bot retest windows_release_unit64_prtest, please

**Comment by genlu** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by CyrusNajmabadi** [comment]
Tests added.

**Pull request merged**
