### PR TITLE
Fixing the build version to be 'correct' for 'official' builds where no build number was specified.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jasonmalinowski, @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
So mind you the 8800 change should really be 8800 * the number of years since 2016. Should we just be directly setting the FiveDigitDateStamp directly to avoid the magic?

**Comment by tannergooding** [comment]
I can do that if you prefer. I was just updating it to be inline with the current logic. Ideally, we would be doing the correct math here and BuildNumber would just be set to 65535 and then the math would do the correct thing.

**Comment by tannergooding** [comment]
@jasonmalinowski, I am closing this. Feel free to re-open against infraswat if you desire.

**Comment by jasonmalinowski** [comment]
@tannergooding I don't even remember what this is. 👍

**Comment by tannergooding** [comment]
@jasonmalinowski, because we subtract 8800 here https://github.com/dotnet/roslyn/pull/16403/files#diff-54b0b12edf4b708f4af885f636027cc8R43, there are some cases when the build number will be "incorrect" (if you specify /p:OfficialBuild=true, without also specifying a BuildNumber). The VSIX from that build will then not be installable since they are "older".

**Comment by tannergooding** [comment]
This was just fixing that.

**Pull request closed without merging**
