### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by cston** [comment]
@dotnet-bot test windows_build_correctness_prtest please

**Comment by cston** [comment]
@dotnet-bot test windows_build_correctness_prtest please

**Comment by jaredpar** [comment]
You should integrate changes like this with git blame so we can know who all the bad spellers are.

Spoiler: i am one of the worst

**Comment by jaredpar** [comment]
FYI: the compiler generated files are now out of date (that is why the build correctness leg is failing). Run the following to fix 

```
build\scripts\generate-compiler-code.cmd
```

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by cston** [comment]
@dotnet/roslyn-compiler for a second review please.

**Pull request merged**
