### PR TITLE
Hide InternalsVisibleToTypeScript items from UI tree

### PR DESCRIPTION
**Pull request by davkean**
InternalsVisibleToTypeScript items are showing up the Solution Explorer visual tree
as missing items (because the C# project system treats them as files). Hide them
like the other InternalsVisibleToXX items.

### CODE REVIEW

**Comment by davkean** [comment]
@Pilchie @CyrusNajmabadi @jasonmalinowski @rchande @brettfo @balajikris @basoundr @jasonmalinowski

**Comment by rchande** [comment]
:+1:

**Comment by balajikris** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
If you're bored, we really should just make the key to be used metadata rather than creating separate item types... But :+1: otherwise.

**Pull request merged**
