### PR TITLE
Document "Better Betterness" for C# 6 and the compat fix

### PR DESCRIPTION
**Pull request by gafter**
described in #6560 and #7727.

You can find the docs pretty-printed at https://github.com/gafter/roslyn/blob/doc6560/docs/specs/CSharp%206/Better%20Betterness.md
@AlekseyTs @MadsTorgersen Please review
/cc @dotnet/roslyn-compiler FYI

### CODE REVIEW

**Comment by davkean** [comment]
(Closing/opening to sync update the merge branch to pick up the build break we just fixed)

**Comment by davkean** [comment]
unit test failure due to #6358, can be ignored. I've submit #7940 to fix it.

**Comment by TyOverby** [comment]
@davkean: Considering that this PR just adds a markdown file, I don't think we need to worry about tests for this one :stuck_out_tongue_closed_eyes:

**Comment by davkean** [comment]
@TyOverby Yes, but our aim should be to have green builds regardless. We want devs to have confidence in Jenkins.

**Comment by AlekseyTs** [comment]
Description of compatibility fix LGTM.

**Pull request merged**
