### PR TITLE
Revert "Delete unused SQM interfaces (#14299)"

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This reverts commit 7259d90be5b99ab9e67cbc90f70be1a0a920317b. These
are still being pulled in by the ruleset editor.

FYI to @dotnet/roslyn-infrastructure, @tmat

### CODE REVIEW

**Comment by tmat** [comment]
Why not move the source to ruleset editor then?

**Comment by jasonmalinowski** [comment]
@tmat We will, but this first brings up integration tests off the floor.

**Comment by tmat** [comment]
👍

**Comment by jasonmalinowski** [comment]
@tmat Also, since we still support running tests on Dev14, that code has already shipped and thus we have to support it. (Although perhaps not for much longer.)

**Comment by jasonmalinowski** [comment]
I'm going to merge this (overriding full CI validation) once I get at least one green build verifying the product fully builds.

**Comment by jasonmalinowski** [comment]
windows_eta_open_prtest has passed the build phase, and is already passing ETA tests. That's enough for me.

**Pull request merged**
