### PR TITLE
Public API checker should ignore protected members on uninheritable types

### LINKED ISSUE #3287: Public API checker should ignore protected members on uninheritable types
This concerns APIs which are `protected` on `public` types which can't be inherited from by customers.  In particular:

- Types which are `sealed`
- Types whose constructors are all `internal` or `private`

For such types the effective accessibility to customers is `internal`.  We should be free to modify, delete, etc ... those members post RTM.  The Public API checker should be updated to reflect that. 

---- Additions 2015-06-09 by @gafter ----

In addition we will give an **error** when an API occurs with the following pattern:

1. `Type1` is public but has only `internal` (no `public` or `protected`) constructors.
2. `Type2` extends `Type1`, is `public` and is not `sealed`, and has a `public` or `protected` constructor.

In that case the public API checker will report an error on each offending constructor in `Type2`. The reason is that `Type2` might be exposing members of `Type1` that are not considered part of the public API of `Type1`. To put it another way, `Type1` is considered "not inheritable by customers" but `Type2` violates that by making it inheritable.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #3287

@tmeschter **Can I please have your help with this?** I think this is the right set of code changes for the checker for #3287 (can you please review the changes?), but I don't know how to do the following remaining steps:

1. For purposes of hand-testing, replace the checker nuget with the one built here, and hand-check that the set of errors reported against the various `PublicApi.txt` are the expected ones
2. Produce a nuget package for the Roslyn API checker that reflects the changes here
3. Update the referenced nuget package for the checker to the one produced.

Once that is done we will need to submit a new/updated pull request that has these code changes, the updated PublicApi.txt, and the project changes to reference the newly created nuget package.

### CODE REVIEW

**Comment by gafter** [comment]
@tmeschter @mavasani CC @jaredpar 

Can you please help me test this? I don't know how to do step (1) above.

**Comment by gafter** [comment]
@tmeschter Can you please take the next step with this PR as we discussed?

**Comment by tmeschter** [comment]
@gafter I'm taking a look at this now.

The Microsoft.Net.ToolsetCompilers NuGet was merged into the Microsoft.Net.Compilers NuGet, which is why the instructions were wrong. I'm updating them as I go through them.

**Comment by tmeschter** [comment]
@gafter I've been able to build and run the updated analyzer, but it no longer seems to consider certain public members to actually be public.

For example, the `Microsoft.CodeAnalysis.CompilationOptions` class is public, with a public `AssemblyIdentityComparer` property, with a protected setter. The setter is definitely part of the public API, but is no longer identified as such by the analyzer.

**Comment by jaredpar** [comment]
@tmeschter the `CompilationOptions` type has only `internal` constructors, hence the `protected` members are not accessible to customers.

**Comment by tmeschter** [comment]
@jaredpar @gafter Oh, right. Never mind, then. Somewhere along the line I forgot that was the point of this change. ;-)

**Comment by tmeschter** [comment]
What about this scenario?

``` C#
public sealed class Alpha
{
    internal Alpha() { ... }

    protected class Beta
    {
        ...
    }
}
```

Should Beta be considered part of the public API?

I'm asking because I don't have time to actually check and see if the compiler allows this and whether or not the analyzer handles it correctly. ;-)

**Comment by jaredpar** [comment]
@tmeschter yes that should be considered public.

**Comment by gafter** [comment]
I don't think `Beta` is part of the public API. There is no way for it to be used outside its own assembly.

**Comment by jaredpar** [comment]
@gafter ah yes you're correct.  That's not accessible.

**Comment by gafter** [comment]
However, I don't think the spec in #3287 (and therefore implemented here) is correct for the following case:

```cs
public class Alpha
{
    internal Alpha() { }

    // is Question part of the "public API"?
    protected void Question() { }
}

public class Beta : Alpha
{
    public Beta() { }
}
```

Since `Beta` can be extended outside its assembly, `Alpha.Question` can be used in those extensions.

Jared: what was your intention for the spec in #3287? We rejected some access changes in shiproom (actually, didn't take them to shiproom) because you believed it was possible to modify the public API checker to handle the relevant APIs. Do you still believe that possible? If so we need to come up with a modified spec.

**Comment by jaredpar** [comment]
@gafter hmm, that's a good point.  Maybe we should extend the checker to flag such inheritance, as exhibited by `Beta`, as an error in the `public` API checker.  I would argue that `Alpha` had no intent of being extensible by customers but `Beta` has covertly added the capability.  Seems like that shouldn't occur without `Alpha` explicitly opting into it.

**Comment by gafter** [comment]
@jaredpar It isn't clear to me that this isn't a valid API shape. Perhaps the intent is that `Alpha` be publicly extensible only through `Beta`. I suspect, though, that this API pattern does not appear in Roslyn, so it is probably OK to flag it as an error for our purposes.

**Comment by jaredpar** [comment]
@gafter I agree it can absolutely be valid.  But it does seem like it should require some acknowledgement on `Alpha` that it intended to allow for public extensibility.  An attribute for example.

**Comment by gafter** [comment]
@jaredpar OK, since (as far as I know) we do not use that API pattern in Roslyn, I will implement that check, but without providing an attribute that the API could use to declare it being intentional.

Specifically, the check will give an **error** when an API occurs with the following pattern:

1. `Type1` is public but has only `internal` (no `public` or `protected`) constructors.
2. `Type2` extends `Type1`, is `public` and is not `sealed`, and has a `public` or `protected` constructor.

In that case the public API checker will report an error on each offending constructor in `Type2`.

I will prepare a revision of this PR to implement that.

**Comment by gafter** [comment]
@jaredpar @tmeschter I have added to this PR an implementation of the rule described in #3287, namely

> In addition we will give an **error** when an API occurs with the following pattern:

> 1. `Type1` is public but has only `internal` (no `public` or `protected`) constructors.
2. `Type2` extends `Type1`, is `public` and is not `sealed`, and has a `public` or `protected` constructor.

> In that case the public API checker will report an error on each offending constructor in `Type2`. The reason is that `Type2` might be exposing members of `Type1` that are not considered part of the public API of `Type1`. To put it another way, `Type1` is considered "not inheritable by customers" but `Type2` violates that by making it inheritable.

**Comment by gafter** [comment]
@jaredpar @tmeschter Please review.

**Comment by gafter** [comment]
After making this change, we see the following deletions from the public API, which I believe is exactly what we wanted.

```none
'Microsoft.CodeAnalysis.CompilationOptions.AssemblyIdentityComparer.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.CheckOverflow.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.ConcurrentBuild.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.CryptoKeyContainer.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.CryptoKeyFile.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.CryptoPublicKey.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.DelaySign.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.EqualsHelper(Microsoft.CodeAnalysis.CompilationOptions other) -> bool'
'Microsoft.CodeAnalysis.CompilationOptions.Features.get -> System.Collections.Immutable.ImmutableArray<string>'
'Microsoft.CodeAnalysis.CompilationOptions.Features.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.GeneralDiagnosticOption.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.GetHashCodeHelper() -> int'
'Microsoft.CodeAnalysis.CompilationOptions.MainTypeName.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.MetadataReferenceResolver.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.ModuleName.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.OptimizationLevel.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.OutputKind.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.Platform.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.ScriptClassName.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.SourceReferenceResolver.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.SpecificDiagnosticOptions.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.StrongNameProvider.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.WarningLevel.set -> void'
'Microsoft.CodeAnalysis.CompilationOptions.XmlReferenceResolver.set -> void'
'Microsoft.CodeAnalysis.ParseOptions.DocumentationMode.set -> void'
'Microsoft.CodeAnalysis.ParseOptions.EqualsHelper(Microsoft.CodeAnalysis.ParseOptions other) -> bool'
'Microsoft.CodeAnalysis.ParseOptions.GetHashCodeHelper() -> int'
'Microsoft.CodeAnalysis.ParseOptions.Kind.set -> void'
'Microsoft.CodeAnalysis.SyntaxNode.GetRed<T>(ref T field, int slot) -> T'
'Microsoft.CodeAnalysis.SyntaxNode.GetRedAtZero<T>(ref T field) -> T'
'abstract Microsoft.CodeAnalysis.CommandLineArguments.CompilationOptionsCore.get -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CommandLineArguments.ParseOptionsCore.get -> Microsoft.CodeAnalysis.ParseOptions'
'abstract Microsoft.CodeAnalysis.Compilation.AppendDefaultVersionResource(System.IO.Stream resourceStream) -> void'
'abstract Microsoft.CodeAnalysis.Compilation.CommonAddSyntaxTrees(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxTree> trees) -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonAssembly.get -> Microsoft.CodeAnalysis.IAssemblySymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonClone() -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonContainsSyntaxTree(Microsoft.CodeAnalysis.SyntaxTree syntaxTree) -> bool'
'abstract Microsoft.CodeAnalysis.Compilation.CommonCreateArrayTypeSymbol(Microsoft.CodeAnalysis.ITypeSymbol elementType, int rank) -> Microsoft.CodeAnalysis.IArrayTypeSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonCreatePointerTypeSymbol(Microsoft.CodeAnalysis.ITypeSymbol elementType) -> Microsoft.CodeAnalysis.IPointerTypeSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonDynamicType.get -> Microsoft.CodeAnalysis.ITypeSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetAssemblyOrModuleSymbol(Microsoft.CodeAnalysis.MetadataReference reference) -> Microsoft.CodeAnalysis.ISymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetCompilationNamespace(Microsoft.CodeAnalysis.INamespaceSymbol namespaceSymbol) -> Microsoft.CodeAnalysis.INamespaceSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetEntryPoint(System.Threading.CancellationToken cancellationToken) -> Microsoft.CodeAnalysis.IMethodSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetMetadataReference(Microsoft.CodeAnalysis.IAssemblySymbol assemblySymbol) -> Microsoft.CodeAnalysis.MetadataReference'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetSemanticModel(Microsoft.CodeAnalysis.SyntaxTree syntaxTree, bool ignoreAccessibility) -> Microsoft.CodeAnalysis.SemanticModel'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetSpecialType(Microsoft.CodeAnalysis.SpecialType specialType) -> Microsoft.CodeAnalysis.INamedTypeSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGetTypeByMetadataName(string metadataName) -> Microsoft.CodeAnalysis.INamedTypeSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonGlobalNamespace.get -> Microsoft.CodeAnalysis.INamespaceSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonObjectType.get -> Microsoft.CodeAnalysis.INamedTypeSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonOptions.get -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.Compilation.CommonRemoveAllSyntaxTrees() -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonRemoveSyntaxTrees(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxTree> trees) -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonReplaceSyntaxTree(Microsoft.CodeAnalysis.SyntaxTree oldTree, Microsoft.CodeAnalysis.SyntaxTree newTree) -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonSourceModule.get -> Microsoft.CodeAnalysis.IModuleSymbol'
'abstract Microsoft.CodeAnalysis.Compilation.CommonSyntaxTrees.get -> System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxTree>'
'abstract Microsoft.CodeAnalysis.Compilation.CommonWithAssemblyName(string outputName) -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonWithOptions(Microsoft.CodeAnalysis.CompilationOptions options) -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.Compilation.CommonWithReferences(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.MetadataReference> newReferences) -> Microsoft.CodeAnalysis.Compilation'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithAssemblyIdentityComparer(Microsoft.CodeAnalysis.AssemblyIdentityComparer comparer) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithFeatures(System.Collections.Immutable.ImmutableArray<string> features) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithGeneralDiagnosticOption(Microsoft.CodeAnalysis.ReportDiagnostic generalDiagnosticOption) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithMetadataReferenceResolver(Microsoft.CodeAnalysis.MetadataReferenceResolver resolver) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithOptimizationLevel(Microsoft.CodeAnalysis.OptimizationLevel value) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithOutputKind(Microsoft.CodeAnalysis.OutputKind kind) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithPlatform(Microsoft.CodeAnalysis.Platform platform) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithSourceReferenceResolver(Microsoft.CodeAnalysis.SourceReferenceResolver resolver) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithSpecificDiagnosticOptions(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, Microsoft.CodeAnalysis.ReportDiagnostic>> specificDiagnosticOptions) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithSpecificDiagnosticOptions(System.Collections.Immutable.ImmutableDictionary<string, Microsoft.CodeAnalysis.ReportDiagnostic> specificDiagnosticOptions) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithStrongNameProvider(Microsoft.CodeAnalysis.StrongNameProvider provider) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.CompilationOptions.CommonWithXmlReferenceResolver(Microsoft.CodeAnalysis.XmlReferenceResolver resolver) -> Microsoft.CodeAnalysis.CompilationOptions'
'abstract Microsoft.CodeAnalysis.Metadata.CommonCopy() -> Microsoft.CodeAnalysis.Metadata'
'abstract Microsoft.CodeAnalysis.ParseOptions.CommonWithDocumentationMode(Microsoft.CodeAnalysis.DocumentationMode documentationMode) -> Microsoft.CodeAnalysis.ParseOptions'
'abstract Microsoft.CodeAnalysis.ParseOptions.CommonWithFeatures(System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, string>> features) -> Microsoft.CodeAnalysis.ParseOptions'
'abstract Microsoft.CodeAnalysis.SyntaxNode.EquivalentToCore(Microsoft.CodeAnalysis.SyntaxNode other) -> bool'
'abstract Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(int position, System.Func<Microsoft.CodeAnalysis.SyntaxTrivia, bool> stepInto) -> Microsoft.CodeAnalysis.SyntaxToken'
'abstract Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(int position, bool findInsideTrivia) -> Microsoft.CodeAnalysis.SyntaxToken'
'abstract Microsoft.CodeAnalysis.SyntaxNode.FindTriviaCore(int position, bool findInsideTrivia) -> Microsoft.CodeAnalysis.SyntaxTrivia'
'abstract Microsoft.CodeAnalysis.SyntaxNode.InsertNodesInListCore(Microsoft.CodeAnalysis.SyntaxNode nodeInList, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxNode> nodesToInsert, bool insertBefore) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.InsertTokensInListCore(Microsoft.CodeAnalysis.SyntaxToken originalToken, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxToken> newTokens, bool insertBefore) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.InsertTriviaInListCore(Microsoft.CodeAnalysis.SyntaxTrivia originalTrivia, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxTrivia> newTrivia, bool insertBefore) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.IsEquivalentToCore(Microsoft.CodeAnalysis.SyntaxNode node, bool topLevel = false) -> bool'
'abstract Microsoft.CodeAnalysis.SyntaxNode.KindText.get -> string'
'abstract Microsoft.CodeAnalysis.SyntaxNode.NormalizeWhitespaceCore(string indentation, bool elasticTrivia) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.RemoveNodesCore(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxNode> nodes, Microsoft.CodeAnalysis.SyntaxRemoveOptions options) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.ReplaceCore<TNode>(System.Collections.Generic.IEnumerable<TNode> nodes = null, System.Func<TNode, TNode, Microsoft.CodeAnalysis.SyntaxNode> computeReplacementNode = null, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxToken> tokens = null, System.Func<Microsoft.CodeAnalysis.SyntaxToken, Microsoft.CodeAnalysis.SyntaxToken, Microsoft.CodeAnalysis.SyntaxToken> computeReplacementToken = null, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxTrivia> trivia = null, System.Func<Microsoft.CodeAnalysis.SyntaxTrivia, Microsoft.CodeAnalysis.SyntaxTrivia, Microsoft.CodeAnalysis.SyntaxTrivia> computeReplacementTrivia = null) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.ReplaceNodeInListCore(Microsoft.CodeAnalysis.SyntaxNode originalNode, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxNode> replacementNodes) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.ReplaceTokenInListCore(Microsoft.CodeAnalysis.SyntaxToken originalToken, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxToken> newTokens) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.ReplaceTriviaInListCore(Microsoft.CodeAnalysis.SyntaxTrivia originalTrivia, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.SyntaxTrivia> newTrivia) -> Microsoft.CodeAnalysis.SyntaxNode'
'abstract Microsoft.CodeAnalysis.SyntaxNode.SyntaxTreeCore.get -> Microsoft.CodeAnalysis.SyntaxTree'
'override Microsoft.CodeAnalysis.AssemblyMetadata.CommonCopy() -> Microsoft.CodeAnalysis.Metadata'
'override Microsoft.CodeAnalysis.LocalizableResourceString.AreEqual(object other) -> bool'
'override Microsoft.CodeAnalysis.LocalizableResourceString.GetHash() -> int'
'override Microsoft.CodeAnalysis.LocalizableResourceString.GetText(System.IFormatProvider formatProvider) -> string'
'override Microsoft.CodeAnalysis.ModuleMetadata.CommonCopy() -> Microsoft.CodeAnalysis.Metadata'
'virtual Microsoft.CodeAnalysis.Emit.EmitResult.GetDebuggerDisplay() -> string'
'virtual Microsoft.CodeAnalysis.Location.GetDebuggerDisplay() -> string'
```

@jaredpar @mattwar @tmeschter Please review this so it can be submitted to shiproom.

**Comment by MattGertz** [comment]
Approved 6/11 by ML Shiproom.

**Comment by tmeschter** [comment]
:+1:

**Pull request merged**
