### PR TITLE
Skip tests on 32bit debug due to messagepack issue

### PR DESCRIPTION
**Pull request by dibarbet**
Same issue as https://github.com/dotnet/roslyn/issues/64195

These have been failing on rolling builds - https://dev.azure.com/dnceng-public/public/_build/results?buildId=103227&view=results

### CODE REVIEW

**Review by arkalyanms — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Do we still have to support VS32bit?  If not, could we just mandate 64bit and only test there and only have code for that?

If we do need to support vs32bit, then this issue def worries me as it makes me think there's some deep issue that we're being blind to by this that will hit customers.

**Comment by CyrusNajmabadi** [comment]
@arkalyanms  ^

**Comment by arkalyanms** [comment]
> Do we still have to support VS32bit? If not, could we just mandate 64bit and only test there and only have code for that?
> 
> If we do need to support vs32bit, then this issue def worries me as it makes me think there's some deep issue that we're being blind to by this that will hit customers.

Thats a reasonable line to hold. 
- When we service to 32 bit installs, we can use a selectively picked test suite to regression test.
- Is there a nuget package route that will hit 32 bit installs continuously though?

**Pull request merged**
