### PR TITLE
Update binding redirects of csc, vbc, vbcscompiler

### PR DESCRIPTION
**Pull request by tmat**
See also #7612

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure @dotnet/roslyn-compiler

**Comment by davkean** [comment]
What am I missing this change doesn't match the description of the bug?

Does this mean that the csc.exe is currently broken in VSUML builds?

**Comment by KevinH-MS** [comment]
Why do these have *any* binding redirects?  @jasonmalinowski any thoughts?

**Comment by tmat** [comment]
@davkean The change is not fixing the bug. It's just updating the redirects manually. The work item is to write a script to do so.

I think we need these redirects in order for analyzers loaded into the compiler process to work.

**Comment by jasonmalinowski** [comment]
:+1:. Do we actually have compilation APIs somewhere that expose the underlying metadata reader?

**Comment by tannergooding** [comment]
:+1:

**Comment by tmat** [comment]
@jasonmalinowski Yes. EnC API. There will be more in future, once we do IL analysis.

**Pull request merged**
