### PR TITLE
Fix intermittent crash in CompilationWithAnalyzers due to an OjbectDi…

### PR DESCRIPTION
**Pull request by mavasani**
…sposedException.

Fixes VSO Bug [199252](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=199252)

Root cause: We were attempting to access the cancellation token for a cancellation token source within a lambda within the using statement for the token source. If client fires a cancellation before the task within the lambda executes, the token source may have been disposed when the task is eventually activated.

Fix: This change saves the cancellation token for the token source upfront for use within the lambda and also checks for cancellation before computing diagnostics.

Justification for ask mode: We are hitting this intermittent crash in perf runs in an internal VSO branch and fix doesn't have any risks.

### CODE REVIEW

**Comment by mavasani** [comment]
test vsi please

**Comment by mavasani** [comment]
@dotnet/roslyn-analysis - can someone take a look? This is for Update2 ask mode.

I'll send a separate PR against future-stabilization.

**Comment by heejaechang** [comment]
:+1:

**Comment by mavasani** [comment]
Tagging @MattGertz for ask mode approval.

I have sent a separate PR for porting the fix to future-stabilization: https://github.com/dotnet/roslyn/pull/9622

**Comment by srivatsn** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved pending successful completion of tests.

**Pull request merged**
