### PR TITLE
[WIP] Run integration tests in Visual Studio 2017 version 15.6

### PR DESCRIPTION
**Pull request by sharwell**
@dotnet/roslyn-infrastructure I'm having trouble running integration tests locally because the harness keeps finding my 15.5 instance. This change updates the default version requirement to state 15.6. This fixes the problem locally, but has a downside of required maintenance. I'm open to ideas for alternate approaches.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
This is fine, but should target dev15.7.x-vs-deps as technically we haven't mandated the minimum requirement yet. Notably, integration test machines don't 15.6 yet hence your failures.

But yes, this is the correct thing to do.

> but has a downside of required maintenance.

What maintenance? It's our minimum version, so we should state that. :-)

**Comment by sharwell** [comment]
> Notably, integration test machines don't 15.6 yet hence your failures.

How are the tests passing on the integration test machines? I'm running the dev15.7.x branch locally and the integration tests fail instantly because they attempt to use an API which is new for 15.6.

**Comment by jasonmalinowski** [comment]
> How are the tests passing on the integration test machines? I'm running the dev15.7.x branch locally and the integration tests fail instantly because they attempt to use an API which is new for 15.6.

We've disabled them for -vs-deps, which is where any dependencies should have gone. Jenkins shows we are green for dev15.7.x itself:

https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x/job/windows_debug_vs-integration/

What API are you running into?

**Comment by sharwell** [comment]
This is the wrong solution to the problem. The right solution is to make the tests select the correct instance for the current install of VS from multiples on a system with side-by-side installations.

**Pull request closed without merging**
