### PR TITLE
Do not even attempt to create indices for non-C#/VB projects.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Tagging @jasonmalinowski @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Also tagging @dotnet/roslyn-ide for any additional reviews.

@MattGertz we've identified a crash in TypeScript projects that would block tomorrow's RI. At this point we _believe_ that might be the only pending issue, so we'll be looking to get this merged in.

**Comment by CyrusNajmabadi** [comment]
Have smoke tested this.

**Comment by CyrusNajmabadi** [comment]
Will try to merge myself.  If i'm not around, anyone is free to merge this in.

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_vs-integration_prtest please

**Pull request merged**
