### PR TITLE
Port #33631 to dev16.0 (Low priority for code wrapping refactorings)

### PR DESCRIPTION
**Pull request by mavasani**
Code wrapping refactorings should be lower pri than other refactorings

Ports https://github.com/dotnet/roslyn/pull/33631 to dev16.0 branch

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@mavasani was this just a cherry-pick?  if so, if you do `cherry-pick -x` it will keep track of the original commit hash.

**Comment by mavasani** [comment]
@CyrusNajmabadi I am trying still having a hard time to retain the same commit hash. I attempted `git cherry-pick -x 8d53065 -m 1` but that still creates a new commit hash.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I am trying still having a hard time to retain the same commit hash. I attempted `git cherry-pick -x 8d53065 -m 1` but that still creates a new commit hash.

Sorry, i wasn't clear.  You'll def get a new commit hash.  It's just that by doing `-x` this new commit will properly point to the cherrypicked commit.

**Comment by CyrusNajmabadi** [comment]
> -x
>
>  When recording the commit, append a line that says "(cherry picked from commit …​)" to the original commit message in order to indicate which commit this change was cherry-picked from. This is done only for cherry picks without conflicts. Do not use this option if you are cherry-picking from your private branch because the information is useless to the recipient. If on the other hand you are cherry-picking between two publicly visible branches (e.g. backporting a fix to a maintenance branch for an older release from a development branch), adding this information can be useful.

It's a minor thing.  But it helps me know that thsi was just a cherry.

**Comment by mavasani** [comment]
@CyrusNajmabadi Thanks, just force pushed https://github.com/dotnet/roslyn/commit/c9183bdd5ac2493ad95c6eb6b6f49b7ada913893

**Comment by jinujoseph** [comment]
Once merged will be available in 16.RC.2

**Comment by CyrusNajmabadi** [comment]
Thanks.  if this is just a CP, with no changes.  the 👍 from me

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
