### PR TITLE
Make db lock static to investigate issue.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by sharwell** [comment]
@CyrusNajmabadi Marked this as a draft for the investigation. Can you modify the implementation to force the use of the V2 provider (overriding the experiment and normal default)?

**Comment by CyrusNajmabadi** [comment]
>  Can you modify the implementation to force the use of the V2 provider (overriding the experiment and normal default)?

Done!

**Comment by CyrusNajmabadi** [comment]
@sharwell do we want to take this (reverting the default-change portion of course)?

It's a very small change prior to hte larger refactoring you're proposing.

**Comment by CyrusNajmabadi** [comment]
Marking as ready for review.  I would like if we could take this simple change @sharwell.  We can then take the composition change approach you're suggesting.  That way, if we have to roll that back, we can rollback to this safe and simple change.  Thanks!

**Review by sharwell — APPROVED** [review]
This is a generally safe change. Recommend squashing before or during merge to avoid 7 commits for the small change. 😄

**Comment by CyrusNajmabadi** [comment]
Will squash on commit.

**Comment by sharwell** [comment]
@CyrusNajmabadi A bunch of these appeared in the failed build. Probably not a bug from this pull request, but generally indicates a bug.

```
10/12/2020 18:54:11 Coordinated Universal Time: Error : 1 :[devenv:1504] Unexpected exception: StreamJsonRpc.RemoteInvocationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
VROhtD5PELooLfOUfRByOGlBIc0=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
uX5V7tpF70sDgeZIaVvYLCpi2tk=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
Ah9ag+BOb7WXoQSsz92FvN0JnxE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
YN6NcMTUSiEbgMYdkvdBPb+9iIM=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
VROhtD5PELooLfOUfRByOGlBIc0=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
uX5V7tpF70sDgeZIaVvYLCpi2tk=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
Ah9ag+BOb7WXoQSsz92FvN0JnxE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
YN6NcMTUSiEbgMYdkvdBPb+9iIM=, Microsoft.CodeAnalysis.Options.SerializableOptionSet



   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__133`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__10`1.MoveNext() in /_/src/Workspaces/Remote/Core/BrokeredServiceConnection.cs:line 114
RPC server exception:
System.InvalidOperationException: Differences detected in solution checksum: assets only in the incremental solution but not in the request
VROhtD5PELooLfOUfRByOGlBIc0=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
uX5V7tpF70sDgeZIaVvYLCpi2tk=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in new solution but not in incremental solution
Ah9ag+BOb7WXoQSsz92FvN0JnxE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
YN6NcMTUSiEbgMYdkvdBPb+9iIM=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in incremental solution but not in new solution
VROhtD5PELooLfOUfRByOGlBIc0=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
uX5V7tpF70sDgeZIaVvYLCpi2tk=, Microsoft.CodeAnalysis.Options.SerializableOptionSet

assets only in the request but not in incremental solution
Ah9ag+BOb7WXoQSsz92FvN0JnxE=, Microsoft.CodeAnalysis.Serialization.SolutionStateChecksums
YN6NcMTUSiEbgMYdkvdBPb+9iIM=, Microsoft.CodeAnalysis.Options.SerializableOptionSet



      at Microsoft.CodeAnalysis.Remote.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Workspaces/Remote/ServiceHub/Services/Host/ThrowingTraceListener.cs:line 14
      at System.Diagnostics.TraceInternal.Fail(String message)
      at Microsoft.CodeAnalysis.Remote.TestUtils.<AssertChecksumsAsync>d__2.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/TestUtils.cs:line 79
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<ValidateChecksumAsync>d__19.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 525
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.<CreateSolutionAsync>d__6.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.SolutionCreator.cs:line 89
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<CreateSolution_NoLockAsync>d__10.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 135
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.<GetSolutionAsync>d__12.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Host/RemoteWorkspace.cs:line 213
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.RemoteDocumentHighlightsService.<>c__DisplayClass2_0.<<GetDocumentHighlightsAsync>b__0>d.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/DocumentHighlights/RemoteDocumentHighlightsService.cs:line 40
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
      at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceAsync>d__11`1.MoveNext() in /_/src/Workspaces/Remote/ServiceHub/Services/BrokeredServiceBase.cs:line 69
```

**Pull request merged**
