### PR TITLE
Normalize references to Microsoft.VisualStudio.Composition

### PR DESCRIPTION
**Pull request by jasonmalinowski**
We had one bad reference HintPath that caused resolution issues inside
Visual Studio. While we're here, make sure they're all the same.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@davkean, @Pilchie for code review.

**Comment by jasonmalinowski** [comment]
And note I have this aiming for the stabilization branch since that's where people are now. It'll flow into master in due course.

**Comment by pharring** [comment]
LGTM (although, I would have made the change in master and cherry-pick it into stabilization if/when Shiproom approves it)

**Comment by jasonmalinowski** [comment]
@Pilchie, what's the policy for stuff like this? I'd prefer to make it in stabilization because

1. the change can then flow back to master per the usual merge vs. lots of cherry-picking
2. people working in stabilization (which is hopefully everyone right now) will see the change quickly

**Comment by Pilchie** [comment]
I'll take it for consideration tomorrow.

**Comment by MattGertz** [comment]
Approved 5/27 by ML Shiproom.

**Pull request merged**
