### PR TITLE
[Test Only]. CI Perf

### PR DESCRIPTION
**Pull request by pharring**
For testing only. Do not merge.

@dotnet-bot test perf please.

### CODE REVIEW

**Comment by pharring** [comment]
@dotnet-bot test perf please.

**Comment by pharring** [comment]
@dotnet-bot test perf please.

**Comment by pharring** [comment]
@dotnet-bot test perf please.

**Comment by pharring** [comment]
@dotnet-bot test perf please.

**Comment by pharring** [comment]
@dotnet-bot test perf please.

**Comment by pharring** [comment]
@dotnet-bot test perf please.

**Comment by davkean** [comment]
we've stopped using mono, it broke linux,

retest linux please

**Comment by davkean** [comment]
Closing this  - as it no longer seems relevant. Feel free to reopen if it is.

**Pull request closed without merging**
