### PR TITLE
Use raw strings in regex tests

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Done with tool.  If you do want to look at this turn whitespace off :)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@ToddGrun another few files :)

**Comment by CyrusNajmabadi** [comment]
Note: this wasn't done until now because a lot of these tests uses interpolated strings, and it was only recently that i added support for converting these.

**Comment by CyrusNajmabadi** [comment]
> This looks weird, is this really the intended behavior?

Yes, this is very intentional.  

```
"""
""
"""
```

is the raw string way of saying "two quotes" (which is what is desired here).

**Comment by ToddGrun** [comment]
> is the raw string way of saying "two quotes" (which is what is desired here).

I wasn't questioning the correctness, just whether it's an improvement. I feel like the raw strings are definitely nicer in the multiline case, but it's a bit more questionable to me for the single line case.

**Comment by CyrusNajmabadi** [comment]
It's definitely nicer for me because it removes escapes I have to interpret :-)

**Review by ToddGrun — APPROVED** [review]
:shipit:

**Pull request merged**
