### PR TITLE
Stop reporting unused usings in submissions

### LINKED ISSUE #4392: Usings shouldn't be dimmed in Interactive
Using statements are dimmed in Interactive and always referred to as "unnecessary." Unused using statements should never be dimmed in Interactive.

### PR DESCRIPTION
**Pull request by amcasey**
Since they can be used in subsequent submissions, they are always
considered to be used.

Fixes #4392

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @cston @ManishJayaswal @KevinH-MS @tmat

**Comment by amcasey** [comment]
@Pilchie seemed to have thoughts as well.

**Comment by cston** [comment]
LGTM

**Comment by Pilchie** [comment]
I think the *ideal* experience would be to continue to report the diagnostics, so that the IDE could continue to provide feedback to users in this case.

However, I get that the fact that usings can become used by later submissions makes that way more difficult to implement than is worth it for it, so :+1: for the simple change.

**Comment by amcasey** [comment]
Test this please

**Pull request merged**
