### PR TITLE
Experimental code coverage collection

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by heejaechang** [comment]
this is nice!. what tool should we use to see the result file?

**Comment by sharwell** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

**Comment by sharwell** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please

**Comment by bruno-garcia** [comment]
Curious why this got closed (as opposed to merge)?

**Pull request closed without merging**
