### PR TITLE
Merge main-vs-deps to release dev17.3

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]

**Comment by sharwell** [comment]
This needs one more change... will locate

**Comment by sharwell** [comment]
I'll just push the fix directly to this branch

**Comment by sharwell** [comment]
OK fixed!

**Comment by allisonchou** [comment]
We plan to delete release/dev17.3 today since we just merged the branch back into main-vs-deps. I think this PR is no longer necessary, closing.

**Pull request closed without merging**
