### PR TITLE
project.json Fixes

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Fix a few things that fell out of our project.json conversion:

2. Update the solution file to match the TestUtilities.FX45 project
3. Copy our NuGet dependencies into our VSIX again.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Reviewers: @Pilchie, @agocke, @tannergooding, @davkean, @tmat

**Comment by Pilchie** [comment]
:+1:

**Comment by agocke** [comment]
I created a PR for the FakeSign change at #5022 because I forgot we also need to update the nuget zip package every time we change nuget packages.

**Comment by agocke** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@agocke: I elided the commit from my branch here.

**Pull request merged**
