### PR TITLE
always save changes to unopened documents

### PR DESCRIPTION
**Pull request by mattwar**
This fixes a bug found when investigating #12531

This is an update to a prior PR #15183, with added integration tests that proves that a change in a single closed document is saved to disk.

This change makes it so InvisibleEditor's created via the vs workspace will always be set to save the document if the document is not open in the editor.

The problem this is fixing is one where an edit is made to just a single closed document. In this case we were failing to call SaveDocuments on the running document table. We generally only called SaveDocuments if there is a global undo transaction in effect, and there is only a global undo transaction if there is more than one document involved. Except closed documents cannot be saved manually by the user as they don't correspond to an open text buffer in the editor.

@dotnet/roslyn-ide please review

### CODE REVIEW

**Comment by mattwar** [comment]
test vsi please

**Comment by mattwar** [comment]
@dotnet-bot retest this please

**Comment by mattwar** [comment]
retest vsi please

**Comment by tannergooding** [comment]
test open-vsi please

**Comment by Pilchie** [comment]
@DustinCampbell - can you take a look at the integration testing code here?

**Pull request merged**
