### PR TITLE
Add support for recursive patterns in `is`

### PR DESCRIPTION
**Pull request by gafter**
- Add support for recursive patterns in `is`.
- Add the discard pattern `_`.
- Add skeletal IOperation support.

### CODE REVIEW

**Comment by gafter** [comment]
@AlekseyTs @agocke You are welcome to review this batch of changes for recursive patterns. I have more changes to queue up after this is integrated (e.g. recursive patterns are now lowered yet, or handled in switch).

**Comment by AlekseyTs** [comment]
@gafter PR are not supposed to be merged without two sign-offs from the compiler team. If you are blocked and cannot wait for review from me or Andy, you should simply find two other people to sign-off.

**Comment by gafter** [comment]
@AlekseyTs That's not my understanding of the way feature branches work.

**Comment by gafter** [comment]
Note that the merge of this PR has been reverted.

**Pull request merged**
