### PR TITLE
Switch to full ngen for Roslyn binaries

### PR DESCRIPTION
**Pull request by genlu**
This reverts commit 55366698b723a70800cf679b84154ca98d69f4ed, the change was originally implemented in #53837 

Fixes: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1362616

Val build: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=5036568&view=results
val insertion: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/341198

### CODE REVIEW

**Comment by genlu** [comment]
The insertion shows reduced jitting across the board and some regression caused by increased image size, which is expected.

**Comment by genlu** [comment]
FYI @allisonchou

**Comment by allisonchou** [comment]
@genlu As someone who's not very familiar with ngen, what implications (if any) will this have on the insertion flow?

**Comment by genlu** [comment]
@allisonchou based on the RPS results in the val insertion, this would reduce jitting but also might cause regression in refset due to increased image size. The regression should be auto-approved for exception though, since it's expected for full ngen

**Review by allisonchou — APPROVED** [review]

**Review by ryzngard — APPROVED** [review]

**Comment by davkean** [comment]
This regressed this counter which should be looked at:

```
BuildInfoVS64.Test - RegressedBeyondThreshold / 0001.BuildInfo / Build_Ngen_InvalidAssemblyCount / Regressed: 4.00 Count (21.05%)
```

**Comment by genlu** [comment]
@davkean That's unrelated. There's a breaking change in LanguageServer.Client ([PR](https://github.com/dotnet/roslyn/pull/55124)), which requires some [additional change](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/339911) in VS repo, which my validation PR doesn't have.

**Pull request merged**
