### PR TITLE
Merging ref assemblies feature into master

### PR DESCRIPTION
**Pull request by jcouv**
**Customer scenario**
Produce reference assemblies.
See feature doc: https://github.com/dotnet/roslyn/blob/features/refout/docs/features/refout.md

**Bugs this fixes:**
Relates to https://github.com/dotnet/roslyn/issues/18612 (test plan) and https://github.com/dotnet/roslyn/issues/17612 (work items)

**Risk**
Low. This has been integrated with Domino, MSBuild and part of Windows build, as validation.

**Performance impact**
The performance hit for generating reference assemblies is small because we re-use most of the work that has already been done, and the reference assemblies themselves are much smaller.
Also, this is pay-per-play (no performance cost unless you choose to emit the ref assembly).

**Known issues**
There is one issue from Windows that I'm investigating, but that I don't think is caused by the compiler.
There are some follow-up issues post-C#-7.1, for further refining the filtering of metadata in ref assemblies.

@gafter FYI

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler This PR will have the entire ref assembly feature, in case you want to take a look. All the individual PRs have already been double-reviewed in the feature branch and the blockers from the test plan addressed.

**Comment by jcouv** [comment]
@dotnet/roslyn-infrastructure FYI, I got a VS integration failure (Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicEditAndContinue.LocalsWindowUpdatesCorrectlyDuringEnC) [details](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4031/)
I'll re-run.

**Comment by jcouv** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please

**Comment by jcouv** [comment]
@MeiChin-Tsai for ask-mode approval. Details up-top. Thanks

**Comment by jcouv** [comment]
Failure on VS integration test: Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigateTo.NavigateTo [details](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4041/)
I'll re-run again.

**Comment by jcouv** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please

**Comment by MeiChin-Tsai** [comment]
approved.

**Comment by jcouv** [comment]
FYI @dotnet/roslyn-compiler @rainersigwald Merging the refout feature branch into master.

**Pull request merged**
