### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160414-150051
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160414-150051 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit64 please.
Build machine went offline during the build.
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6147/

**Comment by AlekseyTs** [comment]
It looks like the test failures are related to https://github.com/dotnet/roslyn/issues/10528. Merging.

**Pull request merged**
