### PR TITLE
Document definite assignment back compat bug

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by gafter** [comment]
@MadsTorgersen Can you confirm whether or not we intend to update the language specification for this case? I seem to remember there being some language change regarding definite assignment ignoring private struct members that we intended would affect some future language version.

**Comment by agocke** [comment]
@gafter What would be the language change here? Something like, "private reference-type fields of structs are always considered definitely assigned if the definition of the struct appears in a different program"?

**Comment by agocke** [comment]
At the very least, I think we should document this for older versions of the compiler.

**Comment by gafter** [comment]
@agocke Yes, I think that is an accurate description of the change, though that's not how it would be described in the specification. Now that I think of it, though, I have a hard time imagining what the specification *would* say. Perhaps something like

> A _struct_type_ variable is considered definitely assigned if each of its instance variables **that is not private or that is declared in the same program** is considered definitely assigned.

The bold type would indicate the new words. I think my wording is a bit awkward, but I think this is what the LDM agreed to, while holding our collective noses.

**Comment by jkotas** [comment]
If you want to make this bug part of the language specification, would it make sense to make the behavior more consistent and omit the `declared in the same program` part?

**Comment by VSadov** [comment]
Note that the bug also observably screws up the life time of the variable. 

You may now see that the variable is alive when you exit/enter blocks or executing loops. Unless it is captured in a lambda, - then it is a new variable every time. And in a case of local function it will depend on optimizations and whether it results in a class or struct capture. It may also differ between release and debug.
Would this be explained in the spec as well?

I also wonder how async capture analysis deals with this?  
Do we just conservatively capture all the "empty" structs or the opposite - may end up randomly losing their values when await actually awaits?

**Comment by VSadov** [comment]
I really wish this was just fixed and tied to the language version. 

Legacy codebases do not need to change langversion and can still have the old behavior.

Irrational behavior like this is hard to maintain and generalizing its interaction with new features is even harder to do.

**Comment by agocke** [comment]
I don't think addressing this through language version is the right solution. 

First, it means we could never warn about this on older code that targets C# 7 or earlier. I think this is also why we shouldn't put this on the language spec. If we fixed this in warning waves then we could warn for any language version. 

Second, since we automatically upgrade projects to the latest major language on major VS upgrades this would functionally break the back compat guarantee that is the reason for preserving the behavior in the first place. To accommodate the back compat requirement  we would have to remove auto upgrade, which is unacceptable.

**Comment by nguerrera** [comment]
I agree with @agocke though I hope we can turn "warning waves" into "diagnostic waves" and make this an error.

**Comment by jnm2** [comment]
Wow. And this isn't something that you'd be willing to make `<features>Strict</feature>` solve?

**Comment by gafter** [comment]
@jnm2 "Features" are not intended to be a supported part of the product.

**Comment by nguerrera** [comment]
Skimming https://github.com/dotnet/roslyn/commit/31ddbfa1a14640c86939e066d9549ac014cf845f, it looks like `strict` does handle this correctly.

**Pull request merged**
