### PR TITLE
Disabling specific unit tests that are failing in standalone runs

### PR DESCRIPTION
**Pull request by mattscheffer**
See issues #5550, #5555, #5557.

### CODE REVIEW

**Comment by mattscheffer** [comment]
@ManishJayaswal

**Comment by ManishJayaswal** [comment]
Disabling them here will also stop them from running in CI runs where these are supposedly passing. I think someone needs to investigate these failures in the stand alone run first before we disable these tests else we would be losing coverage in our runs.
@jaredpar @Pilchie can you have someone take a look at these failures? @mattscheffer  can provide machines if needed for investigation.
@mattscheffer  is there a way to disable these tests only in standalone runs?

**Comment by mattscheffer** [comment]
Ah, I thought this was what you preferred based on our earlier conversation. 

No, I can't disable these individual tests only in the standalone tests. However, I can disable the entire test dll from being ran. This would of course give me loss of coverage on the rest of the passing tests in each test dll. I can't recall the other tests failing outside of versioning issues, so we might be ok there.

**Comment by jaredpar** [comment]
:-1: 

We should not be doing this.  These tests provide valuable coverage to the compiler server.  If there is an issue with the standalone runs (what are they) then we should be changing the tests to disable in that environment only, not reducing our test coverage overall.

**Comment by mattscheffer** [comment]
Correction, there was a method to disable individual tests in the standalone runs. This has been performed. Closing pr.

**Pull request closed without merging**
