### PR TITLE
Merge "generic attributes" to main

### PR DESCRIPTION
**Pull request by RikkiGibson**
Related to #36285

We're shipping this feature in .NET 6 under the "preview" LangVersion.

We don't have an EnC test here but honestly I would like if I could wait for #54891 to be merged before writing one :). Will do this before "promoting" this feature out of preview. When I tried to verify manually I got a rude edit message. I think I was on a pretty recent .NET 6, but not certain now, so am also curious how I can determine which runtimes support editing custom attributes during EnC.

### CODE REVIEW

**Review by jaredpar — APPROVED** [review]

**Comment by RikkiGibson** [comment]
I've been advised to ignore the lsp-CI failure.

**Comment by RikkiGibson** [comment]
We did it @AviAvni 😄. This will be available in the "preview" LangVersion in dev17-preview4 and hopefully will release "stable" in .NET 7 / C# 11. Thanks for your help with this feature.

**Comment by AviAvni** [comment]
@RikkiGibson Thank you very much

**Comment by davidwengier** [comment]
> I would like if I could wait for #54891 to be merged before writing one

The good news is, this is merged!
The bad news is, this is merged.

**Comment by RikkiGibson** [comment]
🙈

**Pull request merged**
