### PR TITLE
Revert "Syntactically classify buffers without a workspace"

### PR DESCRIPTION
**Pull request by dpoeschl**
This reverts commit c25f25282c5609fac7e2525f0d4ab460fd93d44b.

### CODE REVIEW

**Comment by dpoeschl** [comment]
This will reactivate #873 for ```1.2```

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by dpoeschl** [comment]
retest prtest/win/dbg/unit64 please

**Comment by dpoeschl** [comment]
Optimistically merging, but we'll need to verify http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/997/ passed. /cc: @tannergooding

**Comment by dpoeschl** [comment]
All Jenkins tests passed.

**Comment by Pilchie** [comment]
late, but :+1: from me too.

**Pull request merged**
