### PR TITLE
Display a cancellable wait dialog while computing suppressions fix. C…

### PR DESCRIPTION
**Pull request by mavasani**
…urrently we only do so for computing diagnostics and applying the fix, but even computing the new solution with suppression fix (which involves simplify and formatting) can be time consuming for big solutions.

### CODE REVIEW

**Comment by mavasani** [comment]
@heejaechang can you please take a look?

**Comment by CyrusNajmabadi** [comment]
@mavasani can you tag me for these sorts of changes as well?  Thanks!

**Comment by mavasani** [comment]
Sure. Note that there are no functional changes here - just moving some more code inside an existing wait dialog.

**Comment by heejaechang** [comment]
:+1:

**Pull request merged**
