### PR TITLE
Pass CancellationToken at the Analyzers layer

### PR DESCRIPTION
**Pull request by jmarolf**
Redo of https://github.com/dotnet/roslyn/pull/52247

This cleans up passing cancellation tokens in the analyzers layer

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Why 
https://github.com/dotnet/roslyn/blob/50fad85efc2eea0e0bcd2eacab24aeb2bb783002/src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs#L95 wasn't flagged?

GetSymbolInfo can be passed a cancellation token. A cancellation token is even defined in 

https://github.com/dotnet/roslyn/blob/50fad85efc2eea0e0bcd2eacab24aeb2bb783002/src/Analyzers/CSharp/Analyzers/UsePatternMatching/CSharpAsAndNullCheckDiagnosticAnalyzer.cs#L62

**Review by Youssef1313 — COMMENTED** [review]
Also the following can be passed a cancellation token (it's less straightforward to do since there is no cancellation token in scope - the private method will need to have a cancellation token parameter)

https://github.com/dotnet/roslyn/blob/bd010fb0e180dad1ce31066654159416dfab42e1/src/Analyzers/CSharp/CodeFixes/InlineDeclaration/CSharpInlineDeclarationCodeFixProvider.cs#L357

https://github.com/dotnet/roslyn/blob/bd010fb0e180dad1ce31066654159416dfab42e1/src/Analyzers/CSharp/CodeFixes/ConvertTypeOfToNameOf/CSharpConvertTypeOfToNameOfCodeFixProvider.cs#L31

There should be a few more similar cases.

**Comment by jmarolf** [comment]
@Youssef1313 I believe the analyzer is just looking for cancelation tokens passed in as parameters. We should investigate improving this over at dotnet/roslyn-analyzers

**Comment by jmarolf** [comment]
> Also the following can be passed a cancellation token (it's less straightforward to do since there is no cancellation token in scope - the private method will need to have a cancellation token parameter)

It is ok to not pass a cancellation token if the user cannot cancel the underlying operation (no dialog to click on etc).  In these cases (codefixes) they can be so we should try and pass these down.

**Review by genlu — APPROVED** [review]

**Review by CyrusNajmabadi — APPROVED** [review]

**Pull request merged**
