### PR TITLE
Cross platform scripting projects

### PR DESCRIPTION
**Pull request by esdrubal**
Mono System.Reflection.Emit classes now implement the required methods for Roslyn Scripting projects to work. https://github.com/mono/mono/pull/1909

This pull request adds Scripting projects to CrossPlatform.sln, fixes or disables tests that were not working on mono, and implements a Mono friendly GlobalAssemblyCache.

Two tests are currently not passing with mono master:
Roslyn.Services.UnitTests.MetadataShadowCopyProviderTests.Modules [#33007](https://bugzilla.xamarin.com/show_bug.cgi?id=33007)
Microsoft.CodeAnalysis.Scripting.CSharp.UnitTests.InteractiveSessionTests.AssemblyResolution [#32966](https://bugzilla.xamarin.com/show_bug.cgi?id=32966)

### CODE REVIEW

**Comment by tmat** [comment]
@esdrubal The bigger problem with Mono right now is that it doesn't support 4.6 reference assemblies: "TargetFrameworkVersion 'v4.6' not supported by this toolset"

Scripting assemblies require FX 4.6.

We are moving it to portable (DNX-style), so you might need to wait for that to happen.

**Comment by esdrubal** [comment]
@tmat, I understand that it may take a while before cibuild.sh is using a Mono version that handles v4.6, and has the required SRE changes available for Scripting.
So I broke this pull request in two others:
https://github.com/dotnet/roslyn/pull/4556 Fixes for scripting tests in Mono
https://github.com/dotnet/roslyn/pull/4557 Adds a Mono compatible logic for GAC.
Neither do changes to the CI.

**Comment by davkean** [comment]
Can we have someone from @dotnet/interactive look at this, and decide if this an approach we want to take?

**Comment by tmat** [comment]
Some of these changes are definitely useful and we'll cherrypick them for 1.2. 
I'm not sure about the GAC yet. The design of the GacResolver is still in flux. We want to make the resolvers public in next release, so that the host can pick and compose resolvers as needed. So perhaps it would be better to have MonoGacResolver as a separate type. 

Let's keep this PR open for now.

**Comment by tmat** [comment]
As stated above this PR has been superseded by #4556 and #4557. Closing.

**Pull request closed without merging**
