### PR TITLE
Switch to Dev15 debugger references

### PR DESCRIPTION
**Pull request by amcasey**
FYI @dotnet/roslyn-interactive @ericfe-ms @pnelsonmsft

### CODE REVIEW

**Comment by amcasey** [comment]
@KevinH-MS Is this going to blow up on any machine that has v14 in the GAC?

**Comment by amcasey** [comment]
Confirmed, before this change `Microsoft.VisualStudio.Debugger.Metadata` was picked up from the GAC.  Now it is picked up from the binaries directory and the call to `Microsoft.VisualStudio.Debugger.Metadata.Type..ctor` from `Microsoft.CodeAnalysis.ExpressionEvaluator.TypeImpl` throws a `System.Security.VerificationException`.

**Comment by amcasey** [comment]
I'm going to try working around this problem by GAC'ing the new binary.

**Comment by amcasey** [comment]
GAC'ing the Dev15 version seems to work.  I guess we'll have to do that on all the Jenkins machines?

**Comment by jasonmalinowski** [comment]
Is the intent for this to be installable atop Dev14? Any reason we can't include the binary in the EE VSIX rather than GACing? I think we're hoping to not have to mangle Jenkins machines going forward.

**Comment by amcasey** [comment]
The goal is to be able to run the unit tests on both dev14 and dev15.  GAC'ing would probably solve the problem on both, but is undesirable on dev14 and, arguably, incorrect on dev15.

**Comment by jaredpar** [comment]
Does this prevent us from F5'ing into Dev14?

**Comment by amcasey** [comment]
@jaredpar AFAIK, the copy in the output directory only affects the unit tests.

**Comment by heejaechang** [comment]
@amcasey are those failures specific to your PR?

**Comment by amcasey** [comment]
@heejaechang, yes, they're expected.  We're working with the debugger team to figure out a plan.

**Comment by KevinH-MS** [comment]
Per our previous discussions, I think it's fine to just use binding redirect until we have build machines with Dev15.  If there's nothing else to do, please feel free to close.

**Comment by KevinH-MS** [comment]
Woops, I got confused and thought this was an Issue, not a PR (not sure how it was showing up in my query).  In any case, I'm going to close this for now (since it's growing stale, and I don't think we're going to do this now).

**Pull request closed without merging**
