### PR TITLE
Temporarily change LSP FAR back to not using streaming

### PR DESCRIPTION
**Pull request by allisonchou**
This change is a temporary patch for 16.7p2 and should be reverted once https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1094786/ is fixed.

### CODE REVIEW

**Comment by allisonchou** [comment]
@dibarbet Hmmm I think we could, but then I believe we would have to pull out all the code that generates the VSReferenceItems in FindUsagesLSPContext back into the FindAllReferencesHandler, so it seems like it would be a similar amount of work either way.

**Comment by CyrusNajmabadi** [comment]
> Mainly looks fine - lets make sure to keep an eye on the underlying issue and switch back as soon as it's fixed.

Do we have an issue tracking that?  Otehrwise, we'll likely never do it :)

**Comment by allisonchou** [comment]
@CyrusNajmabadi Here's a link to the issue that I'm currently following: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1094786/
Should we be creating a matching issue on the Roslyn side as well?

**Comment by CyrusNajmabadi** [comment]
As long as there's an issue that will land on a *roslyn* developer's plate when the underlying issue if fixed, then we're fine.  However, if the issue just gets closed out, or assigned to someone else, then we won't ever do our side (unless someone remembers).  And depending on people remembering stuff almsot never works out.  Best and safest mechanism is to have a true tracking issue on our side assigned to someone (potentially you), so that we know about this and never lose/forget it.

**Comment by JoeRobich** [comment]
The failing integration test is known failing and has been skipped in master. To avoid restarting all the CI, I will merge the PR.

**Pull request merged**
