### PR TITLE
Disable AppDomain isolation in unit tests

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure

**Comment by tannergooding** [comment]
LGTM

**Comment by davkean** [comment]
There's ~16000 tests failures here.

**Comment by jaredpar** [comment]
@davkean yikes. Looks like we have a much larger dependency on AppDomain isolation for our unit tests than I anticipated, even down in the compiler layer.  Need to start whittling away at that as we move to CoreCLR based xunit runner since there will be no AppDomains.  

For now I'm going to disable AppDomains where the tests can pass without modification.  That will at least reduce our exposure to #6358.  We can use that bug to continue whittling down our dependency here.

**Comment by tannergooding** [comment]
@davkean, @jaredpar. I looked at a random selection of tests and they all seem to be assembly load and MEF errors.

Could this be some issue with us fake signing the assemblies?

**Comment by davkean** [comment]
I don't think fake signing should affect this - but can you point me to one of the errors?

**Comment by jaredpar** [comment]
@davkean the assembly load issues is actually a deep seeded issue with AppDomains and how they are constructed in xunit.  I've narrowed down the issue to a point I understand the circumstances under which the problem reproduces.  But I have no idea why those circumstances should produce that problem :frowning: 

We should sync up on Monday about this.  I suspect you'll understand the root issue here.

**Comment by jaredpar** [comment]
Note: I'm going to move this PR to master as getting it correct involves some code changes and we're locked down in stabilization.  Good news though is I figured out why many of the compiler suites were failing and have a fix for that.

**Pull request closed without merging**
