### PR TITLE
Fixed mistake in RDT handler

### PR DESCRIPTION
**Pull request by mgoertz-msft**
@tvsonar Thanks for pointing this out.

@jasonmalinowski, @Pilchie, @CyrusNajmabadi  Please merge when ready.

Thank you.

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by Pilchie** [comment]
Anyone else on @dotnet/roslyn-ide want to take a look?

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by mgoertz-msft** [comment]
Thank you!

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
