### PR TITLE
Do not offer to spell-check 'var' to anything else.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/15733

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jmarolf

**Comment by CyrusNajmabadi** [comment]
Also, simplified a lot of test code, removing redundancy.

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit64_prtest please

**Comment by jmarolf** [comment]
:+1:

**Pull request merged**
