### PR TITLE
Remove DiaSymReader source, it's been moved to dotnet/symreader repo

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@davkean FYI
@dotnet/roslyn-infrastructure

**Comment by tmat** [comment]
Prerequisite: https://github.com/dotnet/roslyn-internal/pull/880

**Comment by jasonmalinowski** [comment]
Also FYI to @dpoeschl and @tannergooding since this will also require updating our Microbuild definitions. (@tmat not to worry, that's their problem not yours to fix.)

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/6145/
// Retest reason:

**Comment by tmat** [comment]
@jasonmalinowski I'll handle updating the definitions - have them actually open on my screen now.

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/6155/
// Retest reason:

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/628/
// Retest reason:

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/644/
// Retest reason:

**Comment by tmat** [comment]
retest vsi please

**Comment by balajikris** [comment]
@dotnet-bot retest vsi please
// reason : previous builds were caught in the middle of a cross cutting change.

**Comment by tmat** [comment]
@balajikris Still broken.

**Comment by balajikris** [comment]
When I checked an hour ago, the queue was alright, so it has to be something with this particular change. Can you look at the logs and see if they reveal the source of the failure.?

**Comment by balajikris** [comment]
I don't see any test failure, except the build warnings. Have to look if we treat earnings as errors and if that's the reason.

**Comment by tmat** [comment]
@balajikris The warnings are not new. There have been there before my change.

**Comment by tmat** [comment]
@balajikris Where do I find logs?

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
test vsi

**Comment by tmat** [comment]
retest vsi please

**Pull request merged**
