### PR TITLE
Remove invocation of FlushPayLoad method from code instrumentation

### PR DESCRIPTION
**Pull request by genlu**
It's analysis driver's responsibility to invoke this method appropriately, compiler only needs to instrument code. This change can't be merged until the driver side change is in place.

FYI @JohnHamby @AlekseyTs @jcouv @dotnet/testimpact @dotnet/roslyn-compiler
This is ported from #10458

### CODE REVIEW

**Comment by JohnHamby** [comment]
I sign off.

**Comment by jcouv** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by tannergooding** [comment]
@genlu, let me know when this gets merged so I can kick off a signed-build.

**Pull request merged**
