### PR TITLE
Merge 'future' into 'tuples'

### PR DESCRIPTION
**Pull request by AlekseyTs**
@VSadov, @jcouv FYI

### CODE REVIEW

**Comment by AlekseyTs** [comment]
test prtest/lin/dbg/unit32 please

**Comment by VSadov** [comment]
I think this should be a rebase, not a merge.

**Comment by VSadov** [comment]
All previous integrations to tuples were rebases to have cleaner commit history.

**Comment by AlekseyTs** [comment]
@VSadov I'll let you do it then

**Comment by AlekseyTs** [comment]
BTW, I think you are making things more complex than it is needed. Rebase rewrites history and by doing this, you are likely negatively affecting everyone working in the branch because they might not be able to do simple merge after you do the rebase.

**Comment by VSadov** [comment]
Yeah. We figured that by now. :-)
In a branch with more people contributing it might not be possible.

**Comment by AlekseyTs** [comment]
Test prtest/lin/dbg/unit32 please

**Pull request closed without merging**
