### PR TITLE
Avoid toggle checkbox when clicked on an option's description.

### LINKED ISSUE #18614: Can't use mouse to select formatting option lines
"Tools, Options, Text Editor, C#, Code Style, Formatting, New Lines.

It's currently impossible to just select one of the items in the list with mouse click - it registers as a toggle for the checkbox, no matter where on the line you click. Generally I'm lazy so that's good, but it's not good when I want to select a different item/line.

Please stop toggling yet unselected lines. Only when selected should the toggling kick in."

### PR DESCRIPTION
**Pull request by diryboy**
**Customer scenario**

"Tools, Options, Text Editor, C#, Code Style, Formatting, New Lines.
It's currently impossible to just select one of the items in the list with mouse click - it registers as a toggle for the checkbox, no matter where on the line you click.

**Bugs this fixes:**

Fixes #18614

**Workarounds, if any**

Click on places without description text

**Risk**

Low

**Performance impact**

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

**Is this a regression from a previous update?**

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

(E.g. customer reported it vs. ad hoc testing)

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide  for reviews.

**Comment by dpoeschl** [comment]
Also the focus indication border won't be right. I'm not sure of the right way to fix this from an accessibility standpoint. Looking into it.

**Comment by diryboy** [comment]
Good point, from my observation currently the content in ListItem does not have focus when you use keyboard Tab, the ListItem itself does. But when you press Spacebar the CheckBox gets toggled. This behavior is the same before and after this pr.

Are CheckBox allowed to set some kind of accessibility attribute so one can read that only from screen readers or something? If so I'm happy to add that.

**Comment by diryboy** [comment]
Will `AutomationProperties.Name` do?

**Comment by diryboy** [comment]
@dpoeschl I saw your #19638 added `AutomationProperties.LabeledBy`, so I made the same change here. If more changes needed, please let me know.

**Comment by MattGertz** [comment]
Mondo escrow triage:  keeping this as it touches on accessibility.

**Comment by jinujoseph** [comment]
This needs validation , @chborl  can your help with this

**Comment by chborl** [comment]
Verified, accessibility is working as expected

**Comment by dpoeschl** [comment]
Whoo, fantastic. Thanks @diryboy! @jinujoseph for merge approval

**Comment by jinujoseph** [comment]
approved to merge for 15.8.Preview4

**Comment by Neme12** [comment]
> It's currently impossible to just select one of the items in the list with mouse click - it registers as a toggle for the checkbox, no matter where on the line you click.

I'm sorry but I'm a little confused. When I try this in 15.7 or 15.8p2, it's definitely possible and easy to select the item without toggling just by clicking outside of the text.

**Comment by Neme12** [comment]
Am I misunderstanding something? Or is it possible this has been fixed since this PR was created?

**Comment by dpoeschl** [comment]
You're understanding that quote correctly. I see what you see -- clicking to the right of the text or left of the checkmark works in current VS. I'm not sure if that has changed since the original bug was filed.

But regardless, I do think that _not_ toggling when the use clicks the text is the right call here. In know in many contexts you want the checkbox text to toggle the checkbox, but it doesn't make sense in the context of a listview where you have to select the listviewitem to cause a side effect like the preview updating. At least that's my thinking.

**Comment by Neme12** [comment]
Thanks, maybe the issue was just poorly described or investigated originally.

I *think* I would prefer if clicking the label to toggled the checkbox since it's so small and harder to hit, but on the other hand it's true that I've hit it accidentally a few times, so I definitely understand the reasoning here.

**Pull request merged**
