### PR TITLE
[Ask Mode] initialize to max value so that there is no conflict when finding old…

### PR DESCRIPTION
**Pull request by heejaechang**
…est cache.

this fixes Watson crash due to IndexOutOfIndex exception.

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=179939

since it is watson crash, I dont have exact repro or scenarios where this happens, but this fix should make such situation can't ever happen.

### CODE REVIEW

**Comment by heejaechang** [comment]
this is port of https://github.com/dotnet/roslyn/pull/9343

**Comment by srivatsn** [comment]
:+1:

**Comment by heejaechang** [comment]
@MattGertz can I get approval for update 2?

**Comment by MattGertz** [comment]
Approved.  (In future, just tag me, no need to assign.)

**Pull request merged**
