### PR TITLE
Unwrap the cause (inner exception) of operation canceled exceptions when reporting faults

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes [AB#1212299](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1212299)

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

**Review by sharwell — CHANGES_REQUESTED** [review]
OperationCanceledException can occur on both normal cancellation paths and error paths. Currently we only report them on error paths, where it's not required to omit them.

**Comment by tmat** [comment]
Won't we start reporting ConnectionLostExceptions (that are wrapped in OperationCanceledException) if this is merged? These are expected exceptions that occur on shutdown and they may get wrapped in OperationCanceledException and get reported by if cancellation token is not signaled when ReportAndPropagateUnlessCanceled is called with cancellation token.

**Comment by sharwell** [comment]
This is assuming all of the cancellation exceptions getting reported are wrapping a ConnectionLostException. Also, it'd be fine to skip reporting for ConnectionLostException when the current process is the ServiceHub process (ConnectionLostException is a more targeted exclusion than OperationCanceledException).

**Comment by tmat** [comment]
The motivation for adding `OperationCanceledNotMatchingCancellationTokenException` that are wrapping ConnectionLostException or ObjectDisposedException in https://github.com/dotnet/roslyn/pull/61792 is to distinguish OCEs that should not be reported in NFEs from regular OCEs. 

Are there any other cases when we are wrapping exceptions to OCE?

**Comment by ryzngard** [comment]
> The motivation for adding `OperationCanceledNotMatchingCancellationTokenException` that is wrapping ConnectionLostException or ObjectDisposedException in #61792 is to distinguish OCEs that should not be reported in NFEs from regular OCEs.
> 
> Are there any other cases when we are wrapping exceptions to OCE?

If we want to avoid reporting specific exceptions as faults we should filter there instead of `FatalError`. Filtering at that level would also result in it being removed from ETW traces and other logs right? 

The goal of this is specifically around fault reporting. OCE is resulting in millions of events of unactionable data and bucketed in ways we can't root cause. This will, at the very least, give us a clearer picture of root causing.

**Comment by tmat** [comment]
> OCE is resulting in millions of events of unactionable data

Yes, some of these (maybe most?) because we are wrapping ConnectionLostException in OCE today and then reporting it form `FatalError.ReportUnlessCancelled(Exception, CancellationToken)` because the cancellation token is not signaled in this case.

**Comment by tmat** [comment]
Once https://github.com/dotnet/roslyn/pull/61792 is merged I think we shouldn't be seeing any OCE wrapping another exception being reported via NFE.

**Comment by ryzngard** [comment]
> Once #61792 is merged I think we shouldn't be seeing any OCE wrapping another exception being reported via NFE.

I think we should still take this change though. Having the inner exception unwrapped for OCE is more useful than ever reporting OCE for faults

**Comment by ryzngard** [comment]
> Maybe, but there are no other cases where we wrap an exception to OCE in Roslyn.

yet :)

**Pull request merged**
