### PR TITLE
Enable Completion filtering and highlighting by default

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-ide, @CyrusNajmabadi @KevinH-MS.

**Comment by Pilchie** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
Terrifying

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
:+1:. Note there's some duplicate options further down in the file. I've already got that cleaned up in my options PR.

**Comment by Pilchie** [comment]
@jasonmalinowski interesting - those don't seem to be used though?  I did verify that this change worked...

**Comment by jasonmalinowski** [comment]
Yes, I think it was a mis-merge.

**Comment by Pilchie** [comment]
Got it - I'll continue to let you clean that up then.

**Comment by Pilchie** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/285/
// Retest reason: Hit #11429

**Pull request merged**
