### PR TITLE
Update sample documentation for csharp-semantic and csharp-syntax-transf...

### PR DESCRIPTION
**Pull request by mgottein**
...orm for VS 2015 RC

Minor changes are needed to make sure these samples work

### CODE REVIEW

**Comment by gafter** [comment]
@AnthonyDGreen Can you please review these changes to the samples/documentation?

Should this documentation be migrated to markdown, or do we have some other recommendation for our open-source partners?

**Comment by gafter** [comment]
@AnthonyDGreen Ping.

**Comment by AnthonyDGreen** [comment]
I'll be migrating these to the wiki today. I don't think these docs need to version with the code because the API is stable enough and some of the docs include images.

**Comment by ManishJayaswal** [comment]
@AnthonyDGreen ping

**Comment by AnthonyDGreen** [comment]
Hey @mgottein,

Your changes have been ported to the wiki along with another doc change. You can find the updated walkthroughs here:

https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis
https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Semantic-Analysis
https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Transformation

Good job updating the transform walkthrough to use the new "using static" feature in C# 6. This cleans up the code a lot, shows of a new feature, and makes the C# and VB walkthroughs more consistent (Win/Win/Win). I'm closing this PR as now that we have these docs in markdown form we'll be dropping the binary docx and pdf files from the repo.

Sorry for the extreme delay and thanks again!

**Pull request closed without merging**
