### PR TITLE
Expand persister deserialization to also take into account string and accessibility modifiers

### PR DESCRIPTION
**Pull request by Therzok**
CodeStyleOption supports more than just bool and enums, so look into expanding this in the roaming profile persister.

It can be seen here:
https://github.com/dotnet/roslyn/blob/d6f483e56b7089ec08b0af2edc0b9aeda498bfe3/src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs#L151-L152
https://github.com/dotnet/roslyn/blob/d6f483e56b7089ec08b0af2edc0b9aeda498bfe3/src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs#L76-L79
https://github.com/dotnet/roslyn/blob/d6f483e56b7089ec08b0af2edc0b9aeda498bfe3/src/Workspaces/Core/Portable/CodeStyle/CodeStyleOption.cs#L56-L59

This was discovered during porting option persisting to VSMac. We use a more flexible approach, but with reflection, due to the nature of how the serialization code is modeled:
https://github.com/mono/monodevelop/blob/bdc236c2faa86ecdd88d7f36c6294b028a92477e/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.Properties.cs#L109-L129

## Side note 2
It also seems you're not doing anything in case the types don't match, either report that or clear the stored setting:

- https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/Core/Def/Implementation/Options/RoamingVisualStudioProfileOptionPersister.cs#L176

## Side note:
I think the current CodeStyleOption and NamingPreferences (de)serializers can be improved a bit, but for now, this patch works.

3 things at hand:
* If the approach is kept to whitelist specific variants of CodeStyleOption, a test should be added to ensure all possible `T`s are handled (maybe just run through all the options that go in the persister

* I think the approach is not scalable, since anyone can provide their own T (i.e. enum) for `CodeStyleOption<T>`

* Only the persister works with FromXElement.

So, there could be some better way to model this. Can we make `FromXElement` just return `ICodeStyleOption` and use reflection to get the required T and construct the `CodeStyleOption<T>`? That way, every other possible type for T (i.e. custom enum) can be handled, rather than whitelisting on a case-by-case basis.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

Some options might not get persisted even if surfaced int he UI.

### Bugs this fixes

N/A

### Workarounds, if any

None, really.

### Risk

Someone can modify the user preference in the options UI and not see it persisted.

### Performance impact

Don't think there's any

### Is this a regression from a previous update?

Don't think so.

### Root cause analysis

See side-note.

### How was the bug found?

Porting over option persister in VSMac.

### Test documentation updated?

None
</details>

### CODE REVIEW

**Comment by Therzok** [comment]
Possible values found via:
```
➜  roslyn git:(sqlite-blob) ag --nofilename -o "CodeStyleOption<.*?>" | sort | uniq -c
  45
  14 CodeStyleOption<AccessibilityModifiersRequired>
  44 CodeStyleOption<ExpressionBodyPreference>
  33 CodeStyleOption<ParenthesesPreference>
   1 CodeStyleOption<SomeEnumType>
  62 CodeStyleOption<T>
 212 CodeStyleOption<bool>
  14 CodeStyleOption<string>
```

Then looking if any defines a roaming profile persister

**Comment by Therzok** [comment]
Can I get a buddy on this?

**Comment by KirillOsenkov** [comment]
@heejaechang @jinujoseph

**Comment by heejaechang** [comment]
@dpoeschl did code style options. @jasonmalinowski did option persister.

**Comment by jasonmalinowski** [comment]
@jinujoseph Delegated M2 approval will be needed.

@Therzok If you want to give a crack at fixing this better (not special casing), I'd be for that. It's funny that we can serialize all of them in one way but not deserialize them. :-/

**Comment by Therzok** [comment]
I can. So, 2 tasks to improve this PR:
1. Log a non-fatal error when deserialization fails (and clear value? Not sure)
2. Make the deserialization code work on any type.

**Comment by jinujoseph** [comment]
Will wait for #2 to be addressed.

**Comment by Neme12** [comment]
Note: I would recommend pulling latest master branch before you start working on the additional changes so that you don't have conflicts with my changes to RoamingVisualStudioProfileOptionPersister in #26165

**Comment by Therzok** [comment]
Rebased and modified the code.

So, there were a few choices at hand, each with its drawbacks, and this seems to be the simplest and best way to handle it, so a few comments below:

1. `RoamingVisualStudioProfileOptionPersister` has no generically typed information, so we are forced to have a reflection-based way to create a new object of the type of the option if we want to support all options - manual checks seem to be the only way to avoid using reflection.

2. CodeStyleOption is public API, so it's not really possible to change. `ToXElement`/`FromXElement` are also public, as opposed to `NamingStylePreferences` counterparts which are internal.

3. Even if there was a completely generic way to do it based on the `T:new()` constraint, it'll still be reflection based via activator.

4. Not sure if the gains of a compiled lambda outweigh the costs, since each option is fetched only once (some might be reused more).

5. Moving the serialization/deserialization code out of the persister into a centralized place does not fix the general case enum issue, since some still can be missed.

**Comment by jasonmalinowski** [comment]
@dpoeschl want to take a quick look at this as well?

**Comment by jasonmalinowski** [comment]
@jinujoseph Second task is done, so this would be ready for delegated M2 approval.

**Comment by jinujoseph** [comment]
test windows_debug_spanish_unit32_prtest

**Comment by jinujoseph** [comment]
test windows_release_vs-integration_prtest

**Pull request merged**
