### PR TITLE
Dev14RTM: Don't try to get IVsLanguageBlocks in a language that doesn't support SyntaxTrees.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Fixed null-ref when VS calls into the LS for the IVsLanguageBlock API.  Roslyn provided a default implementation that works for VB and C#, but which null-refs for TypeScript.  

The fix is to gracefully bail out when this API is called in TypeScript scenarios.

**Comment by pharring** [comment]
:+1: 
Do we have any tests that could be augmented to cover this?

**Comment by KevinH-MS** [comment]
LGTM :shipit:

**Comment by MattGertz** [comment]
MoreInfo 6/4 by ML Shiproom.  @CyrusNajmabadi Please add customer scenario info, root cause, and tests updated.

**Comment by CyrusNajmabadi** [comment]
@MattGertz 

Customer Scenario: The user opens Find-In-Files and then selects the following option:

image

(instead of saying "search in solution/project/file/etc."). 

Root cause: When the user selects "Current Block" VS calls into the language package to determine what the span of the current block should be.  Roslyn provides a default implementation for this functionality, but that default implementation assumes it will run on a C#/VB file, and dies on a TypeScript file.  This is due to the default implementation trying to access things like the SyntaxTree for a Document (something which TypeScript does not provide).

The simplest fix is to just have the code immediately bail out on Documents that don't have SyntaxTrees.  VB and C# will continue to work as before.  And TypeScript simply will not support this feature (for Dev14 at least).

Tests Updated:  None.  This is a scenario tightly bound to the VS IDE and i could find no good way to try to author a test for this case.   I did manually test that things continued to work properly for C#/VB and TypeScript with the fix in place.

**Comment by CyrusNajmabadi** [comment]
@pharring re. tests.  I could not find any suitable way to write a test for this.  We would need automation to drive the Find-in-files dialog and pick that specific option.  I could not find a way to do that.  So i went with smoke-testing instead.

**Comment by Pilchie** [comment]
This is in a static class specifically to make it easier to write unit tests against.  Isn't it possible to add a test for a language where `!SupportsSyntaxTree` to the existing tests for the feature?

**Comment by Pilchie** [comment]
Sorry about this ☹

**Comment by pharring** [comment]
FYI, we did not look at this in ML Shiproom today because it wasn't assigned to Matt. Please see Pilchie's comment and see if you can add a unit test. Assign back to Matt when you're ready.

**Comment by CyrusNajmabadi** [comment]
I'm contacting @mattwar to see how possible it is to make a unit test for this special type of workspace.

**Comment by Pilchie** [comment]
I thought you added support back when you fixed the CTP5 highlight references bug.

**Comment by Pilchie** [comment]
Also @kevinh_ms is changing this same code in another PR. Might want to coordinate.

**Comment by CyrusNajmabadi** [comment]
/me smacks head.  You're right!  I totally forgot about that.  Thanks for jogging my memory :)

**Comment by CyrusNajmabadi** [comment]
Ok.  Test added.  Assigning back to matt.

**Comment by KevinH-MS** [comment]
My change will be easy to merge with this.  You don't need to worry about it, but thanks!

**Comment by pharring** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Jenkins, re-test this please.

**Comment by MattGertz** [comment]
Approved 6/8 by ML Shiproom.

**Pull request merged**
