### PR TITLE
Dramatically speed up generation of metadata as source for large types

### PR DESCRIPTION
**Pull request by rchande**
Before this change, showing MAS for a type with 4000 empty methods took about 2
minutes on my machine. With this change, it now takes 2-4 seconds. There were
2 different issues causing the slow generation:

1. When formatting the generated file, the formatting engine needs to find the
distance between every token and the new line (or start of file)  before it.
This calls  TokenStream.GetOriginalColumn, which computes the original column
by walking backwards through its list of tokens counting the width of tokens
and trivia until it finds a newline. Though this n ^ 2 operation takes place
in all invocations of the  formatter, it is normally ameliorated by the fact
that real code has enough newlines that GetOriginalColumn doesn't actually
traverse back to the first token in the file. Generated files have no newlines,
so GetOriginalColumn takes up about half the time of generating a MAS document,
because GetOriginalColumn is called on every token in the file.
To mitigate this, TokenStream computes in one pass the original column
of every token and stores that information in a cache.

2. If instructed to use "auto insertion location", the code generation service
computes the location to insert each member, one at a time. This computation
checks that the type's members are sorted, resulting in n ^ 2 iterations over
the list of members. The fix for this takes Kayle's fix for enum members a
little further:
When instructed not to use "auto insertion location", the code generation
generates declaration syntax for each member without inserting it. It then
sorts that list of declarations once, and bulks adds them (essentially
appending each declaration to the end of the growing type declaration).

I've fixed up some of the "Create*Declaration" methods to match the behavior
of the corresponding "Add*Declaration" methods.

### CODE REVIEW

**Comment by rchande** [comment]
Can you review this @heejaechang @basoundr @pharring?

CC @dpoeschl @jasonmalinowski @DustinCampbell @CyrusNajmabadi @Pilchie

**Comment by rchande** [comment]
Looks like this speeds up generating one type with lots of members, but it appears there's more work to do for a type with hundreds of nested types.

**Comment by heejaechang** [comment]
@rchande how about rather having another cache, you change TriviaData to have a field called Column. and save column info there?

and in GetColumn, rather than always calculating number, it checks whether it already have column info calculated otherwise, moving backward to find one that has the column info and add from there. and when it calculate one, it set the value there.

whenever TriviaData is modified, leave the column as empty again so that it can later re-calculated.

reason being, having another collection has over head for collection itself. and TriviaData is already there and there are one specific spot all these calculation and modification is happening. so shouldn't be hard and calculation now itself can be lazy.

**Comment by rchande** [comment]
@heejaechang As we discussed offline, I augmented the MAS formatting rule for both C# and VB to stop the computation of anchor operations--that seems to have the same speedup as my cache did.

**Comment by pharring** [comment]
Nice: :+1:

**Comment by DustinCampbell** [comment]
indeed

**Comment by Pilchie** [comment]
Wow.  Nice!

**Comment by rchande** [comment]
Windows and Linux tests passed; something went wrong in the Mac queue.

**Pull request merged**
