### PR TITLE
Produce error on extension methods in language versions earlier than C# 3

### PR DESCRIPTION
**Pull request by OmarTawfik**
/cc @dotnet/roslyn-compiler @CyrusNajmabadi

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compat-council for guidance

**Comment by OmarTawfik** [comment]
@jaredpar that error is reported in both native and Dev15. No compatibility breaking concerns here.

**Comment by jaredpar** [comment]
@OmarTawfik gotcha.  Thanks for the clarification.

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
