### PR TITLE
Support showing diagnostics on additional files.

### PR DESCRIPTION
**Pull request by heejaechang**
this change is turned off by default. and can be turned on by reg key to dogfood changes.

this only let analyzer author to report such diagnostics but consumer doesnt have any knob to control (including suppressing it) yet.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure a lot of tests are timed out.

**Comment by heejaechang** [comment]
prototype of https://github.com/dotnet/roslyn/issues/6649

**Comment by heejaechang** [comment]
@mavasani @srivatsn @basoundr can you take a look? I probably check this in after update 2.

**Comment by heejaechang** [comment]
existing build time out issue.

**Comment by heejaechang** [comment]
retest prtest/win/dbg/unit64  please

**Comment by heejaechang** [comment]
retest prtest/win/dbg/unit32 please

**Comment by jaredpar** [comment]
We apologize, but we are closing this PR due to code drift. We regret letting this PR go so long without attention, but at this point the code base has changed too much for us to revisit older PRs. Going forward, we will manage PRs better under an SLA currently under draft in issue #26266 – we encourage you to add comments to that draft as you see fit.   Although that SLA is still in draft form, we nevertheless want to move forward with the identification of older PRs to give contributors as much early notice as possible to review and update them.

If you are interested in pursuing this PR, please reset it against the head of master and we will reopen it. Thank you!

**Comment by mavasani** [comment]
@heejaechang I presume reviving this PR will automatically show squiggles in all additional files?

**Comment by heejaechang** [comment]
@mavasani this is really old PR that targets V1 engine not V2.

also, this just makes sure engine process addition files but no presentation work is in.

**Pull request closed without merging**
