### PR TITLE
[Stabilization] Don't crash when we hear about very stale diagnostics for our current Document.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes DevDiv bug 157748.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by balajikris** [comment]
LGTM

**Comment by jasonmalinowski** [comment]
Tests? Otherwise :+1:

**Comment by MattGertz** [comment]
Approved.

**Pull request merged**
