### PR TITLE
Fix crash when a multi-line raw literal becomes a skipped token.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/61270

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]
github is being weird, what is this red?
image

**Comment by CyrusNajmabadi** [comment]
> what is this red?

Github's c# parser doesn't understand raw string literals :)

**Comment by JoeRobich** [comment]
> Github's c# parser doesn't understand raw string literals :)

Which really means that our TextMate Grammar doesn't understand raw string literals https://github.com/dotnet/csharp-tmLanguage/issues/243

**Comment by CyrusNajmabadi** [comment]
Oh, i thought they were using tree sitter, not tm.  Thanks!

**Pull request merged**
