### PR TITLE
Publish only the desired package versions (#24843)

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@jaredpar PTAL

**Comment by jaredpar** [comment]
@mmitche looks like this slipped off my radar. Do we still need it?

**Comment by jaredpar** [comment]
@mmitche did you figure out if we needed this or not?

**Comment by mmitche** [comment]
Not for RC but probably for RTM unless you guys shut down early and freeze the version fed to the product.

**Pull request closed without merging**
