### PR TITLE
make msbuildtask not eat errors

### LINKED ISSUE #8186: Build task shouldn't eat exceptions without logging in InitializeHostCompiler
Both the Csc and Vbc build tasks have a method called `InitializeHostCompiler` that does what it sounds like. This method eats all exceptions without logging them. As a part of the investigation that led up to #8177, the build task was throwing an exception, swallowing it, and then failing the design time build with no further explanation why. The catch block in InitializeHostCompiler should log that exception rather than eating it.

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #8186

### CODE REVIEW

**Comment by jaredpar** [comment]
Closed / Open to trigger Jenkins to properly test the change.

**Comment by jaredpar** [comment]
@jasonmalinowski needs to review this.  He has the most context in this area.

**Comment by TyOverby** [comment]
@jasonmalinowski Based on my limited understanding of #8186, removing these checks would ensure that errors are logged. The alternatives are that either `HostCompilerSupportsAllParameters` is not correct, or the logging that should be happening from the command-line compiler isn't happening (or isn't being captured).

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by TyOverby** [comment]
@jaredpar @dotnet/roslyn-compiler One more review please!

**Comment by jaredpar** [comment]
:+1:

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
