### PR TITLE
Make Syntax.xml choices slightly more explicit.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jcouv I did another full pass over the grammar and found two places i missed the first time.  Not a huge deal.  Without this the grammar emit is still fine, but this makes it just a tad bit better.  Specifically:

```diff
using_directive
-  : 'using' 'static'? name_equals? name ';'
+  : 'using' ('static' | name_equals)? name ';'
   ;
```

**Comment by 333fred** [comment]
Triggering another test run. The failed test appears flaky, filed https://github.com/dotnet/roslyn/issues/37834 for IDE followup.

**Comment by CyrusNajmabadi** [comment]
@jcouv @333fred thanks!  Merge when convenient.  :)

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
