### PR TITLE
Do not offer use-object intiializer on code that references the variable being initialized.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/14988

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by genlu** [comment]
Per @tannergooding , the failure of windows_eta_open_prtest is caused by error in Groovy script, he's working on the fix.

**Comment by genlu** [comment]
@dotnet-bot retest windows_eta_open_prtest please

**Comment by SLaks** [comment]
Yes; exactly.

**Pull request merged**
