### PR TITLE
Move namespace name checking out of the parser.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler @jcouv @AlekseyTs

**Comment by CyrusNajmabadi** [comment]
Note: this depends on https://github.com/dotnet/roslyn/pull/16338 and that should be merged first.

**Comment by gafter** [comment]
I'd prefer to review this after #16338 has been merged and this is synced with master.

**Comment by CyrusNajmabadi** [comment]
Will do.  I will ping when that happens.

**Comment by CyrusNajmabadi** [comment]
@gafter 

> I'd prefer to review this after #16338 has been merged and this is synced with master.

This has now happened.

**Comment by CyrusNajmabadi** [comment]
@gafter @jcouv  @dotnet/roslyn-compiler  this is ready for review if there are spare cycles to look at 15.6 changes.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Pull request merged**
