### PR TITLE
Add a public extensibility model for CodeActions to supply images to show in the UI.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/15456

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @mattwar 

This continues the "Tags" model that @mattwar introduced with completion, and extends it to apply to CodeActions.  In order to allow 3rd parties to supply icons, we also expose a new API to map from Tags to ImageMonikers.  We provide a default implementation with our current approach, and we allow others to supply other implementations that we'll MEF import as well.

@mattwar Can you take a look at let me know what you'd like changed?  I'd love feedback on the shape, patterns, naming, etc.

**Comment by mattwar** [comment]
:shipit:

**Comment by CyrusNajmabadi** [comment]
@mattwar So you're totally ok with this as is?  The names and namespaces work for you?  This is a public API change, so i def want to make sure it feels right to you :)

Also tagging @jaredpar as this is an IDE public API change.

**Comment by CyrusNajmabadi** [comment]
Ok, so this is our second public API in EditorFeatures.  @Pilchie Thinks that's fine though.

**Comment by Pilchie** [comment]
👍

**Pull request merged**
