### PR TITLE
Preserve trivia when simplifier removes unnecessary this / Me keywords.

### LINKED ISSUE #50: Simplifier removes trivia when eliminating 'this.' uses.
Consider the following code:

``` csharp
class C1
{
    int _field;

    void M()
    {
        this. /* comment1 */ _field /* comment 2 */ = 0;
    }
}
```

If the `MemerAccessExpressionSyntax` for the field access is tagged with `Simplifier.Annotation` and the result run through the `Simplifier` the code will be transformed into.

``` csharp
class C1
{
    int _field;

    void M()
    {
        _field /* comment 2 */ = 0;
    }
}
```

Notice that `/* comment 1 */` has been removed.  That seems like a bug.  Removing non-comment trivia seems acceptable here but removing comments is potentially removing valuable documentation during the act of simplification.  At the least it seems like there should be an option to prevent this from happening.

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
Fixes #50

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@srivatsn @tmeschter @jmarolf @mavasani @heejaechang Could you please take a look?

**Comment by tmeschter** [comment]
How general is this fix? That is, does it only apply to situations where we remove `this` and `Me`, or will it preserve trivia in all kids of simplification? For example, does it also apply in these situations:

* Simplifying qualified type names: `System.Exception` -> `Exception`?
* Replacing types with keywords: `Int32` -> `int`?

**Comment by shyamnamboodiripad** [comment]
@tmeschter This fix only addresses simplification of ```MemberAccessExpression``` (e.g. ```this.InstanceMethod()```->```InstanceMethod()```, ```Type.StaticField```-> ```StaticField```) i.e. the case mentioned in #50.

But looks like we have same issue for ``QualifiedNames``` too. Let me try and expand the fix to cover that case too.

**Comment by sharwell** [comment]
This seems like it would benefit from the [`WithoutFormatting`](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/3a2f9796f53e7dcad460c6becc16abb229beb487/StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SpacingExtensions.cs#L95-L120) methods we use in StyleCopAnalyzers.

**Comment by shyamnamboodiripad** [comment]
@tmeschter, I started going down the route of fixing up the ```QualifiedNames``` cases and discovered that there are several cases where we don't preserve trivia today -

- ```System.\* comment *\ Int32``` -> ```int``` (i.e. simplify to predefined type in both member access as well as qualified names)
- ```System. \* comment *\ Int32``` -> ```alias``` (i.e. simplify to alias both in both member access as well as qualified names)
- ```Nullable< \*comment *\ T>``` -> ```T?```
- Preserving trivia when replacing generic names with aliases
- Removing type arguments for generic methods
- Simplifying alias qualified names ```global::System...```

The code generation for many of these cases is similar and so I was able to address them by creating and reusing some helpers. However, the code generation is handled in subtly different ways for some of the cases... In the end, seeing the number of changes I had to make I concluded that we should postpose the larger fix to address all these cases until later. Although this is definitely buggy behavior, I feel this is lower priority than other bugs that need to be addressed + the effort spent on testing all these changes now is probably not worth it.

When we have more time later, we should a. audit all the places that need fixing (in addition to the above list, I am also not sure whether we preserve trivia correctly in other reducers such as extension method simplification, parenthesis simplification etc. some of which can only be invoked via API) and b. test all the changes properly.

I plan to check in the changes in this PR to address the one case mentioned in the above bug. I will log a separate issue to revisit this code to fix up remaining cases above.

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
