### PR TITLE
Handle IRangeCaseClauseOperation in control flow graph

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred, @mavasani, @cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review

**Comment by AlekseyTs** [comment]
This PR also fixes https://github.com/dotnet/roslyn/issues/23818

**Review by 333fred — APPROVED** [review]
:shipit:

**Comment by AlekseyTs** [comment]
@cston, @dotnet/roslyn-compiler Please review, need second review.

**Comment by AlekseyTs** [comment]
@mavasani, @dotnet/analyzer-ioperation Please review

**Review by gafter — APPROVED** [review]
:shipit:

**Review by mavasani — APPROVED** [review]

**Pull request merged**
