### PR TITLE
Gaurd against trying to deserialize bad or ..

### LINKED ISSUE #9418: Crash in SimpleCodeStyleOption.FromXElement
```C#
        public static SimpleCodeStyleOption FromXElement(XElement element)
        {
            var isChecked = bool.Parse(element.Attribute(nameof(IsChecked)).Value);
            var severity = (DiagnosticSeverity)Enum.Parse(typeof(DiagnosticSeverity), element.Attribute(nameof(DiagnosticSeverity)).Value);
            NotificationOption notificationOption;

            switch (severity)
            {
                case DiagnosticSeverity.Hidden:
                    notificationOption = NotificationOption.None;
```
There is a bug in the first line when `element.Attribute("IsChecked")` is null; it throws a `NullReferenceException`.

### PR DESCRIPTION
**Pull request by balajikris**
.. corrupted data in SimpleCodeStyleOption

Fixes #9418.

### CODE REVIEW

**Comment by balajikris** [comment]
tag @dotnet/roslyn-ide and @jmarolf who possibly debugged the crash and has more context.

**_Note:_** I couldn't get it to repro but I can totally understand that persisted data could go corrupt. So, I'm simply trying to guard in such scenarios. Feedback is welcome.

**Comment by jmarolf** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by balajikris** [comment]
tagging @MattGertz for approval

**Comment by balajikris** [comment]
Okay, we figured how this happened. I changed the serialization code and format to be better and Neal's machine had data from a previous version that did not match the format. On a clean machine this scenario for the crash shouldn't happen.

**Comment by balajikris** [comment]
With that change by the way, we now have serializationversion encoded in the string. If we do change the object model in the future, we can check the version and deserialize it appropriately.

**Pull request merged**
