### PR TITLE
Notify XAML of renames caused by Naming Rule fixes

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes https://github.com/dotnet/roslyn/issues/16562

**Customer scenario**: The customer renames a XAML type or element on the C# side to comply with a Naming Rule, and the name doesn't get updated on the XAML side.

**Bugs this fixes**: https://github.com/dotnet/roslyn/issues/16562

**Workarounds, if any**: The customer can manually update XAML references to the symbol.

**Risk**: Low. No other features depend on this aspect of Naming Rules, and we're already calling these VS APIs in other features. This change just makes those API calls available to Code Fixes.

**Performance impact**: Renaming an identifier via a Naming Rule fix will be slightly slower, but this brings it in line with the behavior of Inline Rename and Rename Tracking.

**Is this a regression from a previous update?**: No

**Root cause analysis**: This was a known missing aspect of the Naming Rules fixer that we didn't implement in RTM.

**How did we miss it?** This was a known missing aspect of the Naming Rules fixer that we didn't implement in RTM.

**How was the bug found?** Reported by a customer at https://developercommunity.visualstudio.com/content/problem/9702/naming-rule-violation-not-complete.html

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide for review.

**Comment by dpoeschl** [comment]
@rchande I added a unit test to prove the new Operation is applied only during application and not during preview, and that it receives the correct arguments.

**Comment by rchande** [comment]
Thanks @dpoeschl! Looks good.

**Comment by dpoeschl** [comment]
retest ubuntu_14_debug_prtest please

**Comment by dpoeschl** [comment]
Tagging @MattGertz for Ask Mode consideration. The test failures are unrelated, but I'm working on getting them green.

**Comment by MattGertz** [comment]
Approved -- as noted in side mail, you're also working on getting the tests fixed.

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
"xunit produced no error output but had exit code -2146233082" -- @dotnet/roslyn-infrastructure This happened on both of the failing runs. Is something generally wrong here?

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Pull request merged**
