### PR TITLE
[Master] Don't crash when we hear about very stale diagnostics for our current Document.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes DevDiv bug 157748.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
retest prtest/mac/dbg/unit32 please

**Comment by Pilchie** [comment]
:+1:  Also tagging @heejaechang and @mavasani

**Comment by Pilchie** [comment]
(but we probably want for stabilization).

**Comment by heejaechang** [comment]
:+1:

**Pull request closed without merging**
