### PR TITLE
More cross platform suites

### PR DESCRIPTION
**Pull request by jaredpar**
This change enables the C# Semantic and Symbol suites.

### CODE REVIEW

**Comment by jaredpar** [comment]
@AlekseyTs, @gafter, @agocke, @VSadov

**Comment by jaredpar** [comment]
Ping @AlekseyTs, @gafter, @agocke, @VSadov

**Comment by AlekseyTs** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by jaredpar** [comment]
Thanks guys!

**Pull request merged**
