### PR TITLE
Fix AllowNull/DisallowNull in object initializers

### LINKED ISSUE #39966: Unexpected nullable warning on Property initialisation and [AllowNull]
**Version Used**: 
VS 16.3.10
**Steps to Reproduce**:

```c#
using System;
using System.Diagnostics.CodeAnalysis;

namespace ConsoleApp
{

    public class Foo
    {
        private string? bar;

        [AllowNull]
        public string Bar { get => this.bar ?? string.Empty; set => this.bar = value; }

        static void Main(string[] args)
        {
            var f1 = new Foo()
            {
                Bar = null // CS8625 
            };
            var f2 = new Foo();
            f2.Bar = null; // No Warning
        }

    }
}
```
**Expected Behavior**:
f1.Bar will be assigned without warning in the propertery initialisation.
**Actual Behavior**:
Shows a Warning in property initilizer.

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #39966

/cc @cston

### CODE REVIEW

**Comment by armstrongsean** [comment]
Which version was this fixed in? I am using the latest version of Rider but I don't see warnings for null values passed into methods for parameters with disallow null. I am testing using this constructor:
```
    public Lease([DisallowNull] Guid? uid, [DisallowNull] DateTime? expiresAt,
        [DisallowNull] LeaseStatus? leaseStatus, Proxy proxy, 
        Client client, Domain domain, Country country)
```

**Comment by CyrusNajmabadi** [comment]
> I am using the latest version of Rider

Isn't that on Rider to fix?

**Comment by armstrongsean** [comment]
Not sure... They are using Roslyn analysers.

**Comment by RikkiGibson** [comment]
The milestone on this is 16.5, so we probably shipped this fix around March of 2020. https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.5

**Comment by CyrusNajmabadi** [comment]
>Not sure... They are using Roslyn analysers.

I don't believe this is an analyzer.  This is just the compiler itself.

**Pull request merged**
