### PR TITLE
Merge dev15.1.x to master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15.1.x into master.

``` bash
git fetch --all
git checkout merges/dev15.1.x-to-master-20170306-000004
git reset --hard upstream/master
git merge upstream/dev15.1.x
# Fix merge conflicts
git commit
git push merges/dev15.1.x-to-master-20170306-000004 --force
```

Once all conflicts are resolved and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by tannergooding** [comment]
@TyOverby, could you PTAL at the ubuntu_16 failure.

**Comment by TyOverby** [comment]
what's a PTAL?

**Comment by tannergooding** [comment]
"Please take a look"

**Comment by CyrusNajmabadi** [comment]
Please take a look? (maybe)?

**Comment by CyrusNajmabadi** [comment]
@tmat Can you take a look or ping someone else who can?  ubuntu tests are failing "Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.InteractiveSessionTests.CompilationChain_NestedTypesClass"

This is blocking merging.

**Comment by TyOverby** [comment]
It looks like XUnit isn't running the scripting tests in parallel.

**Comment by tannergooding** [comment]
We do explicitly specify not to run tests in parallel, so if they are doing so it is a bug.

**Comment by jasonmalinowski** [comment]
If the Ubuntu queue is broken, please rollback the breaking change.

**Comment by TyOverby** [comment]
None of the other ubuntu16 runs have failed

**Comment by TyOverby** [comment]
Running another one now just to check

https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_16_debug/3/console

**Comment by TyOverby** [comment]
Yep, still not failing.  

Either there is a genuine problem with this PR, or we hit a once-in-a-lifetime xunit bug.

**Comment by tannergooding** [comment]
@TyOverby, the job passed on retry. We should probably keep an eye out for more failures.

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_vs-integration_prtest  please

**Comment by CyrusNajmabadi** [comment]
Integration failures are known.  @jmarolf is fixing them.

**Pull request merged**
