### PR TITLE
Added dev16.0.x* branches to readme.

### PR DESCRIPTION
**Pull request by AraHaan**
This also contains some fixes to the badges that was easily forgotten to change.

(this might need cherry picked to all the branches this applies to).

### CODE REVIEW

**Comment by AraHaan** [comment]
@jinujoseph you got any idea why those 3 builds failed? It would be nice if those could get fixed (I did not think that editing this file would make them fail at all).

**Comment by AraHaan** [comment]
@heejaechang meaning it was showing the wrong build icon, or the icon shown as failed when the build passed.

**Comment by heejaechang** [comment]
closed and reopen to rerun tests. there was some issue on Jenkins machine last a few days.

**Comment by AraHaan** [comment]
ah, I see

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure can someone from the team take a look? 

here is rendered page
https://github.com/dotnet/roslyn/blob/8eb7a5ce2027261602486d37a0ee80643493bbf4/README.md

bunch of icon is missing and if I go to the url, it is actually not there. also some queue seems to not exist. not sure how to fix those.

**Comment by jasonmalinowski** [comment]
@jaredpar can probably help here. Since jobs have been switched from Jenkins to Azure DevOps some of the broken links are probably those.

**Comment by JoeRobich** [comment]
Hi @AraHaan,
Thanks for taking the time to submit this PR. Unfortunately we changed our readme to only display badges for the master branches and won't be able to take your changes.
-Joey

**Pull request closed without merging**
