### PR TITLE
Order DocCommentHandler after Commit and Completion handlers.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
Tagging @DustinCampbell @dotnet/roslyn-ide   This fixes the regression i caused with VB completion in doc comments.  The fix was 'correct' in as far as it wanted completion ot be ordered before DocComment handling.  however, it didn't work properly because this introduced a circularity into VB's command handlers.  I've broken the circularity so that the command handlers execute in the order:

Commit -> Completion -> DocComment.

Note that this is just the order of the handlers. Not necessarily the order in how things process command.s.  That's because some of these handlers call 'nextHandler' before/after processing the command themselves.  For example, Completion will process 'enter' itself before even deciding if it shuld call nextHandler.  Whereas Commit calls nextHandler first (so that all subsequent comand handlers process the command), and it then fixes up the result as necessary.

**Comment by DustinCampbell** [comment]
@dotnet-bot test vsi please

**Comment by DustinCampbell** [comment]
test passed btw

**Pull request merged**
