### PR TITLE
Update OneLoc build branch

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by JoeRobich** [comment]
@cristianosuzuki77 Is this the correct change?

**Comment by crsuzukimsft** [comment]
@jonfortescue Adding Jon, but seems okay.

**Comment by JoeRobich** [comment]
> Perfect; just make sure you disable it in dev16.11 as well!

Will do. Thanks!

**Review by jmarolf — APPROVED** [review]

**Comment by JoeRobich** [comment]
Merging as this is a non-functional change.

**Pull request merged**
