### PR TITLE
Make 'SplitStringLiteral' fully synchronous.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/11784

This also has the effect of making indentation fully synchronous.

The issue here is that we don't want synchronous command handler features to call out to async code.  This is bad for two reasons:

1. People (i.e. me) make mistakes and attempt to change teh workspace on the async code-path.  This breaks when that async path is not on the UI thread.
2. When we make async calls we're at the mercy of the threadpool.  If it is saturated, or otherwise capricious, our command handler code is blocked until it gets around to running our code.

For sync command handler paths, we want things to execute and complete as quickly as possible.  So we want to avoid async calls from them.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide @jasonmalinowski

**Comment by jasonmalinowski** [comment]
This looks awesome. :+1:

**Comment by CyrusNajmabadi** [comment]
retest windows_eta_open_prtest  please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/68/
// Retest reason: error MSB4018: The "CreateZipPackage" task failed unexpectedly.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/69/
// Retest reason: error MSB3073: The command ""d:\j\workspace\windows_vsi_p---2168b4b2\Closed\Tools\ibcmerge\ibcmerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\windows_vsi_p---2168b4b2\Open\Binaries\Obj\EditorFeatures\Release\Microsoft.CodeAnalysis.EditorFeatures.dll" -incremental "d:\j\workspace\windows_vsi_p--

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/70/
// Retest reason: rror MSB3073: The command ""d:\j\workspace\windows_vsi_p---2168b4b2\Closed\Tools\ibcmerge\ibcmerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\windows_vsi_p--

**Pull request merged**
