### PR TITLE
Fix bug when rewriting expressions with converted enum literals

### LINKED ISSUE #7241: Error rewriting expression tree with converted nullable enum literals
Source: http://stackoverflow.com/questions/34085367/why-does-roslyn-crash-when-trying-to-rewrite-this-lambda-visual-studio-2015-up

This bug is a regression over the VS 2015 RTM behavior.  Here is a sample of the problem:

``` csharp
using System;
using System.Linq.Expressions;

namespace Bug461
{
  class Program
  {
    enum Test { }

    static void Main()
    {
      Expression<Func<Test?, bool>> x = t => t == (Test?)null;
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cyanite**
See http://stackoverflow.com/questions/34085367/why-does-roslyn-crash-when-trying-to-rewrite-this-lambda-visual-studio-2015-up
Fixes #7241

### CODE REVIEW

**Comment by cyanite** [comment]
My previous change was not correct. This aims to solve the problem specifically. Note that the problem originally intended to be solved in https://github.com/dotnet/roslyn/issues/5734 is not fully solved, and can't be fully solved. In the old compiler:

    Expression<Func<Test?, bool>> x = t => t == (Test)0;

Produces:

    t => (Convert(t) == Convert(0))

While:

    Expression<Func<Test?, bool>> x = t => t == (Test?)0;

Produces:

    t => (Convert(t) == Convert(Convert(0)))

Roslyn previously always produced the second kind of output, which is fixed in https://github.com/dotnet/roslyn/issues/5734 as long nullables are not involved. It can't be fixed easily for nullables since the information is simply not available at that point: The two situations above can't easily be told apart.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by AlekseyTs** [comment]
Is there an Issue for this bug?

**Comment by jaredpar** [comment]
Thanks for providing this fix!

I filed issue #7241 to track the bug here. 

Could you add some unit tests to verify this behavior is fixed by this change?

**Comment by cyanite** [comment]
Yes, I'll look at doing that tomorrow.

**Comment by cyanite** [comment]
I updated the PR with a test, inspired by the existing tests of the same functionality.

**Comment by jaredpar** [comment]
:+1:

**Comment by gafter** [comment]
LGTM

**Pull request merged**
