### PR TITLE
Add VisualStudioSetup.Next to the deployment VSIX

### PR DESCRIPTION
**Pull request by jmarolf**
Add VisualStudioSetup.Next to the deployment VSIX

### CODE REVIEW

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
@jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by jmarolf** [comment]
retest windows_debug_unit64_prtest please

http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/future/job/windows_debug_unit64_prtest/156/ Timed out

**Comment by jmarolf** [comment]
@jasonmalinowski I want to merge

**Comment by jasonmalinowski** [comment]
What happens if we install the deployment VSIX onto Dev14?

**Comment by jmarolf** [comment]
@Pilchie would know more than me.  Presumably things would not work.  However, we need this vsix for people who want to use Dev15

**Comment by jasonmalinowski** [comment]
Sure, but we don't want to block Dev14 either, right?

**Comment by Pilchie** [comment]
Yeah, I suspect that this change can't work - the dogfood tool will have to be aware of this and install it separately if you are installing in Dev15.

**Comment by Pilchie** [comment]
Actually, maybe it *will* work, because the new binary will just fail to load properly while building the MEF cache and be ignored.

**Comment by jmarolf** [comment]
I'll test installation on Dev14 and see what happens. I would expect it to not install because we list *.Next as a dependency and it won't be able to satisfy that.

**Pull request closed without merging**
