### PR TITLE
Download the correct version of the nuget packages

### PR DESCRIPTION
**Pull request by davkean**
tag @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2298/
// Retest reason: https://github.com/dotnet/roslyn/issues/7610

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure

**Comment by tmat** [comment]
Do we have 3 places that use the version number? :(:(:(

**Comment by davkean** [comment]
Yes sadly. I've started a thread offline about this.

**Pull request merged**
