### PR TITLE
Fix compilation error on Windows 8.1 with Visual Studio 2015 RC installed

### PR DESCRIPTION
**Pull request by 4creators**
After executing the following instructions I do always encounter the following compilation error on Windows 8.1 Pro with Visual Studio 2015 Enterprise RC installed.

git clone https://github.com/dotnet/roslyn.git
cd roslyn
cibuild.cmd

Implementation\Suggestions\SuggestedAction.cs(235,39): error CS0539: 'SuggestedAction.IconMoniker' in explicit interface declaration is not a member of interface [E:\src\ms\roslyn\Src\EditorFeatures\Core\mjh4jdkx.tmp
_proj]
Implementation\Suggestions\SuggestedAction.cs(23,81): error CS0535: 'SuggestedAction' does not implement interface member 'ISuggestedAction.GetPreview(CancellationToken)' [E:\src\ms\roslyn\Src\EditorFeatures\Core\mjh
4jdkx.tmp_proj]
Implementation\Suggestions\SuggestedAction.cs(23,81): error CS0535: 'SuggestedAction' does not implement interface member 'ISuggestedAction.ActionSets' [E:\src\ms\roslyn\Src\EditorFeatures\Core\mjh4jdkx.tmp_proj]
Implementation\Suggestions\SuggestedAction.cs(23,81): error CS0535: 'SuggestedAction' does not implement interface member 'ISuggestedAction.IconSource' [E:\src\ms\roslyn\Src\EditorFeatures\Core\mjh4jdkx.tmp_proj]
Implementation\Suggestions\SuggestedActionWithFlavors.cs(17,66): error CS0535: 'SuggestedActionWithFlavors' does not implement interface member 'ISuggestedAction.GetPreview(CancellationToken)' [E:\src\ms\roslyn\Src\E
ditorFeatures\Core\mjh4jdkx.tmp_proj]
Implementation\Suggestions\SuggestedActionWithFlavors.cs(17,66): error CS0535: 'SuggestedActionWithFlavors' does not implement interface member 'ISuggestedAction.ActionSets' [E:\src\ms\roslyn\Src\EditorFeatures\Core\
mjh4jdkx.tmp_proj]
Implementation\Suggestions\SuggestedActionWithFlavors.cs(17,66): error CS0535: 'SuggestedActionWithFlavors' does not implement interface member 'ISuggestedAction.IconSource' [E:\src\ms\roslyn\Src\EditorFeatures\Core\
mjh4jdkx.tmp_proj]

The fix is very simple as it requires some minor changes to ISuggestedAction implementation in SuggestedAction.ca file.

Patch is attached. It builds and passes all tests on Windows. Did not test on Linux and Mac.

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@4creators unfortunately, we need to compile the Roslyn code base against newer versions of Visual Studio APIs than what exist in the public VS 2015 RC. The errors you are seeing are because the ISuggestedAction interface that is defined in VS and that Roslyn's light bulb provider depends on has changed since VS 2015 RC. We cannot accept this pull request since then the solution would stop building against the latest internal builds of VS that we need to target for the **1.0 (stable)** release.

**Comment by 4creators** [comment]
@shyamnamboodiripad well, it is obvious for me now. Is there any chance to have an access to latest reference assemblies for VS dependencies in form of nuget packages which would enable build and to some extent with VS RC. It would be a huge help for some of us in community who experiment with latest branch internally before fixing bugs or proposing new features.

**Comment by shyamnamboodiripad** [comment]
@4creators this would enable you to build however you would run into problems when you deploy the built binaries. I believe it should be possible to build and deploy the lower layers (compilers, workspace) that are independent of VS using VS 2015 RC today (I think you can try RoslynLight.sln for this). But layers that depend on VS (editorfeatures etc.) unfortunately suffer from the above external dependency problem. I completely understand the problem that you folks have to deal with because of this.

Some of us have discussed having a branch that will always be buildable against the last released public build of VS. But I am not sure where we are with that. @Pilchie @srivatsn @jaredpar do you have more info about this / are we thinking of other possible mitigations for this problem?

**Comment by Pilchie** [comment]
We are planning on changing our process once VS 2015 ships to ensure that master always builds against a publicly released build of VS.

Next after that is getting a way for people to install newer builds of Roslyn on public builds of VS, and finally for people to be able to debug their own-built Roslyn IDE components in a public build of VS, but that will likely take longer :frowning:

**Comment by 4creators** [comment]
@Pilchie @shyamnamboodiripad From my perspective building roslyn master against current VS and running even subset of tests using my development box environment would be more than enough so I am glad it is in your plans.

**Comment by Pilchie** [comment]
Closing based on above.

**Pull request closed without merging**
