### PR TITLE
Compare Diagnostic.Id and Location only in DiagnosticIncrementalAnalyzer

### LINKED ISSUE #6104: NFW while typing anonymous type in REPL
Type:
```C#
 #r "C:\R1\Binaries\Debug\Microsoft.CodeAnalysis.Scripting.CSharp.dll"
> using Microsoft.CodeAnalysis.Scripting.CSharp;
. 
. CSharpScript.EvaluateAsync("X+Y", new{ }
```

```
Non-fatal exception being thrown.
   at Microsoft.VisualStudio.LanguageServices.Implementation.Watson.WatsonErrorReport.CheckThrottledSubmission(String componentName)

   at Microsoft.VisualStudio.LanguageServices.Implementation.Watson.WatsonErrorReport.ReportIfNecessary()

   at Microsoft.VisualStudio.LanguageServices.Implementation.WatsonReporter.Report(Exception exception)

   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(Exception exception, Action`1 handler)

   at Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportWithoutCrash(Exception exception)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.VerifyDiagnostics(SemanticModel model)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<<TryGetSyntaxAndSemanticCompilerDiagnostics>b__17_3>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticCompilerDiagnostics>b__17_3(DiagnosticAnalyzerDriver _1, DiagnosticAnalyzer _2)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetDocumentDiagnosticsAsync>d__22.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetDocumentDiagnosticsAsync(StateSet stateSet, StateType stateType, Boolean supportsSemanticInSpan, Func`3 versionCheck, Func`3 getDiagnostics, DiagnosticAnalyzerDriver analyzerDriverOpt)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticCompilerDiagnostics>d__17.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticCompilerDiagnostics(StateSet stateSet, VersionStamp textVersion, VersionStamp syntaxVersion, VersionStamp semanticVersion)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetSyntaxAndSemanticDiagnosticsAsync>d__16.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticDiagnosticsAsync(StateSet stateSet, VersionStamp textVersion, VersionStamp syntaxVersion, VersionStamp semanticVersion)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.<TryGetAsync>d__15.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync()

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<TryAppendDiagnosticsForSpanAsync>d__60.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Document document, TextSpan range, List`1 diagnostics, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Document document, TextSpan range, List`1 diagnostics, Boolean includeSuppressedDiagnostics, CancellationToken cancellationToken)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.<>c__DisplayClass16_0.<<TryAppendDiagnosticsForSpanAsync>b__0>d.MoveNext()

   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)

   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.<>c__DisplayClass16_0.<TryAppendDiagnosticsForSpanAsync>b__0()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)

   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)

   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

```

### PR DESCRIPTION
**Pull request by cston**
Fixes #6104

### CODE REVIEW

**Comment by cston** [comment]
@mavasani, @johnhamby, @dotnet/interactive

**Comment by mavasani** [comment]
Also adding @heejaechang

**Comment by cston** [comment]
@dotnet-bot retest this please

**Comment by heejaechang** [comment]
@mavasani I am fine with change, but do you know why with or without span call to GetSemanticModel.GetDiagnostics return different message for anonymous type?

**Comment by cston** [comment]
@heejaechang GetDiagnostics returns new diagnostic instances for each call when binding field initializers (see #6264), and not all diagnostics implement ```Equals``` (see #6262).

**Comment by heejaechang** [comment]
@cston @mavasani ah, so this code doesnt actually have issue then, problem is #6262. anyway, no reason to log non-fatal watson due to the bug. :+1:

**Comment by cston** [comment]
Merged into dotnet:master https://github.com/dotnet/roslyn/commit/caa11f1a4388f28cb88c169368cbf86edc77e36b

**Pull request closed without merging**
