### PR TITLE
Delete many project.lock.json files

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Now that we run restore again on our Windows build machines, we can delete the checked in files for projects only needed for the Windows build. Note, this has one major caveat: since we've turned off automatic restore in Visual Studio, this now _mandates_ you must run a command line restore before opening the solution. Before, you could _sometimes_ get away with that.

*Review:* @dotnet/roslyn-infrastructure, @dotnet/roslyn-ide

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1: Once Jenkins sorts itself out.  Although, should we wait until stabilization calms down?  Are we likely to resurrect these files by mistake when merging from stabilization->master?

**Comment by jasonmalinowski** [comment]
To your question about stabilization, I would say no. The only way we could resurrect the files would be if stabilization has a modification to dependencies, and then it merges to master and the resulting merge conflicts aren't resolved correctly. I would argue that this change makes resolution _easier_ since the merge resolver can just ensure the files are still deleted instead of actually having to ensure the content is correct.

**Comment by jasonmalinowski** [comment]
@davkean, any concerns with this? It will require command line restores if people modify the project.json files. I don't know if that's an in-practice break for anybody or if they were already doing that anyways.

**Comment by davkean** [comment]
:+1:

**Comment by dpoeschl** [comment]
I'm so excited about this.

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-infrastructure: so my Linux build failed with "A new package was introduced, but the Azure store of the packages was not updated." This seems surprising as I'm just deleting lock files that would (in theory) not impact the Linux build. Any guesses what I might have broken?

**Comment by tmat** [comment]
I'd wait with this until https://github.com/dotnet/roslyn/pull/9578 is done and integrated to master. Will be easier integration imo.

**Comment by jasonmalinowski** [comment]
Well, the "integration" is somewhat easier once this is in because you can just resolve the conflict with "take my delete" as opposed to actually merging files. But given your change is most definitely higher priority, I'll wait.

**Comment by jasonmalinowski** [comment]
At this point @tmat's PR has merged. I've rebased the PR to current, so unless anybody else has any concerns, this will get merged today assuming a green test run.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Pull request merged**
