### PR TITLE
fixes issue #4802

### PR DESCRIPTION
**Pull request by ManishJayaswal**

### CODE REVIEW

**Comment by ManishJayaswal** [comment]
FYI @amcasey @tmat @cston @KevinH-MS

**Comment by amcasey** [comment]
For what it's worth, I intentionally made the state transition to ```Resetting``` while executing the ```#reset``` command.  Otherwise, ```IInteractiveWindow.IsResetting``` returns false and the button isn't disabled while the reset is processed.

**Comment by amcasey** [comment]
Per our offline discussion, it still transitions to ```Resetting``` - it's just already cleaned up and waiting for input again by the time it reaches the assert.

**Comment by amcasey** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
fixes #4802

**Pull request merged**
