### PR TITLE
Remove PDB helpers from VS

### PR DESCRIPTION
**Pull request by tmat**
Removes code that's no longer used. We now use the SymReader provided by VS for EnC and thus don't need to create our own instance.

### CODE REVIEW

**Comment by tmat** [comment]
@KevinH-MS

**Comment by KevinH-MS** [comment]
Woops--looks like I missed that. :smile: 

LGTM

**Comment by jaredpar** [comment]
:-1:

**Comment by jaredpar** [comment]
:+1: 

whoops.  slipped up on the keyboard with the previous comment.

**Pull request merged**
