### PR TITLE
Support EditorBrowsable in Fully-Qualify

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1360402

This is a port from teh same fix in main-vs-deps: https://github.com/dotnet/roslyn/pull/53427
Partner team would like this in 16.11

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph This has been approved.  Can you add the right tags?

**Comment by jinujoseph** [comment]
@allisonchou  this is for 16.11 so this should target release/dev16.11 branch right ?

**Comment by allisonchou** [comment]
@jinujoseph Yep, release/dev16.11

**Comment by CyrusNajmabadi** [comment]
Rebased

**Pull request merged**
