### PR TITLE
Cleanup WorkItem Attribute

### PR DESCRIPTION
**Pull request by jaredpar**
The `WorkItem` attribute allows us to associate tests with the bug that caused them to be written.  Even though the constructor takes an id and a description the vast majority of uses in our code base use the ID only.  That was fine when Roslyn was started and we had a single bug database.  Now though we have at least five databases for issues and several of our bugs have migrated between the databases.  

The number of databases and lack of specificity is maknig it hard to link suite failures back to the original bug.  It often takes guessing through several databases to find the intended issue.  

This PR attempts to alleviate this problem by standardizing our use of `WorkItem` attributes to have the following form:

``` C# 
[WorkItem(<issue id>, <url to issue>)
```

This PR was created by a mix of hand changes and tool driven updates.  The latter used a strong heuristic to find the intended database for a given bug ID.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler, @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
For the 8 "unknown" bugs, should we just delete the attributes? It also seems for the unknown bug 1 and a few others those might be CodePlex bug numbers.

**Comment by jasonmalinowski** [comment]
Also, is there some reasonable way to add enforcement that the bug URL is at least a URL of some minimally acceptable form? For example, if we can at least assert it starts with one of the known URL prefixes, then that would prevent people from breaking this again by putting just simple numbers or English in the URL.

**Comment by jasonmalinowski** [comment]
Spot checking a few though, :+1:.

**Comment by CyrusNajmabadi** [comment]
Do we want ```&_a=edit``` in all the server paths?

**Comment by VSadov** [comment]
LGTM

**Comment by jaredpar** [comment]
@CyrusNajmabadi if you omit `&_a=edit` then it isn't a valid link :frowning:  

I'd be more than happy to delete that though if you can find a better URL.

**Comment by jaredpar** [comment]
@jasonmalinowski 

I will add some verification to the WorkItem ctor to ensure it's a minimally valid URL.  

As for the "unknown" I expect to clarify or delete them soon.

**Comment by TyOverby** [comment]
LGTM

**Comment by ManishJayaswal** [comment]
:+1:

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @jaredpar Instead of `http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems#_a=edit&id=638289`, you can do `http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/638289`. It's cleaner looking, but people writing these WorkItem attributes from scratch are probably just going to find/use the `#_a=edit&id=638289` version anyway because that's the only easily discoverable one. ([Found via msdn](https://msdn.microsoft.com/en-us/library/bb822129.aspx)).

**Comment by dpoeschl** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
That is *much cleaner*.  Let's use that syntax instead.

**Comment by dpoeschl** [comment]
But if you want people using that later, we'll probably need an analyzer/fixer to convert it...

**Comment by jaredpar** [comment]
@dpoeschl that is definitely more readable and cleaner.  I can't imagine why that's not the default display in VSO.  Will update my tool to use that syntax.

**Comment by jaredpar** [comment]
Updated to the more readable URL that @dpoeschl discovered. 

The only bad part about the change is clicking on the pretty one will open your browser and navigate to the less readable version :frowning:

**Comment by dpoeschl** [comment]
Did a spot check, :+1: for the prettier urls

**Pull request merged**
