### PR TITLE
Remove space preventing editorconfig settings from applying to vb files

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
Noticed this while dogfooding - PR against master since it doesn't affect build, and helps if others copy our .editorconfig file.

Tagging @dotnet/roslyn-ide for review, and @MattGertz for approval for the non-build change to master.

**Comment by Pilchie** [comment]
Also @olegtk how strict is the .editorconfig spec here?  Should we be more forgiving and allow the space?  Alternatively @madskristensen, is this something your extension can detect and warn about (or maybe it does already?)

**Comment by Pilchie** [comment]
Installed the EditorConfig language service.  In a *pure* VB project there is a message that the glob doesn't match any files, but in a mixed solution where it matches C# files, there is no warning.

**Comment by madskristensen** [comment]
@Pilchie It will give a warning if no files matches the pattern. So it won't catch all cases here

**Comment by Pilchie** [comment]
@madskristensen filed https://github.com/madskristensen/EditorConfigLanguage/issues/5 for you.

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by olegtk** [comment]
EditorConfig spec is not particularly specific, doesn't mention if spaces are allowed: "{s1,s2,s3}	Matches any of the strings given (separated by commas)". But our behavior matches editorconfig-core-net reference implementation and IntelliJ IDEA so I'd say that spaces are not conventionally allowed.

**Comment by madskristensen** [comment]
So perhaps I should add an option to invalidate patterns containing spaces that can be disabled in _Tools -> Options_. Makes sense?

**Comment by Pilchie** [comment]
@madskristensen that sounds great.

**Pull request merged**
