### PR TITLE
Merge from master to features/readonly-ref

### PR DESCRIPTION
**Pull request by VSadov**

### CODE REVIEW

**Comment by VSadov** [comment]
@OmarTawfik - FYI

**Comment by VSadov** [comment]
Test this please

**Comment by VSadov** [comment]
Will rerun tests couple times looking for flakeyness. Would not want to merge with that.

**Comment by VSadov** [comment]
Test this please

**Comment by VSadov** [comment]
test this please

**Comment by OmarTawfik** [comment]
Since you're still fighting flaky tests, can this wait until I merge the PR that lowers stackalloc conversions? I'm sending it out now.

**Comment by VSadov** [comment]
@OmarTawfik - it does not seem flakier than usual, so on that part we are ok. The ubuntu tests are failing bydesign since the CI script is updated in this change, but Jenkins must use the previous version. - Ubuntu will start passing after this change is merged.

It would be better to merge this before the other changes (I also have a PR in progress). 
It was fairly difficult merge (files created/removed, stuff moved between files). I had to move a fair amount of changes manually since merge tools could not figure that.  I do not want to risk redoing.  
Rebasing on top of the merge should be easy though.

My plan is to not merge this while other PRs are in progress, so that to not break commenting, but once they are signed off, merge this first, then rebase the PRs and merge them after.

**Pull request merged**
