### PR TITLE
Enable using tuples in Interactive Window and csi without #r "System.ValueTuple.dll"

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/roslyn/issues/14347

### CODE REVIEW

**Comment by tmat** [comment]
@jcouv @dotnet/roslyn-interactive

**Comment by KevinH-MS** [comment]
I didn't realize we had so man .rsp files.  Are any of the interactive ones different (besides the two diff languages)?

**Comment by KevinH-MS** [comment]
👍

**Comment by tmat** [comment]
@KevinH-MS There is one for Desktop, one for .NET Core, one for VS.

**Comment by jcouv** [comment]
Thanks :-)

**Comment by tmat** [comment]
@KevinH-MS Surprisingly, VB comes to rescue :) VB command line parser adds directories of all response files to the reference search paths. CSI now does the same.

**Comment by tmat** [comment]
@VSadov For compiler change review.

**Comment by tmat** [comment]
test windows_release_unit64_prtest please

**Comment by tmat** [comment]
test windows_release_unit32_prtest please

**Comment by tmat** [comment]
Test failures: https://github.com/dotnet/roslyn/issues/14380

**Comment by tmat** [comment]
test windows_eta_open_prtest please

**Comment by tmat** [comment]
test windows_release_unit64_prtest please

**Comment by tmat** [comment]
test windows_debug_unit64_prtest  please

**Comment by tmat** [comment]
test windows_debug_unit64_prtest please

**Pull request merged**
