### PR TITLE
Fix correct usage of the /keepalive option in the managed client

### PR DESCRIPTION
**Pull request by agocke**
Port commit 752d7ccb9703e667c3d62784a8b517bd4941ca83 from master to preview.

### CODE REVIEW

**Comment by theoy** [comment]
Paging @jaredpar and @pharring  for feedback as well, for consideration for RC2.

**Comment by pharring** [comment]
:+1:

**Comment by agocke** [comment]
@jaredpar ping

**Comment by agocke** [comment]
@jaredpar pong

**Comment by jaredpar** [comment]
:+1: 

Next time just come by and pong me in person. It's probably faster ;)

**Pull request merged**
