### PR TITLE
Update the progress API shape to make it easier to mark a set of work as complete.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Extracted out from NavTo changes.  There we have a need to easily set an entire set of work as being complete.

### CODE REVIEW

**Comment by ryzngard** [comment]
> Extracted out from NavTo changes. There we have a need to easily set an entire set of work as being complete.

Do you have an example usage of this? It looks like it was just added with an extension for single for now. Interested to see what scenarios want to notify multiple items complete and why

**Comment by CyrusNajmabadi** [comment]
> Interested to see what scenarios want to notify multiple items complete and why

For navto we may have to sweep over the projects multiple timse.  So we have the progress represent hte worst case results.  However, if we decide to shortcircuit and avoid some of those passes, we can just add in all the missing work we skipped in one op.

**Review by ryzngard — APPROVED** [review]

**Pull request merged**
