### PR TITLE
Update nuget.exe and the updated lock file

### PR DESCRIPTION
**Pull request by agocke**
/cc @davkean @amcasey @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by davkean** [comment]
Can you add a comment to the commit as to what build you uploaded?

**Comment by davkean** [comment]
:+1:

**Comment by agocke** [comment]
Yup, this is 3.3

**Comment by ManishJayaswal** [comment]
:+1:

**Comment by agocke** [comment]
test win please

**Pull request merged**
