### PR TITLE
Unskip working tests

### LINKED ISSUE #21766: Crash caused by GetEnclosingNamedType returning null in incomplete expression bodied member
```C#
public static class Extensions { public static T Get<T>(this object o) => $$}
```

(Note that the caret is immediately touching the closing brace).
If you type `o` at the caret position, completion crashes because SemanticModel.GetEnclosingNamedType returns null at https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Recommendations/CSharpRecommendationService.cs#L271.

This seems like a compiler bug given that GetEnclosingNamedType doesn't return null if you put the caret next to the arrow instead.

Ported from https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=420697&_a=edit

### LINKED ISSUE #35100: Semantic model returns a single candidate symbol for chained queries and generic vs non-generic overloads
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace ThenIncludeIntellisenseBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var registrations = new List<Registration>().AsQueryable();
            var reg = registrations.Include(r => r.Activities).ThenInclude(c => c.$$);
        }
    }

    public class Registration
    {
        public ICollection<Activity> Activities { get; set; }
    }

    public class Activity
    {
        public Task Task { get; set; }
    }

    public class Task
    {
        public string Name { get; set; }
    }

    public interface IIncludableQueryable<out TEntity, out TProperty> : IQueryable<TEntity>
    {
    }

    public static class EntityFrameworkQuerybleExtensions
    {
        public static IIncludableQueryable<TEntity, TProperty> Include<TEntity, TProperty>(
            this IQueryable<TEntity> source,
            Expression<Func<TEntity, TProperty>> navigationPropertyPath)
            where TEntity : class
        {
            return default(IIncludableQueryable<TEntity, TProperty>);
        }

        public static IIncludableQueryable<Registration, Task> ThenInclude(
            this IIncludableQueryable<Registration, ICollection<Activity>> source,
            Func<Activity, Task> navigationPropertyPath)
        {
            return default(IIncludableQueryable<Registration, Task>);
        }

        public static IIncludableQueryable<TEntity, TProperty> ThenInclude<TEntity, TPreviousProperty, TProperty>(
            this IIncludableQueryable<TEntity, TPreviousProperty> source,
            Expression<Func<TPreviousProperty, TProperty>> navigationPropertyPath) where TEntity : class
        {
            return default(IIncludableQueryable<TEntity, TProperty>);
        }
    }
}
```
`c` before $$ can be either Activity or ICollection<Activity>. One can replace $$ with `Task `or with `First()`. Both are valid. However, intellisense is provided for `First() `and other collection methods. `Task `is not available in intellisense.

This happens because C# semantic model provides just a single candidate for the method symbol.

### PR DESCRIPTION
**Pull request by Rekkonnect**
Discovered 3 tests that pass and were skipped.

Closes #21766
Closes #35100

CC @CyrusNajmabadi

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi all checks passed after the rerun but it wasn't auto-merged

**Comment by CyrusNajmabadi** [comment]
Branch is locked down right now

**Comment by Rekkonnect** [comment]
@CyrusNajmabadi ptal

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
THanks!

**Pull request merged**
