### PR TITLE
Delete Compilers.sln and keep only Compilers.slnf

### PR DESCRIPTION
**Pull request by Youssef1313**
Alternative to: https://github.com/dotnet/roslyn/pull/47531

Here is the approach I took:

- Load Roslyn.sln **without** any projects.
- Right click Compilers and choose "Reload Projects in Solution Folder"
- For every project in the compiler layer, right click and choose "Load Entire Dependency Tree"
- Right click the solution and choose "Save As Solution Filter", replacing Compilers.slnf.
- Next step is manual review.

### Manually add missing projects

- CompilersBoundTreeGenerator.csproj
- CSharpErrorFactsGenerator.csproj
- CompilersIOperationGenerator.csproj
- VisualBasicSyntaxGenerator.vbproj
- VisualBasicErrorFactsGenerator.vbproj
- Microsoft.CodeAnalysis.Collections.shproj
- PrepareTests.csproj
- TestDiscoveryWorker.csproj
- RunTests.csproj
- Microsoft.CodeAnalysis.Scripting.UnitTests.csproj
- Microsoft.CodeAnalysis.CSharp.Scripting.UnitTests.csproj
- Microsoft.CodeAnalysis.VisualBasic.Scripting.UnitTests.vbproj
- Microsoft.CodeAnalysis.Scripting.csproj
- Microsoft.CodeAnalysis.CSharp.Scripting.csproj
- Microsoft.CodeAnalysis.VisualBasic.Scripting.vbproj
- Microsoft.CodeAnalysis.Scripting.TestUtilities.csproj

---

### Note 1

CodeStyleConfigFileGenerator.csproj was in Compilers.sln, but I don't think it's relevant to the compilers layer. So I'm not including it.

---

### Note 2

Nothing in `src\Compilers` depends on the following projects, but I'm not sure if any of them should be included. Currently I'm not including them.

- src\Tools\BuildBoss\BuildBoss.csproj
- src\Tools\BuildValidator\BuildValidator.csproj
- src\NuGet\Microsoft.CodeAnalysis.Scripting.Package.csproj
- src\Interactive\vbi\vbi.vbproj

**vbi.vbproj specifically is a bit suspicious. The equivalent C# csi.csproj has references in `src/Compilers/Extension/Roslyn.Compilers.Extension.csproj` and `src/Compilers/CSharp/Test/CommandLine/Microsoft.CodeAnalysis.CSharp.CommandLine.UnitTests.csproj`. I'm not sure why this is not the case with `vbi.vbproj`.**

---

Finally, I replaced references to `Compilers.sln` to `Compilers.slnf`

### CODE REVIEW

**Comment by Youssef1313** [comment]
I can't make any sense of the CI failure. I appreciate if someone can take a look.

**Comment by 333fred** [comment]
It looks like the PrepareTests project is not being build on linux.

In general, every time we've tried to remove Compilers.sln in the past, we've found some workflow or another that depends on it existing. I'm not certain all of those have been removed.

**Comment by Youssef1313** [comment]
@333fred I thought that it should work since https://github.com/dotnet/msbuild/issues/5715 is closed? Is the issue still on msbuild side?

**Comment by 333fred** [comment]
@Youssef1313 every time, we find something new. That was the latest in the line, but I have no guarantee it's the last :).

**Comment by Youssef1313** [comment]
I'm quite confused as to where the problem is.

If I understand correctly, the script fails here:

https://github.com/dotnet/roslyn/blob/54a50247a9f875916947815176dacadf2d7444ee/eng/prepare-tests.sh#L31

This line (and also above lines) don't reference sln/slnf at all.

**Comment by Youssef1313** [comment]
Oh, that makes total sense (though the error message was quite vague)! Thanks @333fred.

I'll fix that.

**Comment by 333fred** [comment]
I'm not sure, maybe @dibarbet knows?

**Comment by dibarbet** [comment]
@Youssef1313 Tests run on all UnitTests dlls that the build outputs.  If the test dll isn't output, the tests don't get run.  It looks like the build from this PR is missing some UnitTest dlls in the build.

This information is available in the CI artifacts.  In the build from this PR, look at Transport_Artifacts_Unix_Debug - https://dev.azure.com/dnceng-public/public/_build/results?buildId=104298&view=artifacts&pathAsName=false&type=publishedArtifacts - it has 19 UnitTest folders in artifacts/bin

In other CI runs, for example
https://dev.azure.com/dnceng-public/public/_build/results?buildId=104929&view=artifacts&pathAsName=false&type=publishedArtifacts we have 22 unit test dlls.  So some are missing here.

You can run the commands locally too - see the yaml (don't need the preparemachine / ci flags) https://github.com/dotnet/roslyn/blob/main/eng/pipelines/build-unix-job.yml#L31

**Comment by Youssef1313** [comment]
Thanks @dibarbet. The missing ones were "Scripting" tests indeed. I included them in slnf now. It should hopefully be good now.

**Review by dibarbet — APPROVED** [review]
that looks right now

**Comment by Youssef1313** [comment]
@333fred @dibarbet Could we get this merged?

**Comment by 333fred** [comment]
I still don't know how I feel about this change. I'm very worried about breaking both compiler dev workflows and some pipeline that we don't currently know about. @dotnet/roslyn-compiler for other thoughts.

**Comment by CyrusNajmabadi** [comment]
i'm a little concerned too.  i use compilers.sln all the time :)

**Comment by Youssef1313** [comment]
> I still don't know how I feel about this change. I'm very worried about breaking both compiler dev workflows and some pipeline that we don't currently know about. @dotnet/roslyn-compiler for other thoughts.

In case problems are discovered in future, we can either see if they can easily fixed, or otherwise simply revert the PR?

---



> i'm a little concerned too. i use compilers.sln all the time :)

Could you test it locally and see if anything obvious broke for you? :)
I expect issues (**if any**) will be on Linux, but it seems all past issues were resolved.

**Comment by 333fred** [comment]
We're going to wait on this until after the holidays, as if it breaks anything the people to fix may be out.

**Comment by Youssef1313** [comment]
Makes sense.

**Comment by Youssef1313** [comment]
@333fred Is this ready to merge?

**Comment by 333fred** [comment]
@Youssef1313 I'm going to wait until tomorrow afternoon to give the rest of the compiler team a chance to raise any last-minute objections.

**Comment by jcouv** [comment]
Has someone used the `slnf` for at least a few days to validate there isn't any productivity issues?

**Comment by 333fred** [comment]
I've verified that it seems to work in vscode (but not for an extended length of time), and I've used in VS quite a bit (though not in some time, as I'm mostly in vscode these days).

**Comment by 333fred** [comment]
@jcouv did you have any further feedback?

**Review by jcouv — APPROVED** [review]

**Comment by 333fred** [comment]
Alright, looks like there's a conflict @Youssef1313.

**Pull request merged**
