### PR TITLE
Update 'remove unnecessary parens' to support removing from 'negated if statements'.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/30945.  Will eventually be a PR that merges into `features/guard-statements` if that PR is accepted.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
closing

**Comment by CyrusNajmabadi** [comment]
Opening.

**Comment by mavasani** [comment]
@CyrusNajmabadi @gafter - is this PR still relevant given https://github.com/dotnet/roslyn/pull/30945#issuecomment-487788173

**Comment by CyrusNajmabadi** [comment]
@mavasani It really depends on what LDM finally decides.  If tehy add `if!(...)`, then this is relevant.  If they decide that they're not going forward with this, then this can be closed out.

**Comment by CyrusNajmabadi** [comment]
Closing out.  I've seen no movement on guard statements.

**Pull request closed without merging**
