### PR TITLE
Introduce msbuild variables for versions of Immutable and Metadata nuget packages

### PR DESCRIPTION
**Pull request by tmat**
Makes it much easier to merge master with portable-pdb branch.

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski @agocke

**Comment by tmat** [comment]
retest this please

**Comment by jasonmalinowski** [comment]
Is there any reason we can't just do this the "normal" way and have NuGet do the upgrade? Or is this mostly to deal with merge conflicts?

**Comment by tmat** [comment]
"Makes it much easier to merge master with portable-pdb branch."

**Pull request merged**
