### PR TITLE
Cleanup of 'fix all'.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide  @mavasani @heejaechang

**Comment by heejaechang** [comment]
:+1:

**Comment by heejaechang** [comment]
@mavasani did you add new say to fix multi context?

**Comment by Pilchie** [comment]
:+1:

**Comment by mavasani** [comment]
:+1: 
@heejaechang This was the unused API left behind when we moved from multiple invocation of ComputeFix for error list bulk suppression (each of which shows a preview dialog) to invoking GetFix multiple times and showing a single preview dialog at the end. Thanks for cleaning it up Cyrus.

**Pull request merged**
