### PR TITLE
Use NuGet 3.6.0-beta1 which has support for -msbuildpath to find MSBuild

### PR DESCRIPTION
**Pull request by Pilchie**
Tag @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tannergooding** [comment]
@Pilchie, this version of NuGet requires users to explicitly specify the path and does not support automatically locating VS via the Managed Query APIs, correct?

**Comment by Pilchie** [comment]
@tannergooding Yes.  Unfortunately, because jenkins has Dev15 preview 3, my version check is busted :(

**Comment by tannergooding** [comment]
We have machines already setup that contain Preview 5, we could move over to that label instead, if that fixes things.

**Comment by Pilchie** [comment]
@tannergooding pushed a new change that uses an existence check instead of a version check

**Comment by Pilchie** [comment]
@tmat @jaredpar @agocke 

>14:13:26   D:\j\workspace\microbuild_pr---d013602c\src/NuGet\Microsoft.CodeAnalysis.Common.nuspec : error : A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "System.Reflection.Metadata [1.4.1-beta-24430-01, )" or update the version field in the nuspec. [D:\j\workspace\microbuild_pr---d013602c\src\NuGet\NuGet.proj]
14:13:26   D:\j\workspace\microbuild_pr---d013602c\src/NuGet\Microsoft.CodeAnalysis.Common.nuspec : error : A stable release of a package should not have a prerelease dependency. Either modify the version spec of dependency "System.Reflection.Metadata [1.4.1-beta-24430-01, )" or update the version field in the nuspec. [D:\j\workspace\microbuild_pr---d013602c\src\NuGet\NuGet.proj]
14:13:26   D:\j\workspace\microbuild_pr---d013602c\src\NuGet\NuGet.proj(13,5): error MSB3073: The command "D:\j\workspace\microbuild_pr---d013602c\Binaries\Release\Exes\csi\csi.exe D:\j\workspace\microbuild_pr---d013602c\src\NuGet\BuildNuGets.csx D:\j\workspace\microbuild_pr---d013602c\Binaries\Release\ 2.0.0 D:\j\workspace\microbuild_pr---d013602c\Binaries\Release\NuGet\Release" exited with code 1.

Known?

**Comment by tmat** [comment]
I guess nuget error reporting changed in the new version and the script that's trying to package release version of Roslyn nupkg doesn't handle it.

**Comment by Pilchie** [comment]
So - should I disable building of Release NuGets?

**Comment by Pilchie** [comment]
@agocke @jaredpar @tmat @jasonmalinowski can you take a look, and let me know if disabling building release nugets is the right thing to do?

**Comment by tmat** [comment]
@jasonmalinowski I think this is by design. We always try to build release nugets and ignore the errors.

**Comment by tannergooding** [comment]
@Pilchie, @tmat, @jasonmalinowski. IIRC, we only were supposed to build release packages by default in the release branch (where we cannot have any pre-release dependencies). `master` should never be doing this by default because we frequently depend on pre-release packages there.

**Comment by jasonmalinowski** [comment]
Correct, we want to try to build release packages if we can. The problem with "we should only do them in release branches" is there's no way to configure such a thing in our build system, and Git makes it actively annoying to maintain such a thing in a specific branch. We also had cases where we made a release branch and then forgot to update this.

The correct fix is to fix the script's handling of the error that it was able to handle and now isn't.

**Comment by Pilchie** [comment]
Updated with the right fix.  It appears NuGet fixed the grammar of their error message.

**Comment by tannergooding** [comment]
👍

**Pull request merged**
