### PR TITLE
Upgrade BCL nuget packages to RC releases

### PR DESCRIPTION
**Pull request by nguerrera**
There are 3 parts:

* 6891c08  - (yawn) Version search and replace across *.config;*.nupsec;*.csproj;*.vbproj
* ae23df1 - Adjust to small breaking changes in System.Collections.Immutable
* a663279 - Adjust test expectation to correct projected version of System.Numerics.Vectors

cc @tmat @jaredpar @theoy @joshfree

### CODE REVIEW

**Comment by jaredpar** [comment]
Note: I will take care of the Closed portion of this change for @nguerrera 

CC @pharring, @gafter as well for sign off

**Comment by gafter** [comment]
:+1:

**Comment by gafter** [comment]
@nguerrera Did you intend to close this PR?

**Comment by jaredpar** [comment]
@gafter technically speaking I closed the PR.  But I did so by merging @nguerrera change into master.

**Comment by pharring** [comment]
LGTM, thanks.

**Comment by nguerrera** [comment]
Thanks.

**Pull request closed without merging**
