### PR TITLE
Provide more information in sighelp exception when invalid data is passed in.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by Pilchie** [comment]
LGTM, but please wait for the "Approved for next preview" label before merging.

**Comment by CyrusNajmabadi** [comment]
Ok.  Thanks!

**Comment by MattGertz** [comment]
Rejected 5/21 by ML Shiproom.

**Comment by Pilchie** [comment]
Go ahead and merge #2958 instead.

**Pull request closed without merging**
