### PR TITLE
Restore backward compatibility in the way conversion from a reference type to an intrinsic value type is evaluated.

### LINKED ISSUE #9887: CType/CBool/etc throwing invalid cast exception depending on the declared variable type although the actual type is the same
**Version Used**: 

vb.net visual studio 2015 update 1

**Steps to Reproduce**:

1. Create a test method

``` vb
<TestMethod>
Public Sub TestCBoolWithIComparableDouble()
    Dim value As **IComparable** = 1R
    Assert.IsTrue(CBool(value))
End Sub
```

**Expected Behavior**:

Test passes.

**Actual Behavior**:

Test fails with an invalid cast exception

**In Contrast (it actually does pass the test and does not throw)**

``` vb
<TestMethod>
Public Sub TestCBoolWithDouble()
    Dim value As **Object** = 1R
    Assert.IsTrue(CBool(value))
End Sub
```

On a side note: I wasnt even able to decompile the first method, whereas the second one could be decompiled without any problem (.net reflector 9)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #9887.

@dotnet/roslyn-compiler Please review a bug fix for 1.3 milestone.

CC @MattGertz, @jaredpar For approval.

### CODE REVIEW

**Comment by MattGertz** [comment]
Approved pending successful tests and code reviews.

**Comment by gafter** [comment]
:shipit:

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review a bug fix for 1.3 milestone. I need a second sign-off.

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
