### PR TITLE
Don't crash if you rename a file and change or remove the extension

### PR DESCRIPTION
**Pull request by jasonmalinowski**
If you use Solution Explorer to rename a file and the extension were to change or get deleted, we might crash. That's really bad, and we shouldn't do that.

The problem was another fun example where different systems might see the rename first: if the document provider saw the RDT rename first, it'd close a document that the MiscellaneousFilesWorkspace was tracking. However, it saw things after the rename and in one place but hadn't seen the rename yet from the RDT.

*Review:* @dotnet/roslyn-ide

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@DustinCampbell a specific request for a review here as I'm touching the code model cache. After my first fix, renaming Foo.cs to Foocs, then back to Foo.cs and back to Foocs again (testing!) still triggered an exception. I am taking a defensive fix here. I tried to fix the "root cause", that a rename from Foocs -> Foo.cs wasn't updating the cache in a fix like 11b7d0cfdd6fa19ee91ec5c7fd36e1c3f408408d, but that ended up having other issues where Winforms wasn't terribly happy getting a reused codemodel at that point. Let me know if you think this is fine or if I should pursue that proper fix.

**Comment by jasonmalinowski** [comment]
@MattGertz for the bar check.

**Comment by MattGertz** [comment]
Approved pending the usual

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_vsi_p3_open_prtest please.

That is a new way for those tests to blow up.

**Pull request merged**
