### PR TITLE
Break out VB Recommendation tests into their own dll like we do with C#.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Note: the reason for making a new test dll was that it was getting really cumbersome to maintain and work with all the code action unit tests.  Now the UnitTest3 librarys for both C# and Vb are the place for those tests.

**Comment by jasonmalinowski** [comment]
What was the underlying problem here you're trying to address? We originally made the C# unit test DLL as a temporary workaround, planning on eventually getting rid of it again.

**Comment by Pilchie** [comment]
Indeed - can you elaborate on what you mean by "cumbersome".  Also, why not give a meaningful name for the split if we really want to do it?

**Comment by CyrusNajmabadi** [comment]
It's cumbersome that i have to look in one DLL for tests for C#, and then a non-analogous DLL for tests for VB.  It's much easier when we have symmetry.   If I'm in VBFeatures i go to CSharpFeatures, etc.

On aa few occasions i've found myself getting confused as to where these tests actually live because of the non-uniformity.

When the tests were originally broken out for C# i really wish they'd been broken out for VB as well.

**Pull request closed without merging**
