### PR TITLE
WIP: Fixes possible NRE in VisualStudioDebugStateChangeListener

### PR DESCRIPTION
**Pull request by tmat**
Not sure if this is the right fix yet. The debugger might address it on their end.

### CODE REVIEW

**Comment by tmat** [comment]
Actually, the debugger will provide the fix.

**Comment by genlu** [comment]
In that case, should we add asserts here?

**Comment by tmat** [comment]
No, need. It will throw NRE if it's not initialized.

**Comment by davkean** [comment]
@tmat I hit this crash: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/946146/. Is there a bug to dup this against?

**Comment by tmat** [comment]
Yes, https://devdiv.visualstudio.com/DevDiv/_workitems/edit/945028. Do you have EnC disabled in the debugger options? The crash only repros when when EnC is disabled.

**Comment by tmat** [comment]
Ah, never mind the bug explains.

**Comment by tmat** [comment]
Any reasons to have EnC disabled?

**Pull request closed without merging**
