### PR TITLE
Revert "Analyze flow in receiver of extension method group in delegate creation"

### PR DESCRIPTION
**Pull request by 333fred**
Reverts dotnet/roslyn#59874 to unblock insertion.

### CODE REVIEW

**Comment by 333fred** [comment]
FYI @jcouv @RikkiGibson

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Is it the case that when accessing a static member from an instance member, 'this' is implicitly used as the receiver?

**Comment by 333fred** [comment]
> Is it the case that when accessing a static member from an instance member, 'this' is implicitly used as the receiver?

Yes, there's a `BoundThisReference` as a receiver for the `BoundMethodGroup`.

**Review by AlekseyTs — APPROVED** [review]

**Review by ryzngard — APPROVED** [review]

**Comment by 333fred** [comment]
Unit tests and correctness passed. Merged to unblock the insertion.

**Pull request merged**
