### PR TITLE
Retargeted - Still bind unbound lamda with errors within BindDelegateCreationExpression.

### LINKED ISSUE #7520: Parameter type infer failed in lambda.
VS2015 Community Update 1 on Win10 RTM x64
Just create a new Console Application and type the following, ignore the color bug:
image

### PR DESCRIPTION
**Pull request by diryboy**
#10513 retargeted against future. Fixes #7520

### CODE REVIEW

**Comment by diryboy** [comment]
Looks those vsi tests succeed in seconds? Are there any problems?

**Comment by AlekseyTs** [comment]
The change LGTM. 

> Looks those vsi tests succeed in seconds? Are there any problems?

@dotnet/roslyn-infrastructure Could you comment on the question above?

**Comment by mattwar** [comment]
The tests succeeded automatically because nothing was changed.  It is reporting the cached results.

**Comment by AlekseyTs** [comment]
So, we are good to merge then?

**Comment by mattwar** [comment]
Yes.  We can ignore the eta2 failure.  It is still work in progress.

**Comment by AlekseyTs** [comment]
@diryboy Thank you for the contribution!

**Pull request merged**
