### PR TITLE
Try Peek v3

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
This is a working implementation of TryPeek

### CODE REVIEW

**Comment by mikedn** [comment]
> CanGet(at) AndAlso Peek(at) = c

Why not just `Peek(at) = c` and have Peek return an invalid character if `at` is beyond the end of the text source?

That's what the C# lexer seems to do and I've seen this in other parsers too. The assumption that after the end of the text source follows an infinite sequence of invalid characters tends to simply a lot of code.

**Comment by jaredpar** [comment]
@AdamSpeight2008  

I'm closing this Pull Request.  We've repeatedly asked for you to **not** open new PRs when their are existing PRs for the same change.  Doing so causes us to lose valuable feedback that we spent time adding to the previous PR.  For those of us who realize the PR exists we have to open several tabs and keep jumping between them to process the change. 

This is the 3rd PR that you've opened for this change.  Please use the first or second to continue pushing forward with this change.

**Comment by AdamSpeight2008** [comment]
@jaredpar Just use this one as it contains working implementation of the other PR.

**Comment by AdamSpeight2008** [comment]
@pharring `TryPeek` was intend to target the cases where multiple `Peek`s of the same offset where being compared against some characters. Where introducing the local reduces the number of method invocations.

**Comment by jaredpar** [comment]
@AdamSpeight2008 

No.  This particular PR will not be accepted.  If this change goes through it will do so through one of the other existing PRs.  

As we've stated before the problem with multiple PRs is that it makes it harder to find the feedback that others have already provided.  @pharring in particular has taken the time to give valuable feedback to your PRs over time.  This is beneficial to both you as the contributor and others who are reviewing the change.  

Every time a new PR is opened it makes it harder to track down that feedback.  To those that don't follow the PRs as closely that feedback may well not exist.  

This is the third time we've asked to please keep a logical change on the same PR.  I don't know how to make our stance any clearer on this.

**Comment by AnthonyDGreen** [comment]
@mikedn, that's a valid approach. The only concern I would have is that the most logical character to use is the null character ChrW(0). We've actually seen cases where code files have embedded null characters in them and we want to not treat that as strictly the same as end of file. We could pick a different sentinel char perhaps but the problem would be the same - what the parser would do if it ever did encounter that character in the middle of a program.

**Pull request closed without merging**
