### PR TITLE
Move "Unseal class" codefix to VerifyCS

### PR DESCRIPTION
**Pull request by DoctorKrolic**
- Moved `Unseal class` to `VerifyCS` test model
- Enabled nullable in the codefix itself

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]
In the future, can you make the change to raw strings on a separate commit. It will make it easier to review. Thanks!

**Comment by DoctorKrolic** [comment]
> In the future, can you make the change to raw strings on a separate commit

Sure.

Also restart failed CI pls, it seems unrelated to the changes

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Restart failed CI pls

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Restart failed Ci again pls, integration tests seem to be very inconsistent

**Review by sharwell — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi @sharwell Need another CI attempt here...

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Restart failed CI pls

**Pull request merged**
