### PR TITLE
Added initial FreeBSD support

### PR DESCRIPTION
**Pull request by ajensenwaud**
Changed hardcoded bash shebang to env to support multiple directory
structures (required to build on FreeBSD).

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
:+1:

**Comment by jasonwilliams200OK** [comment]
:+1: 
@mmitche, @josteink, in addition to the issues identified at https://github.com/dotnet/coreclr/issues/1044, it would probably be a good idea to merge this one, so more robust support for FreeBSD can be ensured across the stack.

**Comment by josteink** [comment]
LGTM

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
