### PR TITLE
Default Interface Impementation: Verify resulting assembly and runtime behavior when targeting CoreCLR.

### PR DESCRIPTION
**Pull request by AlekseyTs**
@dotnet/roslyn-compiler Please review a test only change.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review a test only change.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review a test only change.

**Comment by jcouv** [comment]
>     static void Main()

Not blocking this PR, but can `Main` be in an interface now?

---
Refers to: src/Compilers/CSharp/Test/Symbol/Symbols/DefaultInterfaceImplementationTests.cs:161 in 332c4ab. [](commit_id = 332c4ab7c5a05e471b712fe2f28a938092ff7c19, deletion_comment = False)

**Comment by AlekseyTs** [comment]
> can Main be in an interface now?

I believe LDM decided that it should be legal. You still need a class or a struct, though, in order to have an instance of an interface.

**Pull request merged**
