### PR TITLE
Fix IDE0028 in non compiler Projects

### PR DESCRIPTION
**Pull request by paul1956**
Done automatically using CodeFix

### CODE REVIEW

**Comment by sharwell** [comment]
I believe this is a discretionary rule, and not one that is enforced in CI. Typically pull requests of this form are only taken if the issue is discussed in advance, agreed on for style, and implemented as part of a complete plan to automate future enforcement.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by paul1956** [comment]
@sharwell I did discuss with @CyrusNajmabadi the plan was to clean up VB issues that did not touch Compiler layer and followed some other rules. I.e. Call out things I did manually since not all of this issues have automatic cleanup. Etc..
The list of approved projects is below provided they don't share code with Compiler.
https://files.gitter.im/5b42cb73d73408ce4fa01370/Q6q1/image.png

**Comment by sharwell** [comment]
@paul1956 it's fine to clean up those projects, but only for diagnostics that get reported during a build. The diagnostic which suggests the use of a collection initializer is not a style for this project. This policy is in place to avoid code churn caused if someone follows this change with an equally-valid pull request to revert it (both styles are equally acceptable, and neither is preferred).

**Comment by CyrusNajmabadi** [comment]
My preference would be to not take these. Primarily because I think this particular style does not sufficiently improve the code in the majority of cases I see here.

**Comment by paul1956** [comment]
@CyrusNajmabadi @sharwell I believe there are .editorConfig rules that would be applied to VB that would suppress these if it is not something you want to support fixing in the Repo.

**Pull request closed without merging**
