### PR TITLE
Remove language agnostic  ControlFlowGraphBuilder.ConvertibleConversion

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Review by mavasani — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@333fred, @cston, @dotnet/roslyn-compiler Please review

**Review by jaredpar — APPROVED** [review]
:shipit:

**Comment by AlekseyTs** [comment]
Test windows_debug_spanish_unit32_prtest please

**Comment by AlekseyTs** [comment]
Test windows_debug_vs-integration_prtest please

**Review by cston — APPROVED** [review]

**Pull request merged**
