### PR TITLE
Wiring the compiler `EmitOptions` through the workspace layer.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @dotnet/testimpact 

This replaces #8938 and retargets the changes against feature/test-impact.

### CODE REVIEW

**Comment by tannergooding** [comment]
Explicitly tagging @KevinH-MS, as this will likely ease the work on performing a 'fast path' build.

**Comment by KevinH-MS** [comment]
@ManishJayaswal @tannergooding is there an active issue tracking this?  I just realized that we need this to be functionally "complete" (although it doesn't adversely affect any known solutions).

**Comment by ManishJayaswal** [comment]
@tannergooding we should create one if it does not exist already. I am surprised that this does not impact any known solutions. Don't we set emit options in any of them?

**Comment by KevinH-MS** [comment]
Either we don't change EmitOptions from their defaults, or it doesn't affect the semantics of the tests (for the known solutions).

**Comment by tannergooding** [comment]
Yes we have an active issue tracking this (number 16). Most of the things that EmitOptions touch are not modified from their default values for the solutions we have tested so far (FileAlignment, HighEntropyVirtualAddressSpace, BaseAddress, etc).

The other important things, which are not part of EmitOptions, but are passed into the Emit command, are things like Resource Files, which I don't believe we have tested yet.

**Pull request closed without merging**
