### PR TITLE
Merge dev15-preview-4 into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15-preview-4 into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-dev15-preview-4-into-master20160810-150125
git reset --hard upstream/master
git merge upstream/dev15-preview-4
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-dev15-preview-4-into-master20160810-150125 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by balajikris** [comment]
@jasonmalinowski: So, this PR was just 2 commits before I merged manually to resolve conflicts. (Fix crash in symbolkeywriting was the only change). Now its 21 commits, (not 152 like the other day though). Could you please stop by, lets review this and merge this branch cleanly?

**Comment by balajikris** [comment]
thanks to @jasonmalinowski , we forced github to recompute their base commit for the PR. Now we're back to 3 commits and no file changes because the changes are already in master. We merge cleanly :v:

**Comment by balajikris** [comment]
No code changes here, just getting the commit history in. No need to wait for ETA or VSI tests. Merging.

**Pull request merged**
