### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git checkout merge-master-into-future20160114-175013
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160114-175013 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by davkean** [comment]
@TyOverby This linux failure could be caused by https://github.com/dotnet/roslyn/pull/7937
@agocke

**Comment by TyOverby** [comment]
Wouldn't the fix to #7937 already be plumbed through?

**Comment by TyOverby** [comment]
test prtest/lin/dbg/unit32 please

**Comment by TyOverby** [comment]
Tests pass; merging

**Pull request merged**
