### PR TITLE
Clean up RoslynPackage

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by balajikris** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/7343/
// Retest reason: ci-admin investigating the above infra failure

**Comment by CyrusNajmabadi** [comment]
retest  prtest/win/dbg/unit64  please

**Comment by CyrusNajmabadi** [comment]
test  prtest/win/dbg/unit64 please

**Comment by basoundr** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by basoundr** [comment]
@balajikris reason why roslyn_prtest_win_vsi3 is failing? We need this fix by today to fix our regressions

**Comment by balajikris** [comment]
CSharpSendToInteractive is failing. I have not seen this before, nor does this particular failure shows up in any bug query. Lets re-run this to see if its a legit break, If it passes, I'll open a separate investigation for that failure.

**Comment by balajikris** [comment]
@dotnet-bot retest vsip3 please
// previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_vsi3/120

**Comment by balajikris** [comment]
okay, it failed again, exactly the same way. At this point, I'd think this is a legit break that this PR will introduce if not addressed.

**Comment by CyrusNajmabadi** [comment]
This is a legit bug.

**Pull request closed without merging**
