### PR TITLE
Fix build break by adding missing parens to Vbc task

### PR DESCRIPTION
**Pull request by pharring**
@TyOverby @agocke @tannergooding

### CODE REVIEW

**Comment by pharring** [comment]
This is currently breaking our rolling perf runs.

**Comment by TyOverby** [comment]
LGTM.

Sorry about that breakage.  Is there any way that we could the continuous integration server to run that target?

**Comment by TyOverby** [comment]
@tannergooding: Can you point me to the bootstrap targets?  I want to make sure that this is fixed once and for all.

**Comment by pharring** [comment]
@TyOverby talk to @agocke about how we could test these targets.

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
