### PR TITLE
Attempt at implementing function pointer XML documentation support

### LINKED ISSUE #46674: Function pointers are not encoded into XML docs
**Version Used**: Latest public preview

**Steps to Reproduce**:

```cs
/// <summary>
/// Registers a callback for when this <see cref="GpuTask"/> completes
/// </summary>
/// <typeparam name="T">The type of the state to be passed to <paramref name="onFinished"/></typeparam>
/// <param name="state">The <typeparamref name="T"/> to pass to <paramref name="onFinished"/></param>
/// <param name="onFinished">The callback to invoke when this <see cref="GpuTask"/> finishes</param>
public void RegisterCallback<T>(T state, delegate*<T, void> onFinished) where T : class => _awaiter.RegisterCallback(state, onFinished);
```

1.  Have this code
2.  Build this code
3.  Try to use XML output from this code

**Expected Behavior**: Function pointers are encoded in the XML

**Actual Behavior**: Function pointers are not encoded in the metadata and simply vanish, e.g the XML output for above is
```xml
<member name="M:Voltium.Core.Memory.GpuTask.RegisterCallback``1(``0,)">
```

### PR DESCRIPTION
**Pull request by petarpetrovt**
Closes #46674

Not sure if this is correct I have no idea what I'm doing.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@petarpetrovt Please provide details on what exactly you are trying to accomplish. Is there a specification for XML doc comment format that explains how function pointers are supposed to be represented?

**Comment by petarpetrovt** [comment]
@AlekseyTs Wanted to help push forward with the issue but couldn't find any information about how it should be implemented. So I guessed how it should be, thats why i wrote:

> Not sure if this is correct I have no idea what I'm doing.

If there is any specification out there i will gladly rewrite the code.

**Comment by AlekseyTs** [comment]
I don't think we can review a PR if we don't know what exactly it is supposed to accomplish.

**Comment by saucecontrol** [comment]
Related: https://github.com/dotnet/roslyn/issues/48363

**Comment by 333fred** [comment]
I'm going to close this PR out. We need to work with the docfx team to make sure that we have an actual agreed-upon format for function pointer calling conventions before we can take a look at an implementation.

**Pull request closed without merging**
