### PR TITLE
Use simple package version string in legacy projects

### PR DESCRIPTION
**Pull request by jaredpar**
Infrastructure change

Even though the legacy project system supports the notion of PackageReference it does not support using MSBuild properties in the version element.  This is supported in NuGet and MSBuild but not during Visual Studio evaluation.  Changing roslyn to use simple version strings in that case.  

The automated conversion is a separate commit to make it easier to review the actual functional changes to the code base.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure, @sharwell

**Comment by jaredpar** [comment]
Giving myself a negative review until we figure out an auto-restore problem

**Comment by jaredpar** [comment]
DO NOT MERGE until we can figure out a restore problem.

**Comment by jaredpar** [comment]
> Thanks! Have you tested to see if this was the only issue preventing Test Explorer from working again?

Don't use test explorer hence hard to tell if everything is working.  It is loading tests again.  But given there are 65,000+ tests and it's so far only up to about 9,000.  All Run action are grayed out, presumably until it loads everything.  

Is this the expected behavior?

**Comment by sharwell** [comment]
> Is this the expected behavior?

I have come to expect this behavior. I manually unload all the test projects in the solution except the one containing the test(s) I'm working on. Then I use the **Class:ClassName** filter in Test Explorer to further limit results.

**Comment by jaredpar** [comment]
@sharwell 

> I have learned to expect this behavior.

Eventually it finished loading and I was able to run a test which passed.  So I can confirm this fixes that problem. 

Unfortunately it seems to cause other issues.  Looped you into an email to discuss options for going forward.

**Comment by jaredpar** [comment]
After thought I'm abandoning this approach in favor of moving fully to new project system.

**Pull request closed without merging**
