### PR TITLE
Adds Prerequisites to vsixmanifest templates

### PR DESCRIPTION
**Pull request by AlexEyler**
For Dev15, we're requiring that extension developers mark their extensions with Prerequisites. In order to support "F5"ing the Roslyn SDK projects in Dev15, the prerequisites have been added to the templates.

@jmarolf @Pilchie

### CODE REVIEW

**Comment by Pilchie** [comment]
test vsi please

Also tagging @dotnet/roslyn-ide for review.

**Comment by Pilchie** [comment]
@MattGertz - what do you think about this for RC?

**Comment by AlexEyler** [comment]
One interesting thing about this process is that these templates get uploaded to the gallery: https://visualstudiogallery.msdn.microsoft.com/2ddb7240-5249-4c8c-969e-5d05823bcb89. I'm not sure what the process would be for uploading it there, but AFAIK this doesn't get inserted back into the VS sources.

**Comment by MattGertz** [comment]
One hour from Escrow snap, and I don't understand the risks involved with this change.  @AlexEyler can you characterize that risk?  How does one test this?

**Comment by AlexEyler** [comment]
The risk is minimal - this will continue to work correctly on Dev14 as well as Dev15. The fix is necessary to be able to F5 a new "Analyzer" project in Dev15. We wanted this so that all of the extensibility projects underneath "Extensibility" will work in Dev15. The current scenario for these packages is that if they create a new Analyzer project and then hit F5, users will get a "you must declare prerequisites" error.

To test this, I downloaded the most recent version of the Roslyn SDK Templates and updated them vsixmanifest files to include the new prerequisites, then F5'd in Dev15 to verify that it launched correctly.

**Comment by MattGertz** [comment]
OK, let's front load it then.  Please get two code reviews, but otherwise this is good to go.

**Comment by DustinCampbell** [comment]
Rebasing to master, which is where RC3 ask mode is taking place.

**Comment by AlexEyler** [comment]
Before taking this, I think the Roslyn team changed the components between the time we created this PR and now. I'll submit an update to change the prerequisites (Microsoft.VisualStudio.Component.Roslyn.LanguageServices is the appropriate one now it seems).

**Comment by DustinCampbell** [comment]
> Before taking this, I think the Roslyn team changed the components between the time we created this PR and now. I'll submit an update to change the prerequisites (Microsoft.VisualStudio.Component.Roslyn.LanguageServices is the appropriate one now it seems).

@Pilchie seemed to think @jaredpar had done some of this work as well.

**Comment by AlexEyler** [comment]
@DustinCampbell okay - I've updated the PR just in case but I'll let you guys figure out what to do.

**Comment by Pilchie** [comment]
@jaredpar  added the initial "Prerequisites" section, but I think we still want to take this.  Pinging @jmarolf  to confirm that it's the right id, and @MattGertz for re-approval.

**Comment by Pilchie** [comment]
@MattGertz this is targeting master, which means by default it's going into RC.3 - confirming that that's okay with you?

**Comment by MattGertz** [comment]
Confirmed (I should have added the "Approved for RC.3" like I promised, but I forgot).

**Comment by jmarolf** [comment]
:+1: This should be merged in

**Comment by Pilchie** [comment]
Closing an re-opening for stale Jenkins jobs.

**Pull request merged**
