### PR TITLE
Merges/private dev15.7.x to dev15.7.x vs deps

### PR DESCRIPTION
**Pull request by AbhitejJohn**
This is a one-off merge pull request from dev15.7.x into dev15.7.x-vs-deps.

```
git fetch 
git checkout upstream/dev15.7.x-vs-deps
git checkout -b merges/private-dev15.7.x-to-dev15.7.x-vs-deps
git merge upstream/dev15.7.x
#Fix merge conflicts
git commit
git push merges/private-dev15.7.x-to-dev15.7.x-vs-deps --force
```

### CODE REVIEW

**Comment by AbhitejJohn** [comment]
Tagging @jasonmalinowski for review.

**Comment by jasonmalinowski** [comment]
@AbhitejJohn I broke dev15.7.x...let me fix that first.

**Comment by AbhitejJohn** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please.

**Comment by AbhitejJohn** [comment]
@jasonmalinowski , @TIHan:  Is this test failure from [here](https://ci.dot.net/job/dotnet_roslyn/job/dev15.7.x-vs-deps/job/windows_debug_unit64_prtest/80/) a known issue too?
Microsoft.CodeAnalysis.Editor.UnitTests.NavigationBar.NavigationBarControllerTests.TestDoNotRecomputeAfterFullRecompute [FAIL]

#21920 is the only trace I was able to find of this.
This is blocking me from pushing this change in.

**Comment by AbhitejJohn** [comment]
@dotnet-bot retest windows_debug_unit64_prtest  please.

**Comment by jasonmalinowski** [comment]
@AbhitejJohn I guess known, we saw that fail in a signed build I think too. Don't let that block.

**Comment by AbhitejJohn** [comment]
@jasonmalinowski : It looks like that test finally passed. Can I get approval on this please? (I cannot approve my own PRs :) )

**Pull request merged**
