### PR TITLE
Improve error reporting around lambdas and multiple overloads in VB

### LINKED ISSUE #2604: Improve error reporting around lambdas and multiple overloads in VB
Need to bring Roslyn's behavior closer to what the VS2012 compiler has.
Consider this code:
```
Module Module1

    Sub Main()
        M0(0, Function() doesntexist)
        M1(0, Function() doesntexist)
        M2(0, Function() doesntexist)
    End Sub

    Sub M0(x As Integer, y As System.Func(Of Integer))
    End Sub

    Sub M1(x As Integer, y As System.Func(Of Integer))
    End Sub

    Sub M1(x As Long, y As System.Func(Of Long))
    End Sub

    Sub M2(x As Integer, y As System.Func(Of Integer))
    End Sub

    Sub M2(x As c1, y As System.Func(Of Long))
    End Sub
End Module

Class c1
End Class
```

VS2012 compiler:
```
.vb(4) : error BC30451: 'doesntexist' is not declared. It may be inaccessible due to its protection level.

        M0(0, Function() doesntexist)
                         ~~~~~~~~~~~
.vb(5) : error BC30451: 'doesntexist' is not declared. It may be inaccessible due to its protection level.

        M1(0, Function() doesntexist)
                         ~~~~~~~~~~~
.vb(6) : error BC30451: 'doesntexist' is not declared. It may be inaccessible due to its protection level.

        M2(0, Function() doesntexist)
                         ~~~~~~~~~~~
```

Roslyn:
```
.vb(4) : error BC30451: 'doesntexist' is not declared. It may be inaccessible due to its protection level.

        M0(0, Function() doesntexist)
                         ~~~~~~~~~~~
.vb(5) : error BC30518: Overload resolution failed because no accessible 'M1' can be called with these arguments:
    'Public Sub M1(x As Integer, y As Func(Of Integer))': 'doesntexist' is not declared. It may be inaccessible due to its protection level.
    'Public Sub M1(x As Long, y As Func(Of Long))': 'doesntexist' is not declared. It may be inaccessible due to its protection level.

        M1(0, Function() doesntexist)
        ~~
.vb(6) : error BC30518: Overload resolution failed because no accessible 'M2' can be called with these arguments:
    'Public Sub M2(x As Integer, y As Func(Of Integer))': 'doesntexist' is not declared. It may be inaccessible due to its protection level.
    'Public Sub M2(x As c1, y As Func(Of Long))': Value of type 'Integer' cannot be converted to 'c1'.
    'Public Sub M2(x As c1, y As Func(Of Long))': 'doesntexist' is not declared. It may be inaccessible due to its protection level.

        M2(0, Function() doesntexist)
        ~~
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2604.

@VSadov, @gafter, @jaredpar Please review.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @gafter, @jaredpar Please review.

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
Ping. @gafter, @jaredpar, @agocke Please review. Need one more sign-off.

**Comment by AlekseyTs** [comment]
Ping. @gafter, @jaredpar, @agocke Please review. Need one more sign-off.

**Comment by jaredpar** [comment]
LGTM

**Pull request merged**
