### PR TITLE
Enable navigate-to to use OOP.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Actually, this is not ready for review.  @heejaechang informs me that OOP has a persistence service, but that it does not actually persist to disk.  That would be unacceptable for both NavigateTo and FAR.  @heejaechang should we file a bug on you to track that work?


Note: this is not an issue for AddNuget.  AddNuget does not use hte persistence service.  It controls persistence of the DB into the user/local directory.

**Comment by heejaechang** [comment]
@CyrusNajmabadi persistent service will save time on initial load and memory. without it, it will have same perf as user opening multiple VS as same solution.

so your choice. and yes. at some point, I need to take a look persistent service on OOP. right now, it is not highest priority.

**Comment by CyrusNajmabadi** [comment]
@heejaechang What is your schedule for upcoming work?  Do you have an idea about when the persistence service might be available?  Thanks!

**Comment by heejaechang** [comment]
@CyrusNajmabadi I will soon start working on that in post-dev15 branch.

**Pull request closed without merging**
