### PR TITLE
Merging master into features/embeddedJson

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv . Just keeping this branch up to date. Finally got through the unicorn. Thanks!

**Comment by CyrusNajmabadi** [comment]
Hrmm... i'm getting:

```
14:09:57 D:\j\workspace\perf_correctn---5f8d76d8>.\build\scripts\cibuild.cmd -testPerfCorrectness 
14:09:57 Repo Dir D:\j\workspace\perf_correctn---5f8d76d8
14:09:57 Binaries Dir D:\j\workspace\perf_correctn---5f8d76d8\Binaries
14:09:57 Unsupported argument -testPerfCorrectness
14:09:57 Usage: build.ps1
14:09:57   -release                 
```

@jaredpar @agocke  do you know what that's about?

**Comment by CyrusNajmabadi** [comment]
@tmeschter did you mean to merge into thsi branch?

**Comment by Neme12** [comment]
@CyrusNajmabadi I think the commits are updated live as master itself is updated.

**Comment by CyrusNajmabadi** [comment]
That is super cool.

**Comment by Neme12** [comment]
> did you mean to merge into thsi branch?

The branch you are merging from is master, so probably yes. I don't think there's any way to update this PR without updating master.

**Comment by CyrusNajmabadi** [comment]
@jcouv can you merge this quickly before anything else goes into master :)  It's really just a merge commit, so reviewwise, there's nothing much to so.

**Comment by Neme12** [comment]
retest perf_correctness_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Pull request merged**
