### PR TITLE
Tolerate snippets where Shortcut is null.

### PR DESCRIPTION
**Pull request by KirillOsenkov**
Simple null-check for snippet.Shortcut in preprocessor context check.

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph it is preview 3, so I need your approval?

**Comment by sharwell** [comment]
❓ Is this something we can add a test for?
❓ Is there an issue that led to this that we can link?

**Comment by jinujoseph** [comment]
@KirillOsenkov  could you pls add more context to the issue

**Comment by KirillOsenkov** [comment]
This is not a blocking or urgent issue. As far as I could see it is not user visible on Windows. But in other environments (VSMac) some snippets may have Shortcut set to null.

I'm OK with postponing it if you like, I just want to make sure this doesn't get lost long term.

**Comment by heejaechang** [comment]
@jinujoseph is there any reason this is now blocked and lost? can I check this in?

**Comment by jinujoseph** [comment]
@heejaechang , lets retarget 16.1.preview1 and merge or hold till we snap from master

**Pull request merged**
