### PR TITLE
Pass correct itemIDs to IVsSymbolicNavigationNotify

### PR DESCRIPTION
**Pull request by dpoeschl**
Partial fix for internal TFS bug #1169405

We previously always passed Nil for all itemidCodeFile parameters in IVsSymbolicNavigationNotify to ensure the XAML language service heard our request (because their current implementation only processes request for Nil or 0-valued itemids.) This caused Go To Definition and Find All References to be slower than necessary in non-XAML cases and also resulted in unwanted behaviors on certain properties that are referenced in XAML.

Our two options for fixing this were to either:
1. Update our implementation to send the correct item ids for heuristically "non-generated" files and send Nil for "generated" files (to match the Dev12 behavior)
2. Always send the actual item ids, even for "generated" files, and update the XAML language service to do a fast initial check of the corresponding document to see if they're interested in processing it.

This changeset represents the Roslyn half of option 2. Any builds that contain this fix but do not contain the corresponding change to the XAML language service will see no Go To Definition navigation to .xaml files (e.g. when navigating from a reference to a named Button) and no .xaml file entries in Find All References.

Unfortunately, this does not remove *all* heuristics from this algorithm, because Roslyn must still decide which itemid to pass in the case of a definition spanning multiple documents (e.g. the MainWindow class created in default WPF projects). We always prefer the "generated" documents to give external language services the best opportunity to participate.

This change also adds asserts to verify all itemID handling during Rename & Navigation happens on the UI thread.

### CODE REVIEW

**Comment by dpoeschl** [comment]
The https://github.com/dpoeschl/roslyn/commit/453655f734d12cf7e56dab93f27fe74ed407039e commit can be cherry-picked if needed.

**Comment by dpoeschl** [comment]
Potential reviewers: @Pilchie @jasonmalinowski @balajikris @brettfo @rchande @jmarolf

**Comment by dpoeschl** [comment]
The internal bug is going back to the xaml team for their side of the fix, so this part addresses the newly created #2994.

**Comment by Pilchie** [comment]
:+1:

**Comment by jmarolf** [comment]
:+1:

**Comment by dpoeschl** [comment]
Thanks for the reviews. I'll post an update & check in when I've validated the Roslyn changes work as expected with the XamlLanguageService change.

**Comment by dpoeschl** [comment]
Still working on testing out the combined changes.

**Comment by dpoeschl** [comment]
Changes tested manually, everything looks great. Will add an automated integration test as well.

**Comment by dpoeschl** [comment]
Shiproom Info:

**Bug Number**: Fixes #2994, which completes the customer bug from internal TFS bug #1169405, which was fixed by the xaml team.
**Customer scenario**: Navigation to properties can navigate to xaml if the property is referenced (not defined) in xaml. The other scenario is that of an extension author that wishes to intercept GTD or contribute entries to FAR -- we now always pass correct ItemIds, which will better allow any extension to quickly decide whether they are interested in participating.
**Fix description**: (above)
**Testing Done**: Created a test environment with the fix to with 1169405 and this proposed fix to #2994, where the CSharpWPF & BasicWPF integration tests still pass and the bug in 1169405 no longer reproduces.

**Comment by dpoeschl** [comment]
Note that this is targeting ```master``` -- I'll send out another one that targets ```stabilization```.

**Comment by dpoeschl** [comment]
Replacing this review with one that targets stabilization: https://github.com/dotnet/roslyn/pull/3227

**Pull request closed without merging**
