### PR TITLE
Remove flow-analysis feature flag for CFG APIs

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Review by gafter — APPROVED** [review]
:shipit:

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 1)

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by mavasani** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
This was approved for merging in the design meeting.

**Pull request merged**
