### PR TITLE
WIP: Target NetStandard 2.0 and .NET Framework 4.7.2 (vs-deps)

### LINKED ISSUE #18479: Scripting Tuples test has broken references between desktop/coreclr tests
On CoreCLR System.ValueTuple is in the runtime corlib, meaning that if System.ValueTuple is passed to the scripting compilation, compilations fail due to duplicate tuple types.

On the other hand, if the reference is removed, compilations fail on Desktop since the current corlib does not have System.ValueTuple.

### LINKED ISSUE #29292: Cleanup Microsoft.CodeAnalysis.Workspaces packages
We package Microsoft.CodeAnalysis.Workspaces and Microsoft.CodeAnalysis.Workspaces.Desktop in the same package, which is an unusal pattern that's not supported by NuGet Pack and needs a custom NuSpec file. Remove the custom NuSpec once we target netstandard2.0 and merge these two assemblies. 

When referencing Microsoft.CodeAnalysis.Workspaces.Desktop.csproj from other project that produce packages we need to do so with `PrivateAssets="all"` since the actual Microsoft.CodeAnalysis.Workspaces.Common package reference is added via reference to Microsoft.CodeAnalysis.Workspaces.csproj.

### PR DESCRIPTION
**Pull request by tmat**
Retargets Roslyn projects to netstandard2.0 and net472.

Moves most code from Workspaces.Desktop to Workspaces, except for MEF V1 implementation.
Removes dependencies on Workspaces.Desktop.
Removes Workspaces.Desktop from Micrososft.CodeAnalysis.Workspaces.Common package.

Removes PortableFacades.vsix.

Enables more scripting tests on Core.

Fixes #29292 (Cleanup Microsoft.CodeAnalysis.Workspaces packages)
Fixes #18479 (Scripting Tuples test has broken references between desktop/coreclr tests)

To be merged only after VS validation.

### CODE REVIEW

**Comment by jaredpar** [comment]
Is this the same PR as before but just retargeted?

**Comment by tmat** [comment]
The same retargeted

**Comment by jaredpar** [comment]
Is this WIP because you want to block accidental merge or because it's not ready for review? Once it's ready let me know and I can do another pass for sign off.

**Comment by tmat** [comment]
Not ready for review yet. Will be soon.

**Comment by tmat** [comment]
@jaredpar Ready for review.

**Comment by tmat** [comment]
test windows_debug_spanish_unit32_prtest  please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/roslyn/pull/30914

**Pull request closed without merging**
