### PR TITLE
Ensure IServiceBroker is used on a background thread

### PR DESCRIPTION
**Pull request by sharwell**
Expands #47903 to other calls to GetProxyAsync.

### CODE REVIEW

**Comment by sharwell** [comment]
@tmat @CyrusNajmabadi @jinujoseph roslyn-integration-CI caught this error in the OOP testing legs, but those legs have been disabled so no one saw it.

**Review by tmat — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@sharwell What's the background here as far as why this is necessary? Do we have a writeup for the team guidance here?

**Comment by sharwell** [comment]
@jasonmalinowski See #47903 for background. This is the same issue.

**Comment by jasonmalinowski** [comment]
@sharwell, I did, hence my request for an explanation. :smile:

**Comment by sharwell** [comment]
The official guidance is to follow the [three threading rules](https://github.com/microsoft/vs-threading/blob/master/doc/threading_rules.md). Code which does so will avoid runtime deadlocks. Roslyn intentionally does not follow these rules, opting instead to mitigate observed deadlocks on an as-needed basis using different strategies based on the type of thread dependency that led to the deadlock. The strategy employed here is the manual mitigation strategy for a UI thread dependency introduced by external code using `ConfigureAwait(true)` (explicitly or implicitly).

**Review by jasonmalinowski — APPROVED** [review]

**Pull request merged**
