### PR TITLE
Revert changes to PreReleaseOnlyPackages

### PR DESCRIPTION
**Pull request by cston**
Revert changes from bd23fe4fd3.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-infrastructure, @tmat, @shyamnamboodiripad please review.
@MattGertz for approval.

**Comment by cston** [comment]
The change re-enables publishing `Microsoft.CodeAnalysis.EditorFeatures.Text`, `Microsoft.VisualStudio.LanguageServices`, and `Microsoft.Net.Compilers` to myget.org and nuget.org.

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by tmat** [comment]
:+1:

**Comment by tmat** [comment]
:+1:

**Pull request merged**
