### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by bkoelman**
Addressed review comments for #3577.

### CODE REVIEW

**Comment by pharring** [comment]
:+1:

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by bkoelman** [comment]
@cston @VSadov @dpoeschl Does this pr look good to you?

**Comment by dpoeschl** [comment]
Yep, thanks for updating it. :+1:

**Comment by cston** [comment]
LGTM

**Pull request merged**
