### PR TITLE
Disable failing CSharpSendToInteractive Tests

### PR DESCRIPTION
**Pull request by dpoeschl**
Test failures documented in
https://github.com/dotnet/roslyn/issues/20868

### CODE REVIEW

**Comment by ivanbasov** [comment]
I am afraid that the fix would not help. 

>System.Runtime.Remoting.RemotingException : Failed to read from an IPC Port: The pipe has been ended.
means that Visual Studio is not running and its instance is not available. This happens when the previous test fails. So, if you disable those tests, next ones in the execution order will fail with the same reason. I think previous in execution order tests should be disabled/investigated.

**Comment by dpoeschl** [comment]
Yep, okay.

**Comment by dpoeschl** [comment]
@ivanbasov In this case the preceding tests were `ExecuteSingleLineSubmissionInInteractiveWhilePreservingReplSubmissionBuffer` and `AddAssemblyReferenceAndTypesToInteractive`, both still in `CSharpSendToInteractive`. Should we disable those? It's hard to tell whether they're to blame or the ones disabled in this PR are to blame (something could have gone wrong in the middle of a test, causing this failure during the same test, right?). Screenshots only show https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6315/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Screenshots/Unknown-ElementNotAvailableException-11.02.35.png and https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_vs-integration_prtest/6315/artifact/Binaries/Debug/UnitTests/VisualStudioIntegrationTests/xUnitResults/Screenshots/Unknown-ArgumentException-11.02.35.png as the last things that happened AFAICT, but those don't look like CSharpSendToInteractive to me. 

If any of this looks obviously related to your code, let me know. Otherwise I'll just try keep trying to figure it out.

**Comment by dpoeschl** [comment]
They keep failing. I'm considering disabling them all. I get IPC failures for them when I run them locally with no other surrounding tests, and Send To Interactive works normally on my machine, and other kinds of tests pass...

**Comment by ivanbasov** [comment]
Interesting. If you get IPC failures for them locally, please disable those tests. It would be pretty interesting to investigate them. It seems that something changed. Thank you, @dpoeschl !

**Comment by dpoeschl** [comment]
retest windows_release_unit32_prtest please

**Comment by dpoeschl** [comment]
@ivanbasov Local failure details:

```
System.Exception: 'Predicate never assigned a value after 10000 milliseconds and no exceptions were thrown. REPL text: > #reset
Resetting execution engine.
Loading context from 'CSharpInteractive.rsp'.
> using System;
> int j = 7;
.'
```

```
>	Microsoft.VisualStudio.IntegrationTest.Utilities.dll!Microsoft.VisualStudio.IntegrationTest.Utilities.OutOfProcess.InteractiveWindow_OutOfProc.WaitForLastReplInputContains(string outputText) Line 80	C#
 	Roslyn.VisualStudio.IntegrationTests.dll!Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ExecuteInInteractiveWithKeyboardShortcut() Line 198	C#
```

**Comment by ivanbasov** [comment]
Thank you, @dpoeschl ! I will take a look.

**Pull request merged**
