### PR TITLE
Compute and cache the 'Full Declaration' SyntaxReferences for a namespace symbol.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler for thoughts here.  We have a customer PR where we are seeing a ton of allocations of all the 'translation' syntax references for source namespace symbols.

I've gone with a two-pronged approach on helping making this property more efficient (and @mavasani is looking at what he can do to make the scenario not even call into this property as often).

The two things i'm doing are:

1. Having SingleNamespaceDeclarations point at both the SyntaxReference for their name, and hte SyntaxReference for their 'declaration'.  If these are the same, we reuse the same syntax-reference.
2. Lazily computing and caching the 'SyntaxReferences' immutable array for a MergedNamespaceDecl. That way, once we create it once, we can reuse as long as we're reusing htat same MergedNamespaceDecl.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
"System.Management.Automation.RuntimeException: Command failed to execute:  & $nuget restore -verbosity quiet -configfile $nugetConfig -MSBuildPath $msbuildDir -Project2ProjectTimeOut 1200 $filePath "

**Comment by jaredpar** [comment]
@CyrusNajmabadi can you link to the failed jobs in future comments?  Cataloging them.

**Comment by CyrusNajmabadi** [comment]
Done.

**Comment by jaredpar** [comment]
Thanks!

**Comment by sharwell** [comment]
@CyrusNajmabadi Can you quantify the impact of this change now that #19875 is merged?

**Comment by CyrusNajmabadi** [comment]
Closing in favor of https://github.com/dotnet/roslyn/pull/19875

**Pull request closed without merging**
