### PR TITLE
Target NetStandard 2.0 and .NET Framework 4.7.2

### LINKED ISSUE #18479: Scripting Tuples test has broken references between desktop/coreclr tests
On CoreCLR System.ValueTuple is in the runtime corlib, meaning that if System.ValueTuple is passed to the scripting compilation, compilations fail due to duplicate tuple types.

On the other hand, if the reference is removed, compilations fail on Desktop since the current corlib does not have System.ValueTuple.

### LINKED ISSUE #29292: Cleanup Microsoft.CodeAnalysis.Workspaces packages
We package Microsoft.CodeAnalysis.Workspaces and Microsoft.CodeAnalysis.Workspaces.Desktop in the same package, which is an unusal pattern that's not supported by NuGet Pack and needs a custom NuSpec file. Remove the custom NuSpec once we target netstandard2.0 and merge these two assemblies. 

When referencing Microsoft.CodeAnalysis.Workspaces.Desktop.csproj from other project that produce packages we need to do so with `PrivateAssets="all"` since the actual Microsoft.CodeAnalysis.Workspaces.Common package reference is added via reference to Microsoft.CodeAnalysis.Workspaces.csproj.

### PR DESCRIPTION
**Pull request by tmat**
Retargets Roslyn projects to netstandard2.0 and net472.

Moves most code from Workspaces.Desktop to Workspaces, except for MEF V1 implementation.
Removes dependencies on Workspaces.Desktop.
Removes Workspaces.Desktop from Micrososft.CodeAnalysis.Workspaces.Common package.

Removes PortableFacades.vsix.

Enables more scripting tests on Core.

Fixes #29292 (Cleanup Microsoft.CodeAnalysis.Workspaces packages)
Fixes #18479 (Scripting Tuples test has broken references between desktop/coreclr tests)

Implements IBC optimization data embedding.

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar

**Comment by agocke** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by filipw** [comment]
❤️@tmat ❤️

**Comment by CyrusNajmabadi** [comment]
Awesome! :)

**Comment by MarcosMeli** [comment]
Thanks !!!
I'm getting a ton of `Could not load file or assembly 'System.Runtime, Version=4.1.2.0` like errors in .net 4.7.2 because of the .net standard 1.3 I think.

There is a way to test these bits ? nightly build ?

**Pull request merged**
