### PR TITLE
Enable recommender for `scoped` keyword

### LINKED ISSUE #66305: `scoped` keyword not included in completion list
**Version Used**: 
Version 17.5.0 Preview 3.0 [33305.347.main]

**Steps to Reproduce**:

1. New Console App
2. Type `scoped` within `Main` method body

scoped-completion

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #66305.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
An actual test would be good. You can add one to csharpcompletioncommandhandlertests.  That's will help catch this sort of issue. Thanks!!

**Comment by jhinder** [comment]
@CyrusNajmabadi Thanks for pointing me in the right direction. Added a simple test.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
Same problem with automerge here

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
