### PR TITLE
avoid double-pop in an ignored conversion expression

### PR DESCRIPTION
**Pull request by TyOverby**
Closes https://github.com/dotnet/roslyn/issues/9703

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler 

Please review at your leisure.

**Comment by jcouv** [comment]
LGTM Thanks
Looks like C# doesn't have such a problem (except for case when conversion is unused and has no side-effects, the input to the conversion will be emitted as used).

**Comment by jaredpar** [comment]
Should we add an equivalent test for C#?

**Comment by jrmoreno1** [comment]
Not the one doing the review, but lines 164/171 are now effectively the same.  Would moving them both out of the conditional blocks not be better?

**Comment by TyOverby** [comment]
@jaredpar I've added a C# test for good measure.

@jrmoreno1 Good point.  Changed.

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
