### PR TITLE
Remove unneeded roslyn-build-tools

### PR DESCRIPTION
**Pull request by jaredpar**
Moved the packages on that feed to roslyn-tools.  Deleting the feed entry as we no longer need it now.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @tannergooding, @333fred, @TyOverby

**Comment by 333fred** [comment]
Provided the tests pass, :shipit:

**Comment by jasonmalinowski** [comment]
Due to NuGet caches on the build machines this can pass even if it breaks stuff, right?

**Comment by tannergooding** [comment]
@jasonmalinowski, correct. We would need to ensure these ran on a new machine (or passed locally after `nuget locals all -clear`, `git clean -xdf`, `cibuild.cmd`

**Comment by jaredpar** [comment]
@jasonmalinowski, @tannergooding not entirely true.  The microbuild test force cleans the caches.  That means it's a reasonable test that we don't have a caching issue.

https://github.com/dotnet/roslyn/blob/master/src/Tools/MicroBuild/cibuild.cmd#L5
https://github.com/dotnet/roslyn/blob/master/src/Tools/MicroBuild/Build.proj#L24

**Pull request merged**
