### PR TITLE
intentionally break test in order to test Jenkins

### PR DESCRIPTION
**Pull request by rchande**
cc @jasonmalinowski

### CODE REVIEW

**Comment by sharwell** [comment]
😆 That worked

**Comment by jasonmalinowski** [comment]
@jaredpar It looks like we have a test caching issue here. @rchande's change will have broken tests here, but for some reason all the results came back cached.

**Comment by jaredpar** [comment]
What test should that have broken?

**Comment by rchande** [comment]
@jaredpar `ShowGenericTypes3` in `ImplementsClauseCompletionProviderTests.vb`

**Comment by jaredpar** [comment]
@rchande what DLL is that in?

**Comment by rchande** [comment]
Roslyn.Services.Editor.VisualBasic.UnitTests.dll

**Comment by jaredpar** [comment]
Not a caching issue.  Here is the log on 64 bit runs

``` txt
11:41:04   Roslyn.Services.Editor.VisualBasic.UnitTests.dll.3                          PASSED 00:00:10.8890326  ?
11:41:04   Roslyn.Services.Editor.VisualBasic.UnitTests.dll.4                          PASSED 00:00:10.8930321  ?
11:41:04   Roslyn.Services.Editor.VisualBasic.UnitTests.dll.5                          PASSED 00:00:10.8949994  ?
11:41:04   Roslyn.Services.Editor.CSharp.UnitTests.dll.5                               PASSED 00:00:11.9973602  ?
11:41:04   Roslyn.Services.Editor.VisualBasic.UnitTests.dll.1                          PASSED 00:00:18.3282801  ?
11:41:04   Roslyn.Services.Editor.VisualBasic.UnitTests.dll.2                          PASSED 00:00:18.3322803  ?
```

Accourding to source.roslyn.io the test is skipped

**Comment by jasonmalinowski** [comment]
@rchande Ah, in your branch the test isn't skipped, but Jenkins will run against the merge with the skip.

**Comment by rchande** [comment]
Pretty sure I merged the unskipping of that test before creating this PR but closed/reopened to test it again.

**Comment by rchande** [comment]
(And also rebased on to the latest master)

**Comment by rchande** [comment]
@jaredpar @jasonmalinowski Tests are still marked as passing even after I unskipped that test.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by jasonmalinowski** [comment]
Woohoo, actual failures!

**Comment by jasonmalinowski** [comment]
(ah, boo, closing means people can't see it...that's silly)

**Comment by sharwell** [comment]
@jasonmalinowski How interesting. Also close/reopen triggers a complete rebuild.

**Comment by jasonmalinowski** [comment]
@sharwell Yes, that's the standard GitHub behavior.

**Pull request closed without merging**
