### PR TITLE
Remove code that doesn’t have any observable side-effects.

### LINKED ISSUE #13830: Untested code in out var implementation
The following code is untested in the implementation of the "out var" feature. No tests distinguish the presence of the code from its absence.

The call to `ReportIfUnused` in `DataFlowPass.cs` method `VisitUsingStatement`
The call to `ReportIfUnused` in `DataFlowPass.cs` method `VisitFixedStatement`

See https://github.com/dotnet/roslyn/commit/dd7bf9688b86363cd0bb331339eb546677ee4986 for the commit that added these.

I suspect that the code is a no-op (see #12225), and should probably be removed.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #13830.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by gafter** [comment]
>             foreach (LocalSymbol local in localsOpt)

There is an API `DeclareVariables` that declares a sequence of variables in an immutable array. We would add much less to the design debt if this loop were replaced by a call to that method. That is a correct transformation in this case.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs:1622 in 0b81b8e. [](commit_id = 0b81b8e4b360d40668cb631d6e32f18fd959487d, deletion_comment = False)

**Comment by gafter** [comment]
>             foreach (LocalSymbol local in node.Locals)

Similarly for this loop.

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs:1656 in 0b81b8e. [](commit_id = 0b81b8e4b360d40668cb631d6e32f18fd959487d, deletion_comment = False)

**Comment by gafter** [comment]
The changes here look good, but there are other opportunities to reduce recently introduced unnecessary complexity nearby. I'd appreciate if you could take this opportunity to simplify that code as well.

**Comment by AlekseyTs** [comment]
>             foreach (LocalSymbol local in localsOpt)

The logic in DeclareVariables doesn't look equivalent to me. 

---
In reply to: [248458447](https://github.com/dotnet/roslyn/pull/13935#issuecomment-248458447) [](ancestors = 248458447)

---
Refers to: src/Compilers/CSharp/Portable/FlowAnalysis/DataFlowPass.cs:1622 in 0b81b8e. [](commit_id = 0b81b8e4b360d40668cb631d6e32f18fd959487d, deletion_comment = False)

**Comment by AlekseyTs** [comment]
At a quick glance, the requested change doesn't look appropriate. At least, the code will not be doing the same thing. I will not be making it within this PR. 

---
In reply to: [248459037](https://github.com/dotnet/roslyn/pull/13935#issuecomment-248459037) [](ancestors = 248459037)

**Comment by gafter** [comment]
I guess it requires an understanding that it is always safe to allocate slots for variables, even if you won't need them.

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by VSadov** [comment]
LGTM

**Comment by agocke** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Thank you for review.

**Pull request merged**
