### PR TITLE
Initialize the error list toggle state when error list is initialized

### LINKED ISSUE #11539: Stale error list toggle state before a solution is opened
Currently, we initialize the error list toggle state only when workspace changes (solution add/remove/reload or project add/remove/reload) OR when FSD options change. However, if you start VS and bring up error list without opening any solution or changing FSD options, we might show stale error list state if your settings file or settings store changed from last VS session.

### PR DESCRIPTION
**Pull request by mavasani**
Currently, we initialize the error list toggle state only when workspace changes (solution add/remove/reload or project add/remove/reload) OR when FSD options change. However, if you start VS and bring up error list without opening any solution or changing FSD options, we might show stale error list state if your settings file or settings store changed after last VS session. Fix is to initialize the error list toggle state as soon as error list is initialized.

Fixes #11539

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @heejaechang @jasonmalinowski @basoundr @dotnet/roslyn-analysis for review

**Comment by mavasani** [comment]
test vsi please

**Comment by basoundr** [comment]
:+1:

**Comment by mavasani** [comment]
Tagging @MattGertz for ask mode approval.

**Comment by srivatsn** [comment]
👍

**Comment by heejaechang** [comment]
:+1:

**Comment by mavasani** [comment]
test vsi please

**Comment by mavasani** [comment]
@srivatsn @heejaechang @basoundr - I have pushed another commit to the PR that ensures we don't toggle the error list full analysis state for workspace changes. This change will address the current perf regression due to us turning on FSD for C# on close solution.

**Comment by mavasani** [comment]
All tests passed - can someone take another look? We need to insert this change to unblock RI.

**Comment by MattGertz** [comment]
Re-approval pending CRs.

**Comment by basoundr** [comment]
:+1:

**Pull request merged**
