### PR TITLE
Upgrade the version of dotnet-cli used in the mac/linux toolsets

### PR DESCRIPTION
**Pull request by agocke**
/cc @dotnet/roslyn-infrastructure @jcouv @jaredpar

### CODE REVIEW

**Comment by agocke** [comment]
FYI, most of this PR is invisible.

What I did was pull down the current toolset packages from azure and replaced the files in the dotnet-cli folder with new ones downloaded from https://github.com/dotnet/cli

**Comment by jasonmalinowski** [comment]
Does this implicitly fix #11017?

**Comment by jcouv** [comment]
LGTM
Does Jared's build ping service collect enough information so we should be able to tell that this is effective (let's say after letting it run in the wild for a day)?

**Comment by agocke** [comment]
@jasonmalinowski Yes.

**Comment by agocke** [comment]
test this please

**Comment by agocke** [comment]
test mac please

**Comment by agocke** [comment]
test linux please

**Pull request merged**
