### PR TITLE
Missed Nameof usage in Update SyntaxList`1.cs

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Utilise `nameof`

### CODE REVIEW

**Comment by gafter** [comment]
LGTM

@AlekseyTs Can you please check this?

**Comment by AlekseyTs** [comment]
LGTM

**Comment by AdamSpeight2008** [comment]
Just happened to spot this whilst I step through the code, so thought I put in an tiny PR for it.
Is it OK to put in small PR like this one? Should I spot others.

**Comment by AlekseyTs** [comment]
@AdamSpeight2008 Thanks for the contribution! The size of the PR is fine and submitting PRs for similar changes is fine too.

**Pull request merged**
