### PR TITLE
added more oop unit tests and some code refactoring

### PR DESCRIPTION
**Pull request by heejaechang**
added more oop unit tests and some code refactoring.

no functional change, just some refactoring to add more unit tests

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @panopticoncentral @srivatsn can you take a look?

**Comment by heejaechang** [comment]
@MattGertz can I get approval for RC3? no product change, most of changes are for adding new unit tests

**Comment by MattGertz** [comment]
Yes, RC.3 tests are tell mode so no problem.

**Comment by heejaechang** [comment]
known issue - https://github.com/dotnet/roslyn/issues/15225

**Comment by heejaechang** [comment]
retest windows_debug_unit64_prtest  please

**Pull request merged**
