### PR TITLE
update nuget packages for scripting to support netstandard1.3 instead…

### PR DESCRIPTION
**Pull request by jmarolf**
… of dotnet
Fixes last bit of https://github.com/dotnet/roslyn/issues/10749 
@tmat @dotnet/roslyn-interactive @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tmat** [comment]
👍

**Comment by jmarolf** [comment]
retest vsi please

**Comment by jmarolf** [comment]
test windows_vsi_dev15_p1_open_prtes please

**Comment by jmarolf** [comment]
test windows_vsi_dev15_p1_open_prtest please

**Comment by jmarolf** [comment]
BasicWinForms  failure is  https://github.com/dotnet/roslyn/issues/14833

**Pull request merged**
