### PR TITLE
Change test import ordering based on runtime globalization library

### PR DESCRIPTION
**Pull request by dibarbet**
https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#icu-on-windows
Windows 10 May 2019 update shipped a ICU for localization which dotnet core will use if present. This update corresponds to version 18362. Our helix machines are using a version prior to this update, so they are not using the windows ICU. The single machine runs are using a version after this windows update and so are using ICU.

The ordering for hiragana vs katakana is different in ICU vs the previous localization method (NLS). Additionally the ordering for half width characters is different. See https://github.com/dotnet/runtime/blob/main/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.cs#L100-L106

At some point last week the ADO ci machines updated to this new version of windows which uses ICU which caused the test run to fail. But helix is still on an older version of windows which does not include ICU, so it uses the old NLS method (with the reversed ordering).

The fix is to check the runtime globalization library and switch test behavior based on that.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
lol :D

**Comment by dibarbet** [comment]
coreclr SingleMachine (Fails with the original test code):

(ｱ, ア, IgnoreNonSpace | IgnoreWidth) = -1

(ｱ, ア, IgnoreWidth) = 0

(ｱ, ア, IgnoreCase | IgnoreWidth) = -1

(ｱ, ア, IgnoreCase) = 1

(ｱ, ア, IgnoreCase | IgnoreNonSpace | IgnoreWidth) = -1



(あ, ア, IgnoreNonSpace | IgnoreWidth) = -1

(あ, ア, IgnoreCase) = -1

(あ, ア, IgnoreWidth) = -1

(あ, ア, IgnoreCase | IgnoreWidth) = -1

(あ, ア, IgnoreCase | IgnoreNonSpace | IgnoreWidth) = -1



Runtime = 7.0.0, OS = Microsoft Windows NT 10.0.20348.0



Helix (passes with original test code)

(ｱ, ア, IgnoreNonSpace | IgnoreWidth) = 0

(ｱ, ア,IgnoreWidth) = 0

(ｱ, ア, IgnoreCase | IgnoreWidth) = 0

(ｱ, ア, IgnoreCase) = -1

(ｱ, ア, IgnoreCase | IgnoreNonSpace | IgnoreWidth) = 0



(あ, ア, IgnoreNonSpace | IgnoreWidth) = 1

(あ, ア, IgnoreCase) = 1

(あ, ア, IgnoreWidth) = 1

(あ, ア, IgnoreCase | IgnoreWidth) = 1

(あ, ア, IgnoreCase | IgnoreNonSpace | IgnoreWidth) = 1



Runtime = 7.0.0, OS = Microsoft Windows NT 10.0.14393.0

**Comment by dibarbet** [comment]
Some potentially relevant code
https://github.com/dotnet/runtime/blob/4e1ef1057e1bd248516b2a189a8d20239239480b/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.cs#L100-L106

**Comment by dibarbet** [comment]
My guess so far.
https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#icu-on-windows
Windows 10 May 2019 update shipped a ICU for localization which dotnet core will use if present.  This update corresponds to version 18362.  Our helix machines are using a version prior to this update, so they are not using the windows ICU.  The single machine runs are using a version after this windows update and so are using ICU.

The ordering for hiragana vs katakana is different in ICU vs the previous localization method (NLS).  Additionally the ordering for half width characters is different.  See https://github.com/dotnet/runtime/blob/main/src/libraries/System.Globalization/tests/CompareInfo/CompareInfoTests.cs#L100-L106

So my guess is at some point last week the ADO ci machines updated to this new version of windows which uses ICU which caused the test run to fail.  But helix is still on an older version of windows which does not include ICU, so it uses the old NLS method (with the reversed ordering)

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by dibarbet** [comment]
passed legs on single machine - https://dev.azure.com/dnceng-public/public/_build/results?buildId=9294&view=results

**Review by Cosifne — APPROVED** [review]

**Review by genlu — APPROVED** [review]

**Comment by JoeRobich** [comment]
We may want to consider back-porting this to servicing branches as necessary.

**Pull request merged**
