### PR TITLE
Have MsbuildWorkspace log all msbuild failures instead of throwing

### PR DESCRIPTION
**Pull request by mattwar**
This is a fix for #14581 

This change captures all exceptions produced by msbuild API and routes them into workspace failed events.  

I've also added a Diagnostics property on the MsbuildWorkspace which can be used to see all failure diagnostics that have occurred. 

@dotnet/roslyn-ide  please review

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> I've also added a Diagnostics property on the MsbuildWorkspace which can be used to see all failure diagnostics that have occurred.

Will these failures get propagated to the error list so people can see the issue?

**Comment by mattwar** [comment]
@CyrusNajmabadi Yes.. all workspace failure diagnostics will show up in the list.

**Comment by mattwar** [comment]
Anyone else want to review/comment?

**Comment by Pilchie** [comment]
@CyrusNajmabadi @mattwar `MSBuildWorkspace` is never used in VS, so no, these diagnostics will NOT show up in the error list.  It's up to the app that consumes `MSBuildWorkspace` to decide what to do with them.

**Comment by mattwar** [comment]
@Pilchie @CyrusNajmabadi I assumed Cyrus meant the diagnostic list I added to MSBuildWorkspace.

**Pull request merged**
