### PR TITLE
Handle DiscardDesignation syntax when comparing variable designations

### PR DESCRIPTION
**Pull request by tmat**
fixes  [link](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/664234 )

### CODE REVIEW

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Comment by tmat** [comment]
@tmeschter Any idea why loc validation is failing? There is no resource change in this PR.

**Comment by tmat** [comment]
test windows_loc_changes_prtest  please

**Comment by tmeschter** [comment]
@tmat I think you're running into Jenkins weirdness. `windows_loc_changes_prtest` isn't enabled for the `dev15.9.x` branch, but it _is_ enabled for `dev15.8.x`--and your PR originally targeted that branch. Re-running `windows_loc_changes_prtest` just re-runs the same check against the `dev15.8.x` branch.

You can safely ignore it.

**Pull request merged**
