### PR TITLE
Encapsulate field: copy documentation to property

### PR DESCRIPTION
**Pull request by rchande**
Fixes internal workitem 1123652.

Potential reviewers: @basoundr @balajikris @brettfo  @dpoeschl @jasonmalinowski @Pilchie

### CODE REVIEW

**Comment by Pilchie** [comment]
@mattwar Can you look at this and see if there is some better way that the trivia should be handled here?

**Comment by rchande** [comment]
ping @mattwar ?

**Comment by rchande** [comment]
ping @basoundr @balajikris @brettfo @dpoeschl @jasonmalinowski @Pilchie?

**Comment by mattwar** [comment]
The part about removing the doc comment looks okay. Replacing with elastic trivia is the right thing to trigger the formatter here.  However, the part about changing the accessibility (that you are not directly modifying in the PR) may have problems. In general, if you are going to manipulate and leading or trailing tokens from a node, then you should first remove all the leading and trailing trivia from it and add it back after the operation. The SyntaxGenerator API has the method WithAccessiblity you can use to change the accessibility and maintain the trivia correctly.

**Comment by rchande** [comment]
Use SyntaxGenerator.

**Pull request closed without merging**
