### PR TITLE
Update GUIDs of dependencies projects in tree.

### PR DESCRIPTION
**Pull request by davkean**
Samples.sln and Roslyn.sln were fighting over the GUIDs of Immutable, Metadata and Compostion.
Searched across the tree, and made sure that they were the uniform everywhere to prevent this.

### CODE REVIEW

**Comment by davkean** [comment]
tag @jasonmalinowski @tmat

**Comment by davkean** [comment]
This is the last GUID changes, I promise.

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6436/
// Retest reason: https://github.com/dotnet/roslyn/issues/10775

**Comment by tmat** [comment]
I guess it's good. :+1:

**Pull request merged**
