### PR TITLE
Reorder 'extract method' and 'introduce variable'

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/30475.

Telemetry shows us that ExtractMethod is used far more than IntroVar.  It's also a nice single item versus the 2-4 you can get with IntroVar. Reordering just makes things nicer and more efficient for users.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@sharwell @jcouv can you review this trivial change?  Thanks!

**Comment by CyrusNajmabadi** [comment]
@jcouv feel free to merge when you have a moment

**Comment by CyrusNajmabadi** [comment]
@sharwell a trivial change to review.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @dpoeschl small and easy PR to look at.  Thanks!

**Comment by sharwell** [comment]
Ack. This would throw me off on the primary case where I use Introduce Variable:

```
var value = [|x.y|].z;
```

The item I'd like to verify in telemetry is whether Extract Method is used more than Introduce Variable _in menus where both are present_. There are many cases where only the former is presented to the user, including what is likely the majority of Extract Method situations, so I want to make sure those cases aren't impacting the decision here.

**Comment by Neme12** [comment]
I use Introduce Variable way more often and would expect it to show up first too, but I can't argue against telemetry.

**Comment by CyrusNajmabadi** [comment]
@sharwell thanks.  let me know hte results of your telemetry spelunking.  Note, in the case where you still do want IV, it's only got one-additional item you need to go through.  This contrasts with the reverse case, where EM usage must go through 4 items to be selected.

So, all things being equal, this reordering seems more appropriate to me.  And, i'd still want it if the numbers were close (or even with IV being used a little bit more).  If, however, IV is picked vastly more often here, then we can keep things teh same way.

**Comment by kendrahavens** [comment]
@sharwell is correct! _In menus were there is more than 1 option_ Introduce Constant is much more popular than Extract Method. My perception was skewed before because I was including all the usages where Extract Method is the only menu option. (Sorry!) If you have any more ideas on how to cut the data let me know!

Based on this, I think we should keep the current ordering.

**Comment by sharwell** [comment]
Closing as Won't Fix based on the available telemetry.

**Pull request closed without merging**
