### PR TITLE
remove CodeLensArguement

### PR DESCRIPTION
**Pull request by heejaechang**
with JsonConverter support, we don't need a type just for marshaling anymore.

### CODE REVIEW

**Comment by heejaechang** [comment]
@panopticoncentral made code lens to use JsonConverter.

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

// extension installation failed.

**Comment by heejaechang** [comment]
retest windows_eta_open_prtest please

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by panopticoncentral** [comment]
:shipit:

**Comment by panopticoncentral** [comment]
Thanks for doing this!

**Pull request merged**
