### PR TITLE
Fix processing misaligned floats and doubles in BlobUtilities

### PR DESCRIPTION
**Pull request by marek-safar**
This is port of https://github.com/dotnet/corefx/commit/3849c6a0f374a3b67a92bccd564b1e83b356b27a fix

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler, @tmat

**Comment by tmat** [comment]
I don't think this file is actually used. Should be deleted.

**Comment by AlekseyTs** [comment]
> I don't think this file is actually used. Should be deleted.

+1

**Comment by jaredpar** [comment]
Closing in favor of #19169 where we just delete this file entirely.

**Pull request closed without merging**
