### PR TITLE
Revert "Update versions of VS packages we reference."

### PR DESCRIPTION
**Pull request by RikkiGibson**
Reverts dotnet/roslyn#46778 because it introduces a new RPS regression.

See the below insertions for more details. Note that both runs contain an approved set of regressions for @tmat: 11 instances of AdjustedImagesInMemory increasing.
"Last known good" run: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/267311
"First known bad" run: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/267597

Diff between the last known good and first known bad commits: https://github.com/dotnet/roslyn/compare/aa8b8e9de2e322833c5f35207127ff5f84cc33ab...6206d887c5c15fee5cb96bca47f7be3e3d005765

Feel free to seek an exception for the regression in parallel to this PR, or to submit your PR again to this branch at a later time when the regressions have been fixed or an exception is granted.

Tagging @CyrusNajmabadi @dotnet/roslyn-infrastructure.

### CODE REVIEW

**Comment by genlu** [comment]
This change is unlikely the cause for the regression, rerunning RPS with a newer baseline to confirm.

**Comment by CyrusNajmabadi** [comment]
So what is the way forward here?  This should just us referencing thew newer API surfaces for dlls that VS already ships with.  This is needed for LSP work so we can target the new apis that platform is shipping.

**Comment by RikkiGibson** [comment]
It sounds like our first resort will be to queue another insertion and see if the new regressions recur or not. If they do, then we get an exception based on Gen's triage indicating that the regressed metrics are actually in line with values from the recent builds.

**Comment by RikkiGibson** [comment]
This no longer appears to be necessary.

**Pull request closed without merging**
