### PR TITLE
Enable test scenarios now supported by CLR

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #46533.

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Comment by jaredpar** [comment]
Is there any more work to do on the feature side now or does this PR essentially complete it?

**Review by jaredpar — APPROVED** [review]

**Comment by AlekseyTs** [comment]
> Is there any more work to do on the feature side now or does this PR essentially complete it?

No more feature work. Once this PR is merged, I'll submit a PR to merge it to master.

**Comment by jaredpar** [comment]
Ah my mistake. I thought this was a PR into master. See now this is a PR into the feature branch. Got it.

**Comment by AlekseyTs** [comment]
It looks like we are still not targeting the required CoreCLR in our dev environment and CI.

**Pull request closed without merging**
