### PR TITLE
Fix typo in makefile

### PR DESCRIPTION
**Pull request by agocke**
Right now this may cause the cache not to be completely cleared.

### CODE REVIEW

**Comment by agocke** [comment]
Btw I think this could be the cause of some recent Linux/Mac failures (e.g. http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/2712/)

**Comment by jaredpar** [comment]
:+1:

**Comment by TyOverby** [comment]
LGTM

**Comment by TyOverby** [comment]
Quick question: it looks like BuildLogPath is never defined.  Is this intentional?

**Comment by agocke** [comment]
@TyOverby It doesn't seem to be defined, but I think it's fine as just an extension point

**Comment by agocke** [comment]
test  prtest/mac/dbg/unit32 please

**Pull request merged**
