### PR TITLE
Add documentation on localizing analyzers

### LINKED ISSUE #3542: Need documentation on localizing analyzers
This should include information on how to create localized resources, use of `LocalizableString`, and where to put satellite assemblies in both NuGet packages and VSIXes so that they will be picked up automatically.

### PR DESCRIPTION
**Pull request by tmeschter**
Add initial documentation on localizing analyzers. This includes the
following:

* Setting up a project to use localized resources
 * Using localized resources in Analyzers
 * Using localized resources in Code Fixes
* Producing localized resource assemblies
* Packaging resource assemblies in NuGet packages and VSIXes
* Testing the localization at the command line and in VS

Fixes #3542.

### CODE REVIEW

**Comment by tmeschter** [comment]
@srivatsn @ManishJayaswal @mavasani @AlekseyTs Please review.

@daking2014 @jepetty @zoepetard I'm going to start including you on some of my Roslyn pull requests so you can get a sense of how the process works when I'm not the one reviewing the code. ;-)

**Comment by tmeschter** [comment]
Note to reviewers: if you click over to the "Files Changed" tab there is a "View" button that will show the rendered document.

**Comment by sharwell** [comment]
> Note to reviewers: if you click over to the "Files Changed" tab there is a "View" button that will show the rendered document.

To the left of **View** is a button (no text) that shows a graphical diff for **.md** files. :+1: (In this case it's an added file so **View** is basically equivalent, but it's a handy button for other reviews.)

**Comment by AlekseyTs** [comment]
LGTM

**Comment by mavasani** [comment]
:+1:

**Pull request merged**
