### PR TITLE
turn off csharp full solution analysis.

### PR DESCRIPTION
**Pull request by heejaechang**
to support this, I added a way to set different default value per language

this is port of https://github.com/dotnet/roslyn/pull/10743 to microupdate branch.

### CODE REVIEW

**Comment by heejaechang** [comment]
this already got approval for microupdate from @MattGertz - see https://github.com/dotnet/roslyn/pull/10743

**Comment by heejaechang** [comment]
retesting not test issue. issue opened - https://github.com/dotnet/roslyn/issues/10761

**Comment by heejaechang** [comment]
retest prtest/win/dbg/unit64 please

**Comment by heejaechang** [comment]
retest  prtest/win/dbg/unit32  please

**Comment by heejaechang** [comment]
retest  prtest/lin/dbg/unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6423/
// Retest reason: issue opened, I think it is machine specific issue since unit32 which had same issue now passed the part it failed.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is Jenkins in broken state?

**Comment by jasonmalinowski** [comment]
@heejaechang, yes, things are broken. We're investigating.

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6428/
// Retest reason:

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/6444/
// Retest reason:

**Comment by heejaechang** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by srivatsn** [comment]
@jasonmalinowski is figuring out why the branch is broken. We are merging in this PR to produce signed binaries in the meantime.

**Pull request merged**
