### PR TITLE
remove error list 2

### PR DESCRIPTION
**Pull request by heejaechang**
IErrorList2 interface has been removed from shell API

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @tmeschter can you take a look?

**Comment by tmeschter** [comment]
LGTM

**Comment by heejaechang** [comment]
retest  linux_debug_prtest please

**Comment by heejaechang** [comment]
nuget restore failure

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure is Jenkins broken?

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by tmeschter** [comment]
retest this please

**Comment by tmeschter** [comment]
@heejaechang How about I roll this work into my change to move the build onto Dev15?

**Comment by heejaechang** [comment]
@tmeschter sure go ahead, I was oof yesterday. sorry about that. looks like I didn't remove one reference to one of the deleted method.

**Pull request closed without merging**
