### PR TITLE
batch asset synchronization on solution creation

### PR DESCRIPTION
**Pull request by heejaechang**
now we have a batch synchronization, we will use it for any solution creation on remote host

### CODE REVIEW

**Comment by heejaechang** [comment]
@panopticoncentral @CyrusNajmabadi @mavasani @srivatsn can you take a look?

**Comment by heejaechang** [comment]
since we have solution asset push on new solution/project, this, most of time, doesn't push much, but still it does batch push which is better than push things one by one.

**Comment by heejaechang** [comment]
adding @KevinH-MS

**Comment by CyrusNajmabadi** [comment]
I don't know what your title means.  can you explain what you're trying to do here?  Thanks!

**Comment by heejaechang** [comment]
we can either ask VS to get data one by one, or ask them to give back bunch of data at once.

I am making CreateSolution to ask all missing data at once.

**Comment by KevinH-MS** [comment]
I can't really comment on the implications of this, but seems like a reasonable change 👍

**Comment by CyrusNajmabadi** [comment]
what does "little weak on asset synchronization" mean?  sorry, i'm just not understanding hte title.

**Comment by heejaechang** [comment]
changed title

**Comment by panopticoncentral** [comment]
:shipit:

**Comment by CyrusNajmabadi** [comment]
👍

**Pull request merged**
