### PR TITLE
Fix Classification for #load...

### PR DESCRIPTION
**Pull request by KevinH-MS**
(and add missing classification test for ```#r```)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @brettfo @DustinCampbell ...

Going to fix up keyword recommender and completion next...

**Comment by brettfo** [comment]
:shipit:

**Comment by DustinCampbell** [comment]
:+1:

**Comment by KevinH-MS** [comment]
@dotnet-bot test this please

**Pull request merged**
