### PR TITLE
Fix #323 bug in SemanticModel.GetAwaitExpressionInfo when await expression used as an expression statement.

### LINKED ISSUE #323: [CodePlex] Bug in SemanticModel.GetAwaitExpressionInfo and expression lambdas
@erikkallen reported: in [http://roslyn.codeplex.com/workitem/400](http://roslyn.codeplex.com/workitem/400)
> The following program will output `FAILURE`, even though the program is valid and no diagnostics messages are reported (using 1.0-beta). It will also fail if the type of f is changed to `Action`. However, if the type of `f` is changed to `Func<Task<int>>`, there is no problem.

```cs
using System;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
namespace RoslynTest {
    class Program {
        static void Main(string[] args) {
            var syntaxTree = CSharpSyntaxTree.ParseText(@"
using System;
using System.Threading.Tasks;
public class C {
    public C() {
        Task<int> task = null;
        Func<Task> f = async() => await task;
    }
}");
            var compilation = CSharpCompilation.Create("Test", new[] { syntaxTree }, new[] { MetadataReference.CreateFromAssembly(typeof(object).Assembly), MetadataReference.CreateFromAssembly(typeof(Enumerable).Assembly) }, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
            foreach (var d in compilation.GetDiagnostics())
                Console.WriteLine(d.GetMessage());
            var semanticModel = compilation.GetSemanticModel(syntaxTree);
            var root = syntaxTree.GetRoot();
            var expr = root.DescendantNodes().OfType<ConstructorDeclarationSyntax>().First().Body.Statements.OfType<LocalDeclarationStatementSyntax>().ElementAt(1).Declaration.Variables[0].Initializer.Value;
            var awaitExpr = expr.DescendantNodes().OfType<AwaitExpressionSyntax>().Single();
            var awaitInfo = semanticModel.GetAwaitExpressionInfo(awaitExpr);
            if (awaitInfo.GetAwaiterMethod != null)
                Console.WriteLine("Everything was OK");
            else
                Console.WriteLine("FAILURE: GetAwaitExpressionInfo returned missing data even though the program is valid");
        }
    }
}
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #323

### CODE REVIEW

**Comment by gafter** [comment]
@AlekseyTs Could you please :+1: here?

**Comment by jaredpar** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@jaredpar ouch, I was going to squish the commit history before merging.

**Pull request merged**
