### PR TITLE
Use dotnet-bot instead of vslsnap GitHub account for GithubMergeTool

### PR DESCRIPTION
**Pull request by dsplaisted**
Fixes part of #14842

@dotnet/roslyn-infrastructure @jasonmalinowski @tannergooding

### CODE REVIEW

**Comment by dsplaisted** [comment]
I've updated this PR to also switch GitMergeBot to use Azure KeyVault and to use dotnet-bot instead of vslsnap.

**Comment by jasonmalinowski** [comment]
@agocke @brettfo If I recall this is the older one, but the one we're still using for F#, right?

**Comment by brettfo** [comment]
Correct, this is the older tool that only exists for F#.

**Comment by brettfo** [comment]
Also note that we'll have to update the script on the machine to stop pulling down the credentials since the tool now handles them internally.

**Comment by agocke** [comment]
I would just delete the GitHub support from the GitMergeBot. It shouldn't be used anywhere, so we should probably make it clear that it's not supported.

Regarding the run.csx file, I believe that file is outdated compared to what's in Azure. I would copy the latest off Azure, make your changes, then check in the new file. You may have to run it in the Azure Function portal if you can't get it to run in VS 2015, which is the only option I know of for running it locally.

**Comment by brettfo** [comment]
> I would just delete the GitHub support from the GitMergeBot.

We can't do this yet because the F# merges happen between GitHub and VSO.

**Pull request merged**
