### PR TITLE
Remove duplicate member symbol from EventReferenceExpression

### PR DESCRIPTION
**Pull request by genlu**
See https://github.com/dotnet/roslyn/pull/22243#discussion_r143185433

### CODE REVIEW

**Comment by genlu** [comment]
@AlekseyTs @cston @dotnet/analyzer-ioperation

**Comment by AlekseyTs** [comment]
>         public BaseFieldReferenceExpression(IFieldSymbol field, bool isDeclaration, ISymbol member, SemanticModel semanticModel, SyntaxNode syntax, ITypeSymbol type, Optional<object> constantValue, bool isImplicit) :

This looks like the same issue. Please fix it as well.

---
Refers to: src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs:1579 in c0d90b0. [](commit_id = c0d90b0c0bfdebf5d791b1aa0736ed27bfe00c6a, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         protected BasePropertyReferenceExpression(IPropertySymbol property, ISymbol member, SemanticModel semanticModel, SyntaxNode syntax, ITypeSymbol type, Optional<object> constantValue, bool isImplicit) :

This looks like the same issue.

---
Refers to: src/Compilers/Core/Portable/Generated/Operations.xml.Generated.cs:3835 in c0d90b0. [](commit_id = c0d90b0c0bfdebf5d791b1aa0736ed27bfe00c6a, deletion_comment = False)

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1). It looks like BasePropertyReferenceExpression and BaseFieldReferenceExpression have the same issue. Please fix them too.

**Comment by jinujoseph** [comment]
@genlu we are in Escrow ...so can you pls revert this change and create new one which we can take for escrow approval. I will get the VSO bug ready for this change

**Pull request merged**
