### PR TITLE
Remove debug assert that is causing some unit tests to be flaky.

### PR DESCRIPTION
**Pull request by heejaechang**
### Customer scenario

No user facing change. this is test only.

### Bugs this fixes

N/A

### Workarounds, if any

N/A

### Risk

N/A

### Performance impact

N/A

### Is this a regression from a previous update?

No

### Root cause analysis

Debug assert is causing some tests to be flaky.

### How was the bug found?

Unit test

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
FYI to @brettfo that we'll see a conflict in the inter-branch merges.

**Comment by heejaechang** [comment]
@jinujoseph do we need approval from shiproom for this? this doesn't affect product.

**Comment by jaredpar** [comment]
Infra only changes don't need shiproom approval.

**Comment by jinujoseph** [comment]
no it doesn't need shiproom approval. cc @MattGertz  for info

**Pull request merged**
