### PR TITLE
Merge pull request #28623 from amcasey/FilePath

### PR DESCRIPTION
**Pull request by amcasey**
Use FilePath in VisualStudioWorkspaceImpl.AddDocumentToProjectItems

(cherry picked from commit a9c960dad19ac7182be27b602061b9deb3e9e7a2)

### CODE REVIEW

**Comment by amcasey** [comment]
@jasonmalinowski I didn't you know you could retroactively change the base branch of a PR.  Should I be concerned that the summary at the top still says `dev15.9-preview2`?

**Comment by jasonmalinowski** [comment]
I had to switch it back; @brettfo it looks like the merge from dev15.9-preview2 to dev15.9.x hasn't happened recently. Do we need to take a look?

**Comment by jasonmalinowski** [comment]
@amcasey You can rebase this yourself with a "git rebase <remote name>/dev15.9-preview2 --onto <remote name>/dev15.9.x" and then click edit by the PR title and change it. Basically, me changing it is causing you to also bring along other commits that you shouldn't be (or at least not yet.)

**Comment by amcasey** [comment]
@jasonmalinowski Does that have any benefit compared to just creating a new PR?

**Comment by jasonmalinowski** [comment]
@amcasey Less confusing, but also review signoffs and comments are preserved.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by amcasey** [comment]
We've decided not to include the corresponding TS functionality in 15.9, so having it in master suffices.

**Pull request closed without merging**
