### PR TITLE
Remove obsolete publishing step

### PR DESCRIPTION
**Pull request by tmat**
This was only needed for legacy Maestro publishing.

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar @RikkiGibson

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
With this change do we need to maintain the channel information in the Publish-Data.json?

**Comment by tmat** [comment]
Good point. Will remove them.

**Comment by RikkiGibson** [comment]
Is there anything we should do to test this before merging?

**Review by RikkiGibson — APPROVED** [review]

**Comment by JoeRobich** [comment]
@tmat @RikkiGibson  Opened https://github.com/dotnet/roslyn/pull/51918 to remove channel publishing data.

**Comment by tmat** [comment]
@JoeRobich Is it ok to merge this then?

**Comment by JoeRobich** [comment]
@tmat Let's merge it!

**Pull request merged**
