### PR TITLE
	Remove comments when moving a type.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is a port from master

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz @ManishJayaswal @Pilchie

**Comment by CyrusNajmabadi** [comment]
Need approval @MattGertz @ManishJayaswal @Pilchie  thanks.

**Comment by ManishJayaswal** [comment]
@CyrusNajmabadi wasn't a PR approved yesterday for the same issue? It's hard to make sense from these port PRs which just have one line titles.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi wasn't a PR approved yesterday for the same issue?

No :)

>  It's hard to make sense from these port PRs which just have one line titles.

Sorry, i've just kept the title's around from the original PRs.  I can provide more detail if you want.  In this case, the issue is that when someone invokes 'move type' they might end up with duplicate comments on the disparate parts that are created in different files.

**Comment by MattGertz** [comment]
@CyrusNajmabadi What's the link to the original bug?  My GitHub-fu is poor.

**Comment by CyrusNajmabadi** [comment]
Here you go: https://github.com/dotnet/roslyn/pull/14562  :)

**Comment by ManishJayaswal** [comment]
@CyrusNajmabadi thanks! I had reviewed it yesterday but did not approve because I could not get all the information I needed. Now @MattGertz is back so he can approve it.

**Pull request merged**
