### PR TITLE
SRM, SCI update in 15.8

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
Because I'm manually inserting directly from this branch and want it to be as close to our normal insertion flow as possible.

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by tmat** [comment]
@jasonmalinowski Could you merge this please, disregarding integration test failures?

**Comment by jinujoseph** [comment]
cc @tannergooding

**Comment by tmat** [comment]
Integration tests are not expected to pass due to different version of SCI/SRM in the VS they are running on.

**Comment by tannergooding** [comment]
Merging.

Talked with @tmat. Tests are expected to fail due to us depending on a newer SCI version than what VS has installed.

Asked him to send a follow up PR disabling integration tests until the new image comes online (24-48 hours).

**Comment by marek-safar** [comment]
@tmat is there a preview with this change available?

**Comment by tmat** [comment]
Yes, `2.9.0-beta7-63029-02` packages have this change.

**Pull request merged**
