### PR TITLE
Merge dev15 preview 4 into master20160804 225700

### PR DESCRIPTION
**Pull request by heejaechang**
merging changes from preview 4 to master on OOP revert.

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@jasonmalinowski @jcouv can you take a look?

it doesnt have any actual file changes since I kept all files from master.

**Comment by jcouv** [comment]
0 changes, looks good

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest  please

known option page test failed

**Comment by jcouv** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/360/
// Retest reason:

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest  please

same test again.

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest please.

option page test is just keep failing.

**Comment by jcouv** [comment]
retest windows_vsi_p3_open_prtest please.

**Comment by jcouv** [comment]
retest windows_vsi_p3_open_prtest please.

**Comment by jcouv** [comment]
All green. Merged. Thanks Heejae.

**Pull request merged**
