### PR TITLE
Update references for public 17.0 Preview 4 release 

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Review by ryzngard — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
This is being coordinated with https://github.com/dotnet/roslyn/pull/56550?

**Comment by sharwell** [comment]
@jasonmalinowski No, this change is part of updating `main` to work with the new 17.0 Preview 4 CI. It's possible for `main-vs-deps` to adopt dependencies newer than Preview 4.

**Comment by jasonmalinowski** [comment]
@sharwell well even if it's going into both places, the changes aren't different that will create merge conflicts later for the infrastructure team?

**Comment by dibarbet** [comment]
@jasonmalinowski @sharwell I can just rebase my change on this once this merges to main-vs-deps.  Shouldn't be a problem as long as we get that merge in relatively quickly.  I only need the LSP package version update (which needs the new editor packages)

**Comment by JoeRobich** [comment]
@sharwell Integration tests are now passing on Preview 4.1. Not sure why the cla check isn't reporting. Let me know if you want this merged.

**Pull request merged**
