### PR TITLE
Add missing 'Fact' attribute to unit test

### PR DESCRIPTION
**Pull request by genlu**
@amcasey

### CODE REVIEW

**Comment by KevinH-MS** [comment]
Woops! :+1:

**Comment by amcasey** [comment]
:+1:

**Comment by amcasey** [comment]
I imagine you already know how to write an analyzer to detect this sort of thing. :)

**Comment by KevinH-MS** [comment]
FWIW, I don't think we can "know" the intent unless we also enforce that all test methods are public and all helpers are non-public.

**Comment by amcasey** [comment]
@KevinH-MS I think it would be reasonable to warn if you have a parameterless, public method in a type in which there's at least one ```Fact``` method.

**Comment by KevinH-MS** [comment]
I see--yeah, given that criteria, even an error seems reasonable.

**Comment by genlu** [comment]
@amcasey Considering the frequency of me making this mistake in merely 3 days, yeah, I'm gonna create one such analyzer :)

**Comment by KevinH-MS** [comment]
@genlu It'd be great if the analyzer also checked to make sure the class containing any methods with FactAttribute is marked public.  Most runners only look for exported types, so these tests will silently be ignored:
```
class Tests
{
    [Fact]
    void Test1()
    {
    }
}
```
(**BAD**)

```
public class Tests
{
    [Fact]
    void Test1()
    {
    }
}
```
(**GOOD**)

**Pull request merged**
