### PR TITLE
Use PowerShell directly in YML

### LINKED ISSUE #48117: Investigate using powershell directly in our YML files
Today in our YML files we use CMD files to just call into Powershell files. We should just consider using the Powershell task diectly and avoid these wasteful CMD files.

### PR DESCRIPTION
**Pull request by jaredpar**
closes #48117

### CODE REVIEW

**Comment by jaredpar** [comment]
Official build validation https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4126024&view=results

**Comment by jaredpar** [comment]
@dotnet/roslyn-infrastructure PTAL. I have run official build validation so we should be good there. 
@jepetty PTAL at the RichNav YML. The test build completed successfully

**Review by JoeRobich — APPROVED** [review]
LGTM!

**Review by jepetty — APPROVED** [review]
Fantastic! Thanks!

**Comment by tmat** [comment]
Unfortunately, this change made it hard to run ci build on dev box. Instead of running eng/cibuild.cmd I now need to find out what parameters to pass to build.ps1 :(
It also makes our repo different from others: https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#build-scripts

**Comment by jaredpar** [comment]
> Instead of running eng/cibuild.cmd I now need to find out what parameters to pass to build.ps1

This was always the case though depending on the scenario that you were digging into. Official build for instance has 20+ additional options on top of `cibuild.cmd`. That's the extreme case but most legs had a few options on top of it that you had to dig into the YML file to find and apply locally to fully replicate the builds. 

Overall though there were some other motivations for moving away from a "one size fits all" approach with cibuild.cmd in all of our legs:
 
- Mixing actions like `-restore` and `-build` into the same task makes it more difficult to investigate CI issues over a long time period. Still very easy for looking at an individual run but if u want to ask questions like "how has our restore time changed over last month" it becomes difficult to dig out of the data. As a separate task though it's pretty trivial. 
- Now that we are building and testing on different machines the types of builds we do are very different. The build for unit tests for example is very different than our correctness builds. The unit test builds are "build as fast as possible ignoring everything which isn't strictly necessary to run tests". In the near future that means I'm going to be disabling items like `-sign` and `-pack` on those jobs. There is no coverage loss here though because the correctness legs still strictly exercising all these options and verifying we work here. I will likely add a Unix correctness leg to ensure we maintain this across all OS. But it does mean that our builds are not uniform anymore because it strictly benefits our CI for them to not be. 

Note: I didn't mean for any of these changes to go in silently. I put a fairly detailed explanation the first part of these changes into #47249 and pinged the Infrastructure channel to make sure everyone was aware of the changes I was making. That PR was left in review mode for a week to give everyone time to digest. Sorry if this slipped past your radar here. 

If we wanted to bring back a cibuild.cmd to say "okay sure not every build is the same anymore but a decent chunk are so lets use cibuild.cmd for that" I wouldn't have an issue with that.

**Comment by tmat** [comment]
> Mixing actions like -restore and -build into the same task makes it more difficult to investigate CI issues over a long time period. Still very easy for looking at an individual run but if u want to ask questions like "how has our restore time changed over last month" it becomes difficult to dig out of the data. As a separate task though it's pretty trivial.

I'm not against this change. This has been discussed in past and seems like there are good reasons and benefits from splitting the build. I'd like to see it in the Arcade though rather then each repo doing their own thing.

I think you'll also want to update this line to change the binlog name based on whether you run with -restore only. Otherwise, the the log file will be overwritten.
https://github.com/dotnet/roslyn/blob/master/eng/build.ps1#L207

> This was always the case though depending on the scenario that you were digging into. 

Yes, it was the case if you wanted a specific flavor. At least basic run with some defaults worked. I think it would still be useful to have cibuild.cmd that has a single parameter that identifies the CI leg (using the display name, ideally). Or alternatively cibuild-{leg}.cmd file for each leg. So that one doesn't need to dig into various yaml files, which are different in each repo, and then look for how variables are set to figure out how to run CI build locally.

**Comment by tmat** [comment]
> Mixing actions like -restore and -build into the same task makes it more difficult to investigate CI issues over a long time period. 

One more thought on this - how do you determine what actions should be run as separate AzDO tasks and which should be within single task? E.g. you can argue that signing should be separate if you want to see how signing time has changed over time.

Seems like AzDO is really not very well designed in this aspect. Either you put more stuff into AzDO tasks, making your YAML more complicated and your build not runnable locally, or you put everything into one script that you can run locally but can't get AzDO telemetry out of - or can you? Aren't there AzDO commands (printed to the script output) that would allow you to answer your telemetry questions? So instead of merging/splitting build actions couldn't we just report AzDO telemetry from the build scripts?

**Comment by jaredpar** [comment]
> how do you determine what actions should be run as separate AzDO tasks and which should be within single task? E.g. you can argue that signing should be separate if you want to see how signing time has changed over time.

I made the determination based off of various investigations I've had to do over the past few years which required me to essentially analyze trends or flakiness across builds. The most notable areas where this occurs is restore, SDK acquisition and test duration. 

As for signing I've definitely seen that be a problem in official builds where the signing service has caused us enormous grief. I haven't personally had to track it down myself on non-official builds where we aren't hitting the service. If you think it's a source of problem though I can pull that out too. 

> Seems like AzDO is really not very well designed in this aspect. Either you put more stuff into AzDO tasks, making your YAML more complicated and your build not runnable locally, or you put everything into one script that you can run locally but can't get AzDO telemetry out of - or can you? 

Indeed this is a major tension point for AzDO (and looking forward GitHub Actions). Their unit of execution is tasks and that is where they primary reporting comes from. While we'd prefer to bundle everything up into a simple script and just execute one thing. 

> Aren't there AzDO commands (printed to the script output) that would allow you to answer your telemetry questions? So instead of merging/splitting build actions couldn't we report AzDO telemetry from the build scripts?

Yes and no. 

Yes: you can use logging detail commands to create mini records. Those are structured and appear in the timeline which means scripting data collection is pretty straight forward as it appears in the timeline data stream. T

No: this is basically completely invisible from the AzDO UI, it only appears at an API level. This means in order for developers to understand what is going wrong with their builds they actually have to sift through the build logs and look at the errors. Experience has shown that on the whole developers are not great at this. Where as when a task named "Restore" fails it's pretty obvious what went wrong here. 

> Yes, it was the case if you wanted a specific flavor. At least basic run with some defaults worked. I think it would still be useful to have cibuild.cmd that has a single parameter that identifies the CI leg (using the display name, ideally).

One tension point I found within our own infra is understanding where the responsibility lies to change defaults based on whether or not we are running in CI. The responsibility seems to be duplicated between cibuild.cmd, build.ps1 and arguably our YML in a few places. Feels like there should be one place that says "okay I'm in CI mode, let me set the defaults for CI".

**Comment by tmat** [comment]
>  The responsibility seems to be duplicated between cibuild.cmd, build.ps1 and arguably our YML in a few places. Feels like there should be one place that says "okay I'm in CI mode, let me set the defaults for CI".

Agreed - the original intent of cibuild.cmd was to set the defaults for CI and then invoke it from YML or locally.

**Comment by tmat** [comment]
>  this is basically completely invisible from the AzDO UI, it only appears at an API level.

Is this going to be better accessible in GitHub Actions? Perhaps we should provide feedback.

**Comment by jaredpar** [comment]
> Is this going to be better accessible in GitHub Actions? Perhaps we should provide feedback.

Can't say for sure as I'm still learning GitHub Actions here and how to map AzDO behavior over. My assumption though would be no though. They are still largely focused on getting to functional parity and this is more of a feature ask hence probably no. 

There is a dialog on-going with them though and I will insert this the next time we sync up with them. 

> Agreed - the original intent of cibuild.cmd was to set the defaults for CI and then invoke it from YML or locally.

Great. That makes the idea of having scripts, or even YML definitions, more approachable. Now that we have different types of builds the idea of flipping option defaults based on `-ci` makes our infra much harder. 

Been trying to think through the best way to put back a cibuild.ps1 style solution. There are essentially four different types of builds now: RichNav, Build for unit Tests, Build for Correctness (dev work flow) and Build for determinism. In your mental model here do you essentially so us having a ci build variant for each of these? For example `ci-build-unittests.ps1`, `cibuild.ps1`, `ci-build-richnav.sp1`, etc ...?

**Comment by tmat** [comment]
> For example ci-build-unittests.ps1, cibuild.ps1, ci-build-richnav.sp1, etc ...?

That was the intent - have a script for each leg. Originally, most repos had only one (main) leg so we just had one `eng\cibuild.cmd`.
We can either include the name of the leg in the name of the script or as a parameter. `eng\cibuild.cmd -leg:tests`, `eng\cibuild.cmd -leg:correctness`,  `eng\cibuild.cmd -leg:determinism`, etc. `eng\cibuild.cmd` for a default leg (could be correctness, e.g.). Parameter might be better as it reduces the number of files (we'd need .sh variants).

**Comment by jaredpar** [comment]
I think the leg idea sounds appealing here. Let me look into it.

**Pull request merged**
