### PR TITLE
Target net46 in all desktop projects

### PR DESCRIPTION
**Pull request by tmat**
Let's try this again... without breaking error list now.

### CODE REVIEW

**Comment by tmat** [comment]
@davkean @jasonmalinowski

**Comment by tmat** [comment]
image
;)

**Comment by davkean** [comment]
Lgtm

Sent from my Windows Phone
________________________________

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
retest vsi/p2 please

**Pull request merged**
