### PR TITLE
Assert unnecessary analyzers derive from AbstractBuiltInUnnecessaryCodeStyleDiagnosticAnalyzer

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes https://github.com/dotnet/roslyn/issues/62731

### CODE REVIEW

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@Youssef1313 Seems like there are real test failures

**Comment by Youssef1313** [comment]
Thanks for the ping @mavasani. Yes the inheritance here is wrong:

https://github.com/dotnet/roslyn/blob/acf27d9429b88dd26ae20c9d189fc26adda328d3/src/Analyzers/Core/Analyzers/SimplifyTypeNames/SimplifyTypeNamesDiagnosticAnalyzerBase.cs#L31-L32

This happened in https://github.com/dotnet/roslyn/pull/62869 when I changed the base type from `DiagnosticAnalyzer` to `AbstractBuiltInCodeStyleDiagnosticAnalyzer`

**Review by mavasani — APPROVED** [review]

**Pull request merged**
