### PR TITLE
Add support for yield return to CompleteStatementCommandHandler

### LINKED ISSUE #54709: CompleteStatementCommandHandler should work with yield return
**Version Used**: 

main

**Steps to Reproduce**:

```csharp
        private static IEnumerable<int> M()
        {
            yield return GetNumber($$)
        }

```

Type `;` in place of `$$`

**Expected Behavior**:

Complete statement works.

**Actual Behavior**:

It doesn't.

Fix is straightforward here:

https://github.com/dotnet/roslyn/blob/7e53c4612ad6778f277de5aa3e97beab1eb061f3/src/EditorFeatures/CSharp/CompleteStatement/CompleteStatementCommandHandler.cs#L330

### PR DESCRIPTION
**Pull request by meziantou**
Fix #54709

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]
Simple and to the point! Thanks.

**Review by Youssef1313 — APPROVED** [review]

**Review by sharwell — APPROVED** [review]

**Comment by meziantou** [comment]
The CI fails, so the PR cannot be merged. The failure doesn't seem related to my changes. Is there something I can do?

**Comment by CyrusNajmabadi** [comment]
@meziantou thanks for letting us know. I'm rerunning tests!

**Pull request merged**
