### PR TITLE
Preserve LookupResult methods in a BoundMethodGroup even if they are not viable.

### LINKED ISSUE #2544: FAR, GTD broken for inaccessible symbol
### Simplified repro added by @brettfo:
Find all references fails to find the inaccessible method D.M() when there are overloads.  Commenting out one of them, e.g., `//private void M(double d) { }` allows it to find the symbol.  This same scenario works in VB.

``` C#
class C
{
    private void M(D d)
    {
        d.[|M|](1);
    }
}

class D
{
    private void M(int i) { }
    private void M(double d) { }
}
```

Part of the issue appears to be that the call to [`model.GetSymbolInfoWorker()`](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Compilation/SyntaxTreeSemanticModel.cs#L173) results in a `SymbolInfo` with no bound symbol and no candidate symbols which ultimately leads to FAR and GTD failing.

Added a test for VB [here](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb#L870) and a skipped test for C# [here](https://github.com/dotnet/roslyn/blob/master/src/EditorFeatures/Test2/FindReferences/FindReferencesTests.OrdinaryMethodSymbols.vb#L895).

### Original repro by @tmat:
Repro: %internal_share%\public\tomat\Bugs\2544\Repro.zip
1) Unzip (contains Roslyn.sln with some changes). 
2) Open src\Tools\Source\MetadataVisualizer\Program.cs
3) Go to line 203:
```C#
_writer.WriteLine($"Method {visualizer.Literal(method.Name)} (0x{MetadataTokens.GetToken(methodHandle):X8})");
```

Literal is not accessible, but I should be able to go to its definition.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2544.

### CODE REVIEW

**Comment by tannergooding** [comment]
test this please

**Comment by AlekseyTs** [comment]
@gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

**Comment by AlekseyTs** [comment]
@dotnet-bot Test prtest/win/dbg/unit64 please.

**Comment by AlekseyTs** [comment]
Test unit64 please

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
LGTM

**Pull request merged**
