### PR TITLE
Add unit-tests to ensure that unterminated element in XML Doc comment doesn't cause compilation failure.

### PR DESCRIPTION
**Pull request by AlekseyTs**
@VSadov, @gafter, @agocke, @jaredpar Please review.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
@gafter, @agocke, @jaredpar Ping, please review.

**Comment by VSadov** [comment]
this looks like a test-only change.

**Pull request merged**
