### PR TITLE
Make method virtual.  Adding abstract methods is a breaking change.

### LINKED ISSUE #9050: SyntaxGenerator.OperatorDeclaration should be virtual
This type is `public` and `OperatorDeclaration` is a new member hence it cannot be `abstract`.  It must be changed to `virtual` to avoid breaking compat.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes #9050

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide again.  Sorry about the mixup.

**Comment by DustinCampbell** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
@MattGertz up for approval.

**Comment by MattGertz** [comment]
Approved.

**Pull request merged**
