### PR TITLE
Fix usage() in cibuild.sh

### PR DESCRIPTION
**Pull request by SirCmpwn**
You can't use a function before it's defined.

### CODE REVIEW

**Comment by SirCmpwn** [comment]
This seems to have failed the CI build but for reasons that don't appear to be relevant to the changes I've made.

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
@SirCmpwn LGTM

Yeah it looks like we had a Jenkins lab issue yesterday and it ended up affecting a large number of jobs.  I've scheduled this for retest.  Once it completes I'll merge this in.

**Comment by SirCmpwn** [comment]
Looks good.

**Comment by jaredpar** [comment]
Thanks for the contribution!

**Pull request merged**
