### PR TITLE
Reenable vbc coreclr bootstrap on Linux

### PR DESCRIPTION
**Pull request by agocke**
@davkean @tannergooding @amcasey @brettfo Please review

### CODE REVIEW

**Comment by davkean** [comment]
:+1:

**Comment by tannergooding** [comment]
:+1:

**Comment by agocke** [comment]
The deadlock we were previously seeing should have been fixed by #6171

**Comment by davkean** [comment]
The deadlock *should be* fixed, but make note we are seeing what appears to be another.

**Comment by agocke** [comment]
test win please

**Comment by davkean** [comment]
retest win please

**Comment by davkean** [comment]
retest windows please

**Comment by davkean** [comment]
retest prtest/win/dbg/unit32 please

**Comment by mmitche** [comment]
retest prtest/win/dbg/unit32 please

**Comment by mmitche** [comment]
retest prtest/win/dbg/unit32 please

**Comment by agocke** [comment]
test win/dbg/unit64 please

**Comment by agocke** [comment]
test prtest/win/dbg/unit64 please

**Pull request merged**
