### PR TITLE
Adding await keyword highlighting on async using & foreach

### PR DESCRIPTION
**Pull request by Neme12**
for #24037

### CODE REVIEW

**Comment by Neme12** [comment]
@jcouv

**Comment by Neme12** [comment]
I removed AwaitHighlighter first. I probably shouldn't do too much cleanup in this feature branch but if I didn't delete it, I would also have to create a separate highlighter for using & another one for foreach + test classes for both.

AwaitHighlighter is actually completely useless because the same thing is already done by AsyncMethodHighlighter. If I added 2 more highlighters for using & foreach, there would be 4 highlighters running on each async method doing the same exact thing.

**Comment by Neme12** [comment]
Or maybe I should do the cleanup properly in another PR first and get it into master? Does this branch get updated with master?

**Comment by jcouv** [comment]
@Neme12 Thanks a lot for such quick handling of this :-)
PR looks good.
I can update the `features/async-streams` (targeting 16.0) with bits from `master` (currently targeting 15.8) if you need it. I have not done it regularly yet. Let me know.

**Comment by Neme12** [comment]
@jcouv I don't need it. But the "cleanup" I did here (deleting `AwaitHighlighter`) is sort of half-baked and the `CombinedHighlighter` class is a hack so I could keep everything as-is in the tests without further changes.

If I were to implement this properly, the whole AwaitHighlighterTests class should be gone (because there's no more AwaitHighlighter) and the tests would be moved to appropriate places. but:
1. I don't think I should be doing so much cleanup in a feature branch. Should I?
2. I already have another PR related to async highlighting with some other cleanup in there too, though it should be unrelated. (I believe there would be no conflicts). Implementing this fix properly (and moving the tests to appropriate places) would really benefit from that other PR's improvements.
3. Should I do everything in that other PR? But then this PR would be stuck until that one gets merged *and* it would also have to get merged back to this feature branch, which could be inconvenient.
4. Leave everything as is? Maybe half-hacked disorganized tests are fine. For now.

**Comment by jcouv** [comment]
I think (4) is fine. Feel free to file a descriptive follow-up issue if there is some cleanup to do after the `features/async-streams` will be merged back to a mainstream branch (that will be at least a couple  of months).
If you can resolve the conflict, then this PR is ready to merge. Thanks

**Comment by Neme12** [comment]
@jcouv I think I would prefer to see if #26007 gets taken first and if it does, wait for it to get merged from master to this branch before merging this PR so that you wouldn't have any conflicts later. I hope you don't mind, is that OK?

**Comment by Neme12** [comment]
But if you'd like to just get this over with, I would understand so please tell me if that's the case and i can fix the conflict.

**Comment by jcouv** [comment]
That's ok too.
Marked the issue as Blocked and Private for now. Ping me when ready to move forward.

**Comment by Neme12** [comment]
@jcouv #26007 was merged so I can get this ready whenever you update this branch with master. Thanks

**Comment by jcouv** [comment]
Thanks, I'll go ahead and refresh the async-streams branch with bits from master.

**Comment by Neme12** [comment]
Please let me know when you do that.

**Comment by Neme12** [comment]
I see, it was done outside of a PR.

**Comment by Neme12** [comment]
@jcouv Everything is good now. Thanks.

**Comment by DustinCampbell** [comment]
Thanks @Neme12!

**Comment by Neme12** [comment]
retest windows_build_correctness_prtest please

**Comment by DustinCampbell** [comment]
@jcouv: I'll leave it to you to merge this since it's your feature branch.

**Comment by jcouv** [comment]
Nice, thanks! Merged. 

PS: Yes, I did update the async-streams branch without a PR. GitHub is giving us unicorns on trying to create PRs for large merges... :-(

**Comment by CyrusNajmabadi** [comment]
> GitHub is giving us unicorns on trying to create PRs for large merges... :-(

can you report this to github?  i'm getting the same thing for the embeddedRegex and embeddedJson branches.  I've already pinged them on this, but having more hits might help improve response time :)

**Comment by jcouv** [comment]
Yes, we should escalate to GitHub (if we haven't already). Tagging @jaredpar for that.

**Pull request merged**
