### PR TITLE
Plumb features option through MSBuild and Workspaces

### PR DESCRIPTION
**Pull request by jaredpar**
This change plumbs the features command line option through MSBuild and the Workspaces layer.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @khyperia, @agocke, @jasonmalinowski, @VSadov

**Comment by VSadov** [comment]
LGTM

**Comment by khyperia** [comment]
LGTM, minus test failures (I think there's still one left - `CommandLineTests.ParseFeatures`)

**Comment by mattwar** [comment]
This is all great except for the fact that is modifies/uses many files I remove in a different PR.

https://github.com/dotnet/roslyn/pull/3690

**Comment by jaredpar** [comment]
@mattwar do you want to try and get that merged today and I'll just sync up afterwards?

**Comment by tmat** [comment]
Could you also plum /checksumalgorithm thru?

**Pull request closed without merging**
