### PR TITLE
Parser diagnostics

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler 

This part of a long term effort to remove unnecessary errors from the parser and move them to later stages of the compiler pipeline.   Doing this makes the parser simpler, makes it faster to get a syntax tree, and makes our incremental implementation simpler (because the parser/incremental-parser needs to track less contextual states).

**Comment by CyrusNajmabadi** [comment]
Note: i have many more PRs other than this.  but i'd like to do things one at a time to make it really easy to review and do things a step at a time.

Tagging @gafter

**Comment by VSadov** [comment]
I agree on this particular change.
There is nothing wrong with parsing here. Also there is no advantage in checking for this warning at parse time either. - not any easier to check at parse time than at bind time, we still have to bind, etc...

**Comment by CyrusNajmabadi** [comment]
@VSadov 

> I agree on this particular change.

Is that an approval for this PR?  Thanks!

**Comment by VSadov** [comment]
Yes, LGTM, i was not sure if this is a part of a bigger change or which branch it goes into, if at all ...

**Comment by CyrusNajmabadi** [comment]
> if this is a part of a bigger change

I intend for this to be one of many changes (see https://github.com/dotnet/roslyn/pull/16091 for example).  But i'm going to take each one at a time.

> or which branch it goes into, if at all ...

I'm doing this all post-dev15.  It's just general cleanup/improvement (and helps out IDE reliability).  No need for this to go into RTM.

**Pull request merged**
