### PR TITLE
Fix issue preventing introduce-variable working on an expression being indexed into

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/28941

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv @dotnet/roslyn-ide

**Comment by mavasani** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
retest windows_release_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
@jinujoseph This is ready to go in.

**Comment by jinujoseph** [comment]
@mavasani  test failure  expected ?

**Comment by CyrusNajmabadi** [comment]
@mavasani this is failing: Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpAutomaticBraceCompletion.Negative_NoCompletionAfterPragmaPreprocesser 

I can't see how that could have been me. Can you merge when convenient?  Thanks!

**Comment by mavasani** [comment]
Yes, unrelated integration test failure.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by Tragetaschen** [comment]
Thanks!

**Pull request merged**
