### PR TITLE
Simplify reference manager code.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
retest perf_correctness_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p2_open_prtest please

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p2_open_prtest please

**Comment by tmeschter** [comment]
👍

**Pull request merged**
