### PR TITLE
Fix regression that caused us to not update hte builder text as the user typed.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Annoyingly, our tests mock out this component.  They validate that the component got the right data.  But they dont validate that VS displays it properly.  :(

**Comment by Pilchie** [comment]
So allow asserting an expected value for the mock?

**Comment by CyrusNajmabadi** [comment]
So the data being passed to the mock isn't changing.  It's literall the final "*VS* completion item" that we're creating for the UI.  We don't have anything that tests that.  And the current test framework operates at a level where those aren't even created.  

It's unclear to me why we do things htis way though.  i.e. why we use a TestCompletionPresenterSession instead of testing the actual "CompletionPresenterSession"

**Comment by CyrusNajmabadi** [comment]
Investigating
will see if we can just convert tests over to using this.

**Comment by CyrusNajmabadi** [comment]
@Pilchie I've  been trying to get a  better testing system in here.  But it's taking me down the rabbit hole.  Including running into some editor issues that i'm trying to work through.  Can we push this in and figure out a good testing story afterwards?

**Comment by Pilchie** [comment]
(I agreed to this in person).

**Pull request merged**
