### PR TITLE
Remove ignored flag

### PR DESCRIPTION
**Pull request by khyperia**
This is a follow-up to PR #21146, which was unable to be merged without
keeping this flag ignore.

### CODE REVIEW

**Comment by khyperia** [comment]
... well, tests are failing. I guess I made this PR too soon after merging the previous PR, and the netci.groovy wasn't re-run? Not sure how to fix that.

**Comment by jaredpar** [comment]
retest this please

**Comment by jaredpar** [comment]
The auto-trigger seems like it's still broken. I manually rebuilt the jobs. Should be taking effect now.

**Comment by jaredpar** [comment]
test mac please

**Comment by khyperia** [comment]
Well, mac doesn't look good. Didn't realize that was a testable thing before merging the previous PR.

**Comment by jaredpar** [comment]
I forgot as well. We don't test it by default because a) mac machines are a limited resource and b) linux is generally a great proxy for mac. Tend to forget about it beacuse it passes so reliably. When I logged in to manually kick off the rebuild of the jobs it reminded me we should test mac here.

**Comment by khyperia** [comment]
test mac please

**Comment by khyperia** [comment]
Seems like the Mac build hit a flaky build bug?

    The "GenerateDepsFile" task failed unexpectedly. [src/Scripting/CoreTestUtilities/ScriptingTestUtilities.csproj]
    System.IO.IOException: The process cannot access the file 'Binaries/Debug/Dlls/ScriptingTestUtilities/Microsoft.CodeAnalysis.Scripting.TestUtilities.deps.json' because it is being used by another process.

**Comment by khyperia** [comment]
retest mac please

**Comment by khyperia** [comment]
Never mind, seems to be a consistent failure. I'm not sure how to investigate why this is happening and fix it, advice would be appreciated. (I have no idea what I could have changed that could be causing it)

**Comment by khyperia** [comment]
test mac please

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_debug_unit32_prtest please

**Comment by dpoeschl** [comment]
@khyperia All green!

**Comment by khyperia** [comment]
Thanks @dpoeschl! :smile:

**Pull request merged**
