### PR TITLE
Use linked files for shared sources

### PR DESCRIPTION
**Pull request by jaredpar**
Our test utilities had a number of files that were duplicated in test utility projects.  Changed them to be linked files so we didn't have duplicate sources.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by cston** [comment]
Could the following be replaced by linked files as well?
```
src/Compilers/Test/Utilities/CSharp.Desktop/CSharpTrackingDiagnosticAnalyzer.cs
src/Compilers/Test/Utilities/CSharp.Desktop/DiagnosticTestUtilities.cs
src/Compilers/Test/Utilities/CSharp.Desktop/Extensions.cs
src/Compilers/Test/Utilities/CSharp.Desktop/MetadataTestHelpers.cs
src/Compilers/Test/Utilities/CSharp.Desktop/ScriptTestFixtures.cs
src/Compilers/Test/Utilities/CSharp.Desktop/SymbolUtilities.cs
src/Compilers/Test/Utilities/CSharp.Desktop/TestOptions.cs
src/Test/Utilities/Desktop/CompilerTraitAttribute.cs
```

**Comment by cston** [comment]
LGTM

**Comment by jaredpar** [comment]
@cston i don't believe so.  I actually wrote a program to look for duplicate content files in the code base (use MD5 for comparison) and linked all the ones it found.  None of those seem to be exactly the same.

**Comment by cston** [comment]
@jaredpar Most of those cases above have trivial differences.

**Comment by jaredpar** [comment]
@cston okay i will see if I can get those linked as well.

**Comment by jaredpar** [comment]
@cston processed all the files you listed and was able to link most of them.  The changes were minimal as you noted.

**Pull request merged**
