### PR TITLE
Update 'convert literal' refactoring to insert leading digit separator if supported

### PR DESCRIPTION
**Pull request by alrz**

### CODE REVIEW

**Comment by alrz** [comment]
@sharwell 

This is a new feature in C# 7.2 and VB 15.5, the refactoring has been updated to use it if available.

**Comment by alrz** [comment]
ping @CyrusNajmabadi

**Comment by sharwell** [comment]
> This is new in C# 7.2/VB 15.5, the refactoring has been updated to use it if available.

It's specifically the "use it if available" part that I was unsure of. It's allowed in 7.2, but it makes the refactoring more complex (has to check versions). To me it seems the same either way.

We should be able to get another review from @dotnet/roslyn-ide during the work week. :smile:

**Comment by DustinCampbell** [comment]
I agree with @sharwell that it's probably not a hard-and-fast rule that we must update the refactoring because the user *can* format their literals this way. This seems a stylistic choice to me and not necessarily something we want to recommend as part of the default experience. For example, *I* don't want this in my code, so I'd probably stop using the refactoring.

**Comment by Pilchie** [comment]
I'm with @DustinCampbell here.  I don't think we should insert the separator immediately after the base specifier in this refactoring by default.  I wonder if we even need an option, I don't expect many people want a separator there.

**Comment by alrz** [comment]
I don't have any data to back up my claim but I do think it's more likely that someone actually want this, otherwise people wouldn't have cared enough to write a proposal for this tiny change. If you look at it as a "bug fix" it's very likely that the refactoring would have been written without this exclusion in the first place. Anyways, I agree that a separate option is too much for this. Feel free to close if you disagree.

**Comment by Pilchie** [comment]
@kuhlenh can you make a style decision here?  If we convert literals to have digit separators, should it place one immediately after the base specifier (if in that position), or not:
E.g. -something like: `0b_0001_1000` or `0b0001_1000`

**Comment by kuhlenh** [comment]
It looks like in industry and in @Pilchie and @DustinCampbell's experience, the latter `0b0001_1000` is the convention. That said, happy to reverse this decision if we hear more feedback indicating that this `0b_0001_1000` format is a convention. 

@Pilchie when we do the different classification colors (https://github.com/dotnet/roslyn/issues/3976) we could consider italicizing the base specifiers, etc. to help make it more readable.

**Comment by sharwell** [comment]
Closing as the current behavior is by design.

**Pull request closed without merging**
