### PR TITLE
Add <serviceable>true</serviceable> and [assembly: AssemblyMetadata("Serviceable", "True")]

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@agocke, @vsadov, @tmat, @jasonmalinowski please review.
@mattgertz for approval.

**Comment by cston** [comment]
Fixes #11796.

**Comment by agocke** [comment]
It looks like we need a new build of NuGet that understands the new attribute. The changes LGTM, we'll just need the nuget team to point is to a suitable drop.

**Comment by MattGertz** [comment]
Approved pending the tests, and I'll send a note to Lee.

**Comment by MattGertz** [comment]
So, do we have access to 3.5.0-beta2-1430 for NuGet?

**Comment by jasonmalinowski** [comment]
Does this flag also need to be applied to our NuGet packages like Microsoft.VisualStudio.LanguageServices, or the command line compilers?

**Comment by MattGertz** [comment]
We only need this for our .NET Core deliverables.  It's harmless elsewhere as long as we are serviceable on that package via breadcrumbs, but not necessary.

**Comment by jasonmalinowski** [comment]
@MattGertz Does "our .NET Core deliverables" mean "core .NET Core deliverables", or "any library that can be consumed in .NET Core applications"? And if the former, how are we defining that boundary?

**Comment by MattGertz** [comment]
It means tools deliverables.

**Comment by agocke** [comment]
I've created a PR to fix up the ETA failure in: https://github.com/cston/roslyn/pull/1

**Comment by VSadov** [comment]
LGTM

**Comment by jasonmalinowski** [comment]
And :+1: from the IDE perspective that the workspace packages marked seem to be the correct ones marked.

**Pull request merged**
