### PR TITLE
Emit error types when EmitMetadataOnly and TolerateErrors

### PR DESCRIPTION
**Pull request by jcouv**
I've only prototyped it for C#.
There is an issue with nested types, since they need to come from a different assembly when emitted to metadata. So when they are loaded from metadata, they are top-level.
I have fixed the arity of the metadata symbol. Also the client no long produces diagnostics on such symbols.

The main thing to do at this point is test all the possible diagnostic scenarios.

A few things to do:
- How do we handle various errors that don't involve error types?
    - illegal overloads/overrides
    - duplicate method
    - un-implemented interface
- Add test with missing ValueTuple.
- I need to investigate what diagnostics should be produced in client (there should only be use-site diagnostics, if any. I'll look for ExtendedErrorTypes with unreported = true. Maybe this requires a different type than MissingMetadataSymbol.TopLevel on the receiving end)
- Implement VB counterpart and tests.
- Talk with IDE team.
- Fail compilation when syntax errors (or at least mismatching braces).
- Fail compilation if tolerate errors is not set, but an dependency is the error assembly.

Fixes https://github.com/dotnet/roslyn/issues/7482 and https://github.com/dotnet/roslyn/issues/20914

### CODE REVIEW

**Comment by jcouv** [comment]
@gafter I'll stop by tomorrow to discuss. Some information such as Arity and containing type get lost when roundtripping through metadata. I assume that is not critical.

**Comment by gafter** [comment]
Preserving `Arity` and containing type is important. Fer example, an error type representing `System.ValueTuple<T1,T2>` should still represent the twople type.

**Comment by CyrusNajmabadi** [comment]
> There is an issue with nested types, since they need to come from a different assembly when emitted to metadata.

Can you explain this bit a little more?

**Comment by CyrusNajmabadi** [comment]
It would be deeply interesting to see if we could relax this restriction:

> Fail compilation when syntax errors (or at least mismatching braces).

Or, at least, consider the following:

1. Always compile, regardless of syntax errors.  Whatever the parser thought the tree was is what we process.
2. Compile, ignoring method-body syntax errors.  Since we don't need the method bodies for declaration-emit why would we care about syntax errors inside?

**Comment by jcouv** [comment]
I haven't managed to push this PR forward. I recorded the status in the issue and am keeping my private branch, but I'll close the PR in the meanwhile.

**Pull request closed without merging**
