### PR TITLE
Add dependency on MinShell

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by brettfo** [comment]
:shipit:, assuming `microbuild_prtest` passes.

**Comment by jmarolf** [comment]
test windows_debug_unit32_prtest please

**Comment by jmarolf** [comment]
test microbuild_prtest please

**Comment by jmarolf** [comment]
test windows_release_unit64_prtest please

**Comment by jinujoseph** [comment]
👍

**Comment by jmarolf** [comment]
test windows_release_unit64_prtest please

**Pull request merged**
