### PR TITLE
Make InteractiveWindowPackage internal

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski

**Comment by jasonmalinowski** [comment]
:+1:. I think this needs to formally go through our Breaking Change Council, but I expect that be a formality.

**Comment by tmat** [comment]
@dotnet/roslyn-compat-council API breaking change. Making an InteractiveWindowPackage internal to avoid surfacing public APIs dependent on a specific VS version. The type should have been internal in the first place.

**Comment by tannergooding** [comment]
👍, I agree that this should have been internal in the first place.

**Comment by crummel** [comment]
Build triggered. sha1 is merged.

**Pull request merged**
