### PR TITLE
Add some extension methods to help work with AutomationElements

### PR DESCRIPTION
**Pull request by tmeschter**

### CODE REVIEW

**Comment by tmeschter** [comment]
@dotnet/roslyn-ide @dpoeschl Please review.

**Comment by CyrusNajmabadi** [comment]
👍 

Though isn't there existing code you can update to use htese?

**Comment by tmeschter** [comment]
@CyrusNajmabadi Yes, but I'm trying not to stomp on @dpoeschl's changes. I'll get them in another PR.

**Comment by tmeschter** [comment]
@dotnet-bot test linux_debug_prtest please

**Pull request merged**
