### PR TITLE
Disable API analysis if telemetry is disabled

### PR DESCRIPTION
**Pull request by sharwell**
Related to #41411

### CODE REVIEW

**Comment by mavasani** [comment]
@sharwell Just to confirm, you are seeing this incremental analyzer kick in only when FSA is enabled correct? Otherwise, given how expensive it is, I am wondering if we need to optimize it further.

**Comment by CyrusNajmabadi** [comment]
No problem with this change.  I have an open question about if we actually use this data in any way.  i.e. we collect it... and what do we then do with it?  If the answer is currently 'nothing', i would be thrilled to just rip it out entirely (as part of another change).

**Comment by mavasani** [comment]
> and what do we then do with it? 

I believe the telemetry analyzer was added to collect telemetry for partner teams. @jinujoseph might have context which team(s) uses this data.

**Comment by sharwell** [comment]
> you are seeing this incremental analyzer kick in only when FSA is enabled correct

I always have FSA enabled, but I'm not sure how they would be related.

**Comment by mavasani** [comment]
> I always have FSA enabled, but I'm not sure how they would be related.

Never mind, seems like the intent was to have this analyzer on by default for everyone to collect telemetry on the low-priority solution crawler queue. If not, the analyzer can check the current `BackgroundAnalysisScope` option value and bail out unless it is set to `EntireSolution`, but then we will collect telemetry only for users that have this option set. I think we should discuss with whichever partner team is using this telemetry whether this needs to be on by default or opt-in only for those who explicitly set `BackgroundAnalysisScope.EntireSolution`

**Comment by tmat** [comment]
There has been an email conversation with @DamianEdwards about this telemetry.

**Comment by mavasani** [comment]
Thanks. Even if we want it on by default, we should throttle it to run very limited number of times per solution, maybe just once when the solution is first loaded.

Any case, this seems like a classic case for offline analysis, not something that should run on user's CPU and compete with resources for functionality that is important to them @vatsalyaagrawal

**Pull request merged**
