### PR TITLE
Simplify the assert in BoundInterpolatedStringExpression

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Associated Issue #22869

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by gafter** [comment]
I believe the developer wrote it that way because it was easier for the developer to understand.

I don't see any motivation for changing it.

**Comment by jaredpar** [comment]
I agree with @gafter. I don't see any reason to change this.

**Comment by AdamSpeight2008** [comment]
@jaredpar Maybe also add response to the linked issue and close it?

**Pull request closed without merging**
