### PR TITLE
Remove special character handling in pattern matching.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide .  We don't need to special case @ inside the pattern matcher.  Because of work we've already done in the matcher to ignore and properly handle punctuation (for example: https://github.com/dotnet/roslyn/pull/18540), we don't need to to do anything special around @.  This is desirable as well as we want to move the pattern matcher down to the platform layer, and we don't want it to have special knowledge of languages like C#.

Tagging @grabalon as well.

**Comment by rchande** [comment]
What were we using `verbatimIdentifierPrefixIsWordCharacter` before? Are there any tests covering that scenario?

**Comment by CyrusNajmabadi** [comment]
> What were we using verbatimIdentifierPrefixIsWordCharacter for before? Are there any tests covering that scenario?

Basically, we had special knowledge in PatternMatching that @ was part of an identifier in C#.  So that a user coudl write "int" and have it match "@int" and also write "@int" and have it match "@int".  

But it turned out this wasn't necessary anymore due to work we did to appropriately match words even when surrounded by punctuation. 

We have many tests for this across completion and navigate-to.

**Comment by CyrusNajmabadi** [comment]
Tagging @ManishJayaswal 

This is part of the work we're doing to be able to move PatternMatching down to the platform layer.  We're making the API simpler, faster, and less C#/VB specific.  We're working with @grabalon on the editor team for this.  I'm generally proving the API changes work (using roslyn as the testbed), and he is then porting things down.

**Comment by CyrusNajmabadi** [comment]
@ManishJayaswal Please review.

**Comment by ManishJayaswal** [comment]
@MattGertz for approval

**Comment by CyrusNajmabadi** [comment]
Tagging @JoshVarty

**Pull request merged**
