### PR TITLE
Merge master into future20160317 150017

### PR DESCRIPTION
**Pull request by agocke**
/cc @heejaechang @dotnet/roslyn-infrastructure 

I've performed this merge

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
:+1: once all vsi tests are passed.

**Comment by heejaechang** [comment]
@agocke vsi is failing due to same reason. is there something need to be changed in internal side as well?

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
test vsi please

// close and open to get new open pointer

**Comment by heejaechang** [comment]
@agocke  still failing.

**Comment by agocke** [comment]
@heejaechang This is a cross-cutting change. It will fail VSI tests.

**Comment by agocke** [comment]
test prtest/win/dbg/unit32 please

**Comment by agocke** [comment]
The internal build passed, so these two PRs are ok to be merged, as long as they're merged together.

**Comment by agocke** [comment]
test vsi please

**Comment by agocke** [comment]
retest vsi please

**Pull request merged**
