### PR TITLE
Implement interactive assembly loader for CoreCLR

### PR DESCRIPTION
**Pull request by tmat**
Initial implementation w/o tests since we don't run CoreCLR tests yet. 

Fixes https://github.com/dotnet/roslyn/issues/3655

### CODE REVIEW

**Comment by tmat** [comment]
test eta please

**Comment by tmat** [comment]
test eta please

**Comment by tannergooding** [comment]
test eta please

**Comment by tannergooding** [comment]
@tmat, @jaredpar. I am rerunning the tests and taking the machine offline for further investigation (the previous results were overwritten by a new run).

**Comment by tannergooding** [comment]
test eta please

**Comment by tmat** [comment]
@tannergooding I'd really like to check this in.

**Comment by tmat** [comment]
test eta please

**Comment by tmat** [comment]
test eta please

**Pull request merged**
