### PR TITLE
LOC CHECKIN | dotnet/roslyn-master | 20171212

### PR DESCRIPTION
**Pull request by tmeschter**
Based on https://github.com/dotnet/roslyn/pull/23742, with further updates.

### CODE REVIEW

**Comment by tmeschter** [comment]
Didn't realize I could update #23742. I have done so, and will close this PR.

**Comment by tmeschter** [comment]
The source branch for #23742 disappeared before I could push the latest fix, so I've had to reopen this PR.

**Comment by tmeschter** [comment]
@jasonmalinowski Could you take a look at this? It's the same as #23742 but with the one broken unit test fixed up.

**Comment by jasonmalinowski** [comment]
@tmeschter Let's merge this!

**Pull request merged**
