### PR TITLE
Read Portable PDB directly in EEs instead of thru ISymUnmanagedReader

### LINKED ISSUE #702: [Portable PDB] Update the Expression Compiler to consume the portable PDB format
Phase 1: introduce an abstraction over the custom debug info.

### LINKED ISSUE #1985: [Portable PDB] Avoid dependencies on legacy PDB format in EE tests
Currently the tests are disabled. Search EE tests for the bug number.

### LINKED ISSUE #1989: [Portable PDB] Support TypeSpecs in MetadataDecoder.ResolveSignatureTypeHandleOrThrow

### LINKED ISSUE #7856: [Portable PDB] Expression evaluator doesn't pickup using statements when compiling using portable PDBs
Repro steps:
1. Install build of update 2 with core debugger support for portable PDBs (you will need to get this from me at the moment)
2. Write a little debuggee that uses Linq
3. Set a breakpoint and hit it
4. Attempt to evaluate a Linq statement in the immediate window

Result:
myKids.Where(x => x.Age == 8).First().Name
error CS1061: 'List<Person>' does not contain a definition for 'Where' and no extension method 'Where' accepting a first argument of type 'List<Person>' could be found (are you missing a using directive or an assembly reference?)

This works correctly if I use traditional PDBs

### PR DESCRIPTION
**Pull request by tmat**
We need to read at least CDI directly since the portable PDB bridge doesn't translate them to the legacy format. Since we are already special casing CDI we could very well read all the infomration directly and avoid a layer of translation.

Fixes #7856
Fixes #1989
Fixes #1985
Fixes #702

### CODE REVIEW

**Comment by tmat** [comment]
FYI: @dotnet/roslyn-interactive @cston I'll be adding commits refactoring EEs as needed for Portable PDB support in this PR. Feel free to wait with review until it's all done.

**Comment by tmat** [comment]
Ready for review.

**Comment by tmat** [comment]
I'll follow up with minor cleanup, adding a few targeted unit and fixing VB issues.

**Comment by tmat** [comment]
I'm gonna merge and implement feedback in a follow-up.

**Comment by KevinH-MS** [comment]
Can't seem to comment in diffs any more, but consider:  Should CompilationExtensions.GetModule now be called "GetModuleOrThrow"?

**Comment by amcasey** [comment]
I've reviewed as much as I'm likely to and I have no objections.

**Pull request merged**
