### PR TITLE
Move classification helper code so it will be usable by the new async find refs service.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/1474/
// Retest reason:

**Comment by balajikris** [comment]
465 files changed and it has compiler changes as well -- though its all removing unused usings as far as i could see.. just checking if its intended?.

**Comment by CyrusNajmabadi** [comment]
It was intended.  I also did a remove-unused using :)

**Comment by Pilchie** [comment]
This is not possible to review effectively.  The Remove Unused Usings should at least have been its own commit :(

**Pull request merged**
