### PR TITLE
Share code between the VB and C# Simplify-Type-Name providers

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/26823.  Reviewing prior to that going in is likely to cause excessive extra work.

There is an enormous amount of duplication between these two impls.  Removing it and following the standard IDE patterns for writing features in a cross language fashion.

When reviewed, i recommend going a commit at a time.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @sharwell @jcouv @mavasani

**Comment by sharwell** [comment]
Blocked on #26823

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jcouv @mavasani Can i get a review?  Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jcouv @mavasani Can i get a review? Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jcouv @mavasani Can i get a review? Thanks!

**Comment by jinujoseph** [comment]
test windows_debug_spanish_unit32_prtest

**Comment by jinujoseph** [comment]
test windows_release_vs-integration_prtest

**Pull request merged**
