### PR TITLE
Don't deploy extensions in Jenkins runs

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @Pilchie

**Comment by Pilchie** [comment]
Tag the rest of @dotnet/roslyn-infrastructure and especially @jasonmalinowski

**Comment by jaredpar** [comment]
retest eta please

**Comment by Pilchie** [comment]
Hmm - how confident are we that extensions are still getting installed for vsi runs before merging this?

**Comment by jaredpar** [comment]
@Pilchie VSI builds via RoslynBuildAndTest.  It doesn't use these scripts to build.

**Comment by Pilchie** [comment]
Great - and I verified that that already passes `DeployExtension:=false` when triggered by jenkins.

**Pull request merged**
