### PR TITLE
Format documents in Roslyn.sln

### PR DESCRIPTION
**Pull request by sharwell**
This extracts the automated portion of #31142 to a separate pull request and assigns @dotnet-bot as the author of the changes.
 
I ran two sanity checks after extracting/rebasing these changes from an earlier pull request:

1. Verified that after this change, formatting all documents only produced changes that are the subject of a bug handled separately/manually in #31142.
2. Verified that running a Format All Documents operation on Roslyn.sln *prior* to this change produces the same output (binary equal) as Format All Documents on Roslyn.sln *after* this change (i.e. the rebase did not introduce any merge-related artifacts).

### CODE REVIEW

**Comment by sharwell** [comment]
@jaredpar and @jinujoseph for approval

**Comment by sharwell** [comment]
Didn't get merged fast enough... have to rebase.

**Comment by sharwell** [comment]
Actually I'll wait for approval to merge, and _then_ I'll merge master into this pull request.

**Comment by jaredpar** [comment]
I approve this change.

**Pull request merged**
