### PR TITLE
Scanner(unification)

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Comment in scanner.vb `  ' REVIEW: Is there a better way to reuse this logic? `
This pull-request is that unification of the two methods internals into a single function.

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
@dotnet-bot test this please

**Comment by AdamSpeight2008** [comment]
@dotnet-bot test this please

**Comment by gafter** [comment]
Merge and test failed. Can you please fix it up and resubmit?

**Comment by AdamSpeight2008** [comment]
@dotnet-bot Please could you test this.

**Pull request closed without merging**
