### PR TITLE
Fix tests for paths with spaces

### PR DESCRIPTION
**Pull request by jeffanders**
Various aspects of the test projects construct paths and command line arguments for running various tests. Some of these simply don't worth if the relevant path environment variable contains a space (for example when the temp path contains a space as will typically happen when using a user account that has a space in the name). 

This included the main BuildAndTest.proj file not being able to run most tests at all due to command line arguments being interpreted incorrectly due to the presence of spaces in paths and lack of quoting around file paths. There was also one test that generated an rsp file for use with a test that was also outputing a path without appropriate quoting leading to the test failing.

Disclaimer, not all tests are passing for me due to issue #16998. However, I cloned roslyn/master and ran the tests under a user account that didn't have a space in the name/path and the set of test failures due to #16998 appeared identical. 

Would it be possible to also change the test infrastructure to always perform builds under paths  containing a space to ensure that in future and changes to tests that will break on systems with paths containing spaces will show up quickly.

### CODE REVIEW

**Comment by Pilchie** [comment]
@jaredpar Is this still relevant?

**Comment by jaredpar** [comment]
@Pilchie yes.  

Overall though have to decide if this is something we care about supporting.  If the answer is "yes" then I think we need to consider changing Jenkins to force a space into our enlistment.  That's the only way we're going to make this work correctly over the long haul.

**Comment by jeffanders** [comment]
I should mention that I later figured out that there are hundreds of tests still broken by paths with spaces (but for some reason my second account without a space in the name fails in the same way which I haven't looked into).  Particularly the command line tests are extremely broken (with some double quote inception required when passing a command line to cmd.exe with that command line itself having parameters with paths in them requiring their own quotes). I am slowly working my way through all the broken tests when I have time.  

So to be clear, this pull request simply fixes the tests so they actually run (whereas before the entire test process would abort without attempting to run tests at all) and can now actually report test failures so they can be fixed.

Given it is unclear whether supporting spaces in paths for tests is something to be pursued should I continue with fixing these tests to work with paths with spaces (as that will end up being a fairly substantial pull request touching many many tests)? My concern is I could fix all of these, have the pull request merged and then find new tests are added that are not compatible with paths with spaces.

**Comment by jeffanders** [comment]
@jaredpar @Pilchie I have worked through all of the tests that were breaking as a result of spaces in paths and fixed them all except for a couple of determinism tests. However, I have reviewed those 2 tests and it makes sense that those tests are failing. I am not sure how they succeed for anyone. The 2 tests are from the VBCSCompilerTests\EndToEndDeterminismTest tests and are the LineDirective and CallerInfo tests. Both of those tests make use of caller attributes and in particular the problem relates to the use of `CallerFilePathAttribute`. The issue is that this causes the absolute path to the source file to be passed as a parameter (and the path is encoded as a literal in the generated assembly) but the tests run two passes to generate assemblies for comparison and always use different paths for the temporary files and therefore the assemblies differ due to the different paths in the string literals. 

In particular the tests use `RunDeterministicTest` which calls `CompileAndGetBytes` twice where each invocation calls `Temp.CreateDirectory()` and places the temporary source files in those locations. But `Temp.CreateDirectory()` ultimately creates a directory based on a `Guid.NewGuid()` and therefore is really not very deterministic. So I am at a loss to figure out how this test works for anyone.

A solution would be to be able to alter `CompileAndGetBytes` to be passed a directory to run the test in and the caller (at this stage only `RunDeterministicTest`) can "clean" the directory between invocations so the second test can be run in the same path to ensure `CallerFilePathAttribute` works the same for both invocations. However, I don't want to proceed with such a change without understanding why these tests are not failing for everyone else in case I am missing something blindingly obvious.

**Comment by CyrusNajmabadi** [comment]
@jeffanders How do those tests work today, in the absence of spaces in paths?

**Comment by jeffanders** [comment]
@CyrusNajmabadi It was a little difficult for me test independently as my user account has spaces in it, but since the problem with the tests is the dependancy on your temp path I simply changed my temp path to a path without spaces and the tests were still failing. I identified that my changes were causing that failure. However that appeared to be due to some inconsistencies with various command line arguments.

Upon digging into these particular tests I realised an important factor in the tests is the use of the `pathmap` command line argument. This is fairly new and as of yet undocumented option (see #18071 and dotnet/docs#1800). It became more obvious to me that the main purpose of pathmap is to remap paths of source files for the benefit of deterministic builds that use CallerFilePathAttribute. 

The general format of the pathmap command line option is:
/pathmap:path1=pathA,path2=pathB etc

I had originally tried quoting the paths for pathmap like so `/pathmap:"{0}=/"` which was not working so I tried `/pathmap:"{0}"=/` which also didn't work. In the end the solution was I needed to quote the entire pathmap option like so `"/pathmap:{0}=/"`. This was surprising to me. 

It seems that `ParsePathMap` is inconsistent with other command line options that take a comma separated list of files or paths. For example the `link` and `reference` command line options make use of `ParseAssemblyReferences` which gives the following examples in comments within that method:
``` C#
// /r:"reference"
// /r:alias=reference
// /r:alias="reference"

```
The MSDN documentation for the `link` option (https://msdn.microsoft.com/en-us/library/dd264728.aspx) explicitly states "If the file name contains a space, enclose the name in quotation marks".

So there is definitely some inconsistency regarding the parsing of pathMaps and existing command line arguments that have similar structure. I have fixed my tests to work around this but should I open an issue regarding the inconsistency of `pathMap` parsing vs `link`/`reference` command line options?

I would be happy to maybe work on making `ParsePathMap` more consistent with `ParseAssemblyReferences` with respect to quoting file names/paths if that is something that needs to be done.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest this please.

**Comment by AdamSpeight2008** [comment]
Doing a new set of test, as the data on the failure isn't available to me. As my fix (which incorporates the unittest work do by @jeffanders ) As only one test partition that is currently failing.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by jasonmalinowski** [comment]
Hmm, wasn't aware this PR was out, but I'm all for taking it (at least in principle.)

@jaredpar I'd be OK adding a space to Jenkins runs as a forcing function to dogfood our own stuff in this scenario before a bug creeps in. Obviously we have to get safe in this situation first.

**Comment by AdamSpeight2008** [comment]
@jasonmalinowski There an alternative PR as well. which includes this.

**Comment by jasonmalinowski** [comment]
@AdamSpeight2008 Ah your bug didn't link to the new one. Got it.

**Comment by jeffanders** [comment]
Thanks @AdamSpeight2008 and @jasonmalinowski for kicking this along the road. It is great to see this being progressed as it had caused me quite a bit of pain and took me a while to get all the tests working with spaces. It will be great to see this merged in some form as it is my first pull request for Roslyn :grinning:.

I also opened issue #19829 regarding the pathMap command line option inconsistency so that issue can be considered separately from this pull request.

**Comment by CyrusNajmabadi** [comment]
This has diverged significantly from our existing sources, and hasn't gotten any movement in 5 years.  Closing out for now.

**Pull request closed without merging**
