### PR TITLE
Roslyn command handler migration mop-up changes

### PR DESCRIPTION
**Pull request by olegtk**
### Customer scenario

Mostly not a customer affecting changes, except improved localized command handler names (which will be used by the editor in typing diagnostics).
Partner impacting scenario: Roslyn is still using deprecated in 15.6 CommandExecutionContext.WaitContext property, which blocks editor from removing it in 15.7.

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/24810

### Workarounds, if any

N/A

### Risk

Low

### Performance impact

No

### Is this a regression from a previous update?

No

### Root cause analysis

These are follow up changes to address "[mop-up in Preview 4]" comments in https://github.com/dotnet/roslyn/pull/23769.

### How was the bug found?

Code Review of https://github.com/dotnet/roslyn/pull/23769

### Overview of the fix

These are follow up changes to address "[mop-up in Preview 4]" comments in https://github.com/dotnet/roslyn/pull/23769

1. Migrate to editor 15.6.281-preview bits (which are inserted into lab/d15.6stg on 1/23/2018, targeting  15.6 Preview4, see https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/102783).
2. CommandExecutionContext.WaitContext is deprecated in favor of OperationContext
3. Convert couple simple command handlers to simpler ICommandHandler interface
4. Simplify command handler display names (get rid of "Command Handler" suffix). That allowed to delete some strings in favor of pre-existing.

### CODE REVIEW

**Comment by olegtk** [comment]
why I end up with 100+ files PR even with a simple mop-up?   ```¯\_(ツ)_/¯```

**Comment by tmat** [comment]
@olegtk 'Cause you're touching resources ;)

**Comment by olegtk** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

**Comment by jasonmalinowski** [comment]
@olegtk This probably needs to target 15.7 now? Too bad it got lost in all the noise.

**Comment by olegtk** [comment]
Oh, right. I will retarget it tomorrow, @jasonmalinowski.

**Comment by olegtk** [comment]
@jinujoseph, @jasonmalinowski I retargeted this one to dev15.7.x-vs-deps, can we take it now? We would need to coordinate with https://github.com/dotnet/roslyn/pull/24748 as this one brings deprecation of WaitContext property.

**Comment by jasonmalinowski** [comment]
I'm good for this going in first. @jinujoseph (and I guess @Pilchie now), what do we still need for ask mode on this one?

**Comment by jinujoseph** [comment]
@olegtk can you fill in the ask mode template pls

**Comment by olegtk** [comment]
Ask mode template filled in, @Pilchie for approval.

**Comment by Pilchie** [comment]
Approved - thanks.

**Pull request merged**
