### PR TITLE
Updating error message for missing or ambiguous ValueTuple type

### PR DESCRIPTION
**Pull request by jcouv**
Follow-up on https://github.com/dotnet/roslyn/pull/20052 to refine the message.

@AlekseyTs for review (15.6). Thanks

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for review. This is updating a diagnostic message for 15.6.

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for a second review. Tiny change to a diagnostic. Thanks

**Comment by OmarTawfik** [comment]
nit: shouldn't this be replaced everywhere?
https://github.com/dotnet/roslyn/search?utf8=%E2%9C%93&q=ERR_PredefinedValueTupleTypeNotFound&type=

**Comment by jcouv** [comment]
@OmarTawfik Thanks. I didn't fix the diagnostic comments for all locations, just the ones in tuple tests. I don't feel it's critical.

**Comment by jcouv** [comment]
test windows_release_vs-integration_prtest please

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
FYI @jaredpar Hit the nuget cache corruption ([details](https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_release_vs-integration_prtest/250/))

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
test windows_release_vs-integration_prtest please

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by jcouv** [comment]
@dotnet/roslyn-infrastructure Is this a known issue by any chance? I'm hitting this on multiple PRs:

`error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'UserOperationBooster' and '' [D:\j\workspace\windows_debug---1522b458\src\Workspaces\Remote\ServiceHub\ServiceHub.csproj]`

([details](https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_debug_vs-integration_prtest/288/))

**Comment by ivanbasov** [comment]
yes, it is a known issue in 15.6. @heejaechang is trying to fix it

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by jcouv** [comment]
test windows_release_vs-integration_prtest  please

**Comment by jcouv** [comment]
test windows_release_vs-integration_prtest please

**Pull request merged**
