### PR TITLE
Highlight `await` and `return` in top-level statements

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Fixes: https://github.com/dotnet/roslyn/issues/60400

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
Does `return` get highlighted correctly?

Should `IsReturnableConstruct` be updated instead? This will require reviewing all its usages, so I don't feel strongly about it.

**Comment by DoctorKrolic** [comment]
> Does `return` get highlighted correctly?

Why do you ask about `return` in context of `async`-`await`? Is there some kind of connection between them or what?

> Should `IsReturnableConstruct` be updated instead?

I don't think so. `IsReturnableConstruct`, as you said, is used in other places and in general it is just a simple `SyntaxKind` filter, while here a bit more complex logic is performed

**Comment by Youssef1313** [comment]
> Why do you ask about `return` in context of `async`-`await`? Is there some kind of connection between them or what?
> 
> >

Just that we fix two bugs together :)

**Review by davidwengier — APPROVED** [review]

**Comment by davidwengier** [comment]
Thanks for the contribution!

**Pull request merged**
