### PR TITLE
Update the VSIXExpInstaller used for legacy integration tests

### PR DESCRIPTION
**Pull request by JoeRobich**
Resolves https://github.com/dotnet/roslyn/issues/63770

Test run: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6739445&view=results (microsoft)

### CODE REVIEW

**Comment by sharwell** [comment]
It'll be nice to finally be done with this one-off tool. 😄 Lots of tests still only in that project though.

**Comment by JoeRobich** [comment]
@sharwell Although this change works locally against an IntPreview installation, the DartLab pipeline is still hanging on extension install. =/

**Comment by JoeRobich** [comment]
On second look, I goofed and queued the run against main, not my feature branch. Started a new test run to confirm the issue is resolved - https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6739445&view=results (microsoft)

**Comment by JoeRobich** [comment]
Verified that extensions are successfully loading with this change.

**Pull request merged**
