### PR TITLE
Removing the NgenApplication attributes from our VSIX projects.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jasonmalinowski, @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tmat** [comment]
Why is it now removed? We have just added it...

**Comment by tannergooding** [comment]
@tmat, the documentation is wrong. They are working on updating it.
The full path to 'vsn.exe' is the default and will be selected if nothing is specified.

The documentation is also going to be updated to indicate the root directory that NgenApplication (if specified) is searched for from (it may be VsInstallDir, in which case for an explicit setting, you would need to specify Common7\IDE\vsn.exe, for example).

**Comment by tannergooding** [comment]
FYI. @MattGertz for RC3 approval.

**Comment by tmat** [comment]
@tannergooding OK, I'll make a corresponding change in Interactive Window.

**Comment by DustinCampbell** [comment]
I think you're good to merge now @tannergooding

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by srivatsn** [comment]
Thanks Tanner! @basoundr can you make this change for project system?

**Pull request merged**
