### PR TITLE
Adjust heuristic to choose a set of best candidates for overload resolution failure.

### LINKED ISSUE #9341: Errors inside VB lambda expression in Visual Studio 2015 not recognized
Back in VS2013 the VB compiler seems to be able to recognize errors inside a lambda expression. While in VS2015 it just won't recognize the sub as a valid expression. This makes code writing much harder.
Some screenshots:

In VS2013:
[![Visual Studio 2013][1]][1]

In VS2015:
[![Visual Studio 2015][2]][2]

Looks like the problem only resides in VB compiler.
Feedback on connect.microsoft.com: [https://connect.microsoft.com/VisualStudio/feedback/details/2416478/errors-inside-vb-lambda-expression-in-visual-studio-2015](https://connect.microsoft.com/VisualStudio/feedback/details/2416478/errors-inside-vb-lambda-expression-in-visual-studio-2015)
  [1]: http://i.stack.imgur.com/c3Xgc.png
  [2]: http://i.stack.imgur.com/H4JQb.png

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #9341.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
CC @dotnet/roslyn-ide for test adjustments.

**Comment by AlekseyTs** [comment]
Test windows_eta_open_prtest please.

http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/3812/
```
Connectivity Issue

Possible issue connecting to GitHub or cloning the repository. This could be caused by a lack of network connectivity or a lack of disk space. Please email netciadmin. Error cloning remote repo 'origin'
```

**Comment by gafter** [comment]
:shipit:

**Comment by mattwar** [comment]
@dotnet-bot test windows_eta_open_pretest please

**Comment by mattwar** [comment]
@dotnet-bot retest windows_eta_open_pretest please

**Comment by mattwar** [comment]
@dotnet-bot test windows_eta_open_prtest please

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by jcouv** [comment]
Does this have any back-compat implications?

**Comment by AlekseyTs** [comment]
> Does this have any back-compat implications?

The change affects only error scenarios. Therefore, I believe it doesn't have backward compatibility implications.

**Comment by jcouv** [comment]
:shipit:

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
Thanks for the review.

**Pull request merged**
