### PR TITLE
Include 'term' and 'description' xml items when under an 'item' tag.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/757

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @tannergooding @sharwell 

@sharwell You mentioned ths will likely conflict with you.  So I won't be submitting this until you're ok.  If you want to merge into your branch feel free.

**Comment by sharwell** [comment]
:memo: This is blocked on #21479.

**Comment by Pilchie** [comment]
@sharwell is this unblocked now?

**Comment by sharwell** [comment]
This is unblocked but has merge conflicts.

**Comment by CyrusNajmabadi** [comment]
@sharwell I have addressed the merge conflicts.  Feel free to merge when convenient.

**Comment by CyrusNajmabadi** [comment]
Ping @sharwell

**Comment by CyrusNajmabadi** [comment]
Definitely!

**Comment by CyrusNajmabadi** [comment]
@sharwell Do you need anything else?

**Pull request merged**
