### PR TITLE
Update XAML completion kind mapping to new 16.10 CompletionItemKinds.

### PR DESCRIPTION
**Pull request by mgoertz-msft**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@mgoertz-msft Who approved this?

**Comment by mgoertz-msft** [comment]
@CyrusNajmabadi  Great question, I was surprised as well. Looks like the msftbot auto-approved this. Would be worth checking the msftbot'srules and capabilities.

**Comment by CyrusNajmabadi** [comment]
@jaredpar @jinujoseph @jasonmalinowski msft-bot just merged this pr without approval from any team members. This seems... Not good.

**Comment by CyrusNajmabadi** [comment]
thanks marco! :-)

**Comment by CyrusNajmabadi** [comment]
This pr looks fine to me. So no need to roll back. But we likely need to put a hold on auto-merge until this is understood.

**Comment by 333fred** [comment]
This is exactly what the bot was designed to do, as it automates the merge PRs between branches.

**Comment by jinujoseph** [comment]
@JoeRobich @333fred @allisonchou to take a look

**Comment by 333fred** [comment]
To be clear: this is how the auto-merge bot has been functioning for at least a year now? Do not put auto-merge on PRs that you are not ready to be auto-merged.

**Comment by JoeRobich** [comment]
auto-approval is granted to anyone who has write or admin access. we could limit auto-approval to dotnet-bot.

**Comment by CyrusNajmabadi** [comment]
This has never happened before.  The bot would always say: i need at least a signoff on a PR.  Or, it would say: you have someone still requesting a change.  

> Do not put auto-merge on PRs that you are not ready to be auto-merged.

Wat?

Shouldn't it only merge PRs that have been signed off on?

**Comment by 333fred** [comment]
> Shouldn't it only merge PRs that have been signed off on?

No. The bot was designed for the branch codeflow process. Bot 1 makes a pr to merge from branch a to b, and adds this label. Bot 2 adds auto approves, then merges (assuming tests pass). That's how it was supposed to function.

**Comment by davidwengier** [comment]
> This has never happened before.

This is how the bot has always worked since I joined, and one of the reasons I don't like it, because I can't use the label on a small PR on a Friday, I instead have to monitor for a human approval on the weekend, then I can label it.

The new auto-merge functionality in GitHub should work a lot better in this regard.

**Pull request merged**
