### PR TITLE
fix perf runs

### PR DESCRIPTION
**Pull request by TyOverby**
post build script wasn't being run, but we can bundle it into the main test?

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet-bot test perf please

**Comment by TyOverby** [comment]
@jasonmalinowski Absolutely no idea.

@mmitche: Do you know why my post-build task wasn't being run?

**Comment by mmitche** [comment]
@TyOverby postbuild script was deprecated (it's unmaintained and not secure).  This is the right change.

@dotnet-bot test ci please

**Comment by TyOverby** [comment]
Looks like everything's good.  @mmitche signoff?

**Pull request merged**
