### PR TITLE
Make our loc strings more consistent

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/15945

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz @srivatsn for approval.

**Comment by CyrusNajmabadi** [comment]
Yeah, not sure if this meets the bar at this point.  If not, i'm happy to rebase against Update1.  What do you think @Pilchie ?

**Comment by srivatsn** [comment]
I think Loc handoffs are done and each string change requires individual coordination now. Given this is a such a minor change, I am not sure it's worth the effort to coordinate.

**Comment by CyrusNajmabadi** [comment]
Ok.  I'm pushing this out to post-dev15

**Comment by DustinCampbell** [comment]
Note that this change broke integration tests in post-dev15. Should be fixed with https://github.com/dotnet/roslyn-internal/pull/1456/commits/9b110d99660ecee64cf3d0d928abdbe883d11fcc.

**Pull request merged**
