### PR TITLE
Add two new dev solutions to the root

### PR DESCRIPTION
**Pull request by agocke**
Right now we have CrossPlatform, Roslyn, and RoslynLight, all of
which are heavyweight except for CrossPlatform, but xplat should 
change depending on what we can build. This change adds two
new solutions for developers to choose from, depending on what they're
working on. The Workspaces solution contains everything workspaces and
down, while the compilers solution just contains the C# and VB
compilers.

@jaredpar

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
@agocke 
So does this mean that I can just play around with just the VB compiler, without having to build and test the rest of then Roslyn bits? Also will this include instruction on how to build and test, these solutions?

**Comment by tmat** [comment]
:-1: Can we not add more solutions? Can we actually remove some? It is rather hard to keep .sln files up to date across multiple-branches if the branches have different projects.

**Comment by AdamSpeight2008** [comment]
@tmat  At least spilt out the compilers from the rest of the Roslyn infrastructure. Or consider a new github repo for each one.

**Comment by tannergooding** [comment]
@dotnet-bot test this please

**Comment by agocke** [comment]
@AdamSpeight2008 Yes, this would allow you to easily edit just the VB compiler without having to load the other projects. As a compiler dev, I really don't need those projects open when I'm developing, just when I'm running tests.

**Comment by tmat** [comment]
Note that you can unload projects you are not working on. The set of unloaded project is persisted and VS doesn't load them next time it opens the solution.

**Comment by jaredpar** [comment]
@tmat unloading projects has a set of problems:

- There are over 100 projects which are completely unnecessary for working on the compiler.  The click, unload, repeat cycle is not conductive for removing this many projects.
- Unloading a project without first unloading its dependencies causes Visual Studio to go into a fit on the error list.

**Comment by tmat** [comment]
@jaredpar You can unload all projects in an entire directory at once, for example EditorFeatures.

**Comment by agocke** [comment]
@tmat However, every time you nuke your .vs directory, which I do a lot to deal with various bugs, all your unloads are gone and you have to do it all over again. Moreover, it's confusing to newcomers who just get overloaded at the size of Roslyn.

I think your issue is mitigated by not necessarily needing to add extra projects to these solutions. If you're having trouble with merging I say just don't add them to those projects until you're ready to bring into master.

**Comment by tmat** [comment]
@agocke So we are fine with all but Roslyn.sln solutions broken in no-master branches?

**Comment by agocke** [comment]
@tmat For portable pdb I would be OK with that.

**Comment by jaredpar** [comment]
Note that RoslynLight.sln will be deleted very soon.  Once VS2015 RTMs it will no longer have a purpose and will go away.

**Pull request merged**
