### PR TITLE
Display effective language version for #error version

### LINKED ISSUE #51879: #error version directive should show language version instead of preview or latest
**Version Used**: latest master (https://sharplab.io/ as of 2021-03-15).

**Steps to Reproduce**:

1. Write `#error version`.

**Expected Behavior**:

For the “Language version” to show something like `9.0` or `9.1`.

**Actual Behavior**:

The “Language version” is listed as `latest` or `preview`.

The point of this compiler directive is to figure out what the effective language version is. I can already see `/langversion:latest` in the build log. Telling me what parameter was passed doesn’t help me. I am interested in what that is being interpreted as. The interpretation should be clearer and not require me to look up the supported versions and preview features by the compiler version itself.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #51879

(Waiting for test failures to update them)

### CODE REVIEW

**Comment by Youssef1313** [comment]
The only test around this area is:

https://github.com/dotnet/roslyn/blob/1cca63b5d8ea170f8d8e88e1574aa3ebe354c23b/src/Compilers/CSharp/Test/Syntax/LexicalAndXml/PreprocessorTests.cs#L3037-L3058

It doesn't test Preview, Default, Latest, etc..

My concern about adding a test with Latest is the current expected will be "9.0", but later it will be "10.0". So it will fail with each language version. Is this okay?

**Comment by jaredpar** [comment]
> My concern about adding a test with Latest is the current expected will be "9.0", but later it will be "10.0". So it will fail with each language version. Is this okay?

That doesn't bother me. It is expected that there is going to be some amount of churn when promote a version from preview to latest. 

If we are changing this though I would like to see increased test coverage here. Think it makes sense to essentially have a `[Theory]` based test where we exercise every value and ensure it prints correctly. Specifically though we should make sure that "preview" continues to print "preview"

**Comment by Youssef1313** [comment]
@jaredpar Added tests to cover those. For `preview`, it only prints `preview`. There is a request in https://github.com/dotnet/roslyn/issues/51879#issuecomment-799471081 that preview prints additional information, but I don't see a good form or actual good information to add. So I'll let you weigh on whether an action should be taken.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

**Review by 333fred — APPROVED** [review]

**Review by jaredpar — APPROVED** [review]

**Pull request merged**
