### PR TITLE
Only run nuget upload script from roslyn-internal

### PR DESCRIPTION
**Pull request by TyOverby**
@dotnet/roslyn-infrastructure @jaredpar

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet/roslyn-infrastructure I need a review on this.  Next time we do a nuget zip upload, this script needs to work.

**Comment by jaredpar** [comment]
Can you explain why this change is necessary?  At this point the NuGet ZIP is only needed for our cross platform efforts.  Everything else does a real NuGet restore on every CI run.  Hence I wouldn't expect anything in roslyn-internal to be relevant to the ZIP files anymore.

**Comment by jaredpar** [comment]
@davkean can correct me here.  But my understanding is internal does an actual restore vs. a zip restore.

**Comment by TyOverby** [comment]
I'll close this for now.

**Pull request closed without merging**
