### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160217-160035
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160217-160035 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by genlu** [comment]
The test failure don't seem to be related to the commits listed above? @dotnet/roslyn-compiler Could you take a look at it please?
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3961/
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3933/

**Comment by AlekseyTs** [comment]
Could it be due to an attempt to merge the following commit https://github.com/vslsnap/roslyn/commit/b60cacf9b2db444e39f3a95f408b2f1cde2167d7, which specifically "marked" as DO NOT MERGE INTO MASTER ?

**Comment by natidea** [comment]
We are seeing these failures in other PRs. So faulty change must already be in master

**Comment by genlu** [comment]
I believe I have resolved that when I merged master into stabilization last week, and those differences are likely unrelated as they are mostly in IDE unit tests.

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please.

**Comment by genlu** [comment]
@dotnet-bot retest  prtest/win/dbg/unit64 please.

**Pull request merged**
