### PR TITLE
Add a WorkspaceKind property to ProjectContext.

### PR DESCRIPTION
**Pull request by JoeRobich**
This change will allow the C# extension to warn users that their active file is not part of the open workspace. See https://github.com/dotnet/vscode-csharp/pull/7628

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Why not just copy the existing value over?  Not sure why we're mapping only two of the values over to two new values.

**Comment by DustinCampbell** [comment]
> Why not just copy the existing value over? Not sure why we're mapping only two of the values over to two new values.

Same question from me. :smile: Does this really need to be an enum? Could it just be the string.

**Review by dibarbet — APPROVED** [review]
seems OK to me (assuming other feedback is taken) - mind adding a test or two for this?

**Comment by jasonmalinowski** [comment]
Or should this just have some string for a general "warning" concept, which maybe we can use in other ways too? Like source generated files being read only (like we show a banner), or other things for debugger files, etc?

**Comment by jasonmalinowski** [comment]
I'd also propose it could just be isMiscellaneous or something else too, in case we change how workspace kinds work on the server a bit and have to figure out how to map it back to this enum type.

**Comment by JoeRobich** [comment]
I went with Jason's suggestion because it is what I wanted to do initially before I complicated things.

**Comment by JoeRobich** [comment]
> Or should this just have some string for a general "warning" concept, which maybe we can use in other ways too? Like source generated files being read only (like we show a banner), or other things for debugger files, etc?

We can talk more if you have scenarios in mind. We are considering also showing a notification when the user opens a misc file after project loading has completed. I think we would still want to show a warning in the status bar, especially if the user has configured not to show those notifications. It is tricky because we are walking the fine line of not being in the users way but also making it obvious that something is different about the open file.

**Pull request merged**
