### PR TITLE
Do not simplify away field as clause - it breaks compilation

### LINKED ISSUE #43123: Do not simplify away field as clause - it breaks compilation
**Version Used**: 
codeanalysis 3.5.0

**Steps to Reproduce**:

On a Visual Basic 
1. Call Reduce on a single variable field with an As clause and an initializer

```vbnet
<Workspace>
    <Project Language="Visual Basic" CommonReferences="true">
        <Document>
            Imports System
            Imports I = System.Int32
            Module Program
                Public Dim {|SimplifyParent:x As Integer = 5|}
            End Module
        </Document>
    </Project>
</Workspace>
```

**Expected Behavior**:
Same output as input

**Actual Behavior**:
As clause gets removed.
If option strict is on: Removing the as clause causes a compile error
If option strict is off: It changes the inferred type of the field to be Object in all cases

**Other details**:
This shot up my priority list when I realized the option to workaround this bug had been removed, though I'd much prefer we fix this bug than bring the option back.

### PR DESCRIPTION
**Pull request by GrahamTheCoder**
Fixes #43123

If there's a case when the As clause actually should be removed (e.g. if you want to do so when option strict is off), let me know and I'll update.

I fixed the obvious explicit test of this. I expect there will be some other tests that need fixing up. My system struggles to run the tests locally so I'll deal with them as they appear from CI.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jcouv @KathleenDollard  do you know if there are any cases in VB where a `dim field = ...` will not infer `object.  as the type of `dim`, but will instead use whatever is in `...` to determine the field type?

**Comment by GrahamTheCoder** [comment]
From https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/dim-statement
> Type inference applies at the procedure level. It does not apply outside a procedure in a class, structure, module, or interface.

**Comment by jcouv** [comment]
@CyrusNajmabadi I don't know. I didn't expect `object` to be inferred in `Dim field = 5` either ;-)

**Comment by GrahamTheCoder** [comment]
Looks like the tests didn't start properly, then timed out, I assume this just needs a rerun since I can't see any actual failing test.

**Comment by GrahamTheCoder** [comment]
All green - let me know if you need anything else

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
