### PR TITLE
Merge master into features/ioperation

### PR DESCRIPTION
**Pull request by genlu**
@dotnet/roslyn-compiler @dotnet/roslyn-interactive

### CODE REVIEW

**Comment by cston** [comment]
Test failure is #11813.

**Comment by genlu** [comment]
@dotnet-bot Retest this please.

**Comment by genlu** [comment]
@dotnet-bot retest windows_debug_unit32_prtest, please
CI-Build: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/features_ioperation/job/windows_debug_unit32_prtest/3/
Reason: test hangs

**Comment by genlu** [comment]
Here's the retest result:
```
http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/features_ioperation/job/windows_debug_unit32_prtest/4/
```
It succeeded but GitHub still shows previouly failed build.

**Pull request merged**
