### PR TITLE
Move stack-allow syntax checks out of the parser.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler @jcouv @AlekseyTs

**Comment by CyrusNajmabadi** [comment]
Note: it looks like we *also* report a semantic error for this issue.  So we could just remove hte syntax check altogether.

**Comment by CyrusNajmabadi** [comment]
@cston Can you take a look?

**Comment by cston** [comment]
LGTM

**Pull request merged**
