### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160601-201349
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160601-201349 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by panopticoncentral** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/207/
// Retest reason:

**Comment by panopticoncentral** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by panopticoncentral** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by panopticoncentral** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Pull request merged**
