### PR TITLE
Add an async test case for a try/finally with an uncaught exception

### LINKED ISSUE #19905: No async test case for a try/finally with an uncaught exception
Looking at the async test cases in https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Emit/CodeGen/CodeGenAsyncTests.cs, there does not appear to be any case in which an exception is thrown inside a `try/finally` block and not caught, causing the `finally` to be entered from exceptional control flow rather than ordinary control flow.

Note: The `AnonType32` and `Await43` tests do throw exceptions inside a `try/finally` block, but then they both catch them before entering `finally`.

Filing this as an issue per @jmarolf.

### PR DESCRIPTION
**Pull request by drcjt**
Added an extra async test case covering finally block entered from exceptional control flow rather than ordinary control flow.

Fixes #19905

### CODE REVIEW

**Comment by drcjt** [comment]
I believe the integration test failure is #20157

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-compiler for review.

**Comment by jaredpar** [comment]
@drcjt would you be able to rebase your code off of master? Sorry we lost track of this PR and it looks like some merge conflicts have made their way in the mean time.

**Comment by drcjt** [comment]
@jaredpar no problem - rebased as requested.

**Comment by jaredpar** [comment]
@drcjt thanks!

**Pull request merged**
