### PR TITLE
Log low VM telemetry at most once per session

### LINKED ISSUE #6279: make vb/ide/vbcs/virtualmemory/lowmemory fire only once when we get into low memory situation.
currently we fire it every time it is raised even if we are already in that mode.

### PR DESCRIPTION
**Pull request by pharring**
Fixes #6279 

Supersedes #6281 

@Pilchie @heejaechang

### CODE REVIEW

**Comment by pharring** [comment]
retest prtest/win/dbg/unit64 please.

**Comment by Pilchie** [comment]
My question about the shell was more along the lines of: "Have we checked whether the shell already has some telemetry around this event, such that we should just remove this and use theirs?"  If not, I'm fine with this. :+1:

**Comment by pharring** [comment]
There's no existing telemetry on the shell side for this event. The shell does have code to record VM stats every 10 minutes or so. However, that code still mentions SQM and I don't know if it's still relevant.

**Comment by pharring** [comment]
@MattGertz In my haste, I merged this without to the "Approved for next preview" tag. Please advise.

**Pull request merged**
