### PR TITLE
Delete VisualStudioSetup.Next

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This project originally existed to support a Dev14 vs. Dev15 split, which we no longer version that way. This project had it's contents moved out a few minor updates of Dev15 ago, and is now empty, only so that way if you had an older VS Update F5 would still work. Now we require 15.6 as a base drop, which also has this containing nothing, so we can just delete this.

Putting this in master so we have sufficient time to shake out any silly side-effects of this.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please.

**Comment by jcouv** [comment]
Do we have "contributing" documents that refer to Setup.Next? If we do, please update them as well. Thanks

**Comment by jasonmalinowski** [comment]
@jcouv The main one I know of was updated as a part of this PR.

**Comment by jasonmalinowski** [comment]
(but always good to be on the lookout for stale docs, so thanks for thinking!)

**Comment by AdamSpeight2008** [comment]
[Stale doc.](https://github.com/dotnet/roslyn/blob/dev16/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md) @jasonmalinowski

**Comment by KGRWhite** [comment]
@jasonmalinowski  There is also a reference to Next in the wiki [https://github.com/dotnet/roslyn/wiki/Contributing-Code#getting-started-coding-in-visual-studio](here) under step 4

**Comment by jasonmalinowski** [comment]
@KGRWhite Thanks deleted!

**Pull request merged**
