### PR TITLE
ExpressionPrinter reduced the string concatenation usage.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Rewriten prefer using the string builder methods over string concatenations.
Extracted out a helper function to do then indenting.
Marked improved in test times

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
I think this should also be ported over to c#

**Comment by AdamSpeight2008** [comment]
The `indent` has potential to optimised, if we can find an implementation that can inlined.

**Comment by AdamSpeight2008** [comment]
@jaredpar ready for review.

**Comment by crummel** [comment]
Build triggered. sha1 is merged.

**Comment by gafter** [comment]
Please quantify "Marked improved in test times"

**Pull request closed without merging**
