### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160608-150056
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160608-150056 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_debug_unit64_prtest please

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_eta_open_prtest please

**Comment by tmat** [comment]
@jinujoseph I think we forgot to update VSL.Versions.props -- needs to have -rc2 version:

```
<MicrosoftDiaSymReaderNativeVersion>1.4.0-rc2</MicrosoftDiaSymReaderNativeVersion>
```

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_eta_open_prtest pls 
failure related to https://github.com/dotnet/roslyn/issues/11893

**Comment by tmat** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/420/
// Retest reason:  #11893, now fixed

**Comment by jinujoseph** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// previous failure related to: https://github.com/dotnet/roslyn/issues/11856

**Pull request merged**
