### PR TITLE
Minor update for 'Generate delegate constructor' refactoring

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Using more efficient way to get number of instance constructors.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by Neme12** [comment]
This is not hard to review :( it would be nice to at least get a response in 4 months.

**Comment by jinujoseph** [comment]
retest this

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.preview3 when test green

**Comment by Neme12** [comment]
Sorry for my previous comment, I didn't mean it in a negative way! It's easy to miss or forget PRs if there wasn't any activity on them. Hopefully that will continue to get better in the future.

I also understand why this wouldn't be very high on the priority list.

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_unit32_prtest please

**Comment by zaytsev-victor** [comment]
@Neme12 thanks (:

**Pull request merged**
