### PR TITLE
Fix Interactive window command handling

### PR DESCRIPTION
**Pull request by amcasey**
When I changed VsInteractiveWindow from is-a ToolWindowPane to has-a
ToolWindowPane, I broke its command handling.  I don't know why, since it
still implemented IOleCommandTarget and forwarded to the same method, but
revert that part of
https://github.com/dotnet/roslyn/commit/0e7a2b6e4fd3e79a78843319af965f5153bf21ad
until we figure out something better.

It's still not acceptable to upcast VsInteractiveWindow to ToolWindowPane,
so I'm leaving the IVsInteractiveWindow2 changes and we'll just have to
trust callers not to do it.

### CODE REVIEW

**Comment by amcasey** [comment]
test vsi please

**Comment by amcasey** [comment]
FYI @drognanar - this should fix the integration tests.

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-interactive

**Comment by amcasey** [comment]
@davkean @jasonmalinowski if either of you knows enough about command handling to suggest a better fix, I'd really appreciate a few minutes of your time.

**Comment by davkean** [comment]
How does the command-target get registered? Are you sure that the ToolWindowPane wasn't doing that?

**Comment by amcasey** [comment]
FYI @drognanar The problematic change appears not to have made it into future-stabilization (which is worrisome on its own, since it's supposed to be in preview).

**Comment by amcasey** [comment]
@davkean No, that sounds reasonably likely.  My next step was going to be to track down the ToolWindowPane source, but I wanted to have a fix available ASAP.

**Comment by ManishJayaswal** [comment]
@amcasey will this revert impact PTVS?

**Comment by amcasey** [comment]
@ManishJayaswal If anything, it will unbreak their code.

**Comment by amcasey** [comment]
test prtest/win/dbg/eta please

**Comment by amcasey** [comment]
I don't believe this change has any advantages over rolling back the original commit.

**Pull request closed without merging**
