### PR TITLE
Move to using hte SyntaxEditor for the 'simplify type name' fix-all code.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/26824.  reviewers should wait on that going in before reviewing this.

This change gets rid of hte hand-rolled fix-all provider we had for this single fixer and instead moves us to the common 'fix-all' infrastructure we use everywhere else. 

When reviewed, i recommend going a commit at a time.

### CODE REVIEW

**Comment by jinujoseph** [comment]
test windows_debug_vs-integration_prtest

**Comment by sharwell** [comment]
@jinujoseph integration tests will fail prior to merging #27933

**Comment by jinujoseph** [comment]
hmm seems to be working

**Comment by CyrusNajmabadi** [comment]
@sharwell @jinujoseph can this be merged in?

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4

**Pull request merged**
