### PR TITLE
fix flaky unit test

### PR DESCRIPTION
**Pull request by heejaechang**
sometimes, instance are kept alive by stack. give it a bit more timeout and clear object in other method.

### CODE REVIEW

**Comment by heejaechang** [comment]
@tmeschter @mavasani @srivatsn can you take a look? basically changed Environment.TickCount (int type) to more reliable (but slightly more expansive) DateTime. and made test to have longer timeout.

**Comment by heejaechang** [comment]
retest this

**Comment by heejaechang** [comment]
retest this please

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by mavasani** [comment]
:+1: assuming the test failures here are unrelated to your change.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Pull request merged**
