### PR TITLE
made bucketing to be better even in telemetry site.

### PR DESCRIPTION
**Pull request by heejaechang**
previous way made bucketting to be better in watson site but not telemetry site. this should make it to better on both site.

### Customer scenario

This doesn't affect user experience. this is to make NFW better bucketed in telemetry site.

### Bugs this fixes

N/A

### Workarounds, if any

No

### Risk

I don't see any risk

### Performance impact

No impact

### Is this a regression from a previous update?

No

### Root cause analysis

Previously we made NFW bucketing better but we put that code that is specific to Watson. but we want telemetry of NFW to be separate reports better as well. so this change make those code path to use the better bucketing as well.

### How was the bug found?

Feature dashboard

### CODE REVIEW

**Comment by heejaechang** [comment]
@ivanbasov @Pilchie @jinujoseph can you take a look? making NFW telemetry (feature dashboard) to have better bucketing.

**Comment by Pilchie** [comment]
Note - unit test failures appear legitimately related to this change.

**Comment by heejaechang** [comment]
@Pilchie yes. fixed.

**Comment by Pilchie** [comment]
And does this match the latest guidance on the internal thread about how to do this right?

**Comment by heejaechang** [comment]
@Pilchie are you talking about GDPR or something else?

**Comment by Pilchie** [comment]
The thread about parameters being 0 based versus 1 based.

**Comment by heejaechang** [comment]
@Pilchie yep. those issues are now addressed.

**Comment by Pilchie** [comment]
Tests still failing.

**Comment by heejaechang** [comment]
hmmm. test failure seems not related to this PR. I will take a look anyway.

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_release_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_release_unit32_prtest please

**Comment by heejaechang** [comment]
@Pilchie is it okay to check in?

**Comment by Pilchie** [comment]
Approved - thanks

**Pull request merged**
