### PR TITLE
Disable failing tests that rely on NuGet restore operations

### PR DESCRIPTION
**Pull request by sharwell**
See #48435

### CODE REVIEW

**Comment by sharwell** [comment]
Marking as draft while we investigate disabling `DOTNET_MULTILEVEL_LOOKUP`

**Review by jasonmalinowski — APPROVED** [review]

**Comment by sharwell** [comment]
@jasonmalinowski I disabled a second round of tests here in hopes that it's enough

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@sharwell: looks like there's more, but those don't seem to be related to NuGet. Also note they're only failing on debug builds, which does seem suspicious. OK if I merge this as is since this is at least getting _some_ test runs unblocked? We've got a bunch of other things that need to get moving behind this.

**Comment by jasonmalinowski** [comment]
Ah, I see some dumps that looks like they'd be fixed by d51593e91bfc2c3c5bdf6dfa0409a9297761a133.

**Comment by jasonmalinowski** [comment]
Want to cherry-pick that one in @sharwell? I get the sense you're working on that change; also since that'll impact all sorts of random stuff that's still easier than trying to play whack-a-mole with those tests.

**Comment by sharwell** [comment]
@jasonmalinowski Looks like #48439 will be ready before this one 👏

**Comment by sharwell** [comment]
This has been resolved

**Pull request closed without merging**
