### PR TITLE
Updating our nuget dependencies to the VS2015.3.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jasonmalinowski, @tmat, @jaredpar, @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tannergooding** [comment]
There are still seven packages (`RoslynDependencies.*`) which we created to fill some gaps in the VSSDK. New packages still need to be uploaded and the versions should be updated.

The relevant files are:
* `src\EditorFeatures\Test\project.json`
* `src\InteractiveWindow\EditorTest\project.json`
* `src\Dependencies\VisualStudioTest\project.json`
* `src\VisualStudio\Core\Def\project.json`

**Comment by tmat** [comment]
:-1: We need post-RTM Core CLR. RTM Core CLR has a bug in assembly loader. It's gonna segfault on Linux.
Other than that LGTM.

**Comment by jasonmalinowski** [comment]
So I defer to @tmat about the other stuff, but not sure why it's necessary to move the VS dependencies forward; these are just reference assemblies, right? Do we care? Did we already cut the ability to build with Update 2? Why cut it now?

**Comment by tmat** [comment]
Actually -- one more thing. You are missing version updates in https://github.com/dotnet/roslyn/blob/master/build/Targets/VSL.Versions.targets

**Comment by tannergooding** [comment]
@tmat, what post-RTM versions do we need? I will update the PR accordingly

**Comment by tmat** [comment]
The one that's already checked in works. Just don't change Core CLR dependencies.

**Comment by tannergooding** [comment]
@tmat, the ones I updated were all pre-RTM, so I would assume they have the same bug?

**Comment by tmat** [comment]
They were not pre-RTM.

**Comment by jaredpar** [comment]
The Linux job has ruled in @tmat favor about whether we need post-RTM bits.

**Comment by tannergooding** [comment]
I've updated to no longer touch the NetCore packages. However, the packages we are using are not Post-RTM.

For `Microsoft.NETCore.App` we are currently using `1.0.0-rc3-004338` (28th of May) where-as RTM is v1.0.0 (24th of June). Post-RTM bits are `1.0.1-beta-000547-00` or later.

For `Microsoft.NETCore.Runtime.CoreCLR` (which seems to be the problem package) we are currently using `1.0.3-rc4-24221-02` (21st of June) where-as RTM is v1.0.3 (24th of June). Post-RTM bits are `1.0.4-beta-24225-02` or later

**Comment by tmat** [comment]
The dates don't meen much since RTM repos snapped a few weeks before the actual RTM build was produced

**Comment by tmat** [comment]
@jasonmalinowski 
So the DiaSymRaeder.Native version should have been integrated from microupdate. Seems like the commit got lost :(

**Comment by tannergooding** [comment]
@jasonmalinowski, this doesn't break the ability to build or deploy on Update 2. It just brings along any fixes that have made their way into the packages.

**Comment by jasonmalinowski** [comment]
@tannergooding Sure, but the packages are just reference assemblies. So we don't get "fixes" either.

**Comment by tannergooding** [comment]
@jasonmalinowski, some of them (such as the VSSDK.BuildTools) come with targets and props files, which were modified for Update 3

**Comment by jasonmalinowski** [comment]
Should we just update those then instead of everything?

**Comment by tannergooding** [comment]
test windows_eta_open_prtest please

**Comment by tannergooding** [comment]
test windows_eta_open_prtest please
test windows_debug_unit64_prtest please

**Comment by tannergooding** [comment]
tagging @brettfo, as I believe updating the VSSDK version to Update 3 is required for the Dev15 SxS work.

**Comment by tannergooding** [comment]
ETA is passing in the internal side PR (see 1159)

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
