### PR TITLE
Minor bug fix: adding missing case for ConversionOperatorDeclaration in IsReturnableConstruct

### PR DESCRIPTION
**Pull request by Neme12**
`SyntaxNodeExtensions.IsReturnableConstruct` is missing a case for `ConversionOperatorDeclaration`.

This causes the following bug: highlighting return statements does not work inside conversion operators.
Repro:
```c#
class C
{
    public static explicit operator string(C a)
    {
        return null;
        return null;
    }
}
```
click on any `return` - nothing is highlighted.

This PR fixes that and adds a lot more tests into ReturnStatementHighlighterTests to cover cases for all constructs (it currently only covers methods & simple lambda expressions). I also renamed existing tests to give them better names as opposed to Test1, Test2, etc...

### CODE REVIEW

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest license/cla please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

**Comment by Neme12** [comment]
@sharwell Would please you take a look at this tiny bugfix? Thanks.

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide can this be merged in for @Neme12

**Comment by CyrusNajmabadi** [comment]
@jinujoe / @dotnet/roslyn-ide  Can someone merge in this tiny PR from @Neme12 ?  Thanks!

**Comment by Neme12** [comment]
@dotnet/roslyn-ide

**Comment by jinujoseph** [comment]
thanks @Neme12

**Pull request merged**
