### PR TITLE
Add (mostly skipped) unit tests for subsumption in typeswitch.

### PR DESCRIPTION
**Pull request by gafter**
@AlekseyTs @agocke Please review the addition of a few unit tests.
/cc @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Consider adding WorkItem attribute to the new tests.

**Comment by gafter** [comment]
@AlekseyTs I expect the WorkItem will be added when the tests are "fixed". Given the way the various features interact, may not have correctly classified them in the Skip.

**Comment by AlekseyTs** [comment]
This feels backwards.

**Comment by gafter** [comment]
[Test-Driven Development](http://agiledata.org/essays/tdd.html) may feel backwards if one is used to producing implementation along with tests.

**Comment by AlekseyTs** [comment]
The backwards part is to skip test without WorkItem attribute.

**Comment by agocke** [comment]
LGTM

**Comment by gafter** [comment]
I don't yet know how the work will be factored.

**Comment by AlekseyTs** [comment]
@gafter I think, it shouldn't be that hard to open an issue or issues. We have a policy, every skipped test should have a WorkItem attribute. You are referencing some issue in the Skip value. At the very least use that issue. If that issue is not related, then using it in the Skip value is not appropriate.

**Comment by gafter** [comment]
These tests are included in #11485

**Pull request closed without merging**
