### PR TITLE
Update static lambdas from master

### PR DESCRIPTION
**Pull request by RikkiGibson**
This refreshes the static-lambdas feature branch. I didn't create this as a regular codeflow PR as there was a bit more manual fixup required than usual.

Commit a18548d requires manual review. Note that I dealt with PublicAPI conflicts by simply taking the master version of PublicAPI and then running the fixer in the manually reviewed commit. Thus the diff will just show where the feature branch added new APIs.

Please take a look @CyrusNajmabadi @jcouv

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> Commit a18548d requires manual review.

I dont' see anything in there of concern.  but i'm not a compiler dev :)

**Comment by RikkiGibson** [comment]
DeeplyNestedGeneric baseline probably needs to be adjusted again.

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-compiler Could I please get a second review on commit a18548d

**Comment by RikkiGibson** [comment]
Ping @dotnet/roslyn-compiler

**Comment by RikkiGibson** [comment]
It sounds like this is acceptable to merge with a single sign-off.

**Pull request merged**
