### PR TITLE
Dead code in flow analysis for tracking exceptions

### PR DESCRIPTION
**Pull request by jcouv**
I noticed that we never set `trackExceptions` to `true`.

### CODE REVIEW

**Comment by gafter** [comment]
You’ve selected only a small part of an obsolete structure. We should be able to eliminate the precise abstract flow analysis wholesale.

**Comment by jcouv** [comment]
From discussion with @gafter and @cston, we're not sure whether this mechanism might be useful for analyzing dereferences in the nullable feature (https://github.com/dotnet/roslyn/issues/23270). 
I'm going to put this PR on hold until we figure this out. Thanks

**Comment by jcouv** [comment]
Chuck completed #23270 without needing this mechanism, so it is safe to remove now.
I've refreshed the PR (rebased to latest preview2 bits and resolved conflicts).

**Comment by jcouv** [comment]
Sounds like Andy is covering this in his next PR.

**Pull request closed without merging**
