### PR TITLE
Do not cut short binding of “return” statement even if expression has syntax errors.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Addresses DevDiv 1179899.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
- Bug number - DevDiv 1179899
- Customer scenario - Intellisense cannot provide any meaningful completion after a dot following a lambda parameter name when the lambda expression is incomplete (being typed in, for example) and it is a return statement expression .  Here is an example:
```
using System;
 
class Program
{
       static Func<Program, string> stuff()
    {
        return a => a.   // <-- This is the dot.
    }
}
```
- Fix description - Binder.BindReturn has a short-cut that results in not attempting to convert return expression to the target type if that expression is “bad”. The badness check, among other things, involves checking if there are syntax errors associated with expression. The fix modifies the logic and prevents the compiler from taking the short-cut solely due to the presence of syntax errors. In the scenario of interest, this ensures that the lambda body is going to be bound for the target delegate type and result of that binding will be available to SemanticModel. Without the fix, the lambda is never bound by the normal binding process and SemanticModel is binding it later in an error recovery mode without any target delegate type, resulting in a loss of type information for parameters, etc.
- Testing done - unit-tests.

@jaredpar FYI

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @agocke, @jaredpar, @khyperia Please review.

**Comment by VSadov** [comment]
LGTM

**Comment by MattGertz** [comment]
Approved 6/3 by ML Shiproom.

**Pull request merged**
