### PR TITLE
Update publish data for 16.8

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Comment by JoeRobich** [comment]
CI passed despite the GH check not updating - https://dev.azure.com/dnceng/public/_build/results?buildId=746805&view=results

**Comment by RikkiGibson** [comment]
Is this just supposed to restore the order of "oldest to newest" releases, while preserving the contents?

**Comment by JoeRobich** [comment]
@RikkiGibson  Oldest to newest as well as setting the 16.8-preview1 branch to rel/d16.8

**Comment by JoeRobich** [comment]
Merging non-functional change.

**Pull request merged**
