### PR TITLE
Fix regression in interactive stack printing

### PR DESCRIPTION
**Pull request by tmat**
Fixes crash in csi.exe: https://github.com/dotnet/roslyn/issues/9176

### CODE REVIEW

**Comment by tmat** [comment]
@amcasey Please review.
//cc @dotnet/roslyn-interactive

**Comment by MattGertz** [comment]
Approved pending CR.

**Comment by ManishJayaswal** [comment]
:+1:

**Comment by amcasey** [comment]
LGTM

**Comment by davkean** [comment]
This appears to have regressed this test in release builds: https://github.com/dotnet/roslyn/issues/9221.

**Comment by amcasey** [comment]
My bad.  I should have mentioned that these fixtures require `[MethodImpl(MethodImplOptions.NoInlining)]`.

**Comment by tmat** [comment]
I do have no inlining there.

**Comment by amcasey** [comment]
On my box, it only fails when run as 64-bit.  Somehow the line number increases by 1.

**Comment by amcasey** [comment]
It's hard to see how the line number could increase without the binary changing.

Also, the 32-bit line number appears to be correct (and works in debug32, debug64, and release32).

**Comment by amcasey** [comment]
```
<method containingType="Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.ObjectFormatterTests+Fixture2" name="MethodDynamic">
  <customDebugInfo>
    <forward declaringType="Microsoft.CodeAnalysis.CSharp.Scripting.Hosting.UnitTests.ObjectFormatterTests+Fixture" methodName="Method" />
  </customDebugInfo>
  <sequencePoints>
    <entry offset="0x0" startLine="10123" startColumn="17" endLine="10123" endColumn="45" document="3" />
    <entry offset="0x54" startLine="10124" startColumn="13" endLine="10124" endColumn="14" document="3" />
  </sequencePoints>
</method>
```

**Comment by amcasey** [comment]
So release64 is reporting the exception as having come from the closing brace.

**Pull request merged**
