### PR TITLE
Redesign active statement handling during debugging

### PR DESCRIPTION
**Pull request by tmat**
### Customer scenario

Previously when entering a break mode the EnC manager synchronously enumerated all active statements in the debuggee (effectively all CLR stack frames) in order to be able to track them during EnC and report them to the language services. This was causing UI delays since all this work was performed on every step on UI thread.

This change removes active statement tracking from EnC manager entirely (see VSO PR [103113](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/103113)) and moves it to the language service, which has already been doing most of the tracking anyways. The active statements are now enumerated lazily and asynchronously to avoid blocking UI.

The new design also removes some of the dependencies of the EnC Manager on project system and is part of longer term effort to redesign EnC Manager tracked by https://github.com/dotnet/roslyn/issues/18350.

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/13276
https://github.com/dotnet/roslyn/issues/24618
VSO [246053](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/246053)
VSO [530575](https://devdiv.visualstudio.com/defaultcollection/DevDiv/_workitems/edit/530575)

### Workarounds, if any

None.

### Risk

Medium. We mitigated risk by 
1) Testing manual and integration test scenarios regularly tested by Roslyn and the VS debugger vendors. Vendors signed off. 
2) Adding unit tests covering new code.
3) Buddy testing using scenario that stresses the new code paths (Tom McDonald)
5) Targeted and exploratory testing. [New scenarios](https://github.com/dotnet/roslyn/issues?q=is%3Aissue+label%3ATest-Scenario+) added to manual testing.
6) Dogfooding: @tmat using the new build to debug in Roslyn.sln. 
7) DDRITS and RPS tests pass. We are loading a couple more images during debugging scenario but that's expected since we moved the implementation to managed code and the number is below the regression bar for the scenario.

### Performance impact

Improves responsiveness during stepping.

### Is this a regression from a previous update?

No.

### Root cause analysis

The debugger enumerated all frames of all threads on every step on UI thread (regardless of whether a file was edited or not).

### How was the bug found?

PerfWatson reported UI delays.

### Test documentation updated?

Yes. New test scenarios added.

### CODE REVIEW

**Comment by tmat** [comment]
Previous version against 15.6: https://github.com/dotnet/roslyn/pull/24316

**Comment by jinujoseph** [comment]
@ivanbasov Can you review the last three commits pls

**Comment by tmat** [comment]
@MattGertz For approval.

**Comment by tmat** [comment]
@cston Thanks for additional review!

**Pull request merged**
