### PR TITLE
Include the actual underlying exception in "failed to run".

### PR DESCRIPTION
**Pull request by davkean**
This enables to actually diagnose TestRunner issues if an exception
occurs during execution.

### CODE REVIEW

**Comment by davkean** [comment]
@tannergooding @jaredpar @dotnet/roslyn-ide

**Comment by davkean** [comment]
Filed #6155 for the ETA failure.

retest prtest/win/dbg/eta please

**Comment by tannergooding** [comment]
@davkean, that will not currently work for the ETA failure. Please fixup the internal test runner (@brettfo, is currently working on merging them so that we have one test runner and it exists in Open).

**Comment by davkean** [comment]
There's already many differences between the internal one and this one (including changes you checked in last week). Ironically, the internal one doesn't actually suffer from this problem - because it leaks the exceptions and doesn't catch them.

We should rationalize this when we merge them, not on a change-by-change.

**Comment by davkean** [comment]
Ah, I get what you mean by "this won't work for the ETA failure".

Yes, I get that now. I changed to help me diagnose the issues locally, I spent 30 minutes trying to diagnose the CreateDirectory issue in the test runner that was broken on Thursday.

**Comment by davkean** [comment]
Filed https://github.com/dotnet/roslyn/issues/6166 for prtest/win/dbg/unit64.

retest prtest/win/dbg/unit64 please

**Pull request merged**
