### PR TITLE
Promote APIs shipped in VS 2015 Update 2

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
Move lines appearing in PublicAPI.Unshipped.txt files to PublicAPI.Shipped.txt files and re-sort the latter.

Note: VB scripting APIs and APIs for IOperation continue to remain unshipped.

I will also port this to master once its committed here. Let me know in case I should also port this to any other branches.

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
FYI @jaredpar @Pilchie @srivatsn @ManishJayaswal 
@dotnet/roslyn

**Comment by shyamnamboodiripad** [comment]
Ping @Pilchie @jaredpar @jasonmalinowski

Could some of you please take a look? I'd like to merge this to stabilization today (and port to master).

**Comment by jaredpar** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Note: for the master port, let it just flow through our usual integration processes. An eager port may just create duplicate work.

**Comment by shyamnamboodiripad** [comment]
Ah thanks I was not aware that we are porting regularly from stabilization to master. In that case, I will just allow the normal process to handle this.

**Pull request merged**
