### PR TITLE
Update optimization data to 2.7.0-beta3-62526-01...

### PR DESCRIPTION
**Pull request by KevinH-MS**
### Customer scenario

All VB/C# scenarios

### Bugs this fixes

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/498615
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/533397
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/559121
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/547161

### Workarounds, if any

None

### Risk

Negligible

### Performance impact

Improves elapsed time and image size for several scenarios

### Is this a regression from a previous update?

Yes

### Root cause analysis

Optprof updates are not automated

### How was the bug found?

RPS

### Test documentation updated?

N/A

### CODE REVIEW

**Comment by KevinH-MS** [comment]
retest this please

**Comment by KevinH-MS** [comment]
retest windows_release please

**Comment by KevinH-MS** [comment]
retest this please

**Comment by KevinH-MS** [comment]
@jasonmalinowski yeah, here were the initial results:  http://ddweb/dashboard/vsbuild/detail/val/27401.9000.kevinh.180201.190935

Everything is good ***except*** "open winform" 🤕  I've retrained the LanguageServices dlls (again) and will queue a new build.

FYI:

Name | Baseline | Current | Delta
-- | -- | -- | --
Microsoft.CodeAnalysis.EditorFeatures.Wpf.ni.dll | 3,092,480 | 1,101,824 | -1,990,656

**Comment by KevinH-MS** [comment]
Latest RPS results look good.

FYI @MattGertz for escrow approval

**Comment by MattGertz** [comment]
@KevinH-MS Thanks.  Please add the VSO PR link to each of the VSO bugs you list up top, and then tag me so I can submit them.  We'll need to move fast on these submissions as we are close to the wire.

**Comment by jinujoseph** [comment]
@KevinH-MS i can help with the bugs submission

**Comment by natidea** [comment]
Approved to merge via https://devdiv.visualstudio.com/DevDiv/_workitems/edit/498615

**Pull request merged**
