### PR TITLE
Removing the rest of PROTOTYPE comments from tuples branch

### PR DESCRIPTION
**Pull request by VSadov**
I think I have got them all...

See related issues:
https://github.com/dotnet/roslyn/issues/10862
https://github.com/dotnet/roslyn/issues/10861
https://github.com/dotnet/roslyn/issues/10857
https://github.com/dotnet/roslyn/issues/10856
https://github.com/dotnet/roslyn/issues/10853
https://github.com/dotnet/roslyn/issues/10852
https://github.com/dotnet/roslyn/issues/10851
https://github.com/dotnet/roslyn/issues/10849

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review

**Comment by jcouv** [comment]
From reading the issues you filed, I'm not sure how easy it will be to trace back to the location in code that prompted the issue.
For the issues I filed, I tried to be as specific as possible when filing issues corresponding to PROTOTYPE markers, including pointing to specific method or copying the code with PROTOTYPE comment. Consider doing something similar?

**Comment by jcouv** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by VSadov** [comment]
@jcouv - i tried to refer to approximate code location in issues that can have that. It just many of these issues are more broad workitems that would not have specific location in the code.
I think the issues are informative enough.

**Pull request merged**
