### PR TITLE
Fixed typo in private field name

### PR DESCRIPTION
**Pull request by bkoelman**

### CODE REVIEW

**Comment by davkean** [comment]
:+1: 

tag @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
:+1: Something tells me I also get to sorry about that. ;-)

**Comment by davkean** [comment]
okay to test
test eta please

**Comment by davkean** [comment]
Hold on merging this - we've had to force push master due to an accident merge from future -> master. We'll provide instructions soon on how to fix your history.

**Comment by jasonmalinowski** [comment]
@bkoelman, can you run this and force push to your PR branch?

    git rebase 015eff20126b8e85e1424cc22435c5bab0da1d25 --onto 5a97d296d3dedbe6cc7c580835da32adb3252d23

**Comment by jasonmalinowski** [comment]
retest this please

**Comment by bkoelman** [comment]
@davkean @jasonmalinowski Thanks for instructions and review.
PR updated, tests are failing though:

```
stderr: fatal: unable to access 'https://github.com/dotnet/roslyn.git/': Failed connect to github.com:443; No error
```

**Comment by davkean** [comment]
There's a test failure, I've filed https://github.com/dotnet/roslyn/issues/6932 to track it. It's not known.

retest prtest/win/dbg/unit32 please

**Comment by davkean** [comment]
Merging this in, thanks for the contribution!

**Comment by jasonmalinowski** [comment]
Yep, thanks for the contribution!

**Pull request merged**
