### PR TITLE
Revert test workaround for 64bit execution of TestAnalyzerLoading_Error

### LINKED ISSUE #4959: Analyzer test tries to load xUnit into app domain when executed in 64 bit.
The unit test [`Microsoft.CodeAnalysis.UnitTests.AnalyzerFileReferenceTests.TestAnalyzerLoading_Error()`](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,b04fd584904390af) fails in 64 bit because the assembly `xunit.dll` cannot be found.  The failing test is identical to [`TestAnalyzerLoading()`](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,196491df9b713bdb) which passes except for the different calls to `TestSuccess()` vs. `TestTypeLoadException()` which in turn both subscribe to the `AnalyzerFileReference.AnalyzerLoadFailed` event.  In the `TestSuccess()` case [here](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,67), the event is never fired when the test behaves as expected, but in `TestTypeLoadException()` [here](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,67), the event **is** fired when the test behaves as expected, and the current theory is that the 64 bit app domain isn't using the [`RemoteAssert`](http://source.roslyn.io/#Roslyn.Compilers.UnitTests/AnalyzerFileReferenceTests.cs,c835ffe2520b5e62) object from the first app domain (which eventually calls `Assert.True()` in `xunit.dll`), but is instead loading its own causing the attempted load of `xunit.dll`.

FYI @amcasey @tannergooding

### PR DESCRIPTION
**Pull request by mavasani**
See workaround added in #4960.
Test is now being executed only in 32bit.

Fixes #4959

### CODE REVIEW

**Comment by mavasani** [comment]
@brettfo

**Comment by brettfo** [comment]
@jaredpar: Since this test is now x86 only this check is indeed redundant, but I'm curious why `[ConditionalFact(typeof(x86))]` was added in 7688690d10f959743cfa659ce46529aa9b4c0e4c?

**Comment by jaredpar** [comment]
I'd like to to understand as well.  At a glance it looks like everything in that test could be run in 64 bit.

**Comment by brettfo** [comment]
@jaredpar: to clarify, that was your commit that made this test x86 only :)  Do you remember your reasoning?  If not, then it should probably be set back to a regular test and this issue approached from another angle.  IIRC, the original thought was that this is ultimately an xunit bug, because that's what appears to be trying to load xunit.dll in the other app domain.

**Comment by mavasani** [comment]
Yes, even I got confused by the history - my assumption was the test was turned off on x64 for some known limitation of new xunit, but poking more it seems that was not the case.

Let me follow up with @tmeschter offline to get more context on this test.

**Comment by mavasani** [comment]
@jaredpar @brettfo I have updated the PR to:

1. Simplify the test to avoid using a remote assert and
2. Remove the x86-only conditional fact on the test

**Comment by brettfo** [comment]
Thanks for fixing this!  :shipit:

**Pull request merged**
