### PR TITLE
LOC CHECKIN | roslyn - master | 20180112

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by tmeschter** [comment]
@sharwell This looks fine to me, but I'll leave merging it to the repo owners/contributors. I've got ten repos to keep track of (and likely more on the way) so I'm only going to step in where I'm needed, e.g. if I see a PR lingering.

**Comment by tmeschter** [comment]
@jinujoseph @jaredpar FYI that you've got a loc PR to review and merge. I'm tagging you as Productivity and Compilers are the primary teams using the repo.

I'm trying to get out of the business of merging these myself, as I've got 10+ repos to keep track of.

**Comment by jinujoseph** [comment]
looks good to me , @jaredpar any concern here

**Comment by jaredpar** [comment]
@tmeschter shoudln't this change be against dev15.7.x?

**Comment by tmeschter** [comment]
@jaredpar Is dev15.7.x flowing into master, or the other way around?

It probably doesn't matter, though. The plan of record is to keep the Loc team working against master for their regularly-scheduled passes, and then once a release branch enters escrow we'll schedule an additional pass of that branch to pick up any remaining items. That way we're not constantly randomizing them.

**Comment by jaredpar** [comment]
> Is dev15.7.x flowing into master, or the other way around?

de15.7.x is flowing into master. Hence this localization change won't ship in 15.7. 

> then once a release branch enters escrow we'll schedule an additional pass of that branch to pick up any remaining items

How will this work though? Are we just going to cherry-pick a whole bunch of loc changes into our escrow branches? That seems more costly than just changing the merge base here. 

@jasonmalinowski

**Comment by tmeschter** [comment]
@jaredpar @jasonmalinowski My thought is to have the loc team do a one-off pass over release branches once they enter escrow. They'll create a PR targeting the release branch, we'll merge it in, and from there the translations can flow automatically back into master. And even if they don't automatically flow, we'll pick them up the next time the Loc team does a pass over master.

**Comment by jasonmalinowski** [comment]
I would imagine retargeting isn't even safe. Pretend dev15.7.x and master had actually diverged. The compiler has a loc string in dev15.7.x that takes one parameter. They decided to reword the error message in master and now it takes two parameters. Do the loc tools catch this (that the .xlf and resource still don't match) and just don't loc, or will they embed the localized string, and hand a mismatched string to the product?

Otherwise agreeing with @tmeschter: at some point the loc team will run against dev15.7.x, they'll make a fix there, and things will flow. Whoever is handling that merge might have a nasty merge conflict, but that'll be the limit of problems.

**Comment by jaredpar** [comment]
> Whoever is handling that merge might have a nasty merge conflict, but that'll be the limit of problems.

That's my primary concern. This can all be avoided by simply re-targeting the PRs from the start.

**Comment by tmeschter** [comment]
@jaredpar @jasonmalinowski Merge conflicts in .xlf files should *always* be handled in the following manner:

1. Accept the changes from the _incoming_ branch as-is.
2. Rebuild to bring the .xlf files in-sync with the merged .resx/.vsct/.xaml/.whatever files.
3. Commit any changes to the .xlf files caused by the build.

This is always safe; the worst that can happen is that we might temporarily "lose" a translation for a string in the target branch, but this will be automatically corrected the next time the loc team does a pass and repopulates the proper value from their database.

So the impact of merge conflicts shouldn't be a concern here. Only the loc team should be thinking deeply about the content of the .xlf files; the rest of us should just let the tooling handle them.

**Comment by jaredpar** [comment]
> Accept the changes from the incoming branch as-is.

That doesn't seem right. In the case where resource files are static (no entries added or removed) then yes that makes sense. Once you start take adds / removes into account then conflicts can get more complex and can't be blanket accepted.

**Comment by tmeschter** [comment]
@jaredpar If a resource has been added, removed, or changed in a .resx (for example) then that will be taken care of in step 2. If a resource has been removed, then the corresponding translations will be removed from the .xlf files during the build. If a resource has been added, then placeholder values will be added to the .xlf files, with a notation signaling that the resources need translation. If a resource has changed, then the .xlf files will be updated to signal that the corresponding translations need to be reviewed and updated.

I'll say it again: _the system is setup such that devs do not need to think about and should not think about the content of the .xlf files_. That is the domain of the Loc team. Devs should defer to the processes and tools put in place.

**Comment by jaredpar** [comment]
Chatted with @tmeschter in person and sorted a few things out:

1. The process of getting LOC on our escrow branches is not cherry-picking these types of commits. Rather we will just ask LOC team to do a pass on the escrow branches. 
1. The manner in which the LOC PRs happen combined with our branch flow does open the possibility that a Tiger will be asked to resolve a conflict between two strings which are both marked as validly translated. Further the question of "which is more recent" will be potentially very ambiguous. This could lead to us temporarily having a valid, but out of date, string in our XLF files. Later PRs should fix this up though.

**Pull request merged**
