### PR TITLE
Warn if user replaces a method that overrides a metadata method with a property

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems?id=443523

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Looks like this:

image

**Comment by sharwell** [comment]
💭 Honestly, I would prefer to not offer the refactoring in this case.

**Comment by Pilchie** [comment]
The implementation looks okay to me.  I know that our principle is to show things with a warning, but in this case that feels a bit too much.

Maybe there is some middle ground heuristic where we don't show it for members from `object`, but don't block the general case?

**Comment by CyrusNajmabadi** [comment]
> Maybe there is some middle ground heuristic where we don't show it for members from object, but don't block the general case?

I'm good with that.  Esp as changing something like ToString will actually be pretty disastrous thanks to how this will go and fixup tons of references and other overrides.

**Comment by CyrusNajmabadi** [comment]
Done.

**Pull request merged**
