### PR TITLE
Properties pointing to themself in the '<see>' tag in GeneratorContexts.cs

### PR DESCRIPTION
**Pull request by piotrstenke**
Properties with the same name as the returned type point to themself in the '\<see\>' tag instead of the actual type.

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Review by sharwell — APPROVED** [review]

**Comment by sharwell** [comment]
@piotrstenke You are absolutely correct, thanks for this! It looks like we have a build problem right now, but we'll re-run the build and get this merged once that is sorted out.

**Comment by 333fred** [comment]
@piotrstenke you submitted this PR at just the right time to get hit by a bad merge in master. You'll need to merge master into your PR to get the build passing.

**Review by 333fred — APPROVED** [review]

**Comment by piotrstenke** [comment]
All should be ok now.

**Comment by AlekseyTs** [comment]
@piotrstenke Thanks for the contribution.

**Pull request merged**
