### PR TITLE
Simplify the smart tag text we show for 'Fully Qualify' and 'Add Imports'

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Part of the overall fix for: https://github.com/dotnet/roslyn/issues/5139

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Reviewers: @balajikris, @basoundr, @brettfo, @davkean, @DustinCampbell, @dpoeschl, @Pilchie @jasonmalinowski

**Comment by jmarolf** [comment]
:+1:

**Comment by DustinCampbell** [comment]
And since it becomes a language keyword, it no longer requires localization. Nice! :+1:

**Comment by Pilchie** [comment]
What about C#?

**Comment by CyrusNajmabadi** [comment]
> What about C#?
The fully qualify change was for C# and VB.

The 'Add imports' change was only for 'VB' because C# already uses the form I converted VB to using.  i.e. in C# is already is shown as "using System.Blah;"

**Comment by Pilchie** [comment]
Ah, got it.

**Pull request merged**
