### PR TITLE
Fix test trait

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by NextTurn** [comment]
@jasonmalinowski This test is skipped when I run tests in the Test Explorer.

**Comment by jasonmalinowski** [comment]
@NextTurn Sorry, still confused -- are you actually seeing it being skipped if you explicitly run it, or you were running all tests with the trait and then this one got skipped because of that?

**Comment by NextTurn** [comment]
@jasonmalinowski Sorry, I can't reproduce that. It's not skipped now.

**Comment by jasonmalinowski** [comment]
Thanks @NextTurn for the fix!

**Pull request merged**
