### PR TITLE
Link to test plans for records and patterns

### PR DESCRIPTION
**Pull request by jcouv**

### CODE REVIEW

**Comment by jcouv** [comment]
Tagging @gafter @agocke for review (doc only)

**Comment by gafter** [comment]
It feels strange for "progress" to link to the test plan.  The state of the pattern-matching implementation is tracked at https://github.com/dotnet/roslyn/issues/41502, not https://github.com/dotnet/roslyn/issues/40727 .

**Comment by jcouv** [comment]
@gafter Previously we didn't have two issues tracking feature work. What's the intended difference between the implementation issue and the test plan? Could we merge them?

**Comment by gafter** [comment]
The test plan tracks test work. The implementation tracks compiler work. Both are needed. Tracking the former is the responsibility of the co-developers. Tracking the latter is the responsibility of the developer.

**Comment by gafter** [comment]
The outstanding work issue for pattern-matching is sort of the equivalent of https://github.com/dotnet/roslyn/issues/17952 for default implementation methods.

**Comment by jcouv** [comment]
Updated to have both links

**Pull request merged**
