### PR TITLE
set roslyn service hub process to have below normal process priority

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @KevinH-MS @CyrusNajmabadi @panopticoncentral @dotnet/roslyn-ide can you take a look?

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by heejaechang** [comment]
retest  windows_debug_unit64_prtest please

**Comment by Pilchie** [comment]
:+1:, though do note that we'll want to be careful about contention for the disk with VS.

**Pull request merged**
