### PR TITLE
Don't generate a binding redirect for Microsoft.Build.Tasks.CodeAnalysis

### PR DESCRIPTION
**Pull request by amcasey**
Hopefully, this will fix internal bug 157535.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @jasonmalinowski @jaredpar @agocke 
FYI @dpoeschl - this probably explains the CSharpRename hang
FYI @dotnet/roslyn-infrastructure

**Comment by amcasey** [comment]
Does this need to go into stabilization?

**Comment by Pilchie** [comment]
Why do we not want the binding redirect?  Because it's always loaded by name using the `AssemblyFile` attribute?

**Comment by amcasey** [comment]
@davkean said it was because it's loaded via ```LoadFrom```.  @jasonmalinowski might have his own reasons.

**Comment by jasonmalinowski** [comment]
Two reasons:

1. The thing @amcasey already said @davkean said. Since it's being LoadFrom'ed, the assembly version doesn't actually matter here.
2. In experimental builds, our redirect also sets a CodeBase to attempt to find that binary within the extension. The VisualStudioSetup extension doesn't ship one, and so if you had VisualStudioSetup experimentally installed, this redirect may specify a codebase to something that doesn't exist and random things break.

Note that the compiler VSIX I'm working on right now *will* specify the redirect since it's shipping it's own copy that you want to load. That's more just to get the codebase attribute; the redirect itself is in theory meaningless.

**Comment by davkean** [comment]
:+1:

**Comment by amcasey** [comment]
@Pilchie Remaining concerns?
@jasonmalinowski @davkean Stabilization?

**Comment by Pilchie** [comment]
No remaining concerns from me.  :+1:

**Comment by jasonmalinowski** [comment]
I would expect this to go into stabilization. If we can't do that I think we'll still be OK for experimental extension support but obviously I haven't tested that...just thought about it.

**Comment by amcasey** [comment]
@Pilchie @ManishJayaswal Okay for stabilization?

**Comment by Pilchie** [comment]
Yes.  Let's take this for stabilization.

**Comment by amcasey** [comment]
Closing in favor of Stabilization PR.

**Pull request closed without merging**
