### PR TITLE
Backport #46237 to dev16.7: Report teh project name that we were unable to recover a symbol from.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Adding more logging information to help us root cause why a certain intermittent failure is happening between VS and OOP.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jinujoseph this is the same PR (no additional changes), just made against dev16.7

**Comment by JoeRobich** [comment]
> just made against dev16.7

@CyrusNajmabadi  Should this PR target release/dev16.7?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Should this PR target release/dev16.7?

Yup!  Sorry about that :)

**Comment by JoeRobich** [comment]
These integration issues are the one we expect from the version of VS that is running our integration tests. Merging

**Pull request merged**
