### PR TITLE
Update language feature status doc.

### PR DESCRIPTION
**Pull request by 333fred**
@jaredpar @jcouv for review. I'm optimistically assuming that https://github.com/dotnet/roslyn/pull/54724 will be merged before this is. I'm also not 100% certain that _all_ the lambda features are in, but certainly a portion of them are? LMK if you think I should break them out into what's been implemented or if this is good.

### CODE REVIEW

**Review by RikkiGibson — APPROVED** [review]

**Comment by jcouv** [comment]
"Static Abstract Members In Interfaces" should stay under C# Next.

**Comment by 333fred** [comment]
> "Static Abstract Members In Interfaces" should stay under C# Next.

I considered this, but I specifically renamed it to "Preview" and put it under 10 because my assumption is that, once we start implementing any feedback from the preview, we'll want to have another feature branch and it will be good to have a separate listing maintaining when the initial preview shipped.

**Comment by 333fred** [comment]
> I'd agree with moving it if the sections were Roslyn versions. But we're using C# versions and this feature it's not part of C# 10.

The preview is part of the C# 10 release cycle. As I said, we use this document to keep track of when things are released. This was released, in preview, as part of the C# 10 release cycle. Next year, when we release for real, we'll have a separate section for C# 11 that includes the non-preview version of this feature, and we will still want to know when the preview was merged.

**Comment by 333fred** [comment]
> Yes and that is tracked by the Status column already.

Where would you propose that we put this feature when C# 11 comes out? Again, remember that there will be _two_ rows: one for the initial preview, one for the final version.

**Comment by jcouv** [comment]
I'm not convinced that we're going to have a second iteration on this feature. My expectation is that we'll add three small satellite features, but likely leave the main feature alone.

But assuming we do need two waves, we'll have the choice of having two links in Status column ("wave 1 merged in dev17p2, wave 2 in progress") or using two rows. Either is fine with me.
Once the feature is released in C# 11, we just move the row (or rows) into C# 11 section.

**Review by jcouv — APPROVED** [review]

**Pull request merged**
