### PR TITLE
Port CA1027 and CA2217 (Mark\Do not mark Enums with FlagsAttribute) to S...

### PR DESCRIPTION
**Pull request by srivatsn**
...ystem.Runtime.Analyzers

This is a straightforward move as the fixer was already built on SyntaxGenerator. It had C#\VB specific fixers though because for VB, to replace the node, it needed to know the distinction between block\statement. DocumentEditor.ReplaceNode abstracts that and so we can have a unified fixer. The analyzer was branching out for getting the location and that's not really needed.

### CODE REVIEW

**Comment by srivatsn** [comment]
@shyamnamboodiripad @mavasani @heejaechang @tmeschter @jmarolf - please take a look

**Comment by tmeschter** [comment]
:+1:

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by srivatsn** [comment]
@dotnet-bot test this please

**Comment by srivatsn** [comment]
One more review please?

**Comment by heejaechang** [comment]
:+1:

**Pull request merged**
