### PR TITLE
Add tests for simplifying type names

### LINKED ISSUE #15996: "Simplify type name" doesn't work when accessing constant/static member from type in VB
``` VB

Module Module1

    Sub Main()

        Dim var As UInt32 = UInt32.MinValue

    End Sub

End Module

```

Expected: Simplify type name to fire both on the type declaration and constant access
Actual: Simplify type name only fires on the type declaration

This works in C#.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #15996

@davkean Can you verify that these tests reflect your scenario? I was not able to reproduce the described behavior, so perhaps it has since been fixed?

@dotnet/roslyn-ide for review

## Ask Mode

**Customer scenario**

This change only adds tests. It does not change code distributed to customers.

**Bugs this fixes:**

N/A. The original bug was fixed at an unknown point but these regression tests were not added.

**Workarounds, if any**

N/A

**Risk**

Very low. Only possible issue is a broken build due to failing tests.

**Performance impact**

None (no changes are made to production code).

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

N/A

**How was the bug found?**

Internal customer (@davkean).

### CODE REVIEW

**Comment by davkean** [comment]
I can't verify this is fixed or not, I can't find the opt to turn this on: 
image

**Comment by sharwell** [comment]
@davkean Bug #15996 specifically concerns **Predefined type preferences** &rarr; **For member access expressions** &rarr; **Prefer predefined type**.

**Comment by sharwell** [comment]
@MattGertz for Ask Mode

**Comment by MattGertz** [comment]
@sharwell No approval needed for test-only changes.

**Pull request merged**
