### PR TITLE
Remove ILegacyIndentationManagerWorkspaceService

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1656187

The editor service can't be safely used on background thread. 
Issue https://github.com/dotnet/roslyn/issues/61109 tracks work to infer white space for all documents, if we want to implement white space inference correctly.

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by tmat** [comment]
@CyrusNajmabadi Rebased to 17.4 and fixed VB

**Review by jasonmalinowski — APPROVED** [review]
So the code change makes sense but I'm still a bit confused why this got worse, or why we're having to make this change now when we've had this code for awhile. Did something change to start this appearing more than before?

**Comment by tmat** [comment]
IDK why it started showing up more. Not sure if it makes sense to spend too much time deliberating on why. Doing the inference outside of command handlers has always been iffy. When refactoring options I tried to preserve as much behavior as possible since it was a huge set of changes. This PR follows up with applying the correct pattern to the remaining code that wasn't cleaned up yet by previous options changes (VB commit command handlers) and then removing the legacy behavior.

**Comment by arkalyanms** [comment]
> IDK why it started showing up more. Not sure if it makes sense to spend too much time deliberating on why. 

We will need to understand why this started showing in 17.4 for QB approval. It looks like the current theory is the way the failure was getting bucketized was changed. @davkean to see if he knows.

@jinujoseph for soft approval request.

**Review by arkalyanms — APPROVED** [review]

**Comment by jinujoseph** [comment]
@tmat this started showing up very recently in preview4 so if we cann't connect to any churn that might have caused this then might be risky to take the fix. 

@arkalyanms lets get the fix in 17.5.Preview1 and we can monitor if hits disappear and bring in back in 17.4 in servicing as needed

**Comment by tmat** [comment]
@jinujoseph Unfortunately, this is a race condition and might be hard to pinpoint specific change. Anything that changed the timing and order of operations might contribute.

**Comment by arkalyanms** [comment]
Already merged the 17.5 P1 targeted fix. It should hit main tomorrow. We also have an email chain with editor team to understand the right fix and source of the regression better.

cc: @jinujoseph, @tmat

**Comment by arkalyanms** [comment]
Closing this one against 17.4 in favor of a more tactical fix to just prevent the crash. We are planning to use 17.5 to gauge if removing this feature altogether is in fact an acceptable way forward. But its too risky for 17.4.

cc: @jasonmalinowski

**Pull request closed without merging**
