### PR TITLE
Don't embed IBC data in PR builds...

### LINKED ISSUE #12636: IBCMerge sporatically fails
PR: [#1180](https://github.com/dotnet/roslyn-internal/pull/1180) *Revert previous integration change now that open side has gone through.* by @CyrusNajmabadi
Failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_prtest/385/

**Issue 1: MSBuild Error**
error MSB3073: The command ""d:\j\workspace\windows_vsi_p---9267604d\Closed\Tools\ibcmerge\IBCMerge.exe" -q -f -partialNGEN -minify -mo "d:\j\workspace\windows_vsi_p---9267604d\Open\Binaries\Obj\EditorFeatures\Release\Microsoft.CodeAnalysis.EditorFeatures.dll" -incremental "C:\Users\dotnet-bot\.nuget\packages\RoslynDependencies.OptimizationData\1.3.0-beta5-60518-02\content\OptimizationData\Microsoft.CodeAnalysis.EditorFeatures.pgo"" exited with code -1. [d:\j\workspace\windows_vsi_p---9267604d\Open\src\EditorFeatures\Core\ep3fwyrh.tmp_proj]

### PR DESCRIPTION
**Pull request by KevinH-MS**
Fixes #12636

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @mavasani @tannergooding 
/CC @dotnet/roslyn-infrastructure

**Comment by tannergooding** [comment]
LGTM (although, I think it might still build for VSI PRs)

**Comment by KevinH-MS** [comment]
Hmmm...is there some other property we could check that all the PR builds set (or don't set)?

**Comment by mavasani** [comment]
👍 VSI PRs now set official build = false, so we should be good.

**Comment by tannergooding** [comment]
I don't believe so (but VSI tests are also not run by default, so it might be ok).

**Pull request merged**
