### PR TITLE
Add FadingOptionsProvider

### PR DESCRIPTION
**Pull request by JoeRobich**
Resolves https://github.com/dotnet/roslyn/issues/53872

Without the OptionsProvider the fading options are not available from OOP and the default value of `true` is used instead.

### CODE REVIEW

**Review by sharwell — APPROVED** [review]

**Review by davidwengier — APPROVED** [review]

**Comment by sharwell** [comment]
@jinujoseph for 16.11 approval (I am in favor of this)

**Comment by jinujoseph** [comment]
Will approve once branch is open for 16.11.Preiew3 ( cc @Rikki)

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
[Automation object](https://github.com/dotnet/roslyn/blob/release/dev16.11/src/VisualStudio/CSharp/Impl/Options/AutomationObject.cs) needs to be updated for this option to be persisted correctly.

(Note: this will conflict with main later, but shouldn't be much of pain to resolve the conflict later on)

**Comment by JoeRobich** [comment]
> [Automation object](https://github.com/dotnet/roslyn/blob/release/dev16.11/src/VisualStudio/CSharp/Impl/Options/AutomationObject.cs) needs to be updated for this option to be persisted correctly.

Thanks @Youssef1313! Updated.

**Pull request merged**
