### PR TITLE
Handle "Color color" from VB completion

### LINKED ISSUE #3086: VB intellisense doesn't show "color color" cases
As per the screenshot below, VB completion list isn't showing static members off of an instance, even though the "color color" rule lets the compiler happily consume them.

intellisense-vb-color-color

WHAT I EXPECT: completion list should show Y.
WHAT I GET: it doesn't.

This repro shows a const member "Y". The same bug also manifests for *shared* members in class C.

### PR DESCRIPTION
**Pull request by rchande**
Fixes #3086.

### CODE REVIEW

**Comment by rchande** [comment]
test this please

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
retest this please

**Comment by Pilchie** [comment]
This good to merge, right?

**Comment by rchande** [comment]
Yes; was waiting for the merge build.

**Pull request merged**
