### PR TITLE
Updating the netci.groovy script to use 'latest-or-auto-dev15'

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jaredpar, @jasonmalinowski, @brettfo

### CODE REVIEW

**Comment by tannergooding** [comment]
test ci please

**Comment by jaredpar** [comment]
This removes all of our Dev14 validation though.  We need to keep some validation here.

**Comment by tannergooding** [comment]
@jaredpar, how? The image still contains VS2015.3 and VS2015 is still being used to build Roslyn.

This just adds Dev15 to the image so that it is available for use.

**Comment by tannergooding** [comment]
This resolves https://github.com/dotnet/roslyn/issues/12118

**Comment by jaredpar** [comment]
If that's the case then we should choose a better name for this image.  I don't think any reasonable developer is going to look at `latest-or-auto-dev15` and conclude that `dev14` is also installed.

**Comment by tannergooding** [comment]
@jaredpar, the image also contains VS2013.5 :smile:

**Comment by tannergooding** [comment]
test ci please

**Comment by jasonmalinowski** [comment]
:+1:, but I do have to agree the naming is a bit confusing.

**Pull request closed without merging**
