### PR TITLE
Revert NuGet back to 3.2.1.10581

### PR DESCRIPTION
**Pull request by davkean**
This prevents us from hitting #6981.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure Please review this quickly, we're running into NuGet restore issues on all the internal builds.

**Comment by amcasey** [comment]
`git revert 851f060f3f18cc1585a0ef1a3caa5e23bb8f69eb`?

**Comment by amcasey** [comment]
Sorry, that was the merge.  It looks like we actually want to revert 13896cff6bfa929593ee6675e6cb901fd718019a.

**Comment by davkean** [comment]
So I did that, have pushed it, but it results in the same thing. What's the difference?

**Comment by amcasey** [comment]
@davkean I don't believe git has checkin kinds the way TFS does, but it still uses standardized text for revert commits that make it easier to see what's going on.  Functionally, I don't believe there's a difference.

**Pull request merged**
