### PR TITLE
make formatting performance better

### PR DESCRIPTION
**Pull request by heejaechang**
this performance improvement is particularly for devdiv bug # 1089540

this makes the file in the bug to be formatted in several seconds compared to several minutes on my machine.

there were several issues. each one fixed by

#1, use concurrency on gathering operations.
#2, don't use too much time to split work to chunks if that requires more work than actually formatting.
#3, don't blindly set beginning of a file as inseparable start point for certain formatting options.

...

but these don't actually address the most impactful root cause of this perf issues. which is perf issue of GetPrevious/GetNextToken API in compiler.
(https://github.com/dotnet/roslyn/issues/3244)

formatter internally uses GetDescendantTokens to get all tokens at once and cache them which takes less than 1 second for the entire file (2M bytes size) in the bug. and use the cache internally.

but certain part of formatter (Rule Provider) can't use that internal cache, so it has to use the GetPrevious/GetNextToken to move around tokens, which in this particular bug, takes more than 40 seconds on my machine. and that is not even for entire file. (less than 1/12 of tokens)

I opened a bug to compiler team, hopely so that we can get better perf on those APIs.

in this PR, I mitigated the issue either by making more things to run concurrently or by changing logic which requires those APIs.

### CODE REVIEW

**Comment by heejaechang** [comment]
related to #3229

**Comment by heejaechang** [comment]
@mattwar @jmarolf @dpoeschl @Pilchie @balajikris can you take a look? thank you.

**Comment by heejaechang** [comment]
missed @rchande

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by mattwar** [comment]
:+1:

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Pull request merged**
