### PR TITLE
Stop exposing imports to #loaded files

### LINKED ISSUE #5423: Usings should not propagate into or out of #loaded scripts
Script.csx:
```C#
using System.IO;
/* System.Text is not in scope here */
```

Interactive:
```C#
using System.Text;
#load "script.csx"
/* System.IO is not in scope here */
```

### PR DESCRIPTION
**Pull request by amcasey**
Fixes #5423 

Note: all commits but the last come from https://github.com/dotnet/roslyn/pull/5788.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @dotnet/interactive
FYI @gafter @MadsTorgersen @AlekseyTs

**Comment by amcasey** [comment]
Test this please

**Comment by cston** [comment]
LGTM

**Comment by amcasey** [comment]
test this please

**Pull request merged**
