### PR TITLE
Don't suggest type arguments in VB Crefs

### LINKED ISSUE #714: [CodePlex] VB xml-doc-comment shouldn't show completion list for generic type parameters
Ported from TFS WorkItem: **1087446**

------------------------------

**Repro Steps:**

**Changes to this WorkItem will <u>not</u> be reflected in CodePlex and may<br>be automatically overwritten!**<br>Please go to [http://roslyn.codeplex.com/workitem/435](http://roslyn.codeplex.com/workitem/435) to modify this bug<br>(*unless you are assigning, resolving, closing or adding private comments*).<br>**--------------------------------------------------------------------------------**<br><br>***lwischik** reported:*<br><br>See attached picture. Inside an xml-doc-comment when I type<br><br>```vb<br>''' &lt;summary&gt;<br>''' &lt;see cref="List(Of |<br>```<br>then the thing I'm typing is a _formal type parameter_. It is not a type _argument_.<br><br>What I expect: since it's a type argument, then no intellisense-completion-list should pop up while I'm typing.<br><br>What I get: it does.

------------------------------

**Revisions:**

1) Created By Visual Studio Languages Snap Account (11/24/2014 5:16:33 PM)

------------------------------

2) Edited By Vladimir Sadov (11/25/2014 11:05:35 AM)

Is this something in IDE or just artefact of parser error recovery?

------------------------------

3) Edited By Kevin Pilch-Bisson (2/19/2015 1:44:15 PM)

Port to GitHub

------------------------------

### PR DESCRIPTION
**Pull request by rchande**
Fixes #714.

Can you take a look? @balajikris @basoundr @davkean @dpoeschl @jmarolf @jasonmalinowski @Pilchie

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by rchande** [comment]
Failing tests are all compiler tests.

test this please

**Comment by rchande** [comment]
test this please

**Comment by rchande** [comment]
Thanks, @Pilchie.

**Pull request merged**
