### PR TITLE
Made BoundNodeClassWriter an abstract class.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Pulling the language specific parts into derived classes.
Part of the work for Issue #22461 

**Important this changes the layout of the generated files**
 * Currently just bound nodes.
So requires a carefully review to see if the changes hasn't affect the behave of the nodes.

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by AdamSpeight2008** [comment]
@gafter Ready for Review.

**Comment by AdamSpeight2008** [comment]
@AnthonyDGreen Please may I have a review?

**Comment by AdamSpeight2008** [comment]
@jcouv Is this ready for review?

**Comment by jaredpar** [comment]
Why are you sending this PR? Don't see any justification for making this type of change.

**Comment by AdamSpeight2008** [comment]
@jaredpar In this pull request the generation is separated for each language C# and VB both inheriting a common base. Makes altering the generated code for a specific language easier. It also update the code used be the generator and generated to use more recent language features. Which in turn makes the generated code simpler (relatively speaking).

**Comment by jaredpar** [comment]
The effect of this change seems to be changing the VB style of the generated code. We've many, many times asked that you not make changes of this nature. There is no way for us to be any clearer on this point.

**Comment by AdamSpeight2008** [comment]
@jaredpar Yet again you've seemed to missed the main point of the pull request *by focusing primarily on stylistic* of the refactoring out the specific implementation for each language.
Examination of the generation code, you;d have seen commented out sections the produced the original style, and changing were a test to see how easy it would be to "modernise" the generated code to use say `auto properties` `interpolated strings` `nameof()` etc.

**Comment by jaredpar** [comment]
> Yet again you've seemed to missed the main point of the pull request by focusing primarily on stylistic of the refactoring out the specific implementation for each language.

We've been crystal clear on this point ever since we've been on Github. We will **not** accept PRs that consist of large style changes to the existing code. This is a part of our contribution guidelines and has been communicated to you directly many times. 

At this point I can only conclude you are deliberately ignoring our feedback here. Further PRs which consist of large style changes will be closed without comment.

**Pull request closed without merging**
