### PR TITLE
17.10: Cherry-pick fix for scenario where lightbulbs weren't being displayed

### PR DESCRIPTION
**Pull request by ToddGrun**
Cherry-pick https://github.com/dotnet/roslyn/commit/c5e8624c7601a2d04424cfb00b3899bb57ca0dc6 from fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2087100 to 17.10

### CODE REVIEW

**Comment by ToddGrun** [comment]
Tagging @arkalyanms. There were a couple merge conflicts. I'm fairly confident in that I resolved them correclty, but it would be nice to get some verification that things are working as I haven't done any validation other than manual code inspection and building.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
@arkalyanms We coudl take this, but my preference would be to just say: "this is fixed in 17.11. sorry, please move to that if this is affecting you".

**Comment by ToddGrun** [comment]
@arkalyanms -- test failures, even on rerun, that don't appear to be related. Are tests on ci for the 17.10 branch in a working state?

**Comment by arkalyanms** [comment]
> @arkalyanms We coudl take this, but my preference would be to just say: "this is fixed in 17.11. sorry, please move to that if this is affecting you".

17.10 is LTS and support last 2 years longer than 17.11, so we need the port.

**Comment by arkalyanms** [comment]
Failed again. If empty PR still fails, lets disable the test and create a bug. @jaredpar fyi as Box.

**Comment by jaredpar** [comment]
This is a servicing branch, there isn't much of an expectation that integration tests will run here successfully given that they're running on VS latest, not 17.10. Generally we ignore them in servicing if we reasonably don't think they're related.

**Comment by ToddGrun** [comment]
> If empty PR still fails

Same tests fail in dummy PR: https://github.com/dotnet/roslyn/pull/74821

**Comment by arkalyanms** [comment]
> > If empty PR still fails
> 
> Same tests fail in dummy PR: #74821

Thanks for checking, merging PR.

**Pull request merged**
