### PR TITLE
Remove PackageTargetFallback

### PR DESCRIPTION
**Pull request by tmat**
**Customer scenario**

Removes package target fallbacks from most projects, making them pure netstandard.

**Bugs this fixes:**

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

None.

**Is this a regression from a previous update?**

**Root cause analysis:**

**How was the bug found?**

Planned work.

### CODE REVIEW

**Comment by sharwell** [comment]
I am a big fan of this effort. 👍

**Comment by tmat** [comment]
@rchande Is windows_eta_open_prtest failure expected? 

> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by rchande** [comment]
@tmat ETA fixes are underway :) https://github.com/dotnet/roslyn-internal/pull/1862

**Comment by tmat** [comment]
@jasonmalinowski @jaredpar Please review.
@MattGertz @MeiChin-Tsai for ask mode approval.

**Comment by MattGertz** [comment]
OK from my side.

**Comment by tmat** [comment]
@MeiChin-Tsai Ping

**Comment by tmat** [comment]
test windows_eta_open_prtest  please

**Comment by MeiChin-Tsai** [comment]
Approved.

**Pull request merged**
