### PR TITLE
Delete unused SQM interfaces

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@tmat IIRC we had somebody pulling this in via InternalsVisibleTo. We sorted that out?

**Comment by tmat** [comment]
What? :(

**Comment by tmat** [comment]
@jasonmalinowski Checking with TypeScript...

**Comment by tmat** [comment]
TypeScript doesn't. F# also doesn't. So I think we are good.

**Comment by jasonmalinowski** [comment]
It was something in the core VS tree, like some FxCop tooling or something. :-(

**Comment by tmat** [comment]
How do they have internals-visible-to?

**Comment by tmat** [comment]
Well, will see... if something breaks we can copy the source to whatever it used it.

**Pull request merged**
