### PR TITLE
made InternalsVisibleToMoq item hidden in solution explorer

### PR DESCRIPTION
**Pull request by heejaechang**
@Pilchie @dpoeschl can you take a look?

### CODE REVIEW

**Comment by dpoeschl** [comment]
:+1:

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

linux machine failed.

**Comment by heejaechang** [comment]
@dotnet-bot test linux please

**Comment by heejaechang** [comment]
@dotnet-bot retest win please

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Pull request merged**
