### PR TITLE
Remove TestUtilities.FX45

### PR DESCRIPTION
**Pull request by jaredpar**
This project is no longer necessary.  It used to help us get TDD working fine in Visual Studio.  That's no lonegr needed with the recent build cleanup.  TDD still functions with this project removed.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure

**Comment by jaredpar** [comment]
Closed PR https://github.com/dotnet/roslyn-internal/pull/1551

**Comment by jasonmalinowski** [comment]
@jaredpar: no deletion of the project itself?

**Comment by jaredpar** [comment]
@jasonmalinowski weird.  Must have been a bad merge in the rebase.

**Comment by jaredpar** [comment]
@jasonmalinowski removed

**Pull request merged**
