### PR TITLE
Un-redirect Console.Out at the end of each test

### PR DESCRIPTION
**Pull request by amcasey**
The InteractiveSessionTests were redirecting ```Console.Out``` to a
```StringWriter``` and then disposing of the ```StringWriter``` breaking
downstream tests that attempted to write to ```Console.Out```
(specifically, ```ScriptTests.TestRunVoidScript```).

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @tannergooding

**Comment by amcasey** [comment]
FYI @KevinH-MS

**Comment by KevinH-MS** [comment]
LGTM :+1:

**Comment by tannergooding** [comment]
:+1:, but I think @tmat brings up a good point in moving this to a shared test utility library

**Pull request merged**
