### PR TITLE
Fix a few outlining unit tests that were not awaiting their results

### PR DESCRIPTION
**Pull request by DustinCampbell**
Tagging @dotnet/roslyn-ide

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by davkean** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
This isn't out for review yet :)   That's why i haven't tagged anyone.

**Comment by DustinCampbell** [comment]
Hmmm... 4 hours pass but the ETA tests haven't even started? Sounds fishy...

**Pull request merged**
