### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160423-150026
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160423-150026 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by JohnHamby** [comment]
test vsi please

**Comment by JohnHamby** [comment]
test vsi please

**Comment by JohnHamby** [comment]
Merging with a mysterious failure in BasicLineSeparators integration test.

**Comment by mavasani** [comment]
@JohnHamby I am seeing BasicLineSeparators VSI test failing on my PR as well: http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_vsi_p0/423/consoleFull#-58729591661aefe2b-268e-4e71-8c03-11b4c0acbfbc

Do we have an open issue tracking this flakiness? Otherwise, I'll open one.

**Comment by mavasani** [comment]
I filed https://github.com/dotnet/roslyn/issues/10916. Feel free to dupe it if an issue already exists.

**Pull request merged**
