### PR TITLE
Use common output directory for Samples.

### PR DESCRIPTION
**Pull request by jmarolf**
@davkean @davkean  @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean @davkean

### CODE REVIEW

**Comment by jmarolf** [comment]
retest vsi please

**Comment by davkean** [comment]
:+1:

**Comment by davkean** [comment]
@Pilchie and @ManishJayaswal This change to reduce PR and rolling build failures due to samples racing by copying the same binaries over each other.

**Comment by davkean** [comment]
This is a trial - I want to turn this on for the whole tree, https://github.com/dotnet/roslyn/issues/8975.

**Pull request merged**
