### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160226-054620
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160226-054620 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by davkean** [comment]
test vsi please
test eta please

**Comment by davkean** [comment]
I'm looking into the unit test failures.

**Comment by TyOverby** [comment]
@davkean All of your tests passed, and my conflict resolution was very minor.  Could we click the merge button?

**Comment by davkean** [comment]
Go head, is internal ready?

**Comment by TyOverby** [comment]
@davkean no, but I don't think there's a cross-cutting change?

**Comment by davkean** [comment]
ok

**Pull request merged**
