### PR TITLE
move workspace event to background thread.

### PR DESCRIPTION
**Pull request by heejaechang**
now feature that wants to run things on UI thread, must do so by themselves.

 #1644

### CODE REVIEW

**Comment by heejaechang** [comment]
@mattwar @jasonmalinowski @dpoeschl @Pilchie can you take a look please?

**Comment by mattwar** [comment]
If we do this, then it will make it impossible for me to remove race condition for code removing event handlers (if running on same thread as event fires from), since they will always be a different thread.

**Comment by Pilchie** [comment]
:-1:

I really don't like this.  People have an expectation in .NET that if they are in single threaded app that events will fire on the same thread that they subscribed on, and that there will not be a race where they unsubscribe and still get events after that.  This change would break both of those assumptions across the board.

(We already cheat a little bit, because we only use the synchronization context, so if they subscribe in a console app, the race is still there, but at least in VS we don't violate it).

**Comment by heejaechang** [comment]
@mattwar I opened this issue based on conversation over email. I thought at the time, people agreed over the change.

@Pilchie regardless synchronization context, our event is Async event using listener snapshot, which means we never guaranteed what you were saying. 

if, at the point, event happened, if listener was there, regardless whether listener is removed or not after that point, event will be sent.

..

also I am not sure fixing that has anything to do with thread it is raising event, we already uses queue to guarantee event ordering.

**Comment by Pilchie** [comment]
@heejaechang see PR #2056.

**Comment by heejaechang** [comment]
@Pilchie @mattwar so the #2056 assumes people who register and unregister events will be on UI thread as well? I am not sure whether that is even true. diagnostic service and others which is MEF based that can created from any thread, subscribe and unsubscribe from any thread. so I am not sure whether what it does is better or not. since at least before subscriber was guaranteed to have all events happened regardless when it unsubscribed as long as event happened before unsubscription.

and I think it is not actually threading issue if we want to solve race.

**Comment by heejaechang** [comment]
@Pilchie @mattwar I added some comment on #2056

**Comment by jasonmalinowski** [comment]
This is a fairly significant change to be making to APIs at this point -- how do we know people won't be broken by this?

**Comment by CyrusNajmabadi** [comment]
I'm also concerned a bit by this.  I've checked the TypeScript codebase, and we currently do *not* assume that Workspace events fire on the UI thread.  That said, it's possible we do depend on that in some way (for example, avoiding some race condition that i'm unaware of).  I'm worried a change here could introduce hard to track down race conditions late in the ship cycle.

**Comment by jasonmalinowski** [comment]
Yeah, at this point I think we'd need to get binaries produced and give them to partner teams to test with before we should be making a change like this.

**Pull request closed without merging**
