### PR TITLE
Fix spanish build

### PR DESCRIPTION
**Pull request by agocke**
Set the current culture to english for validating exception messages

### CODE REVIEW

**Comment by jaredpar** [comment]
approved

**Comment by agocke** [comment]
@AlekseyTs pointed out that this should be done as part of `/preferreduilang`. We may have an actual bug here.

**Comment by agocke** [comment]
OK, I think I know the problem. I think exceptions are reported using *CurrentCulture* instead of *CurrentUICulture*. `/preferreduilang`, of course, only sets the latter. Let's see if the latest change fixes the problem.

**Comment by agocke** [comment]
I found the problem. It's not CurrentCulture being used, it's that Windows is the one responsible for formatting this particular error message, but this error message doesn't appear to have an English localization in the Spanish install pack. I've worked around this problem by cutting out the exception message, since this isn't really necessary to verify the problem and the fix.

**Comment by agocke** [comment]
@jaredpar This is ready for re-review

**Pull request merged**
