### PR TITLE
use DebugType settings from VSL.Settings.targets

### PR DESCRIPTION
**Pull request by ctaggart**
by removing `<DebugType>` lines from projects that import `VSL.Settings.targets`

code to make the change was:
``` fs
open System.IO

let printfn format = Printf.ksprintf System.Diagnostics.Debug.WriteLine format

let hasString str (line: string) = line.Contains str
let hasDebugType = hasString "<DebugType>"
let hasVslSettingsTargets = hasString "VSL.Settings.targets"

let fileHasString hasString file =
    File.ReadLines file
    |> Seq.tryFind hasString
    |> Option.isSome

let removeDebugTypeLines file =
    let lines = File.ReadAllLines file
    use fs = new StreamWriter(file, false, System.Text.UTF8Encoding true) // with a bom
    lines
    |> Seq.filter (not << hasDebugType)
    |> Seq.iter fs.WriteLine


[<EntryPoint>]
let main argv =
    let files = 
        Directory.EnumerateFiles(@"C:\cs\roslyn", "*proj", SearchOption.AllDirectories)
        |> Seq.filter (fileHasString hasDebugType)
        |> Seq.filter (fileHasString hasVslSettingsTargets)
        |> List.ofSeq

    for file in files do
        printfn "file: %s" file
        removeDebugTypeLines file
    0
```

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @tmat

**Comment by davkean** [comment]
@dotnet-bot test eta please

**Comment by tmat** [comment]
:+1:

**Comment by ctaggart** [comment]
The log for the failed `prtest/win/dbg/unit32` shows 1 test failure:
image

Is this a valid failure? It doesn't make sense to me. It passes when I run it locally like so:
``` ps
msbuild .\Roslyn.sln /p:SignAssembly=false /v:m /t:rebuild
msbuild .\src\Samples\Samples.sln /p:SignAssembly=false /v:m /t:rebuild
md Binaries\Debug\xUnitResults
~\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe "Binaries\Debug\RemoveByValVB.UnitTests.dll" -xml "Binaries\Debug\xUnitResults\RemoveByValVB.UnitTests.dll.xml" -noshadow -verbose
```
image

If it is a valid error, how do I reproduce it?

**Comment by davkean** [comment]
I suspect the test failure was caused by: https://github.com/dotnet/roslyn/issues/6358, but the logs have been cleaned up already so I can't confirm.

@dotnet-bot retest prtest/win/dbg/unit32 please

**Comment by ctaggart** [comment]
Thanks @davkean! That makes me feel better. The checks all pass. :+1:

**Comment by davkean** [comment]
:+1: 

Thanks for the contribution!

**Pull request merged**
