### PR TITLE
Fix exception thrown in MSBuildWorkspace when opening multi-targeted project that references an F# project

### LINKED ISSUE #28104: NetCoreTests failing in Jenkins
These tests: Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReferenceWithReversedTFMs
Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM
Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReference

are failing on master

https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/job/master/job/windows_debug_spanish_unit32/lastFailedBuild/

Will skip the tests until they are fixed.

### LINKED ISSUE #30382: MSBuildWorkspace.OpenSolutionAsync throws ArgumentException
**Version Used**: 2.9.0

**Steps to Reproduce**:

1. Clone https://github.com/dotnet/BenchmarkDotNet

1. Create new console app and run

```csharp
VisualStudioInstance instance = MSBuildLocator.QueryVisualStudioInstances().First();

MSBuildLocator.RegisterInstance(instance);

using (MSBuildWorkspace workspace = MSBuildWorkspace.Create())
{
    Solution solution = await workspace.OpenSolutionAsync(solutionFilePath);
}
```
```
System.ArgumentException: Item with Same Key has already been added.

   v System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   v System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   v System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__20.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<TryLoadAndAddReferenceAsync>d__33.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<ResolveReferencesAsync>d__32.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<>c__DisplayClass21_0.<<CreateProjectInfoAsync>b__0>d.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<DoOperationAndReportProgressAsync>d__17`1.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadProjectInfosFromPathAsync>d__20.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.Worker.<LoadAsync>d__18.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildProjectLoader.<LoadSolutionInfoAsync>d__22.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.<OpenSolutionAsync>d__23.MoveNext()
```

Build passes in Visual Studio.

I observed similar behavior with https://github.com/Fody/PropertyChanged.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #30382 
Fixes #28104

In MSBuildWorkspaceProjectLoader, there is a map of "discovered" projects that stores the results of any project references that are loaded. If a project reference can't be loaded (for example, because it is a reference to an F# project), it can end up in the map twice if the project referencing it is multi-targeted. To avoid this situation, we call TryGetValue on the "discovered" projects map and return the results before trying to load the project again.

Note that there are a fair amount of test changes here because the regression test for this scenario hits the same issue that caused a few other MSBuildWorkspace tests to be disabled. So, I've gone ahead and fixed that issue as well (#28104) and unskipped the tests.

### CODE REVIEW

**Comment by sharwell** [comment]
@DustinCampbell This fixes tests which have been disabled in the dev16.0.x branch. Should we retarget the PR?

**Comment by DustinCampbell** [comment]
Sounds good. Shall I move #30331 as well?

**Comment by Pilchie** [comment]
Sure - let's do it.

**Comment by DustinCampbell** [comment]
Done. Any additional approval process for dev16.0.x?

**Comment by Pilchie** [comment]
M2 approval required.  Consider it approved 😄

**Pull request merged**
