### PR TITLE
update roslyn SDK to use 1.0.1 packages

### PR DESCRIPTION
**Pull request by jmarolf**
The Roslyn SDK ships out of band and is not part of ask mode.

Fixes https://github.com/dotnet/roslyn/issues/9292 

@dotnet/roslyn-ide for review

### CODE REVIEW

**Comment by jmarolf** [comment]
test windows_eta_open_prtest please

**Comment by jmarolf** [comment]
@jaredpar what is the correct way to run RepoUtil in Open/Closed? [this](https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/1423) failure appears to be because the props file is not updated, but if I run RepoUtil at the root it makes not changes.

**Comment by jaredpar** [comment]
@jmarolf the error listed is the following

```
17:31:13 Error! Package Microsoft.CodeAnalysis.Common has different versions:
17:31:13 	losed\Tools\Source\SyntaxVisualizer\SyntaxVisualizerExtension\project.json at 1.0.0
17:31:13 	pen\src\Setup\BuildTasks\project.json at 1.0.1
17:31:13 The versions must be the same or one must be explicitly listed as fixed in RepoData.json
```

Why did you believe that was a problem with Dependencies.props not being generated?  

I will send a PR to have it print out the command line it uses.

**Comment by jmarolf** [comment]
test windows_eta_open_prtest please

**Comment by jmarolf** [comment]
@jaredpar  the error message was
```
The Dependencies.props file has unexpected items. Please run `RepoUtil change`.
```
It would be great if it instead had reported
```
Error! Package Microsoft.CodeAnalysis.Common has different versions:
Closed\Tools\Source\SyntaxVisualizer\SyntaxVisualizerExtension\project.json at 1.0.0
Open\src\Setup\BuildTasks\project.json at 1.0.1
The versions must be the same or one must be explicitly listed as fixed in RepoData.json
```

**Comment by jaredpar** [comment]
@jmarolf it does report exactly that in the log file. Look at my earlier comment.  That was copy / pasted from the jenkin run.

**Comment by jmarolf** [comment]
It doesn't show as the failure cause in Jenkins. Why have Jenkins report anything at all for failures if we just need to look at the log anyway?

**Comment by jaredpar** [comment]
@jmarolf it's not anything I added.  I think Jenkins is just matching a different error case.  Either way it's a bit hard to match due to the multi-line nature.  Jenkins has performance issues with that (sadly).

**Pull request merged**
