### PR TITLE
Remove extra logic to see if users are squatting on keywords

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
I personally would consider this a regression of an existing good behavior. I think this makes a semantic classifier not semantic-aware.

**Review by davidwengier — APPROVED** [review]

**Review by sharwell — DISMISSED** [review]
I have no objection to updating the _syntax_ classifier to preemptively classify `var` as a keyword, but the semantic classifier must correct the classification for cases where it's not used in that form.

**Comment by CyrusNajmabadi** [comment]
> I personally would consider this a regression of an existing good behavior. I think this makes a semantic classifier not semantic-aware.

I'm fine with taht.  Indeed, i'll just move this to syntactic classification.

**Comment by CyrusNajmabadi** [comment]
> I have no objection to updating the syntax classifier to preemptively classify var as a keyword, 

I'll do that.

> but the semantic classifier must correct the classification for cases where it's not used in that form.

There is no need for the semantic classifier to do anything with htis.  We're effectively stating *at the language levle* that we don't care about this sort of user code.  It's non-grata.  The IDE operates under an even looser set of rules, and we have absolutely no need or obligation to spend extra cycles trying to provide specialized behavior against pathological code.

**Review by sharwell — CHANGES_REQUESTED** [review]
This is an unnecessary change. The original behavior is more correct with no known problems in performance or maintainability.

**Comment by CyrusNajmabadi** [comment]
> with no articulated problems in performance or maintainability.

The articulated problem is complexity (and that is the case in lots of the code, not just this). We have lots and lots of code that attempts to effectively work with code that we *as a team* are stating we now consider to be pathological. 

The sentiment is that this is not something we are going to continue with, and we will even actively be pushing people away from (including breaking if it comes to that). 

This change simplifies things, allowing us to do less work, and to not have to waste dev cycles (and user cycles) for pathological cases.

**Pull request merged**
