### PR TITLE
Smart Indent appropriately inside MultiLine Literal in VB

### LINKED ISSUE #2231: Multi-Line String Literal + Indentation = Gotcha
VB.net will support multi-line string literals, but it has introduce a gotcha has well.
That of significant whitespace.  After the pressing return to add a newline within the string the following text is indented to align with the current indentation level. But that automatic indentation isn't marked as insignificant. The issue also accord when XML Literals were added to the language.

**Repo Code**
```vb
Imports System
public class C 
    public Sub M() 
        Dim x = "1
        2
        3
        4
        5
        "
        Console.Write(x)
    end sub
  
End Class
```

**Expectation**
```
1
2
3
4
5

```

**Actual**
```
1
        2
        3
        4
        5

```

**Work Around**
A work around is to left-align the string literal.
```
Imports System
public class C 
    public Sub M() 
        Dim x = _
"1
2
3
4
5
"
        Console.Write(x)
    end sub
  
End Class
```

**Desired Resolution**

1. Have the string literal be aware of the indentation level and take it into account.
2. On pressing Return ignore the indentation level, and place the carat at the left-hard margin.

### PR DESCRIPTION
**Pull request by basoundr**
Fix #2231 : Smart indent appropriately inside VB MultiLine literals

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:  Looks good, and thanks for adding @AdamSpeight2008's commit to it.

**Comment by AdamSpeight2008** [comment]
@basoundr :+1:  Thank you so much for adding the Unit Test. *Admittedly I'm shocked it passed them.:bow:*

\CC @ljw1004 @gafter 
Q. Did pick the correct nodes to use?

**Comment by basoundr** [comment]
@AdamSpeight2008 Didn't understand your comment "Q. Did I pick the correct nodes to use?". Could you please explain whom you were trying to address? and what it was about? Were you asking about the change itself?

**Comment by AdamSpeight2008** [comment]
That question was mainly for @ljw1004 

Are these the correct tokens to check on?
`InterpolatedStringTextToken`  
`InterpolatedStringText`
Did I miss other possible tokens?

**Pull request merged**
