### PR TITLE
Missed adding the facades in a few places

### PR DESCRIPTION
**Pull request by agocke**
This adds them to the project.json which the insertion tool picks up on
and adds them directly to the NuSpec used for making the compiler package.

/cc @tmat

### CODE REVIEW

**Comment by tmat** [comment]
:+1:

**Comment by agocke** [comment]
@tmat Is there a reason the target runtime was hard locked at "win"?

**Comment by tmat** [comment]
@agocke What is the alternative?

**Comment by agocke** [comment]
@tmat win7?

**Comment by tmat** [comment]
I don't know what the difference is between these. Nuget complains about one or the other.

**Comment by agocke** [comment]
@tmat It's probably fine for now. Theoretically we could take a dependency on something that's only win7+ and we'll need to up our dependency, but that's not a problem right now.

**Comment by agocke** [comment]
Retest winows_eta_open_prtest please

**Pull request merged**
