### PR TITLE
Serialize all data necessary for NavigateTo from teh OOP process to VS.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @ManishJayaswal 

**Customer scenario**

This change enables the usage of the OOP process for "Find References, Navigate To and Add Import". 

**Bugs this fixes:**

None.  This is featurework.

**Workarounds, if any**

None.

**Risk**

Medium.  This introduces a new indirection for these features and may end up causing issues that we'll need dogfooding to uncover.

Note: we have "escape hatches" so that we go back to running all this "in proc" if there are any issues.

** Performance impact**

Getting RPS data now.  

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Not a regression.

**How was the bug found?**

Not a regression.

**Comment by ManishJayaswal** [comment]
@Pilchie - we should first get perf data before merging this. Additionally should this be buddy tested?

**Comment by CyrusNajmabadi** [comment]
RPS suite is running now.

**Comment by ManishJayaswal** [comment]
Approved pending RPS results.

**Comment by CyrusNajmabadi** [comment]
RPS numbers look fine.  But i do think it would be good to spend a day smoke testing this. I'll do that tomorrow.

**Comment by CyrusNajmabadi** [comment]
This work has been merged in.

**Pull request closed without merging**
