### PR TITLE
Cleanup unneeded ProjectReferences in compilers layer

### PR DESCRIPTION
**Pull request by Youssef1313**
Similar to #51471

This should make running tests faster when working with one test project.

### CODE REVIEW

**Comment by jaredpar** [comment]
> This should make running tests faster when working with one test project.

Why do you believe that is the case? The project references you removed here are all transitively referenced from those projects hence they're still in the build graph here.

**Comment by Youssef1313** [comment]
@jaredpar Initially thought it's similar to https://github.com/dotnet/roslyn/pull/51471

In https://github.com/dotnet/roslyn/pull/51471, running `dotnet build` after removing the reference showed that it's not being restored/built. But that doesn't seem to be correct for the compilers layer.

**Comment by jaredpar** [comment]
Yeah it's tricky. Both compilers are really entangled together when it comes to testing. We reference MS.CA.CSharp and MS.CA.VB at the core compiler unit test utility project. Hence you can't really separate them at the individual unit test project level.

Know this because at one point I went on a quest to make it so that I could compile and run C# tests without having to build the VB compiler (and vice versa). That was a failed experiment. Too much intertwined logic there.

**Comment by Youssef1313** [comment]
> Know this because at one point I went on a quest to make it so that I could compile and run C# tests without having to build the VB compiler (and vice versa). That was a failed experiment. Too much intertwined logic there.

I was actually thinking about trying to do so :smile:
But doesn't look it would be a successful trial.

**Comment by jaredpar** [comment]
Yeah CommonTestBase.cs is basically the core of the reason why this is really difficult. There is a non-trivial need for the unit tests to mix C# and VB projects. Hence in the early days of Roslyn they put the helpers for doing it at the core utility level. Now there is nearly ten years of assumptions baked into the code of that being available.

**Comment by 333fred** [comment]
We use the feature extensively when representing things that can't be natively stated in the other language, such as indexed property consumption in C# or pointer consumption in VB.

**Comment by jaredpar** [comment]
Yep. My thought when I tried this experiment was 

> Okay maybe we just have one unit test assembly where we allow cross C# and VB compilations to interact. Push the cross language testing into that

I eventually decided that wasn't a good trade off. There are way too many one off tests in another feature where we say "and make sure this C# feature works with indexed properties." It would be a pretty large conceptual change to get devs to move all those tests to a diff assembly. Main reason I ended up walking away from this idea.

**Comment by CyrusNajmabadi** [comment]
Note: i would be fine with such a change for the IDE layer.  EditorFeatures-UnitTests-2 is suppsoed to be the official place for cross-language tests to live in.  I think we could do this split and take the small handful of tests we have that have a cross language dep, and move them here.  It would be some manual effort, but fairly easy.

**Comment by Youssef1313** [comment]
@CyrusNajmabadi See https://github.com/dotnet/roslyn/pull/51471

**Comment by jaredpar** [comment]
@CyrusNajmabadi you can't solve this in the IDE layer for the same reason we can't solve it at the compiler layer. All of the IDE layer tests depend on the core compilers utility library and that references both compilers.

**Pull request closed without merging**
