### PR TITLE
Merge dev16.0.x into Features/enhanced using

### PR DESCRIPTION
**Pull request by chsienki**
Update enhanced-using branch from dev16.0.x

### CODE REVIEW

**Comment by chsienki** [comment]
@dotnet/roslyn-compiler updating the enhanced using branch with dev16.0.x commits  please review.

**Comment by chsienki** [comment]
Hmm. Something seems screwy here. Ignore for now, and I'll investigate.

**Comment by chsienki** [comment]
Fixed bad merge. @dotnet/roslyn-compiler ready for review please

**Comment by jcouv** [comment]
@jaredpar FYI Chris is running into the same problem I had trying to update a feature branch with latest bits from master, namely an error with .NET Framework 4.0 reference.
I ended up punting on the problem (I did a merge from features/compiler to the feature branch), so I don't know the root cause.

**Comment by chsienki** [comment]
retest windows_debug_unit32_prtest please

**Comment by chsienki** [comment]
@dotnet/roslyn-compiler Think this is all good now, but would be good to get a second set of eyes on the merge

**Pull request merged**
