### PR TITLE
Binding zoom level to Inheritance margin

### PR DESCRIPTION
**Pull request by Cosifne**
Binding to zoom level of TextView to ScaleFactor of CrispImage.
I
Before:
image

After:
image

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]
Fixes https://github.com/dotnet/roslyn/issues/53372 perhaps?

**Review by sharwell — CHANGES_REQUESTED** [review]
This needs to listen for `ZoomLevelChanged`. See here for example:

https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fdebugger%2Fvsdebugcoreui%2FExceptionHelper%2FSession.cs&version=GBmain&line=643&lineEnd=683&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by Cosifne** [comment]
> This needs to listen for `ZoomLevelChanged`. See here for example:
> 
> https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fdebugger%2Fvsdebugcoreui%2FExceptionHelper%2FSession.cs&version=GBmain&line=643&lineEnd=683&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

@sharwell 
The editor code here
http://index/?leftProject=Microsoft.VisualStudio.UI.Text.Wpf.GlyphMargin.Implementation&leftSymbol=opz6bilxltuu&file=GlyphMargin.cs&line=197
will create new glyphs when the zoom level changed. So if we are still using the IGlyphFactory to create a margin, then I feel we don't need to maintain the status of the old margin.

**Comment by Cosifne** [comment]
@vatsalyaagrawal  for approval

**Pull request merged**
