### PR TITLE
Public API cleanup: replace fields with properties in Workspace layer

### LINKED ISSUE #2476: Avoid public fields in Roslyn API
I have noticed we expose some public fields from the compilers (about 30 or so). I believe the .NET API guidelines prefer using properties for public APIs.

### PR DESCRIPTION
**Pull request by tmat**
Fixes #2476.
Public API cleanup as per .NET Framework API design guidelines.

We have done this cleanup for compilers (see PR https://github.com/dotnet/roslyn/pull/3246). Do the same for workspaces.

@ManishJayaswal

### CODE REVIEW

**Comment by tmat** [comment]
@gafter @mattwar

**Comment by mattwar** [comment]
:+1:

**Comment by pharring** [comment]
:+1:

**Comment by pharring** [comment]
Approved 6/5 ML Shiproom

**Comment by gafter** [comment]
LGTM

**Pull request merged**
