### PR TITLE
Do not copy vsix manifest files to the common build folder

### PR DESCRIPTION
**Pull request by jmarolf**
Fixes https://github.com/dotnet/roslyn/issues/6424

### CODE REVIEW

**Comment by jmarolf** [comment]
Please review: @jasonmalinowski @davkean 

@dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
Well that was easy. :+1:

**Comment by jmarolf** [comment]
test vsi please

**Comment by davkean** [comment]
:+1:

**Comment by jmarolf** [comment]
retest vsi please

**Pull request merged**
