### PR TITLE
Pull common FixAll logic into some helper base types that we can use across many of our code style fixes.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide 

I intend to use this as the basis of all our code style fixers.  Being able to edit a document through a SYntaxEditor is much cleaner than our current mechanism.  Specifically, it addressed the problem where the standard BatchFixAllProvider might not be able to make edits because it thinks that edits conflict (due to how it tries to diff and merge edits).  By using SyntaxEditor, we can cleanly make a tree edit in bulk, without that concern.

**Comment by Pilchie** [comment]
Also tagging @sharwell who has thoughts about the standard batch fixer...

**Comment by CyrusNajmabadi** [comment]
Preemptively, proactively merging.

**Comment by sharwell** [comment]
The standard batch fixer has many issues. To me, the really interesting part here is the change from `DocumentBasedFixAllProvider` to the new `SyntaxEditorBasedFixAllProvider`.

In some complex scenarios, I imagine a `SyntaxEditor` could be helpful. In practice, we've only need to use it once. My main concern is it limits the ability to reach optimum performance for certain types of changes. In particular, many of our code fixes that operate on whitespace, such as tabs to spaces conversions or trailing whitespace elimination, use a `List<TextChange>` and apply the changes using `Document.WithTextAsync`, intentionally bypassing many checks that occur in other mechanisms. By our estimates, this can mean the difference between a couple thousand fixes per second (which isn't bad) and a couple *hundred* thousand fixes per second. We actually haven't reached our real performance limit yet because we first need to make a separate `DocumentTextBasedFixAllProvider` that avoids a `GetSyntaxRootAsync` when applying changes back to a solution (some of our other fixes rely on this call to apply formatting changes).

**Comment by CyrusNajmabadi** [comment]
Note: DocumentBasedFixAllProvider  was internal and purely created for CodeStyelFixes.  All i did here was move the common code across all FixProviders where they got an editor and whatnot, and moved it.  I then renamed the type to make it clearer.

We could consider exposing the concept of a DocumentBasedFixAllProvider so that FixProviders can use that to party on the document however they want (including not getting a syntax root).  Then we'll have hte parallelism across documents, but each document can be processed as a whole by the fixer.  Would that be helpful to you?

**Comment by sharwell** [comment]
@CyrusNajmabadi We're using our own implementation of `DocumentBasedFixAllProvider`. I'm not sure which one came first (Roslyn or ours). #201 is the original feature request we made, but we've long since switched to a custom implementation of the feature.

**Pull request merged**
