### PR TITLE
Backport SpillSequence Fix to 17.1

### PR DESCRIPTION
**Pull request by 333fred**
Backport the fix for https://github.com/dotnet/roslyn/issues/58514 and https://github.com/dotnet/roslyn/issues/58569 to 17.1 for QB mode. QB Bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1460611

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

**Comment by AlekseyTs** [comment]
@333fred Are you planning to submit a separate PR with tests for #58514?

**Comment by 333fred** [comment]
> @333fred Are you planning to submit a separate PR with tests for #58514?

https://github.com/dotnet/roslyn/pull/58764. I wasn't planning on putting it into this branch.

**Comment by AlekseyTs** [comment]
> I wasn't planning on putting it into this branch.

Effectively we don't have any verification that the #58514 is fixed by this PR. I understand that we have a good reason to believe that it is fixed, but still. Perhaps we should port that PR as well #58764 (Do we need a QB approval for test only changes?), or simply include the tests (at least those we have at the moment) in this PR?

**Comment by 333fred** [comment]
> (Do we need a QB approval for test only changes?)

No, we could merge them into this branch without a problem. I could do that, I just didn't think it was worth the extra effort over putting them into `main`.

**Pull request merged**
