### PR TITLE
Align controls on the PullMembersUp Dialog

### PR DESCRIPTION
**Pull request by JoeRobich**
Before:
image

After:
image

### CODE REVIEW

**Review by Cosifne — APPROVED** [review]

**Review by ryzngard — APPROVED** [review]
Worth checking this fits with other uses of MemberSelection control. I imagine it's correct

**Comment by JoeRobich** [comment]
> Worth checking this fits with other uses of MemberSelection control.

@ryzngard The only other use is in the Extract Base Class dialog which appears OK. I will say that we may need to review our dialogs to ensure they have a consistent look and feel. The border around group boxes in the ExtractBase dialog look out of place next to PullMembersUp.

image

**Comment by ryzngard** [comment]
Agree we could use a pass to better our dialogs. Please file an issue for this known one, maybe we can use that as a driver to do a pass and fix then. :) 

Feel free to assign to me. We should eventually theme dialogs anyways...

**Comment by JoeRobich** [comment]
> Please file an issue for this known one

Opened https://github.com/dotnet/roslyn/issues/55560

**Pull request merged**
