### PR TITLE
TryReduce should return TypeArgumentList span for GenericNameSyntax node

### PR DESCRIPTION
**Pull request by Giftednewt**
This change resolves the issue reported in #3300

### CODE REVIEW

**Comment by jmarolf** [comment]
dotnet-bot test this please

**Comment by Pilchie** [comment]
@jmarolf and @DustinCampbell Can you take a look at this?

**Comment by jmarolf** [comment]
@Pilchie taking alook

**Comment by DustinCampbell** [comment]
LGTM :+1:

**Comment by jmarolf** [comment]
image
 
Can confirm that this fixes the issue.

**Pull request merged**
