### PR TITLE
Change citest to run in release

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet-bot test perf please

**Comment by TyOverby** [comment]
cc @john-soklaski

**Comment by TyOverby** [comment]
cc: @dotnet/roslyn-perf @dotnet/roslyn-infrastructure

**Comment by TyOverby** [comment]
@dotnet-bot run windows_release_unit64_prtest please

**Comment by TyOverby** [comment]
review please @dotnet/roslyn-perf @dotnet/roslyn-infrastructure

**Comment by mattwar** [comment]
@dotnet-bot test windows_release_unit64_prtest please

**Comment by TyOverby** [comment]
I swear @dotnet/roslyn-perf if no one reviews this, I'm just going to merge it

**Comment by KevinH-MS** [comment]
Seems reasonable 👍

**Pull request merged**
