### PR TITLE
Update master with dev15 rc

### PR DESCRIPTION
**Pull request by OmarTawfik**
@dotnet/roslyn-infrastructure 
Replacing #14889 as I don't have permissions to resolve conflicts there.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet-bot test vsi please

**Comment by OmarTawfik** [comment]
@dotnet-bot test microbuild_prtest please

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_vsi_p3_open_prtest please

**Comment by OmarTawfik** [comment]
@dotnet-bot test vsi please

**Comment by genlu** [comment]
The failure in windows_vsi_dev15_p1_open_prtest seems to be scenario `Bug 586849 - GTD on My.Forms.FormName` in BasicWinForm causes VS to crash.  https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_dev15_p1_open_prtest/17/

**Comment by genlu** [comment]
@dotnet-bot retest  windows_vsi_dev15_p1_open_prtest please

**Comment by OmarTawfik** [comment]
@jaredpar adding the missing binary, can you please check the commit https://github.com/dotnet/roslyn/pull/14917/commits/06e7e1bcaf09a8d5980fa7991a895a762643f076. Is there any thing else I need to add? seems like it is still not copied.

**Pull request closed without merging**
