### PR TITLE
remove duplicate type from `CSharpScriptingTest`

### LINKED ISSUE #6277: Scripting tests are causing a build error
PR builds are failing with:

```
error CS0436: The type 'TestCompilationFactory' in 'd:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Scripting\CSharpTest\TestCompilationFactory.cs' conflicts with the imported type 'TestCompilationFactory' in 'Microsoft.CodeAnalysis.Scripting.UnitTests, Version=42.42.42.42, Culture=neutral, PublicKeyToken=fc793a00266884fb'. Using the type defined in 'd:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Scripting\CSharpTest\TestCompilationFactory.cs'. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Scripting\CSharpTest\CSharpScriptingTest.csproj]
```

### PR DESCRIPTION
**Pull request by brettfo**
This type now exists in the `ScriptingTest` project and a duplicate copy from the `stabilization` branch wasn't properly detected as having been moved when merging into `master`, hence the duplicate type/file.

Fixes #6277.

FYI: @amcasey @davkean @tannergooding

### CODE REVIEW

**Comment by davkean** [comment]
tagging @dotnet/interactive

**Comment by davkean** [comment]
:+1:

**Comment by amcasey** [comment]
:+1:

**Comment by davkean** [comment]
@brettfo Thanks for fixing this quickly!

**Comment by brettfo** [comment]
the `prtest/win/dbg/eta` test which was previously failing to build is now green so I'm going to pre-emptively merge this in the hopes of unblocking other PRs.

**Pull request merged**
