### PR TITLE
Add support for reporting analyzer diagnostics in editorconfig files

### LINKED ISSUE #64213: Add support for reporting analyzer diagnostics in editorconfig files
@mgoertz-msft FYI that your original feature request has now been implemented for 16.8 P1 with https://github.com/dotnet/roslyn/pull/45076. I will keep this issue open to track exposing a similar API for analyzer config files.

_Originally posted by @mavasani in https://github.com/dotnet/roslyn/issues/44131#issuecomment-658887799_

### PR DESCRIPTION
**Pull request by mavasani**
Closes #64213

Design proposal and public APIs discussed in https://github.com/dotnet/roslyn/issues/64213#issuecomment-1254764899

With this change, analyzers can report diagnostics in editorconfig and globalconfig files, which will be reported both in CI and in the IDE. Additionally, analyzers can access raw source text and file paths for all editorconfig and globalconfig files that are being applied to the compilation from AnalyzerOptions exposed off all analysis contexts for all analyzer callbacks (similar to how they can currently access raw text and file paths of additional files).

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
@mavasani Should https://github.com/dotnet/roslyn/pull/63580 wait until this PR is merged, and move the implementation to an analyzer?

**Comment by mavasani** [comment]
> @mavasani Should #63580 wait until this PR is merged, and move the implementation to an analyzer?

I'll @dibarbet make that call. I am personally fine if we want to go ahead with #63580 and port the diagnostic reporting component to an analyzer subsequently.

**Comment by Youssef1313** [comment]
@mavasani What is the status of this?

**Comment by mavasani** [comment]
@Youssef1313 At the design meeting it was decided that we want to expose a richer object model for the editorconfig file, instead of just a text stream as we do for additional files. I need to come up with a public API proposal for the same and bring this back to API design review.

**Comment by mavasani** [comment]
Closing stale PR. If and when we come up with a design to expose a richer object model for the editorconfig file, we can revive this effort.

**Pull request closed without merging**
