### PR TITLE
Fix SolutionLoadEvents

### PR DESCRIPTION
**Pull request by Pilchie**
So, it turns out that when you AdviseSolutionEvents, the shell actually
checks the same object for all of the related solution events interfaces
to fire events to them.  This meant that after commit
e6a43cb5ca0d0a00dd500eaf21c8ec4421fede02, we never actually received any
IVsSolutionLoadEvents or IVsSolutionWorkingFoldersEvents.  The impact of
this is that we never called "FinishLoad" to populate the Roslyn
workspace with the projects that had been loaded.

Most features would appear to work, as we would load a project and it's
dependencies when a file was opened, but we would then not load any
thing that depends on it, so features like Find All References and
Rename wouldn't work reliably.

Fixes
https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=389698.

### CODE REVIEW

**Comment by Pilchie** [comment]
@GearedToWar, @huizhonglong - please review.

**Comment by Pilchie** [comment]
Tagging @roslyn-ide  Please review/and buddy test ASAP!

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Comment by jasonmalinowski** [comment]
The image has been updated.

@dotnet-bot test vsi please.

**Comment by Pilchie** [comment]
Merged now that testing has completed on internal builds.

**Pull request merged**
