### PR TITLE
Upgrade the Roslyn source tree to System.Collections.Immutable 1.1.37

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Upgrading this caused a problem -- our current version of
System.Reflection.Metadata still depends on 1.1.36, so it was easier to
downgrade (!) the package to an older one that specifies a dependency
on 1.1.37. @tmat assures me the actual code inside is the same.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
I've decided to try deleting our binding directs for unit tests to see if everything still passes without them. If they don't, I'm going to enable automatic generation of those rather than requiring manual tracking.

**Comment by tmat** [comment]
:+1:

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by jasonmalinowski** [comment]
@tmat: I pushed before running tests locally; something is probably actually broken.

**Comment by Pilchie** [comment]
GitHub still got this wrong?

**Comment by jasonmalinowski** [comment]
It looks like @rchande had the wrong bug number in his commit.

**Comment by jasonmalinowski** [comment]
Abandoning this, since we moved to project.json first.

**Pull request closed without merging**
