### PR TITLE
Doc: deconstruction avoids constructing ValueTuple

### PR DESCRIPTION
**Pull request by jcouv**
Doc-only change
Relates to https://github.com/dotnet/csharplang/issues/1656

### CODE REVIEW

**Comment by gafter** [comment]
I don’t think we should encourage people to depend on this. What is the downside of leaving it an optimization that a compiler is not required to do?

**Comment by jcouv** [comment]
I'd like to document it, since some folks had questions on it. But I can make it clear that it's part of the compiler implementation, and not the language spec. Would that be better?

**Comment by gafter** [comment]
If you mean part of *some* but not necessarily all compiler implementations, sure.

**Comment by jcouv** [comment]
After thinking about this more, I think it's ok to leave this information out. I'll close.

**Comment by steevcoco** [comment]
Now closed!

I think one can note that the difference in the syntax IS honoring the optimization. The difference is: "make this tmp var now"; versus: "if you can do this swap without needing a tmp; then either way, swap these".

:)

**Pull request closed without merging**
