### PR TITLE
Initial work to make Features layer portable

### PR DESCRIPTION
**Pull request by DustinCampbell**
This PR represents a couple of changes in service of making the Features layer portable (#3998). There are still outstanding work items before this work will be completed:

* Remove [Serializable] from EnC types (#4354)
* Update reflection code in Analyzer system to portable (#4355)

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Reviewers: @Pilchie, @mattwar, @jasonmalinowski, @davkean, @dpoeschl

**Comment by Pilchie** [comment]
:+1:

**Comment by mattwar** [comment]
FileTracker never gets the love, always the neglected stepchild.

**Comment by mattwar** [comment]
:+1:

**Pull request merged**
