### PR TITLE
Update to best practice use of Apache 2 license

### PR DESCRIPTION
**Pull request by richlander**

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
This is a more or less direct revert of 1ff27b046b5c03abb38bfeda44eb82da0b8df9de? Does this break the GitHub license detection logic?

**Comment by richlander** [comment]
That's funny. Yes, close to revert. This one is much better and clearer.

Sadly, it does break detection. I'll ask the GitHub folks to fix that for us.

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by jaredpar** [comment]
We apologize, but we are closing this PR due to code drift. We regret letting this PR go so long without attention, but at this point the code base has changed too much for us to revisit older PRs. Going forward, we will manage PRs better under an SLA currently under draft in issue #26266 – we encourage you to add comments to that draft as you see fit. Although that SLA is still in draft form, we nevertheless want to move forward with the identification of older PRs to give contributors as much early notice as possible to review and update them.

If you are interested in pursuing this PR, please reset it against the head of master and we will reopen it. Thank you!

**Pull request closed without merging**
