### PR TITLE
Fix our readme badges

### PR DESCRIPTION
**Pull request by jasonmalinowski**
- Fix the image URLs to point to the current configuration names
- Reorder the Spanish/Linux with Mono columns, because the labels were wrong.

### CODE REVIEW

**Comment by sharwell** [comment]
Can the integration test images be fixed as well?

**Comment by sharwell** [comment]
Also would be good to change the text on the badge from **Azure Pipelines** back to just **build**.

**Comment by sharwell** [comment]
@jaredpar was there a script for generating these badges that needs to be updated as well?

**Comment by jaredpar** [comment]
This is the script I wrote to generate the badge table. 

https://github.com/dotnet/roslyn/blob/master/scripts/generate-badges.ps1

I'm not in any way tied to the table layout or the text we display. But given how annoying that table is to update I would like if we kept the badge generator as the primary way to change the badges. Or if we want to do it by hand please just delete this script.

**Comment by jasonmalinowski** [comment]
I was unaware we had a script.

@sharwell Yes, can do. I started this via the web editor and wanted to get this up but can poke further. My thought there was to not have individual badges for all the queue types, since the debug/release legacy/modern splits I think are relatively less interesting, and I don't want to remember to update this every time we change that.

**Comment by jasonmalinowski** [comment]
@chsienki is fixing this properly in #37412.

**Pull request closed without merging**
