### PR TITLE
[EnC] VS Crash when updating a method with async lambda

### PR DESCRIPTION
**Pull request by wschae**
The symbol change around async lambda is not properly covered, resulting into unreachable exception.

### CODE REVIEW

**Comment by wschae** [comment]
@tmat Can you have a look at this change?

**Comment by wschae** [comment]
@tmat Can you have a look at this PR? It is about avoiding unreachable exception for a synthesized generator caused by async lambda.

**Comment by tmat** [comment]
Yes, I’ll take a look.

**Comment by wschae** [comment]
@tmat @gafter @VSadov Can you have a look at this one?

**Comment by wschae** [comment]
@tmat Updated PR to fix merge conflict

**Comment by wschae** [comment]
@dotnet-bot test this please

**Comment by wschae** [comment]
@tmat Thanks for suggestion. I simplify this PR as you suggested. I also need to update LambdaRewriter.vb. Can you have a look at this change?

**Comment by wschae** [comment]
This issue has been addressed and wiil be fixed by https://github.com/dotnet/roslyn/pull/2655. I am closing it :)

**Comment by tmat** [comment]
We can still use the test you have in the PR. Please check them in after my change is in.

**Comment by wschae** [comment]
@tmat Sure. I will check the test. Thanks!

**Pull request closed without merging**
