### PR TITLE
Fix example rulset XML

### PR DESCRIPTION
**Pull request by powellcj12**
@MattGertz  for ask mode approval

**Customer scenario**

The example ruleset provided contains some syntax errors, so copy/pasting wholesale somewhere can result in build errors when including it.

There was also a minor typo I found later in the file while reading through.

**Workarounds, if any**

**Risk**

Low

**Performance impact**

None

**Is this a regression from a previous update?**

**Root cause analysis:**

**How was the bug found?**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-analysis for review.

**Comment by powellcj12** [comment]
@mavasani @jinujoseph I don't suppose someone can merge and close this now?

**Comment by jinujoseph** [comment]
test windows_eta_open_prtest  please

**Comment by powellcj12** [comment]
test windows_eta_open_prtest please

**Comment by MattGertz** [comment]
Approved & thank you!

**Pull request merged**
