### PR TITLE
Fix name lookup through an unbound generic type.

### LINKED ISSUE #9850: It should be possible to access inherited nested types through an unbound generic type in typeof expression
This is port of http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/542581.
It was resolved as "No Repro", but the unit-test (Microsoft.CodeAnalysis.VisualBasic.UnitTests.CodeGenGetTypeOperator.CodeGen_GetType_InheritedNestedTypeThroughUnboundGeneric) remained skipped. It looks like the behavior got regressed.

--------------------
```cs
using System;
 
class C
{
    public class E { }
 
    static void Main()
    {
        Console.WriteLine(typeof(D<>.E));
    }
}
 
class D<T> : C { }
```

**ACTUAL RESULT**: error CS0426: The type name 'E' does not exist in the type 'D<<Error>>'

**EXPECTED RESULT**: no errors, prints C+E
 
See test `Roslyn.Compilers.CSharp.UnitTests.CodeGen.CodeGenTests.TestTypeofInheritedNestedTypeThroughUnboundGeneric`

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #9850.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_release_unit32_prtest please and test windows_release_unit64_prtest please. (These are new jobs that are now also required.)

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Pull request merged**
