### PR TITLE
Fix parsing of "e is nameof" to retain compatibility

### LINKED ISSUE #14636: Breaking change: 'x is nameof' expression
```c#
class nameof {
  // error CS0119: 'nameof' is a type, which is not valid in the given context
  bool M(object o) => o is nameof;
}
```
This code is no longer able to compile because parser now prefers parsing constant pattern instead of type syntax.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #14636 

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by cston** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet-bot test windows_debug_unit64_prtest please

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
