### PR TITLE
Port Microsoft.VisualStudio.AppDesigner and Microsoft.VisualStudio.Editors to Roslyn

### PR DESCRIPTION
**Pull request by davkean**
This is a port of Microsoft.VisualStudio.AppDesigner and Microsoft.VisualStudio.Editors to Roslyn, which includes the Application Designer, associated property pages, settings and resources editors. My changes were related to code clean up and build.

Things remaining:

- Port existing tests (#10255)
- Versioning (#10254)
- Fix pkgdef to be auto-generated, instead of a hand-written + pre-processed file. (#10253)

While I welcome feedback on the code itself, this is a _port_ so I'll be filing bugs for any feedback unrelated to my changes and won't block the merge on it

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis @dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
test this please

**Comment by jaredpar** [comment]
test determinism please

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5809/
// Retest reason: Need logs

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5875/
// Retest reason: Retesting to figure out if I caused this or whether this is flakiness.

**Comment by davkean** [comment]
// retest prtest/win/dbg/eta please
// Retest reason: https://github.com/dotnet/roslyn/pull/10498

**Comment by davkean** [comment]
test determinism please

**Comment by davkean** [comment]
test vsi please

**Comment by davkean** [comment]
@dotnet/roslyn-analysis I'm merging this in, if you want to provide feedback, feel free to review after the fact, and I'll file bugs to track the feedback.

**Pull request merged**
