### PR TITLE
Fix IOperation of byref member initializer

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes https://github.com/dotnet/roslyn/issues/72916.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
From the issue:
> Should check VB behavior as well.

Has this been done?

**Comment by AlekseyTs** [comment]
Done with review pass (commit 1)

**Comment by jjonescz** [comment]
I have forgot to look into VB, thanks. Looks like it does not have the same problem. Added a test.

---
In reply to: [2079711840](https://github.com/dotnet/roslyn/pull/73243#issuecomment-2079711840) [](http://example.com/codeflow?ancestors=2079711840)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Review by 333fred — APPROVED** [review]

**Pull request merged**
