### PR TITLE
Remove crash workaround in `.editorconfig`

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@Youssef1313 There are merge conflicts.

**Comment by jasonmalinowski** [comment]
@mavasani This OK to merge now?

**Comment by Youssef1313** [comment]
Ping @mavasani

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@Youssef1313 main branch is locked right now due to performance regressions. I have enabled auto-merge so it gets merged once the branch is unlocked.

**Comment by Youssef1313** [comment]
@mavasani It seems all PRs with auto-merge enabled with the branch was locked are stuck. Can you manually merge this please? Thanks

**Pull request merged**
