### PR TITLE
Properly handle null paths being passed to the RemotePersistenceService.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
It is totally expected that 'null' solution paths will exist in practice.  VS can create lightweight solutions that are never persisted to disk until the user decides to finally save them.  Or there may be Solution objects not backed by .sln files at all.

'null' is expected and flows through the VS side of the persistence layer just fine.  The mistake i made was to try to take the value and use it to produce a new path on the remote side without checking for null first.  We're now resilient to that and handle null properly.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @srivatsn @panopticoncentral @heejaechang Fixes DDRIT issue.

**Comment by heejaechang** [comment]
👍

**Comment by srivatsn** [comment]
👍

**Comment by CyrusNajmabadi** [comment]
retest windows_release_unit32_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_release_unit64_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
test windows_release_unit32_prtest  please

**Pull request merged**
