### PR TITLE
Add InternalsVisibleTo TestImpact in Features...

### PR DESCRIPTION
**Pull request by KevinH-MS**
I want to start listening to SolutionCrawler events, but the necessary
interfaces are currently internal.

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @dotnet/roslyn-interactive @dotnet/roslyn-analysis

**Comment by tannergooding** [comment]
LGTM

**Comment by amcasey** [comment]
Personally, I would just hand-edit the project files to eliminate the diff noise.

**Comment by amcasey** [comment]
LGTM

**Comment by KevinH-MS** [comment]
test prtest/win/dbg/unit32 s'il vous plaît

**Comment by KevinH-MS** [comment]
test prtest/win/dbg/unit32

**Comment by KevinH-MS** [comment]
test win/dbg/unit32

**Comment by KevinH-MS** [comment]
@tannergooding @davkean any idea why this test command isn't rerunning the tests?

**Comment by KevinH-MS** [comment]
test win please

**Comment by tannergooding** [comment]
@KevinH-MS, the queues appear to be backed up right now.

**Pull request merged**
