### PR TITLE
Revert "Implement IAttributeOperation (#59369)"

### PR DESCRIPTION
**Pull request by dibarbet**
This reverts commit d89769b6289595bff2c344ef24f04f146149cc7d.

This breaks VS build in a fair number of places.  @333fred  is tracking some fixes here https://github.com/dotnet/roslyn-analyzers/pull/6114 but there are too many places popping up now to attempt to suppress the warnings.  The original PR can be taken when we are able to update the copy of roslyn analyzers used by the VS build and have done a val build on that update + Roslyn.

This PR in VS is as far as I got with suppressions - https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/418436, but still has many errors.

### CODE REVIEW

**Review by 333fred — APPROVED** [review]
😢

**Comment by Youssef1313** [comment]
@333fred The roslyn-analyzers PR was fixed. When can this revert be reverted back again?

**Comment by 333fred** [comment]
When we update VS.

**Comment by Youssef1313** [comment]
@333fred @dibarbet The milestone here was set to 17.4 P2 which is already released. What's the status of this?

**Comment by 333fred** [comment]
I'm still working on getting the VS build using the new analyzers. I would expect the IAttributeOperation won't be added back in until 17.5.

**Pull request merged**
