### PR TITLE
update MicroBuild.Plugins.SwixBuild

### PR DESCRIPTION
**Pull request by jmarolf**
We received e-mails over the weekend specifying some changes that were needed to our setup authoring. This makes the requested modifications.

@MattGertz @Pilchie @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by Pilchie** [comment]
How can we verify that this has the correct changes in the output binaries?

**Comment by MattGertz** [comment]
Approved -- let's see if we can get a verification build to validate this.  I'll forward mail on that.

**Comment by jmarolf** [comment]
@Pilchie we'll need to verify that the signed build has the correct checksums in the manifest file.

**Comment by jmarolf** [comment]
test  windows_debug_unit64_prtest  please

**Pull request merged**
