### PR TITLE
Fix unexpected nullability warning

### LINKED ISSUE #47740: Unexpected Nullability Warning
**Version Used**: 
VS 16.8 Preview 3

**Steps to Reproduce**:
The code can be found in `DemonstratePatternMatchingEnhancements()` from https://github.com/JasonBock/WhatsNewInCSharp9. This is what I see in VS:

image

**Expected Behavior**:
The second call to `Equals()` does not create a "possibly null reference" issue.

**Actual Behavior**:
The second call to `Equals()` has a "possibly null reference" issue.

There may be something I'm missing here, but at first glance it doesn't make sense. If add this method to `ObjectNullability`:
```
public bool Check(object? obj) =>
  obj is ObjectNullability other ? this.Value == other.Value : false;
```
And then do this:
```
var nullability2 = new ObjectNullability(3);
Console.Out.WriteLine(nullability2.Check(null));
Console.Out.WriteLine(nullability2.Check(new ObjectNullability(3)));
```
I don't get the same issue. So....I'm confused :). Maybe it has to do with `Equals()` being overriden?

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #47740

### CODE REVIEW

**Comment by Youssef1313** [comment]
```csharp
        [Fact, WorkItem(35816, "https://github.com/dotnet/roslyn/issues/35816")]
        public void InstanceEqualsMethod_NonNullExpr_LiteralNull_NoWarningWhenTrue()
        {
            var source = @"
#nullable enable
class C
{
    static void M1(string s)
    {
        if (s.Equals(null))
        {
            _ = s.ToString(); // 1
        }
        else
        {
            _ = s.ToString();
        }
    }
}";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics(
                    // (9,17): warning CS8602: Dereference of a possibly null reference.
                    //             _ = s.ToString();
                    Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "s").WithLocation(9, 17));
        }
````

---

```csharp
        [Fact]
        [WorkItem(38010, "https://github.com/dotnet/roslyn/issues/38010")]
        public void EqualsMethod_DefaultArgument_02()
        {
            var source = @"
#nullable enable
class C : System.IEquatable<C>
{
    static void M(C c1)
    {
        if (c1.Equals())
        {
            // technically the arg to Equals was 'null' so this should be analyzed as maybe-null
            // however this scenario seems like such an anti-pattern that we shouldn't be concerned about it.
            _ = c1.ToString();
        }

        if (c1.Equals(null))
        {
            _ = c1.ToString(); // 1
        }
    }

    public bool Equals(C? other = null) => false;
}";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics(
                // (16,17): warning CS8602: Dereference of a possibly null reference.
                //             _ = c1.ToString(); // 1
                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "c1").WithLocation(16, 17));
        }
```

---

```csharp
        [Fact]
        [WorkItem(38010, "https://github.com/dotnet/roslyn/issues/38010")]
        public void EqualsMethod_DefaultArgument_01()
        {
            var source = @"
#nullable enable
class C // 1
{
    static void M(C c1)
    {
        if (c1.Equals())
        {
            // technically the arg to Equals was 'null' so this should be analyzed as maybe-null
            // however this scenario seems like such an anti-pattern that we shouldn't be concerned about it.
            _ = c1.ToString();
        }

        if (c1.Equals(null))
        {
            _ = c1.ToString(); // 2
        }
    }

    public override bool Equals(object? other = null) => false;
}";
            var comp = CreateCompilation(source);
            comp.VerifyDiagnostics(
                // (3,7): warning CS0659: 'C' overrides Object.Equals(object o) but does not override Object.GetHashCode()
                // class C // 1
                Diagnostic(ErrorCode.WRN_EqualsWithoutGetHashCode, "C").WithArguments("C").WithLocation(3, 7),
                // (16,17): warning CS8602: Dereference of a possibly null reference.
                //             _ = c1.ToString(); // 2
                Diagnostic(ErrorCode.WRN_NullReferenceReceiver, "c1").WithLocation(16, 17));
        }
```

---

These are the 3 test failures in this PR. None of them now produces a nullable warning. If this is the correct behavior and the correct fix for the issue, I'll update these tests.

**Comment by RikkiGibson** [comment]
@Youssef1313 I think it is good to update the baselines here.

**Comment by 333fred** [comment]
Commented on the linked bug, but I'm not certain this is behavior should be considered a bug.

**Comment by Youssef1313** [comment]
@333fred If the warning is valid in rare cases (e.g. Unity), I think it should be kept and developer should suppress it when it's false positive. I think the PR can be closed and the linked issue could be marked as by design.

@RikkiGibson What do you think?

**Comment by RikkiGibson** [comment]
Agree, let's close this. Also, if the Equals method being called doesn't have special behavior around `null` (e.g. some special objects are equal to `null`), then the fix is probably to delete the call.

**Pull request closed without merging**
