### PR TITLE
Recommend `void` keyword in `using unsafe` directives

### LINKED ISSUE #67986: `void` keyword not recommended in "using unsafe" directive
**Version Used**: VS 17.6 Preview 5 (4.6.0-3.23212.2)

**Steps to Reproduce**:
Place the caret at the marked location and type "void".

```csharp
using unsafe T = $$;
```

**Expected Behavior**:
The keyword "void" is recommended as it's valid in that location if an asterisk follows it.

**Actual Behavior**:
`System.Void` is recommended.
image

Typing `*` will commit the item, leading to invalid code.
image

### PR DESCRIPTION
**Pull request by jhinder**
Fixes #67986.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]
Thanks!

**Review by CyrusNajmabadi — APPROVED** [review]
Thanks!

**Comment by DoctorKrolic** [comment]
Something is really broken here:
firefox_5OcfGMbAUq

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic that means the branch is on lockdown.

**Comment by DoctorKrolic** [comment]
Auto-merge seems to be broken...

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic yup.  if the branch was locked down, merging/auto-merging has to be done manually after it opens.  Thanks for the contribution!

**Pull request merged**
