### PR TITLE
Bring features/param-nullchecking up to date [Old]

### PR DESCRIPTION
**Pull request by kevinsun-dev**
In light of the absolute mess that has been made of this PR, I've decided to close it. Clean one at #46398.

### CODE REVIEW

**Comment by jcouv** [comment]
To fix the correctness leg, you'll need to run `eng\generate-compiler-code.cmd`

**Comment by kevinsun-dev** [comment]
> To fix the correctness leg, you'll need to run `eng\generate-compiler-code.cmd

Huh, it didn't seem to fix it. Are there any other scripts I should be running?

**Comment by jcouv** [comment]
It did fix the correctness leg.

**Comment by jcouv** [comment]
@kevinsun-dev CI is now green. You can merge (don't squash). 
I'll take another look once merged (to review diff from feature branch and master).

**Pull request closed without merging**
