### PR TITLE
Fixing copy-paste issue

### PR DESCRIPTION
**Pull request by tvsonar**

### CODE REVIEW

**Comment by srivatsn** [comment]
:+1: Thanks @tvsonar

**Comment by VSadov** [comment]
Is it possible to add a test to make sure the scenario does no regress?

**Comment by gafter** [comment]
:+1:

**Comment by tvsonar** [comment]
I'll probably not add the test. It seems to me that this method is reachable from `SyntaxExtensions.NormalizeWhitespace()`, but I couldn't find any tests for `SyntaxExtensions`. 

Also, this fix has been already added to your master branch 4 days ago.

**Comment by rasoulian** [comment]
Thanks @tvsonar :+1:

**Comment by VSadov** [comment]
Indeed, the change is already in.

**Comment by VSadov** [comment]
I guess, I will close the PR, then.

**Pull request closed without merging**
