### PR TITLE
Results of using 'use collection expressions'

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
NOT FOR MERGING.

### CODE REVIEW

**Comment by tmat** [comment]
>                         semanticEdits: [

I'd prefer the indentation to follow the `{` and `}`. That is, delete `new[]` and replace braces with brackets.

---
Refers to: src/EditorFeatures/CSharpTest/EditAndContinue/TopLevelEditingTests.cs:2430 in 11fe3a4. [](commit_id = 11fe3a442da3bed38dba7b864fd014fbf609b75c, deletion_comment = False)

**Comment by CyrusNajmabadi** [comment]
> I'd prefer the indentation to follow { and }. That is, delete new[] and replace braces with brackets.

So, current design decision (including at language) is to align these with with list-patterns.  This is, after all, the way to construct collections (just as the pattern deconstructs it).

With the pattern form, we looked at the options and explicitly choose the c#'y way is to write it as `if (x is [var a, .. var b, var c])`.  That is: no spaces on the inside of the `[]` braces, and a space after the `..` part.  The construction side formatting mirrors that style *intentionally* :)

**Comment by tmat** [comment]
I don't follow. How would you format list pattern that's multi-line?

```C#
if (x is [
  a,
  b,
])
{
}
```

or 

```C#
if (x is
 [
  a,
  b,
 ])
{
}
```

**Comment by tmat** [comment]
>  no spaces on the inside of the [] braces

That's fine. I didn't mean that there should be spaces between `[` and `]`.

**Comment by tmat** [comment]
Let me clarify: I'm talking about these two cases:

image

They are handled inconsistently. First is what I'd prefer - replace `{` with `[`, `}` with `]` and erase `new()`. The second is leaving `[` at the end of line even when `{` is on the next line.

**Comment by CyrusNajmabadi** [comment]
I see.  will bring for discussing.  Forcing a newline before the start seems undesirable.  But we'll get a team/design read on this.

**Pull request closed without merging**
