### PR TITLE
Update code to use range operator

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by mavasani** [comment]
I presume there is an analyzer/code fix pair to identify all these replacements? If so, can we enforce this as an analyzer warning in the repo editorconfig, at least for the IDE layer?

**Comment by CyrusNajmabadi** [comment]
> I presume there is an analyzer/code fix pair to identify all these replacements?

Yes.

> If so, can we enforce this as an analyzer warning in the repo editorconfig, at least for the IDE layer?

I'd be ok with anyone driving that.  Personally, we might want to enable a bunch of these in the IDE layer to get the coverage.

**Comment by mavasani** [comment]
> I'd be ok with anyone driving that

Is it possible to just update the editorconfig as part of this PR? We already have bunch of IDExxxx analyzers set to warning severity for IDE layers.

**Comment by CyrusNajmabadi** [comment]
> Is it possible to just update the editorconfig as part of this PR? We already have bunch of IDExxxx analyzers set to warning severity for IDE layers.

Missed this.  Where would this go?  I see that there's an editorconfig, but it looks like it affects the compiler as well.

**Comment by mavasani** [comment]
> > Is it possible to just update the editorconfig as part of this PR? We already have bunch of IDExxxx analyzers set to warning severity for IDE layers.
> 
> Missed this. Where would this go? I see that there's an editorconfig, but it looks like it affects the compiler as well.

You can put them under this section header: https://github.com/dotnet/roslyn/blob/348d99811246a5c143579fcc3093101d630d0e25/.editorconfig#L252

**Pull request merged**
