### PR TITLE
Insert value documentation instead of returns for properties

### LINKED ISSUE #8627: VB XML doc inconsistency between template and IntelliSense for property (template contains <returns>, IntelliseSense not)
Related to #8546, there is inconsistency between what gets inserted when I type ''', and what IntelliSense offers for properties.
When I type ''' above property <summary>

 and <returns> gets inserted. But when I delete <returns> and want to insert it again, IntelliSense does not offer it.
vbprop

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #8627

### CODE REVIEW

**Comment by Pilchie** [comment]
I thought we changed this deliberately in Roslyn because nothing we could find (especially quick info) ever read the `value` tag.

**Comment by sharwell** [comment]
@Pilchie Neither the `returns` nor the `value` tags are used by quick info right now.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
@DustinCampbell @AnthonyDGreen I'm interested in moving this forward. Can you review this?

**Comment by sharwell** [comment]
@agocke I need to reopen this one and retarget it to master, but I need the dev15.7.x branch restored first.

**Comment by agocke** [comment]
You can create a new PR.

**Pull request closed without merging**
