### PR TITLE
Merge dev16.4 preview1-vs-deps into dev16.4 preview1

### PR DESCRIPTION
**Pull request by genlu**
Per @jaredpar, our policy for codeflow is the following:
	
1. Developers should always be able to build master in dotnet/roslyn with a publicly available version of VS. 
2. The version of VS should preferably be an RTM one but can be a preview if circumstances warrant it.

Now that 16.4 Preview 1 is out, I'd like to get vs-deps flows back so all our changes related to completion are all in the same branch, which will make it easier for us to make further code change in this area.

@dotnet/roslyn-infrastructure Please let me know if it's OK to do this, otherwise I will probably need to cherry pick those changes manually.

### CODE REVIEW

**Comment by genlu** [comment]
FYI @mavasani, this one seems to contain your fix for errorlist column

**Comment by JoeRobich** [comment]
@genlu Since this doesn't change the version of any dependencies, I don't think it should be a problem.

**Comment by genlu** [comment]
@JoeRobich Good point. Should have checked that first. Thanks! :)

**Comment by genlu** [comment]
@dotnet/roslyn-infrastructure Can I get a sign-off for this?

**Pull request merged**
