### PR TITLE
Mark read-only structs as readonly

### PR DESCRIPTION
**Pull request by alrz**
(These are a few of them that I noticed.)

/cc @CyrusNajmabadi

### CODE REVIEW

**Comment by alrz** [comment]
FYI this is a JB warning on method calls off of struct-typed readonly fields (probably a good candidate for roslyn-analyzers)

**Comment by CyrusNajmabadi** [comment]
>FYI this is discovered by a JB warning on method calls off of struct-typed readonly fields (probably a good candidate for roslyn-analyzers)

Nice.  Tagging @mavasani .  Feel free to send out a bulk fix for anything in the IDE layer.  If you see hte same in the compiler, please send another PR for that.   Thanks!

**Comment by sharwell** [comment]
@alrz We've been looking at https://github.com/SergeyTeplyakov/ErrorProne.NET as a possibility for analyzing these.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
