### PR TITLE
Fix race condition in PerformanceQueue.AnalyzerNumberAssigner

### PR DESCRIPTION
**Pull request by mavasani**
Fixes [AB#1711338](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1711338)

This regression was introduced with my recent PR #65212. Prior to #65212, we had a single PerformanceQueue for reporting analyzer telemetry from background analysis code path. #65212 introduced a separate PerformanceQueue for reporting analyzer telemetry from lightbulb code path. This lead to a race condition in AnalyzerNumberAssigner singleton used by PerformanceQueue type to get a unique number for each analyzer, as the dictionary read/write operations within AnalyzerNumberAssigner can now happen from multiple threads. This PR fixes this race condition by adding locking in AnalyzerNumberAssigner.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]
looks fine to me.  fyi, we have a BidirectionalMap as well so you don't need GetReverseMap.

**Comment by mavasani** [comment]
> looks fine to me. fyi, we have a BidirectionalMap as well so you don't need GetReverseMap.

Thanks, I am going to avoid any more non critical changes here as this is targeting a release branch in M2 mode.

**Comment by mavasani** [comment]
@arkalyanms for M2 approval

**Comment by CyrusNajmabadi** [comment]
@mavasani Agreed.  Was just info in case you touch this code up in the future :)

**Review by arkalyanms — APPROVED** [review]

**Pull request merged**
