### PR TITLE
Fix attempt for issue #13067

### PR DESCRIPTION
**Pull request by Pvlerick**
The issue seems to come from AttributeSignatureHelpProvider.cs that marks the SignatureHelpItem as variadic [only if the last parameter has `params` and there is no `namedParameters`](https://github.com/dotnet/roslyn/blob/master/src/Features/CSharp/Portable/SignatureHelp/AttributeSignatureHelpProvider.cs#L131) . However, `namedParameters` is declared a few lines above and takes all the properties available to be treated as named parameters in ([see INamedTypeSymbolExtensions.cs](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Shared/Extensions/INamedTypeSymbolExtensions.cs#L419)).

This prevents the item to be marked as variadic so the help provider will always advance as items are added, while it should stay on the params.

I added a unit test for this, but I'm not able to run a dev instance of VS that work properly (I get the "Visual C# 2015 compiler could not be created" or a vanilla C# editor with no intellisense or syntax highlighting.

It would be wise to check that as soon as you wrote a few param and an attribute, it switches to a potential next attribute.

### CODE REVIEW

**Comment by Pilchie** [comment]
Thanks for the submission!

Tagging @dotnet/roslyn-ide for review.

@dotnet-bot test vsi please.

It looks like the integration test failure may be legitimate.  @brettfo can you help with this?  The failures are:

> 14:02:25 Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.Hosting.Test.VerifySignatureHelpAction]: Expected:[C.OutAndParam(ByRef strings As String()(,), ByRef outArr As String(), ParamArray d As Object)
14:02:25 Complex Method Params
14:02:25 
14:02:25 
14:02:25 strings (Jagged MultiDimensional Array)
14:02:25 strings (Jagged MultiDimensional Array),outArr (Out Array),d (Dynamic and Params param)]
14:02:25 Actual:[C.OutAndParam(ByRef strings As String()(,), ByRef outArr As String(), ParamArray d As Object)
14:02:25 Complex Method Params
14:02:25 
14:02:25 
14:02:25 d (Dynamic and Params param)
14:02:25 strings (Jagged MultiDimensional Array),outArr (Out Array),d (Dynamic and Params param)]

and 

> 14:02:25 Tao.Engine.Exceptions.UnexpectedResultException`1[Roslyn.Hosting.Test.VerifySignatureHelpAction]: Expected:[void C.OutAndParam(ref string[][,] strings, out string[] outArr, params dynamic d)
14:02:25 Complex Method Params
14:02:25 
14:02:25 
14:02:25 strings (Jagged MultiDimensional Array)
14:02:25 strings (Jagged MultiDimensional Array),outArr (Out Array),d (Dynamic and Params param)]
14:02:25 Actual:[void C.OutAndParam(ref string[][,] strings, out string[] outArr, params dynamic d)
14:02:25 Complex Method Params
14:02:25 
14:02:25 
14:02:25 d (Dynamic and Params param)
14:02:25 strings (Jagged MultiDimensional Array),outArr (Out Array),d (Dynamic and Params param)]

**Comment by brettfo** [comment]
Sure thing, looking at it now.

**Comment by brettfo** [comment]
@Pvlerick, the internal test failures are legitimate and you'll likely need more unit tests to cover it.  In short, with the following code where '$$' represents the cursor's location, signature help incorrectly highlights the `params` array where it should highlight the first `int x`.

``` C#
[MyAttribute($$)]
class MyAttribute : System.Attribute
{
    public MyAttribute(int x, params string[] args) { }
    public int Role { get; set; }
}
```

**Comment by Pvlerick** [comment]
Thanks for the feedback, I'll investigate.

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
@Pvlerick Did you have a chance to investigate the integration test failures? Regarding your "VS 2015 Compiler Could not be created issue"--VS 2017 is now a requirement in order to be able to develop Roslyn. See https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building,%20Debugging,%20and%20Testing%20on%20Windows.md for details. Note that you can install the free Community edition of 2017.

**Comment by jaredpar** [comment]
We apologize, but we are closing this PR due to code drift. We regret letting this PR go so long without attention, but at this point the code base has changed too much for us to revisit older PRs. Going forward, we will manage PRs better under an SLA currently under draft in issue #26266 – we encourage you to add comments to that draft as you see fit. Although that SLA is still in draft form, we nevertheless want to move forward with the identification of older PRs to give contributors as much early notice as possible to review and update them.

If you are interested in pursuing this PR, please reset it against the head of master and we will reopen it. Thank you!

**Pull request closed without merging**
