### PR TITLE
WIP [tests] Re-enable Mono CI testing, and test MultipleTypeForwardersToTheSameAssemblyShouldNotResultInMultipleForwardError

### PR DESCRIPTION
**Pull request by lambdageek**
Re-enable testing on CI with Mono - the issue https://github.com/mono/mono/issues/16373 that prevented testing was fixed in September 2019.

---

Re-enable`MultipleTypeForwardersToTheSameAssemblyShouldNotResultInMultipleForwardError` for Mono. The Mono issue https://github.com/mono/mono/issues/10332 has been fixed on 
6.8 (2019-10), 6.10 (2019-12) and master.

Tested with Mono 6.8.0.92 and Mono 6.10.0.40

### CODE REVIEW

**Comment by JoeRobich** [comment]
@lambdageek The integration test failure is a known flaky test. I did see lots of Mono test failures with "Explicit assembly load didn't update the proper cache: 'System.ValueTuple'" issues.

**Comment by lambdageek** [comment]
> "Explicit assembly load didn't update the proper cache: 'System.ValueTuple'"

Yep, I see that locally too.   I think this is something new that popped up since the Mono CI was disabled. I'll try to figure out where it's coming from.

**Comment by lambdageek** [comment]
Mono investigation tracked over at https://github.com/mono/mono/issues/18388

**Comment by lambdageek** [comment]
Detailed notes here:
https://github.com/mono/mono/issues/18388#issuecomment-572720782

I think I need to bump src/Compilers/Test/Resources/Core/NetFX/ValueTuple/System.ValueTuple.dll to the latest one (with assembly version 4.0.3.0, instead of the current 4.0.1.0).

Is that okay, @JoeRobich ?

**Comment by JoeRobich** [comment]
> I think I need to bump src/Compilers/Test/Resources/Core/NetFX/ValueTuple/System.ValueTuple.dll to the latest one (with assembly version 4.0.3.0, instead of the current 4.0.1.0).

@agocke @tmat Will this cause any problems we aren't thinking of?

**Comment by tmat** [comment]
Should be fine.

**Comment by lambdageek** [comment]
Tried to bump the System.ValueTuple.dll and got about 700 test failures like this one https://gist.github.com/lambdageek/a31a7bc5f0fef28c959a75dca1b6a53a

I think the problem is that by default all of those tests are compiling with `TargetFramework.Standard` which on Mono ends up using the `Mscorlib46ExtendedReferences` which is the net46 mscorlib.

https://github.com/dotnet/roslyn/blob/8b7bed34f48ba411eae9e6e0fe3dcce7ef4fccfe/src/Test/Utilities/Portable/TargetFrameworkUtil.cs#L97-L124

But the 4.0.3.0 System.ValueTuple.dll that I want to use - the one with the correct MVID - it is the net47 one and it uses type forwarders for the ValueTuple types.

I think I'm heading in the wrong direction.

**Comment by AlekseyTs** [comment]
> I think I'm heading in the wrong direction.

It sounds like we need to add a new target framework and change Standard to use that for Mono and perhaps for Desktop as well.

**Comment by jaredpar** [comment]
Couple of things here:

1. It's reasonable to change `Standard` to be net472 on Desktop. The intent of `Standard` was to be a floating value. Tests which weren't specifically geared at testing a corner case in say net45 should target `Standard`. This gives us flexibility in how we update our test infrastructure to deal with the changing realities of our runtimes.
1. Changing `Standard` to net472 isn't going to fully solve this particular problem. IIRC there are plenty of tuple tests that target other frameworks.
1. https://github.com/mono/mono/issues/18388 is another example of why I think we need to move to testing against a fixed version of mono vs. nightly. By fixed I mean a hard coded version that we regularly update, just as we do for other dependencies. Using latest mean that when issues like this popup it suddenly breaks CI on all of our branches. Can be a bit of work to undo Mono everywhere and then redo it later. Having a fixed version number that we iterate means we catch Mono breaks at PR time vs. whenever nightly updates.

**Comment by agocke** [comment]
I think one of the other problems you'll run into is that many of our tests assumed System.ValueTuple *wasn't* in the standard library, while in 472 it is.

Basically, this is probably gonna be a big pain.

**Comment by lambdageek** [comment]
Found the behavior difference. It's a bug in Mono.  In Mono `Assembly.ReflectionOnlyLoad (byte[] rawAssembly)` applies binding redirections [and in .NET Framework it doesn't](http://blogs.microsoft.co.il/sasha/2010/06/09/assemblyreflectiononlyload-ignores-assembly-binding-redirects/).  Going to fix up Mono and will PR Roslyn again once there's a good nightly build available.

Thanks for the help everyone!

**Pull request closed without merging**
