### PR TITLE
removed additional cost I can find from trace compared to code before…

### PR DESCRIPTION
**Pull request by heejaechang**
… primary workspace changes.

**Customer scenario**

User opens solution in VS. VS allocates less and use less refset while opening solution.

**Bugs this fixes:** 

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/364131
https://github.com/dotnet/roslyn/issues/16410

**Workarounds, if any**

no workaround

**Risk**

since there is no functional changes. it won't have risk regarding that. so far manual testing shows better perf. also verified with private RPS run that code that caused the regression no longer run,

this PR also went through private testing from vendor and didn't find any issue.

**Performance impact**

it should improve allocations and refset perf.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

While OOP is changed to use new design to make it better on VM and CPU usage, Allocation and Refset usage got increased. this is to reduce that back to where it used to be.

fix here do following this.

1. make sure OOP synchronization happens after solution opening (modal portion) is done
2. make sure OOP synchronization do bulk synchronization as much as possible.
3. delay checksum calculation until it is needed.

**How was the bug found?**

performance testing and manual performance investigation.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @dotnet/roslyn-perf

**Comment by heejaechang** [comment]
@mavasani @tmeschter so I guess I need to get RPS number before asking for approval. what should I do?

**Comment by heejaechang** [comment]
@mavasani ping?

**Comment by heejaechang** [comment]
@srivatsn @mavasani @panopticoncentral can I get some code review. I would like to bring this to RTW. this reduce allocations quite a bit according to my manual testing.

tagging @rchande for solution event monitor change.

**Comment by rchande** [comment]
👍 for solutioneventmonitor changes

**Comment by heejaechang** [comment]
@mattscheffer did private testing and didn't find any issue.

**Comment by heejaechang** [comment]
@mavasani @srivatsn @panopticoncentral can I get some code review?

**Comment by heejaechang** [comment]
@srivatsn @natidea I wonder whether this will still meet the bar but otherwise, still want for update 1.

**Comment by mavasani** [comment]
> I wonder whether this will still meet the bar but otherwise, still want for update 1.

I think RPS regressions will still probably meet the bar, though this one is just a refset regression, so might not be a certainty.

**Comment by heejaechang** [comment]
@mavasani as the description said, I already asked vendor to go through some testings on private signed bit.

**Comment by mavasani** [comment]
Ah, I missed those lines in the description, thanks 👍

**Comment by heejaechang** [comment]
ping, one more sign off?

**Comment by srivatsn** [comment]
Tagging @MattGertz for RTM consideration.

**Comment by heejaechang** [comment]
@natidea can I check this in?

**Pull request merged**
