### PR TITLE
Revert "Merge pull request #8906 from amcasey/HidePane2"

### PR DESCRIPTION
**Pull request by TyOverby**
This reverts commit 0e7a2b6e4fd3e79a78843319af965f5153bf21ad, reversing
changes made to e1f34faa3a7f8c60c9489cfee0d46d918cfe0652.

### CODE REVIEW

**Comment by amcasey** [comment]
test prtest/win/vsi/p3 please

**Comment by amcasey** [comment]
LGTM, assuming the tests pass.

**Comment by TyOverby** [comment]
@amcasey Tests failed.  Please investigate as a priority-1

It looks like [the corresponding change to future](https://github.com/dotnet/roslyn/pull/9449) broke as well

**Comment by amcasey** [comment]
@tyoverby Looks like a real but unrelated failure.  I'd ask the @dotnet/roslyn-compiler.

**Comment by amcasey** [comment]
I can't repro the failure locally and I remain extremely skeptical that my change to the Interactive Window UI could have broken a semantic model test.

**Comment by amcasey** [comment]
test prtest/win/dbg/unit32 please

**Comment by amcasey** [comment]
test prtest/win/dbg/unit64 please

**Comment by amcasey** [comment]
I've tried future and future-stabilization with and without my change.  I have yet to repro the failure locally.

**Comment by amcasey** [comment]
@TyOverby Passed on re-run.  Merge?

**Comment by TyOverby** [comment]
Yeah, I've been trying to repro locally too without any luck.  Do you have the link to the jenkins failure so we can see if it's a flakyness issue?  

I'm going to merge, but I'd like to investigate further.

**Comment by amcasey** [comment]
http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4786/

I couldn't find other occurrences (other than an unmerged community PR)

**Comment by amcasey** [comment]
The failure is expected vs actual diagnostics.  Such tests are rarely flakey.

**Comment by amcasey** [comment]
@tyoverby I notice that https://github.com/dotnet/roslyn/pull/8594 modifies the expected diagnostics in the failing test.  Is it conceivable that the test run somehow included both my change and the community PR?

**Comment by TyOverby** [comment]
@amcasey That sounds like what happened.  In fact, we hit this recently where Jenkins was reporting successes and failures in the wrong PR.

Investigation = closed

**Pull request merged**
