### PR TITLE
Constant-folding should not use excess precision.

### LINKED ISSUE #7262: Constant propagation uses wrong floating-point precision
Edit: Deleted first example, because it's almost certainly covered by §4.1.6 allowing that "Floating-point operations may be performed with higher precision than the result type of the operation. ... Other than delivering more precise results, this rarely has any measurable effects." 

I'm assuming this means that a constant expression `(int) (23334800f / 5.5f)` is allowed to be performed with double-precision arithmetic (and not coerced to a `float`) before the truncation to `int`.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #7262 

The Roslyn C# compiler stores constants of type `System.Single` (i.e. `float`) internally as type `double`, but without truncating the value to the required precision. Also, it computes binary constant-folded operators incorrectly, essentially computing the operation in double precision. It also ignores explicit casts to `float`, as those are considered identity conversions, but the language spec required that we truncate precision when we see such a cast.

This change causes floating-point constant-folding operations to be done in precisely the proper precision, and causes casts to truncate precision. With the first change, the latter change may turn out to be a no-op (when the value is already a float, it should already have the correct value with the correct precision), but I'm doing it for completeness.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@gafter How do old and new behavior of the Roslyn compiler compare to the behavior of the native compiler?

**Comment by gafter** [comment]
@AlekseyTs The native compiler uses the wrong precision, even when there is an explicit cast to `float`. However, I should point out that the requirement that the compiler generate code to truncate precision in the presence of the cast was added to the specification in C# 6.

**Comment by AlekseyTs** [comment]
LGTM, other than the fact that this is a breaking change.

**Comment by gafter** [comment]
The question (whether we want to obey the new text that has been added to the C# 6 spec even though it is a breaking change) has been submitted to the compatibility council.

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I please have a second review? This has been approved by the compat council.

**Comment by TyOverby** [comment]
LGTM

**Pull request merged**
