### PR TITLE
Do not generate indent guides for nonstructure block spans

### PR DESCRIPTION
**Pull request by JoeRobich**
Resolves https://github.com/dotnet/roslyn/issues/54305

When the various structure tagging was unified (https://github.com/dotnet/roslyn/pull/50889) we didn't take into account non-structural block spans. This had the effect of user's being unable to disable block structure guidelines in C# > Advanced options. With this change we will not generate HeaderSpans (used for the indent guideline) for reported nonstructural tags.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@vatsalyaagrawal For 16.11 Preview 3 as this was a regression.

**Review by sharwell — CHANGES_REQUESTED** [review]
Was this not already fixed by #54079? Prior to my change, we were reporting NonStructural items as Structural, which caused them to appear in the UI.

**Comment by JoeRobich** [comment]
> Was this not already fixed by #54079? Prior to my change, we were reporting NonStructural items as Structural, which caused them to appear in the UI.

Looks like we need to avoid setting the HeaderSpan for nonstructural tags.

**Comment by JoeRobich** [comment]
@sharwell I take it back. Once I tested in the correct build of VS. Your change resolves this issue. Closing

**Pull request closed without merging**
