### PR TITLE
Clarify #help text

### PR DESCRIPTION
**Pull request by amcasey**
Additional cleanup is required, but this is a start.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @cston @KevinH-MS @ManishJayaswal @kuhlenh

**Comment by tmat** [comment]
The strings for each binding should be loaded from localized resources.

**Comment by amcasey** [comment]
@tmat https://github.com/dotnet/roslyn/issues/5093

**Comment by amcasey** [comment]
In my defence, I’d been meaning to file that bug all afternoon. ☺

**Comment by amcasey** [comment]
@dotnet-bot test this please.

**Pull request merged**
