### PR TITLE
Fix switches on creating dump files when VS instance crashes or hangs (integration tests)

### PR DESCRIPTION
**Pull request by ivanbasov**
Removing _-w_ because it requires process name and waits for it to be started. We actually have a running process with an id. The _-w_ switch does not work with process id.

### CODE REVIEW

**Comment by dpoeschl** [comment]
@ivanbasov This is why we aren't getting any dumps currently?

**Comment by dpoeschl** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
@jasonmalinowski @ivanbasov Tests passing. We good to go?

**Comment by tmat** [comment]
@dpoeschl Ivan is oof.

**Comment by ivanbasov** [comment]
Thank you very much everybody for your help with the commit! Verified with @jaredpar that dumps are created now.

**Pull request merged**
