### PR TITLE
Put partial references underneath definitions in the old FAR results window.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is a lot nicer as it makes it so that partial types don't end up with a lot of top level definition items that all say "(0 references)" next to them.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @Pilchie

**Comment by CyrusNajmabadi** [comment]
New UI looks like this:

image

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
I'm also doing this because it makes the work on the Streaming side easier.

**Comment by CyrusNajmabadi** [comment]
Test failure is because we need to update a baseline in Rolsyn-Internal

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
