### PR TITLE
Center the symbol being navigated to when navigating through doc-outline

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/76242

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@ToddGrun @JoeRobich ptal

**Review by ToddGrun — APPROVED** [review]
:shipit:

**Comment by Axium7** [comment]
Thank you for implementing this feature.  What is the ETA for it to be released in a VS Update?

**Comment by CyrusNajmabadi** [comment]
@Axium7 When this is merged into VS a bot will automatically add that information to this PR.

**Comment by Axium7** [comment]
@CyrusNajmabadi thank you.  I am looking forward to this new feature.  Am I to understand it will appear in the next update based on this Note?

image

**Comment by CyrusNajmabadi** [comment]
A bot will mark this with the specific release of VS once it makes it into a particular vs release. Thanks :-)

**Comment by Axium7** [comment]
@CyrusNajmabadi Thank you

**Pull request merged**
