### PR TITLE
Merging branch 'features/test-impact' into 'master'

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @dotnet/testimpact, @dotnet/roslyn-compiler, @dotnet/roslyn-infrastructure 

Explicitly FYI @ManishJayaswal, @jaredpar, @jasonmalinowski

### CODE REVIEW

**Comment by tannergooding** [comment]
test vsi please

**Comment by jaredpar** [comment]
Hmm,  Seems CodeFlow can't open up this PR because it exceeds their commit count.  Could we squash this to < 64 commits just for the purpose of reviewing?  Don't care if this is committed, would actually prefer it.  But can't review in this state due to the size.

**Comment by tannergooding** [comment]
@jaredpar, not without creating a separate branch/PR. Additionally, we have kicked off signed-builds with these SHA's so rewriting history is not really an option either.

**Comment by jaredpar** [comment]
@tannergooding i was basically asking about a separate review PR :)

**Comment by tannergooding** [comment]
@jaredpar https://github.com/dotnet/roslyn/pull/12662

**Comment by tannergooding** [comment]
@jaredpar, could I explicitly get that sign-off you gave offline.

**Comment by jaredpar** [comment]
So long as @jcouv agrees I'm fine.

**Comment by jcouv** [comment]
PROTOTYPE markers need to be removed (and corresponding issues filed) before merging to master.
Also, you need to make sure that IDE stability is not impair by this new code. For tuples, we did some manual validation on that.

Otherwise, this is just a merge, so we don't need to do code review again, LGTM.

**Comment by jaredpar** [comment]
> PROTOTYPE markers need to be removed (and corresponding issues filed) before merging to master.

100% agree.  These all need to be yanked out before merge and turned into issues / fixed.

**Comment by JohnHamby** [comment]
My search turned up precisely one PROTOTYPE (in EmitStatement.cs), which already has a filed issue.

**Comment by jaredpar** [comment]
@JohnHamby can we delete the PROTOTYPE and change it to reference the bug then?

**Comment by tannergooding** [comment]
@JohnHamby, just fyi: fixing the issue and merging it into the features/test-impact branch will update this PR automatically.

**Comment by jcouv** [comment]
LGTM, thanks!

**Comment by JohnHamby** [comment]
@tannergooding I have merged the removal of "PROTOTYPE" into features/test-impact.

**Comment by tannergooding** [comment]
test vsi please

I will merge after the integration tests are shown to be passing (no reason they shouldn't)

**Comment by tannergooding** [comment]
Merged

**Pull request merged**
