### PR TITLE
Enable execution of well known batch fixer from non-VS host

### PR DESCRIPTION
**Pull request by mavasani**
Well known batch fixer expects a MEF exported IDocumentTextDifferencingService, but we only have one in the EditorFeatures layer.
We already have a simple default differencing service in the workspace, this change exports it at the default service layer.
This change unblocks enabling FixAll testing in roslyn-analyzers repo: https://github.com/dotnet/roslyn-analyzers/issues/1420

<details><summary>Ask Mode template</summary>

### Customer scenario

Unable to write FixAll unit tests for fixers using well known batch fixer outside of Roslyn code base.

### Bugs this fixes

https://github.com/dotnet/roslyn-analyzers/issues/1420

### Workarounds, if any

None, except for not using the well known batch fixer.

### Risk

Low as we are just MEF exporting an existing service implementation.

### Performance impact

Low

### Is this a regression from a previous update?

No

### Root cause analysis

We do not have any FixAll unit tests in roslyn-analyzers repo currently. We are planning to add them this sprint.

### How was the bug found?

Attempting to implement https://github.com/dotnet/roslyn-analyzers/issues/1420

### Test documentation updated?

N/A

</details>

### CODE REVIEW

**Comment by sharwell** [comment]
💭 Do you know why this was never a problem for StyleCop Analyzers testing?

**Comment by mavasani** [comment]
@sharwell StyleCop seems to be using a custom well known batch fixer, not Roslyn's well known batch fixer.

**Comment by sharwell** [comment]
@mavasani The custom batch fixer is just an old build of the Roslyn batch fixer with the determinism bug fixed. :smile:

**Comment by mavasani** [comment]
Essentially `differenceService` is null [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/CodeFixes/FixAllOccurrences/BatchFixAllProvider.cs,400) for `AdHocWorkspace`. This is the StyleCopAnalyzers implementation: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/ebf6c5bf6d7903406bada10e22b383d66fe9c021/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/Helpers/CustomBatchFixAllProvider.cs#L387

**Comment by heejaechang** [comment]
@mavasani you probably want to remove new Default... in http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/LinkedFileDiffMerging/LinkedFileDiffMergingSession.cs,89

since we have default service now.

**Comment by mavasani** [comment]
@heejaechang I tried to remove that in the previous commit, but seems it is needed for test path with custom export provider. See the failure: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/10901/testReport/junit/Microsoft.VisualStudio.LanguageServices.UnitTests.Preview/PreviewChangesTests/TestLinkedFileChangesMergedAndDeduplicated/. I will revert my last commit https://github.com/dotnet/roslyn/pull/23492/commits/c24e51ef84668dd7342f2fc63d5597aebf54276c

**Comment by mavasani** [comment]
@Pilchie @jinujoseph for ask mode approval.

**Comment by Pilchie** [comment]
@mavasani I need an ask mode template.

**Comment by mavasani** [comment]
@Pilchie Sorry, added now.

**Pull request merged**
