### PR TITLE
Don't offer Introduce local for expression statement if expr. stm is assignment.

### PR DESCRIPTION
**Pull request by petrroll**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@petrroll can we see if the LHS binds to some symbol?  If so, do not offer the feature.  If not, offer to basically add the type-syntax to create a variable-statement from the assignment statement.

**Comment by petrroll** [comment]
Even if it doesn't bind to anything it would still produce 
`$$asdf = 42;` -> `object p = asdf = 42;`

Or are you proposing also changing the transformation logic to special case the non-bound assignment case?

**Comment by CyrusNajmabadi** [comment]
Yes, the latter :)

**Comment by petrroll** [comment]
Let's make it separate issue, then.

**Pull request merged**
