### PR TITLE
VisualBasic CodeModel Service should handle Declare Function and Sub for St...

### LINKED ISSUE #1839: EnvDTE.CodeFunction.StartPoint, EndPoint, GetStartPoint, etc. cause exception for VB.NET "Declare Sub"/"Declare Function" methods
See MS Connect bug:

https://connect.microsoft.com/VisualStudio/feedback/details/1232254/envdte-codefunction-startpoint-endpoint-getstartpoint-etc-cause-exception-for-vb-net-declare-sub-declare-function-methods

I didn't detect this bug before because there was a previous bug #148.

### PR DESCRIPTION
**Pull request by basoundr**
...artPoint and EndPoint

Fix #1839 : Visual Basic CodeModelService not handles Declaration
Statement for StartPoint and EndPoint.

### CODE REVIEW

**Comment by basoundr** [comment]
This is a preview bug

Reviewers: @Pilchie @jasonmalinowski @DustinCampbell 
Other Reviewers: @dpoeschl @rchande @balajikris @brettfo

**Comment by DustinCampbell** [comment]
Note: The title should be something like "Declare Function/Subs" rather than "Declaration Statements", which are a different thing.

**Comment by Pilchie** [comment]
:+1:

**Comment by basoundr** [comment]
Just modified the comments with this new commit

**Pull request merged**
