### PR TITLE
Addressing documentation feedback

### PR DESCRIPTION
**Pull request by jasonmalinowski**
*Review:* @diryboy, @dpoeschl

### CODE REVIEW

**Comment by dpoeschl** [comment]
:+1:

**Comment by diryboy** [comment]
:+1: Thanks for addressing those!

**Comment by jasonmalinowski** [comment]
I've followed up internally on the failure and it's being looked at.

**Comment by diryboy** [comment]
A small off topic question, I've seen branches under namespace `releases/`, why not this time? No big deal for me though.

**Comment by jasonmalinowski** [comment]
We're going to be getting rid of the releases/ branches in favor of proper tags, since that's what we should have done all along. In this particular case I guess this branch is the release plus some other stuff, so it's not quite the same. But yeah, perhaps I should have put it there.

**Pull request merged**
