### PR TITLE
fix standalone perftests

### PR DESCRIPTION
**Pull request by TyOverby**
@rchande This fixes standalone perftests by exposing the results through a static variable that gets pulled out of the execution environment instead of being returned.

### CODE REVIEW

**Comment by TyOverby** [comment]
@rchande @balajikris

**Comment by rchande** [comment]
I think you meant @basoundr

**Comment by rchande** [comment]
:+1: but this is really sketchy.

**Comment by basoundr** [comment]
What is the motivation behind this change? why is this method preferred over the other?

**Comment by TyOverby** [comment]
@rchande @basoundr 

The basic problem is this: running `csi.exe foo.csx` enforces that the return value of foo.cxs is an int.  However, we had foo.csx returning a List<PerfTest>, which worked when run from `runner.csx`, but not when run directly.  One way to solve this would be to `#if` around this by checking to see if we are being run through the runner or not, but this is blocking on https://github.com/dotnet/roslyn/issues/10438.

**Comment by TyOverby** [comment]
@rchande and yeah, I'm grossed out by it too, but I talked to @tmat and we think that this is the only way...

**Comment by basoundr** [comment]
:+1:

**Comment by TyOverby** [comment]
ping @basoundr

**Pull request merged**
