### PR TITLE
Treat .csx/.vbx as regular source files not script from command-line compilers

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@tmat, @ManishJayaswal, @jaredpar

**Comment by tmat** [comment]
@cston Are you looking into disallowing SourceCodeKind.Script and Interactive to be passed to the parse options ctor? Rather then creating another internal ctor as I suggested above we could also just make WithSourceCodeKind internal and use that.

**Comment by tmat** [comment]
@dotnet-bot Retest this, please.

**Comment by gafter** [comment]
FYI, this PR missed the stabilization branch cutoff

**Pull request merged**
