### PR TITLE
Include job attempt in log artifact name

### LINKED ISSUE #49214: CI runs fail with "Logs already exists for build"
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=877444&view=logs&j=7f45203e-c771-5e03-a313-4b8cfc15296a&t=9ba0a9f3-f509-5f5b-bb77-a8bffa790afb&l=28

I am wondering if it's impossible for test runs to succeed on retry sometimes because it can't upload logs at the end? I'm not sure if I'm interpreting the CI log properly or not.

/cc @jaredpar

### PR DESCRIPTION
**Pull request by RikkiGibson**
Fixes #49214

### CODE REVIEW

**Comment by RikkiGibson** [comment]
To test this, I think it's necessary to introduce a failure that will definitely write out a log that we can publish. Do you have an idea for how to easily do this @jaredpar?

**Review by jaredpar — APPROVED** [review]

**Comment by jaredpar** [comment]
Easiest way is to introduce a simple build break in MS.CA. That will break the build quickly .

**Review by JoeRobich — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Testing in https://dev.azure.com/dnceng/public/_build/results?buildId=997542&view=results

**Comment by RikkiGibson** [comment]
I'm satisfied this does what we want, looking at the behavior of the above pipeline over multiple attempts.

**Pull request merged**
