### PR TITLE
Explicitly hold on to fields that can be accessed from background thread...

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
... in local so that we don't run into NullReferenceException / ArgumentNullException when these end up getting cleared as part of Dispose()

Following my change f6a925cafe2bb4b4dc517d0b85b928caa8df6664, an internal test failed with the following stack trace. As far as I can tell this crash should have always been there, but somehow my change made it more likely to repro.

In any case, I think this is a race that's happening because we end up accessing fields that are cleared during ```Dispose()``` concurrently from a different thread. The fix is to hold on to the objects in the fields via locals (as we already do in other places in this file) so that we can continue to refer to them without crashing after the fields are cleared in the race case.

```
System.AggregateException: Exceptions found in the exception log ---> System.ArgumentNullException: Value cannot be null.
Parameter name: buffer
   at Microsoft.CodeAnalysis.Text.Extensions.TextBufferContainer.From(ITextBuffer buffer) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\EditorFeatures\Text\Extensions.TextBufferContainer.cs:line 46
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.Source.OnSuggestedActionsChanged(Workspace currentWorkspace, DocumentId currentDocumentId, Int32 solutionVersion, DiagnosticsUpdatedArgs args) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\EditorFeatures\Core\Implementation\Suggestions\SuggestedActionsSourceProvider.cs:line 588
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.Source.OnDiagnosticsUpdated(Object sender, DiagnosticsUpdatedArgs e) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\EditorFeatures\Core\Implementation\Suggestions\SuggestedActionsSourceProvider.cs:line 571
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.RaiseDiagnosticsUpdated(Object sender, DiagnosticsUpdatedArgs state) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\DiagnosticAnalyzerService_UpdateSource.cs:line 21
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.RaiseDiagnosticsUpdated(StateType type, Object key, DiagnosticAnalyzer analyzer, SolutionArgument solution, ImmutableArray`1 diagnostics) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 599
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeSyntaxAsync>d__45.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 141
   --- End of inner exception stack trace ---
   at Roslyn.Hosting.Test.CloseTargetAction.ExecuteOnUIThread() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Closed\Hosting\Test\Actions\EditorTestApp\CloseTargetAction.cs:line 16
   at Roslyn.Hosting.Test.EditorTestAppAction.<>c__DisplayClass24_0.<ExecuteOnUIThread>b__0() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Closed\Hosting\Test\Actions\EditorTestApp\EditorTestAppAction.cs:line 154
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: buffer
   at Microsoft.CodeAnalysis.Text.Extensions.TextBufferContainer.From(ITextBuffer buffer) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\EditorFeatures\Text\Extensions.TextBufferContainer.cs:line 46
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.Source.OnSuggestedActionsChanged(Workspace currentWorkspace, DocumentId currentDocumentId, Int32 solutionVersion, DiagnosticsUpdatedArgs args) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\EditorFeatures\Core\Implementation\Suggestions\SuggestedActionsSourceProvider.cs:line 588
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionsSourceProvider.Source.OnDiagnosticsUpdated(Object sender, DiagnosticsUpdatedArgs e) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\EditorFeatures\Core\Implementation\Suggestions\SuggestedActionsSourceProvider.cs:line 571
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.RaiseDiagnosticsUpdated(Object sender, DiagnosticsUpdatedArgs state) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\DiagnosticAnalyzerService_UpdateSource.cs:line 21
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.RaiseDiagnosticsUpdated(StateType type, Object key, DiagnosticAnalyzer analyzer, SolutionArgument solution, ImmutableArray`1 diagnostics) in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 599
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeSyntaxAsync>d__45.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.<AnalyzeSyntaxAsync>d__44.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\Diagnostics\EngineV1\DiagnosticIncrementalAnalyzer.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<>c__DisplayClass27_1`1.<<RunAnalyzersAsync>b__0>d.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 197
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<GetOrDefaultAsync>d__29`2.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<RunAnalyzersAsync>d__27`1.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.<ProcessDocumentAnalyzersAsync>d__26.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.IncrementalAnalyzerProcessor.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.HighPriorityProcessor.<ProcessDocumentAsync>d__16.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.HighPriorityProcessor.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.SolutionCrawlerRegistrationService.WorkCoordinator.IncrementalAnalyzerProcessor.HighPriorityProcessor.<ExecuteAsync>d__14.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\WorkCoordinator.HighPriorityProcessor.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionCrawler.IdleProcessor.<ProcessAsync>d__12.MoveNext() in C:\Builds\Roslyn\Main-PerCheckin-Release\src\Open\src\Features\Core\SolutionCrawler\IdleProcessor.cs:line 94<---

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@heejaechang @mavasani could you please take a look?

**Comment by mavasani** [comment]
:+1:

**Comment by srivatsn** [comment]
:+1:

**Comment by heejaechang** [comment]
+1

**Pull request merged**
