### PR TITLE
Microsoft.CodeAnalysis.Metadata and Microsoft.CodeAnalysis.PooledObjects

### PR DESCRIPTION
**Pull request by tmat**
Factor code parsing Custom Debug Information to Microsoft.CodeAnalysis.Metadata shared project, and common object pools to Microsoft.CodeAnalysis.PooledObjects.

Moves both shared projects to Dependencies directory. 

The goal is to allow above code to be reused across repos without creating new dlls and/or public APIs. Next step is to package this code into a source-only nuget so that it can be imported by other repos.

We should also consider moving dynamic code analysis resource parsing code to Microsoft.CodeAnalysis.Metadata project.

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn-compiler @dotnet/roslyn-interactive

**Comment by jaredpar** [comment]
Can we keep the directory names shorter?  The Roslyn standand for project directories is to **not** use the full DLL name as is being done with `Dependencies\Microsoft.CodeAnalysis.PooledObjects`.  Prefer we keep that here and just use PooledObjects.

**Comment by tmat** [comment]
@jaredpar That doesn't work since we already have Metadata directory in Dependencies (for System.Reflection.Metadata).

**Comment by jaredpar** [comment]
Then pick a new name. I'd rather keep the current standard then add a random deviation.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Mon, Jul 18, 2016 at 7:46 PM -0700, "Tomáš Matoušek" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jaredpar<https://github.com/jaredpar> That doesn't work since we already have Metadata directory in Dependencies (for System.Reflection.Metadata).

**Comment by tmat** [comment]
Any suggestions for the name? Note that "Microsoft.CodeAnalysis.Metadata" is eventually gonna be a nuget package name. 
I guess I can rename the existing Metadata directory to SystemMetadata.

**Comment by crummel** [comment]
Build triggered. sha1 is original commit.

**Comment by tmat** [comment]
Renamed the directories to ```PooledObjects``` and ```CodeAnaysis.Metadata```.

**Pull request merged**
