### PR TITLE
Use actual multiline string literals in VB tests.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test internal-perf

**Comment by mmitche** [comment]
@dotnet-bot test internal-perf

**Comment by mmitche** [comment]
@dotnet-bot test internal-perf

**Comment by mmitche** [comment]
(ignore results on that)

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit32_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_release_unit32_prtest  please

**Pull request merged**
