### PR TITLE
Disable saving source texts to memory mapped files on non-Windows platforms

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Resolves https://github.com/dotnet/vscode-csharp/issues/7119

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dibarbet ptal

**Comment by sharwell** [comment]
Why is this reaching an AccessViolationException, as opposed to a PlatformNotSupportedException/NotSupportedException/NotImplementedException somewhere before that?

**Comment by sharwell** [comment]
In that case, it should be an IOException, but the point still holds. Something is assuming a pointer is valid when it is not.

**Comment by CyrusNajmabadi** [comment]
> In that case, it should be an IOException, but the point still holds. Something is assuming a pointer is valid when it is not.

@sharwell The call to create the MMF succeeds.  But writing it fails on linux when it actually tries to write to the portion of the mapped file that exceeds the allowed size of the environment.

**Comment by mjrist** [comment]
Any update on this? We are working around this by increasing the shared mem limit as described here (https://github.com/dotnet/vscode-csharp/issues/7119#issuecomment-2123745792), but would prefer not to do that.

**Comment by dibarbet** [comment]
> Any update on this? We are working around this by increasing the shared mem limit as described here ([dotnet/vscode-csharp#7119 (comment)](https://github.com/dotnet/vscode-csharp/issues/7119#issuecomment-2123745792)), but would prefer not to do that.

Had to take a slightly different approach - the new version of the fix is here - https://github.com/dotnet/roslyn/pull/74339

**Comment by CyrusNajmabadi** [comment]
Closing out in favor of David's solution.

**Pull request closed without merging**
