### PR TITLE
Merge Patterns to Future

### PR DESCRIPTION
**Pull request by jaredpar**
Merge the initial patterns feature support into future.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @roslyn-compiler, @CyrusNajmabadi, @DustinCampbell, @Pilchie

**Comment by gafter** [comment]
LGTM

**Comment by jaredpar** [comment]
@dotnet/roslyn-compiler need one more sign off and this is a bit time critical.  Need to get this merged by early tomorrow AM.

**Comment by davkean** [comment]
test vsi please

**Comment by davkean** [comment]
Congrats!

**Pull request merged**
