### PR TITLE
Add handling of ArrowExpressionClauseSyntax nodes to LocalBinderFactory.

### LINKED ISSUE #971: Assert failure at Csharp Binder, triggered by Intellisense when typing expression-bodied members with AnonymousMethodExpressions
1. Open visual studio with debug bits of Roslyn
2. In a C# file, type
`
    Func<int, int> X() => delegate (int y)
    {
        return 8;
    }
`
3. Assert fail dialog pops up while typing the `return` statement.

~~~
System.Exception: ASSERT FAILED 
3/2/2015 1:19:54 PM
   at Microsoft.CodeAnalysis.CSharp.LocalBinderFactory.DefaultVisit(SyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\LocalBinderFactory.cs:line 350
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitArrowExpressionClause(ArrowExpressionClauseSyntax node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\obj\Debug\Syntax.xml.Generated.cs:line 68323
   at Microsoft.CodeAnalysis.CSharp.Syntax.ArrowExpressionClauseSyntax.Accept(CSharpSyntaxVisitor visitor) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\obj\Debug\Syntax.xml.Generated.cs:line 61506
   at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.Visit(SyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Syntax\CSharpSyntaxVisitor.cs:line 46
   at Microsoft.CodeAnalysis.CSharp.LocalBinderFactory.BuildMap(MethodSymbol method, CSharpSyntaxNode syntax, Binder enclosing, Boolean& sawYield) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\LocalBinderFactory.cs:line 49
   at Microsoft.CodeAnalysis.CSharp.ExecutableCodeBinder.get_BinderMap() in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\ExecutableCodeBinder.cs:line 61
   at Microsoft.CodeAnalysis.CSharp.ExecutableCodeBinder.GetBinder(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\ExecutableCodeBinder.cs:line 45
   at Microsoft.CodeAnalysis.CSharp.Binder.GetBinder(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 149
   at Microsoft.CodeAnalysis.CSharp.Binder.GetBinder(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\Binder.cs:line 149
   at Microsoft.CodeAnalysis.CSharp.ExecutableCodeBinder.GetBinder(CSharpSyntaxNode node) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Binder\ExecutableCodeBinder.cs:line 45
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetLambdaEnclosingBinder(Int32 position, CSharpSyntaxNode startingNode, CSharpSyntaxNode containingLambda, Binder lambdaBinder) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1294
   at Microsoft.CodeAnalysis.CSharp.MemberSemanticModel.GetEnclosingBinderInternal(Int32 position) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\MemberSemanticModel.cs:line 1216
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingBinder(Int32 position) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1064
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.GetEnclosingBinderInternal(Int32 position) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\SyntaxTreeSemanticModel.cs:line 163
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.GetEnclosingBinder(Int32 position) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1064
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupSymbolsInternal(Int32 position, NamespaceOrTypeSymbol container, String name, LookupOptions options, Boolean useBaseReferenceAccessibility) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1418
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupSymbols(Int32 position, INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 1254
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.LookupSymbolsCore(Int32 position, INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) in E:\Roslyn\Main\Open\src\Compilers\CSharp\Portable\Compilation\CSharpSemanticModel.cs:line 4600
   at Microsoft.CodeAnalysis.SemanticModel.LookupSymbols(Int32 position, INamespaceOrTypeSymbol container, String name, Boolean includeReducedExtensionMethods) in E:\Roslyn\Main\Open\src\Compilers\Core\Portable\Compilation\SemanticModel.cs:line 428
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsForExpressionOrStatementContext(CSharpSyntaxContext context, Boolean filterOutOfScopeLocals, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Recommendations\CSharpRecommendationService.cs:line 257
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsForCurrentContext(CSharpSyntaxContext context, Boolean filterOutOfScopeLocals, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Recommendations\CSharpRecommendationService.cs:line 80
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetSymbolsWorker(CSharpSyntaxContext context, Boolean filterOutOfScopeLocals, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Recommendations\CSharpRecommendationService.cs:line 64
   at Microsoft.CodeAnalysis.CSharp.Recommendations.CSharpRecommendationService.GetRecommendedSymbolsAtPositionWorker(Workspace workspace, SemanticModel semanticModel, Int32 position, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\CSharp\Portable\Recommendations\CSharpRecommendationService.cs:line 32
   at Microsoft.CodeAnalysis.Recommendations.AbstractRecommendationService.GetRecommendedSymbolsAtPosition(Workspace workspace, SemanticModel semanticModel, Int32 position, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Recommendations\AbstractRecommendationService.cs:line 21
   at Microsoft.CodeAnalysis.Recommendations.Recommender.GetRecommendedSymbolsAtPosition(SemanticModel semanticModel, Int32 position, Workspace workspace, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Recommendations\Recommender.cs:line 23
   at Microsoft.CodeAnalysis.CSharp.Completion.Providers.SymbolCompletionProvider.GetSymbolsWorker(AbstractSyntaxContext context, Int32 position, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\CSharp\Completion\CompletionProviders\SymbolCompletionProvider.cs:line 28
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetSymbolsWorker(Int32 position, Boolean preselect, AbstractSyntaxContext context, OptionSet options, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 230
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__17.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 204
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, Boolean preselect, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.<GetItemsWorkerAsync>d__16.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractSymbolCompletionProvider.cs:line 172
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetItemsWorkerAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetItemsAsync>d__7.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 64
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.GetItemsAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.<GetGroupAsync>d__4.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\Completion\Providers\AbstractCompletionProvider.cs:line 22
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.Providers.AbstractCompletionProvider.GetGroupAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.GetGroupAsync(ICompletionProvider provider, Document documentOpt, SourceText text, Int32 position, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken) in E:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 215
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__13.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 136
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.GetGroupsAsync(Document documentOpt, SourceText text, Int32 position, CompletionTriggerInfo triggerInfo, IEnumerable`1 completionProviders, OptionSet options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.<GetGroupsAsync>d__10.MoveNext() in E:\Roslyn\Main\Open\src\Features\Core\Completion\AbstractCompletionService.cs:line 84
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Completion.AbstractCompletionService.GetGroupsAsync(Document document, Int32 position, CompletionTriggerInfo triggerInfo, IEnumerable`1 completionProviders, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<GetGroupsAsync>d__16.MoveNext() in E:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 146
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.GetGroupsAsync(ICompletionService completionService, CompletionTriggerInfo triggerInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Controller.Session.ModelComputer.<DoInBackgroundAsync>d__15.MoveNext() in E:\Roslyn\Main\Open\src\EditorFeatures\Core\Implementation\Intellisense\Completion\Controller.Session_ComputeModel.cs:line 106
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Text.Extensions.<GetDocumentWithFrozenPartialSemanticsAsync>d__10.MoveNext() in E:\Roslyn\Main\Open\src\EditorFeatures\Text\Extensions.cs:line 126
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Document.<WithFrozenPartialSemanticsAsync>d__27.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Workspace\Solution\Document.cs:line 414
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.Solution.<WithFrozenPartialCompilationIncludingSpecificDocumentAsync>d__132.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Workspace\Solution\Solution.cs:line 1909
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Microsoft.CodeAnalysis.DocumentState.<GetSyntaxTreeAsync>d__29.MoveNext() in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Workspace\Solution\DocumentState.cs:line 482
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
   at Roslyn.Utilities.AsyncLazy`1.Request.CompleteFromTaskSynchronously(Task`1 task) in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Utilities\AsyncLazy`1.cs:line 586
   at Roslyn.Utilities.AsyncLazy`1.Request.CompleteFromTaskSynchronouslyStub(Object task) in E:\Roslyn\Main\Open\src\Workspaces\Core\Portable\Utilities\AsyncLazy`1.cs:line 558
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
~~~

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #971.

@VSadov, @gafter, @agocke, @jaredpar Please review.

### CODE REVIEW

**Comment by agocke** [comment]
LGTM

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet-bot please test this

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot test this please

**Pull request merged**
