### PR TITLE
Fix for #5219

### PR DESCRIPTION
**Pull request by Hosch250**

### CODE REVIEW

**Comment by Hosch250** [comment]
One thing I really hate about the C# change is that the node kind and operator kind are not mapped with a dictionary, so I don't know if they are correctly matched.  I just hoped the lists were in the same order.  If there is a better way to do this, I would love to hear about it.

**Comment by mmitche** [comment]
Can one of the admins approve this PR test or whitelist this user?

**Comment by Hosch250** [comment]
It appears I broke a bunch of tests by throwing argument exceptions on them.  Don't merge this just yet.

**Comment by davkean** [comment]
@dotnet/roslyn-compiler Can we some compiler devs look at this?

**Comment by tannergooding** [comment]
@dotnet/roslyn-compiler, sorry for the message, seeing if @dotnet-bot only spams when @davkean posts.

**Comment by Hosch250** [comment]
@davkean Sorry about this, I have been very busy with school, and I have not been able to get the tests running.  Essentially, by solution adds some conversion methods to ensure the type of the expression is correct, but it appears I broke something in the process.

**Comment by davkean** [comment]
@Hosch250 It looks like you've broken quite a few tests - please test your changes locally on your box by following the [Running Unit Tests](https://github.com/dotnet/roslyn/wiki/Building-Testing-and-Debugging) section. Try running *before* your change to ensure that everything's green on your box, then apply your change.

**Comment by Hosch250** [comment]
@davkean I am currently unable to run those.  VS cannot see the tests.  R# does see the tests, but gives an error because some XUnit file is not in the right place, or something.  I will work on this as soon as I can.

**Comment by davkean** [comment]
@Hosch250 Unfortunately, the VS test runner doesn't scale to our tests and will continue to churn failing to find them. You need to use the command line, please see the link I pointed you to above.

**Comment by gafter** [comment]
I don't think we want to take this change. It ties the syntax generator too closely to the particular syntax it is used to generate, it is delicate due to assuming a correspondence between enums, and it puts more smarts in these nodes than we had intended.

@dotnet/roslyn-compiler Anybody else care to chime in?

**Comment by AlekseyTs** [comment]
@gafter I tend to agree.

**Pull request closed without merging**
