### PR TITLE
Fix dynamic parameter PR

### PR DESCRIPTION
**Pull request by jaredpar**
Responding to some feedback that occurred after pr #5447 was
merged.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @AlekseyTs, @gafter, @VSadov, @agocke, @TyOverby

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by TyOverby** [comment]
LGTM

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test linux please

**Pull request closed without merging**
