### PR TITLE
Metadata writer refactoring

### PR DESCRIPTION
**Pull request by tmat**
Refactors PeWriter into components independent of Roslyn, so that it can later be moved to System.Reflection.Metadata in CoreFX.

The goal is to provide PE/COFF builder and ECMA-335 metadata builder that can be used broadly to write managed and native PE files. The goal is not to immediately provide the full support for writing all existing sections of the PE/COFF format but rather to enable composing PE/COFF files from section blobs and to provide builders for sections commonly appearing in managed PE files.

Includes implementation of a set of types, *blob encoders* that can be used for serialization of various blob structures found in the ECMA-335 metadata (especially signatures). The introduced abstraction provides type-system enforced structure to the blobs with minimal runtime overhead.

More work will follow to polish the public surface of the builders and serializers.

Tracked by work item: #6904

### CODE REVIEW

**Comment by tmat** [comment]
test mac please

**Comment by tmat** [comment]
Failure: #6358

**Comment by tmat** [comment]
@nguerrera

**Comment by tmat** [comment]
Win failure is a known CLR issue:
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(Object sender, EventArgs e)
```

**Comment by amcasey** [comment]
I haven't seen the compilation error outside this PR.

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/roslyn/pull/9459.

**Pull request closed without merging**
