### PR TITLE
Revert "Skip binary for determinism checking"

### PR DESCRIPTION
**Pull request by AlekseyTs**
Reverts dotnet/roslyn#48450

### CODE REVIEW

**Comment by AlekseyTs** [comment]
CC @jasonmalinowski

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
VS_Integration release_32 failure appears to be due to a network issue (HTTP 429--is the CI machine getting rate limited?)

**Review by jaredpar — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jaredpar** [comment]
It appears like this is failing again once we removed the skip here .

https://dev.azure.com/dnceng/public/_build/results?buildId=888293

**Comment by AlekseyTs** [comment]
> It appears like this is failing again once we removed the skip here .

How do we know it is the same reason?

**Comment by jaredpar** [comment]
> How do we know it is the same reason?

I haven't done the diff yet so I'm not 100% sure but the timeline of the revert, the appearance of the failures and the assembly where the failures occur all line up. In the process of doing the diff at hte moment.

**Comment by jaredpar** [comment]
Diff indicates this is the same issue. The case difference in Span is showing up again. 

image

**Comment by AlekseyTs** [comment]
The casing of  the field name now should match casing in the property name. Is it possible the fix isn't there for some reason, because I would expect the to see the difference in the property name as well.

**Comment by jaredpar** [comment]
Not sure where to write down how I investigate bugs like this so just going to throw it here for now. First step is to grab the determinism logs from the build

image

The before / after versions of the binaries will appear in the Left and Right sub-directory. From there I run the folloing in both directories 

> mdv .\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll /out:data.txt

Then I just windiff the data.txt file and see what changed. There are a number of diffs here but most of them are just changing a token value, not the name. This is the only place where the name changes.

**Comment by jaredpar** [comment]
> Is it possible the fix isn't there for some reason, because I would expect to see the difference in the property name as well.

Scrolling through the rest of the diff I see that's mor ethan just the field 

image

image

The string table also shows the different casing (that diff doesn't really fit well into a screen shot but can provid if you want).

**Comment by AlekseyTs** [comment]
So, there is a difference in parameter name, but not in property name? Or we don't check property names?

**Comment by AlekseyTs** [comment]
I'll try following your steps to take a look at the binary itself

**Comment by jaredpar** [comment]
> So, there is a difference in parameter name, but not in property name? Or we don't check property names?

The property name is the same here in both sets. 

The check we do here is a byte for byte comparison of the DLLs. So it checks literally everything that we output. The use of `mdv` is just a way of turning the binary into text so a human can diff and see what changed. It's not actually used in the job here.

**Comment by AlekseyTs** [comment]
Clearly there was a problem with constructor parameters, but I cannot figure out how fields can be non-deterministic after the recent fix. Fixed parameters and added temporary throws to detect if our assumptions are violated in some obscure scenarios in https://github.com/dotnet/roslyn/pull/49467. Hopefully, instead of simply getting a comparison failure we'll get a call stack.

**Comment by sharwell** [comment]
@AlekseyTs This change has resulted in 8 failed rolling builds in the past 3 days. Can you revert this and file a follow-up issue?

/cc @allisonchou

**Comment by AlekseyTs** [comment]
The issues actually have been addressed. See https://github.com/dotnet/roslyn/pull/49483 and  https://github.com/dotnet/roslyn/pull/49467.

**Comment by sharwell** [comment]
@AlekseyTs thank you!!

**Pull request merged**
