### PR TITLE
Improve Interactive icons

### PR DESCRIPTION
**Pull request by amcasey**
Fixes internal bug 153805.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @dotnet/interactive

**Comment by amcasey** [comment]
Note that users on VS 2015 RTM will see blank icons until they upgrade to VS 2015 Update 1.

**Comment by amcasey** [comment]
FYI @MattGertz since this is going into stabilization.  If we don't take this fix, our menu item icon won't be acceptable in high DPI environments.  If we do, I believe the worst thing that could happen is that the icon could be blank (if we fail to get the new icon moniker into RTM for some reason).

**Comment by amcasey** [comment]
FYI @KevinRansom, who will probably have to make a corresponding change in F#.

**Comment by ManishJayaswal** [comment]
:+1: 
Note that users seeing blank icons in VS 2015 RTM is only applicable for internal users who are not on update 1 builds.

**Comment by amcasey** [comment]
The test failures are unrelated - this change could cause compilation errors but not break tests.  I'm following up offline.

**Comment by amcasey** [comment]
Well, that's unfortunate.  You can't actually build the vsct files unless VS has the latest ```KnownImageIds.vsct```.

**Comment by amcasey** [comment]
Thanks, @jaredpar, for the suggested workaround.

**Pull request merged**
