### PR TITLE
Update project.lock.jsons

### PR DESCRIPTION
**Pull request by agocke**
Future equivalent of #9953

/cc @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/5405/
// Retest reason:

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5336/
// Retest reason: Jenkins network issue

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5479/
// Retest reason: Jenkins network issue

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/5451/
// Retest reason: Jenkins network issue

**Comment by gafter** [comment]
LGTM

**Pull request merged**
