### PR TITLE
Replace dynamic invocation of EnumerateExpansionsAsync with direct calls

### LINKED ISSUE #7943: [PR Available] Remove IExpansionManager dynamic workaround
Introduced in https://github.com/dotnet/roslyn/pull/7935

I need to reference a type introduced in Update 1, but the build machines are still on RTM, so I'm working around it by calling the method I need dynamically. Once the build machines are on Update 1, I can remove the hack.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #7943

It is safe to mention IExpansionManager by name now that the build machines are on Visual Studio 2015 Update 1. This should not introduce any behavioral change (other than removing first-chance exceptions).

### CODE REVIEW

**Comment by dpoeschl** [comment]
Replacing https://github.com/dotnet/roslyn/pull/9009 by targeting against `master` instead

**Comment by davkean** [comment]
:+1:

**Comment by dpoeschl** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4379/
// Retest reason: Bug filed as #9215

**Comment by davkean** [comment]
ETA failure is expected at the moment, we're waiting on: https://github.com/dotnet/roslyn-internal/pull/594

**Comment by davkean** [comment]
Andy's going to merge it in

**Comment by dpoeschl** [comment]
retest vsi please

**Comment by dpoeschl** [comment]
Moving forward with https://github.com/dotnet/roslyn/pull/10202 instead

**Pull request closed without merging**
