### PR TITLE
Options pages

### PR DESCRIPTION
**Pull request by Pilchie**
Hide some confusing options and remove confusing words.

### CODE REVIEW

**Comment by Pilchie** [comment]
Ping @basoundr @heejaechang @rchande

**Comment by rchande** [comment]
lgtm

**Comment by basoundr** [comment]
:+1: and as discussed, an workitem to track the work to get the option back.

**Comment by heejaechang** [comment]
:+1:

**Comment by Pilchie** [comment]
@basoundr Filed 2241 to track it.

**Pull request merged**
