### PR TITLE
Make sure the solution crawler is running in the VS workspace.

### LINKED ISSUE #14802: XAML DocumentAnalyzer does not run for C++ projects
XAML is supported for C++ as well. However, the VisualStudioWorspaceImpl's solution crawler may not have been started since neither the C# nor VB package may have been loaded.

### PR DESCRIPTION
**Pull request by mgoertz-msft**
Fixes #14802 by making sure that the solution crawler is running in the VS workspace.

@Pilchie, @CyrusNajmabadi, @jasonmalinowski, @heejaechang, please review. Thank you!

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @ManishJayaswal for ask mode approval.  I'd really like @heejaechang to review this too.

**Comment by natidea** [comment]
I don't think this will make it in for Ask Mode as we are snapping now. @ManishJayaswal

**Comment by ManishJayaswal** [comment]
@mgoertz-msft - It seems this was merged without a signoff from @heejaechang ?

**Comment by mgoertz-msft** [comment]
This was actually what @heejaechang had suggested we do so I hope he is still fine with it.

**Comment by ManishJayaswal** [comment]
ok. Since we have two signoffs I am approving this. @natidea please include this in the final build.

**Comment by heejaechang** [comment]
I know the way it enable the vsworkspace solution crawler is weird but the way they participate in our workspace (dynamically added to solution as xaml file is opened) and xaml language service package doesn't involved in our normal pattern, this seems only way for them to enable solution crawler.

**Pull request merged**
