### PR TITLE
Add an (internal) overload to Rename to allow features to rename a subset of locations.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Previously EncapsulateField was using internal implementation details of the rename API.  It did this so it could effectively perform two renames, one for one set of locations, and one for another.

I've augmented hte internal rename API to just allow features to filter what locations they want to update.

This cleanup was done because i also intend to use this API for the "Use auto property" feature.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Reviewers: @balajikris, @basoundr, @brettfo, @davkean, @DustinCampbell, @dpoeschl, @Pilchie @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by dpoeschl** [comment]
In [this discussion](https://github.com/dotnet/roslyn/issues/197#issuecomment-72541903) we were talking about returning conflict information as part of the result of RenameSymbolAsync, which may be quite noisy in cases where the location set is filtered down, but I suspect any consumers would be aware of this limitation when calling with such a filter.

Anyway, I like this approach *way* more than the random Rename poking & prodding that EncapsulateField was doing before. :+1:

**Comment by jasonmalinowski** [comment]
:+1: modulo nitpick comments.

**Pull request merged**
