### PR TITLE
Add analyzer driver editorconfig option for end users to configure ge…

### LINKED ISSUE #3705: Exclude files or folder from running through the analyzers through a configuration file.
Hi,

we have a lot of generated files that trigger warnings, errors when analyzers run them.
since the file name of the generated files do not follow the common naming conventions for generated code roslyn fires the analyzers away. As a result there are ten of thousands of warnings in the solution.
Could we get a exclude file from analyzing logic that:
- Exclude a file by adding it to a exclusion list
- Exclude a file by adding it to a exclusion list
- Annotate classes with a special Attribute that exclude the class
- exclude certain file name extensions ( like js files generated by typescript)
- Combination of the above like exclude all js files that live under the folder x including all sub folders

Most of the rules come straight from Resharper's exclusion file manager

Thanks

### PR DESCRIPTION
**Pull request by mavasani**
…nerated code

Implements https://github.com/dotnet/roslyn/issues/38674#issuecomment-534621058
Fixes #3705

### CODE REVIEW

**Comment by agocke** [comment]
Since the compiler also has a notion of generated code, and the `#nullable` behavior depends on it, I would expect this to also affect the compiler.

**Comment by mavasani** [comment]
> Since the compiler also has a notion of generated code, and the #nullable behavior depends on it, I would expect this to also affect the compiler.

The option detection is only being added to the core analyzer driver in this PR. It is not part of the shared [GeneratedCodeUtilities](http://source.roslyn.io/#q=GeneratedCodeUtilities) that are used by the core compiler for #nullable, analyzer driver and workspaces. Those utilities remain to be agnostic of editorconfig options. Each host should decide whether or not they want to apply these options. This PR itself does not affect workspaces layer or core compiler layer in how they treat generated code.

**Comment by agocke** [comment]
> This PR itself does not affect workspaces layer or core compiler layer in how they treat generated code.

Agreed that it doesn't. I think it should.

**Comment by mavasani** [comment]
> Agreed that it doesn't. I think it should.

If the concern is that the chosen design might not be sufficient for IDE and compiler requirements, I completely agree that this can be on hold till compiler approves this new option. Otherwise, I think it is fine for each host to be updated in separate PRs, as it would need writing separate host specific unit tests, validation, etc.

**Comment by agocke** [comment]
> If the concern is that the chosen design might not be sufficient for IDE and compiler requirements, I completely agree that this can be on hold till compiler design team approves this new option.

I think we should ship in a complete state, or not at all, so if you can use editorconfig to make a file generated code, it should be generated code for both the compiler and analyzers simultaneously.

**Comment by mavasani** [comment]
> I think we should ship in a complete state, or not at all, so if you can use editorconfig to make a file generated code, it should be generated code for both the compiler and analyzers simultaneously.

Would it be reasonable to re-target this PR to a feature branch which the compiler team can drive forward by respecting the option for #nullable analysis?

**Comment by agocke** [comment]
Sounds good to me. There's probably some design work. For instance, it may be reasonable to add a public API to SyntaxTree for generated code.

**Comment by mavasani** [comment]
I created a separate branch `features/editorconfig-generated-code` and retargeted the PR to this branch.

**Comment by mavasani** [comment]
> For instance, it may be reasonable to add a public API to SyntaxTree for generated code.

The last time this was brought up, Matt Warren was against such an API given the default logic would be based off a heuristic to determine if code is generated or not, especially given vastly different interpretations of generated code. Unless we are ready to future-proof that logic, adding an API might be a risky.

**Comment by mavasani** [comment]
@agocke I looked at the potential approaches for the compiler to also start respecting this option, and found that the core SyntaxTree would need the analyzer config options to correctly update [SyntaxTree.IsGeneratedCode]( http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,647). This would mean adding a new optional parameter to the SyntaxTree APIs to [Create](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,306) and [ParseText](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Syntax/CSharpSyntaxTree.cs,371) APIs, and make the current one a back-compat overload, similar to the way we threaded the DiagnosticOptions. The new optional parameter can either be an `ImmutableDictionary<string, string>` or [AnalyzerConfigOptions](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerConfigOptions.cs,c809ccf2ce8e1395). Does that sound reasonable? If so, I can take a shot at implementing while I am working on this.

**Comment by agocke** [comment]
@mavasani Yup that was what I had in mind.

**Comment by mavasani** [comment]
Thanks @agocke. Any preference on the new parameter type: `ImmutableDictionary<string, string>` or AnalyzerConfigOptions?

**Comment by agocke** [comment]
Wait, why wouldn't it be a boolean parameter? Isn't a file marked generated or not?

**Comment by mavasani** [comment]
> Wait, why wouldn't it be a boolean parameter? Isn't a file marked generated or not?

We can go that route, but then in future if we decide to add detection of more editorconfig options, we would have to keep adding new parameters to the constructor. My proposed API was avoiding exposing specifics of how compiler is processing these options to make the options more opaque. If we decide to go on those lines, probably AnalyzerConfigOptions seems a more appropriate parameter type as opposed to a dictionary of key-value pairs which can be iterated, which is probably undesirable.

One other caveat with a boolean parameter is that it makes "isGeneratedCode" an explicit part of the SyntaxTree public API contract.

I am fine holding off any further work in this area if we feel that it is better to iron these things out at a design meeting before proceeding to implement it.

**Comment by agocke** [comment]
Yeah, let's think more about this

**Comment by mavasani** [comment]
Great, in that case, this PR is ready to be reviewed.

**Comment by agocke** [comment]
No, my original point still stands, which is that generated code should apply everywhere, including to the compiler. We have to decide on the API for that, but it still blocks this change.

**Comment by mavasani** [comment]
> If we do this, we should make sure it applies everywhere, including the compiler checks for generated code

@agocke This PR targets a feature branch, which will be owned by the compiler team to drive the compiler changes and then merge it back to master. Is there a reason to prevent this PR from going into this feature branch?

**Comment by agocke** [comment]
Sorry, missed that this goes to a feature branch. LGTM then

**Comment by mavasani** [comment]
Thanks!

**Pull request merged**
