### PR TITLE
Restore the machinery for enabling language features by feature flags

### LINKED ISSUE #29291: Feature flag machinery improperly deleted. Please restore.
The machinery for enabling language features by a feature flag was partially deleted in https://github.com/dotnet/roslyn/pull/22383. But this machinery was not designed just for IOperation, and its deletion from a parent branch prevents this code from being shared in child branches.

Please restore the machinery for enabling language features by feature flags (even if no specific features are enabled by this flag). This machinery belongs in a common parent branch.

/cc @mavasani @AlekseyTs @cston

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #29291

### CODE REVIEW

**Comment by gafter** [comment]
There appears to be a build error.

**Comment by mavasani** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-compiler for another review.

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-compiler for second review.

**Comment by mavasani** [comment]
retest windows_release_vs-integration_prtest please

**Comment by mavasani** [comment]
Integration test failure is unrelated to this change.

**Comment by gafter** [comment]
THANK YOU!

**Pull request merged**
