### PR TITLE
Added LSP support for document color requests

### PR DESCRIPTION
**Pull request by mgoertz-msft**
- Updated LSP protocol types for document color support
- Updated EA.Xaml to allow external client capability checks

### CODE REVIEW

**Comment by dibarbet** [comment]
@mgoertz-msft FYI some merge conflicts (probably b/c of a recent change to add all the 3.17 LSP types).

**Comment by mgoertz-msft** [comment]
Yeah, I noticed that as soon as I created it. :(

**Comment by mgoertz-msft** [comment]
@dibarbet Resolved. I was able to just take everything from Main. Only EA.Xaml changes left now. :)

cc @etvorun

**Comment by mgoertz-msft** [comment]
@dibarbet Looks like infrastructure errors now. There are no test failures on the Azure pipelines.

**Review by dibarbet — APPROVED** [review]

**Pull request merged**
