### PR TITLE
fixed null exception

### PR DESCRIPTION
**Pull request by heejaechang**
watson shows null exception on DocumentExtensions.GetLanguageService

guarded that method from null exception

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani can you take a look?

**Comment by srivatsn** [comment]
:+1:  once tests pass.

**Comment by tannergooding** [comment]
test this please

**Comment by heejaechang** [comment]
retest win eta please

**Comment by heejaechang** [comment]
@dotnet-bot retest win eta please

**Comment by heejaechang** [comment]
test win eta please

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Pull request merged**
