### PR TITLE
Handle nameof expressions in UnboundIdentifiersDiagnosticAnalyzerBase

### LINKED ISSUE #23667: UnboundIdentifiers: 'nameof' does not exist in the current context.
In a lambda expression. If I write a `#warning` directive, the `nameof` will be error with 

> CS0103  The name 'nameof' does not exist in the current context.

Test codes:

```csharp
Action action = () =>
{
    var x = nameof(System);
#warning xxx
};
```

But there is an interesting phenomenon, the codes can be compile successed and run correctly.

In my test, this bug is appears in both of Visual Studio 2015 and Visual Studio 2017.

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/71314/nameof-does-not-exist-in-the-current-context.html
VSTS ticketId: 454314_
_These are the original issue comments:_

彭闽 on 6/21/2017, 11:43 PM (169 days ago): <pre>Action action = () =&gt; \{
    var x = nameof(System);
#warning xxx
};<br></pre><p></p>

Dan J on 8/30/2017, 11:06 AM (99 days ago): I also have this happen in 15.3.3, does not prevent build from suceeding, but constantly having 20 errors makes it hard to find what is actually boken
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by mavasani**
Addresses #23667

<details><summary>Ask Mode template</summary>

### Customer scenario

`nameof` is incorrectly squiggled in a lambda with diagnostics with the following error:
`Error	 IDE1007	The name 'nameof' does not exist in the current context.`. Note that the code compiles without errors and the IDE experience is very confusing.

### Bugs this fixes

#23667

### Workarounds, if any

Ignore the incorrect IDE1007	errors

### Risk

Low risk, we are special casing nameof expressions in the unbound identifiers analyzer

### Performance impact

Low

### Is this a regression from a previous update?

No

### Root cause analysis

Analyzer was assuming each identifier name should bind to a symbol for successful bind. This is not true for `nameof`, which is represented as an `IdentifierNameSyntax` node in C#, but GetSymbolInfo returns no symbols for it.

### How was the bug found?

Customer reported

### Test documentation updated?

N/A

</details>

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@mavasani Looking at the terribly long conversation in that bug, why didn't we conclude that the compiler should just report this directly and we get rid of the UnboundIdentifiersDiagnosticAnalyzerBase? I have yet to meet somebody who doesn't want that thing to go away. :smile:

**Comment by mavasani** [comment]
@jasonmalinowski The analyzer handles nodes within broken lambdas and incomplete members - I presume the compiler doesn't want to bind them for perf reasons, but I will ask the compiler team for their views on handling these cases.

**Comment by mavasani** [comment]
Closing this PR as per https://github.com/dotnet/roslyn/issues/23667#issuecomment-374980551 cc @jcouv

**Comment by mavasani** [comment]
@jasonmalinowski @jcouv can you please re-review this PR as per https://github.com/dotnet/roslyn/issues/23667#issuecomment-444691732?

**Comment by CyrusNajmabadi** [comment]
Is there a reason we aren't just fixing this at the compiler layer?

**Comment by mavasani** [comment]
> Is there a reason we aren't just fixing this at the compiler layer?

The compiler feature request has been stalled for quite a while now, and the underlying bug has been reported by multiple customers now. I see no reason to block the user experience on our implementation details, especially given this IDE analyzer already exists.

**Comment by CyrusNajmabadi** [comment]
I guess my take is this: given that customers are hitting this, that indicates we should un-stall the root problem.  If we fix on the IDE side, that's just going to remove the motivation to ever really fix this at the root level, and we'll continue being in teh state where the IDE is simulating (poorly) that it is the compiler.  

Note: we've gotten a wide range of bugs over the years with the lack of compiler support here being the root cause.  Rather than fix each one in a piecemeal fashion, i'd rather the compiler just analyze these guys normally.

**Comment by mavasani** [comment]
We discussed this at the last design meeting and it was decided that we take the fix to the analyzer for 16.0, and retain the underlying issue open to track compiler support for correctly reporting errors within a lambda.

Tagging @jcouv @jasonmalinowski @dotnet/roslyn-ide for review - this PR itself is very trivial

**Comment by mavasani** [comment]
Thanks @jasonmalinowski. @jcouv can you take a quick look please?

@jinujoseph @vatsalyaagrawal for approval

**Comment by mavasani** [comment]
@jaredpar @dotnet/roslyn-infrastructure `Linux_Test coreclr` seems to have gotten [abandoned](https://dev.azure.com/dnceng/public/_build/results?buildId=75939), and multiple retry attempts lead to it getting immediately abandoned again. Known issue?

image

**Pull request merged**
