### PR TITLE
Remove AbstractPackage.ForegroundObject, and its costly initialization

### LINKED ISSUE #29283: Remove AbstractPackage.ForegroundObject
From https://github.com/dotnet/roslyn/pull/28781#discussion_r208391862:

> PERF: Remove `AbstractPackage.ForegroundObject`, and its costly initialization

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #29283

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
How costly was this?

**Comment by jasonmalinowski** [comment]
@sharwell We've verified no uses in F#, TypeScript, and possibly XAML?

**Comment by sharwell** [comment]
@jasonmalinowski We have not

**Comment by sharwell** [comment]
@jasonmalinowski The containing type is `internal`, and the intersection of `internal` and `protected` is `private protected`.

**Pull request merged**
