### PR TITLE
Remove obsolete types

### LINKED ISSUE #913: Remove MetadataCache
Incompatible with CoreCLR (http://source.roslyn.io/Microsoft.CodeAnalysis.Desktop/R/2de39448d0953b04.html). Looks like it's not used anyway.

### PR DESCRIPTION
**Pull request by jaredpar**
This change removes two obsolete types:

- MetadataCache
- MetadataFileReference

This types were obsolete and used only in testing.

closes #913

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @gafter, @VSadov, @agocke, @AlekseyTs, @tmat

**Comment by AlekseyTs** [comment]
Should we re-purpose the tests to target components that the functionality was moved to? cc @tmat

**Comment by agocke** [comment]
LGTM

**Comment by gafter** [comment]
LGTM. @tmat should chime in here.

**Pull request closed without merging**
