### PR TITLE
Format this()/base() calls uniformly in the IDE.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
It's always been an annoyance of mine how these calls are inconsistent across the IDE.  I did a check to see what the numbers were like, and it was about 350 (across the entire codebase, around 150 in the IDE) of the form:

```c#
public Foo(...) :
    this(...)
{
}
```

And about *16,000* of the form:

```c#
public Foo(...)
    : this(...)
{
}
```

That's less than 3% of the code uses the first form.  So this PR just makes the IDE codebase consistent here on this one style.

Note: in the future, i'd love a formatting rule that checked fort his (and would be happy to contribute it).  that way you'd get a nice squigle if you didn't write it either on the same line, or in this form.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani @jasonmalinowski

**Comment by mavasani** [comment]
> Note: in the future, i'd love a formatting rule that checked fort his (and would be happy to contribute it). that way you'd get a nice squigle if you didn't write it either on the same line, or in this form.

Can you please open an issue for this? I think it would also be nice to have a similar formatting rule for specifying BaseList of a type declaration.

**Comment by CyrusNajmabadi** [comment]
@mavasani Done: https://github.com/dotnet/roslyn/issues/36868

**Comment by CyrusNajmabadi** [comment]
@mavasani @jasonmalinowski Feel free to merge.

**Comment by CyrusNajmabadi** [comment]
@mavasani @jasonmalinowski Feel free to merge.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
