### PR TITLE
Fix FxCop warnings

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by jaredpar** [comment]
Nice!  Mostly scanned through them as it seems to be the same set of 3 changes repeated.  LGTM

**Comment by jcouv** [comment]
LGTM

**Comment by VSadov** [comment]
Nice! We should probably have some of the perf related FXCop rules rules enabled for the project at some point.
LGTM

**Comment by cston** [comment]
@vsadov, logged #11654.

**Comment by AlekseyTs** [comment]
The build errors look like something that might be related to the changes.

**Comment by cston** [comment]
Leave a comment

**Pull request closed without merging**
