### PR TITLE
[For discussion] Use a true native IStream when constructing a PDB

### PR DESCRIPTION
**Pull request by pharring**
This is for discussion only at the moment. I haven't done full analysis of the resultant performance.

This is a performance fix for PDB writing. We see large byte array allocations during PDB writing, coming from the native stream writer. This is because each interop call from diasymreader into the ComStreamWrapper allocates a byte[] for interop. By letting the bytes accumulate in native memory, we avoid GC pressure. The native stream is copied into the destination stream in 4KB chunks, using a shared byte[] buffer at the end.

### CODE REVIEW

**Comment by pharring** [comment]
@tmat Can you take a look and let me know what you think?

**Comment by CyrusNajmabadi** [comment]
Doesn't this seem like a strange thing for roslyn to have to do for perf?  Wouldn't it make more sense if the runtime/BCL handled this appropriately?

**Comment by pharring** [comment]
@CyrusNajmabadi PDB generation is done in diasymreader.dll which is a Windows component.

In any case, I've been having second thoughts about this change. While it might reduce GC allocations, it increases native allocations by at least as much. I think we can do better by using a modified interop definition of IStream.

**Comment by pharring** [comment]
Re-opening for re-consideration.

**Comment by pharring** [comment]
Will pick this up in #2137

**Pull request closed without merging**
