### PR TITLE
Respect filter flags when searching for symbols.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/12169

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Ping @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Also a simple PR @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
Can you describe how this fixes the issue?

**Comment by CyrusNajmabadi** [comment]
We were doing a search, asking for only Types to be returned.  But we weren't respecting that flag, so other symbols came back as well.  We then casted the results we got back to INamedTypeSymbols and crashed.

**Comment by jasonmalinowski** [comment]
I find your lack of tests disturbing.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Test added.

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
Anyone have any issues with this going in?

**Comment by jmarolf** [comment]
👍

**Pull request merged**
