### PR TITLE
Mark private-protected feature as done

### PR DESCRIPTION
**Pull request by jcouv**
Doc-only change to update compiler feature status.

FYI @dotnet/roslyn-compiler. I'll merge without review or ask-mode.

### CODE REVIEW

**Comment by jcouv** [comment]
windows_debug_unit64_prtest failed on CodeFixServiceTests.TestGetCodeFixWithExceptionInFixableDiagnosticIds for a doc-only change ([details](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/9598/))

FYI @dotnet/roslyn-infrastructure I'll re-run.

**Comment by jcouv** [comment]
test windows_debug_unit64_prtest please

**Comment by jcouv** [comment]
FYI @VSadov I'm also updating the status for the ref readonly and related features since they are now merged.

**Comment by VSadov** [comment]
Thanks!

**Pull request merged**
