### PR TITLE
Revert "Merge pull request #18383 from CyrusNajmabadi/fastInitialTagging"

### PR DESCRIPTION
**Pull request by tannergooding**
This reverts commit 054509fddbf51c3605f87934ca32b99810719b6f, reversing
changes made to fc11e8add33f493fc74fffb2d1d6280cc80bfc2f.

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @rchande, @dotnet/roslyn-infrastructure 

Also FYI. @CyrusNajmabadi, @Pilchie

**Comment by tannergooding** [comment]
I did validate that reverting this change fixes the NRE that Typescript was hitting.

**Comment by tannergooding** [comment]
The change I'm reverting is also in `dev15.6`, `features/DefaultInterfaceImplementations`, `features/non-trailing`, and `features/readonly-ref`.

However, I'm only reverting it here due to us inserting this branch.

The proper fix should likely be made in `dev15.6` and this change should be reverted when it merges into `dev16`.

**Comment by jasonmalinowski** [comment]
@tannergooding We should port the revert to dev15.6 too, since that branch is about to get merged to master.

**Comment by tannergooding** [comment]
@jasonmalinowski, I'll do it tomorrow morning, since we aren't likely to insert master tonight.

**Pull request merged**
