### PR TITLE
Add the facade assemblies to the CompilerExtension VSIX

### PR DESCRIPTION
**Pull request by agocke**
@jasonmalinowski Hopefully I did this right.

/cc @jaredpar

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1:

**Comment by tmat** [comment]
Is this VSIX inserted into VS or is it separate?

**Comment by agocke** [comment]
@tmat Separate.

**Comment by tmat** [comment]
Ok, :+1: then

**Comment by jasonmalinowski** [comment]
Oops, my apologies, but I was ignoring email. :+1:.

**Pull request merged**
