### PR TITLE
Fix to return attributes of VB.NET enum members when using the code model EnvDTE.CodeVariable.Attributes

### PR DESCRIPTION
**Pull request by carlos-quintero**
Fix for bug #29353

### CODE REVIEW

**Comment by carlos-quintero** [comment]
I don't understand how the two lines of code that I added can break these tests that failed the windows_debug_unit32_prtest  and windows_debug_vs-integration_prtest reviews:

Microsoft.CodeAnalysis.Editor.UnitTests.Rename.RenameTagProducerTests.ValidTagsDuringSimpleRename
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpChangeSignatureDialog.VerifyReorderParameters

**Comment by CyrusNajmabadi** [comment]
@carlos-quintero They're likely just flakey tests.

**Comment by CyrusNajmabadi** [comment]
Change looks reasonable.  But it will be good to add tests to validate the behavior.  Tests can be added somewhere under: src\VisualStudio\Core\Test\CodeModel\VisualBasic

**Comment by DustinCampbell** [comment]
@dotnet-bot retest this please

**Pull request merged**
