### PR TITLE
provide HelpKeyword information for offline help

### PR DESCRIPTION
**Pull request by heejaechang**
this will enable user to use offline help viewer when the user is offline.

### CODE REVIEW

**Comment by MattGertz** [comment]
Approved once all tests are passing (currently 29 failing).

**Comment by heejaechang** [comment]
@dotnet-bot retest win unit32 please

**Comment by heejaechang** [comment]
@dotnet-bot retest win eta please

**Comment by heejaechang** [comment]
@dotnet-bot retest win eta please

**Pull request merged**
