### PR TITLE
Fix NGEN failures

### PR DESCRIPTION
**Pull request by ryzngard**
Example failure: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/204591?_a=overview 

These changes remove some dependencies that were added as part of [this change](https://github.com/dotnet/roslyn/commit/66a912c9463eebe832cf742d2fe8bb2e1a4600ec#diff-8b8f08ffbf7b863fb3700c1718eeb4cb) , making Microsoft.VisualStudio.LanguageServer.Protocol and Microsoft.VisualStudio.LanguageServer.Protocol.Extensions depend on the same versions that VS provides. These binaries are intended to be versioned differently, and we ingest at a different cadence than VS. Once VS updated these dependencies we started to see NGEN failures with dll dependency resolution.

### CODE REVIEW

**Comment by ryzngard** [comment]
Run on 16.4p1 with fix: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/204894?_a=overview

**Comment by jaredpar** [comment]
Which NGEN failures are we fixing here? Is there a bug or previous PR that can be used to provide context on this change?

**Comment by jasonmalinowski** [comment]
Agreed -- what is this fixing and how?

**Comment by ryzngard** [comment]
Updated comment to have details on the fix.

**Pull request merged**
