### PR TITLE
Add satellite assemblies to Microsoft.NETCore.Compilers

### PR DESCRIPTION
**Pull request by tmeschter**
Add satellite assemblies for the Roslyn assemblies that we ship in
Microsoft.NETCore.Compiler.nupkg. This includes
Microsoft.CodeAnalysis.dll, Microsoft.CodeAnalysis.CSharp.dll,
Microsoft.CodeAnalysis.VisualBasic.dll, and
Microsoft.Build.Tasks.CodeAnalysis.dll.

This increases the resulting .nupkg size from about 8,988KB to about
12,000KB.

### Customer scenario

This allows consumers of the Microsoft.NETCore.Compilers package to see localized strings when using the tools it contains. However, the immediate motivation for this change is to make it much simpler for the CLI to find and include these localized resources.

### Bugs this fixes

N/A

### Workarounds, if any

Currently the CLI has a complicated process for locating and pulling in these localized resources.

### Risk

Low.

### Performance impact

N/A

### Is this a regression from a previous update?

N/A

### Root cause analysis

N/A

### How was the bug found?

N/A

### Test documentation updated?

N/A

### CODE REVIEW

**Comment by tmeschter** [comment]
test windows_release_unit64_prtest please

**Comment by tmeschter** [comment]
@Pilchie Is there anything else I need to do (or anyone else I need approval from) before merging this into dev15.6.x?

**Comment by Pilchie** [comment]
I would suggest looping @MeiChin-Tsai in so that she is aware, but otherwise I think it can be merged.

**Comment by nguerrera** [comment]
I found an issue while testing a private build and pushed https://github.com/dotnet/roslyn/pull/24353/commits/37018e7e170ae230dfd163ed22eb25f2fcbe9100 with the fix.

cc @jaredpar, @jasonmalinowski, @tmeschter

**Comment by jasonmalinowski** [comment]
@tmeschter @nguerrera @jaredpar Anything holding us back from merging this?

**Comment by tmeschter** [comment]
@jasonmalinowski @MeiChin-Tsai has concerns, hence the additional testing by @nguerrera. We need to make sure all of her concerns are addressed.

**Comment by tmeschter** [comment]
@nguerrera What else might be affected by the changes you've made to the targets?

**Comment by MeiChin-Tsai** [comment]
A couple questions - given that the size increase, does it impact customer's first use scenario in terms of perf? I assume that this also does not impact CLI inner loop perf, correct? Thanks.

**Comment by tmeschter** [comment]
@jaredpar @nguerrera Can you answers MeiChin's questions? I don't have a good sense for exactly how this will be consumed by CLI, or how other end-users may be picking this up.

**Comment by nguerrera** [comment]
> @nguerrera What else might be affected by the changes you've made to the targets?

The PublishWithoutTesting target is used exclusively for publishing vbc, csc, and VBCSCompiler for .NET Core: https://github.com/dotnet/roslyn/search?utf8=%E2%9C%93&q=PublishWithoutBuilding&type= 

The workaround just below that I deleted is for a bug that doesn't exist in v2 of the SDK. It is unrelated and could be reverted, but I don't see a real risk.

> @jaredpar @nguerrera Can you answers MeiChin's questions? I don't have a good sense for exactly how this will be consumed by CLI, or how other end-users may be picking this up.

AFAIK, at this time, the Microsoft.NETCore.Compilers package is only officially supported via its inclusion in the CLI. It has not been release to nuget.org: https://www.nuget.org/packages?q=Microsoft.NETCore.Compilers although I don't know if there are plans to ship it standalone to nuget.org along with 15.6. @jaredpar Can you comment on that?

If there is any desire to make this package official on its own and keep its size down, it would totally work to package the satellites in to a separate, parallel Microsoft.NETCore.Compilers.Localization.nupkg...

> I assume that this also does not impact CLI inner loop perf, correct

Correct. This has zero impact on CLI perf. In fact, there is no size impact at all, we're just getting the same *.resources.dll from a much saner process than a separate build in https://github.com/dotnet/cli-deps-satellites. The size on disk for CLI stays exactly the same. There are ways to obtain a CLI without localization (currently, .zip download doesn't have it, .msi does), but those are implemented by simply stripping **/*.resources.dll from the package, and that will continue to work just fine.

**Comment by jaredpar** [comment]
> AFAIK, at this time, the Microsoft.NETCore.Compilers package is only officially supported via its inclusion in the CLI.

That is correct. This NuGet package is just a vehicle for shipping binaries between the roslyn and cli repos.

**Comment by tmeschter** [comment]
@jaredpar @nguerrera @MeiChin-Tsai I'm going to merge this at noon today unless someone yells at me to stop. :-)

**Comment by tmeschter** [comment]
@jaredpar @nguerrera This is in now.

**Comment by nguerrera** [comment]
@tmeschter 👏 Awesome! Please tag me on the insertion in to CLI that takes this. I shared a commit via email that needs to accompany that.

**Comment by tmeschter** [comment]
@nguerrera Who is responsible for the insertions into CLI?

**Comment by nguerrera** [comment]
^ @livarcocc Did the last one, but I think it usually comes from compiler team. There is an effort to automate it.

**Comment by livarcocc** [comment]
I have set it up using maestro, so we should get automatic insertions. Of course, I may have gotten something wrong.

**Comment by nguerrera** [comment]
@livarcocc OK, can you keep an eye out for the insertions and tag me when it hits.

**Pull request merged**
