### PR TITLE
Expose a public API for consumers of CompilationWithAnalyzers to clea…

### LINKED ISSUE #2576: Memory leak in AnalyzerManager.Instance in the _descriptorCache field
This issue relates to the following commit: https://github.com/dotnet/roslyn/commit/5279e7f7ef066092889d94e1710234ac5853d412#diff-00098a19b037d7ff59205a16189cecd3L50

The static instance `AnalyzerManager.Instance` keeps all `DiagnosticDescriptor` together with an `EventHandler` in a cache (in the field `descriptorCache`), until `ClearAnalyzerState` is called. `EventHandler` is referencing `CSharpCompilation` indirectly, and is therefore quite a large object.

The problem is that, when `CompilationWithAnalyzers` is used as an entry point, that `ClearAnalyzerState()` is never called.

I can see 2 potential fixes:

Fix 1: Use a `ConditionalWeakTable` instead of a `ConcurrentDictionary` in `AnalyzerManager`
Fix 2: Add the `AnalyzerManager.ClearAnalyzerState()` call into `AnalyzerDriver.Dispose()`, and have `CompilationWithAnalyzers` dispose the `AnalyzerDriver` instance it creates.

Comment from @mavasani 
> I’d say Fix 2 is the right approach. Have a method on ”CompilationWithAnalyzers.ClearAnalyzersAndState(array of analyzers)” that just invokes AnalyzerManager.ClearAnalyzersAndState(analyzers)”, indicating that the given set of analyzers are being disposed off. Note that we can’t just invoke ClearAnalyzersAndState on all analyzers passed into the ctor of CompilationWithAnalyzers. Only the analyzer host knows about its lifetime, not the CompilationWithAnalyzers instance it uses.
> What do you do if you have an analyzer instance that lives longer than CompilationWithAnalyzers instance, i.e. if for any analyzer passed to CompilationWithAnalyzers, if it is intended to be used by something else later on? We can’t just call AnalyzerManager.ClearAnalyzersAndStates() with all analyzers passed to CompilationWithAnalyzers.
> 
> Long term, we want to avoid a static instance of AnalyzerManager and have each analyzer host/client explicitly create a new instance of analyzer manager for its entire lifetime. That is going to be tricky to implement without making AnalyzerManager public.

### PR DESCRIPTION
**Pull request by mavasani**
…r off analyzer state cached during analyzer execution.

Executing analyzers requires us to internally store state such as supported diagnostics, registered actions, exception handlers for analyzer exceptions, etc. for the entire lifetime of analyzers. However, the lifetime of the analyzer instances is controlled only by the analyzer host, i.e. the consumer of CompilationWithAnalyzers. We cannot implicitly clear this internal state when disposing CompilationWithAnalyzers as the analyzer host might be re-using the same analyzer instances across multiple CompilationWithAnalyzers instances.

Fix is to expose an API on CompilationWithAnalyzers to allow the analyzer host to explicitly clear stored analyzer state, when it is done using analyzer instances.

Long term solution is to make the AnalyzerManager public and remove its static instance, so that the analyzer host can explicitly control its lifetime.

Fixes #2576

### CODE REVIEW

**Comment by mavasani** [comment]
Opened #2830 to track the correct long term fix for this.

**Comment by mavasani** [comment]
@ManishJayaswal @srivatsn @JohnHamby @heejaechang @shyamnamboodiripad @jmarolf @tmeschter please review.

/cc @dbolkensteyn

**Comment by srivatsn** [comment]
:+1:

**Comment by mavasani** [comment]
Merging this in as I am OOF on Monday, will respond to any additional review feedback on Tuesday.

**Pull request merged**
