### PR TITLE
Port https://github.com/dotnet/roslyn/pull/14289 to RC

### PR DESCRIPTION
**Pull request by rchande**
Fixes https://github.com/dotnet/roslyn/issues/14138

### CODE REVIEW

**Comment by rchande** [comment]
Tag @ManishJayaswal @MattGertz for ask mode approval

**Comment by MattGertz** [comment]
@rchande @Pilchie Would definitely like to ship the fix before RTM, but I'm not clear that this meets the bar for 2nd week of RC ASK mode.  Can you help me understand cost/risk benefit?

**Comment by rchande** [comment]
@MattGertz This change makes signature help usable in the presence of tuples. It has two features:
* Signature help for invocations, etc stays up if a user starts typing a tuple, even a tuple isn't expected in the current argument position (change to existing providers)
* When a tuple is expected at the current argument position, sighelp now shows the type/names of the expected tuple members as the user types them (new provider)

I would expect us to get feedback about the lack of this if we ship it in RC, though its absence certainly won't block the use of tuples. I believe this is relatively low risk--it adds a new signature help provider, though the implementation mostly reuses the large library of sighelp helper methods we already have.

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
retest this please

**Pull request merged**
