### PR TITLE
Use smarter type equality in `DependentTypeFinder`

### LINKED ISSUE #4973: Solution Explorer "Derived Types" missing some derived types
1. Open Roslyn.sln in VS.
2. Navigate to [PreviewWorkspace](http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Shared/Preview/PreviewWorkspace.cs,aa6ee406a52b5a53,references) type node in Solution Explorer.
3. Right click and choose "Derived Types"

**Expected**: It should find [```PreviewDialogWorkspace : PreviewWorkspace```](http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices/Implementation/Preview/PreviewUpdater.PreviewDialogWorkspace.cs,4b37df9c924a4540)
**Actual**: No derived types found.

### PR DESCRIPTION
**Pull request by brettfo**
_This is the same as #7164 but against `stabilization`._

Due to potential assembly retargeting, simple type equivalence (e.g., `==`) can't be used in `DependentTypeFinder` so instead equivalence is checked via an added `AbstractReferenceFinder.OriginalSymbolsMatch` shortened stub.

All added tests force retargeting by referencing the _portable_ mscorlib in the base test assembly and the _normal_ mscorlib in the other.

The end-user impact is that when right-clicking on a type in the Solution Explorer and selecting "Derived Types" or "Implements", the complete (correct) set of types is shown.

Fixes #4973.

### CODE REVIEW

**Comment by brettfo** [comment]
Not sure what happened to ETA tests.  Closing and re-opening to try again.

**Comment by brettfo** [comment]
I have a prior approval from @Pilchie on #7164 which is identical to this, just against a different branch so I'm assuming that approval carries over here as well.

Anybody else from @dotnet/roslyn-ide want to take a look?

**Comment by brettfo** [comment]
Also tagging @amcasey because he'd be really sad if this didn't make it in.

**Comment by brettfo** [comment]
Tagging @MattGertz for ask-mode approval.

**Comment by amcasey** [comment]
@brettfo Very sad.  I've been asking Brett about this weekly for months.

**Comment by MattGertz** [comment]
@amcasey @brettfo This sadness cannot -- _must not _-- be allowed to stand.  Approved.

(But it would also be sad if anyone else tried to play the sadness card...)

**Pull request merged**
