### PR TITLE
Use binary logger

### PR DESCRIPTION
**Pull request by jaredpar**
This will produce more detailed logs that will help the SDK
team track down a few CI issues.

### CODE REVIEW

**Comment by khyperia** [comment]
[Update the Mac/Linux build as well?](https://github.com/dotnet/roslyn/blob/a005d6883c5939705e3e9c41a80e18cece85eb20/cibuild.sh#L113)

**Comment by jaredpar** [comment]
@khyperia done

**Comment by jasonmalinowski** [comment]
@jaredpar I assume we're just going to leave this in for the next time we need it?

**Comment by nguerrera** [comment]
@jasonmalinowski  @jaredpar  I hope seo. Please leave it. I was able to diagnose a subtle issue in minutes using the binlog and it will be invaluable for any similar investigation in the future. We don't want to have to toggle it on and off when something new happens.

**Comment by jaredpar** [comment]
Yes definitely leaving this in. The plan was to always do this.

**Pull request merged**
