### PR TITLE
Re-enable data flow analysis around local functions

### PR DESCRIPTION
**Pull request by agocke**
Aside from a minor fix around captured variables, this PR is mostly just tests and preventing the `Failed` bit from being set when analyzing local functions. There are two outstanding bugs that are not fixed in this PR:

https://github.com/dotnet/roslyn/issues/14214 is an existing bug around accurate reporting of data flows out.

https://github.com/dotnet/roslyn/issues/21975 is a new bug that tracks new feature work to add local functions to the API as reified trackable entities.

### CODE REVIEW

**Comment by agocke** [comment]
cc @ivanbasov @tmat @jcouv

**Comment by agocke** [comment]
@ivanbasov This wasn't OK to merge -- compiler changes need two sign offs from the compiler team to merge.

**Comment by ivanbasov** [comment]
Ouch. Sorry! I thought it was already signed off in the branch review. Should we do anything with this?

**Comment by agocke** [comment]
@ivanbasov No I think it's OK because it was mostly approved.

**Pull request merged**
