### PR TITLE
Disable Failing Documentation Tests (Stabilization)

### PR DESCRIPTION
**Pull request by natidea**
Disable Failing Documentation Tests #8807

### CODE REVIEW

**Comment by genlu** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4024/
// Retest reason: the exception looks like a build machine issue
```
 Scenario: 4) Verify completion list for #load members
	Executing action [2/17/2016 11:11:37 PM] ClearReplText
	Executing action [2/17/2016 11:11:37 PM] CreateUserFile
	Executing action [2/17/2016 11:11:37 PM] SubmitReplText
given range is not current
given range is not current
	Executing action [2/17/2016 11:11:39 PM] DeleteUserFile
--------------------------------
System.IO.IOException: The process cannot access the file 'C:\Users\dotnet-bot\c.csx' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Roslyn.CommonToBothHosts.Test.DeleteUserFileAction.Execute(TaoEngine engine) in d:\j\workspace\dotnet_roslyn---bd6e1dbd\Closed\Hosting\Test\Actions\Common\DeleteUserFileAction.cs:line 22
   at Tao.Engine.DebuggableActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 139
   at Tao.Engine.DefaultActionExecutor.Execute() in f:\dd\src\Omni\Tao\Tao.Engine\ActionExecutor.cs:line 36
```

**Comment by genlu** [comment]
I think it is safe to merge this, as the change has absolute no effect on eta tests.

**Comment by davkean** [comment]
Is this blocking something? If not, let's let the runs run to the end. That may be true in this case, but I don't want a mindset of merging before the runs have completed.

**Comment by genlu** [comment]
@davkean Nope, just wanted to rerun the tests for those ask mode PRs as soon as possible. Now that the eta tests just got started, there's no reason to rush.

**Pull request merged**
