### PR TITLE
SyntaxTrees constructed by the EE should have Locations...

### LINKED ISSUE #4098: VS crashes when anonymous type field names match implicit anonymous types constructed for LINQ query
For example, typing:
```csharp
from x in my_list
from y in my_list
where my_list.IndexOf(y) > my_list.IndexOf(x)
select new { x, y };
```
in the Watch or Immediate Window causes VS to crash.

### PR DESCRIPTION
**Pull request by KevinH-MS**
While the trees constructed by the EE aren't rooted at a CompilationUnit,
they do have SourceText and are capable of providing a valid SourceLocation
for every piece of Syntax.

Emit requires that certain types of Symbols have Locations (for example,
deterministic ordering of anonymous types is based on SourceLocations).

(fixes #4098)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @dotnet/interactive @dotnet/roslyn-compiler

**Comment by KevinH-MS** [comment]
Note:  VB has its own set of problems with analogous scenarios.  I will send a separate PR once I work through those.

**Comment by cston** [comment]
LGTM

**Comment by KevinH-MS** [comment]
PR test revealed that since we now have Location info, Span info was showing up in more Diagnostic messages.  Rather than simply updating the baselines, I'm taking this opportunity to unify the Diagnostic formatting in the EE (consistently omit Span information).  I assert that it is almost never useful, and on the whole, it just clutters up the error messages.

**Comment by amcasey** [comment]
You might want to check for an existing bug - I suspect we already wanted to remove/fix them.

**Comment by TyOverby** [comment]
LGTM

**Comment by KevinH-MS** [comment]
@amcasey I could not find an existing Issue (although I know this has been discussed).

**Comment by KevinH-MS** [comment]
test unit please

**Comment by KevinH-MS** [comment]
test win please

**Comment by KevinH-MS** [comment]
test unit please?

**Comment by KevinH-MS** [comment]
test unit 32 please?

**Comment by KevinH-MS** [comment]
test this please

**Comment by VSadov** [comment]
LGTM

**Comment by KevinH-MS** [comment]
test this please

**Comment by KevinH-MS** [comment]
test this please

**Pull request merged**
