### PR TITLE
Update the project guids for the PooledObjects.shproj in slns

### PR DESCRIPTION
**Pull request by agocke**
/cc @jaredpar @tannergooding @dotnet/roslyn

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Didn't this already get done in the other direction? :+1: otherwise.

**Comment by agocke** [comment]
@jasonmalinowski It got reverted by a merge going the other way. Rather than try and compete with people who have been using Roslyn.sln, this just brings the other solutions to match that one.

**Comment by CyrusNajmabadi** [comment]
Yeah, i thought i already fixed this.  Did i fix it improperly?  If so, sorry about that!

**Comment by agocke** [comment]
@CyrusNajmabadi It's just a mess. I can't figure out quite what happened.

**Pull request merged**
