### PR TITLE
Create life-time regions for flow captures in Control Flow Graph.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Create Control Flow Graph regions to designate life-time of flow captures in a Control Flow Graph. A region should start as soon as a capture is needed to accurately represent the order of evaluation within operations involving control of flow. However, it should not start too soon. For example, if there is a branch that represents an execution path that bypasses the use of a capture completely, that branch should not be included into the region for the capture. Also, the region should end as soon as the last operation referencing the capture is reached.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred, @mavasani, @cston, @dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review. I might do some minor changes/clean-up of implementation in the builder, but do not expect any major changes.

**Comment by 333fred** [comment]
>                                         Debug.Assert(!subRegion.HasCaptureIds);

Somewhat unrelated: we should also assert that there are no locals in the region as well.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:543 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                                         Debug.Assert(!subRegion.HasCaptureIds);

> Somewhat unrelated: we should also assert that there are no locals in the region as well.

This is intentional, we do drop locals if there is no code using them

---
In reply to: [400088532](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400088532) [](ancestors = 400088532)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:543 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             if (operation == null)

Where are we hitting this? Naively, I wouldn't expect to hit null in this function.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1180 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             if (operation == null)

It would imply that we're returning a `null` in `Children` somewhere, and that would be a bug.

---
In reply to: [400089593](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400089593) [](ancestors = 400089593)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1180 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             if (operation == null)

> Where are we hitting this?

I do not remember if there was any specific case, or was I simply defensive by default. In general our generic Visit helpers are safe with null input.

---
In reply to: [400089754](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400089754) [](ancestors = 400089754,400089593)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1180 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             if (operation == null)

Then perhaps we should consider adding an assert here, so that if we do encounter it we can make sure it's not a bug.

---
In reply to: [400091406](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400091406) [](ancestors = 400091406,400089754,400089593)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1180 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             for (int i = 0; i < _evalStack.Count; i++)

Consider using a foreach loop instead, as we don't actually use `i` for any validation.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1295 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by cston** [comment]
>             _evalStack.Push((frame, operationOpt: null));

Where does `frame.RegionBuilderOpt` get assigned to `_currentRegion`?

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1635 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>                     LeaveRegionsUpTo(resultCaptureRegion);

Shouldn't the things that are visited be responsible for leaving the regions they create?

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1560 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by cston** [comment]
>                             if (operation is IFlowCaptureReferenceOperation refernce)

Typo

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1773 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>         private class EvalStackFrame

Consider extracting to a separate file, having the nested class in the middle of a file here is weird and inconsistent with how we do nested classes in Roslyn.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1613 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by cston** [comment]
>                     }

`LeaveRegionsUpTo(currentSpillRegion);`

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1810 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                     }

> LeaveRegionsUpTo(currentSpillRegion);

No. That one doesn't assert what we need.

---
In reply to: [400101566](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400101566) [](ancestors = 400101566)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1810 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                 }

> LeaveRegionsUpTo(toLeave);

No. That one doesn't assert what we need.

---
In reply to: [400101477](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400101477) [](ancestors = 400101477)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1687 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             if (operation == null)

> Then perhaps we should consider adding an assert here, so that if we do encounter it we can make sure it's not a bug.

I do not think this is necessary. The function was and still is safe for null input. There is nothing wrong to call it with null input. We have other means to assert the expected shape of nodes in a tree.

---
In reply to: [400091705](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400091705) [](ancestors = 400091705,400091406,400089754,400089593)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1180 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             if (_startSpillingAt == stackDepth)

Explanatory comment of when this can occur would be useful.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1645 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         private class EvalStackFrame

> Consider extracting to a separate file, having the nested class in the middle of a file here is weird and inconsistent with how we do nested classes in Roslyn.

I do not believe this small class deserves its own file.

---
In reply to: [400101545](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400101545) [](ancestors = 400101545)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1613 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             if (_startSpillingAt == stackDepth)

> Explanatory comment of when this can occur would be useful.

Isn't this obvious? When everything is spilled.

---
In reply to: [400103764](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400103764) [](ancestors = 400103764)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1645 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                     LeaveRegionsUpTo(resultCaptureRegion);

> Shouldn't the things that are visited be responsible for leaving the regions they create?

Not in general. It might be that in this case we will always be at this region, but there is no harm in making sure.

---
In reply to: [400094498](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400094498) [](ancestors = 400094498)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1560 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             _evalStack.Push((frame, operationOpt: null));

> Where does frame.RegionBuilderOpt get assigned to _currentRegion?

SpillEvalStack helper allocates the region and enters it, that makes it current.


---
In reply to: [400093536](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400093536) [](ancestors = 400093536)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1635 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                     LeaveRegionsUpTo(resultCaptureRegion);

To clarify, regions created for stack spilling remain active until either leaved implicitly by another spilling, or explicitly by a caller, but things that are visited often do not know if they can leave the regions yet.

---
In reply to: [400105628](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400105628) [](ancestors = 400105628,400094498)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1560 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>         private void VerifySpilledStackFrames()

Consider using `Conditional("DEBUG")` instead of ifdefs

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1818 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         private void VerifySpilledStackFrames()

> Consider using Conditional("DEBUG") instead of ifdefs

This will leave this function in release build, which I would like to avoid.

---
In reply to: [400107706](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400107706) [](ancestors = 400107706)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1818 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>         private void VerifySpilledStackFrames()

I mean, the function won't be executed in the Release build. Technically the instructions will still be there, but that doesn't seem to me like it's an actual problem, especially not for a small function like this, and it would get rid of the need for preprocessor checking here and everywhere it's called.

---
In reply to: [400108834](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400108834) [](ancestors = 400108834,400107706)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1818 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         private void VerifySpilledStackFrames()

> I mean, the function won't be executed in the Release build. Technically the instructions will still be there, but that doesn't seem to me like it's an actual problem, especially not for a small function like this, and it would get rid of the need for preprocessor checking here and everywhere it's called.

It is my intent to not have this function in release build.

---
In reply to: [400110465](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400110465) [](ancestors = 400110465,400108834,400107706)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1818 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
The eval stack logic seems to be getting sufficiently complex to me to warrant refactoring out of the main builder logic altogether. We've already replaced most of the directly `_evalStack` usage in the individual `VisitX` methods, so it doesn't seem like a huge change.
Separately, we should also consider refactoring out the region and block packing steps, as those aren't dependent on the standard visitor logic.

**Comment by 333fred** [comment]
>         /// This function does not change the current region. The stack should be spilled before calling it.

And yet the first thing this function does is spill the stack?

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:2541 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         /// This function does not change the current region. The stack should be spilled before calling it.

> And yet the first thing this function does is spill the stack?

It looks like the comment got stale in the process. I'll remove it.

---
In reply to: [400116582](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400116582) [](ancestors = 400116582)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:2541 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             EvalStackFrame frame1 = PushStackFrame();

Consider naming for the actual things they represent, rather than frame(1|2)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:3699 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             EvalStackFrame frame1 = PushStackFrame();

> Consider naming for the actual things they represent, rather than frame(1|2)

I think that got actually changed in second commit

---
In reply to: [400120038](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400120038) [](ancestors = 400120038)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:3699 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>             public void AddCaptureId(int captureId)

Nit: consider adding newline before

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.RegionBuilder.cs:47 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>         /// Region with the only purpose to represent the life-time of locals, intermediate results and nested methods (local functions, lambdas).

Nit: consider oxford comma

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowRegionKind.cs:18 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         /// Region with the only purpose to represent the life-time of locals, intermediate results and nested methods (local functions, lambdas).

> Nit: consider oxford comma

You will have to be more specific than that.

---
In reply to: [400129158](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400129158) [](ancestors = 400129158)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowRegionKind.cs:18 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>                         Any(d => d.Code == (int)VisualBasic.ERRID.ERR_GotoIntoWith ||

Consider adding a comment on why these can't be verified.

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:329 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>                         if (candidate.Language != LanguageNames.VisualBasic)

Why not just move this to the top of the function and bail out immediately if the original operation isn't VB?

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:555 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                         if (candidate.Language != LanguageNames.VisualBasic)

> Why not just move this to the top of the function and bail out immediately if the original operation isn't VB?

What operation?

---
In reply to: [400131484](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400131484) [](ancestors = 400131484)

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:555 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>         /// Region with the only purpose to represent the life-time of locals, intermediate results and nested methods (local functions, lambdas).

Sorry, sometimes I forget that English isn't a first language for everyone. In a list of 3 or more things, there are two comma styles that you can use. The first is without the Oxford comma, which you did here. Including an oxford comma means putting a comma before the coordinating conjunction. So in this case, it would read:
> Region with the only purpose to represent the life-time of locals, intermediate results *,* and nested methods (local functions, lambdas).
Technically this comma is optional (depending on whether you ask a linguist), but it helps clarify that the final two elements of a list are disjoint things. I view it as ensuring the reader understands the difference between a || (b && c) and a || b || c.

---
In reply to: [400130053](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400130053) [](ancestors = 400130053,400129158)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowRegionKind.cs:18 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>                         if (candidate.Language != LanguageNames.VisualBasic)

> What operation?

The `OriginalOperation` from the graph.

---
In reply to: [400131707](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400131707) [](ancestors = 400131707,400131484)

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:555 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>                         if (candidate.Language != LanguageNames.VisualBasic)

Same comment

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:588 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                         if (candidate.Language != LanguageNames.VisualBasic)

> Same comment

Yes, I'll update all similar places

---
In reply to: [400132869](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400132869) [](ancestors = 400132869)

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:588 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Comment by 333fred** [comment]
>         private static void GetFlowGraph(System.Text.StringBuilder stringBuilder, Compilation compilation, ControlFlowGraph graph,

This file (and by extension class) is now 71% local functions. At what point can we call bankruptcy on the local functions and make them members to aid understanding of the class.

---
Refers to: src/Test/Utilities/Portable/Compilation/ControlFlowGraphVerifier.cs:88 in 925477b. [](commit_id = 925477b5bfd33ab70684a0f705903589478c5582, deletion_comment = False)

**Review by 333fred — APPROVED** [review]
LGTM once the current pending comments are addressed. I would like to see an issue filed to track some general refactorings on this code. It's very dense and there's a lot of coupling going on for things that can and should be separated to aid comprehension for other developers, and I'd like to make sure we pay back debt on this before much longer to prevent this from becoming an unmaintainable mess.

**Comment by cston** [comment]
>                 EnsureRegionsForStackFrames();

If this is the only caller, consider inlining `EnsureRegionsForStackFrames` so there are fewer small methods to understand.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1266 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Comment by cston** [comment]
Please add a description for this change.

**Review by mavasani — APPROVED** [review]
:shipit:

**Comment by cston** [comment]
>                     // to some captures from the stack. Than means that, after the spilling, we should be able to leave the spill

`That`?

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:1758 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Comment by cston** [comment]
>             Debug.Assert(_evalStack.Last().frameOpt != null && _startSpillingAt >= _evalStack.Count - 1);

Consider splitting into two asserts.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:2728 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Comment by AlekseyTs** [comment]
@333fred 

> I would like to see an issue filed to track some general refactorings on this code. It's very dense and there's a lot of coupling going on for things that can and should be separated to aid comprehension for other developers, and I'd like to make sure we pay back debt on this before much longer to prevent this from becoming an unmaintainable mess.

I am going to delegate opening this issue to you. It feels like you have some specific ideas in mind and I prefer to avoid trying to guess all of them. We might also have differences in opinions.

**Comment by cston** [comment]
>             LeaveRegion();

Consider passing the expected region to `LeaveRegion` and assert there.

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:3919 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>             LeaveRegion();

> Consider passing the expected region to LeaveRegion and assert there.

Since this is will be just a refactoring and since the value to assert is not always readily available (more code will have to be changed, not just the call sites), I will not be making this change in this PR. However, I will keep this suggestion in mind for future changes.

---
In reply to: [400350351](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400350351) [](ancestors = 400350351)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:3919 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Comment by AlekseyTs** [comment]
@cston, @333fred I think all feedback provided to this point has been addressed.

**Comment by AlekseyTs** [comment]
Tagging @jinujoseph for approval. I still need to get a second sign-off from compiler team, but would like to get an approval from you to avoid any unnecessary delays.

**Comment by jinujoseph** [comment]
Pre-Approved for 15.8.P4

**Comment by cston** [comment]
>                                OperationCloner.CloneOperation(captured);

Can we use `CloneOperation` even for the `IFlowCaptureReferenceOperation` case?

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:6076 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
>                                OperationCloner.CloneOperation(captured);

> Can we use CloneOperation even for the IFlowCaptureReferenceOperation case?

Yes we can, unfortunately it will use the original syntax. In this case, we actually would like to change the syntax to point to the property reference. If the original IOperation tree is well formed, we are dealing with a capture reference here and can easily replace the syntax.

---
In reply to: [400370843](https://github.com/dotnet/roslyn/pull/28100#issuecomment-400370843) [](ancestors = 400370843)

---
Refers to: src/Compilers/Core/Portable/Operations/ControlFlowGraphBuilder.cs:6076 in d5d7e2b. [](commit_id = d5d7e2be28fc24b152c23b0438c5e735ff671263, deletion_comment = False)

**Pull request merged**
