### PR TITLE
Fix a bad merge that left a merge conflict marker in a user visible string.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/32986

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @tmat @genlu

**Comment by CyrusNajmabadi** [comment]
@sharwell free free to merge.

**Comment by jasonmalinowski** [comment]
Tagging @jinujoseph for M2 approval.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @sharwell @jinujoseph feel free to merge.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Just waiting on CI.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski CI is complete.  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
