### PR TITLE
fixed DebugType ArgumentNullException in CommandLineArgumentReader

### PR DESCRIPTION
**Pull request by tanghel**
in the situation where DebugType is mising and the DebugSymbols property is set to true when loading project information using CommandLineArgumentReader, the TryGetValue method of the s_debugTypeValues dictionary would throw an exception

reproduceable using the following method on the attached solution:

```csharp
        public static async Task ReproduceDebugTypeError()
        {
            var workspace = Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create();
            var solution = await workspace.OpenSolutionAsync(@"C:\Repros\ProjectLoadErrorOnMissingDebugTypeRepro\ProjectLoadErrorOnMissingDebugTypeRepro.sln");
        }
```

[ProjectLoadErrorOnMissingDebugTypeRepro.zip](https://github.com/dotnet/roslyn/files/2427898/ProjectLoadErrorOnMissingDebugTypeRepro.zip)

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@tanghel Any chance you can add that repro you have as a unit test?

**Comment by tanghel** [comment]
@jasonmalinowski will try to add it tomorrow. You are right, it makes sense to have the repro as a unit test included

**Comment by tanghel** [comment]
@jasonmalinowski just to have a little bit of more context, here is the commit that triggered this issue: e38ad882165357e916183418d724fb8b903f8936

The issue happens only in the ReadCommandLineArgs method call of the GetCommandLineArgs method in ProjectFile.cs, line 162:

```csharp
        private ImmutableArray<string> GetCommandLineArgs(MSB.Execution.ProjectInstance project)
        {
            var commandLineArgs = GetCompilerCommandLineArgs(project)
                .Select(item => item.ItemSpec)
                .ToImmutableArray();

            if (commandLineArgs.Length == 0)
            {
                // We didn't get any command-line args, which likely means that the build
                // was not successful. In that case, try to read the command-line args from
                // the ProjectInstance that we have. This is a best effort to provide something
                // meaningful for the user, though it will likely be incomplete.
                commandLineArgs = ReadCommandLineArgs(project);
            }

            return commandLineArgs;
        }
```

**Comment by jasonmalinowski** [comment]
This looks good to me. @DustinCampbell you're familiar with this code, any thoughts?

**Comment by DustinCampbell** [comment]
FWIW, I just ran into this same problem when fixing #29122 and have the same fix in my PR, #30331.

**Comment by jasonmalinowski** [comment]
Awesome, thanks @tanghel for the fix!

**Comment by tanghel** [comment]
Nice timing! Thanks @jasonmalinowski & @DustinCampbell for approving the PR! Makes me feel that my efforts were not **totally** in vain! 😄

**Pull request merged**
