### PR TITLE
Fix assert failure for FileThatCannotBeDecoded under default codepage 936

### PR DESCRIPTION
**Pull request by diryboy**
I got assert failure from this test case from code page 936. I think it's similar to #6633

```
    Microsoft.CodeAnalysis.CSharp.UnitTests.LoadDirectiveTests.FileThatCannotBeDecoded
      Assert.Equal() Failure
      Expected: 3
      Actual:   4
      Stack Trace:
        src\Compilers\CSharp\Test\Symbol\Compilation\LoadDirectiveTests.cs(77,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.LoadDirectiveTests.FileThatCannotBeDecoded()
```

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-interactive 
@dotnet-bot test eta please

**Comment by KevinH-MS** [comment]
:-1: This doesn't seem right.  The intent of this test is not to be specific to en-US locale.

@diryboy, you're saying you just have 936 set as your default CodePage?  (I can try to repro/debug)

**Comment by KevinH-MS** [comment]
It looks like the correct fix is to just add one more "0x00":
```
69                   KeyValuePair.Create<string, object>("a.csx", new byte[] { 0xd8, 0x00, 0x00, 0x00 }), 
```
@diryboy if you want to update this PR, that'd be swell! :wink:

**Comment by diryboy** [comment]
@KevinH-MS Thanks, I updated the code as you suggested and the test passed locally.

**Comment by KevinH-MS** [comment]
:+1: Thanks!

**Pull request merged**
