### PR TITLE
A method may have the same name as its type parameter.

### LINKED ISSUE #7506: Incorrect error on method name conflict with its type parameter
The following code is allowed by the language spec and allowed by the mono compiler. For compat Roslyn should allow it too.

```cs
void T<T>()  // Should be no error
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #7506 

@dotnet/roslyn-compiler Please review

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet-bot test this please

**Comment by TyOverby** [comment]
test prtest/win/dbg/eta please

**Pull request merged**
