### PR TITLE
Use Microsoft.Metadata.Visualizer

### PR DESCRIPTION
**Pull request by tmat**
MetadataVisualizer and ILVisualizer are now in a separate repo: http://github.com/dotnet/metadata-tools

### CODE REVIEW

**Comment by tmat** [comment]
test windows_eta_open_prtest please

**Comment by tmat** [comment]
@dotnet/roslyn-compiler Please review. Test only change.

**Comment by tmat** [comment]
Tagging @cston For EE test changes

**Comment by cston** [comment]
LGTM

**Pull request merged**
