### PR TITLE
Disable "Reset ... Interactive from Project" for now...

### LINKED ISSUE #4689: Don't show "Reset C# Interactive from Project" command for now...
We're not targeting this scenario for Milestone 1.1, so we should disable the command for now (also, it doesn't work well in current builds...you cannot type after the reset...).

### PR DESCRIPTION
**Pull request by KevinH-MS**
Fixes #4689

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @ManishJayaswal @amcasey @tmat @cston

**Comment by cston** [comment]
LGTM

**Comment by amcasey** [comment]
Is there a work item to restore it?  LGTM

**Comment by KevinH-MS** [comment]
I will augment #4688 to include re-enabling this (they're all kinda related).

**Comment by amcasey** [comment]
As long as there's a link in the commented-out section, I'm happy. :)

**Comment by ManishJayaswal** [comment]
:+1:

**Comment by KevinH-MS** [comment]
Added URLs to the comments

**Pull request merged**
