### PR TITLE
Fix perf regression in gotodef.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=433771&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&src=WorkItemMention&src-action=artifact_link&fullScreen=true&_a=edit

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 


**Customer scenario**

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

**Bugs this fixes:**

https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=433771&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&src=WorkItemMention&src-action=artifact_link&fullScreen=true&_a=edit

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

Perf is improved.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

Work to make our system better handle OOP (by computing more information up front), ended up hurting a non-OOP scenario.

**How was the bug found?**

RPS test.

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest please

**Comment by AdamSpeight2008** [comment]
@CyrusNajmabadi Loving the comments in the code.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_vs-integration_prtest please

**Pull request merged**
