### PR TITLE
DryDock Effort: Removing the skipped unit tests from SymbolKeyTest

### PR DESCRIPTION
**Pull request by jinujoseph**
Associated work Item has been closed as won't fix
http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/530169

### CODE REVIEW

**Comment by jinujoseph** [comment]
@dotnet/roslyn-ide

**Comment by davkean** [comment]
@jinujoseph Are you correctly part of the Microsoft & dotnet organizations? We're not automatically running ETA for you, which would be indication that you are not.

**Comment by jinujoseph** [comment]
test eta please

**Comment by DustinCampbell** [comment]
@jinujoseph: What's the status of this PR? Is it still relevant?

**Pull request closed without merging**
