### PR TITLE
Fix code format in tuple documentation

### PR DESCRIPTION
**Pull request by benknoble**
Code fence misalignment caused improper markdown rendering

@jcouv could you take a look? Not sure why windows debug/integration is failing...

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
FYI @dotnet/roslyn-compiler 
I'll merge when CI is green. This is doc-only change.

Thanks @benknoble

**Comment by jcouv** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by benknoble** [comment]
@jcouv Looks green

**Pull request merged**
