### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160315-150022
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160315-150022 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by davkean** [comment]
tag @jasonmalinowski before we merge this in, we need to resolve the project.lock.json files which have been deleted in master

**Comment by heejaechang** [comment]
I know tomas told me about this yesterday. I will pick deleted one over tomas change


-          heejae

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/503/
// Retest reason: known linked file issue

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/483/
// Retest reason: opened an issue

**Pull request merged**
