### PR TITLE
Adds the [ConditionalFact(typeof(OSVersionWin8))] attribute to several C# Compiler Unit Tests (WinRT).

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by ManishJayaswal** [comment]
Looks good

**Comment by tmeschter** [comment]
:+1:

**Comment by agocke** [comment]
I've created an alternate fix on #606 that keeps compilation but removes the execution (which was causing the test to crash).

**Comment by tannergooding** [comment]
@agocke  LGTM, I'll close this pull request.

**Pull request closed without merging**
