### PR TITLE
Spacing between this and open-paren in tuple extension method

### PR DESCRIPTION
**Pull request by jcouv**
**Customer scenario**
Type an extension method on a tuple type (`static void Extension(this (int, string) self)`) and format document. The space before the tuple's open-paren is removed.

**Bugs this fixes:** 
https://github.com/dotnet/roslyn/issues/15570

**Workarounds, if any**
This is annoying but not breaking.

**Risk**
**Performance impact**
Low. Added a specific case to the space formatting rule.

**Is this a regression from a previous update?**
No.

**How was the bug found?**
Reported by customer.

@CyrusNajmabadi and @dotnet/roslyn-ide for review.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tokens can't have null parents. So ?. Is not needed

**Comment by jcouv** [comment]
@CyrusNajmabadi Makes sense. Simplified the logic.
Thanks

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by jcouv** [comment]
@srivatsn Please approve for RC.3 at your convenience. Details in the description.

**Pull request merged**
