### PR TITLE
Remove some dead code

### LINKED ISSUE #657: Symbol.IsSupportedOperatorName (C#) appears to be unused and should be deleted
Was browsing through the C# symbol code and saw [IsSupportedOperatorName] (http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/SemanticFacts.cs,d03fb008022be42d).

There appear to be no references to this method, even from test code. Looks like it can be deleted (and its attendant [s_supportedOperators](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Semantics/SemanticFacts.cs,5457d3ec75bcec84,references) HashSet.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #657

### CODE REVIEW

**Comment by gafter** [comment]
@jaredpar @VSadov @AlekseyTs @agocke @VladimirReshetnikov Could a couple of you review this please?

**Comment by agocke** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
