### PR TITLE
Canonicalize all interactive window commands

### PR DESCRIPTION
**Pull request by amcasey**
1. Allow button names to have different casing than command names (which
should be PascalCase).
 2. Sidestep some name conflicts with other VS packages.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @cston @KevinH-MS @ManishJayaswal

**Comment by zooba** [comment]
Other than the build issue, the change looks good to me.

**Comment by amcasey** [comment]
Test this please

**Comment by amcasey** [comment]
Test this please

**Pull request merged**
