### PR TITLE
Import parameter's default constant value from metadata even if parameter is not optional.

### LINKED ISSUE #2793: NullReferenceException in ParameterSymbolAdapter.cs
We've gotten a report of a crash (DevDiv 1167553) on the following line of `ParameterSymbolAdapter.cs` (line 73)
```cs
       if (constant.SpecialType != SpecialType.None)
```
This appears to be a bug in `PEParameterSymbol`.  It overrides both `HasMetadatConstantValue` and `ExplicitDefaultConstantValue`.  The former should never return `true` unless the latter is guaranteed to return a non-`null` value.  The base implementation explicitly checks for this but the override does not and hence we end up with a NRE in this method.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2793.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - Fixes bug #2793
- Customer scenario - This is a compiler crash observed in actual customer scenarios involving references to NoPia assemblies that declare a default value for a non-optional parameter.
- Fix description - There was an optimization in implementation of PEParameterSymbol to suppress  default value loading for non-optional parameters. However, this violates mutual contract between HasMetadataConstantValue and ExplicitDefaultConstantValue properties and causes a crash in NoPia scenarios. The fix is to adjust the optimization to cover only attribute values, this doesn’t violate the contract and doesn’t have negative impact on NoPia feature. 
- Testing done - unit-tests.

@jaredpar FYI

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
:+1:

**Comment by jaredpar** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved 5/22 by ML Shiproom.

**Pull request merged**
