### PR TITLE
Stop swallowing JTF exceptions

### PR DESCRIPTION
**Pull request by rchande**
Fixes https://github.com/dotnet/roslyn/issues/21245

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @jmarolf - do we know what changed such that we don't need to do this anymore?

**Comment by rchande** [comment]
@Pilchie Yes--https://github.com/dotnet/roslyn/commit/e47543b238cd0adf8ed146aedf25ff48f76482ec got merged into master.

**Comment by Pilchie** [comment]
@rchande and the update of the editor binaries fixed it, or some other part of that change?

**Comment by rchande** [comment]
@Pilchie Sorry, thought I was copying a file link. https://github.com/dotnet/roslyn/commit/e47543b238cd0adf8ed146aedf25ff48f76482ec#diff-6159a3d84595fb60c93e257f29db681dR206 turns outlining off for our hosted textviews since that's the editor feature for which we can't properly provide a JoinableTaskContext.

**Pull request merged**
