### PR TITLE
Data flow analysis counts var declaration of tuple local as "used"

### PR DESCRIPTION
**Pull request by jcouv**
@dotnet/roslyn-compiler for review (candidate fix for 15.3).

**Customer scenario**
```C#
(int, int) t1 = (-1, 2); // warning CS0219
var t2 = (-1, 2);  // NO warning CS0219
```

**Bugs this fixes:**
https://github.com/dotnet/roslyn/issues/20208

**Risk**
**Performance impact**
Low. Data flow analysis adds a case for TupleLiteral, which return `false` (instead of `true`, the default) just like it does for `ConvertedTupleLiteral`.

**Is this a regression from a previous update?**
No, this bug existed in VS2017 version 15.0. Verified on Microsoft.Net.Compilers package version 2.0.1.

**Root cause analysis:**
The logic in [BindVariableDeclaration](http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp/Binder/Binder_Statements.cs,810) handles two cases differently, (1) `var` and (2) typed local. 
For (2), there will be a conversion, which upgrades the tuple literal to a converted tuple literal. But for (1), which is the case of this bug, there is no conversion. This BoundTupleLiteral makes it through to data flow analysis, which expects that all tuple literals will have been upgraded.
From discussion in https://github.com/dotnet/roslyn/pull/19679, we have established that it's ok for un-converted tuple literals to survive binding. So the fix is to have data flow analysis add a case for BoundTupleLiteral.

This was missed because all the tests with `var` and tuples later use the local.

**How was the bug found?**
Reported by internal customer

### CODE REVIEW

**Comment by cston** [comment]
LGTM

**Comment by jcouv** [comment]
From discussion with Jared, I'll push this out to 15.6.
I will investigate the similar issue that Chuck pointed out with deconstruction, and maybe update this PR.

**Comment by jcouv** [comment]
windows_release_unit32_prtest  failed with 
`error CS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'UserOperationBooster' and '' [D:\j\workspace\windows_relea---d3451073\src\Workspaces\Remote\ServiceHub\ServiceHub.csproj]`

([details](https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_release_unit32_prtest/268/))

I'll re-run

**Comment by jcouv** [comment]
test windows_release_unit32_prtest please

**Comment by jcouv** [comment]
test please

**Comment by jcouv** [comment]
test all please

**Comment by jcouv** [comment]
@cston @AlekseyTs @agocke It looks like I hadn't properly run unittests (sorry about that). I updated them. Now that the var local is properly considered "written", there are warnings when it is not used.

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
