### PR TITLE
Jenkins cross platform updates

### PR DESCRIPTION
**Pull request by jaredpar**
This changes our cross plat build to install the desired version of Mono
on the machine as a part of the CI process.  This lowers the management
overhead of our Mac / Linux machines as we can use any machine in the pool
vs. having reserved, and custom maintained, machines for Roslyn.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @agocke, @mmitche, @VSadov

**Comment by VSadov** [comment]
Can we just require Mono 4.0.1 on the pool machines?
4.0.1 is the first maintenance release of 4.0 series and it looks like our fixes are included.

**Comment by jaredpar** [comment]
@VSadov I chatted with @mmitche about this.  Our fear with that is:

- It is still overhead as it is not a part of the base Mac / Linux drops. 
- It requires sign off / testing for all of the other Jenkins jobs out there (CLR, CoreFx, etc ...). 
- It seems likely that we will need further patches in the future to Mono at which point we would need a solution like this. 

I do agree though it would be nice if we just end up with a standard install.  At some point that will become a reality (as both our cross platform work rounds out and potential future Mono patches make it into the main tree).  When that happens I do plan on pushing us to the solution that you outlined.

**Comment by VSadov** [comment]
LGTM

**Comment by VSadov** [comment]
+1 for eventually pushing for running on a publicly supported setup.

**Comment by MattGertz** [comment]
Approved 5/27 by ML Shiproom.

**Pull request merged**
