### PR TITLE
address more PR feedback.

### PR DESCRIPTION
**Pull request by heejaechang**
this is delta after https://github.com/dotnet/roslyn/pull/8223

it only shows this since PR for reverting those change are still running test.

### CODE REVIEW

**Comment by heejaechang** [comment]
@AlekseyTs can you take a look? I will revert existing and and merge change with this one and send complete PR. but before that can you take a look and see this is what you want?

**Comment by AlekseyTs** [comment]
LGTM. Yes, this should address the remaining issues.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure it looks like tests are killed in the middle of run, known issue?

**Comment by heejaechang** [comment]
@AlekseyTs thank you. so is this sign off this time?

**Comment by AlekseyTs** [comment]
Yes, LGTM (Looks Good To Me) is a sign-off.

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
test failures were due to jenkins brought down.

**Pull request merged**
