### PR TITLE
Fix handling of BlockComments in an empty file

### LINKED ISSUE #16128: Extra * added on the line after a block comment ends.
```C#
/*
class C {}
*/
```
Place the cursor at the end of the comment and press Enter.

**Expected Behavior**:
A newline.

**Actual Behavior**:
A newline plus another `*`.

Originally reported at https://developercommunity.visualstudio.com/content/problem/8316/c-multiline-comment-bug-adds-a-out-of-multiline-ar.html

### PR DESCRIPTION
**Pull request by reaction1989**
Fixes #16128

### CODE REVIEW

**Comment by diryboy** [comment]
Ops, looks we worked on the same issue. I had the same idea with this PR in #16185 but later found not correct. See #16189 for my updated solution.

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide for review.

**Comment by Pilchie** [comment]
Thanks for the submission, but I think I prefer #16189 - particularly for the unit tests.

**Comment by reaction1989** [comment]
@Pilchie  No Problem. I could also add tests for the edge cases. When not just close it

**Comment by Pilchie** [comment]
Okay - I'll go ahead and close it in favor of #16189.  Sorry that your first contribution here ended up colliding like this :(

**Pull request closed without merging**
