### PR TITLE
Exception workarounds

### PR DESCRIPTION
**Pull request by sharwell**
This change avoids some 10,000 `MissingMethodException` and `InvalidCastException` which occur when you load **CrossPlatform.sln** within an experimental instance, improving debugger performance when attempting to debug some IDE behavior with respect to the Roslyn project.

@jaredpar This is pretty ugly. Is this something I should just close or do we want to try and move it forward?

### CODE REVIEW

**Comment by tmat** [comment]
I think this should be addressed in msbuild. Could you follow up with msbuild team?

**Comment by sharwell** [comment]
Closing since the build failures suggest this behavior varies across different versions of MSBuild, and what fixes the problem on one machine actually completely breaks the properties on another.

**Comment by sharwell** [comment]
I fixed this to actually work now. I'm not sure why NuGet failed prior to the last commit in the branch, but the debug experience loading Roslyn.sln is _much_ better with this merged. The MSBuild team is aware of some of the underlying issues, but it's non-trivial to get them fixed. This PR represents an immediate improvement.

**Comment by sharwell** [comment]
@dotnet/roslyn-infrastructure for review

**Pull request merged**
