### PR TITLE
Don't block in library code.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

I thought you had some diagnostics around `WaitAndGetResult` that prevented this?  Or do they not trigger because this code is only called on a UI thread or something?

**Comment by CyrusNajmabadi** [comment]
Correct, this is only called on the UI thread (currently), so it's technically ok.  But, that said, anything that is effectively an IDE library function should be well behaving so we can use from teh BG without any issues.  I really only want to see 'WaitAndGetResult' in code where it absolutely must exist.

**Comment by Pilchie** [comment]
Yep, in favor of the change, just wondering why we didn't see it before.

**Comment by davkean** [comment]
Is this used by TypeScript?

**Comment by CyrusNajmabadi** [comment]
Nope.  TS never refers to our symbolic API.

**Pull request merged**
