### PR TITLE
Revert PRs #12725, #12726, #12786, and #12794 from `dev15-preview-4`.

### PR DESCRIPTION
**Pull request by brettfo**
The specified changes don't meed the bar for Preview 4 but PR #12724 does.

FYI @shyamnamboodiripad @heejaechang @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by brettfo** [comment]
retest windows_debug_unit64_prtest please // random build error?

**Comment by brettfo** [comment]
test vsi please

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by shyamnamboodiripad** [comment]
@brettfo Is the plan to merge this change into master and then un-revert these changes there?

@Pilchie @ManishJayaswal for approval.

**Comment by brettfo** [comment]
The plan is to merge this into `dev15-preview-4` then during the next merge from `dev15-preview-4` to `master` I'll make sure that this revert doesn't make it in.  I've already started a conversation with @jcouv to make this happen.

**Comment by brettfo** [comment]
retest windows_vsi_p3_open_prtest please // test flakiness.  results [here](http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/12/)

**Comment by Pilchie** [comment]
Approved pending Jenkins completion.

**Comment by Pilchie** [comment]
Tag @jasonmalinowski is it better to let it merge and then revert for git's history tracking?

**Comment by jasonmalinowski** [comment]
@Pilchie My concern is if it's "temporarily" in master, then we might start inserting back and forth between these two states. I'm not sure what that might mean. Better to ensure master is "always right" I think.

**Comment by Pilchie** [comment]
Okay - just wanted to make sure you were aware of the plan.

**Comment by brettfo** [comment]
retest windows_vsi_p3_open_prtest please // test flakiness, same failure as before

**Comment by brettfo** [comment]
retest windows_vsi_p3_open_prtest please // more flakiness, different tests [here](http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/15/)

**Comment by brettfo** [comment]
More flakiness that we've already seen.  Since tests failing in one run are passing in another (and the reverse for the other set of flaky tests) I'm merging this.

**Comment by mavasani** [comment]
@brettfo Can you ensure bugs are filed for flaky tests? For flaky test with existing bugs, please add the failure link to the bug, and mark it as Urgency-Now, if not already so.

**Comment by brettfo** [comment]
Flaky tests are already being tracked by #12547.  I've added links in the issue to the test failures seen in this PR.

**Pull request merged**
