### PR TITLE
implement send mail function

### PR DESCRIPTION
**Pull request by TyOverby**
@KevinH-MS

### CODE REVIEW

**Comment by KevinH-MS** [comment]
LGTM - Now that we should be running the tests on a regular cadence, can we get this merged and hooked up to automation.csx?

**Comment by KevinH-MS** [comment]
Merge and hook up?

**Comment by KevinH-MS** [comment]
Seems like Jenkins is going to do this for us soon, so I'm going to close this.

**Comment by TyOverby** [comment]
:+1:

**Pull request closed without merging**
