### PR TITLE
fixing merge break: adding document attribute to pdb in broken tests

### PR DESCRIPTION
**Pull request by ivanbasov**

### CODE REVIEW

**Comment by tmat** [comment]
👍

**Comment by AlekseyTs** [comment]
retest this please

**Comment by AlekseyTs** [comment]
@dotnet-bot Retest this please

**Comment by AlekseyTs** [comment]
Test windows_debug_unit32_prtest please

**Comment by tmat** [comment]
test windows_debug_unit32_prtest  please

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/9399/

Jenkins Remoting Error

Java / Jenkins hit a remoting error that caused the build to fail.
Indication 1

**Comment by AlekseyTs** [comment]
Test windows_debug_unit32_prtest please

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/9388/


Jenkins Remoting ErrorJava / Jenkins hit a remoting error that caused the build to fail.Indication 1 Indication 2 Indication 3
--
  | File operation failedThere was an I/O error during the build. This could be caused by a hung process on the target machine, preventing it from cleaning up the workspace, or other issues, such as low disk space.Indication 4

**Comment by ivanbasov** [comment]
test windows_debug_unit32_prtest

**Comment by AlekseyTs** [comment]
Test windows_coreclr_test_prtest please

**Comment by AlekseyTs** [comment]
Test windows_debug_unit64_prtest please

**Pull request merged**
