### PR TITLE
Ref locals and returns

### PR DESCRIPTION
**Pull request by VSadov**
Ref locals and ref returns are generalizations of ref parameters in a sense that they do not get attached to a data slot automatically and instead can represent existing storage locations.

The goal is to allow abstracting in-place data from its actual storage (fields, arrays,  slices) with minimum overhead. The targeted audience is the set of high performance scenarios where in-place update operations could be used to reduce unnecessary copying.

========================  
Ref locals
For the most part, ref locals behave just like regular locals. The most important difference is that 
unlike regular locals, ref locals do not get a distinct storage location and instead can be ref-assigned an existing location. 
In fact, due to definite assignment rules, a ref local must be ref-assigned before it can be used as a regular local.

``` C#
        int[] arr = new int[] { 1, 2, 3 };

        ref int element;            // ref local declared but does not have any storage        
        element = ref arr[1];       // ref assignment of storage        
        element = element + 40;     // regular reads and writes 

        System.Console.WriteLine(arr[1]);  // prints 42
```

To guarantee that references do not outlive referents, a "safe to return" rule is applied at the point of ref assignment. As a result all ref locals, once ref-assigned, can be ref-returned, or ref-assigned to a different ref local, and so on, transitively and recursively...

=========================
2.2.1        Ref returns
We would allow a function to indicate that its return value is a ref:

```C#
public static ref S Choose(ref S s1, ref S s2)
{
    if (…) return ref s1;
    else return ref s2;
} 
```

Just like ref arguments need to be explicitly annotated as such at the call site, ref return values must also be explicitly indicated in the return statement. This is just a syntactic rule to ensure people are aware that they are trading in refs. A call to a ref-returning method is classified as a variable, and can therefore be assigned to.

It should be legal for a method to pass its own locals to a ref returning method, and get one of them back. However, we want to avoid a method returning a ref to one of its own locals. Technically, we could capture them and hoist them to the heap to enable this, just as we do for lambdas, but that defeats the purpose of being nimble and close to the metal.

Instead there are simple rules about which variables are “safe to return”, essentially ensuring that a method does not return its own variables:

•         refs to variables on the heap are safe to return
•         ref parameters are safe to return
•         out parameters are safe to return (but must be assigned, as is already the case today)
•         instance struct fields are safe to return as long as the receiver is safe to return
•        “this” is not safe to return inside struct members
•         a ref returned from another method is safe to return if all refs passed to that method as formal parameters were safe to return. (specifically it is irrelevant if receiver is safe to return, regardless whether receiver is a struct, class or typed as a generic type parameter)

The last rule works because the rules apply recursively to the invoked method as well.

Here is an example of what’s allowed and what’s not:

```C#
public static ref int Foo(ref int r1, ref int r2)
{
    int v1 = 1, v2 = 2;
    Choose(ref r1, ref r2) = 3; // Ok – one of passed in refs is assigned to
    return ref Choose(ref r1, ref r2); // Ok – one of passed in refs is returned
    Choose (ref v1, ref v2) = 4; // Ok – one of my own locals is assigned to
    return ref Choose(ref v1, ref v2); // Error: Would return one of my locals
    return ref Choose (ref r1, ref v1); //Error: Might return one of my locals
}
 
public interface IRefIndexable<T>
{
    ref T this[int i] { get; } 
}

public static ref int Foo<T>(T indexable, int i) where T: IRefIndexable<int>
{
    DoSomething(blah, blah);
    . . .
    return ref indexable[i];   // valid even though T might be a struct
}

struct MyIndexable : IRefIndexable<int>
{
    int size;
    int[] array;

    public ref int this[int i]
    {
        get
        {
            return ref this.array[i]; // legal, the referent is on the heap
            return ref this.size;     // not legal, “this” is not ref returnable 
         }
    }
}
```

== Also in:
* Ref-returning properties and indexers. (must not have setters)
* Ref-returning lambdas

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @jaredpar @khyperia @gafter @agocke @MadsTorgersen

**Comment by VSadov** [comment]
Most of the credit for the original coding of the prototype goes to @pgavlin

**Comment by VSadov** [comment]
@dotnet-bot test this please

**Comment by VSadov** [comment]
@dotnet-bot retest this please

**Comment by VSadov** [comment]
CC @stephentoub

**Comment by whoisj** [comment]
:dancers: `List<T> where T : struct` without the need for boxing. :dancers:

**Comment by pgavlin** [comment]
One other rule that is important to mention:
- member accesses (fields, properites, and calls) are only safe to return by reference if the receiver of the member access expression is also safe to return by reference

So the following will not compile:
```
struct S
{
    public int Integer;
}

class C
{
    static ref int RefToField(S s)

}
```

**Comment by VSadov** [comment]
@pgavlin - Thanks. I forgot about the recursive rule about struct fields. It is kind of follows from the first "on the heap" rule, but may not be immediately obvious.

**Pull request merged**
