### PR TITLE
Fixes for scripting tests in Mono

### PR DESCRIPTION
**Pull request by esdrubal**
This fixes tests that do not pass in Mono except those that require GAC and

Roslyn.Services.UnitTests.MetadataShadowCopyProviderTests.Modules [#33007](https://bugzilla.xamarin.com/show_bug.cgi?id=33007)
Microsoft.CodeAnalysis.Scripting.CSharp.UnitTests.InteractiveSessionTests.AssemblyResolution [#32966](https://bugzilla.xamarin.com/show_bug.cgi?id=32966)

### CODE REVIEW

**Comment by davkean** [comment]
Can one of the @dotnet/interactive team members look at this?

**Comment by tmat** [comment]
Further work in this area is blocked on #7770.

**Comment by sharwell** [comment]
@tmat The blocking bug is now closed. Can you re-evaluate the state of this PR?

**Comment by jaredpar** [comment]
We apologize, but we are closing this PR due to code drift. We regret letting this PR go so long without attention, but at this point the code base has changed too much for us to revisit older PRs. Going forward, we will manage PRs better under an SLA currently under draft in issue #26266 – we encourage you to add comments to that draft as you see fit.   Although that SLA is still in draft form, we nevertheless want to move forward with the identification of older PRs to give contributors as much early notice as possible to review and update them.

If you are interested in pursuing this PR, please reset it against the head of master and we will reopen it. Thank you!

**Comment by akoeplinger** [comment]
I've quickly checked the PR and the fixes are either already upstreamed or no longer required :)

**Pull request closed without merging**
