### PR TITLE
Add stackalloc in nested contexts to the feature status doc.

### PR DESCRIPTION
**Pull request by gafter**

### CODE REVIEW

**Comment by jcouv** [comment]
Tagging @jaredpar to assign "Reviewer" role.
LGTM otherwise. Thanks

**Comment by gafter** [comment]
test windows_release_unit64_prtest please

**Comment by gafter** [comment]
@jcouv Can you please formally approve so I can merge?

**Comment by jcouv** [comment]
Done. Sorry about that

**Pull request merged**
