### PR TITLE
Merge features/function pointers to master

### PR DESCRIPTION
**Pull request by 333fred**

### CODE REVIEW

**Comment by 333fred** [comment]
@jaredpar for approval to merge to master.

**Comment by jaredpar** [comment]
YES!!!!

**Comment by shaggygi** [comment]
@jaredpar do you know if there will be a blog released or a markup we can read to learn about this feature? thx

**Comment by mt89vein** [comment]
@shaggygi https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md

**Pull request merged**
