### PR TITLE
Assert if we make a blocking wait on a threadpool thread.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Assert if we make a blocking wait on a threadpool thread.

Blocking threadpool threads is bad news.  It leads to threadpool starvation, which then can lead to the UI thread blocking while it waits for some BG work to finish.  That BG work may take *ages* until it finally runs as we starve the threadpool and continually have to spin up new threads to process the work.

This change adds a debug assert that we're not blocking a threadpool thread with .WaitAndGetResult.  Adding this caused (unsurprisingly) massive amounts of failures, and many codepaths had some way they would end up blocking a threadpool thread.

I've addressed almost all the cases that triggered.  And i've judiciously allowed two exceptions to go through. These exceptions (the Workspace and Formatting) are only temporary, and i will continue working to eliminate blocking here with future PRs.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide Please review this asap.  This is a PITA PR to keep merging things into.  So i'd like to get this in tomorrow if possible :)

Also, i highly recommend reading one review at a time.

Thanks!

**Comment by jmarolf** [comment]
:+1: for when this merge/rebase business is all sorted

**Comment by jasonmalinowski** [comment]
Since GitHub can't show the full review, I'm giving comments here:

In src/Compilers/Core/CodeAnalysisTest/Diagnostics/SuppressMessageAttributeTests.cs:

* There's a return Task.FromResult(false) that could be some .Default specialized task. The false made me think Verify returns a boolean.

In src/EditorFeatures/CSharpTest/CodeActions/EncapsulateField/EncapsulateFieldTests.cs:
In src/EditorFeatures/CSharpTest/CodeActions/GenerateDefaultConstructors/GenerateDefaultConstructorsTests.cs:
In src/EditorFeatures/CSharpTest/CodeActions/GenerateFromMembers/GenerateConstructor/GenerateConstructorTests.cs:
In src/EditorFeatures/CSharpTest/CodeActions/GenerateFromMembers/GenerateEqualsAndGetHashCode/GenerateEqualsAndGetHashCodeTests.cs
In src/EditorFeatures/CSharpTest/CodeActions/InlineTemporary/InlineTemporaryTests.cs:
In src/EditorFeatures/CSharpTest/Diagnostics/AddUsing/AddUsingTests.cs:

* These regained WpfFact. Intentional?

In src/EditorFeatures/CSharpTest/Completion/CompletionProviders/AbstractCSharpCompletionProviderTests.cs:

* There's a blank space before the (). :-)

In src/EditorFeatures/Test/CodeGeneration/CodeGenerationTests.CSharp.cs:

* We are asserting that the method call throws AggregateException. That is very wrong.

In src/EditorFeatures/VisualBasicTest/Diagnostics/SimplifyTypeNames/SimplifyTypeNamesTests.vb:

* Contents within the XML literals changed:
```
	     ''' &lt;/Code&gt;
	-        Public Sub testscenarios()
	+        Public Async Function Testtestscenarios() As Task
	         End Sub
```

In src/Features/Core/Portable/CodeFixes/Suppression/AbstractSuppressionCodeFixProvider.RemoveSuppressionCodeAction_Pragma.cs:

We have some private methods that now return Task and only return Task.FromResult()

**Comment by jasonmalinowski** [comment]
:+1:. Thanks for doing this. Are we going to get some bugs tracking the more egregious violators that are calling the new API?

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Pull request merged**
