### PR TITLE
Remove misleading default value for TodoCommentOptions.TokenList

### PR DESCRIPTION
**Pull request by sharwell**
This change removes the default value from `TodoCommentOptions.TokenList`. The previous default value was problematic in two ways:

1. When the default value was used, the solution crawler would compute a bunch of data for documents which would be discarded later when the true value was loaded
2. The default value allowed bugs like [this](https://developercommunity.visualstudio.com/t/custom-task-list-tokens-no-longer-working-in-vs-20/1041405) to be hidden for a long time, since it was difficult to tell when the correct value was used compared to a default that was "close" to correct (for some users)

A fast path was added to reduce the amount of work performed by the solution crawler if it runs with a defaulted option.

⚠️ This change is going to make it very obvious that we have a severe bug in OOP options synchronization. In 100% of cases I tested, TODO comments are using the default value and not the value set by users.

### CODE REVIEW

**Comment by tmat** [comment]
@CyrusNajmabadi

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by sharwell** [comment]
@CyrusNajmabadi planning to merge this after we figure out how to make it work properly so we don't wreak the world 😄

**Comment by CyrusNajmabadi** [comment]
Can we merge it asking with a fix to the underlying issue?  Do we know why the option here isn't serializing properly to oop?

**Comment by sharwell** [comment]
This is ready to merge once #52335 merges.

**Pull request merged**
