### PR TITLE
Use the correct option for splitting comments

### LINKED ISSUE #62362: Two UI checkboxes are tied to a single option
https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs#L118

https://github.com/dotnet/roslyn/blob/8fd033cd948a2eb33e4af650b7a1b3dd18e914d2/src/VisualStudio/CSharp/Impl/Options/AdvancedOptionPageControl.xaml.cs#L124

### PR DESCRIPTION
**Pull request by Youssef1313**
Part of #62362, pending test.

### CODE REVIEW

**Comment by mavasani** [comment]
Do you plan to add a test for it once your other PR that adds tests for these controls gets merged?

**Review by mavasani — APPROVED** [review]

**Review by tmat — APPROVED** [review]

**Comment by Youssef1313** [comment]
Yes sure, let's keep the issue open to track adding the test.

**Comment by Youssef1313** [comment]
@mavasani Is this ready to merge?

**Comment by Youssef1313** [comment]
Also reported in https://github.com/dotnet/roslyn/issues/63309.

Ping @mavasani @tmat

**Pull request merged**
