### PR TITLE
No blank line indentation

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/33989.  That PR shoudl be reviewed and merged first.

This gets rid of the separate IBlankLineIndentation concept now that we can have a single service that just does the right thing in all cases.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell

**Comment by CyrusNajmabadi** [comment]
closing

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani @jasonmalinowski .  This is ready to review.  I recommend turning off whitespace diffs.

This removes an ugly wart added a while back.

Specifically, it used to be possible for the IIndentationService to 'fail' and not know how to compute indentation for a particular line.  This means features couldn't depend on it or this purpose.  So we added in the non-failing GetBlankLineIndentation that they could use.  After a series of refactoring, all indentation logic has been merged into the IIndetationService impls, and it is now the case that GetIdentation cannot fail.  So we can remove this entrypoint and migrate everyone onto this form.

**Comment by CyrusNajmabadi** [comment]
After this is merged, i'll also be able to move a few features that were editor-layer specific to be feature-layer specific.

**Comment by CyrusNajmabadi** [comment]
@heejaechang @mavasani @jasonmalinowski any of you able to take a look?  It would be great to have this in before the 4th as there are several other followup PRs i want to make based on this.  Thanks!

**Comment by CyrusNajmabadi** [comment]
@heejaechang @mavasani @jasonmalinowski any of you able to take a look? It would be great to have this in as there are several other followup PRs i want to make based on this. Thanks!

**Comment by heejaechang** [comment]
so, the blank line indentation and regular indentation service seems to used to do 2 separate things. blank line indentation assumes current line is empty even if there is something in current line, and the other one, GetIndentation, always consider current context.

it looks like now indentation service's behavior is changed so that it always assume the context.

ex) Console.WriteLine(
           "hello" + <= enter here
                     | <= used to set caret here (1 indentation more) for blank line

now, it is changed 
      Console.WriteLine(
           "hello" + <= enter here
           | <= here

previously, that was only if user did 
      Console.WriteLine(
           "hello", | <= hit enter here "hello2"

then, we would put caret at
      Console.WriteLine(
           "hello", 
           | "hello2" <= align caret with "hello"

whether existing behavior was following our indentation behavior of pre-Roslyn. 

not sure whether any one care or knew the existing behavior.

**Comment by CyrusNajmabadi** [comment]
> so, the blank line indentation and regular indentation service seems to used to do 2 separate things.

Right.  'blank line indentation' was a hack to try to deal with not being able to actually get indentation in all scenarios.  It was written literally for just a couple of features to use (like the "hit enter in a string") feature, where we previously had the problem that we otherwise would have to deal with the failure case of hte normal IndentationService.

now that the IndentationService works in 100% of cases, i no longer want the IBlankLineIndentation hack.  And, very importantly, i want the behavior to always match normal indentation.  Any deviations were unintentional and only there because the indentation code was scattered around in different place (which the previous PRs unified). 

Thanks! :)

**Comment by CyrusNajmabadi** [comment]
Basically, for all the existing clients of hte BlankLineIndentation we wanted the behavior to be "whatever the user experiences as the actual indentation in the IDE".  But we couldn't actually get that, so this was our poor approximation that worked "good enough" for the few places where a feature had to care aobut indentation.

Now, we can literally just use the real service as the real "source of truth", which is what all these features have wanted.

**Comment by CyrusNajmabadi** [comment]
> behavior, unless someone want us to keep old behavior, I am fine with new behavior as well.

So i wrote the BlankLineIndentation stuff, and 100% of the consumers of it :)   I 100% want the behavior where there is just one consistent calculation for indentation and consumers can trust they're getting that behavior.  

Feel free to merge in.  Thanks!

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @jasonmalinowski  This has gotten an LGTM by @heejaechang, and the behavior is what i would like it to be (since i wrote all the consumers of the original API).  Can you merge in?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
