### PR TITLE
Remove Logger and RoslynCompilerEventSource

### PR DESCRIPTION
**Pull request by pharring**
Remove the Logger and ETW event source from the compiler layer. Addresses #1007

### CODE REVIEW

**Comment by pharring** [comment]
@agocke @heejaechang Please review. This should be simple, it's just deleting code :-)

**Comment by agocke** [comment]
LGTM, thanks for taking this one!

**Comment by agocke** [comment]
FYI, this change is way easier to review if you add &w=1 to your URL -- it'll hide the whitespace changes.

**Comment by heejaechang** [comment]
adding @shyamnamboodiripad

**Comment by heejaechang** [comment]
looks good to me.

...

so, I guess compiler doesnt need etw for perf investigation at all? I find it quite useful when trying to improve perf of feature.

I used it to improve FAR, HR, formatting engine, tagger and more. basically it let me see sequence of all events and time each pipe line took.

**Comment by VSadov** [comment]
LGTM

**Comment by shyamnamboodiripad** [comment]
LGTM. Its sad that we had to remove the logger code entirely - but I guess we can always bring this back if we need to.

**Comment by agocke** [comment]
@shyamnamboodiripad @heejaechang This is why we have version control :) All this code is a revert away (if we really want it).

**Comment by shyamnamboodiripad** [comment]
:+1:

**Pull request merged**
