### PR TITLE
Add scripts to verify if a branch is ready to review

### PR DESCRIPTION
**Pull request by jmarolf**
Add a script (`Verify.cmd` on windows and `verify.sh` on *nix) that can be run so a contributor can check if there are any obvious errors in their branch.

### CODE REVIEW

**Comment by JoeRobich** [comment]
Does this report formatting errors?

**Review by davidwengier — APPROVED** [review]
I used to type `./build.cmd -a` and now I can type `./verify.cmd` which is 2 characters less, so I am very grateful for the productivity boost here 😁

**Comment by jmarolf** [comment]
> Does this report formatting errors?

IDE errors are enforced when we run analyzer right? let me check

**Comment by jmarolf** [comment]
confirmed working:
image

**Pull request merged**
