### PR TITLE
EnsureNonNullTypesAttributeExists not called for NoPIA

### PR DESCRIPTION
**Pull request by cston**
### Customer scenario

The C# compiler will throw a `KeyNotFoundException` when emitting an assembly that requires embedded types (when the assembly references linked assemblies for NoPIA) when the `#nullable` feature is enabled.

### Bugs this fixes

No bug filed.

### Workarounds, if any

Avoid using `#nullable` feature.

### Risk

Low.

### Performance impact

None.

### Is this a regression from a previous update?

The is a bug in the `#nullable` feature which is new for this update.

### How was the bug found?

Found by @AlekseyTs during code inspection.

VSO Bug: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/718176

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @AlekseyTs, please review.

**Comment by cston** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
approved

**Comment by AlekseyTs** [comment]
Test windows_debug_unit32_prtest please

**Pull request merged**
