### PR TITLE
Notify the remote workspace of working folder paths in the background

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This pulls a .Wait() call off the UI thread in solution load scenarios, since it's not urgent that we notify the OOP process about the working folder path. We still ensure the unregister/register ordering is maintained by ordering the Tasks, and if we have to synchronously shut down the remote persistent storage, we will still wait. That is a rarer gesture (it happens on solution rename) and is something we can address if that's needed.

<details><summary>Ask Mode template</summary>

### Customer scenario

Opening a solution potentially causes a UI delay when we initialize our OOP workspace.

### Bugs this fixes

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/526065

### Workarounds, if any

Don't use OOP, but that only makes performance even worse.

### Risk

Low; we are just moving to the background a piece of initialization that didn't need to happen on the UI thread. We've carefully ensured that ordering of the OOP process is still maintained, and a .Wait() in a much rarer situation (solution rename) is maintained since that was the original reason this code was added. This is a standard pattern across our codebase.

### Performance impact

Much better: a multi-second UI delay doesn't exist anymore. Since we've outright gotten rid of the .Wait() in the common codepath, this is good.

### Is this a regression from a previous update?

Not from 15.5. It might have been introduced in 15.5 but the exact timing is difficult; the bug is sensitive to other code running first and is highly asynchronous.

### Root cause analysis

This happens because we had the UI thread of VS blocked while we did a call to the background worker process. The background worker process sometimes could handle the request immediately, but sometimes was blocked as it was still loading. There is some timing effects here, as a faster machine or different order of operations might mean the background work would have completed sooner and thus it wouldn't have been blocked at all.

This is something really caught best by UI Delay telemetry; longer term we are also refactoring this code heavily to make all sorts of performance improvements.

### How was the bug found?

UI Delay telemetry.

</details>

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@Pilchie Chatting with @heejaechang, no. The reason for the Wait() was more to make sure that in the solution rename case, things had gotten pushed. It's entirely normal for us to not have persistence service stuff there (it's something everything has to be resilient for), and our other theory is that if the OOP process is so backed up that it can't service this, it's not servicing anything else either.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
@jinujoseph @Pilchie @MattGertz I've done the testing on this and am happy with it. Ask mode template is filled out. I'm starting an overnight run to get RPS numbers and share bits for extra testing, but otherwise this is ready to take to shiproom.

**Comment by jinujoseph** [comment]
cc @sharwell for review and info

**Comment by natidea** [comment]
Approved to merge via https://devdiv.visualstudio.com/DevDiv/_workitems/edit/526065

**Comment by jinujoseph** [comment]
Pending RPS validation

**Comment by jasonmalinowski** [comment]
RPS passed, so we're good here.

**Pull request merged**
