### PR TITLE
Results of running https://github.com/dotnet/roslyn-analyzers/pull/4647

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@CyrusNajmabadi Consider providing descriptive title for the PR and detailed enough description. 
Also, since this looks like an automated change, please confirm that you manually reviewed all the changes made by the tool.

**Comment by CyrusNajmabadi** [comment]
> please confirm that you manually reviewed all the changes made by the tool.

Confirmed. I manually reviewed all the changes. 

That said, this wasn't intended to touch the compiler layer. That only happened due to linked files. I'll revert those. Sorry!

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Consider providing descriptive title for the PR and detailed enough description.

Sorry, this was intended just for ide review. I'll remove the affected compiler files and you can ignore this pr.

**Review by davidwengier — APPROVED** [review]
As a fan of the style cop rule, I like this.

**Pull request merged**
