### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160202-160026
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160202-160026 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/3315/
// Retest reason: build timeout

**Comment by davkean** [comment]
All Windows jobs probably failed due to [duplicate symbols in the API file](https://github.com/dotnet/roslyn-analyzers/issues/829).

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
retest vsi please

**Comment by jmarolf** [comment]
test vsi please

**Pull request merged**
