### PR TITLE
Update to System.Reflection.Metadata alpha-00012

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar

**Comment by jaredpar** [comment]
Does this have the fix for the boolean read issue?

**Comment by tmat** [comment]
Yes. Verifying that it works E2E.

**Comment by tmat** [comment]
@jaredpar Build doesn't work. The dependency on immutable v37 got into the metadata branch somwhow. We need to first do this: https://github.com/dotnet/corefx/pull/2755

**Comment by jaredpar** [comment]
@tmat is there a reason we couldn't update to immutable v37 with this PR?

**Comment by jaredpar** [comment]
Looks like we're using 11 now, how did we get a signed binary produced so quickly?  

Also confused why we can't just move both references forward now.

**Comment by tmat** [comment]
@jaredpar 
I have updated this upfront ... waiting for the signed build to go thru.

We'd need to update binding redirects in VS. We can do that, but requires updating binding redirects.

**Comment by tmat** [comment]
For some reason the build didn't pick up the version change. So trying again with v12.

**Comment by jaredpar** [comment]
@tmat I thought we had already updated the binding redirects for both Sys.Col.Immutable and Sys.Reflection.Medata.

**Comment by tmat** [comment]
Done.

**Pull request merged**
