### PR TITLE
Upgrade to NuGet to 3.4.0.665 to fix #9159

### LINKED ISSUE #9159: Flaky Build: Nuget Roslyn Restore Failed
http://dotnet-ci.cloudapp.net/job/roslyn-internal_prtest_win_dbg_unit32/647/console

```
16:35:36 Restoring packages: RoslynBuildAndTest
16:35:38 Restoring packages: Templates
16:35:55 Restoring packages: Toolsets
16:37:56 WARNING: Dependency specified was Microsoft.Build.Mono.Debug (ò 14.1.0-prerelease) but ended up with Microsoft.Build.Mono.Debug 14.1.0.
16:37:56 WARNING: Dependency specified was Microsoft.Build.Mono.Debug (ò 14.1.0-prerelease) but ended up with Microsoft.Build.Mono.Debug 14.1.0.
16:37:56 Restoring packages: Samples
16:38:07 Restoring packages: Roslyn (this may take some time)
16:41:12 A task was canceled.
16:41:12 Restore failed with ERRORLEVEL 1
16:41:12 Restore failed with ERRORLEVEL 1
16:41:12 Build failed with ERRORLEVEL 1
```

May be a network issue

### PR DESCRIPTION
**Pull request by davkean**
FIxes #9159.

### CODE REVIEW

**Comment by davkean** [comment]
test vsi please

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @dotnet/roslyn-ide

**Comment by natidea** [comment]
:+1:

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/vsi/p1 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/348/
// Retest reason: https://github.com/dotnet/roslyn/issues/9241

**Pull request merged**
