### PR TITLE
Run codeformatter on our code.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Right now it is annoying to try to keep code formatted properly. You can't run the code formatter after making your own changes, because too much code gets affected.  So i'm running the formatter once to get our code in good shape.  That way it's easy to just run the code formatter after every personal change to only affect the code that you actually wrote.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
tagging @jaredpar

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-compiler

**Comment by TyOverby** [comment]
I think we should hold off on this until Colby's "code formatting as a service" gets up and running so that we are able to stay on top of things.  Otherwise we'll just need to re-run this every few months to catch people forgetting to do formatting on their PRs.

**Comment by CyrusNajmabadi** [comment]
@TyOverby What is the harm running this now?

> Otherwise we'll just need to re-run this every few months to catch people forgetting to do formatting on their PRs.

That seems ok.  I'm not seeing why that's a bad thing. 

In the meantime, it's hard to make code properly follow formatting because if you run the codeformatter now your code has 2000 extra lines of changes along with  it.

**Comment by TyOverby** [comment]
I'm only wary because of how much harder it makes using `git blame`.  That said, a lot of these changes are either whitespace-only which can be ignored by git-blame or they are signature changes which are rarely useful to blame anyway.

**Comment by jaredpar** [comment]
:+1: 

Thanks for doing this.  I've been lax in my duties of running this regularly.

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3583/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/3466/
// Retest reason: slave went offline.

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler  Can i get a second sign off?  Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3627/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3594/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3627/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit64 please

**Pull request merged**
