### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by genlu**

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by genlu** [comment]
test vsi please.

**Comment by heejaechang** [comment]
@genlu when this will be checked in? I am blocked by it for today code flow.

**Comment by heejaechang** [comment]
both known issues.

https://github.com/dotnet/roslyn/issues/9556
https://github.com/dotnet/roslyn/issues/9557

**Comment by heejaechang** [comment]
:+1:

**Comment by heejaechang** [comment]
checking this in so that we can proceed with today code flow.

**Pull request merged**
