### PR TITLE
Add target framework 'netcoreapp3.0' or replace target framework 'netcoreapp2.1' with 'netcoreapp3.0' when adding is not possible

### PR DESCRIPTION
**Pull request by joperator**
I've tried to build [dotnet/source-build](https://github.com/dotnet/source-build) which uses [dotnet/roslyn](https://github.com/dotnet/roslyn) on FreeBSD with a bootstrap CLI. Building `SoureBuild.sln` failed because it targets `netcoreapp2.1` on FreeBSD, which is not supported by the bootstrap CLI. Therefore, I've applied the patches mentioned in [dotnet/source-build#1139](https://github.com/dotnet/source-build/issues/1139#issuecomment-518646067) to build it on FreeBSD. To avoid destroying the build on other platforms, I've changed the target framework in the whole project to `netcoreapp3.0`, which is also a future goal, I think.
cc: @wfurt

### CODE REVIEW

**Comment by jaredpar** [comment]
Let me try and elaborate a bit more here. At the moment the compilers ship to a number of different products: .NET SDK 2.2, .NET SDK 3.0, some internal teams, MS.Net.Compiliers.Toolset NuPkg, etc ... Many of these environments continue to use a 2.1 runtime as this is the latest RTM version. 

I don't expect them all to update to 3.0 until probably several months after we've shipped 3.0. Even then we'll need to work with various partner teams to ensure they have switched over to netcoreapp3.0 before we can full sale update the product. 

> Building SoureBuild.sln failed because it targets netcoreapp2.1 on FreeBSD, which is not supported by the bootstrap CLI

That seems odd. The bootstrap CLI should indeed support targeting netcoreapp2.1 at build time. After all we  currently participate in source build and this is how our project is setup. Is the problem that the executable's won't run because the runtime.json file lists netcoreapp2.1 and roll forward is disabled? If so then just update the roll forward property to get the compilers to execute.

**Comment by wfurt** [comment]
What do we do for ARM64 @jaredpar ? There is no 2.1 AFAIK?

**Comment by jaredpar** [comment]
@wfurt 

> There is no 2.1 AFAIK?

Target or runtime?

**Comment by jaredpar** [comment]
According to the source build repository ARM support isn't expected yet https://github.com/dotnet/source-build/issues/750#issuecomment-519618485

**Comment by joperator** [comment]
You're right @jaredpar:
> The bootstrap CLI should indeed support targeting netcoreapp2.1 at build time.

But it doesn't. Building a simple console app that targets `netcoreapp2.1` with the bootstrap CLI leads to `error NETSDK1065: Cannot find app host for freebsd-x64. freebsd-x64 could be an invalid runtime identifier (RID). For more information about RID, see https://aka.ms/rid-catalog.` If the console app targets `netcoreapp3.0`, it can be built with the bootstrap CLI. I've already mentioned a similar problem in [dotnet/cli#11262](https://github.com/dotnet/cli/issues/11262).

If it's really planned
> to update to 3.0 until probably several months after we've shipped 3.0

this would likely delay the development of .NET Core for FreeBSD until next year. So what about targeting `netcoreapp2.1` and `netcoreapp3.0` side by side everywhere in the project? This would allow to continue working on .NET Core for FreeBSD and also to facilitate the planned transition to `netcoreapp3.0` in the future, as the various partner teams can decide on their own when to switch to `netcoreapp3.0`. Would that be okay @jaredpar?

**Pull request closed without merging**
