### PR TITLE
Allowing multiple exposed line spans in VS style options preview

### LINKED ISSUE #25573: Bad highlighting in VS style options preview
Go to code style options in C# and select "Prefere local function over anonymous function".
Expected behavior when clicking on the pieces of code:
highlighting2

actual behavior:
highlighting1

Similar highlighting issues happen with most other options that have the Prefer... Over form.

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25573

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This is great.  thanks!

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jinujoe

**Comment by Neme12** [comment]
@CyrusNajmabadi  I think you meant @jinujoseph ?

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
@jinujoseph Is this something that could get accepted for the IDE or is this too insignificant?

**Comment by jinujoseph** [comment]
Every little improvement counts and i like this !! 
Adding @sharwell , @Pilchie , @kuhlenh  if they think otherwise

**Comment by Pilchie** [comment]
We can definitely take this in `master` (for 15.8).  Definitely appreciate every little bit of love and polish we can get, even if we don't have time to fix them all ourselves!

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
@jinujoseph Good to merge?

**Comment by jinujoseph** [comment]
thanks @Neme12

**Pull request merged**
