### PR TITLE
Reference latest VS binaries so we can consume them in our features.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide @paulvanbrenk @vladima 

THis is the PR rebased against preview-5.  This is in case we want to take this work for Preview5.

**Comment by paulvanbrenk** [comment]
LGTM

**Comment by Pilchie** [comment]
Tagging @MattGertz for approval.

We discussed taking this next week if we needed any TS/JS updates for it.  @paulvanbrenk are you happy with it going in today in it's current form?

**Comment by CyrusNajmabadi** [comment]
Closed side is here: https://github.com/dotnet/roslyn-internal/pull/1288

**Comment by MattGertz** [comment]
Approved pending the usual, but we can defer to Escrow if others need more time.

**Comment by paulvanbrenk** [comment]
👍

**Comment by CyrusNajmabadi** [comment]
retest windows_eta_open_prtest  please

**Pull request merged**
