### PR TITLE
Guard against being passed bad symbols or expressions

### PR DESCRIPTION
**Pull request by jmarolf**
No repo case to write tests against, however we do have a callstack.

Fixes https://github.com/dotnet/roslyn/issues/6682

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide

**Comment by jmarolf** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2358/
// Retest reason: flaky test

**Comment by jmarolf** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2382/
// Retest reason: flaky Microsoft.CodeAnalysis.Scripting.Desktop.UnitTests

**Comment by jasonmalinowski** [comment]
Given we've hit plenty of repros internally and externally, should we instead consider making this more actionable to figure out which thing is actually null?

**Comment by amcasey** [comment]
FYI we appear to have had 12 million NFWs for this exception in the last 10 days.

**Comment by Pilchie** [comment]
I'm sort of with @jasonmalinowski on this one.  Maybe we should turn those conditions into a failfast, dogfood for a bit and hope that someone hits it.

**Pull request merged**
