### PR TITLE
Add 'use var when explicit' as a new option for when 'var' is allowed.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/29657

1. Followup to https://github.com/dotnet/roslyn/pull/33647.  This will be easier to review if that goes in.
2. There's a large amount of diff here due to resource files switchin from tabs to spaces.  not sure what's up with that.

## Description

This PR stems from several pieces of feedback we've gotten over time about how "use var when type is apparent" is a bit too broad for some people's tastes.

Specifically, "when apparent" has a couple of cases that are a little too broad for people.  For example, 'when apparent' supports this case:

```c#
var v = x.ToString();
```

The feeling here was that a `ToXXX` method made it apparent-enough that the type on the left would be `XXX`.  However, this was unpleasant for some as it's a very tenuous connection, with `XXX` not actually appearing on the RHS as an actual type.

In a similar vein, "when apparent" was not strict about generics.  if you had, for example:

```c#
var arr = ImmutableArray.Create(1, 2, 3);
```

It would consider this an apparent enough match since the type on the left and the right are both `ImmutableArray` in terms of their name.  However, the type on the left is `ImmutableArray<int>` and the lack of `int` on the RHS made this unpalatable for people.

Finally, there were common method invocation patterns not detected.  For example:

```c#
var logger = component.GetService<ILogger>();
```

In this case, people felt that this was an apparent use of ILogger and should fall under that category.

in this PR we now add a new editorconfig option `csharp_style_var_when_type_is_explicit`.  The meaning is similar to `csharp_style_var_when_type_is_apparent` except that it's now a requirement that the actual type show up in an appropriate location in syntax on the RHS.  The allowed syntax locations are:

1. `= default(SomeType)`
2. `= new SomeType(...)`
3. `= new SomeType[...] { ... }`
4. `= ... as SomeType`
5. `= (SomeType)...`
6. `= Foo<SomeType>(...)` (Foo has to return `SomeType`).
7. `= SomeType.FactoryMethod(...)` (FactoryMethod has to return `SomeType`).

## Design questions

Note: there is an open design question around a few cases.

1. tuples.  i.e. if you have:

```c#
var v = (default(SomeType), default(SomeOtherType);
```

Is the type of 'v' considered 'explicit'?  I personally think so.  It's clearly `(SomeType, SomeOtherType)` from very obvious syntax.  However, i could see some debate here, so i bring this up in case we want to consider that non-explicit.

2. There are certain C# constructs that are completely clear about what type they are, even if the type is not stated.  for example `var v = x is Y`.  'bool' here has the type `bool`.  But `bool` was never stated explicit.  Do we care about this sort of case?  Probably not IMO. It's pretty reasonable that `explicit` means `stated as type` or `stated as type within a large type syntax` (like the tuple case).  

3. Sometimes a type can be semi-explicit in code in something like `ImmutableArray.Create<int>(...)`.  Here, both `ImmutableArray` and `<int>` are specified.  So one might see that as explicit-enough to indicate that it is `ImmutableArray<int>`.

## UI 

To help make the concept understandable, here's the UI:

image

image

## TODO

- [ ] Needs tests.  Especially around the interaction between apparent/explicit.  We need tests for all four permutations of that.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @sharwell

**Comment by CyrusNajmabadi** [comment]
I have opened a discussion [here](https://github.com/dotnet/roslyn/issues/29657#issuecomment-466882204) about several of hte design questions.  If you are a person who strongly feels that 'var' is only ok if the type is totally clear from the RHS, then i ask that you go weigh in and give feedback on these cases.  I'm curious in each case if you feel that 'var' would be appropriate or not.

**Comment by CyrusNajmabadi** [comment]
closing

**Comment by CyrusNajmabadi** [comment]
Opening.  @sharwell can you take this to an IDE design meeting plz?

**Comment by CyrusNajmabadi** [comment]
@sharwell What would it take to move forward with this?  Thanks!

**Comment by CyrusNajmabadi** [comment]
@dpoeschl What does "Next meeting to Need Update" mean?  Thanks!

**Comment by dpoeschl** [comment]
@CyrusNajmabadi It means that we discussed it and somebody will post the results of that discussion soon (not sure what the SLA is on that). FYI @mikadumont @sharwell

**Comment by sharwell** [comment]
Design review conclusion: this pull request introduces a permanent option to work around one specific design limitation of a feature. We decided to table this discussion until we can evaluate the complete scenario, in particular in combination with the new diagnostic suppression APIs that are coming in 16.3. We will reconsider the explicit/implicit type feature as a whole during work to migrate the analyzer from an IDE analyzer to a NuGet package.

**Comment by sharwell** [comment]
For now, this is **Won't Fix**, although it will likely be an input to future work in this space.

**Pull request closed without merging**
