### PR TITLE
Merge features/ide-cleanup back into master

### PR DESCRIPTION
**Pull request by mavasani**
Merges all commits from https://github.com/dotnet/roslyn/tree/features/ide-cleanup back into master

### CODE REVIEW

**Comment by mavasani** [comment]
@CyrusNajmabadi - The IDE team has an additional request for you for future cleanup PRs related to code fix application for IDE suggestions: Would it be possible for you to separate out the commits that apply automated FixAll operations from any manual follow-up fixes you have to do on top of them? The latter likely indicate bugs/opportunities for us to improve the code fixers, and it would help us triage and file bugs more easily if these were separate commits.

Thanks again for your contribution in helping us dogfood IDE suggestions and getting us to a cleaner state!

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi - The IDE team has an additional request for you for future cleanup PRs related to code fix application for IDE suggestions: Would it be possible for you to separate out the commits that apply automated code fix/FixAll operations from any manual follow-up fixes you have to do on top of them? The latter likely indicate bugs/opportunities for us to improve the code fixers, and it would help us triage and file bugs more easily if these were separate commits.

Sure.  I normally try to do that.  But i'm not always 100% effective.  Note: there are significant bugs with teh git integration in VS.  I often use it to commit files.  BUt then i discover from the command line that some files are still non-comitted.  I think there's something going on wrt to asynchronously saving the files while a git commit is happening in vs.  As such, sometimes some files that should be part of one commit go into the next.

Can you plz merge?  Thanks!  :)

**Comment by mavasani** [comment]
Thanks @RikkiGibson @CyrusNajmabadi. @jinujoseph mentioned we want to take this change into post dev16.4 branch, so I am going to retarget and then merge when tests pass.

**Pull request merged**
