### PR TITLE
Enable NuGet debugging

### PR DESCRIPTION
**Pull request by jaredpar**
Temporarily enable NuGet debugging to help NuGet team track down a debugging issue.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @jasonmalinowski, @OmarTawfik for review.  This is related to our swat thread about the NuGet error we are frequently seeing:

``` txt
10:08:22 Restoring packages: Toolsets
10:08:24 An error occurred while retrieving package metadata for 'Roslyn.Diagnostics.Analyzers.1.2.0-beta2' from source 'C:\Users\dotnet-bot\.nuget\packages\'.
10:08:24   '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
10:08:24 Restore failed with ERRORLEVEL 1
 ```

**Comment by jaredpar** [comment]
retest this please

**Comment by jaredpar** [comment]
Jenkins was done.  Didn't seem to pick up any of the legs here.  Issued a restart to poke Jenkins.

**Comment by OmarTawfik** [comment]
@jaredpar jenkins is experiencing networking issues preventing it from spinning up new VMs.

**Pull request merged**
