### PR TITLE
fixes #23123

### LINKED ISSUE #23123: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: '(1,8): error CS1503
**Version Used**: 
.Net 4.6.1
VS 2015 w/ Update 3
Nuget Package: Microsoft.CodeAnalysis.CSharp.Scripting V2.4.0

**Steps to Reproduce**:
```
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;

namespace RoslynExperimentation
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new MyClass()
            {
                Description = "test"
            };

            var code = "using RoslynExperimentation;" +
                       "public class TestClass {" +
                       "  public string HelloWorld(MyClass c) {" +
                       "    return c.Description;" +
                       "  }" +
                       "}";

            var metadata = MetadataReference.CreateFromFile(typeof(MyClass).Assembly.Location);

            var scriptTask =
                CSharpScript.Create(
                        code: code,
                        options: ScriptOptions.Default.WithReferences(metadata),
                        globalsType: typeof(Globals))
                    .ContinueWith("new TestClass().HelloWorld(C)")
                    .RunAsync(new Globals { C = c });

            scriptTask.Wait();
            Console.WriteLine(scriptTask.Result.ReturnValue);
        }
    }

    public class MyClass
    {
        public string Description { get; set; }
    }

    public class Globals
    {
        public MyClass C { get; set; }
    }
}
```

**Expected Behavior**:
"test" is written to the Console.

**Actual Behavior**:
Error is thrown when executing .RunAsync

Unhandled Exception: Microsoft.CodeAnalysis.Scripting.CompilationErrorException:
(1,28): error CS1503: Argument 1: cannot convert from 
'RoslynExperimentation.MyClass [D:\Projects2\RoslynExperimentation\RoslynExperimentation\bin\Debug\RoslynExperimentation.exe]' to 
'RoslynExperimentation.MyClass [RoslynExperimentation, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]'

### PR DESCRIPTION
**Pull request by TobiasBreuer**
Opened up this PR with respect to #23123 for further discussion of proposed solution.

### CODE REVIEW

**Comment by TobiasBreuer** [comment]
I just recognized that the CI build fails. Unfortunately I cannot reproduce those failing tests on my machine. I tried some (not all) of them locally and they succeeded - so the failing doesn't seem to be directly related to the change I made. 

Many of the tests within the highlighted set of tests in the screenshot are failing under CI whereas they succeed on my side.
(The 10 tests that are failing in the screenshot are due to OutOfMemoryException of the test runner) 
image

**Comment by jmarolf** [comment]
@TobiasBreuer if you run `restore.cmd && build.cmd && test.cmd` from the commandline do all tests pass on your machine?

**Comment by TobiasBreuer** [comment]
@jmarolf Well - basically yes. There are however two test failing. But this seems to be related to some localized exception message being expected - As one can see, the test expects an english exception message but a german one is given. It is still the same exception only localized:

```
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.Script_NoHostNamespaces [STARTING]
  
  Expected:
  (1,8): error CS0234: The type or namespace name 'Missing' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
  Actual:
  (1,8): error CS0234: Der Typ- oder Namespacename ""Missing"" ist im Namespace ""Microsoft"" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)
  Differences:
  ++> (1,8): error CS0234: Der Typ- oder Namespacename ""Missing"" ist im Namespace ""Microsoft"" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)
  --> (1,8): error CS0234: The type or namespace name 'Missing' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
  
  Expected: True
  Actual:   False
  Stack Trace:
	src\Test\Utilities\Portable\Assert\AssertEx.cs(459,0): at Roslyn.Test.Utilities.AssertEx.AssertEqualToleratingWhitespaceDifferences(String expected, String actual, Boolean escapeQuotes, String expectedValueSourcePath, Int32 expectedValueSourceLine)
	src\Interactive\HostTest\InteractiveHostTests.cs(993,0): at Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.Script_NoHostNamespaces()
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.Script_NoHostNamespaces [FINISHED] Time: 4,4070409s
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.AsyncExecuteFile_SourceKind [STARTING]
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.AsyncExecuteFile_SourceKind [FINISHED] Time: 1,2396034s
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.ExecuteSequentially [STARTING]
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.ExecuteSequentially [FINISHED] Time: 6,6397456s
Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.InitialScript_Error [STARTING]
  
  Expected:
  C:\Users\breuer_to\AppData\Local\Temp\RoslynTests\InteractiveHostTests.cs_922_4aec50e1-db2d-4c34-a328-556905d362a0.csx(1,3): error CS1002: ; expected
  Actual:
  C:\Users\breuer_to\AppData\Local\Temp\RoslynTests\InteractiveHostTests.cs_922_4aec50e1-db2d-4c34-a328-556905d362a0.csx(1,3): error CS1002: ; erwartet.
  Differences:
  ++> C:\Users\breuer_to\AppData\Local\Temp\RoslynTests\InteractiveHostTests.cs_922_4aec50e1-db2d-4c34-a328-556905d362a0.csx(1,3): error CS1002: ; erwartet.
  --> C:\Users\breuer_to\AppData\Local\Temp\RoslynTests\InteractiveHostTests.cs_922_4aec50e1-db2d-4c34-a328-556905d362a0.csx(1,3): error CS1002: ; expected
  
  Expected: True
  Actual:   False
  Stack Trace:
	src\Test\Utilities\Portable\Assert\AssertEx.cs(459,0): at Roslyn.Test.Utilities.AssertEx.AssertEqualToleratingWhitespaceDifferences(String expected, String actual, Boolean escapeQuotes, String expectedValueSourcePath, Int32 expectedValueSourceLine)
	src\Interactive\HostTest\InteractiveHostTests.cs(936,0): at Microsoft.CodeAnalysis.UnitTests.Interactive.InteractiveHostTests.InitialScript_Error()
```
All other tests have been finished successful. I've attached the content of `artifacts/TestResults/Debug` below. If there is anything else I can provide or do please let me know.

[TestResults.zip](https://github.com/dotnet/roslyn/files/2760448/TestResults.zip)

**Comment by jaredpar** [comment]
@TobiasBreuer 

Try the following and see if it reproduces locally:

> & eng/build.ps1 -build -restore -bootstrap -testDesktop

I'm guessing that once you add `-bootstrap` the tests will begin to fail locally. That argument causes the build to first produce a new copy of csc / vbc based on your changes. Then the entire solution is rebuilt with that compiler. Our CI system does this automatically but it's not the default in the day to day developer environment.

**Comment by TobiasBreuer** [comment]
@jaredpar Okay. Thanks for the info. 
I'll do so tomorrow morning and post the result here afterwards.

**Comment by jaredpar** [comment]
@RikkiGibson looks like we have another instance of the DisableSdkPath bug (#32053). 

@TobiasBreuer this bug when building we've seen a few times but been unable to reproduce it locally. Can you also add `-binary` as one of the options and send us the contents of artifacts\Logs?

**Comment by TobiasBreuer** [comment]
@jaredpar @RikkiGibson Please find the archived log files on my [OneDrive](https://1drv.ms/u/s!AiIlPkVNRiCc-XE9xU2U8aCA87Eb).
It is too big to attach it to this PR directly.

**Comment by jaredpar** [comment]
@TobiasBreuer thanks for providing that. Unfortunately that data doesn't make sense. I'm following up with the MSBuild team to see what is going on here.

**Comment by TobiasBreuer** [comment]
@jaredpar Alright. Please let me know if you need any further data or information regarding my system / environment that could help to narrow down the problem.

**Comment by RikkiGibson** [comment]
Rebuilding

**Comment by rchande** [comment]
@jaredpar @RikkiGibson what's happening with this PR?

**Comment by jaredpar** [comment]
@rchande the PR is failing a number of tests and hence can't be merged. Is the UI not showing that on your machine?

**Comment by rchande** [comment]
@jaredpar Wasn't clear to me from reading if the issues were caused by the PR or a build infra issue

**Comment by jaredpar** [comment]
@rchande don't believe so. Looking at the set of tests that fail they have a strong intersection with tests that deal with assembly identity. Given this change altered how assembly identity is calculated I'd guess it's because of this change.

**Comment by jaredpar** [comment]
Firstly I'm sorry that we let this PR get stale on us. I just noticed it today when I was going through our backlog of open PRs. The PR itself seems to be in a bad state and I was looking into just transfering the commit to a new PR. But the discussion on the issue noted that the bug has apparently already been fixed by #38550. 

So for now closing this out. If it turns out that doesn't completely fix the issue I'll get this commit moved to a new PR and help push it through. Again sorry for letting this slip under the radar.

**Pull request closed without merging**
