### PR TITLE
Add System.ValueTuple to vsix deployment

### PR DESCRIPTION
**Pull request by agocke**
This fixes "F5" for VS.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by mmitche** [comment]
@dotnet-bot test this please (testing)

**Comment by mmitche** [comment]
@dotnet-bot test this please (testing)

**Comment by agocke** [comment]
test this please

**Comment by mmitche** [comment]
@agocke Sorry, just working out some kinks from the server move.

**Comment by agocke** [comment]
@mmitche In this case it was me breaking the build :)

**Pull request merged**
