### PR TITLE
Merge telemetry sources into existing projects

### PR DESCRIPTION
**Pull request by Pilchie**
Now that the telemetry API is consumable from OSS and the code is there, no
need to have a dedicated binary + vsix for it.

(requires a closed side change)

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @heejaechang @jaredpar @jmarolf @dotnet/roslyn-infrastructure

**Comment by jaredpar** [comment]
:+1: 

Let me know when this gets merged and I'll kick off an official build to verify this did the trick.

**Comment by jasonmalinowski** [comment]
Should RoslynTelemetrySetup.cs go away now that we probably have easier ways to do that? This would also mean in the F5 scenario against Visual Studio 2015 we'll have this component being loaded twice. Is that OK?

**Comment by jmarolf** [comment]
:+1:

**Comment by jmarolf** [comment]
We should also delete src/Setup/DevDivVsix/MicrosoftCodeAnalysisLanguageServices/MicrosoftCodeAnalysisVisualStudioTelemetry or signed build will fail.

**Comment by Pilchie** [comment]
Thanks @jmarolf done.  @jasonmalinowski Testing the F5 case now.

**Comment by heejaechang** [comment]
:+1:

**Comment by Pilchie** [comment]
@jasonmalinowski F5 is indeed broken, and I think simplifying the telemetrySetup stuff will be part of fixing it.

**Comment by Pilchie** [comment]
Anyone want to take another look?  With the change to remove the InternalsVisibleTo attributes, F5 works, because the old telemetry vsix is not added to the MEF catalog because it can't be loaded.

**Comment by jaredpar** [comment]
I have looked again and :+1: again.

**Pull request merged**
