### PR TITLE
Include accessible private members from outer types in Intellisense [stabilization branch]

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
Customer scenario: Intellisense for derived type nested in base type does not include private members from base type (see #2639). In the EE in particular, Intellisense completes expressions aggressively which makes it difficult to specify members that are not included in the Intellisense list.

Code reviewers (for corresponding change to master https://github.com/dotnet/roslyn/pull/3263): @rchande, @pharring, @jaredpar, @pilchie

**Comment by pharring** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved 6/3 by ML Shiproom.

**Comment by rchande** [comment]
Buddy tested this, LGTM.

**Pull request merged**
