### PR TITLE
Remove special interpolation brace kinds

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
It has been pointed out that these kinds are not necessary and we can reuse existing token kinds here.  This actually fits what we do elsewhere.  For example, with an xml doc comment `List{T}` the `{` and `}` tokens are actually represented as `.LessThanToken` and `.GreaterThanToken`

Relates to test plan https://github.com/dotnet/roslyn/issues/55306

### CODE REVIEW

**Review by RikkiGibson — APPROVED** [review]
Does PublicAPI.txt need updating? Or are warnings there suppressed here until feature is near completion?

**Comment by CyrusNajmabadi** [comment]
> Does PublicAPI.txt need updating? Or are warnings there suppressed here until feature is near completion?

Yup.  It needs fixing.  Have done so now.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Comment by jcouv** [comment]
The correctness leg is still having an issue with publicAPI. It's probably easy enough to fix by hand, but FYI we also have instructions for running the publicAPI fixere [here](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md#running-the-publicapi-fixer).

**Comment by CyrusNajmabadi** [comment]
Thanks!  i think i got it now :)

**Pull request merged**
