### PR TITLE
Remove one of our out of proc analyzers

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Confirmation with owners of this telemetry indicate that this has not actually been helpful (esp. due to limiting data due to data size) and has not been checked in a very long time.  Remove as it now serves no purpose and is actively impeding our goal of removing solution-crawler.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Confirmed with Damien that this is not being used by them anymore.

**Review by tmat — APPROVED** [review]
:shipit:

**Comment by tmat** [comment]
Nice!

**Comment by mavasani** [comment]
Fantastic!

**Pull request merged**
