### PR TITLE
Refactor ClassificationOptions

### PR DESCRIPTION
**Pull request by tmat**
Instead of reading options the classification service needs from solution snapshot pass them to the service as a parameter. This makes it clear which options the service depends on and potentially allows us to reuse the results when unrelated options change.

We should use this pattern for all solution options used by remote services.

### CODE REVIEW

**Comment by tmat** [comment]
@CyrusNajmabadi This implements the options pattern I proposed last time we talked. LMK what you think.

**Review by CyrusNajmabadi — APPROVED** [review]
I like it!  I don't love the name 'definition', but I have no better suggestion.

**Comment by JoeRobich** [comment]
> I don't love the name 'definition', but I have no better suggestion.

The LSP spec has Tokens and TokenModifiers. This seems like a Modifier option, whether to additionally tag an identifier as Reassigned.

**Comment by tmat** [comment]
@CyrusNajmabadi  `Metadata`?

**Comment by CyrusNajmabadi** [comment]
@tmat   yes. I like that better. :-)

**Pull request merged**
