### PR TITLE
Don't offer to transform object creation expressions that are assigned to 'dynamic'.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/17853

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Preemptively merging in.  Let me know if you have any issues you'd like me to resolve.

**Comment by AlgorithmsAreCool** [comment]
So fast!

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi What about VB?

**Pull request merged**
