### PR TITLE
Enable selection of Mef components based on TextViewRole...

### PR DESCRIPTION
**Pull request by KevinH-MS**
We need a way to provide alternate completion in the Interactive Window.
Previously, we weren't taking ```TextViewRole``` into consideration when
selecting completion providers.  This change allows a service to opt in to
considering ```TextViewRole``` by passing ```OrderableLanguageAndRoleMetadata``` to
```SelectMatchingExtensionValues``` .

This change also includes some cleanup of test helpers and extra
```TextViewRole``` attributes that weren't doing anything meaningful.

**Note:**  The main thing driving this change is extra image loads, which could
have been solved by moving the code into the "core" assemblies.  I chose to
keep everything in a separate "Interactive" assembly, because it seems virtuous
to enforce some discipline around extra completion providers, etc being loaded
when they're not applicable.

### CODE REVIEW

**Comment by KevinH-MS** [comment]
Tagging @DustinCampbell @jasonmalinowski for review...

**Comment by KevinH-MS** [comment]
FYI @tmat @cston @amcasey @ManishJayaswal

**Comment by KevinH-MS** [comment]
I'm going to merge this to get updated RPS results, but I will modify based on any feedback.

**Comment by jasonmalinowski** [comment]
Catching up on this -- what was the result? Also, I believe there's agreement just to move everything back in to the main assemblies. Does that work eliminate the need for this?

**Comment by KevinH-MS** [comment]
Functionally, it seems to work splendidly.  If we moved things back to the main assemblies, it would indeed obviate the need for this from an image load perspective.  On the other hand, I kinda feel like we should always respect ```TextViewRole```, so I'd almost be tempted to use this everywhere (or at least everywhere we use ```OrderableLanguageMetadata```).

**Pull request merged**
