### PR TITLE
Adding tests that demonstrate behavior of stackalloc in using-statements

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler .  This is simply the addition of two tests.

**Comment by jaredpar** [comment]
Curious: what was the motivation for adding this?

**Comment by CyrusNajmabadi** [comment]
i was looking at the code that parse stackallocs and trying to reverse engineer all the codepaths it could be called from.  using-statements were one of those codepaths, but i couldn't find tests around that.  using statements are also very strange as we basically allow stackalloc to be parsed there... but afaict, there's no way that you could ever generate legal code.  (if you can come up with an example, def let me know!).

**Comment by CyrusNajmabadi** [comment]
Er... i just merged without two reviewers.  Sorry about that.  Given that these are just test changes, i hope that that's ok.

**Comment by jaredpar** [comment]
We will forgive you ... <ominous voice>this time </ominous voice>

**Pull request merged**
