### PR TITLE
Auto-suggest <paramref names and <typeparamref names

### LINKED ISSUE #11488: Auto-suggest <paramref names, similar to <param
Today I get offered automatically inside completion window to add `<param/>` with the names pre-entered (such as capability below), it would be great to apply this same thing to `<paramref/>`:

image

### PR DESCRIPTION
**Pull request by aochagavia**
The functionality is similar to the current feature implemented for <param

Closes #11488, supersedes https://github.com/dotnet/roslyn/pull/11506

cc @jasonmalinowski

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
And cc @dotnet/roslyn-ide again, since I still think we're needing more signoffs. And @dotnet-bot, test vsi please.

**Comment by jasonmalinowski** [comment]
This conceptually seems fine for me, although I admit I haven't thought through edge cases. :+1: from me. @rchande, any additional thoughts?

**Comment by rchande** [comment]
My main concern would be: what happens when there are lots of parameters and type parameters? Will  people find the long list annoying? I don't really know. 

What happens if you type <paramref name="$$"> and CTRL-J at the $$? I assume we show the names?

**Comment by aochagavia** [comment]
I don't think people will find the long list annoying. You deal with that kind of stuff every time you call methods on collections because of all LINQ extension methods that are suggested as well. I also expect most functions to have a small amount of type parameters and normal parameters.

**Comment by aochagavia** [comment]
> What happens if you type and CTRL-J at the $$? I assume we show the names?

@rchande Yes, as you can see below:

image

**Comment by rchande** [comment]
@aochagavia: This LGTM--do you want to go ahead and make the same change for VB?

**Comment by aochagavia** [comment]
@rchande I would like to, but I have never used VB in my life. I looked at the completion provider for VB and I don't know exactly what to change (it looks different than the C# version, which is understandable since the language has a different syntax).

Maybe you (or someone else) could checkout my `suggest` branch, work on from there and open a PR in my fork to merge it back.

**Comment by lorcanmooney** [comment]
@aochagavia I could probably pick up the VB side of things, if you'd like?

**Comment by aochagavia** [comment]
@lorcanmooney That would be awesome!

**Comment by lorcanmooney** [comment]
I've opened aochagavia#1 to add support for VB.

**Comment by aochagavia** [comment]
Thanks! I just merged it.

@rchande does this look good to you?

**Comment by rchande** [comment]
@aochagavia @lorcanmooney This looks great! Thank you!

Merging this now.

**Pull request merged**
