### PR TITLE
Initial work to clean up lifetime of keyed Code Model elements

### LINKED ISSUE #3313: Clean up Code Model lifetime management
See PR #3286.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #3313

Getting this out for review and running tests. There's plenty more that could be done, but this makes things simpler and removes the terrifying bit of code that is referenced in #3286.

Tagging @dotnet/roslyn-ide

### CODE REVIEW

**Comment by DustinCampbell** [comment]
test vsi please

**Comment by DustinCampbell** [comment]
retest this please

**Comment by DustinCampbell** [comment]
test unit32 please

**Comment by DustinCampbell** [comment]
test vsi please

**Comment by davkean** [comment]
:+1:

**Comment by DustinCampbell** [comment]
test unit32 please

**Pull request merged**
