### PR TITLE
Fix GetDiagnostics(span) to return all diagnostics intersecting the s…

### LINKED ISSUE #3892: Fatal error typing '.' after Parameterized Property invocation
```
Module Module1

    Sub Main()
        Dim row = New DataRow()
        Stop
        Dim test = row.Item("Test Row").
        Dim test2 = row.Foo(42)
    End Sub

    Class DataRow
        Public ReadOnly Property Item(ByVal str As String) As String
            Get
                Return str
            End Get
        End Property
        Public Function Foo(i As Integer) As String
            Return "No!"
        End Function
    End Class

End Module
```
**RESULTS:**
```
Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.Watson.WatsonErrorReport.CheckThrottledSubmission(string componentName) Line 420	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.Watson.WatsonErrorReport.ReportIfNecessary() Line 190	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.WatsonReporter.Report(System.Exception exception) Line 19	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.ErrorReporting.FatalError.Report(System.Exception exception, System.Action<System.Exception> handler) Line 151	C#
>	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.VerifyDiagnostics(Microsoft.CodeAnalysis.SemanticModel model) Line 182	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticCompilerDiagnostics.AnonymousMethod__16_3(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver _1, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer _2) Line 151	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetDocumentDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet stateSet, Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateType stateType, bool supportsSemanticInSpan, System.Func<Microsoft.CodeAnalysis.VersionStamp, Microsoft.CodeAnalysis.VersionStamp, bool> versionCheck, System.Func<Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver, Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer, System.Threading.Tasks.Task<System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData>>> getDiagnostics, Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticAnalyzerDriver analyzerDriverOpt) Line 268	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticCompilerDiagnostics(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet stateSet, Microsoft.CodeAnalysis.VersionStamp textVersion, Microsoft.CodeAnalysis.VersionStamp syntaxVersion, Microsoft.CodeAnalysis.VersionStamp semanticVersion) Line 145	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetSyntaxAndSemanticDiagnosticsAsync(Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.StateSet stateSet, Microsoft.CodeAnalysis.VersionStamp textVersion, Microsoft.CodeAnalysis.VersionStamp syntaxVersion, Microsoft.CodeAnalysis.VersionStamp semanticVersion) Line 118	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.LatestDiagnosticsForSpanGetter.TryGetAsync() Line 76	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.EngineV1.DiagnosticIncrementalAnalyzer.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan range, System.Collections.Generic.List<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> diagnostics, System.Threading.CancellationToken cancellationToken) Line 458	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.IncrementalAnalyzerDelegatee.TryAppendDiagnosticsForSpanAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Text.TextSpan range, System.Collections.Generic.List<Microsoft.CodeAnalysis.Diagnostics.DiagnosticData> diagnostics, System.Threading.CancellationToken cancellationToken) Line 167	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzerService.TryAppendDiagnosticsForSpanAsync.AnonymousMethod__0() Line 123	C#
```

### PR DESCRIPTION
**Pull request by mavasani**
…pan, rather than just the diagnostics contained within the span.

Fixes #3892 and #4559

### CODE REVIEW

**Comment by mavasani** [comment]
@gafter @heejaechang can you please review?

**Comment by gafter** [comment]
LGTM

**Comment by mavasani** [comment]
@dotnet-bot retest win32 please

**Comment by mavasani** [comment]
@dotnet-bot retest win please

**Comment by mavasani** [comment]
All tests pass locally, so merging this in.

**Pull request merged**
