### PR TITLE
Revert project.json changes.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @tmat

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by tmat** [comment]
One more file to revert: src/Debugging/Microsoft.DiaSymReader.PortablePdb/Microsoft.DiaSymReader.PortablePdb.nuspec
That one doesn't use the version variables yet.

Other than that LGTM
:+1: 

Thanks

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
nuspec change made thanks!

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p3_open_prtest  please

**Pull request merged**
