### PR TITLE
Update SRM, SCI to builds with profiling data

### PR DESCRIPTION
**Pull request by tmat**
**Customer scenario**

VS perf regression. Previously inserted version didn't have optimization data.

**Bugs this fixes:** 

289499

**Workarounds, if any**

None.

**Risk**

Small.

**Performance impact**

Fixes perf regression.

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

IBC data were not included in CoreFX 1.1 libraries.

**How was the bug found?**

Internal perf gates.

### CODE REVIEW

**Comment by tmat** [comment]
@KevinH-MS

**Comment by KevinH-MS** [comment]
@tmat did DiaSymReader package not get uploaded?  Was that change also intended to be included?

> Failure to restore a package: Unable to resolve 'Microsoft.DiaSymReader.PortablePdb (>= 1.2.0-beta1-61222-02)' for '.NETFramework,Version=v4.6'.

**Comment by tmat** [comment]
@KevinH-MS It's intended - DiaSymReader also references SRM and SCI, so it needs to be updated too. Not sure why the package is not found. Glitch likely.

**Comment by tmat** [comment]
test windows_release_unit64_prtest  please

**Comment by tmat** [comment]
Requires change in closed: https://github.com/dotnet/roslyn-internal/pull/1466

**Comment by tmat** [comment]
@srivatsn for ask mode approval

**Pull request merged**
