### PR TITLE
Fix serialization of decimals

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/17336

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler

**Comment by CyrusNajmabadi** [comment]
@jcouv @gafter Can you look asap?

**Comment by TyOverby** [comment]
👍

**Comment by CyrusNajmabadi** [comment]
I also looked through the rest of Syntax.Xml to see if there were any other enum cases.  I could not find anything.

**Comment by jaredpar** [comment]
Why didn't we add any tests here?

**Pull request merged**
