### PR TITLE
DryDock Effort: Enabling the skipped test marked with xunit

### PR DESCRIPTION
**Pull request by jinujoseph**
I am not sure why this were skipped, enabling them seems to work.
Not sure if they are flaky in nature. tested in couple of times.
Let me know if there is any reason why this should not be enabled.

@dotnet/roslyn-ide

### CODE REVIEW

**Comment by rchande** [comment]
FWIW, I searched bung for the names of those tests and nothing came up.

**Comment by jasonmalinowski** [comment]
Can we track down why those skips were originally added? That seems very ominous...

**Comment by davkean** [comment]
@Pilchie Disabled them with: https://github.com/dotnet/roslyn/commit/9f200162298546e6d8d44ecc812bb77d4e4e2ebd#diff-fec16974d9743d80a051286f6b890195 but with no bug. :(

**Comment by davkean** [comment]
:+1:

**Pull request merged**
