### PR TITLE
Revert "Rationalize references for Microsoft.Net.Compilers.netcore (#…

### PR DESCRIPTION
**Pull request by rchande**
…14536)"

This reverts commit 6387201902bb2a21abad62212fc41303c2ae1e33 which currently causes a crash in the PCL project system.

### CODE REVIEW

**Comment by rchande** [comment]
cc @dotnet/roslyn-ide @CyrusNajmabadi @agocke

**Comment by rchande** [comment]
@Pilchie Yes

**Comment by agocke** [comment]
@rchande I think we should leave the nuspec changes.

**Comment by rchande** [comment]
@agocke  Done

**Comment by agocke** [comment]
LGTM

**Comment by rchande** [comment]
Looks like windows_debug_unit64_prtest is hung

**Comment by rchande** [comment]
retest windows_debug_unit64_prtest please

**Pull request merged**
