### PR TITLE
Source packages cleanup

### PR DESCRIPTION
**Pull request by tmat**
Remove unused usings.
Include source packages in list of packages published to myget.
Target net45 instead of net35 -- the source depends on SRM and SCI but they are not available for net35

### CODE REVIEW

**Comment by tmat** [comment]
integration test hang: https://ci.dot.net/job/dotnet_roslyn/job/dev15.6/job/windows_release_vs-integration_prtest/338/consoleFull

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure please review

**Comment by tmat** [comment]
@jasonmalinowski Because they are cool but not too cool to make them public APIs. :)

**Comment by tmat** [comment]
@jasonmalinowski Seriously though, see https://github.com/dotnet/symreader-converter/pull/65.

**Comment by jasonmalinowski** [comment]
Do we have a breaking change policy for those? Do we need to update the PublicAPI checker or something?

**Comment by tmat** [comment]
No, it's not public API. Hence we can break whatever we want.

**Comment by tmat** [comment]
The nice thing is - the projects that reference these won't get broken until they try to update to a newer package version. If they do they need to fix up their code. If they don't want to they can keep the old reference. The code is duplicated at runtime so there is no problem loading different versions in the same process.

**Pull request merged**
