### PR TITLE
re-enabled asserts that got disabled before

### PR DESCRIPTION
**Pull request by heejaechang**
these asserts were disabled before once I added tests that calls GetOperations over every nodes in AllInOneCS and AllInOneVB test files.

since GetOperation is supposed to handle all nodes given to it, it should not cause any assert to fire. even if it returns null if it can't handle the given node.

I talked with @AlekseyTs and he suggested checking IsSemanticModelBinder on all those asserts and re-enable those.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/analyzer-ioperation @cston @AlekseyTs @jcouv can you take a look?

**Comment by heejaechang** [comment]
retest windows_release_unit32_prtest please

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please

**Comment by cston** [comment]
LGTM

**Comment by heejaechang** [comment]
@AlekseyTs @cston can you take a look? I followed @AlekseyTs 's suggestion.

**Pull request merged**
