### PR TITLE
syntax highlighting

### PR DESCRIPTION
**Pull request by cloudRoutine**

### CODE REVIEW

**Comment by genlu** [comment]
@dotnet-bot Retest windows_release_unit64_prtest, please.

**Comment by genlu** [comment]
The test failure in https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit64_prtest/1677/ is a known issue, which has nothing to do with this change.

**Comment by genlu** [comment]
@dotnet-bot Retest windows_release_unit64_prtest please.

**Comment by genlu** [comment]
@dotnet-bot Retest windows_release_unit64_prtest please

**Comment by jaredpar** [comment]
Thanks for that fix!

**Pull request merged**
