### PR TITLE
Initial impl of several Perf test support scripts...

### PR DESCRIPTION
**Pull request by KevinH-MS**
- build.csx (fetches the latest source and produces a build for testing)
- fetch_build.csx (fetches the latest signed build for testing)
- install.csx (installs the binaries you built or fetched, backing up your
  currently installed binaries)
- uninstall.csx (restores previously installed binaries from backup)

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @TyOverby @VSadov @basoundr @rchande @jaredpar

**Comment by KevinH-MS** [comment]
I'm still testing these, but sending out for review...  I *believe* that once this is in place, generating a .csv file that can be consumed by the reporting system should be the last thing we need to try running stuff end to end in the lab.

**Comment by KevinH-MS** [comment]
This PR makes use of "ShellOut" function from #8642

**Comment by TyOverby** [comment]
I've incorporated these commits into #8642 so that I can test them.

**Comment by KevinH-MS** [comment]
Cool--thanks!

**Pull request closed without merging**
