### PR TITLE
Verify conversion kinds in native int conversion tests

### PR DESCRIPTION
**Pull request by jcouv**
Test plan https://github.com/dotnet/roslyn/issues/60578

I recommend github.dev for presenting a minimal diff: https://github.dev/dotnet/roslyn/pull/60895

### CODE REVIEW

**Comment by cston** [comment]
>                 }

Is this used?

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7333 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by cston** [comment]
>             private ConversionKind[] kinds;

`readonly`

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7290 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by cston** [comment]
>             public static ExpectedConversion Identity = ConversionKind.Identity;

`readonly`

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7292 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by cston** [comment]
>             public bool IsNoConversion()

Consider overriding `Equals()` and replacing `IsNoConversion()` and `AssertMatches()` with `Assert.Equals()`.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7322 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by cston** [comment]
>             public void AssertMatches(Conversion conversion)

Consider calling this `Equals()` and let the caller assert.

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7327 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by jcouv** [comment]
>             public void AssertMatches(Conversion conversion)

It's actually better to assert here, because the `Assert.Equal` on enumerables prints out the actual list. Since I'm going to re-use this helper for new tests, that'll be helpful.

---
In reply to: [1105968021](https://github.com/dotnet/roslyn/pull/60895#issuecomment-1105968021) [](http://example.com/codeflow?ancestors=1105968021,1105968021)

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7327 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by cston** [comment]
>         internal class ExpectedConversion

Can we use `Conversion` (or `ConversionKind`) directly?

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7288 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by jcouv** [comment]
>         internal class ExpectedConversion

I don't mind. Switched to `ConversionKind[]`

---
In reply to: [1105977264](https://github.com/dotnet/roslyn/pull/60895#issuecomment-1105977264) [](http://example.com/codeflow?ancestors=1105977264,1105977264)

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:7288 in 5a2ad5e. [](commit_id = 5a2ad5e1a0f7013cf741f6584db48b681b52acab, deletion_comment = False)

**Comment by cston** [comment]
> using System.Diagnostics;

Is this used?

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/NativeIntegerTests.cs:21 in f26191f. [](commit_id = f26191fad683791aa8a24354e6e023ecb32c0cb9, deletion_comment = False)

**Review by cston — APPROVED** [review]

**Pull request merged**
