### PR TITLE
Remove left-over package.config refs

### PR DESCRIPTION
**Pull request by davkean**
Remove left-over unused references in the MetadataVisualizer project.

### CODE REVIEW

**Comment by davkean** [comment]
tag @agocke @tmat

**Comment by davkean** [comment]
prtest/lin/dbg/unit32 has a hung process, took the machine offline.

**Comment by davkean** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by davkean** [comment]
Another machine with a hung, process, took that offline too - at this rate, we'll run out of machines. :)

retest prtest/lin/dbg/unit32 please

**Comment by davkean** [comment]
retest prtest/win/dbg/eta please

**Comment by davkean** [comment]
Filed #6113 for the Windows 64 failure. I can't see the logs to what the actual underlying cause is.

**Comment by davkean** [comment]
Retest prtest/win/dbg/unit64 now that we now what causes 6113.

**Comment by davkean** [comment]
retest prtest/win/dbg/unit64 please

**Comment by davkean** [comment]
Filed #6167 to track the Linux failure.

retest prtest/lin/dbg/unit32 please

**Comment by davkean** [comment]
@jasonmalinowski

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
