### PR TITLE
Show property accessor accessibility in CSharp QuickInfo

### LINKED ISSUE #5094: Poperty tooltip gives incorrect "get; set;" metadata
_(Ported from internal work item 95170)_

``` C#
public class TestClass
{
    public string PrivateSetterProperty { get; private set; }
}

public class OtherClass
{
    public void M()
    {
        var t = new TestClass();
        t.$$
    }
}
```

Where '$$' represents the cursor location above, the tooltip for the `PrivateSetterProperty` in the completion list incorrectly shows `string TestClass.PrivateSetterProperty { get; set; }` where it should list `... { get; private set; }`

### PR DESCRIPTION
**Pull request by diryboy**
Same changes from #5471, not sure why that PR always fail mac git.

Fixes #5094

### CODE REVIEW

**Comment by Pilchie** [comment]
@dotnet-bot: okay to test

@brettfo: Care to take a look?

LGTM.

**Comment by tannergooding** [comment]
okay to test

**Comment by tannergooding** [comment]
test eta please

**Comment by tannergooding** [comment]
okay to test

**Comment by tannergooding** [comment]
okay to test

**Comment by tannergooding** [comment]
test eta please

**Comment by brettfo** [comment]
Changes look good, I'm running internal tests now.

**Comment by brettfo** [comment]
Internal tests pass, merging this now.

**Pull request merged**
