### PR TITLE
Feature/weird vs build errors

### PR DESCRIPTION
**Pull request by eyalsk**
Related to #17345

### CODE REVIEW

**Comment by eyalsk** [comment]
@CyrusNajmabadi Have you guys looked into it?

**Comment by CyrusNajmabadi** [comment]
checking now

**Comment by CyrusNajmabadi** [comment]
So, i see there is an error reported here:

```c#
                var symbolsMissingInLinkedContext = expectedSymbols.Except(linkedContextItemList.Item3, LinkedFilesItemEquivalenceComparer.Instance);
```

```
13>C:\GitHub\roslyn-internal\Open\src\Features\Core\Portable\Completion\Providers\AbstractSymbolCompletionProvider.cs(339,53,339,68): 
error CS1929: 'HashSet<(ISymbol, CompletionItemRules)>' does not contain a definition for 'Except' and the best extension method overload 
'ParallelEnumerable.Except<(ISymbol symbol, CompletionItemRules)>(ParallelQuery<(ISymbol symbol, CompletionItemRules)>, ParallelQuery<(ISymbol symbol, CompletionItemRules)>, IEqualityComparer<(ISymbol symbol, CompletionItemRules)>)' requires a receiver of type 'ParallelQuery<(ISymbol symbol, CompletionItemRules)>'
```

I think the issue is *may* be because you have two different types of tuples here.  You have ```HashSet<(ISymbol, CompletionItemRules)``` (note no names), and ```ImmutableArray<(ISymbol symbol, CompletionItemRules rules)>``` (note the names).  In this case type inference can't infer an appropriate type between the two of these.

If i change the code into:

```c#
                ImmutableArray<(ISymbol, CompletionItemRules)> v = linkedContextItemList.Item3;
                var symbolsMissingInLinkedContext = expectedSymbols.Except(v, LinkedFilesItemEquivalenceComparer.Instance);
```

Then it works fine.  It also works if i provide explicit type arguments to methods like Except.

Tagging @jcouv to see if this behavior is per spec.  Note: if it is per spec, it might be worth us looking into if we want to relax things here or if we want to keep this behavior.  For example, we might say that if we're inferring a type between two tuples that all have the same element types, that that's ok if one of them has names and the other does not.

**Comment by eyalsk** [comment]
@CyrusNajmabadi But this is the part where I expect to have an error, I know about these errors, however, when I'm compiling through Visual Studio I get more errors that are unrelated.

**Comment by CyrusNajmabadi** [comment]
Aren't those just hte cascaded errors because Features.dll didn't build properly?  Do you get those errors if Features.dll builds?

**Comment by eyalsk** [comment]
@CyrusNajmabadi When I compile through the command-line I see only the expected ones whereas with VS I see a lot more errors that imo I shouldn't see.

**Comment by CyrusNajmabadi** [comment]
I do not know why, in the IDE, the compilation does not stop when an error is encountered.  It's just how the IDE has worked for decades.  I would personally like it if it behaved more like the command line.  This is not a roslyn issue though.

**Comment by eyalsk** [comment]
@CyrusNajmabadi Okay, I've fixed it, lesson learnt "Do not trust Visual Studio" haha.., can you forward this feedback or I should post this somewhere? :)

**Comment by CyrusNajmabadi** [comment]
You can potentially try reporting this on https://github.com/dotnet/roslyn-project-system  They might know how to best route things.

**Comment by jcouv** [comment]
FYI I have seen some extensions that make the VS build stop on first error (for instance, [VSColorOutput ](https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput) has this option) That limits the noise. 
I agree that that behavior would make a better default, in my opinion.

**Comment by eyalsk** [comment]
@jcouv Yeah, I was totally confused by the amount of errors I got, thanks for letting me know about the extension, I'll install it. :)

**Comment by Pilchie** [comment]
This seems to be addressed now.

**Pull request closed without merging**
