### PR TITLE
Merge update 1 branch to master

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This is a formality to merge #7249 back into master. We expect that others might want to submit PRs from this branch, and without this merge (which resolved conflicts) they'd have to go fight that mess themselves.

It's expected there is no actual content changes made in this PR.

Review: @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jmarolf** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-infrastructure, want to take a look at this one? [http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/2356/console](The log) isn't clear to me what happened here...

**Comment by jmarolf** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/2356/
// Retest reason: It is unclear if the Tao crash is due to this PR or a very rare flakyness case

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest prtest/win/dbg/eta please

This was a known NuGet timeout being addressed.

**Pull request merged**
