### PR TITLE
Revert SourceLink PRs

### PR DESCRIPTION
**Pull request by allisonchou**
Reverts https://github.com/dotnet/roslyn/pull/58051 and https://github.com/dotnet/roslyn/pull/57978 from the release/dev17.1-vs-deps branch due to regressions. (note, may not be reverted if regressions can be figured out before QB deadline.)

### CODE REVIEW

**Comment by ryzngard** [comment]
This is one of two options we're looking at. Other is https://github.com/dotnet/roslyn/pull/58108

**Comment by allisonchou** [comment]
PR validation: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=5513430&view=results

**Comment by davidwengier** [comment]
Strictly speaking only https://github.com/dotnet/roslyn/pull/58051 needed to be reverted, but I wouldn't expect this to cause any trouble either.

**Review by davidwengier — APPROVED** [review]

**Comment by allisonchou** [comment]
This should no longer be needed since #58108 merged in.

**Pull request closed without merging**
