### PR TITLE
Wait for async operation to complete before disposing workspace

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
not actually certain how this impacts things.  if this has a change in behavior, we should likely disseminate this info so people don't use the previous form in new PRs.

**Comment by sharwell** [comment]
@CyrusNajmabadi Here's the analyzer request for this well-known bug scenario: https://github.com/dotnet/roslyn-analyzers/issues/3071

**Review by davidwengier — APPROVED** [review]
The new using statement makes this way less obvious :(

**Comment by CyrusNajmabadi** [comment]
oh boy.  yeah, that's bad.  there was a discussion at some point about really pushing people to always await, just to avoid these scenarios.  given that we hit this ourselves, i'm now much more inclined to accept such a rule.

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by AArnott — APPROVED** [review]

**Comment by AArnott** [comment]
I've been bit by this bug a few times too. I even call it out in our existing analyzer proposal. https://github.com/microsoft/vs-threading/issues/518

**Pull request merged**
