### PR TITLE
[Do Not Review] Scanner Perf

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Just need some performance data on a "standard machine".

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please.

**Comment by davkean** [comment]
Tag @dotnet/roslyn-compiler, can someone please take a look?

**Comment by gafter** [comment]
@davkean Why would we look at a "DO NOT REVIEW" PR?

**Comment by TyOverby** [comment]
@davkean The title of this pull request is "DO NOT REVIEW"

**Comment by davkean** [comment]
Ah, didn't see that, usually look at the labels. Adding them.

**Comment by AdamSpeight2008** [comment]
@davkean I'm an external contributor hence why I can't tag issues, so I prefix the title.

**Comment by davkean** [comment]
Closing this as it has become stale.

**Pull request closed without merging**
