### PR TITLE
Exclude System.Text.Encoding.CodePages from OptProf

### PR DESCRIPTION
**Pull request by genlu**
@dibarbet This is to fix an OptProf profiling issue https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1515514
Once merged, we will need an 16.11 insertion with OptProf config update only (i.e. dotnet.roslyn.props file in VS)

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
We should consider adding an exclude for this file in our CI and Integration CI, similar to https://github.com/dotnet/roslyn/blob/main/azure-pipelines-integration.yml#L21.

**Comment by genlu** [comment]
@JoeRobich Done! https://github.com/dotnet/roslyn/pull/60828

**Comment by dibarbet** [comment]
@genlu do we have / need QB approval for the insertion?

**Comment by genlu** [comment]
Hmm, maybe? I think it's needed for test only change as well. I can send it for approval once the PR is ready

**Pull request merged**
