### PR TITLE
DynamicFileInfo.cs: fix typo in the constructor

### PR DESCRIPTION
**Pull request by pkulikov**
One of the issues found in #34725

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@pkulikov Is this causing an issue for something you're trying to work on? If so, I'd suggest you retarget this to the dev16.1 branch so it'll get shipped sooner.

**Comment by pkulikov** [comment]
@jasonmalinowski thanks for concern.

No, it doesn't cause any issues. I've just read the [PVS-Studio blog post](https://www.viva64.com/en/b/0622/) about static analysis of the Roslyn code (also see #34725) and noticed an easy thing to fix and submit. So, I think targeting master is fine.

**Comment by jasonmalinowski** [comment]
Sounds good, thanks for the fix!

**Comment by sharwell** [comment]
@jasonmalinowski Can you update the Milestone to match the current release master is targeting?

**Pull request merged**
