### PR TITLE
Unskip quick info tests

### PR DESCRIPTION
**Pull request by dibarbet**
These tests pass now, and moved to the new integration test framework

### CODE REVIEW

**Comment by dibarbet** [comment]
all quick info tests pass on 10 iterations - https://dev.azure.com/dnceng-public/public/_build/results?buildId=100481&view=results

**Comment by Youssef1313** [comment]
> removes the last references to the issue in skipped tests

It seems there are two more

https://github.com/dotnet/roslyn/blob/4d07c7b7a28d445e5bdbf7abd1a59f2f52902af4/src/VisualStudio/IntegrationTest/New.IntegrationTests/CSharp/CSharpUpgradeProject.cs#L37

https://github.com/dotnet/roslyn/blob/4d07c7b7a28d445e5bdbf7abd1a59f2f52902af4/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicIntelliSense.cs#L35

**Comment by dibarbet** [comment]
It looks like you're right, but I swear I'm not crazy for not finding them
image

Seems like find in files is broken

**Comment by dibarbet** [comment]
I'll look at the remaining instances of 38301 in a followup

**Pull request merged**
