### PR TITLE
Fixed typo in build error message

### PR DESCRIPTION
**Pull request by jnm2**

### CODE REVIEW

**Comment by jnm2** [comment]
Wait a minute, lol. I thought this seemed familiar! https://github.com/dotnet/roslyn/pull/24902

**Comment by Neme12** [comment]
i was just going to submit the same exact change :smiley:

**Comment by jnm2** [comment]
@Neme12 I'm still confused how #24902 got wiped out. looking at the blame, it's as if #24902 was never merged, yet it was.

**Comment by 333fred** [comment]
@jnm2 it got wiped out when dev15.7.x was merged into master. @jaredpar made this change: https://github.com/dotnet/roslyn/commit/b16f03fd3b1c6f07dcca65a6e1c15344b3d50ec2#diff-84ed967e20555f74d87c3eaad3c32bd7, which had the old text. When it was merged, the dev15.7.x version was taken.

**Comment by 333fred** [comment]
Test failure is https://github.com/dotnet/roslyn/issues/25230

**Comment by jnm2** [comment]
@dotnet-bot test 'windows_debug_vs-integration_prtest' please

**Comment by jnm2** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Pull request merged**
