### PR TITLE
Update failing test.

### PR DESCRIPTION
**Pull request by gafter**
This fixes a test whose failure was probably caused by a bad auto-merge.

@jaredpar @AlekseyTs @agocke Please review.
@dotnet/roslyn-compiler FYI

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1:

**Comment by agocke** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM. Was the merge committed with failing tests?

**Comment by gafter** [comment]
@AlekseyTs I don't think github checks that all the tests will pass after a PR is integrated by pushing the "Merge pull request" button. I have not investigated precisely where the failure was introduced.

**Comment by AlekseyTs** [comment]
@gafter So, there was a PR for the merge and all tests passed for it. Correct?

**Comment by gafter** [comment]
@AlekseyTs What specific merge are you referring to?

**Comment by AlekseyTs** [comment]
I guess I was referring to the PR with the "Merge pull request" button that you mentioned before. I think it would be good to understand what happened, when the break was introduced and why. So that we can avoid this mistake in the future.

**Comment by gafter** [comment]
@AlekseyTs I wasn't referring to a particular merge operation.

Any insight you can develop on what happened would be welcome.

**Pull request merged**
