### PR TITLE
Enable multiline regex mode for "test <whatever> please"

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This means you can write a comment and then do the line by itself in
one GitHub comment. Otherwise it's requiring you have exactly one
per comment which is annoying.

*Review:* @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot test ci please.

**Comment by tannergooding** [comment]
tagging @mmitche. I'm not sure what "broke" here. But it doesn't look like the default phrase (used by other repos) requires the 'm' and it still appears to work (maybe it has something to do with our change to require the phrase to be on a line by itself).

**Comment by jasonmalinowski** [comment]
Do others not surround with `^$` to require on it's own line?

**Comment by mmitche** [comment]
IIRC, the other repos don't use ^$

**Comment by tannergooding** [comment]
Yeah, they use `"(?i).*test\\W+${contextString}.*"`. Speaking of which, the `\W+` might be incorrect, since it matches any non-word character where-as `\s+` matches any whitespace character (which is probably more desirable).

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Pull request merged**
