### PR TITLE
Keep property on a single line if the getter was on a single line.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/Roslyn/issues/5335

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by rchande** [comment]
This seems reasonable to me, but tagging @basoundr and @heejaechang in case they want to take a look.

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
Retest windows please

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit64  please

**Pull request merged**
