### PR TITLE
[Automated] Merge 'stabilization' and 'master' into 'future'

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
@cston. Am I missing something from this PR? Mac and Linux are both failing with the following:


Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.ExtensionMethodTests.InteractiveExtensionMethods [FAIL]
      \nExpected:\nActual:\n    // error CS0400: The type or namespace name 'System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' could not be found in the global namespace (are you missing an assembly reference?)\n    Diagnostic(ErrorCode.ERR_GlobalSingleTypeNameNotFound).WithArguments("System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089").WithLocation(1, 1)\nDiff:\n++>     Diagnostic(ErrorCode.ERR_GlobalSingleTypeNameNotFound).WithArguments("System.Object, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089").WithLocation(1, 1)
      Stack Trace:
           at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify (IEnumerable`1 actual, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected, Boolean errorCodeOnly) <0x41ff1d40 + 0x0021b> in <filename unknown>:0 
           at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify (IEnumerable`1 actual, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected) <0x41ff1d00 + 0x00013> in <filename unknown>:0 
           at Microsoft.CodeAnalysis.DiagnosticExtensions.Verify (ImmutableArray`1 actual, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected) <0x41ff1c60 + 0x0007b> in <filename unknown>:0 
           at Microsoft.CodeAnalysis.DiagnosticExtensions.VerifyDiagnostics[TCompilation] (Microsoft.CodeAnalysis.TCompilation c, Microsoft.CodeAnalysis.Test.Utilities.DiagnosticDescription[] expected) <0x41ec4460 + 0x00043> in <filename unknown>:0 
           at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.ExtensionMethodTests.InteractiveExtensionMethods () <0x429f5ce0 + 0x0012b> in <filename unknown>:0 
           at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
           at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x41cf1fa0 + 0x000dc> in <filename unknown>:0

**Comment by tannergooding** [comment]
@cston, Actually it appears as though this is also causing failures I the Master branch.

**Comment by cston** [comment]
Created https://github.com/dotnet/roslyn/pull/3510

**Comment by tannergooding** [comment]
@cston. Thanks. I have updated the PR.

**Pull request merged**
