### PR TITLE
Added tests for Out Variable Declarations in new expression contexts.

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. This is another chunk of tests ported from pattern-matching.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review. This is another chunk of tests ported from pattern-matching.

**Comment by agocke** [comment]
Starting review. Github choked on the diff so I assume this is a large change, so it may take me a bit of time.

**Comment by agocke** [comment]
:+1: 

Pretty easy to review, actually, since I remember looking at this code before.

**Comment by AlekseyTs** [comment]
Merging with one sign-off since this is a test only change.

**Pull request merged**
