### PR TITLE
Follow up on added ability to rewrite symbol references in BoundTreeRewriter.

### PR DESCRIPTION
**Pull request by AlekseyTs**
- Extract common reusable functionality from MethodToClassRewriter into a new base class
- Remove some redundant overrides
- Adjust bound nodes and BoundTreeRewriter in preparation for extension method rewrite.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@jcouv, @jjonescz, @dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@jcouv, @jjonescz, @dotnet/roslyn-compiler Please review

**Comment by jcouv** [comment]
Looking but CodeFlow is broken on this PR already :-/

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Review by jjonescz — APPROVED** [review]

**Pull request merged**
