### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git checkout merge-master-into-future20160115-160008
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160115-160008 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by davkean** [comment]
test vsi please

**Comment by davkean** [comment]
test eta please

**Comment by TyOverby** [comment]
@davkean 

Build timeout

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2718/

**Comment by TyOverby** [comment]
test prtest/mac/dbg/unit32 please

**Comment by davkean** [comment]
Okay this failed again with the same issue, @agocke believes its Mono corrupting the stack. Not sure there's anything we can do here other than live with the failures until we move to CoreCLR.

**Pull request merged**
