### PR TITLE
Remove unused tool ProcessWatchDog

### PR DESCRIPTION
**Pull request by jaredpar**
This tool was eventually replaced with a more thorough use of ProcDump in our build environment. Removing as it's no longer needed.

### CODE REVIEW

**Comment by jaredpar** [comment]
retest windows_determinism_prtest please

**Comment by jaredpar** [comment]
retest windows_release_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by AlekseyTs** [comment]
Test failure: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9125/

**Comment by AlekseyTs** [comment]
Test windows_release_unit32_prtest please

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/9134/

16:43:53 Roslyn Error: test timeout exceeded, dumping remaining processes
16:43:53 Dumping xunit.console.x86 6628 to D:\j\workspace\windows_relea---a23004dd\Binaries\Release\xunit.console.x86-0.dmp ... succeeded

**Comment by AlekseyTs** [comment]
Test windows_release_unit32_prtest please

**Pull request merged**
