### PR TITLE
Disabling tests due to flakiness

### PR DESCRIPTION
**Pull request by VSadov**
https://github.com/dotnet/roslyn/issues/18996

Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorLevelWarning
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListDesktop.ErrorList
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListDesktop.ErrorLevelWarning

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @jaredpar @jasonmalinowski

**Comment by sharwell** [comment]
Do you have a link to a build where these failed?

**Comment by VSadov** [comment]
I have statistics such as:


Here is more recent data: failures from monday on.  

FullName count_
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorList
10
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorLevelWarning
6
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListDesktop.ErrorLevelWarning
6
Roslyn.VisualStudio.IntegrationTests.Basic.BasicReferenceHighlighting.Highlighting
6
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpNavigateTo.NavigateTo
5
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSendToInteractive.ResetInteractiveFromProjectAndVerify
5
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpReferenceHighlighting.WrittenReference
4
. . . .

**Comment by VSadov** [comment]
test this please

**Comment by jasonmalinowski** [comment]
@jmarolf Just had a thought: were these supposed to be running in the first place? Or did we break the conditioning again like we did not long ago?

**Pull request merged**
