### PR TITLE
Allow file banner comments to be documentation comments

### LINKED ISSUE #33251: Sort Usings moves incorrect documentation-style header comment
**Version Used**: Visual Studio 2019 Preview 2

🔗 Originally reported as https://developercommunity.visualstudio.com/content/problem/446125/code-clean-mess-with-using-statements.html

**Steps to Reproduce**:

1. Add using directives to the top of a file, where the first is not in the correct location
2. Add a file header comment using documentation comment syntax (even though it's not valid at this location)
3. Run Sort Usings

```csharp
/** This is a documentation comment; it should have only contained one starting asterisk.
 */

using Y;
using X;
```

**Expected Behavior**:

```csharp
/** This is a documentation comment; it should have only contained one starting asterisk.
 */

using X;
using Y;
```

**Actual Behavior**:

```csharp
using Y;
/** This is a documentation comment; it should have only contained one starting asterisk.
 */

using X;
```

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #33251

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Interesting.  does this make sense given the compiler will warn here?  or does it special case these constructs?

**Comment by CyrusNajmabadi** [comment]
Relevant code to update is here: https://github.com/dotnet/roslyn/blob/8c9a6bf6ee44f5570f25c51e85ad35d2069343f7/src/Features/CSharp/Portable/AddFileBanner/CSharpAddFileBannerCodeRefactoringProvider.cs#L16-L25

**Comment by sharwell** [comment]
@CyrusNajmabadi Updated!

**Comment by sharwell** [comment]
@jinujoseph for approval

**Pull request merged**
