### PR TITLE
Rename IOperation for 'with' expression

### PR DESCRIPTION
**Pull request by jcouv**

### CODE REVIEW

**Comment by jcouv** [comment]
@mavasani @333fred @AlekseyTs Simple search&replace PR for purpose of fixing name in public API. Thanks

**Comment by 333fred** [comment]
@jcouv looks like you need to rerun the generator.

**Comment by jcouv** [comment]
Needs more work... Moving back to draft.

**Comment by AlekseyTs** [comment]
@jcouv Should we port this to preview 3?

**Comment by jcouv** [comment]
This was merged before the snap for preview 3 (it's [included](https://github.com/dotnet/roslyn/commits/release/dev16.7-preview3) already)

**Pull request merged**
