### PR TITLE
Bring SignatureHelp support from EditorFeatures.Wpf to EditorFeatures.Cocoa

### PR DESCRIPTION
**Pull request by davidwengier**
https://github.com/dotnet/roslyn/pull/50345 moved some files to EditorFeatures.Wpf that are needed by VS for Mac, so this adds them to EditorFeatures.Cocoa so VS Mac can consume them.

An ideal solution here would presumably be an EditorFeatures.Common that can reference Microsoft.VisualStudio.Language.Intellisense, but not WPF, and then these could be shared. I'm not doing that here simply because I have no idea what infrastructure pieces this would require, and its 4pm my time :) Happy to do it if someone wants to let me know whats involved.

### CODE REVIEW

**Review by KirillOsenkov — APPROVED** [review]
:+1:

**Comment by jasonmalinowski** [comment]
@genlu @KirillOsenkov @davidwengier Can we get a meeting or something scheduled to discuss how we found ourselves in this mess, what was the original goal, and the long term plan here? Not that I'm against this going in strictly but we really should know what the next steps are here.

@davidwengier: did you actually have to make any code changes in those files, or do the compile without modifications? If so, I'd feel a lot better if we just do linked files. The moment we copy/paste things immediately get out of sync which creates a lot of work to clean it back up.

**Comment by davidwengier** [comment]
No changes at all. Linked files is a good idea, I didn't think of, and makes me realise that an EditorFeatures.Common could potentially just be a shared project, if it's easier than shipping something new.

**Review by genlu — APPROVED** [review]
Thanks @davidwengier! Approved assuming linked files will be used.

**Comment by davidwengier** [comment]
This is now using linked files. Verified from a local build in ILSpy:
image

**Comment by jasonmalinowski** [comment]
@davidwengier Did you mean to close?

**Comment by davidwengier** [comment]
Yeah, I have no idea what happened, I didn't close it manually, but at the end of the day the changes are in master so we're good.

When I looked at it, the checks were green but GitHub said there were conflicts (without enumerating what they were) and msftbot said it encountered difficulties. So I merged master in locally, which had no conflicts, shrugged, and pushed. After I pushed I saw it close, and all of Sam's commits from other branches came in. I'm guessing msftbot merged the PR, but then somehow GitHub saw my push included only commits already in master, so closed the PR automatically.

**Comment by CyrusNajmabadi** [comment]
Err..  can we def have a meeting on this . I didn't even know this lib existed.  Def want to have a clean story here for work, esp. around ensuring we aren't unnecessary duplicaitng htings or having to fix things in multiple locations.

**Comment by CyrusNajmabadi** [comment]
> Yeah, I have no idea what happened, I didn't close it manually, but at the end of the day the changes are in master so we're good.

can you clarify which chnages went into master?

**Comment by davidwengier** [comment]
> can you clarify which chnages went into master?

Before GitHub did whatever it did, this PR had these three commits in it, which are now in master:
image
(plus one more, which is the "copy" that the first one reverts, but it was too old to put into one screenshot 😛)

> I didn't even know this lib existed. Def want to have a clean story here for work, esp. around ensuring we aren't unnecessary duplicaitng htings or having to fix things in multiple locations.

The library has existed for as long time AFAIK, but was in the VS Editor repo until recently. It got moved to Roslyn in https://github.com/dotnet/roslyn/pull/48866 to make changes easier, and to avoid having to duplicate (which stupidly, I forgot about and initially did, before Jason rightly pointed out that linked files were better).

Having it Roslyn does solve a dependency mess that I used to have to deal with weekly for VS Mac insertions, but unfortunately it doesn't help us avoid breaking VS for Mac itself, which is what this PR is in response to.

**Pull request closed without merging**
