### PR TITLE
Updated ProjectSystem with new GUID of Composition.csroj

### PR DESCRIPTION
**Pull request by davkean**
These got out of sync.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis

**Comment by srivatsn** [comment]
👍 Curious - what goes wrong if its not in sync with the project? The project doesn't load?

**Comment by davkean** [comment]
VS attempts to update the GUID inside Composition.csproj, and then the next time I open a different solution, it attempts to update it again to a different GUID. Then the solutions just fight with each other.

**Comment by davkean** [comment]
retest prtest/win/dbg/eta please (hung process, started a thread internally)

**Pull request merged**
