### PR TITLE
Use MSBuild Static Graph

### PR DESCRIPTION
**Pull request by jaredpar**
Use MSBuild graph option to verify our build is well formed:

- https://github.com/microsoft/msbuild/blob/master/documentation/specs/static-graph.md
- https://github.com/Microsoft/msbuild/issues/3696

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@jaredpar Any good docs for what this is?

**Comment by tmat** [comment]
You'll need to update https://github.com/dotnet/roslyn/blob/master/eng/build.ps1#L196. 
It might be better to add `-correctness` switch to our build.ps1 and then set `/graph` and other properties there.

**Comment by jaredpar** [comment]
@jasonmalinowski sorry meant for this to be a draft while I worked out the details. Added some docs.

**Comment by jaredpar** [comment]
Closing for now because I don't have time to drive this to completion. Will re-open when I have time.

**Pull request closed without merging**
