### PR TITLE
Port analyzer allocation fixes from master to stabilization

### PR DESCRIPTION
**Pull request by mavasani**
Merged PRs in master: https://github.com/dotnet/roslyn/pull/9327 and https://github.com/dotnet/roslyn/pull/8937

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @srivatsn @heejaechang @basoundr

**Comment by mavasani** [comment]
Tagging @MattGertz for ask mode approval.

**Justification:** We have recently made couple of memory allocation fixes in future and master branch for regressions seen in ML branch. These allocations showed up as soon as we enabled couple new built in analyzers in future. These changes helped bring down the allocations for our perf tests and also improved elapsed time for few scenarios in the test, hence we should port these for 1.2.

**Risks and testing:** None, we have seen these changes benefit perf on ML branch without any new regressions.

**Comment by srivatsn** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved pending successful completion of tests.

**Comment by mavasani** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4797/
// Retest reason: Opened infrastructure issue https://github.com/dotnet/roslyn/issues/9456

**Pull request merged**
