### PR TITLE
Rename internal 'LanguageServices' namespace to not collide with new 'LanguageServices' type.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup to https://github.com/dotnet/roslyn/pull/63241

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@tmat this is ready for review.

**Review by 333fred — APPROVED** [review]
Uh, sorry for suggesting the name... 😅. O# changes LGTM.

**Comment by CyrusNajmabadi** [comment]
@roslyn-ide @jasonmalinowski ptal.  thanks!

**Review by tmat — COMMENTED** [review]
LGTM. I'm wondering why do we have this namespace at all though. It's not very specific, other namespaces also contain language services.

**Comment by CyrusNajmabadi** [comment]
> LGTM. I'm wondering why do we have this namespace at all though. It's not very specific, other namespaces also contain language services.

yeah.  i think we just placed them there to keep them *somewhere*.  but i would actually have no problem being in `Microsoft.CodeAnalysis`.

**Comment by dibarbet** [comment]
@CyrusNajmabadi @333fred this appears to break anyone who references public types like https://github.com/dotnet/roslyn/blob/main/src/VisualStudio/Core/Def/ProjectSystem/VisualStudioWorkspace.cs#L22 via `LanguageServices.VisualStudioWorkspace`.  Found this in a VS insertion.  Should be easy enough to fix, but wanted to check if that was intentional.

**Comment by CyrusNajmabadi** [comment]
Hrmm... That's interesting.  So they have a `using` for `Microsoft.CodeAnalysis.Host` as well?

**Comment by genlu** [comment]
> So they have a using for Microsoft.CodeAnalysis.Host as well?

Yes

**Comment by dibarbet** [comment]
Yeah specifically see this commit - https://devdiv.visualstudio.com/DevDiv/_git/VS/commit/5e5e6d1bbfe272b86625b3fef2fbad65d1155a46?refName=refs%2Fheads%2Fdev%2Fvslsnap%2Finsertions%2Fmain.20220812045626

**Comment by CyrusNajmabadi** [comment]
Yeah, this will be an unfortunate, but rarely-hit source-break.  Binary compat is still there.  Can happen when there are common names in disparate namespaces, and multiple usings.  This can happen within a component, or across components unfortunately,

**Pull request merged**
