### PR TITLE
Switch the inline-hints shortcut from ctrl-alt to alt-f1

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
ctrl-alt has the issue that it's the shortcut for 'create and insert multiple carets'.  Switching to a shortcut that doesn't seem to be taken for any existing features.

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
fyi @DanielRosenwasser @cartermp

**Comment by dibarbet** [comment]
I don't have F row keys on my keyboard :(
Is it at all possible to make this an editor command where I can change the shortcut like other commands (e.g. gotodef)

**Comment by cartermp** [comment]
oof, this is rough. I guess one of the issues is that the f-keys are okay for things that just need to be hit once (e.g., f12, shift-f12, alt-f12) rather than held to see a result. Are there other examples of holding a key command that involve f-keys?

**Comment by CyrusNajmabadi** [comment]
> I don't have F row keys on my keyboard :(

Wat...

Pix?  How on earth do you use VS??  It's like half of hte keys i use.

> Are there other examples of holding a key command that involve f-keys?

Nope.  We're in a brave new world.  But we have ot have something that doesn't literally break some other feature.  ctrl-alt is taken :(

> Is it at all possible to make this an editor command where I can change the shortcut like other commands (e.g. gotodef)

A problem here is that this isn't really a command that comes through, it's a chord held down.

**Comment by dibarbet** [comment]
> Pix? How on earth do you use VS?? It's like half of hte keys i use.

My board needs a little cleanup before I take a picture, but this is the model - http://global.leopold.co.kr/Shop/Item.php?ItId=1524730041

> A problem here is that this isn't really a command that comes through, it's a chord held down.
Hmm yeah I can't think of an example that allows remapping that isn't a command :(

**Pull request merged**
