### PR TITLE
Adds a Mono compatible logic for GAC.

### PR DESCRIPTION
**Pull request by esdrubal**
Implements on each public method of GlobalAssemblyCache logic that does not require Fusion to resolve assemblies and that can be used on Mono.

This changes allow all tests using GAC to pass on Mono except one that is testing an internal method.

### CODE REVIEW

**Comment by davkean** [comment]
@tmat and @dotnet/interactive Can you have a look at this?

**Comment by davkean** [comment]
@tmat and @dotnet/roslyn-interactive, this PR has become stale, can we please drive this conclusion and decide if this an approach we want to take?

**Comment by tmat** [comment]
@davkean Working on it.

**Comment by tmat** [comment]
Merged as part of ea0ce9f4edcf0ffc1ca524a7f1317dfd40332b77, which was based on the implementation in this PR. Thanks for contributing!

**Pull request closed without merging**
