### PR TITLE
do not build additional artifacts in default build

### PR DESCRIPTION
**Pull request by jmarolf**
`build.cmd` currently builds lots of artifacts when `-build` is specified that are only necessary when other flags such as `-sign` or `-pack` are present.  By only building what is needed given the specified arguments we can improve build time for roslyn developers.

|   | Rebuild (after git clean -xdf && restore) | Incremental Build (no changes) |
|--------------- |---------:|---------:|
| Build ExtraSignArtifacts | 232.62 sec | 72.51 sec | 
| No ExtraSignArtifacts | 214.73 sec | 25.97 sec | 
| **Build Time Improvement** | **17.89 sec** | **45.54 sec** |

**Machine Info:**
``` ini
OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.248)
Intel Xeon CPU E5-1620 0 3.60GHz, 1 CPU, 8 logical cores and 4 physical cores
Frequency=3507174 Hz, Resolution=285.1299 ns, Timer=TSC
```

### CODE REVIEW

**Comment by jmarolf** [comment]
> This goes against the explicit design of Build.cmd.

I don't understand the design of `-build` needing to build things for `-pack` or `-sign` when they are not present. We don't build for CoreCLR unless specified. It seems that if `-build` is intended to mean "build everything that can ever be built" we should change `-build` to actually do that.

Lets look at what will happen with this change:
___

`build.ps1 -cibuild -build -sign -pack -bootstrap -binaryLog`:
-  List-VSProcesses
- List-BuildProcesses
- Redirect-Temp
- Make-BootstrapBuild
- Build-Artifacts
   - Run-MSBuild "Roslyn.sln" "/p:DeployExtension=false"
   - Build-ExtraSignArtifacts
   - Build-NuGetPackages
   - Run-SignTool
   - Build-DeployToSymStore
   - Build-InsertionItems

`build.ps1 -build -sign -pack`:
 - Build-Artifacts
   - Run-MSBuild "Roslyn.sln" "/p:DeployExtension=false"
   - Build-ExtraSignArtifacts
   - Build-NuGetPackages
   - Run-SignTool
   - Build-InsertionItems

`build.ps1 -build`:
 - Build-Artifacts
   - Run-MSBuild "Roslyn.sln" "/p:DeployExtension=false"
   - ~~Build-ExtraSignArtifacts~~
   - ~~Build-InsertionItems~~

`build.ps1 -sign`:
 - Build-Artifacts
   - Run-SignTool

`build.ps1 -pack`:
 - Build-Artifacts
   - Build-NuGetPackages
___

As far as I can tell this does not regress any scenarios other than making build.cmd faster for roslyn developers.  Can you help me understand current behavior is beneficial?

**Comment by jaredpar** [comment]
If the goal is minimal build time then just use MSBuild on Roslyn.sln. That is the fastest action and always will be. 

We absolutely build for CoreCLR when it’s not specified. We just don’t use the CoreCLR Toolset. 

If u want build to build absolutely everything including NuGet packages. I’d be fine with that. I excluded it today because it generally isn’t how we expect it to operate. 

I do not want to separate out the build phase again. Too much confusion on that state. It’s going backwards.

**Comment by jmarolf** [comment]
@jaredpar then I would ask: Why is `build.cmd` checked in at all?  None of our infrastructure uses it, its just there for developers.  If it shouldn't be used except in special cases then I would suggest we just tell developers to run `cibuild.cmd`.

**Comment by jaredpar** [comment]
> then I would ask: Why is build.cmd checked in at all? 

My concern is around the changes to build.ps1. That is the core of our infrastructure. The change to reduce build to no longer build everything needlessly complicates the build for no real gain IMHO. 

Options I would consider okay to the design: add ` -skipBuildExtras` parameter that build.cmd can use by default. 

> None of our infrastructure uses it, its just there for developers.

At this point in time this is the case. The longer term goals though are this is the entry point to our build for both developers and our infrastructure. 

>  If it shouldn't be used except in special cases then I would suggest we just tell developers to run cibuild.cmd.

The cibuild.cmd script, and the associated `-cibuild` option, make assumptions about machine resources. In particular that this is the only developer action of consequence happening on the machine at this time. Such actions would be considered destructive on a developer box. This doesn't feel like a real suggestion.

**Comment by jmarolf** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please

@dotnet/roslyn-infrastructure Looks like a flaky test in the [spainish run](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_spanish_unit32_prtest/597/)

**Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.Interactive.Commands.InteractiveCommandHandlerTests.TestCopyToInteractiveWithoutSelection** (from Roslyn.VisualStudio.CSharp.UnitTests)

```
MESSAGE:
System.TimeoutException : Failed to clean up listeners in a timely manner.
 ReportEntireFileChanged SyntacticClassificationTaggerProvider.TagComputer.cs 217
---- System.OperationCanceledException : Operación cancelada.
+++++++++++++++++++
STACK TRACE:
 en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest)
 en Xunit.Sdk.XunitTestInvoker.<>c__DisplayClass6_0.<AfterTestMethodInvokedAsync>b__1()
 en Xunit.Sdk.ExecutionTimer.Aggregate(Action action)
 en Xunit.Sdk.XunitTestInvoker.<>c__DisplayClass6_0.<AfterTestMethodInvokedAsync>b__0()
 en Xunit.Sdk.ExceptionAggregator.Run(Action code)
 ----- Inner Stack Trace -----
 en System.Threading.CancellationToken.ThrowOperationCanceledException()
 en System.Threading.CancellationToken.ThrowIfCancellationRequested()
 en Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcherNoResult(Task task, CancellationToken cancellationToken)
 en Roslyn.Test.Utilities.TaskJoinExtensions.JoinUsingDispatcher(Task task, CancellationToken cancellationToken)
 en Microsoft.CodeAnalysis.Test.Utilities.UseExportProviderAttribute.After(MethodInfo methodUnderTest)
```

**Comment by jmarolf** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please

**Comment by sharwell** [comment]
@jmarolf For test failures like the above:

> Failed to clean up listeners in a timely manner

This indicates a bug where one of our operations using `IAsyncToken` fails to complete or cancel the operation.

> ReportEntireFileChanged SyntacticClassificationTaggerProvider.TagComputer.cs 217

Group the bug by this, which is the identifier for the token which was not completed.

**Comment by jmarolf** [comment]
@sharwell  thanks I filed https://github.com/dotnet/roslyn/issues/26441

**Comment by jmarolf** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by jmarolf** [comment]
spanish build [completed](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_spanish_unit32_prtest/601) but did not report status to github?

**Comment by jmarolf** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest please

**Pull request merged**
