### PR TITLE
Pass correct itemIDs to IVsSymbolicNavigationNotify

### PR DESCRIPTION
**Pull request by dpoeschl**
Retargeted to stabilization (originally reviewed at #2975)

Partial fix for internal TFS bug #1169405

We previously always passed Nil for all itemidCodeFile parameters in IVsSymbolicNavigationNotify to ensure the XAML language service heard our request (because their current implementation only processes request for Nil or 0-valued itemids.) This caused Go To Definition and Find All References to be slower than necessary in non-XAML cases and also resulted in unwanted behaviors on certain properties that are referenced in XAML.

Our two options for fixing this were to either:
1. Update our implementation to send the correct item ids for heuristically "non-generated" files and send Nil for "generated" files (to match the Dev12 behavior)
2. Always send the actual item ids, even for "generated" files, and update the XAML language service to do a fast initial check of the corresponding document to see if they're interested in processing it.

This changeset represents the Roslyn half of option 2. Any builds that contain this fix but do not contain the corresponding change to the XAML language service will see no Go To Definition navigation to .xaml files (e.g. when navigating from a reference to a named Button) and no .xaml file entries in Find All References.

Unfortunately, this does not remove all heuristics from this algorithm, because Roslyn must still decide which itemid to pass in the case of a definition spanning multiple documents (e.g. the MainWindow class created in default WPF projects). We always prefer the "generated" documents to give external language services the best opportunity to participate.

This change also adds asserts to verify all itemID handling during Rename & Navigation happens on the UI thread.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Shiproom Info:

**Bug Number**: Fixes #2994, which completes the Roslyn side of the fix for the customer-reported bug from internal TFS bug #1169405. The xaml side of the fix is already checked in and has migrated to the correct branches.
**Customer scenario**: Navigation to C#/VB properties from C#/VB code may incorrectly navigate to a xaml file if the property is *referenced* in xaml. It can also make navigation and find references slightly slower in some non-xaml situations, but not by much (~10ms). The other scenario is that of an extension author that wishes to intercept GTD or contribute entries to FAR -- we now always pass correct ItemIds, which will better allow any extension to quickly decide whether they are interested in participating.
**Fix description**: (above)
**Testing Done**: Created a test environment with the fix to with 1169405 and this proposed fix to #2994, where the CSharpWPF & BasicWPF integration tests still pass and the bug in 1169405 no longer reproduces.

**Comment by Pilchie** [comment]
:+1: on this one too.

**Comment by dpoeschl** [comment]
retest this please

**Comment by MattGertz** [comment]
Approved 6/2 by ML Shiproom.

**Pull request merged**
