### PR TITLE
I have modified some misspellings!

### PR DESCRIPTION
**Pull request by buk4130**
comparitive -> comparative

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@buk4130, thanks for the spelling fix. Just to check, I see your git client wasn't configured to correctly for your email address in your commit. If you'd like this to be associated with your GitHub account, you'll want to amend your commit with one of the email addresses you have in your GitHub account. If you don't mind, just let us know and we'll hit merge.

**Comment by buk4130** [comment]
Actually, I am participating a project in the school. So, I don't mind about that problem. If you hit merge mine, I will appreciate it^^ Have a nice day!

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Thanks for the spelling fix!

**Pull request merged**
