### PR TITLE
Remove SpecializedTasks.EmptyTask

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
All code can use Task.CompletedTask instead.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jcouv

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @mavasani @heejaechang .  Trivial mechanical change.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @heejaechang  can you merge in?  Thanks!

**Comment by jcouv** [comment]
@jinujoseph Is the master branch still targeting 15.8? Can you approve for merging, or does this need other approval?

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by jinujoseph** [comment]
master is  now targeting 15.8.Preview5 
Approved for 15.8.Preview5 (feel free to merge once green)

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Can you merge in?

**Pull request merged**
