### PR TITLE
Fix indenter so it doesn't indent inside of Interpolation Strings.

### LINKED ISSUE #2231: Multi-Line String Literal + Indentation = Gotcha
VB.net will support multi-line string literals, but it has introduce a gotcha has well.
That of significant whitespace.  After the pressing return to add a newline within the string the following text is indented to align with the current indentation level. But that automatic indentation isn't marked as insignificant. The issue also accord when XML Literals were added to the language.

**Repo Code**
```vb
Imports System
public class C 
    public Sub M() 
        Dim x = "1
        2
        3
        4
        5
        "
        Console.Write(x)
    end sub
  
End Class
```

**Expectation**
```
1
2
3
4
5

```

**Actual**
```
1
        2
        3
        4
        5

```

**Work Around**
A work around is to left-align the string literal.
```
Imports System
public class C 
    public Sub M() 
        Dim x = _
"1
2
3
4
5
"
        Console.Write(x)
    end sub
  
End Class
```

**Desired Resolution**

1. Have the string literal be aware of the indentation level and take it into account.
2. On pressing Return ignore the indentation level, and place the carat at the left-hard margin.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
I think this correct area of the source for this based of C#'s #921
If it is then it fixes #2231

### CODE REVIEW

**Comment by balajikris** [comment]
Needs tests.
tagging @basoundr for feedback.

**Comment by basoundr** [comment]
@AdamSpeight2008 The fix looks good. Please add some testcases like the ones done for C#. This will prevent regressions in the future.

**Comment by AdamSpeight2008** [comment]
@basoundr @balajikris I would add tests but I'm not sure how. There's little documentation describing what every means in the Roslyn Unit Test. Especially those that test IDE features.

**Comment by AdamSpeight2008** [comment]
This is included in #2339, in which @basoundr added in the unit tests. :+1:

**Pull request closed without merging**
