### PR TITLE
updates Roslyn to consume 16.4 version of Editor

### PR DESCRIPTION
**Pull request by AmadeusW**
Update Roslyn to consume 16.4 version of the Editor.
This is the first 16.4 version of Editor which works (there were issues with shell packages), and merging of this PR will allow Editor team to continue with feature work

### CODE REVIEW

**Comment by AmadeusW** [comment]
Do not commit, this PR in current shape is for verification only.
It will take a couple days to release appropriate versions to make this PR ready

**Comment by jaredpar** [comment]
@AmadeusW 

> Do not commit, this PR in current shape is for verification only.

Did you consider submitting this as a draft PR instead of a real PR then? Draft PRs are perfectly suited for this purpose.

**Comment by jasonmalinowski** [comment]
@AmadeusW FYI I have a variation of this since I had to upgrade packages locally to do the IIndentationManagerService stuff.

**Comment by AmadeusW** [comment]
Hey @jasonmalinowski thanks for reaching out.

I'm doing this work for two reasons:

1) I am platformizing the GoTo Def\Impl\Base\References, and will need to change Roslyn from handling these commands to plugging into Editor's service
2) We've updated our copy of PooledObjects to take Roslyn's improvements and began publishing it in **16.3.147**. The types were incorrectly put directly in the `Microsoft.VisualStudio.Utilities` namespace, which causes conflicts in Roslyn's MEF parts which had `using Microsoft.VisualStudio.Utilities` (for the ContentTypeAttribute, for example) as well as used PooledObjects.
Therefore, in 16.4 I'm moving platform's copy of PooledObjects to `Microsoft.VisualStudio.Utilities.PooledObjects` namespace, so that there is no conflict with Roslyn.
I tried to use aliases, to no avail because there were generic types. I did try to onboard Roslyn to Platform's copy of PooledObjects, but this required non trivial changes to many Roslyn projects' target frameworks. Therefore, we decided to make a breaking API change. Fortunately, we have not released 16.3 nuget package, so, optimistically, there is no impact to this. I've sent you a draft email with the impactful change notification for full context

**Comment by AmadeusW** [comment]
Closing, since Jason already accomplished this with #39159

**Pull request closed without merging**
