### PR TITLE
Remove old NavTo interface.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/28343

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @DanielRosenwasser as this will affect TypeScript.  This will not impact F# as they have an EA layer here.

**Review by jasonmalinowski — APPROVED** [review]

**Comment by DanielRosenwasser** [comment]
Looks like we may be good here? https://github.com/dotnet/roslyn/issues/28343#issuecomment-635684895

**Comment by CyrusNajmabadi** [comment]
Right.  But you'll have to move back to the nice, sane, name once i make this change :)  Jusst giving you a heads-up, and also letting you block this on our end if you need more time.

**Review by uniqueiniquity — APPROVED** [review]

**Comment by uniqueiniquity** [comment]
@CyrusNajmabadi works for me, though please try to ensure this gets inserted earlier than the very end of a release cycle so we can respond without dealing with process overhead 😄

**Comment by CyrusNajmabadi** [comment]
@sharwell  any concerns here before i merge?

**Comment by sharwell** [comment]
@CyrusNajmabadi if anything is referencing the interface with the long name, you can't rename it prior to those features moving the external access

**Comment by uniqueiniquity** [comment]
Is there currently an external access version of this? I can go ahead and move us if that's the case.

**Comment by CyrusNajmabadi** [comment]
I'll check.  If there isn't, i can add it.

**Comment by sharwell** [comment]
> Is there currently an external access version of this?

Each partner team would need their own copy of the external access version.

**Comment by CyrusNajmabadi** [comment]
@sharwell  @uniqueiniquity ExternalAccess API added in https://github.com/dotnet/roslyn/pull/48939/commits/e77231b27b4f2979384918306c077f31f29239ba

**Comment by CyrusNajmabadi** [comment]
@sharwell i have added teh bridge type back in.  can you ptal.

**Comment by CyrusNajmabadi** [comment]
@uniqueiniquity once this merges into master, can you move onto the TS EA layer?  thanks!

**Pull request merged**
