### PR TITLE
Run the compiler server at BelowNormal priority so it doesn't interfere with other processes when saturating the CPU.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/11942

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler 

This seemed like the best location to insert this check.  It felt like all program paths flowed through this location, and there was no way to avoid it through virtual overriding or any other mechanism.  However, i'm not sure if there's another location that would be preferred to put this change in.

**Comment by jaredpar** [comment]
I'm beyond terrified about the prospect of checking this in.

**Comment by CyrusNajmabadi** [comment]
What terrifies you?

**Comment by CyrusNajmabadi** [comment]
retest microbuild_prtest please

**Comment by CyrusNajmabadi** [comment]
Also, if we don't do this, do you have a good suggestion on how to make the compiler server not impact hte user as significantly during development?  Note: i don't think we'll have a lot of headway improving Windows here.  So i'm interested in what we can do to have less of a deleterious impact on the user.   Thanks!

**Comment by jaredpar** [comment]
> What terrifies you?

Changing the process priority of a build server is generally terrifying.  It's used in so many scenarios it's hard to completely validate the perf impact of this change. 

> do you have a good suggestion on how to make the compiler server not impact hte user as significantly during development? 

The compiler server is designed to build and build fast.  I'd push back on why we're running it during development if it's causing issues.

**Comment by CyrusNajmabadi** [comment]
> The compiler server is designed to build and build fast.

It should still build fast.  In my own testing all perf impact was basically noise and well within any margin of error.  The only important thing was that other apps on my system that need a bit of CPU when i interacted with them were now no longer laggy.

>  I'd push back on why we're running it during development if it's causing issues.

Ok.  Who would be best to drive that?

**Comment by jaredpar** [comment]
> In my own testing all perf impact was basically noise and well within any margin of error. 

The compiler server has a very large set of scenarios that need to be rigorously tested before we could safely take a change like this:

- Large batch build: VS
- Standard build in VS across small, medium, large project:
- NuGet deployed server 
    - Local developer
    - Web Applications 
- RPS 

I don't think it's realistic for us to get all of this tested for the next release.  The work is known and certainly doable, it's just far below the other priorities we have.  

I think the best we could do is conditionally enable this: off being the default.

**Comment by CyrusNajmabadi** [comment]
> Standard build in VS across small, medium, large project:

What size does 'Roslyn' itself fall into?  On my machine it takes many minutes of sustained CPU to compile it.  As such, it serves as a good litmus of how this change would affect things.   In that scenario i saw, at worse a couple of second difference.  But it was not even consistent and there were times the running at normal pri produced slower results, albeit still degrading the the rest of my computing experience (especially VS and Chrome).

> The compiler server has a very large set of scenarios that need to be rigorously tested

How do you currently validate that any other changes you make to the compiler or compiler server do not regress those scenarios?

> I think the best we could do is conditionally enable this: off being the default.

My general concern here is that we put in a system that aggressively tries to use as much computer resources as possible, at the expense of the other tasks that customers perform on machines (including trying to develop in VS).  While this optimizes for that single isolated compiler concern (raw batch throughput), it does so at a great expense to pretty much any other concern a user may have for what they're going on the computer.  

Conditionally doing something doesn't really help developers (unless you're saying that we would make the condition something like "was this build kicked off from VS?").  I would be ok with such an approach if we were to do that.  Then compiler servers on server machines would get you that full throughput, but compiles on dev machines wouldn't have such an egregious and unpleasant effect on the system.

**Comment by jaredpar** [comment]
> What size does 'Roslyn' itself fall into

It's on the border between Medium and Large. 

> How do you currently validate that any other changes you make to the compiler or compiler server do not regress those scenarios?

We don't have a full set of suites to validate these scenarios.  If we did it would be easier to validate this change.   

What we do know is that this code has a lot of different use cases, can be fragile in terms of getting the right performance and is critical for customer satisfaction.  Taking fixes that we don't know will or won't affect perf is a lot different than taking fixes that we have a reasonable belief will affect perf. 

> My general concern here is that we put in a system that aggressively tries to use as much computer resources as possible, at the expense of the other tasks that customers perform on machines (including trying to develop in VS

That's the point of view of a single customer. Another customer, build for instance, demand that we take every resource possible when building.  

> When you say 'conditionally' could you clarify what you mean? 

Put it behind a switch that is off by default. 

> Conditionally doing something doesn't really help other developers (unless you're saying that we would make the condition something like "was this build kicked off from VS?").

Completely agree.   But I don't think we're willing to invest the resources necessary to take this change as on by default.  The conditional suggested was a bridge so that we could test it on targeted customers, internally, etc ... as a way of vetting the change in the wild.  Assuming that there are targeted scenarios / customers asking for this change.

**Comment by crummel** [comment]
Build triggered. sha1 is merged.

**Comment by VSadov** [comment]
In Menu/Tools/Options/Projects and Solutions/Build and Run    there is a switch that controls how many projects can be built in parallel. It is generally set to the number of logical CPU.

Would dialing that number down to something like CPU/2 have the desired throttling effect while affecting only builds initiated from VS?

**Comment by CyrusNajmabadi** [comment]
I’d be ok with just Max(1, cores - 1) just so there’s some CPU resources available to the rest of my apps to use ☺

            -- Cyrus

**Comment by agocke** [comment]
Closing PR since it's clear we're not taking this for RC

**Comment by CyrusNajmabadi** [comment]
Opening PR.  I'm still working on this.

**Comment by agocke** [comment]
I've re-added `PR for Personal Review Only`

**Comment by CyrusNajmabadi** [comment]
test this please

**Comment by TyOverby** [comment]
@dotnet-bot test perf please

**Pull request closed without merging**
