### PR TITLE
Reverts IServiceBroker changes

### PR DESCRIPTION
**Pull request by tmat**
Fixes [AB#1219902](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1219902)
Fixes [AB#1223635](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1223635)
Fixes [AB#1224230](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1224230)
Fixes [AB#1202649](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1202649)
Fixes [AB#1221938](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1221938)

Reverts partially or in full the following commits:

- https://github.com/dotnet/roslyn/commit/e91ccb5: Use MessagePack for serialization, move services to IServiceBroker (#47461)
- https://github.com/dotnet/roslyn/commit/e0e3655: Provide required callback targets
- https://github.com/dotnet/roslyn/commit/1f7397e: Ensure IServiceBroker is used on a background thread
- https://github.com/dotnet/roslyn/commit/f60ff7e: Prevent potential deadlocks when reading/writing assets (#47864)
- https://github.com/dotnet/roslyn/commit/ebb674f: Make sure to complete copy before returning
- https://github.com/dotnet/roslyn/commit/c020fe8: Wait for GetAssetsAsync before returning
- https://github.com/dotnet/roslyn/commit/24bcf13: Remove ClientDisconnectedSource
- https://github.com/dotnet/roslyn/commit/57759e3: Do not cancel operations after point of no return
- https://github.com/dotnet/roslyn/commit/4123b1c: Work around incorrect implementation of WithMultiplexingStream
- https://github.com/dotnet/roslyn/commit/9499cafa4ac28564c2972b8bf863ba26d854b56f: Fix steaming ISB service hang (#47669)
- https://github.com/dotnet/roslyn/commit/e53ffb731150ce8af1b832a9c04381b990012000: Brokered services (#47216)

### CODE REVIEW

**Comment by sharwell** [comment]
@tmat Can you update the first post to give a list of the pull requests which this change reverts?

**Comment by sharwell** [comment]
Also I'm seeing this in the integration test results (does not appear in the current release/dev16.8 branch):

image

**Comment by tmat** [comment]
I had to revert some commits only partially not to break JavaScript. I also left some test changes in.
Generally any commit that was changing ISB code was reverted.

**Comment by tmat** [comment]
The logs for the failing integration tests show:

```
10/02/2020 05:23:19 Coordinated Universal Time : Error : System.Threading.Tasks.TaskCanceledException: A task was canceled. HResult='-2146233029' 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Client.HubClient.RemoteServiceBrokerWrapper.<>c__DisplayClass9_0.<<RequestServiceChannelAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
10/02/2020 05:23:19 Coordinated Universal Time : Error : System.OperationCanceledException: The operation was canceled. HResult='-2146233029' 
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
10/02/2020 05:23:19 Coordinated Universal Time : Error : System.OperationCanceledException: The operation was canceled. HResult='-2146233029' 
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.ServiceHub.Utility.Shared.ServiceHubRetry.<ExecuteAsync>d__0`1.MoveNext()
```

**Comment by jinujoseph** [comment]
Approved to merge post review

**Review by CyrusNajmabadi — APPROVED** [review]

**Pull request merged**
