### PR TITLE
Order Fully-Qualify results if we believe a certain fix would be better than another one

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/11071

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by jmarolf** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
