### PR TITLE
Fix renaming of files with the new project system

### PR DESCRIPTION
**Pull request by jasonmalinowski**
With the legacy project system, it just so happened that a file rename would be updated in the RDT prior to the project system removing the file under the old name and adding it under the new name. The new
project system doesn't guarantee such an ordering (nor does it have any reason to -- either ordering is perfectly reasonable), so let's handle that too.

@srivatsn, @jmarolf, @davkean for review and also suggestions for testing. I'd like to write an integration test over in this repo, but it looks like all our tests are disabled at this point due to flakiness reasons. Do we think there's any chance I can easily write a stable test for this?

**Customer scenario:** rename an open file. After that, all IDE features stop working properly until you close and reopen the file.
**Bugs this fixes:** dotnet/roslyn#19389.
**Workarounds, if any:** close and reopen the file afterwards.
**Risk**: moderate. Ordering fixes here always can result in other issues.
**Performance impact:** none. Only impacts the file rename case.
**Is this a regression from a previous update?** It's an oversight in this code that just happened to work with the old language service.
**How was the bug found?** dogfooding.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Also tagging @MattGertz for approvals. Given this is quite common and annoying is this worth targeting for preview 2? That's where I have it now.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by MattGertz** [comment]
I agree.

**Comment by davkean** [comment]
@jmarolf is fixing the VSI tests - but I don't know the state.

**Comment by jmarolf** [comment]
@davkean the failing integration tests: 
`Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty`
`Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode`

Are not failures I have seen before and are not related to any project system tests.

**Comment by Pilchie** [comment]
I think the flakiness is https://github.com/dotnet/roslyn/issues/19191, currently assigned to @jasonmalinowski

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Comment by jasonmalinowski** [comment]
Now with 100% more integration tests! @jmarolf can you review that part since I think you might have background here?

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please. Looks like a node with a broken connection got into the Jenkins pool and decided to run a bunch of my jobs.

**Comment by jasonmalinowski** [comment]
(also with 100% more test breakage...)

**Comment by genlu** [comment]
@jasonmalinowski Are you gonna merge this anytime soon?

**Comment by jasonmalinowski** [comment]
@genlu Trying my best; trying to ensure we don't have any other regressions.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by jasonmalinowski** [comment]
Retargeting the branch so am going to do a full retest again.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please.

**Comment by jasonmalinowski** [comment]
Retagging @MattGertz for approval since we're now doing this Preview 3 ask mode.

**Comment by jasonmalinowski** [comment]
Retests for the following reasons:

- windows_eta_open_prtest will be rested as it hit the NuGet cache corruption issue.
- windows_release_unit64_prtest as it hit a cached failure in Microsoft.CodeAnalysis.CompilerServer.UnitTests.CompilerServerUnitTests.ExtraMSCorLibCS. The root issue is logged as #19918.

Not going to retest the integration test failure yet. I don't suspect it's related but at the same time it's not a previously seen failure so need to at least investigate and determine the right action.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_eta_open_prtest please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_unit64_prtest please.

**Comment by jasonmalinowski** [comment]
The last issue looks ot be a new flaky issue, I've filed #19931 to start a conversation there about next steps.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Pull request merged**
