### PR TITLE
Add standard versions of Newtonsoft.Json to RepoUtil

### PR DESCRIPTION
**Pull request by DustinCampbell**
@jaredpar

### CODE REVIEW

**Comment by Pilchie** [comment]
(I think @jaredpar is on his way to the airport for vacation, so I wouldn't block on him)

**Comment by DustinCampbell** [comment]
Sure. And it'd be nice to have a way for non-shipping leaf node tools to be able to excuse from the scan.

**Comment by DustinCampbell** [comment]
OMG: Error: Fixed package Newtonsoft.Json - 9.0.1 is not used anywhere

**Comment by DustinCampbell** [comment]
@heejaechang: look away. I'm not going to be merging this. :smile:

**Comment by DustinCampbell** [comment]
Texted @jaredpar and got a different fix. :smile:

**Comment by jaredpar** [comment]
This won't work in isolation.  You need to both:

- Add it to closed.project.json
- Add the fixed reference in build/config/RepoUtilData.json

**Comment by jaredpar** [comment]
To be clear about fixed.  It's not bad it's just an explicit statement that:

a. We definitely meant to have a different version of this package.  It's not us accidentally say referencing System.Collections.Immutable 1.0 and 1.2 in places we really need a unified version. 
b. When we do package upgrades for the repo (say moving System.Collections.Immutable) don't move this packge.  It has a specific reason for being this version.

**Comment by jaredpar** [comment]
In order to test your changes locally for RepoUtil just do the following:

1. Build `src/Tools/RepoUtil/RepoUtil.csproj` if it's not already built (done so as a part of Roslyn.sln)
2. Run `Binaries\Debug\Exes\RepoUtil.exe verify`

**Comment by DustinCampbell** [comment]
Closing in favor of #15482

**Pull request closed without merging**
