### PR TITLE
Removed missing references and p2p transitiveness from project succes…

### PR DESCRIPTION
**Pull request by heejaechang**
…sfully loaded check.

also, now we log skeleton assembly failure reasons to improve those common cases

**Customer scenario**

User opens a solution and don't see any semantic errors from opened files

**Bugs this fixes:**

related to https://github.com/dotnet/roslyn/issues/21629
(either VSO or GitHub links)

**Workarounds, if any**

fix either design time errors or errors from cross language p2p reference project.

**Risk**

there is a risk where we might show more cascading semantic errors than before.

**Performance impact**

it shouldn't affect performance much.

**Is this a regression from a previous update?**

No

**Root cause analysis:**

this is not a functional bug but rather we are tweaking user experience to find better error situation experience. users only get into this situation when solution has errors. we are experimenting with how much errors we should show users in such situation.

**How was the bug found?**

dogfooding, feedbacks

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @dotnet/roslyn-ide can you take a look?

**Comment by heejaechang** [comment]
I did what I discussed with @Pilchie @jinujoseph today. 

1. removed missing reference as one of cause of project failures
2. removed p2p transitiveness as one of cause of project failures.
3. added telemetry for skeleton assembly failures.

**Comment by jinujoseph** [comment]
cc @jcouv

**Comment by Pilchie** [comment]
Thanks @heejaechang!

For reference this was my thinking for this set of changes:

1. Design time builds that fail but succeed enough to have source files in the project are relatively rare, but the CPS partially loaded state is relatively common, so continue to hide errors in that case until we add a way to distinguish the two.
2. We're going to collect telemetry on skeleton assembly errors, but they come in two forms: a. "Real" errors that the user can see and fix if they build.  b. Errors that are caused by bugs in the project system or language service such that the IDE's Compilation doesn't match a real one.  We could show these to the user, but there is no way for the user to fix them anyway.
3. Given C# and VB's model of requiring references to be specified if they are used (as opposed to pulled in transitively), it doesn't make sense to flow this flag transitively.  If the transitively dependency is a problem, then it should *also* be a top level dependency.

Additional things that I think should happen here:
1. Reduce the number of skeleton assembly errors - @jcouv 
2. Reduce the number of errors reported when there is no standard library to handle the case of a project missing *all* references better.
3. Separate the project "loading" state from the "design time build failed" state.
4. Change IDE diagnostic reporting for closed files to match the compiler and stop at the first pass (keeping open files reporting errors from all phases so that users can fix errors in any order).

@heejaechang / @jinujoseph - does this match your understanding?  If so, can we get bugs tracking the follow-ups above?

**Comment by jinujoseph** [comment]
@Pilchie 
That matches the discussion we had yesterday and  i have linked to open issues 
@heejaechang 
We should target this for dev15.5 , i will take it for shiproom for barcheck

**Comment by natidea** [comment]
@heejaechang to get this in 15.5, please retarget this PR to dev15.5.x
This was approved by shiproom via https://devdiv.visualstudio.com/DevDiv/_workitems/edit/518487

**Comment by frblondin** [comment]
Is it already available in 15.5 Preview 5? The release notes is [really vague](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-Preview-relnotes) for this new preview revision...

**Comment by heejaechang** [comment]
@frblondin it should be in.

**Comment by frblondin** [comment]
The intellisense is still broken on my solution (intellisense dropdown list to resolve missing usings not working, type references failing whereas the build works...).

I understood that you added IDE diagnostic reports. How do I see them?

**Comment by Pilchie** [comment]
@frblondin what version do you have?  Please make sure you have 15.5.2, and then delete the `.vs` directory beside your solution.

**Comment by heejaechang** [comment]
@frblondin if you are using latest 15.5.2 and still not seeing semantic errors but build works fine (I mean solution clean/rebuild), then your solution probably has design time build errors you didn't know about.

use this https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md to find out design time build errors and fix those to get semantic errors back.

**Comment by frblondin** [comment]
@Pilchie I'm using 15.5.2
@heejaechang thanks for sharing this doc, that's really helpful for future issues. For some reason after deleting all files (.vs folder + bin + obj folders) the problem is not reproducible any longer. I did that multiple times yesterday... really weird.

**Pull request merged**
