### PR TITLE
Rename "Src" to "src", so all the files line up.

### PR DESCRIPTION
**Pull request by beannaich**
If you look at the git root directory for this project, you'll see two "src" folders, one with an upper case "S", one with a lower case "s".

This PR resolves that issue by renaming the files to "src", which follows the established convention with the "build" and "docs" folders.

For some reason while making this PR I had some issues with `src\Compilers\VisualBasic\Test\Emit\Resource.Designer.vb`, the file would not reset when explicitly told to.. Given that the file system records were a little off I wouldn't be surprised if this file also has some issues.

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
@beannaich thanks for doing this.  Have no idea why Jenkins failed that job as it listed everything as passing.  I kicked off another Jenkins build to see if it will unstick itself.

**Comment by beannaich** [comment]
@jaredpar No problem, was an easy enough fix to make. I just noticed it when I went to the roslyn page and thought "Two src folders..?"

As I noted in the PR description, there was some strange behavior with one of the VB resources designer files.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
@stephentoub hold off on merging this. Have a larger change I'm trying to get in.  I'll merge this once I get that done (ETA 10 min)

**Comment by stephentoub** [comment]
@jaredpar, thanks, wasn't going to merge... just went through and kicked off rebuilds for all of the PR CI builds that failed due to that script error you just fixed.

**Comment by jaredpar** [comment]
@stephentoub ah okay.  Thanks for doing that ;)

**Comment by beannaich** [comment]
I could have rebased this before merging :)

**Pull request merged**
