### PR TITLE
Pop up a dialog when we're unable to install/uninstall a nuget package.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/8690

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @Pilchie @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by balajikris** [comment]
whats the recourse here.. user retries?

**Comment by balajikris** [comment]
:+1: for the changes.

**Comment by CyrusNajmabadi** [comment]
Well, it's likely to still keep failing.  Recourse would be to try to take the message and see how to resolve the issue (for example, getting back on the network).

**Comment by balajikris** [comment]
sure, that i understand. or retrying after package server is back online or something. what are the options for uninstall.. restart vs? :)

**Comment by CyrusNajmabadi** [comment]
If uninstall breaks... not sure what your recourse is :)

Probably try package manager at that point.

**Comment by CyrusNajmabadi** [comment]
Note: we'll be collecting watsons on these as well.   So if we get tons of failures uninstalling we can use that to drive toward solving what's actually the problem.

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
tagging @MattGertz

**Comment by jmarolf** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved pending successful completion of tests.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/vsi/p3 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/385/
// Retest reason: Issue files on CSharpWinforms timeout.

**Comment by CyrusNajmabadi** [comment]
Fixes #8690

**Pull request merged**
