### PR TITLE
Correct the version number and move them to the Targets

### PR DESCRIPTION
**Pull request by basoundr**
Tagging @dotnet/roslyn @jaredpar @shyamnamboodiripad @jmarolf @brettfo for review.

Since the merge the from dev15-preview-4 to master is not happening now and master is broken. This PR ports the change over to master.

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Make sure you update the packages that depend on these (i.e. TypeScript) when you do the insertion.

**Comment by basoundr** [comment]
@dotnet/roslyn-infrastructure  @jcouv @jasonmalinowski Does the insertion tool update the TypeScript and Roslyn Dependent packages everytime(is it required everytime)?

**Comment by paulvanbrenk** [comment]
Since the AssemblyVersion is stable most of the time i.e. 2.0.0.0 for VS "15" it doesn't need to update each time... but you're changing it from 15.0.0.0 to 2.0.0.0 so you'll have to update manually this time.

**Comment by shyamnamboodiripad** [comment]
@paulvanbrenk: @basoundr accidentally used 15.0 when he added the vs.dependency elements in a previous change. This change is simply fixing these elements to use the correct 2.0 version. Since typescript already correctly references the 2.0 packages, we shouldn't need any change for this on the VS side.

**Comment by shyamnamboodiripad** [comment]
:+1:

**Comment by jaredpar** [comment]
Did we validate this build locally using the SWIX plugin?

**Comment by basoundr** [comment]
The OneNote instruction was only helping in building the vsix from the .swr file and the command line had to provide the Preprocessor variables. This test was helpful in validating a single swr. This is not helpful in validating the dependencies between the swr files or test the .swixproj-s or the .vsmanproj-s.  We will need to spend some time to setup a testing environmment. 

To answer your question, No. I was not able to but for some very limited areas.

**Comment by jasonmalinowski** [comment]
Several questions about this change:

1) I don't understand why we're using assembly version for this; I'd expect file version would be thing we'd use, since that's what we were putting in existing VSIXes in the VS2015 world, and other stuff. Assembly version was explicitly intended for assembly version, and nothing more. If we're going to overload the meaning, we need a different name for it.

2) Why the capping on "next version"? What benefit does this bring us?

**Comment by basoundr** [comment]
1. I thought 'assembly version' was used for all versioning purposes. If it needs to be 'file version' then it can be modified

2. Again, not a mandatory requirement. All the willow components mention the version capping for dependencies. Hence we have too. Theoretically speaking it is not required.

**Comment by jasonmalinowski** [comment]
1. Nope, it's used for controlling assembly versions. This should probably be using file version base.
1. But why? What's the benefit? I really don't like there being another version flag in our build unless it actually provides a benefit.

**Comment by basoundr** [comment]
We could have an issue open for the both. But this was a liberal fix made to get bcb2 off the ground because all of C# and VB was broken.

**Comment by shyamnamboodiripad** [comment]
I think for now our focus should be on getting all our scenarios working correctly in the VS branch. We will have plenty of opportunity to fix things up after preview 4 :) @jasonmalinowski please log issues for the above - we should address them later. (@jmarolf should also chime in on this since the call to use assembly version was originally made by him - not sure if there was some other reason for this choice.)

**Comment by paulvanbrenk** [comment]
We (TypeScript) would like the version to include the buildnumber, so in the case of API changes we can target the right version.

**Pull request merged**
