### PR TITLE
Check to see if it builds.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
This is the recommended base to use, yet it doesn't even build.

**Comment by jaredpar** [comment]
I think you just caught the Jenkins machine at a bad time.  All of the PRs before and after this build.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot ReTest

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
@AdamSpeight2008 the comment I added is the command the bot understands.  I don't think it understands "ReTest".

**Comment by AdamSpeight2008** [comment]
@dotnet-bot test this please

**Comment by AdamSpeight2008** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
