### PR TITLE
Fix tests.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/304/
// Retest reason: The "CreateZipPackage" task failed unexpectedly.

**Comment by jmarolf** [comment]
Why is this change necessary?

**Comment by jmarolf** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
So, the fix went into master here: https://github.com/dotnet/roslyn/pull/11664/files

But it seems to have gotten undone when the merge from future came into master.  So this restores the changes.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p0_open_prtest/63/
// Retest reason: The "CreateZipPackage" task failed unexpectedly.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p1_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/63/
// Retest reason: The "CreateZipPackage" task failed unexpectedly.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/65/
// Retest reason: The "CreateZipPackage" task failed unexpectedly.

**Comment by CyrusNajmabadi** [comment]
i'm also fixing this now because it seems to be affecting 100% of checkins.  Given that the code used to work, but then got changed during the merge, going back to the correct tests from before seems like the right thing to do.

**Comment by CyrusNajmabadi** [comment]
tagging @jasonmalinowski can you take a look here?  I could use some git insight on what happened here (and if i screwed something up majorly).  In master the code was fixed 6 days ago: https://github.com/dotnet/roslyn/pull/11664/files

However, when we did the merge in from future to master, the code got into its broken state.  However, the merge PR for future to master was all green on jenkins.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/66/
// Retest reason: The "CreateZipPackage" task failed unexpectedly.

**Comment by jmarolf** [comment]
:+1:

**Pull request merged**
