### PR TITLE
Replace calls to Enumerable.Count

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@gafter, @pharring, @pilchie

**Comment by pharring** [comment]
:+1: 
@JohnHamby I presume IOperation analyzer would be ideal to detect these? (Calling the "Enumerable.Count()" extension method on an array)

**Comment by Pilchie** [comment]
I thought @jaredpar already wrote an analyzer for this?

**Comment by gafter** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by JohnHamby** [comment]
It's straightforward to write a syntax node action to detect this. An operation action would be a little simpler and multi language, but we can and should have a C# analyzer and a VB analyzer for this today.

**Comment by jaredpar** [comment]
:+1: 

@Pilchie I think I committed to thinking about writing one :smile:

**Pull request merged**
