### PR TITLE
Handle default parameter values for event accessors in CreateBinderForNodeAndUsage.

### LINKED ISSUE #8401: VB syntaxtree re-writier is failing with assert: Unexpected value 'AddHandlerAccessorStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'-
Steps: SytntaxTree re-writing is failing after adding ToString. 
* Parse Syntax Tree, Compile, GetDiagnostics
* **Add ToString to Syntax Tree**, Compile, GetDiagnostics

The input file, and simple project used are added to the details

---- DEBUG ASSERTION FAILED -------- Assert Short Message ----Unexpected value 'AddHandlerAccessorStatement' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'---- Assert Long Message ----   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o) in d:\Roslyn\src\roslyn\src\Compilers\Core\Portable\InternalUtilities\ExceptionUtilities.cs:line 13   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.CreateBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, Binder containingBinder) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 390   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position, Binder containingBinder) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 132   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.GetBinderForNodeAndUsage(VisualBasicSyntaxNode node, NodeUsage usage, VisualBasicSyntaxNode parentNode, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.BinderFactoryVisitor.vb:line 247   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.BinderFactoryVisitor.VisitParameter(ParameterSyntax node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.BinderFactoryVisitor.vb:line 198   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16207   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.MakeBinder(VisualBasicSyntaxNode node, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 50   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderAtOrAbove(VisualBasicSyntaxNode node, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 94   at Microsoft.CodeAnalysis.VisualBasic.BinderFactory.GetBinderForPosition(VisualBasicSyntaxNode node, Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Binding\BinderFactory.vb:line 87   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(Int32 position) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 163   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetMemberSemanticModel(VisualBasicSyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 170   at Microsoft.CodeAnalysis.VisualBasic.SyntaxTreeSemanticModel.GetExpressionTypeInfo(ExpressionSyntax node, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SyntaxTreeSemanticModel.vb:line 288   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetTypeInfoWorker(ExpressionSyntax expression, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 297   at Microsoft.CodeAnalysis.VisualBasic.VBSemanticModel.GetTypeInfo(ExpressionSyntax expression, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\SemanticModel.vb:line 287   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicExtensions.GetTypeInfo(SemanticModel semanticModel, ExpressionSyntax expression, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\VisualBasicExtensions.vb:line 1365   at SPOT.Transformer.VBToStringInserter.VisitInvocationExpression(InvocationExpressionSyntax node) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\RoslynCode\VBToStringInserter.cs:line 19   at Microsoft.CodeAnalysis.VisualBasic.Syntax.InvocationExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 26623   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitBinaryExpression(BinaryExpressionSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 4057   at Microsoft.CodeAnalysis.VisualBasic.Syntax.BinaryExpressionSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 28430   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitEqualsValue(EqualsValueSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2546   at Microsoft.CodeAnalysis.VisualBasic.Syntax.EqualsValueSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16004   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitParameter(ParameterSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2567   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 16207   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 171   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitParameterList(ParameterListSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2078   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ParameterListSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 11499   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitAccessorStatement(AccessorStatementSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 2288   at Microsoft.CodeAnalysis.VisualBasic.Syntax.AccessorStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 13843   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1694   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitNamespaceBlock(NamespaceBlockSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1595   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamespaceBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6849   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 105   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 84   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 1499   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6104   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxRewriter.vb:line 40   at SPOT.Transformer.SourceFileProcessor.Process(String filePath, Stream contentsStream, String& details, String passStatus, String failStatus) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\RoslynCode\SourceFileProcessor.cs:line 80   at SPOT.Transformer.TransformerMapper.ProcessSourceFile(String sourceFilePath, MemoryStream sourceFileContents, String& details) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\JobCode\TransformerMapper.cs:line 10   at SPOT.Azure.SimpleSourceFileMapper.Map(String inputLine, MapperContext context) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\Azure\Jobs\SimpleSourceFileMapper.cs:line 14   at Microsoft.Hadoop.MapReduce.MapperMain.Process(MapperBase mapper, IEnumerable`1 inputEnumerable, MapperContext context)   at Microsoft.Hadoop.MapReduce.StreamingUnit.ExecuteCore[TMapper,TCombiner,TReducer](IEnumerable`1 input, StreamingUnitOptions options)   at Microsoft.Hadoop.MapReduce.StreamingUnit.Execute[TMapper,TReducer](IEnumerable`1 input)   at SPOT.Transformer.Program.Test(String path) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\Program.cs:line 26   at SPOT.Transformer.Program.Main(String[] args) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\Program.cs:line 84

[ConsoleApplication1.zip](https://github.com/dotnet/roslyn/files/118419/ConsoleApplication1.zip)
[MetricsErrorHandler.zip](https://github.com/dotnet/roslyn/files/118420/MetricsErrorHandler.zip)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #8401.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit32 please.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by jaredpar** [comment]
LGTM

**Pull request merged**
