### PR TITLE
Organize Compiler Code

### PR DESCRIPTION
**Pull request by jaredpar**
Makes a couple of changes to the compiler code base:

- Moves the server code into the new Server directory.  This is prep for changes we're about to make for the server. 
- Moves all files in the Compiler sub-directory that are shared by source into the Shared directory.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by jaredpar** [comment]
Note: ETA will fail with this change as the code move breaks the internal solution file.  I will send out a cross cutting notification before merging and fixup the internal code immediately after the merge.

**Comment by jaredpar** [comment]
FYI: merging this now.  We need this change in order to make progress on the portable server work.  Will happily respond to any PR feedback with a subsequent change.

**Comment by diryboy** [comment]
Could you please check if this caused #6577 ?

**Comment by jaredpar** [comment]
@diryboy yep it did.  Don't know why this didn't show up in the Jenkins run.  Will fix here in a minute.

**Comment by jaredpar** [comment]
@diryboy see #6582

**Comment by diryboy** [comment]
I had created #6577 actually, never mind, thanks!

**Pull request merged**
