### PR TITLE
Put in accessor accessibility modifiers when symbol display is asked to show read/write info for properties

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Note: we could also implement this by addind a new SymbolDisplayPropertyStyle flag.  I think that would be appropriate as well.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @dotnet/roslyn-compiler .  This changes the SymbolDisplay for properties so that if the user asks for information about the getters/setters, we not only display the get;/set; but also the accessibility.  

This is to support IDE quick info, where we want to show the respective accessibility of the accessors.  We don't want this controlled by SymbolDisplayMemberOptions.IncludeAccessibility, because that would then show the accessibility of the property itself.  For QuickInfo we don't want that because we already show the accessibility through the glyph we display.

--

An alternate approach here would be to have independent flags for showing get;/set; and for showing the accessor accessibility.  However, i didn't think that was an important enough knob to call out itself as i couldn't think of any scenarios when you'd want one and not the other.

**Comment by jcouv** [comment]
LGTM

Here's the tuple property test from other PR we discussed:
```C#

        [Fact, Trait(Traits.Feature, Traits.Features.QuickInfo)]
        public async Task TupleProperty()
        {
            await TestInMethodAsync(@"
interface I
{
    (int, int) Name { get; set; }
}
class C : I
{
    (int, int) I.Name$$
    {
       get { throw new System.Exception(); }
       set { }
    }
}",
                MainDescription("(int, int) C.Name { get; set; }"));
        }
```

**Comment by CyrusNajmabadi** [comment]
Added hte test.

**Comment by CyrusNajmabadi** [comment]
Ping @dotnet/roslyn-compiler

**Comment by cston** [comment]
This does change the behavior of a public API and does not give the user the ability to drop the accessor modifier, short of modifying the `ImmutableArray<SymbolDisplayPart>`.

**Comment by CyrusNajmabadi** [comment]
> and does not give the user the ability to drop the accessor modifier,

which user wants the accessors for properties, but does not want the accessibility?  When we added this flag, we did so precisely for the QuickInfo case of showing them (where we do want the accessibility).  I'm ok with this just being the default behavior.

> This does change the behavior of a public API

Do you have a suggestion on how we could change things such that we preserved the existing API behavior but were able to get the new behavior that we actually want.  Specifically, we'd want the property to not have accessibility (so we wouldn't provide MemberFlags.IncludeAccessibility), but we would want accessor accessibility.  So we'd likely have to add a new PropertyFlags.IncludeAccessorAccessibility.  However, it would be strange that if you didn't have that flag, and you did ask for member accessibility, that you'd see the accessor accessibility modifiers.

**Comment by cston** [comment]
@CyrusNajmabadi I'm not necessarily suggesting we should support both the current behavior and the new behavior, just pointing out that the behavior has changed. And I don't know of scenarios where the caller would want accessors but not accessibility.

The actual change LGTM, assuming we are comfortable with the behavioral change.

**Comment by CyrusNajmabadi** [comment]
Gotcha.  Thanks Chuck.  @gafter do you have any issues with this change in behavior around SymbolFlags.  It seems very isolated, and the new behavior seems preferable.  So i think the change is acceptable.

**Pull request merged**
