### PR TITLE
Fixes a bug in escape analysis related to 'in' arguments

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #22456

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review

**Comment by VSadov** [comment]
CC: @jcouv for 15.5 signoff

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - PING. This is a very simple fix.

**Comment by jcouv** [comment]
I'll go ahead and merge on behalf of @VSadov

**Comment by VSadov** [comment]
@jcouv - Thanks!!

**Pull request merged**
