### PR TITLE
Lambda rewriter should rewrite method/property symbols when rewriting…

### LINKED ISSUE #3906: Invalid codegen in a particular case with lambda accessing a struct field
The following code does not verify and does not run.

```C#
using System;

public class M {

  public struct S<T> {
    public T x;
  }
 
  public static object SomeFunc<A>(System.Linq.Expressions.Expression<Func<object, A>> selector)
  { return null; }

  public static void CallIt<T>(T t) {
    Func<object, object> goodF = xs => SomeFunc<S<T>>(e => new S<T>());
    var z1 = goodF(3);
    Func<object, object> badF = xs => SomeFunc<S<T>>(e => new S<T> { x = t });
    var z2 = badF(3);
  }

  public static void Main() {
    CallIt<int>(3);
  }
}
```

### PR DESCRIPTION
**Pull request by VSadov**
… member initializers.

Since the containing type could have been changed if it is a type parameter in the containing method.

Fixes #3906

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @khyperia @jaredpar @agocke

**Comment by VSadov** [comment]
Will check if VB needs similar fix and fix in a separate change if needed.

**Comment by jaredpar** [comment]
:+1:

**Comment by VSadov** [comment]
VB does not have the bug because in VB member initializers are not symbolic. To handle additional VB complexity, these initializers are represented as actual field/property access expressions on an imaginary placeholder receiver. As a result of the representation, they get rewritten together with regular access expressions and do not need special handling here.

**Comment by jaredpar** [comment]
@VSadov glad VB doesn't have the same issue.  Can we add a test case to make sure we don't regress that in the future?

**Comment by VSadov** [comment]
@jaredpar - yes, will add a test since I have VB scenario anyways.

**Pull request merged**
