### PR TITLE
Stop inserting old setup and loc files

### PR DESCRIPTION
**Pull request by tmat**
Stop automatically updating loc and old setup authoring files in lab/ml. These are obsolete and won't be used in Dev15 RTM. If any changes are needed to these files (which would be unexpected) they are they can be done manually.

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure @jasonmalinowski

**Comment by jasonmalinowski** [comment]
@tmat So how is localization working? We're just leaving what every is already inserted there for now, and any changes to assemblies in the mean time need to be updated manually in the internal side?

**Comment by jmarolf** [comment]
@jasonmalinowski the work now falls to me to move all of our loc into the roslyn repro itself.

**Comment by tmat** [comment]
@jasonmalinowski Localization still works as it used to work. I haven't removed the locproj/lci files from lab/ml. Unless there is a new dll that needs to be localized, is renamed, its location in lab/ml is changed, or adds/removes dependenyc on XAML, there is no need to change these files.

**Pull request merged**
