### PR TITLE
Fix param collection expression binding in expression trees

### PR DESCRIPTION
**Pull request by bernd5**
fixes: #74163

### CODE REVIEW

**Comment by bernd5** [comment]
We should may add a test for the concrete issue, too. I just created one for the root issue.
(the project seems to have no ref assembly to Net9.0)

**Review by AlekseyTs — CHANGES_REQUESTED** [review]
We don't want to bind differently in expression tree context. See https://github.com/dotnet/csharplang/blob/main/proposals/params-collections.md#expression-trees

**Comment by bernd5** [comment]
Oh, then it becomes a breaking change to existing code. But this is wanted???

**Comment by AlekseyTs** [comment]
> Oh, then it becomes a breaking change to existing code. But this is wanted???

Please see https://github.com/dotnet/csharplang/blob/main/meetings/2024/LDM-2024-06-17.md#params-span-breaks for more information.

**Comment by bernd5** [comment]
I see - then we would need to fix the lowering (and use an array).

**Comment by AlekseyTs** [comment]
> I see - then we would need to fix the lowering (and use an array).

Please see https://github.com/dotnet/roslyn/issues/74163#issuecomment-2191548114. First, we need to understand the root cause of the problem. Where and what is going wrong. Only then we can decide what the fix should look like. I suggest you to start with that if you would like to continue working on the issue.

**Comment by AlekseyTs** [comment]
> then we would need to fix the lowering (and use an array).

We probably don't want to change the lowering in this fashion either.

**Comment by bernd5** [comment]
> We probably don't want to change the lowering in this fashion either.

I wouldn't like to change the lowering code for interpolated string, too.
We could simply dissallow such code (breaking change) - but this is also not very well.

**Comment by AlekseyTs** [comment]
> I wouldn't like to change the lowering code for interpolated string, too. We could simply dissallow such code (breaking change) - but this is also not very well.

Let's discuss possible fix strategies in the issue. While proposing a strategy, please make the proposal very specific and detailed. For example, the quote above looks neither specific, nor detailed to me.

**Pull request closed without merging**
