### PR TITLE
Handle explicit branch operations in control flow graph

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review

**Comment by 333fred** [comment]
Can you add some tests around VB implicit loop labels?

**Comment by 333fred** [comment]
Done with review (Iteration 1)

**Comment by 333fred** [comment]
Ah, missed these.

---
In reply to: [370610366](https://github.com/dotnet/roslyn/pull/25210#issuecomment-370610366) [](ancestors = 370610366)

**Review by 333fred — APPROVED** [review]
:shipit:

**Review by cston — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/analyzer-ioperation Please review

**Review by mavasani — APPROVED** [review]

**Pull request merged**
