### PR TITLE
properly handle VB Global namespace in DeclaredSymbolInfo

### PR DESCRIPTION
**Pull request by brettfo**
When walking the syntax trees to find DeclaredSymbolInfos, I missed a case where VB can have "Namespace Global".  Functionally this is no different than hitting the default case of the Select where I also Return Nothing, but it's a lot nicer to not have asserts :smile:.

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by brettfo** [comment]
@Jenkins test this please

**Comment by brettfo** [comment]
@Jenkins test this please

**Comment by rchande** [comment]
:+1:

**Pull request merged**
