### PR TITLE
Add missing nugets to VS setup VSIX

### PR DESCRIPTION
**Pull request by tmat**
Fixes integration test failures due to missing System.Collections.Immutable v1.2.0

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski @jmarolf @AlekseyTs FYI

**Comment by jasonmalinowski** [comment]
:+1:. We needed immutable again since this is our first upgrade to a newer version since Dev14 RTM?

**Comment by jasonmalinowski** [comment]
Actually revoking feedback. Don't we also need to update AssemblyRedirects.cs to include the appropriate redirection/codebase attributes?

**Comment by tmat** [comment]
retest vsi please

**Comment by jasonmalinowski** [comment]
I see you already had them in an earlier PR, sorry. :+1:

**Comment by tmat** [comment]
There is still one failure (BasicWPF.xml) that is likely caused by immutable array version change, but this at least fixes most of the tests, so merging.

**Pull request merged**
