### PR TITLE
Move some fields into an UncommonFields class

### PR DESCRIPTION
**Pull request by pharring**
For limited review at the moment.
@gafter, per our conversations about symbol size, I'd like to get your opinion on this before I develop it out further.

### CODE REVIEW

**Comment by gafter** [comment]
Awesome. Can you verify that this is never initialized for most PE methods, even those that are used?

**Comment by pharring** [comment]
The choice of which fields to move into uncommon fields was driven by analyzing memory usage in a large C# solution. Any fields that were >95% null or the same uninitialized value were candidates.

**Comment by gafter** [comment]
My question is whether or not you have verified the number of these objects is much smaller than the number of PE methods?

**Comment by pharring** [comment]
Not yet. Lots more testing to do on this. However, if I did it correctly there should be no more than 1 UncommonField allocation for every 20 PEMethodSymbol allocations (5%).

**Comment by gafter** [comment]
If that turns out to be the case in practice, then this change is wonderful.

**Comment by pharring** [comment]
I'm going to start a new PR with the final version including VB.

**Pull request closed without merging**
