### PR TITLE
Use .Any extension of ImmutableArray(Of Symbol)

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Removes the explicit For Each loop and replace with a call to the extension method `.Any` on the `ImmutableArray(Of Symbol)`

### CODE REVIEW

**Review by CyrusNajmabadi — DISMISSED** [review]
this needs to come with performance data indicating that the lambda, and delegate-invocation-overhead is not a problem.

**Comment by sharwell** [comment]
@CyrusNajmabadi This change was submitted [at my request](https://github.com/dotnet/roslyn/pull/48977#discussion_r513542294)

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Review by AlekseyTs — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @AdamSpeight2008

**Pull request merged**
