### PR TITLE
Merge late global analyzer features

### PR DESCRIPTION
**Pull request by chsienki**
Cherry picks a couple of commits from master that we'd like to get into preview2.

1. Fixes a compiler crash
2. Renames msbuild global analyzer config naming

### CODE REVIEW

**Comment by chsienki** [comment]
@jaredpar for M2 approval. 
@JoeRobich for Tiger awareness.

**Comment by JoeRobich** [comment]
@chsienki This needs to be in before 9am for any shot of making it in M2.

**Comment by chsienki** [comment]
Oh. The last email I saw said M2 was 5/20 - 5/22?

**Comment by chsienki** [comment]
Ping @jaredpar

**Comment by JoeRobich** [comment]
> Oh. The last email I saw said M2 was 5/20 - 5/22?

Since they announced the work holiday for the 22nd, the schedule moved up a day.

**Comment by jaredpar** [comment]
@JoeRobich 

> Snce they announced the work holiday for the 22nd, the schedule moved up a day.

Did we communicate the change internally?

**Comment by JoeRobich** [comment]
> Did we communicate the change internally?

Not well enough. There was an email from Bernard on Tuesday afternoon. Next time I will think to forward it more widely.

**Comment by chsienki** [comment]
Closing this, as we'll take it in P3 instead.

**Pull request closed without merging**
