### PR TITLE
Avoid formatting diagnostics with raw strings

### PR DESCRIPTION
**Pull request by jcouv**
Similar to last time we updated CodeStyle version: https://github.com/dotnet/roslyn/pull/58810

### CODE REVIEW

**Comment by jcouv** [comment]
@JoeRobich I'm looking for the dotnet-format version corresponding to CodeStyleAnalyzer `4.2.0-2.final`. Could you help?

**Comment by JoeRobich** [comment]
@jcouv You can use version `6.3.317301`.

**Comment by jcouv** [comment]
@JoeRobich @dotnet/roslyn-compiler for version upgrade to CodeStyle analyzer and dotnet-format, to avoid diagnostics in our usage of raw strings. One compiler test updated to illustrate the fix works.

**Review by 333fred — APPROVED** [review]

**Comment by jcouv** [comment]
Merged with single compiler review since only minor test change in this PR.

**Pull request merged**
