### PR TITLE
Remove src/Diagnostics/ from dotnet/roslyn repo

### PR DESCRIPTION
**Pull request by genlu**
As the first step, everything under dotnet/roslyn/src/Diagnostics/Roslyn is moved to dotnet/roslyn-analyzers/src/Roslyn. All the NuGet related code was removed from Roslyn-internal already.

Removal of other directories will be in upcoming commits.

@srivatsn @tmeschter @jaredpar @mavasani

### CODE REVIEW

**Comment by srivatsn** [comment]
:+1:

**Comment by tmeschter** [comment]
:+1:

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by genlu** [comment]
@dotnet-bot Retest this, please.

**Pull request merged**
