### PR TITLE
Restore async-streams tests on Core

### PR DESCRIPTION
**Pull request by jcouv**
Relates to https://github.com/dotnet/roslyn/issues/30438 which I'm still investigating.

### CODE REVIEW

**Comment by jcouv** [comment]
test windows_coreclr_debug_prtest  please

**Comment by jcouv** [comment]
test windows_coreclr_release_prtest  please

**Comment by jcouv** [comment]
@jaredpar 
My attempts to repro the issue locally didn't succeed. I added a bunch of versions of the Tasks.Extensions package, but the tests still passed.

I confirmed that the CoreCLR tests sometimes pass in CI, but not always (I had 3 successes and 1 failure in this PR so far).
Is there any way to ask for some information about the machine were the failure occurred?

**Comment by jcouv** [comment]
test windows_coreclr_release_prtest please

**Comment by jcouv** [comment]
test windows_coreclr_release_prtest please

**Comment by jcouv** [comment]
test windows_coreclr_debug_prtest please

**Comment by jcouv** [comment]
test windows_coreclr_release_prtest please

**Comment by jcouv** [comment]
test windows_coreclr_release_prtest please

**Comment by jcouv** [comment]
@jaredpar I'm not sure what changed, but I'm now able to enable async-streams tests on Core. I guess waiting was a winning strategy? ;-)

@dotnet/roslyn-compiler for review. Thanks

**Comment by jaredpar** [comment]
Hmm ... that's fairly scary. Oh well. Lets turn them on and if there is flakiness we can disable and dig into it.

**Pull request merged**
