### PR TITLE
Ensure DeclarationTreeBuilder.GetModifiers doesn't throw on unexpected tokens that have errors.

### LINKED ISSUE #8400: VB compiler GetDiagnostics is failing with assert: Unexpected value 'CustomKeyword' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'
Steps:Parse Syntax Tree, Compile, Get Diagnostics with VB compiler. Simple project ConsoleApplication is used.

---- DEBUG ASSERTION FAILED -------- Assert Short Message ----Unexpected value 'CustomKeyword' of type 'Microsoft.CodeAnalysis.VisualBasic.SyntaxKind'---- Assert Long Message ----   at Roslyn.Utilities.ExceptionUtilities.UnexpectedValue(Object o) in d:\Roslyn\src\roslyn\src\Compilers\Core\Portable\InternalUtilities\ExceptionUtilities.cs:line 13   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.GetModifiers(SyntaxTokenList modifiers) in 
d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 794   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitTypeBlockNew(TypeBlockSyntax topTypeBlockSyntax) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 474   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitClassBlock(ClassBlockSyntax classBlockSyntax) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 499   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 7909   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxVisitor.vb:line 36   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitNamespaceChildren(VisualBasicSyntaxNode node, SyntaxList`1 members, SingleNamespaceOrTypeDeclaration& implicitClass) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 60   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitNamespaceChildren(VisualBasicSyntaxNode node, SyntaxList`1 members) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 40   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitNamespaceBlock(NamespaceBlockSyntax nsBlockSyntax) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 304   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamespaceBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6849   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxVisitor.vb:line 36   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitNamespaceChildren(VisualBasicSyntaxNode node, SyntaxList`1 members, SingleNamespaceOrTypeDeclaration& implicitClass) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 60   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.VisitCompilationUnit(CompilationUnitSyntax node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 189   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor) in d:\Roslyn\src\roslyn\Binaries\Obj\BasicCodeAnalysis\Debug\Syntax.xml.Generated.vb:line 6104   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxVisitor`1.Visit(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Syntax\VisualBasicSyntaxVisitor.vb:line 36   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.ForDeclaration(SyntaxNode node) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 34   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTreeBuilder.ForTree(SyntaxTree tree, ImmutableArray`1 rootNamespace, String scriptClassName, Boolean isSubmission) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTreeBuilder.vb:line 22   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.ForTree(SyntaxTree tree, VisualBasicCompilationOptions options, Boolean isSubmission) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 891   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation._Closure$__73-0._Lambda$__0() in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 884   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTable.GetLatestRootDeclarationIfAny(Boolean includeEmbedded) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTable.vb:line 186   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTable.GetMergedReferenceDirectives() in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTable.vb:line 177   at System.Lazy`1.CreateValue()   at System.Lazy`1.LazyInitValue()   at System.Lazy`1.get_Value()   at Microsoft.CodeAnalysis.VisualBasic.Symbols.DeclarationTable.get_ReferenceDirectives() in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Declarations\DeclarationTable.vb:line 245   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.get_ReferenceDirectives() in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1227   at Microsoft.CodeAnalysis.CommonReferenceManager`2.GetCompilationReferences(TCompilation compilation, DiagnosticBag diagnostics, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectives, ImmutableArray`1& referenceDirectiveLocations) in d:\Roslyn\src\roslyn\src\Compilers\Core\Portable\ReferenceManager\CommonReferenceManager.Resolution.cs:line 757   at Microsoft.CodeAnalysis.CommonReferenceManager`2.ResolveMetadataReferences(TCompilation compilation, Dictionary`2 assemblyReferencesBySimpleName, ImmutableArray`1& references, IDictionary`2& boundReferenceDirectiveMap, ImmutableArray`1& boundReferenceDirectives, ImmutableArray`1& assemblies, ImmutableArray`1& modules, DiagnosticBag diagnostics) in d:\Roslyn\src\roslyn\src\Compilers\Core\Portable\ReferenceManager\CommonReferenceManager.Resolution.cs:line 203   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.ReferenceManager.CreateAndSetSourceAssemblyFullBind(VisualBasicCompilation compilation) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Symbols\ReferenceManager.vb:line 271   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.ReferenceManager.CreateSourceAssemblyForCompilation(VisualBasicCompilation compilation) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Symbols\ReferenceManager.vb:line 146   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetBoundReferenceManager() in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1165   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1929   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicCompilation.GetDiagnostics(CancellationToken cancellationToken) in d:\Roslyn\src\roslyn\src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb:line 1865   at SPOT.Transformer.SourceFileProcessor.Process(String filePath, Stream contentsStream, String& details, String passStatus, String failStatus) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\RoslynCode\SourceFileProcessor.cs:line 74   at SPOT.Transformer.TransformerMapper.ProcessSourceFile(String sourceFilePath, MemoryStream sourceFileContents, String& details) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\JobCode\TransformerMapper.cs:line 10   at SPOT.Azure.SimpleSourceFileMapper.Map(String inputLine, MapperContext context) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\Azure\Jobs\SimpleSourceFileMapper.cs:line 14   at Microsoft.Hadoop.MapReduce.MapperMain.Process(MapperBase mapper, IEnumerable`1 inputEnumerable, MapperContext context)   at Microsoft.Hadoop.MapReduce.StreamingUnit.ExecuteCore[TMapper,TCombiner,TReducer](IEnumerable`1 input, StreamingUnitOptions options)   at Microsoft.Hadoop.MapReduce.StreamingUnit.Execute[TMapper,TReducer](IEnumerable`1 input)   at SPOT.Transformer.Program.Test(String path) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\Program.cs:line 26   at SPOT.Transformer.Program.Main(String[] args) in D:\DotNETBI\DotNETBI.Full\Prototypes\SPOT\SPOT\TestApp-Transformer\Program.cs:line 84 

[ModuleCatalog.zip](https://github.com/dotnet/roslyn/files/118410/ModuleCatalog.zip)

[ConsoleApplication1.zip](https://github.com/dotnet/roslyn/files/118415/ConsoleApplication1.zip)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #8400.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit64 please.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by cston** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1: 

Did we verify that C# is resilient to the same type of problem?

**Comment by AlekseyTs** [comment]
I looked at the C# code. It looks like ModifierUtils.ToDeclarationModifiers can handle all tokens that C# parser can put into a modifiers list. The ```custom``` keyword in VB has rather special error recovery handling in VB parser that is why it ends up in the list for VB.

**Pull request merged**
