### PR TITLE
Add EditorConfig settings for source formatting

### PR DESCRIPTION
**Pull request by SLaks**
**Customer scenario**

Working on Roslyn source if you use different source formatting options for your own projects

**Workarounds, if any** Don't use the formatter, or make a separate VS profile.

+ @Pilchie @kuhlenh @jmarolf to think about option names

### CODE REVIEW

**Comment by jmarolf** [comment]
Thanks @SLaks! because this isn't a product fix you don't need to fill out the ask mode template.

**Comment by SLaks** [comment]
I was wondering about that...
When are each of the PR fields required?
For PRs about new features that exactly correspond to a reported bug, most of them seem very irrelevant.

**Comment by SLaks** [comment]
The test failure is _not_ my fault :) #flaky 

It would be nice to validate `.editorconfig` (against either current repo build or a VS release) in some kind of Jenkins check; see #16556

**Comment by SLaks** [comment]
retest windows_release_unit64_prtest please

**Comment by SLaks** [comment]
@dotnet-bot  retest windows_release_unit64_prtest please

**Comment by Pilchie** [comment]
@MattGertz okay to merge this non-product change to master for people who are copying our `.editorconfig` file?

**Comment by MattGertz** [comment]
Yup.

**Comment by Pilchie** [comment]
Thanks @SLaks

**Pull request merged**
