### PR TITLE
Enable Conditional Access optimizations for cases when LocalRewriter introduces a local in the process of initial lowering of the access.

### PR DESCRIPTION
**Pull request by AlekseyTs**
@VSadov, @gafter, @jaredpar Please review.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @gafter, @jaredpar Please review.

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Comment by AlekseyTs** [comment]
@dotnet-bot Test this please

**Pull request merged**
