### PR TITLE
Mac OS X is now macOS (README.md)

### PR DESCRIPTION
**Pull request by rogersachan**
This PR updates all mentions of OSX/OS X to macOS in the README.

### CODE REVIEW

**Comment by benknoble** [comment]
Are there other spots where we need to fix this?

**Comment by rogersachan** [comment]
@benknoble Quite a bit of them, especially in the documentation. I was surprised to see that no one had bothered to fix them as macOS has been out for some time.

**Comment by benknoble** [comment]
@rogersachan I did a repo search for Mac OS X and only got 3 hits, two of which were iOS... surprising

**Comment by rogersachan** [comment]
Make sure you do OSX too, seeing as some made it a habit to not put spaces

**Comment by benknoble** [comment]
Here's the [search](https://github.com/dotnet/roslyn/search?p=1&q=OSX&type=&utf8=✓) for anyone who wants to work on it

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-infrastructure for review.

**Comment by rogersachan** [comment]
@Pilchie Why does the PR test keep failing?

**Comment by benknoble** [comment]
@rogersachan *shrugs* but it all passes now

**Comment by Pilchie** [comment]
Tagging @jaredpar @agocke

**Pull request merged**
