### PR TITLE
Rename - Don't crash when type renamed to 'Current'

### LINKED ISSUE #10469: [PR in review] Attempting to Rename Item Prepended With Current or MoveNext Results In Crash
So I don't know if this is an issue with Roslyn or VS, but attached the trace record.
.NET Framework 4.5:

**Steps to Reproduce**:

1. In VS, right-click item & select Rename.
2. Begin typing Current or MoveNext.

**Expected Behavior**:
No unhandled System.NullReferenceException when typing Current/MoveNext. 

**Actual Behavior**:
Instantly when Current or MoveNext is typed (Apply button not clicked), an unhandled System.NullReferenceException occurs. Here is the trace record:

```none
<TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>DefaultDomain</AppDomain><Exception><ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   

at Microsoft.CodeAnalysis.Shared.Extensions.ITypeSymbolExtensions.&amp;lt;GetBaseTypes&amp;gt;d__20.MoveNext()   

at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)   

at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.ComputePossibleImplicitUsageConflicts(ISymbol renamedSymbol, SemanticModel semanticModel, Location originalDeclarationLocation, Int32 newDeclarationLocationStartingPosition, CancellationToken cancellationToken)   

at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.AddImplicitConflicts(ISymbol renamedSymbol, ISymbol originalSymbol, IEnumerable`1 implicitReferenceLocations, SemanticModel semanticModel, Location originalDeclarationLocation, Int32 newDeclarationLocationStartingPosition, ConflictResolution conflictResolution, CancellationToken cancellationToken)   

at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.&amp;lt;ResolveConflictsAsync&amp;gt;d__18.MoveNext()</StackTrace><ExceptionString>System.NullReferenceException: Object reference not set to an instance of an object.  

at Microsoft.CodeAnalysis.Shared.Extensions.ITypeSymbolExtensions.&amp;lt;GetBaseTypes&amp;gt;d__20.MoveNext()   

at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)  

at Microsoft.CodeAnalysis.CSharp.Rename.CSharpRenameConflictLanguageService.ComputePossibleImplicitUsageConflicts(ISymbol renamedSymbol, SemanticModel semanticModel, Location originalDeclarationLocation, Int32 newDeclarationLocationStartingPosition, CancellationToken cancellationToken)   

at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.AddImplicitConflicts(ISymbol renamedSymbol, ISymbol originalSymbol, IEnumerable`1 implicitReferenceLocations, SemanticModel semanticModel, Location originalDeclarationLocation, Int32 newDeclarationLocationStartingPosition, ConflictResolution conflictResolution, CancellationToken cancellationToken)   

at Microsoft.CodeAnalysis.Rename.ConflictEngine.ConflictResolver.Session.&amp;lt;ResolveConflictsAsync&amp;gt;d__18.MoveNext()

</ExceptionString></Exception></TraceRecord>
```

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #10469

### CODE REVIEW

**Comment by dpoeschl** [comment]
Review: @dotnet/roslyn-ide

**Comment by davkean** [comment]
Is there some subtly that I'm missing? Why does this fix the issue?

**Comment by Pilchie** [comment]
That codepath assumed that the symbol being renamed was always contained within a type, because it expected to only run for methods.

**Comment by Pilchie** [comment]
:+1:

**Comment by davkean** [comment]
:+1:

**Pull request merged**
