### PR TITLE
fixed CA1044 in ConsoleIO

### PR DESCRIPTION
**Pull request by filipw**
**Bugs this fixes:**

Fixes [CA1044: Properties should not be write only](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1044-properties-should-not-be-write-only) violation in `ConsoleIO` in scripting code.

cc @tmat

### CODE REVIEW

**Comment by tmat** [comment]
@filipw thanks for fixing this -- you'll need to update the overrides as well.

**Comment by filipw** [comment]
oops I'm sorry - had lightweight solution load checked and didn't notice 😱

**Comment by filipw** [comment]
@tmat I think this should be good merge 😄

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
@jinujoseph for approval

**Comment by tmat** [comment]
Thanks @filipw for the fix!

**Pull request merged**
