### PR TITLE
Add dependency on Microsoft.DiaSymReader.Native to Microsoft.CodeAnalysis.Common

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@agocke @davidfowl

**Comment by davidfowl** [comment]
I love that the build script is csx. You can probably remove it from Microsoft.Net.Compilers.

**Comment by jaredpar** [comment]
CC @weshaggard as this means we're adding a new component that should go into the shared framework.

**Comment by tmat** [comment]
@MattGertz FYI

**Comment by MattGertz** [comment]
Approved pending tests/CRs.

**Comment by weshaggard** [comment]
Have we verified the right thing happens on non-windows? I don't know who owns or publishes Microsoft.DiaSymReader.Native so I'm unsure if it is setup correctly.

**Comment by tmat** [comment]
We do own the package.

**Comment by tmat** [comment]
This is the nuspec for the package. @weshaggard does it look ok?

```
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
  <metadata>
    <id>Microsoft.DiaSymReader.Native</id>
    <summary>Microsoft DiaSymReader</summary>
    <description>
      Native implementation of PDB file reader and writer.
Supported Platforms:
- Windows x86
- Windows amd64
- Windows arm
    </description>
    <language>en-US</language>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <version>$currentVersion$</version>
    <authors>Microsoft</authors>
    <licenseUrl>http://go.microsoft.com/fwlink/?LinkId=394369</licenseUrl>
    <projectUrl>http://msdn.com/roslyn</projectUrl>
    <releaseNotes>Native implementation of PDB file reader and writer</releaseNotes>
    <tags>DiaSymReader PDB</tags>
  </metadata>
  <files>
    <file src="Microsoft.DiaSymReader.Native.props" target="build" />
    <file src="$DiaSymReaderNativeDir$\Microsoft.DiaSymReader.Native.x86.dll" target="runtimes\win\native" />    
    <file src="$DiaSymReaderNativeDir$\Microsoft.DiaSymReader.Native.amd64.dll" target="runtimes\win\native" />
    <file src="$DiaSymReaderNativeDir$\Microsoft.DiaSymReader.Native.arm.dll" target="runtimes\win\native" />    
    <file src="$DiaSymReaderNativeDir$\Microsoft.DiaSymReader.Native.x86.dll" target="runtimes\win-x86\native" />    
    <file src="$DiaSymReaderNativeDir$\Microsoft.DiaSymReader.Native.amd64.dll" target="runtimes\win-x64\native" />
    <file src="$DiaSymReaderNativeDir$\Microsoft.DiaSymReader.Native.arm.dll" target="runtimes\win8-arm\native" />
  </files>
</package>
```

**Comment by weshaggard** [comment]
Any particular reason you are putting all three builds into the runtimes\win\native folder?

**Comment by tmat** [comment]
To support AnyCPU, I guess.

**Comment by weshaggard** [comment]
I'm not sure about the runtimes\win\native folder but I suspect it doesn't break anything. The other entries seem fine but as always we should test.

**Comment by tmat** [comment]
Doesn't work :(

Restoring packages of an app referencing Roslyn with this dependency fails:
```
Adding package 'Microsoft.DiaSymReader.Native.1.3.3' to folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Added package 'Microsoft.DiaSymReader.Native.1.3.3' to folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Added package 'Microsoft.DiaSymReader.Native.1.3.3' to 'packages.config'
Successfully installed 'Microsoft.DiaSymReader.Native 1.3.3' to ConsoleApplication40
  GET https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.native.System/4.0.0-rc2-23931
  OK https://dotnet.myget.org/F/dotnet-core/api/v2/package/runtime.native.System/4.0.0-rc2-23931 431ms
Installing runtime.native.System 4.0.0-rc2-23931.
Install failed. Rolling back...
Package 'runtime.native.System.4.0.0-rc2-23931' does not exist in project 'ConsoleApplication40'
Removed package 'Microsoft.DiaSymReader.Native.1.3.3' from 'packages.config'
Executing script file 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages\Microsoft.CodeAnalysis.Analyzers.1.1.0\tools\uninstall.ps1'...
Removed package 'Microsoft.CodeAnalysis.Analyzers.1.1.0' from 'packages.config'
Package 'runtime.native.System.4.0.0-rc2-23931' does not exist in folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Removing package 'Microsoft.DiaSymReader.Native.1.3.3' from folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Removed package 'Microsoft.DiaSymReader.Native.1.3.3' from folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Removing package 'Microsoft.CodeAnalysis.Analyzers.1.1.0' from folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Removed package 'Microsoft.CodeAnalysis.Analyzers.1.1.0' from folder 'c:\users\tomat\documents\visual studio 14\Projects\ConsoleApplication40\packages'
Could not install package 'runtime.native.System 4.0.0-rc2-23931'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Comment by tmat** [comment]
Closing the PR. This approach doesn't work.

**Pull request closed without merging**
