### PR TITLE
Trim the length of the banner that we show for outlining down a bit.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Mitigates https://devdiv.visualstudio.com/DevDiv/_workitems?id=472485 somewhat.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dpoeschl

**Comment by dpoeschl** [comment]
Here's the Developer Community version of the internal issue Cyrus mentioned above: https://developercommunity.visualstudio.com/content/problem/84221/xml-documentation-and-region-directives-not-collap.html

**Comment by CyrusNajmabadi** [comment]
retest windows_release_unit64_prtest please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit32_prtest  please

**Pull request merged**
