### PR TITLE
Fully separate out tests to separate directories

### PR DESCRIPTION
**Pull request by jaredpar**
This changes our unit test projects to build and run in isolated directories.  This prevents issues around clashing dependencies from different products we are required to simultaneously ship on. 

The one exception to this are tests which exist in portable class libraries.  In order for a test to execute the full set of dependencies must be present in the output directory.  That is not possible when building a portable class library with MSBuild because there is no associated runtime hence nothing to drive the deployment.  

To work around this our PCL test projects are structured in the following way:

- Each builds without references to `Dlls\<Project Name>`
- Deployment projects (empty exes) reference every PCL test project and create a runnable output per runtime.
    - CoreClr builds to `CoreClrTests` 
    - Desktop builds to `UnitTests\Portable`

This means that our PCL test projects are *properly* tested twice.  Once per runtime they are supported on.  The setup also means that the build system is fully correct and verifiable.

The downside is that these projects don't have an F5 test experience.  Will start an email discussing possible options around an F5 experience here.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure, @tmat, @Pilchie

**Comment by jaredpar** [comment]
ETA test failure is being addressed in a closed PR.

**Comment by tannergooding** [comment]
test open-vsi_prtest please

**Comment by tannergooding** [comment]
@jaredpar, I kicked off the open-vsi tests. I would like to ensure these are not broken (again) by these changes.

**Comment by jaredpar** [comment]
@tannergooding why add VSI?  Did you see the comment about ETA not going to work?

**Comment by tannergooding** [comment]
@jaredpar, this is the open integration tests (which is entirely contained in open and is independent of ETA/Closed VSI),.

**Comment by jaredpar** [comment]
Okay.  Why aren't they enabled by default?

**Comment by tannergooding** [comment]
Because they are 'new' and we didn't want to block PRs on them if they are flaky. They are working, and working reliably (outside of a deployment bug in VS related to VSIX in general), so we can probably enable them by default sometime this week (with sign-off from @jasonmalinowski)

**Comment by tannergooding** [comment]
@jaredpar, looks like some-change in here broke the IncludePattern logic for unit test assemblies: https://github.com/dotnet/roslyn/blob/bf0e9d771d963f1f780108916a433893cfcf3dea/BuildAndTest.proj#L90

**Comment by tannergooding** [comment]
Ah, it would be (at least for open-vsi) because the `RoslynProjectType` wasn't fixed up: https://github.com/dotnet/roslyn/blob/master/src/VisualStudio/IntegrationTests/VisualStudioIntegrationTests.csproj#L14

**Comment by jaredpar** [comment]
@tannergooding that should all be correct in this PR

**Comment by tannergooding** [comment]
test open-vsi_prtest please

**Comment by tannergooding** [comment]
👍

**Comment by TyOverby** [comment]
@jaredpar Is there a reason that this PR would cause more assemblies to be loaded?  Or Jit more methods?  

I'm looking at [this graph](https://benchview/trendline?build_selector=latest&count=100&aggregate=arithmeticMean&interval=INTERVAL_MIN_MAX&rtids=[977,980,960]&archids=[6]&mpids=[1293]&cfgids=[2689]&testids=[49980,49982,49984,49986]&jobid=20739)

**Comment by jaredpar** [comment]
@TyOverby no.  This particular PR really only affected the test directories.  I'd separated out the non-test directories in a previous PR.  That's definitely a bit strange.

**Pull request merged**
