### PR TITLE
Introduce a new 'wrap binary expression' (without alignment) refactoring.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Implements https://github.com/dotnet/roslyn/issues/32830
Followup to https://github.com/dotnet/roslyn/pull/32858

This gives users the option to both 'wrap' and 'wrap and align' a binary expression.  The difference between the two can be seen in cases like this:

image

image

'Wrap expression' wraps as if the user hit 'enter' at each operator.  i.e. it will do whatever 'smart indent' would do.

'Wrap and align expression' wraps the individual parts of the expression, but aligns them with the start of the expression.

The former is for those who just want to speed up the act of pressing 'enter' a lot, and who want whatever default indentation VS would do.  The latter is for people who want the indentation to more clearly indicate the parent/child relationship between the wrapped parts.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @sharwell @jinujoseph @dotnet/roslyn-ide

**Comment by sharwell** [comment]
Design review outcome: looks good for 16.1.

**Comment by CyrusNajmabadi** [comment]
@sharwell review when convenient.  Though you might want to review https://github.com/dotnet/roslyn/pull/32858 first to make this simpler.

**Comment by CyrusNajmabadi** [comment]
@sharwell can you take a look Plz?

**Comment by CyrusNajmabadi** [comment]
Anything i can do to help speed this along?  @sharwell anyone else who may be able to take a look?

**Comment by CyrusNajmabadi** [comment]
Anything i can do to help speed this along? @sharwell anyone else who may be able to take a look?

**Comment by CyrusNajmabadi** [comment]
Ping @sharwell

**Comment by CyrusNajmabadi** [comment]
ping @sharwell @jinujoseph Can we move forward on this?

**Comment by CyrusNajmabadi** [comment]
ping @sharwell @jinujoseph Can we move forward on this?

**Comment by CyrusNajmabadi** [comment]
@jinujoseph Sam says he's got a lot on his plate with async completion and integration tests. Can this get someone else to take a look?

**Comment by dpoeschl** [comment]
@CyrusNajmabadi I'll be taking a look today or tomorrow.

**Comment by CyrusNajmabadi** [comment]
@dpoeschl Thanks much!!

**Comment by CyrusNajmabadi** [comment]
Note: @dpoeschl   This is a followup to https://github.com/dotnet/roslyn/pull/32858.  If you can get that in sooner, it will make this PR easier to review.

**Comment by dpoeschl** [comment]
Imagine I have the following expression already smart-indented onto its own line.

```C#
int x = 
    $$1 + 2 + 3 + 4;
```

Both of these would result in the same eventual code, right? I don't immediately see a place where we would de-dupe, but it seems like we should do this. What do you think @CyrusNajmabadi ?

**Comment by CyrusNajmabadi** [comment]
> Both of these would result in the same resulting code, right? I don't immediately see a place where we would de-dupe, 

The architecture of this feature is that we produce the individual wrapping options unilaterally.  These are then collected by an higher level which checks and dedupes them, leaving only unique options to the user.   So, for this code, you will only end up seeing:

image

**Comment by CyrusNajmabadi** [comment]
Tests added.

**Comment by dpoeschl** [comment]
> The architecture of this feature is that we produce the individual wrapping options unilaterally. These are then collected by an higher level which checks and dedupes them, leaving only unique options to the user.

@CyrusNajmabadi Where is this happening? Sorry if I'm missing something obvious here.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Where is this happening? Sorry if I'm missing something obvious here.

no worries!  It happens here: https://github.com/dotnet/roslyn/blob/d99071e1caf89dfa7431bd3c9cff829cb6dc71b3/src/EditorFeatures/Core/Wrapping/AbstractCodeActionComputer.cs#L97

basically, the subclasses say "here are the edits i want to make" and the base class goes "ok, those edits will make a tree we already saw.  so you don't get to make a code action for this".  This means the `AbstractCodeActionComputer` is stateful.  That's why we instantiate a fresh one when computing the refactorings.

**Comment by CyrusNajmabadi** [comment]
@doeschl did https://github.com/dotnet/roslyn/pull/32859#issuecomment-470758289 make sense?  Thanks!

**Comment by dpoeschl** [comment]
@CyrusNajmabadi Yep, thank you!

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
