### PR TITLE
made Reanalyze not to crash when unknown workspace is given. rather i…

### PR DESCRIPTION
**Pull request by heejaechang**
…t will just ignore the request.

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani @jasonmalinowski @basoundr can you take a look?

follow up for crash report from joshvarty@gmail.com and hi@amadeusw.com

**Comment by jasonmalinowski** [comment]
Why wouldn't the caller just not pass the workspace in the first place? This feels like it's masking the issue rather than fixing it...

**Comment by heejaechang** [comment]
@jasonmalinowski the call is buried deep inside. real cause is VSWorkspace is not registered properly to solution crawler but yet, somehow connected to project system (build)

so, question is when people play with VSWorkspace (since it is exposed through MEF), should we strict about it (crash) or at least not crash.

I would actually prefer exposing API to get VSWorkspace properly.

- heejae

**Comment by AmadeusW** [comment]
:+1: 

> I would actually prefer exposing API to get VSWorkspace properly.

What's the proper way of getting the workspace? Or, what's wrong with getting it using MEF?

**Comment by jasonmalinowski** [comment]
@heejaechang: then we should be updating how that handshake works. At this point MEF import of VisualStudioWorkspace is expected and shipped...we can't change that now.

**Comment by heejaechang** [comment]
well, as you can see from this code.

http://index/#Microsoft.VisualStudio.LanguageServices/Implementation/LanguageService/AbstractPackage%25602.cs,6b017c2c2eae0908

if anyone calls MEF<VSWorkspace> before us, we could be screwed. if they do MEF<VSWorkspace> from UI thread, then might be okay based on what they are doing. 

I think most safer way is we expose PrimaryWorkspace and then they get the workspace through GetWorkspace which we make sure will be called from UI thread.

**Pull request closed without merging**
