### PR TITLE
Type parameters with an oblivious constraint shouldn't be considered as PossiblyNullableReferenceTypeTypeParameter

### LINKED ISSUE #34892: Unexpected "Nullability of type argument doesn't match constraint." warnings when a type parameter with Oblivious constraint is used as a type argument
```
#nullable enable
public class AA
{
    public void M3<T3>(T3 z) where T3 : class { }

    public void M4<T4>(T4 z) where T4 : AA { }

#nullable disable
    public void F1<T1>(T1 x) where T1 : class
    {
#nullable enable
        M3<T1>(x); // warning CS8634: The type 'T1' cannot be used as type parameter 'T3' in the generic type or method 'AA.M3<T3>(T3)'. Nullability of type argument 'T1' doesn't match 'class' constraint.
    }

#nullable disable
    public void F2<T2>(T2 x) where T2 : AA
    {
#nullable enable
        M4<T2>(x); // warning CS8631: The type 'T2' cannot be used as type parameter 'T4' in the generic type or method 'AA.M4<T4>(T4)'. Nullability of type argument 'T2' doesn't match constraint type 'AA'.
    }
}
```

Observed:
```
warning CS8634: The type 'T1' cannot be used as type parameter 'T3' in the generic type or method 'AA.M3<T3>(T3)'. Nullability of type argument 'T1' doesn't match 'class' constraint.
warning CS8631: The type 'T2' cannot be used as type parameter 'T4' in the generic type or method 'AA.M4<T4>(T4)'. Nullability of type argument 'T2' doesn't match constraint type 'AA'.
```

Expected: No warnings.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #34892

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off for a small bug fix.

**Comment by cston** [comment]
>         /// T => true

Where `#nullable enable`?

---
Refers to: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:65 in 0be5f53. [](commit_id = 0be5f53341eb92172458cd41993b849359dadbba, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         /// T => true

> Where #nullable enable?

Yes. The comment is for ```#nullable enable``` context

---
In reply to: [481826206](https://github.com/dotnet/roslyn/pull/34899#issuecomment-481826206) [](ancestors = 481826206)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:65 in 0be5f53. [](commit_id = 0be5f53341eb92172458cd41993b849359dadbba, deletion_comment = False)

**Comment by cston** [comment]
>         /// T => true

Should the comment mention that?

---
In reply to: [481829484](https://github.com/dotnet/roslyn/pull/34899#issuecomment-481829484) [](ancestors = 481829484,481826206)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:65 in 0be5f53. [](commit_id = 0be5f53341eb92172458cd41993b849359dadbba, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>         /// T => true

I will clarify the comment in a separate PR

---
In reply to: [481831040](https://github.com/dotnet/roslyn/pull/34899#issuecomment-481831040) [](ancestors = 481831040,481829484,481826206)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/TypeSymbolExtensions.cs:65 in 0be5f53. [](commit_id = 0be5f53341eb92172458cd41993b849359dadbba, deletion_comment = False)

**Pull request merged**
