### PR TITLE
Update referenced MSBuild to 17.3.4

### PR DESCRIPTION
**Pull request by ericstj**
Fixes https://github.com/dotnet/roslyn/issues/72812
@marcpopMSFT @jaredpar @rainersigwald

### CODE REVIEW

**Comment by ericstj** [comment]
Might need another update somewhere. 
> Error processing binary log file: Unsupported log file format. Latest supported version is 17, the log file has version 18.

**Comment by rainersigwald** [comment]
> Might need another update somewhere.
> 
> > Error processing binary log file: Unsupported log file format. Latest supported version is 17, the log file has version 18.

Tried to update to latest which wasn't on our feeds, so I tried to push it to the feeds but failed, so I backed it down to the latest in the feeds, which should be new enough.

**Comment by jaredpar** [comment]
The CI test failures are expected and not fixable.

**Comment by jaredpar** [comment]
@marcpopMSFT are you good on the .NET SDK to absorb this in 8.0.1xx if we merge here?

**Comment by marcpopMSFT** [comment]
Yes, the 8.0.1xx sdk should take this codeflow for a June release.

**Pull request merged**
