### PR TITLE
Add support for TypedConstant and TypeOf expressions

### PR DESCRIPTION
**Pull request by mattwar**
Fix for #2005 

This change adds support for TypedConstant and TypeOf expressions to SyntaxGenerator.
Attribute(AttributeData) factory now correctly uses TypeConstant factory for arguments
Added tests for Attribute(AttributeData) and TypeOf
Changed SyntaxNormalizer to treat initializer braces differently than code flow braces.

### CODE REVIEW

**Comment by mattwar** [comment]
@dotnet-bot please test this

**Comment by mattwar** [comment]
@Pilchie, @srivatsn please review

**Comment by Pilchie** [comment]
:+1:

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
