### PR TITLE
[WIP] Portable workspace tests

### PR DESCRIPTION
**Pull request by SamB**
[Note: This comes after PR #6943.]

I've noticed that there is not a portable test project for Workspaces, which is a problem because I wanted to add a test to it.  So, I'm about to try creating one; I'm starting this PR now so I can get some early warning when I screw something up that doesn't show up in my own testing.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @jasonmalinowski @agocke and @dotnet/roslyn-ide to take a look at this.

**Comment by jasonmalinowski** [comment]
Rather than having to move all the files in the existing project, would it be easier to:

1. create a new project for Desktop
2. convert the existing project to be portable
3. move the things over that aren't portable?

Looking at the tests in the tests today, it looks like a decent chunk should be portable already, but maybe I'm not thinking of some critical dependency.

**Comment by jasonmalinowski** [comment]
Also to whoever will ultimately merge this: note that the solution file modifications will require equivalent modifications to be made to our non-public code.

**Comment by SamB** [comment]
@jasonmalinowski: Hmm, I guess I could try it that way again, now that I have a better idea of what form the resulting project should take and so on.

**Comment by jasonmalinowski** [comment]
Yeah, if you've seen what it looks like afterwards you might have a better sense than I. I'm never a huge fan of the pattern where everything gets moved to a "legacy" folder and then everything moves back later...

**Comment by jasonmalinowski** [comment]
And my motivation is just to avoid file moves _if easily possible_ to make source control history easier for those who have to dig through this one day. I'm _totally_ OK though churning whatever has to be churned for work like this though!

**Comment by SamB** [comment]
Well, I'm making more progress with the "move what breaks" approach than last time I tried it, but I'm running into a bit of trouble with conflicts between TestUtilities and TestUtilities.Desktop ...

**Comment by SamB** [comment]
So, um, it seemed to be going okay up until about when I tried to switch TestUtilities.Desktop to target .NET framework 4.6 and make it depend on TestUtilities proper, after which (yes, even after updating `project.js` to match, and making sure the packages got restored) VS seemed to go kind of crazy; it couldn't reliably resolve the `System` assembly anymore.  Even when I go back and do basically *only* that part, I still seem to have trouble.  I'm currently preparing a reproducer for it.

**Comment by SamB** [comment]
So, while it would be great if someone could explain the problem with resolving `System` in b94868229881734f0f8570d514572a7a966fd997, I also notice that bumping all of the test projects to FX46 may not be the best move, since this *at least* leads to tons of warnings about not having that framework version around when building under/against Mono.

**Comment by SamB** [comment]
(Hmm, would a change like this require updating the NuGet zip?)

**Comment by SamB** [comment]
Hmm.  Looks like the `Reference` to `System` is getting removed by the `ResolveNuGetPackageAssets` target, shortly after the eponymous task returns.

In fact, I do believe the offending code is:

```
      <!-- Remove simple name references if we're directly providing a reference assembly to the compiler. For example,
           consider a project with an Reference Include="System", and some NuGet package is providing System.dll -->
      <Reference Remove="%(_ReferencesFromNuGetPackages.FileName)" /> 
```

because, according to my `msbuild.log`, the task output included:

```
  Output Item(s): 
      _ReferencesFromNuGetPackages=
          C:\Users\Sam\.nuget\packages\Microsoft.CodeAnalysis.Test.Resources.Proprietary\1.2.0-beta-20151016-11\lib\net45\Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll
                  NuGetPackageId=Microsoft.CodeAnalysis.Test.Resources.Proprietary
                  NuGetPackageVersion=1.2.0-beta-20151016-11
                  Private=false
          [Snipped a bunch of other items of the same exact form, just with different packages]
          C:\Users\Sam\.nuget\packages\xunit.extensibility.execution\2.1.0\lib\net45\xunit.execution.desktop.dll
                  NuGetPackageId=xunit.extensibility.execution
                  NuGetPackageVersion=2.1.0
                  Private=false
          mscorlib
          System.Xml (TaskId:551)
```
and the `%(_ReferencesFromNuGetPackages.FileName)` for that last item would be, if I'm not mistaken, `System`.

Can anyone direct me to the correct project for the package [`NuGet.MsBuild.Integration`](https://www.myget.org/feed/nugetbuild/package/nuget/NuGet.MsBuild.Integration) / the files `Microsoft.NuGet.targets` and `Microsoft.NuGet.Build.Tasks.dll`?

**Comment by Pilchie** [comment]
Tagging @jasonmalinowski, but this actually looks like a bug that was just filed on that task a few days ago. Unfortunately, the repo for it isn't public (yet).

**Comment by SamB** [comment]
@Pilchie:
I suspected that the source wasn't (yet) public; it didn't seem terribly likely that any such public repository would fail to turn up in the results for google searches for any of: the name of the assembly, the name of the targets file, OR the name of that NuGet package. Hopefully it gets open  -sourced soon. (Incidentally, any clue where I should ask for the sources to `Microsoft.Composition`?)

That task certainly isn't doing anything to reduce the ambiguity between filename references and simple name references.  And I think it could use more named variables; someone may have gone a bit overboard with Linq-to-JSON in there ...

**Comment by SamB** [comment]
Hmm, so it looks like retargetting the cross-platform test projects to FX4.6 is ... problematic.

I don't fully understand what's going wrong, but I can tell you (by looking at [this log](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1649/artifact/Binaries/TestRuntime.FX46.log) from the build of https://github.com/SamB/roslyn/commit/84047671f1ab11fc2beb314ce4382ed26cae5b48) that the `GetReferenceAssemblyPaths` target is hitting Microsoft/msbuild#191 in the following code:
```xml
    <PropertyGroup Condition="'$(_TargetFrameworkDirectories)' == '' and '$(AssemblySearchPaths)' != '' and '$(RemoveAssemblyFoldersIfNoTargetFramework)' == 'true'">
      <AssemblySearchPaths>$(AssemblySearchPaths.Replace('{AssemblyFolders}', '').Split(';'))</AssemblySearchPaths>
    </PropertyGroup>
```
(Which turns out to be the same place the original reporter of that bug saw it.)

But I'm not at all sure that an empty search path would be more useful than "System.String[]" is.

Leaving aside for the moment the fact that this particular build failure is occurring in TestRuntime.FX64, has anyone got any ideas about how to avoid the conflict between TestUtilities and TestUtilities.Desktop without bumping TestUtilities.Desktop to FX46?

Perhaps retargeting TestUtilities to something that doesn't imply FX46 in the .NETFramework case?

Perhaps some way to tell VS "yes, I know that project I'm referencing seems to imply a need for FX46, but I don't care -- reference it anyway"?

**Comment by jasonmalinowski** [comment]
@SamB: oops, forgot to reply to this one. Did you make any further progress, or is the conclusion "this is hard" and perhaps it's best not trying this for now?

**Comment by SamB** [comment]
@jasonmalinowski: Well, I can't figure out a portable framework to target that lets me make TestUtilities.Desktop use TestUtilities on Mono, at least not until Mono claims to support framework 4.6.

**Comment by Pilchie** [comment]
Given how much things have changed here with .NET Standard, I'm going to close this PR for now.

**Pull request closed without merging**
