### PR TITLE
Use MetadataReader to extract analyzer display names.

### PR DESCRIPTION
**Pull request by pharring**
Performance tests caught that we were loading VB assemblies in C# projects and vice versa.
This was due to a recent change to avoid using AssemblyName (because it doesn't exist on CoreCLR).
Instead, we can use our own metadata reader to extract the information we need.

### CODE REVIEW

**Comment by pharring** [comment]
Recommended reviewers: @heejaechang @tmat @mavasani 
FYI: @jaredpar

**Comment by jaredpar** [comment]
CC @tmeschter as well as he owns this type.

Given this is a display name it feels like digging through metadata is overkill.  Would a full path or just a file name work here?  Maybe I'm missing the intent of this value though.

**Comment by tmeschter** [comment]
@pharring, @jaredpar: As previously mentioned in my comment on that recent change (https://github.com/dotnet/roslyn/pull/1623#commitcomment-10434578) using just the file name without the directory or extension should work fine here. :-)

**Comment by pharring** [comment]
Note that using our MetadataReader here is no worse than what the CLR was doing with ```AssemblyName.GetAssemblyName(path)```, so perf-wise we should be back to where we were prior to the regression
Using the filename is what the fallback code does when the assembly name can't be extracted. Whether that's good enough to use always is open for discussion.

**Comment by jaredpar** [comment]
@pharring to clarify I agree with your comment.  It was more just seeing "how the sausage is made" that made me wonder if this process (which is the same as before) is worth it.  :) 

:+1:  for this or full name.

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by heejaechang** [comment]
@srivatsn @mavasani @shyamnamboodiripad @tmeschter  I am not sure what made us to use AssemblyName here. probably one of you guys made the decision. can we use filename here instead of assemblyname?

**Comment by tmeschter** [comment]
For all intents and purposes, the file name and the assembly name will always be the same thing; we can just use the file name.

**Comment by tmeschter** [comment]
And to clarify, I mean just the file *name*--not the full path, and not including the .dll extension.

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by mavasani** [comment]
@heejaechang @tmeschter I am pretty sure using just the file name will break this: http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/a1c94dbeedc15fae.html

it will no longer be a unique ID per analyzer reference. 

We need some other means to compute a unique ID per analyzer reference for IDE caches.

**Comment by heejaechang** [comment]
@mavasani but we are using Name instead of FullName. so like @tmeschter said it will be almost always same as just filename without extension.

**Comment by mavasani** [comment]
Note that I think that method is already broken as multiple analyzer references which have a null display will end up with same ID FeatureResources.Unknown. Additionally, its not good to use Display as a unique ID.
We can't use the full path as the unique ID as user might have replaced analyzer assembly with a newer version, and IDE will end up assuming it didn't change.
We really need a way to get the unique identity for any AnalyzerReference so we can maintain this map: http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/d9d5b4dea2c29b73.html that does de-duplication of same analyzer reference coming from multiple sources.

**Comment by heejaechang** [comment]
@mavasani we can't use full path since MEF and nugget installed analyzers (which are exactly same) will have 2 different full path. we need identity.

**Comment by tmeschter** [comment]
@mavasani @heejaechang I don't see why that would break. If you previously had an analyzer with the full path "C:\analyzers\Alpha.Beta.Gamma.dll" then `AnalyzerReference.Display` would previously have returned `Alpha.Beta.Gamma`, and with my proposed change would still return `Alpha.Beta.Gamma`.

`AnalyzerReference.Display` was only ever meant to be a friendly name for display to the user. It should never have been used as a unique identifier, regardless of how it is implemented.

**Comment by mavasani** [comment]
@tmeschter @heejaechang well that proves that this change won't break the IDE de-duplication logic as it was already broken, I thought earlier Display was returning the full AssemblyName.FullName. So I am fine with the proposed change here.

I'll open a separate issue to fix this: http://source.roslyn.io/Microsoft.CodeAnalysis.Features/R/a1c94dbeedc15fae.html

**Comment by tmeschter** [comment]
@mavasani @heejaechang I think we're talking about adding a new property, `AnalyzerReference.ID`.

**Comment by mavasani** [comment]
Opened #1710

**Comment by pharring** [comment]
I've merged this version so we can unblock performance tests.

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
