### PR TITLE
don't deploy extensions

### LINKED ISSUE #8077: [Test Failure] error VSSDK1031: Extension 'ConvertToAutoPropertyRefactoring.Microsoft.a95ab02d-0f23-4c9a-a8d2-b29692654076' could not be found. Please make sure the extension has been installed.
PR: [#8070](https://github.com/dotnet/roslyn/pull/8070) *changed meaning of closed file diagnostic option. now it is solely fo…* by @heejaechang
Failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/2991/

**Issue 1: VSSDK Build error**
error VSSDK1031: Extension 'ConvertToAutoPropertyRefactoring.Microsoft.a95ab02d-0f23-4c9a-a8d2-b29692654076' could not be found. Please make sure the extension has been installed. [d:\j\workspace\roslyn_prtest_win_dbg_unit32\src\Samples\CSharp\ConvertToAutoProperty\ConvertToAutoPropertyCS.csproj]

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #8077

@dotnet/roslyn-infrastructure 
@davkean

### CODE REVIEW

**Comment by TyOverby** [comment]
Please review.  This is important for keeping builds from failing.

**Comment by agocke** [comment]
Why don't we just change to not deploy extensions by default and require an explicit "true" arg?

**Comment by jmarolf** [comment]
:+1:

**Comment by davkean** [comment]
@agocke Because we want F5 to deploy the extensions.

**Comment by davkean** [comment]
:+1:

**Pull request merged**
