### PR TITLE
Add PublicAPI.Unshipped.txt so analyzer runs

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-ide for review.

**Comment by Pilchie** [comment]
Merging pro-actively, since it's just generally good to have this.

**Comment by jasonmalinowski** [comment]
@Pilchie: this looks like a bug in the analyzer; are we tracking that somewhere?

**Comment by Pilchie** [comment]
Tagging @tmeschter - My guess is the original design was to bail if there was no file, and it was just updated when we split the file for shipped and unshipped.  Does that sound right?

If so, I agree that it sounds like a bug if there is one file but not the other - we should issue a diagnostic for that case.

**Comment by tmeschter** [comment]
Right, the original idea was that if you didn't have a PublicAPI.txt file then you didn't have an API surface you wanted to manage and the analyzer should just turn itself off. That way we could simply add the analyzer to every project and just turn it on for the ones we cared about by adding the file.

I didn't split the file into the shipped and unshipped variants (I think that was @jaredpar) but I agree we should have both or neither.

**Pull request merged**
