### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160412-150020
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160412-150020 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit64 please.

**Comment by jasonmalinowski** [comment]
@AlekseyTs, running this locally doesn't reproduce the failure. The reason it failed a second time was because the lab just gave the cached results from the previous run. @jaredpar is looking into a way to opt out of that behavior nicely when trying to rerun tests like this.

**Comment by jasonmalinowski** [comment]
Otherwise, we think this is probably a dupe of #10132. We'll get another run in the lab and if we can get that green we'll then let this go through and continue focusing on #10132.

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by AlekseyTs** [comment]
Ignoring failure of prtest/win/vsi/p2 due to the same reason as for https://github.com/dotnet/roslyn-internal/pull/810. Also the test passed on the first test run.

**Pull request merged**
