### PR TITLE
Revert "Revert "Remove unused TS brace completion code""

### PR DESCRIPTION
**Pull request by MariaSolOs**
Reverts dotnet/roslyn#64574.

We should be able to delete this safely now.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by genlu — CHANGES_REQUESTED** [review]
I'm running a validation insertion [here](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=7310211&view=results). Will merge once it's confirmed this won't break our insertion. Thanks!

**Comment by MariaSolOs** [comment]
@genlu Sorry I was about to remove this code a bit too early again. Once we complete and insert https://dev.azure.com/devdiv/DevDiv/_git/TypeScript-VS/pullrequest/451409, I'll reactivate this PR.

**Comment by MariaSolOs** [comment]
Alright, I _really_ think we're good to go now.

**Comment by genlu** [comment]
Sorry I missed this. Our PR validation system is currently not working. I will unblock and let our current infraswat member decide when to merge. Thanks!

FYI @dibarbet

**Review by genlu — APPROVED** [review]

**Comment by dibarbet** [comment]
Holding off on this for the moment - we have some exisitng RPS regressions to resolve first.

**Comment by MariaSolOs** [comment]
@dibarbet no worries. This is just to clean things up, not extremely urgent.

**Comment by dibarbet** [comment]
Going to merge this

**Pull request merged**
