### PR TITLE
Fixes for 13228 17761 20708

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
This PR contains PR#19319 and an alternative fix for Issue #20701.

### CODE REVIEW

**Comment by sharwell** [comment]
Fixes #20701

**Comment by sharwell** [comment]
@AdamSpeight2008 Sorry about the noise; I edited your post to test a GitHub feature but then I removed by edits and restored things to precisely what you wrote originally.

**Comment by AdamSpeight2008** [comment]
@sharwell Could you retest `windows_release_vs-integration_prtest` as don't think I can trigger it.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot restest windows_release_vs-integration_prtest please.

**Comment by AdamSpeight2008** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Comment by AdamSpeight2008** [comment]
@dotnet/roslyn-compiler please review, thanks.

**Comment by AdamSpeight2008** [comment]
Any feedback at all?

**Comment by cston** [comment]
#20701 has already been fixed. Other changes for that issue, this PR appears to be a duplicate of #19319.

**Pull request closed without merging**
