### PR TITLE
Revert pull requests #7526 and #7692

### PR DESCRIPTION
**Pull request by KevinH-MS**
These are causing excess allocations and an elapsed time regression in Picasso "Rebuild" in RPS.

#7692 is not necessarily problematic itself, but I can't revert #7526 without also reverting the former because the code is intertwined, and I don't understand it well enough to tease them apart.

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @mavasani

**Comment by srivatsn** [comment]
Looks fine. @heejaechang, since @mavasani is on vacation, can you take a look here and see what we need to do to fix the perf issues here?

**Comment by heejaechang** [comment]
@KevinH-MS these changes seem nothing to do with Rebuild? are you sure the issue is due to this change rather than just timing issue like deserializing syntax trees?

**Comment by KevinH-MS** [comment]
@heejaechang that is possible, but someone else will need to try to diagnose the root cause.  I can e-mail you links to the traces.

**Comment by KevinH-MS** [comment]
Per offline conversation with @heejaechang, I'm going to file for an exception on this (argument is that the allocations don't cause an increase in VM, and the elapsed time regression in Rebuild seems like it could have just been testcase noise that coincided with this change).

**Comment by mavasani** [comment]
Thanks Heejae/Kevin. #7526 shouldn't cause any drastic allocation increase, I'll take a quick look to see allocations.

**Pull request closed without merging**
