### PR TITLE
Update cross-platform.md

### PR DESCRIPTION
**Pull request by agocke**
Gives instructions on using the Makefile for building (instead of trying to construct a patched Mono + MSBuild + NuGet + targets files).

### CODE REVIEW

**Comment by Phrohdoh** [comment]
>This guide will walk you through setting up a Linux / Mac box for Roslyn development. 

This line is now incorrect.
The guide boils down to "Run `make`."
Sorry if I'm being a too nit-picky.

**Comment by agocke** [comment]
@Phrohdoh You're not wrong :)

**Comment by Phrohdoh** [comment]
As far as I am aware Roslyn doesn't take `-` prefixed flags, only `/` (switches).

```diff
diff --git a/docs/infrastructure/cross-platform.md b/docs/infrastructure/cross-platform.md
index 9d5be31..cbc344a 100644
--- a/docs/infrastructure/cross-platform.md
+++ b/docs/infrastructure/cross-platform.md
@@ -44,12 +44,12 @@ error CS0006: Metadata file 'System.Workflow.Runtime.dll' could not be found
 ##### Fix: 
 
   This is because `csc.exe` by default references the `csc.rsp` file next to it. This is the Windows response file, so not all
-  assemblies are present when running on Mono. Pass the `-noconfig` option to ignore this response file.
+  assemblies are present when running on Mono. Pass the `/noconfig` option to ignore this response file.
   
 ##### Output:
 
-error CS0041: Unexpected error writing debug information -- 'The requested feature is not implemented
+error CS0041: Unexpected error writing debug information -- 'The requested feature is not implemented'
 
 ##### Fix:
```

**Pull request merged**
