### PR TITLE
fixed typos mentioned in #2786 and #2787

### PR DESCRIPTION
**Pull request by romansp**
This PR fixes typos mentioned in #2786 and #2787 issues.

### CODE REVIEW

**Comment by pharring** [comment]
:+1:

**Comment by Maxwe11** [comment]
Why not to squash commits?
And also [close issue via commit message](https://help.github.com/articles/closing-issues-via-commit-messages)

**Comment by Pilchie** [comment]
Actually, if you're going to do this, could you make the text for `SyntaxReference` into a cref tag while you're at it?

**Comment by romansp** [comment]
Squashed commits and added cref tags.

**Comment by Maxwe11** [comment]
@dotnet-bot test this please

**Comment by romansp** [comment]
@dotnet-bot test this please

**Comment by Pilchie** [comment]
Thanks!  LGTM.

**Pull request merged**
