### PR TITLE
Remove unneeded ProjectReferences in Workspaces layer

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
Failure seems unrelated:

```
Assert.Equal() Failure
↓ (pos 0)
Expected: Class TestProj.العربية123\r\nThis is an XML···
Actual:

```

```
   at Roslyn.VisualStudio.IntegrationTests.VisualBasic.BasicQuickInfo.International() in /_/src/VisualStudio/IntegrationTest/IntegrationTests/VisualBasic/BasicQuickInfo.cs:line 40
```

Closing and re-opening for new build

**Comment by sharwell** [comment]
❓ Are the removed references still included as transitive references, or are they now omitted from the build output for this project?

**Comment by Youssef1313** [comment]
@sharwell I haven't thought about this when I made the change. I can still see `Microsoft.CodeAnalysis.CSharp.Features.dll` under `artifacts\bin\Microsoft.CodeAnalysis.VisualBasic.Workspaces.UnitTests\` when I run `dotnet build` under `VisualBasicTest` directory. So they're still included.

My actual intention was to be completely independent on it. This test project shouldn't need `CSharp.Features` at all.

**Comment by sharwell** [comment]
> This test project shouldn't need CSharp.Features at all.

AdhocWorkspace in the workspaces layer uses the features layer via reflection. Removing the features layer from the build can change the behavior of the workspaces layer, even if there are no apparent references to it.

https://github.com/dotnet/roslyn/blob/171fceda8fb7aa445a605d3eda8df1c816e4db4e/src/Workspaces/Core/Portable/Workspace/Host/Mef/MefHostServices.cs#L112-L120

My preference is to continue including these for most accurate representation of runtime common cases.

**Comment by Youssef1313** [comment]
@sharwell I'm confused a little, how can AdhocWorkspace get affected by change in a unit test project. I can understand this if the *workspaces test project* was using the deleted references via reflection, but not if the *actual workspaces project* does so.

Am I missing something?

**Comment by sharwell** [comment]
@Youssef1313 The first order impact is the test code could change behavior. The runtime code would only be impacted if the test/runtime discrepancy resulted in a bug occurring in a test gap.

**Comment by Youssef1313** [comment]
> The first order impact is the test code could change behavior.

- Does this apply to the other PRs in other layers?
- Do you have any example in mind where test code can change behavior so I could add a test to prevent the same mistake in future?

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
If the tests still pass when the CSharp dependencies are removed (and actually prevented from deploying) then I'm OK with removing this. Customers absolutely can create tools that only deploy VB and not C# via our NuGet packages, so it's not like that's an unsupported scenario.

That all said, do we know why the C# assemblies are still being deployed? I had thought we still had some build rules that were supposed to enforce the closure here had to be complete.

**Comment by Youssef1313** [comment]
I may work on similar changes but on a little bit bigger scale using the new "Remove unused references" feature. Also will give more focus to shipping packages and see if their dependencies could be reduced. @jasonmalinowski @sharwell Should we close?

**Comment by CyrusNajmabadi** [comment]
@sharwell Thoughts on what to do with this PR?

**Comment by sharwell** [comment]
I'm OK with just closing this one

**Pull request closed without merging**
