### PR TITLE
Merge dev15-rc2 into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15-rc2 into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-dev15-rc2-into-master20161117-160049
git reset --hard upstream/master
git merge upstream/dev15-rc2
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-dev15-rc2-into-master20161117-160049 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by OmarTawfik** [comment]
@CyrusNajmabadi can you please take a look at the conflicts? they seem to originate from https://github.com/dotnet/roslyn/commit/f0ea86f36afc7fb5d34f427c6a0c53a83d386fc1.

**Comment by OmarTawfik** [comment]
@dotnet-bot test vsi please

**Comment by OmarTawfik** [comment]
@genlu are these the transient vsi errors that you've been investigating?

**Comment by genlu** [comment]
Seems some pop-up dialog interfered with tests.

@dotnet-bot retest  windows_vsi_p1_open_prtest please

**Comment by genlu** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please

**Comment by DustinCampbell** [comment]
Closing this PR to work on the most recent.

**Pull request closed without merging**
