### PR TITLE
Fix the condition on passing BuildWithSkipAnalyzers marker file to FUTD

### LINKED ISSUE #56370: FastUpToDate check always failed on VS2022 with RunAnalyzersDuringBuild=false
**Version Used**: 
VS2022 Preview3.1 + dotnet sdk 6.0.100-preview.7.21379.14

**Steps to Reproduce**:

1. dotnet new console;
2. Add `<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>` to the csproj file;
3. Open it, and build it more than once;

**Expected Behavior**:
It should not be rebuild since nothing is changed, this makes `RunAnalyzersDuringBuild=false` even more slow than `RunAnalyzersDuringBuild=true`.
>Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped

**Actual Behavior**:
> FastUpToDate: Input 'xxx.csproj.BuildWithSkipAnalyzers' is newer (2021/8/23 17:54:35) than earliest output 'xxx.pdb' (2021/8/23 17:52:15), not up to date. 
...
>Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #56370

`<%ProjectName%>.BuildWithSkipAnalyzers` marker file is touched/created for all builds executed with `/skipAnalyzers` flag. We want this marker file to be considered as a custom additional compile input and fast up-to-date check input for builds where we are executing analyzers. We already had the correct condition on `CustomAdditionalCompileInputs`, this fix ensures the check is also made for `UpToDateCheckInput` for FUTD.

### CODE REVIEW

**Comment by rainersigwald** [comment]
I'm not sure this is the right approach. I don't understand why this file is listed as an input when it's an output that is produced by the build.

I think a cleaner design would be to add a `.BuiltWithAnalyzers` marker file for _full_ builds, and list it as an output. Then it would be ignored for implicit builds, but full builds could trigger if they are up to date _except_ analyzers (because the output would be older). Is that possible?

**Comment by mavasani** [comment]
> I don't understand why this file is listed as an input when it's an output that is produced by the build.

I tried to mimic the approach used for `.CoreCompileInputs.cache` file here: https://github.com/dotnet/msbuild/blob/c88325c7859bcd282ff1fae14ed95936e051e1c3/src/Tasks/Microsoft.Common.CurrentVersion.targets#L3660-L3690

That file is also an output/generated file for that target, but is added to `CustomAdditionalCompileInputs` for ensuring correct incremental builds. This approach seems to work fine, except for this bug. I can switch to your suggested approach if you feel strongly about it.

**Comment by mavasani** [comment]
@rainersigwald I have opened #56446 to track your suggestion. I hope to get to it soon after addressing other high priority issues on my plate. I do hope to get the current PR with trivial fix to existing design merged in sooner - I hope that is fine.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for reviews.

**Comment by rainersigwald** [comment]
> I do hope to get the current PR with trivial fix to existing design merged in sooner

Works for me.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by mavasani** [comment]
Ping @dotnet/roslyn-compiler for reviews

**Review by cston — APPROVED** [review]

**Review by chsienki — APPROVED** [review]

**Pull request merged**
