### PR TITLE
Remove some hacks when we were on RTM

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This is resurrecting an old branch I had written but couldn't commit.

Review: @dotnet/roslyn-infrastructure, @dotnet/roslyn-ide

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Can I get some signoff from @dotnet/roslyn-infrastructure? Since I know some investigations are being done in related areas here, I don't want to churn that unnecessarily.

**Comment by davkean** [comment]
:+1:

**Comment by amcasey** [comment]
LGTM

**Pull request merged**
