### PR TITLE
Delete unneeded skipped test

### LINKED ISSUE #44859: Unskip tests if record clone becomes user-writeable
There are a number of skipped tests that should be enabled if we make Clone writeable.

### PR DESCRIPTION
**Pull request by Youssef1313**
Closes #44859
The test and the linked issue were before deciding to disallow Clone members in records.

Related to dotnet/csharplang#3652

### CODE REVIEW

**Review by 333fred — COMMENTED** [review]
LGTM. @dotnet/roslyn-compiler for a second review.

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Actually, @Youssef1313, there are a bunch of tests in [RecordsTests.cs](https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs) as well. Could you add them?

**Review by 333fred — APPROVED** [review]
Although we are thinking about allowing user customization of clone during C# 10, I think it's likely fine to delete these now and write targeted tests for the scenarios we come up with during development. LGTM (commit 2), @dotnet/roslyn-compiler for a second review.

**Comment by Youssef1313** [comment]
I'm okay if you want to keep the tests and update them for C# 10 later.

**Comment by jcouv** [comment]
I'd rather keep the tests, but I'm fine if someone else wants to sign-off.

**Comment by 333fred** [comment]
I'll defer to Julien then, Thanks Youssef, but we'll keep these in anticipation of enabling struct records.

**Pull request closed without merging**
