### PR TITLE
Revert "Make compilation outputs available via a workspace service

### PR DESCRIPTION
**Pull request by dpoeschl**
(Original PR #34809)

This change broke some unit tests on the VS side with a `System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.` 

See https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/179585 for details.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dpoeschl Was this worked out via binary search? I admit it's not clear to me why this would have been the break...

**Comment by dpoeschl** [comment]
@jasonmalinowski Yes, basically a binary search. It's not clear to me either. Dumping some info:

2 consecutive commits:
- [b252adb](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/179583?_a=overview): Passing (immediately before the original PR here)
- [3bdbd56](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/179585?_a=overview): Failing (the commit for the original PR here)

Additionally, I made a passing build using latest master-vs-deps but with just this change reverted: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/179605?_a=overview

**Comment by dpoeschl** [comment]
FYI @jasonmalinowski @tmat @jinujoseph I've reopened this against master-vs-deps, since we're running out of time and don't have a resolution on fixing the problem on the VS side.

**Comment by dpoeschl** [comment]
XAML team is attempting a solution on the VS side. This is on hold unless really needed later.

**Pull request closed without merging**
