### PR TITLE
Remove source for FakeSign and reference from Roslyn.sln

### PR DESCRIPTION
**Pull request by agocke**
/cc @dotnet/roslyn-compiler @dotnet/roslyn-infrastructure @jaredpar

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by JoshVarty** [comment]
Where has this source gone to? Does it have another home now?

**Comment by agocke** [comment]
@JoshVarty We built the functionality directly into the compiler, so FakeSign wasn't needed anymore

**Comment by JoshVarty** [comment]
:+1:

**Pull request merged**
