### PR TITLE
Stop overbuilding SemanticSearch.ReferenceAssemblies

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/source-build/issues/4390

cc @jaredpar

### CODE REVIEW

**Comment by tmat** [comment]
@ViktorHofer Thanks for the fix! We couldn't figure out what the issue is.

**Comment by tmat** [comment]
@ladipro How come msbuild lock detection was not able to find out that the file is locked by msbuild itself? Is it missing anything?

**Comment by ViktorHofer** [comment]
Feel free to merge. I don't have permissions.

**Review by jaredpar — APPROVED** [review]

**Comment by ladipro** [comment]
> @ladipro How come msbuild lock detection was not able to find out that the file is locked by msbuild itself? Is it missing anything?

Competing writes to `obj` files, such what's in the description of the referenced issue, come from CSC so that's outside of MSBuild; it would have to be implemented in the compiler. For files in `bin`, so typically copying with the `Copy` task, my guess is that the operation is too fast that by the time the process detection logic runs, the file is no longer locked.

As mentioned in the issue, we're working on a double-writes analyzer. Interestingly though, binlog viewer already has double-writes analysis and it didn't catch this. It deserves a closer look because we were going to model MSBuild analysis after the viewer.

**Comment by ladipro** [comment]
Oh yes, currently the output path itself is used as a key which explains why it doesn't detect double writes in this case. I would naively expect the data to live in a list (i.e. no need to de-dup with a HashSet). Cc @KirillOsenkov for insights.

https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/b56ebfb2caea11a3ffad279aa25ddd0f67a115da/src/StructuredLogger/Analyzers/DoubleWritesAnalyzer.cs#L72,L96

**Comment by tmat** [comment]
@ladipro Makes sense in this case - I think we already have a work item to expose the process locking detection logic to tasks, so that csc could also report the process name using msbuild APIs.

**Comment by KirillOsenkov** [comment]
I filed a viewer bug https://github.com/KirillOsenkov/MSBuildStructuredLog/issues/779 to deal with this case.

**Pull request merged**
