### PR TITLE
Add option 'Show remarks in Quick Info'

### PR DESCRIPTION
**Pull request by sharwell**
C#:

image

Visual Basic:

image

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
@sharwell I don't see where this hooks up to the feature itself.

**Comment by sharwell** [comment]
> I don't see where this hooks up to the feature itself.

🤦‍♂️

**Comment by sharwell** [comment]
OK here's the behavior with the option checked:

image

And here's the behavior with it unchecked:

image

**Comment by jinujoseph** [comment]
@mikadumont for review on text

**Comment by alrz** [comment]
wait, we don't have fade unused variables/parameters option?

**Comment by sharwell** [comment]
> wait, we don't have fade unused variables/parameters option?

@alrz I'm not sure what you mean by this.

> ... for review on text

@mikadumont I'm still waiting on this part.

**Comment by mikadumont** [comment]
@sharwell text looks good to me!

**Pull request merged**
