### PR TITLE
Refactor HostedRuntimeEnvironment

### PR DESCRIPTION
**Pull request by jaredpar**
The HostedRuntimeEnvironment code was beginning to show it's age and is the source of some hard to track down Jenkins issues (#6190).  I decided to invest some time this weekend to:

- Improve the rigor of the constraint checking in the code.  In many cases we had assumptions which were never verified that the test suite was regularly violating.  
- Divide the responsibility of many of the times into single purpose types. 
- Simplify the overall scenario: Rather than trying to reuse AppDomain values (which was the source of several bugs) always use a clean AppDomain for every test. 
- Reduce the amount of data being transfered between AppDomains to only the values necessary to create the runtime.  This saved us from unnecessarily marshalling values like mscorlib on every test. 

Note: i still haven't re-enabled the PEVerify functionality.  As part of doing this work I found several issues which would lead to PEVerify problems hence I'm hopeful it is fixed a a result.  But I want to enable that as a separate PR that I can do multiple runs on to ensure the problem is truly fixed.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure, @davkean, @VSadov

**Comment by tmat** [comment]
Re "Rather than trying to reuse AppDomain values (which was the source of several bugs) always use a clean AppDomain for every test."

This will likely significantly slow down tests. The AppDomain reusal was added specifically to speed up emit tests. Have you measured impact of this change?

**Comment by jaredpar** [comment]
@tmat I also paired this change with some optimizations on how we passed data between AppDomains.  In particular I found ways to avoid passing mscorlib, and other prominent DLLs, every time.  As result the marshalling overhead for a run is significantly lower.  

> Have you measured impact of this change?

Tests actually run faster on my machine after this change.  The difference is negligible but it is consistently a few seconds faster.  I'm seeing similar results on Jenkins.

**Comment by tmat** [comment]
OK, sounds good then.

**Comment by jaredpar** [comment]
@tmat hmm, i was looking at the overall test run time.  Specific suites like Emit have increased about ~1 minute with this change (7 - ~8/9) after this change.

**Comment by jaredpar** [comment]
@tmat profiled a bit and I do see that creating RuntimeAssemblyManager in the AppDomain is a significant perf hit.  Working on putting some pooling support back in.

**Comment by tmat** [comment]
Yeah. Note that most tests produce uniquely named assemblies (named using a guid). AppDomains are only needed when we emit compilations with conflicting assembly names across tests.

**Comment by jaredpar** [comment]
@tmat yep.  An early experiment of the pooling on my machine takes the running time of VB Emit from 450 seconds to 230 (faster than before).

**Comment by jaredpar** [comment]
@tmat here are results of the new pooling code I added

Before my change

- Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll  6:51
- Roslyn.Compilers.CSharp.Emit.UnitTests.dll  6:52

After my change

- Roslyn.Compilers.CSharp.Emit.UnitTests.dll  4:58
- Roslyn.Compilers.VisualBasic.Emit.UnitTests.dll  6:18

Seeing similar wins on my local runs.  Looks like the new pooling code is producing real wins here.

**Comment by tmat** [comment]
Cool

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
