### PR TITLE
Add monodevelop to the condition that generates IVTs

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide @dotnet/roslyn-infrastructure 

This currently works, since the item doesn't exist in any file that doesn't *also* have one of the other items, but fixing for correctness' sake.

**Comment by Pilchie** [comment]
@jaredpar the determinism build failed with:

>13:02:44 Killing all build-related processes
13:02:45 ERROR: The process "MSBuild.exe" with PID 1800 could not be terminated.
13:02:45 Reason: The operation attempted is not supported.

13:02:45 Build failed with ERRORLEVEL 1
13:02:45 Killing all build-related processes
13:02:45 ERROR: The process "msbuild.exe" not found.
13:02:45 Build step 'Execute Windows batch command' marked build as failure

Any ideas?

**Comment by jaredpar** [comment]
retest determinism please

**Comment by jaredpar** [comment]
@Pilchie that looked like a hung MSBuild process on the machine.  Similar to what @tmat saw the other day as well on his run.

**Comment by Pilchie** [comment]
retest windows_determinism_prtest  please

**Comment by Pilchie** [comment]
Doh - missed refreshes and started another test.

**Pull request merged**
