### PR TITLE
Add skipped test for bug in SyntaxTree.GetChanges() found through investigating https://github.com/dotnet/roslyn/issues/320

### PR DESCRIPTION
**Pull request by mavasani**
Add skipped test for bug in SyntaxTree.GetChanges() found through investigating https://github.com/dotnet/roslyn/issues/320

### CODE REVIEW

**Comment by mavasani** [comment]
Merging this as its a test only change.

**Comment by heejaechang** [comment]
:+1: 

by the way, the diff affects a lot of stuff in IDE and it even used for like formatting that runs on UI thread. (for example, VB auto commit)

so, it might be good idea for us to add compiler perf test for tree diffing. let me open a bug

**Comment by heejaechang** [comment]
added bug #459

**Comment by theoy** [comment]
(note, bug #463 is now tracking the functional issue with SyntaxTree.GetChanges()., so that #320 can be more focused on the diagnostic scenario)

**Pull request merged**
