### PR TITLE
Fix NuGet problems

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This started by me noticing that when I restored NuGet packages at home, a packages folder was written *outside* my Roslyn root enlistment. Chasing it, I noticed a many problems. This deletes the problems.

### CODE REVIEW

**Comment by diryboy** [comment]
Yes, noticed that also.

**Comment by davkean** [comment]
Looks like you broke restore for samples?

**Comment by jasonmalinowski** [comment]
When I moved where these restored, the locations the internal test app had baked into it's project files need updating. Confusing, it's actually _using_ code in a namespace "Microsoft.Samples" that has nothing to do with our stuff.

**Comment by jmarolf** [comment]
:+1:

**Comment by Pilchie** [comment]
This can be closed now, right @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Well, this is still "broken" in that we have a pointer to the parent folder, but stuff is now project.json based in the public world. Once we move the syntax visualizer public (I have a branch on that now), then this would just merge in cleanly.

**Comment by jasonmalinowski** [comment]
This PR is too old for me to still trust it. @jaredpar is fixing some of this right now so I'll take a look next week if it's still evil.

**Pull request closed without merging**
