### PR TITLE
Merge latest bits from 'main' branch into extensions branch

### PR DESCRIPTION
**Pull request by jcouv**
Relates to test plan https://github.com/dotnet/roslyn/issues/66722

The last commit resolves conflicts.
@gundermanc @CyrusNajmabadi The two updated LSIF tests were pretty cryptic to me so I just updated the baseline but wasn't able to tell whether it's good.

### CODE REVIEW

**Comment by gundermanc** [comment]
> Relates to test plan #66722
> 
> The last commit resolves conflicts. @gundermanc @CyrusNajmabadi The two updated LSIF tests were pretty cryptic to me so I just updated the baseline but wasn't able to tell whether it's good.

@jcouv, it looks fine to me at a glance. The integer arrays shouldn't change but I'd expect any changes to Roslyn classification type names to appear in the capabilities node for the LSIF generator.

**Comment by CyrusNajmabadi** [comment]
I'm on vacation. And @jasonmalinowski knows lsif better than I do :-)

**Review by AlekseyTs — APPROVED** [review]
Changes under Compilers LGTM, assuming CI is passing.

**Review by AlekseyTs — APPROVED** [review]

**Comment by jcouv** [comment]
@jasonmalinowski Please take a look at a couple of IDE/LSIF tests updated. Thanks

**Review by jasonmalinowski — APPROVED** [review]
IDE changes look good.

**Pull request merged**
