### PR TITLE
Move to new MSBuild drop

### PR DESCRIPTION
**Pull request by jaredpar**
Moves xcopy MSBuild to 15.7.4

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @tmat, @dotnet/roslyn-infrastructure

**Comment by jaredpar** [comment]
Spanish run failed with flaky test Microsoft.CodeAnalysis.MSBuild.UnitTests.NetCoreTests.TestOpenProject_NetCoreMultiTFM_ProjectReferenceWithReversedTFMs

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by tmat** [comment]
thanks

**Pull request merged**
