### PR TITLE
Fix issue link

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Review by cston — APPROVED** [review]

**Comment by Youssef1313** [comment]
image

image

Anyone knows what's going on?

**Comment by jmarolf** [comment]
@Youssef1313 branch is locked for unrelated reasons

**Comment by Youssef1313** [comment]
@jmarolf I see other PRs are starting to get merged now, but this one still shows "6 approving reviews are required". Probably GitHub is stuck somehow?

**Comment by 333fred** [comment]
> @jmarolf I see other PRs are starting to get merged now, but this one still shows "6 approving reviews are required". Probably GitHub is stuck somehow?

PRs are not starting to get merged into main. Main is still locked.

**Comment by 333fred** [comment]
Thanks for the ping @Youssef1313, this is merged now.

**Pull request merged**
