### PR TITLE
Prevent static local functions from capturing local functions

### PR DESCRIPTION
**Pull request by svick**
Fixes https://github.com/dotnet/roslyn/issues/38129.

Also fixes a typo in a comment that I found when looking for tests that check for CS8421.

### CODE REVIEW

**Comment by gafter** [comment]
Investigating what the right upstream branch is.

**Comment by gafter** [comment]
@svick can you please rebase to `release/dev16.4-preview1`?  You may have to cherry-pick your changes on top of that branch and force-push to avoid pulling all the things from `master` that are on your branch.

**Comment by svick** [comment]
@gafter Done.

**Comment by 333fred** [comment]
@svick sorry to keep having you change things, but a note of this break needs to be added to https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/Compiler%20Breaking%20Changes%20-%20post%20VS2019.md, since we won't be taking this for the initial release of 8.0.

**Comment by svick** [comment]
@333fred No need to apologize for that, that's what PRs are for. 🙂 Too bad the breaking change couldn't be avoided.

**Comment by 333fred** [comment]
@svick thanks for the contribution!

**Pull request merged**
