### PR TITLE
Fix VB features impacted by IOperation change

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/70004

### CODE REVIEW

**Comment by 333fred** [comment]
Only one commit? Are you feeling ok @CyrusNajmabadi?

**Comment by CyrusNajmabadi** [comment]
@333fred there will be a merge commit once aleksey's change goes in :)

**Comment by AlekseyTs** [comment]
@CyrusNajmabadi #69873 Is merged, it disabled the failing tests. Please make sure to re-enable them in context of this PR.

**Review by ToddGrun — APPROVED** [review]
:shipit:

**Pull request merged**
