### PR TITLE
add missing codebase to VS for System.Xml.ReaderWriter.dll

### PR DESCRIPTION
**Pull request by heejaechang**
many vsi tests are failing due to missing xml documents. this should fix the issue.

### CODE REVIEW

**Comment by heejaechang** [comment]
@jasonmalinowski @tmat @dotnet/roslyn-infrastructure can you take a look?

**Comment by heejaechang** [comment]
I think this is test issue so I don't need approval?

**Comment by heejaechang** [comment]
can I get another sign off?

**Comment by tannergooding** [comment]
LGTM. Ideally, we would have a separate VSIX that adds these binding redirects and facades, rather than including them in the core VSIX (one that is only deployed on F5 and is not inserted into VS).

**Comment by heejaechang** [comment]
@tannergooding, @tmat said these codebase attribute won't be needed in latest ML drop since it works like you said above, but Jenkins and other people who still use old drop need these attribute for now. so we are adding them here.

at some point in future before RTM, I guess you should remove all those attributes.

**Comment by heejaechang** [comment]
opened an issue

**Comment by tannergooding** [comment]
I was indicating a more ideal solution may be to have a separate package that is explicitly for adding these binding redirects and facade assemblies.

As is, we are adding binding redirects and facade assemblies to our VSIX package, which can create weird issues with probing paths, ngen, and assembly resolution.

Having a 'PortableFacades' vsix (in addition to our inserted SWR package) would provide a better experience and ensure we aren't accidentally adding bad binding redirects in our insertion.

**Comment by heejaechang** [comment]
@tmat ? how do you think about @tannergooding suggestion?

**Comment by heejaechang** [comment]
tagging @MattGertz 

I just checked in fix for vsi tests

**Comment by jasonmalinowski** [comment]
@tannergooding: indeed, these all should be moved to the portable facades package and we depend on that, but there's other moving parts that involves.

:+1: to the change.

**Pull request merged**
