### PR TITLE
Update toolset compilers and diagnostics

### PR DESCRIPTION
**Pull request by tmeschter**
This commit moves us forward to version 1.0.0-rc2-20150313-01 of Microsoft.Net.ToolsetCompilers and Microsoft.Net.RoslynDiagnostics.

Most of the changes are to the PublicAPI.txt files, as the DeclarePublicAPI analyzer now takes into account the types of fields, events, and methods.

The other changes all involve specify a `TaskScheduler` when calling `Task.Factory.StartNew` and `Task.ContinueWith` as required by RS0018.

### CODE REVIEW

**Comment by tmeschter** [comment]
@agocke @mavasani @balajikris @dpoeschl @amcasey @KevinH-MS @jaredpar Could you take a look at this, please?

**Comment by amcasey** [comment]
The strongest statement I can make is that I don't see any obvious problems.

**Comment by agocke** [comment]
The targets file and packages.config file change LGTM -- I don't fully understand the public API change, but I don't see anything wrong with it.

**Comment by tmeschter** [comment]
@agocke Previously, the DeclarePublicAPI analyzer didn't consider the type of a field, event, or method as part of the API. So you could change the return type of a method, for example, and it wouldn't catch it.

In the newer version Microsoft.Net.RoslynDiagnostics it *does* consider the return type, so now it needs to be captured by the PublicAPI.txt document.

**Pull request merged**
