### PR TITLE
Filter type parameters in where clause

### LINKED ISSUE #65528: Autocompletion offers type parameters that already have a `where` constraint
**Version Used**: VS 2022 17.5 Preview 1

**Steps to Reproduce**:

Invoke autocompletion at the marked locations.

```csharp
class C1<T1, T2> where T1 : class where $$ {}
class C2<T1> where T1 : class where $$ {}
```

**Expected Behavior**:
1. The autocompletion inserts `T2` as that's the only type parameter without an existing type constraint.
2. Nothing happens because there are no autocompletion items.

**Actual Behavior**:
1. The autocompletion list opens, offering both `T1` and `T2`. image
2. `T1` is automatically inserted.

In both cases inserting `T1` is not useful as there cannot be multiple type parameter constraints clauses for any type parameter (error CS0409).

### PR DESCRIPTION
**Pull request by Rekkonnect**
Closes #65528

### CODE REVIEW

**Review by CyrusNajmabadi — CHANGES_REQUESTED** [review]
This doesn't follow the recommendation from the original issue.

**Comment by Rekkonnect** [comment]
I kinda skipped the comments below the issue tbh, now I see the discussion. Frankly speaking, I'm in favor of filtering down the remaining type parameters available for including in `where`. Misguiding the user into an error is frustrating. If we decide to simply preselect the first type argument that does not have a where clause, I'll adjust this PR to reflect this decision. But in my opinion this is jumping through hoops to reduce the number of typing mistakes to a non-zero probability.

**Comment by CyrusNajmabadi** [comment]
Intellisense is not about guiding the user to correctness. It's about speeding things up and helping avoid misspellings by completing out to the chosen item. I write code on all sorts of different directions, and it drives me nuts when something is filtered out of the list I still want to use.

> Misguiding the user into an error is frustrating. 

Being in an error state is the normal place for code to be.  And it's super normal to stay in that state a while while you're modifying code.

**Comment by Rekkonnect** [comment]
IntelliSense also filters out impossible recommendations in modifier lists where the same modifier does not appear twice (at least in most cases), so the concept is not entirely new (its a first in symbol recommentations if I'm not mistaken).

> it drives me nuts when something is filtered out of the list I still want to use

Why would you want to use the same type parameter in multiple where clauses? Other than intentionally writing bad code to test.

**Comment by CyrusNajmabadi** [comment]
> Why would you want to use the same type parameter in multiple where clauses? 

Because i'm restructuring my code.  Being in an intermediate state may be invalid, but has no bearing on the final state i want to be in.  It's entirely normal to rewrite something that already exists *without* it being in-situ.  For example, i may be reordering/reconstraining type parameters as i update a method.  I may decide that i just want to write the new constraint in a different location directly, not as a move.

> Other than intentionally writing bad code

Your value judgements on what are good/bad are not mine.  I am ok going through bad states that make sense to me along the way to a final good state.  It's very normal for me to rewrite constructs above/below existing constructs *so i can see what i did before*, while then modifying things.  Forcing me to actively delete a construct in order for this to work is not something i find pleasant.

**Comment by Rekkonnect** [comment]
I see, your workflow is vastly different from mine.

Can't we then just introduce an option which toggles this filtering on/off? I don't know if there already exists such a system and how extensible it is. What fits one most is completely strange to another, so options are the greatest approach.

**Comment by Rekkonnect** [comment]
Closing this one as more discussion is needed.

**Pull request closed without merging**
