### PR TITLE
Fix issue where we overly aggressively removed xml doc comment trivia.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/13436

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @MattGertz

**Comment by MattGertz** [comment]
Approved pending signoffs/tests.

**Comment by dpoeschl** [comment]
:+1:

**Pull request merged**
