### PR TITLE
Embed a local definition of IVsSolution7 to avoid loading .Next dll early

### PR DESCRIPTION
**Pull request by Pilchie**
Tag @jasonmalinowski @mavasani @KevinH-MS @dotnet/roslyn-ide @dotnet/roslyn-perf @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by Pilchie** [comment]
retest windows_eta_open_prtest please - hit CreatePkgDef error on http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/4338/

**Comment by Pilchie** [comment]
Pushed changes to allow running on VS 2015 - oops.  retest vsi please.

**Comment by Pilchie** [comment]
retest windows_debug_unit32_prtest please - hit CreatePkgDef error in http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/4269/

**Comment by Pilchie** [comment]
retest windows_debug_unit32_prtest please - CreatePkgDef error on http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/windows_debug_unit32_prtest/4270/

**Comment by dpoeschl** [comment]
LGTM

**Comment by jasonmalinowski** [comment]
Also just added a quick hack to limit MyGet feed name lengths, as @Pilchie's logically-named branch is too long for us to upload packages to MyGet for.

**Comment by mavasani** [comment]
@dotnet retest perf_correctness_prtest please

**Comment by jasonmalinowski** [comment]
Going to merge this because we've inserted the fix directly and wouldn't want to lose the fix on the next insertion.

**Pull request merged**
