### PR TITLE
Disable NuGet package restore in Visual Studio for Roslyn.sln

### PR DESCRIPTION
**Pull request by sharwell**
Infrastructure only change.

This change results in a 50+% reduction in the amount of data allocated during solution load.

Time to fully load Roslyn.sln _after_ running Restore.cmd (i.e. NuGet restore is a NOP):

* Without this change: 1:37-1:51
* With this change: 1:29

### CODE REVIEW

**Comment by tmat** [comment]
Do we have an issue tracking the root of the problem?

**Comment by tmat** [comment]
Seems like it should be possible to check whether all projects in a solution have been restored very quickly.

**Comment by emgarten** [comment]
> Time to fully load Roslyn.sln after running Restore.cmd (i.e. NuGet restore is a NOP):

This is likely being treated as a full restore and not a noop by NuGet due to:
https://github.com/NuGet/Home/issues/4627

You can check by letting VS run the restore fully, then closing and re-opening the solution. That should definitely be a noop.

It looks like https://github.com/NuGet/Home/issues/4627 is going into 15.6, but the fix hasn't been inserted yet.

**Comment by tmat** [comment]
If it's indeed gonna be available in 15.6 then I'd rather not merge this PR.

**Comment by jaredpar** [comment]
> If it's indeed gonna be available in 15.6 then I'd rather not merge this PR.

I'd rather merge this PR and then undo once we confirm the bug is fixed. VS is unusable with NuGet at this point.

**Comment by sharwell** [comment]
@tmat I believe you may be looking at the impact of this change in the wrong way.

Currently users are disabling NuGet for the entire VS installation through Tools &rarr; Options in order to work on Roslyn. This configuration change limits the disabling to only occur for solutions in this repository. The net impact of this change is users will be able to *enable* NuGet for more IDE scenarios, improving overall usage.

**Comment by tmat** [comment]
OK. Fair enough. 👍

**Pull request merged**
