### PR TITLE
fix base image for perf correctness

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by jasonmalinowski** [comment]
Should this have been updated with the rest of them? Is there a reason at this point we don't just put our image name in a variable and use it for all the jobs? We are routinely making this same mistake.

**Comment by TyOverby** [comment]
@jasonmalinowski: yeah, it should have been updated like the rest.  I'd be willing to group all of these machine names together under some variables.

Thoughts @jaredpar ?

**Comment by TyOverby** [comment]
@dotnet-bot test windows_debug_unit32_prtest please

**Comment by TyOverby** [comment]
@dotnet-bot test microbuild_prtest please

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by TyOverby** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please

**Comment by TyOverby** [comment]
auto-retry vsi

**Comment by TyOverby** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest  please

**Comment by jasonmalinowski** [comment]
@TyOverby The integration failures are known right now, feel free to merge this at this point.

**Comment by TyOverby** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest  please

**Comment by TyOverby** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest  please

**Pull request merged**
