### PR TITLE
Make sure buffers are returned to the pool

### PR DESCRIPTION
**Pull request by tmat**
Reduces total memory allocations of EnC diffing.

Fixes https://github.com/dotnet/roslyn/issues/55076
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1338956

### CODE REVIEW

**Comment by tmat** [comment]
@davidwengier PTAL

**Review by davidwengier — APPROVED** [review]
If the buffers weren't being returned the pool, would Allocate have thrown `InvalidOperationException`? If so, this could fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1338956 too ?

**Comment by tmat** [comment]
Seems like the fix is not quite correct. Need to look into it more.

**Comment by tmat** [comment]
@dibarbet PTAL

**Review by dibarbet — APPROVED** [review]

**Pull request merged**
