### PR TITLE
Change language version for VB 15.6 to 15.5

### PR DESCRIPTION
**Pull request by jcouv**

### CODE REVIEW

**Comment by sharwell** [comment]
This would have been so much less confusing if we just skipped 15.4. Sigh.

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for review. This is adjusting the VB version 15.6 to the new name "15.5".

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler Could I get a second review? Simple change to language version (15.6 -> 15.5). Thanks

**Comment by cston** [comment]
LGTM

**Pull request merged**
