### PR TITLE
Backport #49365 to use RTM sdk to 16.8 branch

### PR DESCRIPTION
**Pull request by dibarbet**
Backport https://github.com/dotnet/roslyn/pull/48770/

### CODE REVIEW

**Comment by dibarbet** [comment]
@jasonmalinowski looks like the global.json changes are already present in the branch

**Review by JoeRobich — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]

**Comment by sharwell** [comment]
I'm confused. This looks like my change to update to RTM bits and not the change to update to RC2.

**Comment by dibarbet** [comment]
> I'm confused. This looks like my change to update to RTM bits and not the change to update to RC2.

Yeah, I'll update the title - the change to update to rc2 didn't work so we're trying this one.

**Comment by dibarbet** [comment]
@jasonmalinowski @JoeRobich re-requesting review since this is so different

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@dibarbet It's passing at least which is the biggest endorsement. :smile:

**Pull request merged**
