### PR TITLE
Removed unnecesary InitialTargets in Microsoft.Net.Compilers.props

### PR DESCRIPTION
**Pull request by VSadov**
Removed unnecesary InitialTargets in Microsoft.Net.Compilers.props

This unblocks compiler package on Core

### CODE REVIEW

**Comment by VSadov** [comment]
"Could not write to file" failures

**Comment by VSadov** [comment]
Test this please

**Comment by agocke** [comment]
Have you tested that this works? (You can build the NuGet packages by running `msbuild src/NuGet/NuGet.proj`)

**Comment by VSadov** [comment]
@agocke - I think it would be easier to merge, make a build and see. 
It can not make it much worse since the package is not working anyways and it is a way to be absolutely sure. And we can revert if needed since this is in a branch.

**Pull request merged**
