### PR TITLE
Remove Workspaces.sln from the tree

### PR DESCRIPTION
**Pull request by davkean**
No one uses it, and just adds more confusion and
extra things that we need to touch as we add/remove
projects.

### CODE REVIEW

**Comment by davkean** [comment]
tag @agocke @dotnet/roslyn-ide

**Comment by agocke** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by jmarolf** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1::+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by brettfo** [comment]
retest win please

**Comment by brettfo** [comment]
Ignore the vsi test failures as my last comment accidentally started those tests and opted to abort them to save lab resources.

**Comment by brettfo** [comment]
retest prtest/win/dbg/unit32 please
retest prtest/win/dbg/unit64 please
(re-launching these tests due to a build break being fixed)

**Comment by dpoeschl** [comment]
:+1::shipit::+1::shipit::+1::shipit::+1::shipit::+1::shipit::+1::shipit::+1::shipit::+1:

**Comment by davkean** [comment]
Filed https://github.com/dotnet/roslyn/issues/6319 for the unit32/unit64 failures.

retest prtest/win/dbg/unit32 please
retest prtest/win/dbg/unit64 please

**Comment by davkean** [comment]
retest this please

**Comment by davkean** [comment]
vsi failures are time-outs - they shouldn't have been run in the first place.

**Comment by diryboy** [comment]
LOL

**Pull request merged**
