### PR TITLE
Test only change: Enable VB PDB conversion tests that involve hoisted locals

### PR DESCRIPTION
**Pull request by tmat**
Upgrades to the new version of PDB converter that implements conversion of state machine hoisted locals and enables previously skipped VB tests.

### CODE REVIEW

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Comment by tmat** [comment]
Test failure: https://github.com/dotnet/roslyn/issues/20991

**Comment by tmat** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by jcouv** [comment]
@tmat Since this is targeting master, I assume it's for 15.5. Please confirm or rebase PR.

**Comment by tmat** [comment]
Correct, 15.5 - it's test only.

**Pull request merged**
