### PR TITLE
Merge "target-typed new" feature in 16.7p1

### PR DESCRIPTION
**Pull request by jcouv**
This PR is a merge of "target-typed new" and latest master, resolving a conflict. Targeting master to merge the "target-typed new" feature into 16.7p1.

### CODE REVIEW

**Comment by jcouv** [comment]
FYI @jaredpar

**Comment by jcouv** [comment]
Merged for 16.7p1!
Thanks @alrz!!!

FYI @CyrusNajmabadi

**Comment by jcouv** [comment]
@alrz Could you send me your email address or other mechanism by which I could contact you privately? Thanks
My address is jcouv@microsoft.com and you can DM me at https://twitter.com/jcouv for instance.

**Comment by alrz** [comment]
@jcouv Not active on twitter right now but you can reach me on gitter and via email: habibi.alireza at outlook,com.

Thank you!

**Pull request merged**
