### PR TITLE
Unnamed completions: add tests for nullforgiving operator handling

### PR DESCRIPTION
**Pull request by MaStr11**
Follow up to #47511

Tests for the nullable operator (?) are present, but null-forgiving (!) operator tests are missing. The tests are not exhaustive, but show that in simple cases the null forgiving operator is handled as expected.

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by MaStr11** [comment]
@CyrusNajmabadi ready to merge (only one unrelated ci test failure).

**Comment by MaStr11** [comment]
@CyrusNajmabadi RTM

**Comment by MaStr11** [comment]
@CyrusNajmabadi This plain PR can be merged.

**Review by CyrusNajmabadi — APPROVED** [review]

**Pull request merged**
