### PR TITLE
Mark methods as Obsolete.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/9054

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide  again.  Sorry about the mixup.

**Comment by CyrusNajmabadi** [comment]
retest prtest/win/dbg/unit32 please

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4473/
// Retest reason: https://github.com/dotnet/roslyn/issues/9298

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 

This is PublicAPI feedback work.

**Pull request merged**
