### PR TITLE
Remove 'ID' argument from WorkItem.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This argument is redundant, and just super super annoying to always have to populate when you add a WorkItem attribute to a test. Removing as it is redundant and could be computed from the issue uri if anyone actualy ever needed this.

The old constructor is kept around as there are tests which violate the appropriate pattern here (either having mismatching id/uri, or not having any id in the uri at all).

Note: attributes were only fixed if hte ID was exactly present in the URI. Anything not matching that was kept as is. This was only a few hundred cases that we can consider what to do with in the future.  The regex used was: `WorkItem\(([0-9]+), ".*?\b\1\b.*?"\)`.  The `\1` backreference ensures the id is actually found as a full token in the uri string.  

Can be reviewed a commit at a time.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
> attributes were only fixed if hte ID was exactly present in the URI. 

I think that there is no good reason to "fix" anything. New tests can use new constructor, but I see no good reason to create a lot of churn when nothing is broken.

**Comment by CyrusNajmabadi** [comment]
> but I see no good reason to create a lot of churn when nothing is broken.

Consistency is a virtue. I don't see churn here. Just removal of redundancy.  Regardless, you can choose to take this or not based on your own particular weights around this sort of thing.

**Comment by AlekseyTs** [comment]
> Regardless, you can choose to take this or not based on your own particular weights around this sort of thing.

I prefer to see no changes under Compilers because, I personally, see zero value in the changes offered in this PR.

**Comment by AlekseyTs** [comment]
Apart from adding a new attribute constructor, of course. Zero value in changing existing tests.

**Pull request closed without merging**
