### PR TITLE
Add indent guides for C# and VB blocks

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/14126

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @roslyn-ide.  Note: tests have not been written yet.

**Comment by CyrusNajmabadi** [comment]
Tagging @paulvanbrenk @vladima @minestarks   There are some tiny tweaks here around the BlockSpans API.  Should be very simple to absorb.  Let me know if there are any concerns.

**Comment by CyrusNajmabadi** [comment]
Retest windows_debug_unit64_prtest

**Comment by CyrusNajmabadi** [comment]
Retest windows_debug_unit64_prtest please

**Comment by CyrusNajmabadi** [comment]
Retest windows_debug_unit64_prtest please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit64_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit64_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest  windows_release_unit32_prtest please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by paulvanbrenk** [comment]
One question, are they enabled by default or should we mimic the options you introduced for TypeScript?

**Comment by CyrusNajmabadi** [comment]
> One question, are they enabled by default or should we mimic (some of) the options you introduced for TypeScript?

Hey Paul,

So here's how the API works.  We now have one system for producing the data that feeds into both Outlining and the new 'Indent Guides'.  You feed into both systems by producing 'BlockSpans' from a BlockStructureService.  The BlockSpan has two interesting fields that are the individual language's responsibility to provide:

1. 'IsCollapsible'.  True for items you want collapsible outlining spans for.  
2. 'Type'.  One of the BlockType values.  If it has the value "Nonstructural" then you do not get indent guides.  Any other value will produce indent guides.  The reason for having many different values is that we may show differences in teh guides in the future (for example, colorizing loop guides differently than type guides).

Roslyn has also now created 3 options for outlining and 3 options for indent guides to allow users to customize the C# and VB behavior.  You can find these options in BlockStructureOptions.  You can choose to expose these options to your users in your UI, or you can choose not to.  Because of our history, I was a bit concerned about how much of a change it might be to start outlining and providing indent guides for so many constructs.  So i'm exposing the options for C# and VB in case users want to dial back the experience.  You can decide to do the same.  Or you can just decide on your own defaults and leave it at that.

If you do expose the options, the onus is on you to query for them and produce the right sort of results.  For example, if you expose the "Show outlining for declaration level constructs" and the user turns it off, then you should set 'IsCollapsible' to false for your declaration BlockSpans.

Currently, there is a helper to do this.  However it is not easily accessible.  I will send a followup PR making it an available static member somewhere if you just want to take the same behavior as C# and VB.  The reason this behavior is not 'baked into' the core logic for all languages is that it's not necessarily the case that all languages have the same sorts of constructs and want them to operate in the same manner.

For example, C# has 'nested functions' which it does *not* want to think of as 'declaration level'.  But perhaps TS *does* want to think of them in that way.  

Does this explanation make sense?  Do you need any more info?  

Thanks!

**Comment by paulvanbrenk** [comment]
@CyrusNajmabadi yes, that makes total sense... so I'm corrent to understand the options only drive the data you send to the outlining infrastructure. So we can use our own existing option infrastructure and don't have to opt-in to the Roslyn infrastructure you created. 

Thanks!

**Comment by CyrusNajmabadi** [comment]
Correct.  The options are, pun intended, totally optional for you to make use of.

**Comment by paulvanbrenk** [comment]
Tagging @aozgaa

**Comment by CyrusNajmabadi** [comment]
Note: I've exposed some static helpers on AbstractBlockStructureProvider if you want to get similar behavior to C# and VB.

**Comment by CyrusNajmabadi** [comment]
Closing in favor of https://github.com/dotnet/roslyn/pull/14269

**Pull request closed without merging**
