### PR TITLE
Update System.Reflection.Metadata to 1.2.0 release

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@davkean @dotnet/roslyn-infrastructure

**Comment by tmat** [comment]
@MattGertz Ask mode PR (stabilization)

**Comment by davkean** [comment]
@tmat Please make sure you file two bugs; 1 for 2.0 (Preview) and 1 for 1.2 (RTM) to actually make sure these get inserted.

**Comment by tmat** [comment]
Done: https://github.com/dotnet/roslyn/pull/9578 and https://github.com/dotnet/roslyn/issues/9580.

**Comment by tmat** [comment]
retest vsi please

**Comment by davkean** [comment]
@dotnet-bot test vsi please

**Comment by davkean** [comment]
@tmat We can't take this change - we've just forced a dependency for our packages on a NuGet version that hasn't shipped.

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
retest vsi please

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/vsi/p3 please
Timeout cloning repo from GitHub. Retry the job.

**Pull request merged**
