### PR TITLE
Make test unconditional

### PR DESCRIPTION
**Pull request by tmat**
Fixes build break introduced by the merge of https://github.com/dotnet/roslyn/pull/37025.

### CODE REVIEW

**Comment by tmat** [comment]
@CyrusNajmabadi FYI

**Comment by CyrusNajmabadi** [comment]
Thanks :)

**Comment by JoeRobich** [comment]
Is this change preferred to https://github.com/dotnet/roslyn/pull/37163

**Comment by tmat** [comment]
@JoeRobich Actually, it uncovered a bug. Let's disable the test completely for now. I'll follow up.

**Pull request closed without merging**
