### PR TITLE
Port https://github.com/dotnet/roslyn/pull/11398 over to SymbolKeys. …

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
The previous fix only addressed symbol ids.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by rchande** [comment]
:+1: 
I added test for SymbolId, is that worth porting too?

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@dotnet-bot test vsi please.

**Pull request merged**
