### PR TITLE
Fix issue with missing System.Collections.Immutable.dll...

### PR DESCRIPTION
**Pull request by KevinH-MS**
...in Roslyn.VisualStudio.InteractiveComponents.vsix.

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @amcasey @ManishJayaswal

**Comment by ManishJayaswal** [comment]
Based on the explanation, looks good to me.

**Comment by amcasey** [comment]
Does this problem affect our other vsixes?

**Comment by amcasey** [comment]
:+1:

**Comment by KevinH-MS** [comment]
@amcasey the only other project where it matters (```VisualStudioSetup.csproj```) does specify ```<Private>true</Private>``` for this reference, but wasn't immediately clear to me that was the reason.

**Comment by KevinH-MS** [comment]
**Additional note:** the addition of ```<Private>true</Private>``` is not strictly necessary for the ```System.Reflection.Metadata``` reference, but I added it just in case we ever decide to GAC that assembly.

**Comment by jasonmalinowski** [comment]
How does this help? If the System.Reflection.Metadata was in the GAC, we still have build problems in that your build environment no longer matches the runtime environment. I'd expect we should be explicitly referencing the file path, and letting the improvements to RAR's CopyLocal logic help us here.

**Comment by jasonmalinowski** [comment]
Also, why is interactive components picking up it's own copy? It should be able to reuse the copy Roslyn is already shipping (in fact, since only one can be loaded...there can't be two!)

**Comment by KevinH-MS** [comment]
The InteractiveHost process needs to deploy its own copy of the compilers when we deploy as a VSIX.  In a *real* install, everything will be under PrivateAssemblies (or in the GAC) and we'll use the binaries from there.  However, in the "InstallDogfood" case, we've ripped all those binaries out, so we need copies for InteractiveHost.exe (a separate process from VS) to load.  It can't use the ones VS uses, because it can't probe in all the extension folders for binaries.

**Comment by KevinH-MS** [comment]
To your point, the build environment (normal VS install) does ***not*** match the runtime environment ("InstallDogfood" scenario).

**Pull request merged**
