### PR TITLE
Enable warnAsError for correctness builds

### PR DESCRIPTION
**Pull request by JoeRobich**
These changes setup the Correctness Test leg to fail when the formatting analyzer reports warnings. Other test legs will ignore these warnings and run unit tests as expected. Local builds (`.\build.cmd` and VS) will report warnings but not fail the build.

### CODE REVIEW

**Comment by JoeRobich** [comment]
[Build logs](https://dev.azure.com/dnceng/public/_build/results?buildId=375658) showing a failing correctness build due to formatting errors.
```
src\Workspaces\Core\Portable\AddImports\AbstractAddImportsService.cs(84,1): error IDE0055: (NETCORE_ENGINEERING_TELEMETRY=Build) Fix formatting
src\Workspaces\Core\Portable\AddImports\AbstractAddImportsService.cs(145,121): error IDE0055: (NETCORE_ENGINEERING_TELEMETRY=Build) Fix formatting
src\Compilers\CSharp\Portable\BoundTree\UnboundLambda.cs(620,13): error IDE0055: (NETCORE_ENGINEERING_TELEMETRY=Build) Fix formatting
src\Compilers\CSharp\Portable\BoundTree\UnboundLambda.cs(868,17): error IDE0055: (NETCORE_ENGINEERING_TELEMETRY=Build) Fix formatting
Build failed.
Cmd.exe exited with code '1'.
```

**Comment by JoeRobich** [comment]
@sharwell & @jaredpar  please take a look

**Comment by jaredpar** [comment]
Overall looks good. Think we need to also make the following changes:

When building the desktop legs we should not pass warnAsError and should pass skipAnalyzers. That way the desktop leg is focused on running teests while the correctness leg is focused on build correctness including analyzers, formatting, etc ....

[https://github.com/dotnet/roslyn/blob/master/azure-pipelines.yml#L40](https://github.com/dotnet/roslyn/blob/master/azure-pipelines.yml#L40)

We **should** be able to enable MSBuild's warn as error without qualification now here 

[https://github.com/dotnet/roslyn/blob/master/eng/build.ps1#L231](https://github.com/dotnet/roslyn/blob/master/eng/build.ps1#L231)

**Comment by JoeRobich** [comment]
[Build logs](https://dev.azure.com/dnceng/public/_build/results?buildId=381972&view=logs&jobId=cba777ed-fe28-5aeb-50da-6c54bc98ee08) showing failing correctness leg

**Comment by JoeRobich** [comment]
@jaredpar Did I get those changes right?

**Comment by RikkiGibson** [comment]
I have been instructed by the author to hit the button

**Pull request merged**
