### PR TITLE
Update signing cert used for EE.ResultProvider

### PR DESCRIPTION
**Pull request by JoeRobich**
Move off SHA1 cert

### CODE REVIEW

**Comment by JoeRobich** [comment]
@tmat please take a look

**Comment by jaredpar** [comment]
@tmat we brought this up in teams last week and no one responded (you were directly mentioned). Signed builds are blocked. How can we make progress here fairly speedily?

**Comment by jasonmalinowski** [comment]
Yeah I'd say we merge this and worry about getting the verification asynchronously. We can hold merging insertions if this isn't right...

**Comment by JoeRobich** [comment]
This CI (which is green) for this PR since GitHub is conflating it with another PR. https://dev.azure.com/dnceng/public/_build/results?buildId=292882

**Pull request merged**
