### PR TITLE
Convert file encoding to utf-8.

### PR DESCRIPTION
**Pull request by diryboy**
Fix the files in the second part of #6643, it's just encoding change, no actual behavior changes.

### CODE REVIEW

**Comment by diryboy** [comment]
retest win/dbg/unit32 please

**Comment by diryboy** [comment]
retest this please

**Comment by diryboy** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by jaredpar** [comment]
:+1:

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by gafter** [comment]
:+1:

**Pull request merged**
