### PR TITLE
Remove content SHA from generated files

### PR DESCRIPTION
**Pull request by jcouv**
Fixes https://github.com/dotnet/roslyn/issues/25433

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Out of curiosity, why?

**Comment by jcouv** [comment]
It doesn't serve a purpose and caused some problems in a recent PR.

**Comment by jaredpar** [comment]
@CyrusNajmabadi 
It's an artifact left over from when we generated them on every build vs. only on demand. It used to use `DateTime.Now` but now I switched to SHA's when we got determinism working. Now though it doesn't really help with anything.

**Comment by CyrusNajmabadi** [comment]
Make sense.  Thanks!

**Pull request merged**
