### PR TITLE
Move portable sources from TestUtils to TestUtils2

### PR DESCRIPTION
**Pull request by tmat**
Moving stuff around to separate portable from non-portable test utilities.

### CODE REVIEW

**Comment by tmat** [comment]
FYI @agocke Not changing anything to portable yet, just moving stuff around.

**Comment by tmat** [comment]
@agocke Just a tiny little changeset :)

**Comment by agocke** [comment]
LOL, :+1: I think, it's hard to tell what went where.

**Comment by tmat** [comment]
Yeah, more advance code review tooling would be needed for that. That said, it's better to just look at the result not the diff.

**Pull request merged**
