### PR TITLE
Don't run the IteratorRewriter on BaseMethodWrapperSymbols (#12676)

### PR DESCRIPTION
**Pull request by jcouv**
This is inserting commit https://github.com/dotnet/roslyn/commit/89be9817421125b2b69ff93ebbb640e396c78a90 (from PR https://github.com/dotnet/roslyn/pull/12676) back into preview 4.

### CODE REVIEW

**Comment by jcouv** [comment]
CC @jaredpar @Pilchie @cston FYI
I will merge as soon as checks are green.

**Comment by Pilchie** [comment]
Please *don't* merge until we hear back from shiproom.

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
Okay - let's merge this.

**Pull request merged**
