### PR TITLE
Updating the solution to reflect recent changes

### PR DESCRIPTION
**Pull request by davkean**
Visual Studio is continually asking me to modify the solution, this because we've 
made some changes manually in the solution itself and because configurations
are different between solution and project files.

Sync'ing changes so that we can stop excluding Roslyn.sln from our changes.

### CODE REVIEW

**Comment by davkean** [comment]
Tag @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
Hah, this is similar to jasonmalinowski/roslyn@906e289efc5cd3589e3878f89d58898865e4d5b0 that I wrote a few hours ago. It looks like you caught the project configuration mismatches that I didn't. Can you retarget this pull request against stabilization? We'll need this there since that's where anybody from the community will be branching off of when they're making pull requests atop Update 1.

I'm also curious how this happened. Is there a bug here somewhere in the VS solution manager? :+1: otherwise.

**Comment by davkean** [comment]
This happened probably due to two reasons:

1. Jared, probably manually edited the solution file when he split the tests into two projects.
2. Someone changed a project file without also checking in/updating the solution. We have multiple solutions, so that's probably easy mistake to make.

**Comment by davkean** [comment]
I assumed master will roll into stabilization once Update 1 ships, no?

**Pull request merged**
