### PR TITLE
Add missing using directive

### PR DESCRIPTION
**Pull request by JoeRobich**

### CODE REVIEW

**Review by Cosifne — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Review by ryzngard — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
I'm curious what caused this...

**Comment by Cosifne** [comment]
> I'm curious what caused this...

@CyrusNajmabadi 
Looks like is caused by this PR https://github.com/dotnet/roslyn/pull/56307

**Comment by JoeRobich** [comment]
Looks like there were two PRs that changed this file recently.

The using directive was then removed 19 hours ago in https://github.com/dotnet/roslyn/pull/56326
Use of StorageOptions was added 16 hours ago in https://github.com/dotnet/roslyn/pull/56307

It seems both CI ran independently and were correct with the files as they were at the time. They then both merged and this build break was introduced.

**Comment by JoeRobich** [comment]
Merging as we have green builds again.

**Pull request merged**
