### PR TITLE
Add the updated lock files

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by agocke** [comment]
@jasonmalinowski @jmarolf @amcasey @DustinCampbell FYI

Just waiting to see if this passes on Linux/Mac or if I need to update their NuGet packages.

**Comment by jmarolf** [comment]
:+1

**Comment by DustinCampbell** [comment]
thanks! :+1:

**Pull request merged**
