### PR TITLE
Fix doc bug on SyntaxToken.GetPrevioustoken

### LINKED ISSUE #54126: Documentation bug in Microsoft.CodeAnalysis.SyntaxToken
//
        // Summary:
        //     Gets the token that **follows** this token in the syntax tree.
        //
        // Returns:
        //     The token that **follows** this token in the syntax tree.
        public SyntaxToken GetNextToken(bool includeZeroWidth = false, bool includeSkipped = false, bool includeDirectives = false, bool includeDocumentationComments = false);
        //
        // Summary:
        //     Gets the token that **precedes** this token in the syntax tree.
        //
        // Returns:
        //     The next token that **follows** this token in the syntax tree.
        public SyntaxToken GetPreviousToken(bool includeZeroWidth = false, bool includeSkipped = false, bool includeDirectives = false, bool includeDocumentationComments = false);

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #54126

### CODE REVIEW

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review on a small community PR.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

**Comment by jcouv** [comment]
Merged/squashed. Thanks @Youssef1313

**Pull request merged**
