### PR TITLE
Test that verifies predefined keywords are in completion for switch cases

### LINKED ISSUE #14218: Predefined type keywords should be recommended after case.
**Version Used**: 
25722.02

**Steps to Reproduce**:

``` C#
object o = null;
switch (o)
{
    case $$
};
```

type `int` at `$$`

**Expected Behavior**:
`int` is in the completion list and inserted.

**Actual Behavior**:
It isn't and something else gets inserted instead.

Now that type patterns can be used in switch cases, we need to recommend the predefined type keywords in this context.

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #14218

### CODE REVIEW

**Comment by OmarTawfik** [comment]
//cc @dotnet/roslyn-compiler @Pilchie @gafter @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-ide  can I get another sign off?

**Comment by CyrusNajmabadi** [comment]
It's a test-only change.  You're good to merge.

**Pull request merged**
