### PR TITLE
loose up a bit on what happens when build error report on us errors o…

### PR DESCRIPTION
**Pull request by heejaechang**
…n a file that doesn't exist in roslyn solution but have error code we own.

we used to treat them as project level errors but that made us to sometime show one entry for multiple error reports.

now, we will at least show all of them, but things like double click will not work since we don't know which document it is.

### CODE REVIEW

**Comment by heejaechang** [comment]
related issue 
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/93786?fullScreen=false

and
https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=205144

I believe real fix should be done by xaml (not giving us file that doesnt exist in our solution from build). I am already talking with them on the issue.

**Comment by heejaechang** [comment]
can you code review @srivatsn @mavasani

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/616/
// Retest reason: not test related issue.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/617/
// Retest reason:

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/618/
// Retest reason:

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_eta_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_eta_open_prtest/621/
// Retest reason:

**Comment by mavasani** [comment]
👍

**Comment by srivatsn** [comment]
👍

**Comment by heejaechang** [comment]
retetst  windows_eta_open_prtest  please

**Comment by heejaechang** [comment]
retest windows_eta_open_prtest please

**Pull request merged**
