### PR TITLE
Use captured foreach variable

### PR DESCRIPTION
**Pull request by Therzok**
Given the behaviour of lambda captures with foreach variables, the code might be hiding a bug.

cc @mavasani @CyrusNajmabadi

### CODE REVIEW

**Comment by sharwell** [comment]
In this case I don't think it makes a difference. The `localProject` temporary could be removed.

**Comment by Therzok** [comment]
> In this case I don't think it makes a difference. The `localProject` temporary could be removed.

Yup, you are right! I was mistaking it with the scenario where the variable is declared outside the loop.

Removed the redundant local.

**Comment by Therzok** [comment]
Heh, it seems like the _foreach_ scenario existed, but it was changed in C# 5.0.

**Comment by CyrusNajmabadi** [comment]
Agreed with @sharwell's assessment.  And, even if this was captured, this is safe to do :)

**Pull request merged**
