### PR TITLE
Moved SaveEventsService GetService calls to constructor import statements

### LINKED ISSUE #15143: SaveEventsService is causing a deadlock during MEF construction
SaveEventsService is making `GetService` calls during construction. This ends up causing a deadlock because COM calls are being made, which request the UI thread, and the UI thread is waiting for the SaveEventsService to be constructed. This appears to be relatively rare, but something about migrated xproj solutions causes it to happen more often. The fix is to import the correct types in the constructor for SaveEventsService, instead of importing a service provider and calling `GetService`.

### PR DESCRIPTION
**Pull request by 333fred**
This fixes #15143. @dotnet/roslyn-ide for review. @Pilchie, I think this is something we should take for RC2, is dev15-rc2 open?

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Are there other cases we should fix up to prevent this?  this is making me feel that all types that import a ```SVsServiceProvider serviceProvider``` are suspect.

**Comment by 333fred** [comment]
@CyrusNajmabadi probably

**Comment by Pilchie** [comment]
@dpoeschl - is this related to the deadlock you have assigned about CPS projects with context deadlocks?

@333fred - Tagging @MattGertz for ask mode approval for RC2, you'd need to update your base branch though.

**Comment by Pilchie** [comment]
Is the real problem here that we shouldn't be `Import`'ing this on a background thread?

**Comment by 333fred** [comment]
@Pilchie thanks. @MattGertz, this should fix a deadlock we're seeing after migration, although as @CyrusNajmabadi pointed out, we should go through the codebase and see if there's any other cases that we need to change to use this methodology as well.

**Comment by 333fred** [comment]
@Pilchie I believe that's the general issue, @lifengl's advice was to simply not perform calls that can result in COM activity in the constructor.

**Comment by MattGertz** [comment]
This meets the bar.  Going forward through the endgame, I want to make sure that we always have ASK mode template info filled out here, though, so please add that -- then when we have the CR signoffs, I will approve.

**Comment by 333fred** [comment]
@Pilchie @CyrusNajmabadi I went though the codebase looking for SVsServiceProviders being used in the constructor, and made a list of the ones I found in the original issue. Looks like there are 23 suspect uses.

**Comment by 333fred** [comment]
@dotnet-bot retest windows_release_unit32_prtest please

Bad run link: https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_unit32_prtest/2147/. Some kind of xunit or runtime failure, @genlu is looking into it.

**Comment by 333fred** [comment]
@MattGertz let me know if I should expand on anything. This fixes #15143. Because we were importing a service provider in the constructor and then importing the things with it, instead of directly MEF-importing the things we needed in the first place, a deadlock was possible. This is a very localized change to the constructor of an internal API, and should have low potential impact.

**Comment by CyrusNajmabadi** [comment]
Note: Kevin's question is important.  In general, we try to solve these issues by not importing types like this on hte BG.  instead, we do the importing at a well known UI point (sometimes during package load) to avoid this sort of issue.  Can we not do that here?

**Comment by 333fred** [comment]
Cyrus, that seems like a fragile solution to me. If I decide that I need this type in a different context, what tells me I need to import it on the UI thread? It seems like a much safer solution to just import the types we need.

**Comment by CyrusNajmabadi** [comment]
>  If I decide that I need this type in a different context, what tells me I need to import it on the UI thread? 

You don't need to care.  It will have already been imported on the UI thread because we front load it so that it gets created there.

My primary concern is codebase consistency.  Every new concept and new approach to solving the same problems incurs a cognitive tax and an additional maintenance burden.  Sometimes it's more appropriate to follows hte patterns and practices of the rest of the code to make things clearer and easier to work with moving forward.

**Comment by 333fred** [comment]
Well, the more we do that, the larger start-up costs we incur. That doesn't seem like it will scale very well.

**Comment by CyrusNajmabadi** [comment]
We avoid that by deferring until after startup :)   See LoadComponentsInUIContextOnceSolutionFullyLoaded

**Comment by 333fred** [comment]
I'm not familiar enough with the lifetime of this component, are we guaranteed to not need it until after the solution is loaded?

**Comment by 333fred** [comment]
I'm worried about this, because the scenario in which this hang occurs is that the project doesn't appear to have been fully loaded. Therefore, I don't think putting this in that list will be effective.

**Comment by jasonmalinowski** [comment]
So I find this change surprising because I was unaware that you can directly request VS services from the MEF catalog. How long has that been the case for? And why does that not create a deadlock because MEF would still have to request the COM service the usual?

For the record #14354 is currently implementing the work to move the Visual Studio workspace itself off, which I would have expected is the larger change you want. What was causing the SaveEventsService to be composed in the first place?

**Comment by jasonmalinowski** [comment]
Looking at the dump, the reason this is happening is because VisualStudioWorkspace is pulling on SaveEventsService, and that is fundamentally unsafe to do until #14353 is merged in. Even if this change does fix the deadlock, the workspace task queue will probably initialize on the wrong thread and cause downstream crashes. This change would need the rest of #14354 to be correct.

**Comment by 333fred** [comment]
@jasonmalinowski and I talked offline. I'll add this class to the list of items we need to go over in #15148.

**Pull request closed without merging**
