### PR TITLE
Add a test for an already fixed crash due to missing Microsoft.CSharp.Dll reference.

### LINKED ISSUE #18320: "csc.exe" exited with code -2146232797 / Unit Test project / await on dynamic
**Version 14.0.25420.01 Update 3**: 

**Steps to Reproduce**:

1. Create unit test project.
2. Add the following class.
```
    [TestClass]
    public class Class1
    {
        public dynamic GetResponse()
        {
            return null;
        }
        public async void GetResponseTest()
        {
            var result = await GetResponse();
        }
    }
```
3. Build the project.

**Expected Behavior**:
May be this is not the correct way of coding. But the other project types (class library project) compile successfully without an error.
Expecting to compile same as the class library project or give a compilation error with details to fix. 

**Actual Behavior**:
Compile error only with the description.
> "csc.exe" exited with code -2146232797

### PR DESCRIPTION
**Pull request by AlekseyTs**
Closes #18320.

@dotnet/roslyn-compiler Please review a test only change.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5042/

Java / Jenkins hit a remoting error that caused the build to fail.

**Comment by AlekseyTs** [comment]
Test windows_release_vs-integration_prtest please

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-infrastructure windows_release_vs-integration_prtest fails on aPR that added a compiler test.
https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5045/

**Comment by AlekseyTs** [comment]
Test windows_release_vs-integration_prtest please

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-infrastructure It looks like VS integration tests are broken or flaky:

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5065/
	Test Result (2 failures / +1)
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlPropertyInCode
	
Identified problems

CLR test failure (only matches the first, see "Latest Test Result" link for the rest)

Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpWinForms.ChangeControlProperty [FAIL]
Indication 1 

MSBuild Error

error MSB3073: The command ""Binaries\Release\Exes\RunTests\RunTests.exe" C:\Users\dotnet-bot/.nuget/packages/\xunit.runner.console\2.2.0-beta4-build3444\tools -timeout:50 -xml -testVsi -procDumpPath:c:\SysInternals -log:"D:\j\workspace\windows_relea---8a39a417\Binaries\Release\\runtests.log" D:\j\workspace\windows_relea---8a39a417\Binaries\Release\UnitTests\VisualStudioIntegrationTests\Roslyn.VisualStudio.IntegrationTests.dll" exited with code 1.
Indication 2

**Comment by AlekseyTs** [comment]
Test windows_release_vs-integration_prtest please

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-infrastructure, @jasonmalinowski, @Pilchie It looks like windows_release_vs-integration_prtest runs for 5 hours and still hasn't finished.

**Comment by jasonmalinowski** [comment]
@AlekseyTs There was a Jenkins hiccup around that time, I suspect that's the issue here.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-infrastructure, @jasonmalinowski, @Pilchie Possibly another flaky test.

https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/5159/

CLR test failure (only matches the first, see "Latest Test Result" link for the rest)

Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpCodeActions.AddUsingExactMatchBeforeRenameTracking [FAIL]
Indication 1 

MSBuild Error

error MSB3073: The command ""Binaries\Release\Exes\RunTests\RunTests.exe" C:\Users\dotnet-bot/.nuget/packages/\xunit.runner.console\2.2.0-beta4-build3444\tools -timeout:50 -xml -testVsi -procDumpPath:c:\SysInternals -log:"D:\j\workspace\windows_relea---8a39a417\Binaries\Release\\runtests.log" D:\j\workspace\windows_relea---8a39a417\Binaries\Release\UnitTests\VisualStudioIntegrationTests\Roslyn.VisualStudio.IntegrationTests.dll" exited with code 1.
Indication 2 

There are errors when processing test results

There was an error processing the xunit test results: [xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/xUnitResults/*.xml'. Configuration error?.
Indication 3

**Pull request merged**
