### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160317-150017
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160317-150017 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by davkean** [comment]
@dotnet-bot test eta please

**Comment by heejaechang** [comment]
hmmm I confirmed it builds on my machine not sure it failed on build machine.

**Comment by davkean** [comment]
This build error in particular (not the others) because there's a cross cutting change in internal:
```
Issue 2: MSBuild Error
error MSB3202: The project file "d:\j\workspace\dotnet_roslyn---b84db72c\Open\src\Test\Performance\Fixture\Performance-Fixture.csproj" was not found. [d:\j\workspace\dotnet_roslyn---b84db72c\Roslyn.sln]
```

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/494/
// Retest reason:

**Comment by heejaechang** [comment]
close and reopen PR so that it pick up latest Open pointer.

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
test this please

// some network issue.

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
close/open and retest due to network issue messed up tests running.

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@agocke I must doing something wrong, I can't make it to work with that generator. I will assign this to you to resolve conflict. @davkean 

we probably can't insert ml today.

**Comment by jinujoseph** [comment]
test vsi please

**Comment by jinujoseph** [comment]
test vsi please

**Comment by jinujoseph** [comment]
test vsi please

**Comment by jinujoseph** [comment]
retest prtest/win/dbg/unit64 please

**Comment by jinujoseph** [comment]
retest prtest/win/vsi/p0 please

**Comment by jinujoseph** [comment]
p0 failure is known issue https://github.com/dotnet/roslyn/issues/9602

**Comment by jinujoseph** [comment]
Opened a bug for  prtest/win/dbg/unit64  https://github.com/dotnet/roslyn/issues/9952

**Pull request merged**
