### PR TITLE
Recommend struct and class keywords after record

### PR DESCRIPTION
**Pull request by Youssef1313**
(Not sure if it's that simple)

@jcouv Feel free to close if this doesn't match with the plans.

Test plan: https://github.com/dotnet/roslyn/issues/51199

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Don't we need the same for the `class` keyword?

**Comment by jcouv** [comment]
@Youssef1313 Thanks :-)
`class` should also be offered as Cyrus pointed out.

**Comment by Youssef1313** [comment]
Thanks @CyrusNajmabadi and @jcouv. Added the same check for classes as well

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
