### PR TITLE
Support syntax for explicit implementation of conversion operators

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred, @RikkiGibson, @dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@333fred, @RikkiGibson, @dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@333fred, @RikkiGibson, @dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@333fred, @RikkiGibson, @dotnet/roslyn-compiler Please review.

**Comment by 333fred** [comment]
>                     Diagnostic(ErrorCode.ERR_IdentifierExpected, ".operato").WithLocation(1, 14)

This text seems odd, missing the final r?

---
Refers to: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:2369 in 2f9e8ee. [](commit_id = 2f9e8eed0ee41a7e592310aafaca0decf9e9e78e, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                     Diagnostic(ErrorCode.ERR_IdentifierExpected, ".operato").WithLocation(1, 7)

> Same here. It seems like the error is misplaced?

I do not think so. The error is at the right place. The idetifier is expected between the two dots. I believe the span is extended because there isn't a single dot token in the original token stream and the current token is actually the "operator" token, from which I assume the length is taken. The code that splits the DotDot token and reports the error is not new. It is reused. I do not believe it is worth spending time trying to adjust the end position of the error for this coner case.

---
In reply to: [844444346](https://github.com/dotnet/roslyn/pull/53450#issuecomment-844444346) [](http://example.com/codeflow?ancestors=844444346,844444346)

---
Refers to: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:3927 in 2f9e8ee. [](commit_id = 2f9e8eed0ee41a7e592310aafaca0decf9e9e78e, deletion_comment = False)

**Comment by 333fred** [comment]
>                     Diagnostic(ErrorCode.ERR_IdentifierExpected, ".operato").WithLocation(1, 7)

It just makes me think the compiler has a bug.

---
In reply to: [844476573](https://github.com/dotnet/roslyn/pull/53450#issuecomment-844476573) [](http://example.com/codeflow?ancestors=844476573,844444346)

---
Refers to: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:3927 in 2f9e8ee. [](commit_id = 2f9e8eed0ee41a7e592310aafaca0decf9e9e78e, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                     Diagnostic(ErrorCode.ERR_IdentifierExpected, ".operato").WithLocation(1, 7)

> It just makes me think the compiler has a bug.

Is behavior perfect? No it is not. Does this look like a bug worth fixing? I don't think so. If you feel otherwise, I am happy to open an issue for that, but I am definitely not spending time fixing it under umbrella of this feature.

---
In reply to: [844486287](https://github.com/dotnet/roslyn/pull/53450#issuecomment-844486287) [](http://example.com/codeflow?ancestors=844486287,844444346)

---
Refers to: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:3927 in 2f9e8ee. [](commit_id = 2f9e8eed0ee41a7e592310aafaca0decf9e9e78e, deletion_comment = False)

**Comment by AlekseyTs** [comment]
>                     Diagnostic(ErrorCode.ERR_IdentifierExpected, ".operato").WithLocation(1, 7)

To repeat, the start position of the error is correct. 

---
In reply to: [844492260](https://github.com/dotnet/roslyn/pull/53450#issuecomment-844492260) [](http://example.com/codeflow?ancestors=844492260,844486287,844444346)

---
Refers to: src/Compilers/CSharp/Test/Syntax/Parsing/MemberDeclarationParsingTests.cs:3927 in 2f9e8ee. [](commit_id = 2f9e8eed0ee41a7e592310aafaca0decf9e9e78e, deletion_comment = False)

**Review by 333fred — APPROVED** [review]
LGTM (commit 1)

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler For the second review, please.

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
