### PR TITLE
Add Extract Interface Dialog tests

### PR DESCRIPTION
**Pull request by tmeschter**
**Customer scenario**

Add integration tests for the Extract Interface dialog.

**Bugs this fixes:**

N/A

**Workarounds, if any**

N/A

**Risk**

Low. This changes no product code.

**Performance impact**

No impact; no product code changed.

**Is this a regression from a previous update?**

N/A

**Root cause analysis:**

N/A

**How was the bug found?**

N/A

### CODE REVIEW

**Comment by tmeschter** [comment]
@dotnet/roslyn-ide Please review.

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by tmeschter** [comment]
@dotnet/roslyn-ide Please review.

**Comment by tmeschter** [comment]
Tagging @MattGertz for Ask Mode approval.

**Comment by MattGertz** [comment]
Test-only change; no approval needed.

**Pull request merged**
