### PR TITLE
added some comment suggested by previous PR

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
this has no code change. just added some comment.

**Comment by heejaechang** [comment]
retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3958/
// Retest reason:

**Comment by heejaechang** [comment]
retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3930/

**Comment by natidea** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
@dotnet-bot retest prtest/win/dbg/unit64 please
// Retest reason: Failure tracked by #8807 Tests Disabled by #8822

**Comment by heejaechang** [comment]
@KevinH-MS can you take a look?

**Comment by KevinH-MS** [comment]
Thanks :+1:

**Pull request merged**
