### PR TITLE
Add extra logging to invocation of ibcmerge...

### PR DESCRIPTION
**Pull request by KevinH-MS**
Help diagnose #12508

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @tannergooding @dotnet/roslyn-infrastructure

**Comment by tannergooding** [comment]
test vsi please

**Comment by tannergooding** [comment]
LGTM, just waiting on a VSI run to fail

**Comment by tannergooding** [comment]
test vsi please

**Comment by tannergooding** [comment]
Closing and reopening so that the new copy of ibcmerge is picked up.

**Comment by tannergooding** [comment]
test windows_vsi_p0_open_prtest please

**Comment by tannergooding** [comment]
IBCMerge issues should be resolved now.

**Comment by tannergooding** [comment]
Failing test in vsi_p0 is disabled by internal PR 1178

**Comment by tannergooding** [comment]
Failing test in vsi_p3 is disabled by internal PR 1178

**Pull request merged**
