### PR TITLE
fixed assert where cshtml didn't get proper shared IVsHierarchy set

### PR DESCRIPTION
**Pull request by heejaechang**
this is caused by my previous change - #1730

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani @dpoeschl @shyamnamboodiripad can you take a look?

**Comment by heejaechang** [comment]
@srivatsn I didnt port #1730 to preview branch yet. should I port this and that together to preview or do I need another approval?

**Comment by shyamnamboodiripad** [comment]
LGTM

**Comment by balajikris** [comment]
:+1:

**Comment by srivatsn** [comment]
Port it together.

**Pull request merged**
