### PR TITLE
Unskip CSharpSoruceGenerators.InvokeNavigateToForGeneratedFile test

### PR DESCRIPTION
**Pull request by JoeRobich**
Check if https://github.com/dotnet/roslyn/issues/60477 is resolved.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@jasonmalinowski I ran integration CI several times and haven't seen `InvokeNavigateToForGeneratedFile` test fail. May be worth a shot re-enabling.

**Review by genlu — APPROVED** [review]

**Pull request merged**
