### PR TITLE
Avoid applying partial changes when a code fix contains a mix of supported and unsupported actions

### PR DESCRIPTION
**Pull request by sharwell**
Fixes [AB#1762694](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1762694)

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]
Looks great!  I'd just suggest adding a couple sanity tests here to ensure that the add/deletes come through properly - https://sourceroslyn.io/#Microsoft.CodeAnalysis.LanguageServer.Protocol.UnitTests/CodeActions/CodeActionResolveTests.cs,26c5a52ba3d85f10

fine with that happening in a followup or here.

**Review by arkalyanms — APPROVED** [review]

**Comment by arkalyanms** [comment]
@sharwell is this just pending test additions at this point?

**Comment by sharwell** [comment]
@arkalyanms yes that's correct

**Comment by Cosifne** [comment]
@sharwell I see this PR when checking https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1767589/
Do you want me to push a few unit tests to push forward this change?

**Review by Cosifne — APPROVED** [review]

**Pull request merged**
