### PR TITLE
Actually delete PumpingWait

### PR DESCRIPTION
**Pull request by jaredpar**
Now that the internal dependencies have been removed we can delete the PumpingWait methods.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-ide

**Comment by davkean** [comment]
ETA looks like a real failure.

**Comment by jaredpar** [comment]
retest eta please

**Comment by jaredpar** [comment]
@davkean i updated the ETA code base to not have this dependency anymore.  Think it hadn't sync'd properly when ETA ran last.  If this fails again i'll have chat with someone about how this test runs because locally when I sync everything up it builds correctly.

**Comment by davkean** [comment]
We ran into something similar last week, it appears that once a PR has been submitted, changes aren't merged again with whatever's the latest

**Comment by jaredpar** [comment]
@davkean I just rebased it against latest so let's see if that unsticks it then

**Comment by davkean** [comment]
That didn't fix it - repumping the wheel, found I needed to close/reopen the PR, see if this fixes.

**Comment by davkean** [comment]
Not sure if this expected or not?

**Comment by jasonmalinowski** [comment]
:+1: to the change, assuming we can sort out what's going on with the system.

**Comment by Pilchie** [comment]
:+1:  Hooray!

**Comment by jaredpar** [comment]
Retest please

**Comment by jaredpar** [comment]
Found and fixed the ETA issue. Rest of the test failures were known issues

**Comment by jaredpar** [comment]
Not sure why the unit32 test is registering as running.  It actually completed a bit ago successfully.  

http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/585/

Anyways, all green (finally).

**Pull request merged**
