### PR TITLE
add object dispose check to one missing place.

### PR DESCRIPTION
**Pull request by heejaechang**
this should guard us from object diposed exception that can be fired from stream cancellation.

port https://github.com/dotnet/roslyn/pull/14947 from master to dev15-rc

### CODE REVIEW

**Comment by heejaechang** [comment]
retest windows_release_unit64_prtest please

**Comment by heejaechang** [comment]
version conflict issue.

**Comment by heejaechang** [comment]
ask mode template - https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=288007&_a=edit

**Comment by heejaechang** [comment]
@panopticoncentral figured out what was wrong. verified original simple change fixed the issue. @jmarolf thank you for finding and helping to find fix!

@MattGertz @srivatsn so should we bring this to shiproom?

**Comment by MattGertz** [comment]
Approved based on simple validation.

**Pull request merged**
