### PR TITLE
Updated Misspelled Words

### PR DESCRIPTION
**Pull request by shaggygi**
This addresses a few files with misspelled words for issue #3485.  This is my first PR, so I hope others with more experience could check my work.  Also, I had problems opening APISampleUnitTestsVB.sln, so I created another issue to address the original misspelled word in its respective file.

### CODE REVIEW

**Comment by AdamSpeight2008** [comment]
Looks OK to me, then again I am dyslexic.

**Comment by jasonwilliams200OK** [comment]
@shaggygi, nice catch(es)!
I think the admins will require you to squash this PR to a single commit (currently there are 6 commits). :)

**Comment by pharring** [comment]
LGTM.
Opinion is divided on squashing. Personally, I don't mind if each of the commits is simple enough and shows a progression of small mutations. I don't even mind commits that show "dead ends" that have to be reverted. There are some egregious cases where bulk changes are made and then reverted or mis-merges have to be corrected that have nothing to do with the final PR and it's nice to eliminate those from the history.

**Comment by pharring** [comment]
@gafter Please review and merge if you're happy with it.

**Pull request closed without merging**
