### PR TITLE
Avoid searching for any empty identifier in Find All References

### PR DESCRIPTION
**Pull request by sharwell**
Fixes [AB#1744118](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1744118)

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]
yes yes, a thousand times yes.

**Comment by CyrusNajmabadi** [comment]
Can probably add a tst to C:\github\roslyn\src\Workspaces\CoreTest\FindReferencesTests.cs where the vb code contains `private readonly property`.  Find the node in the tree, get the declared symbol, verify it has no name, then call into FindRefs api directly.

**Comment by arkalyanms** [comment]
Do we have test coverage for this and gates that can reflect the gains?

cc: @genlu to track from the perf wins perspective

**Comment by sharwell** [comment]
> Do we have test coverage for this and gates that can reflect the gains?

Not currently. This change (and the preceding one) were derived from performance traces attached to feedback tickets. Cyrus has speculated on how to reproduce this, but it still needs to be added.

**Comment by genlu** [comment]
@arkalyanms I added one in #66762. From what I can tell, the test never finishes w/o this fix

**Comment by CyrusNajmabadi** [comment]
@arkalyanms We should consider backporting this.  If this is a case of an infinite loop, we're basically going to spin a core non-stop.  As tehre might be many FARs that end up getting kicked off (like for CodeLens, etc.), this could end up just saturating the machine with pointless work.  The fix is trivial, so should be easy to take for 17.5.

**Pull request merged**
