### PR TITLE
Add support for implementations of interface static abstract user-defined conversions in classes and structures

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@333fred, @RikkiGibson, @dotnet/roslyn-compiler Please review.

**Review by 333fred — APPROVED** [review]
LGTM (commit 1)

**Comment by AlekseyTs** [comment]
@RikkiGibson, @dotnet/roslyn-compiler For the second review.

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
