### PR TITLE
Spelling fixes

### PR DESCRIPTION
**Pull request by nnpcYvIVl**

### CODE REVIEW

**Comment by 333fred** [comment]
@nnpcYvIVl please run a build locally, commit the result, and push. There should be some `xlf` file changes after build.

**Comment by nnpcYvIVl** [comment]
@333fred Thanks for the guidance, done.

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Comment by 333fred** [comment]
Thanks @nnpcYvIVl!

**Pull request merged**
