### PR TITLE
Enable parallel runs of determinism job

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @mmitche, @tannergooding, @dotnet/roslyn-infrastructure

**Comment by jaredpar** [comment]
Note: I have no way to test this locally or on the server.  This will just have to be pushed.

**Comment by mmitche** [comment]
LGTM

**Comment by davkean** [comment]
Is this basically the cause of:

image

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3541/
// Retest reason: #8498

**Comment by jaredpar** [comment]
@davkean yes this is the cause.

Note: retesting won't really help here as this change isn't validated at all by the server.  It is only validated on push.

**Comment by davkean** [comment]
Just looking at failures Jared, not looking at particular changes. I don't discriminate.

:+1: let's merge this in - when can we drop these from PR builds?

**Comment by jaredpar** [comment]
@davkean want to have one day of them passing then will merge out of PR builds.  Having it in PR just gives us more runs in a day which should help it get bullet proof faster.  So far found and fixed the one error I've seen.

**Comment by davkean** [comment]
@jaredpar This is failing all the time, I'd prefer that we don't use dev's PRs to validate the job, instead, just kick off a PR and manually run the job over and over.

**Comment by jaredpar** [comment]
@davkean vast majority have failed due to the original bug which is a hung process on the machine.  That has been fixed.  Probably need to reset the machine.

java.io.IOException: remote file operation failed: d:\j\workspace\roslyn_prtest_determinism at hudson.remoting.Channel@6b79df41:dci-win-tbld-19: java.nio.file.AccessDeniedException: d:\j\workspace\roslyn_prtest_determinism\Binaries\Bootstrap\Microsoft.Build.Tasks.CodeAnalysis.dll

**Comment by mmitche** [comment]
@jaredpar Which machine?

**Comment by jaredpar** [comment]
dci-win-tbld-19

**Pull request merged**
