### PR TITLE
Fixed adding a redundant blank line when suppressing with local attribute

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Fixes: https://github.com/dotnet/roslyn/issues/47427

As I've understood, there is always a formatting pass running after this codefix. I think, it is better to fully rely on it, rather than try to add new lines in the codefix ourselves. Otherwise it will be some code duplication. I had no tests broken, when deleted this peace of logic

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@mavasani for eyes on this and if we need more tests here to ensure no regressions.

**Comment by DoctorKrolic** [comment]
I checked most cases manually, just need to write tests now)

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Restart failing CI checks pls

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
