### PR TITLE
Fix null ref in initialize-parameter.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jmarolf

**Comment by jasonmalinowski** [comment]
Shouldn't that be getting an EndOfFile token with the parent as the compilation syntax?

**Comment by CyrusNajmabadi** [comment]
GetPreviousToken on an EOF token can return a .None token with a null parent.

I considered this when i originally wrote the code.  but i thought FirstAncestorOrSelf was an extension method and would handle the 'null' case (like IsKind and many of the other node-extension methods do).  It turned out this was an instance method.  Hence boom.

**Comment by jasonmalinowski** [comment]
All the more reason to hate extension methods that accept null receivers. :wink:

**Comment by CyrusNajmabadi** [comment]
i love them! :D

**Comment by CyrusNajmabadi** [comment]
though, with ?. they're probably not necessary any more.

**Comment by jmarolf** [comment]
@mattwar probably still gets flashbacks from when he changed all those extension methods to instance methods and discovered that *all* if them just returned null if passed null

**Comment by jasonmalinowski** [comment]
There's a part of me that would be happy to see a change where everything did ?. But the bug fallout and massive diff would be crazy...

**Comment by Pilchie** [comment]
> GetPreviousToken on an EOF token can return a .None token with a null parent.

The only case for that is an empty file, right?

**Comment by mattwar** [comment]
sure would be nice to have null checking compiler.

**Comment by CyrusNajmabadi** [comment]
> The only case for that is an empty file, right?

Or any file when you're on the first token.

**Comment by Pilchie** [comment]
Ah, got it.  I was confused by the reference to EOF token before.

**Pull request merged**
