### PR TITLE
Order 'PopulateSwitch' after 'GenerateMethod'

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/11301

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit32_prtest please

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p2_open_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit32_prtest please

**Comment by jasonmalinowski** [comment]
:+1:. @CyrusNajmabadi, what was the failure in the windows_debug_unit32_prtest queue?

**Pull request merged**
