### PR TITLE
Bump the compiler MSBuild task version on every build

### LINKED ISSUE #7185: Rev build task version per day
When we release nuget packages for the compiler with a new build task that task may not be loaded because the task with the same assembly version may have already been loaded with a different path. 

If we Rev the minor version every day (by including the date in the version number) then installing various versions of the compiler should be fine as long s they weren't built in the exact same day.

### PR DESCRIPTION
**Pull request by agocke**
Fixes #7185.

/cc @dotnet/roslyn-compiler @dotnet/roslyn-infrastructure @amcasey

### CODE REVIEW

**Comment by jmarolf** [comment]
:+1:

**Comment by TyOverby** [comment]
LGTM

**Comment by jaredpar** [comment]
:-1: we should not be doing this.  It makes it impossible to do deterministic builds of this DLL.  We should find a different approach.

**Comment by agocke** [comment]
@jaredpar I'm still fleshing out an alternative -- I'll cc you when I have something worked out.

The core idea is two things: add a SharedCompilerLocation task property that allows us to use a specific VBCSCompiler location and hard code a version number for the build task that gets bumped every time the build task is changed. We could enforce that by turning *on* determinism and failing the build if the build task changes.

**Pull request merged**
