### PR TITLE
LOC CHECKIN | dotnet/roslyn-master | 20171212

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@tmeschter Feel free to merge once things are green. I can't think of a way this could break stuff, which is why we should wait until it is green.

**Comment by tmeschter** [comment]
@jasonmalinowski Always.

**Comment by tmeschter** [comment]
@nguerrera I find this highly amusing.

**Comment by tmeschter** [comment]
Superseded by #23744.

**Pull request closed without merging**
