### PR TITLE
Remove dependency on ITextSnapshotLine from indentation code.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This can allow us to move hte indentation service lower.  It also enabled using the indentation service from features that only have a document and aren't connected to an editor.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by DustinCampbell** [comment]
Nice! :+1:

**Comment by jasonmalinowski** [comment]
Oh thank you for fixing this. :+1:

**Comment by Pilchie** [comment]
Will this require fixing anything in TypeScript?

**Pull request merged**
