### PR TITLE
Avoid null ref in ClearAllDiagnosticsForProject...

### PR DESCRIPTION
**Pull request by KevinH-MS**
I was running into a NullReferenceException when switching between solutions in VS...

### CODE REVIEW

**Comment by KevinH-MS** [comment]
@heejaechang can you take a look?

**Comment by KevinH-MS** [comment]
FYI @amcasey @srivatsn this is the issue we were looking at in my office (where you don't get colorization and can't type and sometimes VS crashes).

**Comment by heejaechang** [comment]
:+1: 

thank you!

**Comment by shyamnamboodiripad** [comment]
:+1:

**Pull request merged**
