### PR TITLE
Remove csc2 and vbc2

### PR DESCRIPTION
**Pull request by jaredpar**
They are no longer needed.  Time to remove them.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @agocke, @tannergooding

**Comment by jaredpar** [comment]
test all please

**Comment by jaredpar** [comment]
test win 32 please

**Comment by agocke** [comment]
:+1: :+1: :shipit: Assuming you've removed all traces from the tests.

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by jaredpar** [comment]
test eta please

**Comment by davkean** [comment]
@jaredpar Going to revive this?

**Comment by jaredpar** [comment]
@davkean yes.  This ended up finding a number of internal dependencies that we missed.  It got stale as we tracked them down.  Will revive.

**Comment by jaredpar** [comment]
Retest eta please

**Pull request merged**
