### PR TITLE
Remove Debugger.Break call from two unittests

### PR DESCRIPTION
**Pull request by jcouv**
Fixes https://github.com/dotnet/roslyn/issues/22156

I accidentally left those calls in unittests in https://github.com/dotnet/roslyn/pull/21239

@dotnet/roslyn-ide for review.

### CODE REVIEW

**Comment by jcouv** [comment]
test windows_debug_vs-integration_prtest please

**Comment by jcouv** [comment]
test windows_release_vs-integration_prtest please

**Comment by jasonmalinowski** [comment]
@jcouv Don't worry about the integration tests here, let's just merge this. How did this not drop unit tests on the floor?

**Comment by jcouv** [comment]
@jasonmalinowski Merged.
I think on most machines, calling `Debugger.Break` will do nothing unless you're already attached. You need to call `Debugger.Launch` to interrupt and attach debugger. That's why this is not breaking CI and most local local testing.

I'm not sure, but I suspect that on some machines, `Debugger.Break` will actually launch the debugger too. I have not figured it out, but don't plan to investigate since that code shouldn't be there.

**Comment by jasonmalinowski** [comment]
Indeed, but we attach procdump to running unit tests, which I think functions as a debugger. If you look at old runs, were we creating artifacts?

**Comment by jcouv** [comment]
I'm not sure how to look for that. I'll stop by in the afternoon.

**Pull request merged**
