### PR TITLE
Add CrefSignaturePart to SyntaxFacts.IsInTypeOnlyContext

### LINKED ISSUE #39592: Incorrect Overrides completion in VB
**Version Used**: 
Microsoft Visual Studio Enterprise 2019 Int Preview
Version 16.5.0 Preview 1.0 [29427.7.master]

**Steps to Reproduce**:

1. Add the following API to Compilation class in  src\Compilers\Core\Portable\Compilation\Compilation.cs

```
        public abstract ImmutableArray<MetadataReference> Test();
```

2. Go to VisualBasicCompilation class in src\Compilers\VisualBasic\Portable\Compilation\VisualBasicCompilation.vb 
3. Type ```Overrides```, press space and select Test from the list of methods available to override. 

**Expected Behavior**:
```
        Overrides Function Test() As ImmutableArray(Of MetadataReference)
            Throw New System.NotImplementedException()
        End Function
```

**Actual Behavior**:
```
        Overrides Test()
```

The following entry in the log is likely related:
```
  <entry>
    <record>968</record>
    <time>2019/10/30 22:32:45.547</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.InvalidCastException: Unable to cast object of type &apos;Microsoft.CodeAnalysis.VisualBasic.Syntax.MemberAccessExpressionSyntax&apos; to type &apos;Microsoft.CodeAnalysis.VisualBasic.Syntax.TypeSyntax&apos;.&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCrefSignaturePart(CrefSignaturePartSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CrefSignaturePartSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SeparatedSyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCrefSignature(CrefSignatureSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CrefSignatureSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCrefReference(CrefReferenceSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CrefReferenceSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitXmlCrefAttribute(XmlCrefAttributeSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.XmlCrefAttributeSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitXmlEmptyElement(XmlEmptyElementSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.XmlEmptyElementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitXmlElement(XmlElementSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.XmlElementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitDocumentationCommentTrivia(DocumentationCommentTriviaSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.DocumentationCommentTriviaSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitTrivia(SyntaxTrivia trivia)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement(SyntaxTrivia element)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList(SyntaxTriviaList list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitToken(SyntaxToken token)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement(SyntaxToken token)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList(SyntaxTokenList list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodStatement(MethodStatementSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodStatementSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitMethodBlock(MethodBlockSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.MethodBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitClassBlock(ClassBlockSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.ClassBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitNamespaceBlock(NamespaceBlockSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.NamespaceBlockSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitListElement[TNode](TNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitList[TNode](SyntaxList`1 list)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.VisitCompilationUnit(CompilationUnitSyntax node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax.Accept[TResult](VisualBasicSyntaxVisitor`1 visitor)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxRewriter.Visit(SyntaxNode node)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.VisualBasic.Editing.VisualBasicImportAdder.MakeSafeToAddNamespaces(SyntaxNode root, IEnumerable`1 namespaceMembers, IEnumerable`1 extensionMethods, SemanticModel model, Workspace workspace, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editing.ImportAdderService.MakeSafeToAddNamespaces(SyntaxNode root, IEnumerable`1 namespaceSymbols, SemanticModel model, Workspace workspace, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editing.ImportAdderService.&lt;AddImportsAsync&gt;d__1.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editing.ImportAdder.&lt;AddImportsFromSymbolAnnotationAsync&gt;d__8.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.CodeGeneration.AbstractCodeGenerationService.&lt;GetEditAsync&gt;d__39.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.&lt;GenerateMemberAndUsingsAsync&gt;d__9.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.&lt;DetermineNewDocumentAsync&gt;d__8.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Completion.Providers.AbstractMemberInsertingCompletionProvider.&lt;GetChangeAsync&gt;d__7.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.&lt;GetChangeAsync&gt;d__38.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task, CancellationToken cancellationToken)&#x000D;&#x000A;   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult[T](Task`1 task, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CommitManager.Commit(Document document, CompletionService completionService, ITextView view, ITextBuffer subjectBuffer, CompletionItem roslynItem, TextSpan completionListSpan, Nullable`1 commitCharacter, ITextSnapshot triggerSnapshot, CompletionRules rules, String filterText, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.AsyncCompletion.CommitManager.TryCommit(IAsyncCompletionSession session, ITextBuffer subjectBuffer, CompletionItem item, Char typeChar, CancellationToken cancellationToken)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.AsyncCompletion.Implementation.AsyncCompletionSession.&lt;&gt;c__DisplayClass78_1.&lt;CommitItem&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint[T](Object errorSource, Func`1 call, T valueOnThrow, Predicate`1 exceptionToIgnore, Predicate`1 exceptionToHandle)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>
```

### PR DESCRIPTION
**Pull request by YairHalberstadt**
Fixes #39592

### CODE REVIEW

**Comment by ivanbasov** [comment]
@AlekseyTs pease help with review form the compiler side!

**Comment by ivanbasov** [comment]
@jinujoseph we may want to take it for 16.4. Let us have a compiler review for now, and then decide.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off for a 16.4 candidate.

**Comment by 333fred** [comment]
@jinujoseph this is good from the compiler end now.

**Comment by jinujoseph** [comment]
doing a barcheck for 16.4

**Comment by ivanbasov** [comment]
Thank you for our help, @YairHalberstadt !

**Pull request merged**
