### PR TITLE
Move editor-dependent tests to EditorFeatures

### PR DESCRIPTION
**Pull request by tmat**
Almost all tests in (C#|VB).Features.UnitTests have editor dependencies. Move them to EditorFeatures layer.

Once the test infrastructure for these tests is cleaned up we can move most of them back to Features layer, as applicable.

Next steps:
- https://github.com/dotnet/roslyn/pull/71407
- https://github.com/dotnet/roslyn/pull/71525

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski @dotnet/roslyn-ide ptal

**Comment by CyrusNajmabadi** [comment]
I'm surprised some of these tests need the editor.  like "Add debugger display"... is that actually intended, or is there something wonky in these tests (like copy/pasting something unintentinoally).

**Comment by tmat** [comment]
> I'm surprised some of these tests need the editor. like "Add debugger display"... is that actually intended, or is there something wonky in these tests (like copy/pasting something unintentinoally).

There is a TON of wonky stuff in our tests :(. A lot of tests shouldn't require editor but they do, unfortunately. 
This PR is just first change. I'm gonna need to move almost all tests that are currently in Features to EditorFeatures.

**Comment by tmat** [comment]
A couple of things we can start with if we want to make more progress:

```
https://github.com/dotnet/roslyn/blob/70514c118e2ce45e3b6684d69c7563ac9e2b6f58/src/CodeStyle/Core/Tests/Microsoft.CodeAnalysis.CodeStyle.LegacyTestFramework.UnitTestUtilities.csproj#L28
```

https://github.com/dotnet/roslyn/issues/46153

**Comment by CyrusNajmabadi** [comment]
>  I'm gonna need to move almost all tests that are currently in Features to EditorFeatures.

uh... i'm super wary about that.  a ton fo tests should be fine just in Features (after all, the code for them is just in features).

**Comment by tmat** [comment]
Sure, they should be fine, but they are not.

**Comment by tmat** [comment]
See also https://github.com/dotnet/roslyn/pull/71407.

**Comment by CyrusNajmabadi** [comment]
Can you clarify what they are errantly depending on?

And should there be a FeaturesWorkspace along with an editor one.

Basically, I'm worried about moving some tests too high.

**Comment by tmat** [comment]
> Can you clarify what they are errantly depending on? 

Of course. 

First, let me point out that we do not have *any* Features or Workspace layer tests at all today. All our IDE test projects end up referencing EditorFeatures layer. Moving tests from Features.UnitTests to EditorFeatures.UnitTests is therefore not changing their dependencies. The move allows us to layer things correctly incrementally, without PRs that have 1000s of file changes.

The test types being moved here derive from types defined in `Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities` (e.g. `AbstractCodeActionOrUserDiagnosticTest`). `Microsoft.CodeAnalysis.EditorFeatures.DiagnosticsTests.Utilities` also has dependency on EditorFeatures layer. Removing this dependency would likely require splitting this Utilities project into editor-specific and features-specific parts. Some of the files of this project are also linked in `Microsoft.CodeAnalysis.CodeStyle.LegacyTestFramework.UnitTestUtilities`. Also, bunch of analyzer unit tests are also linked into features layers. I think I'd need to draw a diagram to describe the full dependency graph here...

So, yes, we could (and should) clean this all up, but to keep PRs within reasonable size I think it's best to move the tests around first, establish clear layering and then work on further changes that will eventually allow us to move these and other tests where they belong.

**Comment by tmat** [comment]
Added commits to move the remaining problematic tests.

**Comment by CyrusNajmabadi** [comment]
i dunno.  i feel like we're going to end up moving a massive amount of stuff upwards just to immediately move it down.  if we're doing this work now, i'd prefer the cleaner approach of just introducing the version without editor dependencies, and having these tests not have to move.  AbstractCodeActionOrUserDiagnosticTest feels like it shouldn't need an editor dependency.  could it not be claener/simpler to just move that guy and have the layering be ok then?

**Comment by tmat** [comment]
> i dunno. i feel like we're going to end up moving a massive amount of stuff upwards just to immediately move it down. 

I don't see why this is a problem.

> if we're doing this work now, i'd prefer the cleaner approach of just introducing the version without editor dependencies, and having these tests not have to move. AbstractCodeActionOrUserDiagnosticTest feels like it shouldn't need an editor dependency. could it not be claener/simpler to just move that guy and have the layering be ok then?

I'd prefer cleaner approach too, but I do not have bandwidth to do that. I'd rather not block everything else on these tests.

**Comment by genlu** [comment]
I agree with @tmat. Moving the those tests to proper layer and making the dependency explicit is a good first step. Maybe to minimized potential conflicts with such a massive file movements (seems there's already bunch), we can keep these files in their current locations and use explicit `Include` and `Exclude` in the project file instead?

**Comment by tmat** [comment]
> I agree with @tmat. Moving those tests to their proper layer and making the dependency explicit is a good first step. Maybe to minimize potential conflicts from such a massive file movement (seems there's already bunch), we can keep these files in their current locations and use explicit `Include` and `Exclude` in the project file instead?

Unfortunately, VS solution explorer does not work well with Includes that have globs (I'd certainly not want to list all the files manually). The conflicts shouldn't be an issue - `git rebase` auto-resolves them (just did it for the PR). Seems like just GitHub has an issue with doing so.

**Comment by CyrusNajmabadi** [comment]
> Moving and then moving back is not a problem

it's def a challenge.  especially having to go find them all again and move them.  but i'm not going to block on that.

**Review by CyrusNajmabadi — APPROVED** [review]

**Pull request merged**
