### PR TITLE
Ensure complete information is consistently captured in a bound tree for an explicit C# conversion implicitly applied by compiler.

### LINKED ISSUE #7299: IOperation: Doesn't handle conversions of constant expressions
In this line:

```
private float f = 0.0;
```

... the `ConstantValue` property of the `IExpression` represented by the literal `0.0` is `null`. But in this line:

```
private double d = 0.0;
```

... the `ConstantValue` is `ConstantValueDoubleZero`.

The reason is that the compiler considered the first example as a "conversion expression" rather than a constant expression.

Similarly, the `ConstantValue` of this expression is `null` because the compiler considers it a conversion expression:

```
private char c = 'a' - 'a';
```

... but the `ConstantValue` of this expression is correctly `0`:

```
private char c = (char)('a' - 'a');
```

### LINKED ISSUE #19878: Need to design how to represent failed conversion in tuple assignement
This is a follow-up issue on https://github.com/dotnet/roslyn/pull/19679

How should we represent failed conversion in tuple assignment and how should it be surfaced through the semantic model? Currently, we're using `NoConversion`.

```C#
        internal BoundExpression GenerateConversionForAssignment(TypeSymbol targetType, BoundExpression expression, DiagnosticBag diagnostics, bool isDefaultParameter = false, RefKind refKind = RefKind.None)
        {
            // ...
            else if (!conversion.IsImplicit || !conversion.IsValid)
            {
               // ...
                if (conversion.IsTupleConversion)
                {
                    conversion = Conversion.NoConversion; 
                }

                return new BoundConversion(
                    expression.Syntax,
                    expression,
                    conversion,
                    @checked: CheckOverflowAtRuntime,
                    explicitCastInCode: false,
                    constantValueOpt: ConstantValue.NotAvailable,
                    type: targetType,
                    hasErrors: true);
            }

            return CreateConversion(expression.Syntax, expression, conversion, false, targetType, diagnostics);
        }
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #7299. Fixes #19878

VSO bug : https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/509915

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler , @jcouv, @cston Please review.

**Comment by AlekseyTs** [comment]
CC @jaredpar For initial ask-mode approval

**Review by cston — APPROVED** [review]

**Review by VSadov — APPROVED** [review]
:shipit:

**Comment by AlekseyTs** [comment]
CC @jinujoseph For Ask mode sign-off.

**Comment by natidea** [comment]
Approved to merge via [509915](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/509915)

**Pull request merged**
