### PR TITLE
use 4.2 version of the compiler to build

### PR DESCRIPTION
**Pull request by jmarolf**
This brings us to the latest public preview of VS and allows the use of new features like raw string literals.

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]
‼️

**Comment by jmarolf** [comment]
@sharwell  I want to tag you on this in case there is something I am missing about why we can't just make this change.

**Comment by RikkiGibson** [comment]
https://github.com/dotnet/roslyn/pull/59903#issuecomment-1058400676

**Comment by jmarolf** [comment]
> [#59903 (comment)](https://github.com/dotnet/roslyn/pull/59903#issuecomment-1058400676)

gol darn it you are right. can you block this PR? I just checked the internal schedule and we need to wait jus' a bit.

**Review by RikkiGibson — DISMISSED** [review]
just wait a little longer. Also, we can do this by updating SDK, code style packages etc.

**Comment by davidwengier** [comment]
Can someone explain why we need to wait for preview 2, when it works in preview 1?

**Comment by sharwell** [comment]
> just wait a little longer. Also, we can do this by updating SDK, code style packages etc.

MicrosoftNetCompilersToolsetVersion overrides the SDK version.

**Review by sharwell — APPROVED** [review]
This is a fairly standard change for us.

**Comment by jmarolf** [comment]
Preview 2 is [out](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#1720-pre20--visual-studio-2022-version-172-preview-2) merging...

**Comment by jmarolf** [comment]
shouldn't need anything on the omnisharp side, what errors are you seeing?

**Comment by 333fred** [comment]
> shouldn't need anything on the omnisharp side, what errors are you seeing?

I'm assuming that I will see errors. Haven't actually tried yet though.

**Comment by 333fred** [comment]
Ok, I gave it a try. Raw string literals are not recognized.

**Comment by jmarolf** [comment]
ok, might need to talk with @JoeRobich about this one. My expectation is that if we set `DOTNET_ROOT` like the SDK team does here: https://github.com/dotnet/sdk/blob/dd53a44b49cc8dbe85c5fdfaee1560bc3cc96d61/eng/dogfood.ps1#L47 then O# will pick that sdk up and use it if this option is set to true: https://github.com/dotnet/roslyn/blob/159eea2a45659428d8561466fae1e16a74ea4b2b/.devcontainer/devcontainer.json#L40

So we should just need to update `restore.sh` to install the right SDK and set the right variables. We already call this script when setting up a new environment here: https://github.com/dotnet/roslyn/blob/159eea2a45659428d8561466fae1e16a74ea4b2b/.devcontainer/devcontainer.json#L56

@333fred can you test setting `DOTNET_ROOT` and launching O# on linux? If that works then we should just need to update the `global.json` file to install 6.0.300 and the set the right environment variables in `restore.sh`

**Comment by jmarolf** [comment]
yeah, will need to block PRs for a bit until the new Omnisharp build comes out.

**Comment by RikkiGibson** [comment]
Does this mean that OmniSharp uses its own in-box compiler even when it's using a runtime given by DOTNET_ROOT or similar?

**Comment by 333fred** [comment]
Yes.

**Pull request merged**
