### PR TITLE
Be resilient to projects with multiple versions for a given nuget package

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/19879

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@Pilchie I'm not sure what you mean.  First, we have:
```public ImmutableArray<string> GetInstalledVersions(string packageName)```
 which returns those versions.

We also have: 

```public IEnumerable<Project> GetProjectsWithInstalledPackage(Solution solution, string packageName, string version)``` 

which also consumes these versions as well...

**Comment by Pilchie** [comment]
I was expecting to see a signature change related to `GetInstalledVersions`, since I figured it would only happen per project.  Looked closer and and things make sense now.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Did you open a bug about this crash?  I'd like to do the ask mode template.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 


**Customer scenario**

Customer has a project with multiple versions of the same nuget library referenced.  this causes a NFW for us inside as our datastructure only assumed a single version per package name.

**Bugs this fixes:**

Fixes #19879

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

Low.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Didn't realize this was even possible for projects to do this.

**How was the bug found?**

Huge amount of hits in telemetry for NFWs here.

**Comment by CyrusNajmabadi** [comment]
FYI @MattGertz  this is a huge watson hit according to @Pilchie

**Comment by Pilchie** [comment]
To clarify, it's a common non-fatal Waston in 15.3 use.  The customer impact would be that the Add NuGet package lightbulb wouldn't work properly for customers in this situation.

**Pull request merged**
