### PR TITLE
Fix bootstrapping after update to nuget.52.zip.

### PR DESCRIPTION
**Pull request by rolfbjarne**
Looks like nuget.52.zip has updated the version of Microsoft.Build.Mono.Debug
from 14.1.0-prerelease to 14.1.0, so update the paths as well.

### CODE REVIEW

**Comment by davkean** [comment]
Closing and reopening to sync with Jenkins.

**Comment by davkean** [comment]
tag @agocke @jaredpar

**Comment by agocke** [comment]
Shouldn't there be project.json changes to reference the new MSBuild version? Specifically in `build/ToolsetPackages/project.json`?

**Comment by davkean** [comment]
Resync'ing merge branch.

**Comment by agocke** [comment]
:+1:

**Comment by agocke** [comment]
I believe this PR is obsolete since we stopped using Microsoft.Build.Mono.Debug

**Pull request closed without merging**
