### PR TITLE
Revert #31132

### PR DESCRIPTION
**Pull request by genlu**
FYI @jinujoe @chborl

### CODE REVIEW

**Comment by sharwell** [comment]
Why are we reverting this rather than fixing the issue it had?

**Comment by genlu** [comment]
This is reverted to unblock insertion. If you can send out a fix today, I will make sure it is included.

**Comment by heejaechang** [comment]
@chborl I think this code is having an issue

else if (_isFirstRun)	
{	
    options = options.WithChangedOption(KeybindingResetOptions.NeedsReset, true);	
}

**Comment by heejaechang** [comment]
@chborl let's think about a way to test this code by mocking some services.

**Comment by jinujoseph** [comment]
@sharwell Current payload has this change and we want to unblock by revertting.
plus the fix should have a way to test. Lets take time and fix this right.

**Pull request merged**
