### PR TITLE
Disable some of our analyzers from running on generated code files.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
**Customer scenario**

We currently run our 'Simplify type names' analyzer on all files (including generated files).  This means that the user can get their error list spammed with tons of messages telling them about code that can be fixed up.  It also means that they cannot make these issues into 'errors' as they'll end up with tons of errors they can't actually fix.

This changes things so that we don't actually run these analyzers in generated files.

**Bugs this fixes:** 

https://github.com/dotnet/roslyn/issues/15971

**Workarounds, if any**

None.

**Risk**

Low.  This is using functionality we already have opted into for nearly all of our analyzers.  It just extends it to basically all analyzers we ship.

**Performance impact**

Perf should be better as we're doing less work.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

See above. We run our analyzers on generated code.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Note: we will have another PR that also disables our analyzers for .cshtml files.

**Comment by CyrusNajmabadi** [comment]
@MattGertz @natidea For shiproom.

Basically, we're disabling functionality here because the existing functionality greatly diminishes the usefulness of the feature.  i.e. by running on generated code, we often end up majorly inconveniencing users who want the feature, but don't want to be overwhelmed with messages about things htey cannot fix.

**Comment by natidea** [comment]
Approved to merge via [373316](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/373316)

**Pull request merged**
