### PR TITLE
Dont format comments inside ArrayInitializers

### LINKED ISSUE #939: Dont Format inside Array Initializers
Repro code:
```
class Program
{
    static void Main(string[] args)
    {
        int[] sss = new[] { 2,
            5,            324534,    345345,
                                //Comment1
                                234234,         234,
            234234
        };
    }
}
```

The above code on format should remain the same but we are giving this
```
class Program
{
    static void Main(string[] args)
    {
        int[] sss = new[] { 2,
            5,            324534,    345345,
            //Comment1
            234234,         234,
            234234
        };
    }
}
```

It seems the array element if preceded by a comment gets formatted. This should not happen.

### PR DESCRIPTION
**Pull request by basoundr**
Fix #939 Dont format comments inside Array Initializers and any other place where
spacing is suppressed.

### CODE REVIEW

**Comment by basoundr** [comment]
Reviewers: @Pilchie @heejaechang @jasonmalinowski @dpoeschl @rchande @balajikris @brettfo @jmarolf

**Comment by basoundr** [comment]
Reviewers: @Pilchie @heejaechang @jasonmalinowski @dpoeschl @rchande @balajikris @brettfo @jmarolf

**Comment by Pilchie** [comment]
:+1:

**Comment by heejaechang** [comment]
:+1:

**Pull request merged**
