### PR TITLE
	Respect user settings around 'Blocks' when adding parameter null checks.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/19172
Followup to https://github.com/dotnet/roslyn/pull/19424

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> It seems to be applied to all cases where the simplifier annotation is used, and not just to the null check case described in the original issue

Yes.  Any time someone uses the generator and creates a single-statement block, that single-statement block will be simplified if that's what the user preference is.

**Comment by sharwell** [comment]
@CyrusNajmabadi I'm worried that somewhere something is going to start [doing this to code](https://github.com/EWSoftware/SHFB/blob/3a84b1f886e21f6dee530b87a521fbfb6cc04cef/SHFB/Source/SandcastleBuilderPackage/GoToDefinition/GoToDefinitionCommandTarget.cs#L117-L126), and I'd rather be ignoring the setting than having that happen. At this point I'm not comfortable with the potential impact of this change given the current inability to specify finer-grain control over the behavior.

**Comment by CyrusNajmabadi** [comment]
@sharwell We could certainly tweak the 'prefer block' preference to have another option for single-lines.  but, right now, this is just making it so that our codegen APIs respect user preferences as currently stated.

**Comment by CyrusNajmabadi** [comment]
Adding tests for the other constructs.

**Comment by CyrusNajmabadi** [comment]
@DustinCampbell What do you think?  I think it's appropriate for the syntax-generator to be updated to respect the user's option here.  I would also support future work to have a more fine-grained option.  like "Use braces for multiline nested statements" (actual text to be massage later).

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie

**Comment by Pilchie** [comment]
I'm with Cyrus here, I think we can take this and then *consider* extending the flexibility of the option.

**Comment by CyrusNajmabadi** [comment]
Ok.  Merging.

**Comment by CyrusNajmabadi** [comment]
tagging @MattGertz 


**Customer scenario**

This makes one of our new features better respect user codestyle-options.  Specifically, when adding a null check, we'll respect the user's preferences around if that null check should use a ```{ }``` block in it.

**Bugs this fixes:**

Fixes #19172

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

Low.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Didn't validate all new features against all codestyle permutations.

**How was the bug found?**

Customer report.

**Comment by MattGertz** [comment]
Approving per Kevin's comment.  (The scenario meets the bar at any rate.)  We should file an issue to track extending it, though.

**Comment by CyrusNajmabadi** [comment]
I'll open hte issue.

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/issues/19451

**Pull request merged**
