### PR TITLE
Merge future into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from future into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-future-into-master20160614-150020
git reset --hard upstream/master
git merge upstream/future
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-future-into-master20160614-150020 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by Pilchie** [comment]
Do we still have outstanding PRs against future?  Can we just delete the branch once this is merged?

**Comment by Pilchie** [comment]
@dotnet/roslyn-infrastructure

**Comment by ManishJayaswal** [comment]
@Pilchie yes we should delete this.
@jinujoseph  can you delete future branch today after sending a mail to the team as we do not need it anymore. We had already informed the team that we would be deleting it so your mail should just be a confirmation.

**Comment by jinujoseph** [comment]
@ManishJayaswal  yes , once i merge this in , i will delete the branch after sending out the mail.

**Comment by jinujoseph** [comment]
@dotnet-bot  test windows_debug_unit32_prtest please

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_debug_unit64_prtest please

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_vsi_p0_open_prtest please
failure related to https://github.com/dotnet/roslyn/issues/11856

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_vsi_p2_open_prtest please
failure related to https://github.com/dotnet/roslyn/issues/11868

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_debug_unit64_prtest please 
failure associated with build time out

**Comment by jinujoseph** [comment]
@dotnet-bot test windows_vsi_p2_open_prtest  please
failure related to https://github.com/dotnet/roslyn/issues/11766

**Pull request merged**
