### PR TITLE
Share refactoring code between C# and VB.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by balajikris** [comment]
first few commits are same as in another open PR: https://github.com/dotnet/roslyn/pull/12627

**Comment by CyrusNajmabadi** [comment]
Yes.  this is branched off of that.

**Comment by DustinCampbell** [comment]
:+1:

**Comment by balajikris** [comment]
late, but :+1: .. Also didn't know you could branch off and merge in the same commits from both PRs.. Hmm.

**Comment by Pilchie** [comment]
Also late, but also 👍

**Pull request merged**
