### PR TITLE
Warn for multiple blank lines in source

### PR DESCRIPTION
**Pull request by jcouv**

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by cston — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
might want to remove:

```
# RS0101: Avoid multiple blank lines
dotnet_diagnostic.RS0101.severity = none
```

**Comment by jcouv** [comment]
@CyrusNajmabadi I'm not seeing `RS0101` in the files involved in this PR. Which file/location did you have in mind?

**Comment by CyrusNajmabadi** [comment]
https://github.com/dotnet/roslyn/blob/main/src/Compilers/.editorconfig#L13

**Review by jasonmalinowski — APPROVED** [review]
Signign off on the .editorconfig change, other than as @CyrusNajmabadi observed there might be a second edit to do.

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
