### PR TITLE
Remove SolutionExplorer ProjectItem base classes

### PR DESCRIPTION
**Pull request by cston**
Remove SolutionExplorer ProjectItem base classes added in 56136680f.

Fixes regression where Microsoft.CodeAnalysis.Workspaces.dll was loaded when opening C++ project. Specifically, `CreateCollectionSourceCore` is no longer inlined in caller.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-ide, @basoundr please review.
@mattgertz for approval.

**Comment by MattGertz** [comment]
Approved pending the usual criteria.

**Comment by jasonmalinowski** [comment]
Is this just a direct revert of that single file? Was the refactoring otherwise useful and a more targeted fix is appropriate?

**Comment by cston** [comment]
@jasonmalinowski This essentially reverts all of the Analyzer* classes in SolutionExplorer and removes the base classes. The only other derived classes were reverted (removed) previously so the base class refactoring is not needed currently.

**Comment by Pilchie** [comment]
Note - this targets future, so we're not actually in ask mode, right?

Also, @dotnet-bot test vsi please.

**Comment by MattGertz** [comment]
Technically not 'til Monday, yes, but ironically there is no Monday next week. :-)

**Comment by cston** [comment]
@dotnet/roslyn-ide please review, thanks.

**Comment by cston** [comment]
@dotnet-bot test vsi please

**Comment by Pilchie** [comment]
:+1:

**Pull request closed without merging**
