### PR TITLE
Improve integration test logging

### PR DESCRIPTION
**Pull request by tmat**
Write all log information for each first chance exception to a single file (as opposed to multiple log files per exception).

### CODE REVIEW

**Comment by tmat** [comment]
@JoeRobich @jasonmalinowski PTAL

**Comment by sharwell** [comment]
@tmat The one thing I don't like about this is I lose the ability to see at a glance that a test run was impacted by a product crash. Previously, the existence of the .DotNet.log file indicated this, which could be seen even before the file was downloaded. Do you have a proposed solution for surfacing this information?

**Comment by tmat** [comment]
The artifacts list is unfortunately non-resizable, so I'm not sure looking for `.DotNet.log` generally works anyways:

image

If you find it useful we could add an indicator after the name of the test, something like

`21.19.26-CSharpInteractiveCommands.CRASH.VerifyPreviousAn...`

**Comment by Youssef1313** [comment]
@tmat Is this PR still relevant?

**Comment by sharwell** [comment]
I don't think so. We're slowly migrating to a different integration test harness which has its own data collection implementation. Also, the comment about resizing above doesn't seem to be a problem anymore:
image

**Pull request closed without merging**
