### PR TITLE
Update toolset compiler to 1.1.0-rc1-20151014-05

### LINKED ISSUE #5978: Move to toolset with csc and vbc binding redirects
Both csc.exe and vbc.exe need to be shipped with binding redirects.  Right now only VBCSCompiler.exe has a config file that does redirects.

### PR DESCRIPTION
**Pull request by agocke**
Fixes #5978.

### CODE REVIEW

**Comment by agocke** [comment]
test this please

**Comment by agocke** [comment]
@TyOverby Can you take a look at this? It looks like some projects are setting Deterministic, is that expected?

**Comment by TyOverby** [comment]
Looking into it now.

**Comment by agocke** [comment]
test this please

**Comment by agocke** [comment]
test win32 please

**Comment by agocke** [comment]
test unit32 please

**Comment by agocke** [comment]
test win unit32 please

**Pull request merged**
