### PR TITLE
Create conflict annotation when renaming method to get_ or set_ matching property name

### LINKED ISSUE #45677: Visual Studio instantly crashes if you really want it to by doing this rename
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1095778/visual-studio-instantly-crashes-if-you-really-want.html)._

---
Priority of this issue may be, very, very low, but not completely, because instant crashes can lead to serious loss of data ... ;)

What happened?:
I just made a little discovery when experimenting with the deep limits of the C# language :P (with a property-versus-method conflict that technically only exists at IL level and not in C# itself):

Supose you have a property:
```
public int MyProperty { get; set; }
```
Then you have this method:
```
private void _set_MyProperty(int value) => MyProperty = value;
```
Then use Visual Studio its renaming feature (Ctrl+R, Ctrl+R) and try to remove the underscore so that you get this:
```
private void set_MyProperty(int value) => MyProperty = value;
```

BOOM! Instant exit of the entire IDE.

---
#### Roi Chen [MSFT] on 6/29/2020, 07:18 PM: 

<p>Thank you for taking the time to log this issue!<br>
I’ve tried to reproduce and investigate using the description, and attachments already provided. Unfortunately those aren’t enough and more information is needed in order to investigate it further.<br>
The easiest way to provide all the information is to use the Visual Studio Feedback Tool. This will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace).<br>
Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool:<br>
• Open Visual Studio Feedback tool.<br>
• Click the banner letting you know that you have problems requesting your attention.<br>
• Click this problem from the list<br>
• Click “View their request and respond” from the problem details banner<br>
• Add a comment, in the Attachments/Record: click Start Recording<br>
• When the Steps Recorder tool appears, perform the steps that reproduce the problem.<br>
• When you’re done, choose the Stop Record button.<br>
• Wait a few minutes for Visual Studio to collect and package the information that you recorded.<br>
• Submit. You will be able to see the comment on Developer Community. For security reasons, your files come directly to us and don’t appear on Developer Community.<br>
For the full instructions, please see: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#when-further-information-is-needed-need-more-info</a> . For information about what data is collected, see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect">https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-privacy?view=vs-2017#data-we-collect</a><br>
Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.<br>
We look forward to hearing from you!</p>

#### Eduard de Jong on 6/30/2020, 02:02 PM: 

Hereby my reply to your request, including the requested recording.<br>This time, Visual Studio did an automatic reboot after the crash, which it doesn&#39;t do each time by the way.<br><br>And I realize that I forgot to add the following information:<br>The project type is a Console application, .NET Core 3.1.<br><br>The complete code you need is nothing more than simply this:<br><br>using System;<br><br>namespace ConsoleApp1<br>{<br>    class Program<br>    {<br>        public int MyProperty { get; set; }<br><br>        public void _set_MyProperty(int value) =&gt; MyProperty = value;<br><br>        static void Main(string[] args)<br>        {<br>            Console.WriteLine(&quot;Hello World!&quot;);<br>        }<br>    }<br>}<br>
#### Visual Studio Feedback System on 7/6/2020, 00:31 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes #45677

I probably spent way too long working out where to fix this :(

### CODE REVIEW

**Comment by davidwengier** [comment]
Can we change these errors to report silently, instead of crashing VS? I could have worked around this crash with a `GetValueOrDefault` and it would have meant a better user experience. Sure, the conflict is an even better one, but crashing feels really use hostile to me.

**Comment by jmarolf** [comment]
> Sure, the conflict is an even better one, but crashing feels really use hostile to me.

I am all for not crashing. I just don't want us to paper over user issues. By this being a crash, it was made _important_ by management and we then had to fix it. If that weren't the case, I don't know if this would ever get fixed. @ryzngard's new approach of non-fatal watsons may allow us to both not crash and ensure user issues do not linger.

**Review by jmarolf — APPROVED** [review]

**Comment by ryzngard** [comment]
@davidwengier @jmarolf  NFE could be good here, but I imagine we would not prioritize too highly since this is a "niche" bug. It requires users do a specific set of actions that are somewhat rare, so the raw numbers would be low for hits (probably). Fatal seems appropriate because it's just a bug in the feature code or lack of test surface. Not ideal for user experience, but results in quicker turnaround.

**Comment by davidwengier** [comment]
I can see the logic in that @ryzngard, though it seems like what we're saying is "a single hit is enough, if the user takes some action". That makes sense too, as it gives a metric for importance to a user that hit numbers alone can't express, but that metric applies equally to a yellow bar as it does to a hard crash, right?

**Comment by ryzngard** [comment]
> I can see the logic in that @ryzngard, though it seems like what we're saying is "a single hit is enough, if the user takes some action". That makes sense too, as it gives a metric for importance to a user that hit numbers alone can't express, but that metric applies equally to a yellow bar as it does to a hard crash, right?

Yes and no. Let's take this to a chat, I'm happy to discuss the best option here. We don't currently have a hard set rule for what we do for NFE vs crash.

**Pull request merged**
