### PR TITLE
Stop emitting initobj without address for default expression temp ref local

### LINKED ISSUE #40776: invalid IL when use Index with inlined default(struct).
**Version Used**: 
16.5preview1, default in sharplab

**Steps to Reproduce**:
It's just a test and not code from really world, and report it in case someone need it.

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQhGAzAATZkDCZA3oWYxecAJ4AuMZAKjAM7sADAAoAlHQZMpGAOxkAJjABmAQwCuAG3bCAygAcVAOwA8bTgD5RAbQB6OALoBuSYwC+L5mTNdeAnGIkCKWk5RVVNbX0jUw4YSysHZyCmd2TGUi9Ynn52LAD6NOCANxUoMk4AWz0yAF4FZXUtXQMTb0sk4KZZcpgq20SPVNcgA=

**Expected Behavior**:
`Test0` should also get `IndexOutOfRangeException` like `Test1` and `Test2` does.

**Actual Behavior**:
`InvalidProgramException: Common Language Runtime detected an invalid program.`

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #40776

⚠ Other options, since I don't know anything about this:

- Only check IsRef inside TryEmitAssignmentInPlace inside `if (right.IsDefaultValue())`

- Change https://github.com/dotnet/roslyn/pull/35004/files#diff-74a82622051b7b258352d8b4f8a95630R214

### CODE REVIEW

**Comment by agocke** [comment]
I'm not sure this is the problem. If you look at this example,

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwAEAmARgFgAoKwgZgAIT6Bhegbyvq8YeAE8MMegBUYAZwwAGABQBKdp25LCAdhHiMpOQG0AeqQC6AbkVcAvqZ70AygAcAhgDsAPP0EA+dRK3yOlJcpqACYwAGb2AK64GNJ2Tq4CMO6yJv7cFmlcdPRuQqISxHIKmQEAbvZQ9IIAtrb0ALz0IeFRMXEuucmpAdyqVTC1eobd6VRmQA

It seems to work fine. The trick here is that in lowering I'm basically asking for a ref local, e.g.

```C#
ref var temp = ref receiverExpr;
...
```

What I think *should* be happening here is that Emit should know in this assignment that we need an writeable assignment address. What's actually happening seems to be that Emit thinks `default(Span<byte>)` is address compatible (in Emit terminology, has a home), while in fact it's an rvalue and needs to be spilled.

**Comment by agocke** [comment]
I'll try to investigate  in more detail shortly, this is just my first impression.

**Comment by agocke** [comment]
Ah I see, we're in this situation because it's trying to do the initobj on the address directly.

Yeah, I may have put us into this situation by being cute with the local creation. Lemme think if I should try to refactor the upstream code, or fix this in codegen.

**Comment by agocke** [comment]
Honestly the code I'm generating seems pretty reasonable for lowering. If Emit couldn't handle generating ref locals from rvalues at all I might take a different stance, but this seems like a special case that just isn't handled well.

I think a reasonable way of fixing this is to just bail out of `TryEmitAssignmentInPlace` if the LHS is a ref. When we're calling SafeToGetWriteableReference it's being too smart by knowing that if the LHS *is* a writeable reference, that satisfies the general requirement, but in this case that is not OK. There
actually needs to be a home.

**Comment by jnm2** [comment]
> I think a reasonable way of fixing this is to just bail out of `TryEmitAssignmentInPlace` if the LHS is a ref. When we're calling SafeToGetWriteableReference it's being too smart by knowing that if the LHS _is_ a writeable reference, that satisfies the general requirement, but in this case that is not OK. There
> actually needs to be a home.

If I understand right, this means moving the `assignmentOperator.IsRef` into `TryEmitAssignmentInPlace` as the first thing it does?

**Comment by jnm2** [comment]
Actually, this would be what goes in TryEmitAssignmentInPlace?

```cs
            if (left.GetRefKind() != RefKind.None)
            {
                return false;
            }
```

Or should `SafeToGetWriteableReference` be changed?

**Comment by jnm2** [comment]
(I have no problem with you taking over and closing the PR btw)

**Comment by agocke** [comment]
> 
> 
> Actually, this would be what goes in TryEmitAssignmentInPlace?
> 
> ```cs
>             if (left.GetRefKind() != RefKind.None)
>             {
>                 return false;
>             }
> ```
> 
> Or should `SafeToGetWriteableReference` be changed?

Yup, that's what I'm thinking. Along with a block comment like,

```C#
// If the left hand is itself a ref, then we can't use in-place assignment
// because we need to spill the creation. This code can't be written in C#, but
// can be produced by lowering.
```

I'd also add a test for using a struct constructor as well, since it looks like that follows the same code path.

**Comment by jnm2** [comment]
@agocke This struct constructor test does not end up calling TryEmitAssignmentInPlace, so it passes with and without the fix. Is this what you had in mind?

```cs
        [Fact, WorkItem(40776, "https://github.com/dotnet/roslyn/issues/40776")]
        public void FakeIndexIndexerOnStructConstructor()
        {
            var verifier = CompileAndVerifyWithIndexAndRange(@"
using System;

struct NotASpan
{
    public NotASpan(int x) { }

    public int Length => 1;

    public int this[int index] => 0;
}

class C
{
    static int Repro() => new NotASpan(0)[^0];

    static void Main() => Repro();
}");

            verifier.VerifyIL("C.Repro", @"
{
    // Code size       25 (0x19)
    .maxstack  3
    .locals init (int V_0,
                  NotASpan V_1)
    IL_0000:  ldc.i4.0
    IL_0001:  newobj     ""NotASpan..ctor(int)""
    IL_0006:  stloc.1
    IL_0007:  ldloca.s   V_1
    IL_0009:  dup
    IL_000a:  call       ""int NotASpan.Length.get""
    IL_000f:  ldc.i4.0
    IL_0010:  sub
    IL_0011:  stloc.0
    IL_0012:  ldloc.0
    IL_0013:  call       ""int NotASpan.this[int].get""
    IL_0018:  ret
}");
        }
```

**Comment by agocke** [comment]
Sorry, got that check a little wrong. It's not that the LHS is a ref that's the problem, it's that this is a ref assignment. That erquires that the LHS is a ref, but is not the same as assigning a value *through* the ref. The right check is probably `boundAssignment.IsRef`.

For the constructor, I don't think calling a constructor with arguments goes through the same codepath, but would about the default constructor, e.g. `new Span<byte>()`?

**Comment by agocke** [comment]
Actually, I can hit this with

```C#
    public byte M3() 
        => new Span<byte>(new byte[] { })[^1]
```

That test may not fail for the same reasons, but I'm not sure it's doing the right thing.

**Comment by agocke** [comment]
Ah, I see, `PartialCtorResultCannotEscape` was saving us because assigning to a ref could escape to the heap and emit has no idea that this is the initial ref assignment, so it thinks we may have a ref into the heap. `default` doesn't have the same check because it can't throw.

**Comment by jnm2** [comment]
Okay, so I got it right the first time! =) Updated.

**Comment by jnm2** [comment]
@agocke Ready for review.

**Comment by agocke** [comment]
Can you add a test for     

```C#
public byte M3() 
        => new Span<byte>(new byte[] { })[^1]
```

**Comment by agocke** [comment]
Otherwise LGTM :)

**Comment by jnm2** [comment]
@agocke Is the test I added close enough to what you were thinking? It still doesn't fail prior to the fix in this PR.

**Comment by agocke** [comment]
Yup, I just wanted to add it as a regression test because I didn't see anything like it in the code.

**Comment by agocke** [comment]
@jaredpar @gafter @cston @AlekseyTs @jcouv Could one of you take a look at this community PR?

**Pull request merged**
