### PR TITLE
Use MSBuildVersion instead of MSBuildToolsVersion

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by jaredpar** [comment]
@nguerrera, @rainersigwald

**Comment by jaredpar** [comment]
Fixes #40129

**Comment by jaredpar** [comment]
> Do you need to be defensive against use in <15.6 (when we added MSBuildVersion)? 

No that's not a goal here. 

I'm torn as to whether or not I want to know how to do a `< 15.6` check or not for my own morbid curiousity. Please don't / do tell me.

**Comment by rainersigwald** [comment]
I'd probably go with `'$(MSBuildToolsVersion)' < '16.0' OR '$(MSBuildVersion)' < '16.3'"`

**Comment by Ericvf** [comment]
It would seem logical that `ValidateMSBuildToolsVersion` actually validates the `MSBuildToolsVersion` and nothing else. Why does `MSBuildToolsVersion` no longer contain a number but rather the value `current`? 

This is a breaking change done by Microsoft described here: 
https://developercommunity.visualstudio.com/content/problem/404485/vs2019-msbuildtoolsversion-is-not-a-version.html

My proposal would be to rename the target from `ValidateMSBuildToolsVersion` to `ValidateMSBuildVersion` and only check for the `$(MSBuildVersion)` value. The current package compiles without any problem in 2017 for _our_ projects. 

If this was only done for `editorconfig` file support, why not simply check for `16.3` over there, like so (Microsoft.Managed.Core.targets)
```xml
<!--
========================
.editorconfig Support
========================
Condition=""
-->
<ItemGroup Condition='$(MSBuildVersion)' &gt; '16.3'">
```

These two changes allow me to build using `2017` and `2019` using the latest version of the package.

**Pull request merged**
