### PR TITLE
turn on v2 diagnostic engine as default

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@srivatsn @mavasani can you take a look?

**Comment by srivatsn** [comment]
👍

**Comment by mavasani** [comment]
:+1:

**Comment by basoundr** [comment]
:+1:

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure are these known issues? failed tests seem nothing to do with my change.

**Comment by heejaechang** [comment]
related issue - https://github.com/dotnet/roslyn/issues/10110 and https://github.com/dotnet/roslyn/issues/6852

**Comment by heejaechang** [comment]
retest prtest/win/vsi/p0 please

**Comment by heejaechang** [comment]
retest prtest/win/vsi/p3 please

**Comment by jasonmalinowski** [comment]
The issues in p0 did look unrelated. The p3 issue you should investigate since you might have broken the option system somehow.

**Comment by heejaechang** [comment]
@jasonmalinowski option that failed is changing tab option. I don't think it has anything to do with my change... I think it is just flakyness of the test itself.

**Comment by heejaechang** [comment]
another issue - https://github.com/dotnet/roslyn/issues/10109
interactive window failed to reset.

**Comment by heejaechang** [comment]
test prtest/win/vsi/p3 please

**Pull request merged**
