### PR TITLE
Optimize `T ?? null` to `T` where `T` is a reference type

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Fixes: https://github.com/dotnet/roslyn/issues/55919

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second review.

**Comment by 333fred** [comment]
@DoctorKrolic it does look like the test failures from your lowering change are real, they will need to be investigated.

**Comment by DoctorKrolic** [comment]
@333fred I wasn't able to reproduce failure locally (which is odd), but according to CI test logs the failure is "undeclared local" due to optimization of `??=` operator. Considering that I already had to narrow optimization to just locals and parameters and cut off other potential valid places (like `a.b.c ??= default` where `b` and `c` are field accesses or auto-property accesses) for simplicity, I don't think it is worth complicating optimization algorithm for `??=` anymore. Practice shows that optimizing away `??=` may result in unexpected failures here and there (as opposed to `??`, where lowering `a ?? default` to `a` shouldn't theoretically have side effects), while the value of such optimization is relatively low. So I just reverted all `??=` operator changes all together. If you have an idea of how this optimization can be done in a relatively simple way, while avoiding mistakes, I will be happy to implement it. But as of now, I think the risks are too high for such change to be made.

**Comment by 333fred** [comment]
@DoctorKrolic it's a failure in the `UsedAssemblies` leg. To reproduce locally, follow similar instructions to the [IOperation test hook](https://github.com/dotnet/roslyn/blob/main/docs/compilers/IOperation%20Test%20Hook.md), except in this location: https://github.com/dotnet/roslyn/blob/main/src/Compilers/Test/Core/Compilation/CompilationExtensions.cs#L43

**Review by 333fred — APPROVED** [review]
@dotnet/roslyn-compiler for a second review.

**Comment by DoctorKrolic** [comment]
Can I get a second compiler review here please?

**Comment by DoctorKrolic** [comment]
I'm gonna close this. Partially because this got stale, but mostly due to the fact, that I don't like the solution with ref locals, that I implemented here. It seems more like a workaround than the true way to do it. Yes, we were lucky enough to get 1 failing test to know that the `<condition> ? ref a : ref b` LHS hard-crashes the compiler if we perform this kind of optimization, but what if there are more cases like this that are not covered? The solution with checking for a ref local seems too scoped to a particular case rather than the one preventing such cases to occur entirely. I might return to this later, but for now I don't have a good idea of how that can be improved

**Pull request closed without merging**
