### PR TITLE
Make MetadataReference.CreateFromAssembly internal

### LINKED ISSUE #2911: Move MetadataReference.CreateFromAssembly API to scripting layer
This API throws on CoreCLR so it is best to move this into the scripting layer for now ( that's where we have a dependency on it)  while we decide what to do with it.

### PR DESCRIPTION
**Pull request by tmat**
Fixes #2911.

**Scenario**
The functionality that this method relies on is not available on CoreCLR and although we can implement an alternative it's not clear what the cost is. The method currently throws ```PlatformNotSupportedException```. It was decided that we should not have such APIs in the compiler.

**Fix**
Make the method internal. There is only one place in the RTM shipping code where this method is used: in VS formatting options preview. Replaces this usage with a call to IMetadataService.

**Testing**
Verified that VS formatting options preview works.

@ManishJayaswal
@jaredpar

### CODE REVIEW

**Comment by tmat** [comment]
@rchande @jasonmalinowski

**Comment by rchande** [comment]
Options change LGTM.

**Comment by jasonmalinowski** [comment]
:+1: for IDE changes.

**Comment by jaredpar** [comment]
:+1:

**Comment by MattGertz** [comment]
Rejected 5/21 by ML Shiproom.  @tmat let's do obsoletion instead.

**Pull request closed without merging**
