### PR TITLE
Fixed some inconsistencies in the build/linux scripts

### PR DESCRIPTION
**Pull request by JDemler**

### CODE REVIEW

**Comment by davkean** [comment]
@agocke Can you look at this?

**Comment by davkean** [comment]
retest prtest/win/dbg/unit32 please

**Comment by amcasey** [comment]
FYI, the failure is known: https://github.com/dotnet/roslyn/issues/6211

**Comment by davkean** [comment]
retest prtest/win/dbg/unit32 please

**Comment by agocke** [comment]
These scripts are now insufficient for setting up the mono drop since we now need stuff like the NuGet folders and Portable v5.0 directories.

I have no plan to fix this -- the goal is just to get rid of the mono dependency entirely.

**Comment by JDemler** [comment]
@agocke So the workaround for now would be to delete the /build/linux folder?
One can loose a lot of time in there. 
Maybe update the cross platform building instructions wiki page, too? 
It seems that the sources can be build using linux if you stick to the approach used in the provided cibuild.sh script. Translating that script into english and explaining it might help.

**Comment by agocke** [comment]
@JDemler Yeah I think deleting the `linux/build` folder is good and we should point people at `cibuild.sh`.

**Comment by JDemler** [comment]
So this PR is obviously obsolete.
The question for me remains: How unstable is the build process for linux? Is there an ETA to when the dependency to mono will be resolved?

**Comment by agocke** [comment]
@JDemler CIBuild should always be viable. I hope to have us off Mono in a few weeks -- we're working with the MSbuild team to get a CoreCLR-compatible MSBuild, which is one of the last pieces we need to remove.

**Pull request closed without merging**
