### PR TITLE
Update VS editor SDK version

### PR DESCRIPTION
**Pull request by genlu**
New version contains completion expander support.

@ivanbasov @jinujoseph @vatsalyaagrawal

### CODE REVIEW

**Comment by genlu** [comment]
@vatsalyaagrawal @jinujoseph for approval

**Comment by jinujoseph** [comment]
@genlu has editor side changes merged already ?

**Comment by genlu** [comment]
Yes. Inserted in 16.3 p1 in this PR
https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/188352?_a=overview

**Comment by RikkiGibson** [comment]
Please be aware that this branch is in QB mode on our side now. @genlu

**Comment by genlu** [comment]
@jinujoseph Do we need to take this to shiproom? As discussed offline, this is an infra change and the only effect would be making our unit tests run against actual shipping editor bits.

**Pull request merged**
