### PR TITLE
Remove field that was never written to.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-compiler

**Comment by cston** [comment]
LGTM

**Comment by jaredpar** [comment]
@VSadov did this field have a purpose that we just accidentally removed at some point in time?  If not then definitely :+1: for killing the thing that is dead.

**Comment by CyrusNajmabadi** [comment]
Yeah, i think it's unlikely this could serve a purpose now.  I noticed this during unification because VB didn't even have this.  If VB doesn't have this and C# has it but it has no purpose, then it seems likely that it's just a vestige of things a long time ago that missed being removed.

**Pull request merged**
