### PR TITLE
capture document on findtoken crash in linked files

### PR DESCRIPTION
**Pull request by jmarolf**
**Customer scenario**: The customer has linked files (very common in cross-targeting) in their project and when they type in file Visual Studio crashes.

**Bugs this fixes:**: This will give us more information about [209299](https://devdiv.visualstudio.com/DevDiv/_workitems?id=209299) which hopefully leads to a fix in the future.

**Workarounds, if any**: Unknown

**Risk**: None product is already going to crash in this scenario, this just changes how the dump will be collected.

**Performance impact**: None, just a try/catch around a codepath

**Is this a regression from a previous update?**: This crash has been in Visual Studio since RTM

**Root cause analysis:**: Unknown

**How was the bug found?**: Watson reporting system

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide @dpoeschl please review

**Comment by jmarolf** [comment]
@dpoeschl good point.

**Comment by dpoeschl** [comment]
retest perf_correctness_prtest please
https://ci.dot.net/job/dotnet_roslyn/job/master/job/perf_correctness_prtest/2248/

**Comment by dpoeschl** [comment]
retest perf_correctness_prtest please

**Comment by jmarolf** [comment]
@rchande I could.  Completion accounted for 12% of the crashes, QuickInfo 60%

**Comment by natidea** [comment]
Approved to merge via [209299](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/209299)

**Pull request merged**
