### PR TITLE
MEF has issues with duplicate attributes.

### PR DESCRIPTION
**Pull request by weltkante**
Workaround for issue #11841 until MEF fix gets pushed to nuget.

### CODE REVIEW

**Comment by weltkante** [comment]
There probably should be a unit-test to ensure that MEF can load Microsoft.CodeAnalysis.CSharp.Features until MEF gets fixed properly, otherwise there is risk breaking it again.

**Comment by DustinCampbell** [comment]
:+1: 

cc @dotnet/roslyn-ide

**Comment by DustinCampbell** [comment]
@weltkante: Thanks very much for taking the time to make this tweak! We really appreciate the help on this one.

**Comment by jasonmalinowski** [comment]
Awesome, thanks for the quick fix @weltkante!

**Pull request merged**
