### PR TITLE
Introduce-var should work when caret is on the right of an expression.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixed https://github.com/dotnet/roslyn/issues/28266

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jmarolf @jcouv Simple PR to improve a refactoring niggle @justcla reported.

Thanks!

**Comment by jmarolf** [comment]
@CyrusNajmabadi unfortunately CI is down and unlikely to be up before monday :(

**Comment by CyrusNajmabadi** [comment]
@jmarolf Wow.  What's going on?  

Also, this could still easily be reviewed, even if CI is down :)

**Comment by jmarolf** [comment]
@CyrusNajmabadi 

> What's going on?

Don't know the details, just keeping you in the loop.  

> this could still easily be reviewed, even if CI is down :)

Right, I would just need myself or another reviewer to independently run the tests.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph can this ge ta buddy?

**Comment by CyrusNajmabadi** [comment]
test windows_debug_vs-integration_prtest

**Comment by CyrusNajmabadi** [comment]
@jcouv Feel free to merge when convenient for you :)

**Comment by jcouv** [comment]
I'm expecting a review from IDE team as well.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @jmarolf Can i get eyes on this fairly simple PR?  Thanks!

**Comment by CyrusNajmabadi** [comment]
Anyone care to take a look at a time pr?  Thanks! :)

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jasonmalinowski  can i get another set of eyes? Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jasonmalinowski can i get another set of eyes? It's been almost 3 weeks on this PR already.  Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jasonmalinowski can i get another set of eyes? It's been 3 weeks on this PR already. Thanks!

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide @sharwell @jasonmalinowski can i get another set of eyes? It's been 3 weeks on this PR already. Thanks!

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Pull request merged**
