### PR TITLE
added code lens resource file in vsix

### PR DESCRIPTION
**Pull request by heejaechang**
add resource files for new code lens dlls in setup.

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph what label should I search to find ask mode template?

**Comment by jinujoseph** [comment]
@heejaechang ask mode template needs to be filled in the VSO bug , i have copied a template

**Comment by heejaechang** [comment]
updated vso bug with ask mode template.

**Comment by heejaechang** [comment]
@jinujoseph any update?

**Comment by heejaechang** [comment]
not taking for 16.1

**Pull request closed without merging**
