### PR TITLE
Use the new Find LaF in Interactive

### PR DESCRIPTION
**Pull request by amcasey**
Many thanks to @dpugh.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @cston @tmat @ManishJayaswal @KevinH-MS @genlu

**Comment by amcasey** [comment]
@DinoV @zooba Are you aware of any reason we need/ed to implement ```IVsFindTarget``` explicitly?

**Comment by DinoV** [comment]
I think if we don't implement it explicitly VS doesn't know about the text view being hosted inside of it.  Therefore w/o it Find in Current Window doesn't work.

**Comment by dpugh** [comment]
What should happen is, when the shell tries to find a find target for a window frame, it will first check to see if the frame implements IVsFindTarget. If it doesn't it will IOleCommandTarget.Exec a LocateFindTargetCommand (allowing the view contained in the window frame to provide a find target).



There might be some gaps - which would be bugs - but all the code paths that try and find the find target should fall back to using the LocateFindTarget command.

**Comment by ManishJayaswal** [comment]
@amcasey  what is LaF?

**Comment by amcasey** [comment]
@ManishJayaswal Look-and-Feel

**Comment by amcasey** [comment]
@DinoV @dpugh I tried Find in Window and it found the word but wouldn't navigate when I double-clicked.

**Comment by amcasey** [comment]
Clarification: It's "Find All" that doesn't work.  Before this change it would just find all occurrences in the most recent editor tab, so this doesn't seem like a reduction in functionality.  Shall I file a bug to make "Find All" work in the Interactive window?  It seems like a low priority.

**Comment by amcasey** [comment]
Also, the test failures are legitimate, but I think they'll go away if I move the option back to ```VsInteractiveWindow```.

**Comment by amcasey** [comment]
The behavior of Find in the Interactive window (after this change) seems to match its behavior in the Output window.  I've filed internal bug 144378 for @dpugh to sort out some remaining quirks.  Unless anyone objects, I'm going to merge this change once I get the tests passing.

**Pull request merged**
