### PR TITLE
 tweak to reduce allocations

### PR DESCRIPTION
**Pull request by heejaechang**
for now, serialize solution and its related data creation to reduce allocations.

...

I believe introducing primary workspace concept to OOP and creating new solution by diffing will let us to remove this throttle without increasing allocations too much.

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @panopticoncentral this bring working set down to about 800MB for code lens.

**Comment by heejaechang** [comment]
retest windows_debug_unit64_prtest please

**Comment by heejaechang** [comment]
retest due to known version conflict between d14 and d15 dlls

**Comment by heejaechang** [comment]
@MattGertz can I get approval for rc?

**Comment by MattGertz** [comment]
This meets the bar, and can be merged once tests pass and an additional signoff happens.  @heejaechang please get an updated allocation chart per our e-mail check, and also send the bits to our vendor team to do a general pass today, which I would like done before 5PM.

**Pull request merged**
