### PR TITLE
More test coverage for delegate invoke with conditional access

### PR DESCRIPTION
**Pull request by balajikris**
This PR contains work done for #8309.

- minor code clean ups
- more tests, coverage and documenting current design via tests.

### CODE REVIEW

**Comment by balajikris** [comment]
@CyrusNajmabadi @dotnet/roslyn-ide

**Comment by balajikris** [comment]
@CyrusNajmabadi : Please glance through the tests as well. I've taken the assumptions made in the code and turned them to unit tests to document current design. Such assumptions may or may not be intended, but I wouldn't know :smile:  For e.g: we look for a strict pattern with removing locals -- that the declaration is in the line immediately preceding the null check and invoke pattern. If the local were grouped with other locals at the beginning of the block, we will not touch the declaration. This could be the intended design (it convincingly looks like that is the case), but there could be other cases where it wasn't really intended. So, if you find anything odd with the expectations of the unit tests I've added, Please call them out. Thanks.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by balajikris** [comment]
Test only PR. Merging.

**Pull request merged**
