### PR TITLE
Adjust scope of locals declared within While/Do/Lock/If Statements according to the latest design.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #12597.

@dotnet/roslyn-compiler, @gafter Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @gafter Ping. Please review.

**Comment by jcouv** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @gafter Ping. Please review, need one more sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @gafter Ping. Please review, need one more sign-off. This PR is blocking me from submitting a PR for the next set of changes.

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
