### PR TITLE
Merge master into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-future20160211-160012
git reset --hard upstream/future
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-future20160211-160012 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by genlu** [comment]
Tag @tmat for merge conflit related to https://github.com/dotnet/roslyn/commit/08d2bf88ba328bcf8f8125234490091828432116
- Makefile
- cibuild.cmd

Tag @srivatsn for merge conflit related to https://github.com/dotnet/roslyn/commit/5771b39db0fe81d2fc0286b463b1c3c55d64112d
- build/Targets/GenerateInternalsVisibleTo.targets

Please let me know if the merge is incorrect.

**Comment by tmat** [comment]
Re nuget blob update - the future blob needs to be updated to havfe the right nuget packages. I don't know what the usual process is when merging to future.

**Comment by genlu** [comment]
There's a doc about this, I will try that.
https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/Updating%20NuGet%20ZIP%20file

**Comment by srivatsn** [comment]
I don't see any change other than mine in GenerateInternalsVisibileTo.targets and so don't know what the merge conflict was but yes that file looks right to me.

**Pull request merged**
