### PR TITLE
Remove `GetPositionBeforeParameterListClosingBrace` from Change Signature

### LINKED ISSUE #44603: ArgumentException in VisualBasicChangeSignatureService.GetPositionBeforeParameterListClosingBrace
**Version Used**: Latest 16.7 dogfooding build

**Steps to Reproduce**:

Say the following exception/gold bar while typing:

```
System.ArgumentException : Unexpected SyntaxNode
Parameter name: matchingNode
   at Microsoft.CodeAnalysis.VisualBasic.ChangeSignature.VisualBasicChangeSignatureService.GetPositionBeforeParameterListClosingBrace(SyntaxNode matchingNode)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetContextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.AbstractChangeSignatureService.GetChangeSignatureCodeActionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ChangeSignature.ChangeSignatureCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by dpoeschl**
This method was leftover from when we tried to have the completion list in the Add Parameter dialog, and also was buggy. Since we currently do not attempt completion there and instead check for type binding, we just need a position where types will bind as desired.

Fixes #44603

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
:'(

**Comment by dpoeschl** [comment]
> :'(

I know. I probably should have built locally before submitting a PR that doesn't build... 😬

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide @allisonchou @CyrusNajmabadi for review

**Comment by dpoeschl** [comment]
@jinujoseph Is this okay to merge to `master`?

**Comment by jinujoseph** [comment]
@dpoeschl  yes feel free to merge

**Pull request merged**
