### PR TITLE
Add DiagnosticBag.Enumerable struct

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@tmat, @gafter, @amcasey

**Comment by amcasey** [comment]
FWIW, I believe ```AsEnumerable``` was explicit to make it harder to accidentally resolve the lazy diagnostics in the bag.

**Comment by cston** [comment]
@amcasey We could keep AsEnumerable and not implement IEnumerable&lt;Diagnostic&gt; directly on DiagnosticBag. Either approach seems reasonable to me. See the initial commit for the former approach: 3b2c8fb5d927297368fb64eff0606eba9d52dce2

**Comment by amcasey** [comment]
@cston, given the option, I'd prefer to keep ```AsEnumerable``` explicit.  Getting rid of the iterator is fine with me though. :)

**Comment by cston** [comment]
The change is not needed.

**Pull request closed without merging**
