### PR TITLE
Update vs-extension-testing to 0.1.145-beta

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]
~What are the benefits of this new version?~

Nevermind, I came across https://github.com/microsoft/vs-extension-testing/pull/129 which explains the changes.

**Comment by Cosifne** [comment]
> What are the benefits of this new version?
@JoeRobich 
Currently, the integration test can't be run from TE (which is quite sad in terms of debugging the integration tests we currently have)
The testhost process would be waiting forever for the VSIX installer process to complete its work.
And I talked to Sam yesterday, he found it's because there are some missing assemblies need to be added https://github.com/microsoft/vs-extension-testing/pull/129/files

**Comment by sharwell** [comment]
📝 All integration test failures occurred in the old integration test project, which is not impacted by this pull request in any way.

**Comment by Cosifne** [comment]
I am going to check this in

**Pull request merged**
