### PR TITLE
Delete intermediate file

### PR DESCRIPTION
**Pull request by basoundr**
Tagging @KevinH-MS @TyOverby @rchande for review

### CODE REVIEW

**Comment by TyOverby** [comment]
I actually depend on this behavior in order to collect the csvs for @jaredpar for viewing in PowerBI.

**Comment by KevinH-MS** [comment]
Merge?

**Comment by KevinH-MS** [comment]
Merge or close?

**Comment by TyOverby** [comment]
Close.  This won't merge with the PR that I just landed.

**Pull request closed without merging**
