### PR TITLE
Add regression test for non-repoable customer issue

### PR DESCRIPTION
**Pull request by agocke**
See #15558 for more information.

### CODE REVIEW

**Comment by agocke** [comment]
@jasonmalinowski This is a test-only change which I don't believe falls under ask-mode. Is that correct?

**Comment by agocke** [comment]
@dotnet/roslyn-compiler For review.

**Comment by jasonmalinowski** [comment]
@agocke. Per @MattGertz's comment yesterday, test changes do not apply. Code review policy still applies, of course.

**Comment by jcouv** [comment]
@agocke The bug mentions recursive local functions, but I don't see that in the test. What are you going for?

**Comment by agocke** [comment]
@jcouv `VerifyOutputInMain` sticks the text directly inside of a `static void Main` template, so `oldi` and `@sizeof` should both be local functions in that context.

**Comment by jcouv** [comment]
@agocke I see the local function part, but I don't see the recursive part. I must be missing something.

**Comment by agocke** [comment]
@jcouv Woops, I linked the wrong bug in the PR description. Should be fixed now.

**Comment by AlekseyTs** [comment]
LGTM

**Comment by agocke** [comment]
test windows_eta_open_prtest please

**Comment by jaredpar** [comment]
ETA is broken until this PR is merged

https://github.com/dotnet/roslyn-internal/pull/1454

**Comment by agocke** [comment]
@jaredpar Gotcha, thanks.

**Comment by agocke** [comment]
test windows_eta_open_prtest please

**Pull request merged**
