### PR TITLE
Add a Makefile for *nix OSes

### PR DESCRIPTION
**Pull request by agocke**
@jaredpar

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure 

How does this interplay with the existing cibuild.sh? Is this only for dev boxes? How we make sure that things don't break it? How we keep it in sync?

**Comment by davkean** [comment]
unit32 windows failed during jenkins outage.
@dotnet-bot test prtest/win/dbg/unit32 please

**Comment by agocke** [comment]
You probably don't need to bother testing this -- nothing calls it in any build, so our CI should always turn green, unless there are unrelated failures :)

**Comment by davkean** [comment]
I know, but it just helps me scan the PRs when things are green:

image

**Comment by Phrohdoh** [comment]
```
[...snip...]

Build FAILED.

"/Users/thill/projects/csharp/roslyn/CrossPlatform.sln" (default target) (1) ->
"/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj" (default target) (2) ->
"/Users/thill/projects/csharp/roslyn/src/Test/Utilities/Desktop/TestUtilities.Desktop.csproj" (default target) (5) ->
(CoreCompile target) ->
  /Users/thill/projects/csharp/roslyn/src/Test/Utilities/Shared/Diagnostics/ThrowingDiagnosticAnalyzer.cs(53,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Test/Utilities/Desktop/TestUtilities.Desktop.csproj]
  /Users/thill/projects/csharp/roslyn/src/Test/Utilities/Shared/Diagnostics/ThrowingDiagnosticAnalyzer.cs(66,46): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Test/Utilities/Desktop/TestUtilities.Desktop.csproj]


"/Users/thill/projects/csharp/roslyn/CrossPlatform.sln" (default target) (1) ->
"/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj" (default target) (2) ->
  Diagnostics/SuppressMessageAttributeTests.cs(23,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(39,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(54,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(69,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(88,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(117,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(142,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(167,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(181,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(201,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(217,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(237,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(246,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(254,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(274,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(292,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(315,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(336,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(377,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(357,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(389,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(417,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(453,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(473,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(496,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(515,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(532,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(550,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(568,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(588,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(606,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(627,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(647,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(670,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(695,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(714,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(735,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(754,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(775,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(794,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(813,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(851,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(832,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(871,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(888,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(903,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(922,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(936,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(950,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(989,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(969,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(997,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1010,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1023,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1040,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1059,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1083,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1101,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1118,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1138,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1165,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1175,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1170,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1191,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1186,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1196,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]
  Diagnostics/SuppressMessageAttributeTests.cs(1201,19): warning RS0003: Do not directly await a Task without calling ConfigureAwait [/Users/thill/projects/csharp/roslyn/src/Compilers/Core/CodeAnalysisTest/CodeAnalysisTest.csproj]


"/Users/thill/projects/csharp/roslyn/CrossPlatform.sln" (default target) (1) ->
"/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Emit/CSharpCompilerEmitTest.csproj" (default target) (20) ->
  Attributes/AttributeTests.cs(1000,33): warning RS0014: Do not use Enumerable methods on indexable collections.  Instead use the collection directly. [/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Emit/CSharpCompilerEmitTest.csproj]
  Attributes/AttributeTests.cs(1002,33): warning RS0014: Do not use Enumerable methods on indexable collections.  Instead use the collection directly. [/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Emit/CSharpCompilerEmitTest.csproj]


"/Users/thill/projects/csharp/roslyn/CrossPlatform.sln" (default target) (1) ->
"/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Syntax/CSharpCompilerSyntaxTest.csproj" (default target) (23) ->
  Diagnostics/DiagnosticTest.cs(40,29): warning RS0014: Do not use Enumerable methods on indexable collections.  Instead use the collection directly. [/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Syntax/CSharpCompilerSyntaxTest.csproj]
  Diagnostics/DiagnosticTest.cs(54,29): warning RS0014: Do not use Enumerable methods on indexable collections.  Instead use the collection directly. [/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Syntax/CSharpCompilerSyntaxTest.csproj]
  Diagnostics/DiagnosticTest.cs(55,47): warning RS0014: Do not use Enumerable methods on indexable collections.  Instead use the collection directly. [/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Syntax/CSharpCompilerSyntaxTest.csproj]
  IncrementalParsing/NodeValidators.cs(35,26): warning RS0014: Do not use Enumerable methods on indexable collections.  Instead use the collection directly. [/Users/thill/projects/csharp/roslyn/src/Compilers/CSharp/Test/Syntax/CSharpCompilerSyntaxTest.csproj]


"/Users/thill/projects/csharp/roslyn/CrossPlatform.sln" (default target) (1) ->
"/Users/thill/projects/csharp/roslyn/src/Workspaces/Core/Portable/Workspaces.csproj" (default target) (30) ->
(CoreCompile target) ->
  /Users/thill/.nuget/packages/Microsoft.Build.Mono.Debug/14.1.0-prerelease/lib/Microsoft.CSharp.CurrentVersion.targets(383,9): error MSB6006: "csc" exited with code 139. [/Users/thill/projects/csharp/roslyn/src/Workspaces/Core/Portable/Workspaces.csproj]

    75 Warning(s)
    1 Error(s)

Time Elapsed 00:08:15.64
make: *** [all] Error 1
```

```
tmba:roslyn thill $ find . -iname "csc.exe"
./Binaries/Debug/csc.exe
./Binaries/Debug/csccore/csc.exe
./Binaries/Obj/csc/Debug/csc.exe
./Binaries/Obj/CscCore/x64/Debug/csc.exe
```

**Comment by jmarolf** [comment]
@Phrohdoh RS0003 is supposed to be disables for test projects, were you using the makefile to build? what were the arguments you passed in at the commandline?

**Comment by agocke** [comment]
@Phrohdoh Thanks for testing this. I'm going to try to merge it ASAP. What OS are you using?

**Comment by Phrohdoh** [comment]
OS X 10.100, yes I used the makefile.
I didn't pass any arguments so `all` was assumed.

**Comment by agocke** [comment]
It looks like csc.exe just died for some reason in your log. I just ran this on 10.10 and it worked fine, so maybe 10.11 is the problem?

**Comment by Phrohdoh** [comment]
I am running this again, it took ~8 minutes last time.
I'll ping you once it is done.

**Comment by agocke** [comment]
Yeah, it takes a while since crossgen isn't working on Roslyn right now. You can track https://github.com/dotnet/coreclr/issues/2256 for that to be fixed.

**Comment by Phrohdoh** [comment]
Odd!
It now succeeds.

```
    75 Warning(s)
    0 Error(s)

Time Elapsed 00:09:29.20
```

The makefile looks fine to me outside of the large assumption that `~/.nuget/packages/Microsoft.Build.Mono.Debug/14.1.0-prerelease/lib/MSBuild.exe` will exist.

I don't see anywhere that promises that, but I may be missing something obvious.

:+1:

**Comment by agocke** [comment]
@Phrohdoh It's in the NuGet ZIP file, so if that zip is downloaded and restored correctly then MSBuild.exe should exist.

**Comment by Phrohdoh** [comment]
Do note that there is no `clean` target which is a bit unconventional.

**Comment by agocke** [comment]
@Phrohdoh Yeah, it's pretty sparse because I'm writing the Makefile by hand right now. I'll add clean though.

But I'm probably not going to support distclean, etc. And if I never see autotools again it'll be too soon :)

**Pull request merged**
