### PR TITLE
DONT MERGE test exclude path on CI

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
Related to https://github.com/dotnet/roslyn/issues/58710

@jaredpar I think this PR is merge-able with `roslyn-CI` being required and skipped. So it seems like we can just exclude whatever directories/files we don't want to trigger CI for.

**Comment by jaredpar** [comment]
In general you cannot use excludes in our CI system. The reason is that many of our checks are required and GitHub interprets that as "required to pass". If you have an excluded file, make a change and submit a PR then the checks do not run at all. That is not considered passing hence the PR is red.

**Comment by Youssef1313** [comment]
@jaredpar The PR is currently red due to non-required checks I believe.

**Comment by Youssef1313** [comment]
@jaredpar Can you see if the merge button is available after an approval? (without actually merging)

**Comment by Youssef1313** [comment]
@jaredpar Here it is. It's green :)

**Review by jaredpar — APPROVED** [review]

**Comment by jaredpar** [comment]
Interesting ... it is green now. I'm wondering if something changed. This did not used to be the case. That is why we've never used exclusions before, it basically had zero value with required checks. It does seem to be working now though.

**Comment by Youssef1313** [comment]
Yup I think GitHub behavior has changed at some point of time. Let's close this dummy PR and try to get https://github.com/dotnet/roslyn/pull/58712 merged 🎉

**Pull request closed without merging**
