### PR TITLE
Bump versions for master

### PR DESCRIPTION
**Pull request by agocke**
@dotnet/roslyn-infrastructure @jasonmalinowski

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest microbuild_prtest please. That queue will be less broken now.

The other I can't explain what happened.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest microbuild_prtest please.

That queue will be less broken now. The other I can't explain what happened.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest microbuild_prtest please.

**Comment by agocke** [comment]
@jasonmalinowski Looks like the integration tests are hitting errors.

**Comment by jasonmalinowski** [comment]
@agocke I didn't retest those, and those were failing yesterday. You're clear to merge this.

**Pull request merged**
