### PR TITLE
Include ContentType into assembly qualified type name emitted for an attribute argument.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Addresses DevDiv 1169511.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - Fixes DevDiv 1169511
- Customer scenario - With ProjectN in VS 2015 when putting an attribute that uses a typeof WinRT type as an argument triggers type not found warnings during build. The type reference becomes dangling/invalid and leads to badness down the road. The problem is that the TypeRef in the attribute in metadata does not have ContentType=WindowsRuntime and therefore doesn’t trigger proper type redirection logic.  
- Fix description - Include ContentType into assembly qualified type name emitted for an attribute argument.
- Testing done - unit-tests.

@jaredpar FYI

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

**Comment by jaredpar** [comment]
:+1:

**Comment by gafter** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved 6/4 by ML Shiproom.

**Pull request merged**
