### PR TITLE
Add test verifying completion bug is fixed

### LINKED ISSUE #44862: Completion interferes with typing range expression.
I had this code:

```c#
        private static (string text, string suffix) SplitMemberName(string memberString)
        {
            for (var i = 0; i < memberString.Length; i++)
            {
                if (!SyntaxFacts.IsIdentifierPartCharacter(memberString[i]))
                    return (memberString[0..i], memberString[i]);
            }

            return (memberString, "");
        }
```

Typing it produced:

image

So typing the second dot after the `i` resulted in:

image

instead of

image

### PR DESCRIPTION
**Pull request by allisonchou**
Fixes #44862 (via verifying no repro).
I observed this bug repro-ing occasionally in an older build of VS (16.8 p2.1), but as of the latest Int Preview, the issue no longer seems to repro.
Will squash the commits on merge (was originally working on a fix until I noticed that the issue seems to be already resolved).

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]
I don't know much here, but I'm guessing the `IsHardSelected:=False` is the real verification here?

Two questions: 
1. Is it possible that IntelliCode is part of the issue? ie, do they control their completion items, or do we?
1. Should the test type the second `.` and validate the text in the document, just in case?

**Comment by allisonchou** [comment]
@davidwengier Yep, `IsHardSelected:=False` is meant to be the verification here.
Will take your suggestion to add additional validation, thanks!

I think Intellicode sends their completion items but we display the final preselect behavior - @genlu, is this correct?

**Comment by genlu** [comment]
I think @davidwengier made a very good point re: IntelliCode. In Roslyn, when creating item in symbol completion provider, we only request soft selection if we are on the right side of a numeric type, specifically to fix the range case:
https://github.com/dotnet/roslyn/pull/35749/files#diff-01f9674f8f086f62c00335d148316d73L69

But in IntelliCode, items for APIs are always [hard selected](https://devdiv.visualstudio.com/DevDiv/_git/Pythia?path=%2Fsrc%2FPythiaExt%2FCompletion%2FPythiaHelperLanguageService%2FCSharpPythiaHelperLanguageService.cs&version=GBmaster&line=39&lineEnd=40&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)


I think this should be fixed in IntelliCode
FYI @vivlimmsft

**Comment by allisonchou** [comment]
Thanks Gen! Will close out this PR since it's an Intellicode issue.

**Pull request closed without merging**
