### PR TITLE
Enable EE for .NET Native

### LINKED ISSUE #13468: Turn on the Roslyn EE for .NET Native
Turn on the Roslyn EE .NET Native.  This is dependent on Issue #13275 

expressionevaluator\core\source\expressioncompiler\dkmutilities.cs
 ```C#
        internal static object GetSymReader(this DkmClrModuleInstance clrModule)
        {
            var module = clrModule.Module; // Null if there are no symbols.
            return (module == null) ? null : module.GetSymbolInterface(s_symUnmanagedReaderClassId);
        }
 ```

Can be changed to for Dev15:
 
 ```C#
        internal static object GetSymReader(this DkmClrModuleInstance clrModule)
        {
            var module = clrModule.Module; // Null if there are no symbols.
            return (module == null) ? null : clrModule.GetSymUnmanagedReader();
        }
 ```

ExpressionEvaluator\CSharp\Source\ExpressionCompiler\CSharpExpressionCompiler.vsdconfigxml
 ```XML
    <Class Name="Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CSharpFrameDecoder">
      <Implements>
        <InterfaceGroup Priority="Low">
          <Filter>
            <RuntimeId RequiredValue="DkmRuntimeId.Clr"/>
            <RuntimeId RequiredValue="DkmRuntimeId.ClrNativeCompilation"/> <!-- Add .NET Native Debug Engine -->
          </Filter>
          <Interface Name="IDkmLanguageFrameDecoder"/>
        </InterfaceGroup>
      </Implements>
    </Class>
    <Class Name="Microsoft.CodeAnalysis.CSharp.ExpressionEvaluator.CSharpLanguageInstructionDecoder">
      <Implements>
        <InterfaceGroup Priority="Low">
          <Filter>
            <RuntimeId RequiredValue="DkmRuntimeId.Clr"/>
            <RuntimeId RequiredValue="DkmRuntimeId.ClrNativeCompilation"/> <!-- Add .NET Native Debug Engine -->
          </Filter>
          <Interface Name="IDkmLanguageInstructionDecoder"/>
        </InterfaceGroup>
      </Implements>
    </Class>
 ```
ExpressionEvaluator\VisualBasic\Source\ExpressionCompiler\BasicExpressionCompiler.vsdconfigxml
 ```XML 
    <Class Name="Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.VisualBasicFrameDecoder">
      <Implements>
        <InterfaceGroup>
          <Filter>
            <LanguageId RequiredValue="DkmLanguageId.VB"/>
            <RuntimeId RequiredValue="DkmRuntimeId.Clr"/>
            <RuntimeId RequiredValue="DkmRuntimeId.ClrNativeCompilation"/> <!-- Add .NET Native Debug Engine -->
          </Filter>
          <Interface Name="IDkmLanguageFrameDecoder"/>
        </InterfaceGroup>
      </Implements>
    </Class>
    <Class Name="Microsoft.CodeAnalysis.VisualBasic.ExpressionEvaluator.VisualBasicLanguageInstructionDecoder">
      <Implements>
        <InterfaceGroup>
          <Filter>
            <LanguageId RequiredValue="DkmLanguageId.VB"/>
            <RuntimeId RequiredValue="DkmRuntimeId.Clr"/>
            <RuntimeId RequiredValue="DkmRuntimeId.ClrNativeCompilation"/> <!-- Add .NET Native Debug Engine -->
          </Filter>
          <Interface Name="IDkmLanguageInstructionDecoder"/>
        </InterfaceGroup>
      </Implements>
 ```

### PR DESCRIPTION
**Pull request by cston**
Fixes #13468.

Thanks to @tommcdon for the fix.

@tommcdon, @plnelson, @kevinh-ms please review.

### CODE REVIEW

**Comment by cston** [comment]
@dotnet-bot test perf_correctness_prtest please

**Comment by cston** [comment]
@dotnet-bot test windows_release_unit64_prtest please

**Comment by cston** [comment]
@tommcdon, @plnelson, @kevinh-ms, please review. Thanks.

**Comment by plnelson** [comment]
LGTM

**Pull request merged**
