### PR TITLE
Update the versions of SCI and SRM to public preview 8

### PR DESCRIPTION
**Pull request by 333fred**

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]
Approved with a passing validation insertion

**Comment by 333fred** [comment]
master-vs-deps PR that doesn't have merge conflicts: https://github.com/dotnet/roslyn/pull/47409
Signed build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4036165&view=results
Test insertion: _to be added_

**Comment by 333fred** [comment]
Alright, @JoeRobich it looks like the CloudBuild failed for unrelated reasons. I see a test failure in the build related to FAR returning a different number of references, and in the changelog for this PR I happen to see https://github.com/dotnet/roslyn/pull/47307 in the list.

**Comment by 333fred** [comment]
Alright. The test insertion showed some NGEN invalid assemblies, but I believe those are due to the downgrade I had to accept in MS.CA.dll for conflict resolution, as I had to deal with unrelated breakage. I'm going to rerun tests here to make sure nothing broke in the past couple of days, then go ahead with this. @allisonchou, when this is merged it'll have a merge conflict with master-vs-deps. If you notice it before I do please feel free to ping me.

**Pull request merged**
