### PR TITLE
Rename KeyValuePair

### PR DESCRIPTION
**Pull request by jaredpar**
The target framework netcoreapp2.0 includes a new type: `KeyValuePair`.
This conflicts with our `KeyValuePair` utility class and causes a lot of
friction whenever netcoreapp2.0 is added as a target framework for a
project.

Renaming the type to `KeyValuePairUtil` to remove the ambiguity.

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler, @jasonmalinowski for review

**Comment by jaredpar** [comment]
The `KeyValuePair` is now a framework type. Having a type in our code base with the same name is just going to continue to cause conflict for us. The `#if` doesn't really fix this fundamental issue. Particularly because the type is in a different namespace. 

Think of it a different way. If we were starting now would we ever add a new type that had the same name as a framework type? No that would be unnecessarily causing us pain. We'd pick a name different from that of the framework one. That is the same effect as this PR.

**Comment by jaredpar** [comment]
> Why not move it to the same namespace then?

Couple reasons:

1. That's even more confusing. If I want to refer to the actual type in BCL I have to resort to extern aliases. 
1. The type we define has different behaviors than the one in BCL.
1. Still have to adjust lots of files by adding a new `using` declaration. 
1. Explicitly against the framework design guidelines (don't put types into System).

**Comment by tmat** [comment]
I think the problem would be ambiguity due to InternalsVisibleTo.

**Comment by tmat** [comment]
👍

**Pull request merged**
