### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160311-160036
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160311-160036 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure I am trying to resolve merge conflict for this branch and I am not sure how to resolve cibuild.cmd and Makefile conflict.

basically, stabilization and master seems using different mechanism to restore zip nuget package.should I keep ones in master for master? or take change in stabilization?

**Comment by heejaechang** [comment]
adding @jaredpar and @TyOverby

**Comment by jasonmalinowski** [comment]
@heejaechang: for cibuild.cmd, if the conflict is that stabilization has an updated zip and master doesn't have that anymore, you can take the master side.

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure can someone take a look whether cibuild.cmd/Makefile and project.json (not lock.json) are correct?

**Comment by heejaechang** [comment]
retest prtest/win/vsi/p1 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p1/481/
// Retest reason: not test failure, github timeout.

**Comment by jasonmalinowski** [comment]
cibuild.cmd looks right, at least.

**Pull request merged**
