### PR TITLE
Run xunit with -verbose and save xunit process output to a file on error

### PR DESCRIPTION
**Pull request by tmat**
The goal is to have a better idea what was going on when xUnit process unexpectedly terminates without error output.

### CODE REVIEW

**Comment by davkean** [comment]
Filed https://github.com/dotnet/roslyn/issues/6403 for the ETA failure.

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure

**Comment by amcasey** [comment]
Huh, I guess we lost that when we moved to Jenkins.  LGTM, but you might want to grab stderr too.

**Comment by tmat** [comment]
stderr is printed out in the error output. That seems to be reported in the output.

**Pull request merged**
