### PR TITLE
Support EnC for string interpolation

### LINKED ISSUE #2556: NullReferenceException only when run on Azure
Note this applies to an old version of Roslyn, specifically v1.2.0.0, md5sums of the .dll files are listed below. Also, there's a good chance this is actually an Azure bug, not a Roslyn bug---especially given this started happening without any code changes---but it's hard to debug.

The short version is that parsing programs with `if` statements with empty bodies (e.g. `if(x==0);`) throws a `NullReferenceException`... but only when running on Azure (the code is inside an Azure web role). Running the code locally, or even putting similar code in a command-line program and using Remote Desktop to run it on the Azure VM, works fine.

I can get a little more information by enabling the remote debugging feature in the Azure settings and using [JetBrains dotPeek](https://www.jetbrains.com/decompiler/) to get Roslyn source code to step through, but trying to inspect variables just gives me debugger messages about the variables being optimized away.

Parsing many other programs in the context of Azure also works fine. (The other bug I see which similarly only happens in Azure is errors saying “not all code paths return a value” on programs that clearly have no such problem like “`int foo(int x) { return x*2; }`”, but that doesn’t give a stack trace so I haven’t been focusing my debugging efforts there.)

Specifically, the stack trace is

    System.NullReferenceException: Object reference not set to an instance of an object.
       at Roslyn.Compilers.CSharp.InternalSyntax.SyntaxParser.AddError[TNode](TNode node, ErrorCode code, Object[] args)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseEmbeddedStatement(Boolean complexCheck)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseIfStatement()
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseStatementNoDeclaration(Boolean allowAnyExpression)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseStatement()
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseStatements(SyntaxNode& previousNode, SyntaxListBuilder`1 statements, Boolean stopOnSwitchSections)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseBlock(Boolean isMethodBody)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseBodyOrSemicolon(SyntaxKind parentMemberKind, BlockSyntax& body, SyntaxToken& semicolon)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseMethodDeclaration(SyntaxListBuilder`1 attributes, SyntaxListBuilder modifiers, TypeSyntax type, ExplicitInterfaceSpecifierSyntax explicitInterfaceOpt, SyntaxToken identifier, TypeParameterListSyntax typeParameterList)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind, String typeName)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseClassOrStructOrInterfaceDeclaration(SyntaxListBuilder`1 attributes, SyntaxListBuilder modifiers)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseTypeDeclaration(SyntaxListBuilder`1 attributes, SyntaxListBuilder modifiers)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseMemberDeclarationOrStatement(SyntaxKind parentKind, String typeName)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseNamespaceBody(SyntaxToken& openBrace, NamespaceBodyBuilder& body, SyntaxListBuilder& initialBadNodes, SyntaxKind parentKind)
       at Roslyn.Compilers.CSharp.InternalSyntax.LanguageParser.ParseCompilationUnit()
       at Roslyn.Compilers.CSharp.SyntaxTree.ParseText(IText text, String path, ParseOptions options, Boolean retainLexerCache, LexerCache lexerCache, CancellationToken cancellationToken)
       at Roslyn.Compilers.CSharp.SyntaxTree.ParseText(IText text, String path, ParseOptions options, CancellationToken cancellationToken)
       at Roslyn.Compilers.CSharp.SyntaxTree.ParseText(String text, String path, ParseOptions options, CancellationToken cancellationToken)
       … (goes into my code at this point)

and stepping through the decompiled code,

    protected TNode AddError<TNode>(TNode node, ErrorCode code, params object[] args) where TNode : SyntaxNode
    {
      if (node.IsMissing)
      {
        int offset;
        int width;
        this.GetDiagnosticSpanForMissingToken(out offset, out width);
        return SyntaxNodeExtensions.WithAdditionalDiagnostics<TNode>(node, (DiagnosticInfo) SyntaxParser.MakeError(offset, width, code, args));
      }
      return SyntaxNodeExtensions.WithAdditionalDiagnostics<TNode>(node, (DiagnosticInfo) SyntaxParser.MakeError((SyntaxNode) node, code, args));
    }

The `null` reference is the `node` argument to that method, which very clearly can never be `null`. It’s difficult to determine exactly where the `null` value is coming from when stepping through the code as the debugger just says everything is optimized away, so it doesn’t give much feedback beyond what line is being executed, but the code path it appears to be following is definitely one that cannot produce a `null` value (it ends up being a value generated by a `new` expression, which I think can never be `null`, and getting passed through a few `return` statements before getting to the “`if(node.IsMissing)`” line.

The one oddity I noticed when stepping through with remote debugging is that the `node` value is generated by a method with a big `switch` statement where every case is a `return` statement, but the next step after the `return` statement inside the `switch` was to the last line of that method which was a different `return` statement, but "step into" didn't step into that expression, so I don't think it was actually executed. Not sure if that's actually relevant.

The version of Roslyn I am using identifies itself as Roslyn v1.2.0.0, md5sums (generated these to make sure I was actually running the same code everywhere):

    1121995bb87ecbddcbbdc3a2936932fa Roslyn.Services.VisualBasic.dll
    2844da7fd88a6e20901a34de4d2183cb Roslyn.Compilers.CSharp.dll
    2a4b9e9e206f5435a3b103269c048c80 Roslyn.Compilers.VisualBasic.dll
    56b6b921b12721382058a3215d4fbfdf Roslyn.Utilities.dll
    979c60c9b382948352c41b0cde2b2b63 Roslyn.Services.dll
    db00cbd84b662fd96b074be78d631cfa Roslyn.Compilers.dll
    e25df774723e0ad1fb2df4b619be2f87 Roslyn.Services.CSharp.dll

(Porting the code over to the most recent Roslyn might work around these issues, or at least make them easier to debug… but would both be a huge effort and might not even be possible because parts of the code rely on the Roslyn scripting APIs which don’t exist in the most recent versions.)

### PR DESCRIPTION
**Pull request by wschae**
Fix #2556 and internal bug 1198941

### CODE REVIEW

**Comment by wschae** [comment]
@tmat Can you have a look at this one?

**Comment by tmat** [comment]
Please, add unit tests to compilers. Token comparison is exposed as public API.
FYI: @VSadov @agocke @gafter

**Comment by wschae** [comment]
@tmat @VSadov  @agocke @gafter I added tests in SyntaxEquivalenceTests. I am wondering if there are better places to add these tests.

**Comment by wschae** [comment]
test this please

**Comment by wschae** [comment]
test this please

**Comment by wschae** [comment]
@tmat @VSadov @agocke @gafter Can you have a look at this one?

**Comment by wschae** [comment]
@tmat Did you have a chance to check this update?

**Pull request merged**
