### PR TITLE
Revert statement that is breaking sqlite on OSX.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @ericsink @Therzok @sharwell

**Comment by CyrusNajmabadi** [comment]
Tagging @AArnott

**Comment by CyrusNajmabadi** [comment]
Not sure what the OSX issue is here.  On @Therzok  to continue the investigation with @ericsink and Sqlitepcl.

**Comment by Therzok** [comment]
I think I figured it out, but not sure how to validate it works properly: https://github.com/ericsink/SQLitePCL.raw/issues/407

**Review by Therzok — APPROVED** [review]

**Comment by davidwengier** [comment]
Thank you @CyrusNajmabadi and @Therzok for tracking this down ❤️

**Review by AArnott — APPROVED** [review]
Sad, since this reverts a good change. I hope whatever the underlying bug is can be fixed and this workaround reverted soon.

**Review by davidwengier — APPROVED** [review]

**Review by sharwell — CHANGES_REQUESTED** [review]
Can you make the change conditional on the current operating system (i.e. avoid changing the behavior for Windows)?

**Comment by ericsink** [comment]
Just in case others have not seen it, ericsink/SQLitePCL.raw#407 contains a writeup of what's going on here.

**Comment by CyrusNajmabadi** [comment]
@sharwell  done.

**Review by sharwell — APPROVED** [review]

**Comment by ericsink** [comment]
Discussion of this issue is happening on the sqlite forum at:

https://sqlite.org/forum/forumpost/de445cf241

Notable quote from DRH: "Trying to open an on-disk database using "mode=memory" doesn't make sense. Where were you trying to accomplish?"

He also reports that he was unable to repro the differing behavior, but I'm not yet sure why.

**Comment by ericsink** [comment]
Continuing to parrot things from the sqlite forum thread:

If "mode=memory" is removed, which DRH said does not make sense, then the behavior across Windows and other platforms no longer differs.  In other words, it gives the error in all cases.

**Comment by CyrusNajmabadi** [comment]
@AArnott for info here.  This was added in response to what the platform cache is doing.

**Comment by AArnott** [comment]
@ericsink Thanks for referencing the sqlite thread. I [responded](https://sqlite.org/forum/forumpost/f445d122bc) with a defense of what we're doing, pointing to the docs that explain why this is legit.

**Comment by CyrusNajmabadi** [comment]
Merging this in now.  If we get resolution in https://sqlite.org/forum/forumpost/9babfc9cba?t=h as to what to do here, we can update accordingly.

**Pull request merged**
