### PR TITLE
Updating Roslyn Toolset to v1.2.0-beta1-20160202-02

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @agocke, @jaredpar, @davkean 

Also, FYI. @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tannergooding** [comment]
Forgot to upload the nuget packages first. Doing that now (build was tested locally already).

**Comment by agocke** [comment]
Why did the project.lock.json files change?

**Comment by tannergooding** [comment]
Also, I still have to update the zip file.

**Comment by tannergooding** [comment]
Updated to match the other nuget changes made in the past couple days.

**Comment by tannergooding** [comment]
@jaredpar, @agocke, or @davkean. Can I get sign-off on this?

**Comment by jaredpar** [comment]
How bad would it be if we waited till Monday to update the toolset?  There is a bug fix that got checked in very late last night that I need to deliver to the Windows team (blocking their build).  Would be nice if we kept them on an official toolset vs. a one off.

**Comment by tannergooding** [comment]
@jaredpar, Is there any reason we can't do another toolset update on Monday? This toolset update also brings about a number of fixes which will be consumed by `dotnet/cli`.

**Comment by jaredpar** [comment]
@tannergooding fine with doing multiple toolset updates.

**Comment by tannergooding** [comment]
@jaredpar. Sounds good to me. Merging.

**Comment by davkean** [comment]
@tannergooding Please doc what it takes to do this, so that others can pick it up in the future.

**Comment by tannergooding** [comment]
@davkean, it is already documented in the OneNote.

**Comment by tannergooding** [comment]
@jaredpar. Toolset has been tagged: https://github.com/dotnet/roslyn/releases/tag/toolset_5

**Comment by jaredpar** [comment]
Did you update the OneNote?

**Pull request merged**
