### PR TITLE
Update CoreFX to RTM,  CoreCLR to the latest bits, SRM to the latest.

### PR DESCRIPTION
**Pull request by tmat**
Removes Roslyn copy of PEBuilder and MetadataBuilder.

Note: We can't run Roslyn on Core CLR RTM due to bug in assembly loader that was fixed last Friday. hence the update to the latest CoreCLR build.

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet-bot retest perf_correctness_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn/job/master/job/perf_correctness_prtest/28/
// Retest reason:

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
@cston @dotnet/roslyn-compiler @dotnet/roslyn-infrastructure

**Comment by jcouv** [comment]
Looks good to me. Thanks

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
@dotnet-bot retest windows_vsi_p1_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p1_open_prtest/161/
// Retest reason: https://github.com/dotnet/roslyn/issues/11856

**Pull request merged**
