### PR TITLE
Merge pull request #17174 from heejaechang/OOPKilled

### PR DESCRIPTION
**Pull request by heejaechang**
this is port of #17174 from 15.0.x to master.
...

let OOP to be killed

### CODE REVIEW

**Comment by heejaechang** [comment]
straight port from RTW branch.

**Comment by heejaechang** [comment]
@mavasani @srivatsn @panopticoncentral can you take a look?

**Comment by Pilchie** [comment]
You shouldn't need to do this - @dotnet/roslyn-infrastructure  (currently @agocke) does this merge daily.

**Comment by jasonmalinowski** [comment]
Indeed. And if this is a cherry-pick please _don't_ merge it as it might make @agocke's life more difficult.

Dual checkin is never a requirement in the Roslyn repo for as long as my opinion counts. :-)

**Comment by heejaechang** [comment]
@jasonmalinowski @Pilchie okay. I have some changes I am working on which will conflict with this change, that's why I was trying to bring this to master. I can wait if it will happen tomorrow.

**Comment by jasonmalinowski** [comment]
@heejaechang: it's fine to do, just let infrastructure know so we know what's going on. But make sure you're doing a PR from one branch to another: do _not_ cherry pick or rebase.

**Comment by heejaechang** [comment]
@j

**Pull request closed without merging**
