### PR TITLE
Remove workaround for persistent errors

### LINKED ISSUE #32121: Error list sometimes doesn't clear on solution close
Observed in some recent integration test runs.

⚠️ The following workaround should be removed when this issue is fixed:

https://github.com/dotnet/roslyn/blob/f4e99378935b880202d49e3a75ca99cbd8f498c3/src/VisualStudio/IntegrationTest/TestUtilities/InProcess/ErrorList_InProc.cs#L106-L112

### PR DESCRIPTION
**Pull request by sharwell**
Closes #32121

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Thanks, hadn't gotten to it yet with the context switcher bugs. You feel it's being more stable now?

**Comment by sharwell** [comment]
I ran a full integration test pass without seeing a hang, so it seems good now.

**Comment by sharwell** [comment]
@jaredpar for approval (test only change)

**Comment by sharwell** [comment]
I filed follow-up issue #32401 on suggestion from @jasonmalinowski.

**Comment by jinujoseph** [comment]
Sam , can you retarget to master

**Comment by sharwell** [comment]
@jinujoseph now targeting master

**Pull request merged**
