### PR TITLE
Add Rebuild badge to README

### LINKED ISSUE #51246: Add Correctness_Rebuild to the README badges
I think once the Correctness_Rebuild job matures a bit (i.e. when it can build all of Compilers.sln or Roslyn.sln), it would be good to add it to the Roslyn README along with the other jobs.

---

Do you want to add this to README badges?

_Originally posted by @Youssef1313 in https://github.com/dotnet/roslyn/pull/50968#discussion_r573565884_

### PR DESCRIPTION
**Pull request by RikkiGibson**
Closes #51246

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@dotnet/roslyn-infrastructure for review

**Comment by 333fred** [comment]
These badges can be useful for 3rd party contributors to see current status, but while most are straightfoward, the word `rebuild` is not. Can we make the name better?

**Comment by RikkiGibson** [comment]
We could consider using a term like:

- *Rebuild from artifacts*
- *Build provenance*
- ... not sure if any other terms spring to mind just now.

**Comment by 333fred** [comment]
The former sounds better to me.

**Review by 333fred — APPROVED** [review]

**Pull request merged**
