### PR TITLE
Revert "Use IAsyncEnumerable in DesignerAttributeScanning as well."

### PR DESCRIPTION
**Pull request by genlu**
Reverts dotnet/roslyn#64616 to fix regression in [insertion](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/430655)

1. See https://github.com/dotnet/roslyn/pull/64616#discussion_r1001012370
 
2. This also caused an assembly load in UWP test. It seems the assembly "Microsoft.VisualStudio.Design.ni.dll" is loaded in baseline too, but only after "0200.Xaml Designer Load" scenario completed, but now we are loading it before "0200.Xaml Designer Load" starts.
```
Name
 Image Load Microsoft.VisualStudio.Design.ni.dll (C:\Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.V1de0ecc7#\5d1368f8dfbb87b7d62c2a3f9f13ca1a\)
+ module ntoskrnl <<ntoskrnl!?>>
 + module ntdll <<ntdll!LdrLoadDll>>
  + module kernelbase <<kernelbase!LoadLibraryExW>>
   + module clr <<clr!AssemblyNative::Load>>
    + module mscorlib.ni <<mscorlib.ni!DomainNeutralILStubClass.IL_STUB_COMtoCLR(IntPtr, IntPtr, IntPtr)>>
     + module clr <<clr!GenericComCallStub>>
      + module msenv <<msenv!?>>
       + module microsoft.visualstudio.interop.ni <<microsoft.visualstudio.interop.ni!DomainBoundILStubClass.IL_STUB_CLRtoCOM(System.Guid ByRef, System.Guid ByRef, IntPtr ByRef)>>
        + module microsoft.visualstudio.shell.framework.ni <<microsoft.visualstudio.shell.framework.ni!ServiceProvider.GetService>>
         + module microsoft.visualstudio.languageservices.ni <<microsoft.visualstudio.languageservices.ni!Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.VisualStudioDesignerAttributeService+<NotifyLegacyProjectSystemAsync>d__18.MoveNext()>>

```

FYI @CyrusNajmabadi to investigate

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
i can fix this, instead of needing to revert.

**Comment by genlu** [comment]
@CyrusNajmabadi there's also this

```
Name
 Throw(StreamJsonRpc.RemoteInvocationException) Specified method is not supported.
+ Other <<mscorlib.ni!ExceptionDispatchInfo.Throw>>
|+ microsoft.teamfoundation.git.coreservices.ni!?
|+ microsoft.codeanalysis.remote.workspaces!Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1+<TryInvokeStreamAsync>d__21`1[System.__Canon,Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeData].MoveNext()
|+ microsoft.visualstudio.languageservices.ni!Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.VisualStudioDesignerAttributeService+<ProcessProjectAsync>d__14.MoveNext()
|+ microsoft.visualstudio.languageservices.ni!Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.VisualStudioDesignerAttributeService+<ProcessWorkspaceChangeAsync>d__12.MoveNext()
|+ microsoft.visualstudio.languageservices.ni!Microsoft.CodeAnalysis.Remote.RemoteHostClient+<TryInvokeStreamAsync>d__20`2[System.__Canon,Microsoft.CodeAnalysis.DesignerAttribute.DesignerAttributeData].MoveNext()

```

**Comment by CyrusNajmabadi** [comment]
Preferred fix: https://github.com/dotnet/roslyn/pull/64870

**Comment by genlu** [comment]
Closed in favor of https://github.com/dotnet/roslyn/pull/64873

**Comment by genlu** [comment]
@CyrusNajmabadi FYI there's another RPS regression related to the change being reverted, in case you missed it

This also caused an assembly load in UWP test. It seems the assembly "Microsoft.VisualStudio.Design.ni.dll" is loaded in baseline too, but only after "0200.Xaml Designer Load" scenario completed, but now we are loading it before "0200.Xaml Designer Load" starts.
```
Name
 Image Load Microsoft.VisualStudio.Design.ni.dll (C:\Windows\assembly\NativeImages_v4.0.30319_64\Microsoft.V1de0ecc7#\5d1368f8dfbb87b7d62c2a3f9f13ca1a\)
+ module ntoskrnl <<ntoskrnl!?>>
 + module ntdll <<ntdll!LdrLoadDll>>
  + module kernelbase <<kernelbase!LoadLibraryExW>>
   + module clr <<clr!AssemblyNative::Load>>
    + module mscorlib.ni <<mscorlib.ni!DomainNeutralILStubClass.IL_STUB_COMtoCLR(IntPtr, IntPtr, IntPtr)>>
     + module clr <<clr!GenericComCallStub>>
      + module msenv <<msenv!?>>
       + module microsoft.visualstudio.interop.ni <<microsoft.visualstudio.interop.ni!DomainBoundILStubClass.IL_STUB_CLRtoCOM(System.Guid ByRef, System.Guid ByRef, IntPtr ByRef)>>
        + module microsoft.visualstudio.shell.framework.ni <<microsoft.visualstudio.shell.framework.ni!ServiceProvider.GetService>>
         + module microsoft.visualstudio.languageservices.ni <<microsoft.visualstudio.languageservices.ni!Microsoft.VisualStudio.LanguageServices.Implementation.DesignerAttribute.VisualStudioDesignerAttributeService+<NotifyLegacyProjectSystemAsync>d__18.MoveNext()>>

```

**Pull request closed without merging**
