### PR TITLE
Misc infrastructure fixes

### PR DESCRIPTION
**Pull request by jaredpar**
Includes:

- Fix publish error on Build.Server.Log
- Fix cancellation race in our build task

### CODE REVIEW

**Comment by jaredpar** [comment]
@dotnet/roslyn-infrastructure, @agocke, @chsienki, @RikkiGibson for review

**Comment by jaredpar** [comment]
Can't remember the last time I got six sign offs on an infra PR. Most approved infra PR of all time. Now if only BYOC stop protesting and run the tests ...

**Comment by JoeRobich** [comment]
@jaredpar  I was wrong, earlier, to blame BYOC, we are on a temp-2019 agent pool. Each PR runs 8 legs in this pool. The pool has 10 machines assigned to it. Each PR opened eats up the pool for roughly an hour and it really adds up.

**Comment by jaredpar** [comment]
@JoeRobich somehow BYOC got mis-merged out. Have a PR out to turn it back on. https://github.com/dotnet/roslyn/pull/34656

**Pull request merged**
