### PR TITLE
Be resilient to running with System.IEquatable can not be found.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/20158

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @Pilchie 

Easier to review as https://github.com/dotnet/roslyn/pull/20176/files?w=1

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz 

**Customer scenario**

Customer gets goldbar while moving their caret around an existing class.  This can happen while projects are loading, or if the projects loaded 'strangely' (i.e. references for projects didn't load).  This seems to be an issue that's happening more often now due to issues with things like CPS, DPL and LSL.

**Bugs this fixes:**

Fixes #20158

**Workarounds, if any**

None.

**Risk**

Low.

**Performance impact**

Low.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Our code analyzers have generally always assumed that core libraries (like mscorlib) will always be loaded properly.  For reasons outsie the scope of this fix, it now seems to be far more common that this doesn't happen.  Because we're not loading core libraries, types we expect to be there can't be found.  Our analyzers aren't resilient to this and can end up crashing.

**How was the bug found?**

Dogfooding.

**Comment by MattGertz** [comment]
@CyrusNajmabadi I haven't seen GoldBar used in this context.  Is that equivalent to non-fatal Watson?

**Comment by MattGertz** [comment]
(Proactively setting label since I'm guessing the answer is "yes.")

**Comment by CyrusNajmabadi** [comment]
@MattGertz Yes.  I should have been clearer.  The user gets a goldbar caused by the NFW.

**Comment by MattGertz** [comment]
Groovy, thanks.

**Pull request merged**
