### PR TITLE
A nameof() expression is always legal in an expression tree, as it is a constant

### LINKED ISSUE #3923: Nameof of method group in expression tree triggers debug assert failure
This assert fails: https://github.com/dotnet/roslyn/blob/cedbe7b83c22ec64c872cd0622d8fe2b359c5ae1/src/Compilers/CSharp/Portable/Lowering/DiagnosticsPass_ExpressionTrees.cs#L526

```csharp
using System;
using System.Linq.Expressions;

class Program
{
    static void Main()
    {
        Expression<Func<string>> func = () => nameof(Main);
    }
}
```

### PR DESCRIPTION
**Pull request by gafter**
Fixes #3923

(The analogous situation isn't a bug in VB)

@AlekseyTs @VSadov @jaredpar @agocke Please review

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1:

**Comment by agocke** [comment]
:+1:

**Comment by AlekseyTs** [comment]
@gafter, Could you please elaborate on: "The analogous situation isn't a bug in VB." Does it mean that VB handles this properly, i.e. doesn't assert and an expression tree contains an expected constant? LGTM, BTW.

**Comment by gafter** [comment]
@AlekseyTs VB behaves as expected at compile-time and at runtime. You can verify it with

```vb
Imports System.Linq.Expressions

Module Module1

    Sub Main()
        Dim ex As Expression(Of Func(Of String)) = Function() NameOf(Main)
        Console.WriteLine(ex)
        Console.WriteLine(ex.Compile()())
    End Sub

End Module
```

**Pull request merged**
