### PR TITLE
Add MetadataImportOptions to public compilation options constructor and add validation for the specified value.

### PR DESCRIPTION
**Pull request by AlekseyTs**
This is a follow-up for https://github.com/dotnet/roslyn/pull/24468

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by jcouv** [comment]
@jaredpar for ask-mode approval for 15.7. Thanks

**Comment by AlekseyTs** [comment]
Ping @jaredpar for ask-mode approval for 15.7. Thanks

**Comment by jaredpar** [comment]
Approved

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
