### PR TITLE
switch perf correctness to dev15-rc

### PR DESCRIPTION
**Pull request by TyOverby**
@jaredpar @dotnet/roslyn-perf @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tannergooding** [comment]
@TyOverby is this the same machine configuration as the `windows-perf-internal` machines. I feel like we aren't properly testing correctness if it isn't

**Comment by TyOverby** [comment]
@tannergooding: nope.  "perf correctness" run on VMs, while the actual perf tests run on physical machines.  This is because we run "correctness" on every PR, while we only run the perf tests on-demand (and on rolling releases) because we don't have enough machines to do it on every PR.

**Comment by tannergooding** [comment]
I realize that much. I was asking if the software and OS version on the machine are otherwise the same.

**Comment by TyOverby** [comment]
@tannergooding should be, yeah.  Unfortunately, @rchande  and I have to update the VS version, so sometimes we lag behind.

This "correctness" job just makes sure that our tests compile and run.

**Comment by TyOverby** [comment]
Ah.  I might have misunderstood @jaredpar in an email thread.  I was under the assumption that `latest-or-auto-dev15-rc` was our current "base" vm.  

Should this be `latest-or-auto`?

**Comment by tannergooding** [comment]
No, `latest-or-auto-dev15-rc` is the latest. It contains VS 2017 RC4.

**Comment by jaredpar** [comment]
@jasonmalinowski not understanding the push back on this.  All but one of the legs that use VS are using the same VS tag.  The perf correctness leg was simply missed last time we changed machine tag.  This is fixing that particular miss.  

If there is a separate question of why we're usign that version of VS then that's fine.  But seems like we can adrdess that in a separate issue.

**Comment by jasonmalinowski** [comment]
@jaredpar My concern is `latest-or-auto-dev15` is being used everywhere else in the file, expect VSI tests. Should this always be the same as the VSI tests? Or something else? Isn't `latest-or-auto-dev15` newer than RC? If I was handed this file without being able to see version history, would I believe the differences are intentional or an oversight?

If the answer is "this and VSI tests should be the same", then we might want to consider a variable or a comment or something.

**Comment by tannergooding** [comment]
No, latest-or-auto-dev15 is pre-willow. We had to create a separate label (latest-or-auto-dev15-rc) for post-willow since the environment variables and installation layout was different (and would potentially break people who didn't support it yet).

Realistically, everything should be using latest-or-auto-dev15-rc so they are on VS 2017 RC4.

**Comment by TyOverby** [comment]
@jasonmalinowski: The perf-correctness test should be on the same machines that do our unit tests, not our VS tests

**Comment by jasonmalinowski** [comment]
@TyOverby But isn't that exactly backwards from what this change is doing?

**Comment by TyOverby** [comment]
Wait, yeah, I got confused.  The world seems fine as it is.

@jaredpar Why did you want me to change this?

**Comment by jaredpar** [comment]
> Why did you want me to change this?

The pre-willow versions of VS 2017 do not implement the locate VS APIs.  We're presently using a hack to discover them.  I'd rather remove the hack as it's being keopt around for this single leg.

**Comment by TyOverby** [comment]
Why does this leg use the locate-vs-api?  The only thing I could think of would be that we might need to locate vsi.exe

**Comment by jaredpar** [comment]
It uses the locate-vs API in my branch where I'm trying ot centralize how ew use MSBuild.

**Comment by jaredpar** [comment]
This MSBuild 15.0 has two specific bugs that are making it very difficult for me to get work done:

1. It does not participate in the locate-vs API.  That adds extra logic to test and maintain to our scripts (seems to work by accident today vs. design). 
1. NuGet.exe special cases this particular version of MSBuild 15.0.  Even if you pass an explicit MSBuild path to NuGet.exe it will still try and load this extra version of MSBuild.  This results in tons of warnings during restore. 

This bug has already cost me a day of deveolpment time trying to sort out.  There is no reason to keep this specific Jenkins label around (except to cause more pain).

**Comment by TyOverby** [comment]
> There is no reason to keep this specific Jenkins label around

Should I switch the unit tests over in this PR now?

**Comment by jaredpar** [comment]
> Should I switch the unit tests over in this PR now?

That's fine by me.  I'm going to switch them to win2016 in 1 week though.

**Comment by TyOverby** [comment]
@jaredpar @jasonmalinowski I've updated our unit tests as well.

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by TyOverby** [comment]
Since I didn't touch the VSI tests, can I merge regardless of the VSI timeout?

**Comment by tannergooding** [comment]
Yes, VSI tests are known to be blocked right now.

**Pull request merged**
