### PR TITLE
Allow expression variables in lambdas within constructor and field initializers.

### LINKED ISSUE #16935: Unexpected error CS8200 for an expression variable declared within a lambda within a field initializer.
```
        [Fact]
        public void GlobalCode_Lambda_02()
        {
            var source =
@"
System.Func<bool> l = () => TakeOutParam(1, out int x1) && Dummy(x1); 
System.Console.WriteLine(l());

static bool Dummy(int x) 
{
    System.Console.WriteLine(x);
    return true;
}

static bool TakeOutParam(int y, out int x) 
{
    x = y;
    return true;
}
";
            var compilation = CreateCompilationWithMscorlib45(source, options: TestOptions.ReleaseExe.WithScriptClassName("Script"), parseOptions: TestOptions.Script);
            CompileAndVerify(compilation, expectedOutput: @"1
True");

            var tree = compilation.SyntaxTrees.Single();
            var model = compilation.GetSemanticModel(tree);

            var x1Decl = GetOutVarDeclarations(tree, "x1").Single();
            var x1Ref = GetReferences(tree, "x1").Single();
            VerifyModelForOutVar(model, x1Decl, x1Ref);
        }
```

Result:
```
(2,49): error CS8200: Out variable and pattern variable declarations are not allowed within constructor initializers, field initializers, or property initializers.
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #16935.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
test vsi please

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@gafter 
> We should have a test demonstrating that the issue is addressed in scripting.

There is such a test - GlobalCode_Lambda_02.

> I suggest moving the test for the error to BindConstructorInitializer (where we WrapWithVariablesIfAny) and into BindVariableOrAutoPropInitializer (similarly) ...

Thank you for the suggestion. I am fine with the structure of the code as it is.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@MeiChin-Tsai For 15.1 sign-off
@jaredpar FYI

**Comment by MeiChin-Tsai** [comment]
go ahead.

**Pull request merged**
