### PR TITLE
Merge master into post-dev15

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from master into post-dev15.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-master-into-post-dev15-20170124-100216
git reset --hard upstream/post-dev15
git merge upstream/master
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-master-into-post-dev15-20170124-100216 --force
```

Once all conflicts are resolved and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by jmarolf** [comment]
Merging as this was a cross cutting change so ETA will not pass

**Comment by alrz** [comment]
@jmarolf Can I ask what's that eta test? Cause it failed to pass a few times for my prs as well.

**Comment by jmarolf** [comment]
@alrz Cross cutting changes have now been merged into post-dev15.  Everything should pass now

**Pull request merged**
