### PR TITLE
Rename codefix predefined name

### PR DESCRIPTION
**Pull request by DoctorKrolic**
When implementing `Make type partial` codefix I forgot to rename predefined codefix name. This little PR fixes that. But since I'm modifying the file anyway, I also sorted its content

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
`rosly-CI` is again stuck at infinite `Waiting for status to be reported`. I've seen this _a lot_ in my recent PRs. Something is definitely broken...

**Comment by arkalyanms** [comment]
> `rosly-CI` is again stuck at infinite `Waiting for status to be reported`. I've seen this _a lot_ in my recent PRs. Something is definitely broken...

It should get addressed by https://github.com/dotnet/roslyn/pull/67342

**Comment by CyrusNajmabadi** [comment]
@arkalyanms https://github.com/dotnet/roslyn/pull/67342 was merged, but this pr is still stuck, despite having code merged into it :(

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi Can you perform `/azp run` command to resolve the bug here? If the infra team needs to catch such state for investigation they can look at https://github.com/dotnet/roslyn/pull/67283, it has currently the same problem

**Comment by arkalyanms** [comment]
> @arkalyanms #67342 was merged, but this pr is still stuck, despite having code merged into it :(

Kicked off now - https://dev.azure.com/dnceng-public/public/_build/results?buildId=208835&view=results

**Pull request merged**
