### PR TITLE
Don't cache package information for non-C#/VB languages.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
**Customer scenario**

TypeScript is encountering thousands of NFWs due to a bug in NuGet.  Specifically, Roslyn caches NuGet information for all the projects in a solution.  However, when we ask NuGet for information about the TypeScript project, NuGet crashes because it doesn't expect this type of project.  We're 'fixing' this on the Roslyn end by not even querying NuGet about these projects.  A good long-term fix wouldbe to get Nuget to not throw exceptions in these cases.

**Bugs this fixes:** 

(either VSO or GitHub links)

**Workarounds, if any**

None.

**Risk**

Very low.

**Performance impact**

Very low.

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

Roslyn added the "Add nuget package" feature.  In order for this feature to work, we need to know what packages are already installed for all projects.  So we collect this data in the background.  Querying Nuget about the TS project ends up throwing an exception in the bowels of Nuget.  We catch this, but it still has ended up with 22,000 hits on RC3.

**How was the bug found?**

Watson system.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
> Did you debug and verify that this fixes the issue? 

Not yet.

@vladima I don't have TS on my VS install.  Can you pull this down and try yourself locally at all?

**Comment by CyrusNajmabadi** [comment]
actually @Pilchie is going to try things out.

**Comment by Pilchie** [comment]
I pulled it down and verified that I no longer hit the exception with this change.

**Comment by Pilchie** [comment]
Per @MattGertz given the lack of visible impact, let's move this to `post-dev15`.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Pull request merged**
