### PR TITLE
Avoid double typechecks in simple code checks

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Review by ryzngard — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
@jcouv @cston   for two lines of compiler change :)

**Review by cston — APPROVED** [review]
Compiler changes LGTM.

**Review by sharwell — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1)

**Comment by jcouv** [comment]
@CyrusNajmabadi PR can be merged/squashed. Thanks

**Comment by CyrusNajmabadi** [comment]
Done.  Thanks!

**Pull request merged**
