### PR TITLE
Revert "Revert "Merge pull request #7510 from CyrusNajmabadi/analysisSpeedup""

### PR DESCRIPTION
**Pull request by KevinH-MS**
Reverts dotnet/roslyn#8911

My revert didn't help perf, so revert'ing it...

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @davkean @basoundr @CyrusNajmabadi

**Comment by davkean** [comment]
tag @Pilchie @ManishJayaswal as a heads up.

**Comment by davkean** [comment]
:+1:

**Comment by davkean** [comment]
Merging this and kicking off a stabilization build ready for insertion. We think we've found the problem and want to make sure this change is in.

**Pull request merged**
