### PR TITLE
Update tuples and deconstruction specs with quickstart/install steps

### PR DESCRIPTION
**Pull request by jcouv**
@natidea @dotnet/roslyn-compiler for review. This is a docs-only change.
I removed the `ValueTuples.cs` file which was a prototype for the VT library.

### CODE REVIEW

**Comment by agocke** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by natidea** [comment]
👍

**Comment by natidea** [comment]
Fyi @MadsTorgersen

**Pull request merged**
