### PR TITLE
Do a better job inferring where type parameters will be used when generating methods.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/11141

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by jmarolf** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
