### PR TITLE
Run VB Syntax tests on CoreClr

### PR DESCRIPTION
**Pull request by jaredpar**
This gets our VB syntax tests running on CoreClr.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler for review

**Comment by tmeschter** [comment]
test loc

**Comment by tmeschter** [comment]
Ignore the windows_loc_status_prtest check. I was just making sure it worked. :-)

**Comment by tmeschter** [comment]
@jaredpar This particular leg does not (yet) run automatically, only with an explicit "test loc". I expect it will only be on automatically in release branches close to release, to ensure we don't accidently add unlocalized resources.

**Comment by jaredpar** [comment]
@AdamSpeight2008 they were building against desktop hence can't run on CoreClr.

**Pull request merged**
