### PR TITLE
Be resilient to getting an empty list of diagnostics when fixing all.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/15999

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by Pilchie** [comment]
Tagging @MattGertz for approval here.

@CyrusNajmabadi Can you file a VSO bug for shiproom to track?

**Comment by MattGertz** [comment]
(Will need ASK template.)

**Comment by CyrusNajmabadi** [comment]
Customer scenario

Running 'fix all' on a 'simplify type names' error occasionally crashes.

Bugs this fixes:

Fixes #15999

Workarounds, if any

Customer doesn't run 'fix all'.

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

This is essentially blocking a whole feature space.  i.e. "i can trust the IDE to go and fix up all my issues'.

Risk

Extremely low.

Performance impact

Low/none.

Is this a regression from a previous update?

No.

Root cause analysis:

We have a system where one side produces diagnostics and the 'fix all' system consumes them.  It was thought that the production side would never produce an empty set of diagnostics for a document.  So Fix-all always assumed there was at least one diagnostic per document.  This assumption doesn't hold true, and it appears to be possible to get an empty list of diagnostics.  We now guard against that.

How did we miss it? What tests are we adding to guard against it in the future?

This fell through the combination of multiple complex systems.

How was the bug found?

Internal customer reporting.

**Comment by CyrusNajmabadi** [comment]
tagging @MattGertz @natidea

**Pull request merged**
