### PR TITLE
Add a public API for Inheritance Margin

### PR DESCRIPTION
**Pull request by sharwell**
Adds an adapter assembly to avoid the need for reflection in [tunnelvisionlabs/InheritanceMargin](https://github.com/tunnelvisionlabs/InheritanceMargin).

See #31393.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
It seems we should just properly expose this API. Roslyn is supposed to be an API for understanding languages, and this squarely falls within that goal.

The precedent this would set also seems problematic for me: IVT is challenging enough as it is; non-first-party extensions most definitely should not be granted it.

**Comment by sharwell** [comment]
> non-first-party extensions most definitely should not be granted it.

There is no external IVT involved here. It follows the policy defined in #31393, where no external IVTs are allowed regardless of who maintains the package.

**Comment by jasonmalinowski** [comment]
Oh, that seems even worse, since anybody else can (and will) use the hook then. Let's just make a proper public API here.

**Comment by sharwell** [comment]
Superseded by #31941

**Pull request closed without merging**
