### PR TITLE
Make it so that refactorings can be ordered.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Preemptively merging in.  Let me know if there are any changes you want made here.

**Comment by Pilchie** [comment]
Are any of ours ordered already?  Should they be?  Should we have tests for them?

:+1: for this change on it's own, but it's not clear if it's going to suddenly cause re-ordering of things.

**Comment by CyrusNajmabadi** [comment]
None of our have been ordered yet.  I discoverd this because i wanted "Generate constructor from members" to be ordered before "Generate equals and gethashcode from members" and it wasn't working properly.  We should have tests for this, and i will add some to the integration test harness.

**Pull request merged**
