### PR TITLE
add ubuntu 16.04 to CI

### PR DESCRIPTION
**Pull request by TyOverby**
Closes https://github.com/dotnet/roslyn/issues/17533

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by TyOverby** [comment]
@dotnet-bot test ci please

**Comment by TyOverby** [comment]
Tested on the generated CI job: https://ci.dot.net/job/dotnet_roslyn/job/master/job/GenPRTest/job/ubuntu_16_debug_prtest/1/console using https://github.com/dotnet/roslyn/pull/17386 as the PR to test

**Comment by TyOverby** [comment]
Oops, meant to tag you all on the PR, not the issue

 @mmitche @jaredpar @dotnet/roslyn-infrastructure

**Comment by tannergooding** [comment]
We should probably add release builds. I'm pretty sure they are only missing because we weren't always on a dynamic pool.

**Comment by TyOverby** [comment]
@tannergooding Will follow up in https://github.com/dotnet/roslyn/issues/17573

**Comment by TyOverby** [comment]
@mmitche Can I have another review?

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
