### PR TITLE
Loc update

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
Latest translations.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@cristianosuzuki77 Is this the final update for 16.9 or should we expect more?

**Comment by cristianosuzuki77** [comment]
As for new strings, this is the final.
For the suggestions it will come later next week due to international holidays.

**Comment by JoeRobich** [comment]
> As for new strings, this is the final.

Thanks. We'll take this PR for approval.

**Comment by wli3** [comment]
@JoeRobich SDK close tomorrow. Please merge this today and insert to SDK

**Comment by JoeRobich** [comment]
> @JoeRobich SDK close tomorrow. Please merge this today and insert to SDK

@wli3 We just got approval to take this change.

**Review by JoeRobich — APPROVED** [review]

**Pull request merged**
