### PR TITLE
Disable formatting analyzers

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by sharwell** [comment]
📝 This is implemented as a permanent removal. If the intent is to only disable it in compiler code prior to the 16.4 branch, we should do so via .editorconfig instead.

**Comment by agocke** [comment]
On my machine it looks like these are the numbers:

Without style analyzers:

```
real    0m14.220s
user    0m0.000s
sys     0m0.031s
```

With style analyzers:

```
real    0m18.933s
user    0m0.000s
sys     0m0.031s
```

**Comment by agocke** [comment]
And without analyzers at all:

```
real    0m10.879s
user    0m0.000s
sys     0m0.062s
```

So style analyzers are a big chunk, but we have a ways to go.

**Comment by agocke** [comment]
Notably the build is only about 1 minute faster, even though a single project build is significantly faster locally, so this may not improve our CI speed that much.

**Pull request closed without merging**
