### PR TITLE
Updates SRM to 1.2.0-rc2-23608 and DSR to 1.0.7-beta1

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn

**Comment by davkean** [comment]
Have you updated the zip file?

**Comment by davkean** [comment]
Closed and reopened to resync with Jenkins.

**Comment by tmat** [comment]
@davkean Not yet, forgot about that :(

**Comment by jasonmalinowski** [comment]
Why do we have so many projects specifying the versions to some of these when the NuGet flowing of packages would already do the same thing?

**Comment by tmat** [comment]
@jasonmalinowski A few of them might be redundant.

**Comment by davkean** [comment]
This PR appears to have broken restore on linux, please investigate that.

**Comment by tmat** [comment]
ETA test failure expected. Corresponding change is needed in internal repo.

**Comment by davkean** [comment]
Please do not merge this in, until we have a plan around the end-to-end validation of this change.

**Comment by tmat** [comment]
Superseded by https://github.com/dotnet/roslyn/pull/7517

**Pull request closed without merging**
