### PR TITLE
Change feature flag title

### PR DESCRIPTION
**Pull request by dibarbet**
was requested by VS core to align with other feature flag names.

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]
Unless all of the other feature flags are changing, this seems like it makes it _less_ consistent ¯\\\_(ツ)_/¯

**Review by davidwengier — APPROVED** [review]
Unless all of the other feature flags are changing, this seems like it makes it _less_ consistent ¯\\\_(ツ)_/¯

**Comment by davidwengier** [comment]
Thanks GitHub!

**Comment by dibarbet** [comment]
> Unless all of the other feature flags are changing, this seems like it makes it _less_ consistent ¯\_(ツ)_/¯

I believe they're reaching out to everyone

**Pull request merged**
