### PR TITLE
csi improvements

### PR DESCRIPTION
**Pull request by tmat**
Improves and cleans up handling of command line arguments for csi.

Adds some alternative forms for arguments:

csc:

| Existing arg | New arg | Decription
| --- | --- |--- |
| /lib | /libpath, /libpaths | adds directory(ies) to metadata search paths

vbc:

| Existing arg | New arg | Decription
| --- | --- |--- |
| /libpath | /lib /libpaths | adds directory(ies) to metadata search paths 

csi:

| Existing arg | New arg | Description
| --- | --- |--- |
| | /lib, /libpath, /libpaths | adds directory(ies) to metadata search paths
| | /loadpath, /loadpaths | adds directory(ies) to source search paths
| /u, /using | /usings, /import, /imports | adds import(s) to global imports

Also changes "--" to match ruby/python/*nix. It indicates that the remaining arguments should not be treated as options.

csi only accepts a single script on the command line, any arguments following the script file name is now considered an argument to the script, not to csi.

| Command line |                   Script args:|
| --- | --- |
| csi -- script.csx b c |          ["b", "c"], runs script file "script.csx"|
| csi -- @script.csx a b c |          ["a", "b", "c"], runs script file "@script.csx"| 
| csi -- -script.csx a b c |          ["a", "b", "c"], runs script file "-script.csx"| 
| csi script.csx -- a b c |       ["--", "a", "b", "c"]|
| csi script.csx a b c |         ["a", "b", "c"]|
| csi script.csx a -- b c |      ["a", "--", "b", "c"]|

"/i" or "-i" is now used to launch REPL after executing specified script with arguments:

```
csi -i script.csx a b c
output of script.csx
> Args
List<string>(3) { "a", "b", "c" }
``` 

The design mimics Python.

Fixes https://github.com/dotnet/roslyn/issues/5277

### CODE REVIEW

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
test win please

**Comment by tmat** [comment]
@dotnet/roslyn-compiler @amcasey @KevinH-MS @cston

**Comment by gafter** [comment]
Do you mean the rest of the arguments after -- are treated as file names?

**Comment by tmat** [comment]
@gafter Yes, or script arguments.

**Comment by amcasey** [comment]
Does each row of that table have a corresponding unit test?

**Comment by agocke** [comment]
:+1: The `--` change is great.

**Comment by agocke** [comment]
@tmat Actually, some of these results are confusing. Let's chat about the goals here.

**Comment by ManishJayaswal** [comment]
What does the very first case do? If everything following "--" is an argument, what gets run? 
Are you just listing unit tests here?

**Comment by agocke** [comment]
@TyOverby Wrote up a proposed `usage` in the gist here: https://gist.github.com/TyOverby/41ac9e16e44f2db6376c

I agree with his proposed behavior, although I don't think special syntax should be specified for `-i` or `--` -- those should just be additional csi args IMO.

**Comment by TyOverby** [comment]
As a linux user, I would expect the following syntax out of an interpreter CLI.

## Usage

```
    csi [ csi-arguments ] [ -i ]
    csi [ csi-arguments ]  [ script | - ] [ script-arguments ]
    csi [ csi-arguments ] -i [ script-arguments ]
    csi [ csi-arguments ] -- [ script | - ] [ script-arguments ]
    csi [ csi-arguments ] -i -- [ script-arguments ]
```

## Script Arguments 

In all of these executions, I either expect to have my script name to be passed in on the arguments or not.  This is how other scripting languages solve this problem

* Python: Always pass in script name, then script-arguments (script-name is the empty string if used in interactive mode)
* Ruby: Never pass in script name 
* Node: Always pass in executable name (`/usr/bin/node`), script name if it exists (bad!)

I'm ok with any of these decisions as long as it's consistent.  That said, I think Ruby's option is the better choice and I'll use that in further examples.

## The meaning of "--"

"--" should only mean "we are done parsing csi-arguments."  If we have already started parsing csi-arguments, then include the "--" in the script-arguments, otherwise leave it out.

```
csi -- -test.csx a b c    =>   run -test.csx with ["a",  "b", "c"]
csi test.csx -- a b c     =>   run test.csx with  ["--", "a", "b", "c"]
```

For example, there should be no difference between
```
csi -- script.csx a b c
```
and
```
csi script.csx a b c
```

## The meaning of "-i"
When "-i" is passed, csi will be started in "interactive mode" and a file name will not be looked for.

The only other way to enter "interactive mode" would be to pass in no script-arguments.

```bash 
csi          # Open in interactive mode
csi -i       # Open in interactive mode
csi a b c    # Try to execute the script "a"
csi -i a b c # Open interactive mode with arguments "a", "b", and "c"
```

These semantics are the same as python's 

## The meaning of "-"
When a single dash "-" is used in the place of a filename, instead of reading a file, stdin is used instead.

# Conclusion

The CLI experience is really important, especially for long-time unix hackers for which this release will be their first time using tools made by Microsoft.

**Comment by TyOverby** [comment]
> I agree with his proposed behavior, although I don't think special syntax should be specified for -i or -- -- those should just be additional csi args IMO.

Totally agree on `-i`, but because `--` has special semantic meaning when it comes to parsing the rest of the arguments, I left it in the usage section in order to draw attention to those semantics.

**Comment by tmat** [comment]
Yeah, changing - to -i. We can implement - later.

**Comment by TyOverby** [comment]
Specifically, in the table, here are some proposed script argument changes:

| Command line |                   Script args(old)| Script args (proposed)|
| --- | --- | --- |
| csi -- script.csx b c |          ["script.csx", "b", "c"]|  ["b", "c"], runs "script.csx"|
| csi -- @script.csx a b c |          ["a", "b", "c"], runs script file "@script.csx"|  [same as old] |
| csi -- -script.csx a b c |          ["a", "b", "c"], runs script file "-script.csx"|  [same as old] |
| csi script.csx -- a b c |       ["--", "a", "b", "c"]| [same as old] |
| csi script.csx a b c |         ["a", "b", "c"]| [same as old] |
| csi script.csx a -- b c |      ["a", "--", "b", "c"]| [same as old] |
| csi -i script.csx a b c |  | ["script.csx", "a", "b", "c"] in interactive
| csi -i -- script.csx a b c |  | ["script.csx", "a", "b", "c"] in interactive

**Comment by tmat** [comment]
@TyOverby I have modified the impl to match Python, except for not implementing support for "-" (we can add it later).

The behavior is slightly different from what you suggest in the table above. I have update the table.

**Comment by TyOverby** [comment]
@tmat: How are you judging if an argument to csi is a file or not?

What is it that makes these different?
```bash
csi -i a b c
csi -i script.csx a b c
```

**Comment by tmat** [comment]
@TyOverby It always is.

**Comment by TyOverby** [comment]
@tmat So is there no way to pass in arguments to an interpreted mode that doesn't run a script by default?

**Comment by tmat** [comment]
Not for U1. Will add later. The scenario is imo not important.

**Comment by TyOverby** [comment]
Ok great!  LGTM

**Comment by ManishJayaswal** [comment]
@JohnHamby FYI - this would resolve #5288

**Comment by ManishJayaswal** [comment]
@tmat what would be the syntax to pass arguments to csi interactive mode without a script file when we add it later?

**Comment by tmat** [comment]
@ManishJayaswal 
Syntax: "-" would be used instead of the file name, e.g. "csi - a b c"



API review - yes, it's separate.

**Comment by ManishJayaswal** [comment]
@tmat Ok. So the example at the very top in description is incorrect then?

csi -i a b c
> Args
List<string>(3) { "a", "b", "c" }

**Comment by tmat** [comment]
Right. Fixed.

**Comment by ManishJayaswal** [comment]
:+1:

**Pull request merged**
