### PR TITLE
Organize Interactive solution folder...

### PR DESCRIPTION
**Pull request by KevinH-MS**
This change adds a couple sub folders (Core, language-specific, Setup) and moves BasicVisualStudioRepl back to Interactive.

capture

### CODE REVIEW

**Comment by KevinH-MS** [comment]
@tmat @cston @amcasey any thoughts/objections?

**Comment by amcasey** [comment]
I think the IDE divides by layer, rather than by language.  E.g. Workspaces, Features, EditorFeatures, VisualStudio.  @dpoeschl?

**Comment by tmat** [comment]
Yeah, feels like all VS stuff should be together.

**Comment by KevinH-MS** [comment]
I find this a bit less handy, but if we went this route, I'd just move the VS stuff to VS and leave all the remaining Interactive stuff in a single folder:

capture

PR has been updated...let me know what you think...

**Comment by KevinH-MS** [comment]
Another update (based on some offline feedback):

capture

**Comment by amcasey** [comment]
LGTM

**Comment by tmat** [comment]
Perhaps add Hosts (for csi, vbi, InteractiveHost, -Test) and Window (IW, IWT) folders.

**Comment by KevinH-MS** [comment]
Added "Host" folder:

capture

Note: I left IW and IWT at the top level because they kind of make logical sense there, and I feel like it's a hair too much indirection (original intent was just to improve discoverability of what I was looking for, and having these two projects at the top level seems consistent with that).

**Comment by amcasey** [comment]
I liked it better without the Host folder, especially if csi and vbi not stay there.

**Comment by tmat** [comment]
More hosts will be added in future.

**Comment by tmat** [comment]
Actually, one more thing - VisualStudioInteractiveWindow should be in the same directory as InteractiveWindow, since both don't have a dependency on Roslyn. So I would actually add the Window directory and put those there.

**Comment by KevinH-MS** [comment]
@tmat In that case, I'm inclined to just put IW and IWT in the "Interactive\Visual Studio" folder (because they depend on VS dlls).

**Comment by tmat** [comment]
@KevinH-MS But IW doesn't depend on VS.

**Comment by tmat** [comment]
@KevinH-MS They only depend on the editor. Like EditorFeatures

**Comment by KevinH-MS** [comment]
We're not hosting the Editor outside of VS though (except for testing in ETA), so it's effectively the same thing, right?  Potential alternative:

- IW, IWT, VSIS, VSIW all at the top level
- BVSRepl & CSVSRepl in a "Repl" folder

(no sub folder named "VisualStudio")

**Comment by KevinH-MS** [comment]
I realize we have not achieved consensus, but I believe we're most of the way there, so I'm going to merge this and we can make tweaks as necessary.

**Pull request merged**
