### PR TITLE
Fix project system GUIDs for VB projects in Roslyn.sln

### PR DESCRIPTION
**Pull request by sharwell**
This change fixes project load for VB projects using the new projects system with a 15.1 release of Visual Studio.

### CODE REVIEW

**Comment by jaredpar** [comment]
Is this related to our slack discussion about why your solution has load errors?  If so why is this working on some machines but not others?

**Comment by 333fred** [comment]
Depends on what branch you're running. @srivatsn would know which branches have the selector updated, but the release version of VS doesn't have the VB selector enabled, so it will attempt to load in the old project system.

**Comment by sharwell** [comment]
@jaredpar Yes, this change corrects the editing experience I described, which was caused by the new VB projects still getting loaded under the "legacy" project system. As a best guess, at some point Visual Studio was updated to infer the correct project system instead of just using the one specified in the solution file. We can see that 15.1 does this already for C# projects, hence why only Visual Basic projects were having problems.

**Comment by srivatsn** [comment]
@jaredpar if you had the VB VSIX installed, you wouldn't need this change. Otherwise you'll need this for 15.1, 15.2 builds. You don't need this change for 15.3 builds.

**Comment by jasonmalinowski** [comment]
@srivatsn Is this other factory GUID supported long term? i.e. once we have the selector change this doesn't break again?

**Comment by 333fred** [comment]
@jasonmalinowski it's not going to break again. This is actually the GUID for the new project system, the old project system guid is just being intercepted for backcompat.

**Comment by srivatsn** [comment]
Correct - the selector is just a way to redirect to the new guid for compat reasons. Keeping this in won't harm anything except that the solution will not open in VS2015 now.

**Pull request merged**
