### PR TITLE
Remove unused private method

### PR DESCRIPTION
**Pull request by jcouv**
Fixes https://github.com/dotnet/roslyn/issues/18187

@dotnet/roslyn-compiler for review.

### CODE REVIEW

**Comment by cston** [comment]
LGTM

**Comment by jcouv** [comment]
windows_debug_unit64_prtest failed with error below ([details](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/8684/))
```
error CS0016: Could not write to output file 'D:\j\workspace\windows_debug---f1572675\Binaries\Obj\CSharpCompilerSymbolTest\Debug\Roslyn.Compilers.CSharp.Symbol.UnitTests.xml' -- 'The process cannot access the file 'D:\j\workspace\windows_debug---f1572675\Binaries\Obj\CSharpCompilerSymbolTest\Debug\Roslyn.Compilers.CSharp.Symbol.UnitTests.xml' because it is being used by another process.' [D:\j\workspace\windows_debug---f1572675\src\Compilers\CSharp\Test\Symbol\CSharpCompilerSymbolTest.csproj]
```

**Comment by jcouv** [comment]
test windows_debug_unit64_prtest please

**Comment by jcouv** [comment]
test windows_debug_unit64_prtest please

**Pull request merged**
