### PR TITLE
fixed 2 issue where IDE analyzer throws null exception and host analy…

### PR DESCRIPTION
**Pull request by heejaechang**
…zer exception message not going away from error list issue.

### CODE REVIEW

**Comment by heejaechang** [comment]
@Pilchie @srivatsn @ManishJayaswal @CyrusNajmabadi @panopticoncentral @KevinH-MS can you take a look?

**Comment by Pilchie** [comment]
There is zero context about what the issues are or why this fixes them.

**Comment by heejaechang** [comment]
@Pilchie oh sorry. I used same title as email thread. but anyway. so I noticed the null exception from IDE analyzer still happening even after @CyrusNajmabadi fix. so I debug in and notice OOP doesn't actually give in right AnalyzerOption type IDE side use to get workspace option from it.

so that is one fix. the other is, I found issue where vsix analyzers exception doesn't get cleaned up when solution/project goes away. so fixed that as well.

**Comment by heejaechang** [comment]
can I get code review? I am going to create new PR for rc and send out new PR for approval. but one this to be in master as well.

**Comment by CyrusNajmabadi** [comment]
👍

**Pull request merged**
