### PR TITLE
Run our Nuget package index in the OOP process.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @mavasani - can you work with @CyrusNajmabadi so that we can evaluate the performance, memory, and image load impact of this change?

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @Pilchie 

I have manually verified that this works.  Including stepping through the remote process to validate that updating works, as well as validating that everything works in Add-Using when getting results from the OOP process.

**Comment by CyrusNajmabadi** [comment]
Ok.  I did some basic perf testing.  If i just launch the OOP process and i do not load the index in it, then it takes 25MB for my simple console app.

If i launch the OOP process and i load the index, it takes 50MB.  So about 25MB loaded in memory for an 11MB on-disk index.

**Comment by Pilchie** [comment]
What about the impact to VS working set (and VM)?  Are they reduced by not building the Add Using index in-process?  Is there any impact there?

Does enabling the option cause new binaries to be loaded in the VS process before the feature is invoked (like the NuGet ones, or Elfie)?

**Comment by CyrusNajmabadi** [comment]
> Does enabling the option cause new binaries to be loaded in the VS process before the feature is invoked (like the NuGet ones, or Elfie)?

Definitely not elfie.  All elfie stuff is only loaded in the OOP process.  All data we pass to/from VS-OOP is all simple data-types (strings, arrays, etc.).

It does look like we pre-emptively load the nuget packages *if* the option is on.  However, we need to load the packages to know if they're available.  Because if they're not available, then we don't want to offer to show the user the feature.

**Comment by CyrusNajmabadi** [comment]
So we have a bit of a chicken and egg problem.  We *could* potentially try to defer this until the first time the add-using feature makes a query.  However:

1. We're going to make that query almost immediately.  The moment there is a single unbound identifier, we call through this code.  
2. If we defer to this point, we can definitely cause a large delay in typing/code-actions.  That's because just launching and loading all this stuff takes time and will cause blocking.  Also, it's not clear to me if we can load hte nuget package on the BG at all.  They're COM services.  So we may go and hit hte UI thread, which could cause deadlocks as we block on this.

**Comment by Pilchie** [comment]
@CyrusNajmabadi NuGet should always be installed, so I'm not very worried about users getting an error if we fail to load it.

Could we defer the load until an actual item requiring NuGet is selected?  Then the load happens in response to an explicit user action.

**Comment by Pilchie** [comment]
@CyrusNajmabadi should we split this to do the work in OOP even if don't enable by default (yet) for the file load issue?

**Comment by CyrusNajmabadi** [comment]
Changed so that we're sitll off by default.  But that we'll use the OOP process if available.

**Comment by CyrusNajmabadi** [comment]
@Pilchie Review plz?

**Comment by heejaechang** [comment]
nope. 👍

**Pull request merged**
