### PR TITLE
don't assume that a constructor's parent is a TypeBlockSyntax

### LINKED ISSUE #1834: InvalidCastException at VisualBasicSyntaxFactsService.TryGetDeclaredSymbolInfo
Ported from internal work items 1152014 and 1153151.

-----

### Repro
Create a new VB console application then paste this directly below the `Module` definition:

``` VB
Public Sub New()
End Sub
```

### Result
System.InvalidCastException: Unable to cast object of type 'Microsoft.CodeAnalysis.VisualBasic.Syntax.CompilationUnitSyntax' to type 'Microsoft.CodeAnalysis.VisualBasic.Syntax,TypeBlockSyntax' at VisualBasicSyntaxFactsService.TryGetDeclaredSymbolInfo line 742.

### PR DESCRIPTION
**Pull request by brettfo**
In an error parsing scenario, a VB ConstructorBlockSyntax might be parented by something other than a TypeBlockSyntax.  Added a check for this scenario.  I also audited other explicit casts in this function and determined that no other conversions from `CType()` to `TryCast()` were required.

This is a potential preview fix; tagging @Pilchie @dpoeschl @jasonmalinowski @rchande @balajikris @basoundr as reviewers.

Fixes #1834.

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1: Is it worth auditing all CType(..., TypeBlockSyntax) and DirectCast(..., TypeBlockSyntax) in the whole codebase?

**Comment by SLaks** [comment]
Note that in `Script` documents, a constructor may not have a parent at all.

**Comment by brettfo** [comment]
@SLaks, good catch; there are non-error cases where a constructor (or any method for that matter) doesn't have a parent that this fix will also cover.  I've added the appropriate null checks to VBSyntaxFactsService.GetContainer() and CSharpSyntaxFactsService.GetContainer() to keep that null ref from happening.

@Pilchie, I've audited the rest of the codebase and found some other instances where we're blindly assuming a method/property/constructor is parented by a TypeBlockSyntax and I'll file separate issues to investigate and fix those.

**Comment by brettfo** [comment]
retest this please

**Pull request merged**
