### PR TITLE
Don't attempt to keep members sorted by name.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Instead, only keep them grouped by type/staticness/accessibility.  Within a group,
only keep members together if they have the same name.  i.e. keep overloads together,
but do not order non-overloads in any way.

Fixes https://github.com/dotnet/roslyn/issues/15387

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Work in progress. 

1. Need to do VB side.  
2. Move to sharing a ton more code in the code generators.
3. Add lots tests
4. Add option to disable any sort of auto arrangement of members at all.
5. Detect COM interfaces and do not touch them at all.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide  

This changes how we add members to types.  Before, we would attempt to keep members grouped (by type, staticness, and accessibility).  Within those groups, we would also attempt to keep the members sorted alphabetically (if that's the state they were already in).

Now, we do things slightly differently.  We still try to keep things grouped as before.  However, within a group, we don't do anything related to ordering by name.  Instead, the only logic we have is that we attempt to keep items with the *same* name together.  That helps keep overloads together, but otherwise doesn't affect the ordering.

**Comment by CyrusNajmabadi** [comment]
New Option looks like:

image

image

**Comment by jasonmalinowski** [comment]
The checkbox confuses me, because I'm unable to say what it means to uncheck it. I'd propose we instead make this a radio button that is:

> When inserting properties, events, and methods, insert them:
> * by other members of the same kind
> * at the end

And some .editorconfig setting to match like;

    dotnet_add_new_members = grouped_by_kind | at_end

Given that people may have StyleCop enforcement. This also offers a nice extension point should we want "by name" which people might have analyzer enforcement of too.

**Comment by CyrusNajmabadi** [comment]
@jasonmal looks like this now:

image

**Pull request merged**
