### PR TITLE
Revert "Implement GetTypesByMetadataName"

### PR DESCRIPTION
**Pull request by 333fred**
Didn't make it in before the 17.1 bar closed. Reverting for 17.1 and we'll revert the revert in main.

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet/roslyn-infrastructure for a review.

**Review by RikkiGibson — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@333fred @RikkiGibson Was this the only thing merged that didn't make it in? In the past we've sometimes just done a force push of the release branch to bring it back in sync, which avoids reverts of reverts, but that has it's own fun.

**Comment by 333fred** [comment]
> @333fred @RikkiGibson Was this the only thing merged that didn't make it in? In the past we've sometimes just done a force push of the release branch to bring it back in sync, which avoids reverts of reverts, but that has it's own fun.

It is the only thing.

**Comment by 333fred** [comment]
However, given that this has already gone into -vs-deps, I think the cleanest thing is to just merge the revert, then revert the revert in main.

**Pull request merged**
