### PR TITLE
CSharp.DeclarationTable – avoid realizing lazy roots during add/remove operations.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to [AB#1436225](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1436225).

### CODE REVIEW

**Comment by AlekseyTs** [comment]
This is an alternative for #59392.

**Comment by AlekseyTs** [comment]
@sharwell FYI

**Review by 333fred — COMMENTED** [review]
At first glance, I like this approach better than #59392, given the simplicity. I do want to wait for @sharwell's input before approving though.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@333fred 

> I do want to wait for @sharwell's input before approving though.

I think this is a good change on its own. VB's DeclarationTable behaves this way already.

**Review by 333fred — APPROVED** [review]
LGTM (commit 1), as this aligns VB and C#'s implementations. Further optimizations can be applied to both languages as a follow up if needed.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For the second review.

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
