### PR TITLE
Revert "Merge pull request #18972 from CyrusNajmabadi/docHighlights2"

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This reverts commit 8262112e63d0c92bfa421bcb49e54b6a791cabbd, reversing
changes made to 837ca2141fc63d42ea4f6310c07e58624f0ca48a.

--

Right now there are other issues affecting our ability to insert.  So introducing a known (though communicated) breaking change, is not desirable.  So we're going to roll back this break until everything is good.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @dotnet/roslyn-infrastructure @minestarks @paulvanbrenk  @brettfo 

This reverts the merge in of https://github.com/dotnet/roslyn/pull/18972    We're having some insertion issues right now, and we don't want that break to go in and make lives harder.

**Comment by CyrusNajmabadi** [comment]
Will try to merge myself. If i'm not around, anyone is free to merge this in.

**Comment by sharwell** [comment]
@CyrusNajmabadi Is this a "just in case #19357 doesn't fix it", or do you want to preemptively include regardless of the other?

**Comment by CyrusNajmabadi** [comment]
We want to take this no matter what.  This is a change that is (intentionally) known to break TS.  That's something we want to do.  Just not tonight since we didn't successfully insert due to the other change.

**Comment by jasonmalinowski** [comment]
Overriding merge policies so we can get this in to unblock tomorrow's RI. This is a straight revert of a change merged a few hours ago.

**Pull request merged**
