### PR TITLE
Switch to full ngen for Roslyn binaries

### PR DESCRIPTION
**Pull request by genlu**
In Dev17 partial ngen is being removed
Fix https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1336813

### CODE REVIEW

**Review by tmat — APPROVED** [review]

**Review by 333fred — APPROVED** [review]
I cannot wait to not have to worry about optprof data 😆

**Comment by tmat** [comment]
@333fred I think we would still care - the full NGEN uses optprof data to decide how to lay out the generated code.

**Comment by 333fred** [comment]
> @333fred I think we would still care - the full NGEN uses optprof data to decide how to lay out the generated code.

Well now I am sad again.

**Comment by genlu** [comment]
@333fred Hey, at least we won't see as many image size regressions :)

**Pull request merged**
