### PR TITLE
Update versions of Microsoft.DiaSymReader and Microsoft.NetFX20 packages to release versions 1.0.5 and 1.0.3, respectively

### PR DESCRIPTION
**Pull request by tmat**
The packages are currently versioned as pre-release "rc2", which is not appropriate for RTM.

@ManishJayaswal

### CODE REVIEW

**Comment by tmat** [comment]
Note that the RTM packages are not published on NuGet yet, so the PR build is going to fail until they are. Currently waiting on signed build to produce them.

**Comment by tmat** [comment]
@dotnet-bot Retest this, please

**Comment by pharring** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
LGTM

**Comment by pharring** [comment]
Approved 6/5 ML Shiproom

**Pull request merged**
