### PR TITLE
Merge from features/patterns into future

### LINKED ISSUE #9097: Indentation on colon not working for switches with patterns.
In a normal switch, when you type colon in a case clause, the case clause is properly dedented and aligned.  This does not work for case clauses with complex patterns in them.

### LINKED ISSUE #9620: IOperation code crashes with pattern-matching
One way of enabling new features in stabilization is to define the preprocessor symbol `__DEMO__` in the build options. That happens to enable both IOperation and pattern-matching. But the analyzer driver crashes (causing the IDE to crash) when it encounters pattern-matching code.

(This is fixed in the features/patterns branch in https://github.com/dotnet/roslyn/commit/482060e546585207e8e3d1154c74e6bea8ccc451)

### PR DESCRIPTION
**Pull request by gafter**
These changes went into features/patterns before the merge into future was complete. This completes the merge into future.

Fixes #9620 (IDE crash in `__DEMO__` mode)
Fixes #9097 (indentation on ':' for switches with patterns)
(among others)

@jaredpar please review.

### CODE REVIEW

**Comment by gafter** [comment]
Note that this fixes a IDE crash that will be encountered while trying pattern-matching, so it might belong in the `future-stabilization` branch. Please advise.

**Comment by davkean** [comment]
Note: Jenkins went down @ 9.30.

**Comment by jaredpar** [comment]
> Note that this fixes a IDE crash that will be encountered while trying pattern-matching, so it might belong in the future-stabilization branch. Please advise

Where is the test that prevents this regression from happening again?

**Comment by gafter** [comment]
Please file an issue if you'd like additional tests for fixes already integrated into the feature branch. This is not intended to trigger a new code review for the previously reviewed changes.

**Comment by gafter** [comment]
> Where is the test that prevents this regression from happening again?

#9444

**Pull request closed without merging**
