### PR TITLE
Append chars more efficiently when creating doc comment IDs

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Extracted out of prior pr.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-compiler ptal.  Thanks :)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 59)

**Comment by CyrusNajmabadi** [comment]
@jaredpar @jcouv  ptal :)

**Review by cston — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 59)

**Pull request merged**
