### PR TITLE
Delete unused method

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by sharwell** [comment]
New accessor kinds 😨 

* UseExpressionBodyForAccessorsHelper
* BlockSyntaxExtensions.IsSupportedInCSharp6
* SyntaxNodeExtensions.IsReturnableConstruct
* CSharpSyntaxFacts.IsMemberDeclaration
* CSharpSyntaxFacts.CanHaveAccessibility
* CSharpSyntaxFacts.GetDeclarationKind
* FormattingRangeHelper.IsSpecialContainingNode
* CompleteStatementCommandHandler.SemicolonIsMissing
* CSharpConvertAutoPropertyToFullPropertyCodeRefactoringProvider.GetExistingAccessors
* CSharpProximityExpressionsService.AddValueExpression
* BreakpointSpans.TryCreateSpanForNode
* ... still looking

**Comment by Youssef1313** [comment]
@sharwell I've a bunch of PRs that (hopefully) take care of most of these. (Hope I'm not overwhelming the team with this many PRs (~15 small PRs)

**Comment by sharwell** [comment]
works for me

**Review by sharwell — CHANGES_REQUESTED** [review]
📝 This whole method is never used. Rather than test it, we can delete it.

**Review by sharwell — APPROVED** [review]

**Review by jmarolf — APPROVED** [review]

**Pull request merged**
