### PR TITLE
fixed regression on using nuget

### PR DESCRIPTION
**Pull request by heejaechang**
looks like I broke it when I did refactoring on KeepAliveSession by giving in wrong callback object.

fix https://github.com/dotnet/roslyn/issues/22806

opened this for adding unit test - https://github.com/dotnet/roslyn/issues/22808

currently we don't have test around ISymbolSearchService.

**Customer scenario**

Customer's add using through nuget stop working once he installed fresh VS. it still works for update with staled data

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/513584

**Workarounds, if any**

there is no workaround.

**Risk**

no test right now, we should add tests around ISymbolSearchService

**Performance impact**

I don't see any perf impact of this. 

**Is this a regression from a previous update?**

Yes.

**Root cause analysis:**

wrong callback object is given for the OOP to call back to report progress.

**How was the bug found?**

Dogfooding, customer reports.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dpoeschl @dotnet/roslyn-analysis @dotnet/roslyn-ide can you take a look?

**Comment by heejaechang** [comment]
@jinujoseph @dpoeschl probably we want to bring this to next preview once tests are added?

**Comment by dpoeschl** [comment]
A workaround would be to send them the nuget cache file and have them put it on disk (and then it's good after that). Yes, it's awful, but it's technically a workaround.

**Comment by dpoeschl** [comment]
> probably we want to bring this to next preview once tests are added?

Personally, I think we should buddy test it and ship it. Tests are important, but it completely doesn't work today. This could only make it worse if it crashed, right?

**Comment by dpoeschl** [comment]
Getting this when closing the solution / shutting down VS. Talked to @heejaechang, and he can also repro this.

image

**Comment by natidea** [comment]
Approved to merge via [513584](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/513584)

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest please

**Comment by heejaechang** [comment]
@dpoeschl I tried to repro it several times but it doesn't repro. no idea why that showed up. I think we would rather need to find the one who owns that dialog box and ask them to put more info somewhere.

**Comment by heejaechang** [comment]
@dpoeschl  @jinujoseph checking this in. vendor couldn't repro the issue.

**Pull request merged**
