### PR TITLE
Remove some debug-only code...

### LINKED ISSUE #4337: Remove some debug code around late 2015
See #4334 for code added to help diagnose possible determinism issues.

That code has a performance impact in debug mode (it artificially delays computations). That code can be removed after we have been using it for a bit without observing any symptoms, say November 2015 or so.

### PR DESCRIPTION
**Pull request by gafter**
that intentionally slowed down the code to help detect race conditions
Fixes #4337

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by TyOverby** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
