### PR TITLE
Update Language Feature Status.md

### PR DESCRIPTION
**Pull request by RikkiGibson**
@jcouv

### CODE REVIEW

**Review by jcouv — APPROVED** [review]
LGTM Thanks

**Comment by RikkiGibson** [comment]
also @cston to confirm whether you being a reviewer on this feature is expected :)

**Comment by RikkiGibson** [comment]
it sounds like actually @chsienki is supposed to be the second reviewer on this feature. cc @jaredpar.

**Comment by jcouv** [comment]
Confirmed with Jared (Chris is secondary reviewer for the feature). Let's merge.

**Pull request merged**
