### PR TITLE
change all [Fact] private tests to be public

### LINKED ISSUE #3922: Silently ignored unit tests in Roslyn codebase?
https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Test/Semantic/Semantics/NameCollisionTests.cs contains private unit test methods. When this file is opened in the VS2015 RC editor, they are grayed out. Unit tests in other files are always public methods, as far as I have seen. 

So, will these run or are they silently ignored?

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #3922

This is just a style change.

#### rewrite.pl
```perl
#!/bin/perl

my $file = $ARGV[0];
print "this: $file is my file";
open my $fh, '<', $file or die "$!";
$/ = undef; # undefine the newline separator

my $text = <$fh>;
close $fh;
$text =~ s/(\[Fact[^\n]*\n\s*)private/$1public/gms;

open $fh, ">$file" or die "$!";
print $fh $text;
close $fh;
```

### CODE REVIEW

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler Up for review

**Comment by jaredpar** [comment]
:+1:

**Comment by jaredpar** [comment]
I'm still a bit disturbed at your use of perl ...

**Comment by TyOverby** [comment]
@jaredpar Honestly so am I.  @brettfo is a Perl Wizard though; he is partially responsible for this.

**Comment by gafter** [comment]
:+1: :shipit:

**Pull request merged**
