### PR TITLE
Deal with a cancellation exception being thrown through a sync-path in navigate-to.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide   This already went into master, but we should take it in RC.

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz  This can cause a crash in some cases when typing in navigate-to.

**Comment by MattGertz** [comment]
Approved pending the usual paperwork.

**Comment by CyrusNajmabadi** [comment]
retest windows_release_unit32_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit32_prtest  please

**Pull request merged**
