### PR TITLE
Merge stabilization into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-master20160307-160031
git reset --hard upstream/master
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-master20160307-160031 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-infrastructure, @heejaechang: some of these conflicts are in areas I touched; I'll pick up the resolution for this one.

**Comment by heejaechang** [comment]
@jasonmalinowski do I log in to somewhere to fix the merge?

**Comment by jasonmalinowski** [comment]
@heejaechang: I'm taking care of this.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test eta please.

**Comment by genlu** [comment]
@heejaechang @jasonmalinowski Could you please revert this commit before merging (it will show up if you fetch and merge)? I can do it afterward too, just let me know.
```
*DON'T MERGE INTO MASTER* Hide IOperation API behind a feature flag
b03e84783806dc48f240e56188e6473323dc3ba1
```

**Comment by jasonmalinowski** [comment]
We've disabled the GFU test and #9572 is tracking.

**Comment by jasonmalinowski** [comment]
@genlu: not an option since this was carrying along many other fixes. It's merged, please revert at your leasure. If this was a concern, a better process might have been to:

1. Create a branch from the current base of master and stabilization.
2. Made your fix from there, submitted to stabilization.
3. From that branch with your fix, immediately revert it and submit that to master.

At this point, since the master PR would contain both commits, Git should realize it's already merged and then not try merging it again.

**Pull request merged**
