### PR TITLE
IDE change to handle /warnaserror with Warning analyzer bulk configur…

### PR DESCRIPTION
**Pull request by mavasani**
…ation in editorconfig

Underlying issue: #55541
Corresponding batch compiler fix: #58460
This change fixes the code that computes effective severity for Analyzers node. We also need to update the code that computes effective severity for EditorConfig UX, I will file a separate issue for the same.

NOTE: We have #52720 to track avoiding code duplication for computing effective severity between EditorConfig UX and other parts of the IDE

### CODE REVIEW

**Comment by mavasani** [comment]
> We also need to update the code that computes effective severity for EditorConfig UX, I will file a separate issue for the same.

FYI @jmarolf - I'll file an issue for this and assign it to you. I couldn't figure out a trivial fix to thread in CompilationOptions into the below methods used for EditorConfig UX: https://github.com/dotnet/roslyn/blob/bf84ccf384893628e7b33fd695b59372131527ce/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Extensions/DiagnosticDescriptorExtensions.cs#L53-L135

**Review by sharwell — CHANGES_REQUESTED** [review]
For the scenario described by #55541, the Analyzers node and the EditorConfig UX should both show **Warning** as the effective severity. During build or live analysis, the diagnostics reported for these analyzers should appear in the build output and error list as **Error** severity. The different values shown in these locations is intentional and desired.

**Comment by mavasani** [comment]
@sharwell Can we take this to design meeting and confirm with the team?

**Comment by jmarolf** [comment]
Thanks @mavasani. I have a plan for unifying this so I’ll take care of the plumbing there. My general intuition is that the editorconfig ui should be a representation of the file itself. So of the file shows it as a warning I would expect it to display as one. We should do something here though. We could at least hint to the developer that warn-as-error is active in some build configurations

**Comment by mavasani** [comment]
I agree with both your stance. I’ll close out this PR for now.

**Pull request closed without merging**
