### PR TITLE
Do not fail on platforms with incomplete HashAlgorithm APIs

### LINKED ISSUE #2439: [regression] Roslyn deterministic pdb hashing breaks hello world on .net core
Please see the following issue:

https://github.com/dotnet/coreclr/issues/898

It seems Roslyn presumes the presence of the TransformBlock and TransformFinalBlock methods which are not surfaced in .NET core.

### PR DESCRIPTION
**Pull request by gafter**
Fixes #2439 
@jaredpar @richlander

### CODE REVIEW

**Comment by davidfowl** [comment]
Do we need some sorta test for this so it doesn't regress again?

**Comment by tmat** [comment]
CoreCLR testing is being worked on.

**Comment by gafter** [comment]
@jaredpar Can you review this, please?

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
