### PR TITLE
Format conflicts resolved during rename

### LINKED ISSUE #8334: Conflicts resolved during rename should be formatted if appropriate.
Ported from internal bug 100093 (/cc: @brettfo)

1.  Paste into a C# editor:

  ```C#
    static class E
    {
        public static C Bar(this C x, int i) { return x; }
    }
    class C
    {
        int Foo(int i)
        {
            return this.Bar(1).Foo(2);
        }
    }
  ```
2.  Rename 'Bar' to 'Foo'
 
RESULT:
`return E.Foo(this,1).Foo(2);`
There is no space before the 1.
 
EXPECTED:
`return E.Foo(this, 1).Foo(2);`
There should be a space before the 1.

### PR DESCRIPTION
**Pull request by bmay2**
Fixes #8334

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/5846/
// Retest reason: Test failure appears to be unrelated to this PR.  I'll investigate it offline.

Also, @bmay2, is this PR ready for review or is it still a work in progress?  If it's ready I'll get some people to look at it.

**Comment by brettfo** [comment]
Apologies for the test failure again, I've disabled that test since it's not related to your changes.

retest prtest/win/dbg/unit32 please

**Comment by bmay2** [comment]
@brettfo this is ready for review

**Comment by brettfo** [comment]
Tagging @dotnet/roslyn-ide for review.

(Side note, I'll be looking at the failed test, which isn't related to this change.)

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by Pilchie** [comment]
So, this only formats conflicts inside invocation expressions - do we already format other kinds of conflicts? Should we?

**Comment by Pilchie** [comment]
:+1: for what it is though.

**Comment by brettfo** [comment]
@bmay2: Thanks for fixing this!  I'll be merging it shortly.
@Pilchie: As far as I can tell this will only happen for things that look like invocation expressions (although I'm almost certainly wrong) but I've also filed #10406 which covers the VB scenario.

**Pull request merged**
