### PR TITLE
Rewrite CryptoBlobParser to use BlobReader/BlobWriter instead of casts.

### PR DESCRIPTION
**Pull request by marek-safar**
Part of the effort to run Roslyn on big endian machines.

cc @tmat

### CODE REVIEW

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by jaredpar** [comment]
Sorry we've let this PR lag.  I chatted with @tmat today about this work and we do want to work to take this into the tree.  

The one complication is that we're beginning to lock down for our 15.3 release.  This change doesn't seem like it's not going to meet our bar for 15.3 right now.  In particular because we won't be taking the supporting changes in System.Reflection.Metadata until after 15.3.  Hence for the time being I'm going to mark this as milestone 15.later.  

Probably going to be heads down on 15.3 for a couple more weeks.  Once we start coming up from that though going to prioritize moving through the PRs that we pushed off to 15.later.

**Comment by nealef** [comment]
I'm keen for this PR to be accepted as my mono builds for 5.x are stalled. Not sure I can add anything more than moral support.

**Comment by jaredpar** [comment]
@nealef, @marek-safar we're clear of 15.3 work now and can start looking to take this into master. 

One problem though is we did a bit of work on our infrastructure since this PR was opened. Probably going to hit a bunch of Jenkins snags trying to get this to work. Can we close this PR, rebase against master and open a new one?

**Comment by marek-safar** [comment]
@jaredpar rebased on top of master and pushed, do I really have to create a new PR?

**Comment by marek-safar** [comment]
Replaced with https://github.com/dotnet/roslyn/pull/21072 but it's also failing with some weird MEFv2 errros

**Comment by jaredpar** [comment]
@marek-safar 

> rebased on top of master and pushed, do I really have to create a new PR?

Yes. It has nothing to do with your changes. It's due to Jenkins and the job having started before we reset a bunch of jobs. Jenkins is still giving us stale data for some of the run.s

**Comment by jaredpar** [comment]
@marek-safar 

> Replaced with #21072 but it's also failing with some weird MEFv2 errros

Known break we're digging into. Had two PRs which were green alone but combined broke the build.

**Pull request closed without merging**
