### PR TITLE
Port fix for high memory usage from full solution analysis to microupdate branch

### PR DESCRIPTION
**Pull request by mavasani**
This is the port for https://github.com/dotnet/roslyn/pull/10616

Issues addressed:

1. GitHub https://github.com/dotnet/roslyn/issues/10365
2. VSO [214810](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?_a=edit&id=214810&triage=true)

### CODE REVIEW

**Comment by mavasani** [comment]
test vsi please

**Comment by mavasani** [comment]
@srivatsn @natidea @heejaechang @dotnet/roslyn-analysis please review

**Comment by mavasani** [comment]
the unit tests are still failing in microupdate branch due to:

```
error : The package Microsoft.VisualStudio.Composition with version 14.0.50715-pre could not be found in C:\Users\dotnet-bot\.nuget\packages. Run a NuGet package restore to download the package. [D:\j\workspace\roslyn_prtest---345e02d2\src\EditorFeatures\Test\EditorServicesTest.csproj]
```
@jasonmalinowski any idea if we are missing some change from stabilization/master?

**Comment by jasonmalinowski** [comment]
@mavasani: we're not sure. Feel free to merge assuming you've otherwise done all the validation you can.

**Comment by mavasani** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please

**Comment by mavasani** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please

**Comment by mavasani** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please

**Comment by mavasani** [comment]
We are not taking this fix for Micro-update.

**Pull request closed without merging**
