### PR TITLE
Don't suggest removing necessary boxing casts in conditional expressions

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes issue #5314

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Reviewers: @dpoeschl, @balajikris, @Pilchie

**Comment by balajikris** [comment]
:+1: , assuming VB didn't need code changes for the test you've added to pass.

**Comment by DustinCampbell** [comment]
VB doesn't exhibit the problem, but I added a test to validate the correct behavior.

**Comment by balajikris** [comment]
cool, thought as much. just confirming :smile:

**Comment by dpoeschl** [comment]
Late to the party, but :+1:

**Pull request merged**
