### PR TITLE
Code wrapping refactorings should be lower pri than other refactorings

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/33605

After this change, lightbulb list looks like:

image

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @jcouv @sharwell @DustinCampbell @dotnet/roslyn-ide

**Comment by jinujoseph** [comment]
@mavasani did not we resolve this via https://github.com/dotnet/roslyn/pull/32435 ?

**Comment by CyrusNajmabadi** [comment]
@jinujoseph It was resolved solely for those two refactorings.  My change resolves it for *all* refactorings.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by heejaechang** [comment]
I think we should discuss how to solve ordering problem for refactoring.

I believe this kind of heuristic will require an endless tweak as new refactoring are added.

I opened an issue - https://github.com/dotnet/roslyn/issues/33818

**Comment by CyrusNajmabadi** [comment]
> I believe this kind of heuristic will require an endless tweak as new refactoring are added.

NOte: this was not a tweak.  This was literally just a bug.  The problem here was that we have a system for prioritizing refactorings.  However, the implementation was buggy, and a low-pri refactoring wasn't showing up after medium pri refactorings *if* that refactoring had nested refactorings.  

Nothing about the actual prioritization design changed here.  We just fixed up the impl to match teh intended design.  So i question if anything needs to be done here.

**Pull request merged**
