### PR TITLE
Fix dsr20

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
retest vsi please

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/6120/
// Retest reason:

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by tmat** [comment]
I'm gonna merge to fix the break and watch the jobs.

**Pull request merged**
