### PR TITLE
Redirect TEMP in Jenkins runs

### PR DESCRIPTION
**Pull request by jaredpar**
This was meant to be done as part of my rework of netci.groovy but it looks like I missed
it.

https://github.com/dotnet/roslyn/commit/8a078fac5c497b61f00505d3fe4cf0d92137bef3

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure

**Comment by 333fred** [comment]
@dotnet-bot retest ubuntu_16_debug_prtest please

**Comment by 333fred** [comment]
The machine being used for the ubuntu tests appears to have been hosed, some file system corruption on multiple test runs. I removed it from the pool.

**Comment by Pilchie** [comment]
@brettfo - the thing we were talking about this morning.

**Comment by jaredpar** [comment]
@Pilchie yep.  Me explaining to @brettfo how we did this is what made me realized I'd screwed this up 😦

**Pull request merged**
