### PR TITLE
Use CodePage1252 Encoding if available, Latin1 if not.

### PR DESCRIPTION
**Pull request by pharring**
My previous attempt to introduce our own 1252 Encoding actually made things worse. So, now we'll try to use the framework 1252 Encoding and, if that's not available (on CoreCLR, for example), we'll fall back to Latin1.

### CODE REVIEW

**Comment by pharring** [comment]
@jaredpar @agocke for review, please.

**Comment by agocke** [comment]
LGTM

**Comment by agocke** [comment]
Is it possible to write a test that demonstrates the problem with the old method?

**Comment by pharring** [comment]
@agocke Yes, I think so. Working on it.

**Pull request merged**
