### PR TITLE
Port analyzer driver pooling fix to future-stabilization

### PR DESCRIPTION
**Pull request by mavasani**
This is port of https://github.com/dotnet/roslyn/pull/9426, which addresses the extra allocations due to new analyzers added in future and future-stabilization branch by pooling per-analyzer state objects in the driver.

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @srivatsn @KevinH-MS as an FYI

Tagging @MattGertz for ask mode approval

**Comment by MattGertz** [comment]
Approved pending tests and CRs.

**Comment by mavasani** [comment]
Also tagging @dotnet/roslyn-analysis for CR - this change has already been approved and merged in master and future, can someone take a quick look?

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
