### PR TITLE
Add release/* globs to azure pipelines config

### PR DESCRIPTION
**Pull request by RikkiGibson**
This should reduce config churn moving forward as we add new release branches (e.g. `dev16.2-preview2`, etc...)

### CODE REVIEW

**Comment by dpoeschl** [comment]
Does the `azure-pipelines*` config always read from master? If so, I need to update the internal snap instructions to clarify.

**Comment by jaredpar** [comment]
@dpoeschl no. Azure will read pipeline information from the tip of the current PR.

**Comment by dpoeschl** [comment]
Okay, I'll split this into two PRs

1. YML files targeting release/dev16.1
2. PublishData still targeting master

**Comment by dpoeschl** [comment]
Replacing this one with https://github.com/dotnet/roslyn/pull/35395 and https://github.com/dotnet/roslyn/pull/35396

**Pull request closed without merging**
