### PR TITLE
Avoid virtual calls in compiler when compiling pattern-switch

### PR DESCRIPTION
**Pull request by alrz**

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can we please have a second code review?

**Comment by AlekseyTs** [comment]
I think we, usually, optimize the other direction, toward decreasing the size of objects by using virtual properties. Is there any evidence that this change introduces a noticeable improvement?

**Comment by alrz** [comment]
This is probably what we would have if it was written by ADTs. I suppose syntax trees also follow the same pattern. I'd agree this is a micro optimization and by the way, 32 bits of data which will be needed in every usage don't seem to be an issue.

**Comment by AlekseyTs** [comment]
I recommend rejecting this change until there is a proof that it actually improves something in a noticeable way.

**Comment by alrz** [comment]
@AlekseyTs Isn't it "proven" that virtual calls are slower than field access? Just asking.

**Comment by AlekseyTs** [comment]
> Isn't it "proven" that virtual calls are slower than field access? Just asking.

Yes, but in this case are the calls actually a source of a **noticeable** slowdown? The change increases the size of objects, are we going to get something **real** in exchange.

**Comment by alrz** [comment]
> The change increases the size of objects,

Since the field is accessed in every usage I think this acts as a cache for repetitive data retrieval and trade-off is not really noticeable since it is just an integer. Note that this is not a "fix" for a perf issue, it is just a different way to do it. Also considering how much is change I think the improvement is still acceptable.

**Comment by CyrusNajmabadi** [comment]
> Also considering how much is changed, I think the improvement is still acceptable.

How do we know that this hasn't hurt perf?  Have we done any measurements here?  Size of objects can definitely have a perf impact, and we should not be making changes for 'perf' reasons without actual data to know if this is a benefit (and certainly that it's not a detriment!).

**Comment by alrz** [comment]
I mean, you should choose your trade-off, an additional integer per object or a virtual call per usage. I'd go with former because there is multiple usages (Kind() call) per object instance. and that's pretty much proved in the code. You can literally count Kind() calls.

**Comment by CyrusNajmabadi** [comment]
> and that's pretty much proved in the code.

Nothing is proven without actual data presented.  For all i know, this makes performance tank :)

**Comment by alrz** [comment]
I don't know what actual data is to be presented. This is an encapsulated change and do not depend on anything else. The differences between  the two approaches are statically observable: It costs you an intetger per object instance in exchange to removing all virtual calls which we've done multiple times per object instance. The only thing that is not observable is virtual call vs field access which is proven as @AlekseyTs agreed.

**Comment by CyrusNajmabadi** [comment]
> I don't know what actual data need to be presented. 

Data that shows that this change actually helps the performance of the compiler (or other layers that call into it.  You are making objects bigger.  That means using more memory.   Unless we're getting something valuable from that extra memory usage, why would we take this?

> This is an encapsulated change and do not depend on anything else. 

You are changing something which affects binding.  That means you could be making the compiler (or hte layers above it) slower with your change.  

>  The differences between the two approaches are statically observable: It costs you an intetger per object instance in exchange to removing all virtual calls which we've done multiple times per object instance

Ok.  So we're trading one thing for another.  Where is the data that shows that the new trade is better than the other?

**Comment by alrz** [comment]
>Ok. So we're trading one thing for another. Where is the data that shows that the new trade is better than the other? Again: How do we know that this hasn't hurt perf?

It goes like this:
```cs
var c = new C();
switch (c.Kind)  // virtual call
switch (c.Kind)  // virtual call
switch (c.Kind)  // virtual call
```
Compared to:
```cs
var c = new C(); // an additional integer
switch (c.Kind)  
switch (c.Kind) 
switch (c.Kind)  
```
Which one you'd prefer?

**Comment by AlekseyTs** [comment]
@alrz 
> Which one do you prefer?

By default, I prefer a virtual call vs. increase in size. If you are claiming that you are making compiler faster, you should prove it with data. Something like "compiling this program after the change is that much faster", etc. Also, it wouldn't hurt to provide profiling data showing that the calls before the change were taking that much time for the same scenario.

**Comment by jcouv** [comment]
@alrz My suggestion to help move the discussion forward and address the feedback would be to construct some kind of benchmark and show before/after results. Such concrete measurement will help demonstrate the benefits. 

As a heads-up, based on my experience I would expect that any proposed benchmark will need to be discussed and refined as well. There will be multiple scenarios, with possibly contradictory impact (some cases may be faster, some may be slower, some may have time vs. space trade-off) which will imply discussion to resolve.

**Comment by alrz** [comment]
Ok, what tool should I use for this? I tried [dotnet/benchmarkdotne](https://github.com/dotnet/benchmarkdotnet), but it doesn't support multiple identical assemblies (yet?) and using extern alias apparently doesn't help (of course, if you want both results from a single benchmark session).  There got to be a better way around this..

**Comment by CyrusNajmabadi** [comment]
Can I ask, why mage this change at all? 

In general in feels odd to take an inheritance based system and then try to encode inheritance based data as state when it can just be produced with an override. 

The existing system works and makes sense. Changing it seems like change for changes sake.

**Comment by alrz** [comment]
@CyrusNajmabadi 

Well, basically we don't even need to use `Kind` property right? Because it's still perfectly doable with a type-switch. It's there for the sake of perf in switch statements, but when it itself is virtual, that nullifies the desired effect to some extent — it is a single virtual call vs. multiple type checks but it can be entirely removed with this change. I'm willing to provide profiling data but I just don't know how it is usually done in Roslyn.

**Comment by VSadov** [comment]
Interestingly the typeswitch _could_ be the most efficient solution in this case. - as long as you make the leaf types sealed. 

Note that we only have 3 leaf types and "switch" is likely emitted as an if/else ladder anyways. 
Once the types are sealed, typechecks would be a simple pointer compares.

Besides, most of the uses actually cast the nodes anyways like -

```C#
                switch (decisionTree.Kind)
                {
                    case DecisionTree.DecisionKind.ByType:
                        {
                            LowerDecisionTree((DecisionTree.ByType)decisionTree);
                            return;
                        }
                    case DecisionTree.DecisionKind.ByValue:
                        {
                            LowerDecisionTree((DecisionTree.ByValue)decisionTree);
                            return;
                        }
                    case DecisionTree.DecisionKind.Guarded:
                        {
                            LowerDecisionTree((DecisionTree.Guarded)decisionTree);
                            return;
                        }
                    default:
                        throw ExceptionUtilities.UnexpectedValue(decisionTree.Kind);
                }
```

Not that I think that these switches hurt perf in any observable way, but it is very possible that typeswitch could be faster here, - as long as the leaf types are sealed. 

BTW sealing the leaf types would be nice to do regardless, since that would be unambiguously free perf points - because we downcast all these nodes.

**Comment by alrz** [comment]
>Tagging the tree instances would make sense if the set of DecisionKinds was larger than the set of derived nodes 

So supposedly there is a threshold to do that which is not met in this particular hierarchy. I'm wondering how ADTs are going to be implemented in C# 8.0. I think there is a lot more interesting stuff to investigate when this is going to be built into the compiler. :)

> but it is very possible that typeswitch could be faster here, - as long as the leaf types are sealed. BTW sealing the leaf types would be nice to do regardless, since that would be unambiguously free perf points - because we downcast all these nodes.

ok I can do that instead but I didn't see anywhere in the compiler yet that uses a type-switch. Is that ok here?

**Comment by AlekseyTs** [comment]
> I can do that instead but I didn't see anywhere in the compiler yet that uses a type-switch. Is that ok here?

I think all changes motivated by performance should be supported by data rather than guesses.

**Comment by VSadov** [comment]
I agree with @AlekseyTs about the perf data

The other motivation to use typeswitch could be "just to use typeswitch" - for dogfooding purposes. 

That is not extremely high motivation, so It would still need proof that it does not regress the perf. We know that in a general case typeswitches do cost more than regular switches.

**Comment by alrz** [comment]
I just asked how should I provide that data but nobody seems to be willing to actually help to get this going.

**Comment by agocke** [comment]
@alrz Regarding perf numbers, unfortunately we don't have a robust system for finding these problems yet. Personally, I rely mostly on capturing traces with [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567) and looking for hotspots.

Otherwise, capturing the full command line for a test case (like building CSharpCodeAnalysis, for example) and then running csc against it with and without the change would be pretty useful. Noise could be a problem, but if the wins are sufficiently small that we can't find them in perfview or a few repeated runs, the change probably isn't worth making anyway.

**Comment by alrz** [comment]
> if the wins are sufficiently small that we can't find them in perfview or a few repeated runs, the change probably isn't worth making anyway.

That's probably the case. However, my argument was that perf gain (if any) compared to diff size, *would* worth it. That perhaps just depends on how much you care.

**Comment by agocke** [comment]
@alrz Eh, I think @VSadov's point about additional object size potentially harming perf (via cache invalidation and memory latency) is also reasonable. The perf improvement depends almost entirely on the virtual table not being in L1/L2 and the field being in L1/L2 -- which doesn't seem obviously true to me.

That's why I think data is necessary here. If the CLR type tag and the vtable is in L1/registers (like I would expect) then this shouldn't give any perf improvement.

**Comment by CyrusNajmabadi** [comment]
> That's probably the case. However, my argument was that perf gain (if any) compared to diff size, would worth it.

I disagree.  As mentioned already (at least i think i mentioned it), it seems very odd to me that we would have subclassing, but then store redundant data in the subclass.  That's precisely the sort of thing that virtual calls are appropriate for.   Furthermore, this design doesn't fit our approach of avoiding storing data if we can avoid it (as memory pressure is a huge concern for us).  Finally, any sort of change that is made (ostensibly) for perf reasons, should start *first* with perf data justifying it.  It's not good to speculate about performance.  If you think there's an issue worth addressing, it would be valuable to *first* do an investigation and *then* use that data to help make the case when you send in a PR.

**Pull request closed without merging**
