### PR TITLE
Always record assembly symbols right before creating a FinalState

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski ptal. Thanks!

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski ptal. Thanks!

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Any reason I should just review #51019 and just that?

**Comment by CyrusNajmabadi** [comment]
Superseded by https://github.com/dotnet/roslyn/pull/51019.

**Pull request closed without merging**
