### PR TITLE
Add mac / linux trigger phrases

### PR DESCRIPTION
**Pull request by jaredpar**
This restores the ability to utter the following test phrases:

- test mac please
- test linux please

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @tmat, @agocke, @MattGertz

**Comment by jaredpar** [comment]
This is a test change only, notifying @MattGertz just for a heads up.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
:+1:.

**Pull request merged**
