### PR TITLE
Do not include file/project info on the 'no references found' entry in the FindRefs window

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Before:
image

After:
image

### CODE REVIEW

**Review by jasonmalinowski — APPROVED** [review]

**Review by allisonchou — APPROVED** [review]

**Comment by AmadeusW** [comment]
Without data in the Project column, will the "no references", I'm afraid that the entry won't appear when table groups by "project then definition" (the default grouping)

**Comment by CyrusNajmabadi** [comment]
@AmadeusW 'Project the definition' looks like:

image

Which looks to be what we want.

**Comment by AmadeusW** [comment]
sorry, I wasn't clear: currently, Roslyn displays the bolded header. With this PR, it does not display the header.
image

**Comment by CyrusNajmabadi** [comment]
I think it's good that we don't show the header.  This allows roslyn to show the results as:

image

Instead of:

image
(note that we can't even see all the entries here)

The only downside is that the messages without projects are at the top of hte list.  Is there some way we could get them to be at the bottom of the list @AmadeusW

**Pull request merged**
