### PR TITLE
Add comment on usage of SLocalRegistry service on background thread

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@sharwell @CyrusNajmabadi

**Review by sharwell — DISMISSED** [review]
This conflicts with #56580 and will make it more difficult to re-apply the changes after the documentation issues are resolved.

**Review by jasonmalinowski — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
I can accept ryan's information in the issue as an acceptable contract in the interim period.  We have a link in the code and the comments he put in (which i'm also fine just putting in the code itself).

**Comment by sharwell** [comment]
> I can accept ryan's information in the issue as an acceptable contract in the interim period.

I can for this issue since it already merged, but please do not use the same approach in the future. If the free-threaded nature of the object is not publicly documented. it is not free threaded.

**Pull request merged**
