### PR TITLE
Update version to 1.1.0 and PreRelease tag to -beta1

### LINKED ISSUE #3007: Update version from 1.0.0 to 1.1.0 and prerelease tag from rc to beta
The prerelease change should be in master and future.

### PR DESCRIPTION
**Pull request by agocke**
As it sounds. Fixes #3007.

@ManishJayaswal @jaredpar @tmeschter @amcasey

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
Do we need to update the versions for the NuGet packages too?

**Comment by ManishJayaswal** [comment]
@agocke sorry never mind, you did that already.

**Comment by tmeschter** [comment]
@agocke Presumably we will need changes to InstallDogfood to add the proper binding redirects to Visual Studio?

**Comment by jaredpar** [comment]
@tmeschter isn't htat what the `AssemblyRedirects.cs` file does?

**Comment by tmeschter** [comment]
@jaredpar Hmm, yes, you're right--that should be sufficient.

**Comment by agocke** [comment]
@tmeschter We should only need to modify the existing config file if non-Roslyn assemblies change, like Collections.Immutable or Reflection.Metadata

**Comment by tmeschter** [comment]
@agocke Right. However, we do need binding redirects added to the config files for vbc, csc, and vbcscompiler.

Sent from my Windows Phone
________________________________

**Comment by agocke** [comment]
@tmeschter Won't the exes just be rebuilt with the new versions?

**Comment by tmeschter** [comment]
@agocke We need the redirects so that analyzers built against 1.0 binaries continue to work with the 1.1 compilers.

Sent from my Windows Phone
________________________________

**Comment by agocke** [comment]
@tmeschter Didn't think about that. Will add.

**Comment by agocke** [comment]
@tmeschter Binding redirects added.

**Comment by ManishJayaswal** [comment]
LGTM

**Pull request merged**
