### PR TITLE
Trivial renames of IOperation API parameter names

### LINKED ISSUE #22719: IOperation API Review work items
### Preview

- [x] BinaryOperatorKind.Invalid, DoLoopKind.Invalid, UnaryOperatorKind.Invalid
Can we use None instead?

- [x] Remove IHasArguments and IHasOperatorMethodExpression interfaces
Move their members down. 

- [x] Rename ArgumentsInEvaluationOrder to Arguments

- [x] Rename IIsTypeExpression.IsNotTypeExpression to IsNegated

- [x] Rename IIsTypeExpression.IsType to TypeOperand

- [x] Rename IIsTypeExpression.Operand to ValueOperand

### RTW

- [x] Rename -Expression and -Statement nodes to -Operation

- [x] Unify IIfStatement with IConditionalExpression to IConditionalOperation.

- [x] Rename Microsoft.CodeAnalysis.Semantics namespace to Microsoft.CodeAnalysis.Operations 
Since changing Expressions and Statements to Operations will already break all analyzers we can as well rename the namespace.

## Doc comment updates

- [x] Update doc comments of ICollectionElementInitializerExpression.AddMethod to mention it's null in error cases. Perhaps note that in all cases where IOperation node has a symbol returning property? 

- [x] IExpressionStatement -- Explain that the node represents semantics of dropping the value of the expression.

- [x] IIncrementOrDecrementExpression -- Add a note that unlike unary operation this operation modifies the target.

### PR DESCRIPTION
**Pull request by mavasani**
This was missed as part of #22774 for #22719.
Fixes #22719
vso : https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/521983

### CODE REVIEW

**Comment by 333fred** [comment]
Integeration test failure is https://github.com/dotnet/roslyn/issues/22577.

**Comment by 333fred** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest.

**Comment by 333fred** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Review by 333fred — APPROVED** [review]

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler Can I get 2 compiler reviews please? Very trivial renames.

**Review by jcouv — APPROVED** [review]
LGTM

**Review by jinujoseph — APPROVED** [review]

**Comment by jinujoseph** [comment]
approved via [Link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/521983)

**Comment by mavasani** [comment]
Failure in windows_debug_vs-integration_prtest is unrelated and the change here is extremely trivial rename, so merging with 1 compiler signoff (confirmed with @jinujoseph that it is fine for this PR).

**Review by AlekseyTs — COMMENTED** [review]
LGTM

**Pull request merged**
