### PR TITLE
Remove obsolete UnitTesting and Razor External Access APIs

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@shyamnamboodiripad

**Comment by shyamnamboodiripad** [comment]
Based on code search the following types are still used on UT side - so the obsolete attributes may have been added in error -
* UnitTestingRemoteServiceConnectionWrapper
* UnitTestingIncrementalAnalyzerProvider

**Comment by shyamnamboodiripad** [comment]
@tmat Its late today but I'll build UT against the changes in the current PR on Monday to double check that this doesn't break anything. I'll post an update once I do that.

**Comment by tmat** [comment]
@NTaylorMullen PTAL

**Review by shyamnamboodiripad — APPROVED** [review]
👍🏾 I did a quick smoke test to double check that this doesn't break anything for UT.

**Review by NTaylorMullen — APPROVED** [review]
Cross-checked all the API removals and they look good from Razor's standpoint.

**Pull request merged**
