### PR TITLE
Test analyzer load failures

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by dpoeschl** [comment]
In the [prtest/lin/dbg/unit32 output](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1560/console)

```
05:09:50 curl: (23) Failed writing body (8192 != 16384)
05:09:50 [nuget.35.zip]
05:09:50   End-of-central-directory signature not found.  Either this file is not
05:09:50   a zipfile, or it constitutes one disk of a multi-part archive.  In the
05:09:50   latter case the central directory and zipfile comment will be found on
05:09:50   the last disk(s) of this archive.
05:09:50 unzip:  cannot find zipfile directory in one of nuget.35.zip or
05:09:50         nuget.35.zip.zip, and cannot find nuget.35.zip.ZIP, period.
05:09:50 Unable to download NuGet packages
05:09:50 Build step 'Execute shell' marked build as failure
```

@dotnet/roslyn-infrastructure Do we understand this failure mode of the linux runs? I can add a jenkins failure regex for "Build step <whatever> marked build as failure", but if the curl thing is a possible recurring problem we can flag that too.

**Comment by dpoeschl** [comment]
retest prtest/lin/dbg/unit32 // Looks like fbld3 is out of disk space (see full discussion at #7032). I've taken it offline, so the next run will happen on a different machine.

**Comment by dpoeschl** [comment]
retest prtest/lin/dbg/unit32 please

**Comment by TyOverby** [comment]
This change goes from

```
AnalyzerLoadFailureEventArgs.FailureErrorCode.UnableToLoadAnalyzer => WRN_UnableToLoadAnalyzer,
AnalyzerLoadFailureEventArgs.FailureErrorCode.NoAnalyzers => WRN_NoAnalyzerInAssembly
```
to 

```
AnalyzerLoadFailureEventArgs.FailureErrorCode.UnableToLoadAnalyzer => WRN_NoAnalyzerInAssembly,
AnalyzerLoadFailureEventArgs.FailureErrorCode.NoAnalyzers => WRN_UnableToLoadAnalyzer
```

At first glance it seems like we are currently doing the right thing.  Could you explain the motivation for this change?

**Comment by cston** [comment]
@TyOverby The original code is doing the right thing. This PR was simply to check if these code paths are covered by tests.

**Comment by TyOverby** [comment]
Ah.  Gotcha.  I'll tag this with "do not review" so people know that this isn't a PR that is actually supposed to be merged.

**Comment by cston** [comment]
@TyOverby Thanks. I didn't realize there was such a tag.

**Comment by davkean** [comment]
@cston Is this still relevant? Can we close it out if it isn't.

**Pull request closed without merging**
