### PR TITLE
Test Jenkins change

### PR DESCRIPTION
**Pull request by jaredpar**
DO NOT CHECK IN.

### CODE REVIEW

**Comment by jaredpar** [comment]
test windows_determinism please

**Comment by jaredpar** [comment]
test windows_determinism_prtest please

**Comment by balajikris** [comment]
@jaredpar Sorry for trolling your test PR, but should we be testing VSI as well? or it doesn't matter?

**Comment by jaredpar** [comment]
@balajikris it's a good question. This change is being done in two parts: open and closed.  The VSI tests, even though they appear in the open PRs, are defined in our closed repo.  Hence that hasn't changed at all.  It will change in the next wave.

**Pull request closed without merging**
