### PR TITLE
Update script.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
TAgging @jasonmalinowski

**Comment by jasonmalinowski** [comment]
Looks like you'll have to add dev15.1.x in that branch too...

**Comment by CyrusNajmabadi** [comment]
Ok.  I added that as well.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Oh wait, you have to make the change in the appropriate branch. So dev16 has to be in the dev16 branch, dev15.1.x has to be in that branch...

**Comment by CyrusNajmabadi** [comment]
Oh.

**Pull request closed without merging**
