### PR TITLE
Implement analyzer/fixer: remove unnecessary `Call` keyword from `Call` statement

### LINKED ISSUE #71818: [VB] Remove redundant `Call`
**Brief description:**

Describe your **code style** rule here.

VB requires `Call` before method call expressions if the method calls do not start with identifiers.
However, some old-fashioned developers have forced others to add this `Call` to every method call.
It is mainly because of the compatibility with VBA/VB6 and because they do not know when `Call` is necessary.

**Languages applicable:**

Is your analyzer C# only? VB Only? Or Both?

VB Only

**Code example that the analyzer should report:**

```vbnet
Call SomeClass.SomeMethod(arg1, arg2)
'--
'Call' here can be removed.
```

A small code snippet that describes a case that the analyzer should report.

Note: the following `Call`s are necessary:

```vbnet
Call New SomeForm().Show()
Call If(condition, form1, form2).Show()
```

**Additional information:**

Any more additional information you would like to add.

**Documentation requirements:**

When this analyzer is implemented, it must be documented by following the steps at [Documentation for IDE CodeStyle analyzers](https://github.com/dotnet/roslyn/blob/main/docs/contributing/Documentation%20for%20IDE%20CodeStyle%20analyzers.md).

### PR DESCRIPTION
**Pull request by tats-u**
Fixes #71818

Mandatory:

- [x] Implement the same level as RemoveUnnecessaryByVal

Backlog:

- [ ] Support FixAll
- [ ] Support CodeCleanUp
- [ ] Assign a dedicated code style option name

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Not sure if we would take this for Roslyn itself. Seems like a good candidate for a community driven set of vb migration helpers though!

**Comment by tats-u** [comment]
That doesn't look like good news. 
As you may think, its priority may be lower than ByVal removal.
However, the official document doesn't recommend to abuse Call: 
https://learn.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/call-statement#remarks

**Comment by CyrusNajmabadi** [comment]
@tats-u I'm simply saying these might be better as a package you maintain yourself.

**Comment by tats-u** [comment]
@CyrusNajmabadi I wouldn't work on this PR anymore if you(r team) had no plan to make such kind of Analyzer/Codefix (Lighten the colors of unnecessary Call keywords) in the original Roslyn, VS, and online rich editors (and possibly VS Code in the future).
I wonder who other than your team can keep such a huge project well maintained and popular.
If your team hasn't decided to this PR has even a little chance to be merged, I'll continue to try to make it pass all the tests in CI.

**Comment by CyrusNajmabadi** [comment]
> I wonder who other than your team 

Lots of people maintain nuget packages.  :-)

But roslyn isn't a place where every but if functionality goes.  This has a coat for us as well. So the benefit needs to be there to justify it.  

Given 30+ years working with vb, and only a single person asking for this, it really sounds like this is a feature for you, Rather than something significant for the entire community. 

If you're this passionate about producing solutions for your problems, that's great. But that doesn't really translate to us prioritizing it the same way.

**Comment by tats-u** [comment]
> only a single person asking for this, it really sounds like this is a feature for you, Rather than something significant for the entire community.

Note most VB users won't visit this repo (or vblang repo), and has given up for this feature or raising up their voice for new ones, not only new language ones (announced since .NET 5) but also other ones.

Since your team chose to reject this feature and other new VB-dedicated just-nice-to-have ones even in Analizer, I'll stop improving this code. I'll treat VB for .NET as like the IE mode and the Trident engine for Edge.

**Comment by CyrusNajmabadi** [comment]
Sounds good.  Take it easy :)

**Pull request closed without merging**
