### PR TITLE
Provide a sync path for 'AdditionalText' to prevent thread explosions.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
Can you rebase this properly? You have a bunch of random commits and other changes mixed in here.

**Comment by jasonmalinowski** [comment]
:+1:. @Pilchie, @CyrusNajmabadi makes a good question -- this is potentially a significant perf improvement, we assume stabilization is locked at this point?

**Comment by CyrusNajmabadi** [comment]
Since no one has reported this issue but me, i think we don't need to take this for Update1.

**Comment by Pilchie** [comment]
:+1: for master.  I don't think this meets the bar for `stabilization`

**Comment by Pilchie** [comment]
@srivatsn, @mavasani.  Talking to @sharwell, we suspect that this issue might be the root cause of a slowdown that he was discussing with you.

**Comment by srivatsn** [comment]
Yep Sam just stopped by the next table :) :+1:

**Comment by sharwell** [comment]
It sounds like this could be the source of crushing slowdowns when enabling analyzers in one of the larger projects I work on. I'm currently investigating whether this behavior is actually what we see in that case, and also what we can do in our analyzers to work around the issue (DotNetAnalyzers/StyleCopAnalyzers#1736).

**Pull request merged**
