### PR TITLE
Remove comments to appease CredScan

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes [AB#1100793](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1100793)
Fixes [AB#1100857](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1100857)

This is to make CredScan leave us alone.

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Comment by RikkiGibson** [comment]
These changes should probably be made in Arcade, because we pull the content of this file from them:

https://github.com/dotnet/arcade/blob/6e8b0da07468ed1653292b1aeb11c9d76da64dea/eng/common/internal-feed-operations.ps1#L67

https://github.com/dotnet/arcade/blob/6e8b0da07468ed1653292b1aeb11c9d76da64dea/eng/common/internal-feed-operations.sh#L65

**Comment by davidwengier** [comment]
> These changes should probably be made in Arcade, because we pull the content of this file from them:

Arcade already has done this: https://github.com/dotnet/arcade/pull/6880

How often do we pull changes? Is it better to just wait, and close the bugs against the arcade PR?

**Comment by RikkiGibson** [comment]
You can use darc to manually kick off a maestro PR to make us consume the new version (if they've published it).

**Comment by davidwengier** [comment]
> You can use darc to manually kick off a maestro PR

Oh no, I broke into jail again didn't I? 😛

**Comment by RikkiGibson** [comment]
Looks like arcade needs to backport that PR to their 3.x branch. (or we need to upgrade..)

**Comment by davidwengier** [comment]
Does it cause issues (merge commits?) if we take this PR in the meantime?

**Comment by RikkiGibson** [comment]
I'm not sure--my first guess is that the lines could quietly come back when we take an arcade update in the future. I've opened dotnet/arcade#6924 to address it over there.

**Comment by jaredpar** [comment]
Aren't we still on Acrade 1.X?

**Comment by RikkiGibson** [comment]
release/3.x refers to .NET Core 3.x, but the Arcade version in the branch is actually 1.x.

**Pull request closed without merging**
