### PR TITLE
Be resilient to the document being shorter than when it started when we get a completion item description

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Port of https://github.com/dotnet/roslyn/pull/21566 to 15.0.x

15.0.x Tracking Bug: [484308](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/484308)

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jasonmalinowski @natidea

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by Pilchie** [comment]
@natidea can this be closed now?

**Comment by DustinCampbell** [comment]
@sharwell: Why is this Community?

**Pull request closed without merging**
