### PR TITLE
Fix IArgument and IArrayInitializer to have null types

### LINKED ISSUE #22581: fix IArgument and IArrayInitializer to have null types
See https://github.com/dotnet/roslyn/pull/22546#issuecomment-334824971

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #22581
vso: https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/520791

### CODE REVIEW

**Review by jcouv — APPROVED** [review]
LGTM

**Comment by AlekseyTs** [comment]
Please add asserts to ```public static void ValidateIOperations(Func<Compilation> createCompilation)``` and to the corresponding visit methods in OperationTreeVerifier.

**Comment by AlekseyTs** [comment]
Done with review pass (iteration 1)

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 2)

**Comment by mavasani** [comment]
@natidea @jinujoseph I see the VSO bug has been approved by the division. Can we add the approved to merge label to the PR?

**Comment by jinujoseph** [comment]
Approved via [Link](https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/520791)

**Pull request merged**
