### PR TITLE
Update PublishData.json

### PR DESCRIPTION
**Pull request by RikkiGibson**
Change lab/ml to master now that we're inserting our 16.1 payloads into VS master

### CODE REVIEW

**Comment by tmat** [comment]
Thanks! I also added vsMajorVersion field, which we will need soon.

**Comment by tmat** [comment]
@jaredpar

**Comment by tmat** [comment]
@jaredpar Are the feature branches up to date?  they list some old versions (2.8.*, 2.11.*)

**Comment by jaredpar** [comment]
@tmat 

> Are the feature branches up to date? they list some old versions (2.8._, 2.11._)

That's because i never added the proper validation code for that field. This file is out of date for feature branches though. I will try and get that cleaned up here.

**Comment by tmat** [comment]
Let's merge this now so we can unblock https://github.com/dotnet/roslyn/pull/33410

**Pull request merged**
