### PR TITLE
C# and VB Sample Docs Update 2

### PR DESCRIPTION
**Pull request by v-codeel**
This update includes the C# and VB Diagnostic Analyzer sample documents.

I've removed references to Roslyn End User Preview.
The Diagnostic Analyzer API has been changed majorly since the last version of these documents, so I updated the code and explanations in the documents to use the updated API.

This pull request is related to https://github.com/dotnet/roslyn/pull/4841 initiated by @mattscheffer, as we are both working on updating these documents.

### CODE REVIEW

**Comment by v-codeel** [comment]
@ManishJayaswal @Pilchie @AnthonyDGreen @amcasey Please take a look.

**Comment by v-codeel** [comment]
Added the Semantic Analysis documents.

Once again, removed references to "Roslyn End User Preview" and replaced references to "Roslyn SDK Project Templates" with ".NET Compiler Platform SDK".
Other than that, there were only a couple lines of code that needed to be changed.

**Comment by ManishJayaswal** [comment]
@AnthonyDGreen Any update on this?

**Comment by davkean** [comment]
@AnthonyDGreen @kuhlenh @dotnet/interactive this PR is getting stale, can we have a look at this?

**Comment by AnthonyDGreen** [comment]
Sure. The other docs have been migrated to the wiki. I can move these last two over the weekend.

**Comment by davkean** [comment]
@AnthonyDGreen How did you go with this?

**Comment by AnthonyDGreen** [comment]
I've got the diagnostic docs (both VB and C#) converted to markdown. I haven't fully validated them yet but am working on it. Since these docs weren't originally authored by me they require additional inspection since the conversion tools were built around conventions I used in my walkthroughs. The remaining docs were updated in other PRs with API changes and can now be found on our wiki. The plan is to delete those files from the repo now.

**Comment by AnthonyDGreen** [comment]
@v-codeel,

Thanks for taking the initiative in updating these outdated docs. Both of the "How-to" documents you updated have been converted to markdown and uploaded to the wiki. You can find them here:

https://github.com/dotnet/roslyn/wiki/How-To-Write-a-Visual-Basic-Analyzer-and-Code-Fix
https://github.com/dotnet/roslyn/wiki/How-To-Write-a-C%23-Analyzer-and-Code-Fix

The Semantic Analysis walkthroughs were uploaded from a separate pull request by a different user. 
As we're dropping the Word/PDF versions from the repo I'm closing out this pull request.

Thanks again!

**Pull request closed without merging**
