### PR TITLE
Handle field declaration ambiguity in scripts

### LINKED ISSUE #12781: CompletionService doesn't always return results for variables in a script
**Version Used**: 2.0 Beta 3
I believe this doesn't work in 1.3 either (using Interactive window and 2015 Update 3).

**Steps to Reproduce**:

```csharp
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Completion;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Host;
using Microsoft.CodeAnalysis.Host.Mef;
using Microsoft.CodeAnalysis.Recommendations;
using System.Composition.Convention;
using System.Composition.Hosting;

var compositionContext = new System.Composition.Hosting.ContainerConfiguration()
            .WithAssemblies(MefHostServices.DefaultAssemblies.Concat(new[] {
                Assembly.Load("Microsoft.CodeAnalysis.Features"),
                Assembly.Load("Microsoft.CodeAnalysis.CSharp.Features") }))
            .CreateContainer();

var ws = new AdhocWorkspace(MefHostServices.Create(compositionContext));
var p = ws.AddProject("x", LanguageNames.CSharp)
    .WithMetadataReferences(new[] {
         MetadataReference.CreateFromFile(typeof(object).Assembly.Location) })
    .WithParseOptions(new CSharpParseOptions(kind: Microsoft.CodeAnalysis.SourceCodeKind.Script));
    
var code = @"var s = """";
s.
var k = """";";
var d = p.AddDocument("d", code);

var find = "s.";
var index = code.IndexOf(find) + find.Length.;

var cs = CompletionService.GetService(d);
var list = await cs.GetCompletionsAsync(d, index, CompletionTrigger.CreateInsertionTrigger('.'));
```

Notes:
* This can also be seen in Visual Studio's C# Interactive window by typing `var s =""; s. var k = "";`, placing the cursor after the `.` and hitting Ctrl+Space.
* Removing `var k = "";` makes it work as expected.
* It also works when adding `;` after the `.`.
* And it works inside the body of a method.

**Expected Behavior**: A list of members (in the above case, for `String`).

**Actual Behavior**: `list` is `null`.

### PR DESCRIPTION
**Pull request by aelij**
Fixes #12781

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-interactive for review

**Comment by aelij** [comment]
Ping @dotnet/roslyn-interactive

I would really appreciate it if this PR could be merged before 2.0 is released. It's a one line change (+ a test).

As you may or may not know, I have a [vested interest](https://github.com/aelij/roslynpad) in script language completion... ;)

Thanks!

**Comment by tannergooding** [comment]
FYI. @ManishJayaswal, @tmat

**Comment by tannergooding** [comment]
Also FYI. @KevinH-MS

**Comment by tmat** [comment]
LGTM, but I'm not familiar with the code. @CyrusNajmabadi?

**Comment by KevinH-MS** [comment]
This is in completion, so tagging @dotnet/roslyn-ide

**Comment by KevinH-MS** [comment]
Change seems reasonable to me 👍

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by tannergooding** [comment]
test vsi please

**Comment by KevinH-MS** [comment]
test vsi please

**Comment by tannergooding** [comment]
test windows_release_unit32_prtest please
test windows_release_unit64_prtest please

**Comment by tannergooding** [comment]
@jasonmalinowski, are VSI tests just generally on the floor right now? If so, I'm going to merge this (given that everything else is passing and this has been given the appropriate sign-off).

**Comment by tannergooding** [comment]
Also, will this make it into 2.0 RTM if it goes into Master, or does it need to be retargeted to a separate branch?

**Comment by ManishJayaswal** [comment]
yes it will make it into RTM if merged into master.

**Comment by tannergooding** [comment]
test windows_release_unit32_prtest please

**Comment by tannergooding** [comment]
test windows_release_unit64_prtest please

**Comment by tannergooding** [comment]
Looks like the integration tests are failing for the same reasons as they are in the commit job. I will merge after the release jobs finish.

**Comment by tannergooding** [comment]
Merged. Thanks for your contribution @aelij

**Pull request merged**
