### PR TITLE
Update Completion List API to make it easier to provide custom CompletionItem behavior

### PR DESCRIPTION
**Pull request by DustinCampbell**
This change reduces the number of methods that a ```CompletionListProvider``` implementer needs to handle and deal with. Each of the methods that I've moved were required for the provider to be able to provide the default behavior or to customer behavior around filtering and commit characters, whether enter is sent through to the editor or commit, or retrieving the text change for a particular completion item. Now, implementers get the default behavior for the current language for free. Alternatively, they can supply an object derived from ```CompletionItemRules``` to customize the behavior for their completion items.

**CompletionRules**: This is a concrete class version of the old ```ICompletionRules``` interface that languages can inherit from to provide default behavior. Additionally, it now asks completion items for various behaviors. If a completion item doesn't provide custom behaivor, the ```CompletionRules``` provides default behavior for the current language.

**CompletionItemRules**: a provider can override the methods in this class to provide custom behavior for particular completion items. If a provider does not override a method, the default behavior in the ```CompletionRules``` will be used.

There's still a lot yet to come. :smile:

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Good reviewers: @CyrusNajmabadi, @rchande, @dpoeschl, @Pilche, @jasonmalinowski

**Comment by CyrusNajmabadi** [comment]
Overall this looks great.  Should not be a problem for TS to adopt.  Reading through definitely makes it clear that there are lots of options for future refactorings to make things even better.

**Comment by DustinCampbell** [comment]
Agreed.

**Comment by DustinCampbell** [comment]
jenkins, retest this please

**Comment by DustinCampbell** [comment]
jenkins, retest this please

**Comment by DustinCampbell** [comment]
jenkins, retest this please

**Comment by DustinCampbell** [comment]
Finally! @CyrusNajmabadi, I'll merge this on Monday. I've got one more change planned that'll affect TypeScript (rationalizing text triggers) but I'm going to hold off on that one for a bit.

**Pull request merged**
