### PR TITLE
Clean up extension methods

### PR DESCRIPTION
**Pull request by DustinCampbell**
Taking some time to rename some extension method classes and delete some old extension methods. There's so much more of this to go. :smile:

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by DustinCampbell** [comment]
Please retest this

**Comment by DustinCampbell** [comment]
@dotnet-bot please retest this

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by DustinCampbell** [comment]
@dotnet-bot Retest this, please.

**Comment by DustinCampbell** [comment]
@dotnet-bot Retest this, pretty please with sugar and ice cream and cherries on top.

**Comment by DustinCampbell** [comment]
@dotnet-bot Retest this, please.

**Comment by DustinCampbell** [comment]
@dotnet-bot Retest this, please.

**Comment by DustinCampbell** [comment]
Retest this please

**Comment by DustinCampbell** [comment]
Retest this please

**Comment by DustinCampbell** [comment]
Sigh... this is crazy! Seems like some CI build machines are working and others aren't :frowning:

**Comment by DustinCampbell** [comment]
Last try

**Comment by DustinCampbell** [comment]
Retest this please

**Comment by DustinCampbell** [comment]
Retest this please

**Pull request merged**
