### PR TITLE
Run mutiple csharp compiler configurations

### PR DESCRIPTION
**Pull request by TyOverby**
@VSadov @basoundr @KevinH-MS @rchande

### CODE REVIEW

**Comment by KevinH-MS** [comment]
:+1:

**Comment by TyOverby** [comment]
@drognanar This is the PR that added multiple configurations.  If you give me the command line argument, I can add it here.

**Comment by drognanar** [comment]
I believe that the additional configuration should be added to its corresponding feature branch.

**Comment by TyOverby** [comment]
Sounds good.  I'll merge this now then.

**Pull request merged**
