### PR TITLE
Merge dev15-preview-4-df into master-20160809-150104

### PR DESCRIPTION
**Pull request by balajikris**
codeflow pull request : merge from dev15-preview-4-df into master.

### CODE REVIEW

**Comment by balajikris** [comment]
manually prepared as the bot isn't yet configured to run on preview4-df branch. 

No code changes, nothing to merge here.

@dotnet/roslyn-infrastructure : does this sound right? No merge required today, as there are no code changes.

**Comment by Pilchie** [comment]
We should still submit the merge so that the history records that the change from dev15-preview4-df made it back into master.

**Comment by Pilchie** [comment]
:+1:

**Comment by balajikris** [comment]
accidentally closed by pilchie. reopening.

**Comment by jcouv** [comment]
LGTM

**Pull request merged**
