### PR TITLE
Add declaration kind for local functions

### PR DESCRIPTION
**Pull request by ivanbasov**
Towards #22918
Need this declaration kind in analyzers

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Does this actually enable something new right now? Should there be a test to cover it?

**Comment by ivanbasov** [comment]
The change does not provide a new functionality to SyntaxGenerator. I created #22918 to add this functionality but suppose that its priority is not high. Fixing #22918 should add some methods and test cases for them. 

Here I need just an enum value meaning that "local function declaration" is a declaration. I think that no test scenarios for this are necessary.

This declaration is required in analyzers. They use GetDeclarationKind.

**Comment by mavasani** [comment]
@ivanbasov - I agree with Jason that we do need a test. Probably @agocke can advise on where to add a test.

**Comment by CyrusNajmabadi** [comment]
This seems weird.  I'd prefer a PR that does hte full change to make sure that this is all correct.

**Comment by ivanbasov** [comment]
Thank you! Added

---
In reply to: [340906708](https://github.com/dotnet/roslyn/pull/22919#issuecomment-340906708) [](ancestors = 340906708)

**Comment by ivanbasov** [comment]
Thank you! Added

---
In reply to: [340842043](https://github.com/dotnet/roslyn/pull/22919#issuecomment-340842043) [](ancestors = 340842043)

**Comment by ivanbasov** [comment]
Thank you, @CyrusNajmabadi! I do not mind to implement this but not sure it aligns with our 15.6 priorities. FYI: @jinujoseph

**Comment by CyrusNajmabadi** [comment]
@ivanbasov do you still want to move forward with this?

**Comment by ivanbasov** [comment]
> @ivanbasov do you still want to move forward with this?

@CyrusNajmabadi , I have no plans on this for the nearest time.

**Comment by CyrusNajmabadi** [comment]
Ok.  Going to close out to remove from active PR list.  Thanks!

**Pull request closed without merging**
