### PR TITLE
return correct ProjectGuid for build only filter

### PR DESCRIPTION
**Pull request by heejaechang**
see #3413 for more detail. this is same change for master.

### CODE REVIEW

**Comment by srivatsn** [comment]
LGTM

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by heejaechang** [comment]
retest this please

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by tmeschter** [comment]
@dotnet-bot Retest this, please.

**Comment by heejaechang** [comment]
@dotnet-bot retest this please

**Pull request merged**
