### PR TITLE
Fix assert in the VirtualCharService in C# directive trivia.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/29451

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @jcouv 

Note: i did an audit of both Lexers to see where strings appear.  Fortunately, there aren't any other locations that i could find.  For example, while there are strings that appear in xml doc comments and literals, they are not SyntaxKind.StringLiteralToken.  

So this should hopefully be the only case.  Also, i think it's worth nothing that the asserts were not crashes.  They were just notifications that we weren't handling some construct.  The outcome of that assert was that we would fail out gracefully.  So this should not affect anyone using a release build.

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi I feel like I also saw some case where `#line` still wasn't being used, but this is at least a good start.

And yes, it won't affect release builds....but it's a PITA for me debugging ASP.NET editor scenarios that spits a bunch of these. ;-)

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi I feel like I also saw some case where #line still wasn't being used, but this is at least a good start.

Could they have been other directives?  It looks like all strings in a directive will be of this form.

If you rnu into anything, let me know?  I did do an audit, but i could have missed something!

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Could be other directives, but it seemed like #region at least the compiler really doesn't parse at all.

**Pull request merged**
