### PR TITLE
fix some out-of-sync file names

### PR DESCRIPTION
**Pull request by genlu**
Noticed this while looking at some old PRs

### CODE REVIEW

**Comment by genlu** [comment]
@jinujoseph for approval, no code change here, just change of file names

**Comment by genlu** [comment]
I believe the naming pattern roslyn uses is:
- `OuterClass.InnerClass.cs` for file of nested type
- `ClassName_Subject.cs` for each subject of partial type.

@dotnet/roslyn-ide to confirm. We might want to have at least an analyzer for this in roslyn analyzers

**Comment by jasonmalinowski** [comment]
@genlu That was the rule. Without the enforcement it still got out of sync in plenty of places.

> Technically the name for nested types uses a + instead of a .

Technically yes, but everybody thinks of it as a . since that's how it's qualified in C#/VB/F#, etc.

**Comment by CyrusNajmabadi** [comment]
> @dotnet/roslyn-ide to confirm

That is correct.  We treat them effectively like C# names.  One way that we differ is that when distinguishing a generic vs non-generic type, we'll do `Foo.cs` and ``Foo`1.cs``

**Pull request merged**
