### PR TITLE
IOperation - expose declared locals for field/property/parameter initializers.

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
CC @gafter, @jaredpar For public API changes.

**Review by 333fred — APPROVED** [review]
:shipit:

**Comment by AlekseyTs** [comment]
@ dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review.

**Comment by AlekseyTs** [comment]
@ dotnet/roslyn-compiler, @dotnet/analyzer-ioperation Please review.

**Review by mavasani — APPROVED** [review]

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Review by gafter — APPROVED** [review]
:shipit:

**Pull request merged**
