### PR TITLE
ENC support for C#7.0: out var, ref, tuple and pattern matching

### LINKED ISSUE #12435: Add support for edit-and-continue for pattern-matching
The implementation of the pattern-matching switch statement should support edit-and-continue.

### LINKED ISSUE #12436: Add support for edit-and-continue for tuples
The implementation of tuples (in particular, deconstruction) should support edit-and-continue.

### LINKED ISSUE #16960: Edit and Continue for out variable declarations
I haven't found an issue tracking this very annoying problem, i.e. that EnC is disabled when there is out variable declaration wherever inside the member.

This makes using the feature not justified when just declaring the variable on a separate row gives me EnC.

Related issues: #12736 #13754

### LINKED ISSUE #17896: ENC support for out var

### PR DESCRIPTION
**Pull request by ivanbasov**
**Customer scenario**

Provides ENC support for C#7.0:

- out var
- ref
- pattern matching
- tuples

Unit tests provided. **Also I verified EnC scenarios manually.**

**Bugs this fixes:**

Fixes #17896
Fixes #12436
Fixes #16960
Some works towards #12435

**Workarounds, if any**

**Risk**

Low

**Performance impact**

Low

**Is this a regression from a previous update?**

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

Planned

### CODE REVIEW

**Comment by tmat** [comment]
:shipit:

**Comment by tmat** [comment]
This one is not fixed yet: https://github.com/dotnet/roslyn/issues/12435 -- we don't have switch statement working yet.

**Comment by jinujoseph** [comment]
Do we want to maintain missing switch statement support in pattern matching separately ?

**Comment by jcouv** [comment]
This change looks good as far as it goes, but I am missing some context. I thought that to enable EnC for C# 7 features (such as switch, out var, deconstruction) we needed at least two things:
- a reasonable distance function for such syntax
- some logic for managing slots (creating new ones, matching and re-using existing ones)

I this rough understanding correct? Have the latter been done already?

**Comment by tmat** [comment]
@jcouv Yes, that's correct. Ivan did both. The latter didn't need any changes in the compiler as it turned out the right syntax nodes were already associated with the local symbols.

**Comment by jcouv** [comment]
Very cool. Nice!

**Comment by ivanbasov** [comment]
Thank you, everybody, for the review and help! I have updated reference to #12435 in the description.

**Comment by ivanbasov** [comment]
Tagging @MattGertz for Ask mode approval

**Pull request merged**
