### PR TITLE
Explicitly reference all nuget package versions as build properties

### PR DESCRIPTION
**Pull request by jmarolf**

### CODE REVIEW

**Comment by jmarolf** [comment]
@tmat @srivatsn @shyamnamboodiripad @mavasani could you please take a look?

**Comment by tmat** [comment]
@jmarolf Isn't the PR missing the projects using these variables?

**Comment by jmarolf** [comment]
@tmat sadly I haven'y open sourced the projects that use these variables.

**Comment by tmat** [comment]
:+1: Although it would make reviewing easier if the changes were rebased.

**Pull request merged**
