### PR TITLE
Add nuget for Microsoft.VisualStudio.LanguageServices.Next...

### PR DESCRIPTION
**Pull request by KevinH-MS**

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @heejaechang @dotnet/roslyn-ide 
/CC @dotnet/testimpact

**Comment by KevinH-MS** [comment]
This is so I can consume the Solution SnapshotService from a separate repo...

**Comment by Pilchie** [comment]
The issue I have with this is versioning.  The *plan* is to move this code into LanguageServices once we ship Dev15, and then re-purpose `.Next` for Dev16 stuff.  If we have public surface area in .Next now, then it means adding type forwarders and other pain :(

**Comment by KevinH-MS** [comment]
I'll double check whether there's public surface area.

**Comment by KevinH-MS** [comment]
There is only one public type (```Microsoft.VisualStudio.Imaging.Interop.ImageMoniker```).  This is an embedded interop type.

Is this any concern?  I would guess no, because the compiler should generate an error if you try to use that type (saying you need to add a reference to the PIA yourself).

**Comment by Pilchie** [comment]
No, that's fine - however, I don't think the public API analyzer is hooked up. Can we do so, to ensure no new API *does* get added?

**Comment by KevinH-MS** [comment]
Yes, I'll follow up on that today.

**Comment by KevinH-MS** [comment]
I have verified that the publicapi analyzer is hooked up for the ServicesVisualStudio.Next project and that it generates an error if a new public type is added.

**Comment by Pilchie** [comment]
Thanks!

**Comment by heejaechang** [comment]
public api analyzer should be already hooked up.

**Pull request merged**
