### PR TITLE
Move SRM to 6.0.1

### PR DESCRIPTION
**Pull request by jaredpar**
This gets us in sync with the recent Visual Studio change to move this package forward

https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/434270

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 2)

**Review by ryzngard — CHANGES_REQUESTED** [review]
Waiting on validation build. https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=6964051&view=results

**Comment by ryzngard** [comment]
https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/435837 is the insertion

**Review by ryzngard — APPROVED** [review]
Approving to checkin for P3 with https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/438292 validation PR

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Pull request merged**
