### PR TITLE
Decouple the InteractiveWorkspace from needing a InteractiveEvaluator

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Everything only needed the IInteractiveWindow. This makes life easier for TypeScript.

*Review:* @dotnet/roslyn-interactive, @paulvanbrenk, @mousetraps, @CyrusNajmabadi

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by tmat** [comment]
:+1: 

FWIW, I think we could generalize InteractiveEvaluator a bit to make using IW with Roslyn Workspaces easier. For example, the logic around creating a chain of projects as submissions are added could likely be reused. Perhaps the logic can be moved to InteractiveWorkspace.

**Comment by jasonmalinowski** [comment]
TypeScript's case is they don't have a chain based upon how their underlying model is. But this at least means they can use InteractiveWorkspace as a start while we figure out how to refactor the rest of it.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Comment by paulvanbrenk** [comment]
Do we need to add TypeScript to the IVT ?

**Comment by jasonmalinowski** [comment]
@paulvanbrenk: probably. I'll leave that on you since you can actually test that you're doing it right.

**Pull request merged**
