### PR TITLE
Bug6215

### PR DESCRIPTION
**Pull request by mattwar**
Fix for #6215 API Review followup

Note: only made changed to MSBuildProjectLoader.LoadProjectAsync because argument to LoadSolutionAsync wasn't being used, so I removed it.

@Pilchie @DustinCampbell  please review

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1:

**Comment by davkean** [comment]
retest please

**Comment by davkean** [comment]
retest prtest/win/dbg/eta please

**Comment by davkean** [comment]
retest prtest/win/dbg/eta please
retest  prtest/win/dbg/unit64  please

**Comment by davkean** [comment]
Your builds were aborted when Jenkins went down, reran them.

**Comment by davkean** [comment]
:+1:

**Pull request merged**
