### PR TITLE
Remove GeneratedSource node from Solution Explorer

### PR DESCRIPTION
**Pull request by cston**
How generated source is exposed in the Solution Explorer is still TBD.

### CODE REVIEW

**Comment by cston** [comment]
Fixes 224639.

@dotnet/roslyn-ide, @jaredpar, @mattgertz please review.

**Comment by jasonmalinowski** [comment]
:+1:. That's definitely one way to fix it. :smile:

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by MattGertz** [comment]
Well OK then... :-)

**Pull request merged**
