### PR TITLE
Localize "Error"/"Warning" etc. in the code style UIs

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes part 2 of #9674 for both the general code style page and the
naming style option page.

This also removes the superfluous "EnforcementLevel" class in the
NamingPreferences namespace that was basically a duplication of
"NotificationOption"/"NotificationOptionViewModel" in the general
CodeStyle namespace.

## Ask Mode Info

**Customer scenario**: The Severity options (None/Suggestion/Warning/Error) were not localized in the code style pages, making it hard for non-English users to use..
**Bugs this fixes**: Part 2 of #9674
**Workarounds**: None
**Risk**: Very low
**Performance impact**: None.
**Is this a regression from a previous update?**: No, this has been broken since the UI was introduced
**Root cause analysis**: It was skipped as part of the original feature work.
**How was the bug found?**: Ad hoc testing (see screenshot from #9674)

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide for review.

**Comment by dpoeschl** [comment]
Ping for a second review. @dotnet/roslyn-ide @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by dpoeschl** [comment]
Tagging @MattGertz for Ask Mode approval.

@nguerrera To ensure we're still pre-locfreeze.

**Comment by nguerrera** [comment]
> @nguerrera To ensure we're still pre-locfreeze.

We are. 11/25 build must have your strings in it to make final handback.

**Comment by dpoeschl** [comment]
Merged with a failing test that @jaredpar accidentally enabled for the rc2 branch. He said it was okay to ignore the failure.

**Comment by MattGertz** [comment]
Great, thank you.

**Pull request merged**
