### PR TITLE
Move some of `Roslyn.Utilities` using statements into namespace block

### PR DESCRIPTION
**Pull request by sanmuru**
Roslyn cannot target net6.0 right now though, according to conclusion in #65905, we can still make preparations for that.
These changes only resolve semantic type conflicts between types in Roslyn projects and `System.Runtime` of net6.0, e.g. `Error CS0104: 'IReadOnlySet<T>' is an ambiguous reference between 'Roslyn.Utilities.IReadOnlySet<T>' and 'System.Collections.Generic.IReadOnlySet<T>'`.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=66007) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=66007) before we can accept your contribution.<br/><br/>:x: sanmuru [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=66007)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn?pullRequest=66007) it.</sub>

**Review by AlekseyTs — CHANGES_REQUESTED** [review]
@sanmuru We prefer keeping usings at the top of the file. Ambiguates can be resolved by fully qualifying the types.

**Comment by jaredpar** [comment]
> according to conclusion in https://github.com/dotnet/roslyn/issues/65905, we can still make preparations for that.

Disagree. The conclusion is that we'll move to `net6.0` at some point in the future. Not that we should start actively making changes for that future. I think making them before the change is a bit premature.

**Review by 333fred — CHANGES_REQUESTED** [review]
I would agree with Jared. This change seems both premature and unlikely to result in the outcome you desire, which is "no errors when targeting a newer version". There is no testing that this condition will work as you expect, and using something like IgnoreAccessChecks or fork+new IVT are explicitly scenarios we will never support.

**Comment by sanmuru** [comment]
Thank you @jaredpar and @333fred for your comments and your patience, I really appreciate that.
I don't think we are talking about how ones extend functionalities of Roslyn. It's okay to use IACT or fork+new IVT if they use for their own purposes (no affect to Roslyn whatsoever).
Anyway, I understand Jared's point of view, and I will close this request.

**Pull request closed without merging**
