### PR TITLE
Remove IComWrapperFactory

### PR DESCRIPTION
**Pull request by mattscheffer**
IComWrapperFactory now comes from the VSSDK. Remove our private
definition.

### CODE REVIEW

**Comment by pharring** [comment]
:+1:

**Comment by balajikris** [comment]
LGTM. :+1:

**Comment by pharring** [comment]
I have a more extensive follow-up change to move the BlindAggregator stuff out of VisualStudio.LanguageService and into unit tests, but that can wait.

**Comment by balajikris** [comment]
@pharring - thanks, I agree. We need this commit however to move to the next drop :wink:

**Comment by tannergooding** [comment]
This was replace with PR #2586 as this one contains a merge conflcit and we need to move to the new baseline.

**Pull request closed without merging**
