### PR TITLE
Remove eng/docker/mono.sh script

### PR DESCRIPTION
**Pull request by akoeplinger**
It doesn't seem to be used anymore after https://github.com/dotnet/roslyn/pull/51815

Closes https://github.com/dotnet/roslyn/issues/44813

### CODE REVIEW

**Review by 333fred — APPROVED** [review]

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Tagging @chsienki for review--is this change appropriate?

**Comment by akoeplinger** [comment]
@chsienki ping :)

**Comment by chsienki** [comment]
ping @jaredpar or @RikkiGibson who have merge permissions. I can't get the 64 bit integration to flip green even though this change should have no impact on it.

**Comment by 333fred** [comment]
It's been quite some time since the pipeline was created, I want to make really sure nothing funny happens.

**Review by jaredpar — APPROVED** [review]

**Pull request merged**
