### PR TITLE
draft

### PR DESCRIPTION
**Pull request by Youssef1313**
As usual, to see what this affects.

### CODE REVIEW

**Review by Youssef1313 — COMMENTED** [review]
@333fred @AlekseyTs 

Is there any meaningful impact by this change?

The single test failure is already an error scenario where we now produce one more extra diagnostic. But I can't understand what "real" harm can this change cause.

**Comment by RikkiGibson** [comment]
Suggest adding a test with a readonly setter. Something like:

```cs
S s = default;
object obj = new object();
/*<bind>*/
s.ObjectValue = obj;
/*</bind>*/

class C
{
    public object ObjectValue;
}

struct S
{
    private C CValue;
    public readonly object ObjectValue { get => CValue.ObjectValue; set => CValue.ObjectValue = value; }
}
```

In the above test `s` should *not* show as written. If 'readonly' is removed from the property then it *should* show as written.

**Comment by AlekseyTs** [comment]
@Youssef1313 

> Is there any meaningful impact by this change?

Try flipping around the change. It looks like after the change all properties are processed as auto-properties, consider changing to the mode where all properties are processed as regular properties.

**Comment by RikkiGibson** [comment]
Unassigning myself to clean up my queue, let me know if you need further guidance here.

**Pull request closed without merging**
