### PR TITLE
Remove workaround that's already included in MSBuild 15.5

### PR DESCRIPTION
**Pull request by kzu**
See https://github.com/Microsoft/msbuild/commit/052ad30f8f706a87e9fa9431fda1ec9c0b73893b

I suppose this would need to wait until all CI systems use 15.5+ though? But since it's already RTM, maybe all checks will pass? We'll see ;)

### CODE REVIEW

**Comment by kzu** [comment]
Hm. I'm guessing the jenkins `windows_debug_vs-integration_prtest` isn't running latest MSBuild?

**Comment by jasonmalinowski** [comment]
@kzu It's not yet, no. We still have pending work to update it.

**Comment by jasonmalinowski** [comment]
@kzu No, you hit a random test flaking out. Which MSBuild release was the fix included in? Those machines aren't on 15.5 yet anyways.

**Comment by jaredpar** [comment]
Closing / Re-opening to retrigger our runs.

**Comment by jasonmalinowski** [comment]
@jaredpar Let's just say my concerns about MSBuild and versioning are not increased by or unique to this pull request. 😉

**Comment by jaredpar** [comment]
Thanks @kzu!

**Comment by kzu** [comment]
👍

**Pull request merged**
