### PR TITLE
Classify ??= as an operator.

### LINKED ISSUE #45319: ??= is not colorized as operator
**Version Used**: 
16.6.2

**Steps to Reproduce**:

1.  New C# project

image

**Expected Behavior**:

`??=` should be the same color as `=` above.

### PR DESCRIPTION
**Pull request by diryboy**
Fixes #45319

### CODE REVIEW

**Comment by diryboy** [comment]
retest Windows_Desktop_Unit_Tests release_32 please

**Comment by 333fred** [comment]
Related: https://github.com/dotnet/roslyn/issues/29948

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a second, 1-line review.

**Comment by 333fred** [comment]
Thanks @diryboy!

**Pull request merged**
