### PR TITLE
Remove unnecessary APIs and unused parameters from APIs.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
test windows_eta_open_prtest  please

**Comment by jmarolf** [comment]
test vsi please

**Comment by mavasani** [comment]
This PR broke the API callsites in stancore and also the scenario of suppressing all diagnostics for a project/solution - this needs to pass in the optional project hierarchy. I am going to revert it unblock insertion.

**Comment by CyrusNajmabadi** [comment]
How did it break things?  There was no one htat ever passed in a project hierarchy.

**Comment by CyrusNajmabadi** [comment]
> also the scenario of suppressing all diagnostics for a project/solution 

How was this scenario ever manifested to users?  How did the code action work?

**Comment by mavasani** [comment]
Index is busted - see here: https://devdiv.visualstudio.com/_search?type=Code&lp=search-project&text=AddSuppressions&result=DefaultCollection%2FDevDiv%2FVS%2FGBmaster%2F%2Fsrc%2Fedev%2FStaticAnalysis%2FStanPackage%2FCore%2FMenuHandlers.cs&filters=ProjectFilters%7BDevDiv%7DRepositoryFilters%7BVS%7D&preview=1&_a=contents

**Pull request merged**
