### PR TITLE
Merge dev15-rc into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15-rc into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-dev15-rc-into-master20161031-150038
git reset --hard upstream/master
git merge upstream/dev15-rc
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-dev15-rc-into-master20161031-150038 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by genlu** [comment]
Failed vsi tests in https://ci.dot.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/562/ is caused by windows update dialog.
The other two vsi failure are logged and linked with this PR.

**Comment by genlu** [comment]
@dotnet-bot test vsi please

**Comment by OmarTawfik** [comment]
@genlu are these transient failures? is this expected with VSI tests?

**Comment by genlu** [comment]
@OmarTawfik I was told that dev14 vsi tests are expected to be green

**Pull request merged**
