### PR TITLE
Adjust implementation of OverloadResolution.GetParameterCounts to account for a situation when params parameter is used through a named argument.

### LINKED ISSUE #4424: VS2015 compiler picks overload differently from VS2010; should be ambiguous?
Given the function members

    void Fn(string x = "", string y = "", params object[] p) {}
    void Fn(string x, params object[] p) {}

and the invocation

    Fn("Hello", p: "World");

VS2015 uses the first definition of `Fn` both for IntelliSense and when debugging.

By contrast

 - VS2013 (on a system with VS2015 also installed) uses the first definition of `Fn` when debugging but the second for IntelliSense.
 - VS2010 uses the second definition of `Fn` for IntelliSense and (reportedly) when debugging.

By [my reading of the C# 5 specification](http://stackoverflow.com/a/31884572/215380) both function members are applicable but neither is "better" so the compiler should report the invocation as ambiguous.

(Further, if you remove `p` from both function members and the invocation, both VS2015 and VS2013 pick the second member over the first, which makes me more inclined to believe it should be ambiguous.)

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #4424.

@gafter, @VSadov, @jaredpar, @agocke Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Ping. @gafter, @VSadov, @jaredpar, @agocke Please review.

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @jaredpar, @agocke Please review. Need a second sign-off.

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @jaredpar, @agocke Please review. Need a second sign-off.

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
