### PR TITLE
Workaround for project references bugs

### PR DESCRIPTION
**Pull request by tmat**
Workaround for https://github.com/dotnet/roslyn/issues/43633 and https://github.com/dotnet/roslyn/issues/43632

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski @jinujoseph

**Comment by jasonmalinowski** [comment]
@tmat So you think it's the uniqueness validation that was throwing this off now? Because that might be a good key for a proper fix...

**Comment by tmat** [comment]
@jasonmalinowski Actually, it was a different condition. I commented out the wrong dup validation. It should be the validation that the project doesn't already have the reference, not that there are no dups in the array passed in.

**Comment by jasonmalinowski** [comment]
@tmat even prior to your refactorings though, we did still block AddProjectReference from adding duplicates, right?

https://github.com/dotnet/roslyn/blob/973d5a41454373c70c7d3216fb0cb87cb026d5d6/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs#L907

So this is actually weakening the checks further than what we had in 16.5 right? So your refactoring couldn't have been the problem?

**Comment by jasonmalinowski** [comment]
(not saying this PR isn't useful since it's pointing to where the actual problem is...)

**Comment by tmat** [comment]
Yes, that seems correct. Perhaps we have had these NFW before and just didn't look at them?

**Comment by jasonmalinowski** [comment]
So the project system started reporting and triaging the non-fatal reports in 16.5 which is why we're getting these now. What might be happening though is different stacks are shifting around as we refactored things and that makes it hard to sort out.

**Comment by tmat** [comment]
OK, so maybe we only work around https://github.com/dotnet/roslyn/issues/43633 (RemoveProjectReference) and not the other because it's been there for a while?

**Comment by jasonmalinowski** [comment]
Closing this in favor of https://github.com/dotnet/roslyn/pull/43803 which we think is fixing underlying issues here.

**Pull request closed without merging**
