### PR TITLE
Make MetadataHelpers.GetInfoForImmediateNamespaceMembers more robust against invalid metadata.

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@gafter, @VSadov, @jaredpar, @agocke, @TyOverby Please review.

**Comment by TyOverby** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Ping. @gafter, @VSadov, @jaredpar, @agocke Please review, need a second sign-off.

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
