### PR TITLE
Propagate CharSet for structs implementing fixed buffers from the field's containing type.

### LINKED ISSUE #3392: A C# POD struct is not compiled into a runtime POD struct correctly
There is problem with code generation for that:
```csharp
[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
  public unsafe struct WIN32_FIND_DATA
  {
    public uint dwFileAttributes;
    public FILE_TIME ftCreationTime;
    public FILE_TIME ftLastAccessTime;
    public FILE_TIME ftLastWriteTime;
    public uint nFileSizeHigh;
    public uint nFileSizeLow;
    public uint dwReserved0;
    public uint dwReserved1;
    public fixed char cFileName [260];
    public fixed char cAlternateFileName [14];
  }
```

If you compile project with BuildToolVersion 12 (using C# compiler), all it works.
If you compile project with BuildToolVersion 14 (using Roslyn compiler), we get runtime exception `"Cannot marshal 'parameter #2': Pointers cannot reference marshaled structures.  Use ByRef instead."` when we call P/Invoke.

repro:
https://github.com/vlomshakov/RoslynReproSolution
MsBuild version: 14.0.22609.0

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #3392.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - Fixes #3392
- Customer scenario – If a structure with CharSet != Ansi contains a fixed size buffer, it cannot be successfully marshaled by PInvoke. The PInvoke operation is either going to throw System.Runtime.InteropServices.MarshalDirectiveException, or incorrectly marshal data.   
- Fix description - Propagate CharSet for structs implementing fixed buffers from the field's containing type. VS2013 compiler does this too.
- Testing done - unit-tests.

@jaredpar FYI

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

**Comment by jaredpar** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by MattGertz** [comment]
Approved 6/10 by ML Shiproom.

**Pull request merged**
