### PR TITLE
Remove unused FindAllReferences method.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This interface method wasn't called from anywhere.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @paulvanbrenk 

Once this is removed you can remove your implementation of it.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by balajikris** [comment]
:+1:

**Comment by Pilchie** [comment]
👍

**Pull request merged**
