### PR TITLE
Add all the JSON parsing tests into their own branch.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Follow up to https://github.com/dotnet/roslyn/pull/24110 .  This pulls the JSON parsing tests into their own branch/PR to make the other PR much easier to manage.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
@CyrusNajmabadi should this go into master?

**Comment by CyrusNajmabadi** [comment]
@Neme12 The branch here isn't relevant.  This PR isn't for reviewing.  It's simply to break out hte tests so that once all dependent PRs go in, this can tehn be cleanly merged into whatever branch is most appropriate.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi closing this PR as discussed previously.
We can reopen and work together when we will reconsider this

**Pull request closed without merging**
