### PR TITLE
reduce creating default Task.FromResult tasks.

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@KevinH-MS @mavasani @srivatsn @panopticoncentral can you take a look?

**Comment by heejaechang** [comment]
test vsi please

**Comment by Pilchie** [comment]
:+1:

**Comment by mavasani** [comment]
👍

**Comment by heejaechang** [comment]
retest windows_debug_unit64_prtest please

Jenkins went offline

**Comment by heejaechang** [comment]
retest windows_vsi_p1_open_prtest  please

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest please

**Comment by mavasani** [comment]
VSI runs failing due to https://github.com/dotnet/roslyn/issues/13032

**Comment by panopticoncentral** [comment]
:+1:

**Comment by heejaechang** [comment]
retest windows_vsi_p1_open_prtest  please

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest  please

**Comment by heejaechang** [comment]
@mavasani p3 is having same issue.

**Comment by heejaechang** [comment]
test indows_vsi_p3_open_prtest please

**Comment by mavasani** [comment]
Yes, @dotnet/roslyn-infrastructure were we able to find the root cause for the ErrorListPackage load failures?

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/master/job/windows_vsi_p3_open_prtest/398/
// Retest reason:

**Pull request merged**
