### PR TITLE
semi auto properties: Address feedback of previous PR

### PR DESCRIPTION
**Pull request by Youssef1313**
@333fred @AlekseyTs

### CODE REVIEW

**Comment by Youssef1313** [comment]
Test failure is https://github.com/dotnet/roslyn/issues/34207

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 1)

**Comment by AlekseyTs** [comment]
@333fred, @dotnet/roslyn-compiler For the second review.

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks @Youssef1313!

**Pull request merged**
