### PR TITLE
Update tuples.md to add a note about tuple conversions.

### PR DESCRIPTION
**Pull request by VSadov**
Added a note about tuple conversions.

Fixes:#10852

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - FYI   tuples.md   update to include note about tuple conversions.

**Comment by gafter** [comment]
These documents now belong in https://github.com/dotnet/csharplang/tree/master/proposals/csharp-7.0 rather than in the Roslyn tree.

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by VSadov** [comment]
test windows_release_unit32_prtest please

**Pull request merged**
