### PR TITLE
Do not directly cast symbol to IMethodSymbol

### PR DESCRIPTION
**Pull request by jmarolf**
Fix for issue #786

Do not directly cast symbol to IMethodSymbol

### CODE REVIEW

**Comment by jmarolf** [comment]
@rchande @shyamnamboodiripad @ManishJayaswal @heejaechang could you review this please?

**Comment by heejaechang** [comment]
:+1:

**Comment by rchande** [comment]
:+1:

**Comment by shyamnamboodiripad** [comment]
:+1:

**Pull request merged**
