### PR TITLE
Remove extra files from VSIXes

### PR DESCRIPTION
**Pull request by amcasey**
Mechanically apply <Private>False</Private> to the newly-appeared
references.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @MattGertz @ManishJayaswal: This is the change we discussed this morning.

**Comment by amcasey** [comment]
Possible CRs: @jasonmalinowski @KevinH-MS

**Comment by tmeschter** [comment]
LGTM.

**Comment by KevinH-MS** [comment]
In this context, what does "newly appeared" mean?

**Comment by KevinH-MS** [comment]
Never mind--I read your tf checkin comment.  LGTM, although perhaps MSBuild gives a property/flag to opt into the old behavior?

**Comment by amcasey** [comment]
The next signed build succeeded.

**Pull request merged**
