### PR TITLE
Revert "Merge pull request #14671 from mattwar/Streamer"

### PR DESCRIPTION
**Pull request by dpoeschl**
This reverts commit 7dd78ae8a5f2d64c0fa1a41864b4bb0a61026582, reversing
changes made to 449f55864c4acddae0d489fd54ae8b197622e8e2.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @mattwar @jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by mattwar** [comment]
You going to have to revert Cyrus's change and https://github.com/dotnet/roslyn/pull/14944 too

**Comment by dpoeschl** [comment]
@mattwar We believe we've reverted #14944 now.

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by mavasani** [comment]
Merging in to unblock.

**Pull request merged**
