### PR TITLE
[WIP] Allow using directives in blocks

### PR DESCRIPTION
**Pull request by alrz**
Proposal: https://github.com/dotnet/csharplang/issues/218

Lets you write code like this:
```cs
void M()
{
  using static System.Console;
  WriteLine();
}
``` 
This PR does not cover type-level usings yet.

Note: Public API analyzer is disabled for now.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@alrz Is there an active proposal for this feature as apposed to an issue?

**Comment by alrz** [comment]
@AlekseyTs No, should I open a PR against dotnet/csharplang for it?

**Comment by jaredpar** [comment]
@alrz 

> No, should I open a PR against dotnet/csharplang for it?

Yes. This is the process for new language features (community and compiler team). It's noted in our [repository code contribution document](https://github.com/dotnet/roslyn/blob/master/CONTRIBUTING.md)

The specific guideline is 

> DO submit language feature requests as issues in the C# language / VB language repos. Once a feature is championed and validated by LDM a developer will be assigned to help begin a prototype on this repo inside a feature branch.

Language features generally don't fit into the scope of a PR. Instead we create feature branches for them, do the work there (compiler through IDE experience) and then move them back to the main branches.

**Comment by alrz** [comment]
>Once a feature is championed and validated by LDM a developer will be assigned to help begin a prototype on this repo inside a feature branch.

ok, so I'll wait for LDM approval.

**Pull request closed without merging**
