### PR TITLE
Remove ImportGroup

### PR DESCRIPTION
**Pull request by jaredpar**
The ImportGroup element is just noise.  It was also used very inconsistently in the repo and often within the same project file.  Just remove it.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @jasonmalinowski, @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
Not sure I see the value in making this change. Project systems might take advantage of this, which we've now subtly broken. Do we @dotnet/project-system?

**Comment by jaredpar** [comment]
@jasonmalinowski that's why I asked you on slack if they were just noise or actually valuable.  You indicated noise but certainly one or the other must be true. 

If they're valuable then it should be done consistently in the repo.  If they're not then remove the noise.

**Comment by jasonmalinowski** [comment]
@jaredpar: my statement was not intended to be strong enough to say that we should make this change.

More than anything else, I've seen plenty of places where people tried to make things cleaner in our project files "because I think it's cleaner", only to break all sorts of subtle things. For example, the special case hackery you were asking about for ProjectLanguage stuff in the XAML PR is entirely self-inflicted pain because somebody wanted to "remove duplication" from our projects without understanding the ramifications of the change. That's wasted vastly more time on the team than it ultimately did in work saved.

Not saying we shouldn't do this, let's just ask questions to understand the parts we don't know first. I know that I don't know what in the project system might have behavior dependent upon this. And there are plenty of changes you can make to a project file that appear innocuous to the command line MSBuild that will totally cause broken behavior in the IDE. :smile:

**Comment by jaredpar** [comment]
Right now we have entries in our project files that look like this

``` xml
<Import ... />
<Import ... />
<ImportGroup>
  <Import ... />
</ImportGroup>
```

This needs to be fixed.  Either `ImportGroup` has meaning or it doesn't.  Based on the evidence in our own repo I'd say it has no effect.

**Comment by jasonmalinowski** [comment]
I'd wait until @dotnet/project-system can make a definitive statement about CPS expectations, if there are any.

**Comment by jaredpar** [comment]
I'm happy to wait and get a more authoritative take on the matter.  

I would say though that if `<ItemGroup>` does matter, it's entirely unclear why or how it does.

**Comment by jasonmalinowski** [comment]
@jaredpar you should frame that statement, since that's the project system in a nutshell.

**Comment by davkean** [comment]
This looks good. :+1: 

While CPS can use labels to determine where to put props and items, I'm not aware of it using it for imports. Even then, we have no plans on taking advantage of this in the new project system - as Jared points out, it's just noise.

**Pull request merged**
