### PR TITLE
Add interfaces to EE vsdconfig

### PR DESCRIPTION
**Pull request by cston**
Add interfaces to EE vsdconfig implemented in https://github.com/dotnet/roslyn/commit/fffc52e5f4108ab787410f27b10a6846288b0ad2

### CODE REVIEW

**Comment by cston** [comment]
@kevinh-ms, @r-ramesh, @plnelson please review.

**Comment by plnelson** [comment]
👍

**Comment by r-ramesh** [comment]
Looks good to me

**Comment by cston** [comment]
@dotnet-bot retest this please

**Pull request merged**
