### PR TITLE
Allow an embedded language to participate in document highlighting.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This wasn't part of the previous embedded-language-services PR because that PR just contained the features necessary for embedded-json.  Embedded-json doesn't have a need (afaict) for 'document highlights', whereas embedded-regex does.  

Note: this should be reviewed after https://github.com/dotnet/roslyn/pull/26074 goes in.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@jcouv @jmarolf @dotnet/roslyn-ide  The same code that just went into features/embeddedJson.  This is the system that allows an embedded language to export the right language services so that they light up automatically, without needing the actual features to know about this specific new language.

**Comment by CyrusNajmabadi** [comment]
tagging @jcouv @jmarolf .  much simpler now.

**Comment by jmarolf** [comment]
This *is* much simpler.  What is our strategy for tests here? Is that going to be resolved in a different PR?

**Comment by CyrusNajmabadi** [comment]
Yes.  All of these are tested in their respective "JSON ide features" and "Regex IDE features" PRs.  Those are the PRs that actually add the impls for those interfaces, so those are the best PRs to actually validate that they're doing the right thing.

**Pull request merged**
