### PR TITLE
Add support for paths with spaces in cibuild

### PR DESCRIPTION
**Pull request by davkean**
Quote all the things

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @jaredpar @agocke

**Comment by davkean** [comment]
For some strange reason I decided it would be good dogfooding to put spaces in my roslyn enlistment - this has caused me no ends of pain.

**Comment by jaredpar** [comment]
@davkean way to take one for the team!

**Comment by jaredpar** [comment]
:+1:

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/3547/
// Retest reason: #8498

**Pull request merged**
