### PR TITLE
Remove non-portable dependencies from EEs

### LINKED ISSUE #1704: ExpressionCompiler projects reference non-portable compiler desktop assemblies
...for the DesktopAssemblyIdentityComparer.  We need to refactor to make it properly portable.

### PR DESCRIPTION
**Pull request by tmat**
Move DesktopAssemblyIdentityComparer to CodeAnalysis. 
Add type forwarder to CodeAnalysis.Desktop to avoid a breaking change.

Fixes #1704.

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar

**Comment by tmat** [comment]
@agocke @VSadov

**Comment by tmat** [comment]
@amcasey

**Comment by KevinH-MS** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:

**Comment by tmat** [comment]
@dotnet-bot retest this, please.

**Comment by Maxwe11** [comment]
@dotnet-bot test this please

**Comment by amcasey** [comment]
Am I reading the git rename syntax correctly?  It looks like there's now a "Desktop" folder under "Portable".

**Comment by amcasey** [comment]
Thanks for fixing this!  LGTM

**Comment by tmat** [comment]
Yes, there is Desktop under Portable. We are merging Desktop stuff into CodeAnalysis. As soon as everything is portable we can rename Portable to something else :)

**Comment by agocke** [comment]
LGTM

**Pull request merged**
