### PR TITLE
Add exception message to CSharpCompilation.GetSpecialType

### PR DESCRIPTION
**Pull request by tmeschter**
Related to https://devdiv.visualstudio.com/DevDiv/_workitems/edit/459418.

Our non-fatal error reports indicate this method is often called with
an out-of-range value for the `specialType` parameter. This commit adds
a custom message to the resulting `ArgumentOutOfRangeException` so we
can see what we're being asked about.

### CODE REVIEW

**Comment by jcouv** [comment]
1. Could you add a test? Look for references to this method (a bunch come from tests). Thanks
2. Also, I see a very similar method in VB (`VisualBasicCompilation.GetSpecialType(SpecialType)`, which will `Throw New ArgumentOutOfRangeException()` with no arguments). Consider making same fix.

**Comment by tmeschter** [comment]
@jcouv What would I test? The value of the exception message?

**Comment by jcouv** [comment]
I'd print/assert the exception.

**Comment by cston** [comment]
`GetSpecialType()` is checking for the range of values of `SpecialType` other than `SpecialType.None`. I suspect the exception is when `None` is passed.

**Comment by jcouv** [comment]
Found an issue that is related, and the value in that case was `None`.
https://github.com/dotnet/roslyn/issues/18379

**Comment by tmeschter** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please

**Pull request merged**
