### PR TITLE
Merge dev15-rc into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from dev15-rc into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-dev15-rc-into-master20161102-150038
git reset --hard upstream/master
git merge upstream/dev15-rc
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-dev15-rc-into-master20161102-150038 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by genlu** [comment]
@dotnet-bot Retest windows_vsi_p1_open_prtest, please.

**Comment by genlu** [comment]
@dotnet-bot Retest windows_vsi_p3_open_prtest, please.

**Comment by OmarTawfik** [comment]
@jaredpar in this commit: https://github.com/dotnet/roslyn/commit/b9ba3e9e4904794f0b51e2a6377ef70a31019184, you removed two files from [Compilers.swr](https://github.com/dotnet/roslyn/blob/master/src/Setup/DevDivVsix/CompilersPackage/Microsoft.CodeAnalysis.Compilers.swr) in master:

- System.Diagnostics.Process.dll
- System.Diagnostics.StackTrace.dll

Wanted to make sure this is the intended behavior as I'm resolving these merge conflicts and they do ship in dev15-rc.

**Comment by jaredpar** [comment]
CC @agocke for that question.  He's corrected me several times on it.

**Comment by agocke** [comment]
@jaredpar @OmarTawfik Both of those look necessary. StackTrace is used by scripting and Process is used by the build task.

**Comment by OmarTawfik** [comment]
@jaredpar @agocke will bring them back then.

**Comment by OmarTawfik** [comment]
@dotnet-bot test vsi please

**Comment by genlu** [comment]
@OmarTawfik Yes, looks like #9671

**Pull request merged**
