### PR TITLE
	Allow a user to generate operators when generating .Equals

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Feature looks like 

image

And generates code like:

image

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide 

Note: this is a followup PR to https://github.com/dotnet/roslyn/pull/17975.  When that PR goes through, this PR will becomea  lot smaller.

**Comment by Pilchie** [comment]
Not a full review, but when generating `operator ==` need to check `order1` for null if it's a reference type.

**Comment by Pilchie** [comment]
(or call the static `object.Equals()` though that add a lot of indirection (and boxing in value type cases)

**Comment by CyrusNajmabadi** [comment]
> Not a full review, but when generating operator == need to check order1 for null if it's a reference type.

We do, if the type is a reference type.  We don't when it's a value type :)

**Comment by CyrusNajmabadi** [comment]
In the reference case we call EqualityComparer<T>.Default.Equals(...), thus getting null checks, without any boxing or typechecks.

**Comment by CyrusNajmabadi** [comment]
Preemptively merging in.  Let me know if there's anything you want me to change.

**Pull request merged**
