### PR TITLE
Add S.R.Serialization.Json NuGet reference to CoreCLR projects

### PR DESCRIPTION
**Pull request by agocke**
@jaredpar @richardlford

### CODE REVIEW

**Comment by jaredpar** [comment]
Why do we need this reference?

**Comment by agocke** [comment]
@richardlford discovered that it was a runtime dependency. Rich, did you still have a record of specifically where we load that type?

**Comment by jaredpar** [comment]
I don't know of anywhere the compiler uses JSON so this dependency would be a real surprise.

**Comment by agocke** [comment]
Nevermind, I found the reference: http://source.roslyn.io/#Microsoft.CodeAnalysis/CommandLine/ErrorLogger.cs,30

We support serializing the errors to Json, so we use DataContractJsonSerializer from S.R.Serialization.Json.

**Comment by jaredpar** [comment]
Ah okay. 

:+1:

**Pull request closed without merging**
