### PR TITLE
removed debug code. it looks like this code got accidentally in.

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
failure is know issue https://github.com/dotnet/roslyn/issues/7379

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/dbg/eta please

**Comment by heejaechang** [comment]
@jasonmalinowski @dotnet/roslyn-ide can you code review? simple change, while doing other stuff, saw this one where same variable is assigned twice in a row. I just deleted one.

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
