### PR TITLE
Removed CodeCleanup experiment settings and experience.

### PR DESCRIPTION
**Pull request by JoeRobich**
In preparation for a platform code cleanup experience, remove the Roslyn code cleanup experiment.

CC @sharwell 

### Customer scenario

The Platform Code Clean-Up experience has its own dialog and configuration options for the fixes it performs. A customer would be confused to find a seemingly related Tools>Options page with C# Clean-Up options that are not respected by the platform feature. 

### Bugs this fixes

No reported bugs yet. This is to avoid potential issues from customers regarding Clean-Up configuration options not being respected.

### Workarounds, if any

N/A

### Risk

Low

### Performance impact

None.

### Root cause analysis

N/A

### How was the bug found?

N/A

### CODE REVIEW

**Comment by jinujoseph** [comment]
cc @olegtk

**Comment by sharwell** [comment]
I'm hoping that we can remove `CodeCleanupOptions` as well after #30039 is merged.

**Comment by heejaechang** [comment]
do we get it from somewhere different place? or completely removing the feature?

**Comment by jinujoseph** [comment]
@heejaechang UI is coming from editor team.

**Comment by sharwell** [comment]
📝 We need to make sure to remove `ICodeCleanupService.GetEnabledDiagnostics(OptionSet)` as part of this pull request.

**Pull request merged**
