### PR TITLE
Add a delegate compatibility check in GetMethodGroupDelegateConversion

### PR DESCRIPTION
**Pull request by makiuchi-d**
fixes: #51232

## Summary

Add a delegate compatibility check after getting a method group to delegate conversion in the method `GetMethodGroupDelegateConversion`.

### MethodBodyModelTests.MethodGroupToDelegate04
This is that I want to fix.

### OverloadResolutionTests.DelegateTypeParameterOverload
Test case from #51232.

### SemanticErrorTests.CS0123ERR_MethDelegateMismatch_01, 02
MInor changes in error messages.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=51233) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=51233) before we can accept your contribution.<br/><br/>:x: makiuchi-d [sign now](https://cla.dotnetfoundation.org/dotnet/roslyn?pullRequest=51233)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/roslyn?pullRequest=51233) it.</sub>

**Comment by bernd5** [comment]
Thank you for that fix, well done!

**Comment by AlekseyTs** [comment]
@makiuchi-d Please provide an explanation how the behavior described in #51232 is a violation of the language specification. And how the proposed change is in line with the specification.

**Comment by bernd5** [comment]
He wrote in his commit:

```
// Check the delegate compatibility (section 15.2).
//  * Every value parameter (no-ref or non-out) from the delegate type has an identity conversion or an implicit reference conversion to the corresponding parameter
//  * Every ref or out parameter from the delegate type has an identity conversion to the corresponding parameter
// On this `conversion`, the function applicability has been checked, but the delegate compatibility has not.
```
Which can be found [here](https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/spec/delegates.md#delegate-compatibility)


But this is not all. For ambiguity / overload resolution we have to respect

#### [Applicable function member](https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/spec/expressions.md#applicable-function-member)

>      for a value parameter or a parameter array, an **implicit conversion** (Implicit conversions) 
>      exists from the argument to the type of the corresponding parameter, or

The method group `A` has no implicit conversion to Action<byte> only to Action<int>, therefore it should be removed from the overload set.

Method group conversion is defined [here](https://github.com/dotnet/csharplang/blob/a3d67d141501101af9dbb9e8192ca8b4c717e316/spec/conversions.md#method-group-conversions).

**Comment by makiuchi-d** [comment]
I explained how this behavior violates the language specification in a [issue comment](https://github.com/dotnet/roslyn/issues/51232#issuecomment-780578549).

The problem is that the method `Conversions.GetMethodGroupDelegateConversion` returns an invalid conversion with no delegate compatibility.
This PR add a check the delegate compatibility in this method, and make it returns `Conversion.NoConversion` when it has no delegate compatibility.

**Comment by AlekseyTs** [comment]
> The problem is that the method Conversions.GetMethodGroupDelegateConversion returns an invalid conversion with no delegate compatibility.

The way I interpret the specification, the delegate compatibility is not a requirement for an implicit conversion to exist. I explained in more details in the issue.

**Comment by makiuchi-d** [comment]
Thank you, AlekseyTs.

I understood that `Conversions.GetMethodGroupDelegateConversion` is able to return the conversion with no delegate compatibility.
So this PR is unsuitable.

**Pull request closed without merging**
