### PR TITLE
Fixed a bug with Intellisense on Enum

### PR DESCRIPTION
**Pull request by Ashera138**
Fixed a bug where Intellisense was stripping square brackets from Enum on autocomplete. Issue: #28767

### CODE REVIEW

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
Needs a test :)  I recommend VisualBasicCompletionCommandHandlerTests as this will exercise the entire stack (including committing the item properly).

**Comment by Ashera138** [comment]
Alright, I've added a test. Let me know if anything else is needed! Thank you. 😄

**Comment by sharwell** [comment]
retest this please

**Comment by sharwell** [comment]
retest this please

**Comment by sharwell** [comment]
retest this please

**Comment by mavasani** [comment]
retest this please

**Comment by mavasani** [comment]
@Ashera138 Seems like the test you are adding is failing:

```
2018-09-19T18:29:43.4542567Z Errors Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll
2018-09-19T18:29:43.4543906Z     Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.CompletionDoesNotRemoveBracketsOnEnum(completionImplementation: Legacy) [FAIL]
2018-09-19T18:29:43.4544770Z Command: C:\Windows\ServiceProfiles\NetworkService\.nuget\packages\xunit.runner.console\2.4.1-pre.build.4059\tools\net452\xunit.console.x86.exe "F:\a\_work\4\s\Binaries\Debug\UnitTests\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll"  -xml "F:\a\_work\4\s\Binaries\Debug\UnitTests\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests\xUnitResults\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll.xml" -noshadow -verbose
2018-09-19T18:29:43.4545413Z xUnit output log: F:\a\_work\4\s\Binaries\Debug\Logs\Microsoft.CodeAnalysis.EditorFeatures2.UnitTests.dll.out.log
2018-09-19T18:29:43.4545758Z     Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.CompletionDoesNotRemoveBracketsOnEnum(completionImplementation: Legacy) [FAIL]
2018-09-19T18:29:43.4547909Z ================
```

Can you verify it works locally for you?

**Comment by Ashera138** [comment]
This test is working for me locally.

Here is the result of running Test.cmd:
Test.cmd results

Here is the result of running the new test by itself:
CompletionDoesNotRemoveBracketsonEnum test result

**Comment by mavasani** [comment]
@Ashera138 Thanks. I have re-queued the tests and will let you know if they fail again.

**Comment by mavasani** [comment]
@Ashera138 Test is still failing https://dnceng.visualstudio.com/public/_build/results?buildId=25426&view=ms.vss-test-web.test-result-details.

```
Assert.Equal() Failure\r\n ↓ (pos 0)\r\nExpected: [Enum]\r\nActual: End Class\r\n ↑ (pos 0)
Stack trace
   at 
Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_143_CompletionDoesNotRemoveBracketsOnEnum.MoveNext() in /_/src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb:line 2964
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

 I will try to checkout your branch locally and see whats going on...

**Comment by mavasani** [comment]
@Ashera138 Test is still failing https://dnceng.visualstudio.com/public/_build/results?buildId=25426&view=ms.vss-test-web.test-result-details

```

Assert.Equal() Failure\r\n ↓ (pos 0)\r\nExpected: [Enum]\r\nActual: End Class\r\n ↑ (pos 0)
Stack trace
   at Microsoft.CodeAnalysis.Editor.UnitTests.IntelliSense.VisualBasicCompletionCommandHandlerTests.VB$StateMachine_143_CompletionDoesNotRemoveBracketsOnEnum.MoveNext() in /_/src/EditorFeatures/Test2/IntelliSense/VisualBasicCompletionCommandHandlerTests.vb:line 2964
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by mavasani** [comment]
I see the same test failure locally as well. Following assert is failing: `Assert.Equal("[Enum]", state.GetLineTextFromCaretPosition().Trim())` as the text is "End Class". I did verify under the debugger that the text in the buffer is as expected:
```
{
                          Class C
                             Sub S
        [Enum]
    End Sub
                         End Class
                       }
```

**Comment by Ashera138** [comment]
Alright, thanks for checking it out. I'll take a look at it again and see what I can do.

**Comment by Ashera138** [comment]
Well roslyn-CI is passing, but now I'm getting windows_debug_vs_integration_prtest and windows_release_vs_integration_prtest failing with the same result:

```
Build step 'Execute Windows batch command' marked build as failure
13:35:44 [xUnit] [INFO] - Starting to record.
13:35:44 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
13:35:44 ERROR: Build step failed with exception
13:35:44 java.lang.NullPointerException
13:35:44 Build step 'Publish xUnit test result report' marked build as failure
13:35:44 [Current build status] check if current [FAILURE] is worse or equals then [ABORTED] and better or equals then [FAILURE]
13:35:44 Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
13:35:44 ERROR: [flexible-publish] Archive the artifacts (hudson.tasks.ArtifactArchiver@5c5bfdd2) aborted: no workspace for dotnet_roslyn/master/windows_release_vs-integration_prtest #4194
13:35:44 Build step 'Flexible publish' marked build as failure
13:35:44 [BFA] Scanning build for known causes...
13:35:44 [BFA] Found failure cause(s):
13:35:44 [BFA] Build step... marked build as failure from category Build
13:35:44 [BFA] Done. 0s
13:35:46 Setting status of 2d2cf63660689e80f63f0aea98aa5d61acf4f7b9 to FAILURE with url https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_release_vs-integration_prtest/4194/ and message: 'Build finished. '
13:35:46 Using context: windows_release_vs-integration_prtest
13:35:47 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for dotnet_roslyn/master/windows_release_vs-integration_prtest #4194
13:35:47 Finished: FAILURE
```

Any ideas on what I need to do to resolve this? Thanks for your patience. :)

**Comment by mavasani** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
retest windows_release_vs-integration_prtest please

**Comment by mavasani** [comment]
@Ashera138 Thanks, those seem to be some network related failures. I have requested re-execution of integration tests.

**Comment by jinujoseph** [comment]
test windows_debug_vs-integration_prtest

**Comment by mavasani** [comment]
retest windows_debug_vs-integration_prtest please

**Pull request merged**
