### PR TITLE
Remove unneeded app.config from test projects

### PR DESCRIPTION
**Pull request by davkean**
Since #f9b4d71a, tests inherit app.config if they don't specify one. Removed the ones that match the default behavior.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @dotnet/roslyn-compiler @dotnet/roslyn-interactive @dotnet/roslyn-ide

**Comment by davkean** [comment]
Here's the PR that caused projects to inherit the default: https://github.com/dotnet/roslyn/pull/8534

**Comment by davkean** [comment]
There's still app.configs left, will unify those in a followup.

**Comment by davkean** [comment]
@dotnet-bot test vsi please

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
