### PR TITLE
Add missing project references to Core deployment

### PR DESCRIPTION
**Pull request by tmat**
Might also fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1482793

### CODE REVIEW

**Comment by genlu** [comment]
We'd need both this and https://github.com/dotnet/roslyn/pull/59554, right?

**Review by genlu — APPROVED** [review]
I wonder if we should just add those dependencies to MS.CA.Remote.ServiceHub.csproj directly

**Comment by tmat** [comment]
> I wonder if we should just add those dependencies to MS.CA.Remote.ServiceHub.csproj directly

I don't think we should. The code in Remote.ServiceHub should not have direct dependencies on language specific features. It should imo be up to the "setup" projects to compose these together.

**Comment by tmat** [comment]
> We'd need both this and #59554, right?

Not sure. I don't think we actually need #59554, but we will see...

**Comment by genlu** [comment]
It appears the corehost leg is now passing

**Pull request merged**
