### PR TITLE
Update API suggestion template

### PR DESCRIPTION
**Pull request by Youssef1313**
Pulled the code out of the comment. I had opened a proposal and filled the code, and didn't notice it was commented.

### CODE REVIEW

**Comment by Youssef1313** [comment]
@333fred For a quick review.

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Ohhh, we changed the pipelines to not run for doc-only changes. That explains it.

**Comment by 333fred** [comment]
Thanks @Youssef1313!

**Pull request merged**
