### PR TITLE
Disable failing assertions until an issue is addressed with SemanticModel.GetEnclosingSymbol

### PR DESCRIPTION
**Pull request by gafter**
Includes unit tests for #1504.

@agocke @VSadov @AlekseyTs @jaredpar Please Review

### CODE REVIEW

**Comment by AlekseyTs** [comment]
I am not comfortable with this change, it disable verification completely rather than targeting specific API. Also, it is not clear why FailFast is replaced with an Assert.

**Comment by AlekseyTs** [comment]
Since the intent is to fix the issue proper in a couple of days, consider disabling failing tests rather than disabling the verification.

**Comment by gafter** [comment]
The tests represent actual scenarios that occur in ENC. Disabling the tests does not prevent the IDE from crashing.

**Comment by gafter** [comment]
@AlekseyTs The compiler is not supposed to contain FailFast. I know you like to add such to the compilers as a temporary measure to help diagnose issues by causing a crash in the customer code, but temporary measures must remain temporary. None of these assertions represent problems in the external behavior of the compiler or its APIs. They represent, at most, suboptimal performance. We do not need to crash the client due to possible performance improvements.

**Comment by gafter** [comment]
@AlekseyTs I've updated the PR to leave the assertions intact, and only slightly weaken the problematic one.

**Comment by AlekseyTs** [comment]
Unfortunately, these assertions do represent problems in the external behavior of the compiler or its APIs. Region analysis behaves incorrectly if invariants checked by the asserts are broken. Given that, I would prefer to keep them as FailFast, the code is debug only anyway.

**Comment by gafter** [comment]
@AlekseyTs Please provide a test illustrating the region analysis problem.

We cannot keep this as FailFast as the compiler is not supposed to crash the entire VM.

**Comment by gafter** [comment]
@agocke @VSadov @jaredpar Please Review

**Comment by AlekseyTs** [comment]
@gafter For an illustration, please dig through the history and see when the verification code was enabled, I believe the last time that happened, it was related to a fix, which addressed the failures that I was talking about.

**Pull request closed without merging**
