### PR TITLE
Fix building with non-Visual Studio 2015

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This fixes building the project with Visual Studio versions after 2015. The important caveat is that if you build with anything later than Dev14, you won't be able to run the bits you have in Dev14 since we're still picking up the SDK versions you're building with. That can be fixed once we move to the SDK NuGet packages.

Things to still fix before I merge this:

- [x] ServicesVisualStudioTest has a reference warning when opened with Visual Studio 2015 due to a hack I have there which still needs to be fixed.
- [x] Audit that there isn't any .vsixmanifest metadata that still needs to be updated.
- [x] Investigate a crash in ErrorListPackage when you F5 with these bits.

Review: @dotnet/roslyn-ide, @dotnet/roslyn-infrastructure, @dotnet/roslyn-interactive

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @KevinH-MS

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest prtest/win/dbg/eta. There was a timeout syncing from GitHub.

**Comment by jasonmalinowski** [comment]
Also FYI @jaredpar explicitly. I'll get the side-by-side fixes into this PR that @kuhlenh ran into.

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5443/
// Retest reason: Timeout cloning repo from GitHub. Retry the

**Comment by jaredpar** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
Actually change of plan; the easiest way to fix @kuhlenh's problems is beginning the migration to NuGet packages, and there's no reason to link these two PRs together at that point. I'll continue right to that work, but no reason to block this.

**Comment by jasonmalinowski** [comment]
And looking at the ErrorListPackage load failure this triggers in non-14.0:

my code does and doesn t work and i don t know why

The problem seems to be that we're still referencing Shell.14.0 and expecting some types to be exchange types, but I'm entirely unable to explain how our non-14.0 bits that I'm using to debug work then. It's still bad and something that needs investigation, but this at least unblocks stuff.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please.

**Pull request merged**
