### PR TITLE
Change the text for the newly added background analysis scope option

### PR DESCRIPTION
**Pull request by mavasani**
1. Make the strings sentence cased
2. Rename "Open Documents And Projects" to "Open documents" as per internal review.

### CODE REVIEW

**Comment by mavasani** [comment]
Documentation update PR: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6008

**Comment by davkean** [comment]
👍

**Comment by mavasani** [comment]
@sharwell Can you do a quick review as well? Trivial resource string changes...

**Comment by sharwell** [comment]
LGTM

**Pull request merged**
