### PR TITLE
Another thousand cleanup suggestions in IDE

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani @jasonmalinowski

**Comment by mavasani** [comment]
@CyrusNajmabadi Are you planning to push further cleanup commits or is this ready for review?

**Comment by CyrusNajmabadi** [comment]
@mavasani this is ready.

**Comment by mavasani** [comment]
@JoeRobich - can you please merge this PR? Seems that all tests have passed but roslyn-CI is incorrectly showing as `In progress`.

**Comment by JoeRobich** [comment]
AzDO reports all green (https://dev.azure.com/dnceng/public/_build/results?buildId=244239&view=logs&jobId=1402d8c5-7e47-5bf4-467f-73e45e01bcce) but GitHub hasn't updated. merging

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
