### PR TITLE
Fix significant wrong translation in CodeStyle.Resources.zh-Hans.xlf

### PR DESCRIPTION
**Pull request by huoyaoyuan**
This could be agreed by anyone who understands Chinese. I just used the correct translation from Traditional Chinese version.

### CODE REVIEW

**Comment by genlu** [comment]
The translation looks good to me. Tag @tmeschter to make sure this is how to fix LOC issues like this.

**Comment by tmeschter** [comment]
@janbaltus FYI, we have some feedback on a Chinese translation.

**Comment by genlu** [comment]
@huoyaoyuan Thanks for your contribution!

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed as suggested.

**Comment by genlu** [comment]
@tmeschter I'm merging this so @huoyaoyuan could get the credit for the fix.

**Pull request merged**
