### PR TITLE
Get CSharpSyntaxGenerator to run on coreclr

### PR DESCRIPTION
**Pull request by TyOverby**
@tannergooding What do I need to do in order to 

1. Verify that it still works correctly on Windows
2. Get it to run on Linux and OSX

### CODE REVIEW

**Comment by TyOverby** [comment]
Also why on earth is my project.lock.json 2k lines long?

**Comment by davkean** [comment]
These looks like real failures, you're pulling down NuGet packages that don't exist in our Azure store. @agocke What's the process for updating these? And can you write it up? :)

**Comment by agocke** [comment]
@davkean There are bigger problems here (NuGet transitive dependencies) -- let's just drop this PR for now.

**Comment by TyOverby** [comment]
Yep.  

@agocke, could you write up the two issues that we need fixed for this effort to make progress?  I understood the gist of what was happening, but probably not enough to effectively communicate it.

**Pull request closed without merging**
