### PR TITLE
Multi-target change cleanup

### PR DESCRIPTION
**Pull request by jaredpar**
Fixing a couple issues discovered since we merged the change to use multi-targeting. 

- Didn't properly enforce the use of UnitTestPortable. The distinction between UnitTest and UnitTestPortable is very small now and likely UnitTestPortable will be removed very soon. But for now it's still necessary and need to enforce it.
- Standardized on the portable ThrowingTraceListener. The desktop version was complicating our build for no good reason. 
- Changed pickiing of the test configuration file to use `$(TargetFramework)`. 

Note: once this change is merged using TDD.Net on the portable unit test projects should work again.

### CODE REVIEW

**Comment by jcouv** [comment]
Yay, TDD works on C# syntax, semantic, symbol and emit tests! 🎉

**Comment by KevinH-MS** [comment]
Out of curiosity, why was TDD broken?  The app.config selection?

**Comment by jaredpar** [comment]
@KevinH-MS the app.config had an invalid entry for the TraceListener section. Xunit apparently silently ignores this while TDD.Net issues an exception and fails the test.

**Comment by KevinH-MS** [comment]
Ack! 🤕  Good to know!

**Pull request merged**
