### PR TITLE
Update IDE Test Plan.md

### PR DESCRIPTION
**Pull request by dpoeschl**

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide for signoff.

**Comment by dpoeschl** [comment]
FYI @gafter

**Comment by Pilchie** [comment]
:LGTM:

@CyrusNajmabadi Can you follow-up with another PR that adds the new in 15.3 features:

* Generate Constructor
* Generate Equals, etc
* Generate Parameter checks
* Add parameter to constructor
* Conflict marker support,
* @kuhlenh what else am I missing here?

**Comment by Pilchie** [comment]
This test plan is for the compiler team to use when they implement new language features.  Your team should have similar test plan for how your features are impacted (E&C, EE, breakpoint resolution, Interactive, etc).

**Comment by tmat** [comment]
@Pilchie Sure, but since each IDE feature that's enabled in interactive window or .csx file has a test for it (or should have a test), it would make more sense for the dev who is adding IDE tests for the new feature to know to add a corresponding script test in the same test class. For example, keyword recommendation should provide "readonly ref" keywords on top-level, etc.

**Pull request merged**
