### PR TITLE
Revert "Remove IActiveStatementSpanTracker from the MEF catalog"

### PR DESCRIPTION
**Pull request by chsienki**
This reverts commit 31a883f9509ee389773505b97f6250d76b873af8.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Why reverting?

**Comment by chsienki** [comment]
We're seeing issues with tests in RPS. Theory is this PR, but we're testing.

**Comment by dibarbet** [comment]
FYI @sharwell

**Comment by sharwell** [comment]
@chsienki Where can I find the context for this? This PR was a prerequisite for my work this coming week.

**Comment by chsienki** [comment]
@sharwell We were seeing errors in EnC when running RPS tests. The specific failure was

```
06/14/2020 00:55:03 Coordinated Universal Time: Error : 1 :[devenv:3020] Unexpected exception: System.InvalidOperationException: Service of type 'Microsoft.CodeAnalysis.EditAndContinue.IActiveStatementSpanTrackerFactory' is required to accomplish the task but is not available from the workspace.
   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.CSharp.EditAndContinue.CSharpEditAndContinueAnalyzer.Factory.CreateLanguageService(HostLanguageServices languageServices)
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.<>c__DisplayClass4_1.<.ctor>b__2()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.Host.Mef.MefLanguageServices.GetService[TLanguageService]()
   at Microsoft.CodeAnalysis.EditAndContinue.EditAndContinueWorkspaceService.SupportsEditAndContinue(Project project)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.<CreateActiveStatementsMap>g__supportsEditAndContinue|21_0(DocumentId documentId)
   at System.Linq.ImmutableArrayExtensions.FirstOrDefault[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.CreateActiveStatementsMap(ImmutableArray`1 debugInfos)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.<GetBaseActiveStatementsAsync>d__20.MoveNext()

```

**Pull request merged**
