### PR TITLE
Fix NullReferenceException for MakeFieldReadonlyCodeFixProvider in Visual Basic.NET

### LINKED ISSUE #26850: NullReferenceException in VisualBasicMakeFieldReadonlyCodeFixProvider
**Repro steps**:
1. Create a VB console app.
2. Declare a variable without a type: `Dim age`
3. Press **Ctrl**+**.** or open the Quick Actions menu.

**Expected result**:
To be able to choose the 'Add readonly modifier' refactoring from the Quick Actions menu.

**Actual result**:
A yellow message bar appears saying that 'VisualBasicMakeFieldReadonlyCodeFixProvider' encountered an error and has been disabled. The stack trace is:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.MakeFieldReadonly.AbstractMakeFieldReadonlyCodeFixProvider`2.<>c.<MakeFieldReadonlyAsync>b__6_0(TSymbolSyntax g)
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at async Microsoft.CodeAnalysis.MakeFieldReadonly.AbstractMakeFieldReadonlyCodeFixProvider`2.MakeFieldReadonlyAsync[TSymbolSyntax,TFieldDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.MakeFieldReadonly.AbstractMakeFieldReadonlyCodeFixProvider`2.FixWithEditorAsync[TSymbolSyntax,TFieldDeclarationSyntax](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### PR DESCRIPTION
**Pull request by Scott-Caldwell**
A `NullReferenceException` was being thrown by the `AbstractMakeFieldReadonlyCodeFixProvider` when iterating over the variable declarators.

This fix resolves the issue by ensuring that the `FindAncestorOrSelf()` call can find the necessary node. Without the `getInnermostNodeForTie` argument, `FindNode()` was returning a node that was a layer out from the `TSymbolSyntax`-type node, so the `FindAncestorOrSelf()` call was unable to find the correct node. `getInnermostNodeForTie` ensures that the inner node, which is of type `TSymbolSyntax`, is returned and subsequently found by `FindAncestorOrSelf()`.

Fixes #26850.

### CODE REVIEW

**Comment by Scott-Caldwell** [comment]
I knew I was forgetting something... Thanks for the reminder and for being so helpful! I'll be sure to add a test when I get a chance

**Comment by sharwell** [comment]
Oh, right! I was mistaken on the type of test to use but you figured it out and now I see 😄

**Comment by mavasani** [comment]
I believe the correct long term fix here is to bail out in presence of errors, similar to what we do [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs,84d49ee32e6c739a) and [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.Features/RemoveUnusedMembers/AbstractRemoveUnusedMembersDiagnosticAnalyzer.cs,295) (former is for semantic errors and later for syntax errors).

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/30536 to track my request.

**Pull request merged**
