### PR TITLE
Allow publicsign true and delaysign false

### PR DESCRIPTION
**Pull request by agocke**
Forgot that delaysign is three state

/cc @VSadov @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by agocke** [comment]
test prtest/win/dbg/unit32 please

**Comment by agocke** [comment]
test prtest/lin/dbg/unit32 please

**Comment by agocke** [comment]
test this please

**Comment by agocke** [comment]
test prtest/win/dbg/unit32 please

**Pull request merged**
