### PR TITLE
Add support for IIsTypeOperation to control flow graph

### PR DESCRIPTION
**Pull request by chborl**

### CODE REVIEW

**Comment by 333fred** [comment]
@chborl test failures appear legitimate.

**Comment by chborl** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by chborl** [comment]
@AlekseyTs , @jaredpar , @mavasani for review.

**Pull request merged**
