### PR TITLE
UsePatternCombinator: Fix wrong target equivalence comparison.

### LINKED ISSUE #51691: False positive IDE0078
I don't see how this can be written by using pattern matching. And the suggested codefix is invalid.

image

Another similar case:

image

Also:

image

### LINKED ISSUE #51693: IDE0078 codefix produces incorrect code
image

The fixed code should be `type is INamedSymbol { EnumUnderlyingType: not null } namedTypeSymbol`

**Note:** I think this can change semantics for overridden equality operators.

### LINKED ISSUE #52397: IDE0078 refactoring "loses" a variable
**Version Used**: 

Microsoft Visual Studio Community 2019 Version 16.9.3

**Steps to Reproduce**:

1. Create project with a class inhering another class

2. In subclassed code, create 'if' referring to local variable/property and one from the base class, e.g.:

    if ((CipherMode == CipherMode.CBC) && (IV != null)) {
        return;
    }

3. Use quick action for 'Use pattern matching'

**Expected Behavior**:

    if ((CipherMode is CipherMode.CBC) && (IV is not null)) {
        return;
    }

**Actual Behavior**:

    if (IV is CipherMode.CBC and not null) {
        return;
    }

This is not an equivalent refactoring as local variable/property is not even checked and inherited property is used for both comparisons.

Example project attached.
[TestCS0078.zip](https://github.com/dotnet/roslyn/files/6253152/TestCS0078.zip)

### LINKED ISSUE #52573: Bad 'use pattern matching' suggestion is confusing two separate variables
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bad-use-pattern-matching-suggestion-is/1393465)._

---
**Repro steps:**
1. Paste the following into a C# class:
```
private static bool IsS(char[] ch, int count)
{
    return count == 1 && ch[0] == 'S';
}
```
2. Set cursor on the return line and invoke the lightbulb menu 
3. Select the Use pattern matching suggestion

**Expected:**
Should recommend code that compiles and has the same semantics.

**Actual:**
The line of code is changed to
```
    return ch[0] is 1 and 'S';
```
which is not semantically the same (not comparing count anymore) and also gets a compile error because a char cannot pattern match to an int.

This is especially a pain because our team has turned on this analyzer rule to a high priority, and now we're getting squiggles for a line of code but the code fix doesn't work.

---
#### Feedback Bot on 4/8/2021, 00:39 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

### PR DESCRIPTION
**Pull request by MaStr11**
Fixes #52397
Fixes #51691 
Fixes  #51693 
Fixes #52573

~Also resolves #51693, but @alrz mentioned another solution in https://github.com/dotnet/roslyn/issues/51693#issuecomment-803296746, so I would not close it until a new issue is created.~

### CODE REVIEW

**Comment by MaStr11** [comment]
> Can you please check if this fixes the cases

Looks like it should. I will add some tests later.

**Comment by MaStr11** [comment]
I added tests for #51693 and #51691. All new tests are triggering the analyzer/code fix today and produce invalid code.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by MaStr11** [comment]
@CyrusNajmabadi Should #51693 also be closed by this? This PR solves the problem, but @alrz wanted to fix it by merging two existing patterns into one. See https://github.com/dotnet/roslyn/issues/51693#issuecomment-803296746

**Comment by Youssef1313** [comment]
A new issue to add to the list :smile:

#52573

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Should #51693 also be closed by this? 

Yes.  We should close it as no longer producing incorrect code.  If we want it to produce better code, we can open a new feature request for that.

**Comment by MaStr11** [comment]
>A new issue to add to the list #52573

Confirmed. @CyrusNajmabadi should I push the test, that confirms #52573 is fixed (I ran it locally and can confirm it's fixed). I don't see the point in repeating the same problem in x variations.

**Comment by CyrusNajmabadi** [comment]
> Confirmed. @CyrusNajmabadi should I push the test, that confirms #52573 is fixed

Sure.

**Comment by MaStr11** [comment]
I pushed. *Auto merge* is turned off therefore.

**Pull request merged**
