### PR TITLE
Ignore

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit32 please.

**Comment by AlekseyTs** [comment]
Test prtest/win/dbg/unit32 please

**Comment by pdelvo** [comment]
I think the problem here is that the test creates a Compilation and asks the semantic model after doing that and not white running during the compilation in an analyzer. Could this be the problem?

**Comment by AlekseyTs** [comment]
It is possible. Or some other change fixed the problem, unless you are still able to reproduce it.

**Pull request closed without merging**
