### PR TITLE
More runtime specifications

### PR DESCRIPTION
**Pull request by Pilchie**

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-infrastructure and @jasonmalinowski.  Seems there a few more of these in master.

**Comment by davkean** [comment]
ETA looks like a real failure.

**Comment by Pilchie** [comment]
The failure is:

`C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(83,5): error : Couldn't find the required information in the lock file. Make sure you have .NETFramework,Version=v4.6/win7- mentioned in your targets. [d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\src\Test\Performance\Fixture\Performance-Fixture.csproj]`

Which is odd, because the change includes removing `win-` from `src/Test/Performance/Fixture/project.json`.  @jasonmalinowski any ideas?

**Comment by Pilchie** [comment]
Nevermind.  The issue is that for RTM machines PlatformTarget must be explicitly set to AnyCPU.  Fixing.

**Comment by jasonmalinowski** [comment]
:+1:. Do we need this in stabilization? Or alternatively, why is this that not happening there?

**Comment by Pilchie** [comment]
Not needed because these files were only added in master.

**Pull request merged**
