### PR TITLE
Allow contextual modifiers in any order in type declarations

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
LMK when you woudl like a review.

**Comment by alrz** [comment]
Possible related issue: https://github.com/dotnet/roslyn/issues/22439

**Comment by alrz** [comment]
@jcouv What is the state for this change? I think it would be a nice addition beside non-void partials.

**Comment by jcouv** [comment]
I'm not sure about the status. @agocke Is this a PR you plan to push forward despite your role change?

**Comment by agocke** [comment]
@jcouv Nope, turns out it wasn't necessary for records. Anyone else is free to pick it up though -- I still think it's a good change.

**Comment by alrz** [comment]
I think with the possibility of `partial record` and `partial class record` we finally got to the point that we need to relax this. 

Should I dust this off now and make a PR or wait for the record changes?

**Pull request closed without merging**
