### PR TITLE
Fix SHAs in project.lock.json files

### PR DESCRIPTION
**Pull request by tmat**
Not sure what happened, maybe nuget version mismatch?

### CODE REVIEW

**Comment by tmat** [comment]
@davkean @jasonmalinowski @Pilchie

**Comment by Pilchie** [comment]
:+1: from me.

Will let @davkean decide about `stabilization` versus `master`.

**Comment by jasonmalinowski** [comment]
@tmat, any chance you mixed up feeds? Otherwise @emgarten did something change on what you define to be in the hash?

**Comment by emgarten** [comment]
Hashes should be the same. They are taken from the hash file in the packages folder.

**Comment by tmat** [comment]
I am pretty sure i used Restore.cmd when I was updating the files and didn't change any config.

**Comment by tmat** [comment]
OK, I know what happened. Just verified the following steps:
1) delete nuget package dir
2) restore with nuget version 3.4.0.776
3) revert updated project.lock.json files
4) restore with nuget version 3.4.0.665 (the one currently in master)

This restore updates the SHAs.

**Comment by davkean** [comment]
@emgarten Is this expected I thought the hash was based on pack time? Or at least that's what I've been told a number of times.

**Comment by tmat** [comment]
Actually, never mind. I messed up :( Still looking.

**Comment by tmat** [comment]
I can't repro it anymore :(

**Comment by jasonmalinowski** [comment]
Did you keep your .nuget package dir? Perhaps you had some broken/bad package?

**Comment by tmat** [comment]
@davkean @jasonmalinowski So nuge takes exactly what's in System.Reflection.Metadata.1.2.0.nupkg.sha512 no questions asked. I overwrote the file with random numbers and the numbers ended up in project.lock.json.

**Comment by emgarten** [comment]
@tmat that is expected, NuGet writes out the hash after downloading and extracting the package to the global folder. Fully rehashing all packages on each restore would be costly.

Note that nuget.org allows editing packages on the web site which then updates some of the nuspec fields and changes the hash. It's possible you got into a situation where you had a slightly different copy of the same package locally that was causing a different hash.

**Comment by davkean** [comment]
Just to add another person to the thread, @ericstjohn did you upgrade System.Reflection.Metadata, 1.2.0 in place on nuget.org?

**Comment by ericstj** [comment]
No, but there were a few builds overwriting on myget.  Only the "official" one was put on nuget.org.

**Comment by tmat** [comment]
That could have been it. We fetch from both myget and nuget. Why are they being overwritten? Can it be avoided?

**Comment by ericstj** [comment]
It was only for a couple builds and I corrected it.  We had ~2-3 builds producing a stable package.  Once we had final I made sure to overwrite that one on myget and push to nuget.

**Pull request merged**
