### PR TITLE
Remove unused file

### PR DESCRIPTION
**Pull request by jaredpar**
Remove a file that is not used in our build.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure

**Comment by sharwell** [comment]
:memo: By "not used in the build" I am assuming this means the file exists on disk but isn't part of any project, which is a stronger condition than simply being unused code. :smile:

**Comment by jaredpar** [comment]
Yep.  It used to be used but during some refactoring into corefx we stopped using the file in any project and failed to delete it.

**Comment by jaredpar** [comment]
> Not sure why this is tagged for infrastructure

It was a long day.

**Pull request merged**
