### PR TITLE
Report errors for modifiers that are not valid on fixed buffers.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Addresses DevDiv 1171076.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - Fixes DevDiv 1171076
- Customer scenario - Roslyn doesn’t report an error when ```readonly``` modifier is used on a fixed buffer. As a result an invalid IL is emitted for an access to members of the fixed buffer, causing access violation exception thrown at runtime. According to language spec,  ```readonly``` modifier is not a valid modifier for a fixed buffer declaration.   
- Fix description - Report errors for modifiers that are not valid on fixed buffers.
- Testing done - unit-tests.

@jaredpar FYI

**Comment by gafter** [comment]
:+1:

**Comment by VSadov** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved 6/8 by ML Shiproom.

**Pull request merged**
