### PR TITLE
Run naming rules on closed files.

### LINKED ISSUE #9712: Provide a way for built-in analyzers to run on closed files.
**New General Issue**

We recently set all built-in IDE analyzers to not run on closed files. Let's use this issue to track adding the ability to re-enable running on closed files for built-in analyzers.

**Old Specific Issue**

**Steps to Reproduce**:
1. Write a naming style rule, and set the enforcement to warning
2. Write something that violates the rule
3. Close the file

**Expected Behavior**:
Error list shows the violation

**Actual Behavior**:
Error list is cleared shortly after closing the file.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #9712

### CODE REVIEW

**Comment by dpoeschl** [comment]
FYI @mavasani

**Comment by mavasani** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by Pilchie** [comment]
Retesting since results are a little old, but let's try to get this merged.

@dotnet-bot retest this please.

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
@dotnet-bot retest this please

**Comment by rchande** [comment]
retest this please

**Comment by rchande** [comment]
Failure was inline peek, seems unrelated.

**Pull request merged**
