### PR TITLE
Report CS0513 for abstract declaration

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@amcasey, @kevinh-ms, @tmat, @ManishJayaswal

**Comment by tmat** [comment]
I'd rather avoid reusing the existing error message:

```error CS0513: 'M()' is abstract but it is contained in non-abstract class 'Script'```

The user didn't declare class 'Script' anywhere. It's an implementation detail that top-level methods are in class. 

Instead we should report something like 

```Script methods can't be abstract```

**Comment by tmat** [comment]
Also, could you look into other modifiers? For example:
```C#
> virtual void Foo()
. {
.     Console.WriteLine();
. }
> (1,14): error CS0621: 'Foo()': virtual or abstract members cannot be private
```

**Comment by tmat** [comment]
```C#
> public virtual void Foo()
. {
.     Console.WriteLine();
. }
(1,21): error CS0549: 'Foo()' is a new virtual member in sealed class 'Submission#2'
```

**Comment by amcasey** [comment]
:+1:

**Comment by amcasey** [comment]
I think a new error message would be nice, but I can live with the current text.  If we do use a new code/message, I think we should say "top-level", rather than "script".

**Comment by cston** [comment]
@dotnet-bot retest this please

**Pull request merged**
