### PR TITLE
Annotate implementations of IArrayTypeSymbol

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by sharwell** [comment]
@333fred is this still blocked?

**Comment by sharwell** [comment]
@dotnet/roslyn-compiler for review

**Comment by 333fred** [comment]
>                 return _elementTypeWithAnnotations.Type;

When `TypeWithAnnotations` is annotated, this is going to cause a warning. Perhaps we should be validating `_elementTypeWithAnnotations.HasType` on input? Probably not appropriate to fix in this PR, but consider filing a follow up issue.

---
Refers to: src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs:215 in 1142e4a. [](commit_id = 1142e4a1fac11e584c76b0c8234c8dfb1f282095, deletion_comment = False)

**Comment by 333fred** [comment]
>                 return _elementTypeWithAnnotations.Type;

Oh wait, we already do this. Never mind me.

---
In reply to: [572300945](https://github.com/dotnet/roslyn/pull/39187#issuecomment-572300945) [](ancestors = 572300945)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs:215 in 1142e4a. [](commit_id = 1142e4a1fac11e584c76b0c8234c8dfb1f282095, deletion_comment = False)

**Comment by jcouv** [comment]
>         private readonly NamedTypeSymbol _baseType;

I see that `_baseType` is compared with `null` in this file (`GetUnificationUseSiteDiagnosticRecursive`). Probably should be nullable

---
Refers to: src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs:22 in 1142e4a. [](commit_id = 1142e4a1fac11e584c76b0c8234c8dfb1f282095, deletion_comment = False)

**Comment by cston** [comment]
>         private readonly NamedTypeSymbol _baseType;

The constructor asserts the value is not `null`.

---
In reply to: [572302289](https://github.com/dotnet/roslyn/pull/39187#issuecomment-572302289) [](ancestors = 572302289)

---
Refers to: src/Compilers/CSharp/Portable/Symbols/ArrayTypeSymbol.cs:22 in 1142e4a. [](commit_id = 1142e4a1fac11e584c76b0c8234c8dfb1f282095, deletion_comment = False)

**Pull request merged**
