### PR TITLE
Remove interfaces used for temporary prototype

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
These interfaces are imposing a maintenance tax.  They're also making it difficult ot refactor more of the system to be async and to use the new Dev17 Find-Refs window.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @mavasani

**Comment by mavasani** [comment]
Also tagging @srivatsn - Cyrus had a chat with me and we agreed that we should remove these internal interfaces for now and in future when we get to resurrecting the ExternalDependencies plugin, we should move to the new FindRef APIs.

**Comment by srivatsn** [comment]
Ok

**Comment by CyrusNajmabadi** [comment]
Yup.  I'd be happy to reintroduce APIs like this in the future.  In a nice clean async manner.

**Pull request merged**
