### PR TITLE
Skip failing C# REPL integration tests.

### PR DESCRIPTION
**Pull request by JoeRobich**
After CI image was updated with 16.4 Preview 5 some REPL tests started
failing consistently. https://github.com/dotnet/roslyn/issues/40160

### CODE REVIEW

**Comment by tmat** [comment]
It's very likely that this is caused by the changes in command system. The IW [command filters](https://github.com/dotnet/interactive-window/blob/master/src/Microsoft.VisualStudio.VsInteractiveWindow/VsInteractiveWindowCommandFilter.cs) need to be updated.
@ivanbasov @jinujoseph

**Comment by jasonmalinowski** [comment]
@tmat Does this indicate the product is actually busted in 16.4?

**Comment by tmat** [comment]
Yes.

**Comment by sharwell** [comment]
@tmat do you have a link to information about the change?

**Comment by tmat** [comment]
The IW command filter chain depends on certain [ordering](https://github.com/dotnet/interactive-window/blob/master/src/Microsoft.VisualStudio.VsInteractiveWindow/VsInteractiveWindowCommandFilter.cs#L23) of language service filters related to editor filters. That ordering changed - some command handling was moved down to the editor. 

The IW command filtering needs to be changed accordingly. This change might however break Python and Node.js Interactive Windows unless they also made the same change we made in Roslyn. To address that we need to either fix Python and Node.js as well, or maintain both models and provide a switch.

**Pull request merged**
