### PR TITLE
Add csi.exe.config to compilers vsix

### LINKED ISSUE #16017: csi.exe.config is missing from setup authoring
Calling csi on a recent VS build fails with:
```System.IO.FileLoadException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

I checked and we’re deploying version 4.0.2.0.
https://github.com/dotnet/roslyn/blob/master/src/Setup/DevDivVsix/CompilersPackage/Microsoft.CodeAnalysis.Compilers.swr#L15

### PR DESCRIPTION
**Pull request by OmarTawfik**
Fixes #16017
@dotnet/roslyn-compiler  @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by TyOverby** [comment]
LGTM

**Comment by jaredpar** [comment]
This file is missing from [Microsoft.Net.Compilers.nuspec](https://github.com/dotnet/roslyn/blob/master/src/NuGet/Microsoft.Net.Compilers.nuspec).  Doesn't it need to be added there too @tmat?

**Comment by tmat** [comment]
@jaredpar Yes, it does.

**Comment by OmarTawfik** [comment]
@jaredpar fixed. Can I get another sign off?

**Comment by OmarTawfik** [comment]
@ManishJayaswal can we please get approval for ASK MODE?

**Comment by tannergooding** [comment]
Tagging @srivatsn for ask mode approval since @ManishJayaswal is out. Tagging @KevinH-MS for IntEx approval, since @ManishJayaswal is out.

@OmarTawfik, could you fill in the standard ask mode template (see below). I believe we also need a VSO bug to track this.

GitHub Bug:
GitHub PR:
D15Rel PR:
 
**Customer and Scenario Info**
Who is impacted by this bug:
What is the customer scenario and impact of the bug:
What is the workaround:
How was the bug found:
If this fix is for a regression - what had regressed, when was the regression introduced, and why was the regression originally missed:
​What is a Customer Rea​dy description of change should we need to document this:
 
**Bug Fix Details**
Overview of the fix:
Which VS products, SKUs, or components need the fix:
What branch does the fix go into:
What feature areas are impacted by the fix:
What is the risk of the code change:
Does this change have impact on anything else (e.g. setup, perf, stress, ux, visual freeze, go live, breaking change, samples, etc):
How is this fix rolling forward in the next major release / sprintly train (e.g. Dev15):
 
**​Validation**
What testing/validation was done on the fix, and what were the results:
Which engineering partner teams have signed off on the fix:
Who code reviewed the fix:
 
**Additional information during Divisional Escrow Mode**
Which Engineering DIRECTOR is accountable for the code change and quality:
What are you doing to ensure that this bug does not happen again:
Which part of the D15 Escrow Bar does this fall under?:

**Comment by OmarTawfik** [comment]
@tannergooding I believe VSO bug is not required for GitHub ask mode?
@srivatsn here is the template:

GitHub Bug: #16017
GitHub PR: #16018

**Customer and Scenario Info**
Who is impacted by this bug: customers callind csi from command line.
What is the customer scenario and impact of the bug: call will fail with an assembly load error.
What is the workaround: no workaround so far.
How was the bug found: manual testing
If this fix is for a regression - what had regressed, when was the regression introduced, and why was the regression originally missed: csi used to work before. It is setup authoring error that missed shipping on of the files.
​What is a Customer Rea​dy description of change should we need to document this: setup is now complete, and csi will have its required dependencies to run.

Bug Fix Details
Overview of the fix: Adding csi.exe.config to setup authoring.
Which VS products, SKUs, or components need the fix: all SKUs shipping Roslyn compilers.
What branch does the fix go into: lab/ml.
What feature areas are impacted by the fix: C# scripting.
What is the risk of the code change: none.
Does this change have impact on anything else (e.g. setup, perf, stress, ux, visual freeze, go live, breaking change, samples, etc): setup.
How is this fix rolling forward in the next major release / sprintly train (e.g. Dev15): RC3

​Validation
What testing/validation was done on the fix, and what were the results: manual testing of setup authoring.
Which engineering partner teams have signed off on the fix: @dotnet/roslyn-compiler 
Who code reviewed the fix: @jaredpar @tmat @TyOverby 

Additional information during Divisional Escrow Mode
Which Engineering DIRECTOR is accountable for the code change and quality: @MattGertz 
What are you doing to ensure that this bug does not happen again: #15954 is tracking this.
Which part of the D15 Escrow Bar does this fall under?: RC3 ASK MODE

**Comment by tmat** [comment]
👍

**Comment by KevinH-MS** [comment]
LGTM (approving in @ManishJayaswal 's stead)

**Pull request merged**
