### PR TITLE
Syntax gen nits

### PR DESCRIPTION
**Pull request by SamB**
Just a couple of non-code changes to make working with CSharpSyntaxGenerator and/or VisualBasicSyntaxGenerator ever-so-slightly more pleasant.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler

**Comment by SamB** [comment]
Er, um, could I get some feedback about this at some point, please?

N.B. that the only change that would have any impact on what ships is commit 86f0bea..., "Fix an error found in Syntax.xml using the new schema ...", and that change is to include a documentation comment in **Microsoft.CodeAnalysis.CSharp** that was presumably meant to be shipped all along.  Not exactly earth-shattering, I hope?

(I didn't even actually change any of the code for CSharpSyntaxGenerator, just moved some of the files.  Though I now suspect that it might be possible, and good, to use Model.cs from BoundTreeGenerator instead, since that's even easier to navigate, and would reduce code duplication besides.)

**Comment by agocke** [comment]
:+1: To moving the base type information for the generator to a `Model` subdirectory and :+1: to Moving the doc comment to the syntax node.

:-1: To the editor additions and adding XML schema stuff. XML is bad enough without schemas.

**Comment by TyOverby** [comment]
Agree with Andy.  The fix in Syntax.xml is a nice catch though.

**Comment by SamB** [comment]
@agocke: Er, um, it's not really an XML Schema (shudder).  It's just a (Relax NG Compact) schema that happens to describe some XML, in this case that understood by CSharpSyntaxGenerator.  It can be used to get such nice things as squiggles for mistakes and intellisense-style completion.

Unfortunately, it doesn't look like VS's XML editor is nearly as flexible as Roslyn's language service -- I didn't even see anything that would facilitate adding squiggles, so the only way I'm aware of to actually *get* that support is to use James Clark's excellent `nxml-mode` (which he describes at <http://www.thaiopensource.com/nxml-mode/>, though it comes with GNU Emacs now).

I tried briefly to do this using XML Schema despite its scary overwhelming complexity, but discovered that, despite the creeping featuritus, XML Schema doesn't really support interleaving with any generality and thus couldn't model the inheritance used in CSharpSyntaxGenerator's data model without forcing child elements to appear in a specific order.  In contrast, I think Relax NG has three content-level operators it didn't steal from regular expressions: the "element" and "attribute" operators (kind of obvious in a language for schemas describing the structures of XML documents), and the "interleave" operator.

So, not having the schema won't do any actual *harm*, and I guess the chances of people just happening to open the C# `Syntax.xml` in Emacs are pretty remote, so the schema *could* easily bitrot. (Btw, speaking of bitrot, did you guys take note of those attributes that are processed but don't actually appear in the file?) Though, I'm really not sure that'd be such a big issue, anyone editing the C# `Syntax.xml` in Emacs who might encounter such bitrot could easily just:
  1. [Learn Relax NG Compact](http://www.relaxng.org/compact-tutorial-20030326.html) and update the schema.
  2. Deactivate `rng-validation-mode`, or tell it to use the "vacuous" schema, with any of various degrees of automation.
  3. I doubt many Emacs users would get past 1 & 2, but there's also obviously the option of using some other editor.

Or, the short version: making that schema is how I noticed that the comment was misplaced.

**On the other hand**, without the `.editorconfig` change, **VS goes crazy trying to reformat things** for 4-space indents in `.xml` and `.xsd` files (which you already have three of), due to the `[*]` section at the beginning of the file.

**Comment by davkean** [comment]
@SamB What's your plans with this? Sounds like there's push back on the schema - but :+1: to everything else. Do you plans on updating the PR?

**Comment by SamB** [comment]
@davkean: Okay, I've rebased this and left off the schema.

[I might try resubmitting it at some point without using the word "schema" and see if that sounds less alarming to people, though ;-P]

**Comment by davkean** [comment]
Thanks @SamB 

@dotnet/roslyn-compiler please re-review.
@dotnet-bot test eta please

**Comment by TyOverby** [comment]
LGTM

**Comment by davkean** [comment]
:+1:

**Comment by davkean** [comment]
Thanks for the contribution!

**Pull request merged**
