### PR TITLE
Use Arcade x-plat resx generator

### PR DESCRIPTION
**Pull request by tmat**
The Arcade resx generator generates .cs file with resource string properties into an `obj` directory, removing the need for `*.Designer.cs` files checked into the repo. This approach removes clutter from project files and from the repo, avoids additional conflicts in designer files when merging resx changes, allows updating resx files outside of VS and makes it easier to link resx files through shared projects.

Arcade resx generator is applied on `EmbeddedResource` items that have `.resx` extension and `GenerateSource="true"` metadata.

This PR also removes resx resources from test projects. They should embed the desired text/binary files directly or use strings.

### CODE REVIEW

**Comment by tmat** [comment]
@agocke @jaredpar @jasonmalinowski @JoeRobich @dotnet/roslyn-compiler @dotnet/roslyn-ide PTAL

**Comment by alrz** [comment]
>removing the need for *.Designer.cs

Does this handle xlf somehow? or they're here to stay?

**Comment by tmat** [comment]
@alrz It does not change .xlf file handling.

**Comment by tmat** [comment]
@agocke Ping

**Comment by tmat** [comment]
@agocke Those were used in test projects and not localized. So no reason to actually use resx files for that.

**Comment by alrz** [comment]
Since roslyn is now also multitargeted, I get CS0102 (duplicated definitions)

The file is generated both in `/Debug/netcoreapp3.1` and `/Debug/netstandard2.0`

How do we resolve this?

**Comment by alrz** [comment]
Looks like .Designer.cs file is still auto generated, could we disable that?

**Comment by tmat** [comment]
@alrz For what resx file is it generated? When is it generated?

**Comment by alrz** [comment]
nevermind, apparently Rider runs the generator upon manual edit. VS doesn't do such a thing.

**Comment by tmat** [comment]
Seems like a bug in Rider. MSBuild has a mechanism that allows to customize the generator that should be used for a given file. Our infrastructure uses this extension point to plug in the new resx generator (that doesn't generate .Designer.cs).

**Pull request merged**
