### PR TITLE
Moved the last of the open projects to NuGet

### PR DESCRIPTION
**Pull request by davkean**
Moved the last VS dependencies from binary refs -> NuGet

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-infrastructure @jasonmalinowski @tmat

**Comment by davkean** [comment]
test this please

**Comment by jasonmalinowski** [comment]
:+1:. @dotnet-bot, test vsi please. Some of those assemblies in the EmbedInteropTypes was in the NuGet package that I shamelessly copied that from, and I don't recall why I removed them. The number of similar sounding assemblies might have meant I removed things unnecessarily though.

**Comment by davkean** [comment]
@jasonmalinowski It looks like we mixing embedding here - sometimes we embed shell.interop 10 & 11, sometimes we didn't. Given that I'm running into issues build because we're embedding, them I'm going to undo my changes, and always use the real dll. We ship it anyway.

**Comment by davkean** [comment]
@dotnet-bot test vsi please

**Comment by jasonmalinowski** [comment]
Yeah, if embedding is causing issues then that's why I didn't do that. I probably should have documented why things were or weren't in that list. I did consider making the lists separate for different project files but that just seemed like it was going to be a maintenance nightmare.

**Comment by davkean** [comment]
@jasonmalinowski We should just across the board - if VS ships the dll anyway, you may as well not embed the types.

**Comment by davkean** [comment]
test vsi please

**Pull request merged**
