### PR TITLE
When showing completion for conditional access, walk up the tree to f…

### LINKED ISSUE #4750: Completion should trigger on . after ? in a null-conditional access expression with an implicit With block receiver
In the example below completion should pop up after ?. on line 1 (before Length); today it does not.

``` VB.NET
Module Module1
    Sub Main()
        Dim s As String

        With s
1:         Console.WriteLine(If(?.Length, -1))
            Console.WriteLine()
        End With

        Dim dict = New Dictionary(Of String, Object) From {{"Name", "Anthony"}}

        With dict
            Console.WriteLine(?!Name)
        End With
    End Sub
End Module
```

### PR DESCRIPTION
**Pull request by rchande**
…ind a parent With block

Fixes #4750

cc: @balajikris @brettfo @CyrusNajmabadi @dpoeschl @DustinCampbell @jasonmalinowski @Pilchie

### CODE REVIEW

**Comment by Eyas** [comment]
I think you meant #4750 ?

**Comment by brettfo** [comment]
@Eyas: I think you're right.

@rchande: :shipit:

**Comment by rchande** [comment]
Thanks @Eyas, I rebased to fix the workitem numbers.

Ping?

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
