### PR TITLE
Upgrade NuPkg references

### PR DESCRIPTION
**Pull request by jaredpar**
Move several NuPkg forward to deal with internal process issues

This is a follow up PR for #63765. This includes changes to VS packages that haven't been fully inserted yet. Once they're inserted this PR can be unblocked and merged.

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Comment by JoeRobich** [comment]
So from some internal discussion, I believe we want to retarget this PR at main-vs-deps, since the version of Microsoft.VisualStudio.Cache has not been inserted into VS yet.

**Comment by jaredpar** [comment]
@JoeRobich 

To be clear, there is no urgency to get this in. The issue was in test code so I suppressed it. At the same time I had the fix in hand so wanted to put up a PR. It's perfectly fine from my perspective for this to sit here for 1-2 weeks and then get merged in. 

Basically don't create `main-vs-deps`  _just_ for this 😄

**Comment by JoeRobich** [comment]
> Basically don't create main-vs-deps just for this 😄

@jaredpar I wish it did not already exit =p

**Comment by jaredpar** [comment]
Well if we've already done the deed, may as well pile on

**Pull request closed without merging**
