### PR TITLE
Properly round trip enum values in the settings manager code.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide Plz review, this is a DDRIT issue.

**Comment by rchande** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Pull request merged**
