### PR TITLE
Merge 'dotnet/main' into ParamsCollections

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Need a sign-off on a merge 'main' into ParamsCollections. This a fast-forward merge.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Need a sign-off on a merge from 'main' into ParamsCollections. This is a fast-forward merge.

**Comment by jjonescz** [comment]
> This is a fast-forward merge.

I see some tests updated in https://github.com/dotnet/roslyn/pull/72042/commits/25414ee7363b7f925f8df35ee39e2e0d339d91ad though - are they part of fast-forward merge?

**Comment by AlekseyTs** [comment]
One test was adjusted and one new test was added. The change in behavior is expected in the feature branch.

**Review by jcouv — APPROVED** [review]

**Review by 333fred — APPROVED** [review]

**Pull request merged**
