### PR TITLE
Add per language options to disable GoToDef and GoToImpl.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/15958

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide 

F# wants this so that we don't offer features in the UI that they don't support yet.

**Comment by CyrusNajmabadi** [comment]
@dungpa You would use these by setting the option values to 'false' in your Package initialization routine.

**Comment by dungpa** [comment]
Great, thanks. Please let me know when the new NuGet package is out.

**Comment by CyrusNajmabadi** [comment]
@dungpa can you use https://dotnet.myget.org/F/roslyn-master-nightly/api/v3/index.json

?

**Comment by CyrusNajmabadi** [comment]
That feed is updated nightly

**Comment by jasonmalinowski** [comment]
Why wouldn't we just condition this on whether they've defined an IGoToImplementation service?

**Comment by CyrusNajmabadi** [comment]
Curse you and your sensible thought process!

**Comment by CyrusNajmabadi** [comment]
I'll make that change. Thanks!

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Can you look again?
also @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz @srivatsn This is needed for F# to disable features they don't support.

**Pull request merged**
