### PR TITLE
Reanalyze a project when it's name changes.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Because changing a project name will end up changing it's semantic version, it's
critical that we reanalyze it when the name changes.  If we don't, then other
parts of the LS that cache information may be stuck with information for a stale
semantic version.

Fixes https://github.com/dotnet/roslyn/issues/8565

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by natidea** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
@dotnet-bot retest prtest/win/vsi/p0 please
@dotnet-bot retest prtest/win/vsi/p2 please
@dotnet-bot retest prtest/win/vsi/p3 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/3995/
// Retest reason: Retry tests that failed due to missing binding redirects and dependencies. Those changes have been reverted.

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/vsi/p0 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p0/270/
// Retest reason:

**Comment by CyrusNajmabadi** [comment]
@dotnet-bot retest prtest/win/vsi/p3 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p3/268/
// Retest reason:

**Comment by jmarolf** [comment]
:+1:

**Comment by dpoeschl** [comment]
Might be a silly question, but why can't we just actually check the semantic version instead of this list of possible changes (that might still be missing other stuff we haven't realized yet)?

**Comment by dpoeschl** [comment]
I mean, I see that we want the InvocationReason to be set correctly, but do we need a catchall or something after that?

**Comment by CyrusNajmabadi** [comment]
Good point @dpoeschl .  I can't think of any good reason not to do this.  And if we don't reanalyze hte project even when it's semantic version changes, we won't be able ot add-project-reference... so we definitely should be that aggressive.

**Comment by CyrusNajmabadi** [comment]
Actually, looking at it again, i'm don't think that's an appropriate fix.  The issue there is that the project's version changes for all sorts of reasons (like documents getting changed).  This code *explicitly* does not want to enqueue a full "re-nanalyze this project" task when a document changes.  Instead, it just wants to reanalyze the project for certain types of config changes.  And other code paths will enqueue document analysis tasks for when documents change.

**Comment by mavasani** [comment]
Also tagging @heejaechang for more context - he probably knows that code best.

**Comment by heejaechang** [comment]
the reason it choose to check some specific ones rather than check version is to reduce number of time analyzers run. sure we can run more often to catch all cases even ones currently nobody cares. but that implies more cost. 

currently it has set that we only cares about.

**Comment by heejaechang** [comment]
if you want to make it just check version, but we need to tighten up semantic version more. currently semantic version could go up even if semantic (compilation's point of view) is not actually changed. this  is because version concept in workspace is not as specific as compilation.

for example, project name change doesnt actually change semantic version since it doesnt affect anything in compilaton. or project file path.

**Comment by CyrusNajmabadi** [comment]
Yes.  SemanticVersion at the workspace layer is a higher concept than the compiler layer.  It means "did anything about this project change that would be observable to others" looking at the project or top level semantics from the compiler's POV."  The project name changing is certainly observable.

**Comment by CyrusNajmabadi** [comment]
@heejaechang Are you ok with this going in?

**Comment by heejaechang** [comment]
:+1: sorry forgot to do :+1:

**Pull request merged**
