### PR TITLE
Change our public API tracking

### PR DESCRIPTION
**Pull request by jaredpar**
This change does two actions to our public API files:

- Resets them to the versions from 1.0.0 RTM
- Splits them into the shipped and unshipped files

From now on all public API changes will go into the unshipped files.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @tmeschter, @ManishJayaswal, @srivatsn, @genlu, @gafter

**Comment by jaredpar** [comment]
Note that this will fail to build until we merge the following PR and produce a new NuGet package:

> https://github.com/dotnet/roslyn-analyzers/pull/276 

Wanted to get this change out there though so others have time to review it.

**Comment by gafter** [comment]
:+1:

**Comment by tmeschter** [comment]
@jaredpar I would also expect it to fail until the new Microsoft.Net.RoslynDiagnostics package is uploaded to NuGet.org. My preference is that we upload 1.1.1 (final), not 1.1.1-beta1-20140818.2 or whatever, though that is only because I want us to get in the habit of publishing stable releases out of dotnet/roslyn-analyzers rather than endless betas. :-)

**Comment by tmeschter** [comment]
@jaredpar I see that we've already made some breaking changes to the 1.0.0 API. Is the intent to file issues for each of those so that they can be properly reviewed?

**Comment by jaredpar** [comment]
@tmeschter i do agree we need a way to publish non-prelease versions of these NuGets.  But I think we need to give a bit of thought to the process for how we do that.  

For example I don't think we should publish a package as non-prelease until we've successfully deployed it through Roslyn.  That is the most strenuous test we can give these packages at the moment and hence should be a min bar for a final version.  Best example of why is this exact bug.  Everything worked until we tried to get Roslyn to consume it :smile:

**Comment by jaredpar** [comment]
@tmeschter I know several of them have already been review but I'm unclear on the others.  I have an email in progress to get clarity on that.

**Comment by tmeschter** [comment]
@jaredpar After further thought I'm in complete agreement about publishing packages.

**Comment by tmeschter** [comment]
:+1:

**Comment by genlu** [comment]
:+1:

**Comment by ManishJayaswal** [comment]
@jaredpar would we need different copies of shipped and unshipped files after we ship update1? If yes then should we have an issue tracking that work?

**Comment by jaredpar** [comment]
@ManishJayaswal after we ship update 1 then the shipped and unshipped files get merged together into PublicAPI.Shipped.txt.  All update 2 work would go into PublicAPI.Unshipped.txt.

**Comment by ManishJayaswal** [comment]
@jaredpar I meant the copies of these files will be different in master and future branch after update1 ships.

**Comment by jaredpar** [comment]
@dotnet-bot  test this please

**Comment by jaredpar** [comment]
@ManishJayaswal not sure what you mean.  The files will be diff (more unshipped APIs in future than master).  But once we ship we'll merge the contents in master and it will flow to future on the next integration.  The diff remaining in future will be the APIs that haven't shipped there.

**Comment by jaredpar** [comment]
@dotnet-bot test this please

**Comment by ManishJayaswal** [comment]
@jaredpar never mind, my brain somehow missed that code is flowing from master to future.

**Pull request merged**
