### PR TITLE
Removed redundant default value assignment in field initializers

### PR DESCRIPTION
**Pull request by bkoelman**
Removed redundant default value assignment in field initializers. RoslynLight.sln builds in VS2015 CTP6 and BuildAndTest.proj runs all tests without errors.

### CODE REVIEW

**Comment by bkoelman** [comment]
@amcasey, @gafter, @AlekseyTs, @VSadov, @agocke @mavasani @srivatsn @heejaechang @Pilchie @pharring 

would some of you please review?

**Comment by pharring** [comment]
:+1:

**Comment by VSadov** [comment]
LGTM

**Comment by bkoelman** [comment]
Thanks for review. If this is sufficient, feel free to merge.

**Comment by VSadov** [comment]
@AlekseyTs @gafter - any comments on this? 
 I think it is ok to merge, but will wait a bit in case you have comments.

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
