### PR TITLE
Updating the InteractiveWindow ClipboardTests to match the expected clipboard format in Update 3.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @tmat, @dotnet/roslyn-interactive, @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Tagging @olegtk who might know if this was intentional.

**Comment by tmat** [comment]
Changing the clipboard format seems to me to be a significant breaking change.

**Comment by tannergooding** [comment]
There is a second commit here now that changes some other things modified in the Clipboard Format.

**Comment by tannergooding** [comment]
@jasonmalinowski, @tmat. Am I good to merge for the time being (to unblock unit tests)?

**Comment by tmat** [comment]
@tannergooding Sure. :+1:

**Comment by tmat** [comment]
Please file an issue to follow up.

**Comment by olegtk** [comment]
Yes, this is intentional change. As of Update3 Copy/Cut are now using printer colors (the category in Fonts and Colors is now called "Printer and Cut/Copy") instead of current theme colors to make your emails with pasted code look better.

**Pull request merged**
