### PR TITLE
Disable test StackTrace_Dynamic

### PR DESCRIPTION
**Pull request by tmat**
Unblocks release testing. See https://github.com/dotnet/roslyn/issues/9221.

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn-infrastructure

**Comment by davkean** [comment]
:+1:

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4421/
// Retest reason: https://github.com/dotnet/roslyn/issues/9249

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4424/
// Retest reason: #9249

**Pull request merged**
