### PR TITLE
Fix vbc crashing when compiling 0 files into a library 

### PR DESCRIPTION
**Pull request by TyOverby**
This is a copy of #8634

### CODE REVIEW

**Comment by natidea** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/3999/
// Retest reason: Jenkins Machine failure
```
17:03:25 FATAL: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@53327ecc[name=dci-win-bld-18]
17:03:25 hudson.remoting.RequestAbortedException: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@53327ecc[name=dci-win-bld-18]
```

**Comment by TyOverby** [comment]
@AlekseyTs 

Tests have been added to both C# and VB compilers. I've also manually confirmed that the native compiler fails with the same diagnostic as we do after this fix.

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler 

One more review please!

**Comment by AlekseyTs** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
