### PR TITLE
Move to value-tasks in asset lookup

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
The majority of lookup calls do no async work. they are either retrieving lightweight data objects that are already reified, or they are looking up assets on values that don't have them (for example, walking through all projects looking for data contained on one of them).  As such, they can be ValueTasks as they complete synchronously without needing to do any actual aync work.

### CODE REVIEW

**Review by sharwell — CHANGES_REQUESTED** [review]
> As such, they can be ValueTasks as they complete synchronously without needing to do any actual aync work.

This path is already optimized by the compiler/runtime for `Task` return types.

**Comment by CyrusNajmabadi** [comment]
Understood.  I'd still prefer these be value-tasks to indicate strongly that this is expected to be synchronous the majority of the time, and needs no allocations.

**Comment by sharwell** [comment]
`Task` performs better than `ValueTask` for this purpose though.

**Comment by sharwell** [comment]
Maybe just document with:

```
[PerformanceSensitive(..., OftenCompletesSynchronously = true)]
```

**Comment by CyrusNajmabadi** [comment]
I'd prefer to keep in this form.  It helps document this fairly clearly, without attributes taht can easily fall out of date (and which do not appear to be checked in any way that i can tell).  ValueTask is already our mechanism for this for this area of hte codebase, so this is keeping us in sync with that.

**Comment by sharwell** [comment]
Changing the return type also isn't validated against an assumption that it often returns synchronously. The attribute is the most direct strategy we currently have for marking this intent in code.

**Comment by CyrusNajmabadi** [comment]
I haven't once seen the attributes convey anything.  The return types though ensure that we see how these are used, and it causes immedaitely issues when we don't await, and attempt to do anything with the return types (like treat them as tasks, not value tasks).  As mentioned, this is already how this entire component space works, and i'd like to keep it that way.

**Pull request closed without merging**
