### PR TITLE
Preserve trivia when spellchecking a word.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/12990

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by balajikris** [comment]
:+1:

**Comment by Pilchie** [comment]
Does VB have a similar issue?

**Comment by CyrusNajmabadi** [comment]
Nope.  For some reason, in VB i have the "WithTriviaFrom" call already.  I just missed it in C# (oops).

**Comment by Pilchie** [comment]
Is there a test in VB?

**Comment by CyrusNajmabadi** [comment]
i wil lcheck

**Comment by CyrusNajmabadi** [comment]
Nope.  But i'll add one.

**Comment by CyrusNajmabadi** [comment]
VB test added.

**Comment by Pilchie** [comment]
Thanks!  :+1:

**Pull request merged**
