### PR TITLE
Null reference exception on shutdown VS with Interactive window executing

### PR DESCRIPTION
**Pull request by ivanbasov**
Fixes https://github.com/dotnet/roslyn/issues/24006

### CODE REVIEW

**Comment by ivanbasov** [comment]
@tmat, do you have an idea of unit tests?

**Comment by ivanbasov** [comment]
@jasonmalinowski, it seems that I should use another event. Could you please point me?

**Comment by jasonmalinowski** [comment]
@ivanbasov why do you think you need something else? And stepping back for a second, logically when do you not need this anymore? The window being closed, process going away...?

**Comment by tmat** [comment]
Closing the window does not close the interactive session. It just hides the window. 

Yesterday you mentioned something about unloading the package. This change hooks ProcessExit event but that can happen after the Dispatcher is shutdown, right? 
We should probably do this when the VS package is closed.

**Comment by ivanbasov** [comment]
As I understand, we cannot rely on the order of events in case of shutting down VS. @jasonmalinowski suggested two options:
1. Try to find a point when we explicitly close the interactive process. I tried but could not find it. It seems that we subscribe to OnProcessExit and cannot distinguish then between an error in interactive and shutdown.
2. When sending an output to interactive, check that its window is open.  For example, we can wrap https://github.com/dotnet/interactive-window/blob/master/src/Microsoft.VisualStudio.InteractiveWindow/Output/OutputWriter.cs#L82
with if (!_window.TextView.IsClosed).

**Comment by ivanbasov** [comment]
will revert latest changes. submitted by mistake

**Pull request closed without merging**
