### PR TITLE
RemoveAllSyntaxTrees should preserve embedded syntax trees in Declaration Table.

### LINKED ISSUE #13925: An Assert in VB.Symbols.EmbeddedSymbolManager.MarkSymbolAsReferenced
see https://github.com/dotnet/roslyn/issues/13884#issuecomment-248174097

This is the preview 5 Roslyn solution running, opened the preview 5 Roslyn solution with full solution analysis enabled and switched to Release mode.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #13925.

@dotnet/roslyn-compiler Please review Update 5 fix.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Test vsi please.

**Comment by cston** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by mattwar** [comment]
@dotnet-bot test vsi please

**Comment by AlekseyTs** [comment]
Failing vsi tests:
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-5/job/windows_vsi_p0_open_prtest/9/
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-5/job/windows_vsi_p2_open_prtest/9/
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-5/job/windows_vsi_p3_open_prtest/14/
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-5/job/windows_vsi_p1_open_prtest/15/

**Comment by AlekseyTs** [comment]
I am going to rebase this change against master.

**Pull request merged**
