### PR TITLE
Fix a break in perf runs

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
test perf please

**Comment by jaredpar** [comment]
CC @rchande, @jasonmalinowski, @TyOverby 

Will merge once perf test is green.

**Comment by rchande** [comment]
Note that Jenkins will mark the run as green even if the error I mentioned occurs. Can you ping me when you're ready to merge and I'll look at the logs and verify it's actually working?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaredpar** [comment]
@rchande 

> Note that Jenkins will mark the run as green even if the error I mentioned occurs

Sounds like something we should fix 

Log is ready to view.

**Comment by rchande** [comment]
@jaredpar So there aren't any errors from PowerShell but it still looks like the perf runner isn't getting invoke. @TyOverby any ideas?

**Comment by rchande** [comment]
It also looks like we aren't installing the BenchView tools. Are we actually entering the body of the conditional on line 109?

**Comment by jaredpar** [comment]
@rchande think I figured out the conditional issue.  Pushed another change.

**Comment by rchande** [comment]
test perf please

**Comment by rchande** [comment]
@jaredpar , still seeing issues:

```
15:47:47 The term 'env:GIT_BRANCH' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
15:47:47 System.Management.Automation.CommandNotFoundException: The term 'env:GIT_BRANCH' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
15:47:47    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
15:47:47    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
15:47:47    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
15:47:47    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

**Comment by jaredpar** [comment]
test perf please

**Comment by rchande** [comment]
@jaredpar Looks like we're producing results now, but none of the perf subsystem's logs are appearing in the console output. Any idea what's up with that?

**Comment by jaredpar** [comment]
test perf please

**Comment by rchande** [comment]
@jaredpar looks good. Thanks!

**Pull request merged**
