### PR TITLE
Reduce allocations during NamespaceSymbol.LookupNestedNamespace

### PR DESCRIPTION
**Pull request by ToddGrun**
This method showed up in a profile I took of the codeanalysis process while typing 5 lines of text in a console app. When NamespaceSymbol.GetNestedNamespace was previously being called, it would call GetMembers and return the first namespace found. The PENamespaceSymbol GetMembers call was allocating a single entry immutable array on nearly all these calls. By making GetNestedNamespace virtual, PENamespaceSymbol can now override that method and just return a value without allocating.

*** Old memory allocations ***
 
image

*** New memory allocations ***

image

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
100mb isn't that much. Buy more RAM

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by ToddGrun** [comment]
> 100mb isn't that much. Buy more RAM

I've got four kids to feed! :)

**Comment by CyrusNajmabadi** [comment]
I have three cats, and you don't hear me complaining!

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Review by jjonescz — APPROVED** [review]

**Pull request merged**
