### PR TITLE
Avoid depdendency on pre-release System.Console

### LINKED ISSUE #6438: PR Test Failure: A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "System.Console (ò 4.0.0-beta-23123)" or update the version field.
*See http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/1507/ for more details.*

```
MSBuild auto-detection: using msbuild version '14.0' from 'C:\Program Files (x86)\MSBuild\14.0\bin'.
  Attempting to build package from 'Microsoft.CodeAnalysis.Scripting.Common.nuspec'.
  A stable release of a package should not have on a prerelease dependency. Either modify the version spec of dependency "System.Console (ò 4.0.0-beta-23123)" or update the version field.
d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Closed\Setup\NuGet\NuGet.proj(106,5): error MSB3073: The command "..\..\..\Open\NuGet Pack NuSpec\Microsoft.CodeAnalysis.Scripting.Common.nuspec -BasePath d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\Binaries\Debug\ -OutputDirectory d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\Binaries\Debug\NuGet\Release -prop licenseURL=http://go.microsoft.com/fwlink/?LinkId=529443 -prop binaries=d:\j\workspace\dotnet_roslyn_prtest_win_dbg_eta\Open\Binaries\Debug\ -prop currentVersion="1.1.0" -prop corextVersion="1.1." -prop microsoftCodeAnalysisAnalyzersVersion=1.0.0 -prop systemReflectionMetadataVersion=1.1.0 -prop systemCollectionsImmutableVersion=1.1.37 -prop authors=Microsoft -prop projectURL=http://msdn.com/roslyn -prop releaseNotes="Preview of Microsoft .NET Compiler Platform ("Roslyn")" -prop tags="Roslyn CodeAnalysis Compiler CSharp VB VisualBasic Parser Scanner Lexer Emit CodeGeneration Metadata IL Compilation Scripting Syntax Semantics" -prop buildName=" exited with code 1.
```

### PR DESCRIPTION
**Pull request by tmat**
Fixes #6438

### CODE REVIEW

**Comment by tmat** [comment]
@tannergooding @ManishJayaswal @dotnet/interactive

**Comment by Pilchie** [comment]
:+1:

**Comment by tmat** [comment]
test win please

**Comment by MattGertz** [comment]
Approved pending successful testing.

**Comment by tmat** [comment]
win dbg 64 failed due to #6459.

**Comment by tmat** [comment]
retest win please

**Pull request merged**
