### PR TITLE
Update to the latest dotnet/command-line-api version

### PR DESCRIPTION
**Pull request by MiYanni**
Related: https://github.com/dotnet/sdk/pull/33126

## Summary
This is a coordinated update for `dotnet/command-line-api` in the repos that DARC flows to. There needs to be only 1 version of this dependency for Source Build to function properly.

### CODE REVIEW

**Review by jjonescz — APPROVED** [review]

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
Isn't this something a bot should be doing automatically?

**Comment by MiYanni** [comment]
@jasonmalinowski 

> Isn't this something a bot should be doing automatically?

I went and double checked the DARC subscriptions. It definitely should be automatic for this repo...

image

It is enabled, so I'm not sure why it isn't flowing properly. Even the last update to this dependency was also manual via this PR: https://github.com/dotnet/roslyn/pull/68549

**Comment by MiYanni** [comment]
Looks like the integration test failures is a known (and currently being addressed) issue.

**Comment by MiYanni** [comment]
@jasonmalinowski @jjonescz Are integration tests just being skipped now? I looked a few other PRs to `main` and they don't run them.

**Comment by jasonmalinowski** [comment]
@MiYanni They should all be running after https://github.com/dotnet/roslyn/pull/70872 was merged.

**Comment by MiYanni** [comment]
@jjonescz @jasonmalinowski  This now can be merged immediately. The [SDK PR](https://github.com/dotnet/sdk/pull/33126) and [Runtime PR](https://github.com/dotnet/runtime/pull/95092) have been merged.

**Pull request merged**
