### PR TITLE
Treat receivers as by-value for interpolated string handler constructors

### PR DESCRIPTION
**Pull request by 333fred**
Fixes https://github.com/dotnet/roslyn/issues/56624.
Relates to test plan https://github.com/dotnet/roslyn/issues/51499

### CODE REVIEW

**Comment by 333fred** [comment]
@AlekseyTs @jcouv for review.

**Comment by AlekseyTs** [comment]
Do we have a test covering an invocation of an extension method that "this" parameter by ref? Is this `ref` semantics respected when we construct a handler?

**Comment by AlekseyTs** [comment]
>             RefKind? receiverRefKind,

It doesn't look like this parameter is used in any meaningful way after the change.

---
Refers to: src/Compilers/CSharp/Portable/Binder/Binder_InterpolatedString.cs:769 in 72238ff. [](commit_id = 72238ff3be33349489cddfb927249cac41d77ec2, deletion_comment = False)

**Comment by AlekseyTs** [comment]
Done with review pass (commit 2)

**Comment by 333fred** [comment]
Added new tests for this.

---
In reply to: [932377100](https://github.com/dotnet/roslyn/pull/56864#issuecomment-932377100) [](http://example.com/codeflow?ancestors=932377100,932377100)

**Comment by 333fred** [comment]
@AlekseyTs addressed feedback.

---
In reply to: [932383671](https://github.com/dotnet/roslyn/pull/56864#issuecomment-932383671) [](http://example.com/codeflow?ancestors=932383671,932383671)

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 3), assuming CI is passing.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Pull request merged**
