### PR TITLE
Revert OOP work from preview 4

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@jcouv @Pilchie @jasonmalinowski @dotnet/roslyn-infrastructure can you take a look? reverting OOP work from preivew 4

**Comment by heejaechang** [comment]
test vsi please

**Comment by jcouv** [comment]
Once this is merged into preview-4, ping me and we'll do the special merge to master.

**Comment by heejaechang** [comment]
do I need sign off?

**Comment by Pilchie** [comment]
Approved - Please merge once Jenkins finishes.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p0_open_prtest/14/
// Retest reason: known analyzer node issue

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest please

known razor issue.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p2_open_prtest/11/
// Retest reason: opened an issue

**Pull request merged**
