### PR TITLE
Don't report extra unnecessary diagnostics for static ctors

### LINKED ISSUE #36121: Regular method missing return type should not be assumed to be a static constructor
**Version Used**: 
 04252e from master, 21 May 19

**Steps to Reproduce**:
```c#
class X
{
    private static Foo(int i) {}
}
```
https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQBMQGoA+ABATAAgA0BYAKAG8z9r8AHBASwDcJ59sBGANnwDEB7fgAoGAOxj4GASnzkAvmTlA===

**Expected Behavior**:
```
error CS1520: Method must have a return type
```

**Actual Behavior**:
```
error CS0515: 'X.X(int)': access modifiers are not allowed on static constructors
error CS1520: Method must have a return type
error CS0132: 'X.X(int)': a static constructor must be parameterless
```

In this case `Foo` is unlikely to be a failed attempt at a static constructor because (1) it has the wrong name (2) it has parameters (3) it has an access modifier. It is vastly more likely I just forgot the return type on a regular method.

If the method name does not match the type name, the compiler should not give diagnostics for static constructors.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #36121

Will add test if no existing tests failed.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Done with review pass (commit 3).

**Comment by Youssef1313** [comment]
@AlekseyTs One test is failing and it feels unrelated to my change here.

The following assertion fails:

https://github.com/dotnet/roslyn/blob/6da1274c9d24c2f90a48290394a951b23617f2a3/src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs#L179

StackTrace:

```
   at Microsoft.CodeAnalysis.ThrowingTraceListener.Fail(String message, String detailMessage) in /_/src/Compilers/Test/Core/ThrowingTraceListener.cs:line 26
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at Microsoft.CodeAnalysis.CustomAttributesBag`1.get_IsEarlyDecodedWellKnownAttributeDataComputed() in /_/src/Compilers/Core/Portable/Symbols/Attributes/CustomAttributesBag.cs:line 179
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.get_ObsoleteAttributeData() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 2093
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.get_ObsoleteKind() in /_/src/Compilers/VisualBasic/Portable/Symbols/Symbol.vb:line 451
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.ObsoleteAttributeHelpers.GetObsoleteDiagnosticKind(Symbol context, Symbol symbol, Boolean forceComplete) in /_/src/Compilers/VisualBasic/Portable/Symbols/ObsoleteAttributeHelpers.vb:line 75
   at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportDiagnosticsIfObsolete(BindingDiagnosticBag diagnostics, Symbol context, Symbol symbol, SyntaxNode node) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder.vb:line 973
   at Microsoft.CodeAnalysis.VisualBasic.Binder.ReportDiagnosticsIfObsoleteOrNotSupportedByRuntime(BindingDiagnosticBag diagnostics, Symbol symbol, SyntaxNode node) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder.vb:line 948
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeOrAliasSyntax(TypeSyntax typeSyntax, Binder binder, BindingDiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb:line 309
   at Microsoft.CodeAnalysis.VisualBasic.Binder.TypeBinder.BindTypeSyntax(TypeSyntax typeSyntax, Binder binder, BindingDiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean resolvingBaseType) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb:line 229
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindTypeSyntax(TypeSyntax typeSyntax, BindingDiagnosticBag diagBag, Boolean suppressUseSiteError, Boolean inGetTypeContext, Boolean resolvingBaseType) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder_Symbols.vb:line 37
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindAttributeType(Binder binder, AttributeSyntax attribute, Symbol ownerSymbol, BindingDiagnosticBag diagnostics) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb:line 48
   at Microsoft.CodeAnalysis.VisualBasic.Binder.BindAttributeTypes(ImmutableArray`1 binders, ImmutableArray`1 attributesToBind, Symbol ownerSymbol, BindingDiagnosticBag diagnostics) in /_/src/Compilers/VisualBasic/Portable/Binding/Binder_Attributes.vb:line 36
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.LoadAndValidateAttributes(OneOrMany`1 attributeBlockSyntaxList, CustomAttributesBag`1& lazyCustomAttributesBag, AttributeLocation symbolPart) in /_/src/Compilers/VisualBasic/Portable/Symbols/Symbol_Attributes.vb:line 263
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetAttributesBag() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 1817
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetEarlyDecodedWellKnownAttributeData() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 1891
   at Microsoft.CodeAnalysis.VisualBasic.Symbols.SourceNamedTypeSymbol.GetAttributeUsageInfo() in /_/src/Compilers/VisualBasic/Portable/Symbols/Source/SourceNamedTypeSymbol.vb:line 2111
   at Microsoft.CodeAnalysis.VisualBasic.Symbol.ValidateAttributeUsage(VisualBasicAttributeData attribute, AttributeSyntax node, VisualBasicCompilation compilation, AttributeLocation sym
```

I'm going to close and re-open for a fresh build to confirm whether it's unrelated.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4)

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off for a small community PR.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 4)

**Comment by jcouv** [comment]
Merged/squashed. Thanks @Youssef1313

**Comment by danmoseley** [comment]
Thanks!

**Pull request merged**
