### PR TITLE
Checking in the IDE test plan document

### PR DESCRIPTION
**Pull request by jcouv**
Doc-only change.
This is capturing the current state of issue #8389. This will allow tracking revisions and getting review feedback.

### CODE REVIEW

**Comment by jcouv** [comment]
CC @dpoeschl @Pilchie for approval.

**Comment by Pilchie** [comment]
:shipit:

**Comment by dpoeschl** [comment]
Late, but :+1:

**Comment by jcouv** [comment]
FYI I closed the original issue with a note redirecting to file in repo.

**Pull request merged**
