### PR TITLE
Get the open vs-integration tests running.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @MattGertz, @ManishJayaswal, @tmat, @jasonmalinowski 

These are test only fixes that get the open-integration tests running in the dev15.0.x and dev15.1.x branches.

### CODE REVIEW

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by tmat** [comment]
:shipit:

**Comment by jasonmalinowski** [comment]
Late but :+1:

**Pull request merged**
