### PR TITLE
Do not commit rename session when debugging starts

### PR DESCRIPTION
**Pull request by tmat**
The current behavior creates inconsistency between F5 and Ctrl+F5.
It is perfectly fine to complete a rename while the app is running. The change will be picked up by EnC/Hot Reload.

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski ptal

**Review by CyrusNajmabadi — APPROVED** [review]
Yes.  The less special behavior we have arrived debugging, the better.

**Comment by jasonmalinowski** [comment]
@tmat Behavior change makes sense to me; I'd be curious how well E&C handles all the insanity we do while doing inline rename edits... :smile:

**Comment by tmat** [comment]
It already has to handle that since you can start renaming after starting debugging session.

**Pull request merged**
