### PR TITLE
Port change to remove IOperation feature flag from dev15.5.x to master

### PR DESCRIPTION
**Pull request by mavasani**
@MattGertz , this is FYI 
This changes are already in dev15.5 branch, we are porting this over to master to be in sync

### CODE REVIEW

**Comment by tmat** [comment]
👍

**Comment by sharwell** [comment]
Why?

**Comment by mavasani** [comment]
> Why?

This change was accidentally merged into dev15.5.x prior to merging IOperation feature branch into master - at that time we were unclear if 15.5 work was going to happen in master or dev15.5.x branch. This is now causing repeated merge conflicts when trying to merge master into dev15.5.x (which happens daily). This is to help reduce this unnecessary infrastructure burden.

**Comment by mavasani** [comment]
> it twice increases the chance of something breaking due to merge conflict resolution

I am not sure I agree on this. After this change, the IOp test and product sources should be identical in master and dev15.5.x and further changes only go into master and should flow into dev15.5.x without any merge conflicts. Can you elaborate why you think this will cause more conflicts?

**Comment by sharwell** [comment]
I performed the rebase a second time in order to validate the merge conflict resolution (chance of two people making the same mistake independently is lower). If this is accepted there will still be a big conflict when we next merge master&rarr;dev15.5.x, but that's not really avoidable.

**Comment by mavasani** [comment]
@sharwell Thank you!

**Comment by mavasani** [comment]
@dotnet-bot retest ubuntu_16_debug_prtest please

**Comment by mavasani** [comment]
@dotnet/roslyn-infrastructure Seems like ubuntu_16_debug_prtest is not starting at all. @tmat this is blocking this PR.

**Pull request merged**
