### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by github-john-doe**

### CODE REVIEW

**Comment by github-john-doe** [comment]
@CyrusNajmabadi

**Comment by CyrusNajmabadi** [comment]
IDE side LGTM.  @dotnet/roslyn-compiler  for compiler changes.

**Comment by github-john-doe** [comment]
Hello?

**Comment by jaredpar** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by github-john-doe** [comment]
Thanks, please merge?

**Comment by CyrusNajmabadi** [comment]
Needs second @dotnet/roslyn-compiler review.

**Comment by CyrusNajmabadi** [comment]
Retest windows_release_unit32_prtest please

**Comment by CyrusNajmabadi** [comment]
Will merge once all tests pass :)

**Pull request merged**
