### PR TITLE
Remove redundant GetDeclaredSymbol(DeclarationExpressionSyntax declarationSyntax, ...) API.

### LINKED ISSUE #13291: Reconsider GetDeclaredSymbol API for out argument declarations
The current API for out argument declarations includes, in CSharpSemanticModel

```cs
        /// <summary>
        /// Given an out variable declaration expression, get the corresponding symbol.
        /// </summary>
        /// <param name="declarationSyntax">The syntax node that declares a variable.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>The symbol that was declared.</returns>
        public abstract ILocalSymbol GetDeclaredSymbol(DeclarationExpressionSyntax declarationSyntax, CancellationToken cancellationToken = default(CancellationToken));
```

and also

```cs
        /// <summary>
        /// Given an identifier declared in a deconstruction declaration, get the corresponding local variable symbol.
        /// </summary>
        /// <param name="declarationSyntax">The syntax node that declares a variable in a deconstruction.</param>
        /// <param name="cancellationToken">The cancellation token.</param>
        /// <returns>The symbol that was declared.</returns>
        public abstract ISymbol GetDeclaredSymbol(SingleVariableDesignationSyntax declarationSyntax, CancellationToken cancellationToken = default(CancellationToken));
```

The latter should work for both deconstruction and out argument declarations, so there is a question whether we should have both APIs, or whether we should delete the first API and keep only the second (presumably with a change to its documentation).

Because it would be a breaking change to remove the API later, we should make a decision today (before the 2.0 milestone is frozen) about these APIs.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #13291.

@dotnet/roslyn-compiler, @gafter Please review.

### CODE REVIEW

**Comment by gafter** [comment]
@jaredpar @AnthonyDGreen You may be interested in this proposed API change. For what it's worth, I agree with @AlekseyTs that we should make this change.

I am surprised you didn't need to edit one of the publicapi.txt files, since this changes a public API. Am I missing something?

Otherwise LGTM

**Comment by AlekseyTs** [comment]
The public API specific to DeclarationExpressionSyntax was actually missing. The behavior of other public API that takes any syntax node has changed though.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need second sign-off.

**Comment by AlekseyTs** [comment]
Ping. @dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by jcouv** [comment]
LGTM Thanks

**Pull request merged**
