### PR TITLE
Order 'Make Synchronous' after 'Add Import'

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/20460

### CODE REVIEW

**Comment by Pilchie** [comment]
Wait - is this a regression from 15.0/15.1/15.2?  If so, I'd like to consider for 15.3 given how frustrating  it can be when something is above Add Using...

**Comment by CyrusNajmabadi** [comment]
i'm not sure if it is a regression or not.  It's likely dependent on whatever order MEF decided on.  It's frustrating.  However, it's only really an issue if you're on an async method declaration that doesn't need async *and* you're also trying to add a using for something in that async method signature.

**Comment by DustinCampbell** [comment]
Yup, and that's how I ran into it. Creating a brand new test file and writing my first test (async of course). Super-common scenario.

**Comment by CyrusNajmabadi** [comment]
That doesn't seem super common to me :)  Also, given that we didn't hear about the issue when it could have totally happened to people already makes me feel like it's not really that problematic.

**Comment by DustinCampbell** [comment]
I'm not sure I understand your reasoning if you're not sure it's not a regression.

**Comment by CyrusNajmabadi** [comment]
So, looking at the code, we've never had any ordering for this code fix provider at all.  I've also installed and tried this out in VS2017 community (i.e. before 15.3) and i got this result where Make Synchronous shows up first:

image

However, in my own local VS2017 enterprise int preview, Make Synchronous shows up afterwards.  This makes me feel like we're likely at the mercy of whatever mef and us do when there is no ordering (which i believe is that it's just nondeterministic).  So, i expect some users will be ok (MakeSynchronous was ordered after, and stays ordered after).  Some users (like myself) have gotten better.  Some users stay bad.  And some users have gotten worse.  The question for me is if this is important enough to warrant addressing the latter category.

**Comment by CyrusNajmabadi** [comment]
Note: i have no problem taking this.  I'm just trying to be fair in terms of how we apply our 15.3 bar.

**Comment by CyrusNajmabadi** [comment]
One thing i have no idea about is: what are the ratios of people in those buckets i outlined above.  For example, maybe my VS community is the rare case, and the workload i've picked caused MakeMethodSync to show up first.  Perhaps hte vast majority of users with 15.0 have MakeMethodSync showing up afterwards.  With something seemingly non-deterministic, i'm not really certain how to tell or make a call here.

**Comment by Pilchie** [comment]
@kuhlenh can check telemetry for how often AddUsing is invoked when it's not the first thing in the list, which should give us some idea.

**Comment by Pilchie** [comment]
Telemetry says that this is showing when it is invoked:

image

Thus it looks like it is happening about 10% of the time.

**Comment by Pilchie** [comment]
Given the simplicity of the change, and the fact that this tends to be a pretty bad experience, I'd like to at least try for 15.3 - can you make a PR against master?

**Pull request merged**
