### PR TITLE
Add missing null check to WorkspaceMetadataFileReferenceResolver.Equals

### LINKED ISSUE #19553: NullReferenceException in WorkspaceMetadataFileReferenceResolver.Equals(WorkspaceMetadataFileReferenceResolver)
**Version Used**: 
 Microsoft.CodeAnalysis.Workspaces 2.1.0.61520

**Steps to Reproduce**:
```
using System;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.MSBuild;

namespace WorkspaceMetadataFileReferenceResolverIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            var workspace = MSBuildWorkspace.Create();
            var project = workspace.OpenProjectAsync(args[0]).Result;
            var compilation = project.GetCompilationAsync().Result;
            var options = compilation.Options.WithMetadataReferenceResolver(new ReferenceResolver());
            compilation = compilation.WithOptions(options);
        }
    }

    class ReferenceResolver : MetadataReferenceResolver
    {
        public override bool Equals(object other)
        {
            throw new NotImplementedException();
        }

        public override int GetHashCode()
        {
            throw new NotImplementedException();
        }

        public override ImmutableArray<PortableExecutableReference> ResolveReference(string reference, string baseFilePath, MetadataReferenceProperties properties)
        {
            throw new NotImplementedException();
        }
    }
}
```

Run the sample application passing a full path to csproj.

**Expected Behavior**:
Sample application should not throw an exception.

**Actual Behavior**:
Sample application throws an exception in line `compilation = compilation.WithOptions(options);`:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.Host.WorkspaceMetadataFileReferenceResolver.Equals(WorkspaceMetadataFileReferenceResolver other)
   at Microsoft.CodeAnalysis.Host.WorkspaceMetadataFileReferenceResolver.Equals(Object other)
   at System.Object.Equals(Object objA, Object objB)
   at Microsoft.CodeAnalysis.CompilationOptions.CanReuseCompilationReferenceManager(CompilationOptions other)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithOptions(CSharpCompilationOptions options)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithOptions(CompilationOptions options)
   at Microsoft.CodeAnalysis.Compilation.WithOptions(CompilationOptions options)
   at WorkspaceMetadataFileReferenceResolverIssue.Program.Main(String[] args) in D:\Works
paceMetadataFileReferenceResolverIssue\Program.cs:line 16
```

### PR DESCRIPTION
**Pull request by fsacer**
Fixes #19553

### CODE REVIEW

**Comment by Pilchie** [comment]
@jasonmalinowski can you get the ask mode template ready?

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by jasonmalinowski** [comment]
Tagging @MattGertz for ask mode approval of this customer PR.

**Customer scenario:** customer is trying to use our Workspace API. Doing an operation to change how metadata references are resolved results in null references.
**Bugs this fixes:** #19553.
**Workarounds, if any:** not really. There's slimy/non-obvious hacks but it's not obvious (even to me) how well they'd work.
**Risk:** zero. Trivial oversight in an Equals method.
**Performance impact:** none.
**Is this a regression from a previous update?** probably not, this code is fairly old.
**Root cause analysis:** missing null check in an Equals method.
**How was the bug found?** customer report (#19553.)

**Comment by sharwell** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please

**Comment by sharwell** [comment]
@dotnet-bot retest windows_eta_open_prtest please

**Comment by jasonmalinowski** [comment]
Thank you @fsacer for the fix!

**Pull request merged**
