### PR TITLE
Make CompilationOptions.MetadataImportOptions public.

### LINKED ISSUE #6748: It should be possible to get MetadataImportOptions.All via public API
Currently, if you get symbols from metadata, the private members are not imported. Internally, there are `MetadataImportOptions.All`, but there is no way to specify those semantics via public API.

We are investigating using Roslyn to walk metadata for binary analysis scenarios and would need to be able to see the private members too.

cc @tmat

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #6748.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler  Please review

**Comment by AlekseyTs** [comment]
CC @jaredpar, @gafter  For public API change.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review

**Comment by theBigBadBob** [comment]
I am fairly certain this does not work with VBCSCompiler.exe, which compiles C# projects.  I am creating a Roslyn Diagnostic Analyzer, below is a snippet of the relevant code. 

```
 public override void Initialize(AnalysisContext context)
 {
           context.RegisterCompilationStartAction(SetMetadataImportOptions);
 }

private void SetMetadataImportOptions(CompilationStartAnalysisContext obj)
{
          obj.Compilation.Options.WithMetadataImportOptions(MetadataImportOptions.All);
}

```
When I debug the process I can see the MetadataImportOptions  value does not change when SetMetadataImportOptions  is called.   When I use reflection to set the MetadataImportOptions, everything works. Is this behavior expected?

I am running Visual Studio 2017 version 15.7.5 and Microsoft.CodeAnalysis.CSharp.Workspaces version 2.8.2

**Pull request merged**
