### PR TITLE
Fix portable project errors

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Fix various errors and warnings that appear in the error list right now if you open Roslyn.sln.

Review: @rchande, @tmat, @agocke

### CODE REVIEW

**Comment by tmat** [comment]
:+1:

**Comment by rchande** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@tmat, @rchande: I've pushed a bunch of new changes, if you could take a look at those as well.
@davkean: you might want to look at this as well.

**Comment by tmat** [comment]
:+1:

**Pull request merged**
