### PR TITLE
Fixed formatting for 'Use pattern matching code fix'

### LINKED ISSUE #23504: Use pattern matching code fix changes merges 2 lines into one
**Version Used**: 
15.6.0 Preview 1.0 [27129.0.d15.6]

**Steps to Reproduce**:
image

Repro code:
```C#
using System;

namespace ConsoleApp10
{
    class Program
    {
        static void Main(string[] args)
        {
            var blog = GetBlog();

            var derivedBlog = blog as Derived;
            var title = derivedBlog != null
                ? derivedBlog.Title
                : "";

            Console.WriteLine("Hello World!");
        }

        public static Blog GetBlog()
        {
            return new Derived { Title = "Test" };
        }
    }

    public class Blog
    {
        public int Id { get; set; }
    }

    public class Derived : Blog
    {
        public string Title { get; set; }
    }
}
```

It should just change line where the code fix is applied and not the merge line after into it.

**Expected Behavior**:
```C#
            var title = blog is Derived derivedBlog
                ? derivedBlog.Title
                : "";
```

**Actual Behavior**:
```C#
            var title = blog is Derived derivedBlog ? derivedBlog.Title
                : "";
```

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #23504

<details><summary>Ask Mode template not completed</summary>

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

(either VSO or GitHub links)

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### Test documentation updated?

If this is a new non-compiler feature or a significant improvement to an existing feature, update https://github.com/dotnet/roslyn/wiki/Manual-Testing once you know which release it is targeting.

</details>

### CODE REVIEW

**Comment by jinujoseph** [comment]
cc @chborl

**Comment by zaytsev-victor** [comment]
Any updates on this?

**Comment by sharwell** [comment]
@Pilchie for pre-ask mode

**Comment by Pilchie** [comment]
Approved - thanks

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by Neme12** [comment]
Why is this still open?

**Comment by jinujoseph** [comment]
failing test

**Comment by chborl** [comment]
@dotnet-bot retest ubuntu_14_debug_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_es_unit32_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by chborl** [comment]
@dotnet-bot windows_release_vs-integration_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_release_unit64_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest ubuntu_14_debug_prtest please

**Comment by chborl** [comment]
@dotnet-bot retest windows_debug_es_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
I think the 'ubuntu_14_debug_prtest' test does not exist anymore so the failure is expected.

**Comment by chborl** [comment]
@dotnet-bot retest ubuntu_16_debug_prtest please

**Comment by jinujoseph** [comment]
@Pilchie  missed asking ask mode approval on this , you ok with this change ?

**Comment by Pilchie** [comment]
Approved (after the fact).  Thanks @zaytsev-victor !

**Pull request merged**
