### PR TITLE
Syntax node actions are not called for field declarations in compiler analyzer driver if the declaration defines multiple variables

### PR DESCRIPTION
**Pull request by mavasani**
Fix for #565: Syntax node actions are not called for field declarations in compiler analyzer driver if the declaration defines multiple variables

Simplify logic for execution of syntax node actions for field declarations: If there are multiple decls, execute syntax node actions for entire field decl (and its descendants) when processing symbol declared event for first field within it, and skip syntax node actions for rest of fields defined within that declaration.
Current logic is unnecessarily complex in that it tries to execute syntax node actions for individual variable declarators when processing corresponding field symbol declared event, and executes the node actions for shared nodes (e.g. defining type syntax node) when processing first field symbol, and caused this bug to sneak through.

Added regression tests for compiler driver (VB and C#) and IDE driver.

@JohnHamby @srivatsn please take a look.

### CODE REVIEW

**Comment by JohnHamby** [comment]
The logic has gotten a little tangled but I think the change will produce correct behavior.

Thank you for writing some real tests.

I sign off.

**Comment by mavasani** [comment]
Thanks John, I agree. We should clean up how we execute syntax node actions. The current convoluted logic is to allow calling these actions when individual member symbol is bound (for binding perf advantage). Probably, we can figure out a more cleaner and equally performant implementation.

NOTE: I have merged the change to unblock the customer, I'll address any review feedback subsequently.

**Comment by srivatsn** [comment]
The change looks fine to me. But I'm concerned that this regressed and we didn't catch it. Here's an idea for a test - can we write an analyzer that subscribes to every single node kind and then compares the nodes in a tree to what got called. Something like this:

```CSharp
RegisterCompilationStartedAction( c => 
     {
          var dict = new DictionaryOfTreeToNodes();
          c.RegisterSyntaxNodeAction(sc => 
                        {
                              dict[sc.SemanticModel.SyntaxTree].Add(sc.Node);
                        }, ArrayOfAllSyntaxKinds);

          c.RegisterCompilationEndAction(cec => 
                      {
                           foreach (var tree in compilation.SyntaxTrees)
                           {
                                    var calledNodes = dict[tree];
                                    var allNodes = tree.DescendantNodes();
                                    IssueDiagnosticOnDiff(calledNodes, allNodes);
                           }

     }
```
If we had such an analyzer and we run on it Roslyn.sln, we'll likely cover a lot of these language cases. I suspect the diff between calledNodes and allNodes will be non-null and may even be for good reason but it'll be good to find that baseline as well.

**Comment by sharwell** [comment]
@srivatsn It's not a bad idea, but I'm not sure it would have caught *this* regression, specifically because callbacks are issued for the simple cases of `FieldDeclaration` and `EventFieldDeclaration`.

One thing I did in ANTLR 4 is I created a test which would subscribe to these events for a large static "reference" code base (in our case the reference source for a particular release of JDK 7), and the test would alert me to any change in the order in which callbacks occurred (including the omission or addition of callbacks). I did this by computing a deterministic CRC 32 hash of the operation and then making an assertion that the CRC should not change - a failing test indicates that a closer look needs to be made into the changes which occurred.

**Comment by srivatsn** [comment]
Right that's why I said we should run such an analyzer on Roslyn.sln which would be the reference code base in your example. I imagine we would have declared multiple fields on the same line in Roslyn somewhere. The hash sounds interesting but since we can compare syntax nodes directly may be that would be sufficient?

**Pull request merged**
