### PR TITLE
use public azure build machines 

### PR DESCRIPTION
**Pull request by jmarolf**
Comparing how long we spend waiting for VMs in the past 6 weeks we can see the following average times:

| | dnceng | public |
|--|---:|---:|
| Build_Windows_Debug	| 13:37.4	| 04:04.2 |
| Build_Windows_Release	| 13:41.0	| 04:13.1 |
| Build_Unix_Debug	| 09:35.1	| 03:54.8 |
| Correctness_Build	| 13:56.8	| 04:32.4 |
| Correctness_Rebuild	| 14:08.2	| 04:14.0 |

It appears that changing our VM images will shave about 10 minutes off of CI times.

### CODE REVIEW

**Review by dibarbet — APPROVED** [review]
Definitely not opposed to this considering the improvements in queue times.  I would be interested though if we can get the owners of any of these pools to provide actual SLAs on queue times.  We should remember to ask about these dnceng's pools when we bring up helix queue times as well, as I doubt we'll get any guarantees on the public queues.

**Comment by jaredpar** [comment]
> Definitely not opposed to this considering the improvements in queue times

I'm skeptical this will actually improve our queue times. Consider that a public pool effectively throttles machines to 200 parallel runs per AzDO project. That means the entire dnceng `public` project can have no more than 200 parallel public machines running per queue. 

Queue times for PRs like this look good because we're not really stressing the pool that much. It's a few builds into the bigger bucket. Once we flip the entire Roslyn repo over to this though suddenly it's the full force of our entire developer base pushing on this queue. We average ~100 runs of our standard pipeline per day. That alone will take up a significant amount of the queue. If anyone else is using these queues we're going to get throttled very fast likely resulting in significantly worse queue times. 

This is one of the primary reasons we moved to these queues. I agree the queue times right now are really bad but I think it's likely to get worse if we flip to the public pools.

**Comment by jmarolf** [comment]
> I'm skeptical this will actually improve our queue times. Consider that a public pool effectively throttles machines to 200 parallel runs per AzDO project. That means the entire dnceng public project can have no more than 200 parallel public machines running per pool.

Thanks @jaredpar. You are right and I totally forgot about this. I think I'll just close this PR. 

>I agree the queue times right now are really bad but I think it's likely to get worse if we flip to the public pools.

This is why the saving here are so tantalizing. We pay a ~15 minutes cost to our CI times _no matter what we do_. I can do all sorts of tricks in https://github.com/dotnet/roslyn/pull/62336 but none of that is going to reduce build times by _15 minutes_. We also pay this cost _again_ waiting for helix machines in our test runs, though I don't have any way to switch the VM pool for that one.

Is the simplest solution to just investigate _why_ it takes 3 times as long to allocate a VM on dnceng vs the public azure images? who do I talk to about that?

**Comment by RikkiGibson** [comment]
I think the number of jobs we tend to run in parallel is such that if only roslyn took advantage here, we wouldn't get throttled that much.

**Comment by markwilkie** [comment]
> Is the simplest solution to just investigate why it takes 3 times as long to allocate a VM on dnceng vs the public azure images? who do I talk to about that?

Thoughts @ilyas1974 ?

**Comment by ilyas1974** [comment]
There are several solutions we've looked at in the past to address the issue of "spin up time". Unfortunately most of them are not possible in our environment because of budget constraints. There is an option to "pre-stage" systems so they are already provisioned (what I believe AzDo does) so the spin up "cost" is done outside your workload. While we would like to implement this solution, we do not have the budget. 

As to @dibarbet question about queue times, we have queue wait time data available at https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queues/queue-monitor

**Comment by jmarolf** [comment]
> While we would like to implement this solution, we do not have the budget.

@ilyas1974 by "cost" do you mean we can't spare the engineers? would love to help on the implementation side here.

**Comment by ilyas1974** [comment]
Cost in this context is what we are billed by Azure for our usage. Making the change is a simple process - we just don't have the budget allocated to us for this change.

**Pull request closed without merging**
