### PR TITLE
Merge microupdate into future-stabilization

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from microupdate into future-stabilization.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-microupdate-into-future-stabilization20160628-193823
git reset --hard upstream/future-stabilization
git merge upstream/microupdate
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-microupdate-into-future-stabilization20160628-193823 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test windows_eta_open_prtest please
test windows_vsi_p1_open_prtest please
test windows_vsi_p2_open_prtest please

**Comment by jmarolf** [comment]
test windows_eta_open_prtest please
test windows_vsi_p1_open_prtest please
test windows_vsi_p2_open_prtest please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Pull request merged**
