### PR TITLE
	Use an enum for classification to make things cleaner to OOP.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by Pilchie** [comment]
I know you haven't asked for feedback on this one yet, but while I'm reviewing...

We deliberately avoided doing this with enums to allow the possibility of extending the set of possible classifications in the future (consider other languages, or classifying based on `SymbolSpecifiers` like in naming style.

**Comment by CyrusNajmabadi** [comment]
This enum is only for the marshalling layer so that we odn't have to send strings back and forth.

**Comment by Pilchie** [comment]
But what about when we need to send more types over?  Types that the core system doesn't know about?

**Comment by Pilchie** [comment]
I'm thinking about future proofing.  We already know we want to allow user-configurable symbol specifiers with custom colors.  How will we handle remoting that?

**Comment by CyrusNajmabadi** [comment]
We'd have to allow them to pass their own int, which could be mapped on the other end...

**Comment by CyrusNajmabadi** [comment]
but i haven't given that case much though.

**Comment by CyrusNajmabadi** [comment]
@Pilchie I'd still like this to go through.  If/when we decide to open up semantic classification to 3rd parties, i don't think this will be problematic.  Here's how i would handle things:

I would allow 3rd parties to plug in with some classification system that still returned strings.   Like with analyzers, these plugins would have to declare their classification names.  We would then have our marshaller convert those strings to unused ints and marshall in that manner.

Alternatively, like i've done with other parts of the system, the marshaller could marshall data as either an int or a string.  So if it saw something it didn't know, it would just marshall the entire string over.  I had such a system for a while in the existing OOP serialization code.

**Comment by CyrusNajmabadi** [comment]
I'm leaning toward that now myself.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Closing out.  If we do anything here, it will all be at the serialization layer.

**Pull request closed without merging**
