### PR TITLE
Add documentation for local functions branch

### PR DESCRIPTION
**Pull request by khyperia**
Ping @jaredpar @gafter for a quick review before putting this into the main repo.

### CODE REVIEW

**Comment by jaredpar** [comment]
Right now it has a check box only for every feature.  Complete to me means code, tests and editor functionality.  Many items are checked which don't meet this bar (generics).

**Comment by khyperia** [comment]
What format would you suggest writing it in? Not sure how to integrate a list of descriptions with a table of differing amounts of complete-ness.

**Comment by jaredpar** [comment]
I was thinking of prefixing every entry with say: `[coded]`, `[tested]`, `[complete]`.  Not as nice as check boxes but can't think of a better option here.

**Comment by khyperia** [comment]
Updated.

**Comment by gafter** [comment]
How about something like this

- [ ] Feature
  - [X] Initial Implementation
  - [ ] Tests
  - [ ] IDE integration
- [ ] Feature2
  - [ ] Design approved
  - [ ] Syntax Disambiguation
  - [ ] Etc

**Comment by jaredpar** [comment]
I think that's pretty reasonable.

**Pull request merged**
