### PR TITLE
Update opt prof data (trained on vsuml 26811.4002)...

### PR DESCRIPTION
**Pull request by KevinH-MS**
**Customer scenario**

Performance

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/_queries?id=477707

**Workarounds, if any**

None

**Risk**

None

**Performance impact**

Decreases VS reference set/overall VM

**Is this a regression from a previous update?**

Yes

**Root cause analysis:**

We didn't retrain, because it's still not automated.

**How was the bug found?**

RPS

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @dotnet/roslyn-perf

**Comment by KevinH-MS** [comment]
FYI @Pilchie for Dev15.4 Ask Mode...

**Comment by KevinH-MS** [comment]
retest windows_debug_unit64_prtest please

**Comment by Pilchie** [comment]
Approved, but let's hold off on merging for a bit, because we are holding the branch for things necessary for Preview 1.

**Comment by jaredpar** [comment]
Is the updated opt-prof data also going into the dev15.3.x branch? This necessary to resolve our RPS exceptinos we get for 15.3.

**Comment by Pilchie** [comment]
@jaredpar - I wouldn't think we would ship this in a servicing update?  Isn't the exception to last until 15.4?

**Comment by jaredpar** [comment]
@Pilchie no. Exception is until 15.3.2. Re-forwarded the relevant email.

**Comment by KevinH-MS** [comment]
@Pilchie are we done with Preview 1 (i.e. can we merge this yet)?

**Comment by Pilchie** [comment]
Tagging @MattGertz for confirmation, but I think we're okay to merge now.

**Comment by MattGertz** [comment]
Approved to merge for ASK mode 15.4 (not escrow).

**Pull request merged**
