### PR TITLE
Don't attempt to provide a navbar if there is no navbar language serv…

### PR DESCRIPTION
**Pull request by dibarbet**
…ice.

need to confirm if the content type switch is complete before this runs

https://github.com/dotnet/roslyn/issues/40989

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
(i know this is a draft pr).

> if there is no navbar language service

When does taht happen? :)

**Comment by dibarbet** [comment]
> When does taht happen? :)

in liveshare - the client doesn't have a navbar service, instead the navbar items are retrieved via LSP from the server and the VS LSP client handles the display (creating the dropdowns etc).  
the reason there is no navbar service is the content type shenanigans.  Obviously that will change as soon as C#_LSP is removed and we'll start getting the C# navbar service.  

I think we'll need assistance from the editor to come up with a better way to handle / order multiple dropdowns, or liveshare APIs to determine if a specific file is a shared file so we can disable dropdowns based on that.

It's bugged right now because on the client side, roslyn is overriding the LSP client navbar with an empty one.  So this is a try at fixing that issue.  Would be glad to hear of other suggestions, I don't really like doing it this way.

**Comment by dibarbet** [comment]
#40989 tracks fixing this long term

**Comment by CyrusNajmabadi** [comment]
It feels weird that this isn't entirely transparent to the LS.

**Pull request merged**
