### PR TITLE
Allow snippets in Inline Diff View

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes internal TFS bug #831378

Invoke snippets on the DataBuffer instead of the EditBuffer. Once
IVsExpansion.InsertExpansion/InsertNamedExpansion has been invoked
on the correct buffer, all remaining processing is the same
(formatting, end span tracking, and snippet functions all map their
given spans down to the subject buffer for processing).

Potential reviewers: @Pilchie @jasonmalinowski @balajikris @rchande @brettfo @jmarolf
FYI: @KirillOsenkov

### CODE REVIEW

**Comment by dpoeschl** [comment]
I have a local integration test for snippets in inline diff view, but it currently requires a 1-second wait, so I'll figure that out tomorrow hopefully. Snippets expansion on tab and the snippet picker now work in both inline diff view and razor files, but not in inline diff view **of** razor files, but that did not work in Dev12 either.

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by rchande** [comment]
:+1:

**Comment by KirillOsenkov** [comment]
Excellent! Thanks for fixing this!

**Pull request merged**
