### PR TITLE
Updating Roslyn to Toolset Version 1.1.0-beta1-20150727-01.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jaredpar, @ManishJayaswal, @agocke

### CODE REVIEW

**Comment by tannergooding** [comment]
Bug #4170 is here to track the breaking API change that is part of this PR.

**Comment by tannergooding** [comment]
@dotnet-bot test this please

**Comment by tannergooding** [comment]
@dotnet-bot test this please

**Comment by jaredpar** [comment]
What commit represents this toolset?

**Comment by tannergooding** [comment]
Commit 4643ff584179799ee99a0266b331441f3c1eaaad, I am working on tagging it now.

**Comment by tannergooding** [comment]
Tag VS.Toolset.Roslyn.1.1.0-beta1-20150727-01

**Pull request merged**
