### PR TITLE
Use default constant value for synthesized local reference for LockTa…

### LINKED ISSUE #28301: Invalid ConstantValue for the ILocalReferenceOperation generated for LockTaken variable reference in CFG
Look at any of the flow tests for ILockStatement, for example http://source.roslyn.io/#Roslyn.Compilers.CSharp.Semantic.UnitTests/IOperation/IOperationTests_ILockStatement.cs,455:

```
ILocalReferenceOperation:  (IsDeclaration: True) (OperationKind.LocalReference, Type: System.Boolean, Constant: null, IsImplicit) (Syntax: 'source1 ?? source2')
```

Note that the local reference operation is of type `bool`, but it has a constant value of `null` instead of having no constant value. Issue seems to be at couple of places in the CFG builder where we synthesize LocalReferenceExpression [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/ControlFlowGraphBuilder.cs,3757) and [here](http://source.roslyn.io/#Microsoft.CodeAnalysis/Operations/ControlFlowGraphBuilder.cs,3797), we incorrectly use `constantValue: null` instead of `constantValue: default`.

### PR DESCRIPTION
**Pull request by mavasani**
…ken variable in CFG

Fixes #28301

<details><summary>Ask Mode template</summary>

### Customer scenario

When an analyzer using the new ControlFlowGraph compiler APIs tries to request and analyze a flow graph for source code containing a `lock` statement, we return a corrupt graph. This can cause analsysis to fail in various ways (throws exception(s), fires assert(s), produce incorrect analysis result, etc.). In fact, attempting to move the features/dataflow branch on https://github.com/dotnet/roslyn-analyzers to the latest Microsoft.CodeAnalysis NuGet package is causing all the lock related tests to fail with asserts.

### Bugs this fixes

Fixes #28301

### Workarounds, if any

All CFG based analyzers have to explicitly identify and handle such corrupt cases.

### Risk

Low. This only affects analyzers based on new CFG APIs, which need to be executed under an experimental feature flag. The fix is also pretty trivial.

### Performance impact

None

### Is this a regression from a previous update?

No, this is a new public API.

### Root cause analysis

Missed it while reviewing the tests.

### How was the bug found?

Attempting to move roslyn-analyzers repo to latest Microsoft.CodeAnalysis NuGet pacakge

### Test documentation updated?

N/A

</details>

### CODE REVIEW

**Review by 333fred — COMMENTED** [review]
LGTM. @mavasani, while you're taking care of this, can you check to make sure that we're not doing this anywhere else?

**Review by 333fred — APPROVED** [review]

**Comment by mavasani** [comment]
@333fred Search for `constantValue: null` and `constantValue:null` in this file returned only these 2 instances.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for one more review.

@jaredpar @jinujoseph for approval

**Comment by jcouv** [comment]
Approved (pending second review)

**Comment by mavasani** [comment]
Ping @cston for second review.

**Comment by cston** [comment]
Can we catch these cases with an assert in `Operation..ctor`? Perhaps:
```
Debug.Assert(type?.IsReferenceType != true || !constantValue.HasValue || constantValue.Value != null);
```

**Comment by mavasani** [comment]
> Can we catch these cases with an assert in Operation..ctor?

Thanks, added the assert and verified it fails prior to this change. I also adjusted the assert to handle nullable value types.

**Review by cston — APPROVED** [review]

**Comment by 333fred** [comment]
@mavasani reopend to trigger tests

**Comment by mavasani** [comment]
Filed https://github.com/dotnet/roslyn/issues/28328 for unit test failure in windows_debug_spanish_unit32_prtest

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_spanish_unit32_prtest  please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_spanish_unit32_prtest please

**Comment by mavasani** [comment]
@dotnet-bot test this please

**Comment by mavasani** [comment]
@jinujoseph This needs to go into 15.8 Preview 5. This is blocking moving roslyn-analyzers to latest CFG APIs.

**Comment by mavasani** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview5

**Pull request merged**
