### PR TITLE
Add a new Azure Function-based merge tool

### PR DESCRIPTION
**Pull request by agocke**
This merge tool uses the Github API to create the commits rather than
relying on local Git clones.

### CODE REVIEW

**Comment by agocke** [comment]
@dotnet/roslyn-infrastructure @jasonmalinowski @brettfo For review

**Comment by agocke** [comment]
test this please

**Comment by brettfo** [comment]
When will this be run?  Is the schedule only handled on the Azure side of things?

Also, what are your plans to allow GitHub -> VSO merges?  F# needs this and we can't deprecate the old tool until this is supported.

**Comment by agocke** [comment]
@brettfo This gets run every day at midnight PST. The timer is stored in the Azure function.

**Comment by agocke** [comment]
I would eventually like this to also support the VSO API, but I haven't had the time to hook it up.

**Comment by agocke** [comment]
test this please

**Comment by brettfo** [comment]
Ok.  I'm happy if we set the other tool to only do F# and use this for roslyn, so long as we don't forget that F# will eventually need to be moved, too.  (Although, this might not be an issue since we'll eventually be moving all of F# to GitHub which means we won't need the VSO support anymore.)

**Comment by agocke** [comment]
Merging because this cannot effect the build (since it isn't built by any run).

**Pull request merged**
