### PR TITLE
don't suggest this in a static local function alternative

### PR DESCRIPTION
**Pull request by YairHalberstadt**
This is the alternative option suggested in #35822, shown here for comparison.

### CODE REVIEW

**Comment by YairHalberstadt** [comment]
I wouldn't review this until the compiler team has decided on the correct approach in #35822

**Comment by jasonmalinowski** [comment]
@YairHalberstadt Thanks for the heads up -- I'll watch both then.

**Comment by jasonmalinowski** [comment]
(still watching the other one)

**Comment by jasonmalinowski** [comment]
@YairHalberstadt Since we're going with the other one, OK to close this one? Any other value in this you want to keep?

**Pull request closed without merging**
