### PR TITLE
fixed where project name gets disappeared if a project is unloaded in…

### PR DESCRIPTION
**Pull request by heejaechang**
… "BuildOnly" error list mode.

now we will show < Unknown > for such project.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @basoundr can you take a look? this will make us to show <Unknown> for unloaded project for build errors in "BuildOnly" view.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure tests are not finishing. is this expected after the machine pool change?

**Comment by srivatsn** [comment]
:+1:

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure some tests are never finished. should I ignore them?

**Comment by mavasani** [comment]
:+1:

**Comment by davkean** [comment]
No you should not ignore them.

**Comment by davkean** [comment]
It looks likes Jenkins when down, let me figure out what's going on.

**Comment by davkean** [comment]
retest prtest/win/dbg/eta please

**Comment by davkean** [comment]
retest prtest/win/dbg/unit32 please

**Pull request merged**
