### PR TITLE
Bump the Roslyn.Build.Util version to 0.9.3-portable

### PR DESCRIPTION
**Pull request by agocke**
The current task references 14.1.0 MSBuild references, which fails
the VS design-time build, but succeeds when running MSBuild since
MSBuild has a binding redirect that VS does not.

I temporarily hacked this by ildasm/asming the DLL to downgrade
the reference to 14.0.0.

### CODE REVIEW

**Comment by agocke** [comment]
@jasonmalinowski Can you try this and see if it fixes what you saw?

**Comment by agocke** [comment]
Workaround for https://github.com/dotnet/roslyn/issues/9856

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by jmarolf** [comment]
:+1: provided you fix the mac build failure

**Comment by agocke** [comment]
need to update the nuget zip

**Pull request merged**
