### PR TITLE
Do not return empty nodes in the refactoring helpers service.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/58811

### CODE REVIEW

**Review by ryzngard — APPROVED** [review]

**Review by Youssef1313 — COMMENTED** [review]
I think the fix could be in line 137 (AbstractAddParameterCheckCodeRefactoringProvider.cs
), which might be missing `getInnermostNodeForTie: true`

```csharp
                var firstParameterNode = (TParameterSyntax)root.FindNode(parameterSpan);
```

The challenge is to find a test case. Is there any scenario where the syntax tree can contain a ParameterList with missing parenthesis? this is a case where the ParameterSyntax and ParameterListSyntax might have the same span, so the cast will fail.

**Comment by sharwell** [comment]
> which might be missing `getInnermostNodeForTie: true`

This could cause a problem for simple lambdas, where the parameter span is the same as the identifier span.

**Comment by CyrusNajmabadi** [comment]
> This could cause a problem for simple lambdas, where the parameter span is the same as the identifier span.

Technically that would be ok as this is FindNode and the 'identifier' is a token.  That said, i still can't figure out how FindNode, when given the span of a parameter, is getting the ParameterList back instead.  Taht's the weird thing here.

**Comment by Youssef1313** [comment]
> > I think the fix could be in line 137 (AbstractAddParameterCheckCodeRefactoringProvider.cs
> > ), which might be missing getInnermostNodeForTie: true
> 
> Yes, i thought that was likely teh case too. However, i still can't figure out a repro for this. As such, i didn't want to make a change that doesn't certainly fix things. This change at least lets us know what is going on so we can narrow this down :)

Going to see if https://github.com/dotnet/roslyn/pull/58845 can hint to a repro

**Comment by CyrusNajmabadi** [comment]
actually i have a theory.  let me try out parameters that are *missing*.  that might cause some issues here.

**Comment by CyrusNajmabadi** [comment]
> actually i have a theory. let me try out parameters that are missing. that might cause some issues here.

Yes.  This is the case that hits this.

**Pull request merged**
