### PR TITLE
Remove '.sh' extension from the coreclr csc/vbc scripts

### PR DESCRIPTION
**Pull request by agocke**
Naming the execution scripts 'csc.sh' and 'vbc.sh' is counter to the
convention of not using any extension on *nix executables. While the
scripts are not strictly executable programs, they are meant to be
transparent shims around the actual execution of the compilers on *nix

@TyOverby @jaredpar @AlekseyTs @VSadov @gafter Please review.

### CODE REVIEW

**Comment by agocke** [comment]
test this please

**Comment by TyOverby** [comment]
Looks good to me.  I also agree with the motivation.

**Comment by jaredpar** [comment]
:shipit:

**Comment by agocke** [comment]
@mmitche @tannergooding Still no build hooks for this PR?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@agocke I think that mac-bld-2 is rapidly approaching dead status.  I took it offline

**Comment by jaredpar** [comment]
@mmitche earlier today it was emitting errors that are generally associated with corrupted hard drives.

**Comment by agocke** [comment]
test this please

**Pull request merged**
