### PR TITLE
Localization test failures 3

### PR DESCRIPTION
**Pull request by MaStr11**
Fix for #23837.
Follow up for #24407 and #24424
This is the third of a series of PRs meant to resolve the unit test failures caused by missing localizations.

This PR includes test related to the editor and workspace:

### Roslyn.Services.Editor2.UnitTests 
Done. Tested local (de-DE) and CI (en-US).
### Roslyn.Services.Editor.CSharp.UnitTests 
Done. Tested local (de-DE) and CI (en-US).
### Roslyn.Services.Editor.VisualBasic.UnitTests 
Done. Tested local (de-DE) and CI (en-US).
### Roslyn.Services.UnitTests 
Done. Tested local (de-DE) and CI (en-US).

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
(and now I see the WIP tag, but hey, so far it looks good. :-))

**Comment by MaStr11** [comment]
@jasonmalinowski I'm done with this batch of fixes now. I'm just waiting for the CI to finish and will remove the WIP in case all tests pass. I think it is save to start the review right now if you want to (I don't expect the CI tests to fail).

**Comment by jasonmalinowski** [comment]
@jaredpar @tmeschter @jinujoseph Where are we planning on taking these loc test fixes now? dev15.6.x means we'll be taking an insertion, even though this is test only. Typically test-only hasn't fallen under our escrow bar which is fine, but if this will cause trouble we should just move it.

@MaStr11 Looks good. You can ignore my question, this is entirely a question of internal paperwork. :smile:

**Comment by jaredpar** [comment]
@jasonmalinowski I think we should just move these to dev15.7.x. It looks probably that we're going to be able to setup a Jenkins run to catch these problems at PR time. I'm guessing that's going to cause a couple of other issues to shake out. More runway in dev15.7.x to deal with that. 

Given this branch is in escrow it shouldn't affect contributors that much. Most of our work will be off this branch starting next week. 

If there are strong feelings about commiting it here I wouldn't push back.

**Comment by tmeschter** [comment]
@jaredpar @jasonmalinowski Move it to dev15.7.x.

**Pull request merged**
