### PR TITLE
Ensure that cref completion uses Speculative SemanticModel. Fixes TFS #9...

### PR DESCRIPTION
**Pull request by rchande**
Fixes TFS #988380

Potential reviewers: @balajikris @basoundr @davkean @dpoeschl @jasonmalinowski @jmarolf  @Pilchie

### CODE REVIEW

**Comment by Pilchie** [comment]
Is there any way to test this?

**Comment by rchande** [comment]
I couldn't think of a good way. We could have a test that runs the providers against an ISemanticInfoService that asserts it isn't called on doc comments, I suppose.

**Comment by rchande** [comment]
@Pilchie I added some tests.

**Comment by Pilchie** [comment]
Thanks, LGTM

**Comment by rchande** [comment]
test this please

**Comment by balajikris** [comment]
:+1:

**Pull request merged**
