### PR TITLE
Fix loc files

### PR DESCRIPTION
**Pull request by tmat**
Updates DevDivInsertionFiles to account for changes in loc files made directly to lab/ml.

### CODE REVIEW

**Comment by tmat** [comment]
@dpoeschl @balajikris @dotnet/roslyn-infrastructure

**Comment by balajikris** [comment]
whats the issue that we're fixing here?

**Comment by tmat** [comment]
That the generated files inserted in DevDiv were manually updated without the generator of these files being updated. So it's now out of sync.

**Comment by balajikris** [comment]
I see -- thanks!

**Comment by balajikris** [comment]
:+1:

**Pull request merged**
