### PR TITLE
Properly handle forwarded types in PEModuleSymbol.GetWellKnownType.

### LINKED ISSUE #18092: VB UWP No ConstructorArguments for ITypeSymbol Attributes
Affected Branch: 
Affected Build: 15.1
Affected Product Language: VB only

Steps to reproduce:

1. Launch VS version 15.1
2. Create a UWP VB project, set platform target version to RS2
3. Open MainPage.xaml
4. Add <InkToolbar></InkToolbar> inside the root Grid

Expected:
You get a min target version incompatible warning
image

Actual:
For VB project, you don't see this warning. This scenario works fine on C# and C++ UWP projects.

The root cause is we get the ContractVersionAttribute from a ITypeSymbol, and then get the apiContract name and version from the attributeData's ConstructorArguments. This works as expected for C# and C++ projects, but for VB, the ConstructorArguments are always empty.

This bug is blocking a new XAML feature for RS2 - warn about types and properties not available in the target platform minimum version supported by the project.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #18092.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by cston** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Pull request merged**
