### PR TITLE
Include byte order marks from explicit Encoding in checksum

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@tmat

**Comment by tmat** [comment]
@cston Could you revert the previous change as a separate commit and then apply the new fix? It would be cleaner in the history.

**Comment by cston** [comment]
@tmat see #7680

**Comment by cston** [comment]
@dotnet/roslyn-compiler, @tmat, @gafter Updated fix for #7225.

**Comment by jaredpar** [comment]
:+1:

**Comment by VSadov** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
