### PR TITLE
Tracking span and readonly region cleanup

### PR DESCRIPTION
**Pull request by amcasey**
Tidy up some things I noticed while working on #5141.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @genlu @KevinH-MS @cston @ManishJayaswal @zooba @DinoV

**Comment by cston** [comment]
LGTM

**Comment by amcasey** [comment]
Note: The first commit doesn't change any behavior, but the second commit prevents appending to completed standard input buffers.

**Comment by amcasey** [comment]
It turns out that, since there is a single standard input buffer, being able to append is required so that subsequent input sessions will accept input.

**Pull request merged**
