### PR TITLE
Utilise InlineData for unittests.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
Iniitial start on the proposal in #12510.
By spliting the unittests down into small common chunks, so inline data attributes can be used. Also narrows down the focus of the unit test method to a specific test area.

### CODE REVIEW

**Comment by tmat** [comment]
I do not like the usage of InlineData. It's harder to debug. In the previous code I could have placed breakpoint on the 10th case that I'm interested in and start debugging from there. With InlineData I need to step over 9 cases before I get to the one that I'm interested in, or I need to set up conditional breakpoint, which is extra work.

**Comment by tmat** [comment]
:-1:

**Comment by tannergooding** [comment]
InlineData also does not play well with some test coverage tools (like the CodeLens icons).

Roslyn also has too many tests to be useful in the TestExplorer at the moment, so you can't readily debug just the test you want.

**Comment by AdamSpeight2008** [comment]
@tmat  The CodeRush for Roslyn (v16.1.6.16238) Test Runner (/Test Explorer) has no issue debuging the last inlinedata. Also doesn't seem to have an issue with number of unittests.

**Comment by tmat** [comment]
I don't know what CodeRush does or does not, but not everyone uses CodeRush. I don't see what benefit does using the attribute have vs the original code.

**Comment by AdamSpeight2008** [comment]
@tmat  Rather that dropping a rather large load (of changes) I gonna do them piece. 
On the branch I'm changing over it already a 100 lines smaller, and I've only just started.

**Comment by tmat** [comment]
There is already plenty of opportunity for parallelism, since we have 10s of thousands of independent tests.

**Comment by AdamSpeight2008** [comment]
Let me finish converting over the unit tests on a branch, and then we can compare the results?

**Comment by gafter** [comment]
:-1:

I don't find this an improvement. We already have plenty of parallelism, and the explicit nature of the existing tests makes them easier to understand. Those extra lines aren't getting in anybody's way.

**Comment by AdamSpeight2008** [comment]
@tmat Another way to debug a particular `InlineData` is move it to be first.

**Comment by gafter** [comment]
:-1:

**Pull request closed without merging**
