### PR TITLE
Added pathmap to msbuild options

### LINKED ISSUE #5830: MSBuild support for the pathmap option
We need to plumb support for the `pathmap` option (as described in #949) through MSBuild.

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #5830

CC @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by TyOverby** [comment]
Ping @dotnet/roslyn-compiler

**Comment by jaredpar** [comment]
:+1:

**Comment by TyOverby** [comment]
@gafter When https://github.com/dotnet/roslyn/pull/4543 lands, I'll merge this and start working on the unit tests.

**Comment by jaredpar** [comment]
@TyOverby can you merge / rebase this against master?

**Comment by TyOverby** [comment]
@jaredpar: Yeah.  

@gafter: Could you review?

**Comment by TyOverby** [comment]
@jaredpar Ok, this should be mergeable now.

**Pull request merged**
