### PR TITLE
Check current language version for “Global” keyword only if it starts namespace name in namespace declaration.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Addresses DevDiv 1129404.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - DevDiv 1129404
- Customer scenario - Usage of a “Global” keyword is checked against language version even when it not used to declare a namespace. This is a breaking change and affects a lot of tools generating code. AP.NET projects targeting earlier frameworks are affected.  
- Fix description - Adjust relevant language version check to affect namespace declarations only. Native compiler does the same thing.
- Testing done - unit-tests.

@jaredpar FYI

**Comment by jaredpar** [comment]
:+1:

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @gafter, @agocke, @khyperia Please review.

**Comment by agocke** [comment]
:+1:

**Comment by VSadov** [comment]
LGTM

**Comment by gafter** [comment]
@AlekseyTs Where would I find a description of the desired and actual behavior of the compiler that this is intended to change? Is `Global` supposed to be accepted but not being accepted in the user's code? What was the change in the language specification that the compiler is misapplying and when did it change?

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@gafter Sorry for the confusion. To clarify, a usage of a ```Global``` keyword is supposed to be checked against language version only when the keyword is used to declare a ```Global``` namespace. It used to be checked against in all usage contexts, which was incorrect.

**Comment by MattGertz** [comment]
Approved 6/3 by ML Shiproom.

**Pull request merged**
