### PR TITLE
Revert "Don't produce ref assemblies for test projects"

### PR DESCRIPTION
**Pull request by jcouv**
Reverts dotnet/roslyn#22734

### CODE REVIEW

**Comment by jcouv** [comment]
@jasonmalinowski @jaredpar I messed up and merged an infra change meant for post-dev15.5 into master. I'm reverting asap.

**Comment by sharwell** [comment]
@jcouv Is there a reason we need to revert this? Would it cause a problem for 15.5?

**Comment by jcouv** [comment]
@sharwell It does not cause problem for 15.5, but it also does not solve a critical problem for 15.5 (escrow).
I don't see problem to leave in master, but that was not my intention to merge there. Let me know what you think.

**Comment by sharwell** [comment]
Infrastructure changes are typically allowed during escrow as long as they don't interfere. While we probably wouldn't have done this on purpose, it doesn't seem necessary to revert only to merge it immediately back in another branch.

@jasonmalinowski or @jaredpar should be able to give a second opinion.

**Comment by jasonmalinowski** [comment]
I'm OK leaving it.

**Comment by jcouv** [comment]
Ok. Leaving the change.
Thanks

**Pull request closed without merging**
