### PR TITLE
Implement VB Code Model's AddAttribute method for several declaration kinds

### PR DESCRIPTION
**Pull request by DustinCampbell**
In VB Code Model, AddAttribute is now implemented for the following declaration kinds, fixing Issue #596:

* Subs/Functions
* MustOverride Subs/Functions
* Declare Subs/Functions
* Auto-properties
* Simple Events
* Custom Events

Also, I added more unit test coverage for some other declaration kinds, such as constructors and operator overloads.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Potential reviewers for this change: @jasonmalinowski, @dpoeschl, @rchande, @Pilchie, @balajikris, @basoundr, @brettfo :smiley:

**Comment by DustinCampbell** [comment]
Thanks -- already fixed in my next PR

**Comment by Pilchie** [comment]
:shipit:

**Comment by balajikris** [comment]
:+1:

**Pull request merged**
