### PR TITLE
Add a feature to convert existing code to use 'x is Type t' pattern.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is a port from master.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz @ManishJayaswal @Pilchie

**Comment by ManishJayaswal** [comment]
@CyrusNajmabadi is this a new code fix?

**Comment by CyrusNajmabadi** [comment]
Yes, it is.  Kevin would like it to go into RC.

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit64_prtest  please

**Comment by CyrusNajmabadi** [comment]
Closing in favor of https://github.com/dotnet/roslyn/pull/14613

**Pull request closed without merging**
