### PR TITLE
Detect object initializer pattern inherited from base types

### PR DESCRIPTION
**Pull request by rchande**

### CODE REVIEW

**Comment by rchande** [comment]
FYI @dotnet/mlangide. This is a ressurection of my earlier botched PR.

**Comment by Pilchie** [comment]
:+1: again

**Comment by rchande** [comment]
test this please

**Comment by rchande** [comment]
@genlu Microsoft.VisualStudio.InteractiveWindow.UnitTests.InteractiveWindowTests.CallPasteOnNonUIThread is failing for me. Is it supposed to be disabled?

**Comment by rchande** [comment]
The 32-bit test that failed is as above, the 64-bit results aren't coming in due to rate limiting.

**Comment by genlu** [comment]
@rchande I missed a couple of those tests. Just disabled them.

**Pull request merged**
