### PR TITLE
Change `Location` of record's primary constructor to point to record's identifier.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Related to #47357.

### CODE REVIEW

**Comment by jcouv** [comment]
>         }

nit: do you want to include a direct validation on `.Location` API?

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:22367 in f43ff87. [](commit_id = f43ff87eb04fafb61d37211621d86b90fcf09fec, deletion_comment = False)

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 1) with a test suggestion

**Review by RikkiGibson — APPROVED** [review]

**Comment by AlekseyTs** [comment]
>         }

I think existing tests are good enough.

---
In reply to: [692951110](https://github.com/dotnet/roslyn/pull/47715#issuecomment-692951110) [](ancestors = 692951110)

---
Refers to: src/Compilers/CSharp/Test/Semantic/Semantics/RecordTests.cs:22367 in f43ff87. [](commit_id = f43ff87eb04fafb61d37211621d86b90fcf09fec, deletion_comment = False)

**Comment by CyrusNajmabadi** [comment]
Awesome, thanks :)

**Pull request merged**
