### PR TITLE
Wait for navigation to complete

### PR DESCRIPTION
**Pull request by sharwell**
Wait for editor search using reflection to invoke its test helpers. Fixes flakiness observed in internal test runs.

No public API is currently available (known) that allows waiting for this operation without reflection.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@veler We need a supported way in tests to wait for AOISP's async work to finish so that we can then validate the results/behaviors of it.

**Comment by CyrusNajmabadi** [comment]
@sandyarmstrong as well.  Thanks :)

**Comment by CyrusNajmabadi** [comment]
@veler thanks!

**Comment by sharwell** [comment]
@veler These are integration tests. We don't need _an_ instance of `ISearchController`, we need the instance of `ISearchController` that is created by `SearchViewModel.InitializeSearchController`.

**Pull request merged**
