### PR TITLE
Export an appropriate service so that serialization works properly in the external process.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @heejaechang @srivatsn @panopticoncentral 

A problem here is that the Esent persistence service will not save data if it thinks the solution is too small.  However, problematically, in the remote-service we do not compute solution sizes due to incremental-analysis not running.  i.e. it is an incremental analyzer that figures out how big a solution is.  

For now, i'm making it so that we always presume a solution is large enough to warrant persisting data about it to disk in the remote process.

--

Note: as a design point, i find the idea that persistence is dependent on solution size to be *very* weird.   You could have a solution that references tons of dlls.  Because we might not even enable esent, that means that we'll just regenerate indices for these projects over and over again.  For things like our metadata-indices, this is quite costly (both in CPU and memory).  

This limitation of the persistence service was not documented or communicated.  The api simply says:

```
    /// <summary>
    /// This service allows you to persist information relative to solution, projects and documents.
    /// </summary>
    public interface IPersistentStorageService : IWorkspaceService
    {
        IPersistentStorage GetStorage(Solution solution);
    }

    public interface IPersistentStorage : IDisposable
    {
        Task<Stream> ReadStreamAsync(string name, CancellationToken cancellationToken = default(CancellationToken));
        Task<Stream> ReadStreamAsync(Project project, string name, CancellationToken cancellationToken = default(CancellationToken));
        Task<Stream> ReadStreamAsync(Document document, string name, CancellationToken cancellationToken = default(CancellationToken));

        Task<bool> WriteStreamAsync(string name, Stream stream, CancellationToken cancellationToken = default(CancellationToken));
        Task<bool> WriteStreamAsync(Project project, string name, Stream stream, CancellationToken cancellationToken = default(CancellationToken));
        Task<bool> WriteStreamAsync(Document document, string name, Stream stream, CancellationToken cancellationToken = default(CancellationToken));
    }
```

Note that these are public services in the workspace layer.  Nothing about them indicates that persistence is conditional in any fashion.  Many features have been written that presume the presence of this index and that they can produce data in a costly fashion, knowing that that will only be a one time thing.

I would strongly push on us removing this undocumented and strange internal switch so that layers above hte workspace can depend on having a persistence layer that works for all projects, not just projects that we've deemed 'large enough'.

**Comment by CyrusNajmabadi** [comment]
Note: i have a more aggressive approach to this issue here: https://github.com/dotnet/roslyn/pull/15045

In it i remove this solution-size heuristic entirely.

**Comment by heejaechang** [comment]
Persistent service can always fail. The size switch is just implementation detail. Basically for users, it just fails. We talked about using something cheaper like file system as persistent service for smaller solution. but didn’t implement those.

Turning esent on by default will cause 50MB VM regression in RPS, we got rejected on getting exception for those (it was on for all solution size at the beginning). So if you can get that exception, that’s fine. Otherwise, you will need to get back 50MB VM from somewhere before you can check this in.


-          heejae

**Comment by CyrusNajmabadi** [comment]
> Persistent service can always fail. 

This has not been communicated or *documented* anywhere.

There is nothing about this public API that indicates that failing is part of it's contract.  And it's especially not documented that thing can fail for arbitrary reasons *like file size*.  We have no such failures defined in Roslyn for anything like that.  We do have documented failure reasons for things like IO.  At least that would be somewhat expected from a persistence service (after all... it has to eventually persist somehow, and maybe that just won't be possible).  but we've never had any sort of system in Roslyn just fail because of arbitrary size restrictions.  *And*, importantly, it's not even as if the size restrictions are upper bounds.  We're not saying "if your project gets too large, we may start failing". It's "if your project is too small, we'll fail out to make a dashboard green." :(

Decisions like these need to be documented and communicated clearly *especially* when they're part of our public API.

**Comment by heejaechang** [comment]
why would persistent service API return bool then? if not explicitly saying return true or false means failure and succeeded is matter. than add comment.

**Comment by CyrusNajmabadi** [comment]
Let's discuss this tomorrow.  Right now the concern is that we have a service that we've built many layers on top of that doesn't appear to work properly in completely normal use cases.  This causes excess CPU and memory allocations.  This behavior was not documented and looks to have been added simply to make a dashboard green, despite the problems it could cause higher up the stack.  On top of this, this behavior change was not communicated.  So a core service now breaks, and all the higher up stack layers behave poorly because the conditions that could cause it to break were never communicated.

Please inform people in the future if you are going to do things that change things about how the lower layers of hte system work.  People working on the higher levels need to be aware of these changes as it deeply affects the design and implementation of our features.   This is similar to the change that happened that made it so that you couldn't necessary go from an open document to a text snapshot.  This change was not communicated and it caused crashes because a previous invariant that people communicated, and could depend on, was undone.  This is a similar case.  A heuristic that breaks a service *for some set of solutions* without any documentation is extremely bad.   We do not do that in Roslyn and we certainly shouldn't be doing that just so a test can pass.

**Comment by heejaechang** [comment]
I am not sure what is break. persistent service API can fail always, all service who use persistent service has to make itself know how to deal with it.

I have seen any feature that broken due to it.

**Comment by CyrusNajmabadi** [comment]
> I am not sure what is break. persistent service API can fail always, all service who use persistent service has to make itself know how to deal with it.

No.  That's not how the original design of the persistence service was communicated.  When we discussed this originally, there were only a few thins outlined that would cause failures.  Specifically:

1. IO exceptions occured. 
2. Esent error occurred (likely a special case of '1').

Both of these were messaged as being extremely *rare* occurrences.  This bit is important.  The situations where persistent might fail were communicated as being *exceptional* circumstances.  As such, we designed the layers that might sit on top of persistence with that in mind.  i.e. we designed them to work extremely well in the common case, and to be resilient (but costly) in the uncommon case.

This communicated behavior of this low level API changed *without notification* to supply a completely different contract.  Now the above only holds true for large projects, and for small project the failure rate of persistence is 100%.  That is a completely unlike the originally communicated capabilities of this system.   Falling back on "persistent service API can fail always" is not an acceptable argument.  Completley changing the parameters of when and how failure occurs, is a contract change.  It would be hte same as if the compiler threw a BadImageFormatException on every dll <50kb, and then fall back on "well metadata reading can fail for any reason, so this behavior is ok".  The communicated expectation was that failure was a rare case, not the normal case for *very common projects*.

> I havent seen any feature that broken due to it.

1. That's because we code our features to still be resilient to the cases that are rare.  We do that because we accept that certain things may happen (like IO problems), but we still want things to work properly.  But this behavioral change means our features are broken because their assumptions about how much work they need to do across runs has changed.  Imagine a feature which took several minutes to run and which cached tens of MB of data (like the Nuget Cache).  We might design that feature to persist that data, with the knowledge that needing to perform that amount of work would be exceedingly rare.  If it now happens that such work is necessary *on every VS run*, then our feature is broken wrt our computation budget, not necessarily the end experience for the customer.  

2. We have continually run into issues where changes in behavior are not being suitably communicated up the stack to people using these layers.  The break in the contract that open documents could reach snapshots was not documented and *did* lead to a directly broken user (specifically a crash).  Similarly, the non-communicated change in behavior caused when FSA was disabled broke features.  These features were broken because critical aspects of FSA disabling simply were not communicated adequately.  

This situation has happened several times now, and i'm *strongly* asking you to please make it much clearer to the team when you're going to change implementation behavior.  Stating that it's ok because "persistent service API can fail always" in irresponsible.  If a service goes from rarely failing, to failing 100% of time time for a specific class of projects, then that *must* be communicated.  Layers are being written based on originally communicated expectations, and those layers are deeply impacted when these decisions are made.

**Comment by CyrusNajmabadi** [comment]
test this please

**Pull request closed without merging**
