### PR TITLE
Disable module load assertions in the IDE perf tests

### PR DESCRIPTION
**Pull request by rchande**
Tracked by #4174 .

cc @pharring @heejaechang

### CODE REVIEW

**Comment by heejaechang** [comment]
Do you know which component cause them to be loaded?


-          heejae

**Comment by pharring** [comment]
@rchande What happened here? Looks like the PR got replaced with another unrelated change.

**Comment by pharring** [comment]
Also, 4147 doesn't appear to be the correct tracking number.

**Comment by rchande** [comment]
Not sure what happened, will open another PR.

**Pull request closed without merging**
