### PR TITLE
bring all improvements in master to RC for OOP

### PR DESCRIPTION
**Pull request by heejaechang**
total 13 improvements

https://github.com/dotnet/roslyn/pull/14454
when OOP build new solution, it will synchronize all missing data in batch mode. this should make missing data to be transferred to OOP process way faster than before.

https://github.com/dotnet/roslyn/pull/14457
moved OOP layer down to workspace layer rather than VS layer. this will make working with find all references/navigate to easier. we need this change since it interleaved with other changes.

https://github.com/dotnet/roslyn/pull/14494
this will let multiple requests to use its own pipe line to VS rather than sharing one. this should remove pipe line congestion. 

https://github.com/dotnet/roslyn/pull/14509
made code lens to check cancellation in more places so that it can get cancelled more quickly when no longer needed.

https://github.com/dotnet/roslyn/pull/14531
improve string/char[] allocations when reading text from file/mmf

https://github.com/dotnet/roslyn/pull/14538
add Language to CompilationOptions and ParseOptions which will be used in next PR.

https://github.com/dotnet/roslyn/pull/14539
use the new Language property to remove possibility of crashing due to other language service such as type script not implementing required service for OOP

https://github.com/dotnet/roslyn/pull/14583
made incremental checksum building more efficient by reducing cases where we need to re-calculate checksums.

https://github.com/dotnet/roslyn/pull/14594
we need this PR since it interleaves with other PR which has file moved.

https://github.com/dotnet/roslyn/pull/14629
add IProjectCacheHostService to OOP so that we can let things go when they are no longer needed

https://github.com/dotnet/roslyn/pull/14675
enable cache on code lens service

make servicehub to any cpu and make sure no tree are held strong in solution

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn want to take a look?

**Comment by heejaechang** [comment]
@MattGertz here are list of PRs that are in master but not in RC related to OOP.

**Comment by MattGertz** [comment]
@heejaechang Thanks, HeeJae.  I'll wait for @srivatsn 's recommendations first, so that it's already been narrowed down.

**Comment by KevinH-MS** [comment]
@heejaechang this causes a crash in LUT.  Can you drop by to help debug?

**Comment by KevinH-MS** [comment]
Ok, I finally got my VSIX fixed, and this all seems to work fine once I recompile.

FYI @natidea @ManishJayaswal once this is merged, we'll need to coordinate the Roslyn and LUT insertions or this change will break LUT.

**Comment by ManishJayaswal** [comment]
@heejaechang are you changes ready to be merged? If yes then we will insert this and dynamic analysis into ml simultaneously.

**Comment by MattGertz** [comment]
Note that I'm waiting for @srivatsn to give me the heads up before approving, and I'm expecting that shortly.  @KevinH-MS what is your corresponding change so that I'm ready for that one too?

**Comment by MattGertz** [comment]
Our testers gave this the thumbs up.  Approving.

**Comment by heejaechang** [comment]
@KevinH-MS I checked in.

**Pull request merged**
