### PR TITLE
Stop setting InternalFeatureOnOffOptions

### LINKED ISSUE #5393: Snippets permanently disabled after launching Interactive Window
In https://github.com/dotnet/roslyn/commit/c7c55e3487782d5aad37daf484322c9a8b299355, we used ```InternalFeatureOnOffOptions.Snippets``` as a way for the ```InteractiveWorkspace``` to disable snippets, but changing this option to false for the ```InteractiveWorkspace``` causes that false value to be persisted, and it spreads to all workspaces (```InternalFeatureOnOffOptions``` were never meant to be per-workspace).

We should switch the ```InteractiveWorkspace``` back to using the default options, and include ```WorkspaceKind``` checks (and TODO comments) everywhere ```InternalFeatureOnOffOptions.Snippets``` is checked.

### PR DESCRIPTION
**Pull request by amcasey**
We were doing so to disable snippets in the interactive window, but it
turns out that it's per-user, rather than per-workspace.

Fixes #5393

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @cston @KevinH-MS @ManishJayaswal

**Comment by dpoeschl** [comment]
:+1:

**Comment by cston** [comment]
LGTM

**Comment by KevinH-MS** [comment]
Good to know! :+1:

**Comment by amcasey** [comment]
FYI, pushed update that should fix machines already in a bad state.

**Pull request merged**
