### PR TITLE
Updating Roslyn to Toolset Version 1.1.0-beta1-20150825-02.

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @jaredpar, @ManishJayaswal, @agocke

**Comment by tannergooding** [comment]
https://github.com/dotnet/roslyn/releases/tag/VS.Toolset.Roslyn.1.1.0-beta1-20150825-02

**Comment by jaredpar** [comment]
We should be using the `toolset_<number>` tagging system now.

**Comment by tannergooding** [comment]
Fixed and message edited above.

**Pull request merged**
