### PR TITLE
Remove redundant dependencies for .NET Core.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Comment by 333fred** [comment]
These are not redundant dependencies, and we depend on several APIs in the versions that we have specified. What issue are you trying to solve here?

**Comment by teo-tsirpanis** [comment]
They are already included in .NET Core itself. The packages are required for .NET Standard and Framework only.

**Comment by 333fred** [comment]
> They are already included in .NET Core itself. The packages are required for .NET Standard and Framework only.

A _version_ of these are included with .NET Core. This is not always the correct version for the compiler. Again, what issue are you trying to solve here?

**Comment by teo-tsirpanis** [comment]
Not a particular one, just saw the package's dependencies on NuGet and found it fishy. 😳

Hmm, just saw that older versions of these packages are referenced. Are there breaking changes in later ones or any other problem that holds us from upgrading?

**Comment by 333fred** [comment]
The versions of these packages control a bunch of different downstream dependencies. As such, we'd like to keep them the way they are. I appreciate the willingness to help with issues, but this isn't something we view as an issue.

**Comment by teo-tsirpanis** [comment]
Hello @333fred, I have been thinking of this PR again. How about removing _only_ `System.Memory` and `System.Threading.Tasks.Extensions` from the .NET Core dependencies? These packages are polyfills for early frameworks that do not support spans and are no longer getting new versions.

This could be done as part of #57875.

**Pull request closed without merging**
