### PR TITLE
Do not offer 'use pattern matching' inside an expression tree

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/68784

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@genlu  @Cosifne ptal.

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide ptal.

**Comment by CyrusNajmabadi** [comment]
@genlu @Cosifne ptal.

**Comment by CyrusNajmabadi** [comment]
@genlu @Cosifne @akhera99 ptal :)

**Review by akhera99 — APPROVED** [review]

**Pull request merged**
