### PR TITLE
return Guid.Default if no Guid is present in the project

### PR DESCRIPTION
**Pull request by jmarolf**
In [this PR](https://github.com/dotnet/roslyn/pull/35746) we inadvertently made a change that would cause the language service to fail to initialize if there was no project guid.

Unfortunately there are a lot of projects in the world that depend on this behavior and it is unlikely that we could ship this way.

fixes [AB#915798](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/915798)

CC: @jinujoseph

### CODE REVIEW

**Comment by jmarolf** [comment]
@jasonmalinowski 	

> Having null Project GUIDs will break downstream systems, so this isn't the right fix

I am returning `Guid.Empty` which was the original behavior.  Returning `null` is the breaking change

**Comment by jasonmalinowski** [comment]
Well, but it's somewhat worse now -- since we're not capturing the IVsHierarchy (and are trying to look it back up from the IVsSolution), anything else that may have wanted the hierarchy is now going to be busted.

Why are we not able to get a GUID? Is that a point-in-time thing where it's initializing, or will that project never have a GUID?

**Comment by jmarolf** [comment]
@jasonmalinowski 	it is valid for projects to not have GUIDs defined (at least it has been for the pat 15+ years)

**Comment by jasonmalinowski** [comment]
My impression was in that case the project system "invented" a GUID. Practically, projects are registered with IVsSolution with a GUID, and a number of other things (like error reporting) requires a GUID.

**Comment by jmarolf** [comment]
> My impression was in that case the project system "invented" a GUID.

Nope, project GUIDs are completely optional from an implementation standpoint. Many people copy/paste the same GUID across all their projects or just not had any GUID specified at all.  the language service should never assume a project GUID is unique or that one even exists.  This has been (implicit) csproj behavior for a very long time.

**Comment by jmarolf** [comment]
@jasonmalinowski 	re-reviewing https://github.com/dotnet/roslyn/pull/35746 I see what you mean. It ties proejct identity to project guids which is not a safe thing to do.  We should just revert https://github.com/dotnet/roslyn/pull/35746.  Unless you have a better idea, I'll close this PR and submit a new one that is a revert of 35746

**Comment by tmat** [comment]
So, then if there is no relationship between project and project GUID then why does Roslyn even need to know about the project GUID?

**Pull request closed without merging**
