### PR TITLE
Guard against serialization failure of Encoding

### PR DESCRIPTION
**Pull request by heejaechang**
**Customer scenario**

Intermittently user edits certain text file and LUT failed to run live unit tests on OOP with that change. Once he hits this. LUT always fails to build and VS needs to be restarted

**Bugs this fixes:** 

https://github.com/dotnet/testimpact/issues/1368

**Workarounds, if any**

Restart VS

**Risk**

Change let OOP to ignore encoding of the file. meaning some cache won't be re-used since solution is not 100% in sync. but for LUT, it doesn't care about encoding since content of the file is actually same. so it shouldn't affect result of LUT.

**Performance impact**

when this happens, OOP might not re-use existing cache since the given checksum for the solution is different than the one in OOP. it might fork existing solution to new one which might invalidate some caches.

but, its worst impact should be same as RC2 which re-creating everything from scratch was the default behavior. RC3 is first release that re-use caches and incrementally update solution.

**Is this a regression from a previous update?**

No

**Root cause analysis:**

VS/OOP synchronization relies on hierarchical checksum of a solution which includes encoding. 

since Encoding (http://index/?leftProject=mscorlib&leftSymbol=xgib3ouu7pxt&file=system%5Ctext%5Cencoding.cs&line=88) is serializable, we take advantage of that to move encoding between 2 processes. but some encoding violates that and make itself not serializable. and that cause us to completely fail to synchronize the solution.

the fix is guard from the case, and let us still sync solution in such case.

**How was the bug found?**

Dogfooding/Testing.

### CODE REVIEW

**Comment by heejaechang** [comment]
@KevinH-MS @ManishJayaswal can you try this. it should only be used with latest master since I checked in that relex OOP must 100% same as inproc

**Comment by KevinH-MS** [comment]
I tried this out, and it works around the issue for me (build succeeds and LUT keeps running) 👍

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest  please

**Comment by heejaechang** [comment]
@natidea can you do bar check for this fix? @ManishJayaswal want it for LUT

**Comment by heejaechang** [comment]
@srivatsn @ManishJayaswal @MattGertz I am not sure whether this is RTW bug or not, but regardless I think it is good thing to have in OOP since user can have custom encoding that is not properly marked as serializable.

**Comment by heejaechang** [comment]
@mavasani @KevinH-MS @srivatsn @srivatsn can I get some code review. this is for post-dev15

**Comment by heejaechang** [comment]
ping?

**Comment by heejaechang** [comment]
@KevinH-MS ping?

**Comment by KevinH-MS** [comment]
LGTM 👍

**Pull request merged**
