### PR TITLE
Use nameof instead of hardcoded argument names.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by whoisj** [comment]
:+1:

**Comment by jaredpar** [comment]
:+1: 

We should really just write a tool that does this on every file.  Already a few out there to pick from.

**Comment by CyrusNajmabadi** [comment]
Could your formatter do it @jaredpar ?

**Comment by jaredpar** [comment]
@CyrusNajmabadi this repo certainly could

https://github.com/jaredpar/UseNameOf

We are looking to write a more formal tool though.

**Pull request merged**
