### PR TITLE
Remove unused method from sighelp

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @jasonmalinowski .  Would like to remove this helper entirely, but it's used by testing to validate certain things are true (i.e. that if you type a non-sighelp character, that no sig-help machinery runs in the BG).

**Comment by CyrusNajmabadi** [comment]
@jinujoseph why was this base changed?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski probably not. can you check somehow?

**Comment by jinujoseph** [comment]
@CyrusNajmabadi sorry meant to leave a note.
master is targetting 16.2 and is at GA 
thought this was ready to merge so targetted for 16.3.Preview1

**Comment by CyrusNajmabadi** [comment]
Looks like things have diverged somewhat.   This causes a conflict and added a bunch of strange changes @jinujoseph 

> master is targetting 16.2 and is at GA

IMO, master should always be the place for normal development.  Release branches can be made for specific trains that don't want general stuff going into them.  Just me 2c.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph  @jasonmalinowski can you merge in plz?

**Comment by jinujoseph** [comment]
@CyrusNajmabadi  we need to confirm it's not breaking F# & TS
@jasonmalinowski  will followup on that once he has taken care of few priority items in his plate.

**Comment by jasonmalinowski** [comment]
IVT looks good, so just waiting for CI to complete.

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski Tests have finished.  Thanks!

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi Integration tests failed in some bizarre way. I don't mean "the tests failed and I can see a failure" but rather "the machine just kinda gave up trying and didn't even tell me what went wrong".

**Comment by jasonmalinowski** [comment]
That job has been requeued.

**Comment by jasonmalinowski** [comment]
Thanks @CyrusNajmabadi for the cleanup!

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
