### PR TITLE
Do not generate obsolete `Exception` constructor

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Fixes: https://github.com/dotnet/roslyn/issues/72552

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by DoctorKrolic** [comment]
@CyrusNajmabadi It seems that the CI is failing consistently on a one specific compiler-related test. I also see this error in my other PR. So there might be a CI issue, which needs attention (and it is CI-only since it fails in 1 specific environment, while passes in others and locally)

**Comment by CyrusNajmabadi** [comment]
@DoctorKrolic known issue.

**Review by sharwell — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
Someone restart failed pipelines pls

**Pull request merged**
