### PR TITLE
Require prohibit this me

### LINKED ISSUE #7065: Code Style: Analyzer + Code fix for requiring/prohibiting this/Me
We have an analyzer + code fix to support removing redundant uses, but we need options for what type of access it is (field/property/method/etc), and to require it.

### LINKED ISSUE #7090: "Encapsulate fields" refactoring should consider personal code style
If I have this code:

```csharp
public class Test
{
    protected readonly bool IsATest;
}
```

the refactoring generates the following code.

```csharp
public class Test
{
    private readonly bool isATest;
    protected bool IsATest
    {
        get
        {
            return isATest;
        }
    }
}
```

Since I have checked "Qualify member access with 'this'" I expect to get following refactoring:

```csharp
public class Test
{
    private readonly bool isATest;
    protected bool IsATest
    {
        get
        {
            return this.isATest;
        }
    }
}
```

Notice the added `this.`.

image

Thanks to @sharwell for referring to the right project in DotNetAnalyzers/StyleCopAnalyzers#1833

### PR DESCRIPTION
**Pull request by brettfo**
This is a port of #7540 (now closed) to the `future` branch.

### Description
Splits the option _"Qualify member access with 'this' or 'Me'"_ into four separate options (and marks the former as `[Obsolete]`):

- Qualify **field** access.
- Qualify **property** access.
- Qualify **method** access.
- Qualify **event** access.

### Known Issues
1. We've discussed giving the user a dial in how and when these properties should be applied, e.g., "only apply this style on newly generated code" all the way up to "flag violations of this style as a build break" and various steps in between.  That has not been addressed in this PR and is still an open discussion item that I filed as #7289.
2. If a user currently has _"Qualify member access with 'this' or 'Me'"_ set to `true`, we need some way to upgrade/migrate that setting to the 4 new separate settings.

Fixes #7065.
Fixes #7090.

Also fixes an unrelated bug I found in Encapsulate Field in VB that caused `Me.` to be improperly included when an escaped keyword is used when the option wasn't set and also enables Encapsulate Field in C# for escaped identifiers.

Also fixes event hookup generation in C# to produce `MyEvent += this.GeneratedEventHandler;` where `this.` will be appropriately simplified or not and the inline rename session will always use the `GeneratedEventHandler` span.

@dotnet/roslyn-ide

### CODE REVIEW

**Comment by brettfo** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4015/
// Retest reason: no test results produced

**Comment by brettfo** [comment]
Windows unit test failures due to #8807.

**Comment by brettfo** [comment]
ETA failures are fixed by #8920.  I'll hold off merging until that commit makes its way into `future`.

**Comment by brettfo** [comment]
PR updated to latest commit and merge conflicts resolved.  Pinging for final signoff.

**Comment by Pilchie** [comment]
:+1: from me.  Sorry it took so long to review.

**Comment by brettfo** [comment]
I have previously gotten an OK to merge from @jasonmalinowski and @CyrusNajmabadi on the old version of this PR that was targeting `master` (#7540) so I'm going to assume those apply here as well since nothing changed.  Merging.

**Pull request merged**
