### PR TITLE
Revert PR #65590

### PR DESCRIPTION
**Pull request by allisonchou**
Test revert of 65590 to diagnose RPS issues.

### CODE REVIEW

**Comment by allisonchou** [comment]
PR validation: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=7023013&view=results

**Comment by CyrusNajmabadi** [comment]
What's the rps issue in particular?

**Comment by allisonchou** [comment]
Primarily a refset failure - https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/437918

**Comment by allisonchou** [comment]
This PR turned out to be the culprit. Closing and creating new revert PRs targeting the proper branches

**Pull request closed without merging**
