### PR TITLE
Do not override assembly version in non-official builds

### PR DESCRIPTION
**Pull request by tmat**
The toolset sets the assembly version to 42.42.42.42 if not set explicitly.

### CODE REVIEW

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
test windows_coreclr_debug_prtest please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest  please

**Comment by tmat** [comment]
@jasonmalinowski @agocke

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by agocke** [comment]
This looks good, but I think we may have another bug. I'm not sure we're setting OfficialBuildId -- and if we're not I think we're going to get the wrong info.

The signed build uses UTC time to grab its build number -- but it looks like we use DateTime.Now(), which is pacific time. We should probably switch to also using UTC time.

**Comment by tmat** [comment]
Yes, good point. We need to update the build definition to set OfficialBuildId.

**Pull request merged**
