### PR TITLE
Reduce allocations for IsGeneratedCode analysis in the analyzer driver.

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
@basoundr @Srivatsn @heejaechang can you please review?

**Comment by heejaechang** [comment]
:+1:

**Comment by mavasani** [comment]
FYI: ETA is heavily backed off, so I talked to @davkean who is fine with skipping the ETA run. We want to get this merge in soon.

**Comment by srivatsn** [comment]
:+1:

**Comment by mavasani** [comment]
4 unit tests PRs have passed - so merging this in.

**Pull request merged**
