### PR TITLE
[PR For Personal Review Only] 'me' parameter specifier for VB

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
# PR For Personal Review Only
## 'Me' Parameter Specifier for VB

- [ ] Definition
Same semantic usage rules as the attribute  `<System.RunTime.CompilerServices.Extension()>`
Must be on first parameter, and only first parameter. 
- [x] Parser Support
- [ ] Semantics / Binder Support
- [ ] Synthesis of the method attribute `<System.RunTime.CompilerServices.Extension()>` 
- [ ] Unit Tests
- [ ] Error Messages *(needs reworking)*

**Example**

```vbnet
Public Module Exts
  Public Function IsEven(Me Value As Integer) As Boolean
    Return Value Mod 2 = 0
  End Function

  Public Function IsOdd(Me Value As Integer) As Boolean
    Return Value Mod 2 = 1
  End Function

End Module
```
will be functionally equivalent to have then `<System.RunTime.CompilerServices.Extension()>` attribute on the method.

```vbnet
Public Module Exts
  <System.RunTime.CompilerServices.Extension()>
  Public Function IsEven(Value As Integer) As Boolean
    Return Value Mod 2 = 0
  End Function

  <System.RunTime.CompilerServices.Extension()>
  Public Function IsOdd(Value As Integer) As Boolean
    Return Value Mod 2 = 1
  End Function

End Module
```

### CODE REVIEW

**Comment by tannergooding** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by AdamSpeight2008** [comment]
@tannergooding Don't have test this as it an experimental branch, not ready for prototyping yet.

**Comment by tannergooding** [comment]
@AdamSpeight2008, I realize that, but this PR doesn't impact the integration tests and I was validating that the flakiness issue had gone away (multiple PRs were hit) 😄

**Comment by AdamSpeight2008** [comment]
@tannergooding Could you do #17134 as that is being reviewed for a potential merge.

**Pull request closed without merging**
