### PR TITLE
New version of Mono for Mac

### PR DESCRIPTION
**Pull request by jaredpar**

### CODE REVIEW

**Comment by jaredpar** [comment]
Trying out mono 4.2.1.60 for Mac.  Locally it seems to be more stable, want to try out in the lab.

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-infrastructure, @agocke

**Comment by jaredpar** [comment]
retest windows please

**Comment by agocke** [comment]
New instructions are https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/mono-toolset.md btw

**Pull request merged**
