### PR TITLE
don't assume all reference spans in an inline rename session are projected into the current view

### LINKED ISSUE #6821: VS2015.1 RC: Crash when inline renaming model type
Stacktrace obtained from attaching VS to VS:
```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.SelectionTracking.<>c__DisplayClass5_0.<.ctor>b__0(KeyValuePair`2 kvp)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.SelectionTracking..ctor(OpenTextBufferManager openTextBufferManager)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.ApplyConflictResolutionEdits(IInlineRenameReplacementInfo conflictResolution, IEnumerable`1 documents, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.ApplyReplacements(IInlineRenameReplacementInfo replacementInfo, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.<>c__DisplayClass63_0.<UpdateConflictResolutionTask>b__1(Task`1 t)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass4_0`1.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass1_0.<SafeContinueWith>b__0(Task antecedent)
   at Roslyn.Utilities.TaskExtensions.<>c__DisplayClass5_0`1.<SafeContinueWith>b__0(Task t)
```

I have two files, `Models.cs` and `EmailTemplate.cshtml` (latter using RazorEngine as email templating engine) in a web Project. The `EmailTemplate.cshtml` has a `@model SampleType` directive. When both files are opened and i try to rename `SampleType` inside `Models.cs`, VS will Crash. When i close `EmailTemplate.cshtml` prior to starting the inline rename, VS won't Crash.

### PR DESCRIPTION
**Pull request by brettfo**
_This is the same as #8646 but against `stabilization`._

The Razor directives `@model` and `@inherits` have reference spans in the underlying generated file that aren't projected to the current Razor view and inline rename makes an incorrect assumption that all reference spans are projected.

This removes that assumption.

Also included in this PR is a temporary workaround for `@model` projections getting out of sync with the backing buffer that disables live-preview in Razor files during inline rename.  Below is the out-of-sync behavior that can lead to a crash:

model

The new no-live-update behavior is previewed below.  In an offline discussion this behavior was considered acceptable as a workaround for the crash/out-of-sync-projections because the user only notices it if both .cs and .cshtml files are visible at the same time (Razor currently doesn't support invoking cross-file reference inline rename directly from the .cshtml editor anyways.)

no-live-update

Partially fixes #6821 and internal bug 182787.

### Other fixes included here:

There was also an issue discovered while testing that could cause a crash regarding certain Razor directives when typing and that's addressed in commit 8b48c5b.  This issue doesn't repro in released builds of VS but does repro on the latest internal-only builds.  I was able to confirm the crash and subsequently the fix by building the latest bits locally.

### CODE REVIEW

**Comment by brettfo** [comment]
Not sure when the ETA queue will be back up, but I've address the test failures we were seeing in previous iterations of this.

This PR was originally #8646 so re-tagging appropriate parties here for (re?) review:
@dotnet/roslyn-ide 
@toddgrunn

**Comment by brettfo** [comment]
Also tagging @Pilchie / @MattGertz for ask-mode approval.

**Comment by MattGertz** [comment]
Bonus points for the animation -- that's _extremely _helpful for understanding the issue.  The scenario meets the bar; approved pending successful completion of tests and code reviews.

**Comment by brettfo** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4598/
// Retest reason: Possible flaky test.  Filed #9349 and investigating.

**Comment by Pilchie** [comment]
:+1:

**Comment by brettfo** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4657/
// Retest reason: Potential flaky test.  Investigating offline.

@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4647/
// Retest reason: Jenkins timeout when building.

**Comment by jmarolf** [comment]
:+1:

**Pull request merged**
