### PR TITLE
Re-unskip code model tests

### PR DESCRIPTION
**Pull request by DustinCampbell**
It appears that a handful of code model tests that were previously skipped and then unskipped, were inadvertently re-skipped by commit: https://github.com/dotnet/roslyn/commit/978df2e2d505d6326017ae79307ff9ac7283d5ff.

This change puts things back the way they were before.

Tagging @dotnet/roslyn-ide, @jaredpar

### CODE REVIEW

**Comment by jaredpar** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by DustinCampbell** [comment]
test linux please

**Comment by DustinCampbell** [comment]
test mac please

**Comment by DustinCampbell** [comment]
test eta please

**Pull request merged**
