### PR TITLE
Fix crash with fsharp project references

### PR DESCRIPTION
**Pull request by jmarolf**
**Customer scenario:** Create a new F# project with dotnet cli, open the project with Visual Studio, add a C# project, and reference the F# project from the C# project.
**Bugs this fixes:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/461967
**Workarounds, if any:** nothing good.
**Risk:** low.
**Performance impact:** none. Just an additional check in a relatively rare codepath.
**Is this a regression from a previous update?** yes, ish. Referencing F# from C# in older project types worked fine, but with newer project types it's broken due to us using more of CPS.
**Root cause analysis:** normally, adding a project reference from one project to another when they're different languages is done via telling one project about the output assembly of the other, adding it as a metadata reference. To create live IntelliSense cross-language for C#/VB, we try to convert this back to a project reference in our project model. We did this conversion for C#-to-F#, which wasn't going to work because F# doesn't fit other parts of the Roslyn model. This didn't crash previously because F# projects didn't always have output paths, so we couldn't do the matching to try to convert. A unit test has been added.
**How was the bug found?** Windows Error Reporting hits.

### CODE REVIEW

**Comment by jmarolf** [comment]
@Pilchie @jasonmalinowski creating a PR against dev15.3.x

**Comment by Pilchie** [comment]
Good catch on the branch!

**Comment by jmarolf** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by jasonmalinowski** [comment]
Ouch, yep, good catch!

**Comment by Pilchie** [comment]
Hit `System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.` 

Tagging @dpoeschl, but merging with Admin privileges.

**Comment by dpoeschl** [comment]
:+1: to admin merge

**Pull request merged**
