### PR TITLE
Special case Conversions and BadExpressions with missing syntax to ha…

### PR DESCRIPTION
**Pull request by 333fred**
…ve no type. I've verified that for all the IInvalidExpression changes, we are matching SemanticModel behavior. There is a bit of oddity with the VB ISyntheticReference changes, because VB For loops are currently doing a bunch of code generation. This should be resolved by https://github.com/dotnet/roslyn/issues/21282, which is PR here: https://github.com/dotnet/roslyn/pull/21791. Tagging @dotnet/analyzer-ioperation @dotnet/roslyn-compiler.

Fixes https://github.com/dotnet/roslyn/issues/20175

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Test windows_debug_vs-integration_prtest please

**Review by AlekseyTs — APPROVED** [review]
LGTM

**Comment by 333fred** [comment]
@dotnet/analyzer-ioperation @dotnet/roslyn-compiler ping for a review from each, please.

**Review by mavasani — APPROVED** [review]

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler @cston I need another review, please.

**Review by cston — APPROVED** [review]

**Pull request merged**
