### PR TITLE
Revert "Allow source based test discovery to access ISolutionCrawlerService"

### PR DESCRIPTION
**Pull request by sharwell**
Reverts dotnet/roslyn#34534

A proxy will be added to **Microsoft.CodeAnalysis.ExternalAccess.[SomethingTest]** instead, following the new IVT policies.

### CODE REVIEW

**Comment by sharwell** [comment]
I reached out to @shyamnamboodiripad directly and will assist in creation of the external access assembly.

**Comment by sharwell** [comment]
@shyamnamboodiripad the external access assembly is already submitted for review in #34552.

**Comment by shyamnamboodiripad** [comment]
Tagging @jinujoseph

I agree with @sharwell and @heejaechang that we should move the unit testing dependencies to ExternalAccess model - I fully understand the benefits of doing this from both Roslyn side as well as unit testing side. However, I'd prefer that we add the ExternalAccess shims for all existing unit testing usages in one go rather than doing this for just the new dependency that we want to consume currently.

I'd rather that we didn't have to deal with any fall out from an ExternalAccess change right now (like any RPS regressions due to the extra assembly dependency etc.) given that we are really pushing hard against the clock to get all the unit testing changes merged.

Please let me know if you would like me to log a follow up internal bug on our side to move to the ExternalAccess model for all our dependencies (i.e. to complete the work started in #34552).

**Comment by sharwell** [comment]
After further discussion, I agreed to relax my arguments for following the new design here in exchange for getting preapproval for all assembly loads in question and eliminate _all_ current external IVTs to assemblies that ship with Visual Studio for 16.2 Preview 1.

**Pull request closed without merging**
