### PR TITLE
DiaSymReader build improvements towards moving it to a separate repo

### PR DESCRIPTION
**Pull request by tmat**
Implements more separation of DiaSymReader build from the rest of Roslyn.

First, factors version definitions out of VSL.Settings.targets into a separate VSL.Versions.targets file. The remaining Settings.targets are generally useful helpers that can be reused by other components that version separately from Roslyn binaries/nugets. We can further factor VSIX and VS specific handling.

Second, only import Settings.targets from DSR and set the OutDir to a subdirectory, so that it doesn't collide with the DSR copied from nuget cache when restoring nugets for Roslyn.sln. Finally, fix AssemblyFileVersion generation for DSR.

### CODE REVIEW

**Comment by tmat** [comment]
@jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
Of the stuff that's left in Settings.targets, what does DiasymReader actually need/want? Do you have any sense of how that might be further refactored? Looking at it, it doesn't look like there's much you want there either, and I'm wondering if it's just easier to cut your dependency entirely.

**Comment by jasonmalinowski** [comment]
:+1:.

**Comment by tmat** [comment]
I think we can factor out all stuff related to VSIX/VS. We could even avoid referencing that stuff from compiler projects. There is also fake signing (which will go away once we ship compilers with open sign options support). 

What would be left is a bunch of small tweaks that look like bugfixes to msbuild :) that I don't want to reinvent, and some default value setting which is generally sane. I'd like to keep those.

**Comment by tmat** [comment]
Searching for usage of $(OutDir) I found we are not as consistent on \ as we should be. Also many places don't quote it when building a command line :( I'll file an issue to fix these.

**Pull request merged**
