### PR TITLE
Update prerelease nuget version for Dev15 Preview 3

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
Update prerelease nuget version from 'beta1' to 'beta3' for Dev15 Preview 3

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@jasonmalinowski @natidea @dotnet/roslyn-infrastructure

**Comment by shyamnamboodiripad** [comment]
Ping @jasonmalinowski @natidea @tannergooding @tmat @dotnet/roslyn-infrastructure

**Comment by natidea** [comment]
:+1:

This is an Ask Mode change @MattGertz

**Comment by tmat** [comment]
:+1:

**Pull request merged**
