### PR TITLE
Self host our own compiler package

### PR DESCRIPTION
**Pull request by VSadov**

### CODE REVIEW

**Comment by VSadov** [comment]
test ubuntu_16_debug_prtest please

**Comment by VSadov** [comment]
error CS0234: The type or namespace name 'Loader' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?) [/mnt/j/workspace/dotnet_roslyn/features_readonly-ref/ubuntu_16_debug_prtest/src/Scripting/Core/Scripting.csproj]

I think I have seen that before. Interesting, if reproduces...

**Comment by VSadov** [comment]
Microsoft.CodeAnalysis.CSharp.UnitTests.Semantics.StructsTests.TestOverridingBaseConstructorStruct [FAIL]

That is odd . . .

**Comment by VSadov** [comment]
test windows_debug_unit64_prtest please

**Comment by VSadov** [comment]
test windows_debug_unit64_prtest please

**Comment by agocke** [comment]
Looks like you found the test failure. I guess it may be a compiler change

**Comment by jcouv** [comment]
We'll need to be careful not to merge this back into master. I'd expect it will show up as a conflict, but it's still probably good to keep track of that.

**Pull request closed without merging**
