### PR TITLE
Merge master indo dev15.6

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @dotnet/roslyn-infrastructure

**Comment by jasonmalinowski** [comment]
@tmeschter It surprises me there's commits that old in this. Does this look right?

**Comment by tmeschter** [comment]
@jasonmalinowski That looks right. The generated merge from last night had the same set of commits (minus the most recent) but I haven't merged it in yet as I was waiting for test runs to complete.

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit64_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
retest windows_release_vs-integration_prtest please

**Pull request merged**
