### PR TITLE
Update PublicAPI.Shipped.txt for what we shipped in 1.3.2

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Updating the shipped lists with what we added in 1.3.2.

*Review:* @dotnet/roslyn-infrastructure, @Pilchie

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Also @mavasani, @Srivatsn, @jaredpar. For the compiler layer, I moved in all things not related (as best I could tell) with IOperation.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, restest please, now that the branch is in a happy state.

**Comment by jasonmalinowski** [comment]
@dotnet-bot, restest this please, now that the branch is in a happy state.

**Comment by Pilchie** [comment]
:+1:

**Comment by srivatsn** [comment]
👍

**Pull request merged**
