### PR TITLE
Update System.Reflection.Metadata to 1.2.0-rc2-23826

### PR DESCRIPTION
**Pull request by tmat**
This build includes IBC data.
Fixes internal bug 191268

### CODE REVIEW

**Comment by jaredpar** [comment]
Shouldn't we be upgrading to a RTM version in the stabilization branch?

**Comment by tmat** [comment]
@jaredpar There is no RTM version available yet. We'll need to update one more time.

**Comment by jaredpar** [comment]
@tmat gotcha.  Do we have a bug tracking that?

**Comment by tmat** [comment]
@jaredpar I think there is one to make sure all dependencies are RTM. Can't find it atm.

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4417/
// Retest reason: https://github.com/dotnet/roslyn/issues/9247

**Pull request merged**
