### PR TITLE
Delete extra "Return True"

### PR DESCRIPTION
**Pull request by Youssef1313**
Introduced in #712

### CODE REVIEW

**Review by jmarolf — APPROVED** [review]

**Comment by alrz** [comment]
wait, we dont warn on unreachable code?

**Comment by Youssef1313** [comment]
@alrz I was surprised too, but looks like the case with VB.

**Comment by CyrusNajmabadi** [comment]
VB doens't have the concept.  I believe there's an issue tracking that we would take a PR here to add such a thing as an analyzer.

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 1)

**Review by 333fred — APPROVED** [review]

**Comment by 333fred** [comment]
Thanks Youseff!

**Pull request merged**
