### PR TITLE
Merge master into features extension foreach

### PR DESCRIPTION
**Pull request by YairHalberstadt**
Fix NullableReferenceTypeTests by removing warnings suppressed by https://github.com/dotnet/roslyn/commit/53b2957f2e08a05dc718cbc5ffb9efc60c4cec34

### CODE REVIEW

**Comment by YairHalberstadt** [comment]
@333fred

**Comment by 333fred** [comment]
@YairHalberstadt I hate to be a pain, but can you please separate the changes you needed to make to the baselines in the merge from master from the actual merge commit? It's impossible to review the diff currently.

**Comment by YairHalberstadt** [comment]
> @YairHalberstadt I hate to be a pain, but can you please separate the changes you needed to make to the baselines in the merge from master from the actual merge commit? It's impossible to review the diff currently.

Sorry that was a mistake, which I realized straight after commiting. Not sure best way to fix now, so I'll link to the lines which changed:

https://github.com/dotnet/roslyn/pull/46505/files?file-filters%5B%5D=.cs#diff-4ef499b331bacc63b10e31e95a00db61L72694-L73301

There are 6 tests which changed, in all of them I simply removed a diagnostic.

**Comment by YairHalberstadt** [comment]
Link doesn't seem to have worked. That's NullableReferenceTypesTests.cs lines 72694-73301

**Comment by 333fred** [comment]
> Alternatively I can reset the merge commit and force push.

If you could, that would be appreciated. Thanks.

**Comment by YairHalberstadt** [comment]
@333fred done

**Comment by YairHalberstadt** [comment]
Closing and reopening to diagnose seemingly random test failures.

**Comment by YairHalberstadt** [comment]
There seems to be a few randomly occuring `System.ArgumentException : Illegal characters in path.` errors which are nothing to do with my changes

**Pull request merged**
