### PR TITLE
Move to a newer version of CoreCLR

### PR DESCRIPTION
**Pull request by AlekseyTs**
Microsoft.NETCore.App 3.0.0-preview6-27706-07, SDK version 3.0.100-preview6-011773

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler, @jaredpar Please review.

**Comment by sharwell** [comment]
@AlekseyTs @jaredpar @nguerrera Can we please stop updating this version until the following two items are resolved:

1. Visual Studio has a sane error message for this case.
2. It is *possible* to locate, download, and install the correct version. Either of the following would be acceptable:
    1. The download is the current preview version listed on dotnet.microsoft.com
    2. The build error when using the wrong version links to the correct version

**Comment by jaredpar** [comment]
@sharwell 

> Can we please stop updating this version until the following two items are resolved:

No. The compiler team depends on the runtime / SDK for testing features we're shipping in C# 8.0. It's important for us to update regularly here to ensure our features continue to work properly. 

> Visual Studio has a sane error message for this case.

I'm sympathetic to this case and wish VS was less silent here. But it's an orthogonal issue to us verifying that we're shipping a solid product. I encourage you to reach out ot the product team directly on this.

**Comment by jcouv** [comment]
> The current error message is [bad]

If there is a known pitfall in the short-term, can someone pro-actively message the team as a mitigation?
For the long-term, did we file an issue or communicate some asks to improve the situation?

**Comment by jaredpar** [comment]
@jcouv 

> If there is a known pitfall in the short-term, can someone pro-actively message the team as a mitigation?
For the long-term, did we file an issue or communicate some asks to improve the situation?

The CLI / SDK team is aware of this problem. I'm not sure there are plans to fix it at the moment. But @KathleenDollard, @nguerrera can comment on it.

**Comment by sharwell** [comment]
Also note that in the case of *this* upgrade, installing the new preview broke the build for branches that are still configured to use preview5.

**Comment by jaredpar** [comment]
> Also note that in the case of this upgrade, installing the new preview broke the build for branches that are still configured to use preview5.

Again seems like an excellent discussion to have with the SDK / CLI team. I've personally sent over my scenarios, and how the decisions they've made have increased the maintenance burden on repository owners. The behavior is still what it is and we can't block product evolution on this. 

Have you emailed the *product* owners here or just commenting on our usage of the product?

**Comment by AlekseyTs** [comment]
@sharwell Just an FYI, the https://github.com/dotnet/roslyn/blob/master/docs/contributing/Building%2C%20Debugging%2C%20and%20Testing%20on%20Windows.md document has the link to the SDK installer - https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview6-011773/dotnet-sdk-3.0.100-preview6-011773-win-x64.exe. If you need a link for an installer for a different platform, you can find that from the console output of the corresponding CI job for a PR in Roslyn, the first thing CI job does, it downloads the SDK.

**Pull request merged**
