### PR TITLE
Support CallerArgumentExpressionAttribute

### PR DESCRIPTION
**Pull request by alrz**
Proposal: https://github.com/dotnet/csharplang/issues/287

### CODE REVIEW

**Comment by alrz** [comment]
@jcouv Are you ok with proposed refactorings? namely, unification of diagnostics and introducing CallerInfoAttributeData to streamline attribute handling for caller info attributes. Note: The fix for https://github.com/dotnet/roslyn/issues/23824 would help to shape the new api to diagnose and resolve multiple attributes. Also. I'm not aware if we want to pursue any other caller info attributes e.g. https://github.com/dotnet/csharplang/issues/87. Let me know if I should consider any particular approach to move this forward. Thanks.

**Comment by HaloFour** [comment]
@alrz 

I was just about to ping about the other caller member attributes.  Thanks for bringing it up.  

I was hoping that they could be evaluated as a set during the LDMs and I am a little dismayed that `CallerArgumentExpression` is sailing through solo.

**Comment by jcouv** [comment]
@alrz Thanks, I'll look at the change tonight.

Are you interested in creating the type too? See https://github.com/dotnet/corefx/issues/21809 which is calling for a contributor. 

If LDM is supportive of some of the other similar attributes (https://github.com/dotnet/csharplang/issues/87), any chance you might be interested to implement those (API+compiler) as well?

**Comment by alrz** [comment]
I'm not familiar with corefx API process but I'll try to open a PR there to kick-start the change. I'm up for extending this with other attributes as well but probably it's best to do this in follow-up PRs when we have a solid ground for additions. Thanks.

**Comment by jcouv** [comment]
Sounds great. Yes, other attributes would definitely be separate PRs. LDM first needs to review and prune the proposed list.

**Comment by jcouv** [comment]
LDM reviewed caller expression today and found the current design acceptable. The concern about breaking changes for API authors incorporating this attribute is mitigated in a few ways (they can change API name, take the binary breaking change, or they can do some ref assembly tricks). More details in the LDM notes once they are published.

**Comment by jcouv** [comment]
Tagging @jaredpar since there is a type dependency for this compiler feature. He's driving a related discussion which could affect this feature being in C# 7.3 (versus 8.0). 
I'll let him comment once he has the information (probably next week).

**Comment by alrz** [comment]
@jcouv Should this be rebased to compilerNext as well? What is the resolution on https://github.com/dotnet/roslyn/pull/23861#issuecomment-352897305? Thanks.

**Comment by alrz** [comment]
The branch is outdated. Closing.
Let me know if/when we want to move forward with this.

**Pull request closed without merging**
