### PR TITLE
[AskMode] Rename MS.CA.Scripting.CSharp to MS.CA.CSharp.Scripting...

### PR DESCRIPTION
**Pull request by KevinH-MS**
...and update namespaces contained therein accordingly.

### CODE REVIEW

**Comment by davkean** [comment]
LGTM. Are there corresponding internal changes?

**Comment by KevinH-MS** [comment]
@davkean Yeah, I'm working on those now.

**Comment by KevinH-MS** [comment]
FYI @dotnet/interactive

**Comment by ManishJayaswal** [comment]
:+1: 
Let's stage this in master first.
@tannergooding FYI for insertion changes and dry run by inserting into vsuml
@jinujoseph FYI we will need to get this localized

**Comment by tannergooding** [comment]
@ManishJayaswal, @jinujoseph. The localization already exists, we just need to coordinate with the localization team to get the translation files renamed.

**Comment by davkean** [comment]
ETA failure is tracked by #6099.

**Comment by genlu** [comment]
:+1: Is there a issue for rename MS.CA.Scripting.VB?

**Comment by MattGertz** [comment]
Approved pending successful test completion.

**Comment by KevinH-MS** [comment]
@genlu I'm going to leave #5556 open until VB is also fixed (in master).

**Comment by davkean** [comment]
eta failed to out of disk space issue, which we've long since resolved

retest eta please

**Comment by KevinH-MS** [comment]
Test failures due to #6291

**Pull request merged**
