### PR TITLE
Add quick-info support for ref members and locals.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler  @jaredpar   This change includes public API changes so that we can determine if a local is a 'ref local', and a new SymbolDisplay optoin to let people request if 'ref' is included when getting the symbol display for a local.

This is necessary to complete the experience around ref-locals and ref-returning members in the IDE.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide  for IDE changes.

**Comment by Pilchie** [comment]
Tagging @MattGertz for RTW approval.

**Comment by MattGertz** [comment]
@Pilchie @CyrusNajmabadi Template?  I'll go ahead & set to pending, but we'll need it for Shiproom.

**Comment by CyrusNajmabadi** [comment]
**Customer scenario**

Customer starts using the new C# 'ref-locals/ref-returning-members' feature in the IDE.  Unfortunately, core IDE features (like QuickInfo) don't properly convey this information to the user, making development more different.

**Bugs this fixes:** 

https://github.com/dotnet/roslyn/issues/13514

**Workarounds, if any**

None.

**Risk**

Extremely low.

**Performance impact**

Extremely low.

**Is this a regression from a previous update?**

No.  These are new language features.  We simply didn't do all the necessary work to thread the information through all our features.

**Root cause analysis:**

This was not missed.  It simply took time to get the pieces in place to complete the story.

**How was the bug found?**

Found during the design of the feature.  It just took a while for all the necessary APIs to be in place to support this.

**Comment by CyrusNajmabadi** [comment]
Done @MattGertz

**Comment by natidea** [comment]
Copied Ask Mode to [366706](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/366706)

**Comment by natidea** [comment]
@MattGertz to "Approve to merge" for RTW

**Pull request merged**
