### PR TITLE
[17.10] Disable nullable comparison optimization for decimals

### PR DESCRIPTION
**Pull request by jjonescz**
Cherry-pick of https://github.com/dotnet/roslyn/pull/73536.

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Comment by kirsan31** [comment]
In what version of VS 17.10 this will be deployed?

**Comment by cremor** [comment]
I assume a new SDK version with the fix will be released at the same time as VS 17.10.1?

**Comment by cremor** [comment]
So, has this been fixed in 17.10.1? Because the release notes page still mentions the known issue.
If it has been fixed, is it also fixed in SDK 8.0.301?

**Comment by jjonescz** [comment]
Sorry, it looks like the fix did not make it into SDK 8.0.301; it will be in 8.0.302. I think it should be fixed in VS 17.10.1 (if you build from inside VS).

**Comment by cremor** [comment]
Is it fixed in SDK 8.0.302?
If it is then I think the point should be removed from the [known issues list](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#known-issues).

**Comment by kirsan31** [comment]
17.10.**3** already, and the bug still exist in [known issues](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#known-issues) 🤷‍♂️
Can any one clarify?

**Comment by cremor** [comment]
> But if you have SDK 8.0.3xx (and build using `dotnet build` command for example), the bug is still there; should be fixed in 8.0.303

TBH I find this quite irritating. The bug was so severe that it:
- Made it in the known issues list of Visual Studio
- Was fixed in just 2 days.
- Was released with a new Visual Studio update in just 8 days.

But still, now 6 weeks later, there is no SDK release with the fix. In my opinion, the SDK is way more important than VS because the SDK is what actually compiles our release software on build agents.

**Comment by kirsan31** [comment]
Can any one confirm that this was deployed in 8.0.30**3**?

**Comment by jjonescz** [comment]
> Can any one confirm that this was deployed in 8.0.30**3**?

Yes, this fix is part of SDK 8.0.303.

**Pull request merged**
