### PR TITLE
Fix #55183: Add SymbolVisitor<TArgument, TResult>

### LINKED ISSUE #55183: Add SymbolVisitor<TArgument, TResult>
## Background and Motivation

In order to avoid shared state and allowing parallel invocations of the same visitor, it would be nice to be able to use a `SymbolVisitor<TArgument, TResult>`. We already have a similar pattern with [OperationVisitor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.operations.operationvisitor-2?view=roslyn-dotnet-3.10.0).

## Proposed API

```diff
namespace Microsoft.CodeAnalysis
{
+    public abstract class SymbolVisitor<TArgument, TResult>
+    {
+        public virtual TResult? Visit(ISymbol? symbol, TArgument argument)
+        {
+            if (symbol != null)
+            {
+                return symbol.Accept(this, argument);
+            }
+
+            return default(TResult);
+        }
+
+        public virtual TResult? DefaultVisit(ISymbol symbol, TArgument argument)
+        {
+            return default(TResult);
+        }
+
+        public virtual TResult? VisitAlias(IAliasSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitArrayType(IArrayTypeSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitAssembly(IAssemblySymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitDiscard(IDiscardSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitDynamicType(IDynamicTypeSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitEvent(IEventSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitField(IFieldSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitLabel(ILabelSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitLocal(ILocalSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitMethod(IMethodSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitModule(IModuleSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitNamedType(INamedTypeSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitNamespace(INamespaceSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitParameter(IParameterSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitPointerType(IPointerTypeSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitFunctionPointerType(IFunctionPointerTypeSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitProperty(IPropertySymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitRangeVariable(IRangeVariableSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+
+        public virtual TResult? VisitTypeParameter(ITypeParameterSymbol symbol, TArgument argument)
+        {
+            return DefaultVisit(symbol, argument);
+        }
+    }

	public interface ISymbol : IEquatable<ISymbol?>
    {
		// ...
        void Accept(SymbolVisitor visitor);

        TResult? Accept<TResult>(SymbolVisitor<TResult> visitor);

+        TResult? Accept<TArgument, TResult>(SymbolVisitor<TArgument, TResult> visitor, TArgument argument);
		// ...
    }
}
```

## Usage Examples

``` C#
      var result = symbol.Accept(new GenerateIdVisitor(), new GeneratorContext());
```

## Alternative Designs

It would be possible to implement a visitor based on dynamic invocation, however, I think this is not the optimal solution.

## Risks

none I can think of

### PR DESCRIPTION
**Pull request by siegfriedpammer**
Fixes https://github.com/dotnet/roslyn/issues/55183

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@333fred are we waiting until main becomes 17.1 to review/merge this? Or can it go into 17.0?

**Comment by 333fred** [comment]
Not sure what the bar for 17.0 is at this point. @jaredpar?

**Review by 333fred — COMMENTED** [review]
We do need to have explicit testing of the new visitor.

**Comment by jcouv** [comment]
@siegfriedpammer Let us know if you need some pointers on how to test this change. Thanks

**Comment by siegfriedpammer** [comment]
I tried looking for tests of the other visitors however, I could not find any samples. Any pointers would be appreciated. Thanks!

**Comment by jcouv** [comment]
I would create a new test file under `src\Compilers\CSharp\Test\Symbol\Compilation` called `SymbolVisitorTests.cs` with a nested type that implements the new `SymbolVisitor` with simple traversal and logging (adding some text to a `StringBuilder`).
Then create a simple program with various kinds of symbols (types, methods, aliases, etc. We can assist if you're not sure how to reach some of the cases), make a compilation with it (`CreateCompilation` test helper), grab its `.SourceAssembly`, use the visitor on it and verify the contents of the builder.
Then something similar for VB.

Let me know if that makes sense.

**Comment by jcouv** [comment]
Marking this PR as draft for now (to make room in our review queue while the PR is being worked on). Please ping if you have any questions or when ready for another look.

**Comment by 333fred** [comment]
@siegfriedpammer is there anything you need from us to address feedback? Feel free to chat here, or I'm available on discord (id Orannis#3333).

**Comment by siegfriedpammer** [comment]
Currently I am experiencing a few issues when trying to work with Roslyn.sln. VS 2019 won't run unit tests anymore and VS 2022 refuses to show any editor windows.

image

**Comment by siegfriedpammer** [comment]
Now it finally displays the tests, in the pane to the left, but also printed this exception to the output.

```
Log level is set to Informational (Default).
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation. ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at MS.Internal.Text.TextInterface.Native.Util.ConvertHresultToException(Int32 hr)
   at MS.Internal.Text.TextInterface.FontList.get_Item(UInt32 A_0)
   at MS.Internal.FontFace.PhysicalFontFamily.MapGlyphTypeface(FontStyle style, FontWeight weight, FontStretch stretch, CharacterBufferRange charString, CultureInfo digitCulture, Int32& advance, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFaceFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Boolean nullFont, Double scaleInEm, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Boolean ignoreMissing, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFamily(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, IFontFamily fontFamily, CanonicalFontFamilyReference canonicalFamilyReference, FontStyle canonicalStyle, FontWeight canonicalWeight, FontStretch canonicalStretch, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapOnceByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapByFontFamilyList(CharacterBufferRange unicodeString, CultureInfo culture, CultureInfo digitCulture, FontFamily[] familyList, PhysicalFontFamily& firstValidFamily, Int32& firstValidLength, IDeviceFont deviceFont, Double scaleInEm, Int32 recursionDepth, SpanVector scaledTypefaceSpans, Int32 firstCharIndex, Int32& nextValid)
   at MS.Internal.Shaping.TypefaceMap.MapItem(CharacterBufferRange unicodeString, CultureInfo culture, Span itemSpan, SpanVector`1& cachedScaledTypefaceIndexSpans, Int32 ichItem)
   at MS.Internal.Shaping.TypefaceMap.GetShapeableText(CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
   at MS.Internal.Shaping.GlyphingCache.GetShapeableText(Typeface typeface, CharacterBufferReference characterBufferReference, Int32 stringLength, TextRunProperties textRunProperties, CultureInfo digitCulture, Boolean isRightToLeftParagraph, IList`1 shapeableList, IShapeableTextCollector collector, TextFormattingMode textFormattingMode)
   at System.Windows.Media.TextFormatting.TextCharacters.MS.Internal.TextFormatting.ITextSymbols.GetTextShapeableSymbols(GlyphingCache glyphingCache, CharacterBufferReference characterBufferReference, Int32 length, Boolean rightToLeft, Boolean isRightToLeftParagraph, CultureInfo digitCulture, TextModifierScope textModifierScope, TextFormattingMode textFormattingMode, Boolean isSideways)
   at MS.Internal.TextFormatting.TextStore.CreateTextLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
   at MS.Internal.TextFormatting.TextStore.CreateLSRuns(TextRunInfo runInfo, IList`1 textEffects, CultureInfo digitCulture, Int32 offsetToFirstChar, Int32 stringLength, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel, Int32& textRunLength)
   at MS.Internal.TextFormatting.TextStore.CreateLSRunsUniformBidiLevel(SpanVector runInfoVector, SpanVector textEffectsVector, Int32 runInfoFirstCp, Int32 ichUniform, Int32 cchUniform, Int32 uniformBidiLevel, TextFormattingMode textFormattingMode, Boolean isSideways, Int32& lastBidiLevel)
   at MS.Internal.TextFormatting.TextStore.FetchLSRun(Int32 lscpFetch, TextFormattingMode textFormattingMode, Boolean isSideways, Plsrun& plsrun, Int32& lsrunOffset, Int32& lsrunLength)
   at MS.Internal.TextFormatting.LineServicesCallbacks.FetchRunRedefined(IntPtr pols, Int32 lscpFetch, Int32 fIsStyle, IntPtr pstyle, Char* pwchTextBuffer, Int32 cchTextBuffer, Int32& fIsBufferUsed, Char*& pwchText, Int32& cchText, Int32& fIsHidden, LsChp& lschp, IntPtr& lsplsrun)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at MS.Internal.TextFormatting.TextMetrics.FullTextLine.FormatLine(FullTextState fullText, Int32 cpFirst, Int32 lineLength, Int32 formatWidth, Int32 finiteFormatWidth, Int32 paragraphWidth, LineFlags lineFlags, FormattedTextSymbols collapsingSymbol)
   at MS.Internal.TextFormatting.TextMetrics.FullTextLine..ctor(FormatSettings settings, Int32 cpFirst, Int32 lineLength, Int32 paragraphWidth, LineFlags lineFlags)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLineInternal(TextSource textSource, Int32 firstCharIndex, Int32 lineLength, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak, TextRunCache textRunCache)
   at MS.Internal.TextFormatting.TextFormatterImp.FormatLine(TextSource textSource, Int32 firstCharIndex, Double paragraphWidth, TextParagraphProperties paragraphProperties, TextLineBreak previousLineBreak)
   at System.Windows.Media.FormattedText.LineEnumerator.FormatLine(TextSource textSource, Int32 textSourcePosition, Double maxLineLength, TextParagraphProperties paraProps, TextLineBreak lineBreak)
   at System.Windows.Media.FormattedText.LineEnumerator.MoveNext()
   at System.Windows.Media.FormattedText.DrawAndCalculateMetrics(DrawingContext dc, Point drawingOffset, Boolean getBlackBoxMetrics)
   at System.Windows.Media.FormattedText.get_Metrics()
   at Microsoft.VisualStudio.Text.Formatting.Implementation.TextInfoCache.GetTextInfo(TextRunProperties key)
   at Microsoft.VisualStudio.Text.Formatting.Implementation.FormattedTextSourceFactoryService.Create(ITextSnapshot sourceTextSnapshot, ITextSnapshot visualBufferSnapshot, Int32 tabSize, Double lineSpacing, Double baseIndentation, Double wordWrapWidth, Double maxAutoIndent, Boolean useDisplayMode, IClassifier aggregateClassifier, ITextAndAdornmentSequencer sequencer, IClassificationFormatMap classificationFormatMap, Boolean isViewWrapEnabled)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PreLayout(LayoutLineCache lineCache)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.PerformLayout(SnapshotPoint anchorPosition, Double verticalDistance, ViewRelativePosition relativeTo, Double effectiveViewportWidth, Double effectiveViewportHeight, Boolean preserveViewportTop, Nullable`1 cancel)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.Initialize()
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.InitializeTextView(IWpfTextView view)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.CreateAndTrackTextView(ITextDataModel dataModel, ITextViewRoleSet roles, IEditorOptions parentOptions, Boolean initialize)
   at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextEditorFactoryService.CreateTextView(ITextBuffer textBuffer, ITextViewRoleSet roles, IEditorOptions parentOptions)
   at Microsoft.VisualStudio.TestWindow.Internal.UI.Summary.SummaryBuilder.InitializeTextView()
   at Microsoft.VisualStudio.TestWindow.Internal.UI.Summary.SummaryControl.<InitializeControlContentAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestWindow.Logging.ILoggerExtensions.<CallWithCatchAsync>d__11`1.MoveNext()
Connected to test environment '< Local Windows Environment >'
Test data store opened in 81,904 sec.
```

**Comment by siegfriedpammer** [comment]
But still no editor windows... :(

**Comment by siegfriedpammer** [comment]
Microsoft Visual Studio Community 2022
Version 17.0.0
VisualStudio.17.Release/17.0.0+31903.59
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Azure App Service Tools v3.0.0   17.0.789.48259
Azure App Service Tools v3.0.0

C# Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   6.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   4.0.0-6.21526.21+c7d6f9fab845ffd943216da465022744e7d35f22
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by siegfriedpammer** [comment]
@333fred I am trying to get this wrapped up. I am not sure how you would approach the topic of unit testing the visitor. I have pushed my first try and of course it is still unfinished. Would it be possible for you to take a look and provide feedback nonetheless? Thanks!

**Comment by 333fred** [comment]
@siegfriedpammer that looks great. Just need some for the new API :).

**Comment by siegfriedpammer** [comment]
Thanks, then I will continue and get this done!

**Review by 333fred — APPROVED** [review]
LGTM (commit 2). @dotnet/roslyn-compiler for a second review.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Review by ryzngard — APPROVED** [review]
IDE code LGTM

**Comment by 333fred** [comment]
Thanks for the contribution @siegfriedpammer!

**Pull request merged**
