### PR TITLE
Unify FindTokenOnLeftOfPosition and FindTokenOnRightOfPosition helpers

### PR DESCRIPTION
**Pull request by DustinCampbell**
In IDE code, the `FindTokenOnLeftOfPosition` and `FindTokenOnRightOfPosition` helpers are duplicated for both C# and VB. This is due to the fact that they require language-specific access to `CompilationUnitSyntax` and `SkippedTokensTriviaSyntax` in order to locate the end-of-file token and any skipped tokens. @cyrusnajmabadi added ICompilationUnitSyntax awhile back to make it easier to find the end-of-file token in a language-neutral way. This change adds `ISkippedTokensTriviaSyntax` to make it easier to identify skipped tokens in a language-neutral manner and unifies the helpers.

cc @AnthonyDGreen + @dotnet/roslyn-compiler for Syntax API change, and @dotnet/roslyn-ide for IDE changes

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Compiler changes LGTM.

**Comment by VSadov** [comment]
LGTM

**Comment by DustinCampbell** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2604/
// Retest reason: it failed with "Mono crashed" and this PR has compiler changes

**Comment by DustinCampbell** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/2699/
// Retest reason: This PR has compiler changes and the failure appears to have been infrastructure-related "Key file X is missing the private key needed for signing"

**Comment by DustinCampbell** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/2621/
// Retest reason: Random failure? The issue is unclear to me. However, this PR includes compiler changes, so it's import to get a successful test run.

**Comment by DustinCampbell** [comment]
Tests are passing. Anyone want to take a look from @dotnet/roslyn-ide?

**Comment by jmarolf** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
:+1:

**Pull request merged**
