### PR TITLE
Mark APIs as shipped

### PR DESCRIPTION
**Pull request by 333fred**
Ran the mark APIs shipped script. Infra-only change.

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet/roslyn-infrastructure for review. @Cosifne FYI, this is likely to cause some merge conflicts as it gets flowed through to main.

**Comment by RikkiGibson** [comment]
Looks like we have Correctness failures related to public API analyzer.

**Comment by 333fred** [comment]
@RikkiGibson please take another look.

**Review by jcouv — APPROVED** [review]
LGTM Thanks (iteration 3)

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
