### PR TITLE
Remove Redundant Cast should not incorrectly suggest to remove a cast within a logical not expression

### LINKED ISSUE #10311: Wrong "Cast is redundant" suggestion when returning negated bool
**Version used**:
Microsoft Visual Studio Enterprise 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

**Steps to Reproduce**:
Write the following code:

    public bool NegateBool(object value)
    {
        // "Cast is redundant".
        return !(bool)value;
    }

2. Follow the suggestion to "Remove Unnecessary Cast".

3. Now the code can't compile: Operator '!' cannot be applied to operand of type 'object'

**Expected Behavior**:
Should not suggest to remove the cast.

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes #10311

cc @dotnet/roslyn-ide

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Anyone from @dotnet/roslyn-ide want to take a look?

**Comment by rchande** [comment]
:+1:

**Comment by DustinCampbell** [comment]
retest this please

**Comment by basoundr** [comment]
👍 Except that the comment says that `cast is redundant`. It was a little confusing

**Comment by DustinCampbell** [comment]
@basoundr -- what comment do you mean?

**Comment by DustinCampbell** [comment]
Oh, I see. The commit comment. There's about four negatives in there. :smile:

**Comment by DustinCampbell** [comment]
Oh I see. The comment in the test code. I literally copied and pasted the code from the reported issue.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Pull request merged**
