### PR TITLE
Remove vb specific deletion code

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p3_open_prtest  please

**Comment by Pilchie** [comment]
:+1: for the new part, once the question about the option is answered.

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p1_open_prtest  please

**Comment by CyrusNajmabadi** [comment]
retest windows_vsi_p1_open_prtest please

**Pull request merged**
