### PR TITLE
close sqlite connection when solution is closed

### PR DESCRIPTION
**Pull request by heejaechang**
previously, we didn't close the db when a solution is closed, but when a new solution is opened. this makes sure that we release the db when solution is closed.

user visible outcome of this is that once solution is closed, user can now delete .vs folder. previously, the user wouldn't be able to delete the folder right after solution is closed.

while looking at this 2 other issues are found. 
one is issue on IVsSolution - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/746630
the other issue is - https://github.com/dotnet/roslyn/issues/31686

this fix is needed regardless of the above 2 issues. but without fixing those 2, persistent service can still get into wrong state where either persistent service becomes noop or connection stay alive until next new solution is opened.

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph for preview 2?

**Comment by heejaechang** [comment]
@CyrusNajmabadi not sure what event you are referring.

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi not sure what event you are referring.

There are other IVsSolutionEvents that we also do not respond to.  Were those audited to see if we might be missing another case that could lead to problems in the future?  Thanks!

**Comment by heejaechang** [comment]
@CyrusNajmabadi for sqlite, I dont think we need any other events. for other components that use IVsSolution events, it would be hard to know whether it gets events the way it wanted before. but those code I dont think recently changed, so without test or dogfooding report, it would be hard to know.

**Comment by heejaechang** [comment]
closed the VS side bug, it turns out IVsSolution had an optimization where if we return E_NOTIMPL for event handler, they stop calling us after that.

**Pull request merged**
