### PR TITLE
Throw in unsupported Tag api

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Followup feedback from https://github.com/dotnet/roslyn/pull/64895

### CODE REVIEW

**Review by genlu — APPROVED** [review]
LGTM as long as we don't throw here. Let me know if validation is needed.

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS-Platform?path=/src/Editor/Text/Impl/Structure/StructureSpanningTree/StructureSpanningTree.cs&version=GBmain&_a=contents

**Comment by CyrusNajmabadi** [comment]
Right.  that one stayed the same :)

**Review by jasonmalinowski — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@genlu @CyrusNajmabadi Although I don't mind this, the one that terrified me the most was the one where we're not returning a valid GetHashCode that _is_ being hashed by the editor. I'd hope we can get a proper implementation for that one at least?

**Comment by CyrusNajmabadi** [comment]
>  I'd hope we can get a proper implementation for that one at least?

Will do.

**Review by genlu — APPROVED** [review]

**Pull request merged**
