### PR TITLE
Fix parsing of lambda parameter named "scoped"

### LINKED ISSUE #63469: "Scoped" word is forbidden since MSBuild version 17.3.0+92e077650
### Issue Description
Using "scoped" identifier in deconstructed tuple doesn't compile. Errors:
CS1001 Identifier expected
CS0246 The type or namespace name 'scoped' could not be found (are you missing a using directive or an assembly reference?)

It happens when calling an extension method accepting a Func with generic arguments.

### Steps to Reproduce
`dotnet new console`
replace Program.cs with:
```cs
("","").ProcessTuple((a, scoped) => "");

public static class Extensions
{
    public static void ProcessTuple<T1, T2>(this (T1, T2) t, Func<T1, T2, string> f)
    {

    }
}
```
`dotnet build` fails with `error CS1001: Identifier expected`

### Analysis
In MSBuild version 17.2.0+41abc5629 similar code works with no issues.
In MSBuild version 17.3.0+92e077650 it fails to compile.
Changing "scoped" to other name resolves the issue, but still an old code won't compile on an environment with latest MSBuild.

It happens when targeting both .NET 5 or .NET 6. There is .NET SDK 6.0.400 installed.

### PR DESCRIPTION
**Pull request by jjonescz**
Fixes #63469

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@jjonescz  The underlying issue is probably fixed in https://github.com/dotnet/roslyn/pull/64088. Could you confirm that? If so, then let's wait for that PR to go in and adjust this one to only add tests.

**Comment by jjonescz** [comment]
> The underlying issue is probably fixed in #64088. Could you confirm that?

Yes, it's fixed, except the last of my tests (`ScopedAsParameterName_06`) does not pass, i.e., this code is not reporting any errors (I am not sure whether it should?):

```cs
(scoped scoped) => { }
```

The tree also does not contain `ScopedKeyword`; it looks like this:

```cs
N(SyntaxKind.ParenthesizedLambdaExpression);
{
    N(SyntaxKind.ParameterList);
    {
        N(SyntaxKind.OpenParenToken);
        N(SyntaxKind.Parameter);
        {
            N(SyntaxKind.IdentifierName);
            {
                N(SyntaxKind.IdentifierToken, "scoped");
            }
            N(SyntaxKind.IdentifierToken, "scoped");
        }
        N(SyntaxKind.CloseParenToken);
    }
    N(SyntaxKind.EqualsGreaterThanToken);
    N(SyntaxKind.Block);
    {
        N(SyntaxKind.OpenBraceToken);
        N(SyntaxKind.CloseBraceToken);
    }
}
EOF();
```

**Comment by AlekseyTs** [comment]
> this code is not reporting any errors

This matches my expectations and the syntax tree looks good to me a s well.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 4). This is a test only change, this means it can be merged with a single sign-off. Please squash commits and adjust the comment to accurately reflect the nature of the change (an addition of tests) while merging.

**Pull request merged**
