### PR TITLE
Warn if we're offering a Coalesce Expression inside an ExpressionOfT.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Mitigation for https://github.com/dotnet/roslyn/issues/17028

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
The change from ```x != null ? x : y``` into ```x ?? y``` can be observed inside an ```Expression<T>``` context.  i.e. a different type of node is generated for ```??``` vs ``` ?  :  ```.  Some ```Expression<T>``` providers might not support the ```??``` node.  As such, we warn that this may cause problems, but we do not prevent people from making this change if it is what they want to do.

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by miloush** [comment]
I disagree with this fix. Why warning for the coalesce code fix only? Expression consumers can lack support for arbitrary set of expressions, and any fix potentially changes the behavior.

**Comment by miloush** [comment]
I mean it's not even about supporting the expressions or not. The consumer might support them all, but not be executing them. Could be serializing it or hashing it or whatever and things might break.

**Comment by CyrusNajmabadi** [comment]
> Why warning for the coalesce code fix only?

There is no claim that the warning would only be for coalesce expressions.  We're just happening to start with that.   I'm happy to add more warnings in the future for other features as well.

**Comment by CyrusNajmabadi** [comment]
> If this should be fixed on Roslyn side then I think all code fixes inside ExpressionOfT should be with warning at least.

That's fine.  We can do that.

**Comment by DustinCampbell** [comment]
>> If this should be fixed on Roslyn side then I think all code fixes inside ExpressionOfT should be with warning at least.

> That's fine.  We can do that.

That's fair.

**Pull request merged**
