### PR TITLE
Update System.Reflection.Metadata to -0014

### PR DESCRIPTION
**Pull request by agocke**
This version of S.R.M fixes the reference to System.Collections.Immutable to be 1.1.36 (the current Roslyn target version) instead of 1.1.37.

### CODE REVIEW

**Comment by agocke** [comment]
@jasonmalinowski I assume you sign off on mine if you signed off on @tmat's? :)

**Comment by agocke** [comment]
@tmat I fixed up https://github.com/dotnet/roslyn/pull/5030

**Comment by jasonmalinowski** [comment]
@agocke: I sign off on you making everything better.

**Comment by tmat** [comment]
Excellent. Thanks!

**Comment by agocke** [comment]
The mac/linux builds will fail because I haven't uploaded a new nuget zip. Doing that now.

**Comment by agocke** [comment]
retest this please

**Comment by agocke** [comment]
@tmat @jasonmalinowski Updated and everything passes. Awaiting :+1: :)

**Comment by tmat** [comment]
:+1:

**Comment by tannergooding** [comment]
:+1:

**Pull request merged**
