### PR TITLE
Merge from Features/constraints to dev15.7.x

### PR DESCRIPTION
**Pull request by VSadov**
As of https://github.com/dotnet/roslyn/pull/25397 , the feature branch meets requirements for the merge to the release branch.

The IDE manual pass has been completed (see below).

### CODE REVIEW

**Comment by VSadov** [comment]
# Testing tags

- :mag: = Scenarios that are regularly tested against internal builds
- :fast_forward: = Scenarios that must work as expected before new language features are merged

When doing a test pass, copy this page and consider using these status indicators:

- :white_check_mark: = Tested & Approved (possibly with linked bugs)
- :x: = Merge blocking
- :construction: = Non-blocking bugs
- :ok: = Issue has been fixed
- :free: = No expected impact
- :question: = Open question

<a name="testfootnote1"><sup>1</sup></a> Feature updated by compiler team, with appropriate unit tests.

<a name="testfootnote2"><sup>2</sup></a> Feature requires more complete testing by IDE team.

# Product Features

### Core Scenarios in Editing, Navigating, and Viewing

| Category | Feature/Description | C# Signoff/Notes | VB Signoff/Notes | 
| --- | --- | --- | --- | 
| **Enable/Disable** | :fast_forward: **Feature Flags** <br />To completely enables/disable new compiler features in the compiler & IDE | :white_check_mark: | N/A |
| **Typing** | :fast_forward: **General Typing**<br />- Type and paste new constructs<br />- Nothing interferes with verbatim typing | :white_check_mark: | N/A |
| | :mag: :fast_forward: **Completion**<br />- Typing new keyword/construct names<br />- Dotting off of new constructs<br />- Matching part of the identifier is highlighted (including word prefix matches) [Visual Studio 2015 Update 1]<br />- Target type preselection [Visual Studio 2017]<br />IntelliSense filtering [Visual Studio 2017] | :white_check_mark: | N/A |
| | :fast_forward: **Formatting** <br />- Spacing in and around new constructs<br />- Spacing options<br />- Format Document command<br /> `Tools > Options` settings should be respected | :white_check_mark: | N/A |
| | :fast_forward: **Automatic Brace Completion** (*C# only*) <br />- Auto-insert close brace<br />- Shift+Enter commit of IntelliSense and any pending brace completion sessions (Known issue: https://github.com/dotnet/roslyn/issues/18065) |  :white_check_mark: | N/A |
| | :fast_forward: **Indentation** <br />- Typing `Enter` in an unfinished statement indents the next line | :white_check_mark: | N/A |
| **Navigating** | :mag: :fast_forward: **Go To Definition** <br />- F12 from callsites to definition<br />- Ctrl+click [Visual Studio 2017 version 15.4] |  :white_check_mark: | N/A |
| | :fast_forward: **Go To Implementation** <br />- Ctrl+F12 to jump from virtual members to their implementations<br />- Jump from inheritable types to their implementations |  :white_check_mark: | N/A |
| | :mag: :fast_forward: **Find All References** <br />- Lists references to a symbol in "Find Symbol Results" window<br />- Shows results in hierarchy grouped by definition [Visual Studio 2015]<br />- Results should be groupable/filterable/classified appropriately [Visual Studio 2017] <br />- Find All References on literals [Visual Studio 2017 version 15.3] | :white_check_mark: | N/A |
| **Viewing** | :mag: :fast_forward: **Colorization** <br />- Keywords, literals, and identifiers colored appropriately in code<br />- Colors should theme appropriately<br />- The "Blue Theme (Additional Contrast)" should have sufficiently dark colors |  :white_check_mark: | N/A |
| | :fast_forward: **Error Squiggles** <br />- Squiggles appear as expected on reasonable spans | :white_check_mark: | N/A |

### Code Transformations
| Category | Feature/Description | C# Signoff/Notes | VB Signoff/Notes | 
| --- | --- | --- | --- | 
| **Refactoring with UI** | :mag: **Inline Rename (with UI)**<br />- Dashboard shows correct information<br />- Highlighted spans are updated appropriately<br />- Rename operation updates the correct set of symbols |:white_check_mark: | N/A |
| | :mag: **Change Signature (with UI)**<br />- Updates all direct & cascaded definitions/callsites<br />- Shows appropriate signature & parameter previews in UI<br />- Reorder and Remove in the same session [Visual Studio 2015] |:white_check_mark: | N/A |
| | :mag: **Extract Interface (with UI)**<br />- Generated Interface has expected shape<br />- UI shows appropriate method previews |:white_check_mark: | N/A |
| | **Generate Type (with UI)**<br />- Dialog gives all valid options<br /> |:white_check_mark: | N/A |
| | **Generate Overrides** [Visual Studio 2017 version 15.3] |:white_check_mark: | N/A |
| **Refactorings** | **Rename Tracking**<br />- Tracking span tracks & dismisses as expected<br />- Invokable from references [Visual Studio 2015] |:white_check_mark: | N/A |
| | :mag: **Extract Method**<br />- Extracted method has the expected signature<br />- All arguments/return values handled correctly<br />- Extracted code block is reasonable<br />- Automatically starts Inline Rename |:white_check_mark: | N/A |
| | **Introduce Variable**<br />- Introduced variable has the expected signature and initializer expression<br />- "Introduce for All" correctly finds dupes | N/A | N/A |
| | **Inline Temporary Variable**<br />- Inlined values are appropriately expanded/reduced | N/A | N/A |
| | **Organize Usings**<br />- Honors "Place 'System' namespace first" option | N/A | N/A |
| | **Convert `Get*` Methods to Properties**<br />*Add Description* |:white_check_mark: | N/A |
| | :mag: **Encapsulate Field**<br />- Select a field and convert it to a property backed by the field<br />- Try selecting multiple fields at once | :white_check_mark: | N/A |
| | **Modifier Ordering** [Visual Studio 2017 version 15.5] |N/A| N/A |
| | **Convert `ReferenceEquals` to `is null`** [Visual Studio 2017 version 15.5] |:N/A| N/A |
| | **Add Missing Modifiers** [Visual Studio 2017 version 15.5] |N/A | N/A |
| | **Convert Lambda to Local Function** [Visual Studio 2017 version 15.5] |N/A | N/A |
| | **Move Declaration Near Reference** [Visual Studio 2017 version 15.5] |N/A | N/A |
| | **Introduce Pattern Matching** [Visual Studio 2017 version 15.5] |N/A | N/A |
| | **Simplify Inferred Tuple Names** [Visual Studio 2017 version 15.5] | _Requires C# 7.1 or greater_ N/A | N/A |
| | **Convert keyword and symbol references to doc comment tags** [Visual Studio 2017 version 15.5] |N/A | N/A |
| **Fixes** | **Add Using**<br />- Triggers on appropriate constructs<br />- Including NuGet references<br />- Including Referenced Assemblies<br />- Includes spelling fixes |N/A | N/A |
| | **Generate Local**<br />- Select an expression and introduce a local variable to represent it<br />- This should start an Inline Rename session |:white_check_mark: | N/A |
| | **Generate Field**<br />- Select an expression and introduce a field to represent it<br />- This should start an Inline Rename session |:white_check_mark: | N/A |
| | **Generate Method/Constructor**<br />- Call a nonexistent method or constructor to generate it from its usage<br />- Generated method has the expected signature and accessibility<br />- Add parameter to existing constructor from callsite [Visual Studio 2017 version 15.3] |N/A | N/A |
| | **Generate Constructor from members**<br />- Select fields/properties to generate a constructor accepting corresponding arguments<br />- Generated constructor has the expected signature and accessibility |N/A | N/A |
| | **Implement Interface**<br />- Only missing methods added<br />- All added methods have the expected signature and accessibility |:white_check_mark: | N/A |
| | **Implement IDisposable**<br />- Implement IDisposable and you should see a large block of code properly implementing that particular interface |N/A | N/A |
| | **Implement Abstract Class**<br />- Inherit from an abstract class, and you should be able to auto-generate all of the missing members |:white_check_mark: | N/A |
| | **Remove Unused Variables** [Visual Studio 2017 version 15.3]| N/A | N/A |
| | **Remove Unused Usings** |N/A | N/A |
| | **Sort Usings** |N/A | N/A |
| | **Convert Get Methods to Properties**<br />- Name a method `GetStuff` and convert it to a property called `Stuff` | :white_check_mark: | N/A |
| | **Make Method Async/Sync**<br />- Add an `await` to a synchronous method, you should be offered to add the async keyword<br />- Remove all `await` keywords from an async method, you should be offered to remove the async keyword |N/A | N/A |
| | **Use Object Initializer Over Property Assignment**<br />- Create a new instance of a type and then assign each of its properties on subsequent lines<br />- You should be offered to convert that to an object initializer |N/A | N/A |
| | **Insert Digit Separators** [Visual Studio 2017 version 15.3] |N/A | N/A |
| **Code Gen** | :mag: **Snippets**<br />- Tab completion, presence in completion list<br />- Insertion via Snippet Picker UI (Ctrl + K, Ctrl + X) or (Ctrl + K, Ctrl + S)<br />- (VB) Snippet Picker UI via `?<Tab>`<br />- (VB) Special snippet completion list (`p?<esc><tab>`) | | | N/A |
| | **Event Hookup on Tab** (*C# only*)<br />- Type "+=" after an event name and QuickInfo shows<br />- Invoking should pick good name & launch Inline Rename | N/A | N/A |
| | **End Construct Generation** (*VB only*)<br />- Type `Sub Test()` and hit enter, the `End Sub` should be generated automatically | N/A | N/A |
| | **Automatic End Construct Update** (*VB only*)<br />- Type `Sub Test()` and `End Sub`, changing `Sub` to `Function` in either one should update the other | N/A | N/A |
| | **Spell checking**<br />- Type a name that's close to a variable name but off by a character or two<br />- Lightbulb should have option to fix up the spelling<br />- Includes type names that will require a using |N/A | N/A |
| | **Move type to file**<br />- Lightbulb to move type to another file when the type name doesn't match the filename<br />- Option to change the file name if the type doesn't match the file name |N/A | N/A |
| | **Convert between properties and Get methods** <br />- Offers to change a method named `GetStuff` to a property named `Stuff` |:white_check_mark: | N/A |
| | **Convert auto property to full property** [Visual Studio 2017 version 15.5] |:white_check_mark: | N/A |
| | **Add missing cases**<br />Use a `switch` on a strict subset of an Enum's members<br />- It should offer to generate the rest of the cases |N/A | N/A |
| | **Add null checks for parameters** [Visual Studio 2017 version 15.3] |N/A | N/A |
| | **Change base for numeric literals** [Visual Studio 2017 version 15.3] |N/A | N/A |
| | **Convert if to switch** [Visual Studio 2017 version 15.3] |N/A | N/A |
| | **Resolve git merge conflicts** [Visual Studio 2017 version 15.3] |N/A | N/A |
| | **Add argument name** [Visual Studio 2017 version 15.3 |N/A | N/A |
| | **Fade and remove unreachable code** [Visual Studio 2017 version 15.5] | N/A | N/A |
| | **Add missing file banner** [Visual Studio 2017 version 15.5] | N/A | N/A |
| | **Deconstruct tuple declaration** [Visual Studio 2017 version 15.4] |N/A | N/A |

**Comment by VSadov** [comment]
CC @jaredpar - for the dev15.7.x merge approval.

**Comment by VSadov** [comment]
FYI: @dotnet/roslyn-compiler @dotnet/roslyn-ide

**Comment by VSadov** [comment]
Some tests runs looked like stuck in "Waiting for status to be reported"

**Comment by VSadov** [comment]
@dotnet-bot test windows_coreclr_test_prtest please

**Comment by VSadov** [comment]
@dotnet-bot test windows_coreclr_test_prtest please

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - PING. Please take a look.

**Comment by jaredpar** [comment]
Approved.

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
