### PR TITLE
#3438, use standard Type Conversion Functions when possible

### PR DESCRIPTION
**Pull request by jrmoreno1**
use standard Type Conversion Functions when possible (including CStr), and not CType.

### CODE REVIEW

**Comment by jrmoreno1** [comment]
@jinujoseph what does BuddyAssigned mean?

**Comment by jinujoseph** [comment]
@jrmoreno1 it means you have a buddy @mavasani  who will help you with questions/review/connecting to right people while you help us with this fix.

**Comment by jrmoreno1** [comment]
@mavasani, all of the failed tests are integration and system failures as far as I can tell.  I can’t find a way to rerun the test without making a change in order to be sure, and I don’t want to do that.

**Comment by mavasani** [comment]
@jrmoreno1 I have restarted the failed runs for you, seems like these were unrelated intermittent test failures.

**Comment by mavasani** [comment]
Thanks for the contribution @jrmoreno1!

**Pull request merged**
