### PR TITLE
Revert "Merge pull request #8906 from amcasey/HidePane2"

### PR DESCRIPTION
**Pull request by TyOverby**
This reverts commit 0e7a2b6e4fd3e79a78843319af965f5153bf21ad, reversing
changes made to e1f34faa3a7f8c60c9489cfee0d46d918cfe0652.

### CODE REVIEW

**Comment by amcasey** [comment]
test prtest/win/vsi/p3 please

**Comment by amcasey** [comment]
LGTM, assuming the tests pass.

**Comment by TyOverby** [comment]
@dotnet-bot test prtest/win/dbg/unit32 please

**Comment by TyOverby** [comment]
@dotnet-bot test prtest/win/dbg/unit64 please

**Pull request merged**
