### PR TITLE
Fix EditAndContinueDiagnosticUpdateSource.ReportDiagnostics to return correct set of documents

### PR DESCRIPTION
**Pull request by tmat**
**Customer scenario**

Edit and Continue errors might not appear or appear duplicated in Error List. 
If an error is missing from Error List it's hard to diagnose why EnC failed.

**Bugs this fixes:**

**Workarounds, if any**

None.

**Risk**

Small.

**Performance impact**

None.

**Root cause analysis:**

How did we miss it?  What tests are we adding to guard against it in the future?

**How was the bug found?**

Dogfooding. Some customers report EnC issues where the error is not displayed in Error List.

### CODE REVIEW

**Comment by tmat** [comment]
@ivanbasov Please review

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by ivanbasov** [comment]
:shipit:

**Comment by tmat** [comment]
@MattGertz For ask mode approval

**Pull request merged**
