### PR TITLE
Remote FindAllReferences

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Tagging @dotnet/roslyn-ide @heejaechang @panopticoncentral @srivatsn . This is ready for review.

@heejaechang Is it possible to make unit tests call through the 'mock client'? I'd like to update all FAR tests to test both inproc results and OOP results. Thanks!

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @heejaechang @panopticoncentral 

Please take a look and let me know if i'm doing the OOP stuff correctly.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @heejaechang @panopticoncentral @srivatsn .  This is ready for review.

@heejaechang Is it possible to make unit tests call through the 'mock client'?  I'd like to update all FAR tests to test both inproc results and OOP results.  Thanks!

**Comment by heejaechang** [comment]
@CyrusNajmabadi I am trying to make unit test with d15 dependency work. still not done.

**Comment by CyrusNajmabadi** [comment]
Ping reviewers.  This has been ready for review for a week.  Thanks :)

**Comment by CyrusNajmabadi** [comment]
retest windows_eta_open_prtest  please

**Comment by CyrusNajmabadi** [comment]
@heejaechang @srivatsn @panopticoncentral 

I need reviewews who can check the OOP part of this.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Ping reviewers.  I need this reviewed asap.  This has been open for 20 days now.

**Comment by panopticoncentral** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by Pilchie** [comment]
LGTM

**Comment by heejaechang** [comment]
👍

**Pull request merged**
