### PR TITLE
Have add-using respect EditorBrowsable attributes.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Port of https://github.com/dotnet/roslyn/pull/53427 to dev16.11

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jinujoseph. Needs QB approval.

**Comment by jinujoseph** [comment]
@CyrusNajmabadi can you confirm once the val build has been signed by partner team ?

**Review by davidwengier — APPROVED** [review]

**Comment by sharwell** [comment]
I am opposed to the design presented by this pull request, so naturally I am also opposed to servicing a prior product to break a feature that today is working.

**Comment by CyrusNajmabadi** [comment]
>I am opposed to the design presented by this pull request, so naturally I am also opposed to servicing a prior product to break a feature that today is working.

Understood.  As per our offline talks, we're continuing to work with the API team requesting this change to see if there are things they can do on their end to mitigate the situation.

My personal recommendation is taht we take this simple and easy change (which is already in dev17) which unblocks the partner team.  Concurrently, we can work with them on how they may better package their API in the future to not need this.  Once that is done, we can remove teh mitigation changes (again, already in Dev17) from Roslyn.

@jinujoseph for context and QB decision making here.

**Comment by jinujoseph** [comment]
pending response from partner team

**Comment by JoeRobich** [comment]
Passing RPS in test insertion - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/345045 (microsoft)

**Comment by CyrusNajmabadi** [comment]
Closing out. We're not back porting this.

**Pull request closed without merging**
