### PR TITLE
Embed Shell Interops 10, 11 and 12.

### LINKED ISSUE #1436: Microsoft.VisualStudio.LanguageServices should embed Shell.Interop 10 and 11 IAs
### Problem
If you build a VS component which references both Microsoft.VisualStudio.LanguageServices and Microsoft.VisualStudio.Shell.Interop.10 (or 11) you will get a build warning if you try to embed the interop assembly (NoPIA). That's because MS.VS.LanguageServices does NOT embed these two interops.
### Background
We do not currently embed these two interops in MS.VS.LS because by doing so creates its own build warning due to references in Microsoft.VisualStudio.Progression.CodeSchema
### Fix
Track down the authors of Microsoft.VisualStudio.Progression.CodeSchema and ask them to embed these two interops.

### PR DESCRIPTION
**Pull request by pharring**
Fixes #1436

### CODE REVIEW

**Comment by pharring** [comment]
@jasonmalinowski @Pilchie for review

**Comment by Pilchie** [comment]
Is this the only project that references them?  The C# and VB specific ones don't?

Assuming no, :+1:

**Comment by pharring** [comment]
@Pilchie You're right. The VB and C# ones do reference these interops and they do NOT embed them. It wasn't part of fixing #1436 but I will take care of those too. Stand by.

**Comment by pharring** [comment]
@Pilchie there you go :-)

**Comment by Pilchie** [comment]
So, are these the only projects that reference them now? 

LGTM

**Comment by pharring** [comment]
That should be it now. There are changes in Closed too. Note that SolutionExplorerShim couldn't embed interop 11.0 because of a reference to Microsoft.VisualStudio.CodeAnalysis.Sdk.UI which doesn't embed it.

**Comment by Pilchie** [comment]
:shipit:

**Pull request merged**
