### PR TITLE
WIP: Test to track down the Jenkins AV

### PR DESCRIPTION
**Pull request by jaredpar**
**DO NOT MERGE**

This is a change to aggressively log AV during test runs. Attempting to track down the real AVs causing crashes during our test runs

### CODE REVIEW

**Comment by jaredpar** [comment]
@dpoeschl FYI https://github.com/dotnet/roslyn/pull/26543

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest  please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest  please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest  please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by mmitche** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by mmitche** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by mmitche** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by mmitche** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by mmitche** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by jaredpar** [comment]
retest windows_debug_spanish_unit32_prtest please

**Pull request closed without merging**
