### PR TITLE
Remove commented out class

### PR DESCRIPTION
**Pull request by stefansedich**
Just a bit of clean-up!

### CODE REVIEW

**Comment by theoy** [comment]
@Vsadov - any context on why this is commented instead of deleted?

**Comment by VSadov** [comment]
At some point we had internal visitors generic visitors parameterized on parameters - SyntaxVisitor<TArgument, TResult>. They were convenient, but not very fast because of virtual generic Accept. Eventually all the visitors switched to the faster version SyntaxVisitor<TResult>.
There were some arguments that at some point we might still need the convenience of SyntaxVisitor<TArgument, TResult>, so it was not removed, just commented out.

Perhaps it is time to remove it :-)

**Comment by VSadov** [comment]
At some point we had internal visitors generic visitors parameterized on parameters like ``` SyntaxVisitor<TArgument, TResult> ``` .They were convenient, but not very fast because of virtual generic Accept. Eventually all the visitors switched to the faster version ``` SyntaxVisitor<TResult> ```.
There were some arguments that at some point we might still need the convenience of ``` SyntaxVisitor<TArgument, TResult> ```, so it was not removed, just commented out.

Perhaps it is time to remove it :-)

**Comment by srivatsn** [comment]
@stefansedich If you haven't already, can you please sign the CLA here - https://cla2.dotnetfoundation.org ?

**Comment by stefansedich** [comment]
All done @srivatsn

**Comment by srivatsn** [comment]
Great thanks.

**Pull request merged**
