### PR TITLE
Fix inline description for async completion

### LINKED ISSUE #34271: Regression in async-completion.  'inline description' no longer supported.
Async completion undid the work we did to make inline-descriptions supported in Regex completion:

image

It now looks like:

image

This also affects "completion for other namespaces" as we want to use the 'inline description' to specify where the type is coming from.

### PR DESCRIPTION
**Pull request by genlu**
Fix #34271

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@AmadeusW do you know why this is so wide:

image

**Comment by CyrusNajmabadi** [comment]
Oh, it must just be on shen's machine.  On mine, this looks fine.

**Comment by genlu** [comment]
@CyrusNajmabadi probably because it showed completion list with all the import items before? But it shouldn't remember that, right?

**Comment by CyrusNajmabadi** [comment]
> There, fixed it for you ;)

Sorry!

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi probably because it showed completion list with all the import items before? But it shouldn't remember the length from previous sessions, right?

Maybe... if you are seeing that behavior, we need to address it.  We can't have 'import items' making all completion lists look like this :D

But that can come later.

**Pull request merged**
