### PR TITLE
added missing cancellation token to Task.Delay

### PR DESCRIPTION
**Pull request by heejaechang**
noticed while looking at the code base.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-ide can you take a look?

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by heejaechang** [comment]
we can ignore windows_debug_vs-integration_prtest for now.

**Pull request merged**
