### PR TITLE
Merge microupdate into master

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from microupdate into master.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-microupdate-into-master20160628-193714
git reset --hard upstream/master
git merge upstream/microupdate
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-microupdate-into-master20160628-193714 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jasonmalinowski** [comment]
@jmarolf something seems up here. There shouldn't be all those commits listed in this PR.

**Comment by jmarolf** [comment]
test vsi please

**Comment by jasonmalinowski** [comment]
@dotnet-bot, test vsi please, since I did a push.

**Comment by jmarolf** [comment]
tes vsi please

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test windows_vsi_p0_open_prtest please

**Comment by jmarolf** [comment]
test windows_vsi_p0_open_prtest please
test windows_vsi_p3_open_prtest please

**Comment by jmarolf** [comment]
test windows_vsi_p0_open_prtest please

**Comment by jmarolf** [comment]
test windows_vsi_p0_open_prtest please

**Pull request merged**
