### PR TITLE
VB: Merging "line continuation comments" feature

### PR DESCRIPTION
**Pull request by jcouv**
Championed issue: https://github.com/dotnet/vblang/issues/65

I will do a quick IDE test pass before and we will do a lightweight internal test review before merging this PR.

@paul1956 @KathleenDollard FYI

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet-bot help please

**Comment by jcouv** [comment]
test roslyn-CI please

**Comment by jcouv** [comment]
I'll close and re-open to re-run CI.

**Comment by paul1956** [comment]
@jcouv Do I need to do anything?

**Comment by jcouv** [comment]
> Do I need to do anything?

@paul1956 No need. I'll go ahead and refresh the feature branch with latest bits from master and resolve a couple of tests to fix CI. Thanks

**Comment by jcouv** [comment]
Done.

**Comment by jcouv** [comment]
@jaredpar for approval to merge. Thanks

**Pull request merged**
