### PR TITLE
added a way to dynamically add new incremental analyzer to solution c…

### PR DESCRIPTION
**Pull request by heejaechang**
…rawler

### CODE REVIEW

**Comment by heejaechang** [comment]
@tannergooding can you sync this PR and see whether this works for you?

**Comment by tannergooding** [comment]
FYI. @KevinH-MS 

@heejaechang, I will pull the PR and try this out.

One question: What is the `PreviewSolutionCrawlerRegistrationService`?

and one comment: It would be useful to have an `Unregister` method as well, so that we don't have to worry about returning `null` when we are disabled (although, this is not strictly necessary, as the provider can just return `null`).

**Comment by heejaechang** [comment]
@tannergooding preview workspace (which is used for most of preview window such as code fix or rename and etc) has its own implementation of solution crawler service since its behavior can't be same as regular one.

...

removing is a bit more complex. also adding and removing is expansive. so intentionally didn't add one.

...

I am not sure returning null would fix anything. it should be your analyzer itself that won't do anything if option is off.

**Comment by KevinH-MS** [comment]
LGTM (pending validation from @tannergooding).  FYI, I was talking to HeeJae offline, and we will want to start implementing ```IIncrementalAnalyzer.NeedsReanalysisOnOptionChanged``` (instead of just hard coding ```return false```) after this change.  Otherwise, we won't automatically get called when dynamic anlaysis is enabled, disabled, re-enabled (as there will be no unregister/re-register to trigger this).

**Comment by heejaechang** [comment]
@tannergooding let me know whether I can check this in or not.

**Comment by tannergooding** [comment]
@heejaechang, this look good here

**Pull request merged**
