### PR TITLE
Switch tests unnecessarily using WpfFact to Fact

### PR DESCRIPTION
**Pull request by jasonmalinowski**
These tests were all using `WpfFact`, but not actually doing anything that required either WPF or an STA thread. We plan to enable parallelization of Facts (but not WpfFacts), and this ensures we can parallelize as many tests as possible.

GitHub refuses to show the full diff. The actual diff stat:

    790 files changed, 22213 insertions(+), 22213 deletions(-)

*Review:* @dotnet/roslyn-ide, @jaredpar

### CODE REVIEW

**Comment by jaredpar** [comment]
There are a lot of files listed as 0 changes.  Did you accidentally strip or add a BOM to those files?

**Comment by jasonmalinowski** [comment]
@jaredpar: GitHub gives up showing diffs after 300 files, and shows it as zero diff AFAIK.

**Comment by jasonmalinowski** [comment]
Analyzing my diff locally, a few non WpfFact->Fact changes snuck in the commit. Breaking them apart now.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Comment by jasonmalinowski** [comment]
*Review:* @dotnet/roslyn-ide. Even if you can't diff the huge commit, there are now two other commits for small things I've noticed that would still be good to have somebody look at.

**Comment by Pilchie** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@DustinCampbell: just so it's clear (and written down somewhere)...

I intended for this PR to be the trivial diff of WpfFact -> Fact, with all the "interesting stuff" happening in the previous PR. As I was verifying that my trivial diff was in fact trivial, I noticed a few of those changes snuck due to some bad rebase I did in the past. At that point I just broke apart the commits and continued rather than trying to figure something else out.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please. Even though everything is green, I want a few test runs with this all passing for extra confidence.

**Comment by davkean** [comment]
Windows Unit32 failed due to github communication issues.

retest prtest/win/dbg/unit32 please

**Comment by jasonmalinowski** [comment]
@dotnet-bot, retest prtest/win/dbg/unit64 please. This hit a known failure during test shutdown. Bug #7542 was filed to track why we got a poor message here.

**Pull request merged**
