### PR TITLE
Perform the initial tagging for a file as fast as possible so that that the file appears 'complete' immediately after opening.

### LINKED ISSUE #18376: Very long delay before semantic highlighting appears
Note, that there is no any significant CPU load. It looks like there is an intentional delay somewhere in Roslyn code:

Interesting, that the delay is much longed on preview tab, if I double click on documents, they colored faster (but still not fast enough):

The guidelines appear faster in both cases, but slowly, too.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes #18376

Followup to https://github.com/dotnet/roslyn/pull/18383 
This also improves speed to get initial squiggles to teh screen.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Looks like:

squiggletagging1

**Comment by CyrusNajmabadi** [comment]
here's what it looks like for the provisional tab: 

squiggletagging1

**Comment by CyrusNajmabadi** [comment]
@lorcanmooney Do you want to take a look?

Note: Diagnostics still make take a while *initially*.  We still have actually compute them.  However, once computed and cached, things should be nice and fast.

--

In other words, for all this work we're doing, there are still costs to prime some of our caches.  So if you load VS, and immediately open a file, you will likely observe at least some delays.  However, as you continue using VS (even after just a few seconds), things should get better and better.

**Comment by vasily-kirichenko** [comment]
This is fantastic improvement! If it's merged, how fast it'd be on NuGet and VS itself?

**Comment by CyrusNajmabadi** [comment]
15.3 at the absolute earliest.

**Comment by vasily-kirichenko** [comment]
What does 15.3 mean? Is there a roadmap to look at where it's scheduled?

**Comment by sharwell** [comment]
@vasily-kirichenko I found a description referring to the versioning numbers here:

https://blogs.msdn.microsoft.com/visualstudio/2017/03/16/visual-studio-2017-update-preview-and-windows-10-creators-update-sdk/

> Astute observers may also note that, starting in Visual Studio 2017, we moved to a simpler versioning system – you’ll see minor versions like 15.1, 15.2, and so on, with patch updates identified with a longer build number. This first update will be versioned 15.1, and eventually you will see patches identified (e.g. 15.1.12345) when they become available. This versioning system is a bit simpler than the “Visual Studio Update 1” terminology we used previously and does a better job matching the speed and frequency that we will be releasing.

I don't believe any specific dates have been announced.

**Comment by CyrusNajmabadi** [comment]
> What does 15.3 mean?

15.3 will be the first official VS update (i.e. not the small micro-updates that are being offered to fix major critical issues).  It should be in a couple of months.  I have no idea where schedules are located :)

**Comment by lorcanmooney** [comment]
Awesome 👍

**Comment by cartermp** [comment]
@CyrusNajmabadi Since this PR is a bit old, are we thinking this is still a 15.3 time frame?

**Comment by CyrusNajmabadi** [comment]
i think 15.3 would be too soon.  We haven't had a chance to really dogfood this (i've been focused on the Roslyn OOP work).  I would consider this work pretty risky, so i'd want it to only ship once it had an adequate amount of time to bake.

**Comment by cartermp** [comment]
Makes sense!

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @Pilchie

**Comment by Pilchie** [comment]
This looks okay to me - are we still planning on taking it?

**Comment by cartermp** [comment]
Would love to take this if possible.

**Comment by CyrusNajmabadi** [comment]
Sure, i'd def want to take this.

**Pull request merged**
