### PR TITLE
add back optimized line computation

### PR DESCRIPTION
**Pull request by mattwar**
This change adds back the optimize line computation logic that was removed in #7219 

My intention was to add this logic back with tests.. But it turns out there were already tests.  Instead, I've added some more comments and removed duplicate parsing logic by reusing line computations from inserted sub text.

@jasonmalinowski @heejaechang please review.

### CODE REVIEW

**Comment by mattwar** [comment]
test please

**Comment by mattwar** [comment]
test please

**Comment by davkean** [comment]
Looks like you builds were aborted when we had to reboot jenkins when it stopped responding. 

retest prtest/lin/dbg/unit32 please
retest prtest/win/dbg/unit32 please

**Comment by dpoeschl** [comment]
retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/1936/
// Retest reason: Jenkins was down

**Comment by mattwar** [comment]
retest please

**Comment by mattwar** [comment]
@dotnet-bot test please

**Pull request merged**
