### PR TITLE
Issue #2666 - MefHostServices fails loading unsigned assemblies

### PR DESCRIPTION
**Pull request by jakesays**
Simple fix to allow Roslyn to function without being signed.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
:+1: once the tabs are fixed.

**Comment by jasonmalinowski** [comment]
And @Pilchie, @mattwar for the second code review.

**Comment by pharring** [comment]
:+1:

**Comment by mattwar** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@dotnet-bot test this please.

@jaredpar, is this a known failure?

**Comment by Pilchie** [comment]
Yes, it's failing on all PRs right now.  Also cc @tmat

**Comment by jasonmalinowski** [comment]
@dotnet-bot test this please.

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
