### PR TITLE
Populate switch tweaks

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This change tweaks 'Populate Switch' to provide from 1-3 fixes to the user depending on the state of the switch. The potential fixes provided are:

Add missing cases.
Add missing 'default' case
Add both

### CODE REVIEW

**Comment by Hosch250** [comment]
Why did you PR to Future instead of Master?  My PR was merged into Master, so shouldn't it be corrected there and be auto-PR'ed to Future?

**Comment by CyrusNajmabadi** [comment]
Because IOperatoin has been disabled in Master :)

**Comment by mattwar** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/6507/
// Retest reason:

**Comment by Hosch250** [comment]
OK.  I hope this gets worked in before it is released: it is quite an improvement over my first version.

**Comment by CyrusNajmabadi** [comment]
We're discussing what to do.  :)

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide  please review.

**Comment by CyrusNajmabadi** [comment]
We've decided we're going to do all the work here out of 'future'.  We'll be disabling this in master and shipping this out of future (with IOperations) instead.  Thanks!

**Comment by rchande** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide For signoff.

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by jmarolf** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by DustinCampbell** [comment]
adding @mattwar for `SyntaxGenerator` API additions

**Comment by DustinCampbell** [comment]
change looks righteous though 👍

**Comment by mattwar** [comment]
what are the missing tokens for?

**Comment by CyrusNajmabadi** [comment]
So that if you add switch sections to ```switch (foo)``` you get ```switch (foo) { case ... }``` not ```switch (foo) case ...```

This enables someone to easily just do:  ```switch (foo)<ctrl-dot><add missing cases>``` and have a fully formed switch they can use.

**Comment by mattwar** [comment]
in case you are operating on a code fragment?  I see, since you've only just typed the first part and you want to auto generate the cases?  Couldn't you just add the token directly without the rewriter?

**Comment by Hosch250** [comment]
I haven't tried this, but you could probably just do `CSharpSyntaxFactory.Block({newNodesFromGenerator})`

**Comment by CyrusNajmabadi** [comment]
> Couldn't you just add the token directly without the rewriter?

I could... but then i'd have to write logic specifically to handle the open and close tokens being missing.  I just decided i would write the helper once and then would have it whenver i needed it.

**Comment by CyrusNajmabadi** [comment]
> CSharpSyntaxFactory.Block({newNodesFromGenerator})

'Block' won't generate the write type of node for a switch statement unfortunately.

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
retest vsi please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
test vsi please

**Pull request merged**
