### PR TITLE
report NFW instead of crash when creating formatting rules if encoutered unexpected state

### PR DESCRIPTION
**Pull request by genlu**
Fixing internal bug [753909](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753909).

I couldn't figure out a repro, so opted for NFW. Tagging @heejaechang @jasonmalinowski, who's more knowledgeable in this area (editor and Razor) and might know how to trigger the crash.

FYI @dotnet/roslyn-ide

### CODE REVIEW

**Comment by genlu** [comment]
@jinujoseph Just wanna confirm this is for preview 2. Whose approval do I need?

**Comment by jinujoseph** [comment]
Lets target this to master

**Comment by genlu** [comment]
@jasonmalinowski Any idea why this exception can cause undo to stop working?

**Comment by jasonmalinowski** [comment]
@genlu: looking at it, you're being called as a part of snippet expansion; and we're called to format right before they complete an IVsCompoundAction which is a legacy wrapper around the undo system. We're probably propogating the exception through them, so they never complete the IVsCompoundAction. 

The fact they're not handling the exception well and wedging the editor is a bug that should be moved to the editor because although we should try our best to not screw up, screwing up shouldn't permanently wedge the editor. At the same time, we should try our best not to screw up. :smile:

**Comment by genlu** [comment]
@jinujoseph for approval

**Pull request merged**
