### PR TITLE
Pr feedback

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @RikkiGibson.  This merges master into the branch, and also does hte couple of changes you wanted.

**Comment by RikkiGibson** [comment]
to be clear, is everything except d9a00fd already reviewed?

**Comment by CyrusNajmabadi** [comment]
@RikkiGibson Yup.  You can see that prior to that is simply the master merge.

**Comment by RikkiGibson** [comment]
the new changes are very simple so I'll just merge

**Pull request merged**
