### PR TITLE
Update nonshipping flags

### PR DESCRIPTION
**Pull request by jasonmalinowski**
*Review:* @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jmarolf** [comment]
:+1:

**Comment by tannergooding** [comment]
LGTM.

How compatible is this with the new signed build system?

**Comment by jasonmalinowski** [comment]
@tannergooding It might be throwaway work, I don't know. The goal is just to get this off the floor first, and the fastest way to do that was to just enforce the correct behavior.

**Comment by tannergooding** [comment]
:shipit:

**Pull request merged**
