### PR TITLE
Unconstruct method if any type arguments are error types

### LINKED ISSUE #1903: Type inference should infer enumerable item type inside a lambda
Ported from TFS WorkItem: **726766**

------------------------------

**Repro Steps:**

1. Paste this code

```C#
using System.Collections.Generic;
using System.Linq;
 
class A { }
class B { }
class C
{
    IEnumerable<B> GetB(IEnumerable<A> a)
    {
        return a.Select(i => Foo(i));
    }
}
```

2. Invoke Generate Method on Foo

&nbsp;

*Expected*:
```C#
private B Foo(A i)
```

*Actual*:
```C#
private object Foo(A i)
```
------------------------------

**Revisions:**

1) Created By Kirill Osenkov (6/28/2013 1:30:35 PM)

------------------------------

2) Edited By Kirill Osenkov (6/28/2013 1:32:05 PM)

Dev12 generates this, which is equally useless:

&#160;
<font face=Consolas>

</font><font color="#0000ff" face=Consolas><font color="#0000ff" face=Consolas>private</font></font><font face=Consolas> <font style="BACKGROUND-COLOR:#ffff00;">TResult</font> Foo(</font><font color="#2b91af" face=Consolas><font color="#2b91af" face=Consolas>A</font></font><font face=Consolas> i)

{

</font><font color="#0000ff" face=Consolas><font color="#0000ff" face=Consolas>&#160;&#160;&#160; throw</font></font><font face=Consolas> </font><font color="#0000ff" face=Consolas><font color="#0000ff" face=Consolas>new</font></font><font face=Consolas> </font><font color="#2b91af" face=Consolas><font color="#2b91af" face=Consolas>NotImplementedException</font></font><font face=Consolas>();

}
</font>

------------------------------

3) Edited By Kevin Pilch-Bisson (7/1/2013 9:20:58 AM)

Yes, this would be a nice improvement.

------------------------------

### PR DESCRIPTION
**Pull request by bmay2**
Fixes #1903

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-ide for review.

@dotnet-bot test vsi please.

**Comment by Pilchie** [comment]
@CyrusNajmabadi in particular might want to take a look at this.

**Comment by CyrusNajmabadi** [comment]
:+1:

**Comment by Pilchie** [comment]
Any chance this makes things worse in cases where some of the constructed arguments would have been better matches.

**Comment by CyrusNajmabadi** [comment]
>Any chance this makes things worse 

Really hard to say.  We have a reasonably good test bed for type inference (both directly, and through lots of refactoring tests).  That nothing even changed is a good sign.

**Comment by balajikris** [comment]
:+1:

**Comment by balajikris** [comment]
@Pilchie I'm ready to merge this in, if your concerns have eased?

**Comment by Pilchie** [comment]
Yes, let's go!  :shipit:

**Comment by balajikris** [comment]
@bmay2 thanks for the contribution.

**Pull request merged**
