### PR TITLE
porting named pipe fix from service hub.

### PR DESCRIPTION
**Pull request by heejaechang**
while investigating NFW issue, service hub team found a bug in NamedPipe library code. I am porting that fix to our side since we use same code for named pipe.

this is service hub PR (https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_git/DevCore/pullrequest/91111?_a=overview )

...

**Customer scenario**

in the middle of using VS, client can see an info bar indicating there was an issue in OOP.

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/NET%20Developer%20Experience%20Productivity/_workitems/edit/515282

**Workarounds, if any**

there is no workaround

**Risk**

right now, we only see NFW on service hub side but not Roslyn side. but since we both uses same code (I borrowed service hub code), I am porting the fix to our side.

**Performance impact**

N/A

**Is this a regression from a previous update?**

No

**Root cause analysis:**

from NFW report, service hub team identified a possible race on NamedPipeClientStream.Connect and made a fix/workaround. we are porting that fix to our side.

**How was the bug found?**

non fatal watson

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph I would like to bring this to 15.5

**Comment by heejaechang** [comment]
@prasethu can you take a look?

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest  please

**Comment by natidea** [comment]
Approved to merge via [515282](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/515282)

**Pull request merged**
