### PR TITLE
Fix race condition in CodeFixService

### LINKED ISSUE #38198: Flaky integration test CSharpCodeActions.ConfigureCodeStyleOptionValueAndSeverity
This integration was recently added, and it seems it fails intermittently on quite a few integration test runs.

```
System.Exception : The following expected item(s) not found in sequence:\r\nConfigure IDE0059 code style\r\nunused__local__variable\r\ndiscard__variable\r\nConfigure IDE0059 severity\r\nNone\r\nSilent\r\nSuggestion\r\nWarning\r\nError\r\nSuppress IDE0059\r\nin Source\r\nin Suppression File\r\nin Source (attribute)\r\n\r\nActual items:\r\nUse discard '__'\r\nPreview changes\r\nDocument\r\nProject\r\nSolution\r\nUse explicit type instead of 'var'\r\nPreview changes\r\nDocument\r\nProject\r\nSolution\r\nConfigure or Suppress issues\r\nConfigure IDE0059 code style\r\nunused__local__variable\r\nPreview changes\r\ndiscard__variable\r\nPreview changes\r\nConfigure IDE0059 severity\r\nNone\r\nPreview changes\r\nSilent\r\nPreview changes\r\nSuggestion\r\nPreview changes\r\nWarning\r\nPreview changes\r\nError\r\nPreview changes\r\nSuppress IDE0059\r\nin Source\r\nPreview changes\r\nDocument\r\nProject\r\nSolution\r\nin Suppression File\r\nPreview changes\r\nDocument\r\nProject\r\nSolution\r\nin Source (attribute)\r\nPreview changes\r\nDocument\r\nProject\r\nSolution\r\nConfigure IDE0008 code style\r\ncsharp__style__var__elsewhere\r\ntrue\r\nPreview changes\r\nfalse\r\nPreview changes\r\ncsharp__style__var__for__built__in__types\r\ntrue\r\nPreview changes\r\nfalse\r\nPreview changes\r\ncsharp__style__var__when__type__is__apparent\r\ntrue\r\nPreview changes\r\nfalse\r\nPreview changes\r\nConfigure IDE0008 severity\r\nNone\r\nPreview changes\r\nSilent\r\nPreview changes\r\nSuggestion\r\nPreview changes\r\nWarning\r\nPreview changes\r\nError\r\nPreview changes\r\n
```

The test will be disabled and this issue tracks fixing and re-enabling it.

### PR DESCRIPTION
**Pull request by mavasani**
Ensure that we process diagnostics ordered by their span and then diagnostic ID. This fixes a race condition seen in intermittent failures for integration test `ConfigureCodeStyleOptionValueAndSeverity` where the order of configuration/suppression fixes is non-deterministic.

Closes #38198

### CODE REVIEW

**Comment by mavasani** [comment]
Test passes locally a few times and also passed in first attempt on CI in this PR - closed and re-opened PR to double check.

**Comment by jasonmalinowski** [comment]
@mavasani: as far as I'm concerned once this is passing even once more let's call it good. Better to be optimistic and merge it if it isn't making things worse rather than spend time validating.

Is this a fix we should port to 16.5 Preview 2?

**Comment by mavasani** [comment]
> Is this a fix we should port to 16.5 Preview 2

The flaky test is still disabled in that branch: https://github.com/dotnet/roslyn/blob/release/dev16.5-preview2/src/VisualStudio/IntegrationTest/IntegrationTests/CSharp/CSharpCodeActions.cs#L647, so I'd rather let the product fix be in master to get some more bake time for 16.5 Preview3.

**Comment by mavasani** [comment]
> as far as I'm concerned once this is passing even once more let's call it good. Better to be optimistic and merge it if it isn't making things worse rather than spend time validating.

Sure, I'll merge as soon as tests pass.

**Comment by AmadeusW** [comment]
BTW I made a change in Editor which will cause display gold bar instead of crashing VS when a language service throws an exception.

**Pull request merged**
