### PR TITLE
Improves location used for base class errors when partial classes are used

### LINKED ISSUE #7878: Wrong source code location for CS0060 error
```
internal class NV
{
}

public partial class C1
{
}

partial class C1 : NV
{
}
```

Produces error message like `x.cs(5,22): error CS0060: Inconsistent accessibility: base class 'NV' is less accessible than class 'C1'` but I'd expect the error row to be 9 not 5.

### PR DESCRIPTION
**Pull request by leppie**
Fixes #7878

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot test eta please

tag @dotnet/roslyn-compiler

**Comment by cston** [comment]
LGTM

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
