### PR TITLE
Move base-type-list syntax checks out of the parser.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-compiler @jcouv @AlekseyTs 

Note: it seems like we also report semantic errors here.  So we possibly could get rid of the syntax checks.

**Comment by CyrusNajmabadi** [comment]
@cston Could you take a look?  Thanks!

**Comment by CyrusNajmabadi** [comment]
retest windows_debug_unit64_prtest  please

**Comment by TyOverby** [comment]
LGTM

**Comment by CyrusNajmabadi** [comment]
Tagging @gafter on this.  I've moved a syntax-check to the semantic layer.  However, i think the code may be entirely unnecessary to begin with.  Specifically, we already do seem to check that base/interface type must be the correct type of symbol.  So i'm thinking of removing the syntactic check altogether.

As some who i believe was very involved in base-binding, i wanted to get your thoughts on if I should do that or not.

Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks for the reviews!

**Pull request merged**
