### PR TITLE
Always use hard links when building in CI

### PR DESCRIPTION
**Pull request by RikkiGibson**
Related to #30005

Hard links reduce the amount of writes by ~10GB when enabled in the build. One effect of this is it makes us fit within the size budget of the built-in AzDo Windows agents, which are slower, but highly available (10-30 second wait time versus 5-10 minute wait time.)

### CODE REVIEW

**Comment by jaredpar** [comment]
This change is fine but I'm somewhat leery of us taking large dependencies on it. By that I mean I'm a bit leery of us predicating our infrastructure on the ability to use hard links in CI. As an optimization though, absolutely lets go with it. 

The reasoning is that hard links are generally not a well tested feature across the entire ecosystem of tools that we consume in our builds. There have been times when updates to various components temporarily broke our ability to use hard links. As evidenced by me having to turn hard links off in CI pretty much as soon as I turned them on as an update broke them 😦 

If we want to depend on them deeply I think we should start by turning them on, waiting for a few update cycles (~3 weeks) and seeing how it goes. If we can maintain it that long then I'd feel better about taking deeper dependencies on it.

**Review by jaredpar — APPROVED** [review]

**Review by JoeRobich — APPROVED** [review]

**Comment by RikkiGibson** [comment]
> As evidenced by me having to turn hard links off in CI pretty much as soon as I turned them on as an update broke them

Good to know. It sounds like the failure wasn't just "the build silently stopped using hard links", instead it was "the build loudly started failing"?

**Comment by RikkiGibson** [comment]
Let's merge this with the expectation that if it starts failing we will just revert it.

**Comment by jaredpar** [comment]
Yes the build started failing once the break occurred. Been a few years but I believe it was essentially a double write / write + read error in the SDK / MSBuild (basically the type of error which is more likely to get caught with hard links).

**Pull request merged**
