### PR TITLE
fix crash on a bug on analyzer data up to date check

### PR DESCRIPTION
**Pull request by heejaechang**
**Customer scenario**

VS crashes seemingly randomly while working on a VS with full solution analysis on. it doesn't happen always, but some times.

**Bugs this fixes:** 

https://github.com/dotnet/roslyn/issues/16363

**Workarounds, if any**

Turn off full solution analysis

**Risk**

Risk should be low since implementation-wise, it is removing existing contract since we now verified the condition can happen.

**Performance impact**

There should be no perf impact. 

**Is this a regression from a previous update?**

No

**Root cause analysis:**

hard to know why this only happens now, might be recent change changed timing. code-wise, this seems could have happened since beginning.

**How was the bug found?**

dogfooding.

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @mavasani @tannergooding @panopticoncentral can you take a look?

**Comment by heejaechang** [comment]
@srivatsn I added milestone as RC3 since risk seems low and it is crashing bug.

**Comment by heejaechang** [comment]
@tannergooding can you add your opinion how serious this crash is?

**Comment by srivatsn** [comment]
Tagging @MattGertz for RC3 consideration. 

@heejaechang you'll need to change the base branch to dev15-rc3 if we decide to take this for RC3.

**Comment by heejaechang** [comment]
@srivatsn sure.

**Comment by MattGertz** [comment]
RC3, please.

**Comment by tannergooding** [comment]
I was able to hit this very consistently (5-6 times in a 10 minute period) just by having full solution analysis on and switching back and forth between various files.

It made it nearly impossible to do any actual work with FSA enabled, and I feel as though I would not be able to enable it at all without this fix.

**Comment by heejaechang** [comment]
@MattGertz should I wait for approval label before checking in? I saw email that it got approved from shiproom

**Comment by MattGertz** [comment]
Go for it.

**Pull request merged**
