### PR TITLE
Porting two recent tuple-related fixes to VB

### PR DESCRIPTION
**Pull request by VSadov**
Fixes: #14260

== VB counterpart for:
Fixes: #10891 - Forbid constructing tuples via "new"
Fixes: #11689 - Enforce that ValueTuple types are structs

Note that #11689 requires validation that ValueTuple is a value type only in common cases, That is - to convey that cases where ValueTuple happens to be a Class, Enum, Delegate, etc are clearly not supported.

From the language prospective, tuples are value types composed of their elements. That is visible through the semantics of definite assignment, conversions, nullable lifting, async capturing and so on. This change intentionally introduces emit failures when underlying ValueTuple types are not structs.

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please review

**Comment by VSadov** [comment]
@MattGertz - for RC approval.

This is mostly just a parity with C#. 
* We do not have a well defined behavior for cases when ValueTuple types are classes/interfaces/enums etc, so we produce an error to intentionally not support such scenarios.
* We do not want tuple types be used in ```New <Type>``` expressions because a simpler, more concise syntax exist for tuple creation, while ```New (a, b)``` may also be infringing on the syntax for another proposed feature.

**Comment by MattGertz** [comment]
Approved pending tests and signoffs.

**Comment by VSadov** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
