### PR TITLE
Revert "BackgroundAnalysisScope enhancements"

### PR DESCRIPTION
**Pull request by RikkiGibson**
Reverts dotnet/roslyn#57172

This PR is suspected of introducing RPS regressions.

Last known good: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379422
First known bad: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379438
Revert validation: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/379561

Regressed counters:
- UWP64.ProjectManagement - RegressedBeyondThreshold / 0200.Xaml Designer Load / RefSet_Image_Delta_devenv / Regressed: 6668288.00 Bytes (8.10%)
- WebToolsVS64.Debugging - RegressedBeyondThreshold / 0300.Stop Debugging / CLR_BytesAllocated_Total_devenv / Regressed: 193326051.20 Bytes (19.17%)
- WinformsVS64.Designer - RegressedBeyondThreshold / 0200.Open Existing WinForm - Async / RefSet_Image_Delta_devenv / Regressed: 12410880.00 Bytes (620.27%)

Please advise whether the failures are plausibly connected with this PR, and if so, whether we should revert, or take a follow-up PR to fix, or seek an exception. @genlu @mavasani @CyrusNajmabadi @sharwell.

### CODE REVIEW

**Comment by mavasani** [comment]
I suspect the regression could be from this PR. Solution crawler is turned off in RPS, and this PR adds a code path that might have accidentally bypassed the solution crawler option check and hence led to it executing causing the regression.

@RikkiGibson I can create a simple PR to fix the above issue instead of reverting the PR. Would it be possible to validate RPS with that and if it still doesn’t fix these regression then revert the entire PR?

**Comment by RikkiGibson** [comment]
Sounds great. Please link to this PR when you create it. Then provide your PRNumber and CommitSHA (not Commit) in [this pipeline](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?definitionId=8972&_a=summary), and link to the pipeline run in your PR.

**Comment by mavasani** [comment]
Thanks @RikkiGibson. Created https://github.com/dotnet/roslyn/pull/59498 to attempt to fix the RPS regression and kicked off the [RPS validation PR](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/results?buildId=5744401&view=results) for it.

**Comment by sharwell** [comment]
Marked as draft as #59498 is preferred.

**Pull request closed without merging**
