### PR TITLE
filter tests for async completion

### PR DESCRIPTION
**Pull request by ivanbasov**
Fixes https://github.com/dotnet/roslyn/issues/29110

### CODE REVIEW

**Comment by ivanbasov** [comment]
@AmadeusW , @genlu this is a draft implementation. 
Tests fail now.
Actually, need a help from @AmadeusW to involve the presenter into the completion process. It seems that the broker gets `Options` from the presenter provider but then the presenter provider is called only by the test code. I expect that it should be called from `GetOrCreate` and then the presenter will be called for `Open `and `Update`

**Comment by ivanbasov** [comment]
@genlu please review
@AmadeusW thank you for your help! Tests seem to work

**Comment by genlu** [comment]
A test failed, seems to be related to this change.

**Comment by ivanbasov** [comment]
> A test failed, seems to be related to this change.

looking into it. thank you!

**Pull request merged**
