### PR TITLE
Features/local functions prototype

### PR DESCRIPTION
**Pull request by gafter**
This is a PR for integrating @khyperia's implementation of local functions into the `future` branch.

@AlekseyTs @jaredpar @VSadov @agocke I need one more reviewer for this code, please.

### CODE REVIEW

**Comment by gafter** [comment]
I'll bring this up-to-date with the future branch shortly and squash the history.

**Comment by gafter** [comment]
/cc @jaredpar @AlekseyTs @VSadov @agocke @khyperia @gafter

Although there are some issues that we had wanted to revisit based on the design review (definite assignment, for example) I believe this is close enough to what we want that we should integrate it into the future branch.

**Comment by gafter** [comment]
@AlekseyTs @jaredpar @VSadov @agocke I need one more reviewer for this code, please. Once this is pulled into the `future` branch, there will be a small number of issues opened against the feature for design changes (return type `var` inference will probably be removed; also definite assignment changes. These are discussed in the included documentation).

**Comment by tmat** [comment]
@gafter Please, also file an issue to implement and test Edit and Continue and EE support. I suspect that to be a non-trivial work item.

**Comment by gafter** [comment]
@tmat done, in #5156 and #5157.

**Comment by gafter** [comment]
@dotnet-bot test this please

**Comment by agocke** [comment]
Can we file a bug to remove or fix `var`? I don't want that to get dropped on the floor. Otherwise, :+1:

**Comment by gafter** [comment]
@agocke Filed #5168 for that.

**Pull request merged**
