### PR TITLE
Fix remote authoring

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1615873

Have validated this fixes things.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@sharwell could we add Services.props to Roslyn.sln so find-in-files will search it?
@tmat any ideas on how this could be caught ahead of time?  e.g. some task that validates tehse entries are valid.
@jasonmalinowski could we make it so that if we (Roslyn) issue a yellowbar in VS breaks integration tests?

**Review by genlu — APPROVED** [review]

**Comment by genlu** [comment]
>  ideas on how this could be caught ahead of time? e.g. some task that validates tehse entries are valid.

We could add a build step to read the metadata from `Microsoft.CodeAnalysis.Remote.ServiceHub.dll` to ensure the type exist

**Comment by tmat** [comment]
I think it would be best to have a source generator generate the factories (as partial classes) based on Services.props content.

**Comment by jasonmalinowski** [comment]
> @genlu: We could add a build step to read the metadata from Microsoft.CodeAnalysis.Remote.ServiceHub.dll to ensure the type exist

Should be easy to get that in a unit test I'd hope?

**Comment by jasonmalinowski** [comment]
> @jasonmalinowski could we make it so that if we (Roslyn) issue a yellowbar in VS breaks integration tests?

Absolutely; if we don't already have a test hook for our path for reporting errors it'd be easy enough to add.

**Pull request merged**
