### PR TITLE
FeatureOnOffOptionsProvider should provide FeatureOnOffOptions.InlineParameterNameHints option

### PR DESCRIPTION
**Pull request by retran**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
this doesn't seem particularly necessary.  we don't serialize this option to our OOP server.  Is this needed for something?  Thanks!

**Comment by jasonmalinowski** [comment]
I think we still use the discovered options either when we want integration tests to reset settings, or to show it in our UI that shows all settings if you build our private VSIXes...I think?

**Comment by retran** [comment]
@jasonmalinowski Thank you!

Looks like roslyn-integration-CI  has been failed due to an infrastructure problem.  Should it be restarted somehow?

**Comment by jasonmalinowski** [comment]
Thanks for the fix!

**Pull request merged**
