### PR TITLE
Generate assembly version without using the patch version.

### PR DESCRIPTION
**Pull request by JoeRobich**
Specify the version number in pieces so we can generate the assembly version using just the major and minor version numbers.

### CODE REVIEW

**Comment by JoeRobich** [comment]
@jasonmalinowski @tmat @jaredpar Is this a sane way to avoid breaking assembly redirects due to incrementing the patch version?

**Comment by tmat** [comment]
What issue are we trying to address?

**Comment by JoeRobich** [comment]
> What issue are we trying to address?

@tmat Updating the `VersionPrefix` so that nuget packages can have a patch number without breaking AssemblyVersion redirects.

**Comment by tmat** [comment]
But why would we need to do that?

**Comment by JoeRobich** [comment]
> But why would we need to do that?

@tmat The recommendation from the Version.props AssemblyVersion comment was to hardcode the AssemblyVersion when performing servicing to avoid breaking redirects. The hope was to avoid having to do that in the future, because you then have to ensure that change doesn't flow forward to other branches.

**Comment by tmat** [comment]
I see. Makes sense.

**Pull request merged**
