### PR TITLE
Use nameof expression for exceptions in Compilers projects

### PR DESCRIPTION
**Pull request by alexanderkozlenko**

### CODE REVIEW

**Comment by davkean** [comment]
@dotnet-bot test eta please

tag @dotnet/roslyn-compiler 

:+1:

**Comment by TyOverby** [comment]
LGTM

**Comment by cston** [comment]
LGTM

**Comment by TyOverby** [comment]
@davkean: looks like all the ETA tests passed

**Comment by davkean** [comment]
Thanks for the contribution!

**Pull request merged**
