### PR TITLE
Fix nested path check in FilePathUtilities

### LINKED ISSUE #4660: MSBuildWorkspace should add Project references correctly
While using MsBuildWorkspace to add project references to a project.
Working on project file: "C:\source\project1\project1.csproj"
and adding project reference to: "C:\source\project1.foo\project1.foo.csproj"

the project reference vil get an incorrect relative path as: ".foo\project1.foo.csproj"
it should have been: "..\project1.foo\project1.foo.csproj"

the bug is in: roslyn/src/Workspaces/Core/Desktop/InternalUtilities/FilePathUtilities.cs

```C#
        public static bool IsNestedPath(string basePath, string fullPath)
        {
            return fullPath.StartsWith(basePath, StringComparison.OrdinalIgnoreCase);
        }
```
Adding a backslash probably solves the bug.

```C#
        public static bool IsNestedPath(string basePath, string fullPath)
        {
            return fullPath.StartsWith(basePath + "\", StringComparison.OrdinalIgnoreCase);
        }
```

I will happily make a repro project if needed, or a PR for the fix

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #4660

Change IsNestedPath to only match complete directory names.

@pilchie @rchande @dpoeschl  please review

### CODE REVIEW

**Comment by mattwar** [comment]
@dotnet-bot test linux please

**Comment by mattwar** [comment]
@tmat the desktop library is not yet portable anyway.

**Comment by mattwar** [comment]
@dotnet-bot test linux please

**Comment by mattwar** [comment]
Needs review!  It's tiny.  Free cookies.

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
