### PR TITLE
Debugger displays for command-line items

### PR DESCRIPTION
**Pull request by davkean**
Added debugger displays for the command-line items, so they they look better under the debugger.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler

**Comment by cston** [comment]
LGTM

**Comment by jcouv** [comment]
@davkean Ping

**Comment by davkean** [comment]
@dotnet-bot retest vsi please

**Comment by davkean** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please
@dotnet-bot retest windows_release_vs-integration_prtest please

**Pull request merged**
