### PR TITLE
Revert 'Conditionally skip tests when fonts corrupted on the machine'

### PR DESCRIPTION
**Pull request by Youssef1313**
Reverts #13793

The test was conditionally skipped due to an issue occurring on Jenkins machines back at that time. The problem may not be occurring on Azure. If the test failed again, you can revert this.

cc: @jaredpar

### CODE REVIEW

**Comment by jcouv** [comment]
@jaredpar Your PR (https://github.com/dotnet/roslyn/pull/13793) that added this conditional skipping says it's a rare issue. 
Do you think it's better to keep this mitigation or try to run this test unconditionally again (risk of rare failure if root problem with installed fonts hasn't been resolved)?

**Comment by jcouv** [comment]
Ping @jaredpar to advise. This PR is reverting a mitigation you'd put in place. Are we confident the underlying issue with font installation was resolved?

**Comment by jaredpar** [comment]
> Are we confident the underlying issue with font installation was resolved?

No. Been a few years but my memory of digging into this is that I ended up finding an actual Windows bug that was "Won't Fixed". Hence it wasn't specific to Jenkins but rather Windows.

**Comment by jcouv** [comment]
Based on Jared's information, it seems safer to keep this workaround. I hope it makes sense.
I'll go ahead and close the PR. Thanks though

**Pull request closed without merging**
