### PR TITLE
Respect ParamArray attribute in source on a delegate parameter.

### LINKED ISSUE #2903: Compiler errors when calling a delegate with ParamArrayAttribute parameter
Following snippet produces a BC30311 and a BC30455 error, which should not be there? I want to copy the paramArray functionality using a delegate. 

```vb
Module Program

    Public Delegate Function MessageFormatter(ByVal format As String, <[ParamArray]> args As Object()) As String

    Sub Main()
        ToMimic("test {0}", 1)
        Log(Function(f) f("Test {0}", 1))
        Log(Function(f) f("Test"))
        Log(Function(f) "Test")
    End Sub

    Sub ToMimic(format As String, ParamArray args As Object())
        Console.WriteLine(format, args)
    End Sub

    Sub Log(messageFunc As Func(Of MessageFormatter, String))
        Console.WriteLine(messageFunc(New MessageFormatter(Function(format, args) String.Format(format, args))))
    End Sub

End Module
```
```
Error	BC30455	Argument not specified for parameter 'args' of 'Program.MessageFormatter'.
Error	BC30311	Value of type 'Integer' cannot be converted to 'Object()'
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #2903.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - Fixes #2903
- Customer scenario - ParamArray attribute in source on a delegate parameter is not respected, i.e. Overload Resolution doesn’t consider the parameter as a candidate for expanded ParamArray form. This is a behavior change by comparison to VS 2013 compiler. Note, the attribute is respected when delegate is imported from metadata.
- Fix description - Remove code that was specifically ignoring the attribute on delegate parameters. I assume that was an optimization.  
- Testing done - unit-tests.

@jaredpar FYI

**Comment by gafter** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Comment by pharring** [comment]
LGTM

**Comment by ManishJayaswal** [comment]
Approved 5/26 by ML Shiproom.

**Pull request merged**
