### PR TITLE
Revert "Tweak delays we have before we start incrementally analyzing in OOP."

### PR DESCRIPTION
**Pull request by RikkiGibson**
Reverts dotnet/roslyn#46426. We suspect this is related to some new RPS issues so opening the PR in order to test a revert of the change.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
What rps issues are you seeing?

**Comment by RikkiGibson** [comment]
@CyrusNajmabadi here's an insertion with some failures: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/264730?_a=overview

We've added you to a Teams chat to discuss

**Comment by sharwell** [comment]
@RikkiGibson Merging this revert would make the product _much, much_ slower (I believe 2.5x slower following typing). in the name of making it faster. We should exhaust efforts to avoid this before doing so.

**Comment by RikkiGibson** [comment]
This change has nothing to do with making the product faster or slower. My job is just to unblock our ability to ship the product. If we revert a change due to an RPS regression, the author is still welcome to try and integrate that change again after either seeking an exception for the RPS regression or modifying the implementation to prevent the regression.

**Comment by CyrusNajmabadi** [comment]
I'm going to investigate further to try to find some approach that meets all our needs.  In the meantime, i'm totally ok with thsi being reverted.  As i work on PRs in thsi space, i'll run them through the RPS system to know ahead of time if they're ok, or might have issues.

**Comment by RikkiGibson** [comment]
Superseded by #46540

**Pull request closed without merging**
