### PR TITLE
remove old syntax tree root tests

### LINKED ISSUE #4453: Some SyntaxTreeRootTests are commented out
Validation for some of the tests are commented out:
```
#ifdef false
...
#endif
```.

### PR DESCRIPTION
**Pull request by TyOverby**
Closes #4453

### CODE REVIEW

**Comment by TyOverby** [comment]
cc @jaredpar @dotnet/roslyn-compiler 

I've rewritten some tests that were commented out.

**Comment by jaredpar** [comment]
👍

**Comment by jaredpar** [comment]
@TyOverby looks like the new tests are failing with NRE.

**Comment by TyOverby** [comment]
@jaredpar Ack.  Thought I pushed the fix last night.  The problem was that I didn't understand Nothing.

**Comment by TyOverby** [comment]
@jaredpar tests pass.

**Comment by jaredpar** [comment]
:+1:

**Comment by TyOverby** [comment]
@dotnet/roslyn-compiler One more review please!

**Comment by agocke** [comment]
:+1:

**Pull request merged**
