### PR TITLE
Add dependencies between Swixproj

### PR DESCRIPTION
**Pull request by basoundr**
The Swixproj projects encapsulating each Vsix should mention the
dependencies betweeen them similar to the dependencies stated in the
contained Vsixes.

Tagging @dotnet/roslyn @shyamnamboodiripad @jmarolf @brettfo @jaredpar for review

### CODE REVIEW

**Comment by jaredpar** [comment]
👍

**Comment by basoundr** [comment]
Tagging @MattGertz for approval

**Comment by srivatsn** [comment]
👍

**Comment by srivatsn** [comment]
@MattGertz approved this in person. @basoundr don't add the approved tag yourself :)

**Comment by basoundr** [comment]
My bad. I wanted to add the asking for Approval label!! Just noticed, I added the wrong label

**Comment by MattGertz** [comment]
Yeah, to get me to approve, just tag me. :-)

**Comment by shyamnamboodiripad** [comment]
:+1:

**Pull request merged**
