### PR TITLE
Handle in-memory assemblies correctly in ScriptOptions.AddReference and when adding reference to the host object

### LINKED ISSUE #2246: Can't use object from a dynamic assembly as global object for script
To reproduce, create a dynamic assembly using Roslyn:

```
SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(@"
    public class MyGlobals
    {
        ...
    }
");
CSharpCompilation compilation = CSharpCompilation.Create("DynamicAssembly")
    .WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
    .AddSyntaxTrees(syntaxTree)
    .AddReferences(...);
byte[] assemblyBytes;
using (MemoryStream ms = new MemoryStream())
{
    compilation.Emit(ms);
    assemblyBytes = ms.ToArray();
}
Assembly assembly = Assembly.Load(assemblyBytes);
Type globalsType = assembly.GetType("MyGlobals");
object globals = Activator.CreateInstance(globalsType);
```

Then try and use the dynamic globals object in a script:

```
ScriptOptions options = new ScriptOptions()
    .AddNamespaces(...)
    .AddReferences(...);
CSharpScript.Eval(@"...", options, globals);
```

It throws an exception `System.ArgumentException : Empty path name is not legal.`. This is the same exception you see if you attempt to call `MetadataReference.CreateFromAssembly()` with a dynamic assembly. Since dynamic assemblies don't have a `Location`, the following call in `MetadataReference.cs" fails:

```
string location = AssemblyLocationLightUp.GetAssemblyLocation(assembly);
Stream peStream = FileStreamLightUp.OpenFileStream(location);
```

Normally I get around this in a compilation by creating my `MetadataReference` from a `Stream`:

```
MetadataReference dynamicReference;
using (MemoryStream ms = new MemoryStream(assemblyBytes))
{
    dynamicReference = MetadataReference.CreateFromStream(ms);
}
```

However, this doesn't work for script globals because of the following line in `Core\Script.cs` (https://github.com/dotnet/roslyn/blob/master/src/Scripting/Core/Script.cs#L375):

```
var globalsTypeAssembly = MetadataReference.CreateFromAssembly(this.GlobalsType.Assembly);
```

**TL;DR: A script always tries to use `MetadataReference.CreateFromAssembly()` to get the assembly metadata for the global object, and that approach doesn't work for global objects defined in dynamic assemblies.**

Not sure what a good fix would be. Perhaps allowing the specification of a `MetadataReference` for the global object to be used? Or checking the provided assembly references for one that contains the global object *before* attempting to get one? Alternatively, any fix for dynamic assemblies causing an exception with `MetadataReference.CreateFromAssembly()` would also resolve this more specific, but related issue.

### PR DESCRIPTION
**Pull request by tmat**
Throw NotSupportedException when a reference to an assembly without a location is added to script.
Don't try to implicitly add a reference to host assembly if it is an in-memory assembly.

Fixes #2246 

(originally PR #6246)

### CODE REVIEW

**Comment by davkean** [comment]
The failed runs look like real failures, I've never seen them before.

**Comment by tmat** [comment]
@davkean Yeah. A merge conflict.

**Comment by tmat** [comment]
test lin please

**Comment by tmat** [comment]
test linux please

**Comment by davkean** [comment]
What was the reason that Linux failed?

**Comment by filipw** [comment]
awesome, thanks a lot

**Pull request merged**
