### PR TITLE
Speedup Request::WriteToPipe

### PR DESCRIPTION
**Pull request by apolukhin**
Reserve buffer to avoid reallocations and data copying (not tested)

### CODE REVIEW

**Comment by pharring** [comment]
I haven't seen any bottlenecks in this code, but the change looks reasonable.

**Comment by theoy** [comment]
@pharring is right - we're in active planning to replace this component with a managed implementation (issue #137). Thanks a ton for the tip though. We're really appreciative that community members are reviewing the code and proposing improvements. :heart:

**Comment by gafter** [comment]
@Jenkins test this please

**Comment by gafter** [comment]
@agocke If this pull request is obsolete, can you please close it?

**Comment by gafter** [comment]
Closing this PR, as the relevant code no longer exists.

**Pull request closed without merging**
