### PR TITLE
Fix 233612 - Reload  window project failed after unload  window project in a C# blank App(Universal Windows 8.1) project

### PR DESCRIPTION
**Pull request by Pilchie**
Support "OnProjectRemoved" calls when the project has open documents

We already had code to deal with this case, we just hit checks before
it which threw.  The existing code needed to be modified to not modify
the collection it was enumerating though.

Fixes internal issue 233612.  Unloading a project with an open file that is
in a shared project or is linked would hit hit the exception in
CheckProjectCanBeRemoved because it still had Open documents.  Normal
projects didn't hit this because the documents were already closed by
RunningDocumentTableEvents.

Also fix a couple of other things I found while debugging

### CODE REVIEW

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
@dotnet/roslyn-ide

**Comment by Pilchie** [comment]
test vsi please

**Comment by Pilchie** [comment]
retest windows_vsi_p2_open_prtest please

**Comment by Pilchie** [comment]
Ping?  Anyone?

**Comment by jmarolf** [comment]
👍

**Comment by Pilchie** [comment]
Closing in favor of #12308

**Pull request closed without merging**
