### PR TITLE
Fix descriptions for XMLDoc Triple Apostrophes in some languages.

### PR DESCRIPTION
**Pull request by gekka**
Incorrect description on how to generate XML comments in Japanese, Korean, Russian, and Turkish.

### CODE REVIEW

**Comment by wli3** [comment]
@janbaltus could you update this in your database? ''' should not be translated

Once this is done, this PR is no longer needed. It will be reflected for the next loc pass

**Comment by gekka** [comment]
@jasonmalinowski I tried to fix the BasicVSResources.resx, is this correct?

**Comment by janbaltus** [comment]
@wli3 implemented

**Comment by jasonmalinowski** [comment]
@gekka ah: the change to the resx requires the .xlf files to get updated. All you should have to do is a local rebuild, and check in the changes that are made automatically.

**Comment by jasonmalinowski** [comment]
Thanks @gekka for the fix!

**Pull request merged**
