### PR TITLE
Use dotnet-external-vs2019-preview for integration testing

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by MattGal** [comment]
Looks like that pipeline isn't actually enabled.

**Comment by jaredpar** [comment]
@MattGal 

> Looks like that pipeline isn't actually enabled.

Can you elaborate? That pipeline is the roslyn-integration-ci pipeline and it ran as a part of this PR. Feel like I'm missing something.

**Comment by MattGal** [comment]
@jaredpar I simply meant that Windows_VisualStudio_Integration_Tests did not run on dotnet-external-vs2019-preview as part of this PR, which it hadn't at 15 hours ago when I commented.  It did get run last night at 2/19/2019, 9:39:26 PM, but all history of this is seemingly lost so I am guessing Sam pushed more changes.

**Comment by sharwell** [comment]
@MattGal The build is here: https://dev.azure.com/dnceng/public/_build/results?buildId=100146

**Pull request merged**
