### PR TITLE
Report semantic errors even in syntactically invalid lambdas.

### LINKED ISSUE #1867: Have compiler return semantic errors in lambdas even in the presence of syntax errors
Today, the compiler does not return semantic errors inside lambdas in the IDE if there are syntax errors.   This causes several quick fix scenarios to fail inside lambdas (for example #1239, #1241, and #1744 are all caused by this problem).  

Consider the code sample below from issue #1239:
```C#
using System.Threading.Tasks;

class C {
    C() {
        Task.Run(() => {
            new C(0)
        });
    }
}
```

_new C(0)_ will never be squiggled by the IDE because of the lack of a semicolon.  This makes quick-fixes that could generate a constructor unable to run because there is no error to trigger them.  

By having the compiler return semantic errors in lambdas even in the presence of syntax errors, many more IDE scenarios will "Just Work"

### PR DESCRIPTION
**Pull request by gafter**
Fixes #1867 
@dotnet/roslyn-compiler @CyrusNajmabadi Please review.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
This will help, but there will be a few more cases with lambdas where we'll still need errors coming through.  When this gets checked in, i'll be able to let you know! (or, if you want that info sooner, I can merge your changes locally and figure it out).  Let me know!

**Comment by gafter** [comment]
@dotnet-bot test prtest/mac/dbg/unit32 please

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I please have another set of eyes on this?

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Can I please have another set of eyes on this?

**Comment by TyOverby** [comment]
LGTM

**Pull request merged**
