### PR TITLE
Fix tuple deconstruction for field name containing escaped context keyword 

### LINKED ISSUE #27251: Incorrect deconstructions suggestion in the Visual Studio for escaped field name of value tuple
Hi,

I'm used **Visual Studio 15.6.6** and it give to me incorrect suggestion at the light bulb for the code bellow:

```c#
...
// Doesn't matter what the type of escaped field
var collection = new List<(int position, int @delegate)>();
foreach (var item in collection)
{
    ...
}
```

Suggestion is given for the `item` and after applying I receive `delegate` variable without escaping and, of course, with compile time errors:

```c#
var collection = new List<(int position, int @delegate)>();
foreach (var (position, delegate) in collection)
{
    ...
}
```

If this issue should be moved to the [Visual Studio Community](https://developercommunity.visualstudio.com/spaces/8/index.html) instead of Roslyn repository, let me know about it.

### PR DESCRIPTION
**Pull request by chborl**
Fixes #27251

### CODE REVIEW

**Comment by jcouv** [comment]
@CyrusNajmabadi No deconstruction in VB

**Comment by jinujoseph** [comment]
test windows_debug_vs-integration_prtest

**Comment by chborl** [comment]
VB can have escaped keywords, but to my knowledge tuple deconstruction isn't implemented in VB.

**Comment by chborl** [comment]
test roslyn-CI

**Pull request merged**
