### PR TITLE
Move 'Wrapping' code actions down to 'Feature' layer.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This had to be at the 'Editor' layer previous because 'indentation computation' was defined at the editor-layer.

We've since moved 'indentation computation' down to teh workspace layer (since it is only dependent on formatting), so we can move these actual code action features down to the appropriate layer where the rest of the code actions live.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @jasonmalinowski @mavasani @dotnet/roslyn-ide .  Trivial PR.  Thanks!

**Comment by CyrusNajmabadi** [comment]
@genlu @mavasani can you merge in please?

**Comment by mavasani** [comment]
@CyrusNajmabadi There seemed to be build failures (unrelated to your change). I have re-started all the tests.

**Comment by CyrusNajmabadi** [comment]
Oh, thanks! :)

**Comment by CyrusNajmabadi** [comment]
@mavasani @genlu all green.  Thanks!

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
