### PR TITLE
Merge master to features/UsedAssemblyReferences

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Comment by JoeRobich** [comment]
I started a validation insertion for this PR - https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/304044

**Comment by JoeRobich** [comment]
Removing the auto-merge label until cloudbuild issues are resolved.

**Comment by AlekseyTs** [comment]
@JoeRobich 

> Will approve once cloudbuild issues are resolved.

Do you need to keep this PR alive for the investigation? Otherwise, I think we can merge, this PR is targeting a feature branch.

**Comment by JoeRobich** [comment]
> this PR is targeting a feature branch.

Thanks. I missed that.

**Pull request merged**
