### PR TITLE
Simplify code generation options code

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani

**Comment by CyrusNajmabadi** [comment]
Tagging @mavasani @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
@mavasani can you PTAL/merge?  Thanks!

**Comment by genlu** [comment]
There seems to be some issue with CI. I have triggered rerun

**Comment by CyrusNajmabadi** [comment]
Thanks @genlu

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
