### PR TITLE
Add PR template

### PR DESCRIPTION
**Pull request by Pilchie**
Tagging @dotnet/roslyn-infrastructure and @MattGertz.

This way, PRs should be pre-populated with the questions we want answered.

This will merge into master, but we can change it there, and then just re-update in each release branch once as we make it.

### CODE REVIEW

**Comment by svick** [comment]
Since new contributors will get to see this when making their first PR (for example), should the template explain terms like Escrow and generally be more friendly?

Though maybe that's not necessary, depending on how temporary this is.

**Comment by AdamSpeight2008** [comment]
Is this for every branch? or just `master`?

**Comment by Pilchie** [comment]
The plan is to have this in branches that are created for releases as we try to tighten up on the changes and prevent regressions.  I wouldn't expect this in master or feature development branches.

**Comment by Pilchie** [comment]
Ping @MattGertz for permission to add this to the rc branch?

**Comment by MattGertz** [comment]
Already approved.

**Comment by Pilchie** [comment]
Doh! I always forget that GitHub doesn't send a notification when labels change.

Thanks!

**Pull request merged**
