### PR TITLE
Don't set up a classification format map for the immediate window bec…

### PR DESCRIPTION
**Pull request by rchande**
…ause we don't allow classification within it.

### CODE REVIEW

**Comment by rchande** [comment]
@dotnet/roslyn-ide  please review.

As noted by @DustinCampbell, we don't allow classification in the immediate window so there's no reason to setup a classification type map. 

This addresses https://devdiv.visualstudio.com/DevDiv/_workitems?id=130129&triage=true&fullScreen=false&_a=edit

**Comment by rchande** [comment]
Since we'll now do half as much work, this should cut the 90th percentile delay of 5.4 seconds in half.
Note that one proposed solution was to completely disable the ColorThemeFixer, but that entirely prevents Roslyn tooltips from pickup up Fonts and Colors changes (confirmed by David Pugh).

**Comment by rchande** [comment]
Also tag @MattGertz for ask mode approval

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by MattGertz** [comment]
Approved pending tests.  Glad to see this.  @Pilchie we discussed a different route earlier at staff, but I am assuming that you are OK with this?

**Comment by DustinCampbell** [comment]
Out of curiosity, does the "immediate" classification format map affect colorization in the Watch window?

**Comment by DustinCampbell** [comment]
I don't *think* it does, but it's worth checking.

**Comment by DustinCampbell** [comment]
Also, note that it won't cut the time in half if the bulk of the time isn't spent copying values, but rather the first hit causing something else to load. Have we measured that to know whether this will really address the problem?

**Comment by rchande** [comment]
@DustinCampbell:
PerfWatson shows the delays as caused by CPU time, but also GCs due to allocations in the editor APIs we call--hopefully making half as many calls will help.
As far as I can tell, we don't allow classification in the watch window.

**Comment by DustinCampbell** [comment]
Sounds good.

**Pull request merged**
