### PR TITLE
Remove caching of declaring syntax references for symbols in analyzer… 

### LINKED ISSUE #7156: Compiler code crosses abstraction boundaries
Regarding #4988
                                                                                                         
- This PR adds code to the compiler that inappropriately crosses abstraction boundaries. The Compiler layer should not be making calls into the Analyzer layer that is logically above it (e.g. in `src/Compilers/CSharp/Portable/Symbols/Source/SourceMemberContainerSymbol.cs`).
- The presence of an event queue does not indicate that the compiler is being run under control of an analyzer driver.
- We do not want the compiler itself to be using a `ConditionalWeakTable` during its normal operation.

@mavasani

### PR DESCRIPTION
**Pull request by mavasani**
… driver - this was done as part of addressing some performance regressions, but the subsequent tuning should make the original change redundant.

Fixes #7156

### CODE REVIEW

**Comment by davkean** [comment]
Looks like eta failed due to NuGet package restore timing out: 

```
Restoring packages: Roslyn (this may take some time)
MsBuild timeout out while trying to get project to project references.
Restore failed with ERRORLEVEL 1
Restore failed with ERRORLEVEL 1
Roslyn Build and Test
```

Which ended up causing the rest of build to fail. We need to change BuildAndTest.proj to fail in that case, filed https://github.com/dotnet/roslyn/issues/7237 to track it.

The timeout for NuGet calling MSBuild also looks too short, talking to them.

retest eta please

**Comment by gafter** [comment]
@dotnet/roslyn-compiler Compiler team review, please.

**Comment by gafter** [comment]
LGTM

**Comment by TyOverby** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Comment by mavasani** [comment]
Holding off this PR for some more time as per the request from @KevinH-MS

**Comment by gafter** [comment]
oops, I just pulled this before reading your "holding off" message. Do you want me to revert?

**Comment by mavasani** [comment]
@KevinH-MS did some perf validations, so we may be okay. Kevin, do you want Neal to revert or you want to do some further validations?

**Comment by jaredpar** [comment]
Was perf testing done on the change which originally incorrectly crossed the abstraction boundary?

**Comment by mavasani** [comment]
Yes, it reduced a bunch of allocations from DeclaringSyntaxReferences while running analyzers in IDE live analysis - but it wasn't the primary cause of the perf regression back then.

Compiler team should consider not re-computing declaring syntax references every time this property is accessed on the symbols. Current implementation will always create new syntax references (see [here](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/Symbols/Source/SourceNamespaceSymbol.vb,409) for an example). The fact that a property does such allocations on every access also violates basic design guidelines.

**Comment by KevinH-MS** [comment]
@gafter Don't worry about reverting.  I'll just keep it in mind and see if any regressions show up tomorrow.

**Comment by gafter** [comment]
@mavasani Yes, this is a classic time-space trade-off. Whether to cache or not depends on usage and should be decided based on measurement. If we elect to cache, it should simply be a field of the class, and not in some side table.

**Pull request merged**
