### PR TITLE
Handle ReduceExtensionMethod throwing Argument exception. 

### PR DESCRIPTION
**Pull request by jmarolf**
It is unclear how this can happen but we have several instances reported.

### CODE REVIEW

**Comment by jmarolf** [comment]
@dotnet/roslyn-ide

**Comment by jasonmalinowski** [comment]
We should not be try/catching exceptions. Do we understand where the throw is coming from?

**Comment by jmarolf** [comment]
@jasonmalinowski exception is coming from [EnsureVbSymbolOrNothing](https://github.com/dotnet/roslyn/blob/master/src/Compilers/VisualBasic/Portable/Symbols/SymbolExtensions.vb#L425)

**Comment by jmarolf** [comment]
@CyrusNajmabadi having a look at https://github.com/dotnet/roslyn/issues/8036

**Pull request closed without merging**
