### PR TITLE
Move LanguageServer out of Features directory

### PR DESCRIPTION
**Pull request by tmat**
LanguageServer is not part of Features layer.
This matches layering in the Solution.

### CODE REVIEW

**Comment by tmat** [comment]
@dibarbet

**Comment by tmat** [comment]
Waiting for https://github.com/dotnet/roslyn/pull/73566 ...

**Comment by DustinCampbell** [comment]
> Waiting for #73566 ...

Thanks @tmat! I've merged.

**Review by DustinCampbell — APPROVED** [review]
I looked through all of the files that weren't pure renames. Looks good to me!

**Pull request merged**
