### PR TITLE
Unify VS Setup

### PR DESCRIPTION
**Pull request by jasonmalinowski**
A change to move some of the stuff in our language service integration to GitHub.

### CODE REVIEW

**Comment by jaredpar** [comment]
LGTM

**Comment by tmeschter** [comment]
I updated the Commands.vsct file this morning, so you may want to pull in those changes before you move it to open.

**Comment by jasonmalinowski** [comment]
@tmeschter Can you verify I've consumed the update?

**Comment by tmeschter** [comment]
Looks like it's all up to date.
:+1:

**Comment by jaredpar** [comment]
LGTM

**Pull request merged**
