### PR TITLE
Porting tuple tests over to VB

### PR DESCRIPTION
**Pull request by jcouv**
Porting a first chunk for tuples tests to VB.

### CODE REVIEW

**Comment by jcouv** [comment]
>             ' REMOVE AFTER REVIEW: this test crashes in TypeSubstitution

@VSadov, you mentioned there is an open issue for this known limitation in VB TypeSubstitution. I couldn't find it. Could you share the link?

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:3026 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by jcouv** [comment]
>             ' REMOVE AFTER REVIEW those errors are different than in C# and there seems to be a duplicate

Note that one of the errors is duplicated and there are differences with the same test in C#, which produces:
```C#
  // (10,12): error CS0518: Predefined type 'System.ValueTuple`2' is not defined or imported
                //     static (T1 first, T2 second) M<T1, T2>()
                Diagnostic(ErrorCode.ERR_PredefinedTypeNotFound, "(T1 first, T2 second)").WithArguments("System.ValueTuple`2").WithLocation(10, 12),
                // (12,16): error CS0518: Predefined type 'System.ValueTuple`2' is not defined or imported
                //         return (default(T1), default(T2));
                Diagnostic(ErrorCode.ERR_PredefinedTypeNotFound, "(default(T1), default(T2))").WithArguments("System.ValueTuple`2").WithLocation(12, 16)
```

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:3917 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by jcouv** [comment]
>             ' REMOVE AFTER REVIEW This is different than C#

@VSadov, Is this expected?

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:4144 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by jcouv** [comment]
>             ' Getting error: a.vb(6) : error BC30149: Class 'C' must implement 'Function M(a As (Integer, Integer)()) As (Integer, Integer)()' for interface 'I'.

@VSadov, I suspect this is a bug in tuple unification. If you could confirm, I will file an issue.

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:4322 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by jcouv** [comment]
>             ' REMOVE AND UPDATE AFTER REVIEW

Note a crash here.

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:4535 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by jcouv** [comment]
@VSadov @dotnet/roslyn-compiler I will take a break on porting tests, and this PR is already rather large, so this chunk can be reviewed. 
In particular, look for the word "REMOVE".

After you confirm whether the change in behavior is expected or is an issue, I will remove all those markers.

**Comment by VSadov** [comment]
Thanks!!
NOTE. While working on a default type inference, I have fixed several bugs in conversions/inference. Mostly around missing special cases for tuples containing typeless constructs (Nothing, lambdas, array literals).

You may be hitting those. We should see how this works once that is merged in.

**Comment by VSadov** [comment]
>             ' REMOVE AFTER REVIEW: this test crashes in TypeSubstitution

[https://github.com/dotnet/roslyn/issues/13298](https://github.com/dotnet/roslyn/issues/13298)

---
In reply to: [240827757](https://github.com/dotnet/roslyn/pull/13209#issuecomment-240827757) [](ancestors = 240827757)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:3026 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by VSadov** [comment]
>             ' REMOVE AFTER REVIEW This is different than C#

Call (42, "Alice").Extension()

same as :
   Call (New S1()).ToSting()


---
In reply to: [240828407](https://github.com/dotnet/roslyn/pull/13209#issuecomment-240828407) [](ancestors = 240828407)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:4144 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by VSadov** [comment]
>             ' Getting error: a.vb(6) : error BC30149: Class 'C' must implement 'Function M(a As (Integer, Integer)()) As (Integer, Integer)()' for interface 'I'.

seems like a bug in type equality when arrays and tuples are involved

---
In reply to: [240828612](https://github.com/dotnet/roslyn/pull/13209#issuecomment-240828612) [](ancestors = 240828612)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/CodeGen/CodeGenTuples.vb:4322 in 207f479. [](commit_id = 207f4794d96c836f50364b674de490faac783cc1, deletion_comment = False)

**Comment by jcouv** [comment]
@VSadov I replaced all the REMOVE markers and opened corresponding issues. I'll go ahead with merge.

**Pull request merged**
