### PR TITLE
Remove EOLN check from MarkupTestFile

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@jaredpar @jasonmalinowski

**Comment by tmat** [comment]
This is causing issues on Mac. Unfortunately the Mac machines are inaccessible currently, so until we figure out what's going on remove these checks.

**Comment by jasonmalinowski** [comment]
Fine by me. This check (at least in some form) is going to be important -- we're going to have to figure out a consistent story for IDE unit tests in how we want to handle newlines in source files they analyze.

**Comment by jaredpar** [comment]
@jasonmalinowski what is this check trying to enforce though?  That we have line endings consistent with the OS platform?

**Comment by jasonmalinowski** [comment]
It's enforcing that the string is consistent with itself.

This was fallout of us using XML doc comments in the VB tests to work around the lack of multi-line literals. If you have a VB XML doc comment and ask for it's value, the resulting string is always LF only, despite the platform you're running on. I enforced a convention that in all places we grabbed a value from an XML literal we immediately converted from LF to CRLF for consistency with multi-line string literals. We had lots of code that was concating strings of different line-ending stuff together, resulting in hilarity when unit tests ran on them.

**Comment by jaredpar** [comment]
@jasonmalinowski so the test is just enforcing that there is a single line ending used throughout the string?

**Comment by jasonmalinowski** [comment]
Oh, sorry, I mis-read the check: it's asserting that it should contain CRLF, since the convention was:

XML  = LF
string = CRLF

Now that we're cross-plat this needs to go away, but it's going to require us fixing a lot of helpers to be properly cross-plat aware. All work that needs to happen.

**Pull request merged**
