### PR TITLE
Fix unintentional removal of "InsertionText" property from implements…

### PR DESCRIPTION
**Pull request by rchande**
… clause completion items

### CODE REVIEW

**Comment by rchande** [comment]
Tag @dotnet/roslyn-ide 
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems?_a=edit&id=394863&triage=true
I went through all the other overrides of CreateItem and did not find misuses of `WithProperties`

**Comment by jasonmalinowski** [comment]
@rchande Does this mean implements intellisense is completely broken? We didn't have more tests on that?

**Comment by rchande** [comment]
@jasonmalinowski Correct, it appears there were no tests that validated committing implements clause intellisense and that things got a little scrambled when we rewrote the completion APIs.

**Comment by jasonmalinowski** [comment]
Should this be hitting something sooner than 15.3?

**Comment by rchande** [comment]
@jasonmalinowski What's the bar for the close milestone (cc @Pilchie) ?

**Comment by Pilchie** [comment]
What is the user impact here?

**Comment by rchande** [comment]
@Pilchie It's impossible to use implements clause completion to add an implements clause if you're implementing a generic method.

**Pull request merged**
