### PR TITLE
Ensure SemanticModel reports node as a default instance access rather than as a type reference, when the type reference is reclassified as such.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Addresses DevDiv 1169533.

@VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
- Bug number - DevDiv 1169533
- Customer scenario – IDE features are unaware of the fact that a type reference is reclassified as a Default Instance access by the compiler, this causes incorrect IDE behavior during refactoring/simplification/colorization. Consider the following code:
```
Public Class DetailsForm
    Private Sub DetailsForm_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Form1.Close()
    End Sub
End Class
```  
```Form1.Close()``` calls Close method on a Default Instance of Form1. However, the ```Form1```  is colorized as a type and IDE offers to simplify ``` Form1.Close()``` to ``` Close()```. Though the simplification doesn’t cause any compilation errors, it actually calls Close method on an instance of a DetailsForm, which is not what developer originally intended.
- Fix description – Adjust syntax node associated with a bound node for a Default Instance access to ensure that SemanticModel reports node as a default instance access rather than as a type reference, when the type reference is reclassified as such.
- Testing done - unit-tests.

 @jaredpar FYI

**Comment by MattGertz** [comment]
Approved 6/1 by ML Shiproom.

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @gafter, @agocke, @jaredpar, @khyperia Please review.

**Comment by jaredpar** [comment]
:+1:

**Comment by gafter** [comment]
:+1:

**Pull request merged**
