### PR TITLE
Prototype #references, #files, and #imports

### PR DESCRIPTION
**Pull request by amcasey**
* `#references` - referenced assemblies
 * `#files` - loaded files
 * `#imports` - imported namespaces/types/aliases

They should work in both csi and the C# interactive window.  All but `#imports` should also work in VB, to the extent that VB works at all.

Caveat: `#references` will not show references inherited from previous submissions until https://github.com/dotnet/roslyn/issues/6587 is fixed.

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @dotnet/roslyn-interactive please give this a whirl and let me know what you think of it.  If the behavior seems desirable, I'll lock it in with tests.

**Comment by dpoeschl** [comment]
retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/1604/
// Retest reason: Testing StashPop (sorry for the noise Andrew)

**Comment by heejaechang** [comment]
@amcasey I believe this is specific to your PR?

**Comment by amcasey** [comment]
@heejaechang yes.

**Comment by amcasey** [comment]
@tannergooding Why don't you take over the branch, since it dovetails so nicely with your proposal?  You might want to build it locally and play around with the commands to get a feel for this design - it's totally experimental and open to improvements.

Things to consider:
 1. There are no tests of this code.  I didn't want to lock in experimental behavior.
 1. `#references` doesn't include references from previous submissions.  This code calls the correct API, but the API is broken.  See @tmat for details.

**Pull request closed without merging**
