### PR TITLE
Merge future-stabilization into future

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from future-stabilization into future.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-future-stabilization-into-future20160315-150029
git reset --hard upstream/future
git merge upstream/future-stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-future-stabilization-into-future20160315-150029 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by gafter** [comment]
please test prtest/lin/dbg/unit32

**Comment by gafter** [comment]
@dotnet-bot retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/5133/
// Retest reason:

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/502/
// Retest reason: known error list issue.

**Comment by heejaechang** [comment]
@dotnet-bot retest prtest/win/vsi/p2 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_vsi_p2/505/
// Retest reason: known goto definition issue.

**Comment by davkean** [comment]
@agocke Have you seen this Linux failure before: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/5133/consoleFull#-157160608879494335-f7bd-47d0-8771-8661e00c2db2?

**Pull request merged**
