### PR TITLE
Use CurrentUICulture to load message strings and for string formatting within Doc Comment Compiler.

### PR DESCRIPTION
**Pull request by AlekseyTs**
@VSadov, @gafter, @jaredpar, @agocke Please review.

### CODE REVIEW

**Comment by gafter** [comment]
I'm uncomfortable relying on ambient state such as the current UI culture. Is a user-specified culture already threaded through so that it has a reliable value, even in compiler-server scenarios?

**Comment by AlekseyTs** [comment]
Yes, command line compiler (even in compiler-server scenarios) sets CurrentUICulture to the value requested by the user.

**Comment by gafter** [comment]
LGTM

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
