### PR TITLE
Move GenerateConstructorFromMembers to language dependent implementations

### LINKED ISSUE #33287: GenerateConstructorFromMembersCodeRefactoringProvider encounted an error and has been disabled. (VB.NET not supported)
VSF_TYPE_MARKDOWNStacktrace:

```
System.NotSupportedException : ThrowExpressions are not supported in Visual Basic
   at Microsoft.CodeAnalysis.VisualBasic.CodeGeneration.VisualBasicSyntaxGenerator.ThrowExpression(SyntaxNode expression)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxGeneratorExtensions.CreateThrowArgumentNullExpression(SyntaxGenerator factory,Compilation compilation,IParameterSymbol parameter)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxGeneratorExtensions.CreateAssignWithNullCheckStatement(SyntaxGenerator factory,Compilation compilation,IParameterSymbol parameter,SyntaxNode fieldAccess)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxGeneratorExtensions.AddAssignmentStatements(SyntaxGenerator factory,Compilation compilation,IParameterSymbol parameter,SyntaxNode fieldAccess,Boolean addNullChecks,Boolean preferThrowExpression,ArrayBuilder`1 nullCheckStatements,ArrayBuilder`1 assignStatements)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxGeneratorExtensions.CreateAssignmentStatements(SyntaxGenerator factory,Compilation compilation,ImmutableArray`1 parameters,IDictionary`2 parameterToExistingFieldMap,IDictionary`2 parameterToNewFieldMap,Boolean addNullChecks,Boolean preferThrowExpression)
   at Microsoft.CodeAnalysis.Shared.Extensions.SyntaxGeneratorExtensions.CreateFieldDelegatingConstructor(SyntaxGenerator factory,Compilation compilation,String typeName,INamedTypeSymbol containingTypeOpt,ImmutableArray`1 parameters,IDictionary`2 parameterToExistingFieldMap,IDictionary`2 parameterToNewFieldMap,Boolean addNullChecks,Boolean preferThrowExpression,CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.GenerateConstructorFromMembers.GenerateConstructorFromMembersCodeRefactoringProvider.FieldDelegatingCodeAction.GetChangedDocumentAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.GenerateConstructorFromMembers.GenerateConstructorFromMembersCodeRefactoringProvider.GenerateConstructorWithDialogCodeAction.ComputeOperationsAsync(&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsAsync(&lt;Unknown Parameters&gt;)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.&lt;&gt;c__DisplayClass17_0.&lt;InvokeCore&gt;b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

_This issue has been moved from https://developercommunity.visualstudio.com/content/problem/448852/generateconstructorfrommemberscoderefactoringprovi-1.html
VSTS ticketId: 788929_
_These are the original issue comments:_
(no comments)
_These are the original issue solutions:_
(no solutions)

### PR DESCRIPTION
**Pull request by ryzngard**
fixes #33287 

In VB, we can't generate null checks in the same way and it currently throws when we try. The setting is language dependent, but could potentially be enabled for VB, so just ignore the value. If possible, could we move this setting to CSharp only? Is it a breaking change to move that setting?

### CODE REVIEW

**Comment by JoeRobich** [comment]
You could still generate null checks for VB; you would just not want to create throw expressions. There could be a version of [`CreateAssignWithNullCheckStatement`](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/Shared/Extensions/SyntaxGeneratorExtensions.cs#L285) that generates a throw statement inside an if statement.

**Comment by CyrusNajmabadi** [comment]
I agree with  @JoeRobich This should be simple to support on the existing system afaict.

**Comment by ryzngard** [comment]
Yea, looking at it, syntax generator should handle that `preferThrowExpression` won't work for VB. I'll implement that change instead. Thanks for keeping me on top of it @JoeRobich 	@CyrusNajmabadi 	 :)

**Comment by ryzngard** [comment]
Does this check need to be added to the public api for syntax generator?

**Comment by CyrusNajmabadi** [comment]
It does not

**Pull request merged**
