### PR TITLE
update auto-merge tool to support multiple repositories and options

### PR DESCRIPTION
**Pull request by brettfo**
Update the merge tool to support various options at the command line to enable creating PRs for different repos.  Also includes the NuGet package Mono.Options to make command line parsing easier.

For test-only PRs created with this code see #7836 and dotnet/roslyn-internal#501.

FYI @dotnet/roslyn-infrastructure, specifically @amcasey, @davkean, @tannergooding, and @TyOverby.

Remaining work items:
- Auto-merge if there were no conflicts and all tests pass.
- List all files with merge conflicts and add a comment to the PR that those files need additional signoff.

### CODE REVIEW

**Comment by brettfo** [comment]
Commands used to generate sample PRs:

``` bash
GitMergeBot.exe -a 1234 -r roslyn -s master -d future --su=roslyn-bot --du=dotnet
```

and

``` bash
GitMergeBot.exe -a 1234 -r roslyn-internal -s master -d future --su=roslyn-bot --du=dotnet
```

**Comment by jmarolf** [comment]
They don't have a binary version of Mono.Options we can use?

**Comment by TyOverby** [comment]
LGTM.  Not sure if a full opt-parse library is required, but I'm not opposed to adding the full source to our repo.

**Comment by brettfo** [comment]
No binary option, just source (that's what the NuGet package installed), and while I agree that a full library is a little overkill, this was way easier than messing around with custom string parsing.

**Comment by brettfo** [comment]
Ping for any more feedback before I merge and update the tool.

**Comment by brettfo** [comment]
Updated to not create a new PR if an existing one is already open.

**Comment by brettfo** [comment]
Not waiting for tests since this code doesn't run anything.

**Pull request merged**
