### PR TITLE
Fix tabstop and focus behavior for member selection control

### PR DESCRIPTION
**Pull request by ryzngard**
Fixes [internal bug 794061](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/794061)

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by JoeRobich — APPROVED** [review]

**Review by davidwengier — APPROVED** [review]
Pro-tip: If you reference internal bugs as `AB#<num>` then they automatically get linked, and if you says "Fixes AB#794061" then merging the PR will automatically resolve the issue, just like a GitHub one :)

**Review by davidwengier — APPROVED** [review]
Pro-tip: If you reference internal bugs as `AB#<num>` then they automatically get linked, and if you says "Fixes AB#794061" then merging the PR will automatically resolve the issue, just like a GitHub one :)

**Comment by davidwengier** [comment]
I swear I only pressed the button once :P

**Comment by ryzngard** [comment]
Based on feedback from @AbhitejJohn I'm looking at a different route. Thanks for all the quick reviews :) I'll close this one to not get confused over who has approved what

**Pull request closed without merging**
