### PR TITLE
Disable checks for non-compliant overloading for extension methods to match VS2013 behavior

### LINKED ISSUE #4704: VB compiler is unable to consume extension methods that are utilizing unsupported overloading.
Ported from DevDiv 1202022.

Given a library
```
// Metadata version: v4.0.30319
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly lib
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [mscorlib]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                             63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [mscorlib]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [mscorlib]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 07 01 00 00 00 00 ) 

  .custom instance void [mscorlib]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 

  .hash algorithm 0x00008004
  .ver 0:0:0:0
}
.module lib.dll
// MVID: {866DFDCB-9BF6-47CA-A90A-4C1FCEA128C0}
.imagebase 0x10000000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x00BA0000


// =============== CLASS MEMBERS DECLARATION ===================

.class public abstract auto ansi sealed beforefieldinit Matrix
       extends [mscorlib]System.Object
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 

.method public hidebysig static void 
        ToArray(int32 a,
                string[] b) cil managed
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
  .param [2]
  .custom instance void [mscorlib]System.ParamArrayAttribute::.ctor() = ( 01 00 00 00 ) 
  // Code size       11 (0xb)
  .maxstack  1
  IL_0000:  ldstr      "1"
  IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
  IL_000a:  ret
} // end of method Matrix::ToArray

.method public hidebysig static void 
        ToArray(int32 a,
                [out] string[]& b) cil managed
{
  .custom instance void [mscorlib]System.Runtime.CompilerServices.ExtensionAttribute::.ctor() = ( 01 00 00 00 ) 
  // Code size       11 (0xb)
  .maxstack  1
  IL_0000:  ldstr      "2"
  IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
  IL_000a:  ret
} // end of method Matrix::ToArray

} // end of class Matrix

// =============================================================
``` 

The following code is compiled without errors by VS2013 compiler and prints 1:
```
Module Module1
    Sub Main()
        Dim a As Integer = 5
	a.ToArray("Field1", "Field2", "Field3")
    End Sub
End Module
```

Roslyn reports an error:
```
(4) : error BC31429: 'ToArray' is ambiguous because multiple kinds of members with this name exist in class 'Matrix'.
    a.ToArray("Field1", "Field2", "Field3")
      ~~~~~~~
```

Both compilers produce the same errors for the following code:
```
Module Module1
    Sub Main()
        Dim a As Integer = 5

        Matrix.ToArray(a, "Field1", "Field2", "Field3")
        Matrix.ToArray(a, {"Field1", "Field2", "Field3"})
    End Sub
End Module

(5) : error BC31429: 'ToArray' is ambiguous because multiple kinds of members with this name exist in class 'Matrix'.
        Matrix.ToArray(a, "Field1", "Field2", "Field3")
        ~~~~~~~~~~~~~~
(6) : error BC31429: 'ToArray' is ambiguous because multiple kinds of members with this name exist in class 'Matrix'.
        Matrix.ToArray(a, {"Field1", "Field2", "Field3"})
        ~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #4704.

@gafter, @VSadov, @jaredpar, @agocke Please review.

### CODE REVIEW

**Comment by gafter** [comment]
:+1:

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @jaredpar, @agocke Please review. Need a second sign-off.

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @jaredpar, @agocke Please review. Need a second sign-off.

**Comment by agocke** [comment]
:+1:

**Pull request merged**
