### PR TITLE
add 64bit detect code to razor remote host client

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@rynowak can you take a look? I tried to test this on my machine but Razor was giving me some legacy.textchange type load issue on RoslynDev hive. do you know what that issue is?

**Comment by rynowak** [comment]
> I tried to test this on my machine but Razor was giving me some legacy.textchange type load issue on RoslynDev hive. do you know what that issue is?

What branch? - we might need the WTE team to do an insertion there.

**Comment by heejaechang** [comment]
the drop I have is 
image

**Comment by rynowak** [comment]
Ok if you are using prerel, try updating. I have 26929 and it is working

**Comment by heejaechang** [comment]
closed and reopen to run tests. looks like Jenkins are not working properly

**Comment by heejaechang** [comment]
retest windows_debug_vs-integration_prtest  please

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @dotnet/roslyn-ide can you take a look? @sharwell

**Comment by heejaechang** [comment]
ping? can I get some code review? @333fred @mavasani ? it is adding A/B testing check for Razor component in Roslyn side.

**Comment by heejaechang** [comment]
@Pilchie sorry, didn't know about ask mode on master. can I get approval?

**Comment by Pilchie** [comment]
Approved.

**Pull request merged**
