### PR TITLE
 Stop emitting ModuleInitializerAttribute as a custom attribute since it has no runtime meaning

### PR DESCRIPTION
**Pull request by jnm2**
The presence of ModuleInitializerAttribute as a custom attribute in the metadata doesn't make sense for the same reason that MethodImplAttribute/SerializerAttribute/IndexerNameAttribute wouldn't make sense in the metadata. They do nothing as custom attributes at runtime. ModuleInitializerAttribute should probably be added to the [C# reserved attributes page](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/general). (I can think of a few others, too.)

Checking for a ModuleInitializerAttribute custom attribute in metadata isn't even a canonical way to answer the question, "Is this method called by the module initializer?" That would depend on the compiler and version used to create the metadata. Therefore, adding it to the custom attributes table is only misleading.

@RikkiGibson

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Could you please send a PR to https://github.com/dotnet/csharplang/blob/master/proposals/csharp-9.0/module-initializers.md specifying this behavior and reference this PR from there?

**Comment by gafter** [comment]
This isn't the way to make the attribute not be emitted. The proper way to do it would be to make the attribute *conditional* in its source. No compiler change should be required to accomplish this.  See https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.conditionalattribute?view=net-5.0

**Comment by jnm2** [comment]
@RikkiGibson Sure.

@gafter `[Conditional("false")]`? Why would MethodInitializerAttribute be different from InitializerNameAttribute or MethodImplAttribute which do not use ConditionalAttribute?

**Comment by RikkiGibson** [comment]
Hi @jnm2, the LDM at this point has not decided to change this behavior and we no longer have the runway to get the change in for .NET 5. For this reason we will have to hold off on the change for now.

**Comment by jnm2** [comment]
@RikkiGibson What's the next step to take? There's a request to do this for ModuleInitializerAttribute and SkipLocalsInitAttribute: https://github.com/dotnet/csharplang/pull/3783

**Comment by jnm2** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
