### PR TITLE
Explicitly invoke diagnostic re-analysis whenever any bulk suppressio…

### LINKED ISSUE #6007: Syntax analysis is not re-executed in the IDE diagnostic service on adding global suppressions
1. Create a new C# class library with below code:
    ```C#
    class Class1
    {
        // Comment with trailing whitespaces     
    }
    ```

2. Install [codecracker](http://www.nuget.org/packages/codecracker/1.0.0-rc3) analyzer nuget package (check "Include prerelease" checkbox in Nuget package manager).

3. Change rule _"CC0065 (Remove trailing whitespace)"_ to be a warning from the ruleset editor.

4. Build project and see CC0065 diagnostic:
    ```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CC0065	Remove trailing whitespace	ClassLibrary14	c:\users\mavasani\documents\visual studio 2015\Projects\ClassLibrary14\ClassLibrary14\Class1.cs	3	

    ```

5. From the lightbulb menu select "Suppress CC0065" -> "In Suppression File" and hit enter

6. Verify suppression added to GlobalSuppressions.cs

  **Expected:** Diagnostic is suppressed in the error list + squiggle disappears.
  **Actual:** Diagnostic is retained in the error list and squiggle also doesn't go away. If you rebuild the project, the output window doesn't show the original diagnostic (though it shows 2 more instances of CC0065 in the newly added GlobalSuppressions file), but the error list still shows the origin CC0065 intellisense diagnostic.

7. Edit Class1.cs at an unrelated location - say hit enter at the end of the last line of the source file.
You will now see the expected behavior, and the diagnostic and squiggle disappear.

**Details:** The reason for this bug is that CC0065 is a syntax diagnostic (syntax tree analyzer action), and our IDE diagnostic service assumes that syntax diagnostics only depend on text version of the document. Adding a global suppression to other file invalidates this assumption. We cannot run all syntax analyzers on every single edit, that would cause perf problems - we need to figure out how to implement this reasonably.

### PR DESCRIPTION
**Pull request by mavasani**
…n fix is invoked from the error list or solution explorer.

**User Scenario:** User installs an analyzer with syntax diagnostics (e.g. CodeCracker), and bulk suppresses the syntax diagnostics from the error list or using the solution explorer "Suppress active issues" command. The code fix correctly adds suppressions to the global suppressions file, but the error list entries never get cleared. Even doing a rebuild doesn't clear the error list.

**Reason:** Our IDE diagnostic service assumes that syntax diagnostics only depend on text version of the document. Adding a global suppression to other file invalidates this assumption. We cannot run all syntax analyzers on every single edit, that would cause perf problems.

**Fix:** We explicitly invoke diagnostic re-analysis whenever any bulk suppression fix is invoked from the error list or solution explorer. This ensures that the error list gets refreshed.

**Testing:** Verified that syntax diagnostics are correctly removed from the error list for bulk suppression scenarios.

**Fixes #6007**

### CODE REVIEW

**Comment by mavasani** [comment]
@heejaechang @srivatsn kindly review.

**Comment by mavasani** [comment]
ping, can one of you take a look? This is a very small change.

**Comment by heejaechang** [comment]
:+1:

**Comment by srivatsn** [comment]
:+1:

**Comment by MattGertz** [comment]
Approved.

**Pull request merged**
