### PR TITLE
Set State.WaitingForInput in PrepareForInput [stabilization]

### PR DESCRIPTION
**Pull request by cston**
Port #6169 to stabilization

### CODE REVIEW

**Comment by cston** [comment]
@ManishJayaswal

**Comment by cston** [comment]
@dotnet-bot retest this please

**Comment by ManishJayaswal** [comment]
Approved for 1.1 pending test completion based on the approval for the PR on master.

**Comment by cston** [comment]
@dotnet-bot retest this please

**Comment by cston** [comment]
@dotnet-bot retest this please

**Pull request merged**
