### PR TITLE
Require MSBuild 16.3 in compiler NuGet packages

### LINKED ISSUE #38312: Compiler NuPkg MSBuild version check needs to be updated.
Example: 

https://github.com/dotnet/roslyn/blob/master/src/NuGet/Microsoft.Net.Compilers/build/Microsoft.Net.Compilers.props#L18

The props file here, and for related packages, need to be labeling everything before 16.0 as unsupported. That includes 15.0 - 15.3.

### PR DESCRIPTION
**Pull request by agocke**
Fixes #38312

### CODE REVIEW

**Comment by jaredpar** [comment]
Isn't there a bug we should link this to?

**Comment by agocke** [comment]
@jaredpar Add as a comment or a commit message?

**Comment by jasonmalinowski** [comment]
Should we remove https://github.com/agocke/roslyn/blob/189b230ef08a44d4a7f7caebea7e4360328203f6/src/Compilers/Core/MSBuildTask/Microsoft.Managed.Core.targets#L63 since we don't need the conditioning now?

**Comment by agocke** [comment]
@jasonmalinowski Yes, I'll inline now. I didn't realize we didn't remove this before shipping. The NuGet package is never supported on anything except the matching toolset in VS (aka MSBuild 16.3).

**Comment by agocke** [comment]
@dotnet/roslyn-compiler for one more review

**Pull request merged**
