### PR TITLE
upgrade runtests dependency on system.reflection.metadata

### PR DESCRIPTION
**Pull request by TyOverby**

### CODE REVIEW

**Comment by gafter** [comment]
@dotnet-bot test this please

**Comment by davkean** [comment]
Looks like you updated more than just runtests.exe, you should back out the project.lock.json changes - they shouldn't be part of this change.

**Comment by TyOverby** [comment]
@davkean I changed the runtests project.json file.  The rest of the project.lock.json changes happened when I did a restore.

@jaredpar Any idea why this is happening?

**Comment by tmat** [comment]
@TyOverby https://github.com/dotnet/roslyn/pull/9704

**Comment by TyOverby** [comment]
@tmat Interesting.  Do you know what caused it?

**Comment by jaredpar** [comment]
Closing as this was fixed in 7797003f46ec2b16ba2fd4b9fabc18ab726b66bd

**Pull request closed without merging**
