### PR TITLE
Handle out of range span in GetSemanticModelForSpanAsync

### PR DESCRIPTION
**Pull request by tmat**
**Customer scenario**

VS crashes while deleting text in interactive window when completion list is displayed.

Repro:

1) submit ```int a;```
2) type```a``` , wait for completion list to appear, hover over ```a``` in the list, type Backspace, crash.

**Bugs this fixes:**

VSO Bug [434828](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=434828)
VSO bug [395081](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=395081)

**Workarounds, if any**

Do not hover over completion list items while deleting text in submission.

**Risk**

Small.

**Performance impact**

None.

**Is this a regression from a previous update?**

**Root cause analysis:**

Edge case not handled.

**How was the bug found?**

Customer reported.

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet/roslyn-ide Please review.

**Comment by tmat** [comment]
@jinujoseph FYI

**Comment by tmat** [comment]
test https://github.com/dotnet/roslyn/issues/19512 please

**Comment by tmat** [comment]
@jasonmalinowski The completion items are created with current position and that position is passed to this function. If the buffer is shortened while the completion list is displayed then such position is no longer valid. It seems reasonable to me that this function should handle positions outside of the syntax tree span without crashing. It handles other cases as well (like a token not having a parent).

**Comment by tmat** [comment]
test windows_release_unit64_prtest please

**Comment by jasonmalinowski** [comment]
@tmat: this function is a very core function; it should be calling out callers doing bad things. @rchande is this a known completion bug we should be fixing instead?

**Comment by tmat** [comment]
@rchande This is the stack trace of the crash:

```
	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SyntaxNode.FindTokenCore(int position, bool findInsideTrivia) Line 1294	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetSemanticModelForSpanAsync(Microsoft.CodeAnalysis.Document document = {Microsoft.CodeAnalysis.Text.TextSpan}, Microsoft.CodeAnalysis.Text.TextSpan span = Submission#1, System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 56	C#
 	Microsoft.CodeAnalysis.CSharp.Features.dll!Microsoft.CodeAnalysis.CSharp.Completion.Providers.SymbolCompletionProvider.CreateContext(Microsoft.CodeAnalysis.Document document = Submission#1, int position = 1, System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 72	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetOrCreateContext.AnonymousMethod__0(Microsoft.CodeAnalysis.Document d) Line 316	C#
 	mscorlib.dll!System.Runtime.CompilerServices.ConditionalWeakTable<Microsoft.CodeAnalysis.Document, System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext>>.GetValue(Microsoft.CodeAnalysis.Document key = Submission#1, System.Runtime.CompilerServices.ConditionalWeakTable<Microsoft.CodeAnalysis.Document, System.Threading.Tasks.Task<Microsoft.CodeAnalysis.Shared.Extensions.ContextQuery.SyntaxContext>>.CreateValueCallback createValueCallback) Line 248	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetOrCreateContext(Microsoft.CodeAnalysis.Document document, int position, System.Threading.CancellationToken cancellationToken) Line 316	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.Providers.AbstractSymbolCompletionProvider.GetPerContextSymbols(Microsoft.CodeAnalysis.Document document = Length = 2, int position = Submission#1, Microsoft.CodeAnalysis.Options.OptionSet options = 1, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.DocumentId> relatedDocuments = IsCancellationRequested = false, bool preselect = false, System.Threading.CancellationToken cancellationToken = {Microsoft.CodeAnalysis.Options.WorkspaceOptionSet}) Line 282	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.Providers.AbstractRecommendationServiceBasedCompletionProvider.GetDescriptionWorkerAsync(Microsoft.CodeAnalysis.Document document = "System", Microsoft.CodeAnalysis.Completion.CompletionItem item = Submission#1, System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 116	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.CommonCompletionProvider.GetDescriptionAsync(Microsoft.CodeAnalysis.Document document = Submission#1, Microsoft.CodeAnalysis.Completion.CompletionItem item = "System", System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 41	C#
 	Microsoft.CodeAnalysis.Features.dll!Microsoft.CodeAnalysis.Completion.CompletionServiceWithProviders.GetDescriptionAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.Completion.CompletionItem item, System.Threading.CancellationToken cancellationToken) Line 462	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.CustomCommitCompletion.GetDescriptionAsync(System.Threading.CancellationToken cancellationToken = IsCancellationRequested = false) Line 59	C#
>	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.CancellableContentControl.CancellableContentControl(Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider toolTipProvider, Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.CustomCommitCompletion item) Line 69	C#
 	Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider.GetUIElement(Microsoft.VisualStudio.Language.Intellisense.Completion itemToRender, Microsoft.VisualStudio.Language.Intellisense.ICompletionSession context, Microsoft.VisualStudio.Language.Intellisense.UIElementType elementType) Line 49	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.Helpers.FindUIElement.AnonymousMethod__0(Microsoft.VisualStudio.Language.Intellisense.IUIElementProvider<Microsoft.VisualStudio.Language.Intellisense.Completion, Microsoft.VisualStudio.Language.Intellisense.ICompletionSession> provider) Line 314	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension<System.__Canon, System.__Canon, System.__Canon>(object errorSource = ThreadSafetyMode=ExecutionAndPublication, IsValueCreated=true, IsValueFaulted=false, Value={Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.ToolTipProvider}, System.Lazy<System.__Canon, System.__Canon> provider, System.Func<System.__Canon, System.__Canon> getter) Line 349	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.Helpers.FindUIElement<Microsoft.VisualStudio.Language.Intellisense.Completion, Microsoft.VisualStudio.Language.Intellisense.ICompletionSession>(Microsoft.VisualStudio.Language.Intellisense.IIntellisenseSession session = {Microsoft.CodeAnalysis.Editor.Implementation.IntelliSense.Completion.Presentation.CustomCommitCompletion}, Microsoft.VisualStudio.Language.Intellisense.Completion itemToRender = {Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession}, Microsoft.VisualStudio.Language.Intellisense.ICompletionSession context = Tooltip, Microsoft.VisualStudio.Language.Intellisense.UIElementType elementType, System.Collections.Generic.IList<System.Lazy<Microsoft.VisualStudio.Language.Intellisense.IUIElementProvider<Microsoft.VisualStudio.Language.Intellisense.Completion, Microsoft.VisualStudio.Language.Intellisense.ICompletionSession>, Microsoft.VisualStudio.Text.Utilities.IOrderableContentTypeMetadata>> orderedUIElementProviders, Microsoft.VisualStudio.Text.Utilities.GuardedOperations guardedOperations = {Microsoft.VisualStudio.Text.Utilities.GuardedOperations}) Line 316	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionView.CustomTooltipContent.get() Line 231	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultCompletionSetPresenter.ShowToolTip() Line 954	C#
 	Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultCompletionSetPresenter.OnShowTooltipTimer_Tick(object sender, System.EventArgs e) Line 569	C#
```

**Comment by rchande** [comment]
@tmat What position is completion passing in? I agree with @jasonmalinowski that we should just fix the completion bug.

**Comment by tmat** [comment]
The original position that the completion items were created with.

**Comment by tmat** [comment]
> The completion items are created with current position and that position is passed to this function. If the buffer is shortened while the completion list is displayed then such position is no longer valid.

**Comment by rchande** [comment]
Also @tmat can you repro the same crash by typing at the end of a normal cs file?

**Comment by tmat** [comment]
@rchande No, presumably because member completion is not applicable at the end of .cs file.

**Comment by tmat** [comment]
@rchande Actually it does, like so (notice I'm typing at the end of the file without braces closed):

image

**Comment by rchande** [comment]
@tmat Yes, I suspect that might be the case. Feel free to move it to IDE and assign me (cc @Pilchie )

**Comment by tmat** [comment]
OK

**Pull request closed without merging**
