### PR TITLE
Do not run Add-Using on syntax errors.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by heejaechang** [comment]
retest prtest/lin/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1709/
// Retest reason: known mono crash

**Comment by DustinCampbell** [comment]
:+1:

**Comment by jmarolf** [comment]
:+1: What is the rationale for moving the tests around?

**Comment by CyrusNajmabadi** [comment]
@jmarolf They're moved into the tests that use your special analyzer.  These tests work with the "unbound identifier" diagnostic, and no longer the "syntax error" diagnostic.

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
