### PR TITLE
Merge stabilization into future-stabilization

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from stabilization into future-stabilization.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-stabilization-into-future-stabilization20160311-015018
git reset --hard upstream/future-stabilization
git merge upstream/stabilization
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-stabilization-into-future-stabilization20160311-015018 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by heejaechang** [comment]
@davkean so we are not adding vsi for these?

**Comment by davkean** [comment]
@heejaechang I will, I'm waiting on the queue

**Comment by davkean** [comment]
Yes I will add vsi.

**Comment by davkean** [comment]
test vsi please
test eta please

**Pull request merged**
