### PR TITLE
Expanding out character range.

### PR DESCRIPTION
**Pull request by AdamSpeight2008**
So the compilation results in a IL Switch rather than an IF

### CODE REVIEW

**Comment by pharring** [comment]
LGTM

**Comment by pdelvo** [comment]
Wouldnt it be great if the compiler would do such a transformation if the number of elements in the range are below some threshold?

**Comment by AdamSpeight2008** [comment]
@pdelvo Someone also noticed that but I can't remember where it was mentioned.

**Comment by gafter** [comment]
Does this actually makes any difference in the IL generated?

**Comment by AdamSpeight2008** [comment]
I didn't check the IL but the following example should suffice as evidence
```
Imports System
Public Module M
    Public Sub Main()
        Dim c = "A"c
        Select Case c
        Case "A"c To "Z"c
            Console.WriteLine("A-Z")
        End Select
    End Sub
End Module
```
**Debug**
With `To`
```
.class private auto ansi '<Module>'
{
} // end of class <Module>

.class public auto ansi sealed M
    extends [mscorlib]System.Object
{
    .custom instance void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute::.ctor() = (
        01 00 00 00
    )
    // Methods
    .method public static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 37 (0x25)
        .maxstack 2
        .locals init (
            [0] char,
            [1] char,
            [2] bool
        )

        IL_0000: nop
        IL_0001: ldc.i4.s 65
        IL_0003: stloc.0
        IL_0004: nop
        IL_0005: ldloc.0
        IL_0006: stloc.1
        IL_0007: ldloc.1
        IL_0008: ldc.i4.s 65
        IL_000a: blt.s IL_0013
        IL_000c: ldloc.1
        IL_000d: ldc.i4.s 90
        IL_000f: cgt
        IL_0011: br.s IL_0014
        IL_0013: ldc.i4.1
        IL_0014: stloc.2
        IL_0015: ldloc.2
        IL_0016: brtrue.s IL_0023
        IL_0018: ldstr "A-Z"
        IL_001d: call void [mscorlib]System.Console::WriteLine(string)
        IL_0022: nop
        IL_0023: nop
        IL_0024: ret
    } // end of method M::Main

} // end of class M
```
Without `To`
```
.class private auto ansi '<Module>'
{
} // end of class <Module>

.class public auto ansi sealed M
    extends [mscorlib]System.Object
{
    .custom instance void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute::.ctor() = (
        01 00 00 00
    )
    // Methods
    .method public static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 136 (0x88)
        .maxstack 2
        .locals init (
            [0] char
        )

        IL_0000: nop
        IL_0001: ldc.i4.s 65
        IL_0003: stloc.0
        IL_0004: nop
        IL_0005: ldloc.0
        IL_0006: ldc.i4.s 65
        IL_0008: sub
        IL_0009: switch (IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078, IL_0078)
        IL_0076: br.s IL_0086
        IL_0078: nop
        IL_0079: ldstr "A-Z"
        IL_007e: call void [mscorlib]System.Console::WriteLine(string)
        IL_0083: nop
        IL_0084: br.s IL_0086
        IL_0086: nop
        IL_0087: ret
    } // end of method M::Main

} // end of class M
```
**Release**
With `To`
```
.class private auto ansi '<Module>'
{
} // end of class <Module>

.class public auto ansi sealed M
    extends [mscorlib]System.Object
{
    .custom instance void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute::.ctor() = (
        01 00 00 00
    )
    // Methods
    .method public static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 24 (0x18)
        .maxstack 2
        .locals init (
            [0] char
        )

        IL_0000: ldc.i4.s 65
        IL_0002: stloc.0
        IL_0003: ldloc.0
        IL_0004: ldc.i4.s 65
        IL_0006: blt.s IL_0017
        IL_0008: ldloc.0
        IL_0009: ldc.i4.s 90
        IL_000b: bgt.s IL_0017
        IL_000d: ldstr "A-Z"
        IL_0012: call void [mscorlib]System.Console::WriteLine(string)
        IL_0017: ret
    } // end of method M::Main

} // end of class M

```
without
```
{
} // end of class <Module>

.class public auto ansi sealed M
    extends [mscorlib]System.Object
{
    .custom instance void [Microsoft.VisualBasic]Microsoft.VisualBasic.CompilerServices.StandardModuleAttribute::.ctor() = (
        01 00 00 00
    )
    // Methods
    .method public static 
        void Main () cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 128 (0x80)
        .maxstack 2
        .locals init (
            [0] char
        )

        IL_0000: ldc.i4.s 65
        IL_0002: stloc.0
        IL_0003: ldloc.0
        IL_0004: ldc.i4.s 65
        IL_0006: sub
        IL_0007: switch (IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075, IL_0075)
        IL_0074: ret
        IL_0075: ldstr "A-Z"
        IL_007a: call void [mscorlib]System.Console::WriteLine(string)
        IL_007f: ret
    } // end of method M::Main

} // end of class M
```

**Comment by AdamSpeight2008** [comment]
Sorry pressed wrong button. doh.

**Comment by gijswassink** [comment]
I tested both cases with stopwatch and found no differents by doing 999 999 999 iterations on my machine just 1.8 seconds.

**Comment by AdamSpeight2008** [comment]
@gijswassink The example I posted may not be the greatest but more about the larger `Case Select` that the `Case "A"z To "Z"c` is contained in. The compiler can now has the option of making it a O(1) lookup.

**Comment by AdamSpeight2008** [comment]
Another benefit *(for me)* is that I now know that I have a stable building and tested branch.
So I know that any subsequent issue is something I've introduced.

**Comment by AdamSpeight2008** [comment]
@gijswassink  IL for TryScanToken
[Before](https://gist.github.com/AdamSpeight2008/0a577f9ca6ab2b06defe)
[After](https://gist.github.com/AdamSpeight2008/2f48a330b32c77fc45e9)

**Comment by gafter** [comment]
@AdamSpeight2008 I suspect you have the before and after mixed up.

**Comment by VladimirReshetnikov** [comment]
@AdamSpeight2008 67% - is it a reduction in number of lines in disassembled IL, or in number of bytes?

**Comment by AdamSpeight2008** [comment]
:@VladimirReshetnikov  Number of lines, still smaller in bytes though :smirk: 

Don't focus just on the `Case "a"c To "z"c` but the whole `Select Case` block it is in.
As was prior to this PR the compiler was emitting the `Select Case` block as a  series of `If Then Else`, Which is O(ln) in best case and O(n) in the worst (in terms of the number of `Case`s.
Eg
```vb
If "A"c Then
  ' ...
Else
  If "E"c Then
    ' ...
  Else 
    If c = "I"c Then
      ' ...
    Else
      If c < "a"c Then
        GoTo _ElseCase_
      Else
        If c > "z"c Then
          GoTo _ElseCase_
        Else
          ' ...
        End If
      End If
    End If
  End If
End If
```
As as a series of `If Then Else`, Which is O(ln) in best case and O(n) in the worst. 
With the expansion it affect an array index lookup then a jump.

**Comment by AdamSpeight2008** [comment]
@gafter Nope I was very careful to make sure.

**Pull request merged**
