### PR TITLE
Extract out a 'relational' section for parenthese preferences

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
@sharwell Implements the design we discussed in https://github.com/dotnet/roslyn/pull/26013#issuecomment-387274353

There are now three general groups.   Parenthese only affect expressions entirely of that type of group type.

### CODE REVIEW

**Comment by sharwell** [comment]
This is currently undergoing a design review, but I do not see any objections coming.

* The design needs to be approved before merge
* Two tests are currently broken, so that will need to be fixed
* I left two additional notes related to the (internal) API change in `SyntaxEditorBasedCodeFixProvider`

**Comment by CyrusNajmabadi** [comment]
> Two tests are currently broken, so that will need to be fixed

Have fixed the tests.  The tests were actually broken and were only working because of the previously broken way that 'fix all tests' worked (i.e. where the test supplied the equivalence key instead of actually figuring that out from the real action invokved).  Fixing that test harness bug revealed that my code was buggy.  I've now fixed it.

**Comment by sharwell** [comment]
@CyrusNajmabadi The design for this change was approved today. We may decide to review the names of the .editorconfig keys and values after this change is merged but before it ships.

**Comment by CyrusNajmabadi** [comment]
@sharwell Merge conflicts addressed.

**Comment by CyrusNajmabadi** [comment]
test windows_debug_spanish_unit32_prtest

**Comment by CyrusNajmabadi** [comment]
test windows_release_vs-integration_prtest

**Comment by Neme12** [comment]
Why do relational operators only have "Ignore" and not "Always for clarity" like arithmetic and other operators do?
image

**Comment by Neme12** [comment]
If this setting only affects expressions where all operators are from the relational group, it seems desirable to be able to mandate parentheses in those cases: `a < b == c < d`.

From my understanding, this setting would not require parentheses in cases like `a < b && c < d`. Would it?

**Comment by sharwell** [comment]
@jinujoseph for approval to merge

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview3

**Comment by CyrusNajmabadi** [comment]
Thanks guys!

**Pull request merged**
