### PR TITLE
Expose IsGeneratedCode boolean property on diagnostic analyzer contexts

### LINKED ISSUE #7578: Expose "IsGeneratedCode" on analysis contexts
PR https://github.com/dotnet/roslyn/pull/7526 adds support for analyzers to configure generated code analysis: analyzers can turn off reporting of diagnostics on generated code and/or turn off analyzer callbacks on generated code. Analyzer driver uses a heuristic to determine what code is generated code for analysis for this filtering.

We have received public requests (see https://github.com/dotnet/roslyn/issues/6998#issuecomment-165297425 and https://github.com/dotnet/roslyn/issues/6998#issuecomment-165451569) to expose this boolean flag on the relevant analysis contexts so that analyzers can do customized generated code analysis relying on driver's heuristic.

### PR DESCRIPTION
**Pull request by mavasani**
Closes #7578

Based on the recent feature requests in allowing more fine grained generated code analysis, we have decided to initially expose a boolean IsGeneratedCode property on each of the analysis contexts. Note that this flag indicates if the callback symbol/node/operation/tree is considered generated code or not based on compiler's internal heuristics for analyzer execution. This flag helps the analyzers that only want to analyze certain kinds of generated code to narrow down their custom fine grained generated code analysis to only those callbacks that have this flag set to true.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
In the Razor scenario, you might have "generated platform code" and "generated code from user code" in the same method, right? Something like:

```razor
<h1>@MyMethod()</h1>
```

might turn into (*extreme* pseudocode, sorry if I've totally botched what Razor actually does)

```cs
void RenderTemplate()
{
    #line hidden
    Render("<h1>");

    #line 1,5 Index.cshtml
    Model.MyMethod();

    #line hidden
    Render("</h1>");
}
```

This kind of thing is not handled in this PR, right? Is there any expectation to handle it eventually?

**Review by RikkiGibson — APPROVED** [review]

**Comment by mavasani** [comment]
> In the Razor scenario, you might have "generated platform code" and "generated code from user code" in the same method, right?
> 
> This kind of thing is not handled in this PR, right? Is there any expectation to handle it eventually?

Yes, that is correct. This PR is not changing semantics, just exposing a public API for an existing `isGeneratedCode` flag tracked within analyzer driver.

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for another review

**Comment by mavasani** [comment]
@dotnet/roslyn-compiler for second review

**Comment by mavasani** [comment]
https://github.com/orgs/dotnet/teams/roslyn-compiler for second review

**Comment by mavasani** [comment]
Merging this PR as the underlying public API has been approved by the compiler team in https://github.com/dotnet/roslyn/issues/7578#issuecomment-1234766960. I'll address any further feedback with a follow-up PR.

**Pull request merged**
