### PR TITLE
Properly handle __arglist argument in OverloadResolution.BetterFunctionMember.

### LINKED ISSUE #8152: Visual Studio crashes when multiple methods with __arglist is added to a class
If you add the following (invalid) code to a file in Visual Studio, then the IDE crashes:
```
public class SpecialCases
{
	public void ArgListMethod(__arglist)
	{
		ArgListMethod(__arglist(""));
	}
	public void ArgListMethod(__arglist)
	{
		ArgListMethod(__arglist(""));
	}
}
```
I'm using VS 2015 Update 1.

I reproduced the issue while trying to compile this code with Roslyn. I tried to get all diagnostics from a `Compilation` that only contains this code, and I got the following exception. It seems that the method overload resolution throws.
```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
...
  InnerException: 
       HResult=-2146233080
       Message=Index was outside the bounds of the array.
       Source=Microsoft.CodeAnalysis.CSharp
       StackTrace:
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.GetParameterType(Int32 argIndex, MemberAnalysisResult result, ImmutableArray`1 parameters, RefKind& refKind)
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.GetParameterType(Int32 argIndex, MemberAnalysisResult result, ImmutableArray`1 parameters)
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.BetterFunctionMember[TMember](MemberResolutionResult`1 m1, MemberResolutionResult`1 m2, ArrayBuilder`1 arguments, Boolean considerRefKinds, HashSet`1& useSiteDiagnostics)
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.BetterFunctionMember[TMember](MemberResolutionResult`1 m1, MemberResolutionResult`1 m2, ArrayBuilder`1 arguments, HashSet`1& useSiteDiagnostics)
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.RemoveWorseMembers[TMember](ArrayBuilder`1 results, AnalyzedArguments arguments, HashSet`1& useSiteDiagnostics)
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.PerformMemberOverloadResolution[TMember](ArrayBuilder`1 results, ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, Boolean completeResults, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.OverloadResolution.MethodOrPropertyOverloadResolution[TMember](ArrayBuilder`1 members, ArrayBuilder`1 typeArguments, AnalyzedArguments arguments, OverloadResolutionResult`1 result, Boolean isMethodGroupConversion, Boolean allowRefOmittedArguments, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.Binder.ResolveDefaultMethodGroup(BoundMethodGroup node, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroupInternal(BoundMethodGroup methodGroup, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.Binder.ResolveMethodGroup(BoundMethodGroup node, CSharpSyntaxNode expression, String methodName, AnalyzedArguments analyzedArguments, Boolean isMethodGroupConversion, HashSet`1& useSiteDiagnostics, Boolean inferWithDynamic, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindMethodGroupInvocation(CSharpSyntaxNode syntax, CSharpSyntaxNode expression, String methodName, BoundMethodGroup methodGroup, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(CSharpSyntaxNode node, CSharpSyntaxNode expression, String methodName, BoundExpression boundExpression, AnalyzedArguments analyzedArguments, DiagnosticBag diagnostics, CSharpSyntaxNode queryClause, Boolean allowUnexpandedForm)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindInvocationExpression(InvocationExpressionSyntax node, DiagnosticBag diagnostics)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionInternal(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindExpression(ExpressionSyntax node, DiagnosticBag diagnostics, Boolean invoked, Boolean indexed)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(CSharpSyntaxNode node, ExpressionSyntax syntax, Boolean allowsAnyExpression, DiagnosticBag diagnostics)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindExpressionStatement(ExpressionStatementSyntax node, DiagnosticBag diagnostics)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindStatement(StatementSyntax node, DiagnosticBag diagnostics)
            at Microsoft.CodeAnalysis.CSharp.Binder.BindBlock(BlockSyntax node, DiagnosticBag diagnostics, Binder blockBinder)
            at Microsoft.CodeAnalysis.CSharp.MethodCompiler.BindMethodBody(MethodSymbol method, TypeCompilationState compilationState, DiagnosticBag diagnostics, ImportChain& importChain)
            at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethod(MethodSymbol methodSymbol, Int32 methodOrdinal, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissionFields previousSubmissionFields, TypeCompilationState compilationState)
            at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileNamedType(NamedTypeSymbol symbol)
            at Microsoft.CodeAnalysis.CSharp.MethodCompiler.<>c__DisplayClass21_0.<CompileNamedTypeAsTask>b__0()
            at Roslyn.Utilities.UICultureUtilities.<>c__DisplayClass5_0.<WithCurrentUICulture>b__0()
            at System.Threading.Tasks.Task.InnerInvoke()
            at System.Threading.Tasks.Task.Execute()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at Microsoft.CodeAnalysis.CSharp.MethodCompiler.WaitForWorkers()
            at Microsoft.CodeAnalysis.CSharp.MethodCompiler.CompileMethodBodies(CSharpCompilation compilation, PEModuleBuilder moduleBeingBuiltOpt, Boolean generateDebugInfo, Boolean hasDeclarationErrors, DiagnosticBag diagnostics, Predicate`1 filterOpt, CancellationToken cancellationToken)
            at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnosticsForAllMethodBodies(DiagnosticBag diagnostics, CancellationToken cancellationToken)
            at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CompilationStage stage, Boolean includeEarlierStages, CancellationToken cancellationToken)
            at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetDiagnostics(CancellationToken cancellationToken)
            at Microsoft.CodeAnalysis.Diagnostics.CompilationWithAnalyzers.<GetAllDiagnosticsAsync>d__10.MoveNext()
       InnerException: 
```

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #8152.

@dotnet/roslyn-compiler Please review.

### CODE REVIEW

**Comment by agocke** [comment]
:+1:

Not sure how many users it will affect though ;)

**Comment by davkean** [comment]
@tannergooding Notice that prtest/win/tst/unit64 failed again: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_tst_unit64/132/

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review, need a second sign-off.

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
