### PR TITLE
Fix Class View/Object Browser search for Web Site projects

### PR DESCRIPTION
**Pull request by DustinCampbell**
Fixes TFS 1033946

**Customer scenario**: Create a Web Site project and add a class to the App_Code folder. Bring up either the Class View or Object Browser and search for the class name. It should be found, but it isn't.

**Description of fix:**: Really, search in Web Site projects was working fine. The problem was that the default class template, when added to an App_Code folder does not contain a namespace declaration. So, the class ends up in the global namespace, which the search skipped.

**Testing done**: Manual verification

Suitable reviewers: @dpoeschl, @rchande, @jasonmalinowski, @Pilchie.

*Can anyone do some buddy testing for me?*

### CODE REVIEW

**Comment by DustinCampbell** [comment]
Also, @brettfo and @balajikris

**Comment by Pilchie** [comment]
Is it possible to add a test to verify that we find global namespace types?

**Comment by Pilchie** [comment]
Also, any historical clues as to why the code used to explicitly skip the global namespace?

**Comment by DustinCampbell** [comment]
@Pilchie - there isn't a great way to add a test for this case. It would mean building out test infrastructure.

Historically, the reason is that I goofed up when I originally wrote it. I did not really use the old C#/VB language services as a guide for much of the Object Browser/Class View support in Roslyn. So, there's not much historical reasoning other than "Dustin wasn't thinking clearly." :smile:

**Comment by DustinCampbell** [comment]
jenkins, please retest this

**Comment by DustinCampbell** [comment]
Jenkins, retest this please.

**Comment by Pilchie** [comment]
Okay, LGTM.

**Comment by MattGertz** [comment]
@DustinCampbell Per our conversation.

**Comment by DustinCampbell** [comment]
Creating new pull request on master.

**Pull request closed without merging**
