### PR TITLE
Report semantic errors in lambdas

### LINKED ISSUE #1239: Add using quick fix doesn't show in incomplete lamba
Source (entire file):

```C#
using System.Linq;

class C {
    C() {
        "".Select(() => {
            new Byte
```

No quick fix appears in `Exception`.

----

Alternate source with same issue:
```C#
using System.Linq;

class C {
    C() {
        "".Select(() => {
            new Byte()
            }
```
Here, removing the `()` makes the quick fix appear.

### LINKED ISSUE #1241: Generate Constructor doesn't appear in statement lambda with missing semicolon
```
using System.Threading.Tasks;

class C {
	C() {
		Task.Run(() => {
			new C(0)
		});
	}
}
```
No quick fix will appear until a semicolon is added.

This may be a dup of #1239; I'm not sure.

### LINKED ISSUE #1744: Incomplete catch block in lambda doesn't show Add Using quick fix
Source:

```C#
class A {
	System.Action a = () => {
		try {
		}
		catch (Exception
	};
}
```

The Add Using/Qualify Name quick fix will not appear until after adding `) {`.

### PR DESCRIPTION
**Pull request by jmarolf**
The compiler does not generate semantic errors inside lambdas in the
presence of syntactic errors causing several features to not work in
lambdas with syntax errors.  The bug for this
([1867](https://github.com/dotnet/roslyn/issues/1867)) was moved to
milestone 1.1 so we are going to use an analyzer in the interim for 1.0.

1. We now check for IncompleteMemberSyntax nodes and
LambdaExpressionSyntax nodes which contain syntax diagnostics on any of
their descendant nodes.
2. We report both unbound identifier names and constructors that the
compiler reports as binding, but which fail overload resolution
(actually don't exist).

Performance considerations should be mitigated by only doing these
checks only lambdas with syntax errors.

Other notes:

- Renamed analyzer to UnboundIdentifier instead of AddImport since it is
being used in more places than just the AddImport fixer
- Updated the DiagnosticDescriptor for this analyzer to take
localizeable strings.

Fixes #1744
Fixes #1241
Fixes #1239

### CODE REVIEW

**Comment by jmarolf** [comment]
@srivatsn @heejaechang @shyamnamboodiripad @tmeschter @mavasani Could you please take a look?

**Comment by jmarolf** [comment]
ping @srivatsn @heejaechang @shyamnamboodiripad @tmeschter @mavasani

**Comment by tmeschter** [comment]
:+1:

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
