### PR TITLE
Feature: Add wrap all elements for initializer expressions

### PR DESCRIPTION
**Pull request by tokarzkj**
Users will now be offered wrapping refactor options similar to functions with multiple arguments and parameters. The following refactor options are available for initializer expressions:

- Wrap every
- Unwrap and indent
- Wrap long list

I added 3 unit tests to test:

- Initializer that should offer no suggestion
- Small initializer with a few values
- Long initializer with 9 values

This implements the request from issue #37428

### CODE REVIEW

**Comment by tokarzkj** [comment]
**TODO**
- I still need to look at naming the refactor options appropriately. They currently use the argument Feature Resources. I considered making wrap_every_expression, but I wanted a second opinion.

- I need to look at the code refactor provider here because it has a few small issues. We are always offering the wrap long refactor. The other issue is the refactor removes the white space between values in the expression.

**Comment by CyrusNajmabadi** [comment]
Let me know when you'd like a review.  Thanks! :)

**Comment by tokarzkj** [comment]
> 
> 
> Let me know when you'd like a review. Thanks! :)

@CyrusNajmabadi Thanks! I did have a couple of questions regarding a few things I am unsure about.

When I was looking at it I was thinking it might make more sense to be wrap_every_expression_element? The original comment in the issue suggested wrap_every_expression. I wanted a second opinion before going ahead with that.

The other question I have is about the actual code fixes being done. Should the styles stay consistent with the code fixes for wrap_every_argument? 

For example, currently, indent all doesn't move the curly braces to the next line. However, I believe it is more common to put the braces on a line by themselves.

Here is an example of the current code fix works.
image

**Comment by CyrusNajmabadi** [comment]
> When I was looking at it I was thinking it might make more sense to be wrap_every_expression_element? The original comment in the issue suggested wrap_every_expression. I wanted a second opinion before going ahead with that.

I'd go with `wrap_every_element`.

>For example, currently, indent all doesn't move the curly braces to the next line. However, I believe it is more common to put the braces on a line by themselves.

The curly brace should be moved to wherever the formatter would put it if this is a multiline construct.  You might be able to fix this by adding elastic trivia to the open-curly so that the formatter will try to fix things up for it.  I can help with this later if you have trouble here :)

**Comment by jinujoseph** [comment]
cc @CyrusNajmabadi

**Comment by tokarzkj** [comment]
@CyrusNajmabadi - I may need help tackling how to get the opening brace on a line of its own. I have accomplished getting the elements and closing brace formatted appropriately. My main approach has been trying to add elastic trivia in front of the opening brace with the following code:

```c#
result.Add(Edit.UpdateBetween(_listSyntax.GetFirstToken().WithPrependedLeadingTrivia(NewLineTrivia), NewLineTrivia, SingleWhitespaceTrivia, _listItems[0]));
```

That just causes an issue when trying to compute the code fix.

**Comment by CyrusNajmabadi** [comment]
> That just causes an issue when trying to compute the code fix.

1. what issue does this cause?
2. it may be more conducive to take the discussion to gitter.im/dotnet/roslyn or aka.ms/sharp-discord

Note: i may not be on until tomorrow due to all hallows eve.

**Pull request closed without merging**
