### PR TITLE
Consume construction with nullable in type inferrer

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This consists of two parts:

1. Fixing a compiler bug in NormalizeWhitespace that I hit while trying to test the second part and
2. Updating the type inferrer and the appropriate tests.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@jcouv @agocke While fixing the IDE stuff I hit a compiler bug in NormalizeWhitespace. The IDE fixes have to go into master; if the compiler fix can't also go into master then we'll have to break this apart.

**Comment by agocke** [comment]
@jasonmalinowski SyntaxNormalizer isn't used in batch compilation, so this seems fine

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-compiler some reviews then would be appreciated if this is good for master.

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-compiler can I get a second compiler review? Change is very tiny.

**Comment by agocke** [comment]
This is good to go.

**Pull request merged**
