### PR TITLE
Merge remote-tracking branch 'dotnet/future' into features/test-impact

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @dotnet/testimpact

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @JohnHamby and @TyOverby, there were conflicting changes in `src/Test/Utilities/Desktop/CommonTestBase.CompilationVerifier.cs` and `src/Test/Utilities/Desktop/HostedRuntimeEnvironment.cs`, which I resolved, but should be verified.

FYI. @drognanar, there were some conflicting changes in ` src/Compilers/Core/Portable/PublicAPI.Unshipped.txt` which I resolved, but should be verified.

**Comment by TyOverby** [comment]
@tannergooding just came into my office to talk about merge conflicts.  He fixed everything up correctly, but hasn't pushed yet.  :+1: for when he pushes what we worked on.

**Comment by tannergooding** [comment]
I've pushed the updated bits after going over them with @TyOverby

**Comment by tannergooding** [comment]
I've pushed updated bits again after going over them with @drognanar

**Comment by tannergooding** [comment]
Merging. Eta is unsupported as this is a feature branch. Linux is a known flaky issue.

**Pull request merged**
