### PR TITLE
Report level 7 name warning for `record` when langversion is below 9

### PR DESCRIPTION
**Pull request by 333fred**
Another small bug I noticed when working on required members and touching this function. We currently do not report a level 7 warning for 'record' when the langversion is below the minimum for records.

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a small review.

**Comment by 333fred** [comment]
@dotnet/roslyn-compiler for a small review.

**Review by jcouv — APPROVED** [review]
I'd left the record case intentionally alone but that doesn't make much sense. I agree the warning should apply too.  LGTM Thanks (iteration 2)

**Comment by 333fred** [comment]
Yeah, my reasoning is that, since the warning is only possibly true for most identifiers, but is _definitely_ true for `record`, we should warn there.

@dotnet/roslyn-compiler for a second small review.

**Review by AlekseyTs — APPROVED** [review]
LGTM (commit 2)

**Pull request merged**
