### PR TITLE
Fix null reference exception.

### PR DESCRIPTION
**Pull request by heejaechang**
this just change crash to NFW. this doesn't actually fix the root cause.

### Customer scenario

What does the customer do to get into this situation, and why do we think this
is common enough to address for this release.  (Granted, sometimes this will be
obvious "Open project, VS crashes" but in general, I need to understand how
common a scenario is)

### Bugs this fixes

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/551174?src=alerts&src-action=cta

### Workarounds, if any

Also, why we think they are insufficient for RC vs. RC2, RC3, or RTW

### Risk

This is generally a measure our how central the affected code is to adjacent
scenarios and thus how likely your fix is to destabilize a broader area of code

### Performance impact

(with a brief justification for that assessment (e.g. "Low perf impact because no extra allocations/no complexity changes" vs. "Low")

### Root cause analysis

How did we miss it?  What tests are we adding to guard against it in the future?

### How was the bug found?

(E.g. customer reported it vs. ad hoc testing)

### CODE REVIEW

**Comment by heejaechang** [comment]
retest windows_debug_unit32_prtest  please

**Comment by jinujoseph** [comment]
@jasonmalinowski  for review and info

**Comment by jasonmalinowski** [comment]
And the problem with masking this: if this is corrupted, other things are probably going to fail downstream. Pushing for root causes here is key.

**Comment by heejaechang** [comment]
@jasonmalinowski sure if you are tracking down root cause. I was thinking doing InfoBar and NFW instead of hard crash.

**Comment by jasonmalinowski** [comment]
@heejaechang We've identified at least one root cause that means the IDE is pretty much busted as a whole. I don't think it's safe to continue; there's a good chance we crash even farther away from the failure.

**Pull request closed without merging**
