### PR TITLE
Add a pinned pkcs entry

### PR DESCRIPTION
**Pull request by marcpopMSFT**

### CODE REVIEW

**Comment by ericstj** [comment]
CC @jjonescz and @sharwell since this was added in https://github.com/dotnet/roslyn/pull/72242.  I think this is correct regardless.  Since that reference of XML will bring in the out-of-date Pkcs, they both should be updated.

Please double check that the branch is open for these types of check-ins before merging.

**Comment by marcpopMSFT** [comment]
@MichaelSimons @mthalman do I need to go update SBRP for this package now?

**Comment by mthalman** [comment]
> @MichaelSimons @mthalman do I need to go update SBRP for this package now?

Yes. Does it need to be 7.0.3? We already have 7.0.2 in SBRP.

**Comment by marcpopMSFT** [comment]
Good suggestion. 7.0.2 appears to be new enough to not have known issues so let me try that one. I went to 7.0.3 simply because that was the latest one.

**Pull request merged**
