### PR TITLE
Ensure related docs in the preview workspace link to same sourcetext

### PR DESCRIPTION
**Pull request by ToddGrun**
Without this change, I'm seeing a massive number of solution forks occurring.

For lightbulb preview in CommonSyntaxTest.cs, I see ForceForkProject calls go from ~250 to ~60.

For lightbulb preview in SegmentedArray.cs, I see ForceForkProject calls go from ~1370 to ~310.

Will actually take perfview measurements once I get some validation of the approach.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Fascinating

**Comment by CyrusNajmabadi** [comment]
so, for the purposes of preview, i actually have no idea why the solution we're making has anything more than the project in question (and any projects it depends on).  having all the sibling targets (as well as unrelated projects) is just pointless.  

we might want to go more extreme and strip teh final solution down to practically nothing.

**Comment by ToddGrun** [comment]
Perfview is showing a pretty big effect for my test case:

```
    Name												Inc %	Inc

OLD
  VS Process:
    Microsoft.CodeAnalysis.Workspaces!SolutionCompilationState.UpdateDocumentState			29.3	2,208
  CodeAnalysis Process: 
    Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.DriverStateTable+Builder.GetLatestStateTableForNode	37.9	10,488

NEW:
  VS Process:
    Microsoft.CodeAnalysis.Workspaces!SolutionCompilationState.UpdateDocumentState			6.2	296
  CodeAnalysis Process: 
    Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.DriverStateTable+Builder.GetLatestStateTableForNode	1.6	230
```

**Comment by CyrusNajmabadi** [comment]
a question i have is: what is pulling on all the linked files in the preview workspace, causing all those SG runs to happen?

**Comment by ToddGrun** [comment]
> a question i have is: what is pulling on all the linked files in the preview workspace, causing all those SG runs to happen?

I just added a comment that mentioned why these modifications are done. Does that clarify it enough, or do you think more details would be helpful?

**Comment by CyrusNajmabadi** [comment]
@ToddGrun not really.  I'm trying ot figure out this bit: 

Microsoft.CodeAnalysis!Microsoft.CodeAnalysis.DriverStateTable+Builder.GetLatestStateTableForNode

THis indicates high cost in SG computation.  Which goes away once the text is shared.  First, as the driver tables are not shared across TFM targets, i don't really see how this helps.   Second, if this does help, i want to understand why :)

3rd, if there is something here that is running taggers in the preview workspace across multiple versions of a linked file, i also want to understand that :)

**Comment by ToddGrun** [comment]
On the VS side, when the tagger is called, it would call GetOpenTextDocumentInCurrentContextWithChanges. The related sourcetext value would not match in the preview workspace, so it would Fork the solution with that changed. Nothing would update the preview workspace. Somehow, this would kick off a new compilation. Upon completion, the tagger would again operate, and again use a workspace that didn't have the related document changed.

**Comment by CyrusNajmabadi** [comment]
> On the VS side, when the tagger is called, it would call GetOpenTextDocumentInCurrentContextWithChanges. The related sourcetext value would not match in the preview workspace,

this part is weird to me.  isn't the point of hte preview workspace that that specific document is 'correct' because it's the one that the original workspace forked?  having it not match right when tagged is... odd.  

I'm coming into the office now.  can chat there :)

**Comment by ToddGrun** [comment]
I took a couple more profiles, this time not only waiting for the solution load and background tasks to complete before starting collecting profiles, but also waiting for codelens references to fully display, and I no longer see GetLatestStateTableForNode showing up in the CodeAnalysis process as a difference between the two. I still see the UpdateDocumentState difference in the VS process. I'll dig into the profiles a bit more to see if I notice any other differences.

**Comment by ToddGrun** [comment]
OK, with the updated profiles, the CodeAnalysis improvement appears to be a bit more related and is:

```
Name                                                                                                                                        	Inc %	   Inc

OLD CPU:
 Microsoft.CodeAnalysis.Remote.ServiceHub!Microsoft.CodeAnalysis.Remote.RemoteWorkspace+SolutionCreator+<UpdateProjectsAsync>d__6.MoveNext()	 46.0	   2,009

NEW CPU:
 Microsoft.CodeAnalysis.Remote.ServiceHub!Microsoft.CodeAnalysis.Remote.RemoteWorkspace+SolutionCreator+<UpdateProjectsAsync>d__6.MoveNext()	 32.6	   795

**Comment by ToddGrun** [comment]
Profiles are at \\vwdbuild01\dev\toddgrun\1-29-main-3.etl.zip and  \\vwdbuild01\dev\toddgrun\1-29-previewWorkspace_RelatedDocs2-2.etl.zip

**Review by CyrusNajmabadi — APPROVED** [review]

**Pull request merged**
