### PR TITLE
Subclass the editor's BlockTag so we can pick up some heuristic changes they're making on their end.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
There are currently a few code cases where the editor ends up drawing a structure-guide in a poor location.  For example:

image

They're tweaking some of these heuristics while they change their API to make this more controllable by the end language.  However, to pick up the heuristic we need to subclass from their BlockTag base class.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz  This is a minor refactoring htat will help out some work the Editor team is doing in terms of how they draw Structure-Guides.

**Comment by Pilchie** [comment]
Tagging @srivatsn since @MattGertz is on vacation

**Comment by CyrusNajmabadi** [comment]
The editor bug tracking their side is: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems?id=361527

**Pull request merged**
