### PR TITLE
Add test to prevent regression for a bug in legacy compiler

### PR DESCRIPTION
**Pull request by leppie**
Add test for #4695

### CODE REVIEW

**Comment by leppie** [comment]
retest prtest/lin/dbg/unit32  please

**Comment by dpoeschl** [comment]
The prtest/lin/dbg/unit32 failure ```07:42:53 curl: (23) Failed writing body (12288 != 16384)``` is the same that happened in #7033. Both ran on ```dci-ub-fbld-3```, so maybe it's a machine issue? @dotnet/roslyn-infrastructure

**Comment by dpoeschl** [comment]
Maybe it's this: http://stackoverflow.com/a/28879552

**Comment by dpoeschl** [comment]
retest prtest/lin/dbg/unit32 please // Trying to figure out if the [previous failure](http://dotnet-ci.cloudapp.net/job/roslyn_prtest_lin_dbg_unit32/1563/) is a machine problem or a build script problem or...

**Comment by leppie** [comment]
@dpoeschl @davkean think it is out of disk space https://github.com/dotnet/roslyn/pull/7028#issuecomment-159533998

**Comment by dpoeschl** [comment]
@leppie Thanks! @davkean @TyOverby I've taken fbld3 offline.

**Comment by dpoeschl** [comment]
retest prtest/lin/dbg/unit32 please // fbld3 is probably out of disk space. rerunning linux tests to ensure they load balance to another machine (and to get real results)

**Comment by dpoeschl** [comment]
Linux tests now running on dci-ub-bld-11

**Comment by davkean** [comment]
@dotnet-bot test eta please

**Comment by davkean** [comment]
tag @dotnet/roslyn-compiler

**Comment by gafter** [comment]
LGTM

**Comment by davkean** [comment]
eta failed due to https://github.com/dotnet/roslyn/issues/6981.

@dotnet-bot retest eta please

**Comment by davkean** [comment]
retest eta please

**Comment by AlekseyTs** [comment]
Would it make sense to have the test assembly run and output something that is compared against a baseline? LGTM, otherwise.

**Comment by leppie** [comment]
@AlekseyTs: The legacy compiler throws a `BadImageFormat` exception, but it is detectable with PEVerify.

**Comment by AlekseyTs** [comment]
Even so, if we expect some method to be called, it might make sense to verify that fact.

**Comment by leppie** [comment]
@AlekseyTs: Will add something

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
