### PR TITLE
porting OOP to preview 4 branch

### PR DESCRIPTION
**Pull request by heejaechang**
changes include
make SourceText::GetChecksum and AnalyzerTelemetry contructor public.

added MustRunInProc in IBuiltInAnalyzer and some clean up around serializing Solution/Project/DocumentId and how DocumentState is exposed.

simplified temporary storage service's temporary storage management and added ability to attach to existing temporary storage

solution checksum and serialization service.

added remote host client
- this gives an ability for host (vs) to talk to remote host (service hub)

rename and moving files between feature/workspace layers
- only real change is having ICompilerDiagnosticAnalyzer interface which can either have inproc implementation or out of proc implementation.
- inproc is needed since diagnostics are in feature layer and one who uses feature layer out side of VS host need an implementation.

added RemoteWorkspace
- RemoteWorkspace has host agnostic implementation of roslyn features/services/workspace that will run in remote host

added service hub component and setup project for service hub
- service hub component is basically thin layer that deals with converting data to pass in to RemoteWorkspace

made devdiv insertion tool to ignore servicehub related files

### CODE REVIEW

**Comment by heejaechang** [comment]
@MattGertz can I get approval for preview 4?

this is port from master for oop work. I got signed off from master branch.

**Comment by heejaechang** [comment]
retest vsi please

**Comment by heejaechang** [comment]
retest vsi please

**Comment by MattGertz** [comment]
Approved assuming tests passing and that the signoffs on code reviews are good.

**Comment by heejaechang** [comment]
thank you

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p1_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p1_open_prtest/3/
// Retest reason: opened issue.

**Comment by heejaechang** [comment]
http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/3/artifact/Open/Binaries/Release/Screenshots/

looks like VS license expired on test machine. all vsi tests are failing due to that.

**Comment by mavasani** [comment]
test vsi please

**Comment by heejaechang** [comment]
@mavasani build timeout. is it something related to moving to Dev15? should I rerun the test?

**Comment by mavasani** [comment]
The machines where the vsi runs were failing have been set offline for migration to Dev15. We are still holding back few machines for Dev14 microupdate and Dev15 preview4 runs - and if we still see the sign in dialog on those machines, we need to get them fixed.

**Comment by mavasani** [comment]
@dotnet-bot retest vsi please

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/4/
// Retest reason: same license issue.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/5/
// Retest reason: the machine ran into windows update issue.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p0_open_prtest/7/
// Retest reason: add analyzer node failed. opened an issue.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p0_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p0_open_prtest/8/
// Retest reason: same issue as before.

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/7/
// Retest reason: same issue as before.

**Comment by heejaechang** [comment]
retest vsi please

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p2_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p2_open_prtest/6/
// Retest reason: known issue - https://github.com/dotnet/roslyn/issues/12651

**Comment by heejaechang** [comment]
@dotnet-bot retest windows_vsi_p3_open_prtest please
// Previous failure: http://dotnet-ci.cloudapp.net/job/Private/job/dotnet_roslyn-internal/job/dev15-preview-4/job/windows_vsi_p3_open_prtest/9/
// Retest reason: known issue - https://github.com/dotnet/roslyn/issues/12320

**Pull request merged**
