### PR TITLE
Updating dependency versions for APEX binaries

### PR DESCRIPTION
**Pull request by jmarolf**
Microsoft.VisualStudio.Composition and Microsoft.VisualStudio.Threading need to be upgraded and `WithDesktopSupport` is now depricated

### CODE REVIEW

**Comment by olegtk** [comment]
This is already done for 15.6 in https://github.com/dotnet/roslyn/pull/23943. And it broke build correctness test so you might want to merge it if you hit any issues.

**Comment by mavasani** [comment]
@dotnet-bot retest this please

**Comment by jmarolf** [comment]
@mavasani there is no CI setup for this branch as its dependencies are not signed and will never succeed in Jenkins.  This is a temporary feature branch while we wait for official binaries.

**Comment by jmarolf** [comment]
as per @olegtk 's comment.  I've rebase on top of `master-vs-deps`

**Pull request merged**
