### PR TITLE
Bail out early before getting SyntaxTree

### PR DESCRIPTION
**Pull request by Youssef1313**
Preventing unneeded `await tree.GetRootAsync` may get things a little bit faster.

### CODE REVIEW

**Comment by sharwell** [comment]
📝 In practice, it won't really make a difference. The syntax root will already be cached because the same node is used by all analyzers that run on the tree¹. The only time this would save work is when both of the following are true:

1. This is the only analyzer enabled for the tree
2. The configuration for the analyzer is such that the analyzer doesn't run even though it is enabled

The main code that would benefit from optimizations relates to the options storage/evaluation.

¹ Strictly speaking, there is at least one additional allocation for a `Task<SyntaxNode>`, but for perspective we currently produce ~200GB allocations to analyze Roslyn.sln.

**Comment by Youssef1313** [comment]
> The configuration for the analyzer is such that the analyzer doesn't run even though it is enabled

@sharwell, I didn't get this. :-(

---

What I understood is my change only prevents an allocation of Task<SyntaxNode>, and this SyntaxNode is already cached. So, it's a kind of micro-optimization that doesn't have any value in practice. Is that right?

In that case, should I close the PR?

And thanks for review.

**Comment by sharwell** [comment]
> I didn't get this. :-(

Partly because I was mistaken thinking this was a change to the _analyzer_ when you actually changed the _refactoring_.

>  it's a kind of micro-optimization that doesn't have any value in practice. Is that right?

It's right in the sense that the value here doesn't come from the _performance_ difference, but see the next point...

> In that case, should I close the PR?

Absent a performance difference, it may still be relevant if we follow a pattern everywhere else except here, and this change means the code follows the pattern. If we aren't consistent, then I lean towards closing not because it's bad, but because it seems likely that another developer comes through in the future and moves this line back to where it was, and then we're back where we started.

**Comment by Youssef1313** [comment]
@sharwell That means we should check other code refactoring and see whether they bailout early or not?

**Comment by sharwell** [comment]
I don't see any harm in taking this one since it does follow the general "move declaration near first use" approach.

**Pull request merged**
