### PR TITLE
Change the prerelease NuGet version tag from rc3 to beta1

### PR DESCRIPTION
**Pull request by agocke**
@ManishJayaswal @amcasey @tmeschter

### CODE REVIEW

**Comment by agocke** [comment]
I'll also pull this into future

**Comment by ManishJayaswal** [comment]
LGTM

**Comment by ManishJayaswal** [comment]
Can we also start building 1.0.0 for stabilization branch?

**Comment by agocke** [comment]
@ManishJayaswal Yes, but that's a separate change.

**Comment by tmeschter** [comment]
Shouldn't we update `$(NugetReleaseVersion)` at the same time?

**Comment by agocke** [comment]
@tmeschter I would like this change to go into both master and future.

The versions should be updated as well, but that will be a different change (since master and future should have different version numbers).

**Comment by tmeschter** [comment]
@agocke I just want to make sure we don't "go back in time" and produce a signed build from master with version 1.0.0-beta1. :-)

**Comment by agocke** [comment]
@tmeschter Good point.

**Comment by agocke** [comment]
@tmeschter Also updated the version number here.

**Comment by tmeschter** [comment]
LGTM. We'll also need binding redirects for the csc.exe, vbc.exe, and vbcscompiler.exe binaries so that analyzers built against v1.0 can continue working in v1.1. However, I'll file a separate issue to handle that.

**Pull request merged**
