### PR TITLE
Make diagnostic bag argument non-nullable

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Found during exploratory work to reduce allocations of BindingDiagnosticBags.

### CODE REVIEW

**Review by AlekseyTs — CHANGES_REQUESTED** [review]
No motivation was provided

**Comment by CyrusNajmabadi** [comment]
> No motivation was provided

"Found during exploratory work to reduce allocations of BindingDiagnosticBags."

The motivation is to have parameters/state accurately describe what values they can be.

**Comment by AlekseyTs** [comment]
> The motivation is to have parameters/state accurately describe what values they can be.

It was intentional to allow null as an input for the APIs

**Comment by AlekseyTs** [comment]
So they can be null.

**Pull request closed without merging**
