### PR TITLE
Include content files in Roslyn.VisualStudio.Setup.Interactive.vsix

### LINKED ISSUE #4203: Response files not included in Interactive vsix(es)
This is why we're not picking them (e.g. CSharpInteractive.rsp) up at runtime.

### PR DESCRIPTION
**Pull request by amcasey**
Specifically, the default response files for initializing the Interactive windows.

Fixes #4203

### CODE REVIEW

**Comment by amcasey** [comment]
FYI @tmat @KevinH-MS @cston @ManishJayaswal

**Comment by KevinH-MS** [comment]
LGTM (but note, you've got an extra commit in this PR)

**Comment by amcasey** [comment]
@kevinh, yeah, I expected to have merged the preceding commit by now, but Jenkins is slow this morning.

**Comment by ManishJayaswal** [comment]
:+1:

**Pull request merged**
