### PR TITLE
Add InternalsVisibleTo TestImpact in Features...

### PR DESCRIPTION
**Pull request by KevinH-MS**
I want to start listening to SolutionCrawler events, but the necessary
interfaces are currently internal.

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @dotnet/roslyn-analysis @dotnet/roslyn-interactive

**Comment by KevinH-MS** [comment]
Note:  I'm just adding ```Microsoft.CodeAnalysis.TestImpact.Orchestrator```, the rest is just sorting things alphabetically.

**Comment by ManishJayaswal** [comment]
Why are we merging this change into master? Should't this be merged into features/test-impact?

**Comment by KevinH-MS** [comment]
@ManishJayaswal this is ***future***.  I'm doing it here (rather than test-impact), because we don't have a feed/builds from that branch, and I don't want to block on that for getting my stuff checked in (since this is a very low impact  change).

**Comment by tannergooding** [comment]
@KevinH-MS, @ManishJayaswal. we do have builds and a feed for the features/test-impact branch now.

**Pull request closed without merging**
