### PR TITLE
added support for metadata xml doc comment

### PR DESCRIPTION
**Pull request by heejaechang**
this was one of missing feature in OOP that was in backlog to support. @rynowak wanted this for Razor running in OOP. so added the support.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @panopticoncentral @KevinH-MS @rynowak @CyrusNajmabadi can you take a look?

**Comment by heejaechang** [comment]
ping?

**Comment by heejaechang** [comment]
can I get sign off?

**Comment by rynowak** [comment]
Thanks @heejaechang - for reference what VS release is this aligned with?

**Comment by heejaechang** [comment]
@rynowak right now 15.3 if you need, I can push it for earlier version.

**Comment by rynowak** [comment]
Ok, so is 15.3 going to be the default for anything going on in master? I'll check with my side and make sure we can rationalize this with our schedule.

**Pull request merged**
