### PR TITLE
Source Generators: Entered tracking issues on Source Generators and removed "PROTOTYPE" remarks

### PR DESCRIPTION
**Pull request by VSadov**
Entered tracking issues on Source Generators and removed "PROTOTYPE" remarks.
Very mechanical change.

The issues:
https://github.com/dotnet/roslyn/issues/11111
https://github.com/dotnet/roslyn/issues/11112
https://github.com/dotnet/roslyn/issues/11113
https://github.com/dotnet/roslyn/issues/11114
https://github.com/dotnet/roslyn/issues/11115
https://github.com/dotnet/roslyn/issues/11116
https://github.com/dotnet/roslyn/issues/11117
https://github.com/dotnet/roslyn/issues/11118
https://github.com/dotnet/roslyn/issues/11120
https://github.com/dotnet/roslyn/issues/11121
https://github.com/dotnet/roslyn/issues/11122
https://github.com/dotnet/roslyn/issues/11123
https://github.com/dotnet/roslyn/issues/11124
https://github.com/dotnet/roslyn/issues/11125
https://github.com/dotnet/roslyn/issues/11126
https://github.com/dotnet/roslyn/issues/11127
https://github.com/dotnet/roslyn/issues/11129
https://github.com/dotnet/roslyn/issues/11130
https://github.com/dotnet/roslyn/issues/11131
https://github.com/dotnet/roslyn/issues/11132
https://github.com/dotnet/roslyn/issues/11134

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet/roslyn-compiler - please take a look.  Removing PROTOTYPE in generators branch

**Comment by jcouv** [comment]
LGTM

**Comment by cston** [comment]
LGTM

**Comment by VSadov** [comment]
Thanks!!

**Pull request merged**
