### PR TITLE
Use immutable arrays.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Preemptively merging.

**Comment by Pilchie** [comment]
I'm fairly concerned about this change.  AFAIK, Roslyn.sln still doesn't compile with `/strict`, which means we still miss struct comparison with null warnings, and you may have just introduced a bunch which will now throw on the underlying array :-/

**Comment by Pilchie** [comment]
I would definitely prefer to see this broken up into a bunch of individual PRs (or at least commits), for each place that is changed so that they can be effectively reviews.

**Comment by CyrusNajmabadi** [comment]
How do we enable 'strict' mode for our projects?  I'm happy to validate things.

**Comment by Pilchie** [comment]
@gafter @jasonmalinowski is there a way to get `/strict` passed to the compiler?

**Pull request merged**
