### PR TITLE
Add RestrictedIVT to dotnet watch to Features

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@davidwengier PTAL

**Review by sharwell — DISMISSED** [review]
Restricted IVTs are not needed for dotnet-watch, since a proper External Access assembly is available.

https://github.com/dotnet/roslyn/tree/main-vs-deps/src/Tools/ExternalAccess/DotNetWatch

**Comment by tmat** [comment]
It is needed since the External Access project can't access debugger internals. The debugger only has IVT to Features currently and I would rather not add more IVTs to the debugger.

**Comment by sharwell** [comment]
> It is needed since the External Access project can't access debugger internals

We already updated that project to provide the new IVTs right?

**Comment by tmat** [comment]
> We already updated that project to provide the new IVTs right

Not sure what do you mean.

**Review by davidwengier — APPROVED** [review]

**Pull request merged**
