### PR TITLE
Make scripting specific VB compiler API internal for U2

### PR DESCRIPTION
**Pull request by tmat**
Fixes https://github.com/dotnet/roslyn/issues/9057 
Fixes https://github.com/dotnet/roslyn/issues/9058

### CODE REVIEW

**Comment by tmat** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/4118/
// Retest reason: timeout

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/4245/
// Retest reason:

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/unit64 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit64/4219/
// Retest reason:

**Comment by MattGertz** [comment]
LGTM, approved.

**Comment by Pilchie** [comment]
:+1:

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/4267/
// Retest reason: https://github.com/dotnet/roslyn/issues/9159

**Pull request merged**
