### PR TITLE
Upgrade to the Shell 15.8.27828 NuGet packages

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This upgrades us to 15.8.27828 for the core Visual Studio Shell NuGet packages.

I am removing our explicit references to Microsoft.VisualStudio.Imaging and Microsoft.VisualStudio.Utilities; both of these are carried along in references to Shell.15.0, and trying to state them explicitly just results in package downgrade warnings. I also fix up some other interop packages we had created ourselves now that official ones exist too.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Comment by heejaechang** [comment]
test failure @dotnet/roslyn-infrastructure 

Roslyn.VisualStudio.IntegrationTests.Other.CSharpAddMissingReference.VerifyAvailableCodeActions [FAIL] - Check Test Results for specific test information and call stack.
Indication 1 

https://ci.dot.net/job/dotnet_roslyn/job/master-vs-deps/job/windows_release_vs-integration_prtest/337/

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please

**Comment by jinujoseph** [comment]
Awesome !!! thanks @jasonmalinowski

**Pull request merged**
