### PR TITLE
Fix signing info

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
It's simpler if we sign everything we build.

**Comment by jasonmalinowski** [comment]
So this is a revert of #22936, where these *were* being signed but with a different key. What changed the key we were using?

**Comment by tmat** [comment]
@jasonmalinowski I switched all projects to the same key.

**Comment by jasonmalinowski** [comment]
@tmat That might have been bad. Why did we change that?

**Comment by tmat** [comment]
@jasonmalinowski What's bad about it?

> Why did we change that?

To simplify infrastructure.

**Pull request merged**
