### PR TITLE
Initialize FatalError handlers in VS and OOP

### PR DESCRIPTION
**Pull request by sharwell**
* Initialize `FatalError` handlers in VS and OOP
* Fail integration tests immediately on command execution failure

### CODE REVIEW

**Review by JoeRobich — APPROVED** [review]

**Comment by sharwell** [comment]
Didn't work as expected :(

**Comment by Youssef1313** [comment]
@sharwell Is there a way to run the integration tests a few times on say the last 50 commit on master, and see what's the oldest commit that fails? this might help knowing what's the changes that started to cause this failure for further investigation.

(Not entirely sure if that makes sense honestly)

**Review by tmat — APPROVED** [review]

**Review by jaredpar — CHANGES_REQUESTED** [review]
This is removing one of the _key_ parts of the compiler verification in order to enable telemetry in CI. That is not the right trade off here. We should make a more targeted disabling of this rather than whole sale disable it for all tests.

**Comment by sharwell** [comment]
> enable telemetry in CI

Enabling telemetry in CI is a non-goal for this PR. Our intent is to enable telemetry for shipping. I'm certainly open to alternatives to fix this.

**Comment by jaredpar** [comment]
> i'm certainly open to alternatives to fix this.

Disable the test that hit the assert.

**Comment by sharwell** [comment]
@jaredpar Switched to just skip that test. May need to skip more depending on how the tests go.

**Review by jaredpar — APPROVED** [review]

**Comment by 333fred** [comment]
@sharwell what is this waiting on?

**Comment by sharwell** [comment]
@333fred it still has a failing test (and possible crash), plus it needs ship room approval after it's passing

**Pull request merged**
