### PR TITLE
Avoid deadlock on solution close with linked files

### LINKED ISSUE #17305: Deadlock in VS while unloading project at OnDocumentContextUpdated
**Version Used**: d15rel/15.0.26221.0, Roslyn commit: 38afa69825db300e58aa6416dbb2c14ab340da7f

**Steps to Reproduce**:
(this seems to be very intermittant and probably not reproduce, please see attached dump)
1. Open solution with several projects and several open files
2. Close VS

**Expected Behavior**:
VS exits

**Actual Behavior**:
VS freezes at "Unloading project 6 of 31: [Project Name]"

**Callstack**:
```
 	mscorlib.dll!System.Threading.Monitor.Wait(object obj, int millisecondsTimeout, bool exitContext) Line 203	C#
 	mscorlib.dll!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeout(int millisecondsTimeout, uint startTime, System.Threading.CancellationToken cancellationToken) Line 469	C#
 	mscorlib.dll!System.Threading.SemaphoreSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken) Line 439	C#
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Workspace.OnDocumentContextUpdated(Microsoft.CodeAnalysis.DocumentId documentId, Microsoft.CodeAnalysis.Text.SourceTextContainer container) Line 354	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.OnHierarchyChanged(uint docCookie, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierOld, uint itemidOld, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, bool itemidChanged) Line 547	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.OnAfterAttributeChangeEx(uint docCookie, uint grfAttribs, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierOld, uint itemidOld, string pszMkDocumentOld, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, string pszMkDocumentNew) Line 535	C#
 	Microsoft.VisualStudio.LanguageServices.dll!Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.RunningDocTableEventsSink.OnAfterAttributeChangeEx(uint docCookie, uint grfAttribs, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierOld, uint itemidOld, string pszMkDocumentOld, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy pHierNew, uint itemidNew, string pszMkDocumentNew) Line 27	C#

```
See dump at: \\\\mlangfs1\public\pafenelo\Issue17305

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #17305
Fixes
https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=388328&_a=edit

Escrow Template
==========
**Customer scenario** I'm not exactly sure how to reproduce it, but multiple reports point to the same problem. When closing a solution, we close a linked file, which causes the running document table to tell us about a context change, which deadlocks. I believe it can hang **before saving the solution**.

**Bugs this fixes:** 

#17305
https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems?id=388328&_a=edit

**Workarounds, if any**: Close all open documents before closing the solution.

**Risk**: Fairly low. We avoid taking a lock when the lock has already been taken for us.

**Performance impact**: Essentially none. No allocations or complexity changes. 

**Is this a regression from a previous update?**: Unknown, but probably. I can't repro it, but the reports seem to be on RC4+ builds.

**Root cause analysis:** I don't know what regressed it. This should have been fixed in https://github.com/dotnet/roslyn/pull/16889, but I missed the linked files case. Shared Projects and linked files are now both handled appropriately.

**How did we miss it?**  I didn't think there were any additional callers of a particular overload of OnDocumentContextUpdated.

**How was the bug found?** Customer reports and dogfooding.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging for review: @dotnet/roslyn-ide 
FYI: @Pilchie

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by dpoeschl** [comment]
Tagging @ManishJayaswal and @srivatsn for escrow consideration.

**Comment by dpoeschl** [comment]
retest windows_release_vs-integration_prtest please

**Comment by natidea** [comment]
@dpoeschl you will need to retarget this to dev15.0.x
/cc @MattGertz I'm adding the pending shiproom tag. This is [388328](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/388328)

**Comment by MattGertz** [comment]
Groovy.

**Comment by dpoeschl** [comment]
Merging into master, not dev15.0.x.

**Pull request merged**
