### PR TITLE
Merge current microupdate fixes back into master

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Just a housekeeping merge, pulling all the fixes in microupdate-3.2 back into master, so we also get the nuget.exe fix.

*Review:* @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@cston I'm guessing this is OK with you? @jardpar or @agocke I think you generally wanted to be informed any time there was a nuget.exe update.

**Comment by cston** [comment]
@jasonmalinowski Yes, in fact nuget.exe was updated in master in https://github.com/dotnet/roslyn/pull/12173.

**Comment by agocke** [comment]
@jasonmalinowski LGTM, thanks

**Comment by jasonmalinowski** [comment]
Everything is green other than perf_correctness_prtest, which is failing because it doesn't know how to deal with this cross-branch merge since it's not running against merged sha1s right now.

**Pull request merged**
