### PR TITLE
Trigger ThemeColorFixer on FormatMappingChanged

### LINKED ISSUE #1123: VS font + color settings need a restart for tool tips
If you change color settings e.g. for User defined types you need to restart VS for them to be applied in tool tips. Im not sure if this bug reports fits here.

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes #1123

Update the ThemeColorFixer to trigger on IClassificationFormatMap.ClassificationFormatMappingChanged. This allows us to update the tooltip classifications when the user manually changes colors or imports color settings.

We previously listened for WM_SYSCOLORCHANGED and WM_THEMECHANGED, but those are now redundant and have been removed.

### CODE REVIEW

**Comment by dpoeschl** [comment]
Reviewers: @DustinCampbell @Pilchie @jasonmalinowski @rchande @balajikris @basoundr @brettfo

**Comment by DustinCampbell** [comment]
:+1:

**Comment by dpoeschl** [comment]
I've modified the commit message to point out that this means we now update the tooltip category when the user manually changes a color or imports color settings.

**Comment by Pilchie** [comment]
:+1:

**Pull request merged**
