### PR TITLE
Disable Obsolete checks for project level imports.

### LINKED ISSUE #4903: StackOverflowException caused by importing Serializable class on a project level
Ported from DevDiv 1208378

Compile the following code with /t:library /imports:GlobEnumsClass
```
<Serializable> Class GlobEnumsClass

    Public Enum xEmailMsg
        Option1
        Option2
    End Enum

End Class
```

Process is terminated due to StackOverflowException.

Doesn't crash if Serializable attribute is removed from the class.

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #4903.

@VSadov, @gafter, @jaredpar, @agocke Please review.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Ping. @VSadov, @gafter, @jaredpar, @agocke Please review.

**Comment by gafter** [comment]
Can you please explain why things were broken before? What was the problem and why does this fix it?

**Comment by gafter** [comment]
LGTM

**Comment by AlekseyTs** [comment]
Remapping of lazy Obsolete diagnostics in SourceModuleSymbol.BindImports forces compiler to bind attributes on imported types, which needs project level imports, and eventually causes SourceModuleSymbol.BindImports to be called again and the cycle continues. Reporting Obsolete diagnostics on project level imports is a breaking change, so suppressing it kills two birds with one stone.

**Comment by gafter** [comment]
LGTM

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
