### PR TITLE
Report an error for a misplaced `::` token.

### LINKED ISSUE #53021: A syntax error is missing for a misplaced ColonColon token in explicit interface implementation.
```
using N = NS1;

public class C : NS1.I
{
    void N::I::M() // Expect an error on a :: before M
    {
    }
}

namespace NS1
{
    interface I
    {
        void M();
    }
}
```

Observed: No errors
Expected: A syntax error

### PR DESCRIPTION
**Pull request by AlekseyTs**
Fixes #53021.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review a small bug fix.

**Review by 333fred — APPROVED** [review]
LGTM (commit 1). I'm curious: what did we treat the `::` as previously? A `.`, effectively?

**Comment by AlekseyTs** [comment]
> I'm curious: what did we treat the :: as previously? A ., effectively?

Correct.

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler For a second review for a small bug fix.

**Review by RikkiGibson — APPROVED** [review]

**Pull request merged**
