### PR TITLE
Update to the new issue template workflow

### PR DESCRIPTION
**Pull request by Youssef1313**
I can write more templates other than a bug report if you wish to.

### CODE REVIEW

**Comment by Youssef1313** [comment]
Note: This PR triggered a build process, which isn't really needed.

If the CI could be changed to avoid that, it will be better.

**Comment by Youssef1313** [comment]
I'm going to add a config file that redirects users to csharplang repo for suggesting features to the c# language.

**Comment by Youssef1313** [comment]
The CI fails while I didn't touch any code files. That's strange.

**Comment by RikkiGibson** [comment]
Yeah, it’s because we have test flakiness issues

**Comment by Youssef1313** [comment]
I added the config.yml file.
I also changed the default branch in my fork so you can preview how this would look from [here](https://github.com/Youssef1313/roslyn/issues/new/choose).

**Comment by jmarolf** [comment]
@Youssef1313 I'll merge this in today, thanks for the help!

**Pull request merged**
