### PR TITLE
Disable UseAutoPropertyAnalyzer for now...

### PR DESCRIPTION
**Pull request by KevinH-MS**
The performance impact needs to be investigated.

### CODE REVIEW

**Comment by mmitche** [comment]
Can one of the admins approve this PR test or whitelist this user?

**Comment by KevinH-MS** [comment]
test full please

**Comment by KevinH-MS** [comment]
FYI @CyrusNajmabadi

**Comment by KevinH-MS** [comment]
FYI @tannergooding

**Pull request merged**
