### PR TITLE
Don't commit rename after dismissed during debugging

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes internal bug #1176673

### CODE REVIEW

**Comment by dpoeschl** [comment]
Potential reviewers: @Pilchie @jasonmalinowski @brettfo @rchande @balajikris @jmarolf

**Comment by jasonmalinowski** [comment]
How is this possible? I would have imagined the dismiss unsubscribes from everything so it'd never see this again...

**Comment by Pilchie** [comment]
Same question as @jasonmalinowski.

**Comment by Pilchie** [comment]
Also, what about tests? I thought when you added the debugger state tracking you had a way of tests causing the events to fire.

**Comment by dpoeschl** [comment]
Good point, recalling this approach completely.

**Pull request closed without merging**
