### PR TITLE
Completion options

### PR DESCRIPTION
**Pull request by Pilchie**
Port changes to add options for completion filtering and highlighting to `future-stabilization`.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tag @dotnet/roslyn-ide @CyrusNajmabadi to review these look right.  @MattGertz FYI - this is the change to introduce the options in `future-stabilization`.

**Comment by MattGertz** [comment]
Provisional approval pending shiproom.

**Comment by Pilchie** [comment]
test vsi please

**Comment by CyrusNajmabadi** [comment]
:+1:

**Pull request merged**
