### PR TITLE
Simplify some of our internal extension methods.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Review by sharwell — CHANGES_REQUESTED** [review]
The original exception messages were more meaningful. I do not have confidence that these exceptions are unreachable.

**Comment by CyrusNajmabadi** [comment]
> The original exception messages were more meaningful.

I really fail to see how that's the case.  If we hit this exception in these helpers it's instantly obvious what the issue is.  We do one check: did we get null.  If we get null, we fail.  So, if someone calls `GetRequriedSyntaxTree` and this blows up, the issue is clear and needs no more explanation.

This is the same as practically all other contract calls we have when the methods are this basic.

> I do not have confidence that these exceptions are unreachable.

Evne if they are reachable, they should not be localized.  These are not public contract sides of people calling into us.  They are internal failures.  They need not be localized, just as our usages of Contract.ThrowXXX, or Debug.XXX need not be localized.  If someone ever gets this calling through us then it's a bug on our side as we either didn't consider this condition, or we forgot to check some input (which should have had an ArgumentException, not an InvalidOperaitonException).

Invariant checking does not get localized.

**Comment by sharwell** [comment]
Is there an issue that this is resolving to get more context? It's not clear why the current approach is a problem, or why we would want to move in this direction.

**Comment by CyrusNajmabadi** [comment]
> Is there an issue that this is resolving to get more context? It's not clear why the current approach is a problem, or why we would want to move in this direction.

Yes, this came up in another PR where more of these methods were being added.  This brought the issue to my attention.  

>  It's not clear why the current approach is a problem

A few reasons.  First, it's a tax on our loc team.  Second, it's inconsistent with the rest of the patterns and practices for the rest of hte IDE codebase.

**Comment by jasonmalinowski** [comment]
So what worries me here is Contract.ThrowIfNull() looks like it throws an InvalidOperationException, which we _also_ were throwing intentionally before. We have a bunch of tests for the Workspace and such that assert that we throw InvalidOperationException, but we rarely assert the actual message. If any of these were being expected to throw a proper message, we won't know that.

What happens if we change Contract.Fail to instead throw a custom exception type that derives straight from Exception? That way if any of these do escape into tests we'd know; if we don't have tests in the first place, well...that's our own fault. :smile: If we call it something like RoslynInternalException it'll hopefully also be clearer that if we ever did leak one, that it shouldn't have leaked.

**Pull request closed without merging**
