### PR TITLE
Fix ApplyPartialNgenOptimization property name

### PR DESCRIPTION
**Pull request by tmat**
Turns out I named the property `ApplyNgenOptimizationData` in one place and `ApplyPartialNgenOptimization` in other places and that obviously does not work :-|. Use `ApplyPartialNgenOptimization` consistently.

### CODE REVIEW

**Comment by tmat** [comment]
@genlu

**Comment by genlu** [comment]
@dpoeschl I think we just missed the codeflow for today, so we need to trigger another merging PR once this is merged,

**Comment by dpoeschl** [comment]
@genlu Yep. Will push to `-vs-deps` after it's merged.

**Comment by dpoeschl** [comment]
Actually, Spanish just finished. @tmat @genlu is this good to merge?

**Pull request merged**
