### PR TITLE
Fix access violation when MemoryMappedFile is disposed

### LINKED ISSUE #56195: AV from DirectMemoryAccessStreamReader
OOP crashes with AV

image

Crash dump and `.vs` dir content: `\\mlangfs1\public\tomat\Bugs\AV`

```
>	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.DirectMemoryAccessStreamReader.Read(char[] buffer, int index, int count) Line 463	C#
 	mscorlib.dll!System.IO.TextReader.ReadToEnd()	Unknown
 	Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.Text.SourceText.From(System.IO.TextReader reader, int length, System.Text.Encoding encoding, Microsoft.CodeAnalysis.Text.SourceHashAlgorithm checksumAlgorithm) Line 133	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Host.TextFactoryService.CreateText(System.IO.TextReader reader, System.Text.Encoding encoding, System.Threading.CancellationToken cancellationToken) Line 36	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.ReadText(System.Threading.CancellationToken cancellationToken) Line 241	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Host.TemporaryStorageServiceFactory.TemporaryStorageService.TemporaryTextStorage.GetChecksum() Line 211	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.Serialization.SerializerService.CreateChecksum(object value, System.Threading.CancellationToken cancellationToken) Line 92	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.TextDocumentState.ComputeChecksumsAsync(System.Threading.CancellationToken cancellationToken) Line 43	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.Serialization.DocumentStateChecksums>.StartAsynchronousComputation(Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.Serialization.DocumentStateChecksums>.AsynchronousComputationToStart computationToStart, Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.Serialization.DocumentStateChecksums>.Request requestToCompleteSynchronously, System.Threading.CancellationToken callerCancellationToken) Line 398	C#
 	Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.AsyncLazy<Microsoft.CodeAnalysis.Serialization.DocumentStateChecksums>.GetValueAsync(System.Threading.CancellationToken cancellationToken) Line 359	C#
 	Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.GetDocumentMapAsync(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.TextDocumentState> states, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.Checksum> documents) Line 498	C#
 	Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateDocumentsAsync(Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums projectChecksums, System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.TextDocumentState> existingTextDocumentStates, Microsoft.CodeAnalysis.Serialization.ChecksumCollection oldChecksums, Microsoft.CodeAnalysis.Serialization.ChecksumCollection newChecksums, System.Func<Microsoft.CodeAnalysis.Solution, System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.DocumentInfo>, Microsoft.CodeAnalysis.Solution> addDocuments, System.Func<Microsoft.CodeAnalysis.Solution, Microsoft.CodeAnalysis.DocumentId, Microsoft.CodeAnalysis.Solution> removeDocument) Line 361	C#
 	Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectAsync(Microsoft.CodeAnalysis.Project project, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums oldProjectChecksums, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums newProjectChecksums) Line 244	C#
 	Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Microsoft.CodeAnalysis.Solution solution, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.Checksum> oldChecksums, System.Collections.Generic.HashSet<Microsoft.CodeAnalysis.Checksum> newChecksums) Line 177	C#

 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
>	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown
 	[Completed] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.SynchronizeAssetsAsync(System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.ProjectId, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums> oldMap, System.Collections.Generic.Dictionary<Microsoft.CodeAnalysis.ProjectId, Microsoft.CodeAnalysis.Serialization.ProjectStateChecksums> newMap) Line 195	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown
 	[Completed] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.AssetProvider.SynchronizeProjectAssetsAsync(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Checksum> projectChecksums, System.Threading.CancellationToken cancellationToken) Line 104	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult>.TrySetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.VoidTaskResult result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.SetResult(System.Threading.Tasks.Task<System.Threading.Tasks.VoidTaskResult> completedTask)	Unknown
 	[Completed] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.ChecksumSynchronizer.SynchronizeProjectAssetsAsync(System.Collections.Generic.IEnumerable<Microsoft.CodeAnalysis.Checksum> projectChecksums, System.Threading.CancellationToken cancellationToken) Line 55	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<Roslyn.Utilities.SemaphoreSlimExtensions.SemaphoreDisposer>.TrySetResult(Roslyn.Utilities.SemaphoreSlimExtensions.SemaphoreDisposer result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Roslyn.Utilities.SemaphoreSlimExtensions.SemaphoreDisposer>.SetResult(Roslyn.Utilities.SemaphoreSlimExtensions.SemaphoreDisposer result)	Unknown
 	[Completed] Microsoft.CodeAnalysis.Workspaces.dll!Roslyn.Utilities.SemaphoreSlimExtensions.DisposableWaitAsync(System.Threading.SemaphoreSlim semaphore, System.Threading.CancellationToken cancellationToken) Line 24	C#
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<bool>.TrySetResult(bool result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<bool>.SetResult(bool result)	Unknown
 	[Completed] mscorlib.dll!System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(System.Threading.SemaphoreSlim.TaskNode asyncWaiter, int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.OutputAsyncCausalityEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(System.Threading.Tasks.Task completingTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<bool>.TrySetResult(bool result)	Unknown
 	mscorlib.dll!System.Threading.SemaphoreSlim.TaskNode.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	[Native to Managed Transition]	
 	[Async Call Stack]	
 	[Async] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.UpdateProjectsAsync(Microsoft.CodeAnalysis.Solution solution, Microsoft.CodeAnalysis.Serialization.ChecksumCollection oldChecksums, Microsoft.CodeAnalysis.Serialization.ChecksumCollection newChecksums) Line 126	C#
 	[Async] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.CreateSolutionAsync(Microsoft.CodeAnalysis.Checksum newSolutionChecksum) Line 82	C#
 	[Async] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteWorkspace.GetProjectSubsetSolutionAsync.__GetProjectSubsetSolutionSlowAsync|15_0(Microsoft.CodeAnalysis.Solution baseSolution, Microsoft.CodeAnalysis.Remote.AssetProvider assetProvider, Microsoft.CodeAnalysis.Checksum solutionChecksum, Microsoft.CodeAnalysis.ProjectId projectId, System.Threading.CancellationToken cancellationToken) Line 273	C#
 	[Async] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.GetSemanticClassificationsAsync.AnonymousMethod__0(System.Threading.CancellationToken cancellationToken) Line 36	C#
 	[Async] Microsoft.CodeAnalysis.Remote.ServiceHub.dll!Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.RunServiceImplAsync<Microsoft.CodeAnalysis.Classification.SerializableClassifiedSpans>(System.Func<System.Threading.CancellationToken, System.Threading.Tasks.ValueTask<Microsoft.CodeAnalysis.Classification.SerializableClassifiedSpans>> implementation, System.Threading.CancellationToken cancellationToken) Line 75	C#
 	[Async] StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.DispatchIncomingRequestAsync(StreamJsonRpc.Protocol.JsonRpcRequest request)	Unknown
 	[Async] StreamJsonRpc.dll!StreamJsonRpc.JsonRpc.HandleRpcAsync(StreamJsonRpc.Protocol.JsonRpcMessage rpc)	Unknown

```

### PR DESCRIPTION
**Pull request by sharwell**
This change updates `CreateReadableStream` and `CreateWritableStream` to consistently throw 
`InvalidOperationException`/`ObjectDisposedException` if `MemoryMappedFile` is disposed prior to creating the stream, including
concurrent scenarios.

Fixes #56195

### CODE REVIEW

**Comment by ryzngard** [comment]
❓ are these exceptions handled as expected, or is it to better understand the problem at the point of creation rather than use?

**Comment by sharwell** [comment]
This exception is not expected or handled. This pull request serves only to stabilize the exception instead of sometimes getting an InvalidOperationException and sometimes just corrupting unmanaged memory.

**Review by ryzngard — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
I wouldn't say this "Fixes #56195" just yet.  It helps mitigate the memory munging issue.  but the user is likely going to face a crash with this new exception type, and/or see oop instability with these features.  i'm ok with this going through, but i don't think we should stop the investigation until we can determine the underlying race.

**Comment by sharwell** [comment]
@CyrusNajmabadi I can file a follow-up issue for investigating the concurrent dispose.

**Comment by sharwell** [comment]
➡️ Filed https://github.com/dotnet/roslyn/issues/56305

**Pull request merged**
