### PR TITLE
Adding some IDE code fix tests for async using & foreach

### PR DESCRIPTION
**Pull request by Neme12**
I discovered that these features already work so I just added the tests.

Tagging @jcouv this is for your feature branch

### CODE REVIEW

**Comment by Neme12** [comment]
@jcouv This is for your feature branch can you please take a look? Thanks

**Comment by jcouv** [comment]
@dotnet/roslyn-ide for a second review (test-only change). Thanks

**Comment by Neme12** [comment]
Does this need review from the IDE team?

**Comment by CyrusNajmabadi** [comment]
Note: in general, our requirements for a test-only change are much weaker.  Tagging @jinujoseph for her thoughts here.  I think it's fine to just get a single review for safe and clear test-only changes like these.

**Comment by jinujoseph** [comment]
yes, single review from IDE team is good.

**Comment by Neme12** [comment]
> yes, single review from IDE team is good.

Can I get a buddy from IDE then please? Thank you

**Comment by jinujoseph** [comment]
I just reviewed it , good from IDE

**Comment by Neme12** [comment]
@jinujoseph Thanks, I commented at the same time and didn't notice (again).

**Comment by jcouv** [comment]
Thanks much, @Neme12!

**Comment by Neme12** [comment]
@jcouv Note: I think you should be able to check the third checkbox in this list as this PR took care of testing that (from #24037):

> * [ ]  Code fixers:
>   
>   * [ ]  fix `foreach` (by adding/removing `await`) depending on the collection type
>   * [ ]  fix method declaration depending on presence/absence of `yield` or `await`
>   * [ ]  using `foreach await` in non-async method should offer to convert the method to `async`

**Comment by jcouv** [comment]
Cool!
Checked that box. Thanks

**Pull request merged**
