### PR TITLE
Bump the version number to 2.3.1

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This pull request will be merged once we've uploaded the 2.3.0 NuGet packages, but no sooner than that.

### CODE REVIEW

**Review by jaredpar — APPROVED** [review]

**Review by shyamnamboodiripad — APPROVED** [review]

**Review by mavasani — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
ubutnu_14_debug_prtest hit #18985.
windows_release_unit32_prtest hit #14592.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest this please.

**Review by jinujoseph — APPROVED** [review]

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_debug_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_release_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please.

**Pull request merged**
