### PR TITLE
Handle names correctly in long tuples in EE

### LINKED ISSUE #13625: Incorrect names in the EE in long tuple
Names in the last nested tuple of `C.F` are incorrect in the EE.
```
class C
{
    static ((int A, (int B, int C) D, int E, int F, int G, int H, int I, int J) K, (int L, int M, int N) O) F =
        ((1, (2, 3), 4, 5, 6, 7, 8, 9), (10, 11, 12));
}
```
Result:
```
((int A, (int B, int C) D, int E, int F, int G, int H, int I, int J) K, (int, int L, int M) O)
```

### PR DESCRIPTION
**Pull request by cston**
Port #13651 to dev15-preview-5.

Fixes #13625.

### CODE REVIEW

**Comment by cston** [comment]
@mattgertz for approval
cc @dotnet/roslyn-compiler

**Comment by MattGertz** [comment]
Approved pending tests & signoff.

**Comment by cston** [comment]
@dotnet-bot test this please

**Comment by cston** [comment]
@dotnet-bot test this please

**Pull request merged**
