### PR TITLE
esnure path to global config file is correctly cased

### PR DESCRIPTION
**Pull request by jmarolf**
fixes https://github.com/dotnet/roslyn-analyzers/issues/5360

### CODE REVIEW

**Review by davidwengier — APPROVED** [review]

**Review by Youssef1313 — COMMENTED** [review]
Is there a parallel PR to roslyn-analyzers? Both repos have the same issue

**Comment by jmarolf** [comment]
> Is there a parallel PR to roslyn-analyzers? Both repos have the same issue

https://github.com/dotnet/roslyn-analyzers/pull/5421

**Comment by jmarolf** [comment]
azp /run

**Pull request merged**
