### PR TITLE
Upgrade Microsoft.CodeAnalysis.Analyzers version to 2.6.1

### PR DESCRIPTION
**Pull request by jmarolf**
Fixes https://github.com/dotnet/roslyn/issues/24899

### CODE REVIEW

**Comment by sharwell** [comment]
💭 Interested to see if everything downstream works after this but seems fine.

**Comment by mavasani** [comment]
We need 2.6.1 (not yet produced) to include Dustin’s MSBuild analyzer. I will produce and publish this package on Tuesday.

**Comment by jmarolf** [comment]
@mavasani what is the status of 2.6.1?

**Comment by mavasani** [comment]
> @mavasani what is the status of 2.6.1?

They are currently being tested. I have added you to the email thread.

**Comment by etbyrd** [comment]
@dotnet-bot test windows_debug_spanish_unit32_prtest

**Comment by jmarolf** [comment]
retest windows_debug_spanish_unit32_prtest  please

**Pull request merged**
