### PR TITLE
Remove PROTOTYPE markers from "private protected" feature

### LINKED ISSUE #22244: Remove PROTOTYPE markers from "private protected" feature
It looks like some PROTOTYPE markers made it through when the feature was merged.

https://github.com/dotnet/roslyn/blame/9da689b5e705672c050bbac63bccd896ba4aefbb/src/VisualStudio/CSharp/Impl/CodeModel/CSharpCodeModelService.cs#L1041

https://github.com/dotnet/roslyn/blob/9da689b5e705672c050bbac63bccd896ba4aefbb/src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb#L1425

### PR DESCRIPTION
**Pull request by gafter**
Fixes #22244
Related to #22406

This is a comment-only change, to remove PROTOTYPE comments and replace by open issues.

@jcouv Please review and approve for 15.5.

### CODE REVIEW

**Comment by jcouv** [comment]
test windows_debug_unit64_prtest please

**Comment by jcouv** [comment]
windows_debug_unit64_prtest failed with test timeout ([details](https://ci.dot.net/job/dotnet_roslyn/job/master/job/windows_debug_unit64_prtest/9881/))

FYI @dotnet/roslyn-infrastructure I'll re-run

**Comment by jcouv** [comment]
test windows_debug_unit64_prtest please

**Comment by gafter** [comment]
test windows_debug_unit64_prtest please

**Comment by gafter** [comment]
test windows_debug_unit64_prtest please

**Comment by gafter** [comment]
test windows_debug_unit64_prtest please

**Pull request merged**
