### PR TITLE
Use VBCSCompilerServer in bootstrap build

### PR DESCRIPTION
**Pull request by jaredpar**
Small change to enable VBCSComplierServer in our bootstrap builds.  This should help reduce the time in Jenkins a bit.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @agocke, @tannergooding, @TyOverby

**Comment by jaredpar** [comment]
test windows please

**Comment by TyOverby** [comment]
How does this speed things up?  Seems like you just added an extra layer of indirection; I must be missing something.

**Comment by TyOverby** [comment]
Oh, the introduction of "/shared"?

**Comment by jaredpar** [comment]
The speed up trick comes with the `/shared` option.  This tells csc / vbc to use the shared compilation process if possible.  That process will speed up the compilation because allow us to pay certain costs a single time that tend to factor significantly into batch build operations.  In particular: cracking metadata and JIT.

**Comment by jaredpar** [comment]
Not I ended up moving this over to #5931 to work around a jenkins issue.

**Comment by TyOverby** [comment]
Makes sense; lgtm

**Pull request closed without merging**
