### PR TITLE
Update the work around for .editorconfig evaluation bugs in command l…

### LINKED ISSUE #44589: Shared projects in Roslyn.sln showing no files in solution explorer
**Version Used**: Latest 16.7 dogfood build

**Steps to Reproduce**:

1. git clone https://github.com/dotnet/roslyn.git
2. cd roslyn
3. git checkout dfdc4efd75ab7ab67668154323702227a2a805d3
4. restore
5. Roslyn.sln
6. Expand any shared project in solution explorer

**Expected Behavior**:
Shows files:
image

**Actual Behavior**:
No files:
image

### PR DESCRIPTION
**Pull request by mavasani**
…ine builds

Fixes #44589

### CODE REVIEW

**Comment by sharwell** [comment]
What happens if we explicitly put this in the .shproj file?

```
<PropertyGroup>
  <DesignTimeBuild>true</DesignTimeBuild>
</PropertyGroup>
```

**Comment by mavasani** [comment]
> What happens if we explicitly put this in the .shproj file(s)

That seems very wonky to me. Current workaround is more explicit as the target only needs to execute before CoreCompile, which only executes on explicit builds.

**Comment by mavasani** [comment]
Ping for reviews..

**Comment by mavasani** [comment]
@sharwell Thanks, fixed now.

**Pull request merged**
