### PR TITLE
we called work done too early for error list.

### PR DESCRIPTION
**Pull request by heejaechang**
previously, we set all work as done when we pass out last work from the queue without waiting that work to be done.

now, we raise works as done only when last item passed out are actually done.

<details>

### Customer scenario

user thinks error list is up to date, but it is still missing information or errors in error list looks wrong.

### Bugs this fixes

https://github.com/dotnet/roslyn/issues/23607

### Workarounds, if any

there is no workaround.

### Risk

I don't see any risk

### Performance impact

no performance impact. it doesn't do any additional work. just moved marker to later point.

### Is this a regression from a previous update?

No

### Root cause analysis

we have very subtle "in progress" indicator in error list that basically tells users (if they are looking for it) whether error list is done and up to date or it is still updating errors in the error list.

image

we have this since analyzing errors for whole solution takes time. if building solution takes 5 min in command line, then in IDE, it will at minimum take 5 min (actually way more since build uses whole resources and all CPUs for throughput, but IDE uses only 1 thread to calculate errors for UI responsiveness). but since we can't update or block error list until we are fully up to date (then we might never update error list since user constantly modifies code), we incrementally/partially update error list all the time with portion of up to date errors that we believe most relevant to users at this point of time. but this is heuristic and not always 100% correct. so we need a way to tell users error list is not 100% up to date yet. so we have the above indicator.

this also will be used in test to indicate that error list is up to date and test can reliably see what the result is. or we use this in screenshot of user feedback to see user has up to date information.

previously, this bug could result in user confusion (if they know about this indicator), or flaky tests.

### How was the bug found?

dogfooding. tests

</details>

### CODE REVIEW

**Comment by heejaechang** [comment]
@jinujoseph can we bring this to ask mode?

**Comment by jinujoseph** [comment]
@heejaechang can you fill out the ask mode template pls then loop in Kevin

**Comment by heejaechang** [comment]
@jinujoseph you mean VSO bug?

**Comment by heejaechang** [comment]
@jinujoseph I already did. see the <detail> tag.

**Comment by jinujoseph** [comment]
dha, sorry about that ...looping @Pilchie for ask mode approval

**Comment by Pilchie** [comment]
Approved.

**Comment by heejaechang** [comment]
@dotnet/roslyn-infrastructure 
https://ci.dot.net/job/dotnet_roslyn/job/master/job/ubuntu_16_debug_prtest/7776/
Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.IndexerTests.ParameterArray [Failed]

**Comment by heejaechang** [comment]
retest ubuntu_16_debug_prtest please

**Pull request merged**
