### PR TITLE
Remove Esent entirely from Roslyn.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/21181

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @Pilchie

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechang

**Comment by heejaechang** [comment]
👍

**Comment by Pilchie** [comment]
I synced `master` this morning, and restored and got restore warnings about ManagedEsent, so it looks like some trace remains...

**Comment by Pilchie** [comment]
```
C:\Code\roslyn [master ≡]> .\Restore
Repo Dir C:\Code\roslyn
Binaries Dir C:\Code\roslyn\Binaries
Running restore
Using existing NuGet.exe at version 4.1.0
Restore using MSBuild at C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\\MSBuild\15.0\bin
Restoring Base Toolset
Restoring Roslyn
WARNING: Dependency specified was ManagedEsent  but ended up with ManagedEsent 1.0.
WARNING: Dependency specified was ManagedEsent  but ended up with ManagedEsent 1.0.
WARNING: Dependency specified was ManagedEsent  but ended up with ManagedEsent 1.0.
Restoring Samples
Restoring Templates
Restoring DevDivInsertionFiles
C:\Code\roslyn [master ≡]>
```

**Pull request merged**
