### PR TITLE
Port: #18163 "Change s_FieldModifiers filter to accept WithEvents modifier on VB fields" Dev15.2.x

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @Pilchie

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz  as well.

**Comment by MattGertz** [comment]
I'll push to JoC.

**Comment by natidea** [comment]
Bug and Ask Mode content [406966](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/406966)

**Comment by natidea** [comment]
Shiproom approved to merge via  [406966](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/406966)

**Pull request merged**
