### PR TITLE
Porting VB WinForms Tests

### PR DESCRIPTION
**Pull request by jmarolf**
Poring the VB WinForms tests to the new test framework.
Depends on https://github.com/dotnet/roslyn/pull/17226 getting merged

### CODE REVIEW

**Comment by Pilchie** [comment]
Will look again when tests passing.

**Comment by jmarolf** [comment]
retest windows_release_vs-integration_prtest please

**Comment by jmarolf** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by jmarolf** [comment]
ping @dotnet/roslyn-ide these tests aren't going to pass until the infrastructure issue is fixed Tuesday, so could I get some reviews?

**Pull request merged**
