### PR TITLE
Provide user facing options to control if expression bodied members are preferred or not.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is a port from master to RC.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz  @ManishJayaswal @Pilchie

**Comment by CyrusNajmabadi** [comment]
Will need a change in closed as well.

**Comment by ManishJayaswal** [comment]
@Pilchie I am assuming all these ports from master are reviewed and approved by you to port to rc as there is not explicit signoff on these PRs. Please let me know if this is not true.

**Comment by ManishJayaswal** [comment]
Approved pending test completion.

**Comment by CyrusNajmabadi** [comment]
We're not taking for RC.  We'll take for RC2 instead.

**Pull request closed without merging**
