### PR TITLE
Revert "use FormattedSymbol"

### PR DESCRIPTION
**Pull request by heejaechang**
Reverts dotnet/roslyn#8223

### CODE REVIEW

**Comment by srivatsn** [comment]
Why?

**Comment by davkean** [comment]
Context?

**Comment by heejaechang** [comment]
@srivatsn @davkean @AlekseyTs put some more feedback on the PR which it seems I didn't address. I thought I went through all feedbacks but some seems still left. and he said I need one more sign off from compiler team.

**Comment by heejaechang** [comment]
I am closing this. @AlekseyTs is okay checking in the other delta PR (https://github.com/dotnet/roslyn/pull/8561) rather than reverting it back and merge PRs and check the new one.

**Pull request closed without merging**
