### PR TITLE
Avoid building .vsix in parallel

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@dotnet-bot retest this please

**Comment by jaredpar** [comment]
What's the motivation for this change?  This will significantly slow down our Jenkins runs as it increases build time by about %35.

**Comment by jaredpar** [comment]
CC @jasonmalinowski

**Comment by cston** [comment]
@jaredpar I've created the PR to try to narrow down the source of #11856.

**Comment by cston** [comment]
@dotnet-bot retest this please

**Comment by jasonmalinowski** [comment]
@cston Can this be closed now?

**Pull request closed without merging**
