### PR TITLE
Removed text truncation logic from Introduce Variable codeaction

### LINKED ISSUE #5258: Introduce Variable codeaction has text truncation logic that should be removed
Porting internal bug 129568.

Editor team has changed the LightBulb functionality so that it truncates LightBulb menu item's text at a certain length. It also replaces newlines, carriage returns, and tab characters with spaces.

[IntroduceVariable](https://github.com/dotnet/roslyn/blob/7755b1632509f7fc9c6f494c99711dae8d700499/src/Features/Core/Portable/IntroduceVariable/AbstractIntroduceVariableService.AbstractIntroduceVariableCodeAction.cs#L79) does some truncation that is no longer required, so it should be removed (to maintain consistency).

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Fixes #5258

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Interesting.  THe link mentions that they also remove newlines and whatnot.  So we could get rid of our ConvertToSingleLine helper in several cases.

**Comment by jinujoseph** [comment]
@JieCarolHu  to validate the change

**Comment by sharwell** [comment]
retest this please

**Comment by JieCarolHu** [comment]
Verified it works as expected

image

**Comment by JieCarolHu** [comment]
@jinujoseph  Could you approve this merge? Thanks

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview4

**Comment by jinujoseph** [comment]
thanks zaytsev-victor

**Pull request merged**
