### PR TITLE
Include Analyzers UnitTests projects in Compilers.slnf

### LINKED ISSUE #44823: Missing analyzer test projects in slnf
The analyzers test projects cannot be found in Solution Explorer when Compilers.slnf is opened in Visual Studio.

The analyzers were added recently to the slnf in https://github.com/dotnet/roslyn/pull/44751.
I think the unit tests should be added too.

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #44823

### CODE REVIEW

**Comment by Youssef1313** [comment]
This change made the tests appear in solution explorer, however, when editing the files it shows as *Miscellaneous Files* with type navigation not working.

image

@sharwell, Is there something I should add to the slnf so the tests work properly?

**Comment by sharwell** [comment]
The **.shproj** files contain the source code, but the **.csproj** files under src/CodeStyle are the actual projects for these.

**Comment by Youssef1313** [comment]
@sharwell, I've added the csproj too and it seems to work locally. Can you re-review?

**Comment by sharwell** [comment]
The IDE team (Area-IDE) maintains these projects, but does not use **Compilers.slnf**. The compiler team will need to review this change and determine if they want these projects included in their normal workflow.

**Comment by Youssef1313** [comment]
@mavasani, This should be closed right?

**Comment by mavasani** [comment]
Instead of closing this PR, I would suggest to go the opposite route: Remove all the projects under `src\Analyzers` and `src\CodeStyle` from `Compilers.sln` and `Compilers.slnf`. The fact that we have some of these in solution, but not all is the root cause of the confusion.

@dotnet/roslyn-compiler team, any concerns removing these IDE specific projects from compilers solution?

**Comment by Youssef1313** [comment]
@mavasani, I opened a new PR to remove these (Just easier than modifying this one, I had to just click the revert button in the PR that added these).

https://github.com/dotnet/roslyn/pull/45164

**Pull request closed without merging**
