### PR TITLE
Make IDEDiagnosticIDs distinct

### PR DESCRIPTION
**Pull request by dpoeschl**
Switch AddQualificationDiagnosticId to "IDE0009" to remove conflict with IntellisenseBuildFailedDiagnosticId ("IDE0006").

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging for review: @Pilchie @srivatsn @heejaechang

**Comment by srivatsn** [comment]
:+1:

**Comment by Pilchie** [comment]
:+1:

**Comment by davkean** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/5418/
// Retest reason: https://github.com/dotnet/roslyn/issues/10101

**Pull request merged**
