### PR TITLE
Revert the commit that removed IOperation Feature flag 

### PR DESCRIPTION
**Pull request by genlu**
@jaredpar @AlekseyTs @agocke @ManishJayaswal @srivatsn

### CODE REVIEW

**Comment by genlu** [comment]
retest vsi please

**Comment by AlekseyTs** [comment]
LGTM

**Comment by AlekseyTs** [comment]
@dotnet/roslyn-compiler Please review.

**Comment by genlu** [comment]
@jcouv Could you take a look at this please?

**Comment by jcouv** [comment]
LGTM

**Pull request merged**
