### PR TITLE
Fix DiaSymReader nuget version string calculation

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by davkean** [comment]
Fix how? What was the original issue?

**Comment by tmat** [comment]
The release version string was incorrect: 1.0.7-12345 instead of just 1.0.7

**Comment by tmat** [comment]
@dotnet-bot retest prtest/mac/dbg/unit32 please
// Previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_mac_dbg_unit32/3470/
// Retest reason:

**Comment by tmat** [comment]
prtest/determinism is backed up. Merging now to fix signed build asap. This change is unlikely to affect deterministic build.

**Pull request merged**
