### PR TITLE
Update EditAndContinueCapabilities.cs

### PR DESCRIPTION
**Pull request by davidwengier**
Oops!

### CODE REVIEW

**Review by tmat — APPROVED** [review]

**Comment by davidwengier** [comment]
I'm watching the clock, willing these builds to finish within 5 minutes 😛

**Comment by davidwengier** [comment]
Missed it by that much...

**Comment by jinujoseph** [comment]
@davidwengier this may need retargetting now

**Comment by davidwengier** [comment]
Retargeted to dev16.10, @jinujoseph for M2 approval.

**Pull request merged**
