### PR TITLE
Remove PackageTargetFallback that was necessary due to non-netstandard debugger packages

### PR DESCRIPTION
**Pull request by tmat**
New packages (15.0.26725-gamma) have reference assemblies in ref\netstandard1.3 and ref\net20 dirs and implementation assembly in lib/net45.

### CODE REVIEW

**Comment by tmat** [comment]
Integration tests failed with
```
System.Runtime.InteropServices.COMException (0x80010001): Call was rejected by callee. (Exception from HRESULT: 0x80010001 (RPC_E_CALL_REJECTED)).GetType().Name
```

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest please

**Comment by dpoeschl** [comment]
VS test failures are being investigated.

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_release_vs-integration_prtest please

**Comment by tmat** [comment]
test windows_debug_vs-integration_prtest  please

**Comment by tmat** [comment]
@jaredpar Looks good?

**Pull request merged**
