### PR TITLE
Merge remote-tracking branch 'upstream/future' into features/test-impact

### PR DESCRIPTION
**Pull request by drognanar**

### CODE REVIEW

**Comment by drognanar** [comment]
FYI. @dotnet/testimpact

**Comment by balajikris** [comment]
Re. test failures, ETA failed because the commit pump is down (bringing that back up now), the unit test failure seems to be unrelated. Please re-run both queues after a while.

**Comment by drognanar** [comment]
retest prtest/win/dbg/unit32 please
// previous failure: http://dotnet-ci.cloudapp.net/job/roslyn_prtest_win_dbg_unit32/7287/

**Comment by tannergooding** [comment]
@balajikris, ETA tests do not support feature branches. They will never pass.

**Comment by balajikris** [comment]
@tannergooding : Ah yes. At this exact moment, the pump was also down, So, I believed that to be the underlying reason. Observing the branch now after you mentioned. Thanks, nothing much to see then.

**Pull request merged**
