### PR TITLE
Moved VB tests to test emitted attributes vs source synthesized ones

### LINKED ISSUE #18799: Defective tests: testing source attributes vs emitted attributes
Most of compiler attribute testing is done on source symbols, instead of compiling code and actually testing the symbols emitted. These tests should be converted to test the actual output. Breaking down this big task into separate todo items:

- [x] Remove C# `CompilationUtils.GetSynthesizedAttributes()` and fix callers and its VB match.
- [x] Remove C# `EmitMetadataTestBase.ValidateDeclSecurity(Compilation)` and its VB match.
- [x] Reconsider all tests calling:
  - [x] `Symbol.GetCustomAttributesToEmit()`
  - [x] `Symbol.AddSynthesizedAttributes()`
  - [x] `Symbol.AddSynthesizedReturnTypeAttributes()`
- [x] Refactor all tests in `src\Compilers\CSharp\Test\Emit\Attributes`.
- [x] Finally remove `CSharpTestBaseBase.GetDefaultPEBuilder()` and its VB match.

It is a lot of manual labor, but should be straight forward.

/cc @AlekseyTs @jaredpar

### PR DESCRIPTION
**Pull request by OmarTawfik**
Closes #18799

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_release_vs-integration_prtest

**Comment by OmarTawfik** [comment]
cc @dotnet/roslyn-compiler

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler any reviewers? this is a test-only change.

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler any reviewers? this is a test-only change.

**Comment by OmarTawfik** [comment]
@dotnet/roslyn-compiler for review.

**Comment by jaredpar** [comment]
>             Return result

Consider adding a helper method which converts all members of an enum to a `List(Of Object())` that works for theory. This pattern is used at least twice in this PR. 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:37 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
>         Public Sub Accessors(optimizationLevel As OptimizationLevel)

Glad we're making better use of Theory's i the code. 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:136 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
>                 Dim comp = CreateCompilationWithMscorlib40(source, options:=options)

Next time prefer doing the theory conversion as a separate commit. Makse the other changes easier to review. 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:59 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by jaredpar** [comment]
>                                                                 attrs.Single(Function(a) a.AttributeClass.Name = "DebuggerBrowsableAttribute").ConstructorArguments(0).Value())

Consider using a helper to extract the constructor value as an enum. That would avoid the new casts and possible remove duplicate code. 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:112 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
>             Dim compilationRelaxationsAttrType As NamedTypeSymbol = compilerServicesNS.GetTypeMember("CompilationRelaxationsAttribute")

Before there was an implicit assertion that the attribute was a part of the System.CompilerServices namespace. It seems we lost that in the new code. 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:573 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by jaredpar** [comment]
>             Assert.Equal("RuntimeCompatibilityAttribute", attribute.AttributeClass.Name)

Before there was an implicit assertion of the full name of the attribute. Seems we've lost that here.

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:631 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
>                 CompilationUtils.AssertNoErrors(compilation)

Is there an equivalent to this assert in the new code? 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:709 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by jaredpar** [comment]
>                 CompilationUtils.AssertNoErrors(compilation)

Is there an equivalent to this assert in the new code? 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:754 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by jaredpar** [comment]
>                                          Assert.Equal(3, attributes.Length)

Why did the code move from having 2 attributes to 3? 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:799 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
> <Module: RuntimeCompatibilityAttribute>

Why was this removed?

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:789 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by jaredpar** [comment]
>                 CreateCompilationWithMscorlib40(source, options:=New VisualBasicCompilationOptions(outputKind, optimizationLevel:=OptimizationLevel.Release)),

Shouldn't this be indented one level? 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:923 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
>             Assert.Equal("DebuggableAttribute", attribute.AttributeClass.Name)

There used to be an implicit assert about the full name of this type that we've lost in the new code. 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:937 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
>         Private Sub TestDebuggableAttributeMatrix(source As String, validator As Action(Of VisualBasicCompilation), Optional includeMscorlibRef As Boolean = True, Optional compileAndVerify As Boolean = True)

Why were these methods removed?

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:941 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by jaredpar** [comment]
>                         Assert.Equal(0, attributes.Length)

Assert.Empty? 

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:982 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by jaredpar** [comment]
done with review pass 1

**Comment by OmarTawfik** [comment]
>                 CompilationUtils.AssertNoErrors(compilation)

CompileAndVerify() will fail if there are any errors

---
In reply to: [384106614](https://github.com/dotnet/roslyn/pull/25032#issuecomment-384106614) [](ancestors = 384106614)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:709 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by OmarTawfik** [comment]
>                 CompilationUtils.AssertNoErrors(compilation)

CompileAndVerify() will fail if there are any errors

---
In reply to: [384107229](https://github.com/dotnet/roslyn/pull/25032#issuecomment-384107229) [](ancestors = 384107229)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:754 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by OmarTawfik** [comment]
>         Private Sub TestDebuggableAttributeMatrix(source As String, validator As Action(Of VisualBasicCompilation), Optional includeMscorlibRef As Boolean = True, Optional compileAndVerify As Boolean = True)

Replaced by the <Theory>

---
In reply to: [384108356](https://github.com/dotnet/roslyn/pull/25032#issuecomment-384108356) [](ancestors = 384108356)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:941 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by OmarTawfik** [comment]
> <Module: RuntimeCompatibilityAttribute>

error BC30549: Attribute 'RuntimeCompatibilityAttribute' cannot be applied to a module.
Check the test: RuntimeCompatibilityAttributeCannotBeAppliedToModule

---
In reply to: [384107586](https://github.com/dotnet/roslyn/pull/25032#issuecomment-384107586) [](ancestors = 384107586)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:789 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = True)

**Comment by OmarTawfik** [comment]
>                                          Assert.Equal(3, attributes.Length)

Because this is testing the compiled assembly. The compiler also adds `Debuggable`.

---
In reply to: [384107428](https://github.com/dotnet/roslyn/pull/25032#issuecomment-384107428) [](ancestors = 384107428)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:799 in 4fc6afa. [](commit_id = 4fc6afa1484a4c9857aecb0044d7861594a69e54, deletion_comment = False)

**Comment by OmarTawfik** [comment]
@jaredpar comments addressed.
Had to rebase because of the `15.8` project system changes :( so comments might get moved a bit.

**Comment by jaredpar** [comment]
>             Return result

At the least I think this could benefit from having an API that returned a typed collection of Enum values from an enum. 

---
In reply to: [387245899](https://github.com/dotnet/roslyn/pull/25032#issuecomment-387245899) [](ancestors = 387245899,384095345)

---
Refers to: src/Compilers/VisualBasic/Test/Emit/Attributes/AttributeTests_Synthesized.vb:37 in 6788668. [](commit_id = 6788668ca9f84e4bcab59b56e2ca99b9a395e723, deletion_comment = False)

**Comment by OmarTawfik** [comment]
@dotnet-bot test windows_debug_unit64_prtest

**Comment by OmarTawfik** [comment]
@jaredpar for ask mode approval.

**Comment by jaredpar** [comment]
approved

**Comment by jaredpar** [comment]
Note: this is test only hence it doesn't need approval.

**Pull request merged**
