### PR TITLE
Avoid unnecessary tail increment in collection expressions codegen

### PR DESCRIPTION
**Pull request by DoctorKrolic**
Fixes: https://github.com/dotnet/roslyn/issues/74875

### CODE REVIEW

**Review by jaredpar — DISMISSED** [review]
This doesn't meet the bar for 17.12. Putting a hold on this until main is targeting 17.13

**Comment by DoctorKrolic** [comment]
What kind of bar are we talking about here? Because I was thinking the opposite way: since the logic change is pretty much trivial this is a low risk change & it will get less review feedback to address, thus, I thought, it is gonna be a more suitable PR for a near-the-release time point

**Comment by 333fred** [comment]
> What kind of bar are we talking about here? Because I was thinking the opposite way: since the logic change is pretty much trivial this is a low risk change & it will get less review feedback to address, thus, I thought, it is gonna be a more suitable PR for a near-the-release time point

A bugfix only bar.

**Comment by jaredpar** [comment]
> since the logic change is pretty much trivial this is a low risk change

Unfortunately optimization changes, even trivially ones, are not considered low risk. I understand that it can seem that way but in reality optimization changes are our most frequent source of regressions in the compiler. We've had a lot more luck with optimizations in collection expressions vs. other parts of the compiler but even so the bar for optimizations in general goes up faster than other bug fixes.

**Comment by hez2010** [comment]
> in reality optimization changes

Actually the JIT is smart enough to get rid of the unnecessary increment here: https://godbolt.org/z/63ahWzrar
So the optimization in this PR actually didn't optimize anything.

**Comment by DoctorKrolic** [comment]
> So the optimization in this PR actually didn't optimize anything

IL size also matters. Though a lot less of course, but still

**Comment by DoctorKrolic** [comment]
@jaredpar I've seen [this PR](https://github.com/dotnet/roslyn/pull/75263). Does it mean, that `main` is `17.13` now?

**Comment by jaredpar** [comment]
Yes main is 17.13 now.

**Comment by DoctorKrolic** [comment]
@RikkiGibson @cston PTAL

**Comment by DoctorKrolic** [comment]
@RikkiGibson @cston PTAL

**Pull request closed without merging**
