### PR TITLE
Disabling flaky tests failed in last 24hr.

### PR DESCRIPTION
**Pull request by VSadov**
Disabled NavigateTo

### CODE REVIEW

**Comment by VSadov** [comment]
more is coming

**Comment by sharwell** [comment]
@VSadov There are no failures of Navigate To in the build history for either the Debug or Release integration test builds.

**Comment by VSadov** [comment]
@sharwell - there is statistics showing that they failed 4 times in the last 24 hours and I am being asked why the tests are still running. 
(which was a surprise, since I have disabled them once already)

@jaredpar - does the failure report include queues other than integration ones?

**Comment by sharwell** [comment]
@VSadov I see failures, but none on the master branch where I applied a fix. The failures appear restricted to feature branch builds.

**Comment by jaredpar** [comment]
@sharwell good catch.  The query I was using didn't consider branch name.  When I filter to only master get this

```
FullName	count_
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpErrorListNetCore.ErrorsDuringMethodBodyEditing	15
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSquigglesNetCore.VerifySemanticErrorSquiggles	11
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSquigglesNetCore.VerifySyntaxErrorSquiggles	1
Roslyn.VisualStudio.IntegrationTests.CSharp.CSharpSquigglesDesktop.VerifySyntaxErrorSquiggles	1
```

**Comment by sharwell** [comment]
@jaredpar Thanks! I was sensitive to this since I spent 3 days fixing some of them 😄

**Comment by jaredpar** [comment]
@sharwell 

> I was sensitive to this since I spent 3 days fixing some of them

The work is much appreciated.  

Only had Kusto for a week or so now.  Still working out some of the kinks in how to accurately look at the data.

**Comment by VSadov** [comment]
@sharwell - will do. 

I am the "Test Disabler in Chief" now and we tend to err on the side "it might still be flaky" side. 
Because of all the churn it is hard to keep it up with all the flakiness coming and leaving the system.

**Pull request merged**
