### PR TITLE
made WorkCoordinator test to use its own MEF containers that are not shared with others

### PR DESCRIPTION
**Pull request by heejaechang**
it looks like at some point of a time, our unit test MEF code has changed and made CreateExportProviderWithCSharpAndVisualBasic to not create an isolated MEF container but share some parts of MEF with others.

this change will make the method above to create isolated MEF container as it used to be.

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani @srivatsn @jaredpar can you take a look? thank you

**Comment by heejaechang** [comment]
fixes https://github.com/dotnet/roslyn/issues/5915

**Comment by heejaechang** [comment]
ping?

**Comment by heejaechang** [comment]
can I get some sign off for this, I would like to check in

**Comment by jaredpar** [comment]
:+1:

**Pull request merged**
