### PR TITLE
Don't fade code out when suggesting the 'Qualify with 'this.'' lightbulb

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn/issues/10223

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @dotnet/roslyn-ide @dpoeschl

**Comment by CyrusNajmabadi** [comment]
@dpoeschl can you take a looksie?

**Comment by jmarolf** [comment]
Can we write tests for this?  Seems like we could check for the uncessesary tags?

**Comment by CyrusNajmabadi** [comment]
That's a good suggestion JMarolf.  I think we probably should update our test harness to make it so that tests can decoratively state what their dianostic spans are, and what treatment they get .   Maybe @dpoeschl can do that?

**Pull request merged**
