### PR TITLE
Move FunctionIdOptions to EditorFeatures

### PR DESCRIPTION
**Pull request by tmat**
Remove PerformanceFunctionIdOptionsProvider - IOptionProvider is only needed for solution options.

### CODE REVIEW

**Comment by JoeRobich** [comment]
Why is EditorFeatures the right layer for this?

**Comment by tmat** [comment]
@JoeRobich Global options are client options (i.e. not available in OOP). Workspaces and Features are server (OOP) components. EditorFeatures and VS are client components. EditorFeastures is x-plat, VS is not.

**Comment by JoeRobich** [comment]
> @JoeRobich Global options are client options (i.e. not available in OOP). Workspaces and Features are server (OOP) components. EditorFeatures and VS are client components. EditorFeastures is x-plat, VS is not. Makes sense?

Thanks for that description of our layering. I feel like little gaps get filed in the more I learn.

**Comment by tmat** [comment]
@JoeRobich No problem. It's been a bit fuzzy historically, but with the latest refactorings the separation is hopefully more clear now.

**Review by JoeRobich — APPROVED** [review]

**Pull request merged**
