### PR TITLE
Spell checking fixes.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This is a port of https://github.com/dotnet/roslyn/pull/14448 into RC

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @MattGertz @ManishJayaswal @Pilchie

**Comment by MattGertz** [comment]
Approved pending the usual.

**Comment by CyrusNajmabadi** [comment]
test windows_eta_open_prtest please

**Comment by CyrusNajmabadi** [comment]
test windows_eta_open_prtest  please

**Pull request merged**
