### PR TITLE
Perform the initial tagging for a file as fast as possible so that that the file appears 'complete' immediately after opening.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
This PR is against master so we can test perf.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
test internal-perf please

**Comment by CyrusNajmabadi** [comment]
test test internal-perf please

**Comment by CyrusNajmabadi** [comment]
test internal-perf please

**Comment by CyrusNajmabadi** [comment]
@rchande this is the PR against master so that we can get perf tests running.

**Comment by CyrusNajmabadi** [comment]
retest this please

**Comment by rchande** [comment]
test internal-perf please

**Pull request closed without merging**
