### PR TITLE
Remove dependency on Microsoft.VisualStudio.Text.UI.Wpf

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Microsoft.CodeAnalysis.VisualBasic.EditorFeatures was depending on Microsoft.VisualStudio.Text.UI.Wpf but there are now new APIs to fix this problem.

Fixes dotnet/roslyn#23182

### CODE REVIEW

**Comment by jinujoseph** [comment]
@Pilchie  for ask mode approval

**Comment by Pilchie** [comment]
Approved for 15.7 - thanks

**Comment by sharwell** [comment]
@jasonmalinowski Why is this only for the vs-deps branch?

**Comment by jasonmalinowski** [comment]
@sharwell The ITextViewConnectionListener API is new and is only in our packages in -vs-deps. Given we're almost nearly mandating 15.6 Preview 4 we could do that merge back, but that's an independent decision.

**Pull request merged**
