### PR TITLE
Suppress supports warnings

### PR DESCRIPTION
**Pull request by jasonmalinowski**
Remove all the supports sections that are causing warnings since we're using them in projects that don't have Microsoft.NETCore.Targets package references. Some of these projects (the first commit) already have runtime sections and so it's silly to even the supports in the first place. The others (the second project) _should_ have them, but I'm unable to sort out through the endless stream of errors if I try adding the package references. We should sort through those, but until then we should just not have sections that do nothing other than create errors.

*Review:* @tmat, @agocke, @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by TyOverby** [comment]
LGTM

**Comment by jasonmalinowski** [comment]
So since many people don't fully understand what supports clauses are, here's the background behind this change:

First, consider the "runtimes" section. When NuGet restores, it produces two different lists of items: the items that get passed to the compiler, and the items that get copied into the output directory. Although there's obviously a relationship between them, you can think of them as completely unrelated lists of the sake of treating NuGet as a black box. The first list can be produced as long as you know just your target framework; the latter can be produced only if you know your target framework _and_ the OS/chip you're targeting (Yes, in simple cases they're the same, but to actually guarantee correctness, you need to know the OS/chip, especially for CoreCLR packages.) For "runnable" projects like executables, you need a runtimes section. That means NuGet will write out the information in the lock file for what needs to be deployed for each of those OSes. If any of your packages _don't_ support one of those runtimes, it'll fail during the restore; this enforces that you actually run where you think you run.

For class libraries, you _don't_ have a runtimes section, because you're not actually running your class library anywhere. You only have a frameworks section, since all you need is the surface area you're compiling against. This is great (since it means you can run anywhere your dependencies ultimately can), but you want some guidance to ensure your packages actually _will_ work. The last thing you'd want is a class library that you thought ran on UWP, but once you try it, you discover you took some dependency on some package that can't actually run there. This is what the supports clause is for. It's optional, and it lets you gives a list of supports identifiers where you think you run. A supports identifier maps to framework/runtime pairs, and internally NuGet just does a "pretend restore" for each of those to see if things would work and your dependencies all exist. You don't have to use these, but it ensures you don't create a portable class library that isn't very portable. When you create a project.json portable class library, the checkboxes you check in the dialog just map to entries in the supports section.

My first commit in the PR simply removes the supports sections in our executable projects; they already have a runtimes section saying where they actually run, and NuGet already validates that, so there's no harm there. The second commit is removing the supports sections that really should be there -- those are simple portable class libraries that we want to ensure run where we think they run. The problem is the NuGet doesn't know _per se_ what the entries in the supports clauses mean: it looks them up in referenced packages. The .NET packages define them in Microsoft.NETCore.Targets, but we don't reference that. As a result, we just get a bunch of warnings saying NuGet can't figure them out. I tried adding that package, but then got a bunch of version mismatches which I couldn't make heads or tails of. But until we fix that (and I'll file a bug for it), we mind as well remove this just so you don't get warnings.

**Comment by jasonmalinowski** [comment]
Any takers for the review other than @TyOverby?

**Comment by Pilchie** [comment]
Hmm, I looked at this earlier and meant to give it a :+1:

**Pull request merged**
