### PR TITLE
Reduce number of stack frames to prevent StackOverflow until we have …

### PR DESCRIPTION
**Pull request by 333fred**
…the ability to capture dumps.

Test-only change. Filed https://github.com/dotnet/roslyn/issues/25606 to track restoring this to original counts.

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@333fred Should this be against dev15.7.x?

**Comment by jaredpar** [comment]
Have we seen the failure there yet?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jasonmalinowski** [comment]
@jaredpar @333fred looks like yes, we have a bunch of examples in #25539, including the one you looked at to find the issue, I think. :smile:

**Comment by 333fred** [comment]
@jasonmalinowski @jaredpar retargeted.

**Comment by 333fred** [comment]
This is an emit-only test change, integration test failures are unrelated.

**Comment by 333fred** [comment]
@jaredpar approved offline, but is on mobile so he can't add the tag.

**Pull request merged**
