### PR TITLE
Fixing the VsixVersion to be 42.42.42.42 for unofficial builds.

### PR DESCRIPTION
**Pull request by tannergooding**
FYI. @jasonmalinowski, @Pilchie, @CyrusNajmabadi, @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by tannergooding** [comment]
test windows_eta_open_prtest please

**Comment by Pilchie** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
I'm just going to merge this in.  Thanks @tannergooding

**Comment by jasonmalinowski** [comment]
:+1:

**Pull request merged**
