### PR TITLE
Merge thread starvation fix into master

### PR DESCRIPTION
**Pull request by vslsnap**
**Customer scenario**

Building a large XAML project with many files, you might experience a hang after a build as the IDE re-reads many modified files on disk. In just the right set of conditions, this might cause thread starvation.

**Bugs this fixes:** https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems?id=169649&_a=edit, others

**Workarounds, if any**: none.

**Risk**: low. We're just changing a flag that is passed to FileStream to work around the underlying issue. This is the recommendation from the framework team and has been their previous recommendation.

**Performance impact**: This improves performance in this certain case. Regular codepaths are unaffected.

**Is this a regression from a previous update?** No.

**Root cause analysis:** There is a bug in the .NET framework which means that certain asynchronous file reads are handled less efficiently than they should be. If you have many threads doing reads at once, this can cause thread starvation which will cause a hang as soon as any UI thread element needs to wait for something on a background thread.

**How was the bug found?** Multiple customer pieces of feedback.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by jasonmalinowski** [comment]
cc @Pilchie @MattGertz on this. This is the fix we're working on for the other update, but want it in dev15-rc3 or something else as well.

**Comment by MattGertz** [comment]
@jasonmalinowski Too late today; ping me again tomorrow after reviews & tests.  But I agree with it.

**Comment by Pilchie** [comment]
@MattGertz @jasonmalinowski This didn't happen today - do you want to try and take it tomorrow, or wait for RTW?

**Comment by jasonmalinowski** [comment]
And as far as testing is concerned, we've already given a customer privates with this fix, and they've confirmed it addressed their scenario.

**Comment by MattGertz** [comment]
RTW, please.

**Comment by jasonmalinowski** [comment]
@Pilchie We'll still need to take this through shiproom. Are you catching this in your flow of bugs?

**Pull request merged**
