### PR TITLE
Remove all shared projects from Roslyn.sln

### PR DESCRIPTION
**Pull request by sharwell**
This change reduces the amount of time it takes to open Roslyn.sln and run a unit test.

Before: 5:09 mins
After: 2:18 mins

Changes to the developer experience:

* The files now behave like linked files. Creating, renaming, deleting, or moving a file that lives in one of the shared projects must be done either in Folder View in Solution Explorer, or by going to Windows Explorer.
* Refactorings that create, rename, or move files cannot be used if they affect files in shared projects.

We will certainly work with the project system team to resolve the underlying performance barriers and allow us to return to a more desirable working state as soon as possible.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
interesting, why are the projects so expensive?  is that on us?  project system?  something else?  Can we use this data to drive some appropriate perf improvements?  I ask given the divisional efforts in perf right now.  This would be really good information to drive very high value changes :)

**Comment by CyrusNajmabadi** [comment]
Tagging @tmeschter

**Comment by mavasani** [comment]
@sharwell Can we create a separate solution, similar to Compilers.sln but for just CodeStyle/Workspaces/Features + these shared projects, so that anyone making the changes that are now unsupported in Roslyn.sln can still work off that solution?

**Comment by jasonmalinowski** [comment]
What bug is tracking the performance investigation here? The only thing keeping my sanity working in some of those projects is the shared projects, so this will be a real regression in experience here...

**Comment by sharwell** [comment]
> so that anyone making the changes that are now unsupported in Roslyn.sln can still work off that solution?

I'm not sure that's going to work since I removed the `Label="Shared"` from the imports.

**Comment by sharwell** [comment]
> What bug is tracking the performance investigation here? The only thing keeping my sanity working in some of those projects is the shared projects, so this will be a real regression in experience here...

I'm meeting with project system this evening to discuss tracking this work.

**Comment by jaredpar** [comment]
Can you make a similar change to Compilers.sln as you did to Roslyn.sln?

**Comment by sharwell** [comment]
@jaredpar Yes, I will send a follow-up pull request for that.

**Comment by sharwell** [comment]
I am not planning to move forward with this change. Another workaround is available if you are experiencing problems.

During validation of this change, I found that the Node.js Development Tools may be negatively interacting with the Test Explorer and project system. Uninstalling this workload dramatically improved the Roslyn scenario (exceeding even the performance numbers observed by removing shared projects) without requiring a change to the way we structure our solution. I’ll be following up with that team independently to find a solution for users who wish to install this workload.

image

**Pull request closed without merging**
