### PR TITLE
Add handling for VB With statement in control flow graph.

### PR DESCRIPTION
**Pull request by AlekseyTs**

### CODE REVIEW

**Review by jaredpar — APPROVED** [review]

**Comment by 333fred** [comment]
I don't see any tests for implicit receivers for control flow inside the with statement (ensuring that the implicit receiver is spilled in the correct order). I think these are probably important enough scenarios to warrant a test.

**Comment by AlekseyTs** [comment]
> I don't see any tests for implicit receivers for control flow inside the with statement (ensuring that the implicit receiver is spilled in the correct order), or implicit receivers on the right side of an expression. I think these are probably important enough scenarios to warrant a test.

I do not believe there is anything out of the ordinary in these scenarios by comparison to any other expressions used in place of a receiver. However, I will add tests like that in one of the next PRs

---
In reply to: [393705842](https://github.com/dotnet/roslyn/pull/27303#issuecomment-393705842) [](ancestors = 393705842)

**Comment by AlekseyTs** [comment]
@mavasani, @dotnet/analyzer-ioperation Please review

**Review by mavasani — APPROVED** [review]

**Review by jcouv — APPROVED** [review]
LGTM Thanks

**Review by 333fred — APPROVED** [review]
LGTM (iteration 1)

**Pull request merged**
