### PR TITLE
AnalyzerDriver - Replace invocations of DisposableWaitAsync with explicit WaitAsync/Release of underlying SemaphoreSlim gate

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by davkean** [comment]
Mac's a back up now.

retest prtest/mac/dbg/unit32 please

**Comment by mavasani** [comment]
Not attempting to resurrect this now - will do so in future if we receive user requests.

**Comment by CyrusNajmabadi** [comment]
Why not use DisposableWaitAsync?

On Dec 16, 2015 12:35 PM, Manish Vasani <notifications@github.com> wrote:

Not attempting to resurrect this now - will do so in future if we receive user requests.

-

**Comment by mavasani** [comment]
I actually did the change to use DisposableWaitAsync but it caused a regression in perf tests and Kevin reverted it - we were allocating a large number of SemaphoreDisposer objects as it was in a hot code path. We can probably use a pool instead. It was just not that high priority work to invest more cycles on it right now.

**Pull request closed without merging**
