### PR TITLE
Disable Navigate-To filtering of previous results.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes: https://github.com/dotnet/roslyn/issues/23051
Fixes: https://github.com/dotnet/roslyn/issues/40828

This filtering is broken *by design*.  Here's the fundamental issue the previous 'optimization' failed to recognize:

NavigateTo results for a string `S1S2...Sn` are not a subset of the results for a string `S1S2...Sn-1`.  A very simple example of htat are 'fuzzy' matches.  Fuzzy matches can produce *more* results as you add more data (since you're now close enough to consider the hits fuzzily-close.  Similarly, everything we do matching-wise that uses edit-distances is very length dependent.  If the lengths are too far apart, we don't even bother (for perf reasons).  

This could lead to a really bad experience where, depending on your typing speed, you might end up with no results in nav-to *and then stay there as you continued to add more text*.  

-- 

Another case this hits is typing out (manually) `Foo.Bar`.  As you type `Foo` it's doing a normal symbol search for variables with that name.  but whne you add the `.Bar` it wants to find symbols called `.Bar` off of symbols called `Foo`.  If we keep filtering the list down, this can't work.

### CODE REVIEW

**Comment by jinujoseph** [comment]
cc @dibarbet

**Comment by davkean** [comment]
@CyrusNajmabadi Does this also fix: https://github.com/dotnet/roslyn/issues/40828?

**Comment by CyrusNajmabadi** [comment]
Yes, that's another good case @davkean will update the OP with that.

**Comment by CyrusNajmabadi** [comment]
>  I'm just curious, how much slower is it actually?

I couldn't perceive any problems.  And it's faster than what i currently have to do, which is realize that the results are busted, cut the string, wait for it to reach no results, paste back in and get the real search for the real results.  :)

**Pull request merged**
