### PR TITLE
Avoid capturing the solution in Quick Info

### PR DESCRIPTION
**Pull request by sharwell**
Fixes 10% (200+ MiB) of the working set that led to problems in [AB#1270826](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1270826).

This change is submitted to master (16.10), but the parent commit is release/16.9 to allow retargeting if this is approved for 16.9.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Could you clarify how this works overall?  Won't this just be GC'ed once QI goes away?

**Comment by sharwell** [comment]
The completion control keeps a [strong reference](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FLanguage%2FImpl%2FIntellisense%2FCompletionUI%2FDefaultCompletionControl.xaml.cs&version=GBmain&line=40&lineEnd=41&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) to its popup, and only [sets the content](https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FLanguage%2FImpl%2FIntellisense%2FCompletionUI%2FDefaultCompletionControl.xaml.cs&version=GBmain&line=507&lineEnd=508&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) right before showing it. For each text view you have open, a strong reference is held to the last popup content until the next time the tooltip shows.

**Comment by sharwell** [comment]
@CyrusNajmabadi editor is also going to look at resolving this, but it doesn't hurt to fix on our side since we didn't really need the reference anyway.

**Comment by CyrusNajmabadi** [comment]
> For each text view you have open, a strong reference is held to the last popup content until the next time the tooltip shows.

Ickkk. That also seems bad. Is that on or end or the editor?

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by sharwell** [comment]
Here's the editor-side fix for this, which should be included in 16.9 before release:
https://devdiv.visualstudio.com/DevDiv/_git/VS-Platform/pullrequest/300657

Since this change is still an improvement, I'll include it for 16.10.

**Pull request merged**
