### PR TITLE
changed preview warning tagger name from "Warning" to "Preview Warning" ...

### PR DESCRIPTION
**Pull request by heejaechang**
...to reduce confusion between compiler warning tag.

### CODE REVIEW

**Comment by heejaechang** [comment]
@shyamnamboodiripad @srivatsn @mavasani @tmeschter @jmarolf can you take a look? quite simple change.

**Comment by shyamnamboodiripad** [comment]
I am assuming this is not a user facing string (i.e. won't show up in any UI).

Should we also change the ```WarningTag.TagId``` that is used when MEF exporting the tag definition? It is currently set to ```"RoslynWarningTag"``` - maybe change to ```RoslynPreviewWarningTag```

Also why don't we have special taggers for other severities (error, info) in the preview pane?

**Comment by shyamnamboodiripad** [comment]
:+1: modulo my above comments

**Comment by heejaechang** [comment]
This has nothing to do with diagnostic warning. U can add warning annotation to a tree that will show warning title in preview windows.

Sent from my Windows Phone
________________________________

**Comment by shyamnamboodiripad** [comment]
Ah got it this is the conflict warning adornment that we show when some change has potential to change semantics. Ignore my question above.

I think it still makes sense to update the TagId to match the DisplayName as I mentioned above.

Also if we could put something in the name to distinguish from diagnostic warning that may be good too. PreviewConflictWarningTag?

**Comment by heejaechang** [comment]
sure

**Comment by tmeschter** [comment]
:+1:

**Pull request merged**
