### PR TITLE
Update NamingStyle.cs

### PR DESCRIPTION
**Pull request by gewarren**
Corrected resource string for error message for CheckAllLower.

### CODE REVIEW

**Comment by jcouv** [comment]
@sharwell @dpoeschl Anything holding back merge?

**Comment by sharwell** [comment]
retest ubuntu_16_mono_debug_prtest please

**Comment by sharwell** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by sharwell** [comment]
@jinujoseph for approval to merge

**Comment by jinujoseph** [comment]
Approved to merge for 15.8.Preview5

**Comment by sharwell** [comment]
@gewarren Thanks for contributing this! 😄 Due to the unexpected delay, we are reviewing the ways we track work from Microsoft employees who are not primary developers in dotnet/roslyn (they fell in a gap between "Community" and "Non-community"), and hope to avoid similar situations in the future.

**Pull request merged**
