### PR TITLE
Switch to a 2.0 version of our stage 1 bootstrap compiler

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by agocke** [comment]
test this please

**Comment by agocke** [comment]
+ @jaredpar @dotnet/roslyn-compiler

**Comment by agocke** [comment]
ping @jaredpar @dotnet/roslyn-compiler

**Comment by agocke** [comment]
Also, I guess @dotnet/roslyn for anyone else who wants to use new features in Roslyn.

**Comment by TyOverby** [comment]
LGTM

**Comment by jaredpar** [comment]
What about the Mac / Linux toolsets?  Can't switch to C# 7.0 till these are fixed too.

**Pull request merged**
