### PR TITLE
Update version information

### PR DESCRIPTION
**Pull request by jasonmalinowski**
*Review:* @dotnet/roslyn-infrastructure

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please. I don't think a readme change will break compiler unit tests, and I don't see any logs here to make it clear what happened.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_debug_unit32_prtest please. I don't think a readme change will break compiler unit tests, and I don't see any logs here to make it clear what happened.

**Comment by jasonmalinowski** [comment]
@dotnet-bot test windows_debug_unit32_prtest please

I don't think a readme change will break compiler unit tests, and I don't see any logs here to make it clear what happened.

**Comment by tannergooding** [comment]
test windows_debug_unit32_prtest please

**Pull request merged**
