### PR TITLE
Correct quote escaping mechanism in cibuild.cmd !@#&^(%$*)$(%_)[]{}.,/\%0A

### PR DESCRIPTION
**Pull request by TyOverby**
closes https://github.com/dotnet/roslyn/issues/14480

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet/roslyn-infrastructure @jaredpar

**Comment by TyOverby** [comment]
@333fred Your change has been reverted.

**Comment by TyOverby** [comment]
@333fred Apparently we were just escaping the " characters incorrectly...  Switching to the proper escape method fixes this without any of the ugly hacks.

**Comment by TyOverby** [comment]
cc: @brettfo

**Comment by TyOverby** [comment]
@dotnet-bot test windows_eta_open_prtest please

**Comment by TyOverby** [comment]
@333fred @brettfo @dotnet/roslyn-infrastructure @jaredpar

**Comment by TyOverby** [comment]
This PR is now 2 weeks old.  I just need one more review for this 2 line diff.
@brettfo @dotnet/roslyn-infrastructure @jaredpar

**Comment by tannergooding** [comment]
👍

**Pull request merged**
