### PR TITLE
Add support for unsafe local functions in IDE0062 code fix

### PR DESCRIPTION
**Pull request by meziantou**
Fix https://github.com/dotnet/roslyn/issues/59286

### CODE REVIEW

**Review by CyrusNajmabadi — APPROVED** [review]

**Review by Youssef1313 — APPROVED** [review]

**Review by sharwell — APPROVED** [review]

**Comment by DoctorKrolic** [comment]
Tagging @CyrusNajmabadi as an assignee of this PR: note, that auto merge is not gonna be performed, because of exception during integration tests. Needs manual merge

**Comment by meziantou** [comment]
@sharwell The CI fails, so the PR cannot be merged. The failure doesn't seem related to my changes. Is there something I can do?

**Comment by Youssef1313** [comment]
@jinujoseph FYI auto merge got disabled here.

**Pull request merged**
