### PR TITLE
Don't require services from the VS layer that aren't present on VS Mac

### PR DESCRIPTION
**Pull request by davidwengier**
Fixes Pull Members Up and Move Static Members to not require UI options services that are only implemented in the VS layer, and don't exist in VS Mac (yet?)

Fixes [AB#1449154](https://devdiv.visualstudio.com/0bdbc590-a062-4c3f-b0f6-9383f67865ee/_workitems/edit/1449154)

/cc @sandyarmstrong @KirillOsenkov

### CODE REVIEW

**Comment by sandyarmstrong** [comment]
Thank you! And yes, it is a "yet". There are a few missing services/dialogs that we will implement as time allows.

**Review by sandyarmstrong — APPROVED** [review]

**Comment by sharwell** [comment]
❓ Is it possible to instead use the approach from https://github.com/dotnet/roslyn/pull/49127 (provided a default implementation of the service in the same layer where the interface is defined, and provide a host-specific override in a higher layer)?

**Comment by davidwengier** [comment]
Wouldn't that mean VS Mac would use the default implementation, and therefore offer the action?

That is not desirable. We don't want the action offered until VS Mac provides its implementation.

**Comment by sharwell** [comment]
> Wouldn't that mean VS Mac would use the default implementation, and therefore offer the action?

Not if the default implementation is implemented in such a way that it says the feature is not available.

**Review by sharwell — APPROVED** [review]

**Comment by sharwell** [comment]
It might be nice in the future to have an analyzer that flags uses of `GetRequiredService` on interfaces that don't have an implementation defined in the same layer as the interface.

**Comment by davidwengier** [comment]
> Not if the default implementation is implemented in such a way that it says the feature is not available.

ahh yes, makes sense. I did think about whether we should establish a pattern for these types of services to have a `bool IsEnabled` property or something, but I like the idea of the analyzer better, even if it was only specifically for calling `GetRequiredService` for things that are implemented in the VS layer.

**Pull request merged**
