### PR TITLE
Change version to 1.3.1

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by cston** [comment]
@dotnet/roslyn-infrastructure please review.
@mattgertz for approval.

**Comment by jinujoseph** [comment]
:+1:

**Comment by cston** [comment]
Updated `bindingRedirects` to fix build failure with bootstrap compiler. (Thanks @tannergooding.)

**Comment by cston** [comment]
@tannergooding please review.

**Comment by tannergooding** [comment]
LGTM

**Pull request merged**
