### PR TITLE
crash right away when we don't get mandatory analyzers from VS.

### PR DESCRIPTION
**Pull request by heejaechang**
if we let this one pass, roslyn will crash at some point since our code assumes that compiler analyzer always exist. and at that point, it is too late to figure out why those are missing.

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-analysis @mavasani @srivatsn @panopticoncentral can you take a look?

**Comment by panopticoncentral** [comment]
:+1:

**Comment by srivatsn** [comment]
👍

**Comment by heejaechang** [comment]
test vsi please

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest  please

known Option page test failure

**Comment by heejaechang** [comment]
retest windows_vsi_p3_open_prtest please

Option test failed again.

**Pull request merged**
