### PR TITLE
Fix usage of wrong resource manager and fix loc issue

### LINKED ISSUE #55005: IDE0150 description is missing in the error list
**Version Used**: 17.0.0-p2.0

image

IDE0150 shows up for `is object` checks:

image

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #55005

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@Youssef1313 build failures seem legit.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
Thanks @Youssef1313

**Comment by Youssef1313** [comment]
@CyrusNajmabadi Auto merge was disabled due to pushing a commit.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
