### PR TITLE
fixed a bug where free after shutdown is not properly handled. this i…

### PR DESCRIPTION
**Pull request by heejaechang**
…s expected behavior. looks like got messed up while addressing PR feedbacks

### Customer scenario

Users shutdown VS after using C#/Vb and VS crashes.

### Bugs this fixes

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/572016

### Workarounds, if any

one can set hidden reg key to turn off connection pool but it requires special reg key

### Risk

I don't see any risk

### Performance impact

No perf impact

### Is this a regression from a previous update?

Yes. Connection Pool is newly added to 15.7 to improve perf.

### Root cause analysis

Free being called for a connection after OOP is asked to shutdown is expected since connection is given out to async workers and we can't control their lifetime. this is common to any pool. existing code didn't handle this properly.

### How was the bug found?

Testing

### CODE REVIEW

**Comment by heejaechang** [comment]
@dotnet/roslyn-ide can I get some code review? @jinujoseph

**Comment by jinujoseph** [comment]
@Pilchie  for ask mode approval for 15.7.p2

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest  please

**Comment by heejaechang** [comment]
retest ubuntu_16_mono_debug_prtest please

**Pull request merged**
