### PR TITLE
Fix gold-bar when an analyzer starts up, but not all references are restored/found

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Found while dogfooding.  I didn't take into account that even built-in types like System.String might come back as an error-type during VSLoading.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@heejaechang can you take a look?  This fixes what looks like a crash to the user.

**Comment by CyrusNajmabadi** [comment]
@jinujoseph can this get eyes.  THis will appear as a crash/product-instability from the user's perspective.

**Comment by mavasani** [comment]
@CyrusNajmabadi can we get some unit tests? I think compiler team has some test-only APIs to make compilation with missing well known/special types, which we can probably re-use or re-purpose. @jcouv is that something that we can do?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi can we get some unit tests? I think compiler team has some test-only APIs to make compilation with missing well known/special types, which we can probably re-use or re-purpose. @jcouv is that something that we can do?

Let me see what i can do.  The problem is more about this going through our analyzer-harness, which itself doesn't have a great way of exposing this...

Although, come to think of it, i think we can use the Workspace-Xml literals and *not* ask for well-known assemblies to be added.  That might be sufficient.

**Comment by CyrusNajmabadi** [comment]
@mavasani @sharwell  This can be merged in now.  Thanks!

**Comment by mavasani** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by mavasani** [comment]
retest windows_release_vs-integration_prtest please

**Comment by CyrusNajmabadi** [comment]
@mavasani can you merge in?

**Comment by mavasani** [comment]
@CyrusNajmabadi How often or likely is this issue?

**Comment by CyrusNajmabadi** [comment]
Fairly likely, esp. the larger the solution.  Roslyn will load the solution and slowly start hydrating the projects.  If, during that time, the analyzer infrastructure runs, then you get this issue.

--

Aside: it's unclear to me why we run analysis before we've completed hyrating the solution.  At the very least, we should wait until the project is done before doing stuff.

There are multiple reasons for that beyond just avoiding this sort of crash:

1. The analysis results are very normally useless during this timeframe.  i.e. they're the results of analysis on incomplete information, so they will very often squiggle/fade or otherwise mess up completely normal code.
2. even if the analysis is correct, users can't do anything about it. If you try to invoke a code-action to apply it, it will never succeed.  That's because the final .TryApplyChanges call will just bail since the solutoin has since moved forward since we're populating it in the BG.

Effectively, doing this analysis early doesn't actually help anyone, and in several ways it actively hurts.  That said, regardless of that problem, this fix is appropriate and should likely go into P2.  :)

**Comment by mavasani** [comment]
@CyrusNajmabadi Thanks. I have retargeted the PR. @jinujoseph, can you please approve?

@heejaechang for suggestions in https://github.com/dotnet/roslyn/pull/30944#issuecomment-437496438

**Comment by mavasani** [comment]
retest windows_release_vs-integration_prtest  please

**Comment by Neme12** [comment]
> How often or likely is this issue?

I'm just speaking from personal experience but I hit this almost every time when doing F5 from Roslyn.

**Comment by Neme12** [comment]
@CyrusNajmabadi 

> The analysis results are very normally useless during this timeframe. i.e. they're the results of analysis on incomplete information, so they will very often squiggle/fade or otherwise mess up completely normal code.

This happens to me very often when I load the Roslyn solution with a file open. It will get red squiggles all over the place that eventually disappear.

**Comment by CyrusNajmabadi** [comment]
@heejaechange @mavasani ^ Additional anecdata points.  Is there telemetry we can collect here that shows how often we collect unactionable diagnostics?

**Comment by Neme12** [comment]
@heejaechang

**Pull request merged**
