### PR TITLE
Use proper lowering for language version

### PR DESCRIPTION
**Pull request by jcouv**
**Customer scenario**

Invoke the compiler with "ISO-1" on a machine with Turkish culture.
`csc.exe /langversion:ISO-1 b.cs`
`csc.exe /langversion:"ISO-1" b.cs`

You get "CSC : error CS1617: Invalid option '"ISO-1"' for /langversion; must be ISO-1, ISO-2, Default or an integer in range 1 to 6"

**Bugs this fixes:**

https://devdiv.visualstudio.com/DevDiv/_workitems?id=194594

**Workarounds, if any**

Use lowercase format "iso-1"

### CODE REVIEW

**Comment by jcouv** [comment]
I was not able to repro the issue on either of the Turkish VMs I tried. 
@gafter  Should I make the change regardless?

**Comment by gafter** [comment]
I suspect the version of the compiler this was reported against has since been fixed by the call to ToLowerInvariant. However, we are better off using the new API, so I support going forward with this change.

**Comment by jcouv** [comment]
Thanks for the confirmation, Neal.
@dotnet/roslyn-compiler for a second review. Thanks

**Comment by jcouv** [comment]
@dotnet/roslyn-compiler for a second review (tiny change).

**Comment by cston** [comment]
Please add a test if possible.
```
Thread.CurrentThread.CultureInfo.CurrentCulture = new CultureInfo("tr-TR");
"ISO-1".TryParse(out var version);
```

**Comment by jcouv** [comment]
@cston Added the test you suggested. 
I'm not 100% sure the best practice for modifying the current's thread culture, so I took a conservative approach.

**Comment by cston** [comment]
LGTM

**Pull request merged**
