### PR TITLE
disabled semantic version tracking

### PR DESCRIPTION
**Pull request by heejaechang**
current one is too fragile. just re-calculate it on new vs session

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @shyamnamboodiripad @mavasani @tmeschter @jmarolf can you take a look please?

**Comment by srivatsn** [comment]
Why don't you just delete the code instead of commenting it out and just add a link to an issue that details what needs to happen in the future?

**Comment by srivatsn** [comment]
:+1:

**Comment by heejaechang** [comment]
#1540

**Comment by heejaechang** [comment]
yes, I could delete the code. if I dont see any issue, let me delete the code. but for now, let's see whether any one notice this.

**Pull request merged**
