### PR TITLE
Added member classification support for c#.

### PR DESCRIPTION
**Pull request by mkrueger**
Rebased https://github.com/dotnet/roslyn/pull/24100

Added classification for c# methods, events, fields and properties.

VB.NET is missing and unit tests. I've atm problems compiling/running the tests on my system. So do not merge it - it's untested.
But that's basically what we need in Visual Studio 4 Mac. It should be a base for discussion about classification enhancements.

esp. for making a difference between properties, events and fields this is useful.

### CODE REVIEW

**Comment by DustinCampbell** [comment]
I've re-kicked the CI tests that failed as they don't look related to this change.

**Comment by jinujoseph** [comment]
looping @Pilchie  for Ask mode approval for 15.7.Preview2
This contains only the C# side of changes, Dustin will work on the VB side once this is merged

**Comment by Pilchie** [comment]
Approved for 15.7 P2 - thanks @mkrueger !

**Comment by mkrueger** [comment]
Thanks @all for the help :)

**Pull request merged**
