### PR TITLE
Add null check for Item1 dereference

### LINKED ISSUE #7616: AbstractLanguageService.GetCurrentBlock throwing NullReferenceException
I hit a bunch of these trying to debug Roslyn in VS.

There is a missing null check on foundBlock.Item1, but there is null check for foundBlock in many locations before and after this line.  

This exception was getting swallowed up by VS.

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #7616 

Add null conditional access operator.

@jasonmalinowski @Pilchie please review

### CODE REVIEW

**Comment by jasonmalinowski** [comment]
Oops, sorry. :+1:

**Comment by jasonmalinowski** [comment]
@dotnet/roslyn-ide for more general review coverage.

**Comment by mattwar** [comment]
hey, no judging here. :smile_cat:

**Comment by Pilchie** [comment]
Uh, oh - @mattwar has discovered the :smile_cat: emoji.  What's next?  :sparkles:?  :fire:?  Only the magic :8ball: knows...

:+1:

**Comment by mattwar** [comment]
test mac please

**Pull request merged**
