### PR TITLE
Don't crash when analyzing projects without compiler options.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Change https://github.com/dotnet/roslyn/commit/05a7e645c997449db53ad412ea74c740232dcf91#diff-ba00854a436654ed773eb6870589c579 broke TypeScript as it assumes that all project have CompilationOptions.

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Paging @mavasani 

Note: i could have put the fix in at the DiagnosticDescriptor level itself.  The crash occurs here:

```c#
        public ReportDiagnostic GetEffectiveSeverity(CompilationOptions compilationOptions)
        {
            if (compilationOptions == null)
            {
                throw new ArgumentNullException(nameof(compilationOptions));
            }
```

But it smelled a bit off to have the code there have the special casing for 'null' options there.  Let me know what you would prefer for the fix.

**Comment by CyrusNajmabadi** [comment]
I'm also going to add a test for this for a 'NoLanguage' project.

**Comment by mavasani** [comment]
Thanks @CyrusNajmabadi your fix looks fine. Please do add a test.

@heejaechang The code for error list here: http://source.roslyn.io/#Microsoft.VisualStudio.LanguageServices.SolutionExplorer/DiagnosticItem/DiagnosticItemSource.cs,67 also assumes non-null compilation options for project. Is this only for C#/VB projects or can it hit the same issue?

**Comment by CyrusNajmabadi** [comment]
test added.

Note: this was the only codepath i hit that had a problem in the TS case.

**Comment by mavasani** [comment]
Thanks for adding the test :+1:

**Pull request merged**
