### PR TITLE
EnC: Fix variable capture analysis in presense of parameter changes

### PR DESCRIPTION
**Pull request by tmat**
The analysis has not been updated to account for changing parameters.

This should fix some of the NFW we have seen in telemetry: 271,368 events with stack trace:

```
Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.CalculateCapturedVariablesMaps(ImmutableArray`1,SyntaxNode,ImmutableArray`1,ISymbol,SyntaxNode,BidirectionalMap`1,ArrayBuilder`1,ArrayBuilder`1,ArrayBuilder`1,ArrayBuilder`1,Boolean&,CancellationToken)
Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.ReportLambdaAndClosureRudeEdits(SemanticModel,SyntaxNode,SemanticModel,SyntaxNode,ISymbol,IReadOnlyDictionary`2,BidirectionalMap`1,EditAndContinueCapabilitiesGrantor,ArrayBuilder`1,Boolean&,CancellationToken)
Microsoft.CodeAnalysis.EditAndContinue.AbstractEditAndContinueAnalyzer.AnalyzeChangedMemberBody(SyntaxNode,SyntaxNode,SyntaxNode,SyntaxNode,SemanticModel,SemanticModel,ISymbol,ISymbol,SourceText,ImmutableArray`1,ImmutableArray`1,EditAndContinueCapabilitiesGrantor,Builder,Builder,ArrayBuilder`1,Func`2&,CancellationToken)
```

### CODE REVIEW

**Comment by tmat** [comment]
@davidwengier PTAL

**Review by davidwengier — APPROVED** [review]

**Comment by davidwengier** [comment]
It's somewhat surprising that these edits re-use the same lambda helpers, but my memory on it is vague. I think it makes sense though, and I suspect separate edits, ie deleting the method in one generation, then adding it back with one less parameter in a second, would have worked. Nice find!

**Comment by tmat** [comment]
> It's somewhat surprising that these edits re-use the same lambda helpers

Which "lambda helpers" do you mean?

BTW, turns out VB has more issues ... fixing now. Will add a commit soon.

**Comment by davidwengier** [comment]
I was thinking of the display classes that are generated, that hold the fields that get captured. My assumption was that the compiler was re-using the methods on it, but thats probably wrong. I guess its actually the symbol matcher matching `x => x + a1` from gen 1 with `x => x + a1 + a2` from gen 2, regardless of what the compiler ends up actually doing.

**Comment by tmat** [comment]
I'll check what the emit looks like.

**Pull request merged**
