### PR TITLE
Upgrade System.Collections.Immutable and System.Reflection.Metadata

### PR DESCRIPTION
**Pull request by agocke**
These are the versions currently used by VS in lab/ml.

### CODE REVIEW

**Comment by jaredpar** [comment]
@jasonmalinowski what VS version did this change go into: 15.8?

**Comment by jasonmalinowski** [comment]
@jaredpar Yes.

**Comment by jasonmalinowski** [comment]
And _in theory_ there is support for Roslyn F5 where we put dependencies we have higher than VS in a separate non-shipped VSIX, so this might be fine. Just test it first against a 15.7 machine.

(I'll ignore the general non-building-ness of this PR first. :smile:)

**Comment by jaredpar** [comment]
We've chosen to make master preview only in the past. Is there a reason we can't do this here?

**Comment by agocke** [comment]
@jasonmalinowski I don't understand why this being in vs-deps helps. All of the new `ref` APIs need new SCI/SRM references.

**Comment by jasonmalinowski** [comment]
> We've chosen to make master preview only in the past. Is there a reason we can't do this here?

You could; I just wanted to call out that decision should be intentional and in advance -- and before it breaks integration tests more than they already are. And like I said, this might actually work just fine due to our Dependencies VSIX.

> I don't understand why this being in vs-deps helps.

Well, your PR didn't indicate any "why?", and depending on what you were trying to do that might have been just fine. If you needed them for one bug fix, for example, you could just put the bugfix in master-vs-deps too.

**Comment by tmat** [comment]
If we are ok with updating master to the latest SRC/SCI let's cherry-pick the commits that did this in master-vs-deps.
Repeating the work in a new PR is a waste of time.

**Comment by agocke** [comment]
@tmat Works for me. I'll close this PR for now.

**Comment by jasonmalinowski** [comment]
@tmat @agocke And if we're comfortable just declaring 15.8 as the minimum baseline for contributions at this point, just ask @dotnet/roslyn-infrastructure to do a merge from dev15.8-vs-deps to dev15.8 and that'll get your change for you without the adventures of cherry-picking.

**Pull request closed without merging**
