### PR TITLE
Analyze argument conversion for this argument of Deconstruct extension method

### PR DESCRIPTION
**Pull request by cston**

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Do we have an issue that is closed by this PR?

**Comment by cston** [comment]
@RikkiGibson, there is no issue logged for this bug. This is a small fix found while investigating https://github.com/dotnet/roslyn/issues/38638.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by cston** [comment]
@dotnet/roslyn-compiler please review.

**Comment by cston** [comment]
@dotnet/roslyn-compiler for a second review.

**Pull request merged**
