### PR TITLE
Merge microupdate into dev15-preview-4

### PR DESCRIPTION
**Pull request by vslsnap**
This is an automatically generated pull request from microupdate into dev15-preview-4.

@dotnet/roslyn-infrastructure:

``` bash
git remote add vslsnap-roslyn "https://github.com/vslsnap/roslyn.git"
git fetch vslsnap-roslyn
git fetch upstream
git checkout merge-microupdate-into-dev15-preview-420160713-175309
git reset --hard upstream/dev15-preview-4
git merge upstream/microupdate
# Fix merge conflicts
git commit
git push vslsnap-roslyn merge-microupdate-into-dev15-preview-420160713-175309 --force
```

Once the merge can be made and all the tests pass, you are free to merge the pull request.

### CODE REVIEW

**Comment by vslsnap** [comment]
@dotnet-bot test vsi please

**Comment by jasonmalinowski** [comment]
@jmarolf: @Pilchie should be able to confirm that I think this merge is a no-op and it's just taking the destination.

**Comment by jmarolf** [comment]
test vsi please

**Comment by jmarolf** [comment]
test vsi please

**Pull request merged**
