### PR TITLE
Document `-nullable:annotations` option

### PR DESCRIPTION
**Pull request by jcouv**

### CODE REVIEW

**Comment by jcouv** [comment]
@dotnet/roslyn-infrastructure This PR has repeatedly hit an integration issue (sometimes in debug, sometimes in release). Please advise.

**Comment by jaredpar** [comment]
@dotnet/roslyn-ide looks like the integration tests are hanging here in some way. This is a doc change so it's a test issue vs. issue in the change. Is anyone looking into this?

**Comment by mavasani** [comment]
I see lot of failing error list test with the following diagnostic:
```
The current .NET SDK does not support targeting .NET Core 3.1. Either target .NET Core 3.0 or lower, or use a version of the .NET SDK that supports .NET Core 3.1. Project:TestProj File:Microsoft.NET.TargetFrameworkInference.targets Line:127 Column:5
```

@sharwell @dotnet/roslyn-infrastructure known issue?

**Comment by dibarbet** [comment]
Known, @JoeRobich sent a fix - https://github.com/dotnet/roslyn/pull/39567

**Pull request merged**
