### PR TITLE
Address followup nits from IOp prs.

### PR DESCRIPTION
**Pull request by 333fred**
Fixes nits raised during review for #23041 and #22972. Fixes https://github.com/dotnet/roslyn/issues/23093.

### CODE REVIEW

**Comment by AlekseyTs** [comment]
Test this please

**Review by AlekseyTs — APPROVED** [review]
LGTM (iteration 2)

**Comment by 333fred** [comment]
Ping @jcouv @dotnet/analyzer-ioperation for reviews please.

**Review by jcouv — APPROVED** [review]
LGTM

**Review by mavasani — APPROVED** [review]

**Pull request merged**
