### PR TITLE
Enabling tests for 3593 and 3746

### LINKED ISSUE #3593: The hidden keyword __makeref does not produce an error if used when System.TypedReference is not defined
If the code snippet below is compiled in a release build, the expected CS0518 error is not produced. I realize the the mkrefany opcode does not require the IL to refer to System.TypedReference, but any use of mkrefany without System.TypeReference is useless and should produce an error.

* Make a new Universal Windows Blank app 
* Drop this function in the project:
```
    public static T Read<T>() where T : new()
    {
        T result = new T();
        var refresult = __makeref(result);

        // ... method body

        return result;
    }
```
* Build under debug, you should get this error: error CS0518: Predefined type 'System.TypedReference' is not defined or imported
* Build under release and the C# compiler does not produce an error. (The .NET Native toolchain will produce an error, that I'm currently working to improve, but the C# compiler has the by far best capability to produce a good error.)

### LINKED ISSUE #3746: Boxing a TypedReference produces an undiagnosable error
This is similar to issue #3593 - create a blank Windows Universal app in VS and put this method and field in it:

    public static object rrr;

    public static T Read<T>() where T : new()
    {
        T result = new T();
        var refresult = __makeref(result);
        rrr = refresult;
        return result;
    }

An attempt to build the app results in CSC : error CS7038: Failed to emit module 'TestEmptyApp'. I would expect the compiler to tell me not to box a TypedReference.

### PR DESCRIPTION
**Pull request by VSadov**
The actual bugs appear to be addressed by the earlier change.

Fixes #3746
Fixes #3593

### CODE REVIEW

**Comment by VSadov** [comment]
@AlekseyTs @gafter @agocke @TyOverby @jaredpar - FYI.  Test only change.

**Comment by jaredpar** [comment]
:+1:

**Comment by VSadov** [comment]
@dotnet-bot test mac

**Comment by VSadov** [comment]
@dotnet-bot test this

**Comment by VSadov** [comment]
retest mac

**Comment by VSadov** [comment]
@dotnet-bot test this please

**Comment by AlekseyTs** [comment]
LGTM

**Comment by gafter** [comment]
:+1:

**Comment by jaredpar** [comment]
test mac please

**Comment by jaredpar** [comment]
I found the issue which was causing the Mac run failures and addressed it.  This run should pass.

**Comment by VSadov** [comment]
test mac please

**Pull request merged**
