### PR TITLE
CSharp and VB Sample Docs Update

### PR DESCRIPTION
**Pull request by mattscheffer**
This is an update to the Syntax Analysis Sample Docs for CSharp and VB. 

Changes includes the following:
* Removed references to Roslyn End User Preview, SDK Project Templates etc. 
* Changed Prereqs to include .NET Compiler Platform SDK and VS 2015
* Changed New Project Dialog structure to accurately depict current structure
* Added steps to add required CodeAnalysis libraries to the project.
* Adjusted properties to be inspected that were renamed.
* Changed code to not use obsolete properties which previously threw errors. (Notably MethodBlockSyntax's begin property. Using BlockStatement instead)

@v-codeel and I will be making code reviews and requests for the rest of the documents in this folder either at the end of this week or next week as we finish going through and updating them

### CODE REVIEW

**Comment by mattscheffer** [comment]
@ManishJayaswal @Pilchie @AnthonyDGreen @amcasey Please take a look...

**Comment by mattscheffer** [comment]
Added changes to CSharp and VB Syntax Transformation sample docs.

Changes to these docs includes:
*Removed references to Roslyn End User Preview, SDK Project Templates etc.
*Changed Prereqs to include .NET Compiler Platform SDK and VS 2015
*Changed New Project Dialog structure to accurately depict current structure
*Added steps to add required CodeAnalysis libraries to the projects.
*Adjusted the CreateTestCompilation method in both of the languages as most of the property creations were out of date with old unused code. 

Please take a look specifically at the last for both languages. I'm not entirely happy with my changes involving parsing the documents because of ParseFile being out dated and having to use ParseText instead. The code works, but I think its rather ugly and would love to have a better implementation.

**Comment by AnthonyDGreen** [comment]
@mattscheffer, Thanks for the updates Matt. I'm migrating your updates to markdown and pushing them to the wiki today. I plan to delete all of the word and PDF docs from the repo once all docs are migrated but since you've already updated these I can handle these now. Thanks!

**Comment by AnthonyDGreen** [comment]
@mattscheffer, I converted your updates to C# Syntax walkthrough to markdown and uploaded them to the wiki. I'll aim for 1 doc converted per day so these four docs you've changed should be ported by end of week. I made a few updates to your changes. I replaced the "New Project" steps with just creating a new stand-alone code analysis tool (console app). It should include all the references they need by default.

**Comment by mattscheffer** [comment]
Ah, I didn't know that was a thing. That'll definitely be more useful than needing to add all the references. Does it include System.Collections.Immutable? I know that needs to be referenced in the Syntax documents. Thanks!

**Comment by ManishJayaswal** [comment]
@AnthonyDGreen should we delete these documents then after they have been converted to markdown and uploaded to wiki. Why should we have these binary files here?

**Comment by AnthonyDGreen** [comment]
@ManishJayaswal, absolutely we should delete them afterward.

@mattscheffer, all of the C# Getting started walkthroughs have been ported to markdown on our wiki. You can find them here:

https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis
https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Semantic-Analysis
https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Transformation

Another contributor submitted an update to the transform doc that conflicted with yours - they were mostly the same but as theirs used a new C# 6 language feature in a way that cleaned up the code and brought the C# walkthrough in line with the VB version (by using static imports) I just took their changes on that one file. Per my last update your changes to the Syntax analysis walkthrough were already ported.

I'll port your changes to the VB docs along with some of my own then close this PR. Thanks again for taking the time to make those updates!

**Comment by mattscheffer** [comment]
@AnthonyDGreen Thanks for the update! I'm do like the change with the static imports. The original transformation doc actually had something similar to that which I had to take out as the code wasn't working, so I'm glad it's closer to its original state. 

@v-codeel The Analysis doc is actually yours so heads up here.

**Comment by AnthonyDGreen** [comment]
@mattscheffer,

I added the VB docs with your changes to the wiki. You can see the full list [here](https://github.com/dotnet/roslyn/wiki/Samples-and-Walkthroughs). Note: I didn't get to the How To Write a Diagnostic and Code Fix documents but they weren't included in this pull request anyway. The Word and PDF docs are now stale and we don't want to have to keep them in sync with the wiki all the time (and certainly don't want them source controlled). We can now delete these files from the repo.

Thanks!

**Pull request closed without merging**
