### PR TITLE
Update Microsoft.CodeAnalysis.Test.Resources.Proprietary.nuspec to netstandard13

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@agocke Does this look correct?

**Comment by tmat** [comment]
@dotnet-bot retest prtest/win/dbg/eta please
// Previous failure: http://dotnet-ci.cloudapp.net/job/dotnet_roslyn_prtest_win_dbg_eta/6123/
// Retest reason:

**Comment by tmat** [comment]
retest vsi please

**Comment by agocke** [comment]
I think you have to keep net45 as a supported target.

**Comment by agocke** [comment]
Also, these are just resources, couldn't they be used on 1.1?

**Pull request closed without merging**
