### PR TITLE
Fixed app.config casing

### PR DESCRIPTION
**Pull request by jaredpar**
Ensured that all uses of app.config in our product / test code base is
used in the lower case form.  This helps with our Unix efforts where
mixing the case can be significant.  Updated all of the project
references to ensure they used the lower case version as well.

### CODE REVIEW

**Comment by jaredpar** [comment]
CC @dotnet/roslyn-compiler

**Comment by TyOverby** [comment]
Some of these are comments but I feel like they should be changed anyway.

```
$ git grep "App.config"
src/Compilers/Core/MSBuildTaskTests/MSBuildTaskTests.csproj:    <None Include="App.config" />
src/Compilers/Core/Portable/CommandLine/CommonCommandLineArguments.cs:        /// An absolute path of the App.config file or null if not specified.
src/Compilers/Core/Portable/Desktop/DesktopAssemblyIdentityComparer.cs:        //   and the portability for its PublicKeyToken is not disabled in App.config file then the identity is replaced by a different identity
src/Compilers/Core/Portable/Desktop/DesktopAssemblyIdentityComparer.cs:        /// Loads <see cref="AssemblyPortabilityPolicy"/> information from XML with App.config schema.
src/EditorFeatures/Test2/Diagnostics/AdditionalFileDiagnosticsTests.vb:                If item.Path.EndsWith("App.config", StringComparison.OrdinalIgnoreCase) Then
src/VisualStudio/CSharp/Impl/ProjectSystemShim/TempPECompilerService.cs:            // TODO (tomat): Revisit compilation options: App.config, strong name, search paths, etc? (bug #869604)
src/Workspaces/CoreTest/TestFiles/CSharpProject_CSharpProject_WithPrefer32Bit.csproj:    <None Include="App.config" />
src/Workspaces/CoreTest/TestFiles/CSharpProject_CSharpProject_WithoutPrefer32Bit.csproj:    <None Include="App.config" />
src/Workspaces/CoreTest/TestFiles/VisualBasicProject_VisualBasicProject_WithPrefer32Bit.vbproj:    <None Include="App.config" />
src/Workspaces/CoreTest/TestFiles/VisualBasicProject_VisualBasicProject_WithoutPrefer32Bit.vbproj:    <None Include="App.config" />

```

**Comment by jaredpar** [comment]
@TyOverby good catch.  Updated.

**Comment by TyOverby** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
