### PR TITLE
Mark ParseOptions.CommonWithKind with attribute of EditorBrowsableState.Never

### PR DESCRIPTION
**Pull request by eriawan**
Mark ParseOptions.CommonWithKind with attribute of `EditorBrowsableState.Never` according to #8353

### CODE REVIEW

**Comment by Pilchie** [comment]
:+1: from me.  @dotnet/roslyn-compiler want to take a look?

**Comment by AlekseyTs** [comment]
LGTM, though it would be good to leave a comment about why did we decide to add the attribute.

**Comment by eriawan** [comment]
@AlekseyTs agree. I just following #8353, imho we should have explanations on why this attribute addition is necessary.

@jasonmalinowski could elaborate more on the reason? I will add comment based on the reason and commit using this PR, if it's OK for you to help us track the historical reason for this change.

**Comment by jasonmalinowski** [comment]
It was supposed to be a protected implementation detail. The "pattern" we have for these is the public With* method is the only public callable one, and that forwards to the protected Common* like all the other methods in the class.

**Comment by jmarolf** [comment]
test vsi please

**Comment by eriawan** [comment]
@jasonmalinowski , should I include your latest comment in my PR?

@jaredpar , @Pilchie and @jaredpar : is there any update/concerns on this PR? It's ok if this PR need more time to be discussed :smile:

**Comment by jaredpar** [comment]
:+1:

**Comment by jasonmalinowski** [comment]
@eriawan: sure, go ahead.

**Comment by eriawan** [comment]
@jasonmalinowski : thanks! your comment has been added.

**Comment by eriawan** [comment]
hi @jaredpar , @jasonmalinowski 

Does this PR still need more edits or additional comments? Or is there no milestone linked to this PR?

I'm quite curious on not just when this PR be merged,  also on after this PR is merged, when this PR will be released on certain release/milestone. 

Thanks in advance :smile: 

Apologize if I seem to be so rush/noisy, because this is my first PR on dotnet/roslyn repo :blush:

**Comment by jaredpar** [comment]
Compiler side we are good.  @jasonmalinowski are we good IDE side?

**Comment by jasonmalinowski** [comment]
:+1: Although I'm not an IDE representative here. I'm just here because I filed the original bug.

(If I were to nitpick, I'd remove my name and the reference to this PR from the comment. If the comment needs a reference to this conversation to understand it, the comment should be rewritten. It should stand alone.)

**Comment by eriawan** [comment]
@jasonmalinowski makes sense.

I'm updating the comments now. Thanks for your feedback!

**Comment by eriawan** [comment]
@jasonmalinowski , @jaredpar 

PR Updated :)

**Pull request merged**
