### PR TITLE
Refactor IConditionalChoiceExpression.

### PR DESCRIPTION
**Pull request by 333fred**
Fixes https://github.com/dotnet/roslyn/issues/21280. Tagging @dotnet/analyzer-ioperation @dotnet/roslyn-compiler for review.

### CODE REVIEW

**Review by cston — APPROVED** [review]

**Comment by 333fred** [comment]
Ping, I need another review from @dotnet/roslyn-compiler and two from @dotnet/analyzer-ioperation.

**Review by CyrusNajmabadi — APPROVED** [review]

**Comment by CyrusNajmabadi** [comment]
This is so basic, you're good with only one ioperation review. We do need another @dotnet/roslyn-compiler review though.

**Comment by 333fred** [comment]
Ping for reviews.

**Review by mavasani — APPROVED** [review]

**Review by AlekseyTs — APPROVED** [review]
LGTM

**Pull request merged**
