### PR TITLE
Update EditorFeatures.WPF dependencies

### LINKED ISSUE #35897: Microsoft.CodeAnalysis.EditorFeatures.Wpf NuGet package needs to declare a dependency on Microsoft.VisualStudio.InteractiveWindow
**Version Used**: 
3.1.0-beta4-19261-04

The NuGet package https://www.nuget.org/packages/microsoft.codeanalysis.editorfeatures.wpf contains Microsoft.CodeAnalysis.EditorFeatures.Wpf.dll which reference Microsoft.VisualStudio.InteractiveWindow.dll 2.0.0.0.

However the NuGet package doesn't declare this dependency. The NuGet package needs to declare an explicit dependency on https://www.nuget.org/packages/microsoft.visualstudio.interactivewindow

### PR DESCRIPTION
**Pull request by JoeRobich**
Fixes #35897

### CODE REVIEW

**Comment by JoeRobich** [comment]
@tmat Please take a look

**Comment by tmat** [comment]
I think we also need to update MicrosoftVisualStudioInteractiveWindowVersion to 2.8.0

**Comment by JoeRobich** [comment]
@tmat Good catch. Updated.

**Comment by tmat** [comment]
I think we might need to add some package references to resolve the ambiguities :(.

**Comment by JoeRobich** [comment]
@tmat Updated package references.

**Comment by JoeRobich** [comment]
@tmat I think I got all the references added. Please take another look.

**Pull request merged**
