### PR TITLE
Don't null ref if we can't find the host document in SetDocumentContext

### PR DESCRIPTION
**Pull request by dpoeschl**
Fixes internal bug #237579

### CODE REVIEW

**Comment by dpoeschl** [comment]
Tagging @dotnet/roslyn-ide for review.

**Comment by dpoeschl** [comment]
@CyrusNajmabadi @jasonmalinowski Thanks for the help with the investigation! :smile:

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by dpoeschl** [comment]
@MattGertz for RC ask mode

**Comment by MattGertz** [comment]
Approved pending test completion.

**Pull request merged**
