### PR TITLE
Handle pointer and error types in NormalizeTaskTypes

### PR DESCRIPTION
**Pull request by cston**
Handle pointer and error types in `NormalizeTaskTypes`

PR feedback from #12671.

### CODE REVIEW

**Comment by cston** [comment]
@AlekseyTs, @jaredpar, @dotnet/roslyn-compiler please review.

**Comment by agocke** [comment]
LGTM

**Comment by jcouv** [comment]
LGTM

**Comment by AlekseyTs** [comment]
LGTM

**Pull request merged**
