### PR TITLE
IDE1006: Support multiple underscores

### LINKED ISSUE #40713: IDE1016 should not warn when name is all underscores
```cs
void M()
{
    //                            ↓ IDE1006should not warn here
    Console.CancelKeyPress += (_, __) => { };
}
```

### PR DESCRIPTION
**Pull request by Sjoerdsjoerd**
The issue describes the problem when multiple underscores are used, and the IDE still gives the IDE1006 message.

In a quick glance I could not find any unit tests for IDE1006, so I tested it locally and it seems to work.

Closes #40713

### CODE REVIEW

**Comment by Sjoerdsjoerd** [comment]
> @Sjoerdsjoerd please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

**Review by Youssef1313 — CHANGES_REQUESTED** [review]
Best to have another PR to dotnet/roslyn-analyzers as well:

https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/Extensions/ISymbolExtensions.cs

**Comment by Sjoerdsjoerd** [comment]
> Tests can be added to these files:
> 
> https://github.com/dotnet/roslyn/blob/main/src/Analyzers/CSharp/Tests/NamingStyles/NamingStylesTests.cs https://github.com/dotnet/roslyn/blob/main/src/Analyzers/VisualBasic/Tests/NamingStyles/NamingStylesTests.vb

I have extended the discard tests with the extra underscores

**Comment by Sjoerdsjoerd** [comment]
> Best to have another PR to dotnet/roslyn-analyzers as well:
> 
> https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/Extensions/ISymbolExtensions.cs

Sure, I will create an PR there as well.

**Review by sharwell — APPROVED** [review]
This appears to meet the behavior described in the original issue, but leaving the final review to @mavasani to confirm there haven't been any changes to the space over the past 3 years.

**Comment by mavasani** [comment]
> This appears to meet the behavior described in the original issue, but leaving the final review to @mavasani to confirm there haven't been any changes to the space over the past 3 years.

I can’t recall any subsequent design discussions on this, so seems fine to me.

**Comment by Sjoerdsjoerd** [comment]
The pipeline is failing. Is it possible to restart it?

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Pull request merged**
