### PR TITLE
use correct line ending

### PR DESCRIPTION
**Pull request by heejaechang**
### Customer scenario

user commit completion in razor on mac and code got messed up.

### Bugs this fixes

 https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585147 and #28240

### Workarounds, if any

don't use tab and use windows line ending.

### Risk

Low. no code loss. 

### Performance impact

Low. no perf impacting changes

### Is this a regression from a previous update?

No

### Root cause analysis

formatter we used for razor didn't set line ending correctly (always used windows style) and didn't check tab for whitespace causing it to group strings in the wrong group (whitespace group)

### How was the bug found?

A customer from VS for Mac

### CODE REVIEW

**Comment by heejaechang** [comment]
for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585147 and https://github.com/dotnet/roslyn/issues/28240

**Comment by heejaechang** [comment]
@ToddGrun can you take a look? @KirillOsenkov is not responding.

**Comment by KirillOsenkov** [comment]
@heejaechang apologies HeeJae, today's been a busy day. I will respond my EOD :)

**Comment by KirillOsenkov** [comment]
I confirm that this doesn't fix our issues, but it's still a good change to take.

**Comment by heejaechang** [comment]
ported https://github.com/mono/monodevelop/pull/5335/files

**Comment by heejaechang** [comment]
@KirillOsenkov can you take a look?

**Comment by heejaechang** [comment]
@dotnet/roslyn-ide can you take a look?

**Comment by heejaechang** [comment]
retest windows_release_vs-integration_prtest please

**Comment by heejaechang** [comment]
@jasonmalinowski it does 2 thing.

1. is porting fix @KirillOsenkov made for VS for mac to us (https://github.com/mono/monodevelop/pull/5335/files)

2. and set right line ending for formatting for razor file.

**Pull request merged**
