### PR TITLE
Have Windows make dump files

### PR DESCRIPTION
**Pull request by jasonmalinowski**
This is cherry-picking @sharwell's changes out that use the windows error reporting options to capture dumps. Right now this is pulled out in isolation while we try to track down some crashes that aren't getting dumps.

### CODE REVIEW

**Comment by sharwell** [comment]
Feel free to amend the first commit per the second. The "fixup" mention is a reminder to rebase the change. 😁

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_debug_vs-integration_prtest please.

**Comment by jasonmalinowski** [comment]
@dotnet-bot retest windows_release_vs-integration_prtest please.

**Comment by sharwell** [comment]
@dotnet-bot retest this please

**Comment by sharwell** [comment]
retest this please

**Comment by sharwell** [comment]
retest this please

**Comment by Pilchie** [comment]
@jmarolf did you see this?  We may want something similar for `project-system`

**Comment by jasonmalinowski** [comment]
This never seemed to be successful, and also the approach worries me since we're changing machine state that may not be reliably reset and could break later runs.

**Pull request closed without merging**
