### PR TITLE
VB Compiler Test Utilities Tweaks

### PR DESCRIPTION
**Pull request by AdamSpeight2008**

### CODE REVIEW

**Comment by tannergooding** [comment]
test windows_release_vs-integration_prtest please

**Comment by AdamSpeight2008** [comment]
@jaredpar  Do you have an idea how to remove them?

**Comment by jaredpar** [comment]
Once again this change contains a lot of unnecessary formatting changes.  As said many times before, we will not take PRs which contain large formatting changes.  When these are corrected we will reopen the PR for consideratoin.

**Comment by AdamSpeight2008** [comment]
@jaredpar  I think you should reexamine, as these "formatting" changes, are in fact changes to use more recent available, as well as better usage of existing features of the language. Eg `With Block" and "Auto Properties". Resultant formatting changes are side-effects of using them. eg different indentation levels.

Also I have repeatedly ask for explicit documentation of what formatting is expected or permitted for VB.net submissions. As I see it closing a pull requesting primarily on "stylistic formatting" when the repo hasn't stated what that style is. A passing reference to C# style isn't applicable as VB isn't a C-Style brace based language. Hence the repeated clarification, that constantly seems to be ignored.  It seems that you (or the project) don't want to Pull Request from VB contributors.

**Pull request closed without merging**
