### PR TITLE
Manish's new analyzer flagged it as not disposing disposable object e…

### PR DESCRIPTION
**Pull request by heejaechang**
…xplicitly.

so, added using to make it explicit

...

no user visible change. just code clean up

### CODE REVIEW

**Comment by heejaechang** [comment]
@mavasani do you want to bring this to your PR or checkin separately?

**Comment by heejaechang** [comment]
PR to run tests.

**Comment by mavasani** [comment]
Heejae, I am preparing a PR to enable the dispose rules on Roslyn.sln, with necessary fixes and suppressions. Feel free to check this in, otherwise I will take care of it.

**Comment by jinujoseph** [comment]
yay !! 
@Pilchie  for ask mode approval for 15.7.P2

**Comment by Pilchie** [comment]
Approved if you want to merge this one.

**Pull request merged**
