### PR TITLE
Add InternalsVisibleTo

### PR DESCRIPTION
**Pull request by shyamnamboodiripad**
Need IVT to implement source based test discovery component as an incremental analyzer.

### CODE REVIEW

**Comment by shyamnamboodiripad** [comment]
@heejaechang I think these are the only IVTs we will need (including for OOP). I copied the ones that LUT already has - but let me know if I don't need some of these...

**Comment by shyamnamboodiripad** [comment]
cc @dotnet/testimpact @peterwald

**Comment by shyamnamboodiripad** [comment]
Tagging @Pilchie for ask mode approval

**Comment by Pilchie** [comment]
What is the reason to implement source based discovery in yet another assembly?  We're working hard on reducing the number of assemblies loaded to support C#/VB projects.

**Pull request merged**
