### PR TITLE
Fixing async keyword highlighting on local functions

### LINKED ISSUE #25036: Async keyword not highlighted on local functions
Repro:
```c#
using System.Threading.Tasks;

class C
{
    async Task M()
    {
        async Task F()
        {
            await Task.Yield();
        }

        await F();
    }
}
```
Click on first `async` - both `async` and corresponding `await` is highlighted.
Click on second `async` - nothing is highlighted.

### PR DESCRIPTION
**Pull request by Neme12**
fixes #25036

First 4 commits are just refactoring/cleanup. The last commit actually adds local functions.

The cleanup involved (it's not clear from the final diff, which shows some false renames):
- Replacing `AsyncSimpleLambdaHighlighter`, `AsyncParenthesizedLambdaHighlighter` & `AsyncAnonymousMethodHighlighter` with one class: `AsyncAnonymousFunctionHighlighter` (their functionality was exactly the same)
- Merging their equivalent test classes: `AsyncSimpleLambdaHighlighterTests`, `AsyncParenthesizedLambdaHighlighterTests` & `AsyncAnonymousMethodHighlighterTests` into `AsyncAnonymousFunctionHighlighterTests`
- In `AbstractAsyncHighlighter<TNode>.HighlightRelatedKeywords`, replacing cases for `SimpleLambdaExpressionSyntax`, `ParenthesizedLambdaExpressionSyntax` & `AnonymousMethodExpressionSyntax` with one for `AnonymousFunctionExpressionSyntax` (the code was exactly the same)

### CODE REVIEW

**Comment by Neme12** [comment]
@dotnet-bot retest ubuntu_16_mono_debug_prtest please

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_debug_vs-integration_prtest please

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest thanks

**Comment by Neme12** [comment]
retest windows_release_vs-integration_prtest please

**Comment by DustinCampbell** [comment]
@dotnet-bot restest this please

**Comment by Neme12** [comment]
failure is #25931

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_unit64_prtest please

**Comment by Neme12** [comment]
@dotnet-bot retest windows_debug_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_release_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_debug_unit32_prtest please

**Comment by Neme12** [comment]
retest windows_debug_spanish_unit32_prtest please

**Comment by Neme12** [comment]
@DustinCampbell I finally won over the tests here... would you give this small-ish PR also a chance? :smile:

**Comment by DustinCampbell** [comment]
Absolutely, and thanks for your contribution. As the one who originally wrote that keyword highlighting code near the beginning of Roslyn, I'm happy to see it updated. Thanks!

**Comment by Neme12** [comment]
Thanks!

**Pull request merged**
