### PR TITLE
Check for null in snippets

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@dotnet/roslyn-ide plz review.

**Comment by dpoeschl** [comment]
:+1:

Thanks / Sorry / Facepalm

**Comment by dpoeschl** [comment]
For those reading this without context, this became a problem when we switched from returning a HashSet<T> to an ImmutableHashSet<T>. The latter throws on null, while the former does not. Surprise!

**Comment by dpoeschl** [comment]
/cc: @jasonmalinowski, who convinced me to change it to immutable, so he knows the treachery of such conversions in the future. :wink:

**Comment by davkean** [comment]
This is masking the issue, I think the real bug is that http://source.roslyn.io/#Microsoft.CodeAnalysis.EditorFeatures/Implementation/Intellisense/Completion/CompletionProviders/MemberInsertingCompletionItemRules.cs,15 returns default(TextChange) instead of null.

**Comment by dpoeschl** [comment]
Sure, but we are *sure*, right this moment, tonight, that this null check puts us back where we were before the Snippets change. We can fix the "real" bug as well, but if that fix isn't ready basically-immediately then I'd merge this before tomorrow's dogfooding.

**Comment by jmarolf** [comment]
:+1:

**Comment by DustinCampbell** [comment]
:+1:

**Pull request merged**
