### PR TITLE
Use new LSP packages to provide better failure notifications

### PR DESCRIPTION
**Pull request by dibarbet**
Responds to LSP breaking changes.

TODO - finish test insertion

### CODE REVIEW

**Comment by dibarbet** [comment]
@mgoertz-msft could you take a quick look at the xaml changes and ensure they match your expectations

**Comment by mgoertz-msft** [comment]
Looks good. Thank you @dibarbet!

**Comment by LinglingTong** [comment]
Looks good to me. Thanks @dibarbet !

**Review by davidwengier — APPROVED** [review]
Love the explanatory comments for each ShowNotificaiton method <3

**Pull request merged**
