### PR TITLE
Port fix for an intermittent crash in CompilationWithAnalyzers to future-stabilization

### PR DESCRIPTION
**Pull request by mavasani**
This is port of https://github.com/dotnet/roslyn/pull/9621 to future-stabilization for 2.0 milestone.

Tagging @dotnet/roslyn-analysis for CR.

### CODE REVIEW

**Comment by mavasani** [comment]
test vsi please

**Comment by mavasani** [comment]
Tagging @MattGertz for ask approval for future-stabilization. The original PR #9621 was already approved and merged into stabilization.

**Comment by MattGertz** [comment]
Approved pending testing and code reviews.

**Comment by mavasani** [comment]
@heejaechang @srivatsn can one of you please give a sign off? Original PR was already approved by you.

**Comment by heejaechang** [comment]
:+1:

**Pull request merged**
