### PR TITLE
Fix dynamic analysis instrumentation for VB

### PR DESCRIPTION
**Pull request by genlu**
This is cherry-picked from master branch. The original PR is here: https://github.com/dotnet/roslyn/pull/17083

**Customer scenario**

For Live Unit Testing users whose solution contains tests covering VB async methods, those tests would fail in LUT run because exception thrown by instrumented code.

**Bugs this fixes:** 

https://devdiv.visualstudio.com/DevDiv/_workitems?id=383387&_a=edit

**Workarounds, if any**

None. Those test would always fail in LUT.

**Risk**

Low. And this fix only affect instrumentation.

**Performance impact**

low perf impact because there is no extra allocation or complexity

**Is this a regression from a previous update?**

No.

**Root cause analysis:**

We insert a method prologue that contains a call to `CreatePayload(Guid,int,int,ref bool[],int)` during instrumentation for each method, however, the 4th argument (of type `bool[]`), which is an array access node created as an RValue. As an result, in the IL generated for instrumentation, the argument is the reference to an local variable instead of to the indexed element in the array. This will cause `CreatePayload` to throw an exception when it tries to add a payload array for a method that already has a payload array created.

This only affect VB instrumentation of async method. The local variable is introduced by local rewriter when rewriting the method call, and the method prologue is inserted **after** first run of local rewriter. As a result, in most cases LUT works correctly because the IL generated is wrong (bypassed local rewriting) but end up to be what we actually intended. For async methods, async rewriter tries to call local rewriter again, which is after the insertion of method prologue.

How did we miss it?  What tests are we adding to guard against it in the future?

We don't have tests that check IL of instrumented VB async method. And we never tested LUT with VB async method.

Unit test is added.

**How was the bug found?**

Dogfooding LUT on roslyn-analyzers solution

FYI @dotnet/roslyn-compiler @dotnet/roslyn-interactive

### CODE REVIEW

**Comment by genlu** [comment]
@MattGertz for approval.

**Comment by MattGertz** [comment]
15.1, please.

**Comment by genlu** [comment]
@MattGertz I thought dev15.1.x is for 15.1? Or did you mean this should be in the quarterly update 1?

**Comment by MattGertz** [comment]
I am only approving fixes for RTW right now; that's what I thought you were submitting against.  Hold onto the others for now.

**Comment by genlu** [comment]
@ManishJayaswal Which branch should this change be targeting? dev15.1.x or master?

**Comment by ManishJayaswal** [comment]
Put it in master for now.

**Comment by ManishJayaswal** [comment]
@jaredpar do you already have compiler fixes that you are taking for 15.1? If yes then I would like to consider this as well.

**Comment by jaredpar** [comment]
@ManishJayaswal at this time we don't have any we are taking.  Still looking at a couple though.

**Comment by genlu** [comment]
@jaredpar Please let me know if we are gonna insert for 15.1, otherwise the change is already in master so there's no further action needed.

**Comment by jasonmalinowski** [comment]
@genlu @ManishJayaswal Is this something we're still (potentially) tracking for 15.1? Just wanted to check, we have some stale PRs. Feel free to leave this if you're still considering it.

**Comment by ManishJayaswal** [comment]
@jasonmalinowski yes we are still considering it.

**Pull request closed without merging**
