### PR TITLE
Remove equivalenceKey from CodeAction.Create overload

### LINKED ISSUE #5975: CodeAction.Create should not have an equivalence key
Consider this overload of CodeAction.Create

``` csharp
public static CodeAction Create(string title, IEnumerable<CodeAction> nestedActions, string equivalenceKey = null)
```

During API review it seemed that there was no reason for an equivalenceKey here.  The default is to use the first `CodeAction` so shouldn't it always be the equivalence key.

### PR DESCRIPTION
**Pull request by Pilchie**
Automatically calculate equivalence keys from nested actions.

Fixes #5975.

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @dotnet/roslyn-ide @mavasani @CyrusNajmabadi @mattwar again, for this version against `stabilization`.

**Comment by mavasani** [comment]
:+1:

**Comment by CyrusNajmabadi** [comment]
Cute.  :+1:

**Comment by Pilchie** [comment]
Updated to remove the overload that takes nested actions altogether until we can decide how we want to represent this.  Conviently `CodeAction.GetCodeActions()` and `CodeAction.HasCodeActions`  were already internal.

Please take another look.

**Comment by mattwar** [comment]
:+1:

**Pull request merged**
