### PR TITLE
Assert that completion has a TypeInferenceService

### PR DESCRIPTION
**Pull request by rchande**
We have watsons where completion NRE's failing to find one; this is indicative of a
setup issue.

### CODE REVIEW

**Comment by rchande** [comment]
@dotnet/roslyn-ide plz review

**Comment by rchande** [comment]
These are the providers for C#/VB respectively that raise the watsons.

**Comment by jasonmalinowski** [comment]
This is just to get better watsons? :+1:

**Comment by balajikris** [comment]
@dotnet-bot retest prtest/win/dbg/unit32 please
@dotnet-bot retest prtest/win/dbg/unit64 please
// Retest reason: infra break

**Comment by Pilchie** [comment]
What extra information do we think that these will help us obtain?

**Comment by rchande** [comment]
@Pilchie Instead of getting an NRE and wondering what was null, we'll know specifically that we didn't get a TypeInferenceService, which is indicative of a MEF issue.

**Pull request merged**
