### PR TITLE
Reduce VM usage for RPS tests by using a special back-door interface to mark analyzer as needing less work.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes: https://github.com/dotnet/Roslyn/issues/7486

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
tagging @heejaechang @mavasani @KevinH-MS

**Comment by CyrusNajmabadi** [comment]
tagging @dotnet/roslyn-ide

**Comment by dpoeschl** [comment]
:+1:

**Comment by mavasani** [comment]
:+1:

**Comment by KevinH-MS** [comment]
I will kick off a run with this and let you know by EOD.

**Comment by Pilchie** [comment]
:+1:

**Comment by KevinH-MS** [comment]
With this change total bytes allocated looks good, but there's still more VM usage (~20MB increase).  We should understand this regression before merging.

**Comment by Pilchie** [comment]
Likely just one more 16MB GC segment at some point during the run?

**Comment by heejaechang** [comment]
What is base? with or without the analyzer? More analyzer means more memory. there is no other way around. Can we see how much memory variation we get by having new analyzer?


-          heejae

**Comment by KevinH-MS** [comment]
Yeah, I'm willing to experiment.  Can you suggest another analyzer I could add instead of this one?  (anything hanging out in a pr?)

**Comment by KevinH-MS** [comment]
@Pilchie I thought of that as well, but the last week has taught me to not jump to that conclusion to quickly...it seems that not all analyzers are created equally.

When I initially identified this analyzer as problematic, I was able to repro the 20MB VM change both by:
- Reset'ing to the change immediately before the new analyzer was added (almost a month ago)
- Disabling the analyzer after fast forwarding to the current tip of master

There were many other analyzers added in the interim, and none of them caused the same VM increase.

**Comment by heejaechang** [comment]
How about just adding one of analyzer from roslyn-analyzer or fxcop.


-          heejae

**Comment by CyrusNajmabadi** [comment]
Hey @KevinH-MS Any info on this?  Can you check if you still see this VM increase with this feature enabled?  I'd like to get this checked in soon if possible.

**Comment by KevinH-MS** [comment]
Just getting back from vacation--if we get a VS build later today, I can check against that (assuming there aren't other regressions).

**Comment by KevinH-MS** [comment]
Sorry for the long delay on getting to this, but I've done a run on the current bits, and I think we're O.K. to merge this (it's not triggering any VM regressions at this point) :+1:

**Pull request merged**
