### PR TITLE
use Build as BuildTool even for live error

### PR DESCRIPTION
**Pull request by heejaechang**

### CODE REVIEW

**Comment by heejaechang** [comment]
@srivatsn @jmarolf @tmeschter can you take a look? very simple change

**Comment by jmarolf** [comment]
:+1:

**Comment by tmeschter** [comment]
@heejaechang What does this actually change when you're looking at the Error List?

**Comment by heejaechang** [comment]
All Roslyn compiler stuff whether it is coming from build or live, it will show as “Compiler” in build tool rather than live and compiler.

Error source will distinguish live and compiler.


-          heejae

**Comment by tmeschter** [comment]
LGTM

**Pull request merged**
