### PR TITLE
Properly pass along cancellation token when calling OOP service during FAR.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @heejaechange @dotnet/roslyn-ide

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @dpoeschl @jcouv can you review this simple PR?

**Comment by CyrusNajmabadi** [comment]
@jasonmalinowski @dpoeschl @jcouv can you review this simple PR?

**Comment by CyrusNajmabadi** [comment]
@jcouv Feel free to merge, thanks!

**Comment by CyrusNajmabadi** [comment]
closing

**Comment by jasonmalinowski** [comment]
@CyrusNajmabadi: did you intend to close?

**Comment by CyrusNajmabadi** [comment]
Yes.  If you would like to take this, feel free. I'm just not interested in owning it. Thanks!

**Comment by jinujoseph** [comment]
Blocked on https://github.com/dotnet/roslyn/pull/33960

**Comment by heejaechang** [comment]
@CyrusNajmabadi hey Cyrus. I checked in the StreamJsonRpc 2.0 PR. thank you!

**Comment by CyrusNajmabadi** [comment]
Thanks for letting me know!

**Comment by CyrusNajmabadi** [comment]
@jinujoseph @heejaechang this can go in.  thanks :)

**Comment by jcouv** [comment]
Removed "blocked" tag since https://github.com/dotnet/roslyn/pull/33960 is merged.
Kicked off a retry of remaining CI legs.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
@jcouv This can be merged.  Tnx!

**Comment by jinujoseph** [comment]
Thanks @CyrusNajmabadi for the change 
and thanks @jcouv for taking care of merge

**Pull request merged**
