### PR TITLE
Fix usage of unshared mscorlib ref in numeric IntPtr tests

### PR DESCRIPTION
**Pull request by jcouv**
Fixes https://github.com/dotnet/roslyn/issues/63152

Relates to test plan https://github.com/dotnet/roslyn/issues/60578

FYI @dibarbet

### CODE REVIEW

**Comment by dibarbet** [comment]
@jcouv awesome!  I see this is a draft, but let me know when it is ready I can pull this into my branch and test it

**Comment by jcouv** [comment]
@dibarbet Feel free to try it now. I verified locally by running in VS and also `build.cmd -testCoreClr -testCompilerOnly`.

**Comment by dibarbet** [comment]
@jcouv - tested out on my branch - looks like it fixes the partitioning issue I was having!  I'll wait for this PR to merge in

**Review by dibarbet — APPROVED** [review]

**Review by cston — APPROVED** [review]

**Comment by jcouv** [comment]
FYI @dibarbet, this was merged.

**Comment by dibarbet** [comment]
much thanks for the quick turnaround @jcouv !!

**Pull request merged**
