### PR TITLE
Catch exceptions closer to tree serialization

### LINKED ISSUE #14504: Catch exceptions closer to tree serialization
When SyntaxTree serialization fails the watsons often capture call stacks too far removed from the actual error due to async.   We should capture these failures closer to the actual error.

### PR DESCRIPTION
**Pull request by mattwar**
Fixes #14504 

Adds watson checks when SyntaxTrees are serialized and deserialized. This should help find problems in serialization, so the dumps have better information for tracking down the problems.

@jaredpar @Pilchie @VSadov @jasonmalinowski please review

### CODE REVIEW

**Comment by Pilchie** [comment]
Tagging @CyrusNajmabadi too, since I think he was looking at a related Watson the other day.

**Comment by CyrusNajmabadi** [comment]
👍

**Comment by tmat** [comment]
Where is such exception caught today? Is there an async call on the way that causes us to loose the stack trace? It shouldn't be necessary to report Watsons from each site in the compiler that might throw an exception.

**Comment by mattwar** [comment]
@tmat the exception gets caught by the layers indirectly invoking it.  In one case it was the incremental analyzer.  The exception can be found in the dump, but it is not possible to correlate it back to the tree that was having the problem, or what actual node was being deserialized.  

Another problem is that it is reported via watson as AggregateException in a generic place that could be masking many different problems.

**Comment by tmat** [comment]
This is ok solution if we just want to target one particular site that throws. 
in general though the problem is with async methods catching all exceptions. We address that in many places by adding filters to async methods. Ideally, there would be a way to instruct the compiler to do it for all async methods in given scope (type or assembly).

**Comment by mattwar** [comment]
Sorry, meant to close this one.

**Pull request closed without merging**
